### ISSUE TITLE
https://apt.llvm.org/ flang-20 package for Jammy seems broken

### ISSUE THREAD

**Issue by gaborcsardi** [llvm/llvm-project#113954] opened 2024-10-28 19:26 UTC
I noticed that since about two weeks ago, the Jammy flang-20 package seems to be broken. It only contains symlinks, but not the actual binary:

```
root@0ca605ef6f4f:~# ls -l /usr/lib/llvm-20/bin/flang*
lrwxrwxrwx 1 root root 8 Oct 28 05:38 /usr/lib/llvm-20/bin/flang -> flang-20
lrwxrwxrwx 1 root root 5 Oct 28 05:38 /usr/lib/llvm-20/bin/flang-new -> flang
```

```
root@0ca605ef6f4f:~# dpkg -L flang-20 | xargs ls -ld  | grep bin
drwxr-xr-x 1 root root    12288 Oct 28 16:14 /usr/bin
lrwxrwxrwx 1 root root       22 Oct 28 05:38 /usr/bin/bbc-20 ->../lib/llvm-20/bin/bbc
lrwxrwxrwx 1 root root       33 Oct 28 05:38 /usr/bin/f18-parse-demo-20 -> ../lib/llvm-20/bin/f18-parse-demo
lrwxrwxrwx 1 root root       26 Oct 28 05:38 /usr/bin/fir-opt-20 -> ../lib/llvm-20/bin/fir-opt
lrwxrwxrwx 1 root root       24 Oct 28 05:38 /usr/bin/flang-20 -> ../lib/llvm-20/bin/flang
lrwxrwxrwx 1 root root       28 Oct 28 05:38 /usr/bin/flang-new-20 -> ../lib/llvm-20/bin/flang-new
lrwxrwxrwx 1 root root       22 Oct 28 05:38 /usr/bin/tco-20 -> ../lib/llvm-20/bin/tco
drwxr-xr-x 1 root root    12288 Oct 28 16:14 /usr/lib/llvm-20/bin
-rwxr-xr-x 1 root root 41232072 Oct 28 05:38 /usr/lib/llvm-20/bin/bbc
-rwxr-xr-x 1 root root  5024856 Oct 28 05:38 /usr/lib/llvm-20/bin/f18-parse-demo
-rwxr-xr-x 1 root root 23093696 Oct 28 05:38 /usr/lib/llvm-20/bin/fir-opt
lrwxrwxrwx 1 root root        8 Oct 28 05:38 /usr/lib/llvm-20/bin/flang -> flang-20
lrwxrwxrwx 1 root root        5 Oct 28 05:38 /usr/lib/llvm-20/bin/flang-new -> flang
-rwxr-xr-x 1 root root 20907592 Oct 28 05:38 /usr/lib/llvm-20/bin/tco
```

Am I missing something here?

**Comment by edoapra** [comment] 2024-10-31 06:29
Duplicate of https://github.com/llvm/llvm-project/issues/112778

**Closed** 2024-10-31 14:30 UTC
Labels: duplicate, packaging, platform:linux, flang
