### ISSUE TITLE
Deprecated warning is emitted twice

### ISSUE THREAD

**Issue by aelovikov-intel** [llvm/llvm-project#108878] opened 2024-09-16 20:31 UTC
For
```
template <typename T>
struct ptr {};

struct sub_group {
    template <typename T>
    [[deprecated("use new interface")]]
    auto load(T *) {}
};

auto foo(sub_group sg, int *p) { return sg.load(p); }
```

the warning is emitted twice (https://godbolt.org/z/PbzPMfhh5):
```
<source>:10:44: warning: 'load' is deprecated: use new interface [-Wdeprecated-declarations]
   10 | auto foo(sub_group sg, int *p) { return sg.load(p); }
      |                                            ^
<source>:7:10: note: 'load' has been explicitly marked deprecated here
    7 |     auto load(T *) {}
      |          ^
<source>:10:44: warning: 'load<int>' is deprecated: use new interface [-Wdeprecated-declarations]
   10 | auto foo(sub_group sg, int *p) { return sg.load(p); }
      |                                            ^
<source>:6:7: note: 'load<int>' has been explicitly marked deprecated here
    6 |     [[deprecated("use new interface")]]
      |       ^
2 warnings generated.
```

**Comment by shafik** [comment] 2024-09-17 01:04
This unfortunately looks like a duplicate of: https://github.com/llvm/llvm-project/issues/15612  which was opened in 2013 😱

**Closed by shafik** 2024-09-17 01:04 UTC
Labels: clang:diagnostics
