### ISSUE TITLE
llvm-exegesis does not work for one snippet with RSP defined

### ISSUE THREAD

**Issue by 9Tempest** [llvm/llvm-project#72193] opened 2023-11-14 02:29 UTC
```
# LLVM-EXEGESIS-MEM-DEF test1 4096 2147483647
# LLVM-EXEGESIS-MEM-MAP test1 1048576
# LLVM-EXEGESIS-DEFREG RAX 100000
# LLVM-EXEGESIS-DEFREG RBX 100000
# LLVM-EXEGESIS-DEFREG RCX 100000
# LLVM-EXEGESIS-DEFREG RDX 100000
# LLVM-EXEGESIS-DEFREG RSI 100000
# LLVM-EXEGESIS-DEFREG RDI 100000
# LLVM-EXEGESIS-DEFREG RBP 100000
# LLVM-EXEGESIS-DEFREG RSP 100000
# LLVM-EXEGESIS-DEFREG R8 100000
# LLVM-EXEGESIS-DEFREG R9 100000
# LLVM-EXEGESIS-DEFREG R10 100000
# LLVM-EXEGESIS-DEFREG R11 100000
# LLVM-EXEGESIS-DEFREG R12 100000
# LLVM-EXEGESIS-DEFREG R13 100000
# LLVM-EXEGESIS-DEFREG R14 100000

movq %r14, (%rax)
```
This code snippet is tested by the following command
```
llvm-exegesis --mode=inverse_throughput -execution-mode=subprocess  --snippets-file=llvm-exe-test/1.test
```
Version of llvm-exegsis is based on SHA https://github.com/llvm/llvm-project/commit/2a1f1b5fde0a2e03f94fa2cb5c7765d405fda0de

Output is
```
---
mode:            inverse_throughput
key:
  instructions:
    - 'MOVDQUrm XMM1 RDI i_0x1 %noreg i_0x0 %noreg'
    - 'MOVDQUrm XMM0 RSI i_0x1 %noreg i_0x0 %noreg'
    - 'PCMPEQBrr XMM0 XMM0 XMM1'
    - 'PMINUBrr XMM0 XMM0 XMM1'
    - 'PXORrr XMM1 XMM1 XMM1'
    - 'PCMPEQBrr XMM0 XMM0 XMM1'
    - 'PMOVMSKBrr EAX XMM0'
    - 'TEST64rr RAX RAX'
  config:          ''
  register_initial_values:
    - 'RAX=0x10000'
    - 'RBX=0x10000'
    - 'RCX=0x10000'
    - 'RDX=0x10000'
    - 'RSI=0x10000'
    - 'RDI=0x10000'
    - 'RBP=0x10000'
    - 'RSP=0x10000'
    - 'R8=0x10000'
    - 'R9=0x10000'
    - 'R10=0x10000'
    - 'R11=0x10000'
    - 'R12=0x10000'
    - 'R13=0x10000'
    - 'R14=0x10000'
    - 'R15=0x10000'
    - 'XMM0=0x10000'
    - 'XMM1=0x10000'
    - 'XMM2=0x10000'
    - 'XMM3=0x10000'
    - 'XMM4=0x10000'
    - 'XMM5=0x10000'
    - 'XMM6=0x10000'
    - 'XMM7=0x10000'
    - 'XMM8=0x10000'
    - 'XMM9=0x10000'
    - 'XMM10=0x10000'
    - 'XMM11=0x10000'
    - 'XMM12=0x10000'
    - 'XMM13=0x10000'
    - 'XMM14=0x10000'
    - 'XMM15=0x10000'
cpu_name:        skylake-avx512
llvm_triple:     x86_64-unknown-linux-gnu
num_repetitions: 10000
measurements:    []
error:           'The benchmarking subprocess sent unexpected signal: Segmentation fault'
info:            ''
assembled_snippet: 554157415641554154534989FC4989F548BF0000000000000000488D350000000048C1EE0C48C1E60C4881EE0010000048B80B000000000000000F054C8D05000000004C89E74C01C748C1EF0C48C1E70C4881C70010000048BE00F0FFFFFF7F00004829FE48B80B000000000000000F0548BF00E0FFFFFF7F000048BE001000000000000048BA030000000000000049BA01001000000000004D89E849B9000000000000000048B809000000000000000F0548BF000001000000000048BE001000000000000048BA030000000000000049BA010010000000000049B804E0FFFFFF7F0000458B0049B9000000000000000048B809000000000000000F0548BC00F0FFFFFF7F000048B8000001000000000048BB000001000000000048B9000001000000000048BA000001000000000048BE000001000000000048BF000001000000000048BD000001000000000048BC000001000000000049B8000001000000000049B9000001000000000049BA000001000000000049BB000001000000000049BC000001000000000049BD000001000000000049BE000001000000000049BF00000100000000004883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F04244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F0C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F14244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F1C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F24244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F2C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F34244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062F17E086F3C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F04244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F0C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F14244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F1C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F24244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F2C244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F34244883C4104883EC10C7042400000100C744240400000000C744240800000000C744240C0000000062717E086F3C244883C41050575648BF00E0FFFFFF7F00008B3F48BE032400000000000048B810000000000000000F055E5858F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C0F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C0F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C0F30F6F0FF30F6F06660F74C1660FDAC1660FEFC9660F74C1660FD7C04885C048BF00E0FFFFFF7F00008B3F48BE012400000000000048B810000000000000000F0548BF000000000000000048B83C000000000000000F055B415C415D415E415F5DC3
...
```

Interestingly, if you remove the line `# LLVM-EXEGESIS-DEFREG RSP 100000`, `llvm-exegesis` works correctly on my machine, generated the output
```
---
mode:            inverse_throughput
key:
  instructions:
    - 'MOV64mr RAX i_0x1 %noreg i_0x0 %noreg R14'
  config:          ''
  register_initial_values:
    - 'RAX=0x100000'
    - 'RBX=0x100000'
    - 'RCX=0x100000'
    - 'RDX=0x100000'
    - 'RSI=0x100000'
    - 'RDI=0x100000'
    - 'RBP=0x100000'
    - 'R8=0x100000'
    - 'R9=0x100000'
    - 'R10=0x100000'
    - 'R11=0x100000'
    - 'R12=0x100000'
    - 'R13=0x100000'
    - 'R14=0x100000'
cpu_name:        skylake-avx512
llvm_triple:     x86_64-unknown-linux-gnu
num_repetitions: 10000
measurements:
  - { key: inverse_throughput, value: 1.1839, per_snippet_value: 1.1839 }
error:           ''
info:            ''
assembled_snippet: 55415641554154534989FC4989F548BF0000000000000000488D350000000048C1EE0C48C1E60C4881EE0010000048B80B000000000000000F054C8D05000000004C89E74C01C748C1EF0C48C1E70C4881C70010000048BE00F0FFFFFF7F00004829FE48B80B000000000000000F0548BF00E0FFFFFF7F000048BE001000000000000048BA030000000000000049BA01001000000000004D89E849B9000000000000000048B809000000000000000F0548BF000010000000000048BE001000000000000048BA030000000000000049BA010010000000000049B804E0FFFFFF7F0000458B0049B9000000000000000048B809000000000000000F0548BC00F0FFFFFF7F000048B8000010000000000048BB000010000000000048B9000010000000000048BA000010000000000048BE000010000000000048BF000010000000000048BD000010000000000049B8000010000000000049B9000010000000000049BA000010000000000049BB000010000000000049BC000010000000000049BD000010000000000049BE000010000000000050575648BF00E0FFFFFF7F00008B3F48BE032400000000000048B810000000000000000F055E58584C89304C89304C89304C893048BF00E0FFFFFF7F00008B3F48BE012400000000000048B810000000000000000F0548BF000000000000000048B83C000000000000000F055B415C415D415E5DC3
...
```

**Comment by boomanaiden154** [comment] 2023-11-15 20:33
Can confirm that this is an issue, even with the following more minimal test case:
```asm
# LLVM-EXEGESIS-MEM-DEF test1 4096 2147483647
# LLVM-EXEGESIS-MEM-MAP test1 1048576
# LLVM-EXEGESIS-DEFREG RAX 100000
# LLVM-EXEGESIS-DEFREG R14 100000
# LLVM-EXEGESIS-DEFREG RSP 100000

movq %r14, (%rax)
```

I originally thought it would've been an issue with the function that defines the registers loading in vector registers from the stack without saving the value of `RSP`, but that's not what's happening here as there aren't any vector registers and that would be fixed by loading in `RSP` at the end, which still isn't happening here. Will do some more investigation.

**Comment by boomanaiden154** [comment] 2023-11-15 21:04
Figured out what the issue is. When setting up the registers and making an `ioctl` syscall to enable the performance counter, we run the following:
```asm
# Register setup
      f9: 48 bc 00 f0 ff ff ff 7f 00 00 movabsq $0x7ffffffff000, %rsp   # imm = 0x7FFFFFFFF000
     103: 48 b8 00 00 10 00 00 00 00 00 movabsq $0x100000, %rax         # imm = 0x100000
     10d: 49 be 00 00 10 00 00 00 00 00 movabsq $0x100000, %r14         # imm = 0x100000
     117: 48 bc 00 00 10 00 00 00 00 00 movabsq $0x100000, %rsp         # imm = 0x100000
# start performance counter with ioctl
# Saving registers
     121: 50                            pushq   %rax
     122: 57                            pushq   %rdi
     123: 56                            pushq   %rsi
# Actually calling ioctl
     124: 48 bf 00 e0 ff ff ff 7f 00 00 movabsq $0x7fffffffe000, %rdi   # imm = 0x7FFFFFFFE000
     12e: 8b 3f                         movl    (%rdi), %edi
     130: 48 be 03 24 00 00 00 00 00 00 movabsq $0x2403, %rsi           # imm = 0x2403
     13a: 48 b8 10 00 00 00 00 00 00 00 movabsq $0x10, %rax
     144: 0f 05                         syscall
```
The issue here is that we're trying to save registers to the stack after we've changed `%rsp` from what we're expecting. It segfaults while trying to push things to the stack with the stack moving downward. The solution is either to not save the registers used in the ioctl call on the stack or to set `%rsp` after making the call. Will post a patch soonish.

**Closed** 2023-11-29 09:40 UTC
Labels: tools:llvm-exegesis, confirmed
