### ISSUE TITLE
Good first issue bot instructs to create a review on phabricator

### ISSUE THREAD

**Issue by cor3ntin** [llvm/llvm-project#65890] opened 2023-09-10 11:11 UTC
When an issue is tagged 'good first issue', the automatic comment bot instruct people to create a review on phabricator.
This should be updated

Ex https://github.com/llvm/llvm-project/issues/65858#issuecomment-1712784751

**Comment by Endilll** [comment] 2023-09-10 11:39
The first step that message suggests is to assign the issue to yourself, which target audience of that message cannot do.

**Comment by tbaederr** [comment] 2023-09-10 11:55
This is easy to fix, but don't create a review on phabricator!

**Comment by Da-Viper** [comment] 2023-09-10 21:03
@tbaederr I would like to work on this issue 

The fix would essentially to remove item six and add add a like to the repo pull request. Something like 

6. Submit a patch to github [here](https://github.com/llvm/llvm-project/pulls).

**Comment by Endilll** [comment] 2023-09-10 21:07
Yeah, and as you can see for yourself, we need to do something about the first step.
At least we should say something along the lines "ask in the comments to assign the issue to yourself".

**Comment by Da-Viper** [comment] 2023-09-10 21:22
> Yeah, and as you can see for yourself, we need to do something about the first step. At least we should say something along the lines "ask in the comments to assign the issue to yourself".

Something in the lines of 

Hi!

This issue may be a good introductory issue for people new to working on LLVM. If you would like to work on this issue, your first steps are:

1. In the comment of the issue, request for it to be assigned to you.
2. Fix the issue locally.
3. [Run the test suite](https://llvm.org/docs/TestingGuide.html#unit-and-regression-tests) locally.
   3.1) Remember that the subdirectories under test/ create fine-grained testing targets, so you can
    e.g. use make check-clang-ast to only run Clang's AST tests.
4. Create a git commit
5. Run [git clang-format HEAD~1](https://clang.llvm.org/docs/ClangFormat.html#git-integration) to format your changes.
6. Create a pull request 
    6.1) Detailed instructions can be found [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?platform=mac).

If you have any further questions about this issue, don't hesitate to ask via a comment on this Github issue.

@llvm/issue-subscribers-good-first-issue

**Comment by Endilll** [comment] 2023-09-10 21:25
Yes. I think we can discuss the rest during PR review.

**Comment by xgupta** [comment] 2023-10-17 17:17
The GitHub bot comment is not working 

In this issue. good-first-issue didn't comment the right thing  - https://github.com/llvm/llvm-project/issues/68492, might be conflicting with other automation.

**Comment by Da-Viper** [comment] 2023-10-17 17:24
@xgupta I am assuming it is from somewhere else because this hasn't been merged

**Comment by xgupta** [comment] 2023-10-18 04:27
Yes, it is a blocker for this task which needs to be fixed first.

**Closed** 2023-11-26 15:53 UTC
Labels: infrastructure, good first issue, github-prs
