### ISSUE TITLE
[clangd] Find references on constructor should also show call sites of make_unique and make_shared that call it

### ISSUE THREAD

**Issue by RedBeard0531** [llvm/llvm-project#53755] opened 2022-02-11 12:09 UTC
When trying to find callers of a constructor (eg to see if it is dead or nearly so) I wish it would also show any callers of `std::make_unique` and `std::make_shared` that end up selecting that constructor, since for some types all construction goes through them.

Those are the easy cases and doing just those two would probably cover 80% or more, but it would be great if it could also do something similar for the wide variety of `emplace()` methods. They are trickier though. Maybe it could be solved with some sort of attribute like `[[clangd::factory_for(Type, args...)]]`? But ideally it would still work for `std::make_unique` and `std::make_shared` even without the attributes because it is common to use clangd with other stdlibs than libc++.

**Comment by upsj** [comment] 2022-05-08 16:48
Related: https://github.com/clangd/clangd/issues/716

**Comment by HighCommander4** [comment] 2023-12-20 19:54
I'm going to close this as a duplicate of https://github.com/clangd/clangd/issues/716 to keep the dicussion in one place. I mentioned your suggestion of an attribute there, which is pretty interesting.

**Comment by HighCommander4** [comment] 2023-12-20 19:54
Duplicate of https://github.com/clangd/clangd/issues/716

**Closed by HighCommander4** 2023-12-20 19:54 UTC
Labels: clang:tooling
