### ISSUE TITLE
Clang accepts the undefined behavior operation in a constant expression

### ISSUE THREAD

**Issue by xmh0511** [llvm/llvm-project#56528] opened 2022-07-14 12:13 UTC
````cpp
enum A {a = 0};
constexpr A e = static_cast<A>(1024);
````
According to [expr.static.cast p10
> If the enumeration type does not have a fixed underlying type, the value is unchanged if the original value is within the range of the enumeration values ([dcl.enum]), and **otherwise, the behavior is undefined**.

[dcl.enum] p8 defines the range of the enumeration values, which says
> Otherwise, the values of the enumeration are the values representable by a hypothetical integer type with **minimal** width M such that all enumerators can be represented.  

In this case, it is sufficient to represent the value `0` of the unique enumerator if `M` is `1`. Apparently, the value `1024` cannot be representable in the hypothetical integer type with **minimal** width M. So, the full-expression of the initialization is not a constant expression since the violation of [expr.const] p5
> an operation that would have undefined behavior as specified in [intro] through [cpp];

However, Clang accepts this example without any diagnosis.

**Comment by AaronBallman** [comment] 2022-07-14 14:26
Agreed, closing this as a duplicate of https://github.com/llvm/llvm-project/issues/50055.

**Closed by AaronBallman** 2022-07-14 14:26 UTC
Labels: c++20, clang:frontend, clang:diagnostics
