### ISSUE TITLE
Wrong canonicalization of `select` for a vector of poisonous values

### ISSUE THREAD

**Issue by bongjunj** [llvm/llvm-project#113515] opened 2024-10-24 02:49 UTC
https://github.com/llvm/llvm-project/blob/33363521ca24f912cc25530f6cecbca53acce8a3/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp#L1043-L1049

Alive2 report: https://alive2.llvm.org/ce/z/fqZFy9

```llvm
----------------------------------------
define <2 x i32> @uadd_sat_not_ugt_commute_add.2(<2 x i32> %x, <2 x i32> %yp) {
#0:
  %y = sdiv <2 x i32> %yp, { 2442, 4242 }
  %notx = xor <2 x i32> %x, { 4294967295, poison }
  %a = add <2 x i32> %y, %notx
  %c = icmp ugt <2 x i32> %y, %x
  %r = select <2 x i1> %c, <2 x i32> { 4294967295, 4294967295 }, <2 x i32> %a
  ret <2 x i32> %r
}
=>
define <2 x i32> @uadd_sat_not_ugt_commute_add.2(<2 x i32> %x, <2 x i32> %yp) {
#0:
  %y = sdiv <2 x i32> %yp, { 2442, 4242 }
  %notx = xor <2 x i32> %x, { 4294967295, poison }
  %r = uadd_sat <2 x i32> %y, %notx
  ret <2 x i32> %r
}
Transformation doesn't verify!

ERROR: Target is more poisonous than source

Example:
<2 x i32> %x = < #x00000000 (0), #x00000000 (0) >
<2 x i32> %yp = < #x00000000 (0), #x00002041 (8257) >

Source:
<2 x i32> %y = < #x00000000 (0), #x00000001 (1) >
<2 x i32> %notx = < #xffffffff (4294967295, -1), poison >
<2 x i32> %a = < #xffffffff (4294967295, -1), poison >
<2 x i1> %c = < #x0 (0), #x1 (1) >
<2 x i32> %r = < #xffffffff (4294967295, -1), #xffffffff (4294967295, -1) >

Target:
<2 x i32> %y = < #x00000000 (0), #x00000001 (1) >
<2 x i32> %notx = < #xffffffff (4294967295, -1), poison >
<2 x i32> %r = < #xffffffff (4294967295, -1), poison >
Source value: < #xffffffff (4294967295, -1), #xffffffff (4294967295, -1) >
Target value: < #xffffffff (4294967295, -1), poison >

Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

**Comment by dtcxzyw** [comment] 2024-10-31 01:44
This test case is a duplicate of the one in https://github.com/llvm/llvm-project/issues/113869.

**Closed** 2024-11-07 11:59 UTC
Labels: miscompilation, llvm:instcombine
