### ISSUE TITLE
[clangd][feature request] call hierarchy on data members

### ISSUE THREAD

**Issue by timon-ul** [llvm/llvm-project#97825] opened 2024-07-05 13:07 UTC
We are trying to establish clangd in our company, but we get a lot of feedback from developers that they change back to the eclipse indexer, because of clangd's inability to show a call hierarchy on data members. 
As a simple example for the behaviour, consider the following simple class:
```
class C
{
  void f()
  {
    number = 0;
  }

  int number = 0;
};
```
Now if I request a call hierarchy on the variable "number" I want it to show "f()" as caller.

**Comment by HighCommander4** [comment] 2024-07-08 04:38
Duplicate of https://github.com/clangd/clangd/issues/1308

**Closed by HighCommander4** 2024-07-08 04:38 UTC
Labels: enhancement, clangd
