### ISSUE TITLE
Wrong code generation with inline assembly

### ISSUE THREAD

**Issue by royger** [llvm/llvm-project#82598] opened 2024-02-22 08:16 UTC
Hello,

Given the following example:
```
unsigned int func(uint8_t t)
{
    return t;
}

static void bar(uint8_t b)
{
    int ret_;
    register uint8_t di asm("rdi") = b;
    register unsigned long si asm("rsi");
    register unsigned long dx asm("rdx");
    register unsigned long cx asm("rcx");
    register unsigned long r8 asm("r8");
    register unsigned long r9 asm("r9");
    register unsigned long r10 asm("r10");
    register unsigned long r11 asm("r11");

    asm volatile ( "call %c[addr]"
                   : "+r" (di), "=r" (si), "=r" (dx),
                     "=r" (cx), "=r" (r8), "=r" (r9),
                     "=r" (r10), "=r" (r11), "=a" (ret_)
                   : [addr] "i" (&(func)), "g" (func)
                   : "memory" );
}

void foo(unsigned int a)
{
    bar(a);
}
```
clang will generate the following assembly with -O2:
```
func:                                   # @func
        movl    %edi, %eax
        retq
foo:                                    # @foo
        callq   func
        retq
```
Note how the cast (truncation) to uint8_t is not done anywhere (either in the caller or the callee), and hence the full value of 'a' gets passed into 'func()'. Gcc however explicitly uses movzbl:
```
func:
        movzbl  %dil, %eax
        ret
foo:
        call func
        ret
```
This has been raised with the psABI group at:
https://groups.google.com/g/x86-64-abi/c/h7FFh30oS3s
And it seems like the consensus is that the callee shouldn't assume registers to be zero-extended for types < 32 bits.
Godbolt link with the example: https://godbolt.org/z/qdodj64hK

Thanks, Roger.

**Comment by nickdesaulniers** [comment] 2024-02-22 16:33
https://groups.google.com/g/x86-64-abi/c/h7FFh30oS3s links to https://reviews.llvm.org/D72742 which links to https://github.com/llvm/llvm-project/issues/43573. Closing this as a duplicate of that, please subscribe to the discussion there. (Thanks for the report though)!

**Closed by nickdesaulniers** 2024-02-22 16:33 UTC
Labels: duplicate, clang:codegen, ABI

**Comment by andyhhp** [comment] 2024-02-23 01:32
@nickdesaulniers I don't think closing out as a dup of that is helpful.  Every other thread/PR on this subject talks in terms of "be more like GCC", which is misleading and masking the severity.

This started from a real malfunction reported in FreeBSD.  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277200 

Clang has managed to produce a build of Xen where neither the caller nor the callee zero-extended the register containing a `uint8_t`, and this resulted in an out-of-bounds write in the form of an atomic bit-set.

The ABI-list thread has a different example of this going wrong with plain variadic functions and no inline asm.

**Comment by jyknight** [comment] 2024-02-26 21:00
The register that's passed to the inline-asm is actually `dil`, not `rdx`, because you asked for an 8-bit register. (This is consistent with GCC). However, the asm code you generate only implicitly uses the register, so you can't obviously see that in your example. But, you can check with e.g.
```
static void bar(uint8_t b)
{
    register uint8_t di asm("rdi") = b;
    asm volatile ("mov %0, %0" : "+r" (di));
}
```

Since only `dil` is used, the upper bits of the register are irrelevant, so the truncation in "foo" from `unsigned int` to `uint8_t` can be omitted. That's all fine so far -- if your inline-asm legitimately only used `dil`, and not the rest of `edi`.

However, with `func` compiled by Clang, it assumes the argument is zero-extended up to 32-bits, and so your asm call _does_ effectively use the rest of `edi`. The most straightforward fix would simply be to use an `unsigned int` instead of a `uint8_t` operand on your inline-asm, which will ensure that it gets zero-extended before the call.

Of course, you _shouldn't_ need to make that change, except to workaround Clang's incorrect interpretation of the x86 psABI specification -- which is why this is truly a dup of the other bug.
