### ISSUE TITLE
[clang-format] `AlignOperands: false` Still aligns the stream operator

### ISSUE THREAD

**Issue by AidanWelch** [llvm/llvm-project#65008] opened 2023-08-26 11:03 UTC
Expected:
```cpp
std::cout << 1 << 1 << 1 << 1 << 1 << 1 <<
    1 << 1 << 1 << 1 << 1 << 1;
```
Result:
```cpp
std::cout << 1 << 1 << 1 << 1 << 1 << 1
          << 1 << 1 << 1 << 1 << 1 << 1;
```
[This has persisted for over 7 years](https://stackoverflow.com/questions/38699555/clang-format-stream-output)

**Comment by PiotrZSL** [comment] 2023-08-26 11:17
This has nothing to do with clang-tidy.

**Comment by AidanWelch** [comment] 2023-08-26 11:32
> This has nothing to do with clang-tidy.

Oh sorry that was a typo I thought I had written clang-format

**Comment by owenca** [comment] 2023-10-18 22:49
Duplicate of #67897

**Closed by owenca** 2023-10-18 22:49 UTC
Labels: duplicate, clang-format

**Comment by AidanWelch** [comment] 2023-10-18 22:53
Isn't that issue a duplicate of this rather than the other way around?

**Comment by owenca** [comment] 2023-10-18 23:46
They are duplicate of each other, but I left the other open because it got more info and referenced two more issues.
