### ISSUE TITLE
type-constraint masks friendship

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#61823] opened 2023-03-29 22:54 UTC
GCC test `concepts-friend3.C` fails. Note that despite being isomorphic, `f` is diagnosed, while `g` is not.
```cpp
// RUN: %clang_cc1 -std=c++20 -fsyntax-only -verify %s

template <class T> concept True = true;

template <True U> void f() { ++U::x; }
template <class U> void g() requires True<U> { ++U::x; }

template <class V> class C
{
  static int x;

  template <True U> friend void f();
  template <class U> friend void g() requires True<U>;
};

int main()
{
  f<C<int>>();
  g<C<int>>();
}
```
Diagnostic:
```console
<source>:5:35: error: 'x' is a private member of 'C<int>'
template <True U> void f() { ++U::x; }
                                  ^
<source>:19:3: note: in instantiation of function template specialization 'f<C<int>>' requested here
  f<C<int>>();
  ^
<source>:10:14: note: implicitly declared private here
  static int x;
             ^
```

**Comment by shafik** [comment] 2023-03-30 03:52
Confirmed

**Comment by usx95** [comment] 2023-03-30 09:06
This is dupe of https://github.com/llvm/llvm-project/issues/58859

**Closed by usx95** 2023-03-30 09:06 UTC
Labels: c++20, clang:frontend, rejects-valid, concepts, confirmed
