### ISSUE TITLE
Clang crash in SemaInit.cpp when printing a diagnostic for an uninitialized reference member

### ISSUE THREAD

**Issue by miyuki** [llvm/llvm-project#53046] opened 2022-01-06 17:28 UTC
Clang crashes while trying to compile the following ill-formed code:

```
struct S1 {
  int a;
  int &b;
};

struct S2 {
  S1 x;
};

const S2 s2{1};
```

Command line:
```
$ clang -fsyntax-only -std=c++11 test.cc
```

Godbolt reproducer: https://godbolt.org/z/84Tasfq3q

```
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -g -o /app/output.s -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++11 <source>
1.	<source>:10:15: current parser token ';'
 #0 0x000055679403f0bf PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055679403cee0 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a3cee0)
 #2 0x0000556793f75728 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f4904ce93c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x0000556796d4d178 clang::Stmt::getSourceRange() const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x674d178)
 #5 0x000055679647eb01 (anonymous namespace)::InitListChecker::FillInEmptyInitForField(unsigned int, clang::FieldDecl*, clang::InitializedEntity const&, clang::InitListExpr*, bool&, bool) SemaInit.cpp:0:0
 #6 0x000055679647efd8 (anonymous namespace)::InitListChecker::FillInEmptyInitializations(clang::InitializedEntity const&, clang::InitListExpr*, bool&, clang::InitListExpr*, unsigned int, bool) SemaInit.cpp:0:0
 #7 0x000055679647e9e4 (anonymous namespace)::InitListChecker::FillInEmptyInitForField(unsigned int, clang::FieldDecl*, clang::InitializedEntity const&, clang::InitListExpr*, bool&, bool) SemaInit.cpp:0:0
 #8 0x000055679647efd8 (anonymous namespace)::InitListChecker::FillInEmptyInitializations(clang::InitializedEntity const&, clang::InitListExpr*, bool&, clang::InitListExpr*, unsigned int, bool) SemaInit.cpp:0:0
 #9 0x0000556796474b8d (anonymous namespace)::InitListChecker::InitListChecker(clang::Sema&, clang::InitializedEntity const&, clang::InitListExpr*, clang::QualType&, bool, bool, bool) SemaInit.cpp:0:0
#10 0x00005567964775b0 diagnoseListInit(clang::Sema&, clang::InitializedEntity const&, clang::InitListExpr*) SemaInit.cpp:0:0
#11 0x0000556796477a54 clang::InitializationSequence::Diagnose(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::ArrayRef<clang::Expr*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e77a54)
#12 0x000055679647a175 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e7a175)
#13 0x00005567961aacbe clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5baacbe)
#14 0x0000556795f6064a clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x596064a)
#15 0x0000556795f70037 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5970037)
#16 0x0000556795f4a2d9 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x594a2d9)
#17 0x0000556795f4aa21 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.280) Parser.cpp:0:0
#18 0x0000556795f4ac10 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x594ac10)
#19 0x0000556795f4b869 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x594b869)
#20 0x0000556795f419d9 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x59419d9)
#21 0x000055679505bbb8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a5bbb8)
#22 0x00005567949f65f1 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43f65f1)
#23 0x00005567949921ea clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43921ea)
#24 0x0000556794ac5b83 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44c5b83)
#25 0x00005567919df27c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x13df27c)
#26 0x00005567919da619 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#27 0x0000556794838145 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#28 0x0000556793f75d13 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3975d13)
#29 0x000055679483a4c6 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x423a4c6)
#30 0x000055679480f84a clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x420f84a)
#31 0x00005567948104df clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42104df)
#32 0x000055679481878a clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x421878a)
#33 0x0000556791903c8f main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1303c8f)
#34 0x00007f49047990b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#35 0x00005567919da18a _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x13da18a)
clang-14: error: clang frontend command failed with exit code 139 (use -v to see invocation)
```

**Comment by miyuki** [comment] 2022-01-06 18:29
The crash is caused by a bug in `clang/lib/Sema/SemaInit.cpp` function `InitListChecker::FillInEmptyInitForField`:
```C++
if (Field->getType()->isReferenceType()) {
  if (!VerifyOnly) {
    // C++ [dcl.init.aggr]p9:
    //   If an incomplete or empty initializer-list leaves a
    //   member of reference type uninitialized, the program is
    //   ill-formed.
    SemaRef.Diag(Loc, diag::err_init_reference_member_uninitialized)
      << Field->getType()
      << ILE->getSyntacticForm()->getSourceRange();
    SemaRef.Diag(Field->getLocation(),
                 diag::note_uninit_reference_member);
  }
  hadError = true;
  return;
}
```
`LE->getSyntacticForm()` returns a null pointer, an attempt to dereference it causes a segmentation fault.

**Comment by shafik** [comment] 2023-05-02 19:26
No longer reproduces on trunk: https://godbolt.org/z/33G5q3Y7K

Duplicate of https://github.com/llvm/llvm-project/issues/58028

**Closed by shafik** 2023-05-02 19:26 UTC
Labels: clang:frontend, crash-on-invalid
