### ISSUE TITLE
clang coverage reports zero count on line after an assert

### ISSUE THREAD

**Issue by hanickadot** [llvm/llvm-project#57388] opened 2022-08-26 15:13 UTC
For code:

```c++
#include <cstdio>
#include <cassert>

int main(int argc, char ** argv) {
	puts("hello");
	assert(argc>=1);
	puts("ciau");
	return 0;
}
```

The line after `assert(argc>=1);` is marked as not covered:

![Screenshot 2022-08-26 at 17 10 23](https://user-images.githubusercontent.com/6557263/186936402-122bde9c-e814-481f-8250-e0f0e7b921ca.png)

When I expanded the `assert` macro to look what's going on inside I got:

```c++
#include <cstdio>
#include <stdlib.h>

#define assert(e)  \
    ((void) ((e) ? ((void)0) : __assert (#e, __FILE_NAME__, __LINE__)))
#define __assert(e, file, line) \
    ((void)printf ("%s:%d: failed assertion `%s'\n", file, line, e), abort())

int main(int argc, char ** argv) {
	puts("hello");
	assert(argc>=1);
	puts("ciau");
	return 0;
}
```

The line after the assert is still not matched...

![Screenshot 2022-08-26 at 17 12 13](https://user-images.githubusercontent.com/6557263/186936831-847f6b3f-4da2-42f9-ba0c-f7894874d700.png)

expected behaviour:

1) assert is marked as covered (and not expanded so the failure is not seen)
2) line after the assert is also marked as covered

**Comment by hanickadot** [comment] 2022-08-26 15:14
tried with 14 and 15rc3

**Comment by zmodem** [comment] 2023-02-14 12:50
Duplicate of #59030

**Closed** 2023-02-14 15:05 UTC
Labels: duplicate, coverage
