### ISSUE TITLE
Inconsistent spacing when passing C array by const reference

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#61786] opened 2023-03-29 08:28 UTC
Hi!

We are bumping clang-format from:
`15_15~%2b%2b20220316052642%2b11a12544b5fd-1~exp1~20220316172739.191`
to:
`17_17~%2b%2b20230328053227%2b498e1506981f-1~exp1~20230328173331.583`

And the following example code gets inconsistent spacing when passing C arrays by const reference:

```cpp
#include <cstddef>

template <typename T, std::size_t n>
void foo(T const (&array)[n]);

template <typename T>
struct Foo
{};

template <typename T, std::size_t n>
struct Foo<T const [n]>
{
    static constexpr void foo (T const (&array)[n]);
};
```

Running clang-format with default settings leads to:

```cpp
#include <cstddef>

template <typename T, std::size_t n> void foo(T const (&array)[n]);

template <typename T> struct Foo {};

template <typename T, std::size_t n>
struct Foo<T const [n]> { static constexpr void foo(T const(&array)[n]); };
```

Note the inconsistency between the free-standing function, and the member function:

```cpp
void foo(T const (&array)[n]);
void foo(T const(&array)[n]);
```

This does not happen if I apply this change:

```cpp
-struct Foo<T const [n]>
+struct Foo<T [n]>
```

**Comment by rymiel** [comment] 2023-03-29 17:11
the `[` in `struct Foo<T const [n]>` is annotated as a `LambdaLSquare` (!!), meaning the `{` belonging to the struct is annotated as `LambdaLBrace` (!!), and the body of the struct is formatted as a lambda.

With the correct options, you could probably get invalid-code-generation out of this, I couldn't with just some simple changes, but this seems like pretty bad mis-annotation.

**Comment by rymiel** [comment] 2023-03-30 09:23
Could you please clarify how this is a regression? The output seems same on all versions of clang-format I could get my hands on, where does it regress?

**Comment by carlosgalvezp** [comment] 2023-03-30 10:03
We had correct behavior on `15_15~%2b%2b20220316052642%2b11a12544b5fd-1~exp1~20220316172739.191`, but it now incorrect on trunk. Would that be considered as regression?

**Comment by rymiel** [comment] 2023-03-30 11:22
Okay, I was confused because this was fixed and then reverted within the clang-format-15 development cycle, the commit you used just happened to be after it was fixed, but before it was reverted.

This effectively makes this issue a duplicate of https://github.com/llvm/llvm-project/issues/54245

**Closed by rymiel** 2023-03-30 11:22 UTC
Labels: clang-format, regression

**Comment by carlosgalvezp** [comment] 2023-03-30 11:46
Oh, I wasn't aware it was reverted, too bad! I'll wait for a fix then :)
