### ISSUE TITLE
float3 a = {1, 2, 3, }; // line breaks if initializer list ends with comma

### ISSUE THREAD

**Issue by mplexor** [llvm/llvm-project#53181] opened 2022-01-13 15:45 UTC
```
float3 a = {1, 2, 3 }; // ok
float3 a = {1, 2, 3, }; // line breaks

```

**Comment by mkurdej** [comment] 2022-01-13 16:08
I think this is by design.
@mydeveloperday, WDYT?

**Comment by mplexor** [comment] 2022-01-13 16:11
should be configurable... could not find word about it on doc page.

**Comment by mydeveloperday** [comment] 2022-01-13 16:48
I agree its kind of  `by design`, i.e. its how you force it to be one way or the other i.e.

```
float3 a = {1, 
                  2, 
                  3, };
```

we can't easily change this now to not do that we'd break way too much code, but we'd need to introduce some sort of new option. this is a whole topic on its own, because the way arrays initializers etc are handled.

I'd prefer to see a proposal on how we treat all `{...}` cases, this can't in my view be fixed in isolation. (but its not a bug)

**Comment by EugeneZelenko** [comment] 2022-02-12 03:17
Please give developers time to address problems.

**Closed** 2022-02-14 15:32 UTC
Labels: clang-format
