### ISSUE TITLE
[InstCombine] Assertion `!Ty->isIntOrIntVectorTy(1) && "i1 divide not removed?"' failed.

### ISSUE THREAD

**Issue by TatyanaDoubts** [llvm/llvm-project#62607] opened 2023-05-08 13:50 UTC
The bug was found by FuzzGen IR test generator
Run opt with -passes='instcombine'

Reproducer: https://godbolt.org/z/3qqGave4c

Stack dump:
```console
opt: /root/llvm-project/llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp:1099: llvm::Instruction* llvm::InstCombinerImpl::commonIDivTransforms(llvm::BinaryOperator&): Assertion `!Ty->isIntOrIntVectorTy(1) && "i1 divide not removed?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/opt -o /app/output.s -S -passes=instcombine <source>
 #0 0x00005556bfc2800f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x363700f)
 #1 0x00005556bfc25734 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f0b7564d420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f0b7511a00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f0b750f9859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00007f0b750f9729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #6 0x00007f0b7510afd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #7 0x00005556bf7dfcfa llvm::InstCombinerImpl::commonIDivTransforms(llvm::BinaryOperator&) (.part.0) InstCombineMulDivRem.cpp:0:0
 #8 0x00005556bf7dfe89 llvm::InstCombinerImpl::visitUDiv(llvm::BinaryOperator&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x31eee89)
 #9 0x00005556bf71e737 llvm::InstCombinerImpl::run() (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x312d737)
#10 0x00005556bf7225ac combineInstructionsOverFunction(llvm::Function&, llvm::InstructionWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::ProfileSummaryInfo*, unsigned int, llvm::LoopInfo*) InstructionCombining.cpp:0:0
#11 0x00005556bf723785 llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x3132785)
#12 0x00005556bfe4abc6 llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x3859bc6)
#13 0x00005556bd43414d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0xe4314d)
#14 0x00005556bf524d1d llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2f33d1d)
#15 0x00005556bd4188a6 llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0xe278a6)
#16 0x00005556bf522cad llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x2f31cad)
#17 0x00005556bcf86415 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x995415)
#18 0x00005556bce99d76 main (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x8a8d76)
#19 0x00007f0b750fb083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#20 0x00005556bcf799ee _start (/opt/compiler-explorer/clang-assertions-trunk/bin/opt+0x9889ee)
Compiler returned: 139
```

**Comment by inclyc** [comment] 2023-05-08 16:38
This is a not a bug I think... udiv by 1 should be removed before "InstCombine" pass (and expected by our code here). The source code was transformed correctly by simple `-passes="early-cse,instcombine"` pipeline. https://godbolt.org/z/f3fz64bdn

CC @rotateright to confirm.

**Comment by rotateright** [comment] 2023-05-08 18:24
This is a real bug. InstCombine can't assume that other passes will transform the IR before it begins, so probably the assert should be relaxed or InstSimplify needs to be made to handle the pattern. 

The assert doesn't happen with the 16.0 release, so a fairly recent change uncovered the problem.

I'm not actively working on LLVM right now, but @nikic or @goldsteinn can probably fix or review a fix for this bug.

**Comment by goldsteinn** [comment] 2023-05-08 23:30
A simpler reproduction:
```
define i1 @foo(i1 %c, i1 %x, i1 %y) {
  br i1 %c, label %true, label %false
true:
  %y_true = and i1 %y, 0
  br label %done
false:
  %y_false = and i1 %y, 0
  br label %done
done:
  %yy = phi i1 [ %y_false, %false ], [ %y_true, %true ]
  %r = sdiv i1 %x, %yy
  ret i1 %r
}
```

**Comment by goldsteinn** [comment] 2023-05-19 16:47
NB: The fix has been pushed:
https://github.com/llvm/llvm-project/commit/ab1b42ac5cb82cd7d541caa06e7929825b4fed84

**Closed** 2023-05-19 16:48 UTC
Labels: llvm:crash, llvm:instcombine
