### ISSUE TITLE
Test test/tools/llvm-reduce/file-output-type.test is intermittently failing

### ISSUE THREAD

**Issue by xortator** [llvm/llvm-project#61761] opened 2023-03-28 13:05 UTC
I noticed it often happening in our regular LLVM merge process with ~25% chance on AMD64 RA builds. It's very annoying, and it always passes on rerun. The failure looks like:
```console
FAIL: LLVM :: tools/llvm-reduce/file-output-type.test (45893 of 47450)
******************** TEST 'LLVM :: tools/llvm-reduce/file-output-type.test' FAILED ********************
Script:
--
: 'RUN: at line 2';   rm -f reduced.ll reduced.bc
: 'RUN: at line 4';   /home/user/build/bin/llvm-as -o test-output-format.bc /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll
: 'RUN: at line 7';   llvm-reduce --delta-passes=instructions --test /home/user/build/bin/FileCheck --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test --test-arg --input-file /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll
: 'RUN: at line 8';   /home/user/build/bin/llvm-as -disable-output reduced.ll
: 'RUN: at line 12';   rm -f reduced.ll reduced.bc
: 'RUN: at line 13';   llvm-reduce --delta-passes=instructions --test "/usr/local/bin/python3.6" --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/llvm-dis-and-filecheck.py --test-arg /home/user/build/bin/llvm-dis --test-arg /home/user/build/bin/FileCheck --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test test-output-format.bc
: 'RUN: at line 14';   /home/user/build/bin/llvm-dis -disable-output reduced.bc
: 'RUN: at line 18';   llvm-reduce --delta-passes=instructions -o /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.0.bc --test "/usr/local/bin/python3.6" --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/llvm-dis-and-filecheck.py --test-arg /home/user/build/bin/llvm-dis --test-arg /home/user/build/bin/FileCheck --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test test-output-format.bc
: 'RUN: at line 19';   /home/user/build/bin/llvm-dis -disable-output /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.0.bc
: 'RUN: at line 23';   rm -f reduced.ll reduced.bc
: 'RUN: at line 24';   llvm-reduce --delta-passes=instructions -o /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.0.ll --test "/usr/local/bin/python3.6" --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/llvm-dis-and-filecheck.py --test-arg /home/user/build/bin/llvm-dis --test-arg /home/user/build/bin/FileCheck --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test test-output-format.bc
: 'RUN: at line 25';   /home/user/build/bin/llvm-dis -disable-output /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.0.ll
: 'RUN: at line 29';   llvm-reduce -o /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.1.bc --delta-passes=instructions --test /home/user/build/bin/FileCheck --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test --test-arg --input-file /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll
: 'RUN: at line 30';   /home/user/build/bin/llvm-as -disable-output /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.1.bc
: 'RUN: at line 34';   llvm-reduce -output-bitcode -o /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.2_no_suffix --delta-passes=instructions --test /home/user/build/bin/FileCheck --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test --test-arg --input-file /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll
: 'RUN: at line 35';   /home/user/build/bin/llvm-dis -disable-output /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.2_no_suffix
: 'RUN: at line 39';   llvm-reduce -output-bitcode -o /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.2.ll --delta-passes=instructions --test /home/user/build/bin/FileCheck --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test --test-arg --input-file /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll
: 'RUN: at line 40';   /home/user/build/bin/llvm-dis -disable-output /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.2.ll
: 'RUN: at line 44';   llvm-reduce -output-bitcode --delta-passes=instructions -o /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.3 --test /home/user/build/bin/FileCheck --test-arg --check-prefix=MIR --test-arg /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test --test-arg --input-file /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.mir
: 'RUN: at line 45';   /home/user/build/bin/llc -x mir -run-pass=none -o /dev/null /home/user/build/test/tools/llvm-reduce/Output/file-output-type.test.tmp.3
--
Exit Code: 1
Command Output (stderr):
--
*** Reducing Instructions...
/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test:48:10: error: CHECK: expected string not found in input
# CHECK: store i32 0
         ^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-eb907c.ll:1:1: note: scanning from here
; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll'
^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-eb907c.ll:4:23: note: possible intended match here
define void @foo(ptr %ptr) {
                      ^
Input file: /tmp/lit-tmp-slhbp6p_/llvm-reduce-eb907c.ll
Check file: /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test
-dump-input=help explains the following input dump.
Input was:
<<<<<<
            1: ; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll' 
check:48'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
            2: source_filename = "/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll" 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            3:  
check:48'0     ~
            4: define void @foo(ptr %ptr) { 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:48'1                           ?       possible intended match
            5:  ret void 
check:48'0     ~~~~~~~~~~
            6: } 
check:48'0     ~~
>>>>>>
 **** SUCCESS | Saved new best reduction to reduced.ll
/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test:48:10: error: CHECK: expected string not found in input
# CHECK: store i32 0
         ^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-07fa69.ll:1:1: note: scanning from here
; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll'
^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-07fa69.ll:4:23: note: possible intended match here
define void @foo(ptr %ptr) {
                      ^
Input file: /tmp/lit-tmp-slhbp6p_/llvm-reduce-07fa69.ll
Check file: /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test
-dump-input=help explains the following input dump.
Input was:
<<<<<<
            1: ; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll' 
check:48'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
            2: source_filename = "/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll" 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            3:  
check:48'0     ~
            4: define void @foo(ptr %ptr) { 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:48'1                           ?       possible intended match
            5:  ret void 
check:48'0     ~~~~~~~~~~
            6: } 
check:48'0     ~~
>>>>>>
/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test:48:10: error: CHECK: expected string not found in input
# CHECK: store i32 0
         ^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-1d185b.ll:1:1: note: scanning from here
; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll'
^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-1d185b.ll:4:23: note: possible intended match here
define void @foo(ptr %ptr) {
                      ^
Input file: /tmp/lit-tmp-slhbp6p_/llvm-reduce-1d185b.ll
Check file: /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test
-dump-input=help explains the following input dump.
Input was:
<<<<<<
            1: ; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll' 
check:48'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
            2: source_filename = "/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll" 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            3:  
check:48'0     ~
            4: define void @foo(ptr %ptr) { 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:48'1                           ?       possible intended match
            5:  ret void 
check:48'0     ~~~~~~~~~~
            6: } 
check:48'0     ~~
>>>>>>
----------------------------
*** Reducing Instructions...
/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test:48:10: error: CHECK: expected string not found in input
# CHECK: store i32 0
         ^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-641f58.ll:1:1: note: scanning from here
; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll'
^
/tmp/lit-tmp-slhbp6p_/llvm-reduce-641f58.ll:4:23: note: possible intended match here
define void @foo(ptr %ptr) {
                      ^
Input file: /tmp/lit-tmp-slhbp6p_/llvm-reduce-641f58.ll
Check file: /builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/file-output-type.test
-dump-input=help explains the following input dump.
Input was:
<<<<<<
            1: ; ModuleID = '/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll' 
check:48'0     X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
            2: source_filename = "/builds/dev/llvm-merge/llvm/test/tools/llvm-reduce/Inputs/test-output-format.ll" 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            3:  
check:48'0     ~
            4: define void @foo(ptr %ptr) { 
check:48'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:48'1                           ?       possible intended match
            5:  ret void 
check:48'0     ~~~~~~~~~~
            6: } 
check:48'0     ~~
>>>>>>
----------------------------
Done reducing! Reduced testcase: reduced.ll
/home/user/build/bin/llvm-as: reduced.ll:8:1: error: expected top-level entity
, ptr %ptr, align 4
^
--
********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.
.
 
********************
Failed Tests (1):
  LLVM :: tools/llvm-reduce/file-output-type.test
```

I don't understand what this test is doing. Can someone who knows this stuff please take a look?

**Comment by max-quazan** [comment] 2023-03-28 13:06
@arsenm you seem to be its author, can you please take a look? I'd appreciate if this test could be disabled until fixed.

**Comment by arsenm** [comment] 2023-04-03 13:28
I'm unable to reproduce this. My only guess would be try changing to a temporary directory before the test runs?

**Comment by MaggieYingYi** [comment] 2023-05-09 19:21
@arsenm, I think the issue is caused by the default output file reduced.ll. The default output file is generated in the `Build\test\tools\llvm-reduce\reduced.ll`. However, there is another `llvm-reduce` test named `llvm\test\tools\llvm-reduce\disable-crash-reports.test`. It also ran `llvm-reduce` to text default output in `Build\test\tools\llvm-reduce\reduced.ll`. Since `llvm\test\tools\llvm-reduce\file-output-type.test` and `llvm\test\tools\llvm-reduce\disable-crash-reports.test` both output to `Build\test\tools\llvm-reduce\reduced.ll`, it will cause `llvm\test\tools\llvm-reduce\file-output-type.test` failed in some cases.

As you mentioned that the issue can be fixed by changing to a temporary directory before the test runs. However, the commit https://github.com/llvm/llvm-project/commit/546daf1a50bde3e970e289e81f52724bb9a4ccbb only created a temporary folder but not changed to the created folder. Should the run command change from

```
# RUN: rm -rf %t.dir && mkdir %t.dir
```

to

```
# RUN: rm -rf %t.dir && mkdir %t.dir && cd %t.dir
```

Thanks,

**Comment by arsenm** [comment] 2023-05-12 16:57
> Should the run command change from
> 
> ```
> # RUN: rm -rf %t.dir && mkdir %t.dir
> ```
> 
> to
> 
> ```
> # RUN: rm -rf %t.dir && mkdir %t.dir && cd %t.dir
> ```
> 
> Thanks,

That was already done in 2aafb73f86f4296b1620540e5d7e49d19f18e60b

**Closed** 2023-06-06 12:16 UTC
Labels: regression, llvm-reduce
