### ISSUE TITLE
Build failed for kernel-6.6.47-gentoo (USE=experimental) with LTO when choosing AMD Zen 4 at link time

### ISSUE THREAD

**Issue by wiebel** [llvm/llvm-project#106409] opened 2024-08-28 15:37 UTC
This happened on a kernel-6.6.47-gentoo build for AMD Zen 4 (gentoo experimental patches) with LTO
The same .config for a generic-x86-64 built just fine.

`
|LD      vmlinux.o
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ld.lld -m elf_x86_64 -mllvm -import-instr-limit=5 -z noexecstack -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive vmlinux.a --no-whole-archive --start-group --end-group
1.      Running pass 'Function Pass Manager' on module 'ld-temmp:
0.      Program arguments: ld.lld -m elf_x86_64 -mllvm -import-instr-limit=5 -z noexecstack -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive vmlinux.a --no-whole-archive --start-group --end-group
1.      Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
 #0 0x00007fb210316d1a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x37ced1a)
 #1 0x00007fb210314814 llvm::sys::RunSignalHandlers() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x37cc814)
 #2 0x00007fb2103173f5 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x37cf3f5)
 #3 0x00007fb20c8352a0 (/usr/lib64/libc.so.6+0x3c2a0)
 #4 0x00007fb20c893d75 __libc_realloc (/usr/lib64/libc.so.6+0x9ad75)
 #5 0x00007fb2102a77e1 llvm::SmallVectorBase<unsigned int>::grow_pod(void*, unsigned long, unsigned long) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x375f7e1)
 #6 0x00007fb21092f1e9 llvm::SUnit::addPred(llvm::SDep const&, bool) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x3de71e9)
 #7 0x00007fb210baf4ff llvm::ScheduleDAGSDNodes::AddSchedEdges() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x40674ff)
 #8 0x00007fb210ba5a56 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x405da56)
 #9 0x00007fb210c681ab llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x41201ab)
#10 0x00007fb210c6733d llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x411f33d)
#11 0x00007fb210c650ce llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x411d0ce)
#12 0x00007fb2134293a3 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x68e13a3)
#13 0x00007fb2107570a9 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x3c0f0a9)
#14 0x00007fb2104977df llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x394f7df)
#15 0x00007fb21049dc63 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x3955c63)
#16 0x00007fb210497fb5 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x394ffb5)
#17 0x00007fb211b3c4e9 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4ff44e9)
#18 0x00007fb211b3b441 llvm::lto::backend(llvm::lto::Config const&, std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4ff3441)
#19 0x00007fb211b2bd80 llvm::lto::LTO::runRegularLTO(std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4fe3d80)
#20 0x00007fb211b2b14e llvm::lto::LTO::run(std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, std::__1::function<llvm::Expected<std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>> (unsigned int, llvm::StringRef, llvm::Twine const&)>) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4fe314e)
#21 0x00007fb21407b13b lld::elf::BitcodeCompiler::compile() (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x1a813b)
#22 0x00007fb213ff2204 void lld::elf::LinkerDriver::compileBitcodeFiles<llvm::object::ELFType<(llvm::endianness)1, true>>(bool) (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x11f204)
#23 0x00007fb213fede56 lld::elf::LinkerDriver::link(llvm::opt::InputArgList&) (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x11ae56)
#24 0x00007fb213fdfcda lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x10ccda)
#25 0x00007fb213fdeb3a lld::elf::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x10bb3a)
#26 0x00007fb213bf9d50 lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/usr/lib/llvm/18/bin/../lib64/liblldCommon.so.18.1+libcxx+0x12d50)
#27 0x00005643d02652fa lld_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm/18/bin/ld.lld+0x42fa)
#28 0x00005643d0265b68 main (/usr/lib/llvm/18/bin/ld.lld+0x4b68)
#29 0x00007fb20c81f0d0 (/usr/lib64/libc.so.6+0x260d0)
#30 0x00007fb20c81f189 __libc_start_main (/usr/lib64/libc.so.6+0x26189)
#31 0x00005643d0264fb5 _start (/usr/lib/llvm/18/bin/ld.lld+0x3fb5)
make[2]: *** [scripts/Makefile.vmlinux_o:62: vmlinux.o] Error 139
make[1]: *** [/usr/src/linux-6.6.47-gentoo/Makefile:1145: vmlinux_o] Error 2
make: *** [Makefile:234: __sub-make] Error 2
`

**Comment by Jannik2099** [comment] 2024-09-14 16:42
This is a duplicate of #98301

@wiebel please try with llvm >= 18.1.8-r2 - that should contain the backport https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=e4f041a12d6b2862e04663e54e1cfbdeaf48aa67

**Closed** 2024-09-14 21:22 UTC
Labels: duplicate, crash, llvm:SelectionDAG

**Comment by wiebel** [comment] 2024-09-16 13:48
Thanks @Jannik2099 I installed sys-devel/llvm-18.1.8-r4  from ~amd64 and it worked right away.
