### ISSUE TITLE
Link error in MLIR -> Debian packages not building in CI

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#54277] opened 2022-03-08 15:06 UTC
Hi,

The snapshot amd64 deb packages have not been released since Feb 26th. It seems they no longer build due to a linker error in MLIR:

```
tools/mlir/lib/Dialect/GPU/CMakeFiles/obj.MLIRGPUTransforms.dir/Transforms/SerializeToHsaco.cpp.o:SerializeToHsaco.cpp:function (anonymous namespace)::SerializeToHsacoPass::optimizeLlvm(llvm::Module&, llvm::TargetMachine&): error: undefined reference to 'mlir::makeOptimizingTransformer(unsigned int, unsigned int, llvm::TargetMachine*)'
```
https://llvm-jenkins.debian.net/job/llvm-toolchain-binaries/architecture=amd64,distribution=unstable,label=amd64/291/console

Would it be possible to fix it?

Thanks!

**Comment by joker-eph** [comment] 2022-03-08 16:00
Duplicate of #54242

**Closed** 2022-03-08 16:00 UTC
Labels: bug, packaging, mlir:gpu, mlir
