### ISSUE TITLE
clang crash: Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#84044] opened 2024-03-05 17:15 UTC
Compiling some C++ on x86_64 with `-g -O3 -Wall` and I get:
```
Instruction does not dominate all uses!
  %17 = alloca [328 x i8], align 16, !dbg !21650
  %alg_in.0.sroa.gep = getelementptr inbounds i8, ptr %17, i64 2, !dbg !21550
Instruction does not dominate all uses!
  %16 = alloca [328 x i8], align 16, !dbg !21649
  %alg_in.0.sroa.gep2072 = getelementptr inbounds i8, ptr %16, i64 2, !dbg !21550
Instruction does not dominate all uses!
  %16 = alloca [328 x i8], align 16, !dbg !21649
  %alg_in.0.sroa.gep2084 = getelementptr inbounds i8, ptr %16, i64 264, !dbg !21550
```
[expmed-e0dd12.sh.gz](https://github.com/llvm/llvm-project/files/14498958/expmed-e0dd12.sh.gz)
[expmed-e0dd12.cpp.gz](https://github.com/llvm/llvm-project/files/14498961/expmed-e0dd12.cpp.gz)

**Comment by nikic** [comment] 2024-03-15 13:57
Can't reproduce this on current main -- I believe it was fixed by https://github.com/efcs/llvm-project/commit/47841ed5b5d009539c9251c34919a8e69f3f272a.

**Closed by nikic** 2024-03-15 13:57 UTC
Labels: clang, needs-reduction

**Comment by Endilll** [comment] 2024-03-24 00:05
Comment above corresponds to upstream commit eae4f56cb40c5db0ec2c4e967107cba2473246f1
