### ISSUE TITLE
Expressions are better optimised by including a redundant term

### ISSUE THREAD

**Issue by ThomasMayerl** [llvm/llvm-project#56711] opened 2022-07-25 15:27 UTC
Sometimes expressions are better optimised by including a redundant term. The following if expression is always false:

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(bool x, bool s, bool c, bool r) {
    if (((c && !(c)) || (x && r && !(s))) && (!x == !s)) {
        DCEMarker0_();
    }
}
```

LLVM cannot eliminate the dead code. In the following snippet, `!s` is replaced by `!s || 0`.

```c
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(bool x, bool s, bool c, bool r) {
    if (((c && !(c)) || (x && r && !(s))) && (!x == (!s || 0))) {
        DCEMarker0_();
    }
}
```

LLVM is now able to detect and to remove this dead code. 

Note: With LLVM 13 both snippets cannot be optimised. The described behaviour was observed using LLVM 14.0.5

The snippets and the compiled assembly instructions can also be compared on the following Compiler Explorer website: https://godbolt.org/z/4hdvrfYM4

**Comment by ThomasMayerl** [comment] 2022-07-25 16:09
This behaviour can also be observed by using `&& 1`

Example snippets:

Original:

```
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(bool c, bool sc, bool s, bool r) {
    if (((s && !(s)) || (sc && s && !(r))) && (!r == !sc)) {
        DCEMarker0_();
    }
}
```

Modified - more complex but optimises better:

```
#include <stdio.h>
#include <stdbool.h>

static void __attribute__ ((noinline)) DCEMarker0_() {printf("DCE2.0");}

void f(bool c, bool sc, bool s, bool r) {
    if (((s && !(s)) || (sc && s && !(r))) && ((!r && 1) == !sc)) {
        DCEMarker0_();
    }
}
```

Compiler Explorer link: https://godbolt.org/z/e4vM35ncY

**Comment by bcl5980** [comment] 2022-07-28 16:20
https://alive2.llvm.org/ce/z/W310Av
(~(a & b) | c) | (a ^ c) --> true
The pattern is a little complicate , we may need find a general way to fix it.

**Comment by bcl5980** [comment] 2022-07-29 05:20
If we remove the condition (c && !(c), ipsccp can remove the deadcode. Maybe we can try to fix it in ipsccp

**Comment by bcl5980** [comment] 2022-08-01 03:00
@nikic , do you have any ideal for this issue? I tried to run ipsccp twice then the issue is gone. 
It looks ipsccp can remove only 1 dead condition every time for this case.

**Comment by rotateright** [comment] 2022-08-12 21:36
We're missing a relatively simple logic fold that should allow the larger expression to collapse:
https://alive2.llvm.org/ce/z/BsxTTx

I can post a patch for that.

**Comment by rotateright** [comment] 2022-08-16 11:58
Fixed with:
9d218b61cc50256b0cd32ba4

**Closed by rotateright** 2022-08-16 11:58 UTC
Labels: llvm:optimizations

**Comment by ThomasMayerl** [comment] 2022-08-23 09:09
I have found another case where this issue can still be reproduced:

DCE fails in the following snippet:

```c
#include <stdbool.h>

void DCEMarker0_();

void f(bool sc, bool r, bool c, bool s) {
    if ((((s && r && !(sc)) || (c && c)) && !(c) && (!sc == !(r && r)))) {
        DCEMarker0_();
    }
}
```

DCE succeeds when adding && 1:

```c
#include <stdbool.h>

void DCEMarker0_();

void f(bool sc, bool r, bool c, bool s) {
    if ((((s && r && !(sc)) || (c && c)) && !(c) && (!sc == !((r && r) && 1)))) {
        DCEMarker0_();
    }
}
```

This can also be seen over the following Compiler Explorer link: https://godbolt.org/z/59Yjrhjov
