### ISSUE TITLE
[Bug report] clang-cl fastcall (32bits) abi does not match msvc

### ISSUE THREAD

**Issue by sergeay** [llvm/llvm-project#57737] opened 2022-09-14 13:27 UTC
I hit an abi incompatibility between msvc and clang regarding fastcall x86-32bits architecture, possibly a clang bug unless something was missed

Assume two functions implemented in two different source files:

`x.cpp`:
```cpp
void caller()
{
unsigned long long a = 0x3333333344444444;
int b = 0x11111111, c = 0x22222222;

  fastercall(a, b, c);
}
```

`y.cpp`:
```cpp
__fascall void fastercall(unsigned long long a, int b, int c)
{
unsigned long long v = a;
v += b;
v += c;
std::cout << v << std::endl;
}
```

Calling method `caller()` above should result in printing: `0x3333333377777777`

And this is the case if both files are compiled with msvc compiler or clang-cl compiler.
But if `y.cpp` is compiled with clang-cl and `x.cpp` with msvc then the result is `0x33333333aaaaaaaa`

fastcall definition is here: [__fastcall | Microsoft Docs](https://docs.microsoft.com/en-us/cpp/cpp/fastcall?view=msvc-170)

it says the two first `DWORD`s or smaller size arguments should be passed with `ecx edx`, the others by stack.
i.e. `b` and `c` should go with `ecx edx` while `a` go to stack and this is not what clang-cl does:
with msvc `edx` and `ecx` have the proper values `0x1…1` and `0x2…2` while it is not the case with clang-cl.

See also Phoebe's issue identification here:
https://godbolt.org/z/v1Ghah68M

**Comment by tru** [comment] 2022-09-14 15:24
@rnk @zmodem thoughts? Probably not a regression and just due to 32bit not being as widely used for clang-cl?

**Comment by zmodem** [comment] 2022-09-14 16:16
I'll take a look. It's probably not a regression, but something that was always like this. Maybe it's a difference between Microsoft- and GNU-style `fastcall`.

**Comment by rnk** [comment] 2022-09-14 16:20
It looks like this same issue exists for __vectorcall and __regcall (icc convention):
https://godbolt.org/z/h8x9bWf9T

It looks like this check for large integer types needs to be done before the call to updateFreeRegs:
https://github.com/llvm/llvm-project/blob/main/clang/lib/CodeGen/TargetInfo.cpp#L1783

**Comment by sergeay** [comment] 2022-09-14 17:17
Maybe related to this large integer type check: if 'unsigned long long' is replaced by 'double' then we do not have the same problem.

**Comment by phoebewang** [comment] 2022-09-15 07:56
I think the reason is we updated free regs before we check if we can pass them by reg.
I have a candidate fix: https://reviews.llvm.org/D133920

**Comment by tru** [comment] 2022-09-15 08:41
Thanks @phoebewang - should we try to get this into 15.x as well?

**Comment by phoebewang** [comment] 2022-09-15 08:54
This is not regression but ABI change (from PoV of LLVM). I'd slightly prefer to leaving it to LLVM 16.

**Comment by nikic** [comment] 2022-09-15 08:56
I don't think this should go into a patch release, because this is a major breaking change. The ABI change probably needs to be broadcast on Discourse so that other frontends that have copied Clang's ABI implementation know that they need to adjust their implementation. E.g. from a cursory look, https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/abi/call/x86.rs is probably affected.

**Comment by tru** [comment] 2022-09-15 09:00
Thanks - I agree with that, I thought maybe it would have been a regression. But in that case it's better that it goes into 16 and we post about it to discourse when it's landed in main.

**Comment by sergeay** [comment] 2022-09-16 12:24
Thank you guys for handling this so fast.
I'll try version 16 when it is released.

**Closed** 2022-09-20 01:36 UTC
Labels: ABI, clang-cl
