### ISSUE TITLE
clang 17: llvm segfaults on building kernel

### ISSUE THREAD

**Issue by ambasta** [llvm/llvm-project#67631] opened 2023-09-28 04:25 UTC
Stack dump:
```
0.	Program arguments: clang -Wp,-MMD,arch/x86/power/.cpu.o.d -nostdinc -I./arch/x86/include -I./arch/x86/include/generated -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ --target=x86_64-linux-gnu -fintegrated-as -Werror=unknown-warning-option -Werror=ignored-optimization-argument -Werror=option-ignored -Werror=unused-command-line-argument -Werror -fmacro-prefix-map=./= -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mstack-alignment=8 -mskip-rax-setup -march=znver1 -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-address-of-packed-member -O2 -Wframe-larger-than=1024 -fno-stack-protector -Wno-gnu -Wno-unused-but-set-variable -Wno-unused-const-variable -fomit-frame-pointer -fno-stack-clash-protection -fzero-call-used-regs=used-gpr -fno-lto -fsanitize=kcfi -falign-functions=16 -Wvla -Wno-pointer-sign -Wcast-function-type -fstrict-flex-arrays=3 -Wimplicit-fallthrough -fno-strict-overflow -fno-stack-check -Werror=date-time -Werror=incompatible-pointer-types -Wno-initializer-overrides -Wno-sign-compare -Wno-pointer-to-enum-cast -Wno-tautological-constant-out-of-range-compare -Wno-unaligned-access -Wno-cast-function-type-strict -fno-stack-protector -DKBUILD_MODFILE=\"arch/x86/power/cpu\" -DKBUILD_BASENAME=\"cpu\" -DKBUILD_MODNAME=\"cpu\" -D__KBUILD_MODNAME=kmod_cpu -c -o arch/x86/power/cpu.o arch/x86/power/cpu.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'arch/x86/power/cpu.c'.
4.	Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@save_processor_state'
 #0 0x00007f79a469381e llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x25b281e)
 #1 0x00007f79a4690e74 llvm::sys::CleanupOnSignal(unsigned long) (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x25afe74)
 #2 0x00007f79a4582328 (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x24a1328)
 #3 0x00007f79a1c48f70 (/usr/lib64/libc.so.6+0x38f70)
 #4 0x00007f79a4d43fb1 (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x2c62fb1)
 #5 0x00007f79a4d4c3ef (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x2c6b3ef)
 #6 0x00007f79a4bd0129 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x2aef129)
 #7 0x00007f79a483b37c llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x275a37c)
 #8 0x00007f79a483b88c llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x275a88c)
 #9 0x00007f79a483c066 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x275b066)
#10 0x00007f79aa5c204f (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x27fe04f)
#11 0x00007f79aa5c2e4e clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x27fee4e)
#12 0x00007f79aaa4df3e (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x2c89f3e)
#13 0x00007f79a925fad5 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x149bad5)
#14 0x00007f79ab43a009 clang::FrontendAction::Execute() (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x3676009)
#15 0x00007f79ab3b7b2b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x35f3b2b)
#16 0x00007f79ab4c8137 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x3704137)
#17 0x00000000002187c6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm/17/bin/clang-17+0x2187c6)
#18 0x000000000021279c (/usr/lib/llvm/17/bin/clang-17+0x21279c)
#19 0x00007f79aafccb29 (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x3208b29)
#20 0x00007f79a4582703 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/llvm/17/bin/../lib64/libLLVM-17.so+0x24a1703)
#21 0x00007f79aafcfa02 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x320ba02)
#22 0x00007f79aaf8ea3b clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x31caa3b)
#23 0x00007f79aaf8f55d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x31cb55d)
#24 0x00007f79aafa1cec clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/lib/llvm/17/bin/../lib64/libclang-cpp.so.17+0x31ddcec)
#25 0x0000000000214330 clang_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm/17/bin/clang-17+0x214330)
#26 0x0000000000226271 main (/usr/lib/llvm/17/bin/clang-17+0x226271)
#27 0x00007f79a1c33af7 (/usr/lib64/libc.so.6+0x23af7)
#28 0x00007f79a1c33bb5 __libc_start_main (/usr/lib64/libc.so.6+0x23bb5)
#29 0x000000000020e801 _start (/usr/lib/llvm/17/bin/clang-17+0x20e801)
clang: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 17.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/17/bin
Configuration file: /etc/clang/x86_64-unknown-linux-gnu-clang.cfg
  CC      kernel/configs.o
clang: note: diagnostic msg: 
********************
```

**Comment by ambasta** [comment] 2023-09-28 04:30
reproducer:
[cpu-5141eb.c.txt](https://github.com/llvm/llvm-project/files/12745543/cpu-5141eb.c.txt)
[cpu-5141eb.sh.txt](https://github.com/llvm/llvm-project/files/12745544/cpu-5141eb.sh.txt)

**Comment by ambasta** [comment] 2023-09-28 04:34
Might be a duplicate of #63422

**Comment by Endilll** [comment] 2023-10-02 11:50
Appears to be a duplicate of #63422 indeed.
Fixed on post-17 trunk: https://godbolt.org/z/8jPcKzc9x
Reduced by C-Reduce:
```cpp
void (*x86_platform_0)();
void save_processor_state() { x86_platform_0(); }
```

**Closed by Endilll** 2023-10-02 11:50 UTC
Labels: clang
