### ISSUE TITLE
[bug] [clang] the position of main function influence the result

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [llvm/llvm-project#60618] opened 2023-02-09 05:24 UTC
gcc:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/60744015/217725184-f3fae706-0181-43a1-bc9d-115e38ab70e6.png">

clang:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/60744015/217725298-a1e7293a-1a1b-4fdd-a287-64366aed766b.png">

**Comment by tbaederr** [comment] 2023-02-09 05:44
This is a duplicate of https://github.com/llvm/llvm-project/issues/60588 IMO - the loop is UB.

**Closed by tbaederr** 2023-02-09 05:44 UTC
Labels: new issue
