### ISSUE TITLE
Clang 16 crashing - LLVM ERROR: out of memory (bug report)

### ISSUE THREAD

**Issue by alidavanian** [llvm/llvm-project#64873] opened 2023-08-21 19:27 UTC
Compiling the source code below using the following command results in the CLANG crash:

` clang-16 -std=c++17 -c -x c++ test.cpp -o test.bin -I.`

```
struct A {
  int i;
  constexpr A() : i(0) {}
};
struct B {
  A a[ 305748893455492146];
};
extern const B b{};
```
Below is the standard output:
```
1.      test.cu:13:19: current parser token ';'
 #0 0x00005650724c4d64 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005650724c2bcc llvm::sys::CleanupOnSignal(unsigned long) (/usr/local/bin/clang-16+0x2c30bcc)
 #2 0x000056507240c6d8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f4c944af520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007f4c94503a7c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x00007f4c94503a7c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x00007f4c94503a7c pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x00007f4c944af476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007f4c944957f3 abort ./stdlib/abort.c:81:7
 #9 0x00005650724135c4 (/usr/local/bin/clang-16+0x2b815c4)
#10 0x00005650724135eb (/usr/local/bin/clang-16+0x2b815eb)
#11 0x00007f4c9484ca23 operator new(unsigned long) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaea23)
#12 0x000056507709d634 clang::APValue::Arr::Arr(unsigned int, unsigned int) (/usr/local/bin/clang-16+0x780b634)
#13 0x00005650770a14d8 clang::APValue::MakeArray(unsigned int, unsigned int) (/usr/local/bin/clang-16+0x780f4d8)
#14 0x0000565077389356 clang::APValue::APValue(clang::APValue::UninitArray, unsigned int, unsigned int) (/usr/local/bin/clang-16+0x7af7356)
#15 0x00005650774a7f71 (anonymous namespace)::ArrayExprEvaluator::VisitInitListExpr(clang::InitListExpr const*, clang::QualType) ExprConstant.cpp:0:0
#16 0x00005650774daa5e clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::ArrayExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
#17 0x00005650774a7922 EvaluateArray(clang::Expr const*, (anonymous namespace)::LValue const&, clang::APValue&, (anonymous namespace)::EvalInfo&) ExprConstant.cpp:0:0
#18 0x00005650774ba64e EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) ExprConstant.cpp:0:0
#19 0x00005650774a422d (anonymous namespace)::RecordExprEvaluator::VisitInitListExpr(clang::InitListExpr const*) ExprConstant.cpp:0:0
#20 0x00005650774d41b5 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
#21 0x00005650774a53cb EvaluateRecord(clang::Expr const*, (anonymous namespace)::LValue const&, clang::APValue&, (anonymous namespace)::EvalInfo&) ExprConstant.cpp:0:0
#22 0x00005650774ba683 EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) ExprConstant.cpp:0:0
#23 0x00005650774bbed7 clang::Expr::EvaluateAsInitializer(clang::APValue&, clang::ASTContext const&, clang::VarDecl const*, llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic>>&, bool) const (/usr/local/bin/clang-16+0x7c29ed7)
#24 0x000056507736258d clang::VarDecl::evaluateValueImpl(llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic>>&, bool) const (/usr/local/bin/clang-16+0x7ad058d)
#25 0x00005650773628ef clang::VarDecl::checkForConstantInitialization(llvm::SmallVectorImpl<std::pair<clang::SourceLocation, clang::PartialDiagnostic>>&) const (/usr/local/bin/clang-16+0x7ad08ef)
#26 0x0000565075e8f128 clang::Sema::CheckCompleteVariableDeclaration(clang::VarDecl*) (/usr/local/bin/clang-16+0x65fd128)
#27 0x0000565075e8c941 clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/usr/local/bin/clang-16+0x65fa941)
#28 0x0000565075b1f060 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/usr/local/bin/clang-16+0x628d060)
#29 0x0000565075b1d57c clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/local/bin/clang-16+0x628b57c)
#30 0x0000565075afb057 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/bin/clang-16+0x6269057)
#31 0x0000565075afb16d clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/bin/clang-16+0x626916d)
#32 0x0000565075afa601 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/usr/local/bin/clang-16+0x6268601)
#33 0x0000565075af93f0 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/usr/local/bin/clang-16+0x62673f0)
#34 0x0000565075aef5fe clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clang-16+0x625d5fe)
#35 0x0000565073538d6d clang::ASTFrontendAction::ExecuteAction() (/usr/local/bin/clang-16+0x3ca6d6d)
#36 0x0000565073dd16bc clang::CodeGenAction::ExecuteAction() (/usr/local/bin/clang-16+0x453f6bc)
#37 0x000056507353862c clang::FrontendAction::Execute() (/usr/local/bin/clang-16+0x3ca662c)
#38 0x00005650734681fb clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/bin/clang-16+0x3bd61fb)
#39 0x00005650736e6921 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/bin/clang-16+0x3e54921)
#40 0x0000565071092536 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/bin/clang-16+0x1800536)
#41 0x00005650710849d0 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#42 0x0000565073317a91 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()::operator()() const Job.cpp:0:0
#43 0x0000565073319487 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#44 0x000056507240ce47 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/local/bin/clang-16+0x2b7ae47)
#45 0x0000565073317caf clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/usr/local/bin/clang-16+0x3a85caf)
#46 0x00005650732afe14 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/local/bin/clang-16+0x3a1de14)
#47 0x00005650732b01a2 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/local/bin/clang-16+0x3a1e1a2)
#48 0x00005650732c545b clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/local/bin/clang-16+0x3a3345b)
#49 0x0000565071086324 clang_main(int, char**) (/usr/local/bin/clang-16+0x17f4324)
#50 0x00005650710af477 main (/usr/local/bin/clang-16+0x181d477)
#51 0x00007f4c94496d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#52 0x00007f4c94496e40 call_init ./csu/../csu/libc-start.c:128:20
#53 0x00007f4c94496e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#54 0x0000565071080d3e _start (/usr/local/bin/clang-16+0x17eed3e)
clang-16: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 16.0.0 (https://github.com/llvm/llvm-project.git 19ce5e515fc5059fad8ec9aee1389ac9d109b647)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-16: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-16: note: diagnostic msg: /tmp/test-c24f69.cpp
clang-16: note: diagnostic msg: /tmp/test-c24f69.sh
clang-16: note: diagnostic msg:

********************
```
The sources and run script(s):

test-c24f69.sh:

```
# Crash reproducer for Ubuntu clang version 14.0.0-1ubuntu1
# Driver args: "--driver-mode=g++" "-std=c++17" "-c" "-x" "c++" "test.cu" "-o" "test.bin" "-I" "."
# Original command:  "/usr/lib/llvm-14/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "--mrelax-relocations" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "test.cu" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=." "-resource-dir" "/usr/lib/llvm-14/lib/clang/14.0.0" "-I" "." "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward" "-internal-isystem" "/usr/lib/llvm-14/lib/clang/14.0.0/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-std=c++17" "-fdeprecated-macro" "-fdebug-compilation-dir=." "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "test.bin" "-x" "c++" "test.cu"
 "/usr/lib/llvm-14/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "--mrelax-relocations" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "test.cu" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=." "-std=c++17" "-fdeprecated-macro" "-fdebug-compilation-dir=." "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "test-8422b5.cpp"
```
test-c24f69.cpp

`Same as test.cpp above.`

**Comment by EugeneZelenko** [comment] 2023-08-21 19:35
Probably duplicate of #57317.

**Comment by cor3ntin** [comment] 2023-08-22 06:51
@EugeneZelenko Yup!  Closing as duplicate

**Closed by cor3ntin** 2023-08-22 06:51 UTC
Labels: clang:frontend, crash
