### ISSUE TITLE
llvm-rc: Error parsing file: expected BLOCK or VALUE, got...

### ISSUE THREAD

**Issue by hmartinez82** [llvm/llvm-project#57334] opened 2022-08-24 08:46 UTC
This was found while trying to build GIMP 3 with Clang, using Meson as the build generator. The example below is an attempt to simplify a reproducible error.

The following rc file:
```c
#define _QUOTE(x) #x
#define QUOTE(x) _QUOTE(x)

#define VER_INTERNALNAME_STR        QUOTE(INTERNALNAME_STR)

STRINGTABLE
{
    1,   VER_INTERNALNAME_STR
} 
```
Compiles correctly with `windres "--define" "INTERNALNAME_STR=\"goat-exercise\"" error.rc error.o`  when using Mingw64's windres, but fails with LLVM's:
```console
$ windres "--define" "INTERNALNAME_STR=\"goat-exercise\"" error.rc error.o
llvm-rc: Error parsing file: expected '-', '~', integer or '(', got goat-exercise\
```

**Version info**
```
clang version 14.0.6
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/msys64/clang64/bin
```

This is an example from the real build:
```console
[98/1885] Generating extensions/goat-exercises/windows_compile_resources_0_gimp-plug-ins.rc with a custom command
FAILED: extensions/goat-exercises/719be94@@gimp_plugins_rc@cus_0_gimp-plug-ins.o
"D:\msys64\clang64\bin/windres.EXE" "--define" "ORIGINALFILENAME_STR=\"goat-exercise-c.exe\"" "--define" "INTERNALNAME_STR=\"goat-exercise\"" "--define" "TOP_SRCDIR=\"D:/Dev/Github/MINGW-packages/mingw-w64-gimp3/src/gimp3-2.99.12.r3.g02739dd6e6\"" "-ID:/Dev/Github/MINGW-packages/mingw-w64-gimp3/src/gimp3-2.99.12.r3.g02739dd6e6/." "-ID:/Dev/Github/MINGW-packages/mingw-w64-gimp3/src/build-CLANG64/." "-ID:/Dev/Github/MINGW-packages/mingw-w64-gimp3/src/gimp3-2.99.12.r3.g02739dd6e6/app" "-ID:/Dev/Github/MINGW-packages/mingw-w64-gimp3/src/build-CLANG64/app" "build/windows/gimp-plug-ins.rc" "extensions/goat-exercises/719be94@@gimp_plugins_rc@cus_0_gimp-plug-ins.o" "--preprocessor-arg=-MD" "--preprocessor-arg=-MQextensions/goat-exercises/719be94@@gimp_plugins_rc@cus_0_gimp-plug-ins.o" "--preprocessor-arg=-MFextensions/goat-exercises/719be94@@gimp_plugins_rc@cus_0_gimp-plug-ins.o.d"
llvm-rc: Error parsing file: expected BLOCK or VALUE, got goat-exercise\
```
Where the full rc file is:
```c
#include <winver.h>
#include "git-version.h"

#define _QUOTE(x) #x
#define QUOTE(x) _QUOTE(x)

#define VER_COMPANYNAME_STR         "Spencer Kimball, Peter Mattis and the GIMP Development Team"

#define VER_PRODUCTVERSION          2,99,12,0
#define VER_PRODUCTVERSION_STR      "2.99.12\0"
#define VER_PRODUCTNAME_STR         "GNU Image Manipulation Program"

#define VER_FILEVERSION             2,99,12,0
#define VER_FILEVERSION_STR         "2.99.12.0\0"

#define VER_FILEDESCRIPTION_STR     "GNU Image Manipulation Program Plug-In"
#define VER_INTERNALNAME_STR        QUOTE(INTERNALNAME_STR)
#define VER_ORIGINALFILENAME_STR    QUOTE(ORIGINALFILENAME_STR)

#define VER_LEGALCOPYRIGHT_STR      "Copyright © 1995-" GIMP_GIT_LAST_COMMIT_YEAR

#ifndef DEBUG
#define VER_DEBUG                   0
#else
#define VER_DEBUG                   VS_FF_DEBUG
#endif

#ifndef GIMP_UNSTABLE
#define VER_PRERELEASE              0
#else
#define VER_PRERELEASE              VS_FF_PRERELEASE
#endif

VS_VERSION_INFO VERSIONINFO
FILEVERSION    	VER_FILEVERSION
PRODUCTVERSION 	VER_PRODUCTVERSION
FILEFLAGSMASK  	VS_FFI_FILEFLAGSMASK
FILEFLAGS      	(VER_PRERELEASE|VER_DEBUG)
FILEOS         	VOS__WINDOWS32
FILETYPE       	VFT_APP
FILESUBTYPE    	VFT2_UNKNOWN
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "CompanyName",      VER_COMPANYNAME_STR
            VALUE "FileDescription",  VER_FILEDESCRIPTION_STR
            VALUE "FileVersion",      VER_FILEVERSION_STR
            VALUE "InternalName",     VER_INTERNALNAME_STR
            VALUE "OriginalFilename", VER_ORIGINALFILENAME_STR
            VALUE "ProductName",      VER_PRODUCTNAME_STR
            VALUE "ProductVersion",   VER_PRODUCTVERSION_STR
            VALUE "LegalCopyright",   VER_LEGALCOPYRIGHT_STR
        END
    END

    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200

    END
END

#include "winuser.h"
1	ICON	"/build/windows/plug-ins.ico"
CREATEPROCESS_MANIFEST_RESOURCE_ID RT_MANIFEST "/build/windows/gimp.manifest"
```

**Comment by hmartinez82** [comment] 2022-08-25 22:45
@mstorsjo I've been trying to build LLVM in Debug mode, but nothing I can do ends up with llvm-rc.exe being debuggable. Is there anything else I need to do, besides setting the CMAKE build type to Debug?

**Comment by mati865** [comment] 2022-08-25 23:30
It's an error not a crash so there is no need for debugging.

**Comment by mstorsjo** [comment] 2022-08-26 11:05
As @mati865 noted, this isn't a crash so you shouldn't need debugging info - although I guess you're wanting to step around in the codebase at runtime to understand what's going on. (In general, I haven't really tried to debug LLVM much on Windows, so I don't have much of value to add on that point.)

However, your issue is tricky. When GNU windres does preprocessing, it invokes GCC in a subprocess, and includes the relevant `--define`/`-D` options from the command line. However - it doesn't properly escape quotes/backslashes, but just passes the string on to the subshell invocation which runs GCC. This means that if you really really do want a quote in there, it has to be escaped as to be passed through two nested shell parsings. See https://sourceware.org/bugzilla/show_bug.cgi?id=27843 for more discussion on this.

In your case, when you have the preprocessor doing the quoting of the passed string,
```
#define _QUOTE(x) #x
#define QUOTE(x) _QUOTE(x)

#define VER_INTERNALNAME_STR        QUOTE(INTERNALNAME_STR)
```

Then you clearly want `INTERNALNAME_STR` to end up here without any extra quotes. If you execute your windres command with `-v`, you'll see how it invokes GCC:
```
$ windres "--define" "INTERNALNAME_STR=\"goat-exercise\"" res-quoting.rc res-quoting.o -v
Using `C:\msys64\mingw64\bin\gcc.exe -E -xc -DRC_INVOKED -DINTERNALNAME_STR="goat-exercise" res-quoting.rc'
Using popen to read preprocessor output
```
If we execute the same GCC command, we'll see how the shell consumes the quotes before invoking GCC:
```
$ gcc.exe -E -xc -DRC_INVOKED -DINTERNALNAME_STR="goat-exercise" res-quoting.rc
# 0 "res-quoting.rc"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "res-quoting.rc"





STRINGTABLE
{
    1, "goat-exercise"
}

```

However in the case of llvm-windres:
```
$ windres "--define" "INTERNALNAME_STR=\"goat-exercise\"" res-quoting.rc res-quoting.o -v
 C:/msys64/clang64/bin/clang.exe --driver-mode=gcc -target x86_64-w64-windows-gnu -E -xc -DRC_INVOKED res-quoting.rc -o C:/msys64/tmp/preproc-f7df2b.rc -D "INTERNALNAME_STR=\"goat-exercise\""
llvm-rc: Error parsing file: expected '-', '~', integer or '(', got goat-exercise\
```
Here you see that llvm-windres preserved the quotes around goat-exercise as-is when invoking clang, which means that the preprocessing output contained those quotes:
```
$ clang.exe --driver-mode=gcc -target x86_64-w64-windows-gnu -E -xc -DRC_INVOKED res-quoting.rc -D "INTERNALNAME_STR=\"goat-exercise\""
# 1 "res-quoting.rc"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 375 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "res-quoting.rc" 2





STRINGTABLE
{
    1, "\"goat-exercise\""
}
```

In your case, since you are expecting to have the processor quote the string for you in the end, I'd suggest just dropping any extra manual escaped quotes from the preprocessor argument. That wouldn't work if you wanted to pass a string that contains spaces, but that breaks in various unexpected ways today anyway, so I guess you aren't really doing that.

The other alternative is to use the same way of quoting strings that libiconv uses, as referenced in the binutils bug report above. Then you can do this kind of passing of string literals to windres this way:
```
$ cat res-quoting2.rc

STRINGTABLE
{
    1,   INTERNALNAME_STR_QUOTED
}
$ windres -DINTERNALNAME_STR_QUOTED=\\\"goat-exercise\\\" res-quoting2.rc res-quoting.o
```
This is the usecase I was aware of from before, which I've made sure that works exactly the same across both GNU windres and llvm-windres.

Finally, I think this patch to llvm-windres would fix the issue for your particular case, to make the subshell invoking closer match what happens in GNU windres:
```diff
diff --git a/llvm/tools/llvm-rc/llvm-rc.cpp b/llvm/tools/llvm-rc/llvm-rc.cpp
index 312cc15e222f..2e669f17c5c7 100644
--- a/llvm/tools/llvm-rc/llvm-rc.cpp
+++ b/llvm/tools/llvm-rc/llvm-rc.cpp
@@ -308,6 +308,9 @@ std::string unescape(StringRef S) {
       else
         fatalError("Unterminated escape");
       continue;
+    } else if (S[I] == '"') {
+      // This eats an individual unescaped quote, like a shell would do.
+      continue;
     }
     Out.push_back(S[I]);
   }
```
I'm not sure if that is safe for all the various use of llvm-windres elsewhere, but it might be - I could consider trying to do that, test it with my build corpus to see that it doesn't break something else, add a testcase and propose an upstream patch at some point.

**Comment by lazka** [comment] 2023-10-06 16:28
Looks like this was fixed by 0f4c6b120f21d582ab7c5c4f2b2a475086c34938. Can this be closed?

The first reproducer works fine now.

GIMP itself still fails, but due a different problem:

```
llvm-rc: Error in ICON statement (ID 1):
Is a directory
```

**Comment by jeremyd2019** [comment] 2023-10-06 17:10
> GIMP itself still fails, but due a different problem:
> 
> ```
> llvm-rc: Error in ICON statement (ID 1):
> Is a directory
> ```

Without looking into this, the error sounds like #51286

**Comment by lazka** [comment] 2023-10-06 20:46
Thanks, yes looks like it. So I think this can be closed then.

**Comment by mstorsjo** [comment] 2023-10-10 07:42
Fixed by https://github.com/llvm/llvm-project/commit/0f4c6b120f21d582ab7c5c4f2b2a475086c34938.

**Closed by mstorsjo** 2023-10-10 07:42 UTC
Labels: llvm-tools
