### ISSUE TITLE
Missing optimization for reducing common factors in integer division.

### ISSUE THREAD

**Issue by tstanisl** [llvm/llvm-project#58137] opened 2022-10-04 08:16 UTC
The optimizer fails to reduce a common factor in nominator and denominator producing efficient code.

```cpp
int foo(int a, int b) {
    return (2 * a * b) / (2 * a);
}

int bar(int a, int b) {
    return (2 * b * a) / (2 * a);
}
```

Compiled with CLANG 15.0 and options `-O3` produces assembly:
```asm
foo(int, int):
 mov    eax,esi
 ret    

bar(int, int):
 mov    eax,esi
 add    edi,edi
 imul   eax,edi
 cdq    
 idiv   edi
 ret 
```

See https://godbolt.org/z/51Pjen5Px

The `idiv` instruction is about 10+ times slower than `imul`. Using `int` guarantees no overflow due to invoking UB so the order of operand of `*` can be safely reordered allowing reduction of common factors in nominator and denominator. This issue appears when working with VLA when the number of elements is computed with `sizeof` operator. For example:

```cpp
int A[n][m];
int rows = sizeof A / sizeof *A;
```

**Comment by phoebewang** [comment] 2022-10-04 14:32
This should be missing optimization in middle end. The common factor in `foo` is eliminated by EarlyCSEPass. Maybe it needs enhancement to detect the commutable candidates? https://godbolt.org/z/sbhhG38e1

**Comment by rotateright** [comment] 2022-10-06 18:33
> This should be missing optimization in middle end. The common factor in `foo` is eliminated by EarlyCSEPass. Maybe it needs enhancement to detect the commutable candidates? https://godbolt.org/z/sbhhG38e1

I didn't know godbolt could show the opt pipeline like that - thanks!

I think we are just getting lucky with EarlyCSE in the first example. 
We need more folds of division in instcombine to see the common factor between multiply and shift, so I added these:
6b869be8100d
8da2fa856f1b

That solves the reduced "bar" example shown here, but it doesn't solve the motivating source example yet. Is that correct @tstanisl ?

**Comment by tstanisl** [comment] 2022-10-07 16:33
@rotateright I think it does. See https://godbolt.org/z/bdvWPvdfo. I am not good at using godbolt this way but the result looks very promising. Thank you!

**Comment by rotateright** [comment] 2022-10-07 17:24
> @rotateright I think it does. See https://godbolt.org/z/bdvWPvdfo. I am not good at using godbolt this way but the result looks very promising. Thank you!

Thanks for testing. That new example actually looks ok now, but it's slightly different than the original linked example. I'm finding a long tail of missing/deficient transforms based on the original one, so that may be why we're getting unreliable optimization with minor diffs in the source. 

I'm trying to fix those gaps. Example:
3e6767ed5f6d

If you're seeing problems in different source examples, please paste those, so we can try to make sure the problem is solved properly.

**Comment by rotateright** [comment] 2022-10-09 10:02
Another missing transform uncovered by this report:
eccb9a77c6e4

**Comment by rotateright** [comment] 2022-10-10 12:26
And another:
9cff4711ac72

**Comment by rotateright** [comment] 2022-10-12 15:56
I added a regression test for one remaining potential udiv canonicalization in IR, but we should get the optimal IR/codegen on the examples shown here now, so closing.

**Closed by rotateright** 2022-10-12 15:56 UTC
Labels: llvm:instcombine, missed-optimization
