### ISSUE TITLE
Clang++ 18.1.4 crash

### ISSUE THREAD

**Issue by caiovpsilveira** [llvm/llvm-project#93892] opened 2024-05-30 23:11 UTC
with llvm 18.1.4 x64 linux binaries, running on Debian 12.

[VulkanGraphicsContext-4ae694.zip](https://github.com/user-attachments/files/15506602/VulkanGraphicsContext-4ae694.zip)

```
caiovps@debian-desktop:~/workspace/Voxel-game/build$ make
[ 26%] Built target sdl_headers_copy
[ 26%] Building C object third_party/SDL-release-2.30.3/CMakeFiles/SDL2.dir/src/SDL.c.o
[ 26%] Linking C shared library libSDL2-2.0.so
[ 94%] Built target SDL2
[ 96%] Built target glm
[ 96%] Building CXX object CMakeFiles/voxel_game.dir/src/core/VulkanGraphicsContext.cpp.o
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/caiovps/depot/clang_llvm/18.1.4/bin/clang++ -DVK_NO_PROTOTYPES -DVMA_DYNAMIC_VULKAN_FUNCTIONS=1 -DVMA_STATIC_VULKAN_FUNCTIONS=0 -DVULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1 -I/home/caiovps/workspace/Voxel-game/src -I/home/caiovps/workspace/Voxel-game/third_party/glm-1.0.1 -I/home/caiovps/workspace/Voxel-game/build/third_party/SDL-release-2.30.3/include -I/home/caiovps/workspace/Voxel-game/build/third_party/SDL-release-2.30.3/include/SDL2 -I/home/caiovps/workspace/Voxel-game/build/third_party/SDL-release-2.30.3/include-config-/SDL2 -Wall -Wextra -pedantic -stdlib=libc++ -Wno-nullability-extension -std=gnu++2b -MD -MT CMakeFiles/voxel_game.dir/src/core/VulkanGraphicsContext.cpp.o -MF CMakeFiles/voxel_game.dir/src/core/VulkanGraphicsContext.cpp.o.d -o CMakeFiles/voxel_game.dir/src/core/VulkanGraphicsContext.cpp.o -c /home/caiovps/workspace/Voxel-game/src/core/VulkanGraphicsContext.cpp
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      /usr/include/vk_mem_alloc.h:6756:14: Generating code for declaration 'VmaBlockBufferImageGranularity::GetStartPage'
 #0 0x000055a902b10858 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x61cc858)
 #1 0x000055a902b0e5ee llvm::sys::RunSignalHandlers() (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x61ca5ee)
 #2 0x000055a902b0fce1 llvm::sys::CleanupOnSignal(unsigned long) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x61cbce1)
 #3 0x000055a902a83289 CrashRecoverySignalHandler(int) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x613f289)
 #4 0x00007f7eb7c5b050 (/lib/x86_64-linux-gnu/libc.so.6+0x3c050)
 #5 0x000055a905ab1123 clang::Decl::getAttrs() const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x916d123)
 #6 0x000055a905aa5827 getVisibilityOf(clang::NamedDecl const*, clang::NamedDecl::ExplicitVisibilityKind) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x9161827)
 #7 0x000055a905a97234 clang::NamedDecl::getExplicitVisibility(clang::NamedDecl::ExplicitVisibilityKind) const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x9153234)
 #8 0x000055a905a95fba clang::LinkageComputer::getLVForClassMember(clang::NamedDecl const*, clang::LVComputationKind, bool) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x9151fba)
 #9 0x000055a905a94b29 clang::LinkageComputer::getLVForDecl(clang::NamedDecl const*, clang::LVComputationKind) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x9150b29)
#10 0x000055a905a97169 clang::NamedDecl::getLinkageAndVisibility() const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x9153169)
#11 0x000055a902cbd054 clang::CodeGen::CodeGenModule::setGlobalVisibility(llvm::GlobalValue*, clang::NamedDecl const*) const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6379054)
#12 0x000055a902cbd7a9 clang::CodeGen::CodeGenModule::setGVProperties(llvm::GlobalValue*, clang::GlobalDecl) const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x63797a9)
#13 0x000055a902ccd44b clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x638944b)
#14 0x000055a902cc6afa clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6382afa)
#15 0x000055a902cb9843 clang::CodeGen::CodeGenModule::EmitDeferred() (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6375843)
#16 0x000055a902cb6eca clang::CodeGen::CodeGenModule::Release() (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6372eca)
#17 0x000055a9031d5f78 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6891f78)
#18 0x000055a9031cebd9 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x688abd9)
#19 0x000055a904d2d656 clang::ParseAST(clang::Sema&, bool, bool) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x83e9656)
#20 0x000055a90357e397 clang::FrontendAction::Execute() (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6c3a397)
#21 0x000055a9034f68d4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6bb28d4)
#22 0x000055a9036438fe clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6cff8fe)
#23 0x000055a900b67ee7 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x4223ee7)
#24 0x000055a900b64c91 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x4220c91)
#25 0x000055a903354469 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0>(long) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6a10469)
#26 0x000055a902a8306c llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x613f06c)
#27 0x000055a9033540d6 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x6a100d6)
#28 0x000055a903315ef4 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x69d1ef4)
#29 0x000055a90331638e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x69d238e)
#30 0x000055a903334b7f clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x69f0b7f)
#31 0x000055a900b642db clang_main(int, char**, llvm::ToolContext const&) (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x42202db)
#32 0x000055a900b73a27 main (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x422fa27)
#33 0x00007f7eb7c4624a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#34 0x00007f7eb7c46305 call_init ./csu/../csu/libc-start.c:128:20
#35 0x00007f7eb7c46305 __libc_start_main ./csu/../csu/libc-start.c:347:5
#36 0x000055a900b6102a _start (/home/caiovps/depot/clang_llvm/18.1.4/bin/clang+++0x421d02a)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 18.1.4
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/caiovps/depot/clang_llvm/18.1.4/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/VulkanGraphicsContext-4ae694.cpp
clang++: note: diagnostic msg: /tmp/VulkanGraphicsContext-4ae694.sh
clang++: note: diagnostic msg: 

********************
make[2]: *** [CMakeFiles/voxel_game.dir/build.make:104: CMakeFiles/voxel_game.dir/src/core/VulkanGraphicsContext.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/voxel_game.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by Endilll** [comment] 2024-06-03 11:19
I'm not able to reproduce this on the trunk (19.0). It's virtually impossible to get anything fixed in 18.x branch at this point, so I'm closing this as not reproducible. Feel free to reopen if it still crashes for you on trunk.

**Closed by Endilll** 2024-06-03 11:19 UTC
Labels: clang:frontend, crash, needs-reduction
