### ISSUE TITLE
[clang] Parenthesized initialization of arrays does not work in new expression

### ISSUE THREAD

**Issue by tomasz-kaminski-sonarsource** [llvm/llvm-project#78183] opened 2024-01-15 16:37 UTC
The parenthesized initialization of arrays (aggregates) is not supported in the new expression:
```C++
int main() {
  int x[10](1, 2);  // OK
  auto p = new int[10](1, 2); // ERROR, accepted by GCC and MSVC
}
```
Live example: [Godbolt](https://godbolt.org/z/64K39oEhK)

**Comment by shafik** [comment] 2024-01-15 23:44
@MitalAshok I believe this is a duplicate of: https://github.com/llvm/llvm-project/issues/68198 

When triaging new issue please be mindful of finding duplicates because often key analysis can be found in those issues.

**Comment by alanzhao1** [comment] 2024-01-22 18:13
Fixed by https://github.com/llvm/llvm-project/pull/76976

**Closed by alanzhao1** 2024-01-22 18:13 UTC
Labels: clang:frontend, confirmed
