### ISSUE TITLE
DAGToDAGISel pass confusion

### ISSUE THREAD

**Issue by karka228** [llvm/llvm-project#49023] opened 2021-03-22 14:28 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [49679](https://llvm.org/bz49679) |
| Version | trunk |
| OS | Linux |

## Extended Description 
When specifying x86-64 (or any other backend) the -debug-pass=Arguments still prints amdgpu-isel. This is a bit confusing. A consequence of this is that we can't reliably use -stop-before or run-pass for the pass.

$ llc -mtriple x86_64-unknown-unknown -O3 /dev/null -debug-pass=Arguments -o /dev/null 2>&1 | grep -o amdgpu-isel
amdgpu-isel

**Comment by RamNalamothu** [comment] 2022-12-26 15:28
Duplicate of https://github.com/llvm/llvm-project/issues/59538.

**Closed by RamNalamothu** 2022-12-26 15:28 UTC
Labels: duplicate, backend:AMDGPU, bugzilla
