### ISSUE TITLE
Assertion `MSSA->dominates(NewDef, FirstDef) && "Should have dominated the new access"' failed when running GVN

### ISSUE THREAD

**Issue by 009b8ea0-6754-41bc-becf-d830f82bdd65** [llvm/llvm-project#51257] opened 2021-09-20 16:40 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51915](https://llvm.org/bz51915) |
| Version | trunk |
| OS | Linux |
| Attachments | [IR reproducer.](https://user-images.githubusercontent.com/92601278/143762553-a1b9014c-dd4e-46eb-9e11-6eef0e01ae03.gz) |
| CC | @alinas |

## Extended Description 

LLVM commit: 15feaaa359c7245bb59ff0a2aa3b806682f44286

$ opt -enable-new-pm=0 -licm -gvn -memcpyopt -S should-have-dominated-the-new-access.ll
opt: /llvm/lib/Analysis/MemorySSAUpdater.cpp:505: void llvm::MemorySSAUpdater::fixupDefs(const llvm::SmallVectorImpl<llvm::WeakVH>&): Assertion `MSSA->dominates(NewDef, FirstDef) && "Should have dominated the new access"' failed.

I have not been able to reduce this to a single-pass opt invocation, nor reproduce this with the new pass manager.

**Comment by DaniilSuchkov** [comment] 2022-03-21 23:36
By running this command:
```
opt -passes='require<memoryssa>,gvn' -disable-output repro.ll
```
On this IR:
```
define void @test() personality i32* ()* null {
  invoke void @bar()
          to label %bar.normal unwind label %exceptional

bar.normal:
  ret void

dead.block:
  br label %baz.invoke

baz.invoke:
  invoke void @baz()
          to label %baz.normal unwind label %exceptional

baz.normal:
  ret void

exceptional:
  %tmp9 = landingpad { i8*, i32 }
          cleanup
  call void @foo()
  ret void
}

declare void @foo()
declare void @bar()
declare void @baz()
```
I'm able to reproduce the same failure on a recent LLVM build (6c0af92612d0730a039226d67cfa08f4d6db5be9).

**Comment by arpilipe** [comment] 2022-03-25 21:14
The assertion failure happens while inserting a def in dead code. We simply can't assert domination relationship in dead code, DomTree returns false for block not reachable from entry.

MSSA marks dead memory accesses as live on entry on construction. Looks like we should not bother updating the defs in dead code.

**Comment by arpilipe** [comment] 2022-03-28 19:18
A fix is suggested at https://reviews.llvm.org/D122601

**Comment by arpilipe** [comment] 2022-04-08 20:50
Fixed by the commit above.

**Closed by arpilipe** 2022-04-08 20:50 UTC
Labels: bugzilla, llvm:crash, llvm:optimizations
