### ISSUE TITLE
[Regression] clang 18 compiler crash involving source_location, auto return type, and default argument: `undeduced type in IR-generation`

### ISSUE THREAD

**Issue by yujincheng08** [llvm/llvm-project#93773] opened 2024-05-30 06:32 UTC
### Min repro
Godbolt Link https://godbolt.org/z/K88YG695q

### Additional notes
1. cannot reproduce on clang-17.
2. replacing `__builtin_source_location()` to `nullptr` does not crash.
3. changing `template <class T> auto t() -> decltype(T::x()) {}` to `template <class T> auto t() -> { return T::x(); }` does not crash.
4. changing `auto p() { return t<Q>(); }` to `template auto t<Q>() -> decltype(Q::x());` does not crash. 

### Unreachable output

```console
undeduced type in IR-generation
UNREACHABLE executed at /root/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:250!
```

### Stack dump
```console
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
1.	<eof> parser at end of file
2.	<source>:18:6: LLVM IR generation of declaration 'p'
3.	<source>:18:6: Generating code for declaration 'p'
 #0 0x00000000039ea408 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39ea408)
 #1 0x00000000039e80dc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39e80dc)
 #2 0x00000000039311b8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007908ffc42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007908ffc969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007908ffc42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007908ffc287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000000000393c40a (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x393c40a)
 #8 0x0000000003d964da clang::CodeGen::CodeGenFunction::getEvaluationKind(clang::QualType) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d964da)
 #9 0x0000000003efe8ff clang::CodeGen::isAggregateTypeForABI(clang::QualType) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3efe8ff)
#10 0x0000000003ee6a66 (anonymous namespace)::X86_64ABIInfo::getIndirectReturnResult(clang::QualType) const X86.cpp:0:0
#11 0x0000000003ef145b (anonymous namespace)::X86_64ABIInfo::computeInfo(clang::CodeGen::CGFunctionInfo&) const X86.cpp:0:0
#12 0x00000000040a02bb clang::CodeGen::CodeGenTypes::arrangeLLVMFunctionInfo(clang::CanQual<clang::Type>, clang::CodeGen::FnInfoOpts, llvm::ArrayRef<clang::CanQual<clang::Type>>, clang::FunctionType::ExtInfo, llvm::ArrayRef<clang::FunctionType::ExtParameterInfo>, clang::CodeGen::RequiredArgs) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40a02bb)
#13 0x00000000040a55c9 arrangeLLVMFunctionInfo(clang::CodeGen::CodeGenTypes&, bool, llvm::SmallVectorImpl<clang::CanQual<clang::Type>>&, clang::CanQual<clang::FunctionProtoType>) CGCall.cpp:0:0
#14 0x00000000040a8f3c clang::CodeGen::CodeGenTypes::arrangeFunctionDeclaration(clang::FunctionDecl const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40a8f3c)
#15 0x0000000003e0cb0d clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e0cb0d)
#16 0x0000000003e07725 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e07725)
#17 0x0000000003e07d1b clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e07d1b)
#18 0x0000000003e12073 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#19 0x00000000042c1966 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#20 0x00000000042b1cf8 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42b1cf8)
#21 0x000000000632b964 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x632b964)
#22 0x00000000042bf348 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42bf348)
#23 0x0000000004547b09 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4547b09)
#24 0x00000000044cdd8e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x44cdd8e)
#25 0x000000000463000e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x463000e)
#26 0x0000000000c587dc cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc587dc)
#27 0x0000000000c5195a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#28 0x00000000043029a9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#29 0x0000000003931654 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3931654)
#30 0x0000000004302fbf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#31 0x00000000042c8bd5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42c8bd5)
#32 0x00000000042c964d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42c964d)
#33 0x00000000042d1275 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42d1275)
#34 0x0000000000c55c93 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc55c93)
#35 0x0000000000b30a24 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb30a24)
#36 0x00007908ffc29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#37 0x00007908ffc29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#38 0x0000000000c5140e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc5140e)
```

**Comment by shafik** [comment] 2024-05-30 18:40
Confirmed compiles cleanly on clang-17: https://godbolt.org/z/1W8KPo68j

**Comment by yujincheng08** [comment] 2024-07-03 13:20
Is this issue being fixed? Or it's a wontfix?

**Comment by shafik** [comment] 2024-07-03 21:27
> Is this issue being fixed? Or it's a wontfix?

Compiler crash is always a bug but I don't think anyone is looking into this issue right now.

**Comment by cor3ntin** [comment] 2024-07-19 12:38
duplicate of [#81155](https://github.com/llvm/llvm-project/issues/81155)

**Closed by cor3ntin** 2024-07-19 12:38 UTC
Labels: clang:codegen, confirmed, crash-on-valid
