### ISSUE TITLE
Constraint does not have type bool after substitution 

### ISSUE THREAD

**Issue by shafik** [llvm/llvm-project#60038] opened 2023-01-14 23:43 UTC
Given the following ill-formed C++ code:

```cpp
template<typename T> struct S {
  constexpr operator bool() {return true;}
};

template<typename T> requires(S<T>{})
void f(T);
void f(int);

void g(){f(0);} 
```

clang fails to diagnose this while both gcc and MVCS correctly do godbolt: https://godbolt.org/z/ePnM6Gxvh

see [temp.const.atomic p3](https://eel.is/c++draft/temp.constr.atomic#3), which says:

> To determine if an atomic constraint is satisfied, the parameter mapping and template arguments are first substituted into its expression. If substitution results in an invalid type or expression, the constraint is not satisfied. Otherwise, the lvalue-to-rvalue conversion is performed if necessary, and E shall be a constant expression of type bool. ...

and has this exact example.

**Comment by shafik** [comment] 2023-01-14 23:43
CC @erichkeane

**Comment by royjacobson** [comment] 2023-01-15 19:54
Duplicate of #54524, I think

**Closed** 2023-01-17 14:55 UTC
Labels: c++20, clang:frontend, accepts-invalid
