### ISSUE TITLE
[LoopVectorize] "Cannot get condition of an uncond branch!" assert triggered on a simple loop

### ISSUE THREAD

**Issue by danilaml** [llvm/llvm-project#54745] opened 2022-04-04 22:53 UTC
The following reduced IR crashes with
```
/root/llvm-project/llvm/include/llvm/IR/Instructions.h:3170: llvm::Value* llvm::BranchInst::getCondition() const: Assertion `isConditional() && "Cannot get condition of an uncond branch!"' failed.
```
when run under `opt -passes=loop-vectorize`:
```
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128-ni:1-p2:32:8:8:32-ni:2"
target triple = "x86_64-unknown-linux-gnu"

define void @foo() {
entry:
  br label %header

header:                            ; preds = %loopexit, %entry
  %indvars.iv3586 = phi i64 [ %indvars.iv.next3587, %loopexit ], [ 2, %entry ]
  %local_10_50637.us.us3529 = phi i32 [ %1, %loopexit ], [ -202, %entry ]
  %0 = trunc i64 %indvars.iv3586 to i32
  %1 = add i32 %local_10_50637.us.us3529, %0
  %2 = trunc i32 %1 to i8
  br label %body

body:                             ; preds = %body, %header
  %indvars.iv3584 = phi i64 [ %indvars.iv.next3585, %body ], [ 1, %header ]
  %3 = phi i8 [ %4, %body ], [ undef, %header ]
  %4 = sub i8 %3, %2
  %5 = and i32 undef, 31
  %indvars.iv.next3585 = add nuw nsw i64 %indvars.iv3584, 1
  %6 = icmp ugt i64 %indvars.iv3584, 83
  br i1 %6, label %loopexit, label %body

loopexit:                  ; preds = %body
  %indvars.iv.next3587 = add nuw nsw i64 %indvars.iv3586, 1
  br label %header
}
```
Appears to be a recent regression, haven't yet bisected it to the problematic commit.
Godbolt link: https://godbolt.org/z/449Ke7q9M

**Comment by max-quazan** [comment] 2022-04-05 04:26
Looks like we query SCEV on a loop in invalid state:
```
Loop: Loop at depth 1 containing: %iter.check<header>,%body,%loopexit<latch>,%middle.block,%vec.epilog.iter.check,%vector.main.loop.iter.check,%vector.ph,%vector.body,%loopexit.loopexit,%vec.epilog.middle.block,%vec.epilog.scalar.ph,%vec.epilog.ph<exiting>
    Loop at depth 2 containing: %body<header><latch><exiting>
    Parallel Loop at depth 2 containing: %vector.body<header><latch><exiting>

```
IR:
```
define void @foo() {
entry:
  br label %iter.check

iter.check:                                       ; preds = %loopexit, %entry
  %induction.iv = phi i8 [ %induction.iv.next, %loopexit ], [ -56, %entry ]
  %indvar = phi i8 [ %indvar.next, %loopexit ], [ 0, %entry ]
  %indvars.iv3586 = phi i64 [ %indvars.iv.next3587, %loopexit ], [ 2, %entry ]
  %local_10_50637.us.us3529 = phi i32 [ %3, %loopexit ], [ -202, %entry ]
  %0 = mul i8 %indvar, -1
  %1 = add i8 %0, -3
  %2 = trunc i64 %indvars.iv3586 to i32
  %3 = add i32 %local_10_50637.us.us3529, %2
  %4 = trunc i32 %3 to i8
  br i1 false, label %vec.epilog.scalar.ph, label %vector.main.loop.iter.check

vector.main.loop.iter.check:                      ; preds = %iter.check
  br i1 false, label %vec.epilog.ph, label %vector.ph

vector.ph:                                        ; preds = %vector.main.loop.iter.check
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %index.next = add nuw i64 %index, 16
  %5 = icmp eq i64 %index.next, 80
  br i1 %5, label %middle.block, label %vector.body, !llvm.loop !0

middle.block:                                     ; preds = %vector.body
  %cmp.n = icmp eq i64 84, 80
  br i1 %cmp.n, label %loopexit, label %vec.epilog.iter.check

vec.epilog.iter.check:                            ; preds = %middle.block
  br i1 true, label %vec.epilog.scalar.ph, label %vec.epilog.ph

vec.epilog.ph:                                    ; preds = %vector.main.loop.iter.check, %vec.epilog.iter.check
  %vec.epilog.resume.val = phi i64 [ 80, %vec.epilog.iter.check ], [ 0, %vector.main.loop.iter.check ]
  br label %vec.epilog.vector.body

vec.epilog.vector.body:                           ; preds = %vec.epilog.ph
  br label %vec.epilog.middle.block

vec.epilog.middle.block:                          ; preds = %vec.epilog.vector.body
  br i1 true, label %loopexit.loopexit, label %vec.epilog.scalar.ph

vec.epilog.scalar.ph:                             ; preds = %iter.check, %vec.epilog.iter.check, %vec.epilog.middle.block
  %bc.resume.val = phi i64 [ 81, %vec.epilog.middle.block ], [ 81, %vec.epilog.iter.check ], [ 1, %iter.check ]
  %bc.resume.val1 = phi i8
  br label %body

body:                                             ; preds = %body, %vec.epilog.scalar.ph
  %indvars.iv3584 = phi i64 [ %indvars.iv.next3585, %body ], [ %bc.resume.val, %vec.epilog.scalar.ph ]
  %6 = phi i8 [ %7, %body ], [ undef, %vec.epilog.scalar.ph ]
  %7 = sub i8 %6, %4
  %8 = and i32 undef, 31
  %indvars.iv.next3585 = add nuw nsw i64 %indvars.iv3584, 1
  %9 = icmp ugt i64 %indvars.iv3584, 83
  br i1 %9, label %loopexit.loopexit, label %body

loopexit.loopexit:                                ; preds = %vec.epilog.middle.block, %body
  br label %loopexit

loopexit:                                         ; preds = %loopexit.loopexit, %middle.block
  %indvars.iv.next3587 = add nuw nsw i64 %indvars.iv3586, 1
  %indvar.next = add i8 %indvar, 1
  %induction.iv.next = add i8 %induction.iv, %1
  br label %iter.check
}
```
Problematic block: vec.epilog.ph

So not a bug in SCEV, it was provided with broken loop info. Must be a bug in LV.

**Comment by max-quazan** [comment] 2022-04-05 04:59
Failued appeared with patch
```
commit f8101e4d68ba428fb6a700a183e39e8f5a766dfb
Author: Florian Hahn <flo@fhahn.com>
Date:   Fri Apr 1 16:53:39 2022 +0100

    Recommit "[LV] Remove unneeded createHeaderBranch.(NFCI)"

    This reverts commit 14e3650f01d158f7e4117c353927a07ceebdd504.

    The issue causing the revert were fixed independently in
    a08c90a4023f and 14e5f9785c9c.

```
@fhahn

**Comment by max-quazan** [comment] 2022-04-05 05:16
Cannot simply revert patch; there are conflicts & trivial resolution causes another crash. Florian please take a look.

**Comment by fhahn** [comment] 2022-04-05 10:55
The issue was that SCEV was getting confused because a bb wasn't added to the correct parent loop. Should be fixed now.

**Closed** 2022-04-05 10:54 UTC
Labels: loopoptim, vectorization
