### ISSUE TITLE
[compile bugs] Can't get scale and zeropoint

### ISSUE THREAD

**Issue by imyzx2023** [llvm/llvm-project#71781] opened 2023-11-09 07:07 UTC
Here is the bug: How to fix it??
```console
%119 = "top.Add"(%102, %118) {do_relu = false, relu_limit = -1.000000e+00 : f64} : (tensor<512x1x4096xf32>, tensor<512x1x4096xf32>) -> tensor<512x1x4096xf32> loc("hidden_states_Add")
can't get scale and zeropoint
```

![image](https://github.com/llvm/llvm-project/assets/129168209/4eda6674-6342-4e8e-a46c-6f93eeedbe4d)

**Comment by fhahn** [comment] 2023-11-10 10:55
@imyzx2023 could you provide a full test case?

**Comment by fhahn** [comment] 2023-11-10 10:58
Also, this crashes in `/workspace/tpu-mlir/lib/Support/Module.cpp: 1056` which looks like the code lives in https://github.com/sophgo/tpu-mlir, not in `llvm-project/mlir`.

AFAICT the issue should be reported to that project, or we need a reproduce that shows the issue on `llvm-project/mlir`. Closing for now, please let me know if the assessment is incorrect and I'll re-open.

**Closed by fhahn** 2023-11-10 10:58 UTC
Labels: mlir
