### ISSUE TITLE
Redundant jmp instructions make N-body C++ benchmark ~30% slower than on GCC (Benchmarks Game)

### ISSUE THREAD

**Issue by yurai007** [llvm/llvm-project#56383] opened 2022-07-05 10:26 UTC
**Problem description**

Consider following C++ snippet: https://godbolt.org/z/oaY61Yjhz. The most relevant part - std::sqrt computation coming from advance function looks like:

```c++
...
double dSquared = dx * dx + dy * dy + dz * dz;
double mag = dt / (dSquared * std::sqrt(dSquared));
...	    
```

In unrolled and vectorized output produced by GCC before every sqrt computation we perform checking dSquared against 0 and conditional jump in case of slow path:

```asm
vxorpd  xmm8, xmm8, xmm8
...
vucomisd  xmm8, xmm4	; Compare dSquared with 0
ja      .L42                ; Jump if dSquared < 0
vsqrtsd xmm0, xmm4, xmm4	; Compute square root
```

That's OK case scenario. In NOK case scenario - code generated by Clang - we perform one extra redundant unconditional jmp instruction after dSquared check, at the end of every block containing vsqrtsd:

```asm
vxorpd  xmm5, xmm5, xmm5
vucomisd  xmm1, xmm5	
...
jb      .LBB0_2
vsqrtsd xmm0, xmm1, xmm1
jmp     .LBB0_3             ; Redundant unconditional jmp
```

**Impact on Benchmarks Game N-body benchmark**

Presented advance function is core computation part in one of C++ Benchmarks Game programs - N-body benchmark: https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-gpp-9.html. Relevant ja+vsqrtsd (GCC) and jb+vsqrtsd+jmp (Clang) sequences can be seen in benchmark assembly output: https://godbolt.org/z/zvE1W3jvK Since hot path containing those instructions is executed tens of millions of times, in case of Clang that one extra jmp cause significant ~30% slowdown in comparison to binary produced by GCC.

The problem with redundant branch for Clang binary can be seen in perf output as well. If you isolate only advance loop from N-body benchmark (which anyway dominates whole execution time), build the code (using exact command from: https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/nbody-gpp-9.html for both Clang and GCC) and run it, you should get similar perf output:

    [yurai@archlinux release]$ perf stat -e task-clock,cache-references,cache-misses,cycles,instructions,branches,branch-misses,L1-icache-misses ./nbody-cc-clang 50000000
    time (ms): 4061

    Performance counter stats for './nbody-cc-clang 50000000':

           4062.76 msec task-clock:u              #    1.000 CPUs utilized          
             81398      cache-references:u        #   20.035 K/sec                    (71.35%)
             45289      cache-misses:u            #   55.639 % of all cache refs      (57.09%)
       12402630163      cycles:u                  #    3.053 GHz                      (57.17%)
       21957136382      instructions:u            #    1.77  insn per cycle           (71.49%)
        1150438778      branches:u                #  283.167 M/sec                    (71.50%)
              6943      branch-misses:u           #    0.00% of all branches          (71.48%)
             50259      L1-icache-misses:u                                            (71.41%)

       4.063508370 seconds time elapsed

    [yurai@archlinux release]$ perf stat -e task-clock,cache-references,cache-misses,cycles,instructions,branches,branch-misses,L1-icache-misses ./nbody-cc-gcc 50000000
    time (ms): 3277

    Performance counter stats for './nbody-cc-gcc 50000000':

           3278.81 msec task-clock:u              #    1.000 CPUs utilized          
             87807      cache-references:u        #   26.780 K/sec                    (71.43%)
             49205      cache-misses:u            #   56.038 % of all cache refs      (57.18%)
       10020295771      cycles:u                  #    3.056 GHz                      (57.18%)
       19647384440      instructions:u            #    1.96  insn per cycle           (71.45%)
         650524259      branches:u                #  198.402 M/sec                    (71.45%)
               371      branch-misses:u           #    0.00% of all branches          (71.38%)
             29921      L1-icache-misses:u                                            (71.36%)

       3.279453499 seconds time elapsed

Clang binary (nbody-cc-clang) execution time is nearly ~30% higher with nearly 2x branches executed in comparison to GCC binary run (nbody-cc-gcc). Interestingly, branch misses and L1-icache-misses rate is quite low for both runs. 
In case of Clang there is more instructions cache misses which can be explained by looking again at advance assembly: https://godbolt.org/z/oaY61Yjhz where cold blocks are interleaved with hot ones.
Even if it could be improved I believe it's minor CodeGen issue orthogonal to one reported, after all what really matters here is number of branches.

**Workarounds**

Finally there are at least 2 workarounds. In first after passing -fno-math-errno, Clang emits branchless advance function assembly and run time is as fast as for GCC. Another way to improve Clang output is replacing "constexpr" specifier with "static" one for advance. After doing that advance function body is inlined and whole loop is vectorized by poking LV which somehow mitigates redundant jmp instructions (still seen in assembly) penalty. In consequence execution time matches GCC.
Although problem is quite easy to workaround in case of N-body benchmark I still believe it would be nice to have some general improvement in LLVM CodeGen.

**Comment by yurai007** [comment] 2022-07-05 10:28
Is it related to: https://github.com/llvm/llvm-project/issues/52620 ?

**Comment by rotateright** [comment] 2022-07-05 22:59
Thanks for the report and analysis! Yes, it does appear to be the same root problem as #52620. 

Can you check the perf on your system when compiling with "-fno-math-errno"?

**Comment by rotateright** [comment] 2022-07-05 23:02
> Can you check the perf on your system when compiling with "-fno-math-errno"?

Oops - I missed the line where you already did that. So yes, it's the same root cause as the other report. I've proposed a possible first step towards fixing this in:
https://reviews.llvm.org/D129155
(That patch won't do anything for this particular example, but it is trying to lay the foundation for follow-on patches that would get this case.)

**Comment by rotateright** [comment] 2022-07-27 16:36
Should be fixed with:
e079bf655832

**Closed by rotateright** 2022-07-27 16:36 UTC
Labels: backend:X86, llvm:codegen, performance
