### ISSUE TITLE
[LLVM-COV] DEFFUNC callsites result wrong coverage statistics under while-statement

### ISSUE THREAD

**Issue by NJUocean** [llvm/llvm-project#56228] opened 2022-06-26 09:13 UTC
1|       |struct ucharp { unsigned char *v, *l, *h; };
    2|     15|#define AREF(var, idx) ((((((((var).v+(idx)) < (var).l) \
    3|     15|			   || (((var).v+(idx)+1) > (var).h))) \
    4|     15|			  && (__builtin_trap (), 0)), \
    5|     15|			 (var).v)[(idx)])
    6|       |
    7|       |struct list
    8|       |{
    9|       |  struct list *next;
   10|       |};
   11|       |
   12|       |struct list *
   13|       |alloc_list (void)
   14|      2|{
   15|      2|  static struct list l;
   16|      2|  return &l;
   17|      2|}
   18|       |
   19|       |int one = 1;
   20|       |
   21|       |void
   22|       |foo (struct ucharp cp, struct ucharp lp, struct list **nextp)
   23|      1|{
   24|      2|  while (1)
   25|      2|    {
   26|      2|      struct list *list;
   27|      2|      while (AREF (lp, 0) && AREF (cp, AREF (lp, 0)))
   28|      2|        ++lp.v;
   29|      2|      list = alloc_list ();
   30|      2|      while (AREF (cp, AREF (lp, 0)))
   31|      2|        ++lp.v;
   32|      2|      if (AREF (lp, 0) == one)
   33|      2|	do
   34|      2|	  ++lp.v;
   35|      2|	while (AREF (lp, 0) && AREF (cp, AREF (lp, 0)));
   36|      2|      *nextp = list;
   37|      2|      nextp = &list->next;
   38|      2|      if (!*lp.v)
   39|      1|	break;
   40|      2|    }
   41|      1|}
   42|       |
   43|       |extern void exit (int);
   44|       |
   45|       |int
   46|       |main (void)
   47|      1|{
   48|      1|  static unsigned char cp0[] = "\0\0\0\0";
   49|      1|  struct ucharp cp = { cp0, cp0, cp0 + sizeof (cp0) };
   50|      1|  static unsigned char lp0[] = "\1\1\0\0";
   51|      1|  struct ucharp lp = { lp0, lp0, lp0 + sizeof (lp0) };
   52|      1|  struct list list;
   53|      1|  struct list *nextp = &list;
   54|      1|  foo (cp, lp, &nextp);
   55|      1|  exit (0);
   56|      1|}

Line 28 and 31 were not executed in fact.

**Comment by NJUocean** [comment] 2022-06-26 09:30
For LLVM-COV 11.0.0

**Comment by EugeneZelenko** [comment] 2022-06-26 13:43
Could you please try 14 or `main`?

**Comment by NJUocean** [comment] 2022-06-26 14:47
> 
Thanks for your reply! It is fixed in 14.0.4.
Last year I reported some bugs for 11.0.0 on bugzilla and it was automatically moved to github. Now I'm sorting out my previous work and continuing to report some missing bugs. I find that some bugs indeed have been fixed in 13 and 14, while some not. By the way, the labels of issues has been modified like replacing "new issue" with "tools:llvmcov " , is this equivalent to bugzilla's confirmation?

**Comment by NJUocean** [comment] 2022-06-26 14:48
> Could you please try 14 or `main`?



> Thanks for your reply! It is fixed in 14.0.4.
> Last year I reported some bugs for 11.0.0 on bugzilla and it was automatically moved to github. Now I'm sorting out my previous work and continuing to report some missing bugs. I find that some bugs indeed have been fixed in 13 and 14, while some not. By the way, the labels of issues has been modified like replacing "new issue" with "tools:llvmcov " , is this equivalent to bugzilla's confirmation?



> Could you please try 14 or `main`?

Thanks for your reply! It is fixed in 14.0.4.
Last year I reported some bugs for 11.0.0 on bugzilla and it was automatically moved to github. Now I'm sorting out my previous work and continuing to report some missing bugs. I find that some bugs indeed have been fixed in 13 and 14, while some not. By the way, the labels of issues has been modified like replacing "new issue" with "tools:llvmcov " , is this equivalent to bugzilla's confirmation?

**Comment by EugeneZelenko** [comment] 2022-06-26 14:54
@NJUocean: No it's just categorization of issue. There is `confirmed` label. Please not that issues could be fixed only in `main` since even backports to 14 were stopped. So if problems of older versions gone in 14 and `main` there is no point to report them.

**Comment by NJUocean** [comment] 2022-06-26 15:05
@EugeneZelenko Get it. I will no longer report what have been fixed in latest version.

**Closed** 2022-06-26 15:13 UTC
Labels: worksforme, tools:llvm-cov

**Comment by NJUocean** [comment] 2022-07-04 12:52
> @NJUocean: No it's just categorization of issue. There is `confirmed` label. Please not that issues could be fixed only in `main` since even backports to 14 were stopped. So if problems of older versions gone in 14 and `main` there is no point to report them.

I also find that some previously reported issues (in 11 and 12) have disappeared in the new version (13 and 14). Could you mind doing me a favor to take a look if you have a minute? Thanks a lot!
https://github.com/llvm/llvm-project/issues/48767
https://github.com/llvm/llvm-project/issues/48770
https://github.com/llvm/llvm-project/issues/48771
https://github.com/llvm/llvm-project/issues/48772
https://github.com/llvm/llvm-project/issues/48782
https://github.com/llvm/llvm-project/issues/48783
https://github.com/llvm/llvm-project/issues/48784
https://github.com/llvm/llvm-project/issues/50201
https://github.com/llvm/llvm-project/issues/50500
https://github.com/llvm/llvm-project/issues/50610
https://github.com/llvm/llvm-project/issues/50611
https://github.com/llvm/llvm-project/issues/50614

**Comment by NJUocean** [comment] 2022-07-19 07:01
> > @NJUocean: No it's just categorization of issue. There is `confirmed` label. Please not that issues could be fixed only in `main` since even backports to 14 were stopped. So if problems of older versions gone in 14 and `main` there is no point to report them.
> 
> I also find that some previously reported issues (in 11 and 12) have disappeared in the new version (13 and 14). Could you mind doing me a favor to take a look if you have a minute? Thanks a lot! #48767 #48770 #48771 #48772 #48782 #48783 #48784 #50201 #50500 #50610 #50611 #50614

@EugeneZelenko  Sorry to bother you again:)

**Comment by NJUocean** [comment] 2022-07-20 06:01
> @NJUocean: I closed all issues except #50500 (need your confirmation) and #50201 (looks partially fixed).

sorry，I got it wrong, 50500 still exists. And 50201 is indeed partially fixed.
