### ISSUE TITLE
clang-format: formatting is strange for lambdas with attributes in designated initializers

### ISSUE THREAD

**Issue by jacobsa** [llvm/llvm-project#97013] opened 2024-06-28 06:54 UTC
clang-format doesn't seem to correctly format lambdas with attributes, at least as part of designated initializers. For example, it wants this formatting for the following code:

```c++
SendCuratorRpcsRequest request = {
    .response_prototype = request.response_prototype,

    .choose_curators = [] [[clang::coro_wrapper]] ()
    -> k3::Gen<AddressAndChannel, void> { LOG(QFATAL) << "DO NOT SUBMIT"; },

    .rpc_timeout = some_long_expression + with_multiple_long_terms +
                   that_wraps_across_lines,
};
```

The formatting of the lambda is atypical, not aligning the second line with the rest of the lambda expression as is done with other expressions. I would expect something more like the following:

```c++
SendCuratorRpcsRequest request = {
    .response_prototype = request.response_prototype,

    .choose_curators = [] [[clang::coro_wrapper]] ()
                           -> k3::Gen<AddressAndChannel, void> {
                               LOG(QFATAL) << "DO NOT SUBMIT";
                        },

    .rpc_timeout = some_long_expression + with_multiple_long_terms +
                   that_wraps_across_lines,
};
```

or something closer to what you get if you remove the attribute but add a long capture list, with the second line at least indented:

```c++
SendCuratorRpcsRequest request = {
    .response_prototype = request.response_prototype,

    .choose_curators = [long_capture_list_here]()
        -> k3::Gen<AddressAndChannel, void> { LOG(QFATAL) << "DO NOT SUBMIT"; },

    .rpc_timeout = some_long_expression + with_multiple_long_terms +
                   that_wraps_across_lines,
};
```

**Comment by rymiel** [comment] 2024-06-28 21:28
This has already been fixed in d9593c1edd7add74564cf950cd209fc35f5261b6. The fix will be present in clang-format 19. Duplicate of #94181

**Closed by rymiel** 2024-06-28 21:28 UTC
Labels: clang-format
