### ISSUE TITLE
opt-18 crash: LLVM ERROR: Instruction Combining did not reach a fixpoint after 1 iterations

### ISSUE THREAD

**Issue by iamanonymouscs** [llvm/llvm-project#76431] opened 2023-12-27 08:24 UTC
opt-18 crash at "Combine redundant instructions" when compiled with -fsanitize=address.
Compiler explorer: https://godbolt.org/z/r1esW5hcK
```
$cat mutant.c
char *a;
int **b;
int c;
void d() { a[c] = a[c] + b[0][c]; }

$clang-18 -fsanitize=address -O3 -mllvm -disable-llvm-optzns -c -emit-llvm mutant.c -o mutant.bc
$opt-18 -passes=instcombine mutant.bc -o mutant.opt.bc
LLVM ERROR: Instruction Combining did not reach a fixpoint after 1 iterations
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: opt-18 -passes=instcombine mutant.bc -o mutant.opt.bc
 #0 0x00007fa3e181d266 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0xd2b266)
 #1 0x00007fa3e181b170 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0xd29170)
 #2 0x00007fa3e181d940 (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0xd2b940)
 #3 0x00007fa3e08e5980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #4 0x00007fa3dfaffe87 raise /build/glibc-CVJwZb/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #5 0x00007fa3dfb017f1 abort /build/glibc-CVJwZb/glibc-2.27/stdlib/abort.c:81:0
 #6 0x00007fa3e1778cfc llvm::report_fatal_error(llvm::Twine const&, bool) (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0xc86cfc)
 #7 0x00007fa3e2575f05 (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0x1a83f05)
 #8 0x00007fa3e257559f llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0x1a8359f)
 #9 0x00007fa3e47f1add (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0x3cffadd)
#10 0x00007fa3e1998b04 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0xea6b04)
#11 0x00007fa3e381dadd (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0x2d2badd)
#12 0x00007fa3e199c311 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0xeaa311)
#13 0x00007fa3e381d8fd (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0x2d2b8fd)
#14 0x00007fa3e1997864 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/llvm-18/bin/../lib/libLLVM-18.so.1+0xea5864)
#15 0x000055f9b6d079b9 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (/usr/lib/llvm-18/bin/opt+0x1d9b9)
#16 0x000055f9b6d148a4 main (/usr/lib/llvm-18/bin/opt+0x2a8a4)
#17 0x00007fa3dfae2c87 __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:344:0
#18 0x000055f9b6d0201a _start (/usr/lib/llvm-18/bin/opt+0x1801a)
Aborted (core dumped)
********************
```

**Comment by zjaffal** [comment] 2023-12-28 14:25
IR before instcombine.  

```
@a = external global ptr
@c = external global i32
@b = external global ptr

; Function Attrs: nounwind sanitize_address ssp uwtable
define void @d() #0 {
entry:
  %0 = load ptr, ptr @a, align 8
  %1 = load i32, ptr @c, align 4
  %idxprom = sext i32 %1 to i64
  %arrayidx = getelementptr inbounds i8, ptr %0, i64 %idxprom
  %2 = load i8, ptr %arrayidx, align 1
  %conv = sext i8 %2 to i32
  %3 = load ptr, ptr @b, align 8
  %4 = load ptr, ptr %3, align 8
  %5 = load i32, ptr @c, align 4
  %idxprom2 = sext i32 %5 to i64
  %arrayidx3 = getelementptr inbounds i32, ptr %4, i64 %idxprom2
  %6 = load i32, ptr %arrayidx3, align 4
  %add = add nsw i32 %conv, %6
  %conv4 = trunc i32 %add to i8
  %7 = load ptr, ptr @a, align 8
  store i8 %conv4, ptr %7, align 1
  ret void
}
```

It looks like the issue is with the pattern

```
%conv = sext i8 %2 to i32
%add = add nsw i32 %conv, %6
%conv4 = trunc i32 %add to i8
```
https://godbolt.org/z/bo4c5669d

**Comment by topperc** [comment] 2023-12-28 17:59
Looks like an interaction with the scan limit for `FindAvailableLoadedValue`. The default is 6. I guess some combines removed some instructions between %1 and %5, allow %5 to be detected as redundant.

To get InstCombine to reach a fixed point in one iteration, %5 would need to be added to the worklist when the instructions are deleted so that it gets visited. But %5 was not involved in the combine so there's no trigger to add it to the worklist.

**Comment by zjaffal** [comment] 2023-12-28 20:54
I will take a look and fix itOn 28 Dec 2023, at 17:59, Craig Topper ***@***.***> wrote:﻿
Looks like an interaction with the scan limit for FindAvailableLoadedValue. The default is 6. I guess some combines removed some instructions between %1 and %5, allow %5 to be detected as redundant.
To get InstCombine to reach a fixed point in one iteration, %5 would need to be added to the worklist when the instructions are deleted so that it gets visited. But %5 was not involved in the combine so there's no trigger to add it to the worklist.

**Comment by nikic** [comment] 2024-03-13 15:08
Closing this as won't fix. Always reaching the fixpoint is a non-goal, and there is no worklist management bug in this example.

**Closed by nikic** 2024-03-13 15:08 UTC
Labels: llvm:crash, llvm:instcombine
