### ISSUE TITLE
Wrong code at -O1/2/3/s  on x86_64-linux_gnu

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#58725] opened 2022-11-01 12:28 UTC
```console
% clang-tk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project.git 70fdabff416936cbcb021ff2e7a7b8d520bc2d8c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /zdata/shaoli/compilers/ccbuilder-compilers
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
%
% clang-tk -O0 a.c && a./.out
0
% clang-tk -O1 a.c && a./.out
20
% clang-tk -O2 a.c && a./.out
20
% clang-tk -O3 a.c && a./.out
20
% clang-tk -Os a.c && a./.out
20
% cat a.c
int printf(const char *format, ...);
int a;
char b;
int main() {
    int c = (1 << a) - 1;
    b = 10 * c;
    printf("%d\n", b);
}
%
```

Compiler explorer: https://godbolt.org/z/d6WGWczax

`opt-bisect-limit` suggests the issue might be in `InstCombinePass`.

**Comment by rotateright** [comment] 2022-11-01 13:17
Thank you for the report! 

This was my fault - caused by:
bc886e9b587b9d009f49
...which was reverted shortly after with:
e1de7ac20ff35aab00942f
See comments in #58717

**Comment by rotateright** [comment] 2022-11-01 13:59
Marking this as closed since the patch was reverted; please re-open if that was wrong.

**Closed by rotateright** 2022-11-01 13:59 UTC
Labels: llvm:instcombine
