### ISSUE TITLE
Regression: huge .rodata section generated because of constant vector of bool.

### ISSUE THREAD

**Issue by gwenzek** [llvm/llvm-project#55522] opened 2022-05-17 07:57 UTC
Given the simple .ll file `@0 = internal constant <4 x i1> <i1 true, i1 false, i1 true, i1 false>`,
LLVM 14 will generate an object file with 4Gb of rodata

```console
$ rm reduced.o ; cat reduced.ll && ~/Downloads/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/llc --filetype=obj reduced.ll && size -A reduced.o
@0 = internal constant <4 x i1> <i1 true, i1 false, i1 true, i1 false>
reduced.o  :
section                 size   addr
.text                      0      0
.rodata           4294967297      0
.note.GNU-stack            0      0
Total             4294967297
```

If I try with vector of i8, I correctly obtain 4 bytes of rodata.

```console
$ rm reduced.o ; cat reduced.ll && ~/Downloads/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/llc --filetype=obj reduced.ll && size -A reduced.o
@0 = internal constant <4 x i8> <i8 1, i8 0, i8 1, i8 0>
reduced.o  :
section           size   addr
.text                0      0
.rodata              4      0
.note.GNU-stack      0      0
Total                4
```

Vectors of i2, and i4 also generate the same issue.

This seems to be a regression from LLVM 13 where this was working fine (I believe the warning is just because my .ll is too dry).

```console
$ rm reduced.o ; cat reduced.ll && ~/Downloads/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/llc --filetype=obj reduced.ll && size -A reduced.o
@0 = internal constant <4 x i1> <i1 true, i1 false, i1 true, i1 false>
~Downloads/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/llc: /lib64/libtinfo.so.5: no version information available (required by ~/Downloads/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/llc)
reduced.o  :
section           size   addr
.text                0      0
.rodata              4      0
.note.GNU-stack      0      0
Total                4

```

I've tried searching for similar issue but without success.

**Comment by gwenzek** [comment] 2022-05-30 20:38
AFAICT this is still an issue on LLVM 14.04

**Comment by BertalanD** [comment] 2022-07-03 14:55
With the following assertion added, we can see what the issue is:
```diff
diff --git a/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp b/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
index 4a31bf85446b..7326d161deb6 100644
--- a/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
+++ b/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp
@@ -2981,6 +2981,7 @@ static void emitGlobalConstantVector(const DataLayout &DL,
   unsigned Size = DL.getTypeAllocSize(CV->getType());
   unsigned EmittedSize = DL.getTypeAllocSize(CV->getType()->getElementType()) *
                          CV->getType()->getNumElements();
+  assert(EmittedSize <= Size && "Size cannot be less than EmittedSize!");
   if (unsigned Padding = Size - EmittedSize)
     AP.OutStreamer->emitZeros(Padding);
 }

```

The debugger shows that `Size` is 4 and `EmittedSize` is 1, so we end up wanting to add -3 bytes of padding, which becomes the huge value when it's assigned to `unsigned Padding`.

I've bisected it to bdd55b2f1810eb5a2474a36229d08a9e5ca870fc ("Fix the default alignment of i1 vectors.", @efriedma-quic)

It's still broken on trunk.

**Comment by efriedma-quic** [comment] 2022-07-05 22:38
Posted https://reviews.llvm.org/D129164

**Closed** 2022-07-06 19:57 UTC
Labels: llvm:codegen

**Comment by joebonrichie** [comment] 2022-07-10 10:47
Can this be backported for 14.0.7?

**Comment by EugeneZelenko** [comment] 2022-07-10 13:29
@joebonrichie: 14.0.6 was last release of 14.
