### ISSUE TITLE
clang-13 crashes while compiling tests from the vc project

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#55641] opened 2022-05-22 20:32 UTC
[llvm-bug.tar.gz](https://github.com/llvm/llvm-project/files/8750236/llvm-bug.tar.gz)

[Vc project](https://github.com/VcDevel/Vc)

FreeBSD 13.1

**Comment by EugeneZelenko** [comment] 2022-05-22 21:21
What is happened with 14 and `main`?

**Comment by DimitryAndric** [comment] 2022-05-22 21:50
llvm 14 didnt' come out in time for FreeBSD 13.1, so it still has llvm 13.0.0. In any case, I'll have to see if the reproducer also results in assertions or crashes with more recent versions.

**Comment by DimitryAndric** [comment] 2022-05-23 09:34
This is a duplicate of the good old #29774, which is ~8 years old now, so don't count on it getting solved very soon! :)

If you use an llvm build with assertions enabled, you'll see:

```
Assertion failed: (Reg >= X86::FP0 && Reg <= X86::FP6 && "Expected FP register!"), function getFPReg, file /home/dim/src/llvm/llvm-project/llvm/lib/Target/X86/X86FloatingPoint.cpp, line 318.
```

In any case, the workaround is to *NOT* disable SSE2 on x86_64 platforms, as the ABI basically does not allow it.

**Closed by DimitryAndric** 2022-05-23 09:34 UTC
Labels: duplicate, clang, crash
