### ISSUE TITLE
OpenMP on i386 fails to build with `pointer size is incompatible with host 'i386-unknown-linux-gnu'`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#56699] opened 2022-07-25 06:39 UTC
It started to fail recently

```console
[2045/2626] cd "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL" && "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/bin/clang" -c -emit-llvm -std=c++17 -fvisibility=hidden -O3 -mllvm -openmp-opt-disable -DSHARED_SCRATCHPAD_SIZE=512 --offload-device-only -nocudalib -nogpulib -nostdinc -fopenmp -fopenmp-cuda-mode "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/../include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/llvm/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/include" -DOMPTARGET_DEBUG=0 --offload-arch=sm_35 -fopenmp-targets=nvptx64-nvidia-cuda -DLIBOMPTARGET_BC_TARGET --cuda-feature=+ptx61 "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/src/Configuration.cpp" -o Configuration.cpp-sm_35.bc
FAILED: openmp/libomptarget/DeviceRTL/Configuration.cpp-sm_35.bc /build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL/Configuration.cpp-sm_35.bc 
cd "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL" && "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/bin/clang" -c -emit-llvm -std=c++17 -fvisibility=hidden -O3 -mllvm -openmp-opt-disable -DSHARED_SCRATCHPAD_SIZE=512 --offload-device-only -nocudalib -nogpulib -nostdinc -fopenmp -fopenmp-cuda-mode "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/../include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/llvm/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/include" -DOMPTARGET_DEBUG=0 --offload-arch=sm_35 -fopenmp-targets=nvptx64-nvidia-cuda -DLIBOMPTARGET_BC_TARGET --cuda-feature=+ptx61 "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/src/Configuration.cpp" -o Configuration.cpp-sm_35.bc
error: OpenMP target architecture 'nvptx64-nvidia-cuda' pointer size is incompatible with host 'i386-unknown-linux-gnu'
```

**Comment by jhuber6** [comment] 2022-07-25 11:51
> It started to fail recently
> 
> ```
> 
> [2045/2626] cd "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL" && "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/bin/clang" -c -emit-llvm -std=c++17 -fvisibility=hidden -O3 -mllvm -openmp-opt-disable -DSHARED_SCRATCHPAD_SIZE=512 --offload-device-only -nocudalib -nogpulib -nostdinc -fopenmp -fopenmp-cuda-mode "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/../include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/llvm/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/include" -DOMPTARGET_DEBUG=0 --offload-arch=sm_35 -fopenmp-targets=nvptx64-nvidia-cuda -DLIBOMPTARGET_BC_TARGET --cuda-feature=+ptx61 "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/src/Configuration.cpp" -o Configuration.cpp-sm_35.bc
> FAILED: openmp/libomptarget/DeviceRTL/Configuration.cpp-sm_35.bc /build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL/Configuration.cpp-sm_35.bc 
> cd "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/runtimes/runtimes-bins/openmp/libomptarget/DeviceRTL" && "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/bin/clang" -c -emit-llvm -std=c++17 -fvisibility=hidden -O3 -mllvm -openmp-opt-disable -DSHARED_SCRATCHPAD_SIZE=512 --offload-device-only -nocudalib -nogpulib -nostdinc -fopenmp -fopenmp-cuda-mode "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/../include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/llvm/include" "-I/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/build-llvm/include" -DOMPTARGET_DEBUG=0 --offload-arch=sm_35 -fopenmp-targets=nvptx64-nvidia-cuda -DLIBOMPTARGET_BC_TARGET --cuda-feature=+ptx61 "/build/llvm-toolchain-snapshot-15~++20220724100748+9e88cbcc403b/openmp/libomptarget/DeviceRTL/src/Configuration.cpp" -o Configuration.cpp-sm_35.bc
> error: OpenMP target architecture 'nvptx64-nvidia-cuda' pointer size is incompatible with host 'i386-unknown-linux-gnu'
> ```

The problem is that `i386-unknown-linux-gnu` is a 32-bit architecture and `nvptx64-nvidia-cuda` is a 64-bit architecture. We decided at some point that it's out of scope to support architecture with conflicting pointer sizes isn't really sound as we can't directly map host pointers to device pointers. This is caused by the GPU runtime library, so one option now is to just disable it with `-DLIBOMPTARGET_BUILD_DEVICERTL_BCLIB =OFF`. To actually solve this, I'm not sure if we should use `nvptx-nvidia-cuda` instead or we should just disable it, I don't know whether or not we actually support 32-bit offloading with OpenMP. Maybe @jdoerfert can help.

**Comment by jdoerfert** [comment] 2022-07-25 16:17
I think 32 bit might just work (though I haven't tried it). That said, I think disabling it by default on 32 bit platforms is the right choice. @jhuber6 can you look into this for the release? Or @shiltian?

**Comment by jhuber6** [comment] 2022-07-25 16:18
> I think 32 bit might just work (though I haven't tried it). That said, I think disabling it by default on 32 bit platforms is the right choice. @jhuber6 can you look into this for the release? Or @shiltian?

I should be able to make a patch in a moment.

**Closed** 2022-07-25 21:01 UTC
Labels: wontfix, openmp

**Comment by jebalunode** [comment] 2023-11-17 11:23
I am seeing a similar error for compiling llvm-16.0.6, but this time specific to 64bit system. 
count_gpus.cpp: contents
int main()
{
    cout <<"Number of devices_found:\t"<< omp_get_num_devices() <<endl;
    return 0;
}

clang++ count_gpus.cpp  -fopenmp -fopenmp-targets=nvptx

error: OpenMP target architecture 'nvptx-nvidia-cuda' pointer size is incompatible with host 'x86_64-redhat-linux-gnu'
 
clang++ -v
clang version 16.0.6
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /project/dsi/apps/llvm/16.0.6/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/8
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /project/dsi/apps/easybuild/4.7.0/software/CUDA/11.4.1, version 11.4

**Comment by jhuber6** [comment] 2023-11-17 12:56
> I am seeing a similar error for compiling llvm-16.0.6, but this time specific to 64bit system. count_gpus.cpp: contents int main() { cout <<"Number of devices_found:\t"<< omp_get_num_devices() <<endl; return 0; }
> 
> clang++ count_gpus.cpp -fopenmp -fopenmp-targets=nvptx
> 
> error: OpenMP target architecture 'nvptx-nvidia-cuda' pointer size is incompatible with host 'x86_64-redhat-linux-gnu'
> 
> clang++ -v clang version 16.0.6 Target: x86_64-redhat-linux-gnu Thread model: posix InstalledDir: /project/dsi/apps/llvm/16.0.6/bin Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/8 Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/8 Candidate multilib: .;@m64 Candidate multilib: 32;@m32 Selected multilib: .;@m64 Found CUDA installation: /project/dsi/apps/easybuild/4.7.0/software/CUDA/11.4.1, version 11.4

You want `nvptx64`. Honestly we should remove `nvptx` entirely, support for 32-bit systems has already been removed by Nvidia.

**Comment by jebalunode** [comment] 2023-11-17 15:12
oh oh, I will try that.

**Comment by jebalunode** [comment] 2023-11-17 15:16
Is there a way to completely disable 32 bit build, during the llvm compiler build phase? I have tried cflags -m64 but it still generates multiblib support.

**Comment by jhuber6** [comment] 2023-11-17 15:20
> Is there a way to completely disable 32 bit build, during the llvm compiler build phase? I have tried cflags -m64 but it still generates multiblib support.

Generally the compiler will have support for 32-bit cross-compilation even without any libraries. I don't think there's a specific way to prevent `clang` from being able to target various architectures it supports. You can disable the backends that get built, but `clang` can still target LLVM-IR for them generally. (Which is why we can build GPU runtimes with LLVM-IR for users that didn't enable the NVPTX backend).
