### ISSUE TITLE
[vectorization] the pragma prevent the vectorization

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#78007] opened 2024-01-13 01:20 UTC
* test: https://gcc.godbolt.org/z/1rb1vG5GP
```
#define ARRAY_SIZE 10000
#define ELE_TYPE int

void __attribute__((noinline)) test_direct_access_2(int *A, ELE_TYPE *B, ELE_TYPE *C) {
   #pragma clang loop vectorize_width(1) interleave_count(1)
   #pragma nounroll
   for (int i = 0; i < ARRAY_SIZE; i++) {
      if (C[i] > 0)
      C[i] = C[i] + B[i] * A[i];
      else
      C[i] = C[i] - B[i] * A[i];
   }
}
```

* the above case doesn't generate vectorization body for llvm, but it does when we comment the above pragma **#pragma clang loop vectorize_width(1) interleave_count(1)**

**Comment by fhahn** [comment] 2024-01-17 21:39
@vfdff I might be missing something, but isn't this working exactly as intended? The pragmas specify vectorization with VF=1 and for VF=1 there's nothing the vectorize.

**Comment by fhahn** [comment] 2024-01-18 08:21
@vfdff I am closing this for now, please let me know if I missed anything!

**Closed by fhahn** 2024-01-18 08:21 UTC
Labels: vectorization

**Comment by vfdff** [comment] 2024-01-18 11:02
you are right, the VF=1 prevent the vectorize, so it isn't a issue, thanks
