### ISSUE TITLE
llvm-objdump --adjust-vma does not adjust symbol table

### ISSUE THREAD

**Issue by mysterymath** [llvm/llvm-project#63203] opened 2023-06-08 22:41 UTC
The `llvm-objdump` version of the `--adjust-vma` flag does not adjust the addresses of symbol table entries, while the binutils `objdump` does. This seems to have been an oversight, as symbol addresses are elsewhere adjusted (e.g., in the disassembly).

Example from the adjust-vma LLVM test case:
```console
$ objdump --all-headers -D -z --adjust-vma=0x123000 adjust-vma.test.tmp
...
SYMBOL TABLE:
0000000000123001 l     F .text  0000000000000000 func
0000000000123000 l       .text  0000000000000000 sym
0000000000123000 l    d  .text  0000000000000000 .text

$ llvm-objdump --all-headers -D -z --adjust-vma=0x123000 adjust-vma.test.tmp
...
SYMBOL TABLE:
0000000000000001 l     F .text  0000000000000000 func
0000000000000000 l       .text  0000000000000000 sym
0000000000000000 l    d  .text  0000000000000000 .text
```

**Comment by Da-Viper** [comment] 2023-06-09 16:56
@mysterymath do you have the test file you used for the example or how to create the test file  

I tried using the compile output from this 
```
int main (int, char**) { 
    return 0;
}
```
But the output is the same as not adding the --adjust-vma=0x123000

Thanks

**Comment by mysterymath** [comment] 2023-06-09 19:17
@Da-Viper, I obtained the example by partially running the existing test case:
[llvm/test/tools/llvm-objdump/X86/adjust-vma.test](https://github.com/llvm/llvm-project/blob/8006c7e3f29ab196bd26e4e98d6ac1a4692c2d92/llvm/test/tools/llvm-objdump/X86/adjust-vma.test)

It's just a matter of running yaml2obj on the test:
`$ <build_dir>/bin/yaml2obj <llvm_dir>/llvm/test/tools/llvm-objdump/X86/adjust-vma.test -o example.elf`

**Comment by HamidrezaSK** [comment] 2023-06-12 15:48
Hi @mysterymath,

I want to work on this issue. Could you assign it to me?

**Comment by HamidrezaSK** [comment] 2023-06-13 17:37
I believe I have resolved the problem, but there is still one remaining issue. When I run the test "ninja check-llvm-tools-llvm-objdump," the adjust-vma test fails, which is expected. Should I modify the test as well? Specifically, should I include the symbol table instance for ADJUST check-prefix?

**Comment by HamidrezaSK** [comment] 2023-06-16 12:50
Hi @mysterymath,

I submitted my patch [D153027](https://reviews.llvm.org/D153027) for review. The Linux build is OK. However, the Windows build encounters a failure in the "split-dwarf-local-import3.ll" test, and I'm having difficulty understanding why. I would appreciate it if you could provide some guidance in this case.

**Comment by mysterymath** [comment] 2023-06-16 22:37
That test is newly added and doesn't invoke llvm-objdump at all; seems pretty safe to call it a flake. :)

**Comment by HamidrezaSK** [comment] 2023-07-08 19:10
Hi,

The patch I sent was accepted. Does this imply that the issue is now considered closed?

**Comment by EugeneZelenko** [comment] 2023-07-08 20:06
@HamidrezaSK: Issue should be closed after patch committed to `main`.

**Comment by mysterymath** [comment] 2023-07-10 22:10
@HamidrezaSK , I can land the patch for you, but it doesn't cleanly apply to tip of tree since D153401 landed. Can you sync, resolve the merge conflicts, and reupload?

**Closed** 2023-09-11 04:28 UTC
Labels: good first issue, tools:llvm-objdump
