### ISSUE TITLE
does libc++ support c++17 special math functions?

### ISSUE THREAD

**Issue by adapt-L** [llvm/llvm-project#72055] opened 2023-11-12 15:28 UTC
https://en.cppreference.com/w/cpp/numeric/special_functions

These seem not to work for me unless I use libstdc++

**Comment by philnik777** [comment] 2023-11-12 16:24
Not yet. We talked about this on the last libc++ meeting. See https://docs.google.com/document/d/1yC-3bE6pefVizUhfiUs1Shv11EzuL0KOklGSLqto6dk/edit?pli=1#heading=h.1qj3hyp88s2w for the discussion.

**Comment by h-vetinari** [comment] 2023-11-12 23:10
I had noted in #52642:
> For example, trying to find the current status of what's blocking C++17 conformance is not an easy task; e.g., searches for "P0226" or "Mathematical Special Functions" turn up nothing, although there [were](https://reviews.llvm.org/D58876) and [are](https://reviews.llvm.org/D59937) PRs for it. [since then also [another](https://reviews.llvm.org/D142806)]

I still think it would be good to have separate issues for these unimplemented papers (like clang does, mostly), so that it's easier to find out the current status.

> Not yet. We talked about this on the last libc++ meeting.

Cool to see some movement on this!

**Comment by mordante** [comment] 2023-11-16 11:14
> I had noted in #52642:
> 
> > For example, trying to find the current status of what's blocking C++17 conformance is not an easy task; e.g., searches for "P0226" or "Mathematical Special Functions" turn up nothing, although there [were](https://reviews.llvm.org/D58876) and [are](https://reviews.llvm.org/D59937) PRs for it. [since then also [another](https://reviews.llvm.org/D142806)]
> 
> I still think it would be good to have separate issues for these unimplemented papers (like clang does, mostly), so that it's easier to find out the current status.

I strongly disagree it's hard to find out. I don't know what you mean with Clang's status; I assume you mean https://clang.llvm.org/cxx_status.html. Libc++ has similar pages per language version. For example, for C++17 there is https://libcxx.llvm.org/Status/Cxx17.html.

Since this is not a bug, I'm closing the issue.

**Closed by mordante** 2023-11-16 11:14 UTC
Labels: libc++
