### ISSUE TITLE
[DirectX] convert vector to array for groupshared

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#92153] opened 2024-05-14 17:45 UTC
DXIL requires vector to be removed
https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst#vectors

Normally, vectors are removed by the scalarizer. 
However, for groupshared memory, keeping elements of vector next to each other helps maintain the layout so that the data can be loaded/stored in a continuous address.
This will be done by convert vector into array.

AC:
    A pass to convert vector into array.
    Test.

**Comment by damyanp** [comment] 2024-07-02 18:58
Refine this once #92422 has built up a list of subtasks.

**Comment by farzonl** [comment] 2024-11-13 21:38
This looks like a dupe of https://github.com/llvm/llvm-project/issues/107920

**Closed by farzonl** 2024-11-13 21:38 UTC
Labels: duplicate, backend:DirectX
