### ISSUE TITLE
libcxx GCC+musl Build Failure Re: xlocale.h __LIBCXX_HIDE_FROM_ABI Usage

### ISSUE THREAD

**Issue by gilmorem560** [llvm/llvm-project#59540] opened 2022-12-15 23:01 UTC
Hello, I'm posting to report either a bug or environmental issue on my part with the generated `xlocale.h` file in the `c++/v1/__support/musl` folder when building with the following configuration:

```shell
cmake -DCMAKE_C_COMPILER=aarch64-unknown-linux-musl-gcc -DCMAKE_CXX_COMPILER=aarch64-unknown-linux-musl-g++ -DCMAKE_CXX_FLAGS="-nostdlib" -DLIBCXX_INCLUDE_BENCHMARKS=OFF -DLIBCXX_HAS_MUSL_LIBC=ON -Wno-dev ..
```

The build environment is `binutils-2.39`, `gcc-12.2.0`, and `musl-1.2.3` up on top of a predictable Debian x86_64 system.

This header file contains the attribute `__LIBCXX_HIDE_FROM_ABI` which maps to `abi_tag` in GCC: https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Attributes.html.  This is a C++ attribute in this case, but the extern declarations in question are marked as `extern "C"` so this is failing to compile.  In my case, simply removing this attribute allows me to proceed.

This appears to have been added here: https://reviews.llvm.org/D124227. The summary there does mention some trepidation with, among other C libraries, musl.

What I haven't investigated myself is if `__LIBCXX_HIDE_FROM_ABI` would resolve to a different attribute in a different configuration scenario.  In any case, if I do find that this is solved by a predictable configuration adjustment I'll respond with the details.

**Comment by gilmorem560** [comment] 2022-12-15 23:34
Also if it helps, this is the exact change: https://reviews.llvm.org/rG67b0b02ec9f2bbc57bf8f0550828d97f460ac11f#change-sVuAkWzbQtVW

**Comment by philnik777** [comment] 2022-12-25 01:58
We don't support musl AFAIK. Note that we don't accept fixes for platforms anymore that we don't get a runner for. So if you want libc++ to work with musl you or someone else who is interested has to provide a runner to libc++. Otherwise we will probably remove the code at some point entirely. See https://libcxx.llvm.org/AddingNewCIJobs.html#addingnewcijobs for more details on how to add a new runner.

**Comment by gilmorem560** [comment] 2022-12-27 16:43
I was just going by the presence of musl support in the code, not really sure where the support list is but I do want to reiterate the solution is simply to remove the labels, not adjust files related to other C libraries, not adjust something important, this (based on your claims that nobody is officially using musl) additionally doesn't stand to break any supported users, so a tiny little shepherding along of a change that makes the next musl-ite to descend into the depths of the code doesn't seem like a deal breaker to me...

So just to be clear, if I submit a patch myself, it still won't be honored because I'm not also going to write the entirety of the rest of musl support into your library?

**Comment by philnik777** [comment] 2022-12-27 17:34
> I was just going by the presence of musl support in the code, not really sure where the support list is but I do want to reiterate the solution is simply to remove the labels, not adjust files related to other C libraries, not adjust something important, this (based on your claims that nobody is officially using musl) additionally doesn't stand to break any supported users, so a tiny little shepherding along of a change that makes the next musl-ite to descend into the depths of the code a little less confused doesn't seem like a deal breaker to me...

The problem isn't that the change would be large, the problem is that we don't know if the code actually works, and more importantly, if our changes to the code work. If we don't test the configuration the support code is basically dead code to us.

> So just to be clear, if I submit a patch myself, it still won't be honored because I'm not also going to write the entirety of the rest of musl support into your library?

It's quite likely that this is the only part that prevents you from building libc++ with musl currently (you can try to build libc++ with `-DLIBCXX_ENABLE_LOCALIZATION=Off`). If we find someone who is interested enough to provide a runner for the configuration we are happy to support it. Otherwise we will never get out of the situation we are in currently; We have a lot of configurations where we don't know if they work or if anybody is still interested in them.

What do are you using this configuration for? If it's for a larger open source project or some company-internal project the project/company might be interested in providing a runner. There are also a few linux distros which have a musl/LLVM version (like Gentoo). Maybe they are interested in providing one.

**Comment by gilmorem560** [comment] 2022-12-27 17:39
I was just tinkering with a toolchain using GCC+musl+libcxx to try and build a minimal Linux rollout with absolutely zero Glibc or GCC libstdc++. I came across this incidentally, patched it up to fix my situation, and figured I'd come contribute instead of keeping it to myself. I'm not working on some grand design or anything like that, I found a problem, fixed it for myself, and am trying to get that fix somewhere that someone like me might benefit from it. Not demanding anyone do anything for me specifically, and this is certainly not mission critical to anything I, as an individual, am working on.

That said, take it or leave it, I'm not going to debate with you on a project you obviously contribute to and know, but I wanted to post this fix and the details so that someone deep in the bowels of their own research doesn't have to rediscover this. If one of the big players out there in the world wants to take the llvm project to task over this, they can be my guest, I don't have a horse in their races. I just saw a break, worked up a fix, and plopped some commentary about that in the most likely place that might result in an improvement to the situation.

**Comment by sylvestre** [comment] 2023-01-05 15:08
To help with the search, the error is:

**Comment by brad0** [comment] 2023-01-13 07:30
Please confirm if this can be closed now?

**Comment by sylvestre** [comment] 2023-01-13 07:33
yes, thanks

**Comment by sylvestre** [comment] 2023-01-13 07:33
it has been fixed by https://reviews.llvm.org/D141208

**Closed by sylvestre** 2023-01-13 07:33 UTC
Labels: libc++
