### ISSUE TITLE
unexpected alignment with AlignConsecutiveAssignments

### ISSUE THREAD

**Issue by zhang-stephen** [llvm/llvm-project#60677] opened 2023-02-11 16:01 UTC
`.clang-format` with LLVM 15.0.7, windows 11 x64:
```markdown
---
Language: Cpp
BasedOnStyle: WebKit

# user-defined details
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
  AlignCompound: true
  PadOperators: true
AlignConsecutiveDeclarations: Consecutive
AlignConsecutiveBitFields: Consecutive
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortLoopsOnASingleLine: true
# AllowShortBlocksOnASingleLine: true
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: WithoutElse
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
BreakBeforeConceptDeclarations: Always
BreakBeforeTernaryOperators: true
BreakStringLiterals: true
BreakConstructorInitializers: BeforeComma
BreakBeforeBraces: Allman
ColumnLimit: 120
EmptyLineBeforeAccessModifier: Always
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
IncludeBlocks: Regroup
IndentCaseBlocks: true
Language: Cpp
NamespaceIndentation: None
PointerAlignment: Left
ReferenceAlignment: Left
SpaceInEmptyBlock: false
SpaceBeforeCaseColon: false
UseTab: Never
UseCRLF: false
```

Then I got this:
![image](https://user-images.githubusercontent.com/17326718/218268064-ceefdd29-f76a-48f1-8e38-39aa2ceb182f.png)

This is different from the documentation of clang-format: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutiveassignments

![image](https://user-images.githubusercontent.com/17326718/218268121-a45472ed-d8e4-4290-81e7-d799fccc9636.png)

**Comment by rymiel** [comment] 2023-02-11 16:02
Duplicate of https://github.com/llvm/llvm-project/issues/58029. Fixed in clang-format 16 (upcoming release)

**Closed by rymiel** 2023-02-11 16:02 UTC
Labels: duplicate, clang-format
