### ISSUE TITLE
clang-tidy reports misc-use-internal-linkage when using modules

### ISSUE THREAD

**Issue by selassje** [llvm/llvm-project#118171] opened 2024-11-30 14:35 UTC
Ubuntu LLVM version 19.1.5
  Optimized build.

Minimum code:

export module aoc24_day1;

export namespace aoc24::day1 {

int
solve();

}

FAILED: src/CMakeFiles/aoc.dir/__/import/aoc24/day1.cppm.o src/CMakeFiles/aoc.dir/aoc24_day1.pcm 
/opt/hostedtoolcache/cmake/3.28.6/x64/cmake-3.28.6-linux-x86_64/bin/cmake -E __run_co_compile --tidy="/usr/bin/clang-tidy;--extra-arg-before=--driver-mode=g++" --source=/home/runner/work/aoc/aoc/import/aoc24/day1.cppm -- /usr/bin/clang++ -DENABLE_TESTS -I/home/runner/work/aoc/aoc/src/../include -isystem /home/runner/work/aoc/aoc/tests/Catch2/src/catch2/.. -isystem /home/runner/work/aoc/aoc/build/tests/Catch2/generated-includes -O3 -DNDEBUG -std=gnu++23 -Wall -Wextra -Wpedantic -Werror -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wconversion -Wsign-conversion -Wmisleading-indentation -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -stdlib=libc++ -MD -MT src/CMakeFiles/aoc.dir/__/import/aoc24/day1.cppm.o -MF src/CMakeFiles/aoc.dir/__/import/aoc24/day1.cppm.o.d @src/CMakeFiles/aoc.dir/__/import/aoc24/day1.cppm.o.modmap -o src/CMakeFiles/aoc.dir/__/import/aoc24/day1.cppm.o -c /home/runner/work/aoc/aoc/import/aoc24/day1.cppm
/home/runner/work/aoc/aoc/import/aoc24/day1.cppm:6:1: error: function 'solve' can be made static or moved into an anonymous namespace to enforce internal linkage [misc-use-internal-linkage,-warnings-as-error

**Comment by 5chmidti** [comment] 2024-11-30 20:52
This is a duplicate of #97190 and will be fixed by #117901

**Closed by 5chmidti** 2024-11-30 20:52 UTC
Labels: clang-tidy, clang:modules
