### ISSUE TITLE
[AArch64] Use scalar operand for lane extract 0

### ISSUE THREAD

**Issue by SamTebbs33** [llvm/llvm-project#60817] opened 2023-02-16 16:53 UTC
For this input:

```cpp
#include <arm_neon.h>
float32_t __attribute__ ((noinline))
test_vmulxs_laneq_f32_lane0 (float32_t vec1_1, float32x4_t vec1_2) {
  return vmulxs_laneq_f32 (vec1_1, vec1_2, 0);
}
```

We generate:

`fmulx   s0, s0, v1.s[0]`

but this could be:
`fmulx   s0, s0, s1`

which has only scalar operands and could perform more consistent across different cores (i.e. the same or better than the lane extract)

**Comment by satyadev2** [comment] 2023-03-08 11:31
Hello sir, I'm satya kushwaha , an outreachy applicant, i have cleared the initial application round ,i want to work on this issue, i have prior knowledge of computer architecture and low-level programming concepts l,would you please assign this project to me.

**Comment by overmighty** [comment] 2023-06-09 09:55
I am working on this.

> which has only scalar operands and could perform more consistent across different cores (i.e. the same or better than the lane extract)

I assume that you are referring to the "by element" variants of `fmul` and `fmulx` performing worse on some Arm cores. For example, the [Arm Cortex-A55 Software Optimization Guide](https://developer.arm.com/documentation/EPM128372/0300/?lang=en) states that "ASIMD FP multiply, by element" instructions have a throughput of 1 IPC whereas the regular "ASIMD FP multiply" ones have a throughput of 2 IPC when not operating on 128-bit vectors.

**Comment by overmighty** [comment] 2023-06-17 22:07
I submitted a candidate patch: https://reviews.llvm.org/D153207.

**Closed** 2023-06-30 07:34 UTC
Labels: backend:AArch64, missed-optimization

**Comment by v01dXYZ** [comment] 2023-06-30 09:01
Nice little optimisation, it's surprising the CPU is unable to detect that the two encodings have exactly the same semantics and thus uses the same execution path showing equal performance.

---

The following patterns were the relevant ones before the addition of new patterns:

The patterns to replace a `(extract_subvector val, 0)` with a `(extract_subreg val, subreg)`, they look like the ones that you added to `SIMDFPIndexed`:  https://github.com/llvm/llvm-project/blob/db15ace6ab667af302f8788ab2a14c3382522ed4/llvm/lib/Target/AArch64/AArch64InstrInfo.td#L8504-L8519

The pattern for `SIMFPIndexed` naturally destroys the above `extract_subvector` pattern for the second operand, the indexing being "Morphed": https://github.com/llvm/llvm-project/blob/3a9ea6a48a7092b89515f4c3e2b2b6d5851b2b61/llvm/lib/Target/AArch64/AArch64InstrFormats.td#L8430

I think the reason why you didn't add the `FMUL`/`FMULX` patterns to `SIMDFPIndexed` instead is because there is no assurance there is a scalar version of the instruction for all the `SIMDFPIndexed` instruction.

**Comment by overmighty** [comment] 2023-06-30 09:52
Could you clarify what you mean by the indexing being "morphed"?

I didn't add the new scalar patterns to `SIMDFPIndexed` mainly because I haven't noticed any existing `def : Pat`s in the multiclass of the pattern instructions, only in the multiclass of the result instructions. `SIMDFPIndexed` happens to only be invoked for FMUL and FMULX, but that feels more like a "coincidence" than a contract that there must be scalar versions of the instructions anyway, yeah.

**Comment by v01dXYZ** [comment] 2023-06-30 13:50
My bad, I should I've said "replaced" instead of "morphed". "Morphed" is what the debug mode of SelectionDAG outputs to inform that the matching node is being overwritten instead of creating a new node and putting it in the DAG.

**Comment by v01dXYZ** [comment] 2023-07-01 06:09
@overmighty hello again, I took some time to read the code before commenting. Do you think the following patterns are really necessary ? https://github.com/llvm/llvm-project/blob/ea045b99da8ee236076fddb256bdac98681441fa/llvm/lib/Target/AArch64/AArch64InstrFormats.td#L8538-L8556

I am maybe wrong but it seems they are redundant with https://github.com/llvm/llvm-project/blob/3a9ea6a48a7092b89515f4c3e2b2b6d5851b2b61/llvm/lib/Target/AArch64/AArch64InstrInfo.td#L6279-L6289

It interferes with the following case btw:

``` llvm
define float @multiple_extractelement(<4 x float> %a, <4 x float> %b) {
    %a.0 = extractelement <4 x float> %a, i32 0
    %b.0 = extractelement <4 x float> %b, i32 0
    %mul = fmul float %a.0, %b.0

    ret float %mul
}
```

Result:

* Without: it ouputs the `scalar, scalar` operands 
* With: it outputs `scalar, vec_index[0]` operands.

**Comment by v01dXYZ** [comment] 2023-07-01 06:16
@overmighty hello again, I took some time to read the code before commenting. Do you think the following patterns are really necessary ? https://github.com/llvm/llvm-project/blob/ea045b99da8ee236076fddb256bdac98681441fa/llvm/lib/Target/AArch64/AArch64InstrFormats.td#L8538-L8556

I am maybe wrong but it seems they are redundant with https://github.com/llvm/llvm-project/blob/3a9ea6a48a7092b89515f4c3e2b2b6d5851b2b61/llvm/lib/Target/AArch64/AArch64InstrInfo.td#L6279-L6289

It interferes in the following case btw:

``` llvm
define float @multiple_extractelements(<4 x float> %a, <4 x float> %b) {
    %a.0 = extractelement <4 x float> %a, i32 0
    %b.0 = extractelement <4 x float> %b, i32 0
    %mul = fmul float %a.0, %b.0

    ret float %mul
}
```

Result:

* Without: `fmul s0, s0, s1`
* With:  `fmul s0, s0, v1.s[0]`

**Comment by overmighty** [comment] 2023-07-01 09:44
These patterns prevent the scalar instructions from being used if it might introduce an extra `mov`, see https://reviews.llvm.org/D153207#inline-1480867. I did notice that they cause the indexed instructions to be used in some cases where the scalar instructions were already being used, see https://reviews.llvm.org/D153207#inline-1480865, and ideally we would generate scalar instructions in both cases, but I don't know how to approach this issue. If I recall correctly, GCC generates the scalar instructions even when they require an extra `mov`.

**Comment by overmighty** [comment] 2023-07-01 21:06
Here's a case where GCC generates `mov`/`dup` to use scalar `fmul`: https://godbolt.org/z/6Mooosdo6. LLVM generates vector indexed `fmul` instead of the scalar indexed one due to Clang emitting IR with `shufflevector` and vector `fmul` instead of `extractelement` and scalar `fmul`.

**Comment by v01dXYZ** [comment] 2023-07-02 05:03
Very interesting, thanks for the explanation. Indeed the pattern introduced with `FMULScalarFromIndexedLane0Patterns` collides with the pattern for `SIMDFPIndexed`.

`FMULScalarFromIndexedLane0Patterns`: 

```
def : Pat<
(f32 (OpNode
               (f32 FPR32:$Rn),
               (f32 (vector_extract (v4f32 V128:$Rm), (i64 0))))),
     (!cast<Instruction>(inst # inst_f32_suffix) FPR32:$Rn, (EXTRACT_SUBREG V128:$Rm, ssub))
>;
```

`SIMDFPIndexed`

```
def v132_indexed : BaseSIMDIndexed<1, U, 1, 0b10, opc, FPR32Op, FPR32Op, V128, VectorIndexS, asm, ".s", "", "", ".s",
[(set (f32 FPR32Op:$Rd),
         (OpNode (f32 FPR32Op:$Rn),
                 (f32 (vector_extract (v4f32 V128:$Rm), VectorIndexS:$idx))))]>
```

I still don't understand the difference between `FPR32Op` and `FPR32` when defining a pattern.

The solution would be to add another pattern for the double zero index case but there are already too many patterns for that...

**Comment by v01dXYZ** [comment] 2023-07-02 06:28
Very interesting, thanks for the explanation. Indeed the pattern introduced with `FMULScalarFromIndexedLane0Patterns` collides with the pattern for `SIMDFPIndexed`.

`FMULScalarFromIndexedLane0Patterns`: 

```
def : Pat<
(f32 (OpNode
               (f32 FPR32:$Rn),
               (f32 (vector_extract (v4f32 V128:$Rm), (i64 0))))),
     (!cast<Instruction>(inst # inst_f32_suffix) FPR32:$Rn, (EXTRACT_SUBREG V128:$Rm, ssub))
>;
```

`SIMDFPIndexed`

```
def v132_indexed : BaseSIMDIndexed<1, U, 1, 0b10, opc, FPR32Op, FPR32Op, V128, VectorIndexS, asm, ".s", "", "", ".s",
[(set (f32 FPR32Op:$Rd),
         (OpNode (f32 FPR32Op:$Rn),
                 (f32 (vector_extract (v4f32 V128:$Rm), VectorIndexS:$idx))))]>
```

If we takes the following code, which is essentially how LLVM partially lower the `llvm.vector.reduce.fmul` you used in your comment:

``` llvm
target triple = "aarch64-unknown-linux-gnu"

define float @fmul_3(<3 x float> %v) {
       %v_0 = extractelement <3 x float> %v, i64 0
       %v_1 = extractelement <3 x float> %v, i64 1
       %v_2 = extractelement <3 x float> %v, i64 2

       %mul.0 = fmul float %v_0, %v_1
       // ^ before: produce v0.s[1] as second input operand
       //    after: produce s0 as second input operand with added dup
       %mul.1 = fmul float %mul.0, %v_2

      ret float %mul.1
}
```

It collides because the pattern to create the scalar `fmul` will be prefered over the pattern for the indexed `fmul` 

BTW do you know the difference between `FPR32Op` and `FPR32` when defining a pattern ?

The solution would be to add another pattern (again !) for the double zero index case but there are already too many patterns for that...

**Comment by overmighty** [comment] 2023-07-04 19:58
I was not aware of this case where indexed instructions are still being used for lane 0. However, your patch does not fix the regression I mentioned: https://reviews.llvm.org/D153207#inline-1480865. This issue turned out trickier than I thought.

**Comment by v01dXYZ** [comment] 2023-07-06 06:13
@overmighty Indeed, you're right, the patch is for `fmul Rm.[0], Rn.[0]`, it's off topic wrt the issue which mentions scalar multiplied by 0-indexed element of vector.

Concerning the regression, it is the following:

Input:

``` llvm
define <2 x half> @complex_mul_v2f16(<2 x half> %a, <2 x half> %b) {
entry:
  %a.real   = shufflevector <2 x half> %a, <2 x half> poison, <1 x i32> <i32 0>
  %a.imag = shufflevector <2 x half> %a, <2 x half> poison, <1 x i32> <i32 1>
  %b.real = shufflevector <2 x half> %b, <2 x half> poison, <1 x i32> <i32 0>
  %b.imag = shufflevector <2 x half> %b, <2 x half> poison, <1 x i32> <i32 1>
  %0 = fmul fast <1 x half> %b.imag, %a.real
  %1 = fmul fast <1 x half> %b.real, %a.imag
  %2 = fadd fast <1 x half> %1, %0
  %3 = fmul fast <1 x half> %b.real, %a.real
  %4 = fmul fast <1 x half> %a.imag, %b.imag
  %5 = fsub fast <1 x half> %3, %4
  %interleaved.vec = shufflevector <1 x half> %5, <1 x half> %2, <2 x i32> <i32 0, i32 1>
  ret <2 x half> %interleaved.vec
}
```

Before:

``` asm                                             
complex_mul_v2f16:
// %bb.0: // %entry
// kill: def $d1 killed $d1 def $q1
// kill: def $d0 killed $d0 def $q0
mov h3, v0.h[1]
mov h2, v1.h[1]
fmul h4, h2, v0.h[0]   // <=====     line of interest
fnmul h2, h3, h2
fmla h4, h3, v1.h[0]
fmla h2, h0, v1.h[0]
mov v2.h[1], v4.h[0]
fmov d0, d2
ret
```

After:

``` asm
 complex_mul_v2f16:
// %bb.0: // %entry
// kill: def $d1 killed $d1 def $q1
// kill: def $d0 killed $d0 def $q0
mov h3, v0.h[1]
mov h2, v1.h[1]
fmul h4, h0, v1.h[1]   // <=====     line of interest
fnmul h2, h3, h2
fmla h4, h3, v1.h[0]
fmla h2, h0, v1.h[0]
mov v2.h[1], v4.h[0]
fmov d0, d2
ret
```

What we would have prefered : `fmul h4, h0, h2`.

It seems the `mov/dup` occurs no matter what, so prefering the indexed instruction to the scalar one is not the most cost effective.

I'll take a look at the differences between the intermediate DAG and write it down here.

**Comment by overmighty** [comment] 2023-07-06 06:37
I'd like to keep looking into this too but I started an internship now so I don't have as much time anymore. Do you think we should continue the conversation here?

**Comment by v01dXYZ** [comment] 2023-07-06 09:02
We can open a new Github issue or you can directly message me (I find this discovery very funny as the guy was used to make things explode contrasting with the importance of this advancement):

``` python
l = [1686, 1965, 1126, 847, 1686, 1500, 1866, 940, 1219,
      942, 475, 192, 1035, 1219, 568, 1965, 1965, 1866, 754, 1686]

# https://www.computerhistory.org/siliconengine/development-of-oxide-masking/
unexpected_discovery_surface_passivation_with_silicon_oxyde = ...

print(bytes(
  pow(
    unexpected_discovery_surface_passivation_with_silicon_oxyde,
    -1,
    2048,
  ) * b % 2048 for b in l
))
```

**Comment by overmighty** [comment] 2023-07-07 14:45
@SamTebbs33 Could you reopen this issue?

**Comment by v01dXYZ** [comment] 2023-07-09 07:13
I think the regression is not really introduced by your patch. If I modify a little bit the regression case to force the element to be 1 or 2 indexed, it would necessary generate dup for the other instructions that use the values.

``` llvm
target triple = "aarch64-unknown-linux-gnu"

define <2 x half> @complex_mul_v2f16(<3 x half> %a, <3 x half> %b) #0 {
entry:
  %a.real = shufflevector <3 x half> %a, <3 x half> poison, <1 x i32> <i32 1>
  %a.imag = shufflevector <3 x half> %a, <3 x half> poison, <1 x i32> <i32 2>
  %b.real = shufflevector <3 x half> %b, <3 x half> poison, <1 x i32> <i32 1>
  %b.imag = shufflevector <3 x half> %b, <3 x half> poison, <1 x i32> <i32 2>
  %0 = fmul fast <1 x half> %b.imag, %a.real
  %1 = fmul fast <1 x half> %b.real, %a.imag
  %2 = fadd fast <1 x half> %1, %0
  %3 = fmul fast <1 x half> %b.real, %a.real
  %4 = fmul fast <1 x half> %a.imag, %b.imag
  %5 = fsub fast <1 x half> %3, %4
  %interleaved.vec = shufflevector <1 x half> %5, <1 x half> %2, <2 x i32> <i32 0, i32 1>
  ret <2 x half> %interleaved.vec
}

attributes #0 = { "target-features" = "+fullfp16,+neon" }
```

The output which is the same prior and post your patch:

``` asm
complex_mul_v2f16:                      // @complex_mul_v2f16
        .cfi_startproc
// %bb.0:                               // %entry
                                        // kill: def $d1 killed $d1 def $q1
                                        // kill: def $d0 killed $d0 def $q0
        mov     h2, v0.h[2]
        mov     h3, v1.h[2]
        mov     h4, v0.h[1]
        fmul    h5, h3, v0.h[1]
        fnmul   h0, h2, h3
        fmla    h5, h2, v1.h[1]
        fmla    h0, h4, v1.h[1]
        mov     v0.h[1], v5.h[0]
                                        // kill: def $d0 killed $d0 killed $q0
        ret
```

It selects a indexed fmul instruction for `v0.h[1]` while there is already a `DUP` to `h4`.

**Comment by overmighty** [comment] 2023-07-09 13:19
I somehow messed up in some of my earlier comments. I corrected the one where I had said that there is a case where the new indexed patterns cause indexed instructions to be used where "the scalar instructions were already being used" and the one where I said there is a regression. Indexed instructions were already being used in that case before my patch, it's just that we now generate a different indexed instruction whereas we could generate a scalar instruction in that case too. So it's not a regression, it's just that the issue isn't really entirely fixed.

Maybe I had gotten a scalar instruction to be generated in that case when I only had the new scalar patterns, but adding the new indexed patterns too to fix cases where extra `mov`s were being generated "unfixed" that `complex_mul_v2f16` case and I confused it for an actual regression when writing those comments.

Also, it's good to know that there were cases of indexed `fmul` not using the destination register of a previous `mov` before my patch already. Thanks.

**Comment by overmighty** [comment] 2023-07-09 20:45
Maybe we just shouldn't try to generate scalar `fmul` in this `complex_mul_v2f16` case. "ASIMD duplicate, element" has 2 cycles of latency on the Cortex-A55 according to the Arm Software Optimization Guide for it, so adding a dependency on a `mov`/`dup` to an `fmul` instruction to use the scalar variant instead of the indexed variant would actually be a regression I think.

Maybe you should just submit your patch to fix the remaining cases of indexed `fmul` being used with lane 0.

**Comment by overmighty** [comment] 2023-08-15 18:26
> Maybe you should just submit your patch to fix the remaining cases of indexed `fmul` being used with lane 0.

@v01dXYZ Ping.
