### ISSUE TITLE
[clang-format] Misformatted scope braces 

### ISSUE THREAD

**Issue by zxwreg** [llvm/llvm-project#56756] opened 2022-07-27 15:34 UTC
clang-format version: **14.0.6**

<img width="172" alt="Screen Shot 2022-07-27 at 8 31 44 AM" src="https://user-images.githubusercontent.com/37418875/181288518-75b98e07-284a-4fb5-828b-5554f3549b71.png">

Tried to format above file (can't upload cpp file so used png) using command: `clang-format -style=google a.cpp`, and got

```cpp
namespace A {
namespace B {
namespace C {

void x() {}

void f() {
  { {{x(); }
}

{ x(); }
}  // namespace C
}  // namespace B

}  // namespace A
}
}
```

I expected no changes to the code itself except adding the comments for ending namespace.

**Comment by rymiel** [comment] 2023-01-01 18:30
Duplicate of https://github.com/llvm/llvm-project/issues/33891

**Closed by rymiel** 2023-01-01 18:30 UTC
Labels: clang-format
