### ISSUE TITLE
[clang++] Crash when calling coroutine handle.destroy() in await suspend()

### ISSUE THREAD

**Issue by FunMiles** [llvm/llvm-project#67828] opened 2023-09-29 16:16 UTC
This is a bump up of [issue 67828 ](https://github.com/llvm/llvm-project/issues/62335). The reason I am bring it back here is that the problem exists with the brew version of clang++ version 15 ( https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/llvm-project-15.0.7.src.tar.xz ).
So it does not seem to be an issue introduced by apple's LLVM fork.

 @ChuanqiXu9 if you need me to run a local version of godbolt for you, I can certainly do it.

The code is
```cpp
#include <iostream>
#include <coroutine>
namespace crt = std;

struct Timer {
    auto die_or_return(int t, bool destroy_handle=false)
    {
        struct awaiter {
            bool await_ready() const noexcept { return false; }

            void await_resume() const noexcept {}
            /* https://en.cppreference.com/w/cpp/language/coroutines states:
             * The coroutine is suspended (its coroutine state is populated with local variables and current suspension point).
             * awaiter.await_suspend(handle) is called, where handle is the coroutine handle representing the current coroutine.
             * Inside that function, the suspended coroutine state is observable via that handle,
             * and it's this function's responsibility to schedule it to resume on some executor,
             * or to be destroyed (returning false counts as scheduling)
             */
            crt::coroutine_handle<> await_suspend(crt::coroutine_handle<> h) noexcept
            {
                auto n = next; // Making this variable thread_local is a workaround.
                if (destroy_handle) {
                    h.destroy();
                }
                return n;
            }
            crt::coroutine_handle<> next;
            bool destroy_handle;
        };

        return awaiter{ender, destroy_handle};
    }

    crt::coroutine_handle<> ender = crt::noop_coroutine();
};

inline static bool active{true};

struct [[nodiscard]] autodestruct_task {
    struct promise_type {
        ~promise_type() { active = false; std::cout << "Dying" << std::endl; }
        autodestruct_task get_return_object() noexcept
        {
            return autodestruct_task{crt::coroutine_handle<promise_type>::from_promise(*this)};
        }

        crt::suspend_always initial_suspend() noexcept { return {}; }

        /// If the coroutine does not suspend at the end, its handle is automatically
        /// destroyed.
        crt::suspend_never final_suspend() noexcept {return {}; }

        void return_void() noexcept {}

        void unhandled_exception() noexcept { std::terminate(); }
    };

    crt::coroutine_handle<promise_type> handle;

    explicit autodestruct_task(crt::coroutine_handle<promise_type> h) noexcept : handle(h) {}

};

autodestruct_task test_death(Timer &timer) {
    co_await timer.die_or_return(0,true);
}

autodestruct_task end_task() {
    std::cout << "Ending" << std::endl;
    co_return;
}

int main() {
    Timer timer;
    timer.ender = end_task().handle;
    auto tsk_handle = test_death(timer).handle;
    while (active && !tsk_handle.done()) {
        std::cout << "Resume" << std::endl;
        tsk_handle();
    }
}
```

**Comment by ChuanqiXu9** [comment] 2023-10-02 10:03
I don't understand what the problem is from godbolt: https://godbolt.org/z/7jvhTr376. It will be helpful to present this in godbolt.

**Comment by apolloww** [comment] 2023-11-06 19:14
I think the issue is likely fixed by https://github.com/llvm/llvm-project/commit/c4672454743e942f148a1aff1e809dae73e464f6

**Comment by FunMiles** [comment] 2023-11-06 22:46
> I think the issue is likely fixed by [c467245](https://github.com/llvm/llvm-project/commit/c4672454743e942f148a1aff1e809dae73e464f6)

It looks like it addresses very similar issues that I think share their cause with my test above.

Is there a way I can test that it does indeed fix it? It seems I should build the compiler once without that commit and once with it and confirm that the first one crashes and the second doesn't. Is that the best approach to test?

**Comment by ChuanqiXu9** [comment] 2023-11-07 01:09
> > I think the issue is likely fixed by [c467245](https://github.com/llvm/llvm-project/commit/c4672454743e942f148a1aff1e809dae73e464f6)
> 
> It looks like it addresses very similar issues that I think share their cause with my test above.
> 
> Is there a way I can test that it does indeed fix it? It seems I should build the compiler once without that commit and once with it and confirm that the first one crashes and the second doesn't. Is that the best approach to test?

Yeah, I think this is the approach.

**Comment by FunMiles** [comment] 2023-11-10 16:13
> > > I think the issue is likely fixed by [c467245](https://github.com/llvm/llvm-project/commit/c4672454743e942f148a1aff1e809dae73e464f6)
> > 
> > 
> > It looks like it addresses very similar issues that I think share their cause with my test above.
> > Is there a way I can test that it does indeed fix it? It seems I should build the compiler once without that commit and once with it and confirm that the first one crashes and the second doesn't. Is that the best approach to test?
> 
> Yeah, I think this is the approach.

This may not be the best place to ask, but I did try this and though I can successfully compile and install LLVM with clang/clang++, when trying to compile something using <iostream>, I do get errors. I tried to put a `-I<MacOS SDK include path>` and get some errors as well as `-I<homebrew LLVM 16 include path>` where I get different errors.
Is there somewhere to find the proper cmake arguments/install commands to get everything working correctly? I will look at what homebrew does, but I think it is concerned with more things that I need.

**Comment by ChuanqiXu9** [comment] 2023-11-13 01:49
> > > > I think the issue is likely fixed by [c467245](https://github.com/llvm/llvm-project/commit/c4672454743e942f148a1aff1e809dae73e464f6)
> > > 
> > > 
> > > It looks like it addresses very similar issues that I think share their cause with my test above.
> > > Is there a way I can test that it does indeed fix it? It seems I should build the compiler once without that commit and once with it and confirm that the first one crashes and the second doesn't. Is that the best approach to test?
> > 
> > 
> > Yeah, I think this is the approach.
> 
> This may not be the best place to ask, but I did try this and though I can successfully compile and install LLVM with clang/clang++, when trying to compile something using `#include <iostream>`, I do get errors. I tried to put a `-I<MacOS SDK include path>` and get some errors as well as `-I<homebrew LLVM 16 include path>` where I get different errors. Is there somewhere to find the proper cmake arguments/install commands to get everything working correctly? I will look at what homebrew does, but I think it is concerned with more things than I need.

There are some headers from `bin/clang/../lib/clang/version/...`. This is a common issue. Maybe you can find som solutions by searching it. Generally, you can choose to not install clang/llvm. And invoke the build clang from the build dir directly.

**Comment by FunMiles** [comment] 2023-11-14 02:30
I found a solution. For others who may read this, it is to use:
```
export SDKROOT="`xcrun --show-sdk-path`"
```
and then calling the compiler.

The good news is that the previous commit (7c4e8c6) crashes while c467245 works. If there is no other issue, it should close this thread.
What expected release should have this fix?

**Comment by ChuanqiXu9** [comment] 2023-11-14 03:03
> I found a solution. For others who may read this, it is to use:
> 
> ```
> export SDKROOT="`xcrun --show-sdk-path`"
> ```
> 
> and then calling the compiler.
> 



> The good news is that the previous commit ([7c4e8c6](https://github.com/llvm/llvm-project/commit/7c4e8c6a273f25b3ef33e9c123b3969632ab59bb)) crashes while [c467245](https://github.com/llvm/llvm-project/commit/c4672454743e942f148a1aff1e809dae73e464f6) works. If there is no other issue, it should close this thread. 

Thanks for looking into this!

> What expected release should have this fix?

It should be clang18.

**Closed by ChuanqiXu9** 2023-11-14 03:03 UTC
Labels: coroutines

**Comment by FunMiles** [comment] 2023-11-14 14:57
To give credit where it is due, the `SDKROOT` solution was found in this blog post: https://andreasfertig.blog/2021/02/clang-and-gcc-on-macos-catalina-finding-the-include-paths/
