### ISSUE TITLE
Error: Compilation of files not involved and not needed in the project

### ISSUE THREAD

**Issue by LeonidBolyukh** [llvm/llvm-project#116981] opened 2024-11-20 14:41 UTC
When compiling a project with the Сlang compiler, a set of errors occurs related to the compilation of third-party files that are not
are used in the project. Also, these files are not planned to be used in the future. Please provide a way to disable these files
with a ban on compiling them in our project..

    Compiling ext file abs.c
    Compiling ext file heap.c
    Compiling ext file memcmp.c
    Compiling ext file memcpy.c
    Compiling ext file memset.c
/Users/macmini/builds/_z-Kurf-/0/repo/middleware-capsense/output/libs/TOOLCHAIN_A_Clang/abs.c:64:1: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C23 [-Werror,-Wdeprecated-non-prototype]
   64 | abs(j)
      | ^
1 error generated.
make[1]: *** [/Users/macmini/builds/_z-Kurf-/0/repo/middleware-capsense/output/test/sut/capsense/library/A_Clang/CY8C6347BZI-BLD53/Debug/ext/output/libs/TOOLCHAIN_A_Clang/abs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/Users/macmini/builds/_z-Kurf-/0/repo/middleware-capsense/output/libs/TOOLCHAIN_A_Clang/memcpy.c:73:73: error: unused parameter 'slen' [-Werror,-Wunused-parameter]
   73 | void *__memcpy_chk(void * __restrict a, const void *b, size_t n, size_t slen)
      |                                                                         ^
1 error generated.
make[1]: *** [/Users/macmini/builds/_z-Kurf-/0/repo/middleware-capsense/output/test/sut/capsense/library/A_Clang/CY8C6347BZI-BLD53/Debug/ext/output/libs/TOOLCHAIN_A_Clang/memcpy.o] Error 1
make: *** [secondstage_build] Error 2
cpp_test_p6

**Comment by AaronBallman** [comment] 2024-11-20 15:02
Clang compiles the files you tell it to compile, so this sounds like an issue with your build system. Closing the issue as there's not a bug with Clang here, but feel free to reopen with more detail if I've misunderstood your issue.

**Closed by AaronBallman** 2024-11-20 15:02 UTC
Labels: new issue
