### ISSUE TITLE
Failed Template Deduction in C++20 Designated Initializers

### ISSUE THREAD

**Issue by marstaik** [llvm/llvm-project#56394] opened 2022-07-05 23:32 UTC
Tested with clang 14.0

When a template field is initialized via designated initializers, clang fails to deduce the final specialization.

Code example:
```cpp
template<typename T>
struct Foo {
    int foo;
    T bar;
};

int main() {
    constexpr auto foo = Foo {
        .foo = 1,
        .bar = +[]() { return 5; }
    };

    constexpr auto eval = foo.bar();
    
    return 0;
}
```

Note that this works succesfully in MSVC and GCC:

MSVC: https://godbolt.org/z/qr5a56xbs
GCC: https://godbolt.org/z/sqc4r1Eb4
clang: https://godbolt.org/z/P1c3v7Gfj

The compiler reports:
```
x86-64 clang 14.0.0 - 358ms

<source>:8:26: error: no viable constructor or deduction guide for deduction of template arguments of 'Foo'
    constexpr auto foo = Foo {
                         ^
<source>:2:8: note: candidate function template not viable: requires 1 argument, but 2 were provided
struct Foo {
       ^
<source>:2:8: note: candidate function template not viable: requires 0 arguments, but 2 were provided
1 error generated.
ASM generation compiler returned: 1
<source>:8:26: error: no viable constructor or deduction guide for deduction of template arguments of 'Foo'
    constexpr auto foo = Foo {
                         ^
<source>:2:8: note: candidate function template not viable: requires 1 argument, but 2 were provided
struct Foo {
       ^
<source>:2:8: note: candidate function template not viable: requires 0 arguments, but 2 were provided
1 error generated.
Execution build compiler returned: 1
```

**Comment by marstaik** [comment] 2022-07-05 23:42
@EugeneZelenko  I think this is more of a clang-frontend issue than a clang-format issue :P

**Comment by EugeneZelenko** [comment] 2022-07-05 23:43
@marstaik: Sorry for my mistake. Fixed.

**Comment by schwarzschild-radius** [comment] 2022-07-18 17:11
I think it is because of missing deduction candidate. Here is a smaller repro (https://godbolt.org/z/b4v14T74d)

```c++
template<typename T>
struct Foo {
    int foo;
    T bar;
};

int main() {
    auto foo = Foo {1, 0.5};
    return 0;
}
```

**Comment by alanzhao1** [comment] 2022-08-23 23:27
Fixing this is going to be somewhat complicated

Currently, template argument deduction is centered [around functions](https://github.com/llvm/llvm-project/blob/af7edf1557d87026bb4dd4783f60e766538e923c/clang/lib/Sema/SemaTemplateDeduction.cpp#L4220). Functions cover things such as constructors. Aggregate initializers, however, [do not fit this model](https://github.com/llvm/llvm-project/blob/af7edf1557d87026bb4dd4783f60e766538e923c/clang/lib/Sema/SemaOverload.cpp#L5181-L5207), so I think there might be a good amount of refactoring necessary to resolve this.

**Comment by danakj** [comment] 2022-11-06 23:20
Even smaller repro: https://godbolt.org/z/xqbde4hfM

```cpp
template <class T>
struct S {
    T t;
};

S s{.t = int(3)};
```

**Comment by alanzhao1** [comment] 2022-11-07 00:45
I believe this bug is a duplicate of #54050 and #54049, both of which are track the implementation of class template argument deduction for aggregates as described in [P1816R0](https://wg21.link/p1816r0) and [P2082R1](https://wg21.link/p2082r1).

**Comment by yuanfang-chen** [comment] 2023-07-05 16:53
duplicates #54049 and #54050

**Closed by yuanfang-chen** 2023-07-05 16:53 UTC
Labels: duplicate, c++20, clang:frontend
