### ISSUE TITLE
std::vector rotate crash

### ISSUE THREAD

**Issue by devilsclaw** [llvm/llvm-project#62005] opened 2023-04-07 15:41 UTC
The crash only happens on windows and not in Linux and I have tested it on an online compiler as well.

The below code is just moving an item from one index position to another and it crashes

If I am doing something wrong let me know but it would be weird that it works everywhere else but the windows builds

Toolchains tested in windows are:
llvm-mingw-20220323-msvcrt-i686
llvm-mingw-20230320-msvcrt-i686
llvm-mingw-20230320-msvcrt-x86_64

my target app is 32bit due to dependencies but it currently can be build for 64bit to test.

`
#include <cstdio>
#include <cstring>
#include <string>

template<typename T>
void set_zorder(std::vector<T> v, T id, int index) {
  if(index >= v.size()) {
    return;
  }

  auto it = std::find(v.begin(), v.end(), id);
  if(it != v.end()) {
    std::rotate(it, it + 1, v.begin() + 1 + index);
  }
}

int main(int argc, char** argv) {
  std::vector<int> values = {1, 2, 3, 4, 5, 6, 7, 8, 9 , 10};
  printf("BEFORE: = { ");
  for(auto value : values) {
    printf("%i, ", value);
  }
  printf("}\n");

  set_zorder<int>(values, 9, 0);

  printf("AFTER : = { ");
  for(auto value : values) {
    printf("%i, ", value);
  }
  printf("}\n");
  return 0;
}
`

**Comment by DimitryAndric** [comment] 2023-04-07 15:45
duplicate of #62006

**Closed** 2023-04-07 16:14 UTC
Labels: duplicate
