### ISSUE TITLE
This makes your program crash at load time

### ISSUE THREAD

**Issue by jacob-navia** [llvm/llvm-project#58450] opened 2022-10-18 18:40 UTC
Consider this assembly code:

```s
.section __TEXT,text,regular,pure_instructions
_foo:
     adrp x14,Lswitch@PAGE
      add x14,x14,Lswitch@PAGEOFF // Get the address of a jump table into x14
      ldp q0,q1,[x0,16]
      ldr x15,[x14,x10,lsl 3] // Get the label you want to jump into by indexing the jump table
      ldp q2,q3,[x0,48]
      br x15.     // do it: jump to the label
```

At the end of the assembler file I have the jump table:
```s
Lswitch:
    .quad L_ERROR
    .quad L_DO_1
    .quad L_DO_2
    .quad L_DO_3
    .quad L_DO_4
    .quad L_DO_5
    .quad L_DO_6
    .quad L_DO_7
    .quad L_ERROR
    .quad L_ERROR
    .quad L_ERROR
    .quad L_ERROR
    .quad L_ERROR
```

The program will assemble correctly and link correctly but the dynamic loader will crash with:
```
(lldb) run
Process 17303 launched: '/Users/jacob/lcc/qlibarm64/qtime' (arm64)
Process 17303 stopped
* thread #1, stop reason = EXC_BAD_ACCESS (code=2, address=0x10000f5f0)
    frame #0: 0x0000000100039a54 dyld`invocation function for block in dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const + 60
dyld`invocation function for block in dyld4::Loader::applyFixupsGeneric(Diagnostics&, dyld4::RuntimeState&, dyld3::Array<void const*> const&, dyld3::Array<void const*> const&, bool, dyld3::Array<dyld4::Loader::MissingFlatLazySymbol> const&) const:
->  0x100039a54 <+60>: str    x19, [x20]
```
 The program crashes in the dynamic loader. It costed me 3 days of work to figure this stuff out.
1) What is the correct way to layout a jump table?
2) Could you PLEEEEEEZE make some error message hinting at the error instead of the incomprehensible stuff?

Thanks in advance guys!

Jacob

P.S. I have tried to put it in the text segment, the data segment, it always crashes. OI tried doing:
`ldr x14,=Lswitch`

and then `.pool` later

It also crashes.

This is so difficult to find because the assembler code was in a library within a fairly big program. Just linking with the library
suffices to crash the program. Note that NO ERRORS were issued by the assembler. The relocations looked fairly normal also.

**Comment by BertalanD** [comment] 2022-12-04 10:23
Because this issue doesn't have a complete standalone reproducer, I can only speculate what's happening.

Unless you have a `.data` directive that you didn't include in the report, the jump table ends up in the text segment along with the code. The `.quad L_ERROR` expression means that the *address* of the label needs to be stored in that memory location. As macOS uses position-independent code,  the address of the label is not know until load time, so `dyld` needs to relocate it (hence the call to `dyld4::Loader::applyFixupsGeneric`). But the text segment is read-only, so attempting to write to it will trigger an access violation.

>  Is this a badly formed program?

If you run `dyld_info -validate_only` on your executable, you will likely see that it's invalid:

```console
❯ dyld_info -validate_only a.out
dyld_info: 'a.out' in 'a.out' REBASE_OPCODE_DO_REBASE_IMM_TIMES pointer rebase is in non-writable segment
```

> What is the correct way to layout a jump table?

You could take a look at some compiler-generated code, like [this one](https://godbolt.org/z/Trsjr7eGr). I think the most common approach is to keep the jump table in the text segment, but store offsets rather than absolute addresses (e.g. `.long Lswitch - L_ERROR`), which does not require run-time fixups. You can then add the base address (`Lswitch`) to the loaded offset to get the address. I'm not a compiler developer though, so there are probably other approaches I don't know about.

>  I have used the LLVM ASSEMBLER, the LLVM LINKER and Mac OS X Loader (also LLVM)

The default linker on Apple platforms (`ld64`) is not part of the LLVM project, so we can't do anything about it. I do think that warning on invalid fixups like here would be useful, so I'll look into adding checks to the LLD linker. If you want Apple's linker or `dyld` to diagnose it too, you should open a feature request via Feedback Assistant. 

I'm closing this issue as I don't think LLVM tools are doing anything incorrect here. Feel free to re-open it though if you think I missed something.

**Closed** 2022-12-04 10:24 UTC
Labels: new issue

**Comment by BertalanD** [comment] 2023-01-05 11:54
> If you want Apple's linker or dyld to diagnose it too, you should open a feature request via Feedback Assistant.

I have filed FB11923322 for the missing diagnostic in dyld.
