### ISSUE TITLE
Compiler flag '-Warray-compare' not implemented

### ISSUE THREAD

**Issue by stephenLucien** [llvm/llvm-project#114770] opened 2024-11-04 10:26 UTC
clangd version
```shell
[li@ArchLinux-li cpp]$ clangd --version
clangd version 18.1.8
Features: linux
Platform: x86_64-pc-linux-gnu
[li@ArchLinux-li cpp]$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 18.1.8
  Optimized build.
```

my `.clangd` file:
```yaml
Diagnostics:
    ClangTidy:
        Remove: 
            - modernize-use-trailing-return-type
            - modernize-use-nullptr
            - modernize-use-using
            - modernize-use-bool-literals
            - modernize-use-equals-default
            - modernize-avoid-c-arrays
            - modernize-redundant-void-arg
            - modernize-deprecated-headers
            - bugprone-easily-swappable-parameters
        Add: 
            - modernize*
            - bugprone-* 
            - performance-*
CompileFlags:
    Add: 
        - "-ferror-limit=0"
        - "-fdelete-null-pointer-checks"
        - "-Wall"
        - "-Wextra"
        - "-Wpedantic"
        - "-Wformat=2"
        - "-Wnull-dereference"
        - "-Wpointer-compare"
        - "-Wstring-compare"
        - "-Warray-compare"
        - "-Wno-unused-but-set-variable"
        - "-Wno-unused-but-set-parameter"
        - "-Wno-unused-variable"
        - "-Wno-unused-parameter"
        - "-Wno-unused-label"
        - "-Wno-unused-function"
        
```

my test code `main.cpp`:
```cpp

#include <iostream>

typedef struct {
  char str[16];
  int id[16];
} MyObj;

bool myobj_equal(const MyObj &obj1, const MyObj &obj2) {
  if (obj1.str != obj2.str) // compare array here, expect warning !!!
    return false;
  if (obj1.id != obj2.id) // compare array here, expect warning !!!
    return false;
  return true;
}

int main(int argc, char *argv[]) {
  //
  char str1[16] = "hello";
  char str2[16] = "hello";
  if (str1 == str2) {
    std::cout << "same string";
  }
  //
  MyObj a1 = {.str = "hello"};
  MyObj a2 = {.str = "hello"};
  if (myobj_equal(a1, a2)) {
    std::cout << "same obj";
  }
  return 0;
}

```

only the following warnings pops up:
![image](https://github.com/user-attachments/assets/dea82e61-02e4-4cbe-942d-e6795e7fdcc7)

**Comment by AaronBallman** [comment] 2024-11-05 17:34
Clang doesn't implement `-Warray-compare`, which is why you're seeing this: https://godbolt.org/z/dMPs5oE8s

I've changed the issue to be a feature request instead.

**Comment by AmrDeveloper** [comment] 2024-11-20 22:00
If it is approved and has priority, I will be interested in implementing it :D

**Comment by AaronBallman** [comment] 2024-11-21 13:53
> If it is approved and has priority, I will be interested in implementing it :D

We'd love to see an implementation for it; I'll assign this to you.

**Comment by AmrDeveloper** [comment] 2024-11-21 18:35
> > If it is approved and has priority, I will be interested in implementing it :D
> 
> We'd love to see an implementation for it; I'll assign this to you.

Thank you

**Comment by AmrDeveloper** [comment] 2024-11-21 21:08
What GCC does is producing waring for all versions, but for C++20 or above it mention that this comparison is deprecated, i think we can implement the same in Clang

-Wall -std=c++23
```
warning: comparison between two arrays is deprecated in C++20 [-Warray-compare])
```

-Wall
```
warning: comparison between two arrays [-Warray-compare]
```

**Comment by AaronBallman** [comment] 2024-11-22 14:24
Ah! Good investigation! Yes, I think we should do the same in Clang, but we have to figure out what to do about the warning group name.

Clang adds this under `-Wdeprecated` because it's a deprecation warning, GCC does not: https://godbolt.org/z/7E1W5d79M I prefer Clang's behavior in this case.

We could add `-Warray-compare` as an alias to `-Wdeprecated-array-compare` for compatibility with GCC, but should that spelling also be under `-Wdeprecated`?

**Comment by AmrDeveloper** [comment] 2024-11-22 20:24
> We could add -Warray-compare as an alias to -Wdeprecated-array-compare for compatibility with GCC, but should that spelling also be under -Wdeprecated?

I am not sure because it's deprecated for C++20 or more but if we run with C++17 i think it's not to be in deprecated category 🤔

**Comment by erichkeane** [comment] 2024-11-25 19:01
> Ah! Good investigation! Yes, I think we should do the same in Clang, but we have to figure out what to do about the warning group name.
> 
> Clang adds this under `-Wdeprecated` because it's a deprecation warning, GCC does not: https://godbolt.org/z/7E1W5d79M I prefer Clang's behavior in this case.
> 
> We could add `-Warray-compare` as an alias to `-Wdeprecated-array-compare` for compatibility with GCC, but should that spelling also be under `-Wdeprecated`?
> 
> Tagging [@erichkeane](https://github.com/erichkeane) [@MaskRay](https://github.com/MaskRay) [@jansvoboda11](https://github.com/jansvoboda11) for additional opinions

I concur.  I think we want to keep 2 separate warnings.  1 is a C++20 warning inside of 'deprecated', a 2nd is for non-C++20 mode that just warns about it.  But part of the problem is we should emit ONE of the two at all times, and I'm worried about cases where `deprecated` is disabled in C++20+ mode.  I also don't want us emitting duplicate diagnostics in the other case.

SO perhaps some level of checking to see if it is !C++20 || C++20-warning-not-enabled as the choice between the diags?

**Comment by AmrDeveloper** [comment] 2024-11-26 17:48
> C++20-warning-not-enabled

For `C++20-warning-not-enabled` you mean `-Wc++20-extensions` to enable C++20 warning there are another options to enable full warnings?

**Comment by AaronBallman** [comment] 2024-11-26 17:51
> SO perhaps some level of checking to see if it is !C++20 || C++20-warning-not-enabled as the choice between the diags?

Okay, so what I think you're advocating for is that in C++17 and earlier modes, or in C++20 mode with `-Wno-deprecated-array-compare`, you'll get `comparison between two arrays; to compare array addresses, use unary '+' to decay operands to pointers` under `-Warray-compare`, and in C++20 mode you'll get `comparison between two arrays is deprecated; to compare array addresses, use unary '+' to decay operands to pointer` under `-Wdeprecated-array-compare`?

**Comment by erichkeane** [comment] 2024-11-26 17:55
> > C++20-warning-not-enabled
> 
> For `C++20-warning-not-enabled` you mean `-Wc++20-extensions` to enable C++20 warning there are another options to enable full warnings?

Just any situation where that warning is disabled in some way (we have a mechanism of checking that).

> > SO perhaps some level of checking to see if it is !C++20 || C++20-warning-not-enabled as the choice between the diags?
> 
> Okay, so what I think you're advocating for is that in C++17 and earlier modes, or in C++20 mode with `-Wno-deprecated-array-compare`, you'll get `comparison between two arrays; to compare array addresses, use unary '+' to decay operands to pointers` under `-Warray-compare`, and in C++20 mode you'll get `comparison between two arrays is deprecated; to compare array addresses, use unary '+' to decay operands to pointer` under `-Wdeprecated-array-compare`?

I THINK so?  Basically, in C++ 20 mode, emit the `-Wdeprecated-array-compare`, unless it is disabled.  Else, emit `-Warray-compare`.  In all other modes, emit `-Warray-compare`.

**Closed** 2024-12-04 18:33 UTC
Labels: enhancement, clang:diagnostics
