### ISSUE TITLE
[RISCV] llc -compile-twice -filetype=obj generates mysterious ".apple_objc"

### ISSUE THREAD

**Issue by alexfanqi** [llvm/llvm-project#55548] opened 2022-05-18 08:33 UTC
test case
```llvm
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64-unknown-linux-gnu"
```
llc output
```console
# fail
> llc -compile-twice -filetype=obj -mattr=+m,+a,+f,+d,+c test.ll -o twice.o
Running the pass manager twice changed the output.
Writing the result of the second run to the specified output
To generate the one-run comparison binary, just run without
the compile-twice option
```
use readelf -a and compare the output with and without -compile-twice:
```txt
13,14c13,14
<   Start of section headers:          232 (bytes into file)
<   Flags:                             0x0
---
>   Start of section headers:          240 (bytes into file)
>   Flags:                             0x1, RVC, soft-float ABI
28c28
<        000000000000003b  0000000000000000           0     0     1
---
>        0000000000000041  0000000000000000           0     0     1
33,34c33,34
<   [ 4] .apple_objc       PROGBITS         0000000000000000  00000040
<        0000000000000034  0000000000000000           0     0     1
---
>   [ 4] .riscv.attributes RISCV_ATTRIBUTE  0000000000000000  00000040
>        0000000000000035  0000000000000000           0     0     1
58a59,62
> Attribute Section: riscv
> File Attributes
>   Tag_RISCV_stack_align: 16-bytes
>   Tag_RISCV_arch: "rv64i2p0_m2p0_a2p0_f2p0_d2p0_c2p0"
```

This is a major block for the Julia riscv port to bootstrap a compiler successfully. Similar issues seem to have happened before in [ppc](https://github.com/llvm/llvm-project/issues/26752) and [arm](https://reviews.llvm.org/D15950). 

I understand that -compile-twice is probably not supported atm, but it would help the Julia riscv port a lot to at least get around the mysterious .apple_objc mixed in, as that seems to cause an incompatible cast into MCSymbolELF in Julia. Something looks like
```console
julia: /var/tmp/portage/sys-devel/llvm-14.0.1/work/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_r
etty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::MCSymbolELF; Y = llvm::MCSymbol; typename llvm::cast_retty<X, Y*>::ret_type = llvm::MCSymbolELF*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

**Comment by luxufan** [comment] 2022-05-18 12:28
Are you using a release version of `llc` tool? I run the same command for my Debug version of `llc` and it crashed.

**Comment by kito-cheng** [comment] 2022-05-18 15:57
Confirmed, but I didn't get crashed on my debug build...

**Comment by luxufan** [comment] 2022-05-18 16:37
As what `Arm` did, we need to set `AttributeSection` to `nullptr` when we reset all of the MC things.  
Since we don't do that currently, `AttributeSection` will be used again when we compile secondly. And some symbols related to `AttributeSection` will also be used. This may also be the reason for my `llc` crash.

**Comment by kito-cheng** [comment] 2022-05-18 16:54
https://reviews.llvm.org/D125905

**Comment by alexfanqi** [comment] 2022-05-19 06:37
Thanks @kito-cheng and @luxufan, the patch seems to have fixed the issue in Julia.

**Comment by alexfanqi** [comment] 2022-05-20 06:53
Ah, It seems the target-abi flags got removed even if -target-abi=lp64d is specified.
 ```
llc -target-abi=lp64d -compile-twice -filetype=obj -mattr=+m,+a,+f,+d test.ll -o a1.o
llc -target-abi=lp64d -filetype=obj -mattr=+m,+a,+f,+d test.ll -o a.o
diff <(readelf -a a.o) <(readelf -a a1.o)
```
gives
```
14c14
<   Flags:                             0x4, double-float ABI
---
>   Flags:                             0x0
```

**Comment by luxufan** [comment] 2022-05-20 15:01
> Ah, I found new issues. It seems the target-abi flag is lost even if -target-abi=lp64d is specified. That results in the hard float ELFHeaderEFlags is missing and linker issue. Looks like `MCELFStreamer::reset();` drops that flag.
> 
> ```
> llc -target-abi=lp64d -compile-twice -filetype=obj -mattr=+m,+a,+f,+d test.ll -o a1.o
> llc -target-abi=lp64d -filetype=obj -mattr=+m,+a,+f,+d test.ll -o a.o
> diff <(readelf -a a.o) <(readelf -a a1.o)
> ```
> 
> gives
> 
> ```
> 14c14
> <   Flags:                             0x4, double-float ABI
> ---
> >   Flags:                             0x0
> ```
Is your llvm code the latest? I think https://reviews.llvm.org/D121183 can solve your problem.

**Comment by alexfanqi** [comment] 2022-05-20 23:18
> Is your llvm code the latest? I think https://reviews.llvm.org/D121183 can solve your problem.

You are right. I was using a llvm version that corresponds to Julia's bundled one and add in patches if necessay. With this additional patch compiled in, the issue is solved.

**Comment by kito-cheng** [comment] 2022-05-26 08:10
Fixed via https://github.com/llvm/llvm-project/commit/e45087fd53d5946f47efa7bb7be088c668c386a1

**Closed by kito-cheng** 2022-05-26 08:10 UTC
Labels: backend:RISC-V
