### ISSUE TITLE
Nested CTAD fails with "could not match 'inner_foo<T2>' against 'int'"

### ISSUE THREAD

**Issue by royjacobson** [llvm/llvm-project#57812] opened 2022-09-18 19:43 UTC
CTAD on this example:

```C++
template <class T1>
struct outer_foo {
  template <class T2>
  struct inner_foo {
    inner_foo(const T2& t);
  };
};

void f() {
  auto X = outer_foo<int>::inner_foo(1);
}
```
fails with 
```console
<source>:10:12: error: no viable constructor or deduction guide for deduction of template arguments of 'inner_foo'
  auto X = outer_foo<int>::inner_foo(1);
           ^
<source>:4:10: note: candidate template ignored: could not match 'inner_foo<T2>' against 'int'
  struct inner_foo {
         ^
<source>:4:10: note: candidate function template not viable: requires 0 arguments, but 1 was provided
1 error generated.
Compiler returned: 1
```

https://godbolt.org/z/Ea9j6GxdP

**Comment by royjacobson** [comment] 2022-09-18 19:55
I _think_ that due to some laze evaluation thing, when we call `DeclareImplicitDeductionGuides` on `inner_foo`, we haven't added `inner_foo`'s constructors yet into the ClassTemplateDecl so we get the default deduction guide for classes without a constructor and this error.

**Comment by LRFLEW** [comment] 2022-12-02 09:40
I ran into this issue while working on my own project. I found this issue when checking to see if it had already been reported, so I'll add my notes here.

This looks like it might be a duplicate of #46200. The code example given there is a bit different, so this might be slightly different, but they are at least related. That issue references [CWG 2471](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2471), though _that_ example is more complicated than this one.

I checked to see how other compilers are handling it, and both GCC and MSVC compile the example here without any errors. That doesn't necessarily mean that it's **correct** to compile it without errors, just that it's the direction others are going.

The error doesn't occur when the outer class is not a template class. If you remove the `template <class T1>`, then using `outer_foo::inner_foo(1)` compiles.

This issue can currently be worked around by adding a user-defined deduction guide for the inner class within the outer class. For example, this code compiles without issues:

```C++
template <class T1>
struct outer_foo {
  template <class T2>
  struct inner_foo {
    inner_foo(const T2& t);
  };

  template <class T2>
  inner_foo(const T2& t) -> inner_foo<T2>;
};

void f() {
  auto X = outer_foo<int>::inner_foo(1);
}
```

**Comment by JoyNyuguto** [comment] 2023-04-01 11:10
To fix the error, the template argument T2 needs to be explicitly specified when creating the object X. This can be done using the syntax outer_foo<int>::inner_foo<int>(1), which explicitly specifies that T2 is int. The fixed code would look like:
``
void f() {
  auto X = outer_foo<int>::inner_foo<int>(1);
}
``

**Closed** 2023-10-16 19:17 UTC
Labels: good first issue, c++17, clang:frontend, rejects-valid
