### ISSUE TITLE
Using a constexpr value through a reference is not constexpr

### ISSUE THREAD

**Issue by OgnianM** [llvm/llvm-project#64376] opened 2023-08-03 09:24 UTC
The code below fails to compile with clang, works on gcc
```
#include <iostream>

template<int v>
struct Test {
    static constexpr int value = v;
};

int main() {
    Test<124> test;
    auto& test2 = test;

    if constexpr(test2.value > 3) {
        std::cout << "Hello, World!" << std::endl;
    }

    return 0;
}

```
```
$ clang++ --version
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

https://godbolt.org/z/vbbrWMYe7

**Comment by frederick-vs-ja** [comment] 2023-08-03 10:25
It seems that this program is made valid by [P2280R4](https://wg21.link/p2280r4).

P2280R4 is tracked in #63139.

**Comment by cor3ntin** [comment] 2023-08-03 11:42
@frederick-vs-ja Agreed, this is a duplicate of #63139

**Closed** 2023-08-03 11:42 UTC
Labels: clang:frontend
