### ISSUE TITLE
LSR miscompile

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#58039] opened 2022-09-28 12:21 UTC
```console
% clang-tk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project.git 8f19de848b968bfdd237bdb6ffb65e7412bb6a0c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /zdata/shaoli/compilers/ccbuilder-compilers
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
%
% clang-tk -w -O0 a.c && ./a.out
1
-1
% clang-tk -w -O1 a.c && ./a.out
1
0
%
% cat a.c
int printf(const char *format, ...);
static short d;
long e;
long *g = &e;
int h;
int i(int j) {
  int c = 1;
  for (;; c++)
    if (1 << c >= j)
      return c;
}

void l(int j) {
  int m, o = (j + 83)%12;
  h = -o + 9;
  unsigned n = h;
  m = n >= 32 ? 1 : 1 >> n;
  if (m)
    *g = j;
  short *a = &d, *b = &a;
  b || 0;
}
void p() {
  int q = i(d - 8);
  printf("%d\n", q);
  l(-q);
}
int main() {
  p();
  printf("%d\n", e);
}
%
```
Compiler explorer: https://godbolt.org/z/xqn3v7coM

**Comment by nikic** [comment] 2022-09-28 13:14
Based on opt-bisect it looks like the issue is introduced during `-loop-reduce` on:
```
; ModuleID = 'test.c'
source_filename = "test.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@e = dso_local global i64 0, align 8
@g = dso_local local_unnamed_addr global ptr @e, align 8
@h = dso_local local_unnamed_addr global i32 0, align 4
@.str = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1

; Function Attrs: nofree nounwind
declare noundef i32 @printf(ptr nocapture noundef readonly, ...) local_unnamed_addr #3

define i64 @main() local_unnamed_addr #2 {
entry:
  br label %for.cond.i.i

for.cond.i.i:                                     ; preds = %for.cond.i.i, %entry 
  %c.0.i.i = phi i32 [ 1, %entry ], [ %inc.i.i, %for.cond.i.i ]
  %shl.i.i = shl i32 1, %c.0.i.i
  %cmp.not.i.i = icmp slt i32 %shl.i.i, -8
  %inc.i.i = add nuw nsw i32 %c.0.i.i, 1
  br i1 %cmp.not.i.i, label %for.cond.i.i, label %i.exit.i
  
i.exit.i:                                         ; preds = %for.cond.i.i
  %call1.i = tail call i32 (ptr, ...) @printf(ptr noundef nonnull @.str, i32 noundef %c.0.i.i)
  %add.i.i = sub nsw i32 83, %c.0.i.i
  %rem.i.i = srem i32 %add.i.i, 12
  %add1.i.i = sub nsw i32 9, %rem.i.i
  store i32 %add1.i.i, ptr @h, align 4
  %cmp.i.i = icmp ult i32 %add1.i.i, 32
  %tobool.not5.i.i = icmp ne i32 %rem.i.i, 9
  %tobool.not.i.i = and i1 %tobool.not5.i.i, %cmp.i.i
  br i1 %tobool.not.i.i, label %p.exit, label %if.then.i.i
  
if.then.i.i:                                      ; preds = %i.exit.i
  %sub2.i = sub nsw i32 0, %c.0.i.i
  %conv.i.i = sext i32 %sub2.i to i64
  store i64 %conv.i.i, ptr @e, align 8
  br label %p.exit
  
p.exit:                                           ; preds = %i.exit.i, %if.then.i.i
  %res = load i64, ptr @e, align 8
  ret i64 %res
}
```
Though alive does not report anything.

**Comment by nikic** [comment] 2022-09-28 14:02
Somehow I had to go through two LSR runs, but this is the failing `-loop-reduce` transform: https://alive2.llvm.org/ce/z/TZhg9z

**Comment by bcl5980** [comment] 2023-01-11 10:28
It looks the regression point is 63f244c4f4f84fd066f
If we extend a negative const in SCEVAddExpr, it will be zext to a positive const. And if the add expr referenced by a SCEVUDivExpr, the error happen. 
For example in this case:
original i32 SCEV 
(12 * ({83,+,-1}<nuw><nsw><%loop> /u 12))<nuw><nsw>
will be extend to i64
(12 * ({83,+,4294967295}<nuw><nsw><%loop> /u 12))<nuw><nsw>

After add 4294967295, then div 12 will caused miscompile.

**Comment by fhahn** [comment] 2023-06-16 15:38
Looks like this would be fixed by https://reviews.llvm.org/D153004

**Closed** 2023-06-17 09:02 UTC
Labels: miscompilation, loopoptim
