### ISSUE TITLE
Clang-Format inserts extra indent for initializer lists with PP in the #else branch

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#69237] opened 2023-10-16 19:03 UTC
For the following snippet:
```cpp
A a_ {
  kFlag1,
#if BUILD_FLAG
      kFlag2,
#else
      kFlag3,
#endif
      kFlag4
};
```
Clang-Format inserts an extra indent in the `#else` branch after #65409:
```cpp
A a_{kFlag1,
#if BUILD_FLAG
     kFlag2,
#else
       kFlag3,
#endif
     kFlag4};
```

**Comment by owenca** [comment] 2023-10-16 22:42
@rymiel

**Comment by owenca** [comment] 2023-10-17 05:53
May be a duplicate of #68404.

**Comment by rymiel** [comment] 2023-10-18 16:57
It's unrelated, I haven't yet found the cause for this one yet

**Closed** 2023-10-23 20:12 UTC
Labels: clang-format
