### ISSUE TITLE
clang-format14 Incorrectly formats single line function if there is an #if inside class declaration

### ISSUE THREAD

**Issue by elpixo** [llvm/llvm-project#54499] opened 2022-03-22 14:47 UTC
With contents of .clang-format
`AllowShortFunctionsOnASingleLine: Inline`

example.cpp
```
#if DEBUG
#endif
class Example1
{
   bool empty() { return true; }
};
```

Both clang-format13 and clang-format14 *correctly* generate
```
#if DEBUG
#endif
struct Example1 {
  bool empty() { return true; }
};
```

BUT

example2.cpp
```
struct Example1
{
#if DEBUG
#endif
   bool empty() { return true; }
};
```

clang-format13 correctly generates;
```
struct Example1 {
#if DEBUG
#endif
  bool empty() { return true; }
};
```

clang-format14 incorrectly generates;
```
struct Example1 {
#if DEBUG
#endif
  bool empty() {
    return true;
  }
};
```

# Versions
clang-format13 version 13.0.1
clang-format14 version 14.0.0

[files.tar.gz](https://github.com/llvm/llvm-project/files/8325304/files.tar.gz)

**Comment by mkurdej** [comment] 2022-03-22 16:19
I think that the culprit was the commit https://github.com/llvm/llvm-project/commit/7af11989be21df00ad6a510a831ea2425e48fa90.

**Comment by owenca** [comment] 2022-04-14 09:25
Duplicate of #54901.

**Closed by owenca** 2022-04-14 09:25 UTC
Labels: bug, clang-format, regression
