### ISSUE TITLE
CTAD: parameter pack assertion crash when synthesizing deduction guides for alias  

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#90209] opened 2024-04-26 13:24 UTC
Example:

```
struct Key1 {}; 

template <int i>
struct Item {};

template <class... Ts>
struct List {};

template <class Key, class L>
struct TemplatedClass {
  template <class... Items>
  TemplatedClass(Key, Items...);
};

template <class Key, class...Items>
  requires(sizeof(Key) > 0 && (sizeof(Items) && ...))
TemplatedClass(Key, Items...) -> TemplatedClass<Key, List<Items...>>;

template <class T>
struct HasTemplateParam {
  template <class Key, class... Items>
  using Alias = TemplatedClass<Key, List<Items...>>;
};

struct Mod1 : HasTemplateParam<Mod1> {
  using Foo1 = decltype(Alias{Key1()});
};

```

https://godbolt.org/z/fssjafzYe.

**Comment by shafik** [comment] 2024-04-26 19:22
Confirmed, it looks like this bug is an addition since clang-18 release. Do you know which change introduced it?

**Comment by hokein** [comment] 2024-04-29 07:44
I think it is a new issue introduced by the recent changes I made to implement the alias CTAD feature as the crash occurs in that code path.

**Comment by shafik** [comment] 2024-04-29 20:19
> I think it is a new issue introduced by the recent changes I made to implement the alias CTAD feature as the crash occurs in that code path.

Do you understand the underlying issues? Do you have plan to fix it?

**Comment by hokein** [comment] 2024-05-15 08:48
I haven't delved into it deeply yet, but I suspect we may have some issues with handling the parameter pack. I plan to address this before the next clang release.

**Comment by hokein** [comment] 2024-05-28 19:34
A more simplified test case:

```
template <class Ts>
struct List {
  List(int);
};

template <class T1>
struct TemplatedClass {
  TemplatedClass(T1);
};

template <class T1>
TemplatedClass(T1) -> TemplatedClass<List<T1>>;

template <class T2>
using Alias = TemplatedClass<List<T2>>;

Alias test(1);
```

The alias deduction guide synthesized from the written `TemplatedClass` deduction guide is ill-formed because its template parameter list is **empty**:

```
FunctionTemplateDecl 0x55c2a051f440 </tmp/t8.cpp:14:1, line:15:38> col:1 <deduction guide for Alias>
|-TypeTraitExpr 0x55c2a051f330 <col:1> 'bool' __is_deducible
| |-DeducedTemplateSpecializationType 0x55c2a051dc00 'Alias' dependent
| `-ElaboratedType 0x55c2a051f150 'TemplatedClass<List<type-parameter-0-0>>' sugar dependent
|   `-TemplateSpecializationType 0x55c2a051f100 'TemplatedClass<List<type-parameter-0-0>>' dependent TemplatedClass
|     `-TemplateArgument type 'List<type-parameter-0-0>'
|       `-ElaboratedType 0x55c2a051f0b0 'List<type-parameter-0-0>' sugar dependent
|         `-TemplateSpecializationType 0x55c2a051f060 'List<type-parameter-0-0>' dependent List
|           `-TemplateArgument type 'type-parameter-0-0'
|             `-SubstTemplateTypeParmType 0x55c2a051efa0 'type-parameter-0-0' sugar dependent class depth 0 index 0 T1
|               |-FunctionTemplate 0x55c2a051ba20 '<deduction guide for TemplatedClass>'
|               `-TemplateTypeParmType 0x55c2a04fa090 'type-parameter-0-0' dependent depth 0 index 0
`-CXXDeductionGuideDecl 0x55c2a051f378 <line:14:1, line:15:38> col:1 <deduction guide for Alias> 'auto (type-parameter-0-0) -> TemplatedClass<List<type-parameter-0-0>>'
  `-ParmVarDecl 0x55c2a051efe8 <line:12:16> col:18 'type-parameter-0-0'
```

When deducing the template arguments of the return type of the `TemplatedClass` deduction guide from the right-hand side of `Alias`, we expect `T1` to be deduced to `T2`, and the deduced argument to hold sufficient information to retrieve the `T2` template parameter declaration of `Alias`. However, we don't have enough information in this case (specifically, with `TemplateSpecializationType`). The deduced argument is merely a **canonical**`TemplateTypeParmType`, which only has the index and depth. Consequently, `TemplateParamsReferencedInTemplateArgumentList` cannot determine that `T2` is referenced in the deduced argument, resulting in an empty template parameter list.

This seems working as intended, as clang loses this kind of information during the template argument deduction, see the [FIXME](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaTemplateDeduction.cpp#L686).

**Comment by hokein** [comment] 2024-05-28 19:53
> This seems working as intended, as clang loses this kind of information during the template argument deduction, see the [FIXME](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaTemplateDeduction.cpp#L686).

Ideally, addressing the FIXME should fix this issue. @mizvekov, how hard would it be to address it? If it is hard or requires significant work, I think we can use fix this crash by using the index and depth to retrieve the corresponding decl from the template parameter list of the alias.

**Comment by mizvekov** [comment] 2024-05-28 20:55
> > This seems working as intended, as clang loses this kind of information during the template argument deduction, see the [FIXME](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaTemplateDeduction.cpp#L686).
> 
> Ideally, addressing the FIXME should fix this issue. @mizvekov, how hard would it be to address it? If it is hard or requires significant work, I think we can use fix this crash by using the index and depth to retrieve the corresponding decl from the template parameter list of the alias.

That FIXME is partially addressed in https://github.com/llvm/llvm-project/pull/93433, regarding the TemplateName.
It will be fully addressed, regarding the arguments, by https://github.com/mizvekov/llvm-project/commit/252f292ed22dd374aa177faaf18bab1a32199cfe when I get the time to rebase and submit a PR.

But I don't think we should depend on type sugar to be correct here, figuring out the correct parameter from depth and index alone is more consistent.

**Closed** 2024-07-11 14:03 UTC
Labels: c++20, clang:frontend, confirmed, crash
