### ISSUE TITLE
[clang-format] Regression in class braces formatting in 19.1.0

### ISSUE THREAD

**Issue by MiKom** [llvm/llvm-project#112526] opened 2024-10-16 11:48 UTC
Hey. After updating to clang-format 19.1 from 18.x, it started formatting class braces placement differently.

For example, given the code:
```cpp
#define EXPORT_MACRO
class EXPORT_MACRO MyClass
{
public :
    virtual ~MyClass() {}
};
```

And config:
```
---
BasedOnStyle: WebKit

BreakBeforeBraces: Custom
BraceWrapping:
    AfterClass: true
```

I get the following formatting in 19.1:
```cpp
#define EXPORT_MACRO
class EXPORT_MACRO MyClass {
    public :
        virtual ~MyClass() {}
};
```
(the brace after class moves to the same line as class name and not on a new line, plus class contents gets indented)

Whereas in 18.1.3 there's no change to the source.

Interestingly, if I change the destructor to:
```cpp
virtual ~MyClass();
```

It starts behaving properly again.

I haven't seen anything in the 19.1 release notes that would indicate that the behavior might change. It seems that the problem boils down to the class not having any out-of-line members.

Thanks for clang-format!

**Comment by owenca** [comment] 2024-10-17 03:46
Duplicate of #94184.

**Closed by owenca** 2024-10-17 03:46 UTC
Labels: duplicate, clang-format

**Comment by MiKom** [comment] 2024-10-17 07:38
Thanks @owenca!
