### ISSUE TITLE
[BOLT] Assertion `Section && "cannot find section for address"' failed.

### ISSUE THREAD

**Issue by llongint** [llvm/llvm-project#71901] opened 2023-11-10 08:11 UTC
Using the same test case as issue #71804 , adding the linker option -Wl,-z,notext during compilation causes the following problem:
```css
# /home/test/llvm/build4/bin/llvm-bolt pre.exe -o pre.opt
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: 042c444c9a68
BOLT-INFO: first alloc address is 0x0
BOLT-INFO: creating new program header table at address 0x200000, offset 0x200000
BOLT-INFO: enabling relocation mode
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
llvm-bolt: /home/test/llvm/bolt/lib/Core/BinaryContext.cpp:2097: void llvm::bolt::BinaryContext::addDynamicRelocation(uint64_t, llvm::MCSymbol*, uint64_t, uint64_t, uint64_t): Assertion `Section && "cannot find section for address"' failed.
 #0 0x0000aaaadea0b738 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/test/llvm/llvm/lib/Support/Unix/Signals.inc:565:22
 #1 0x0000aaaadea0b808 PrintStackTraceSignalHandler(void*) /home/test/llvm/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x0000aaaadea09640 llvm::sys::RunSignalHandlers() /home/test/llvm/llvm/lib/Support/Signals.cpp:103:20
 #3 0x0000aaaadea0afd0 SignalHandler(int) /home/test/llvm/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x0000ffffad17d7c0 (linux-vdso.so.1+0x7c0)
 #5 0x0000fffface33e80 raise (/lib64/libc.so.6+0x34e80)
 #6 0x0000fffface35374 abort (/lib64/libc.so.6+0x36374)
 #7 0x0000fffface2cdd4 (/lib64/libc.so.6+0x2ddd4)
 #8 0x0000fffface2ce5c (/lib64/libc.so.6+0x2de5c)
 #9 0x0000aaaae049e514 llvm::bolt::BinaryContext::addDynamicRelocation(unsigned long, llvm::MCSymbol*, unsigned long, unsigned long, unsigned long) /home/test/llvm/bolt/lib/Core/BinaryContext.cpp:2097:3
#10 0x0000aaaadeabe948 llvm::bolt::RewriteInstance::readDynamicRelocations(llvm::object::SectionRef const&, bool) /home/test/llvm/bolt/lib/Rewrite/RewriteInstance.cpp:2350:29
#11 0x0000aaaadeabd36c llvm::bolt::RewriteInstance::processDynamicRelocations() /home/test/llvm/bolt/lib/Rewrite/RewriteInstance.cpp:2073:60
#12 0x0000aaaadeab919c llvm::bolt::RewriteInstance::discoverFileObjects() /home/test/llvm/bolt/lib/Rewrite/RewriteInstance.cpp:1262:17
#13 0x0000aaaadeab6bc4 llvm::bolt::RewriteInstance::run() /home/test/llvm/bolt/lib/Rewrite/RewriteInstance.cpp:808:24
#14 0x0000aaaadd99e258 main /home/test/llvm/bolt/tools/driver/llvm-bolt.cpp:244:29
#15 0x0000fffface1fbec __libc_start_main (/lib64/libc.so.6+0x20bec)
#16 0x0000aaaadd99d1dc _start (/home/test/llvm/build4/bin/llvm-bolt+0x53d1dc)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/test/llvm/build4/bin/llvm-bolt pre.exe -o pre.opt
```

**Comment by yota9** [comment] 2023-11-10 08:15
I've added the  -Wl,-z,notext to the test included with the patch for #71804 and was not able to reproduce it :(

**Comment by llongint** [comment] 2023-11-10 08:23
Try adding all of these options?
```bash
-O3  -flto=thin -fuse-ld=lld -std=c++14 -Wl,-q -Wl,-mllvm,-enable-branch-prob-enhancement=false  -pthread -rtlib=compiler-rt -Wl,-z,noexecstack -Wl,-z,relro,-z,now -Wl,--build-id=uuid -no-pie -fno-pie -Wl,-Bstatic -Wl,-Bdynamic -L/home/hezuoqiang/BiShengKernel/build/lib/aarch64-unknown-linux-gnu -lunwind  -Wl,-z,notext -Wl,--script=mylld.lds
```

**Comment by yota9** [comment] 2023-11-10 08:27
No, sorry, unable to repro. Please attach the binary

**Comment by llongint** [comment] 2023-11-10 08:46
Save the following string as a text file pre.exe.tar.gz.base64, and execute the following command to obtain pre.exe:
```bash
base64 -d pre.exe.tar.gz.base64 &> pre.exe.tar.gz
tar -xzvf pre.exe.tar.gz
```
```log
H4sIAAPsTWUAA+3af2wc553f8Wd2lxRtUdJaoizakqV1ogayYzNckpIpnxGvftAWY1lWJDlRfb4M
l8u1uMhyl9kd2pTjIHQuV7hN0EoXXSwc7FRO/IesGqh60V10ON9V8bmF0AaoWjtOisQOozqtiwY4
F1EcMjmLfZ6ZZ5bfHe44l0MPSIv3S1jOPp95fs0zs8NdaidrxZ7idFH9Q+rV7ti61Wz7erdm7dYv
9/b19fdmB3pVdmBrX3//tq39+nlvtn9gW1Zlev9BZ2VN1b18LZNR48XHp6qfKeUrR1rX+3X7/x/1
+aG99yQcp1FOqG8pUxqx5Zzdjmy+plEnpwbVcv2zV/WopC6n9ON0onX/6yNbR2zfr93DkW3Y0vxs
8+cXlMN5htvMsuatbGfGm1kWlGfs/nC7+ZfLmrayXbuZpxMc/2mno2nbnVRN22i7C6mg3YVUR9M2
bWs/mWhulwjb2fEu2HHCrQrr261N1YGfeGOpv8M8D6+Uoym137Y7bNsdtvXD7V5bL9ym7Pbjul27
+s2l7OMVO/8Nqnmbi2zD8T5SLo1+pDx2e7lUmZq+PZ+vFca3DfTUqz3ZoE7aHtO9+x7065vDXSb6
SNvM7B/YeGzjc+v++n88NbLiw9//V3/93/4ehwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAADg7+EmNfNfNurHT5LqzI+TufnLH1TH/3tSHde7jqmRxPFNmeR3Cx0qbbabO1X6YUed
+KR+uEp1qZSuM7tjPqfUuYcc1XUh6b7+3mf/7Qvv6fam/qlMLq1UbrvakPvDTUr97x876pDJZzfl
0jermQOOUtv9Pt7aMW/2K73flJ2RNX77zNyq9B49VkKPZcrvffbbp+UYftuRruNyjOcSQR8mbxrj
7WCMUyqYw8x6f27zA7p/f/9Pg/0X7P7clVXpbMuxX/LHvvI954Uu3W6tfrz7o8QLJy63H//Tr7cf
n9uk5t9NqltPJNb+x18knTMnru76ylwyceZdpU6ccNS5by5X82v0en/j8frc5WS3XvN1Z2aT1986
ou5+vd6ujv/LxJr/dfPCwqFvLs/NX/nejhfe/dHOF+Y25ebf++wr/vjBHP7qhSsPOI11nl2X88/P
k+/enU44Mwf69bz99dP5c3oN1utyhz7Wn+lz3PHkp+Y6VMeXuo7m5g8p9ad36X1PXc5t1+u8dTbZ
dcYvJ3LzHTfk5k15h+5POXe//mN9TGYtnly5Y/tscs2ZD+l6t5i10/t/oY+tQ69Dh9N2vEOpeTO2
887d/py+sFGlzf6f6bX4/Er1mW+n1KFf6fIVPRez/ys35tKObnvz88njpt+diZkDSTsHM37HNbl5
M77qVOdMm5Ted9m2PdWdS/9Y1zH9j5s562MbT3R8aY0+tldXqHPj+rg6rjHHteZMu2Pr+Me1pum4
9PXb9bru4/PXqs88lwrO/6trc2kzXnRuP1RL5zZzTTC3N9Ti3C6sCeZ2qcXc+q+xc1sWzO1HKn5u
vfb6O3idXadcMJdEcubAn7fquz3oezwZ9H3xffpeo/vO6/PpX+8rc+l/o+ue04+n9WM2uenWKw/s
eOG9z77sX3fhOCN6nI5M7s8dR/U9q+t9fWFhXdhHpjOX1q+vE9/Qj78R+cjyXPqPdWbq/0+dt+rr
n+l9f6b3nbTjf9W/ZtQZT2/b9TzN88/o50n7vOLPcc2ZE3qrX+Mnrq7aNFfU27J+mNfHz/TrzLw+
TN2Dtu7PlpvX0cunj4T3rq7U8fD1FNY3863rtTD1t6rgdTTbHtz/Ls/frc/pYj96f1d4L/rLqwtP
R+9PYVneb9/R+9J67Ot+uWM+/fKq45nEptdN3+HD33dV77sc7PPLiZ3z6UR6sdyuyx8Q5Wt1eaco
r9TlUVFerctfEOXrdfnronyjLr8syht1+bIof8CMf91i+UNmfFG+1Ywvyj1mfFHuM+OL8jYzvijf
acYX5Y+a8UV5pxl/9WL5HjO+KH/MjC/K+8z4onzAjC/KnzDji/JDZnxR/pQZPyjH/d7U15xa3SJf
FpPfoB+ZFvmWmPyj+vGBFvn9MfWLMeP+UUz+9Zj8P8XkP4jJ34nJfxmTdzqt8w0x+W0xeX9M/mRM
/pcx+Ssx+aWY/M2Y/N2YfJ3+pXldizwXkxcTrfv5nArykfbm/C9sfiySf9zvf5PKtHX45bQT5L9r
89725lyphP7n6H/mZ1L/TPn/kvZnUrX5adL/1+5nji3pe7J+nlJeIrg2037ZUd/S5f22d++WP9QD
JtXvJ4L9//Tzt+hnbepf2HJ+7mn9rF09a8uv/utPtynd54uJoP3Tx7/abub4bVs2015vtzf6B3JD
LuME2Zah7+7d+2TH0a6Tnbv+0UTnLv2+TpnHtfrRaeezwrY152CjWLebxHM9AbVBmV8WwRqvs/k1
oo55Xa/Vj+ttuVsttb5FJoWnLhHJl8XUX6Uf+ne3MmcwbTNzDlL6sdKWzZosDxvkR6s1T7luuTRa
cOtevua5E/lSRSdHJqoVm7i6WCseKdW9Ys19pJafKLqlyiNVnRam8+4jpUq+XHq8qItjxZbVHtp3
0BssVevuaL5eHBiulLxd2aFHW+W7/dzvNu8Vp0teWCiXqwWduMXpQnHSK1UrQevtjfLuvkZLb7xW
fcwcwfS0O1ms1atmft5R99Fev1G1XB8q2aqjeroVV/dcGLdJsTIWlh/S/etDmdDH5xXNdMfK+x/1
4+w2163WvVoxP6EPsV6secMFnWYL4/ma69XyJa8+XBgaOqCzfn1spUJYe/iQe6jXHTq4zd1/38F+
t2yPIqijV6JlN1sL5WK+NqT39LnDerX0w9MzUrrLcjFYiGr/5JQ3VAieb32kPFUfH1qcqr8gepHN
kdU9f+HvO+htLXhHJ4t6gGy/e7/7WGmsWNEHU/L8hoc+sS/ba1ZkOj9aejTbp5/XS26hnK/XXdPM
P7NDpuKwPAv+kAOF6pRnnxVrNeU+WHmspJf1QLE+NVFU+lKre2OFD3+4p17t2abu3Tu8c9fhw25/
z4B83rO9qZTNKv10x85hN9vTb7ooiNZuX0/2DhNO+QOZPVlTnAjq6GeTegmKeX9Pb3jpX0gG9zn9
3tl/jYQuijwl8ksibxP590Uub7W/coJXrX4Pu/h6086rjkbeLV6nJ0V+g5xPTJ5zFvMNIg/v62by
8p4V3tdNLu9rc3b+iVRw32tILeby/tMhcrluaZHLdesWuVy3jMjlum0RubzP9Ypc3jcHRd4h8pzI
5X15j8jluu0X+bUiPyzyTpGPiHyFyMdFvlLkkyJfJfJpkadFPiNy+X7gKZHL9wPHRL5G5CdF3iXy
UyJfK/LTIr9e5GdFvk7k50V+owIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBvqy67dR4/oFLTG531nZv88gb7OKauLoyZ
YMfK9LOJrzmffPONlaa4WT/u0o/X9P4nxP7fs/tDA/ph2m9xri7MBPVyz3Z8bdmOFTftONH2R6l7
vpp8OnHS2fOV9o+9uvvNN77/+vde+66ZgpnXM/oxqdulYubrPLE43812vmOpqwvmudq9MrOn86bM
V1Jfa3+2Y2/npsyelerVN98w7Xfrx4iu1yn6NW0e1o9DOr9rSfuxRvsNjfH37/VnsHyxDzOXAdvX
S3pdupJKdaRUh5L9JU74PV6bfDhhO33tzTd2i14AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA3x6OSqgFdcpxPtc545xz2r7sdCld7NJPz5mn
F50NM+3qLSej1BcTe/XTS4m0UrOJzJU2NZPU6ankXv30neTht9vUpVRa15hNbVHqqbaUfnqiLa3j
F9tu01V+6CezbSmdvNWW0slP2zYca3eeau/0p/G55Of0fM6rjpbzzGbvPzo0XShOeqVqReSnI/V3
5aeOjHuZqcqnK9XHKplio4nd0QjuzKgDxfpU2dNPdk3VvepEZmhxX143rdWqtUy1UJiq1YpjN0fm
E53nQFuwPWy3zvrk7zx/dX7B1Dq88IuFC/r5S3o7q7eDam6hY2F+4bze5vT2Jb2d09sfJucWJvVW
peYWTuptp96eNWXtrB1nzPbf5YTnL/CdRHPZi5R/ECn/JFL+li1vtOVOu/3VwkJV1lsbWYdldptb
FWzDVemwDa6x5W67XWe3e9LB1g6rDtsnSVueTQY9dUXGabfbGRssj/Rvl0fttgdwrS3/3PZ/fWT+
P78aHF+37SgVtrflG2z5tBPMZ70t2+mrG+32vN2/wZbDdQjX8ZSd2ApbPmfL79j1HbcTvWrLp215
wZbDdfq/5VLb/x/b0MVUsOLTtrzGCc7loC0/YbdrI/mMqP87or8vivoyf0rUHxT5l0V9mR+z2/U6
v1vkJ0S+XeQn7fZGnd8l8mfs9g6d7xD5KbsdjOSnRT8yPy/mv0zkL4n5y/xSTP3XYurPinnuFPlb
Yp4yfyfSf/i6uRLpP8znRH3pb0X9Jra8PjLuBqd53D02zzjN44b5QEz9wZj6u21u1mGXGHePs9hO
5odE/90iPyz6l/mIOC7Zz5gYd7fIx8W4MvfEuNK0GFd6Qowr+3lG9LNN5KdEfofIT4v+Zf0XRS7r
XxTjrhR5JrHY/8Mi35xY7EfmW0T9Ab29zea3ifoyH0gsjntQ9DMYM+5dMePuFv3sE/mIyA+LfFLk
/1jkJ0X+CZE/I/JPivx5kX9M5KfF/LNq8ffZi2L+Mj8n6t8j+jkv6sv8JVH/PpFfEPVl/oqY516R
vybyB0T+Q9H/74l8VvQv87ci5z38vf525LyH+ZWY855OLuYPirw72Xo+G5Kt57NZ9CP73yNyed7H
RS7XwYsZdzpm3BlRXx7vF0V9mR+LmeeLMetwLmY+52PmcyGm/7di1iGVat1/R6p1/52i/oDI06K+
zDekWs8nJ3I5n7GY+YzHzKcs+pGv30mRy9evJ/L9In9G5IdEfjpmPi/GzOdszHzOxcznQkz/r8T0
fzGm/+/E9P92zHG9I3J5n7wSk8/F5OEHhOh6dsbk3TF5RuSfEvlmkZsphMd/m8jl67dX5B8X+W6R
y/vkIZub93UHRB5+7gyv8602f9jmayP5pKh/u+jHE/Vl/oSYz70inxH97BH5F0U/Mn9K1JfvZ74s
6sv8GXG8wyJXe6byjxVLmZ2lg+PFypHMrurEZKlcrGUK5bwuPlqs1fUH+Ux2a09vz0BmS+9AX2Fg
YKCwPb9t8BZ1765dd2a23LvvwVsy2d6e/p5etbdU+XSxdmcmrte9e3fbvmTjO/y2/ntT//ekWZsd
m53+fFaNhPO321Z1nvkN6px9nzrhZ8sX2+LrhJ83X3qfOl32d164bVUnHOPc+/QTjvGK+IwWfo53
nMXP2MaGSB5+5hmMyXMx+cMx+VgkD1/DMyIPP6MbT0XycN/zIl8h6r8YycPPKRcj456z718vxeQ/
jRn3SiQP1zHttB63O5KH799OR+5L4fqEn5udyOsuY//i0BZZt1wkP2fz8Ujea+dxKpKfbaxDc/6a
vSjmInl4H087zXnKHs8um5v53y/mfzhSP1znvKh/m6gf/n0nep2cjeThuOcjebgOx9RiLt8PnxT5
74r8vMgfUovn64LIh0T9izH9DDqtx82JXP4e2ROZf7j++yP5nHyxtvBtfzkTjddxKFjuVOM+2Fz/
OqVa/J032aJ+kC/tP8hv0u9HWvWzSV1qmX9wSRbO85mWeVvj3tqctzfuf839L60f5Evrz+tHIrG0
frA+Gxuvy+bcXB3NfwkM539WqRb1uxvXdXN+Q+P6bc43qf/cct2WzifIl/Yf5Ev7P6H7dxKL/YR7
w/kfc1rNP62vh0TLvPU6tDV+PzXn7Y3fSaHRZDBuV3M3aqefr9Z7mud/h62/JdLPbTYfiOQ32/xw
JN9g87FIvs7PMyq3rHnc1X6+Zsn/c6zw864l/w/R4edr1d9G8of9/Hp9X27O7/Lz7sZ9LpT18w+o
qA/5eVpfb0v/Ip1ssW5BvvS4gnzpcQX50uMK8qXzzzvmulrMtzTVj7vPLD2uIF+rfy+1qu8syZ4z
h5/oXnKdv6yCPPq6uOoEV1XaLlt4WzV/d13dYi4/UEH9kUj+NzYPXy8zNn/e9t94D2c/P39Pmatq
6X3yTxLmLry4PuF8nnZaz+e7ypz1pf1cSpj+l7rZaZ3fmWh1VSl1TUz9us5vFtdJ+Le/P/Dzxesk
fO/yx6r1/L9g85H25vxyTP07YtahYusfi/STiunn3mTrfGWidd4dk98ak2+JGXcwJj8bc1zDMf2/
EFP/lZj6IzHjpmPyu2PyHyWCdwlR+53W+Z8ok2/Sn8uD6yF8f7xg89725vwPYuavemrFcr6nVCl5
br5Wyx+1wSM6aQq84rSneo5U9Y9CdWKiWAlKPZNlz9bwn43W6z3uQwe9vYOuW6qabsUI/m5bPlKZ
6hmdKpXHevKeVyuNTnlFvWvsaKXu1VRPcdx9pJafKLrjY7pk6tpPuK4ulipesTZp+9Et7LNadSzv
5fXohz7R/L/nYs/B6J7mhsOR3WLgcNqFghv8n7rr5UfLxZ6JfKkSzPvoRDgl05t+1lOuFvJl5a9l
0Nd4vj6ueipVr9izY+fw7V7+iG0SHq/d2Vic20tjfuf5iVJB9dTH9eLoYfWzcHt0wt+aIRvHWah7
A42CrpntySq1eVq5bmE673rjtepjypyj7DY3KLmj+TG3kK97j/r5dr28E6VK3iua8lh5v9nsu++g
t7XgHZ0sDheGsv3u/e5jpbFixTXndcivcLC69ZHyVH3clrztje8e7O4Ls8FSta5HqxcHhnW73dnW
+a4gP+gNFKpTnsqPVmuenv3iRerWvbwfmUNsFMzR6UlPl0yhXBotuIX6lN/Kdlas1UybYq14pFTX
B2mvsVLlkarOW6d+p2VzJr2iu/j1CnOxyENUSy+7pZfb0ivMztM/Ate/lPT5KhcrjfNT1eVifkLP
pl6secMFnWYL4/ma69XyJa+uz8XQAZ3167UrFcLaw4fcQ73u0MFt7v77Dva7Zbkc/sXon61yfahk
D3BUH3pFXwFeYdwmxcpYU1k3y5dLjxftqQ2G0yet5Yy2FsrFfG1I7+lzh/WJ1Q9PL59yH6w8VtId
my+i6Gtdn4p61R3PV8bKxebTq0dX7vADel3G9Lym6sUxtXksmHX/5JQ3VNDVj0zou0GwcK6/+vuy
vWau0/nR0qPZPv28XnIL5Xy97pqr1j+fQ7qbnu3mx6D5cYf5sU2/NHq2mh8DppjtN0/7/ad95mmf
/zTr/zTDTk+7k/qWUDXr4R11H+319/Saqr2tbrC/mW+q4D189N1m+P9X6yN59J2aef+wTLQPP0eG
/9+UidSPftw9Fmkf/t3krb9j+y12TuHbhZHGNphpLvI5IN1cVOOR9uHnxVNtQfuuSP3o+AWnuf25
xt/vnJbjRdt/LDL+4vcvgvZnIwse7e8eJ/iOTrh+4fd2ZpYFDcP/f1thx2n8Hctub3KC78CE7cPv
yYxfG7T/qM3DdonI1vzd7qpoH36v5rRtP6kWxzd1osdf0tXeFe3D7wl1Lw/ah39D6ohsQxNO8F8O
Yfvwe0W7l4d/qGtul4ps/7kKvhPVaN8ZboOGP4+8MKLX/1/YvsJq4fe0cquCmh2R8aPrP2Tbh9+d
CL+3tce+kQq/t2XabWjR/p840ddv+Cz4gPLlyISj6/cd2371khrBN8ui5yu6fh+JjJ9qfN4J2j+v
mkX7M99bke3DzyGnbfuVkfrR9U9Gxg8/r5y37bsj9aPH/19t+z5bDj+fXrLtH4oZP9z+h8j8w8/J
vU7QXn5ebjX+VyPtD9v2h237vZH60fUz9w2zRuH3+sLPxadt++j9Ijq++b7gKtE+/Lx93raP1o9e
x99wgjmE7S/Y9hdseyXuP7JdOK8eFRx/o739XuKFZNA+82vmf1ekffi9xlnbfvbXtP/3TmR8+/n7
Qqr19R+9/g5G2od/f7uYev/1C1VsFrYP/656ybafjNx/ou0fiLQP/w4Uto/ON1o2f7E1x5iL5GH7
t+399HZbL3r/6bd9Rt+KnE8H7b8UM364Nd8nXKaW2n2dPf+RCUfPRz1m/uOrg/YzzuL8P9hi/oWY
9m+vab5/mPZtLdrvc1q3V11L229s0f7JmPbdtn34/T3TPt2ivRMz/461QfvwvNxu20Tbr45pP7h2
6fxvaNH+1pj5728x/uoW7a/GjD9j24f/t23ad7Vo/+9i2l+07UdE++tbtP8rp/V3f7dcb69/2+Aj
KvibT7S9+T5dUi2V3mTbR67f6Ovvz2Laz2WC9kciO5f+pRQA8Nvo/wAfLPtyADgJAA==

```

**Comment by yota9** [comment] 2023-11-10 09:12
It looks to me like the initial binary is corrupted.
It has a relocation:
00000000000201fb  0000000b00000101 R_AARCH64_ABS64        0000000000000000 __gxx_personality_v0@CXXABI_1.3 + 0

The nearest section is   [16] .eh_frame         PROGBITS        0000000000020000 030000 00018c 00   A  0   0  8
But the relocation offset is out of this section, i.e it is between .eh_frame and .rodata.cst4 . Probably it is linker issue, but anyway it has nothing to do with the BOLT.

**Comment by llongint** [comment] 2023-11-10 09:24
Oh, let me try with the latest version of lld.

**Comment by yota9** [comment] 2023-11-10 09:34
I'm not sure would it help or not. You've got rare combination of c++, no-pie and notext options. I don't think it is very common and well tested, plus the problem doesn't shown on normal usage. So for now I'm closing the issue, right now I don't think we need to handle such cases at BOLT level, although it is possible just to skip such relocations.

**Closed by yota9** 2023-11-10 09:34 UTC
Labels: BOLT

**Comment by llongint** [comment] 2023-11-11 08:50
Okay, this does seem like an issue with lld. I tried the latest version of lld, and the problem persists. Since relocation information doesn't affect the binary's execution, it might not have been caught in testing. I will attempt to see if I can address this issue with lld.
