### ISSUE TITLE
[clang-format] double slash in include directives with angles is interpreted as a comment

### ISSUE THREAD

**Issue by lahwaacz** [llvm/llvm-project#53106] opened 2022-01-10 10:20 UTC
Small repro code:
```cpp
#include "foo//bar"
#include <foo//bar>
```

Run clang-format:
```
$ clang-format --style="{SpacesBeforeTrailingComments: 4}" foo.cpp
#include "foo//bar"
#include <foo    //bar>
```

**Comment by mkurdej** [comment] 2022-01-10 10:26
Duplicate of #51900.

**Closed by mkurdej** 2022-01-10 10:26 UTC
Labels: duplicate, clang-format
