### ISSUE TITLE
Extra stack save+restore with memset loop idiom transformation

### ISSUE THREAD

**Issue by hiraditya** [llvm/llvm-project#56662] opened 2022-07-21 19:41 UTC
Test case:

```cpp
#include <stdio.h>
#include <string.h>
#include <array>

constexpr size_t N = 1120;
float buffer[N];

void zero_int_memset(int* buffer) {
    memset(buffer, 0, N * sizeof(int) );
}

void zero_int_loop(int* buffer) {
    for(int i = 0; i < N; ++i){
        buffer[i] = 0;
    }
}
```

`$ clang -O2 -std=c++17`

```asm
# x86
zero_int_memset(int*):                  # @zero_int_memset(int*)
        mov     edx, 4480
        xor     esi, esi
        jmp     memset@PLT                      # TAILCALL
zero_int_loop(int*):                    # @zero_int_loop(int*)
        push    rax                          <-----------------------  save
        mov     edx, 4480
        xor     esi, esi
        call    memset@PLT
        pop     rax                          <-----------------------  restore
        ret
buffer:
        .zero   4480
```

```asm
# arm64
zero_int_memset(int*):                  // @zero_int_memset(int*)
        mov     w1, wzr
        mov     w2, #4480
        b       memset
zero_int_loop(int*):                    // @zero_int_loop(int*)
        stp     x29, x30, [sp, #-16]!           // 16-byte Folded Spill
        mov     x29, sp
        mov     w1, wzr
        mov     w2, #4480
        bl      memset
        ldp     x29, x30, [sp], #16             // 16-byte Folded Reload
        ret
buffer:
        .zero   4480
```

https://godbolt.org/z/7T8T1hhTP

**Comment by nikic** [comment] 2022-07-21 20:19
Duplicate of https://github.com/llvm/llvm-project/issues/47852.

**Comment by hiraditya** [comment] 2022-07-21 20:52
@nikic why do we think this is a duplicate of https://github.com/llvm/llvm-project/issues/47852?
Can you please clarify? This issue is also in arm64 not only x86 (https://godbolt.org/z/sff1vEGsG)

**Comment by nikic** [comment] 2022-07-21 21:01
Because the issue is that the memset introduced by LIR is not marked as a potential tail call. I'm not sure what part of #47852 gave you the impression that it is x86 specific, x86 is never even mentioned there. Did you open the wrong issue?

**Comment by hiraditya** [comment] 2022-07-21 21:05
w.r.t. x86, it was tagged with x86 by someone. i removed it.

**Comment by thecppzoo** [comment] 2022-07-21 21:11
AFAIK the tail call marking has nothing to do with this bug, the application of the `memset` idiom is requiring preserving `rax`, the return-value register, even if that register is not preserved across function calls in this ABI, should there be other things not a `return` after the invocation of `memset`, the inefficiency here will "pop" again (pun intended), so, this is not related to the ability to tail call.
Not being knowledgeable of LLVM I could be wrong in many places in the above argument, but please let us know to be able to help.

**Comment by hiraditya** [comment] 2022-07-21 22:26
As per the calling convention, the return value is passed in `eax` register. As 
1. caller isn't using the return value of memcpy, and
2. caller doesn't have anything to return so previous value of eax doesn't need to be saved

It should be trivial to delete the save+restore pair.

**Comment by efriedma-quic** [comment] 2022-07-22 17:59
On x86, rax isn't really being saved or restored here.  The instructions are just there to ensure the stack remains 16-byte aligned, as the ABI requires. We use push/pop because they're faster and have a shorter encoding than "sub $8, %rsp" etc.

**Comment by hiraditya** [comment] 2022-07-22 18:15
How does save+restore pair ensure alignment in this case? Any place I can read more about it?

**Comment by thecppzoo** [comment] 2022-07-22 18:32
@efriedma-quic : thanks for your reply, but it does not apply:
the equivalent code does not have the stack alignment issue, and the net result of both codegens is the same.
Pushing `rax` won't guarantee stack aligment to 16 bytes either.

**Comment by efriedma-quic** [comment] 2022-07-22 18:41
> How does push+pop pair ensure alignment in this case? Any place I can read more about it?

We're just using "pushq" for the effect of subtracting 8 from the stack pointer.

For the 16-byte alignment rule, see the x86-64 ABI, section 3.2.2 (https://github.com/hjl-tools/x86-psABI/wiki/x86-64-psABI-1.0.pdf).  For the semantics of "push" and "pop", see the Intel manual (https://llvm.org/docs/CompilerWriterInfo.html#x86).  For the commit implementing the optimization, see 65089fc6c73211e7d76307efe02c42b6f83a0dc2 .

> the equivalent code does not have the stack alignment issue, and the net result of both codegens is the same.

Suppose you write the following:

```
        mov     edx, 4480
        xor     esi, esi
        call    memset@PLT
        ret
```

You have a stack alignment issue: on entry to memset, the stack is not correctly aligned according to the ABI rules.

Changing the call/ret to a "jmp" works, sure.  That's referred to as "tail call optimization" or "sibling call optimization". That's what https://github.com/llvm/llvm-project/issues/47852 is about.

**Closed by efriedma-quic** 2022-07-22 18:41 UTC
Labels: loopoptim, missed-optimization

**Comment by hiraditya** [comment] 2022-07-22 18:48
> You have a stack alignment issue: on entry to memset, the stack is not correctly aligned according to the ABI rules.

Can the stack be misaligned even if caller is properly aligned?

How about arm64, does the x86_64 ABI semantics apply there as well?

**Comment by efriedma-quic** [comment] 2022-07-22 18:58
> > You have a stack alignment issue: on entry to memset, the stack is not correctly aligned according to the ABI rules.
>
> Can the stack be misaligned even if caller is properly aligned?

The x86 "call" instruction pushes 8 bytes to the stack.  So on entry to a function, the RSP % 16 == 8.  Therefore, to restore alignment, every x86 function that calls another function has to adjust the stack.

> How about arm64, does the x86_64 ABI semantics apply there as well?

You don't have an alignment issue on arm64, no.  But all non-leaf functions have to explicitly save/restore x30, the return register.  (By default, we also set up the frame pointer, x29; you can suppress that with -fomit-frame-pointer.)

**Comment by thecppzoo** [comment] 2022-07-22 20:43
Thanks a lot for the explanation, I now understand the reason for the push/pop and thus that this is an issue of enabling tail calling

**Comment by rotateright** [comment] 2022-07-26 12:51
This report is already closed - but for the record, 'tail' should be present in the IR with:
bfb9b8e075ee32197157ccaf0c301122ca9b81af
...so we should have the ideal codegen. Please open a new bug if you still see problems.
