### ISSUE TITLE
libc build, for rv64gc

### ISSUE THREAD

**Issue by advancedwebdeveloper** [llvm/llvm-project#54986] opened 2022-04-19 23:05 UTC
64 bit RISC-V related.

**Comment by EugeneZelenko** [comment] 2022-04-19 23:08
@advancedwebdeveloper: Please provide more details.

**Comment by jrtc27** [comment] 2022-04-19 23:14
They want someone to port it (asked on the official RISC-V International Slack and got no response), so just a feature request against LLVM libc, nothing to do with the LLVM RISC-V backend. I don't know why it's of such great interest, it's a nascent project that's not hugely useful in the real world yet.

**Comment by EugeneZelenko** [comment] 2022-04-19 23:17
@jrtc27: backend label is still relevant because `libc` would be ported for specific hardware architecture.

**Comment by jrtc27** [comment] 2022-04-19 23:18
No it's not. Backend is for llvm/lib/Target-related things. What someone does in libc/ is totally irrelevant and I don't care about those bugs.

**Comment by jrtc27** [comment] 2022-04-19 23:20
(It is a bug relating to RISC-V, but it is not a bug relating to the RISC-V _backend_ any more than "my favourite C/C++ program doesn't support RISC-V")

**Comment by advancedwebdeveloper** [comment] 2022-04-21 13:59
>   Unknown CMake command "llvm_update_compile_flags".

**Comment by sivachandra** [comment] 2023-03-14 01:41
Duplicate of #55752

**Closed** 2023-03-14 01:41 UTC
Labels: duplicate, new-feature, libc
