### ISSUE TITLE
clang-format 14 is extremely slow

### ISSUE THREAD

**Issue by manxorist** [llvm/llvm-project#57117] opened 2022-08-12 10:09 UTC
Formatting https://github.com/OpenMPT/openmpt/blob/072d4ccc83d842cfa34601dddf2c69a4cc889c74/src/mpt/arch/x86_amd64.hpp (~50kB) using https://github.com/OpenMPT/openmpt/blob/072d4ccc83d842cfa34601dddf2c69a4cc889c74/src/mpt/.clang-format with clang-format 14 takes about 14 minutes for me (CPU is a 3.4GHz AMD Piledriver).
I am using `clang-format version 14.0.5` (as shipped with Visual Studio 2022 17.3.0) or `Ubuntu clang-format version 14.0.6-++20220622053131+f28c006a5895-1~exp1~20220622173215.157` (from `deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main`).

I do not see any excessive memory consumption, it's only CPU time.

The performance was fine with clang-format 13.

I could also provide other source files where performance is noticeably slow with clang-format 14 if required, however the given file is the worst offender.

**Comment by hansfn** [comment] 2022-08-12 12:03
I can confirm this problem. I just upgrade Qt Creator from 6.0.0 to 8.0.1, and suddenly it ate up all my CPUs - 99,7 % load when idle... Disabling the ClangFormat plugin dropped the CPU load to less than 1 % when idle.

Maybe related to https://bugs.llvm.org/show_bug.cgi?id=49519

**Comment by codido** [comment] 2022-08-12 18:03
@manxorist Could you please run this with `QualifierAlignment` set to `Leave` instead of `Custom` and remove `QualifierOrder` in your .clang-format?

**Comment by manxorist** [comment] 2022-08-12 18:13
```
manx@quadratus:~/projects/openmpt/trunk-1$ time clang-format-14 -i src/mpt/arch/x86_amd64.hpp
real    0m2.576s
user    0m2.555s
sys     0m0.020s
```

@codido So yes, changing `QualifierAlignment` to `Leave` makes it run in seconds and avoids the performance problem.

I'll probably use that as a work-around for now.

**Comment by mydeveloperday** [comment] 2022-08-14 14:20
Qualifier Ordering along with a file with lots of #ifdef will likely be the combined cause

**Comment by tru** [comment] 2022-08-15 07:43
@brad0 since you added it to the 15.x milestone and it seems to be pretty high impact issue - I will move this from triage to needs fix. Next rc is released the 23rd of august if you want to get a fix in that one.

**Comment by tru** [comment] 2022-08-22 06:48
@mydeveloperday is anyone looking for a fix for this issue for 15.x?

**Comment by brad0** [comment] 2022-08-26 02:04
@tru Sorry I did not see your response. I don't have a fix at the moment. I just added the ticket as I saw this referenced in another community and it seemed like a regression that would be good to fix for 15.x.

**Comment by tru** [comment] 2022-09-15 07:13
15.0.1 window is soon closing - any updates on a fix here?

**Comment by tru** [comment] 2022-09-19 06:46
Moving this to 15.0.2

**Comment by tru** [comment] 2022-10-07 06:53
Removing this from 15.x - let me know if there is a fix we can merge.

**Comment by Sedeniono** [comment] 2022-11-16 09:57
I also noticed this slow down. I do not think that it is necessarily related to preprocessor macros such as `#ifdef`. I have a cpp file ~13000 lines **without** any preprocess macros (asides from includes). Formatting some selection from within Visual Studio with clang-format 15 without `QualifierAlignment` runs in approx. half a second (as it used to), while with `QualifierAlignment` and `QualifierOrder: ['inline', 'static', 'constexpr', 'type', 'const', 'volatile' ]` in the configuration file takes approx. 2 seconds. So 4x longer.

**Comment by Sedeniono** [comment] 2023-05-11 19:11
I did a bit of profiling myself. From what I could understand:

* I noticed that even without any preprocessor directives in the source code, using anything but `QualifierAlignment: Leave` slows down clang-format noticeably. For example, take some file with like 20000 lines. With `Leave` the formatting is almost instantaneous, while any other `QualifierAlignment` setting takes a considerable amount of time. The more elements are in `QualifierOrder`, the longer it takes. Apparently, the `QualifierAlignmentFixer` goes over the whole file once for every single element in `QualifierOrder` (see the [loop over `Passes`](https://github.com/llvm/llvm-project/blob/77811752e3c7e3b354a235bd21d9aa076da9825a/clang/lib/Format/QualifierAlignmentFixer.cpp#L72)). So the setting 

        QualifierAlignment: Custom
        QualifierOrder: ['inline', 'static', 'constexpr', 'restrict', 'type', 'const', 'volatile' ]
    (I think 6 passes) is MUCH slower than just

        QualifierAlignment: Custom
        QualifierOrder: ['type', 'const' ]
    (1 pass).
So if you only really care about `const`, use that setting. For `QualifierAlignment: Left` and `QualifierAlignment: Right` the `QualifierOrder` contains 2 elements (`const` and `volatile`).

* The problem multiplies in presence of nested preprocessor directives. As far as I understand, clang-format does some macro evaluation. In the example of the OP, clang-format seems to generate 289 "variations" of the input file. (The [`UnwrappedLines`](https://github.com/llvm/llvm-project/blob/04e94bb12fe5c295d0c1b88bbcb49607a566136c/clang/lib/Format/TokenAnalyzer.cpp#L116) contains 289 elements, and each element seems to represent a version of the input file.) In other words, clang-format create 289 copies of the file, and each time the `QualifierAlignmentFixer` then goes another N times over the whole file, where N is the number of elements in `QualifierOrder`. So this scales very poorly.

**Comment by Sedeniono** [comment] 2023-05-13 17:36
I did some more digging and I think I understand the problem better and came up with a potential patch. My previous analysis was not complete.

In `clang::format::internal::reformat()` the code iterates over all individual passes (where a pass is a "formatting job"), one of which is `QualifierAlignmentFixer(...).process()`. This `process()` call is actually calling the generic implementation `TokenAnalyzer::process()`. `TokenAnalyzer::process()` [iterates over `UnwrappedLines`](https://github.com/llvm/llvm-project/blob/c19c248466cc730d46bbf3c3112791872661be5e/clang/lib/Format/TokenAnalyzer.cpp#L116), which in the example of the OP contains 289 entries. Each entry represents 1 variant of the input file, generated by evaluating preprocessor directives differently. For each entry, it calls `QualifierAlignmentFixer::analyze()` which does [a loop over a fixer for every qualifier](https://github.com/llvm/llvm-project/blob/c19c248466cc730d46bbf3c3112791872661be5e/clang/lib/Format/QualifierAlignmentFixer.cpp#L72) (in the code also called "Passes"). It calls `LeftRightQualifierAlignmentFixer(...).process()` each time, which again is the generic implementation in `TokenAnalyzer::process()`. There it **again** iterates over all 289 entries in `UnwrappedLines`, and calls `LeftRightQualifierAlignmentFixer::analyze()` for each.

So, boiled down, the structure looks like this:
```
for each of the 289 versions of the file in UnwrappedLines:
    for each configured qualifier:
        for each of the 289 versions of the file in UnwrappedLines:
            LeftRightQualifierAlignmentFixer::analyze()
```
This obviously scales quadratic with the number of preprocessor branches, causing the terrible performance. Generally speaking, it seems to be a bad idea to use a `TokenAnalyzer` within another `TokenAnalyzer` since this will always cause this double loop over `UnwrappedLines`.

I currently do not really see a good reason for the inner loop over the `UnwrappedLines`. So I attempted to fix the performance issue and created a potential patch [Patch_57117.patch](https://github.com/llvm/llvm-project/files/11470220/Patch_57117.patch). It does the following:
* It gets rid of the the double loop over `UnwrappedLines` by adding the passes for the individual qualifiers (i.e. the calls to `LeftRightQualifierAlignmentFixer(...).process()`) to the list of passes in `clang::format::internal::reformat()` directly, instead of using an intermediate `QualifierAlignmentFixer`. Hence, `QualifierAlignmentFixer` became obsolete and is removed.
* This change bypasses also the code in `QualifierAlignmentFixer::analyze()`. However, the code seems to have been [copy](https://github.com/llvm/llvm-project/blob/c19c248466cc730d46bbf3c3112791872661be5e/clang/lib/Format/Format.cpp#L3549-L3566) & [paste](https://github.com/llvm/llvm-project/blob/c19c248466cc730d46bbf3c3112791872661be5e/clang/lib/Format/QualifierAlignmentFixer.cpp#L72C19-L88) from `clang::format::internal::reformat()` anyway, except the [part at the end](https://github.com/llvm/llvm-project/blob/c19c248466cc730d46bbf3c3112791872661be5e/clang/lib/Format/QualifierAlignmentFixer.cpp#L90-L104) where it filters out replacements that do nothing ("NoOpFixes"). I originally tried to move that code to the individual qualifier analysis ([`LeftRightQualifierAlignmentFixer::analyze()`](https://github.com/llvm/llvm-project/blob/c19c248466cc730d46bbf3c3112791872661be5e/clang/lib/Format/QualifierAlignmentFixer.cpp#L612)), but this caused many test failures because the NoOpFixes-code relies on the fixes for all qualifiers to have been merged. So instead, in the patch I moved the code to the top level function `clang::format::internal::reformat()`. Of course, this then potentially affects the output of clang-format always, i.e. for all passes, not just for the qualifier fixer. I am really unsure of the implications, but maybe it is a good idea to filter replacements that do nothing always? In any case, all tests pass.
* Regarding the "NoOpFixes" code, the [original commit](https://github.com/llvm/llvm-project/commit/c2ec5dd209532b1d618958ade6a7d550a0c31ea5) that introduced it also added a test (`QualifierFixerTest.NoOpQualifierReplacements`). Unfortunately, the test got broken at some point since it [no longer tests the `ReplacementCount` of the first `verifyFormat`](https://github.com/llvm/llvm-project/blob/c19c248466cc730d46bbf3c3112791872661be5e/clang/unittests/Format/QualifierFixerTest.cpp#L1209-L1210). So my patch fixes this in order to test the effect of the "NoOpFixes" code again.

Formatting the [x86_amd64.hpp](https://github.com/OpenMPT/openmpt/blob/072d4ccc83d842cfa34601dddf2c69a4cc889c74/src/mpt/arch/x86_amd64.hpp) with the given [.clang-format](https://github.com/OpenMPT/openmpt/blob/072d4ccc83d842cfa34601dddf2c69a4cc889c74/src/mpt/.clang-format) file of the OP:
* Without the patch: 320s
* With the patch: 3s
* For comparison, with `QualifierAlignment: Leave`: 1.1s

So an increase of performance by two orders of magnitude 😃 The resulting files are identical.

Any opinions on the patch from someone with any clang-format experience, maybe @mydeveloperday? Especially regarding the NoOpFixes code that I moved to `clang::format::internal::reformat()`? Or should I just submit it for review?

**Comment by Sedeniono** [comment] 2023-06-18 15:44
I just submitted a fix for review: https://reviews.llvm.org/D153228

**Comment by HazardyKnusperkeks** [comment] 2023-06-18 19:21
> Or should I just submit it for review?

The answer is always: yes. :)
I for one don't look here at github (sorry, no time), but reviews I look at all (clang-format related), most of the time I also post something.

**Closed** 2023-07-07 23:16 UTC
Labels: clang-format, performance, awaiting-review
