### ISSUE TITLE
[HLSL] Implement derivative intrinsics

### ISSUE THREAD

**Issue by hekota** [llvm/llvm-project#88820] opened 2024-04-16 00:17 UTC
Implement HLSL derivative intrinsics `ddx`, `ddx_fine`, `ddx_coarse`, `ddy` , `ddy_fine` and `ddy_coarse`.

https://godbolt.org/z/1Ej8514MY

The `ddx` and `ddy` intrinsic were initially introduced in Shader Model 2.1 for pixel shaders:
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-ddx
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-ddy

Shader Model 5.0 added `ddx_fine`, `ddx_coarse`, `ddy_fine` and `ddy_coarse`, also just for pixel shaders:
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/ddx-fine
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/ddx-coarse
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/ddy-fine
https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/ddy-coarse

In DirectX the `ddx` and `ddy` functions default to coarse behavior - `ddx` is the same as `ddx_coarse` and `ddy` is the same as `ddy_coarse`.

In Shader model 6.6 the derivative intrinsics support was extended to compute, mesh and amplification shaders:
https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Derivatives.html

**Comment by davidcook-msft** [comment] 2024-04-16 19:00
Need an additional discussion on if we are using the rich availability diagnostics to also validate the numthreads on shaders using derivative intrinsics.

Conversation around if the availability diagnostics should be used for larger analysis should happen on the diagnostics spec.

**Comment by damyanp** [comment] 2024-09-17 20:33
@farzonl, @hekota  - is this now a dupe of the following issues?

* #99096 
* #99097 
* #99098
* #99099 
* #99100 
* #99101 

If so, is it ok to close this one?

**Comment by hekota** [comment] 2024-09-18 04:35
Yes, it looks like it is a dupe and can be closed!

**Closed** 2024-09-18 04:41 UTC
Labels: duplicate, backend:DirectX, HLSL
