### ISSUE TITLE
clang-format 13 and 14 breaks compile with braced initialization of lambda 

### ISSUE THREAD

**Issue by davidhunter22** [llvm/llvm-project#53409] opened 2022-01-25 19:35 UTC
The following code with the attached .clang-format file breaks code

```cpp
auto l { [] -> int
{
    int const x { 42 };

    return x;
}
};
```

Running "clang-format-13 test.cpp" produces the following

```cpp
auto l { [] -> int
         {
             int constx { 42 };

             return x;
         } };
```

Obviously Mardown has butchered the formating as it always does but the important thing is that the "int const x" is now "int constx" so the very important space has been removed which means the code will no longer compile.
Note if you use assignment rather than braced initialization so "auto l = [] ..." things work OK

[lambda.zip](https://github.com/llvm/llvm-project/files/7936629/lambda.zip)

**Comment by mydeveloperday** [comment] 2022-01-26 09:04
with LLVM default format we see this

```
auto l{[] -> int {
  int const x{42};

  return x;
}};
```

breaking down the settings that cause this to just

```
AlignConsecutiveDeclarations: Consecutive
Cpp11BracedListStyle: false
```

This produces the following

```
auto l{ [] -> int {
  int constx{ 42 };

  return x;
} };
```

Commenting out either of these will reverse this issue.

**Comment by mkurdej** [comment] 2022-01-26 09:10
Seems to be a duplicate of #45874.

**Closed** 2022-01-26 09:25 UTC
Labels: bug, duplicate, clang-format

**Comment by mydeveloperday** [comment] 2022-01-26 09:48
That you for seeing the duplicate... (worrying when we know our list of issues that intimately ;-) )
