### ISSUE TITLE
[flang][hlfir] No regressions on BLAS/LAPACK

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#64750] opened 2023-08-17 01:18 UTC
Part of https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778:
* @kiranchandramohan: BLAS/LAPACK should continue to work. We are in the process of checking where we are with this.

**Comment by kiranchandramohan** [comment] 2023-08-21 16:22
HLFIR lowering looks OK for the BLAS/LAPACK version that we run downstream.
@h-vetinari @mmuetzel Would you like to see whether your changes for OpenBLAS (https://github.com/xianyi/OpenBLAS/pull/4016) work with HLFIR lowering (`-flang-experimental-hlfir`)?

**Comment by h-vetinari** [comment] 2023-08-22 00:45
I'm still stuck trying to get flang 17 to work on windows (spread over a couple of issues; most are referenced from https://github.com/conda-forge/flang-feedstock/pull/28). I could build off of main with some effort, but I first want to be able to get flang 17 to compile a hello world on windows _at all_ (help would be much appreciated...). Once that's done, I can easily throw it at various of our code bases, with or without `-flang-experimental-hlfir`.

The OpenBLAS folks were further along with this already, perhaps @martin-frbg (or @mmuetzel) could retry building OpenBLAS using a flang build off of main with `-flang-experimental-hlfir`.

**Comment by kiranchandramohan** [comment] 2023-08-24 10:05
Thanks @martin-frbg @h-vetinari. I am closing this ticket as completed.

**Closed by kiranchandramohan** 2023-08-24 10:05 UTC
Labels: flang:hlfir-switch

**Comment by h-vetinari** [comment] 2023-08-24 10:45
Thanks @martin-frbg!

> There does however appear to be a regression in LLVM17's clang compilation of the AVX512 kernels for BLAS1 CASUM/ZASUM that looks similar to what Nvidia engineers found from their nvc [xianyi/OpenBLAS#4162 (comment)](https://github.com/xianyi/OpenBLAS/issues/4162#issuecomment-1655949959)

Worth another issue perhaps?

**Comment by martin-frbg** [comment] 2023-11-19 22:25
> Thanks @martin-frbg!
> 
> > There does however appear to be a regression in LLVM17's clang compilation of the AVX512 kernels for BLAS1 CASUM/ZASUM that looks similar to what Nvidia engineers found from their nvc [xianyi/OpenBLAS#4162 (comment)](https://github.com/xianyi/OpenBLAS/issues/4162#issuecomment-1655949959)
> 
> Worth another issue perhaps?

Just for the record - this was now found to be caused by unsafe coding in OpenBLAS that just happened to work with gcc
