### ISSUE TITLE
Undefined symbol boost::archive::archive_exception

### ISSUE THREAD

**Issue by zoharl3** [llvm/llvm-project#111889] opened 2024-10-10 18:43 UTC
https://stackoverflow.com/questions/79073953/clang-undefined-symbol-boostarchivearchive-exception

**Comment by sehe** [comment] 2024-10-10 19:26
This is not a valid problem description. Also, the linked post indicates this would be a duplicate of #58806

**Comment by zoharl3** [comment] 2024-10-10 20:06
I'm building the demo from the tutorial

https://www.boost.org/doc/libs/1_85_0/libs/serialization/doc/tutorial.html

I created the project using cmake for VS22 with clang-cl.exe, and the cmakefile.txt has

```
find_package( Boost REQUIRED COMPONENTS serialization )
if(Boost_FOUND)
    message( "Boost found: ${Boost_INCLUDE_DIRS}" )
    target_include_directories( ${PROJECT_NAME} PRIVATE ${Boost_INCLUDE_DIRS} )
    target_link_libraries(${PROJECT_NAME} ${Boost_LIBRARIES})
endif()
```

and I verified that the project is linked against `..\vcpkg_installed\x64-windows\debug\lib\boost_serialization-vc143-mt-gd-x64-1_85.lib`.

I get two linker errors:

```
lld-link : error : undefined symbol: __declspec(dllimport) public: void __cdecl boost::archive::archive_exception::`vbase dtor'(void)
lld-link : error : undefined symbol: public: void __cdecl boost::archive::archive_exception::`vbase dtor'(void)
```

When building with cl.exe, there are no errors.

**Comment by frederick-vs-ja** [comment] 2024-11-08 12:31
Closing this as duplicate of #58806.

**Closed by frederick-vs-ja** 2024-11-08 12:31 UTC
Labels: duplicate
