### ISSUE TITLE
Array parameter cannot be used in nested `consteval` function call

### ISSUE THREAD

**Issue by BertalanD** [llvm/llvm-project#57096] opened 2022-08-11 17:35 UTC
[Godbolt link](https://godbolt.org/z/qre1GKo66)

The following snippet does not compile with Clang (trunk), but does with MSVC and GCC:
```c++
template<unsigned int N>
consteval int inner(char const (&str)[N]) {
    return str[0];
}

template<unsigned int N>
consteval int func(char const (&str)[N]) {
    auto val = inner(str);
    return val;
}

auto var = func("test");
```

```console
<source>:8:16: error: call to consteval function 'inner<5U>' is not a constant expression
    auto val = inner(str);
               ^
<source>:12:12: note: in instantiation of function template specialization 'func<5U>' requested here
auto var = func("test");
           ^
<source>:8:22: note: function parameter 'str' with unknown value cannot be used in a constant expression
    auto val = inner(str);
                     ^
<source>:7:33: note: declared here
consteval int func(char const (&str)[N]) {
```

The issue can be worked around by making `inner` `constexpr` instead of `consteval`.

**Comment by usx95** [comment] 2022-08-20 03:54
Thanks for the report. Looks like the same issue of https://github.com/llvm/llvm-project/issues/51182

Duplicate of [51182](https://github.com/llvm/llvm-project/issues/51182)

**Comment by usx95** [comment] 2022-08-20 03:57
Duplicate of #51182

**Closed** 2022-08-20 03:57 UTC
Labels: c++20, clang:frontend
