### ISSUE TITLE
flang link failure when calling exp intrinsic with quad precision

### ISSUE THREAD

**Issue by ajmay81** [llvm/llvm-project#101207] opened 2024-07-30 17:23 UTC
Reproducer:
```
program test
implicit none
integer, parameter :: qp = selected_real_kind(30)
real(qp) :: qvar
qvar=1.0_qp
write(6,*)exp(qvar)
end program test
```
results in:
```
> flang-new test.f90 
./test.f90:7:11: warning: exp(real(kind=16)) cannot be folded on host
  write(6,*)exp(qvar)
            ^^^^^^^^^
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /tmp/test-81af64.o: in function `_QQmain':
FIRModule:(.text+0x87): undefined reference to `_FortranAExpF128'
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by clementval** [comment] 2024-07-31 20:45
Did you build flang with `-DFLANG_RUNTIME_F128_MATH_LIB=libquadmath`?

**Comment by ajmay81** [comment] 2024-07-31 21:46
> Did you build flang with `-DFLANG_RUNTIME_F128_MATH_LIB=libquadmath`?

No, I wasn't aware of this, but I see [it's required](https://flang.llvm.org/docs/Real16MathSupport.html), thanks for the tip - I'll rebulid my install.

Since it's known when flang is configured/built whether that option was given, wouldn't it be possible then to catch at compile time when such cases are not supported and issue an informative error message, rather than just discovering undefs at link time?

**Comment by clementval** [comment] 2024-08-01 17:06
Yes it could. Patches are welcome.

**Comment by klausler** [comment] 2024-08-01 18:44
Assigning to Kiran so that Arm can adjust the `evaluate::TargetCharacteristics` structure passed to semantics from the flang-new driver according to the target and the build flags.

**Comment by tblah** [comment] 2024-08-06 14:04
@klausler was this what you meant? https://github.com/llvm/llvm-project/pull/102147

With this change the reproducer in this ticket will fail to compile because `selected_real_kind(30)` will return `-1`.

If `real(16)` is used directly, there will be a warning saying the type is disabled for this target then the executable will still fail to link. I wonder if it might be more helpful to link to the [documentation](https://flang.llvm.org/docs/Real16MathSupport.html) and make this an error?

**Closed** 2024-08-28 15:33 UTC
Labels: flang:ir
