### ISSUE TITLE
#elifdef and #elifndef shouldn't have meaning prior to C23 in standards conformance mode

### ISSUE THREAD

**Issue by Halalaluyafail3** [llvm/llvm-project#84601] opened 2024-03-09 04:36 UTC
Prior to C23 there was no `#elifdef` or `#elifndef` directive, so they should be ignored like they were part of a skipped group in conditional inclusion. For example:
```c
#define X
#if 0
a
#elifdef X
b
#endif
```
The `#elifdef X` should be ignored here, similar to how any other directive would be ignored. Standards conformance modes such as `-std=c11` should avoid changing the behavior of strictly conforming programs, so I would expect this to expand to nothing. GCC will do this correctly (https://godbolt.org/z/476norbon), but Clang issues a warning and interprets the directive as it would in C23 mode (https://godbolt.org/z/vxs86781s). In `-std=gnu11` mode the extension is allowable since it doesn't have the same requirements on extensions (GCC does the same thing as Clang here, without the diagnostic).

**Comment by Sirraide** [comment] 2024-03-09 10:38
CC @AaronBallman

**Comment by AaronBallman** [comment] 2024-03-12 16:45
I think Clang's behavior is still conforming even in C standard conformance mode.

C17 6.10p6: Each directive’s condition is checked in order. If it evaluates to false (zero), the group that it controls is skipped: directives are processed only through the name that determines the directive in order to keep track of the level of nested conditionals; the rest of the directives’ preprocessing tokens are ignored, as are the other preprocessing tokens in the group. Only the first group whose control condition evaluates to true (nonzero) is processed; any following groups are skipped and their controlling directives are processed as if they were in a group that is skipped. If none of the conditions evaluates to true, and there is a #else directive, the group controlled by the #else is processed; lacking a #else directive, all the groups until the #endif are skipped.

I read "directives are processed only through the name that determines the directive in order to keep track of the level of nested conditionals; the rest of the directives’ preprocessing tokens are ignored, as are the other preprocessing tokens in the group." as allowing other groupings as an extension with the usual behavior of issuing pedantic diagnostics for people who need strict conformance.

However, 6.10p3 has an interesting bit I'd not noticed before: "A text line shall not begin with a # preprocessing token. A non-directive shall not begin with any of the directive names appearing in the syntax."

"shall not begin with any of the directive names" suggests that `#elifdef` and `#elifndef` are not valid non-directives in C17 and earlier, which suggests it's not a conforming extension.

CC @gustedt for a second opinion about conformance from someone well-versed in preprocessor specification.

Is there evidence that Clang's behavior is breaking code in the wild?

**Comment by cor3ntin** [comment] 2024-03-12 17:35
FYI I think it would be pretty... unintuitive (to put it midly) to have #elifdef be in effect ignored in some language modes and not other; the current behavior is the least surprising/error-prone.

**Comment by Sirraide** [comment] 2024-03-12 17:51
Yeah, that and, regarding what Aaron mentioned, I seriously doubt there is any actual code out there that is breaking because Clang supports e.g. `#elifdef` in language modes before C23—if anything, I’d argue any such code wouldn’t really make much sense to begin with: I can’t think of a singular reason as to why someone would ever just sprinkle random unsupported preprocessor directives (which is all they really are from a standards point of view in e.g. C17) throughout their code and expect anything of value to come from that—if that ever does happen w/ `#elifdef`, it’s probably because someone forgot to enable C23, and at that point, outright ignoring them is probably the worst we could do. 

Moreover, the `#elifdef` warning is already on by default in language modes before C23—even if you don’t pass any `-W` flags to Clang at all. So unless it turns out that there really is no way around ignoring it, then I’d say we’re already doing enough to warn users that they either should not be using `#elifdef` or should be using C23.

**Comment by Sirraide** [comment] 2024-03-12 17:54
One more thing because I just thought of this, but just ignoring it for the sake of GCC compatibility doesn’t really make sense either: Trying to be compatible with GCC only makes sense if it’s a feature that people actually use and I at least wouldn’t consider ‘`#elifdef` being ignored with no warning in language modes before C23’ as a ‘feature’ to begin with...

**Comment by AaronBallman** [comment] 2024-03-12 18:55
Yeah, I find GCC's behavior to be a bit surprising, though I can understand why they implemented it that way (less risk of breaking existing code). But I just... struggle to imagine non-pathological code breaking because of this, and I think GCC's behavior is less intuitive than Clang's in terms of what I think people expect.

**Comment by gustedt** [comment] 2024-03-12 21:07
Aaron,
I never understood the concept of "non-directives".
At the worst, having these beast in a program is UB, but the kinder form of UB that is there for implementations to invent extensions.
And I can't imagine any code being in conflict with the semantics of the new feature. Either such code would come from an implementation that already has this feature and does exactly the same, or it is completely hostile and clearly on the dark side. This is not a case like for identifiers where there may be plenty of conflicts with userspace choices.
So I'd suggest to be user friendly here, and accept this even in non-C23 mode.
Jens
-- 
Jens Gustedt - INRIA & ICube, Strasbourg, France

**Comment by AaronBallman** [comment] 2024-03-13 11:28
Great, thank you all! I think we're in agreement that this behavior is by design in Clang and that we're happy with that design decision. I'm closing this issue as won't fix unless we get more information to change this stance.

**Closed by AaronBallman** 2024-03-13 11:28 UTC
Labels: wontfix, c23, clang:frontend
