### ISSUE TITLE
[LICM][TBAA] LICM needlessly drops TBAA

### ISSUE THREAD

**Issue by wsmoses** [llvm/llvm-project#53794] opened 2022-02-12 19:52 UTC
See: https://godbolt.org/z/bcj3zEz7P

```llvm
; ModuleID = '<source>'
source_filename = "<source>"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: mustprogress nofree norecurse nosync nounwind uwtable
define void @licm(double** align 8 dereferenceable(8) %_M_start.i, i64 %numElem) {
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.body, %entry
  %k.0 = phi i64 [ 0, %entry ], [ %inc, %for.body ]
  %cmp = icmp ult i64 %k.0, %numElem
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.body:                                         ; preds = %for.cond
  %0 = load double*, double** %_M_start.i, align 8, !tbaa !3
  %add.ptr.i = getelementptr inbounds double, double* %0, i64 %k.0
  store double 2.000000e+00, double* %add.ptr.i, align 8, !tbaa !8
  %inc = add nuw i64 %k.0, 1
  br label %for.cond, !llvm.loop !10

for.cond.cleanup:                                 ; preds = %for.cond
  ret void
}

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{!"clang version 15.0.0 (https://github.com/llvm/llvm-project.git fc510998f7c287df2bc1304673e0cd8452d50b31)"}
!3 = !{!4, !5, i64 0}
!4 = !{!"_ZTSNSt12_Vector_baseIdSaIdEE17_Vector_impl_dataE", !5, i64 0, !5, i64 8, !5, i64 16}
!5 = !{!"any pointer", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C++ TBAA"}
!8 = !{!9, !9, i64 0}
!9 = !{!"double", !6, i64 0}
!10 = distinct !{!10, !11, !12}
!11 = !{!"llvm.loop.mustprogress"}
!12 = !{!"llvm.loop.unroll.disable"}
```

When the %0 load is hoisted, it no longer has TBAA:

```llvm
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @licm(double** align 8 dereferenceable(8) %_M_start.i, i64 %numElem) {
entry:
  %0 = load double*, double** %_M_start.i, align 8
  br label %for.cond

for.cond:                                         ; preds = %for.body, %entry
  %k.0 = phi i64 [ 0, %entry ], [ %inc, %for.body ]
  %cmp = icmp ult i64 %k.0, %numElem
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.body:                                         ; preds = %for.cond
  %add.ptr.i = getelementptr inbounds double, double* %0, i64 %k.0
  store double 2.000000e+00, double* %add.ptr.i, align 8, !tbaa !3
  %inc = add nuw i64 %k.0, 1
  br label %for.cond, !llvm.loop !7

for.cond.cleanup:                                 ; preds = %for.cond
  ret void
}

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{!"clang version 15.0.0 (https://github.com/llvm/llvm-project.git fc510998f7c287df2bc1304673e0cd8452d50b31)"}
!3 = !{!4, !4, i64 0}
!4 = !{!"double", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = distinct !{!7, !8, !9}
!8 = !{!"llvm.loop.mustprogress"}
!9 = !{!"llvm.loop.unroll.disable"}
```

**Comment by wsmoses** [comment] 2022-02-12 20:08
This also appears to drop debug info as well.

This pattern appears quite common (as this originally arises in the context of a std::vector)

**Comment by nikic** [comment] 2022-02-12 20:10
It is not legal to preserve TBAA on a speculatively executed load. LICM will preserve the metadata if the load is guaranteed to execute. In your particular example, the load may not be executed if `%numElems` is zero.

**Comment by nikic** [comment] 2022-02-12 20:48
@wsmoses As a matter of general policy, we prefer doing optimizations that require dropping metadata or attributes over not doing them. This is obviously better on average, and avoids awkward situations where inferring more information in one place inhibits later optimizations.

We're certainly not going to inhibit load hoisting to preserve TBAA. We can reconsider doing LICM before LoopRotate though. This is a recent change made in https://reviews.llvm.org/D99249, that is a win in some cases and a loss in others. You could probably present an argument that this is not the right tradeoff.

**Comment by wsmoses** [comment] 2022-02-12 20:59
Would it be reasonable making the speculative instruction conditionally executed above the loop in a limited set of circumstances (and thus preserve metadata).

The original code is complex because the condition is not loop-invariant, but suppose the speculation was due to a single loop-invariant condition, we could reproduce that outside the loop.

The loop-dependent condition is a bit more tricky and would require the outside loop condition to be a "any of the inner conditions are true".

**Comment by wsmoses** [comment] 2022-02-12 21:07
Another less-intrusive option:

Since we now run LICM both before and after Loop rotate, could we add an option to LICM to not speculatively hoist data that would drop information.

Thus we could still run LICM prior to LoopRotate and see those benefits (while preserving information), and the "full" LICM run would still perform all of the speculative information.

**Comment by nikic** [comment] 2022-02-12 21:10
> Would it be reasonable to make the speculative instruction conditionally executed above the loop in a limited set of circumstances (and thus preserve metadata).
> 
> The original code is complex because the condition is not loop-invariant, but suppose the speculation was due to a single loop-invariant condition, we could reproduce that outside the loop.
> 
> The loop-dependent condition is a bit more tricky and would require the outside loop condition to be a "any of the inner conditions are true".

I don't think that would be a profitable transform. In fact, if you do that, SimplifyCFG is just going to speculate the load out the branch lateron and drop the metadata anyway. Keeping around control flow to preserve TBAA metadata will be non-profitable outside a few very special circumstances.

**Comment by nikic** [comment] 2022-02-12 21:28
> Another less-intrusive option:
> 
> Since we now run LICM both before and after Loop rotate, could we add an option to LICM to not speculatively hoist data that would drop information.
> 
> Thus we could still run LICM prior to LoopRotate and see those benefits (while preserving information), and the "full" LICM run would still perform all of the speculative information.

I think this is principally viable. I would phrase this more generally in terms of only hoisting guaranteed-to-execute instructions, because any instructions that can be hoisted through speculation can also be speculated post-rotation.

Though I think we'd be better off dropping the first LICM run than complicating things in this direction. I believe the specific problem it was intended to solve was later addressed by emitting necessary alignment attributes in clang.

**Comment by wsmoses** [comment] 2022-02-12 21:35
I'm okay with either approach, what do you recommend and how do we proceed?

**Comment by davidbolvansky** [comment] 2022-02-12 22:11
Drop LICM run before LoopRotate in pass manager?

**Comment by wsmoses** [comment] 2022-02-16 19:38
Added the speculative option in the PR here: https://reviews.llvm.org/D119965.

**Closed** 2022-02-18 04:57 UTC
Labels: llvm:core
