### ISSUE TITLE
clang frontend crashed.

### ISSUE THREAD

**Issue by ComixHe** [llvm/llvm-project#59508] opened 2022-12-13 20:24 UTC
When I compile a project called [co_context](https://github.com/Codesire-Deng/co_context), the clang frontend crashed.
here are some info

```console
Stack dump:
0.      Program arguments: /usr/bin/clang++ -DLIBURINGCXX_KERNEL_VERSION_MAJOR=6 -DLIBURINGCXX_KERNEL_VERSION_PATCHLEVEL=0 -DUSE_MIMALLOC -I/home/comix/workspace/co_context/include -fsized-deallocation -std=c++20 -Wall -march=native -flto -O3 -DNDEBUG -std=gnu++20 -MD -MT test/CMakeFiles/swtch.dir/swtch.cpp.o -MF test/CMakeFiles/swtch.dir/swtch.cpp.o.d -o test/CMakeFiles/swtch.dir/swtch.cpp.o -c /home/comix/workspace/co_context/test/swtch.cpp
1.      <eof> parser at end of file
2.      Optimizer
3.      While splitting coroutine @_Z1fRK5swtch
 #0 0x00007f90d82d545a (/usr/lib/libLLVM-14.so+0xcd545a)
 #1 0x00007f90d82d2aef llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-14.so+0xcd2aef)
 #2 0x00007f90d81bfb59 (/usr/lib/libLLVM-14.so+0xbbfb59)
 #3 0x00007f90d7051a00 (/usr/lib/libc.so.6+0x38a00)
 #4 0x00007f90d805e248 (/usr/lib/libLLVM-14.so+0xa5e248)
 #5 0x00007f90d9a218af (/usr/lib/libLLVM-14.so+0x24218af)
 #6 0x00007f90d9a23b91 llvm::CoroSplitPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/lib/libLLVM-14.so+0x2423b91)
 #7 0x00007f90dba1ea56 (/usr/lib/libLLVM-14.so+0x441ea56)
 #8 0x00007f90d9ac3ec9 llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/lib/libLLVM-14.so+0x24c3ec9)
 #9 0x00007f90d97e5206 (/usr/lib/libLLVM-14.so+0x21e5206)
#10 0x00007f90d9ac6f30 llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/lib/libLLVM-14.so+0x24c6f30)
#11 0x00007f90d97e51b6 (/usr/lib/libLLVM-14.so+0x21e51b6)
#12 0x00007f90d9ac581e llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/libLLVM-14.so+0x24c581e)
#13 0x00007f90d97ea5c3 llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/libLLVM-14.so+0x21ea5c3)
#14 0x00007f90dba1fb76 (/usr/lib/libLLVM-14.so+0x441fb76)
#15 0x00007f90d8487ea4 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/libLLVM-14.so+0xe87ea4)
#16 0x00007f90e0c9a3d5 (/usr/lib/libclang-cpp.so.14+0x249a3d5)
#17 0x00007f90dfc9e804 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib/libclang-cpp.so.14+0x149e804)
#18 0x00007f90dff7c32c (/usr/lib/libclang-cpp.so.14+0x177c32c)
#19 0x00007f90defd9f9b clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/libclang-cpp.so.14+0x7d9f9b)
#20 0x00007f90e05b3f39 clang::FrontendAction::Execute() (/usr/lib/libclang-cpp.so.14+0x1db3f39)
#21 0x00007f90e0553427 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.14+0x1d53427)
#22 0x00007f90e060ae7a clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/libclang-cpp.so.14+0x1e0ae7a)
#23 0x0000555bfb4226f1 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang+++0x176f1)
#24 0x0000555bfb424337 (/usr/bin/clang+++0x19337)
#25 0x00007f90e02aaa79 (/usr/lib/libclang-cpp.so.14+0x1aaaa79)
#26 0x00007f90d81bfc27 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/libLLVM-14.so+0xbbfc27)
#27 0x00007f90e02b05df (/usr/lib/libclang-cpp.so.14+0x1ab05df)
#28 0x00007f90e02c5d33 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/lib/libclang-cpp.so.14+0x1ac5d33)
#29 0x00007f90e02c6109 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/lib/libclang-cpp.so.14+0x1ac6109)
#30 0x00007f90e02ce442 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib/libclang-cpp.so.14+0x1ace442)
#31 0x0000555bfb41946a main (/usr/bin/clang+++0xe46a)
#32 0x00007f90d703c290 (/usr/lib/libc.so.6+0x23290)
#33 0x00007f90d703c34a __libc_start_main (/usr/lib/libc.so.6+0x2334a)
#34 0x0000555bfb41a655 _start (/usr/bin/clang+++0xf655)
clang-14: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-14: note: diagnostic msg: 
```

swtch-275612.cpp and switch-275612.sh: [swtch-275612.zip](https://github.com/llvm/llvm-project/files/10221742/swtch-275612.zip)

**Comment by ChuanqiXu9** [comment] 2022-12-14 01:43
Would you like to provide a minimal reproducer?

**Comment by ComixHe** [comment] 2022-12-14 07:04
I didn't write this project, the source code is [here](https://github.com/Codesire-Deng/co_context/blob/main/test/swtch.cpp).

**Comment by ChuanqiXu9** [comment] 2022-12-14 08:22
It would be hard to fix problems without a reduced reproducer.  It would be best to be something like  the reproducer in https://github.com/llvm/llvm-project/issues/59221, which is a minimal reproducer. Or at least, the bug report should contain a single reproducible preprocessed source file.

**Comment by Codesire-Deng** [comment] 2022-12-19 12:13
@ChuanqiXu9 @ComixHe 
Hi there! I could provide a small reproducer:

`bug.cpp`:
```cpp
#include <coroutine>

class task {
  public:
    using final_awaiter = std::suspend_always;

    struct promise_type {
        std::suspend_always initial_suspend() const noexcept { return {}; }

        std::suspend_always final_suspend() const noexcept { return {}; }

        task get_return_object() const noexcept { return task{}; }

        void unhandled_exception() const noexcept {};

        void return_void() const noexcept {}
    };
};

unsigned count = 0;

task fun() {
    while (count++ < 100) {
        co_await std::suspend_always{};
    }
}

int main() {
    return 0;
}
```
Compile it with `clang-14 -lstdc++ -O2 -std=c++20  bug.cpp`, where  then the problem happens.

```bash
➜ clang-14 --version
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Something as far as I know:
1. This problem disappears on clang 16.0.0-git 36a879e80f8179358001a7a6cfad7adec6e02504.
2. This problem disappears if I move `unsigned count = 0;` inside `fun()`.
3. This problem happens with `-O2`, `-O3`, `-Os` and disappears with `-O1`.
4. According to @ComixHe , the problem may still happen on clang 16.0.0-git 97842fcba9e3a. I didn't have a try.

**Comment by shafik** [comment] 2022-12-19 13:32
This looks fixed on trunk: https://godbolt.org/z/xE7oxenbe

**Comment by ChuanqiXu9** [comment] 2022-12-20 01:51
I failed to reproduce it in 97842fcba9e3a3fa4db52a47215 too.

**Comment by ComixHe** [comment] 2022-12-20 06:18
Native Env: 
ArchLinux
clang-git(16.0.0_r441380.97842fcba9e3a-1)

```
clang++ -lstdc++ -O1 -std=c++20 test.cpp
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /usr/bin/clang-16 -cc1 -triple x86_64-pc-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/home/comix -resource-dir /usr/lib/clang/16.0.0 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/x86_64-pc-linux-gnu -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/backward -internal-isystem /usr/lib/clang/16.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/home/comix -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/test-b9f302.o -x c++ test.cpp
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x00007f2dc04b6bd9 (/usr/bin/../lib/libLLVM-16.so+0xcb6bd9)
 #1 0x00007f2dc046c77f llvm::sys::RunSignalHandlers() (/usr/bin/../lib/libLLVM-16.so+0xc6c77f)
 #2 0x00007f2dc046c947 (/usr/bin/../lib/libLLVM-16.so+0xc6c947)
 #3 0x00007f2dbf251a00 (/usr/bin/../lib/libc.so.6+0x38a00)
 #4 0x00007f2dc192782e llvm::MemorySSA::~MemorySSA() (/usr/bin/../lib/libLLVM-16.so+0x212782e)
 #5 0x00007f2dc30d0348 (/usr/bin/../lib/libLLVM-16.so+0x38d0348)
 #6 0x00007f2dc063e3ec llvm::AnalysisManager<llvm::Function>::invalidate(llvm::Function&, llvm::PreservedAnalyses const&) (/usr/bin/../lib/libLLVM-16.so+0xe3e3ec)
 #7 0x00007f2dc17e51fc llvm::CGSCCToFunctionPassAdaptor::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/bin/../lib/libLLVM-16.so+0x1fe51fc)
 #8 0x00007f2dc23808a5 (/usr/bin/../lib/libLLVM-16.so+0x2b808a5)
 #9 0x00007f2dc17e1fc2 llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/bin/../lib/libLLVM-16.so+0x1fe1fc2)
#10 0x00007f2dc156e2e5 (/usr/bin/../lib/libLLVM-16.so+0x1d6e2e5)
#11 0x00007f2dc17e25a4 llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/bin/../lib/libLLVM-16.so+0x1fe25a4)
#12 0x00007f2dc156df95 (/usr/bin/../lib/libLLVM-16.so+0x1d6df95)
#13 0x00007f2dc17e3f3e llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0x1fe3f3e)
#14 0x00007f2dc156e295 (/usr/bin/../lib/libLLVM-16.so+0x1d6e295)
#15 0x00007f2dc066088d llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0xe6088d)
#16 0x00007f2dc156daa2 llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0x1d6daa2)
#17 0x00007f2dc30a27e5 (/usr/bin/../lib/libLLVM-16.so+0x38a27e5)
#18 0x00007f2dc066088d llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0xe6088d)
#19 0x00007f2dc82a3b43 (/usr/bin/../lib/libclang-cpp.so.16+0x16a3b43)
#20 0x00007f2dc82a7383 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/usr/bin/../lib/libclang-cpp.so.16+0x16a7383)
#21 0x00007f2dc85c5a89 (/usr/bin/../lib/libclang-cpp.so.16+0x19c5a89)
#22 0x00007f2dc74bab70 clang::ParseAST(clang::Sema&, bool, bool) (/usr/bin/../lib/libclang-cpp.so.16+0x8bab70)
#23 0x00007f2dc8c80189 clang::FrontendAction::Execute() (/usr/bin/../lib/libclang-cpp.so.16+0x2080189)
#24 0x00007f2dc8c20e7f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/bin/../lib/libclang-cpp.so.16+0x2020e7f)
#25 0x00007f2dc8ce8582 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/bin/../lib/libclang-cpp.so.16+0x20e8582)
#26 0x0000556fdc58c320 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-16+0x11320)
#27 0x0000556fdc5904c0 (/usr/bin/clang-16+0x154c0)
#28 0x0000556fdc591105 clang_main(int, char**) (/usr/bin/clang-16+0x16105)
#29 0x00007f2dbf23c290 (/usr/bin/../lib/libc.so.6+0x23290)
#30 0x00007f2dbf23c34a __libc_start_main (/usr/bin/../lib/libc.so.6+0x2334a)
#31 0x0000556fdc587cf5 _start (/usr/bin/clang-16+0xccf5)
clang-16: error: unable to execute command: Segmentation fault (core dumped)
clang-16: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 16.0.0 (/startdir/llvm-project 97842fcba9e3a3fa4db52a47215641f9141fea63)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Maybe it's a problem with the clang-git package on ArchLinux?

**Comment by ChuanqiXu9** [comment] 2022-12-20 08:06
> Native Env: ArchLinux clang-git(16.0.0_r441380.97842fcba9e3a-1)
> 
> ```
> clang++ -lstdc++ -O1 -std=c++20 test.cpp
> PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
> Stack dump:
> 0.      Program arguments: /usr/bin/clang-16 -cc1 -triple x86_64-pc-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/home/comix -resource-dir /usr/lib/clang/16.0.0 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/x86_64-pc-linux-gnu -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../include/c++/12.2.0/backward -internal-isystem /usr/lib/clang/16.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/home/comix -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/test-b9f302.o -x c++ test.cpp
> 1.      <eof> parser at end of file
> 2.      Optimizer
>  #0 0x00007f2dc04b6bd9 (/usr/bin/../lib/libLLVM-16.so+0xcb6bd9)
>  #1 0x00007f2dc046c77f llvm::sys::RunSignalHandlers() (/usr/bin/../lib/libLLVM-16.so+0xc6c77f)
>  #2 0x00007f2dc046c947 (/usr/bin/../lib/libLLVM-16.so+0xc6c947)
>  #3 0x00007f2dbf251a00 (/usr/bin/../lib/libc.so.6+0x38a00)
>  #4 0x00007f2dc192782e llvm::MemorySSA::~MemorySSA() (/usr/bin/../lib/libLLVM-16.so+0x212782e)
>  #5 0x00007f2dc30d0348 (/usr/bin/../lib/libLLVM-16.so+0x38d0348)
>  #6 0x00007f2dc063e3ec llvm::AnalysisManager<llvm::Function>::invalidate(llvm::Function&, llvm::PreservedAnalyses const&) (/usr/bin/../lib/libLLVM-16.so+0xe3e3ec)
>  #7 0x00007f2dc17e51fc llvm::CGSCCToFunctionPassAdaptor::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/bin/../lib/libLLVM-16.so+0x1fe51fc)
>  #8 0x00007f2dc23808a5 (/usr/bin/../lib/libLLVM-16.so+0x2b808a5)
>  #9 0x00007f2dc17e1fc2 llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/bin/../lib/libLLVM-16.so+0x1fe1fc2)
> #10 0x00007f2dc156e2e5 (/usr/bin/../lib/libLLVM-16.so+0x1d6e2e5)
> #11 0x00007f2dc17e25a4 llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/usr/bin/../lib/libLLVM-16.so+0x1fe25a4)
> #12 0x00007f2dc156df95 (/usr/bin/../lib/libLLVM-16.so+0x1d6df95)
> #13 0x00007f2dc17e3f3e llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0x1fe3f3e)
> #14 0x00007f2dc156e295 (/usr/bin/../lib/libLLVM-16.so+0x1d6e295)
> #15 0x00007f2dc066088d llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0xe6088d)
> #16 0x00007f2dc156daa2 llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0x1d6daa2)
> #17 0x00007f2dc30a27e5 (/usr/bin/../lib/libLLVM-16.so+0x38a27e5)
> #18 0x00007f2dc066088d llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/bin/../lib/libLLVM-16.so+0xe6088d)
> #19 0x00007f2dc82a3b43 (/usr/bin/../lib/libclang-cpp.so.16+0x16a3b43)
> #20 0x00007f2dc82a7383 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/usr/bin/../lib/libclang-cpp.so.16+0x16a7383)
> #21 0x00007f2dc85c5a89 (/usr/bin/../lib/libclang-cpp.so.16+0x19c5a89)
> #22 0x00007f2dc74bab70 clang::ParseAST(clang::Sema&, bool, bool) (/usr/bin/../lib/libclang-cpp.so.16+0x8bab70)
> #23 0x00007f2dc8c80189 clang::FrontendAction::Execute() (/usr/bin/../lib/libclang-cpp.so.16+0x2080189)
> #24 0x00007f2dc8c20e7f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/bin/../lib/libclang-cpp.so.16+0x2020e7f)
> #25 0x00007f2dc8ce8582 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/bin/../lib/libclang-cpp.so.16+0x20e8582)
> #26 0x0000556fdc58c320 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-16+0x11320)
> #27 0x0000556fdc5904c0 (/usr/bin/clang-16+0x154c0)
> #28 0x0000556fdc591105 clang_main(int, char**) (/usr/bin/clang-16+0x16105)
> #29 0x00007f2dbf23c290 (/usr/bin/../lib/libc.so.6+0x23290)
> #30 0x00007f2dbf23c34a __libc_start_main (/usr/bin/../lib/libc.so.6+0x2334a)
> #31 0x0000556fdc587cf5 _start (/usr/bin/clang-16+0xccf5)
> clang-16: error: unable to execute command: Segmentation fault (core dumped)
> clang-16: error: clang frontend command failed due to signal (use -v to see invocation)
> clang version 16.0.0 (/startdir/llvm-project 97842fcba9e3a3fa4db52a47215641f9141fea63)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> ```
> 
> Maybe it's a problem with the clang-git package on ArchLinux?

Would you like to reproduce this on trunk? If we can't reproduce it on trunk, we can close this issue.

**Closed** 2022-12-20 15:32 UTC
Labels: crash, coroutines
