### ISSUE TITLE
`substitution failure` for template argument pack in template argument

### ISSUE THREAD

**Issue by rroohhh** [llvm/llvm-project#71811] opened 2023-11-09 14:22 UTC
The following code
```cpp
#include <utility>
#include <variant>
#include <vector>

template <class T>
class Wrap {};


template <
    template <typename>
    class Prefix,
    template <typename>
    typename OuterType,
    typename... InnerTypes>
auto prefix_inner_types_helper(OuterType<InnerTypes...> v) -> OuterType<Prefix<InnerTypes>...>;


using ReadResult = std::variant<std::monostate, std::vector<int>>;

using PromiseType =
    decltype(prefix_inner_types_helper<Wrap>(std::declval<ReadResult>()));
```
gives the following error:
```
<source>:21:14: error: no matching function for call to 'prefix_inner_types_helper'
   21 |     decltype(prefix_inner_types_helper<Wrap>(std::declval<ReadResult>()));
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:15:6: note: candidate template ignored: substitution failure [with Prefix = Wrap]: template template argument has different template parameters than its corresponding template template parameter
   21 | auto prefix_inner_types_helper(OuterType<InnerTypes...> v) -> OuterType<Prefix<InnerTypes>...>;
      |      ^
   22 | 
   23 | 
   24 | using ReadResult = std::variant<std::monostate, std::vector<int>>;
   25 | 
   26 | using PromiseType =
   27 |     decltype(prefix_inner_types_helper<Wrap>(std::declval<ReadResult>()));
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```
while `gcc` accepts it without any complaints.
(See https://godbolt.org/z/7qoWsWe4a)

**Comment by shafik** [comment] 2023-11-16 21:16
This is fixed using `-frelaxed-template-template-args`: https://godbolt.org/z/rPGa1TEn7

We tried turning this on by default: https://discourse.llvm.org/t/why-frelaxed-template-template-args-is-added-back/65727 but a cuda thrust seems to have an issue: https://reviews.llvm.org/D109496

I don't know if and when this will be picked up again. 

CC @mizvekov @cor3ntin @AaronBallman

**Comment by mizvekov** [comment] 2024-04-27 19:37
Duplicate of https://github.com/llvm/llvm-project/issues/55894

**Closed by mizvekov** 2024-04-27 19:37 UTC
Labels: clang:frontend
