### ISSUE TITLE
clang-scan-deps unable to find system headers in p1689 format

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#61006] opened 2023-02-26 17:40 UTC
While testing modules with CMake I ran into an issue that some system headers are not found.

I tested with `Debian clang version 17.0.0 (++20230226071743+b8df886c1e2a-1~exp1~20230226071846.576)`

And this code
```cpp
module;
#include <vector>
export module test;
void test() {}
```
Compilation with Clang succeeds
```shell
/usr/bin/clang++-17 -stdlib=libc++ -std=c++20 -x c++ test.cppm -c -o /tmp/test.cppm.o
```

But testing with the dependency scanner
```shell
/usr/bin/clang-scan-deps-17 -format=p1689 -- /usr/bin/clang++-17 -stdlib=libc++ -std=c++20 -x c++ test.cppm -c -o /tmp/test.cppm.o
```

Fails with the following output
```console
Error while scanning dependencies for test.cppm:
In file included from test.cppm:3:
In file included from /usr/bin/../include/c++/v1/vector:281:
In file included from /usr/bin/../include/c++/v1/__algorithm/copy.h:12:
In file included from /usr/bin/../include/c++/v1/__algorithm/copy_move_common.h:12:
In file included from /usr/bin/../include/c++/v1/__algorithm/iterator_operations.h:15:
In file included from /usr/bin/../include/c++/v1/__iterator/advance.h:26:
In file included from /usr/bin/../include/c++/v1/cstdlib:87:
In file included from /usr/bin/../include/c++/v1/stdlib.h:94:
In file included from /usr/include/stdlib.h:31:
/usr/bin/../include/c++/v1/stddef.h:17:15: fatal error: 'stddef.h' file not found
{
  "revision": 0,
  "rules": [],
  "version": 1
}
```
The line where the header is not found uses `#include_next <stddef.h>` to include `stddef.h`.

I get similar errors when I don't specify libc++ and use libstdc++.

**Comment by ChuanqiXu9** [comment] 2023-02-27 03:01
What is the path of `<stddef.h>` in your system? Does it live in `/usr/lib/clang/17/include`? If it doesn't live in the directory, then I can understand the behavior. 

I can reproduce this if I make <symbolic-linked-clang> a symbolic link of the real clang in another directory.  Since the clang-scan-deps won't invoke `<executable>` actually. The clang-scan-deps just use it to get the resource dir. In the case that we can't put builtin headers like `<stddef.h>` in the default resource dir, we can use `-I`  to specify the missing resource dir explicitly.

If this works for you, I'd like to update the document.

**Comment by HailToDodongo** [comment] 2023-02-27 10:35
Not OP, but is was having the same issue exclusively on Ubuntu when installing the latest snapshot package via APT.
Installing it from source on another Ubuntu or Arch machine works fine.
 
By default the package seems to create a broken link:
`/usr/lib/clang/17/include -> ../../llvm-17/lib/clang/17.0.0/include`
But only `/usr/lib/llvm-17/lib/clang/17/include` exists.
Changing this doesn't fix it however.

After adding `-I/usr/lib/clang/17/include` to the clang++ options clang-scan-deps works,
without the option it still fails.

Is this an expected behavior? 
Because what is strange to me is that clang itself works fine even without the setting.

**Comment by mordante** [comment] 2023-02-27 17:10
I did some more testing, using the good case with `--trace-includes` it finds `stddef.h` in the directory `/usr/lib/llvm-17/lib/clang/17/include`. Adding 
`-system /usr/lib/llvm-17/lib/clang/17/include` fixes clang-scan-deps.

Your suggestion to use the real path instead of a symlink works too. I think it would be nice if `clang-scan-deps` would resolve the symlink and use the proper directory, but since there is a solution I would consider this low priority. I will update the documentation to mention this limitation.

**Comment by mordante** [comment] 2023-02-27 18:38
I've created https://reviews.llvm.org/D144894

**Comment by tschuett** [comment] 2023-02-27 18:45
```console
> clang -print-resource-dir
```
clang knows where stddef.h is.

**Comment by mordante** [comment] 2023-02-27 18:52
> ```
> > clang -print-resource-dir
> ```
> 
> clang knows where stddef.h is.

Thanks for the info, this seems to work when using the symlink too. Maybe then it's trivial to fix. @ChuanqiXu9 if you want I can take a look at it.

**Comment by ChuanqiXu9** [comment] 2023-02-28 02:04
> > ```
> > > clang -print-resource-dir
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > clang knows where stddef.h is.
> 
> 
> Thanks for the info, this seems to work when using the symlink too. Maybe then it's trivial to fix. @ChuanqiXu9 if you want I can take a look at it.

I'll be pretty appreciated if you can look at it :)

**Comment by huangqinjin** [comment] 2023-03-26 16:43
I am trying to use clang-scan-deps from LLVM 16 as the scanner for gcc. 

Use the same code and replace `/usr/bin/clang++-17` with ` /usr/bin/g++`:

```shell
$ /opt/llvm-16/bin/clang-scan-deps -format=p1689 -- /usr/bin/g++ -std=c++20 -x c++ test.cppm -c -o /tmp/test.cppm.o
Error while scanning dependencies for test.cppm:
In file included from test.cppm:3:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/13/../../../../include/c++/13/vector:80:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/13/../../../../include/c++/13/bits/memory_resource.h:38:
/usr/bin/../lib64/gcc/x86_64-suse-linux/13/../../../../include/c++/13/cstddef:50:10: fatal error: 'stddef.h' file not found
{
  "revision": 0,
  "rules": [],
  "version": 1
}
```

On my system, `stddef.h` is in `/usr/lib64/gcc/x86_64-suse-linux/13/include`.

Manually adding `-isystem /usr/lib64/gcc/x86_64-suse-linux/13/include` resolves the issue.

**Comment by superg** [comment] 2023-04-30 16:15
Experiencing the same issue with Ubuntu 22.04 clang-17 nightly packages.
Two symlinks point to non existing paths:
```
/usr/lib/clang/17/include -> ../../llvm-17/lib/clang/17.0.0/include
/usr/lib/clang/17/lib -> ../../llvm-17/lib/clang/17.0.0/lib
```
My current workaround:
```sudo ln -s /usr/lib/llvm-17/lib/clang/17 /usr/lib/llvm-17/lib/clang/17.0.0```

**Comment by namniav** [comment] 2023-08-03 11:10
I have similar issue using clang-scan-deps with Apple Clang and macOS SDK. Leaving information in case it's helpful for fixing or for folks to find this issue.

``` $ clang-scan-deps --format=p1689 -- \
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ \
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
-std=c++20 -c test.cpp -o test.cpp.o
```

> ```
> Error while scanning dependencies for test.cpp:
> In file included from test.cpp:1:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:37:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:214:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:95:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/wchar.h:119:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wchar.h:89:10: fatal error: 'stdarg.h' file not found
> {
>   "revision": 0,
>   "rules": [],
>   "version": 1
> }
> ```

`test.cpp` just includes `<iostream>` and does nothing else.

The command following `--` works along without clang-scan-deps. By adding `-MD` we can also exam the location of `stdarg.h` which clang-scan-deps fails to find.

```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ \
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
-std=c++20 -MD -c test.cpp -o test.cpp.o
```
In `test.cpp.d`:
>   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include/stdarg.h

A temporary sloppy workaround, at user side of clang-scan-deps, could be adding this directory to `-I` flag in clang-scan-deps command, but I'm not sure whether it would introduce other problems that I did't encounter yet.

**Comment by ChuanqiXu9** [comment] 2023-08-04 09:52
I sent https://reviews.llvm.org/D157081

**Comment by ChuanqiXu9** [comment] 2023-08-11 05:58
Sadly, the above patch is incorrect strictly. To solve the issue manually, we can pass `--resource-dir-recipe invoke-compiler` to clang-scan-deps. What the option did actually is invoke `<clang++> -print-resource-dir` and recorded the result and then pass the result to the command line. It may be a little bit inefficient in the current usgae of `clang-scan-deps` with cmake. Since cmake will invoke clang-scan-deps a lot of times for a single file and then clang-scan-deps itself can't cache the results.

Maybe we need to add a mode to clang-scan-deps to accept the specified resource directory.

**Comment by ChuanqiXu9** [comment] 2023-08-11 07:19
Now I feel it is primarily a usage issue and we can't do a lot inside the clang-scan-deps itself. So I update the document (https://clang.llvm.org/docs/StandardCPlusPlusModules.html#possible-issues-failed-to-find-system-headers) and I am going to close the issue itself since there may not be more things to do in our repo.

While it is indeed user-infriendly and annoying, since clang-scan-deps is mainly used by build systems, so we can hope build systems to handle this well. Then we should file issues with corresponding build systems.

**Closed by ChuanqiXu9** 2023-08-11 07:19 UTC
Labels: clang-tools-extra, clang:modules

**Comment by ChuanqiXu9** [comment] 2023-08-11 07:29
The issue for cmake I registered is https://gitlab.kitware.com/cmake/cmake/-/issues/25180

**Comment by topazus** [comment] 2023-10-30 01:17
> After adding `-I/usr/lib/clang/17/include` to the clang++ options clang-scan-deps works,
> without the option it still fails.

Many thanks. I also encountered the similar error, which I used clang 17 and CMake 3.28 to compile a simple hello world project with c++20 modules, it also worked for me after adding `-I/usr/lib/clang/17/include` to clang++ compiler option.

**Comment by ScherbakovAl** [comment] 2023-12-13 10:01
Hello!
If I use /usr/lib64/ccache/clang, then I get an error "/usr/include/wchar.h:35:10: fatal error: 'stddef.h' file not found".
if I add set(CMAKE_CXX_FLAGS "-I/usr/lib/clang/17/include"), then the project will be assembled.

If I use /usr/bin/cmake , then the project will be built without adding a flag "-I/usr/lib/clang/17/include", but when setting up cmake there will be the following messages:

[proc] The command: clang -v exited with code: 1
[proc] The command: clang++ -v exited with code: 1

I'm using Fedora 39.

**Comment by ChuanqiXu9** [comment] 2023-12-13 10:20
> Hello! If I use /usr/lib64/ccache/clang, then I get an error "/usr/include/wchar.h:35:10: fatal error: 'stddef.h' file not found". if I add set(CMAKE_CXX_FLAGS "-I/usr/lib/clang/17/include"), then the project will be assembled.
> 
> If I use /usr/bin/clang , then the project will be built without adding a flag "-I/usr/lib/clang/17/include", but when setting up cmake there will be the following messages:
> 
> [proc] The command: clang -v exited with code: 1 [proc] The command: clang++ -v exited with code: 1
> 
> I'm using Fedora 39.

I don't get your point quite a lot. For the problem of failed to find , we recorded it here: https://clang.llvm.org/docs/StandardCPlusPlusModules.html#possible-issues-failed-to-find-system-headers. And if there are other problems, I think a new issue may be worthy.

**Comment by StellaSmith** [comment] 2024-05-26 02:33
I'm having the same issue in Fedora 40. When trying to invoke `"/usr/bin/clang-scan-deps" -format=p1689 -- /usr/lib64/ccache/clang++` it fails to find `stddef.h`, but if I change it to ``"/usr/bin/clang-scan-deps" -format=p1689 -- /usr/bin/clang++` it works.
