### ISSUE TITLE
[rejects-valid] void{} (DR 2351)

### ISSUE THREAD

**Issue by fsub** [llvm/llvm-project#58828] opened 2022-11-05 12:46 UTC
`clang version 15.0.0 (https://github.com/llvm/llvm-project.git 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137)`

`clang++ -std=c++20` rejects
```c
void f()
{
   return void{};
}
```
with
```
<source>:3:15: error: illegal initializer type 'void'
   return void{};
```
The code is valid considering DR 2351 [1] and accepted by recent versions of other major compilers [2].

[1] https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2351
[2] https://godbolt.org/z/x4Errshnb

**Comment by shafik** [comment] 2022-11-05 15:23
Duplicate of: https://github.com/llvm/llvm-project/issues/51552

**Closed by shafik** 2022-11-05 15:23 UTC
Labels: duplicate, clang:frontend
