### ISSUE TITLE
Too much indentation for pragma's in clang-format 16, was good in clang-format 15

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#61679] opened 2023-03-24 14:16 UTC
Given this which was indented using clang-format 15:

```c++
#pragma comment( \
    linker,      \
    "\"/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
```

using `_clang-format`:

```yaml
---
BasedOnStyle: Google
IndentWidth: 4
ColumnLimit: 100
...
```

clang-format 16 yields the following:

```c++
#pragma comment( \
        linker,  \
            "\"/manifestdependency:type='Win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
```

Notice the indentation for clang-format 16 is too much and not consistent with the clang-format doc.
Continuation should be 4 spaces, but clang-format 16 gives something else. The clang-format 15 behavior is
consistent with the doc.

**Comment by rymiel** [comment] 2023-03-26 01:36
Bisected to 037669de8bdff42fc17b72460bf8784403c8d055 / https://reviews.llvm.org/D136100

This change was related to OpenMP, and seems to have a change in continuation indent, but it doesn't seem to very explained, and I don't have further input since I don't do OpenMP.

**Comment by rymiel** [comment] 2023-03-28 14:16
Oops, this has already been fixed for 17 as discussed in the review, making this a duplicate of #59473

**Closed by rymiel** 2023-03-28 14:16 UTC
Labels: clang-format
