### ISSUE TITLE
[DirectX] remove module flag and function attribute not supported by DXIL

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#90773] opened 2024-05-01 20:33 UTC
The only module flags DXIL used are "Dwarf Version" and "Debug Info Version".

And the only string function attributes allowed in DXIL are "waveops-include-helper-lanes" and "fp32-denorm-mode".

Other string function attributes and module flags should be removed before emit DXIL.

**Comment by python3kgae** [comment] 2024-06-24 22:27
Reopen for missing the module flag part.

**Comment by python3kgae** [comment] 2024-06-25 17:37
Add PR to document module flag at DXC repo https://github.com/microsoft/DirectXShaderCompiler/pull/6722

**Comment by llvm-beanz** [comment] 2024-07-09 18:26
This is a duplicate of #96912

**Closed by llvm-beanz** 2024-07-09 18:26 UTC
Labels: backend:DirectX
