### ISSUE TITLE
Friended struct's template alias is unable to access class's private member

### ISSUE THREAD

**Issue by SteveZhangSZ** [llvm/llvm-project#54467] opened 2022-03-20 18:42 UTC
```
struct theFriend{
    template<class T>
    using theAlias = decltype(&T::i);
};

class theC{
    int i;
    public:
    friend struct theFriend;
};

int main(){
    (void)sizeof(theFriend::theAlias<theC>);
}
```

```theFriend``` is a friend of ```theC```, but its template alias, when provided with ```theC```, produces a compile-time error:

```
<source>:3:35: error: 'i' is a private member of 'theC'
    using theAlias = decltype(&T::i);
                                  ^
<source>:11:29: note: in instantiation of template type alias 'theAlias' requested here
    (void)sizeof(theFriend::theAlias<theC>);
                            ^
<source>:6:9: note: implicitly declared private here
    int i;
        ^
1 error generated.
Compiler returned: 1
```
GCC and MSVC compile the code without problems. [Godbolt link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAMwAHKSuADJ4DJgAcj4ARpjEElykAA6oCoRODB7evgHBaRmOAuGRMSzxiVzJdpgOWUIETMQEOT5%2BQbaY9sUMjc0EpdFxCUm2TS1teZ0KE4MRwxWj1QCUtqhexMjsHLPEXg4A1AQImABixHiuJgDsVhoAgofPx5gsKQYEmCb%2BbsgGCgUhwAKj9sCZHi9Dl4MkZjqcHrQ8EwgT8ACKHLD/AgATxSmAg5gAbMCQCA8CsfvcHrc0VSIQ9/iigSdMG5btSoRECIc8PTIS8Ul5YkjkCAGVCqJdXIc9gceayLlcGOh%2BTSbnT/NTuYcWEwIhBKXcJS8IAA3VB4dArDIAL0wqCoEEV0pVZNZiORCh%2BblZ7P82EpWoZtI4a1onAArLw/BwtKRUJx2ZZrLKNltMIdzP4eKQCJow2sANYgSNmAB0XAAnGZJGZ/P4zESbjd/K39JxJDGCwnOLwFCANHmC2s4LAYIgUKh3nQEuRKGgZ/REsBqmY%2BHQvsQBxBYj3YhFmjjOLnF2xBAB5Bi0Y9x3hYPVGcR30j4Yh1RxmzADl%2BYVR1LwvhPXhuW6HskViYgjw8LAewIS4WGAtYqAMYAFAANSuAB3C98VjXN%2BEEEQxHYKQZEERQVHUF9dGSAwjBQaxrH0PBYgHSA1lQFJeh/ftug/LIXBVKY/GSMIFnKSo9EKTIBBE6T0lkhghkk5Yuh6Bo5nkmp%2BPqAR%2BhaFSRiqcYBm00zDIk4yJDWBR022PR4MwHYeHDKNuxfRMOFUQIiQAWiJSRDmAZBkEOapyzMQ4IGTKxLFIQ5cEIEgs3rZJDg8JcElSnMVl4fM71HJBFxSWcyAoCASrKlB6NXfwNGSGhaC3Hc9xfA9mGIW9T2nc8CCvG8ewfQxgGfXM3wEr8f3jP8AKA7gQMEMCFpYyDoIwHZ43gvBEIW5DUIw7DcMYYDyOEURxDIwj5CUNQe10fx9BGxiU3iiD2MNBNuKyXj1IE5wIFcczxLKazkhk3pzIhrIjKWEzaj0votM8do9AR3oDPmUG4bR5HclEiyscWKSuFs%2BzSLzd8XLDDsOGjUhY3jLyfP8wLDiZOEuH8csNEraLYuYxL8CIYgcvSzLSuXHL/Dy4dCuLEAm3LZtAi4MwpDXDRJGCCMOC7UhEKCctAhuDQq2bG5JGrfxI0kKsGZ7Lz%2B0ckdSDHKAJwgYrp0lucKqq5cQDNZAUhSAB9M1qzDz5vwIMPVECjdmoSVr90PLrTrPRh%2BuvW942Gp9NvvPB33qKae1m5BAOp8glt1%2BMIKgrqYKLymdqQvgDswzAcLw07ruIy7pGuyi7poxWnoY0xXpsd74E476BF%2B9HBMB4SUbyMSVVhknUkUyGN4J6GSisnGdI0/S8dR8//qRgYd7U2YzMP3H79Pkmyc2Bzkic6m3LpjyTNOAJyCiwBQwdDiRyrOWGOsx%2BZMXikLZKotszix9mVHKZhZYFS0CsNYpwmBYESJ9EskYhy631ozXgTtbCDjlrgt2nskAbAIEKAg85KroMDo9TAwsSB6AHhdUiw9ZCj2oltKmp0sJQRSK7XW9MqG9g4BeQCbDDiOkOCzAKQUObAHCtzXmXB%2BZcOytmGW%2BURz4MwIQ0YJDSzkM7LwRCSsNAaDLOrKQ2tAj1Q0ESB2nk%2By0KHDgwstMzBOJAESLglYzBVg0I2MwkZAi%2BMkGWfxQCOAWPlqQEskgbjGw0DcSMNwiTNgSUSMwOtOD%2BEAdQwJIS8FhNqUorJuC1hfm3IJSQQA%3D%3D).

**Comment by shafik** [comment] 2023-09-18 16:30
duplicate of: https://github.com/llvm/llvm-project/issues/41693

**Closed** 2023-09-18 16:30 UTC
Labels: clang:frontend
