### ISSUE TITLE
Regression since 0efe111365 when building opencv with clang-cl 17.0.6 on Windows: clang-cl just hangs

### ISSUE THREAD

**Issue by emmenlau** [llvm/llvm-project#69428] opened 2023-10-18 07:54 UTC
I have reported a build issue of opencv in https://github.com/opencv/opencv/issues/24390. If needed I can clone the information here. Sadly, I am unable to provide a minimal reproducer, and building opencv is slightly more involved.

It would be great if somebody could still look at this, as opencv is quite a relevant library...

**Comment by DimitryAndric** [comment] 2023-10-18 08:47
One of the things you can try is identifying one or more instances of clang-cl that hang, and attempt to make it crash, so it produces test case files (preprocessed .cpp and .sh). On Linux you would simply send a `SIGABRT` to the process, and this would cause the clang-cl driver to create test case files, but on Windows I am unsure.

**Comment by emmenlau** [comment] 2023-10-18 10:02
Thanks a lot @DimitryAndric for this suggestion! If you or someone knows how I can create the test case files (on Windows), I would be happy to do so!

**Comment by Neumann-A** [comment] 2023-11-06 23:13
I observe the same issue with 17.0.4. Trying to install opencv4 via vcpkg using my clang-cl toolchain just hangs forever.

**Comment by emmenlau** [comment] 2023-11-15 14:57
Did anyone try with 17.0.5 yet?

**Comment by Neumann-A** [comment] 2023-11-28 09:49
@emmenlau Did you check your build logs carefully? I noticed when bisceting that there was an ICE somewhere at the start of the logs which I didn't notice at first. I don't know why ninja did not abort the build in this case and left it hanging.

**Comment by emmenlau** [comment] 2023-11-29 09:30
Hi @Neumann-A ,
I checked by logs back then quite carefully: I compared them with a diff-view with a working build using clang 16.x. As far as I could see there was no ICE in my case with clang 17.0.3. But its interesting that you could move one step ahead!
One thing I found (but can not try myself): there is an option where clang would print the full diagnostics even without a crash! Maybe this can help developers isolate the problem?

**Comment by emmenlau** [comment] 2024-01-08 10:01
Did anyone try clang-cl 17.0.6 yet?

**Comment by Neumann-A** [comment] 2024-01-08 10:24
> Did anyone try clang-cl 17.0.6 yet?

Same issue.
Master from end of November also same issue. I don't think it will be fixed for 18.

https://github.com/backengineering/llvm-msvc doesn't seem to have the issue

**Comment by emmenlau** [comment] 2024-01-08 11:27
Thanks @Neumann-A ! I'll try to run the build today with `-gen-reproducer` in the hope that devs will consider fixing this issue.

**Comment by Neumann-A** [comment] 2024-01-08 11:29
I mean I even bisected the issue. The ICE/hang happens since https://github.com/llvm/llvm-project/commit/0efe111365ae176671e01252d24028047d807a84. Reverting it fixes it.

**Comment by emmenlau** [comment] 2024-01-08 12:12
Oh my, that is very relevant! Thanks for sharing!!!

**Comment by emmenlau** [comment] 2024-01-23 06:47
Dear LLVM devs, could someone kindly consider this compiler hang? It is quite relevant to build openCV, which is a rather relevant library in the image analysis community...

**Comment by DimitryAndric** [comment] 2024-01-23 09:40
Somebody still needs to provide a .sh and .cpp file from one of those hanging builds. This is essential for reproducing the problem, and attempting to fix it.

**Comment by Neumann-A** [comment] 2024-01-23 11:12
> Somebody still needs to provide a .sh and .cpp file from one of those hanging builds. This is essential for reproducing the problem, and attempting to fix it.

#73538 and #73536 have reproducers and are related

**Closed** 2024-04-04 13:12 UTC
Labels: clang-cl, hang

**Comment by emmenlau** [comment] 2024-04-19 13:48
Is [a1f4ac7](https://github.com/llvm/llvm-project/commit/a1f4ac7704255627ac33ad67a22be5ac030f6179) in ClangCl 18.1.4? Because I still can not build OpenCV, it still hangs :-( :-(

**Comment by phoebewang** [comment] 2024-04-19 14:20
> Is [a1f4ac7](https://github.com/llvm/llvm-project/commit/a1f4ac7704255627ac33ad67a22be5ac030f6179) in ClangCl 18.1.4? Because I still can not build OpenCV, it still hangs :-( :-(

Not, it's not getting cherry-picked to 18 release.

**Comment by Nick-Kooij** [comment] 2024-05-22 01:44
The recently released Microsoft **Visual Studio 2022 17.9.10** now ships with headers that only support **LLVM 17** and up, compounding the issue.

Developers impacted by this issue, using clang-cl on Windows with using the latest Microsoft IDE/header, will be soon be stuck:
- LLVM 16 can't be used due to lack of header support
- LLVM 17 and up crash

**Comment by EugeneZelenko** [comment] 2024-05-22 01:57
> Thanks a lot for the feedback @phoebewang ! And there are probably strong reasons against picking it for the 18.x series, yes? It would be really great to have OpenCV build working again... :-(

Backports to 18.1.x were stopped recently, so it'll be necessary to wait for 19.

**Comment by efriedma-quic** [comment] 2024-05-22 19:38
This specifically only impacts code built with /EHa; does OpenCV really need to be built with that flag?

**Comment by phoebewang** [comment] 2024-05-23 08:23
> This specifically only impacts code built with /EHa; does OpenCV really need to be built with that flag?

Right. The `/EHa` was a dud in LLVM before 17. Removing it should have no side effect.

**Comment by emmenlau** [comment] 2024-05-23 09:30
@efriedma-quic , thanks a billion for this insight! No, I do not require `/EHa` and can happily build without. This reduces the severity of this issue a whole *lot*!

For other people looking into this, I'll just try now the following OpenCV diff:
```
diff --git a/cmake/OpenCVCompilerOptions.cmake b/cmake/OpenCVCompilerOptions.cmake
index eca6ff1a8a..04e31981bb 100644
--- a/cmake/OpenCVCompilerOptions.cmake
+++ b/cmake/OpenCVCompilerOptions.cmake
@@ -445,7 +445,12 @@ if(MSVC)
       string(REGEX REPLACE " /EH[^ ]* " " " ${flags} " ${${flags}}")
     endforeach()
     if(NOT " ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE} ${CMAKE_CXX_FLAGS_DEBUG}" MATCHES " /EH")
-      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHa")
+      if(NOT CV_CLANG)
+        # It is no longer recommended to use /EHa with clang-cl on MSVC. It
+        # makes the compiler hang. See also upstream issue (and i.e. comment):
+        # https://github.com/llvm/llvm-project/issues/69428#issuecomment-2126517886
+        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /EHa")
+      endif()
     endif()
   endif()
 
```

**Comment by phoebewang** [comment] 2024-05-23 12:29
`/EHsc` would be an independent issue. How about just removing `/EHa`?

**Comment by emmenlau** [comment] 2024-05-23 12:39
After removing `/EHa` the build complains that exceptions are not enabled (unless I'm just unable to configure OpenCV correctly and did a mistake, haha). Is that likely possible that removing `/EHa` alltogether disables exceptions?

**Comment by phoebewang** [comment] 2024-05-23 14:40
No sure, what I know is `/EHa` doesn't really enable asynchronous exceptions before LLVM17. Maybe it enabled partial or maybe the build script just checking the `/EH` strings?

**Comment by emmenlau** [comment] 2024-05-23 15:38
I've spend some time reading up on this, and I'm under the impression that any of the `/EHx` options needs to be added, otherwise exceptions are turned off by the compiler. See for example [here](https://learn.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170#to-set-this-compiler-option-in-the-visual-studio-development-environment) and [here](https://learn.microsoft.com/en-us/cpp/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line?view=msvc-170#next-steps).

This explains why removing `/EHa` disabled exceptions in opencv alltogether, thereby breaking the build.

> `/EHsc` would be an independent issue.

Can you elaborate about an independent issue? So does the current fix in clang 19 not address the issue of a compiler hang with `/EHsc`? Should I report it as a new issue?

**Comment by phoebewang** [comment] 2024-05-24 02:16
> This explains why removing `/EHa` disabled exceptions in opencv alltogether, thereby breaking the build.

I'm not expert of Clang driver. Just took a quick look, maybe you can try `-Xclang -fcxx-exceptions -Xclang -fexceptions` to enable exceptions without a `/EH*`?

> Can you elaborate about an independent issue? So does the current fix in clang 19 not address the issue of a compiler hang with `/EHsc`? Should I report it as a new issue?

I didn't see it else where. My justification is 1) `/EHsc` would not generate such `llvm.seh.*` intrinsics 2) the fixed issue is a crash issue if compiler built with assert on. A hang may or may not related with it. Did you check if the `/EHsc` option works with trunk code?

**Comment by mzukovec** [comment] 2025-01-08 10:51
clang-cl 19.1.6 builds the project successfully
