### ISSUE TITLE
[clang-tidy] misc-unused-parameters inconsistently misses intitializers

### ISSUE THREAD

**Issue by DaAwesomeP** [llvm/llvm-project#58116] opened 2022-10-02 23:49 UTC
I am seeing clang-tidy inconsistently warn or ignore about unused parameters in constructors where the initializer makes use of the parameter. It will complain about some parameters but not others.

I have some functions like:

```cpp
class MyClass {
  public:

    MyClass(Point point1, Point point2, MyStruct otherStruct, bool someBool, float someFloat)
      : mPoint1{ point1 }
      , mPoint2{ point2 }
      , mOtherStruct{ otherStruct }
      , mSomeBool{ someBool }
      , mSomeFloat{ someFloat } {}
    MyClass(Point point1, Point point2)
      : mPoint1{ point1 }
      , mPoint2{ point2 }
      , mOtherStruct{ MyStruct() }
      , mSomeBool{ false }
      , mSomeFloat{ 0 } {}
  private:
    Point mPoint1;
    Point mPoint2;
    MyStruct mOtherStruct;
    bool mSomeBool;
    float mSomeFloat;
};
```
I am seeing:
```console
/home/myuser/file.hpp:30:20: error: parameter 'point1' is unused [misc-unused-parameters,-warnings-as-errors]
    MyClass(Point point1, Point point2, MyStruct otherStruct, bool someBool, float someFloat)
                  ^~~~~~
                   /*point1*/
/home/myuser/file.hpp:30:34: error: parameter 'point2' is unused [misc-unused-parameters,-warnings-as-errors]
    MyClass(Point point1, Point point2, MyStruct otherStruct, bool someBool, float someFloat)
                                ^~~
                                 /*point2*/
/home/myuser/file.hpp:37:20: error: parameter 'point1' is unused [misc-unused-parameters,-warnings-as-errors]
    MyClass(Point point1, Point point2)
                  ^~~~~~
                   /*point1*/
/home/myuser/file.hpp:37:34: error: parameter 'point2' is unused [misc-unused-parameters,-warnings-as-errors]
    MyClass(Point point1, Point point2)
                                ^~~
                                 /*point2*/
```
Even though `point1` and `point2` are clearly used in the initializers. **More importantly, I am not seeing this warning for `otherStruct`, `someBool`, or `someFloat`.**

**Comment by DaAwesomeP** [comment] 2022-10-03 16:30
@njames93 Ah, my bad. I was changing variable names when copy-pasting. I edited above.

Interestingly, this warning disappeared after fixing other completely unrelated warnings (in other classes and functions).

**Comment by PiotrZSL** [comment] 2023-04-10 10:02
I assume that due to errors in code, clang produced invalid AST, and due to that didn't see usage of constructor arguments.
Closing, if problem still exist please re-open this issue and provide some minimal reproduction example.

**Closed by PiotrZSL** 2023-04-10 10:02 UTC
Labels: clang-tidy, worksforme
