### ISSUE TITLE
incompatible-pointer-types-discards-qualifiers trigger context?

### ISSUE THREAD

**Issue by mu578** [llvm/llvm-project#60980] opened 2023-02-24 18:35 UTC
Hello, 

can someone explain?

```
typedef uint32_t       xxx_uint32_t;
typedef xxx_uint32_t * xxx_vuint32_t;

xxx_uint32_t vec[10]      = { 0 };
// trigger incompatible-pointer-types-discards-qualifiers 
// why left operand is evaluated within that context as 
// a `unsigned int * const` expr vs `const unsigned int *`
const xxx_vuint32_t expr1 = (const xxx_uint32_t *)vec;
// end trigger

const xxx_vuint32_t expr2 = (xxx_uint32_t *)vec;
const xxx_vuint32_t expr3 = (const xxx_vuint32_t)vec;
const uint32_t * expr4    = (const uint32_t *)vec;
const uint32_t * expr5    = (const xxx_vuint32_t)vec;

Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.3.0
```

**Comment by AaronBallman** [comment] 2023-02-24 19:15
`typedef` types work somewhat unintuitively with qualifiers.

`const xxx_vuint32_t` is specifying `uint32_t *const` and not `uint32_t const *` (so it's a constant pointer to a mutable `uint32_t`, not a mutable pointer to a constant `uint32_t`).

`(const xxx_uint32_t *)` is specifying `uint32_t const *` and not `uint32_t *const`, so the typecast is dropping the const qualification of the pointer.

https://wiki.sei.cmu.edu/confluence/display/c/DCL05-C.+Use+typedefs+of+non-pointer+types+only has some good examples of why it's a problem to use qualifiers with a typedef type that hide a pointer.

Closing this issue as it's not a bug, but if you have further questions or concerns, feel free to reopen the issue with more comments.

**Closed by AaronBallman** 2023-02-24 19:15 UTC
Labels: question

**Comment by mu578** [comment] 2023-02-25 01:39
@AaronBallman thank you, that's perfectly fine, I remember over the years to have been hit a few times with that case, the problem here as API designers, qualifiers are primarily useful indicators first for endusers before having a coding functionality, somehow this drop qualifier force me to infer on my own policy and change coding conventions just because the expression is type-defined.
