### ISSUE TITLE
LLVM build fails with GCC 12 on GNU/Linux

### ISSUE THREAD

**Issue by DanielMYT** [llvm/llvm-project#55369] opened 2022-05-10 10:59 UTC
Using GCC 12.1.0 to build LLVM+Clang+LLD on GNU/Linux. Build fails with the following error with GCC 12, when it was fine with GCC 11:
```
[2478/3646] Building CXX object tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o
FAILED: tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o 
/usr/bin/c++ -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/sources/llvm/LLVM-build/tools/clang/lib/ASTMatchers/Dynamic -I/sources/llvm/tools/clang/lib/ASTMatchers/Dynamic -I/sources/llvm/tools/clang/include -I/sources/llvm/LLVM-build/tools/clang/include -I/sources/llvm/LLVM-build/include -I/sources/llvm/include -flarge-source-files -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -Os -DNDEBUG  -fno-exceptions -std=c++14 -MD -MT tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o -MF tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o.d -o tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o -c /sources/llvm/tools/clang/lib/ASTMatchers/Dynamic/Registry.cpp
{standard input}: Assembler messages:
{standard input}:132812: Error: unbalanced parenthesis in operand 2.
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
ninja: build stopped: subcommand failed.
```
Tested with LLVM 14.0.3. I haven't been able to test with a development git checkout, since LLVM takes too long to build to able to test it in other cases, so if it has been fixed upstream already, I apologise. I'll also be happy to provide any additional information if it is needed.

**Comment by DimitryAndric** [comment] 2022-05-10 16:45
> {standard input}: Assembler messages:
> {standard input}:132812: Error: unbalanced parenthesis in operand 2.
> {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
> c++: fatal error: Killed signal terminated program cc1plus

This is a symptom of gcc, or more specifically its cc1plus stage (the actual C++ compiler frontend) running out of memory, and then getting killed by the kernel.

Because gcc works by producing assembly output and piping it to a separate assembler process, the latter gets confused by its input being cut off right in the middle of something. E.g. this is not a bug in the assembler.

If this is not resolved by adding more memory or swap to your machine, try lowering the number of concurrent gcc instances. If you can reproduce an out-of-memory situation even with a reduced test case and plenty of memory available, you should report a bug on the gcc bug tracker.

**Closed by DimitryAndric** 2022-05-10 16:45 UTC
Labels: build-problem, platform:linux

**Comment by coffeebe4code** [comment] 2023-05-17 16:19
It's weird that I can get it in the same place every time, and someone else had it happen at the exact same place.
```
[3888/4830] Building CXX object tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o
FAILED: tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o 
```

**Comment by DimitryAndric** [comment] 2023-05-17 16:40
> It's weird that I can get it in the same place every time, and someone else had it happen at the exact same place.
> 
> ```
> [3888/4830] Building CXX object tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o
> FAILED: tools/clang/lib/ASTMatchers/Dynamic/CMakeFiles/obj.clangDynamicASTMatchers.dir/Registry.cpp.o 
> ```

That is possible, if this particular cpp file file takes lots of RAM to compile with gcc. It could also be a gcc bug.

**Comment by coffeebe4code** [comment] 2023-05-18 00:06
I was able to fix this by increasing my swapfile size. Most certainly oom.

**Comment by nairn62** [comment] 2023-10-27 14:19
I had the same problem compiling LLVM using GCC 13.2.0 under VMware using 8Gb. I increased the RAM to 32Gb, and the error went away, and it successfully compiled and linked.

**Comment by uis246** [comment] 2024-08-26 01:54
Same file(Registry.cpp) makes gcc13 spend 2 hours compiling this one file and then crash with OOM on 16+6GB of RAM and swap.
