### ISSUE TITLE
bugprone-forwarding-reference-overload shouldn't match some constructors with constraints

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#60179] opened 2023-01-21 05:05 UTC
This can be more nuanced than the `std::enable_if` suppression that happens, as concepts are substantially more transparent.

```cpp
template<class T, class U>
concept different_to = not std::same_as<T, U>;

struct S {
  // suppressed: std::input_iterator<S> is always false
  template<std::input_iterator I>
  S(I&& i) {}

  // warns: std::copyable<S> is true
  template<std::copyable T>
  S(T&& t) {}

  // suppressed: we have an explicit opt-out in the form of `not std::same_as<T>`
  template<different_to<S> T>
  requires std::copyable<T>
  S(T&& t) {}
};
```

**Comment by PiotrZSL** [comment] 2023-07-22 17:17
This is probably duplicate of #58230

**Closed** 2023-07-23 12:03 UTC
Labels: duplicate, enhancement, clang-tidy
