### ISSUE TITLE
Clang reports an undefined function that has been defined

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#73232] opened 2023-11-23 11:38 UTC
Not sure how to title this properly.

The original reproducer is just:

```c++
#include <string>
constexpr auto z = std::string("", 0);
```
with libstdc++.

Using cvise, I get:
```c++
template <typename _CharT>
struct basic_string {
  constexpr void _M_construct();

  constexpr basic_string() {
    _M_construct();
  }

};


basic_string<char *> a;


template <typename _CharT>
constexpr void basic_string<_CharT>::_M_construct(){}

constexpr basic_string<char*> z{};
```
https://godbolt.org/z/7PzreExcf

Clang's output is:

```console
<source>:18:16: error: constexpr variable 'z' must be initialized by a constant expression
   18 | constexpr auto z = basic_string<char *>();
      |                ^   ~~~~~~~~~~~~~~~~~~~~~~
<source>:6:5: note: undefined function '_M_construct' cannot be used in a constant expression
    6 |     _M_construct();
      |     ^
<source>:18:20: note: in call to 'basic_string()'
   18 | constexpr basic_string<char*> z{}
      |                    ^~~~~~~~~~~~~~~~~~~~~~
<source>:3:18: note: declared here
    3 |   constexpr void _M_construct();
      |                  ^
```

The problem vanishes if `a` is commented out, or if `basic_string` is not a template anymore.

**Comment by cor3ntin** [comment] 2023-11-23 13:06
same problem with free functions

```cpp
template <typename T>
constexpr void g(T);

constexpr int f() {
    g(0);
    return 0;
}

template <typename T> 
constexpr void g(T) {}

constexpr auto z = f();```

**Comment by cor3ntin** [comment] 2023-11-23 18:29
We probably want to call `Sema::InstantiateFunctionDefinition` in `CheckConstexprFunction`.
Unfortunately, `CheckConstexprFunction` does not have access to `Sema`. in general, nothing in ExprConstant has access to Sema.
To fix that we'd need to add a reference to Sema in `EvalInfo`, probably. A bit tedious. Anyone has a better idea? @erichkeane

**Comment by tbaederr** [comment] 2023-11-23 18:37
CC @AaronBallman and @zygoloid, maybe they have an idea

**Comment by zygoloid** [comment] 2023-11-23 22:54
Ultimately this is a language bug. There's no point of instantiation after the function template is defined and before the end of the TU -- we only get PoIs at uses and at end of TU.

What we should probably do is instantiate all used specializations at the point where the function template is defined (if it's constexpr). Constant evaluation shouldn't have side effects.

I'm pretty sure this is a duplicate of a (very) old PR.

**Comment by zygoloid** [comment] 2023-11-23 22:56
See CWG2497.

**Comment by cor3ntin** [comment] 2023-11-24 14:46
> Ultimately this is a language bug. There's no point of instantiation after the function template is defined and before the end of the TU -- we only get PoIs at uses and at end of TU.
> 
> What we should probably do is instantiate all used specializations at the point where the function template is defined (if it's constexpr). Constant evaluation shouldn't have side effects.

Hum, I can see how trying to do instantiations in the middle of constant evaluation would not be great, thanks!

Do you think we should wait for core to resolve the issue, or should we try to eagerly instantiate at the end of the definition of constexpr functions?

**Comment by zygoloid** [comment] 2023-11-25 06:08
I think we should eagerly start instantiating at the end of definitions. (Both function and variable templates are affected by this IIRC.)

**Closed** 2023-11-30 07:45 UTC
Labels: clang:frontend, rejects-valid, confirmed

**Comment by cor3ntin** [comment] 2023-12-02 12:40
Reverted in https://github.com/llvm/llvm-project/commit/19e2174d54356e1654583a65ff9cd38eccf797ee

We need to handle the following code

```cpp

template <typename> constexpr static void fromType();

void registerConverter() { fromType<int>(); }
template <typename> struct QMetaTypeId  {};
template <typename T> constexpr void fromType() { 
  (void)QMetaTypeId<T>{};
} // #1
template <> struct QMetaTypeId<int> {}; // #20428 
```

We can't instantiate `fromType` in `#1` because we later specialize an entity that it uses.
GCC seems to do instantiation at evaluation time https://godbolt.org/z/Wz5oMzdnP

**Comment by zygoloid** [comment] 2023-12-02 20:10
Normally I'd just say that the code needs to be fixed to give the explicit specialization before it's used or to make sure the instantiation is deferred, but the breakage is probably too much given that this seems to be in Qt core code.

I guess the question is, do we follow GCC's problematic model that evaluation can cause instantiation (which the language rules elsewhere explicitly try to avoid), or do we add a workaround just for Qt (detect that pattern somehow and don't eagerly Instantiate)?

**Comment by cor3ntin** [comment] 2024-04-08 07:29
@zygoloid The current direction taking by the reflection proposal is that arbitrary instantiations can emanate from constexpr evaluation. (Both explicitly as there is a proposed method to instantiate and define classes, and implicitly when querying the properties of not yet instantiated definitions).

In that way the model you consider problematic is going to be mandated by the standard

Is that something you gave any thought above? It might impact how we resolve this issue

**Comment by zygoloid** [comment] 2024-04-08 09:07
Thinking about the Qt example some more, if you simply reverse the order of the function definitions:
```c++
template <typename> constexpr static void fromType();

template <typename> struct QMetaTypeId  {};
template <typename T> constexpr void fromType() { 
  (void)QMetaTypeId<T>{};
}

void registerConverter() { fromType<int>(); }

template <> struct QMetaTypeId<int> {};
```
... then the example is clearly invalid (albeit no diagnostic required, because there are two points of instantiation for `fromType<int>` and only one of them results in the use of `QMetaTypeId<int>` prior to the explicit specialization), and clang correctly rejects. (GCC still doesn't, which is also permissible.) It seems pretty hard to justify why this example should be valid with the use and the template definition in the other order. The explicit specialization is simply declared too late.

**Comment by Fedr** [comment] 2025-04-07 07:11
A similar issue presented in https://stackoverflow.com/q/79558008/7325599

```c++
struct A {
    consteval A(int i) {
        chk(i);
    }
    constexpr void chk(auto) {}
};

A a{1};
```
GCC, EDG, MSVC all accept it. But Clang complains:
```
<source>:8:3: error: call to consteval function 'A::A' is not a constant expression
    8 | A a{1};
      |   ^
<source>:3:9: note: undefined function 'chk<int>' cannot be used in a constant expression
    3 |         chk(i);
      |         ^
<source>:8:3: note: in call to 'A(1)'
    8 | A a{1};
      |   ^~~~
<source>:5:20: note: declared here
    5 |     constexpr void chk(auto) {}
      |                    ^
```
Online demo: https://gcc.godbolt.org/z/xnGEM7oqe

**Comment by jyknight** [comment] 2025-11-26 16:39
FWIW, the fact that Clang cannot defer instantiation until use is a major issue for trying to migrate to C++23, because `unique_ptr` now has a constexpr destructor.

Thus, code like the following stops building when switching to -std=c++23 -- but only using Clang.

```
#include <memory>

struct X;

struct Y {
    Y() {}
    std::unique_ptr<X> member_;
};

struct X {  int a; };
```

(https://godbolt.org/z/Mv8ccsbqf)

At least in my codebase, there is lots of code similar to this, which makes it hard to contemplate using -std=c++23 until Clang is able to defer instantiation of constexpr functions.
