### ISSUE TITLE
aarch64 llvm 14 regression with vectors: assertion `TmpVec.size() > 1' failed

### ISSUE THREAD

**Issue by andrewrk** [llvm/llvm-project#56397] opened 2022-07-06 01:14 UTC
Does *not* affect LLVM 13.0.1.
Tested with LLVM 14.0.6. Have not yet confirmed whether it affects trunk.

Reduced LLVM IR:

```llvm
define internal fastcc i16 @test2.doTheTest.S.doTheTest() {
Block10:
  %0 = call fastcc i16 undef(<3 x i32> zeroinitializer, <3 x i32> zeroinitializer)
  ret i16 0
}
```

Reproduction:

```console
$ ~/local/llvm14-debug/bin/clang -c reduced.ll -target aarch64-linux-unknown
warning: overriding the module target triple with aarch64-unknown-linux-unknown [-Woverride-module]
clang: /home/andy/Downloads/llvm-project-14/llvm/lib/CodeGen/GlobalISel/MachineIRBuilder.cpp:656: llvm::MachineInstrBuilder llvm::MachineIRBuilder::buildUnmerge(llvm::ArrayRef<llvm::Register>, const llvm::SrcOp&): Assertion `TmpVec.size() > 1' failed.
```

Downstream issue: https://github.com/ziglang/zig/issues/12012

Apologies for not catching this during the RC phase.

**Comment by DavidSpickett** [comment] 2022-07-06 10:22
@petar-avramovic

**Comment by petar-avramovic** [comment] 2022-07-06 10:51
Will look into this, reproduces on O0 only
llc -global-isel -mtriple=aarch64-unknown-linux-unknown -verify-machineinstrs -O0
+ @aemerson for awareness

**Comment by petar-avramovic** [comment] 2022-07-06 12:51
Fix: https://reviews.llvm.org/D129194

**Comment by nikic** [comment] 2022-07-21 20:29
Looks like the fix landed in https://github.com/llvm/llvm-project/commit/2483f43d47ca30a9d9ff3f1714a45ca63d9b3410.

**Closed by nikic** 2022-07-21 20:29 UTC
Labels: bug, backend:AArch64, regression
