### ISSUE TITLE
"Did you mean" suggests deprecated namespaces for Range-v3 library

### ISSUE THREAD

**Issue by Aster89** [llvm/llvm-project#52726] opened 2021-12-15 14:59 UTC
This simple C++ file
```cpp
#include <range/v3/view/single.hpp>
auto xxx = ranges::single(3);
```
has a bug: `ranges::single` doesn't exist

Clang, when called with `-fsyntax-only -std=c++20` or `-fsyntax-only -std=c++17`, suggests changing the second line to
```cpp
auto xxx = ranges::view::single(3);
```
whereas it should suggest to change it to
```cpp
auto xxx = ranges::views::single(3);
```
(which it does when called with `-fsyntax-only -std=c++14`, strangely) because the `ranges::view` namespace is deprecated (just like `range::view`).

There's an issue with a similar title, #47272, but I see it's never been replied to.

@sam-mccall and @HighCommander4 in https://github.com/clangd/clangd/issues/951 suggested that I post this question/request here.

**Comment by sam-mccall** [comment] 2021-12-15 15:10
Minimized:

```
namespace good {}
namespace [[deprecated]] bad { using namespace good; }
namespace good { int x; }
int i = x;
```

Want: "Use of undeclared identifier 'x'; did you mean 'good::x'?"
Actual: "Use of undeclared identifier 'x'; did you mean 'bad::x'?"

Possible heuristics:
- prefer non-deprecated namespace
- prefer path that doesn't require a using directive

**Comment by sam-mccall** [comment] 2021-12-15 15:10
Oh, this is definitely a dupe of #47272

**Closed by sam-mccall** 2021-12-15 15:10 UTC
Labels: duplicate, clang:diagnostics
