### ISSUE TITLE
Incorrect formatting of template with less-than operator

### ISSUE THREAD

**Issue by 830f859b-50dd-44c4-8478-1ade9785ec56** [llvm/llvm-project#51297] opened 2021-09-24 12:49 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51955](https://llvm.org/bz51955) |
| Version | trunk |
| OS | Linux |
| CC | @carlosgalvezp |

## Extended Description 
I think this is a bug with the clang-format, where the "<" should have spaces around it, but it seems it is interpreted incorrectly.

Minimal example with default google style would be:

```
#include <cstdint>

class foo {
  template <typename T, std::size_t dimension,
            std::enable_if_t<dimension<4U, bool> = true> void foobar() {
    // do something
  }
}
```

I would have wanted this:
```
- std::enable_if_t<dimension<4U, bool> = true> void foobar() {
+ std::enable_if_t<dimension < 4U, bool> = true> void foobar() {
```

**Comment by mydeveloperday** [comment] 2021-12-13 11:04
Can you help me here to understand what you are expecting to see?

Currently I think it produces this with default Google Style

```
#include <cstdint>

class foo {
  template <typename T, std::size_t dimension,
            std::enable_if_t<dimension<4U, bool> = true> void foobar() {
    // do something
  }
}
```
Are you expecting to see this?

`            std::enable_if_t<dimension < 4U, bool> = true> void foobar() {`

If so can you explain why? and not the following?

`            std::enable_if_t < dimension < 4U, bool > = true > void foobar() {`

i.e. why wouldn't you have spaces around all <> if you are expecting it around the `dimension < 4U` to be honest I don't think google style IS to add spaces around template arguments is it?

**Comment by mydeveloperday** [comment] 2021-12-14 06:43
Oh I see now it’s dimension < 4

**Comment by carlosgalvezp** [comment] 2021-12-14 10:04
Sorry, I didn't get a notification for this reply. Yes, `dimension < 4` is not part of the template, it's simply the comparison operator. I don't expect spaces around template braces.

**Comment by mydeveloperday** [comment] 2021-12-14 12:55
It sees the < as a template opener not a less than. (which is exactly what I did by eye)

```
AnnotatedTokens(L=1):
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=0 Name=template L=8 PPK=2 FakeLParens= FakeRParens=0 II=0x203c8937658 Text='template'
 M=0 C=0 T=TemplateOpener S=1 F=0 B=0 BK=0 P=30 Name=less L=10 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='<'
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=360 Name=typename L=18 PPK=2 FakeLParens=1/ FakeRParens=0 II=0x203c8937750 Text='typename'
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=263 Name=identifier L=20 PPK=2 FakeLParens= FakeRParens=0 II=0x203c897a718 Text='T'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=261 Name=comma L=21 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=','
 M=0 C=1 T=Unknown S=1 F=0 B=0 BK=0 P=261 Name=identifier L=25 PPK=2 FakeLParens= FakeRParens=0 II=0x203c897a748 Text='std'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=263 Name=coloncolon L=27 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='::'
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=760 Name=identifier L=33 PPK=2 FakeLParens= FakeRParens=0 II=0x203c897a778 Text='size_t'
 M=0 C=1 T=StartOfName S=1 F=0 B=0 BK=0 P=460 Name=identifier L=43 PPK=2 FakeLParens= FakeRParens=0 II=0x203c897a7b0 Text='dimension'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=261 Name=comma L=44 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=','
 M=0 C=1 T=Unknown S=1 F=0 B=0 BK=0 P=261 Name=identifier L=48 PPK=2 FakeLParens= FakeRParens=0 II=0x203c897a748 Text='std'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=263 Name=coloncolon L=50 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='::'
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=760 Name=identifier L=61 PPK=2 FakeLParens= FakeRParens=0 II=0x203c897a7e8 Text='enable_if_t'
 M=0 C=0 T=TemplateOpener S=0 F=0 B=0 BK=0 P=270 Name=less L=62 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='<'
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=600 Name=identifier L=71 PPK=2 FakeLParens=2/ FakeRParens=0 II=0x203c897a7b0 Text='dimension'
 M=0 C=0 T=TemplateOpener S=0 F=0 B=0 BK=0 P=510 Name=less L=72 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='<'
                     ^^^^^^^^^^^
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=840 Name=numeric_constant L=74 PPK=2 FakeLParens=1/ FakeRParens=0 II=0x0 Text='4U'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=741 Name=comma L=75 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=','
 M=0 C=1 T=Unknown S=1 F=0 B=0 BK=0 P=741 Name=bool L=80 PPK=2 FakeLParens= FakeRParens=1 II=0x203c8937278 Text='bool'
 M=0 C=0 T=TemplateCloser S=0 F=0 B=0 BK=0 P=750 Name=greater L=81 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='>'
 M=0 C=0 T=BinaryOperator S=1 F=0 B=0 BK=0 P=510 Name=equal L=83 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='='
 M=0 C=1 T=Unknown S=1 F=0 B=0 BK=0 P=502 Name=true L=88 PPK=2 FakeLParens= FakeRParens=1 II=0x203c89376e8 Text='true'
 M=0 C=0 T=TemplateCloser S=0 F=0 B=0 BK=0 P=510 Name=greater L=89 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='>'
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=270 Name=void L=94 PPK=2 FakeLParens= FakeRParens=0 II=0x203c8936f18 Text='void'
 M=0 C=1 T=StartOfName S=1 F=0 B=0 BK=0 P=460 Name=identifier L=101 PPK=2 FakeLParens= FakeRParens=0 II=0x203c897a818 Text='foobar'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=263 Name=l_paren L=102 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='('
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=299 Name=r_paren L=103 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=')'

```

Taken at first glance this might be hard to do

when I see this

`dimension<4U, bool>`

To clang-format this isn't much different from

T<4U,bool>

The only thing I can think of is if we can see the whole template holistically and try and match up the template openers and closers because at present we don't have a matching number then somehow mark the missing one as a BinaryOperator.

Its wouldn't be easy from what I can tell.

**Comment by rymiel** [comment] 2023-04-17 14:29
Duplicate of https://github.com/llvm/llvm-project/issues/31556

**Closed by rymiel** 2023-04-17 14:29 UTC
Labels: bug, duplicate, clang-format, bugzilla
