### ISSUE TITLE
clang crashes with Assertion `RHS.U.VAL != 0 && "Divide by zero?"' failed.

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#58727] opened 2022-11-01 13:13 UTC
LLVM commit:
Reproduce with:
```shell
clang bbi-75382.c
```
Result:
```console
clang-16: ../lib/Support/APInt.cpp:1576: llvm::APInt llvm::APInt::udiv(const llvm::APInt &) const: Assertion `RHS.U.VAL != 0 && "Divide by zero?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /repo/uabelho/main-github/llvm/build-all/bin/clang-16 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name bbi-75382.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/repo/uabelho/llvm-dev3/llvm -resource-dir /repo/uabelho/main-github/llvm/build-all/lib/clang/16.0.0 -internal-isystem /repo/uabelho/main-github/llvm/build-all/lib/clang/16.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../x86_64-redhat-linux/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/repo/uabelho/llvm-dev3/llvm -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/bbi-75382-205345.o -x c bbi-75382.c
1.	bbi-75382.c:3:38: current parser token ';'
2.	bbi-75382.c:2:1: parsing function body 'foo'
3.	bbi-75382.c:2:1: in compound statement ('{}')
 #0 0x0000000002fc9873 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x2fc9873)
 #1 0x0000000002fc758e llvm::sys::RunSignalHandlers() (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x2fc758e)
 #2 0x0000000002fc9bf6 SignalHandler(int) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x2fc9bf6)
 #3 0x00007f95da7e1630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x00007f95d7f28387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f95d7f29a78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007f95d7f211a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007f95d7f21252 (/lib64/libc.so.6+0x2f252)
 #8 0x0000000002f0f414 llvm::APInt::udiv(llvm::APInt const&) const (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x2f0f414)
 #9 0x0000000002f119e6 llvm::APInt::sdiv(llvm::APInt const&) const (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x2f119e6)
#10 0x00000000057cf673 (anonymous namespace)::ComplexExprEvaluator::VisitBinaryOperator(clang::BinaryOperator const*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x57cf673)
#11 0x00000000057cc0eb EvaluateComplex(clang::Expr const*, (anonymous namespace)::ComplexValue&, (anonymous namespace)::EvalInfo&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x57cc0eb)
#12 0x00000000057961bd Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x57961bd)
#13 0x0000000005792fe8 EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x5792fe8)
#14 0x000000000579316f clang::Expr::EvaluateForOverflow(clang::ASTContext const&) const (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x579316f)
#15 0x0000000004b722cc clang::Sema::CheckForIntOverflow(clang::Expr*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4b722cc)
#16 0x0000000004b727be clang::Sema::CheckCompletedExpr(clang::Expr*, clang::SourceLocation, bool) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4b727be)
#17 0x0000000004eccc43 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool, bool) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4eccc43)
#18 0x000000000511c486 clang::Sema::BuildReturnStmt(clang::SourceLocation, clang::Expr*, bool) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x511c486)
#19 0x000000000511b9e2 clang::Sema::ActOnReturnStmt(clang::SourceLocation, clang::Expr*, clang::Scope*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x511b9e2)
#20 0x0000000004aa9e98 clang::Parser::ParseReturnStatement() (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4aa9e98)
#21 0x0000000004aa29e9 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4aa29e9)
#22 0x0000000004aa1b35 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4aa1b35)
#23 0x0000000004aac491 clang::Parser::ParseCompoundStatementBody(bool) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4aac491)
#24 0x0000000004aad935 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x4aad935)
#25 0x00000000049d6794 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49d6794)
#26 0x00000000049f3097 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49f3097)
#27 0x00000000049d53ed clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49d53ed)
#28 0x00000000049d4d00 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49d4d00)
#29 0x00000000049d3e4f clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49d3e4f)
#30 0x00000000049d1316 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49d1316)
#31 0x00000000049d09ff clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49d09ff)
#32 0x00000000049cb808 clang::ParseAST(clang::Sema&, bool, bool) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x49cb808)
#33 0x0000000003aa55f6 clang::FrontendAction::Execute() (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x3aa55f6)
#34 0x0000000003a17764 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x3a17764)
#35 0x0000000003b66632 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x3b66632)
#36 0x00000000009d93b6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x9d93b6)
#37 0x00000000009d6110 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x9d6110)
#38 0x00000000009d5d85 clang_main(int, char**) (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x9d5d85)
#39 0x00007f95d7f14555 __libc_start_main (/lib64/libc.so.6+0x22555)
#40 0x00000000009d233b _start (/repo/uabelho/main-github/llvm/build-all/bin/clang-16+0x9d233b)
clang-16: error: unable to execute command: Aborted (core dumped)
clang-16: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 16.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /repo/uabelho/llvm-dev3/llvm/../../main-github/llvm/build-all/bin
clang-16: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-16: note: diagnostic msg: /tmp/bbi-75382-973200.c
clang-16: note: diagnostic msg: /tmp/bbi-75382-973200.sh
clang-16: note: diagnostic msg: 

********************
```
This seems to be very old.
[bbi-75382.c.gz](https://github.com/llvm/llvm-project/files/9910107/bbi-75382.c.gz)

**Comment by shafik** [comment] 2022-11-01 14:39
Confirmed, see godbolt: https://godbolt.org/z/vbrc1r6h8

code as follows:

```cpp
int foo() {
  return 1 / (_Complex int)1073741824;
}
```

Assertion:

```console
clang++: /root/llvm-project/llvm/lib/Support/APInt.cpp:1576: llvm::APInt llvm::APInt::udiv(const llvm::APInt&) const: Assertion `RHS.U.VAL != 0 && "Divide by zero?"' failed.
```

Whole backtrace:

```console
<source>:2:12: error: implicit conversion from '_Complex int' to 'int' is not permitted in C++
  return 1 / (_Complex int)1073741824;
  ~~~~~~ ~~^~~~~~~~~~~~~~~~~~~~~~~~~~
clang++: /root/llvm-project/llvm/lib/Support/APInt.cpp:1576: llvm::APInt llvm::APInt::udiv(const llvm::APInt&) const: Assertion `RHS.U.VAL != 0 && "Divide by zero?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:2:38: current parser token ';'
2.	<source>:1:11: parsing function body 'foo'
3.	<source>:1:11: in compound statement ('{}')
 #0 0x0000556555202f24 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000556555200cbc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3fa9cbc)
 #2 0x000055655513c008 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007efec4159420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007efec3c2600b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007efec3c05859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007efec3c05729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007efec3c16fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000556555117279 llvm::APInt::udiv(llvm::APInt const&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ec0279)
 #9 0x000055655511767e llvm::APInt::sdiv(llvm::APInt const&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ec067e)
#10 0x00005565587e1d92 llvm::APSInt::operator/(llvm::APSInt const&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x758ad92)
#11 0x000055655884210a (anonymous namespace)::ComplexExprEvaluator::VisitBinaryOperator(clang::BinaryOperator const*) (.part.0) ExprConstant.cpp:0:0
#12 0x0000556558844665 (anonymous namespace)::ComplexExprEvaluator::VisitBinaryOperator(clang::BinaryOperator const*) ExprConstant.cpp:0:0
#13 0x00005565588404fd clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::ComplexExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
#14 0x0000556558841057 EvaluateComplex(clang::Expr const*, (anonymous namespace)::ComplexValue&, (anonymous namespace)::EvalInfo&) ExprConstant.cpp:0:0
#15 0x000055655880248a Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) ExprConstant.cpp:0:0
#16 0x000055655880d649 EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) ExprConstant.cpp:0:0
#17 0x000055655880f655 clang::Expr::EvaluateForOverflow(clang::ASTContext const&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x75b8655)
#18 0x000055655798156d clang::Sema::CheckForIntOverflow(clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x672a56d)
#19 0x00005565579dbbd5 clang::Sema::CheckCompletedExpr(clang::Expr*, clang::SourceLocation, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6784bd5)
#20 0x0000556557de8432 clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6b91432)
#21 0x0000556558096411 clang::Sema::BuildReturnStmt(clang::SourceLocation, clang::Expr*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e3f411)
#22 0x0000556558097eaf clang::Sema::ActOnReturnStmt(clang::SourceLocation, clang::Expr*, clang::Scope*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6e40eaf)
#23 0x00005565578a3b8f clang::Parser::ParseReturnStatement() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x664cb8f)
#24 0x00005565578a6dbe clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x664fdbe)
#25 0x00005565578a8415 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6651415)
#26 0x00005565578a940a clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x665240a)
#27 0x00005565578aad1a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6653d1a)
#28 0x00005565577dafe1 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6583fe1)
#29 0x0000556557807c60 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65b0c60)
#30 0x00005565577cfbd2 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6578bd2)
#31 0x00005565577d0430 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#32 0x00005565577d5beb clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x657ebeb)
#33 0x00005565577d6a7a clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x657fa7a)
#34 0x00005565577d6eb4 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x657feb4)
#35 0x00005565577cae1a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6573e1a)
#36 0x0000556556530c78 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x52d9c78)
#37 0x0000556555dc1d69 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b6ad69)
#38 0x0000556555d488ce clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4af18ce)
#39 0x0000556555ea78d3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4c508d3)
#40 0x00005565526bc414 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1465414)
#41 0x00005565526b5528 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#42 0x0000556555bb5839 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#43 0x000055655513c7aa llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ee57aa)
#44 0x0000556555bb608f clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#45 0x0000556555b7f559 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4928559)
#46 0x0000556555b7ffdd clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4928fdd)
#47 0x0000556555b895fc clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49325fc)
#48 0x00005565526ba853 clang_main(int, char**) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1463853)
#49 0x00007efec3c07083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#50 0x00005565526b512e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x145e12e)
clang-16: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

**Comment by RKSimon** [comment] 2022-11-01 14:52
Duplicate of #55390 ?

**Comment by AaronBallman** [comment] 2022-11-01 19:45
Yeah, this appears to be a duplicate of #55390, closing as such.

**Closed by AaronBallman** 2022-11-01 19:45 UTC
Labels: duplicate, clang:frontend, confirmed, crash
