### ISSUE TITLE
[clang] `static constexpr` variable initialized inside `consteval` function is loosing its value

### ISSUE THREAD

**Issue by hanickadot** [llvm/llvm-project#92690] opened 2024-05-19 12:08 UTC
Any variable initialized as `static constexpr` variable inside `consteval` is not keeping its value in runtime:

```c++
consteval const int & get_value() {
    constexpr static int value = 42;
    return value;
}

int foo() {
  return get_value();
}
```

generates assembly (with clang 18.1):
```asm
foo():                                # @foo()
        push    rbp
        mov     rbp, rsp
        mov     eax, dword ptr [rip + get_value()::value]
        pop     rbp
        ret
get_value()::value:
        .long   0    
```

confirmed with clang 16+ to current `main` branch (`597ac471cc7da97ccf957362a7e9f7a52d6910ee` at compiler explorer)

link to example: https://compiler-explorer.com/z/fj6zco3d5

same thing happens to strings and arrays ... their storage is all zeros

**Comment by hanickadot** [comment] 2024-05-19 21:09
A little bit better example: https://compiler-explorer.com/z/vTE8WYMGz

**Comment by shafik** [comment] 2024-05-19 21:21
I believe this is a duplicate of: https://github.com/llvm/llvm-project/issues/82994

CC @cor3ntin @Fznamznon

**Comment by hanickadot** [comment] 2024-05-19 21:24
Yes, you are correct, this seem as the same problem.

**Closed** 2024-06-05 03:47 UTC
Labels: duplicate, clang:codegen, confirmed, consteval, constexpr
