### ISSUE TITLE
[clang-format] RemoveParentheses RPS_MultipleParentheses removes parentheses for parameter pack expansion

### ISSUE THREAD

**Issue by vaijns** [llvm/llvm-project#118142] opened 2024-11-29 23:20 UTC
When having `RemoveParentheses` on `RPS_MultipleParentheses` it removes parentheses around parameter pack expansions e.g. in a `static_assert()`:
```c++
template<bool... Values>
bool test(){
	static_assert((Values && ...));
	return true;
}

int main(){
	test<true, true, true, true>();
}
```

replaces the static_assert with `static_assert(Values && ...);` which doesn't compile because you have to add the extra parentheses when expanding the parameter pack.

I know that it says setting `RemoveParentheses` to anything else than `Leave` can lead to incorrect code but still though I'd report it, maybe it's possible to detect the parameter pack expansion and leave the parentheses in this case.

**Comment by owenca** [comment] 2024-11-30 04:38
Duplicate of #90966.

**Closed by owenca** 2024-11-30 04:38 UTC
Labels: duplicate, clang-format
