### ISSUE TITLE
[HLSL] Support semantic on struct field.

### ISSUE THREAD

**Issue by python3kgae** [llvm/llvm-project#57889] opened 2022-09-21 22:36 UTC
Support case like
struct Input {
 int GI : SV_GroupIndex;
 int ID : SV_DispatchThreadID;
};

**Comment by bogner** [comment] 2023-08-24 16:46
Duplicate of https://github.com/llvm/llvm-project/issues/57875

**Closed** 2023-08-24 16:47 UTC
Labels: duplicate, HLSL

**Comment by bob80905** [comment] 2024-06-26 19:55
This may not necessarily be a duplicate. One issue is ensuring that input structs have a semantic on every member.
This issue may be addressing the fact that some semantics aren't parsed on fields at all. A subtle difference.
