### ISSUE TITLE
[Format] Removes space between `&&` and `noexcept`

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#59729] opened 2022-12-28 04:14 UTC
https://godbolt.org/z/a7henzE5c

```cpp
struct SomeMarker {
    void f() &&noexcept {}
    operator int() &&noexcept { return 0; }
};
```

Should be:
```cpp
struct SomeMarker {
    void f() && noexcept {}
    operator int() && noexcept { return 0; }
};
```

**Comment by rymiel** [comment] 2022-12-28 09:03
Surprisingly it appears this behaviour is tested for:

https://github.com/llvm/llvm-project/blob/9816c1912d56668736a2bd95ce18b7fb41653b92/clang/unittests/Format/FormatTest.cpp#L10580-L10582

Adding the style option `PointerAlignment: Left` performs the format you want, as verified by tests:

https://github.com/llvm/llvm-project/blob/9816c1912d56668736a2bd95ce18b7fb41653b92/clang/unittests/Format/FormatTest.cpp#L10619-L10620

See https://github.com/llvm/llvm-project/issues/44542
See https://github.com/llvm/llvm-project/commit/ae1b7859cbd61d2284d9690bc53482d0b6a46f63
See https://github.com/llvm/llvm-project/commit/a218706cba90248be0c60bd6a8f10dbcf0270955

Note that this issue is technically a duplicate of https://github.com/llvm/llvm-project/issues/44542, but I still think this behaviour is surprising, and should at least be decoupled from `PointerAlignment`, so I'd like input from other maintainers (@HazardyKnusperkeks, @mydeveloperday, @owenca)

**Comment by HazardyKnusperkeks** [comment] 2022-12-29 11:37
It is a ref specifier, but a different kind than on a variable or argument. I think it should be annotated differently and I can not believe anyone would want no space between the specifier and anything besides the semicolon.

**Comment by rymiel** [comment] 2022-12-29 21:53
I'm taking that as encouragement to change this behaviour, so here's a patch which does that: https://reviews.llvm.org/D140767

**Comment by danakj** [comment] 2022-12-29 23:58
Thank you 🙏

**Closed** 2023-01-06 03:08 UTC
Labels: clang-format, awaiting-review
