### ISSUE TITLE
fatal error: error in backend: SSE register return with SSE disabled

### ISSUE THREAD

**Issue by ixlang** [llvm/llvm-project#108510] opened 2024-09-13 07:43 UTC
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: D:\\Programs\\msys64\\clang64\\bin\\clang++.exe -O0 -w -g -mno-sse -I ./xinclude/libffi/include -I ../../caLibrary/castl/include -I ../../thrid_part/openssl/output/MINGW64_NT-10.0-22631_x86_64/include -I ./xcross -I ../xrvm/xrvm -I ./xcross/clazz -DNO_LIBICONV -D_XRVM -D__XRE__ -DUNICODE -DDEBUG_VM -D_UNICODE -DWIN32 -DFFI_BUILDING -D_WIN32 -D_VM_SHELL -DDONT_OVERRIDE_NEWDELETE -DNOT_DEF_REPLACEMENTS -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -o objs/xcross/clazz/X_StreamClass.obj -c xcross/clazz/X_StreamClass.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'xcross/clazz/X_StreamClass.cpp'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@_ZN13X_StreamClass29xproc__Stream__readFloat__0__EP7ContextR10MetaObjectR8XVMSTACKS3_'
Exception Code: 0xE0000046
 #0 0x00007ffb2a31fabc (C:\Windows\System32\KERNELBASE.dll+0x5fabc)
 #1 0x00007ffa50239a9a llvm::CrashRecoveryContext::HandleExit(int) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0xde9a9a)
 #2 0x00007ffa502bd549 llvm::sys::Process::Exit(int, bool) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0xe6d549)
 #3 0x00007ff6142fc789 void llvm::SmallVectorImpl<char const*>::append<std::__1::move_iterator<char const**>, void>(std::__1::move_iterator<char const**>, std::__1::move_iterator<char const**>) (D:\Programs\msys64\clang64\bin\clang++.exe+0xc789)
 #4 0x00007ffa502458e2 llvm::report_fatal_error(llvm::Twine const&, bool) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0xdf58e2)
 #5 0x00007ffa4fd32e74 llvm::report_fatal_error(char const*, bool) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x8e2e74)
 #6 0x00007ffa529ee205 llvm::X86::createFastISel(llvm::FunctionLoweringInfo&, llvm::TargetLibraryInfo const*) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x359e205)
 #7 0x00007ffa5076fd3f llvm::FastISel::lowerCallTo(llvm::FastISel::CallLoweringInfo&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x131fd3f)
 #8 0x00007ffa50771af8 llvm::FastISel::lowerCall(llvm::CallInst const*) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x1321af8)
 #9 0x00007ffa50773a0f llvm::FastISel::selectInstruction(llvm::Instruction const*) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x1323a0f)
#10 0x00007ffa4f95bf7f llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x50bf7f)
#11 0x00007ffa4fbae800 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x75e800)
#12 0x00007ffa4fbae3cd llvm::AsmToken& llvm::SmallVectorImpl<llvm::AsmToken>::emplace_back<llvm::AsmToken::TokenKind, llvm::StringRef>(llvm::AsmToken::TokenKind&&, llvm::StringRef&&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x75e3cd)
#13 0x00007ffa4f790f3b llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x340f3b)
#14 0x00007ffa4f5b34e0 llvm::FPPassManager::runOnFunction(llvm::Function&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x1634e0)
#15 0x00007ffa4f5b2ed1 llvm::FPPassManager::runOnModule(llvm::Module&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x162ed1)
#16 0x00007ffa4f5b2823 llvm::legacy::PassManagerImpl::run(llvm::Module&) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0x162823)
#17 0x00007ffa615ee857 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x71e857)
#18 0x00007ffa615ecc9d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x71cc9d)
#19 0x00007ffa6167cfbb clang::ParseAST(clang::Sema&, bool, bool) (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x7acfbb)
#20 0x00007ffa612085ae clang::FrontendAction::Execute() (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x3385ae)
#21 0x00007ffa61207f26 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x337f26)
#22 0x00007ffa61207940 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x337940)
#23 0x00007ff6142f5688 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (D:\Programs\msys64\clang64\bin\clang++.exe+0x5688)
#24 0x00007ff6142f4f46 llvm::raw_ostream::operator<<(llvm::StringRef) (D:\Programs\msys64\clang64\bin\clang++.exe+0x4f46)
#25 0x00007ffa62b7011d void std::__1::vector<std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>::__assign_with_size[abi:nn180100]<std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>*, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>*>(std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>*, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>*, long long) (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x1ca011d)
#26 0x00007ffa50239a68 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (D:\Programs\msys64\clang64\bin\libLLVM-18.dll+0xde9a68)
#27 0x00007ffa617a4357 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x8d4357)
#28 0x00007ffa61776e7a clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x8a6e7a)
#29 0x00007ffa61776b40 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&, bool) const (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x8a6b40)
#30 0x00007ffa617766d5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&) (D:\Programs\msys64\clang64\bin\libclang-cpp.dll+0x8a66d5)
#31 0x00007ff6142f1d37 clang_main(int, char**, llvm::ToolContext const&) (D:\Programs\msys64\clang64\bin\clang++.exe+0x1d37)
#32 0x00007ff6142f1075 main (D:\Programs\msys64\clang64\bin\clang++.exe+0x1075)
#33 0x00007ff6142fbec1 WinMainCRTStartup (D:\Programs\msys64\clang64\bin\clang++.exe+0xbec1)
#34 0x00007ff6142fbf16 mainCRTStartup (D:\Programs\msys64\clang64\bin\clang++.exe+0xbf16)
#35 0x00007ffb2b46257d (C:\Windows\System32\KERNEL32.DLL+0x1257d)
#36 0x00007ffb2cb0af28 (C:\Windows\SYSTEM32\ntdll.dll+0x5af28)
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 18.1.4
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:/Programs/msys64/clang64/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: C:/Users/Cadaqs/AppData/Local/Temp/X_StreamClass-5d8b1a.cpp
clang++: note: diagnostic msg: C:/Users/Cadaqs/AppData/Local/Temp/X_StreamClass-5d8b1a.sh
clang++: note: diagnostic msg: 

********************

**Comment by DimitryAndric** [comment] 2024-09-13 08:09
Yet another duplicate of #29774. Try removing `-mno-sse`, as SSE is basically required on x86_64.

**Closed by DimitryAndric** 2024-09-13 08:09 UTC
Labels: duplicate, backend:X86
