### ISSUE TITLE
AMDGPU backend: range is set incorrectly for mbcnt instructions

### ISSUE THREAD

**Issue by Venemo** [llvm/llvm-project#55598] opened 2022-05-19 21:32 UTC
According to the GCN / RDNA ISA documentation, the `v_mbcnt_lo` and `v_mbcnt_hi` instructions can have a source which is added to the result. The LLVM AMDGPU backend disregards this and always sets the range of these instructions as if their upper bound was the wave size, however this is incorrect when the addition is used because it can then exceed this range.

The problematic line of code is this: https://github.com/llvm/llvm-project/blob/25af3af/llvm/lib/Target/AMDGPU/AMDGPUISelLowering.cpp#L4601

This causes false assumptions when the instruction is used with arbitrary addition, resulting in buggy code being compiled.

**Comment by jayfoad** [comment] 2022-05-20 07:29
Caused by https://reviews.llvm.org/D39951

**Comment by dstutt** [comment] 2022-08-09 16:49
I took a look at this - see https://reviews.llvm.org/D131478

**Comment by dstutt** [comment] 2022-08-11 12:26
Fixed in https://reviews.llvm.org/D131478

**Closed by dstutt** 2022-08-11 12:26 UTC
Labels: backend:AMDGPU

**Comment by Venemo** [comment] 2022-08-11 17:37
Can you say which version of LLVM will have this fix?

**Comment by dstutt** [comment] 2022-08-23 09:33
(Sorry for delayed response - been on vacation)

I'm trying to get a backport to the llvm 15 release.

**Comment by dstutt** [comment] 2022-08-23 09:33
If not for llvm 15, then it'll be in the next release.

**Comment by Venemo** [comment] 2022-08-23 11:16
Thanks. Please let me know when you know for sure. (As a workaround we emit an extra add instruction now, but I'd like to remove that workaround for the first LLVM version which doesn't need it.)

**Comment by dstutt** [comment] 2022-09-07 08:34
The change should be in 15.0.1
See https://github.com/llvm/llvm-project-release-prs/pull/124 and https://github.com/llvm/llvm-project/issues/57295

**Comment by Venemo** [comment] 2022-09-07 10:13
Ouch. Sad to see it didn't make it into 15.0.0 :(

**Comment by Venemo** [comment] 2022-09-07 10:13
Thanks for the fix and thanks for letting me know it will be usable in 15.0.1 at least.
