### ISSUE TITLE
arm-windows-msvc compilation error

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#96470] opened 2024-06-24 09:41 UTC
```
clang++: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
fatal error: error in backend: Cannot select: 0x118400be110: ch = cleanupret 0x118400be260
In function: main
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
```
Looks like lowering for EH handling is doing wrong

**Comment by EugeneZelenko** [comment] 2024-06-24 14:08
@trcrsired: Could you please provide reproducer, ideally on https://godbolt.org?

**Comment by efriedma-quic** [comment] 2024-06-24 17:58
Duplicate of #37689

**Closed by efriedma-quic** 2024-06-24 17:58 UTC
Labels: incomplete, crash, llvm:SelectionDAG
