### ISSUE TITLE
[AMDGPU][MC][GFX11] Assembly of v_fmac_.*_e64_dpp is broken

### ISSUE THREAD

**Issue by Sisyph** [llvm/llvm-project#57585] opened 2022-09-06 18:14 UTC
The e32 version works. The combination of operand list, asmString, and or conversion function cvtVOP3DPP are not right for this instruction. 
It has  string Constraints = "$src2 = $vdst"; and  string DisableEncoding = "$src2"; which is different than other vop3 dpp.

**Comment by dpreobra** [comment] 2022-10-03 11:20
https://reviews.llvm.org/D134961

**Comment by dpreobra** [comment] 2022-10-10 14:27
Fixed by 8f8e4e3b38c4fdb2bc5336bf324af14c2ab61509

**Comment by dpreobra** [comment] 2022-11-10 18:39
It looks like the fix is incomplete - there is a special case not handled by the patch.

An example of failed test:

    v_fmac_f16_e64_dpp v5, v1, v2       // dpp modifiers are optional!

Expected output:

    0x05,0x00,0x36,0xd5,0xe9,0x04,0x02,0x00,0x01,0x00,0x00,0x00

Actual result:

    An exception

A fix is pending.

**Comment by dpreobra** [comment] 2022-11-10 19:05
Hopefully https://reviews.llvm.org/D137549 will handle this case. The problem here is that an optional `clamp` modifier is followed by a mandatory `DPP8`/`DPPCtrl` modifier. As a result, the instruction w/o modifiers is accepted by the parser though it should not.

**Comment by dpreobra** [comment] 2022-11-11 15:25
Not reproducible after ef848f27d74dcff6455f05890566333bddbdb77e. Kudos to @kosarev.

**Closed by dpreobra** 2022-11-11 15:25 UTC
Labels: backend:AMDGPU, mc
