### ISSUE TITLE
Clang crash on invalid code: "no parens or braces but have direct init with arguments?"

### ISSUE THREAD

**Issue by kparzysz-quic** [llvm/llvm-project#59207] opened 2022-11-25 23:52 UTC
Testcase:
```cpp
class a {
  class b {
    b(a) {
      struct c {
        a j
      };
      auto e = [](a f, a, auto) { b d(f } auto g = [](a) -> c {
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
```

```console
$ clang++ -c -std=c++17 interesting.ii
interesting.ii:9:1: error: expected '}'
^
interesting.ii:2:11: note: to match this '{'
  class b {
          ^
interesting.ii:8:53: error: expected ';' after class
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
                                                    ^
                                                    ;
interesting.ii:9:1: error: expected '}'
^
interesting.ii:1:9: note: to match this '{'
class a {
        ^
interesting.ii:5:12: error: expected ';' at end of declaration list
        a j
           ^
           ;
interesting.ii:7:41: error: expected ')'
      auto e = [](a f, a, auto) { b d(f } auto g = [](a) -> c {
                                        ^
interesting.ii:7:38: note: to match this '('
      auto e = [](a f, a, auto) { b d(f } auto g = [](a) -> c {
                                     ^
interesting.ii:7:40: error: expected ';' at end of declaration
      auto e = [](a f, a, auto) { b d(f } auto g = [](a) -> c {
                                       ^
                                       ;
interesting.ii:7:42: error: expected ';' at end of declaration
      auto e = [](a f, a, auto) { b d(f } auto g = [](a) -> c {
                                         ^
                                         ;
interesting.ii:8:8: error: expected ';' at end of declaration
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
       ^
       ;
interesting.ii:8:13: error: expected ';' at end of declaration
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
            ^
            ;
interesting.ii:8:25: error: use of undeclared identifier 'V00'; did you mean 'V0'?
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
                        ^~~
                        V0
interesting.ii:8:11: note: 'V0' declared here
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
          ^
interesting.ii:8:29: error: expected ';' at end of declaration
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
                            ^
                            ;
interesting.ii:8:46: error: member reference type 'c' is not a pointer; did you mean to use '.'?
      } a V0 auto h = g(V00) int i = e(a(), h->j, i)
                                            ~^~
                                             .
clang++: /w/src/llvm.org/clang/lib/Sema/TreeTransform.h:4052: clang::ExprResult clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformInitializer(clang::Expr *, bool) [Derived = (anonymous namespace)::TemplateInstantiator]: Assertion `NewArgs.empty() && "no parens or braces but have direct init with arguments?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /w/c/org/bin/clang++ -c -std=c++17 interesting.ii
1.      interesting.ii:8:52: current parser token ')'
2.      interesting.ii:1:1: parsing struct/union/class body 'a'
3.      interesting.ii:3:10: parsing function body 'a::b::b'
4.      interesting.ii:3:10: in compound statement ('{}')
5.      interesting.ii:7:16: instantiating function definition 'a::b::b(a)::(anonymous class)::operator()<int>'
 #0 0x0000000002e16d53 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/w/c/org/bin/clang+++0x2e16d53)
 #1 0x0000000002e14c1e llvm::sys::RunSignalHandlers() (/w/c/org/bin/clang+++0x2e14c1e)
 #2 0x0000000002e1618d llvm::sys::CleanupOnSignal(unsigned long) (/w/c/org/bin/clang+++0x2e1618d)
 #3 0x0000000002d885be (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x0000000002d88810 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x00007fab13320420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #6 0x00007fab12e5e00b raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #7 0x00007fab12e3d859 abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81:7
 #8 0x00007fab12e3d729 get_sysdep_segment_value /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:509:8
 #9 0x00007fab12e3d729 _nl_load_domain /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:970:34
#10 0x00007fab12e4efd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
#11 0x000000000579d428 (/w/c/org/bin/clang+++0x579d428)
#12 0x000000000579a02e clang::Sema::SubstInitializer(clang::Expr*, clang::MultiLevelTemplateArgumentList const&, bool) (/w/c/org/bin/clang+++0x579a02e)
#13 0x00000000057ea087 clang::Sema::InstantiateVariableInitializer(clang::VarDecl*, clang::VarDecl*, clang::MultiLevelTemplateArgumentList const&) (/w/c/org/bin/clang+++0x57ea087)
#14 0x00000000057dcd1e clang::Sema::BuildVariableInstantiation(clang::VarDecl*, clang::VarDecl*, clang::MultiLevelTemplateArgumentList const&, llvm::SmallVector<clang::Sema::LateInstantiatedAttribute, 16u>*, clang::DeclContext*, clang::LocalInstantiationScope*, bool, clang::VarTemplateSpecializationDecl*) (/w/c/org/bin/clang+++0x57dcd1e)
#15 0x00000000057dc3e4 clang::TemplateDeclInstantiator::VisitVarDecl(clang::VarDecl*, bool, llvm::ArrayRef<clang::BindingDecl*>*) (/w/c/org/bin/clang+++0x57dc3e4)
#16 0x000000000581eb54 void llvm::function_ref<void ()>::callback_fn<clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&)::$_0>(long) SemaTemplateInstantiateDecl.cpp:0:0
#17 0x0000000004ff269b clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/w/c/org/bin/clang+++0x4ff269b)
#18 0x00000000057ebb89 clang::Sema::SubstDecl(clang::Decl*, clang::DeclContext*, clang::MultiLevelTemplateArgumentList const&) (/w/c/org/bin/clang+++0x57ebb89)
#19 0x00000000057c5ee7 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDeclStmt(clang::DeclStmt*) SemaTemplateInstantiate.cpp:0:0
#20 0x00000000057ba6e4 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#21 0x000000000579bbd3 clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/w/c/org/bin/clang+++0x579bbd3)
#22 0x00000000057ed6d0 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/w/c/org/bin/clang+++0x57ed6d0)
#23 0x0000000004ff269b clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/w/c/org/bin/clang+++0x4ff269b)
#24 0x000000000572a2f6 clang::Sema::DeduceReturnType(clang::FunctionDecl*, clang::SourceLocation, bool) (/w/c/org/bin/clang+++0x572a2f6)
#25 0x00000000052afb9a clang::Sema::DiagnoseUseOfDecl(clang::NamedDecl*, llvm::ArrayRef<clang::SourceLocation>, clang::ObjCInterfaceDecl const*, bool, bool, clang::ObjCInterfaceDecl*, bool) (/w/c/org/bin/clang+++0x52afb9a)
#26 0x00000000055db4c0 CreateFunctionRefExpr(clang::Sema&, clang::FunctionDecl*, clang::NamedDecl*, clang::Expr const*, bool, clang::SourceLocation, clang::DeclarationNameLoc const&) SemaOverload.cpp:0:0
#27 0x00000000055e20b4 clang::Sema::BuildCallToObjectOfClassType(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation) (/w/c/org/bin/clang+++0x55e20b4)
#28 0x00000000052b583c clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/w/c/org/bin/clang+++0x52b583c)
#29 0x00000000052cf16a clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/w/c/org/bin/clang+++0x52cf16a)
#30 0x0000000004f247b9 clang::Parser::ParsePostfixExpressionSuffix(clang::ActionResult<clang::Expr*, true>) (/w/c/org/bin/clang+++0x4f247b9)
#31 0x0000000004f25767 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/w/c/org/bin/clang+++0x4f25767)
#32 0x0000000004f21794 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/w/c/org/bin/clang+++0x4f21794)
#33 0x0000000004eedf3f clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/w/c/org/bin/clang+++0x4eedf3f)
#34 0x0000000004eeb4c3 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/w/c/org/bin/clang+++0x4eeb4c3)
#35 0x0000000004eea785 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/w/c/org/bin/clang+++0x4eea785)
#36 0x0000000004eea111 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/w/c/org/bin/clang+++0x4eea111)
#37 0x0000000004f8e30e clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/w/c/org/bin/clang+++0x4f8e30e)
#38 0x0000000004f8d737 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/w/c/org/bin/clang+++0x4f8d737)
#39 0x0000000004f97360 clang::Parser::ParseCompoundStatementBody(bool) (/w/c/org/bin/clang+++0x4f97360)
#40 0x0000000004f98305 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/w/c/org/bin/clang+++0x4f98305)
#41 0x0000000004edbbde clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) (/w/c/org/bin/clang+++0x4edbbde)
#42 0x0000000004eda14a clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (/w/c/org/bin/clang+++0x4eda14a)
#43 0x0000000004eda14a clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (/w/c/org/bin/clang+++0x4eda14a)
#44 0x0000000004f1352b clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributes&, unsigned int, clang::Decl*) (/w/c/org/bin/clang+++0x4f1352b)
#45 0x0000000004f10ce7 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) (/w/c/org/bin/clang+++0x4f10ce7)
#46 0x0000000004eef9c4 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) (/w/c/org/bin/clang+++0x4eef9c4)
#47 0x0000000004ece484 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/w/c/org/bin/clang+++0x4ece484)
#48 0x0000000004ece138 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/w/c/org/bin/clang+++0x4ece138)
#49 0x0000000004ecd070 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/w/c/org/bin/clang+++0x4ecd070)
#50 0x0000000004eca95f clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/w/c/org/bin/clang+++0x4eca95f)
#51 0x0000000004eca20e clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/w/c/org/bin/clang+++0x4eca20e)
#52 0x0000000004ec4c00 clang::ParseAST(clang::Sema&, bool, bool) (/w/c/org/bin/clang+++0x4ec4c00)
#53 0x0000000003883da0 clang::FrontendAction::Execute() (/w/c/org/bin/clang+++0x3883da0)
#54 0x0000000003802eaf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/w/c/org/bin/clang+++0x3802eaf)
#55 0x0000000003950d76 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/w/c/org/bin/clang+++0x3950d76)
#56 0x0000000000a4d80f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/w/c/org/bin/clang+++0xa4d80f)
#57 0x0000000000a49a7b ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#58 0x0000000003670792 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_1>(long) Job.cpp:0:0
#59 0x0000000002d88439 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/w/c/org/bin/clang+++0x2d88439)
#60 0x0000000003670050 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const (/w/c/org/bin/clang+++0x3670050)
#61 0x000000000363588a clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/w/c/org/bin/clang+++0x363588a)
#62 0x0000000003635b7e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&, bool) const (/w/c/org/bin/clang+++0x3635b7e)
#63 0x0000000003653440 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&) (/w/c/org/bin/clang+++0x3653440)
#64 0x0000000000a48fb7 clang_main(int, char**) (/w/c/org/bin/clang+++0xa48fb7)
#65 0x00007fab12e3f083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#66 0x0000000000a4625e _start (/w/c/org/bin/clang+++0xa4625e)
clang-16: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 16.0.0 (https://github.com/llvm/llvm-project 4f17734175099e0cd492882e17d2ad51fda964aa)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /w/c/org/bin
clang-16: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
```

**Comment by shafik** [comment] 2022-11-26 16:08
This looks like a duplicate of https://github.com/llvm/llvm-project/issues/23688

**Comment by shafik** [comment] 2023-06-10 22:03
Assertion:

```console
clang++: /root/llvm-project/clang/lib/Sema/TreeTransform.h:4120:
clang::ExprResult clang::TreeTransform<Derived>::TransformInitializer(clang::Expr*, bool) [with Derived = {anonymous}::TemplateInstantiator; clang::ExprResult = clang::ActionResult<clang::Expr*>]:
Assertion `NewArgs.empty() && "no parens or braces but have direct init with arguments?"' failed.
```

**Comment by shafik** [comment] 2023-06-10 22:08
Duplicate of: https://github.com/llvm/llvm-project/issues/21394

**Closed by shafik** 2023-06-10 22:08 UTC
Labels: clang:frontend, crash-on-invalid, confirmed
