### ISSUE TITLE
Throwing a non-copyable exception

### ISSUE THREAD

**Issue by jensmaurer** [llvm/llvm-project#57519] opened 2022-09-02 07:21 UTC
`clang -std=c++20` accepts the following program:

```c++
struct S
{
  S() = default;
  S(const S&) = delete;
};

int main()
{
  try {
    throw S();         // #1
  } catch (S s) {
    return 1;
  }
}
```

but it is ill-formed at #1 according to [except.throw] p5. (We need to be able to copy exception objects in a type-erased manner for `std::exception_ptr` on implementations without reference-counted exceptions.)

Cross-reference: gcc bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106812

**Comment by CaseyCarter** [comment] 2023-02-06 00:26
This is a duplicate of #53224.

**Closed** 2023-02-06 01:58 UTC
Labels: duplicate, clang:frontend, accepts-invalid
