### ISSUE TITLE
`__builtin_bit_cast` doesn't properly convert to bool if the value was not 0 or 1

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#60901] opened 2023-02-21 15:39 UTC
See Godbolt: https://godbolt.org/z/P9v65oaba

Filing this against clang since it seems to be the outlier.

```c++
constexpr char c = 2;
constexpr bool b = __builtin_bit_cast(bool, c);
```

```console
<source>:2:16: error: constexpr variable 'b' must be initialized by a constant expression
constexpr bool b = __builtin_bit_cast(bool, c);
               ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:2:20: note: value 2 cannot be represented in type 'bool'
constexpr bool b = __builtin_bit_cast(bool, c);
                   ^
1 error generated.
```

bools are 1 byte large, not 1 bit, so this shouldn't be a problem as far as I can see.

**Comment by AaronBallman** [comment] 2023-02-21 15:53
`bool` needs to only represent `true` and `false`, so it's a bit unclear how to interpret https://eel.is/c++draft/bit.cast#2.sentence-5.

http://eel.is/c++draft/basic.types#basic.fundamental-10 makes it clear there's an implementation-defined decision here as to the object and value representation of `bool`. If we decided that `bool` only requires one bit to represent it, then it can only represent -1 (or 1) and 0, and 2 is neither of those. I *think* (but haven't verified) that we treat the object representation as being the width of a `char` but the value representation as only having a single bit.

**Comment by shafik** [comment] 2023-02-21 17:39
Note, although it does not really resolve the unspecified nature here but compiler pretty consistently treat this:

```cpp
bool b = {2} ; 
```

as ill-formed narrowing conversion: https://godbolt.org/z/c7E81E8PY

On the more fun side, `memcpy`'ing a value of `2` or `3` to a `bool` while completely 💯 UB can amusingly result in it being considered both `true` and `false`: https://twitter.com/shafikyaghmour/status/1148990347386580992?s=20

**Comment by tbaederr** [comment] 2023-02-21 18:53
> `bool` needs to only represent `true` and `false`, so it's a bit unclear how to interpret https://eel.is/c++draft/bit.cast#2.sentence-5.

_A bit_ unclear, I get it.

Thanks for the info though. I guess we can close this then? Or should the spec make this clearer?

**Comment by AaronBallman** [comment] 2023-02-21 19:14
> Thanks for the info though. I guess we can close this then? Or should the spec make this clearer?

Given that Clang is the odd-implementation-out, let's ask some STL folks just to be certain (but I think this can be closed as not a bug). @ldionne @jwakely @StephanTLavavej would any of you care to make a case for Clang's behavior being wrong? (Feel free to ping others if you'd like.)

**Comment by jwakely** [comment] 2023-02-21 19:35
I think the test case is undefined, so clang can do what it likes.

**Comment by shafik** [comment] 2023-02-21 21:49
Now that I think about it again, even bit casting from `1` should be UB since we don't actually know the underlying values that `true` and `false` map to.

We have [DR 1448](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_closed.html#1448) but the resolution only deals w/ conversion of `false` to *null pointer constant* and not the wider issue.

**Comment by jwakely** [comment] 2023-02-21 22:07
It's not undefined if the value representation of `(char)1` happens to be the same bit pattern as the value representation of `true`, the problem is that you can't know whether that is the case in portable code.

But I don't consider it to be a big problem; just don't bit cast to bool. I don't think there are going to be many valid use cases for doing that.

**Comment by AaronBallman** [comment] 2023-02-22 12:41
Thanks for the discussion! I'm comfortable closing this as not a bug.

**Closed by AaronBallman** 2023-02-22 12:41 UTC
Labels: invalid, c++20, clang:frontend
