### ISSUE TITLE
Errors when initializing _Atomic scalars with their non-atomic counterparts

### ISSUE THREAD

**Issue by pskocik** [llvm/llvm-project#53804] opened 2022-02-13 11:23 UTC
In the following set of examples, all the examples under ERR raise compiletime errors on clang but are accepted by other compilers (gcc, icc):

```
#if ERR
char *_Atomic zero = 0;
void zerofn(void){ (void)(char *_Atomic){0}; }
#endif
char *_Atomic ptr = (void*)0;
#if ERR
void ptrfn(void){ (void)(char *_Atomic){(void*)0}; }
#endif
char *_Atomic chptr = (char*)0;
#if ERR
void chptrfn(void){ (void)(char *_Atomic){(char*)0}; }
#endif

char *chp=0;
char *vp=0;
#if ERR
void chptrfn2(void){ (void)(char *_Atomic){chp}; }
void chptrfn3(void){ (void)(char *_Atomic){vp}; }
#endif
_Atomic int ai  = 0;
#if ERR
void itnfn(void){ (void)(_Atomic int){0}; }
#endif

```
https://gcc.godbolt.org/z/xzvo7n88c

I believe this is a bug. Ran into this while trying to use _Atomic literals inside of __typeof.

**Comment by efriedma-quic** [comment] 2022-02-14 18:20
The descriptions of constant expressions and initializer lists in the standard don't mention atomics at all.  But I guess the intent is clear; it doesn't make sense to specifically prohibit atomics in those contexts.

All the failing examples basically reduce to just the following:

```
_Atomic(char *) a = {0};
```

**Comment by AaronBallman** [comment] 2023-04-20 13:51
There's been some improvement here in that we now accept: `_Atomic(char *) a = 0;` rather than reject it, but the issue with braced initialization still remains (and also impacts empty brace initialization the same way).

**Comment by AaronBallman** [comment] 2023-04-20 15:14
Ah, now I know why this seemed familiar. This is a duplicate of #28814.

**Closed by AaronBallman** 2023-04-20 15:14 UTC
Labels: duplicate, c11, clang:frontend, rejects-valid, confirmed
