### ISSUE TITLE
[Flang] Compilation error of adjustable explicit-shape array

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#68652] opened 2023-10-10 02:09 UTC
```
Version of flang-new : 18.0.0(cc627828f5176c6d75a25f1756d387d18539c1fb)
```

`Adjustable explicit-shape array` specified in `PRIVATE` clause results in a compilation error.

The following are the test program, Flang-new, Gfortran and ifort compilation result.

snggk268_2.f90:
```fortran
subroutine test01(ic)
  common/com01/ i3,iarr(10)
  integer ic(iarr(i3))
!$omp parallel private(ic)
!$omp end parallel
end subroutine test01
```

```
$ flang-new snggk268_2.f90 -c -fopenmp
error: Semantic errors in snggk268_2.f90
./snggk268_2.f90:3:14: error: 'iarr' is not an object that can appear in an expression
    integer ic(iarr(i3))
               ^^^^
./snggk268_2.f90:2:20: Declaration of 'iarr'
    common/com01/ i3,iarr(10)
                     ^^^^
$
```

```
$ gfortran snggk268_2.f90 -c -fopenmp
$
```

```
$ ifort snggk268_2.f90 -c -qopenmp
$
```

**Comment by atzhtianyu** [comment] 2023-10-30 07:58
I removed the `PRIVATE` clause from this test program and it still results in a compilation error.
The following are the test program, Flang-new and Gfortran compilation result.
snggk268_2.f90:
```fortran
subroutine test01(ic)
  common/com01/ i3,iarr(10)
  integer ic(iarr(i3))
end subroutine test01
```
```
$ flang-new snggk268_2.f90 -c -fopenmp
error: Semantic errors in snggk268_2.f90
./snggk268_2.f90:3:14: error: 'iarr' is not an object that can appear in an expression
    integer ic(iarr(i3))
               ^^^^
./snggk268_2.f90:2:20: Declaration of 'iarr'
    common/com01/ i3,iarr(10)
                     ^^^^
```
```
$ gfortran snggk268_2.f90 -c -fopenmp
$
```
In this case, is it related to openmp?

**Comment by kiranchandramohan** [comment] 2023-11-21 23:05
Removing OpenMP tag since the issue is present without OpenMP constructs and also the `-fopenmp` flag.

```
./bin/flang-new sngg.f90 
error: Semantic errors in sngg.f90
./sngg.f90:3:14: error: 'iarr' is not an object that can appear in an expression
    integer ic(iarr(i3))
               ^^^^
./sngg.f90:2:20: Declaration of 'iarr'
    common/com01/ i3,iarr(10)
                     ^^^^

```

**Comment by klausler** [comment] 2023-11-22 15:20
Likely due to the deferral of `COMMON` statement processing to the end of the specification part; will fix.

**Comment by klausler** [comment] 2023-11-22 21:05
Fix coming in https://github.com/llvm/llvm-project/pull/73169.

**Comment by klausler** [comment] 2023-11-30 21:08
Fix has been merged into llvm-project/main; closing this bug.

**Closed** 2023-11-30 21:07 UTC
Labels: flang:frontend
