### ISSUE TITLE
[Clang] _Atomic Pointer Arithmetic error

### ISSUE THREAD

**Issue by zhangtianhao6** [llvm/llvm-project#116736] opened 2024-11-19 03:19 UTC
demo.c
```
#include<stdio.h>
int main(){
static int ia[2];
 static volatile _Atomic (int *) a = (int *) (&ia[1]);
 if ((a += (1)) != (int *) ((int *) (&ia[1]) + (1)))
         printf("1");
}
```
compile failed
```
<source>:5:9: error: invalid operands to binary expression ('volatile _Atomic(int *)' and 'int')
    5 |  if ((a += (1)) != (int *) ((int *) (&ia[1]) + (1)))
      |       ~ ^  ~~~
1 error generated.
Compiler returned: 1
```

Gcc is ok
https://godbolt.org/z/fMqzoe4b5

Does llvm supprot _Atomic Pointer Arithmetic?

**Comment by neldredge** [comment] 2024-11-19 05:04
Duplicate of #25135

**Closed** 2024-11-19 05:35 UTC
Labels: duplicate, clang:frontend, diverges-from:gcc
