### ISSUE TITLE
[Clang][OpenMP] Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.

### ISSUE THREAD

**Issue by wierton** [llvm/llvm-project#69085] opened 2023-10-15 01:14 UTC
The program to reproduce this crash:
```
int k[-46], t[10];
#pragma omp threadprivate(t)

void foo() {
#pragma omp task depend(inout: k [0.5:])
}
```

Compiler Explorer: https://godbolt.org/z/WxzxbMPMG
Related Clang's Commit: f2b79ed9c6c858426b15a0374103ab901b5b2ef3

The stack dump:
```
<source>:1:7: error: 'k' declared as an array with a negative size
    1 | int k[-46], t[10];
      |       ^~~
<source>:2:27: error: use of undeclared identifier 't'
    2 | #pragma omp threadprivate(t)
      |                           ^
clang: /root/llvm-project/clang/include/clang/AST/Type.h:752: const clang::ExtQualsTypeCommonBase* clang::QualType::getCommonPtr() const: Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-9.2.0 -fcolor-diagnostics -fno-crash-diagnostics -O0 -fopenmp-simd <source>
1.	<source>:5:41: at annotation token
2.	<source>:4:12: parsing function body 'foo'
3.	<source>:4:12: in compound statement ('{}')
 #0 0x000000000372dd18 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x372dd18)
 #1 0x000000000372b9dc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x372b9dc)
 #2 0x00000000036742f8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007fc543274420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007fc542d3700b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007fc542d16859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007fc542d16729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007fc542d27fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000000003a529df clang::QualType::getNonReferenceType() const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3a529df)
 #9 0x00000000066b58bd clang::Sema::ActOnOpenMPDependClause(clang::OMPDependClause::DependDataTy const&, clang::Expr*, llvm::ArrayRef<clang::Expr*>, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x66b58bd)
#10 0x0000000006702ca0 clang::Sema::ActOnOpenMPVarListClause(llvm::omp::Clause, llvm::ArrayRef<clang::Expr*>, clang::OMPVarListLocTy const&, clang::Sema::OpenMPVarListDataTy&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x6702ca0)
#11 0x0000000005f5040f clang::Parser::ParseOpenMPVarListClause(llvm::omp::Directive, llvm::omp::Clause, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f5040f)
#12 0x0000000005f506a8 clang::Parser::ParseOpenMPClause(llvm::omp::Directive, llvm::omp::Clause, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f506a8)
#13 0x0000000005f5c7b8 clang::Parser::ParseOpenMPDeclarativeOrExecutableDirective(clang::Parser::ParsedStmtContext, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f5c7b8)
#14 0x0000000005f792e4 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f792e4)
#15 0x0000000005f7b188 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f7b188)
#16 0x0000000005f7c0c9 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f7c0c9)
#17 0x0000000005f7d9ea clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5f7d9ea)
#18 0x0000000005eab6d1 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5eab6d1)
#19 0x0000000005ed2bd8 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ed2bd8)
#20 0x0000000005e9fb3b clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5e9fb3b)
#21 0x0000000005ea026f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#22 0x0000000005ea7c14 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ea7c14)
#23 0x0000000005ea843d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5ea843d)
#24 0x0000000005e9b4ea clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x5e9b4ea)
#25 0x00000000049982a8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x49982a8)
#26 0x00000000041fc4f9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x41fc4f9)
#27 0x000000000417d9ce clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x417d9ce)
#28 0x00000000042db54e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x42db54e)
#29 0x0000000000bef0e6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbef0e6)
#30 0x0000000000be69aa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#31 0x0000000003fd9c19 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#32 0x00000000036747a4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x36747a4)
#33 0x0000000003fda20f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#34 0x0000000003fa23d5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3fa23d5)
#35 0x0000000003fa2e3d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3fa2e3d)
#36 0x0000000003faad65 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0x3faad65)
#37 0x0000000000bec58c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbec58c)
#38 0x0000000000ae6751 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xae6751)
#39 0x00007fc542d18083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#40 0x0000000000be648e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+0xbe648e)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
```

**Comment by neoncube2** [comment] 2023-10-30 12:41
This looks like a duplicate of https://github.com/llvm/llvm-project/issues/69200

(Well, this issue was first, but the other issue has already been assigned to someone, so it might make more sense to close this issue)

**Comment by shiltian** [comment] 2023-10-30 14:52
@gogo2464 You might want to check if this issue can be fixed with your patch. If so, you could close this one as well when you fix https://github.com/llvm/llvm-project/issues/69200.

**Comment by gogo2464** [comment] 2023-10-30 15:18
@shiltian I did not provide a patch yet. I just located the code that has an issue. I do not have a lot of time. I would like to do it this month.

**Comment by gogo2464** [comment] 2023-12-13 18:32
Hello. I do not have the time to do it. I must provide more time for my work. If somebody would like to fill this issue, he could do it.

**Comment by Sh0g0-1758** [comment] 2024-01-09 05:46
@wierton , this is somewhat similar to #69200 but the reason of crash is different. I am new to LLVM and would like to work on this issue. Can you please assign me it.

**Comment by wierton** [comment] 2024-01-09 08:22
@Sh0g0-1758, you may want to @ the developer to assign it to you, I don't have necessary priviledge to do so.

**Comment by Sh0g0-1758** [comment] 2024-01-09 08:25
@shiltian, can you assign me this issue.

**Comment by Sh0g0-1758** [comment] 2024-01-23 13:29
Hello @jhuber6 , I tracked the bug and found that the second error is there because of the first error only. So if you write the code like this : 

```
int k[-46];
int t[10];
#pragma omp threadprivate(t)

void foo() {
#pragma omp task depend(inout: k [0.5:])
}
```

Then only the error of negative size will arise. Since that is handled by this [issue](https://github.com/llvm/llvm-project/issues/69198), I can add a check so as to make sure it gets ignored in the SemaOpenMP.cpp file like this : 

```
            if (ExprTy.isNull()) {
              continue;
            }
            ExprTy = ExprTy.getNonReferenceType();
```

Shall I raise a PR for the same? Also it would be really helpful if you could guide me as to how to add tests for the same.

**Comment by jhuber6** [comment] 2024-01-23 13:51
> Shall I raise a PR for the same? Also it would be really helpful if you could guide me as to how to add tests for the same.

The compiler should never hit an assertion, so it should definitely be fixed if it's still causing a compiler crash. If it's an issue with a negative index then we probably just need an extra Sema check like you've pointed out.

Adding tests is done through LLVM's lit testing infrastructure. Your build of LLVM will always have `llvm-lit` as a binary, which more or less runs some command line arguments and then checks the output against some regular expressions. Since this is likely an issue in Sema, you'll probably just need to add a test like the one in the issue you linked earlier. The one with `expected-error`. You can run these yourself by doing `./bin/llvm-lit ../clang/test/OpenMP/bug69198.c -vv`.

**Comment by Sh0g0-1758** [comment] 2024-02-07 17:36
@jhuber6, I have made a PR for this issue with the required changes and a test. Please review it.

**Closed** 2024-02-07 19:38 UTC
Labels: good first issue, openmp, clang:frontend, crash-on-invalid
