### ISSUE TITLE
support raw string literals in (gnu) c mode

### ISSUE THREAD

**Issue by Villemoes** [llvm/llvm-project#71933] opened 2023-11-10 12:23 UTC
As an extension, gcc supports using `R"(raw string literals)"` in C when using `-std=gnu99` or higher. It would be nice if clang did the same.

Godbolt example: https://godbolt.org/z/TaYMhhGjx

**Comment by AaronBallman** [comment] 2023-11-10 14:04
Duplicate of #39238

**Closed by AaronBallman** 2023-11-10 14:04 UTC
Labels: enhancement, c, clang:frontend, extension:gnu
