### ISSUE TITLE
'out-of-line definition' when defining member function enabled with concept outside class

### ISSUE THREAD

**Issue by alemuntoni** [llvm/llvm-project#56442] opened 2022-07-08 10:35 UTC
When building the following code with Clang 14.0.0 (flag `-std=c++20`):

```cpp
template<typename T>
concept MyConcept = std::is_integral<T>::value; //could be anything...

template<typename T>
class F {
public:
    void foo() requires MyConcept<F>;
};

template<typename T>
void F<T>::foo() requires MyConcept<F<T>>
{
    //long implementation...
}
```

I get the following error:

```console
main.cpp:38: error: out-of-line definition of 'foo' does not match any declaration in 'F<T>'
main.cpp:38:12: error: out-of-line definition of 'foo' does not match any declaration in 'F<T>'
void F<T>::foo() requires MyConcept<F<T>>
           ^~~
main.cpp:34:7: note: member declaration nearly matches
        void foo() requires MyConcept<F>;
             ^
```
that seems a bug since the code should be correct.

See also https://stackoverflow.com/questions/72897153/outside-class-definition-of-member-function-enabled-with-concept?noredirect=1#comment128757341_72897153

**Comment by alemuntoni** [comment] 2022-07-09 15:31
I don't know if I need to open another issue, but I have another issue related to outside-class member function definition. When building this piece of code:
```
template<typename T>
concept MyConcept = std::is_integral<T>::value; //could be anything...

template<typename T>
class F {
public:
	void foo() {};
};

template<MyConcept T>
class F<T> {
public:
	void foo();
};

template<MyConcept T>
void F<T>::foo()
{
}
```

I get:
```
main.cpp:43:10: error: type constraint differs in template redeclaration
template<MyConcept T>
         ^
main.cpp:31:10: note: previous template declaration is here
template<typename T>
         ^
1 error generated.
```
it seems that the outside class definition of `foo` is referring to the non-specialized `F` class.
Works fine when placing the definition of `foo` inside the specialized `F` class.

**Comment by Flarkk** [comment] 2022-08-27 23:06
I experience this exact bug as well, with this function template.
It does not compile if defined outside the class (but does well inside).
Experienced with clang-14.
```
template <typename T, nav::ParserGetter PG>
template <typename C, PtrToMember<C, MyClass<T, PG>> PTMB>
void MyClass<T, PG>::my_function(...)
{ ... }
```

**Comment by royjacobson** [comment] 2022-09-29 16:57
The first issue was duplicate of #56482 and is solved now. The second issue with the template specializations is #50208, so I'm closing this issue.

**Closed by royjacobson** 2022-09-29 16:57 UTC
Labels: clang:frontend, concepts
