### ISSUE TITLE
opt: ../lib/Analysis/ScalarEvolution.cpp:12526: ScalarEvolution::ExitLimit llvm::ScalarEvolution::howManyLessThans(const llvm::SCEV *, const llvm::SCEV *, const llvm::Loop *, bool, bool, bool): Assertion `isAvailableAtLoopEntry(OrigRHS, L) && "Must be!"' failed.

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#55910] opened 2022-06-07 06:26 UTC
llvm commit: a7b154aa177
Reproduce with: ```opt -passes="loop-mssa(indvars),loop(loop-deletion,require<access-info>)" bbi-70606.ll -o /dev/null```
[bbi-70606.ll.gz](https://github.com/llvm/llvm-project/files/8850629/bbi-70606.ll.gz)

Result:
```
opt: ../lib/Analysis/ScalarEvolution.cpp:12455: ScalarEvolution::ExitLimit llvm::ScalarEvolution::howManyLessThans(const llvm::SCEV *, const llvm::SCEV *, const llvm::Loop *, bool, bool, bool): Assertion `isAvailableAtLoopEntry(OrigRHS, L) && "Must be!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build-all/bin/opt -passes=loop-mssa(indvars),loop(loop-deletion,require<access-info>) bbi-70606.ll -o /dev/null
 #0 0x0000000002cab533 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build-all/bin/opt+0x2cab533)
 #1 0x0000000002ca91ae llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x2ca91ae)
 #2 0x0000000002cab8b6 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f1c5ce78630 __restore_rt sigaction.c:0:0
 #4 0x00007f1c5a5bf387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f1c5a5c0a78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007f1c5a5b81a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007f1c5a5b8252 (/lib64/libc.so.6+0x2f252)
 #8 0x0000000001cfc83f llvm::ScalarEvolution::howManyLessThans(llvm::SCEV const*, llvm::SCEV const*, llvm::Loop const*, bool, bool, bool) (build-all/bin/opt+0x1cfc83f)
 #9 0x0000000001cf6083 llvm::ScalarEvolution::computeExitLimitFromICmp(llvm::Loop const*, llvm::CmpInst::Predicate, llvm::SCEV const*, llvm::SCEV const*, bool, bool) (build-all/bin/opt+0x1cf6083)
#10 0x0000000001cf5ce4 llvm::ScalarEvolution::computeExitLimitFromICmp(llvm::Loop const*, llvm::ICmpInst*, bool, bool, bool) (build-all/bin/opt+0x1cf5ce4)
#11 0x0000000001cf527f llvm::ScalarEvolution::computeExitLimitFromCondImpl(llvm::ScalarEvolution::ExitLimitCache&, llvm::Loop const*, llvm::Value*, bool, bool, bool) (build-all/bin/opt+0x1cf527f)
#12 0x0000000001cf4d87 llvm::ScalarEvolution::computeExitLimitFromCondCached(llvm::ScalarEvolution::ExitLimitCache&, llvm::Loop const*, llvm::Value*, bool, bool, bool) (build-all/bin/opt+0x1cf4d87)
#13 0x0000000001cf4487 llvm::ScalarEvolution::computeExitLimit(llvm::Loop const*, llvm::BasicBlock*, bool) (build-all/bin/opt+0x1cf4487)
#14 0x0000000001cf013b llvm::ScalarEvolution::computeBackedgeTakenCount(llvm::Loop const*, bool) (build-all/bin/opt+0x1cf013b)
#15 0x0000000001cef566 llvm::ScalarEvolution::getPredicatedBackedgeTakenInfo(llvm::Loop const*) (build-all/bin/opt+0x1cef566)
#16 0x0000000001d12aa8 llvm::PredicatedScalarEvolution::getBackedgeTakenCount() (build-all/bin/opt+0x1d12aa8)
#17 0x0000000001c0f972 llvm::LoopAccessInfo::canAnalyzeLoop() (build-all/bin/opt+0x1c0f972)
#18 0x0000000001c14583 llvm::LoopAccessInfo::LoopAccessInfo(llvm::Loop*, llvm::ScalarEvolution*, llvm::TargetLibraryInfo const*, llvm::AAResults*, llvm::DominatorTree*, llvm::LoopInfo*) (build-all/bin/opt+0x1c14583)
#19 0x0000000001c157dd llvm::LoopAccessAnalysis::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&) (build-all/bin/opt+0x1c157dd)
#20 0x0000000002ff2b2e llvm::detail::AnalysisPassModel<llvm::Loop, llvm::LoopAccessAnalysis, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::Invalidator, llvm::LoopStandardAnalysisResults&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&) crtstuff.c:0:0
#21 0x0000000001c1cfae llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::getResultImpl(llvm::AnalysisKey*, llvm::Loop&, llvm::LoopStandardAnalysisResults&) (build-all/bin/opt+0x1c1cfae)
#22 0x000000000301a83b llvm::RequireAnalysisPass<llvm::LoopAccessAnalysis, llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) crtstuff.c:0:0
#23 0x000000000301a67d llvm::detail::PassModel<llvm::Loop, llvm::RequireAnalysisPass<llvm::LoopAccessAnalysis, llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) crtstuff.c:0:0
#24 0x000000000358205f llvm::Optional<llvm::PreservedAnalyses> llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::runSinglePass<llvm::Loop, std::unique_ptr<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, std::default_delete<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>>>>(llvm::Loop&, std::unique_ptr<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, std::default_delete<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>>>&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&, llvm::PassInstrumentation&) (build-all/bin/opt+0x358205f)
#25 0x0000000003581c83 llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::runWithoutLoopNestPasses(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) (build-all/bin/opt+0x3581c83)
#26 0x0000000003581348 llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) (build-all/bin/opt+0x3581348)
#27 0x0000000002fea55d llvm::detail::PassModel<llvm::Loop, llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) crtstuff.c:0:0
#28 0x000000000358335b llvm::FunctionToLoopPassAdaptor::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x358335b)
#29 0x0000000003007dfd llvm::detail::PassModel<llvm::Function, llvm::FunctionToLoopPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManopt: ../lib/Analysis/ScalarEvolution.cpp:12455: ScalarEvolution::ExitLimit llvm::ScalarEvolution::howManyLessThans(const llvm::SCEV *, const llvm::SCEV *, const llvm::Loop *, bool, bool, bool): Assertion `isAvailableAtLoopEntry(OrigRHS, L) && "Must be!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build-all/bin/opt -passes=loop-mssa(indvars),loop(loop-deletion,require<access-info>) bbi-70606.ll -o /dev/null
 #0 0x0000000002cab533 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build-all/bin/opt+0x2cab533)
 #1 0x0000000002ca91ae llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x2ca91ae)
 #2 0x0000000002cab8b6 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f1c5ce78630 __restore_rt sigaction.c:0:0
 #4 0x00007f1c5a5bf387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f1c5a5c0a78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x00007f1c5a5b81a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #7 0x00007f1c5a5b8252 (/lib64/libc.so.6+0x2f252)
 #8 0x0000000001cfc83f llvm::ScalarEvolution::howManyLessThans(llvm::SCEV const*, llvm::SCEV const*, llvm::Loop const*, bool, bool, bool) (build-all/bin/opt+0x1cfc83f)
 #9 0x0000000001cf6083 llvm::ScalarEvolution::computeExitLimitFromICmp(llvm::Loop const*, llvm::CmpInst::Predicate, llvm::SCEV const*, llvm::SCEV const*, bool, bool) (build-all/bin/opt+0x1cf6083)
#10 0x0000000001cf5ce4 llvm::ScalarEvolution::computeExitLimitFromICmp(llvm::Loop const*, llvm::ICmpInst*, bool, bool, bool) (build-all/bin/opt+0x1cf5ce4)
#11 0x0000000001cf527f llvm::ScalarEvolution::computeExitLimitFromCondImpl(llvm::ScalarEvolution::ExitLimitCache&, llvm::Loop const*, llvm::Value*, bool, bool, bool) (build-all/bin/opt+0x1cf527f)
#12 0x0000000001cf4d87 llvm::ScalarEvolution::computeExitLimitFromCondCached(llvm::ScalarEvolution::ExitLimitCache&, llvm::Loop const*, llvm::Value*, bool, bool, bool) (build-all/bin/opt+0x1cf4d87)
#13 0x0000000001cf4487 llvm::ScalarEvolution::computeExitLimit(llvm::Loop const*, llvm::BasicBlock*, bool) (build-all/bin/opt+0x1cf4487)
#14 0x0000000001cf013b llvm::ScalarEvolution::computeBackedgeTakenCount(llvm::Loop const*, bool) (build-all/bin/opt+0x1cf013b)
#15 0x0000000001cef566 llvm::ScalarEvolution::getPredicatedBackedgeTakenInfo(llvm::Loop const*) (build-all/bin/opt+0x1cef566)
#16 0x0000000001d12aa8 llvm::PredicatedScalarEvolution::getBackedgeTakenCount() (build-all/bin/opt+0x1d12aa8)
#17 0x0000000001c0f972 llvm::LoopAccessInfo::canAnalyzeLoop() (build-all/bin/opt+0x1c0f972)
#18 0x0000000001c14583 llvm::LoopAccessInfo::LoopAccessInfo(llvm::Loop*, llvm::ScalarEvolution*, llvm::TargetLibraryInfo const*, llvm::AAResults*, llvm::DominatorTree*, llvm::LoopInfo*) (build-all/bin/opt+0x1c14583)
#19 0x0000000001c157dd llvm::LoopAccessAnalysis::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&) (build-all/bin/opt+0x1c157dd)
#20 0x0000000002ff2b2e llvm::detail::AnalysisPassModel<llvm::Loop, llvm::LoopAccessAnalysis, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::Invalidator, llvm::LoopStandardAnalysisResults&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&) crtstuff.c:0:0
#21 0x0000000001c1cfae llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::getResultImpl(llvm::AnalysisKey*, llvm::Loop&, llvm::LoopStandardAnalysisResults&) (build-all/bin/opt+0x1c1cfae)
#22 0x000000000301a83b llvm::RequireAnalysisPass<llvm::LoopAccessAnalysis, llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) crtstuff.c:0:0
#23 0x000000000301a67d llvm::detail::PassModel<llvm::Loop, llvm::RequireAnalysisPass<llvm::LoopAccessAnalysis, llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) crtstuff.c:0:0
#24 0x000000000358205f llvm::Optional<llvm::PreservedAnalyses> llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::runSinglePass<llvm::Loop, std::unique_ptr<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, std::default_delete<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>>>>(llvm::Loop&, std::unique_ptr<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, std::default_delete<llvm::detail::PassConcept<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>>>&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&, llvm::PassInstrumentation&) (build-all/bin/opt+0x358205f)
#25 0x0000000003581c83 llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::runWithoutLoopNestPasses(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) (build-all/bin/opt+0x3581c83)
#26 0x0000000003581348 llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) (build-all/bin/opt+0x3581348)
#27 0x0000000002fea55d llvm::detail::PassModel<llvm::Loop, llvm::PassManager<llvm::Loop, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&>::run(llvm::Loop&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>&, llvm::LoopStandardAnalysisResults&, llvm::LPMUpdater&) crtstuff.c:0:0
#28 0x000000000358335b llvm::FunctionToLoopPassAdaptor::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x358335b)
#29 0x0000000003007dfd llvm::detail::PassModel<llvm::Function, llvm::FunctionToLoopPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
#30 0x0000000002471945 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x2471945)
#31 0x0000000000b14dfd llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
#32 0x0000000002475d4a llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x2475d4a)
#33 0x0000000000b14bdd llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) crtstuff.c:0:0
#34 0x0000000002470ad8 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x2470ad8)
#35 0x000000000079098f llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (build-all/bin/opt+0x79098f)
#36 0x00000000007a174f main (build-all/bin/opt+0x7a174f)
#37 0x00007f1c5a5ab555 __libc_start_main (/lib64/libc.so.6+0x22555)
#38 0x000000000078b340 _start (build-all/bin/opt+0x78b340)
Abort
ager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
#30 0x0000000002471945 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x2471945)
#31 0x0000000000b14dfd llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
#32 0x0000000002475d4a llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x2475d4a)
#33 0x0000000000b14bdd llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) crtstuff.c:0:0
#34 0x0000000002470ad8 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x2470ad8)
#35 0x000000000079098f llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (build-all/bin/opt+0x79098f)
#36 0x00000000007a174f main (build-all/bin/opt+0x7a174f)
#37 0x00007f1c5a5ab555 __libc_start_main (/lib64/libc.so.6+0x22555)
#38 0x000000000078b340 _start (build-all/bin/opt+0x78b340)
Abort
```

**Comment by mikaelholmen** [comment] 2022-06-08 11:37
With typed pointers it starts crashing with 6c99e63120:
```
    [SCEV] By more careful when traversing phis in isImpliedViaMerge.
    
    I think currently isImpliedViaMerge can incorrectly return true for phis
    in a loop/cycle, if the found condition involves the previous value of
    
    Consider the case in exit_cond_depends_on_inner_loop.
    
    At some point, we call (modulo simplifications)
    isImpliedViaMerge(<=, %x.lcssa, -1, %call, -1).
    
    The existing code tries to prove IncV <= -1 for all incoming values
    InvV using the found condition (%call <= -1). At the moment this succeeds,
    but only because it does not compare the same runtime value. The found
    condition checks the value of the last iteration, but the incoming value
    is from the *previous* iteration.
    
    Hence we incorrectly determine that the *previous* value was <= -1,
    which may not be true.
    
    I think we need to be more careful when looking at the incoming values
    here. In particular, we need to rule out that a found condition refers to
    any value that may refer to one of the previous iterations. I'm not sure
    there's a reliable way to do so (that also works of irreducible control
    flow).
    
    So for now this patch adds an additional requirement that the incoming
    value must properly dominate the phi block. This should ensure the
    values do not change in a cycle. I am not entirely sure if will catch
    all cases and I appreciate a through second look in that regard.
    
    Alternatively we could also unconditionally bail out in this case,
    instead of checking the incoming values
    
    Reviewed By: nikic
    
    Differential Revision: https://reviews.llvm.org/D101829
```
So: ```opt -passes="loop-mssa(indvars),loop(loop-deletion,require<access-info>)" bbi-70606_typed.ll -o /dev/null```
[bbi-70606_typed.ll.gz](https://github.com/llvm/llvm-project/files/8861132/bbi-70606_typed.ll.gz)


cc: @fhahn

**Comment by fhahn** [comment] 2022-06-30 11:18
I am unable to reproduce this on current `main`. It would be great if you could verify this as fixed on your end. If it still reproduces on your side, please re-open the issue with an update reproducer.

**Closed by fhahn** 2022-06-30 11:18 UTC
Labels: llvm:crash, llvm:optimizations

**Comment by mikaelholmen** [comment] 2022-07-18 08:10
> I am unable to reproduce this on current `main`. It would be great if you could verify this as fixed on your end. If it still reproduces on your side, please re-open the issue with an update reproducer.

Yes it seems the crash went away with 20d798bd47
```Recommit "[SCEV] Look through single value PHIs." (take 3)```
Thanks :)
