### ISSUE TITLE
//comment prefix spacing not working v13 (with ReflowComments: false)

### ISSUE THREAD

**Issue by mplexor** [llvm/llvm-project#53187] opened 2022-01-13 18:21 UTC
```
---
Language:        Cpp
BasedOnStyle:  LLVM
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: -1
ReflowComments:  false
```

```
switch (0) {
   case 0: test(); break; //should have prefix spacing
}
```

**Comment by mkurdej** [comment] 2022-01-14 08:45
`ReflowComments: false` makes clang-format not touch comments at all (comment tokens becoming unbreakable), so not adding nor removing leading whitespace too.
I'm not entirely sure that it's the intended behaviour though. @mydeveloperday, opinion?

**Comment by mydeveloperday** [comment] 2022-01-14 09:00
For me this is a case of options that might conflict with each other, I almost feel like we can call this `undefined behaviour` and we give no guarantees what might/might not happen or what option might win. Sorry, I don't think this is a bug, and frankly, at this stage of our development (and the effort associated with providing a patch) I don't think we have to cover these cases. I would rather spend my time fixing issues that actually cause the code to format incorrectly. I'd say reject this is "Functioning as Designed" (which would make a good github label to be honest if it doesn't already exist)

**Comment by mkurdej** [comment] 2022-01-14 09:12
Closing. `ReflowComments: false` doesn't touch comments at all, by design.

**Closed by mkurdej** 2022-01-14 09:12 UTC
Labels: clang-format, invalid-bug

**Comment by mplexor** [comment] 2022-01-14 15:46
reflow comments is independent config option and should not be tied together with comment prefix.
reflow comments who can tell its a preceding option to all other comment related config options?
If its by design, that means its incomplete implementation imo.
