### ISSUE TITLE
Explicit object operator() copies movable temporaries

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#100542] opened 2024-07-25 09:38 UTC
This program
```
struct A {
    A() {}
    A(A&&) = default;
    void operator() (this A) {}
};

int main() {
    A{}.operator()(); // ok
    A{}();            // fails in Clang
}
```
is accepted by GCC and MSVC, but not in Clang, which tries to copy `A` in `A{}();`:
```
error: call to implicitly-deleted copy constructor of 'A'
    9 |     A{}();            // fails in Clang
      |     ^~~
<source>:3:5: note: copy constructor is implicitly deleted because 'A' has a user-declared move constructor
    3 |     A(A&&) = default;
      |     ^
<source>:4:28: note: passing argument to parameter here
    4 |     void operator() (this A) {}
      |               
```
Online demo: https://gcc.godbolt.org/z/YEKh8G71o

**Comment by MitalAshok** [comment] 2024-07-25 09:49
Duplicate of #100341

**Closed** 2024-07-25 14:29 UTC
Labels: duplicate, clang:frontend
