### ISSUE TITLE
Diagnostic for functions that are candidates for inlining but couldn't be inlined

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#79953] opened 2024-01-30 07:05 UTC
We would like to emit a diagnostic when the function is hot (based on a profile) and a candidate for inlining but couldn't be inlined because its definition is not available externally.

This is a use case we encountered in embedded applications where hot functions are often defined in a source file (rather than a header) and thus cannot be inlined across translation units. Normally this would be addressed by LTO, but that's not viable in this case because embedded applications often rely on complex linker scripts whose semantics is incompatible with LTO ([this talk](https://llvm.org/devmtg/2017-10/slides/LTOLinkerScriptsEdlerVonKoch.pdf) has more details). We would eventually like to address this limitation by extending LTO to support linker scripts, but we believe that such a diagnostics would provide a useful alternative giving developers a hint where it would beneficial to move the definition to a header to allow more inlining.

cc @teresajohnson @david-xl @aeubanks @nickdesaulniers @ilovepi

**Comment by ilovepi** [comment] 2024-01-30 15:30
I think the problem is when the function’s implementation is unavailable because it originated from a different TU, and thus isn’t in the module. If the developer had a signal that it would be profitable to inline across modules, they may be able to refactor their code to be amenable to inlining, for example by moving it to a header. 

LTO is still a more powerful (and probably better suited) option, but as @petrhosek mentioned, not all code base can use LLVMs LTO if they rely on certain linker script features. 

I don’t recall if ‘-Rpass-missed=inline’ handles that case, but maybe that would work. If not maybe we can extend it to report those cases by adding a few checks when using a profile?

**Comment by teresajohnson** [comment] 2024-01-30 15:42
I think the missed optimization remark I pointed to should cover this case, but yes, if not we should improve that. But I know I have seen those before.

**Comment by nickdesaulniers** [comment] 2024-01-30 17:19
> I don’t recall if ‘-Rpass-missed=inline’ handles that case, but maybe that would work. If not maybe we can extend it to report those cases by adding a few checks when using a profile?

+1

Or create another optimization remark for the more specific use case described.

---

Could you do the opposite, too? "This function defined in a header is cold, perhaps a candidate for hiding the definition in a TU."  For instance, I frequently have a sinking feeling that most functions defined in headers are dead or cold, and pessimize compile times to lex+parse+sema+ir codegen only to be dead code eliminated.

I guess there's potential for developers to be unable to reach a fixed point though.  Consider foo() and bar() which call baz().  foo()'s callsite of baz() is hot/common, bar()'s callsite of baz() is not.  Should baz() go in a header or not?  Does the compiler give conflicting advice when foo() and bar() are in different TUs?

---

> This is a use case we encountered in embedded applications where hot functions are often defined in a source file (rather than a header) and thus cannot be inlined across translation units.

Even if the definition is available for inlining or constant sinking+hoisting, the inline cost model might still prevent inline substitution from occurring.  In that case, global dead code elimination will not clean up the definition.  For `static inline` functions defined in a header file, this can lead to code bloat (since each TU will have its own copy, and there's no ODR in C, so the linker MUST NOT dedupe the definitions), which may be less tolerable for embedded applications in particular.  The always_inline function attribute can help (and flatten fn attr, though that's not my favorite function attribute; it's the nuclear option).  In my experience, turning on sanitizers or code coverage (or anything that involves instrumenting the code) tends to pessimize the inline cost model due to increased size of the callee.

**Comment by david-xl** [comment] 2024-01-30 18:15
> I think the missed optimization remark I pointed to should cover this case, but yes, if not we should improve that. But I know I have seen those before.

If we want to limit the diagnostics to only cross-module inlines that actually happens, perhaps add an option to emit only successfully cross module inlines with -Rpass=inline in LTO mode. Such messages can be used to tell user what is missing without LTO.

**Comment by aeubanks** [comment] 2024-01-30 22:39
https://github.com/llvm/llvm-project/blob/bb770f0df53eee91a803b2829808d82279f7b577/llvm/lib/Transforms/IPO/Inliner.cpp#L265 already emits this exact missed optimization, and you can filter remarks for hot functions only with [this](https://github.com/llvm/llvm-project/blob/bb770f0df53eee91a803b2829808d82279f7b577/llvm/lib/IR/LLVMRemarkStreamer.cpp#L99), although I'm unsure if there's clang plumbing for the hotness filter

**Comment by petrhosek** [comment] 2024-01-31 07:11
> https://github.com/llvm/llvm-project/blob/bb770f0df53eee91a803b2829808d82279f7b577/llvm/lib/Transforms/IPO/Inliner.cpp#L265
> 
> already emits this exact missed optimization, and you can filter remarks for hot functions only with [this](https://github.com/llvm/llvm-project/blob/bb770f0df53eee91a803b2829808d82279f7b577/llvm/lib/IR/LLVMRemarkStreamer.cpp#L99), although I'm unsure if there's clang plumbing for the hotness filter

Looks like there is: https://clang.llvm.org/docs/UsersManual.html#cmdoption-fdiagnostics-hotness-threshold

**Comment by aeubanks** [comment] 2024-01-31 22:47
Or rather, the flag right below: `-fdiagnostics-hotness-threshold`

Can we close this?

**Comment by aeubanks** [comment] 2024-02-01 22:05
Closing since we seem to already have all the necessary infra. Please reopen if there's anything missing.

**Closed by aeubanks** 2024-02-01 22:05 UTC
Labels: enhancement

**Comment by petrhosek** [comment] 2024-02-01 22:29
I'd like to explore @david-xl's suggestion, but `-Rpass-missed=inline` with `-fdiagnostics-show-hotness` is sufficient for my needs right now, thanks!
