### ISSUE TITLE
Regression lowering global as inline asm memory operand for RISCV64

### ISSUE THREAD

**Issue by jacobly0** [llvm/llvm-project#64656] opened 2023-08-13 09:18 UTC
```llvm
target triple = "riscv64"

@g = global i32 0

define void @f() {
  call void asm "sw zero, $0", "=*m"(ptr elementtype(i32) @g)
  ret void
}
```
```
$ llc-16 -version # 7cbf1a2591520c2491aa35339f227775f4d3adf6
LLVM (http://llvm.org/):
  LLVM version 16.0.6
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver4
$ llc-16 repro.ll -o -
...
	lui	a0, %hi(g)
	addi	a0, a0, %lo(g)
	#APP
	sw	zero, 0(a0)
	#NO_APP
	ret
...
$ llc-17 -version # 8f4dd44097c9ae25dd203d5ac87f3b48f854bba8
LLVM (http://llvm.org/):
  LLVM version 17.0.0-rc2
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver4
$ llc-17 repro.ll -o -
...
	lui	a0, %hi(g)
	#APP
error: invalid operand in inline asm: 'sw zero, $0'
<inline asm>:1:11: error: unknown operand
        sw zero, 
                 ^
	#NO_APP
	ret
...
```

**Comment by wangpc-pp** [comment] 2023-08-14 06:35
Caused by https://reviews.llvm.org/D146245:
```diff
--- a/llvm/lib/Target/RISCV/RISCVAsmPrinter.cpp
+++ b/llvm/lib/Target/RISCV/RISCVAsmPrinter.cpp
@@ -237,11 +237,11 @@ bool RISCVAsmPrinter::PrintAsmMemoryOperand(const MachineInstr *MI,
   // RISCVDAGToDAGISel::SelectInlineAsmMemoryOperand).
   if (!AddrReg.isReg())
     return true;
-  if (!DispImm.isImm())
-    return true;

-  OS << DispImm.getImm() << "("
-     << RISCVInstPrinter::getRegisterName(AddrReg.getReg()) << ")";
+  uint64_t Offset = DispImm.isImm() ? DispImm.getImm() : 0;
+
+  OS << Offset << "(" << RISCVInstPrinter::getRegisterName(AddrReg.getReg())
+     << ")";
   return false;
 }
```

**Comment by tru** [comment] 2023-08-21 08:17
Is this something that needs to be fixed for 17.x? @asb ?

**Comment by wangpc-pp** [comment] 2023-08-21 08:20
> Is this something that needs to be fixed for 17.x? @asb ?

Should be fixed in https://reviews.llvm.org/D157839, but I need new approval.

**Comment by tru** [comment] 2023-08-21 08:26
@asb @topperc can we get an approval on this in phabricator?

**Comment by wangpc-pp** [comment] 2023-08-21 11:02
/cherry-pick a3b11ce78680ef39e4dfbc72085ae3e1814e3cba dc60003ec8b2faf595b528a39f64b697a589da06

**Closed** 2023-08-22 05:49 UTC
Labels: backend:RISC-V, release:backport
