### ISSUE TITLE
[avr] Wrong code: 32-bit variable (unsigned long) treated as 16-bit value.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58882] opened 2022-11-08 20:37 UTC
The following code is supplying a 32-bit value to inline asm by means of a local register variable in R20:
```c++
static __inline__ __attribute__((__always_inline__))
void sysc (unsigned long _v1_)
{
    register unsigned long r20 __asm ("20") = _v1_;
    __asm __volatile__ (";; %%0 = %0" :: "r" (r20));
}

void func (void)
{
  sysc (0x12345678);
}
```
When I compile this with `-target avr -mmcu=atmega8 -Os -save-temps` then the following assembly is generated:
```asm
func:
	ldi	r20, 120
	ldi	r21, 86
	;APP
	;; %0 = r20
	;NO_APP
	ret
```
which means that the high part `r22` and `r23` have been ignored and contain wrong values.

Similar happens if `r20` is of type `float` instead of `unsigned long`.

**Comment by aykevl** [comment] 2022-12-28 03:20
This looks correct. The `r` constraint is for a single 8-bit register, and in this case it sets `r20` to the correct value. I think the compiler could have left out `ldi r21, 86` and still be correct.

For more information, see: https://www.nongnu.org/avr-libc/user-manual/inline_asm.html

**Comment by aykevl** [comment] 2022-12-28 03:27
Also see: #55159

**Comment by sprintersb** [comment] 2023-01-03 17:50
> This looks correct. The `r` constraint is for a single 8-bit register,

No. "r" stands for a register class.  And as the register is C type `long`, it's restricted to 4 consecutive GPRs starting at an even register due to avr-gcc ABI. Hence we have a 32-bit register (in GCC speek of `SImode`), that's passed as `0x12345678` from the caller.  Hence, when the inline asm starts, the compiler must have initialized it with:
```
%A0 = 0x78
%B0 = 0x56
%C0 = 0x34
%D0 = 0x12
```
For that AVR-LibC example we have that for the specific example given there, `value` is an 8-bit type `uint8_t` in class `"r"`, thus only one GPR is allocated.

For a more elaborate 32-bit example, cf. e.g. `avr/pgmspace.h` from AVR-LibC and `pgm_read_dword` or `pgm_read_float`. An easy sub-case is `__LPM_dword_enhanced__` (`lpm *,z+` is available):
```c++
#define __LPM_dword_enhanced__(addr)        \
(__extension__({                            \
    uint16_t __addr16 = (uint16_t)(addr);   \
    uint32_t __result;                      \
    __asm__ __volatile__                    \
    (                                       \
        "lpm %A0, Z+"   "\n\t"              \
        "lpm %B0, Z+"   "\n\t"              \
        "lpm %C0, Z+"   "\n\t"              \
        "lpm %D0, Z"    "\n\t"              \
        : "=r" (__result), "=z" (__addr16)  \
        : "1" (__addr16)                    \
    );                                      \
    __result;                               \
}))
```
Re issue #55159: Are you saying that only 8-bit and 16-bit types will be supported and nothing else; in particular that `long`, `float` and `long long`, `__int24` won't be supported by clang`?

It's also completely fine for avr-gcc to pass non-scalar types, and types whose size is not a power of 2:
```c++
typedef struct
{
    unsigned char r, g, b;
} rgb_t;

rgb_t next (rgb_t rgb)
{
    __asm ("inc %A0 $ inc %B0 $ inc %C0 ; size = %1"
           : "+r" (rgb) : "n" (sizeof (rgb)));
    return rgb;
}
```

```none
> avr-gcc foo.c -c -Os && avr-objdump -d foo.o
```

```asm
00000000 <next>:
   0:	63 95       	inc	r22
   2:	73 95       	inc	r23
   4:	83 95       	inc	r24
   6:	08 95       	ret
```

with assembly as of `-save-temps`:
```asm
next:
/* #APP */
	inc r22 $ inc r23 $ inc r24 ; size = 3
/* #NOAPP */
	ret
```

**Comment by aykevl** [comment] 2023-01-11 22:01
> For a more elaborate 32-bit example, cf. e.g. `avr/pgmspace.h` from AVR-LibC and `pgm_read_dword` or `pgm_read_float`. An easy sub-case is `__LPM_dword_enhanced__` (`lpm *,z+` is available):

Hmm, ok. So avr-libc uses this feature.
I tried with ARM but apparently both GCC and Clang support something like this: https://godbolt.org/z/5edfva9Wh. I was hoping I could use it as an example, but apparently not.



> Re issue #55159: Are you saying that only 8-bit and 16-bit types will be supported and nothing else; in particular that `long`, `float` and `long long`, `__int24` won't be supported by clang`?

Right now they aren't supported in inline assembly (as you have found out). But most of those work just fine in C. Support for larger-than-16bit values is a feature that would be nice to have but I haven't looked much into inline assembly and whether a feature like this is feasible.

**Comment by sprintersb** [comment] 2023-01-12 10:31
> Hmm, ok. So avr-libc uses this feature.

avr-gcc itself uses this feature all over the place, cf. for example [avr.md](https://gcc.gnu.org/git?p=gcc.git;a=blob;f=gcc/config/avr/avr.md;h=e581e959e5747c812d9eb348407b4b6ac1223743;hb=f54e3b3ba01ced7ecda3caed51b42f707d489c77#l1780):
```
(define_insn_and_split "*addsi3_zero_extend_split"
       [(set (match_operand:SI 0 "register_operand"                         "=r")
             (plus:SI (zero_extend:SI (match_operand:QI 1 "register_operand" "r"))
                      (match_operand:SI 2 "register_operand"                 "0")))]
...
```
Operands 0 and 2 are of SImode, which is some 32-bit integer.  Constraints of operands 0, 1 and 2 are `"=r"`,  `"r"` and  `"0"` respectively, which you would write the exact same way in linline assembly where operand 0 is `[unsigned] long long` and operand 1 is `[unsigned] char`. Constraint `r` is a machine independent register constraint in GCC which is any general purpose register where all parts fit in that register class.  There might be additional rules how values fit in registers, for example on AVR, values that have more than 1 byte must start in even register.

> I tried with ARM but apparently both GCC and Clang support something like this

Problem is that asm print modifiers `%A` ... `%D` are AVR-specific, so ARM compile will throw an error at you.  The `long long` argument is perfectly fine though. For the high part, use print modifier `%H` for ARM:
```c++
long long inlineasm (long long x, long long y)
{
    __asm__  ("add %0, %1" "\n\t"
              "add %H0, %H1"
              : "+r"(x) : "r"(y));
    return x;
}
```
Both GCC and Clang will generate at `-O2`:
```
inlineasm:
        add r0, r2
        add r1, r3
        bx      lr
```

With avr-gcc we have the additional problem that we cannot go higher that `%D` with print modifiers, so we have to use `%r` which will print a plain register number without register-prefix. avr-gcc allows simple arithmetic on register numbers. For example, the high byte of a l`long long` or `long double` in operand 0 can be accessed as `%r0+7`.

This means code like `LDI 16+1,16` is completely fine for the GNU assember.  As the 1st operand of `LDI` is always a register, there is no ambiguity that `16+1` in the 1st operand means `r17`.

**Comment by aykevl** [comment] 2023-01-12 13:32
> avr-gcc itself uses this feature all over the place, cf. for example [avr.md](https://gcc.gnu.org/git?p=gcc.git;a=blob;f=gcc/config/avr/avr.md;h=e581e959e5747c812d9eb348407b4b6ac1223743;hb=f54e3b3ba01ced7ecda3caed51b42f707d489c77#l1780):
> 
> ```
> (define_insn_and_split "*addsi3_zero_extend_split"
>        [(set (match_operand:SI 0 "register_operand"                         "=r")
>              (plus:SI (zero_extend:SI (match_operand:QI 1 "register_operand" "r"))
>                       (match_operand:SI 2 "register_operand"                 "0")))]
> ...
> ```

Sure, but avr-gcc is not Clang. And LLVM works very different from GCC. Unlike GCC, LLVM has an integrated assembler so it skips the assembly generation step entirely (it emits its in-memory representation of instructions directly as machine code). So avr-gcc might use a similar syntax to inline assembly in its own implementation but that's irrelevant to LLVM.

> Problem is that asm print modifiers `%A` ... `%D` are AVR-specific, so ARM compiler will throw an error at you.

Right, I see. I was assuming this was a generic feature.

Anyway, closing this as a duplicate of #55159.

**Closed by aykevl** 2023-01-12 13:32 UTC
Labels: backend:AVR, miscompilation

**Comment by sprintersb** [comment] 2023-01-13 19:18
> avr-gcc is not Clang

Of course.  What I was trying to get across is the semantics of inline assembly, in particular semantics of register constraints like `r`, `a`, `d`, `l`, `x`, `y`, `z` and `w`.

Some of the comments indicate that there is misunderstanding about what they mean, and if the clang maintainers don't unterstand constraints, inline asm will be a frustrating business, both for useres and maintainers.

Both existing prjects and also AVR-LibC are making use of inline asm and its intricate semantics.  You can of course start your own Libc with their own semantics of inline asm, bit IMHO it's much easier to use existing AVR-LibC.
