### ISSUE TITLE
Unable to build www-client/firefox-100.0 on Gentoo with Clang/LLVM

### ISSUE THREAD

**Issue by pog5** [llvm/llvm-project#55400] opened 2022-05-12 05:09 UTC
Build Log:
```194:35.02 LLVM ERROR: Cannot select: intrinsic %llvm.x86.aesni.aesenc
194:35.02 PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
194:35.02 Stack dump:
194:35.02 0.    Running pass 'Function Pass Manager' on module '/var/tmp/portage/www-client/firefox-100.0/work/firefox_build/x86_64-unknown-linux-gnu/release/libgkrust.a(wgpu_hal-c3c9d5de806c2325.wgpu_hal.8b04d973-cgu.0.rcgu.o at 24369424)'.
194:35.02 1.    Running pass 'X86 DAG->DAG Instruction Selection' on function '@"_ZN9hashbrown3raw5inner17RawTable$LT$T$GT$14reserve_rehash17h827623bee5367f13E"'
194:35.24  #0 0x00007f1b4dcf2684 (/usr/lib/llvm/14/lib64/libLLVM-14.so+0xf1e684)
194:35.24  #1 0x00007f1b4dcef96b (/usr/lib/llvm/14/lib64/libLLVM-14.so+0xf1b96b)
194:35.24  #2 0x00007f1b4c9dfed0 (/lib64/libc.so.6+0x3ced0)
194:35.24  #3 0x00007f1b4ca29bac (/lib64/libc.so.6+0x86bac)
194:35.24  #4 0x00007f1b4c9dfe32 gsignal (/lib64/libc.so.6+0x3ce32)
194:35.24  #5 0x00007f1b4c9cb45b abort (/lib64/libc.so.6+0x2845b)
194:35.24  #6 0x00007f1b4dbfec40 llvm::report_fatal_error(llvm::Twine const&, bool) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0xe2ac40)
194:35.24  #7 0x00007f1b4e6acd26 llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x18d8d26)
194:35.24  #8 0x00007f1b4e6b067b llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x18dc67b)
194:35.24  #9 0x00007f1b4ff13d07 (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x313fd07)
194:35.24 #10 0x00007f1b4e6ab016 llvm::SelectionDAGISel::DoInstructionSelection() (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x18d7016)
194:35.25 #11 0x00007f1b4e6b4940 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x18e0940)
194:35.25 #12 0x00007f1b4e6b7cd4 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x18e3cd4)
194:35.25 #13 0x00007f1b4e6baca7 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x18e6ca7)
194:35.25 #14 0x00007f1b4ff1bba0 (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x3147ba0)
194:35.25 #15 0x00007f1b4e140acc llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x136cacc)
194:35.25 #16 0x00007f1b4de68226 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x1094226)
194:35.25 #17 0x00007f1b4de6853c llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x109453c)
194:35.25 #18 0x00007f1b4de69a03 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x1095a03)
194:35.25 #19 0x00007f1b4f7686d4 (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x29946d4)
194:35.25 #20 0x00007f1b4f76a050 llvm::lto::thinBackend(llvm::lto::Config const&, unsigned int, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream> > > (unsigned int)>, llvm::Module&, llvm::ModuleSummaryIndex const&, llvm::StringMap<std::unordered_set<unsigned long, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >, llvm::MallocAllocator> const&, llvm::DenseMap<unsigned long, llvm::GlobalValueSummary*, llvm::DenseMapInfo<unsigned long, void>, llvm::detail::DenseMapPair<unsigned long, llvm::GlobalValueSummary*> > const&, llvm::MapVector<llvm::StringRef, llvm::BitcodeModule, llvm::DenseMap<llvm::StringRef, unsigned int, llvm::DenseMapInfo<llvm::StringRef, void>, llvm::detail::DenseMapPair<llvm::StringRef, unsigned int> >, std::vector<std::pair<llvm::StringRef, llvm::BitcodeModule>, std::allocator<std::pair<llvm::StringRef, llvm::BitcodeModule> > > >*, std::vector<unsigned char, std::allocator<unsigned char> > const&) (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x2996050)
194:35.25 #21 0x00007f1b4f74fdc4 (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x297bdc4)
194:35.25 #22 0x00007f1b4f75398f (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x297f98f)
194:35.25 #23 0x00007f1b4e25bbbf (/usr/lib/llvm/14/lib64/libLLVM-14.so+0x1487bbf)
194:35.25 #24 0x00007f1b4dc77f62 (/usr/lib/llvm/14/lib64/libLLVM-14.so+0xea3f62)
194:35.25 #25 0x00007f1b4ca27faa (/lib64/libc.so.6+0x84faa)
194:35.25 #26 0x00007f1b4caa795c (/lib64/libc.so.6+0x10495c)
194:35.30 clang-14: error: unable to execute command: Aborted
194:35.30 clang-14: error: linker command failed due to signal (use -v to see invocation)
194:35.31 gmake[4]: *** [/var/tmp/portage/www-client/firefox-100.0/work/firefox-100.0/config/rules.mk:531: libxul.so] Error 254
194:35.31 gmake[4]: Leaving directory '/var/tmp/portage/www-client/firefox-100.0/work/firefox_build/toolkit/library/build'
194:35.31 gmake[3]: *** [/var/tmp/portage/www-client/firefox-100.0/work/firefox-100.0/config/recurse.mk:72: toolkit/library/build/target] Error 2
194:35.31 gmake[3]: Leaving directory '/var/tmp/portage/www-client/firefox-100.0/work/firefox_build'
194:35.31 gmake[2]: *** [/var/tmp/portage/www-client/firefox-100.0/work/firefox-100.0/config/recurse.mk:34: compile] Error 2
194:35.31 gmake[2]: Leaving directory '/var/tmp/portage/www-client/firefox-100.0/work/firefox_build'
194:35.31 gmake[1]: *** [/var/tmp/portage/www-client/firefox-100.0/work/firefox-100.0/config/rules.mk:352: default] Error 2
194:35.31 gmake[1]: Leaving directory '/var/tmp/portage/www-client/firefox-100.0/work/firefox_build'
194:35.31 gmake: *** [client.mk:63: build] Error 2
194:35.31 249 compiler warnings present.
 * ERROR: www-client/firefox-100.0::gentoo failed (compile phase):
 *   Failed to run './mach build --verbose'
 *
 * Call stack:
 *     ebuild.sh, line  127:  Called src_compile
 *   environment, line 5266:  Called virtx './mach' 'build' '--verbose'
 *   environment, line 6579:  Called die
 * The specific snippet of code:
 *       [[ ${retval} -ne 0 ]] && die "Failed to run '$@'";
 *
 * If you need support, post the output of `emerge --info '=www-client/firefox-100.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=www-client/firefox-100.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/www-client/firefox-100.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-client/firefox-100.0/temp/environment'.
 * Working directory: '/var/tmp/portage/www-client/firefox-100.0/work/firefox-100.0'
 * S: '/var/tmp/portage/www-client/firefox-100.0/work/firefox-100.0'

>>> Failed to emerge www-client/firefox-100.0,
```

Output of emerge --info`:
```Portage 3.0.30 (python 3.9.12-final-0, default/linux/amd64/17.1/desktop, gcc-12.1.0, glibc-2.35-r4, 5.17.6-gentoo x86_64)
=================================================================
System uname: Linux-5.17.6-gentoo-x86_64-Intel-R-_Core-TM-_i3-4130_CPU_@_3.40GHz-with-glibc2.35
KiB Mem:     8078208 total,   2752428 free
KiB Swap:    4607996 total,   4313256 free
Timestamp of repository gentoo: Tue, 10 May 2022 17:00:01 +0000
Head commit of repository gentoo: b9815d9def17a7032dfb13bd20d19b1983ff5039
Timestamp of repository guru: Tue, 10 May 2022 13:33:03 +0000
Head commit of repository guru: 00b1cff87dc9da7ece5ba4cb85936a70c7496c29

sh bash 5.1_p16
ld GNU ld (Gentoo 2.38 p4) 2.38
app-misc/pax-utils:        1.3.4::gentoo
app-shells/bash:           5.1_p16::gentoo
dev-java/java-config:      2.3.1::gentoo
dev-lang/perl:             5.34.1-r3::gentoo
dev-lang/python:           3.9.12::gentoo, 3.10.4::gentoo
dev-lang/rust:             1.60.0::gentoo
dev-util/cmake:            3.23.1::gentoo
dev-util/meson:            0.61.4-r2::gentoo
sys-apps/baselayout:       2.8::gentoo
sys-apps/openrc:           0.44.10::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-devel/autoconf:        2.13-r1::gentoo, 2.71-r1::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.38-r2::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           14.0.3::gentoo
sys-devel/gcc:             12.1.0::gentoo
sys-devel/gcc-config:      2.5-r1::gentoo
sys-devel/libtool:         2.4.7::gentoo
sys-devel/lld:             14.0.3::gentoo
sys-devel/llvm:            14.0.3::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  5.17-r1::gentoo (virtual/os-headers)
sys-libs/glibc:            2.35-r4::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts:

guru
    location: /var/db/repos/guru
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/guru.git
    masters: gentoo

ACCEPT_KEYWORDS="amd64 ~*"
ACCEPT_LICENSE="@FREE"
AR="llvm-ar"
CBUILD="x86_64-pc-linux-gnu"
CC="clang"
CFLAGS="-mtune=native -march=native -O3 -pipe -fomit-frame-pointer -flto=thin"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/terminfo"
CXX="clang++"
CXXFLAGS="-mtune=native -march=native -O3 -pipe -fomit-frame-pointer -flto=thin"
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--read-news=y --autounmask=y --with-bdeps=y --ask --load-average=4"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-mtune=native -march=native -O3 -pipe -fomit-frame-pointer -flto=thin"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news nodoc parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS=""
GENTOO_MIRRORS="rsync://mirror.leaseweb.com/gentoo/ http://mirror.leaseweb.com/gentoo/ rsync://linux.rz.ruhr-uni-bochum.de/gentoo rsync://linux.rz.ruhr-uni-bochum.de/gentoo https://mirror.netcologne.de/gentoo/ http://mirror.netcologne.de/gentoo/ http://mirrors.xservers.ro/gentoo/ http://ftp.romnet.org/gentoo/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-O2 -Wl,--as-needed"
MAKEOPTS="-j5 -l4"
NM="llvm-nm"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
RANLIB="llvm-ranlib"
RUSTFLAGS="-C opt-level=3 -C target-cpu=native"
SHELL="/bin/bash"
USE="X a52 aac acl acpi alsa amd64 branding cdda clang cli dbus dri dts elogind encode fortran gdbm gif gpm gtk gui iconv icu libglvnd libnotify libtirpc lto mad mp3 mp4 mpeg multilib ncurses nls nptl openmp pam pango pcre pgo pipewire png policykit pulseaudio readline savedconfig spell split-usr ssl startup-notification svg truetype udev udisks upower usb wxwidgets x264 xattr xcb xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2020" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LLVM_TARGETS="X86" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_9" RUBY_TARGETS="ruby26 ruby27" USERLAND="GNU" VIDEO_CARDS="nouveau intel" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, ARFLAGS, AS, ASFLAGS, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXXFILT, ELFEDIT, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LEX, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS,
PORTAGE_RSYNC_EXTRA_OPTS, READELF, SIZE, STRINGS, STRIP, YACC, YFLAGS

```

**Comment by topperc** [comment] 2022-05-12 05:25
Is this a duplicate of #54055

**Comment by pog5** [comment] 2022-05-12 05:42
> Is this a duplicate of #54055

 I'm currently compiling Firefox without Profile Guided Optimization (PGO), if it still fails, I'll try to compile it without Link Time Optimization (LTO), If it STILL fails, I'll try to compile it without both.
 I'll update you if it finishes successfully.

**Comment by pog5** [comment] 2022-05-12 07:17
Firefox Failed  to emerge with LTO Enabled. Disabling LTO and reenabling PGO to see if it will still compile.

**Closed** 2022-05-12 07:19 UTC
Labels: llvm:crash, llvm:optimizations
