### ISSUE TITLE
wrong code at -O1 and above on x86_64-linux-gnu (affect versions from 10.0.0 to trunk)

### ISSUE THREAD

**Issue by haoxintu** [llvm/llvm-project#53979] opened 2022-02-22 04:49 UTC
Hi, the following valid code is miscompiled by llvm-10.0.0 above versions. I am not sure whether there is a dup or not.

```
$cat s.c
#include <stdint.h>
#include <stdio.h>
struct {
  int8_t a;
} b;
union {
  int32_t a;
  int16_t c;
} d;
int32_t e;

int16_t *f = &d.c;
int32_t *volatile g = &d.a;
uint32_t h() {
  b.a = 0;
  for (; b.a >= 0; b.a = b.a - 1) {
    *f = 0;
    *g = 1;
  }
  return e;
}
int main() {
  h();
  printf("%d\n", d.a);
}

$clang -O0 s.c ;./a.out
1
$clang -O1 s.c ; ./a.out (same as -O2 to -Os) 
0

$clang -v
clang version 15.0.0 (https://github.com/llvm/llvm-project 294072e10b9949323bf20695085723158f7c873c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/haoxin/haoxin-data/compilers/llvm-project/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

Please check how this issue affects other versions here: https://godbolt.org/z/76foMvd5x

Thanks,
Haoxin

**Comment by phoebewang** [comment] 2022-02-22 06:36
It's not a bug to backend. `d` is a union. So `f` and `g` are pointed to the same address. I'm not sure if the front end need to keep the order of the store. https://godbolt.org/z/xEWae45da

**Comment by nikic** [comment] 2022-02-22 09:12
I believe this is a strict aliasing violation, and as such UB. I don't think the special rules for unions apply when you take pointers to union members (as that would completely break strict aliasing as a concept).

**Comment by fhahn** [comment] 2022-04-11 09:41
I agree that this looks like a strict aliasing violation and that the input is UB, so Clang/LLVM is allowed to re-order the stores.

And I think if `volatile`should come into play, the variable would need to be declared as follows `volatile int32_t *volatile g = &d.a;`

@haoxintu I am closing this as working as expected, but please feel free to re-open the issue with additional details if you believe this is incorrect.

**Closed by fhahn** 2022-04-11 09:41 UTC
Labels: clang:frontend
