### ISSUE TITLE
[Clang] Possible bug with labels at the end of compound statements in C

### ISSUE THREAD

**Issue by OCHyams** [llvm/llvm-project#58632] opened 2022-10-26 15:08 UTC
With this test case `test.c`:
```
void fun(void) {
label:
}
```

Before [D133887](https://reviews.llvm.org/D133887) we got an error:
```
$ clang label.c -c -std=c17
label.c:3:1: error: expected statement
}
^
1 error generated.
```

With [D133887](https://reviews.llvm.org/D133887) we just get a warning:
```
$ clang label.c -c -std=c17
label.c:3:1: warning: label at end of compound statement is a C2x extension [-Wc2x-extensions]
}
^
1 warning generated.
```

I'm not very familiar with the C standard but it seemed suspicious that this error has become a warning even though `-std=c17` is specified in the example. Is this a bug?

Also see on [compiler explorer](https://godbolt.org/z/oc54T61sz) with clang-15 vs trunk.

cc @cor3ntin and @Izaron from [D133887](https://reviews.llvm.org/D133887).

**Comment by Izaron** [comment] 2022-10-26 15:20
Hi! This isn't a bug, it's a C++2b (tentatively C++23) and C2x (tentatively C23) feature: https://github.com/cplusplus/papers/issues/1006

> even though -std=c17 is specified in the example
Clang backports most of the features of more recent standards to all possible standards (with warnings) if it doesn't break important things.

If you want to forbid backporting features of the more recent standard, you can use `-Werror=c2x-extensions` flag

**Comment by AaronBallman** [comment] 2022-10-26 15:49
This behavior is by design, closing as not a bug.

**Closed by AaronBallman** 2022-10-26 15:49 UTC
Labels: invalid, c, clang:frontend

**Comment by OCHyams** [comment] 2022-10-26 16:07
Ok, thanks for the info!

**Comment by AaronBallman** [comment] 2022-10-26 16:18
Btw, the reference to the C paper for this feature is: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2508.pdf
