### ISSUE TITLE
clang-cl compat with MSVC's C2488 is too eager

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#55362] opened 2022-05-10 01:30 UTC
The following code compiles fines with MSVC:
```c++
struct Foo {
    //__declspec(naked) void func1() {} // C2488
    void func2();
};

__declspec(naked) void Foo::func2() {} // NOT C2488
```
[godbolt](https://godbolt.org/z/ej35WzdGP)

But as of 5b164a3a9b8c52e45641203de9c4c73fa7402570, is rejected by clang-cl.

Cc: @AaronBallman

**Comment by AaronBallman** [comment] 2022-05-10 11:26
Huh, thanks for letting me know! I'm not convinced that isn't a mistake in cl. From Microsoft's documentation (https://docs.microsoft.com/en-us/cpp/cpp/naked-cpp?view=msvc-170):

> The compiler issues an error if the naked attribute is applied to anything other than the definition of a non-member method.

That is the definition of a non-member function, so it seems like it should be issuing a diagnostic. I've filed https://developercommunity.visualstudio.com/t/__declspecnaked-allowed-on-out-of-line/10036031 with Microsoft to see what they have to say.

**Comment by glandium** [comment] 2022-05-10 20:41
FWIW, the code this was found on was built with MSVC from 1999 to 2018.

**Comment by CaseyCarter** [comment] 2023-01-19 22:33
> That is the definition of a non-member function, so it seems like it should be issuing a diagnostic. I've filed https://developercommunity.visualstudio.com/t/__declspecnaked-allowed-on-out-of-line/10036031 with Microsoft to see what they have to say.

FWIW, per MSVC's internal bug database this is definitely an "accepts-invalid" CL bug and not a clang-cl bug. I suggest you close this issue.

**Comment by AaronBallman** [comment] 2023-01-20 12:52
Thank you for the details @CaseyCarter! Closing as not a bug.

**Closed by AaronBallman** 2023-01-20 12:52 UTC
Labels: invalid, clang-cl
