### ISSUE TITLE
[clang-tidy] add_new_check.py creates a faulty FixItHint

### ISSUE THREAD

**Issue by RedPenguin100** [llvm/llvm-project#61416] opened 2023-03-14 21:06 UTC
When the `add_new_check.py` script is invoked to create a new vanilla custom clang-tidy check, the following code is emitted inside the check override function:

```cpp
  diag(MatchedDecl->getLocation(), "function %0 is insufficiently awesome")
      << MatchedDecl;
  diag(MatchedDecl->getLocation(), "insert 'awesome'", DiagnosticIDs::Note)
      << FixItHint::CreateInsertion(MatchedDecl->getLocation(), "awesome_");
```

Running clang tidy with `--fix` won't fix the function name.
Changing the code to the following will work:

```cpp
  diag(MatchedDecl->getLocation(), "function %0 is insufficiently awesome")
      << MatchedDecl
      << FixItHint::CreateInsertion(MatchedDecl->getLocation(), "awesome_");
  diag(MatchedDecl->getLocation(), "insert 'awesome'", DiagnosticIDs::Note);
```

I'm not sure why but I think the reason for this is that the FixItHint comes after a `DiagnosticsIDs::Note` which possibly prevents fixes afterwards. Also removing the last line in the second code example altogether works, but I'm not sure how the mainteners want this to look like.

I hope I didn't break too many rules, this is my first time posting, was trying to understand why this isn't working for way too long

**Comment by PiotrZSL** [comment] 2023-03-25 15:49
You missing: --fix-notes

**Comment by PiotrZSL** [comment] 2023-03-25 15:58
Looks like this were broken by:
commit f2879d8a4877eafcdb12c852030746d175f8abbd
Author: Haojian Wu <hokein@google.com>
Date:   Wed Apr 17 12:53:59 2019 +0000

    [clang-tidy] Add fix descriptions to clang-tidy checks.

**Comment by PiotrZSL** [comment] 2023-03-25 16:04
One way to fix this is here: https://reviews.llvm.org/D146875

**Comment by PiotrZSL** [comment] 2023-03-26 15:56
Duplicate of https://github.com/llvm/llvm-project/issues/50400

**Closed by PiotrZSL** 2023-03-26 15:56 UTC
Labels: duplicate, clang-tidy
