### ISSUE TITLE
[clang][c++] Compile error in the weak alias 

### ISSUE THREAD

**Issue by ipasichnyk** [llvm/llvm-project#66790] opened 2023-09-19 16:39 UTC
Want to bring attention to the similar https://github.com/llvm/llvm-project/issues/53916
clang v18 still fails on

```
#include <iostream>
extern "C" {
  static const char* do_something_original (void)
  {
    return NULL;
  }
  const char* do_something (void) __attribute__((weak, alias("do_something_original")));
}

```
with an error

```
aliasing.cpp:8:56: error: alias must point to a defined variable or function
  const char* do_something (void) __attribute__((weak, alias("do_something_original")));
```

**Comment by MaskRay** [comment] 2023-11-05 21:40
Duplicate of #18149 and it works as intended.

**Closed by MaskRay** 2023-11-05 21:40 UTC
Labels: duplicate, clang:frontend, extension:gnu
