### ISSUE TITLE
Clang Python marks assert as case statement

### ISSUE THREAD

**Issue by Rubyfi** [llvm/llvm-project#109787] opened 2024-09-24 12:19 UTC
Hi,
I'm trying to parse a set of swtich-case statements using the Python clang module and ran into some weird behavior.
Given something like this:
```
switch(Enum)
{
   case Enum::Value1:
      assert(false);
      break;
   case Enum::Value2:
      ....
      break;
....
}
```
Clang returns the assert statement's cursor kind as `CursorKind.CASE_STMT`.
However, this only seems to happen when an `assert` is the first statement in a case.
Any other statements parse like expected.
When another expression is placed first in the `case`, the cursor of `assert` is `CursorKind.COMPOUND_STMT` instead:
```
switch(Enum)
{
   case Enum::Value1:
      ;
      assert(false);
      break;
   case Enum::Value2:
      ....
      break;
....
}
```

Am I misinterpreting the functionality of the underlying cursor; i.e. that it is supposed to help identifying the syntactical meaning of the according token; or is this a bug?

**Comment by Rubyfi** [comment] 2024-09-24 13:43
Apologies, I might have posted this in the wrong repo.
I'm using the libclang module to use the parser.
I'll check if updating this wrapper module fixes the issue and get back to you.

**Comment by efriedma-quic** [comment] 2024-12-17 20:39
The way the clang AST is structured follows the C grammar: the first statement following a case is a child of the case.  The python bindings reflect this: depending on how you structure your query, you'll find the case statement itself instead of its child.  So I'm going to close this as working as intended, I think.

This is something we've discussed modifying, because it's not particularly useful to structure the AST this way, but nobody has really dug into it deeply.

**Closed by efriedma-quic** 2024-12-17 20:39 UTC
Labels: clang:as-a-library
