### ISSUE TITLE
Clang-format with GNU style splits up three-way comparison operator

### ISSUE THREAD

**Issue by Halalaluyafail3** [llvm/llvm-project#104655] opened 2024-08-17 00:52 UTC
Clang-format with GNU style doesn't recognize three-way comparison operators and will split them up. For example:
```cpp
1<=>2;
```
Clang-format with GNU style will format this to:
```cpp
1 <= > 2;
```
This is ill-formed and shouldn't be generated.

**Comment by rymiel** [comment] 2024-08-17 01:45
Same root cause as https://github.com/llvm/llvm-project/issues/58435

The GNU option sets the C++ standard when parsing to C++03, where three-way comparison operators didn't exist; therefore the clang parser doesn't see them as such.

This is fixed by adding `Standard: Latest` in your config

**Comment by Halalaluyafail3** [comment] 2024-08-17 02:31
Ok that does solve the problem, is there any reason to not make this the default behavior (or at least, not splitting up <=>)?

**Closed** 2024-08-18 19:02 UTC
Labels: clang-format, invalid-code-generation
