### ISSUE TITLE
[Clang] The assignment to object outside its lifetime is not allowed in a constant expression error while initializing heap allocated memory

### ISSUE THREAD

**Issue by kridenberg** [llvm/llvm-project#120846] opened 2024-12-21 18:04 UTC
Below I wrote down a simplified version of the code I try to implement in the production environment.
The code below is compiled with the latest GCC and the latest MSVC.
Minimal reproducible example here: https://godbolt.org/z/s5G6as9bc

```cpp
#include <bit>
#include <cstddef>
#include <memory>
#include <iostream>

struct buffer
{
	constexpr buffer(char16_t const* values, size_t const count)
        : m_byte_count {count * sizeof(char16_t)}
        , m_bytes {std::allocator<std::byte>().allocate(m_byte_count)}
	{
		struct bytes
		{
			std::byte bytes[2];
		};

		for (std::size_t index = 0; index < count; ++index)
		{
			bytes const bitwise = std::bit_cast<bytes>(values[index]);
			m_bytes[(index * sizeof(char16_t)) + 0] = bitwise.bytes[0];
			m_bytes[(index * sizeof(char16_t)) + 1] = bitwise.bytes[1];
		}
	}

	constexpr auto compute() const -> int
	{
		int result = 0;
		for (std::size_t index = 0; index < m_byte_count; ++index)
		{
			result = result ^ static_cast<int>(m_bytes[index]);
		}

		return result;
	}

	constexpr ~buffer()
	{
		std::allocator<std::byte>().deallocate(m_bytes, m_byte_count);
	}

	std::size_t m_byte_count;
	std::byte* m_bytes;
};

consteval auto compute(char16_t const* values, size_t const count) -> int
{
	buffer b(values, count);
	return b.compute();
}

auto main() -> int
{
	constexpr auto value = compute(u"oadpoadopa", 10);
	std::cout << value << std::endl;
	return 0;
}
```

```
<source>:53:17: error: constexpr variable 'value' must be initialized by a constant expression
   53 |         constexpr auto value = compute(u"oadpoadopa", 10);
      |                        ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:20:44: note: assignment to object outside its lifetime is not allowed in a constant expression
   20 |                         m_bytes[(index * sizeof(char16_t)) + 0] = bitwise.bytes[0];
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
<source>:47:9: note: in call to 'buffer(&u"oadpoadopa"[0], 10)'
   47 |         buffer b(values, count);
      |                ^~~~~~~~~~~~~~~~
<source>:53:25: note: in call to 'compute(&u"oadpoadopa"[0], 10)'
   53 |         constexpr auto value = compute(u"oadpoadopa", 10);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:53:25: error: call to consteval function 'compute' is not a constant expression
   53 |         constexpr auto value = compute(u"oadpoadopa", 10);
      |                                ^
<source>:20:44: note: assignment to object outside its lifetime is not allowed in a constant expression
   20 |                         m_bytes[(index * sizeof(char16_t)) + 0] = bitwise.bytes[0];
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
<source>:47:9: note: in call to 'buffer(&u"oadpoadopa"[0], 10)'
   47 |         buffer b(values, count);
      |                ^~~~~~~~~~~~~~~~
<source>:53:25: note: in call to 'compute(&u"oadpoadopa"[0], 10)'
   53 |         constexpr auto value = compute(u"oadpoadopa", 10);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

**Comment by shafik** [comment] 2024-12-23 19:02
Clang is correct here, `std::allocate` does not start the lifetime of the array elements see [allocator.members p5](https://eel.is/c++draft/allocator.members#5.sentence-2):

> This function starts the lifetime of the array object, but not that of any of the array elements[.](https://eel.is/c++draft/allocator.members#5.sentence-2)

If we add the `construct_at` call then clang accepts it: https://godbolt.org/z/Tebhsx1xY

So this looks like a bug in other implementations.

Looks like this is a duplicate of: https://github.com/llvm/llvm-project/issues/46391

**Closed by shafik** 2024-12-23 19:02 UTC
Labels: clang:frontend, constexpr, diverges-from:gcc, diverges-from:msvc

**Comment by kridenberg** [comment] 2024-12-23 19:11
Understandable, I did not realised that stuff, while this look like ab obvious thing to check. Thanks for the clarification.
