### ISSUE TITLE
There is an issue with alignof in the template

### ISSUE THREAD

**Issue by 4465464** [llvm/llvm-project#62543] opened 2023-05-04 07:41 UTC
```c++
#include <iostream>

__attribute__((aligned(8)))  typedef struct{
    int x;
    int y;
} int2;

template<class T>
void test(){
    int a =alignof(T);
    printf("a:%d\n",a);
}

int main(){
    test<int2>();
    return 0;
}
```

The result of `alignof (int2)` in the template and not in the template is inconsistent. The expected result should be 8, but in reality it is 4.

**Comment by 4465464** [comment] 2023-05-04 07:48
printf("%lu\n",alignof(int2));  // the result is 8;
printf("a:%lu\n",alignof(T));   // the result is 4;   
Inconsistent results in and out of templates.

**Comment by efriedma-quic** [comment] 2023-05-05 05:00
This looks like another instance of "`aligned` attribute on typedefs is broken".  (Generally, I'd recommend using alignas for new code because it's harder to misuse.)

**Comment by shafik** [comment] 2023-05-05 05:41
Duplicate of https://github.com/llvm/llvm-project/issues/59788

**Closed by shafik** 2023-05-05 05:41 UTC
Labels: clang:frontend
