### ISSUE TITLE
Weird behavior of ELF tests with newer version of MSVC.

### ISSUE THREAD

**Issue by rlavaee** [llvm/llvm-project#60013] opened 2023-01-13 21:03 UTC
As pointed in https://reviews.llvm.org/D100808, ELF format tests succeed with MSVC v14.29 (from Visual Studio 2019) but fail with MSVC v14.33 (from Visual Studio 2022).

**Comment by red1bluelost** [comment] 2024-01-23 02:30
Testing on  `llvm-objdump/X86/elf-bbaddrmap-disassemble-symbolize-operands.yaml`, I've managed to bisect the issue as being a yaml2obj problem and not llvm-objdump/readBBAddrMap. I'm assigning this to me as I should be able to get around to debugging more this week.

**Comment by red1bluelost** [comment] 2024-01-23 16:57
I have a fix up at https://github.com/llvm/llvm-project/pull/79168. The problem is we accidentally had side-effects in the expressions of a binary operator. This is unfortunately unspecified behavior in C++ which is why the generated ELF would have fields out of order.

**Closed** 2024-01-24 22:26 UTC
Labels: test-suite, platform:windows, llvm
