### ISSUE TITLE
std::allocator deallocate fails to check validity of second parameter in constexpr

### ISSUE THREAD

**Issue by beached** [llvm/llvm-project#56437] opened 2022-07-08 01:18 UTC
In constexpr code the following will successfully compile when it should not as it fails the precondition check of [deallocate allocator.requirements.general#48.2](http://eel.is/c++draft/allocator.requirements.general#48.2) 

```c++
constexpr int func() {
  std::allocator<int> alloc;
  int* p = alloc.allocate(5);
  alloc.deallocate(p, 2);
  return true;
}

static_assert(func());
```

https://godbolt.org/z/83M34ba9v

**Comment by beached** [comment] 2022-07-08 18:08
I don't know if it should or shouldn't be checked, but, it is checked on MSVC.  

This is a strange area for me as I rarely use allocators and clang is doing a lot of work here already  so it might not be out of place for the lifetime checking it already does e.g.
```c++
auto * ptr = alloc.allocate( 5 );
ptr[2] = 42;
``` is checked, and fails, on clang but not others.

**Comment by dwblaikie** [comment] 2022-07-08 20:08
ah, constexpr, I missed that in the description above (might be worth editing that to include more context in the example - the complete code from godbolt).

Yeah, not sure where the line is with constexpr and library-level UB. I would assume/hope/guess it's not meant to be/doesn't need to be diagnosed, but don't know for sure.

**Comment by AaronBallman** [comment] 2022-07-11 12:41
Based on the above, I am closing this as not a bug. However, it might be a reasonable feature request for a debug mode build of the library. If that's the case, please reopen the issue and set the labels to `libc++` and `enhancement`. Thanks!

**Closed by AaronBallman** 2022-07-11 12:41 UTC
Labels: invalid, c++20, clang:frontend
