### ISSUE TITLE
Clang-15.0.6: std::ranges::subrange doesn't work with std::vector<T>::iterator.

### ISSUE THREAD

**Issue by wuye9036** [llvm/llvm-project#59697] opened 2022-12-25 16:42 UTC
```c++
#include <ranges>
#include <iostream>
#include <vector>

std::vector<int> ints{0, 1, 2, 3, 4};

std::ranges::subrange<std::vector<int>::iterator> rng;

int main() {
    std::cout << rng.front() << std::endl;
    std::cout << _GLIBCXX_RELEASE << std::endl;
    std::cout << __cplusplus << std::endl;
    
    return 0;
}
```

This code snippet will cause compilation error on Clang 15.0.x whereas MSVC and GCC 12 works well. libstdc++11 and 12 has been tested and failed.

Following is the error
```
/opt/compiler-explorer/gcc-12.2.0/lib/gcc/x86_64-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/iterator_concepts.h:982:13: error: no matching function for call to '__begin'
        = decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/gcc-12.2.0/lib/gcc/x86_64-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/ranges_base.h:595:5: note: in instantiation of template type alias '__range_iter_t' requested here
    using iterator_t = std::__detail::__range_iter_t<_Tp>;
    ^
/opt/compiler-explorer/gcc-12.2.0/lib/gcc/x86_64-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/ranges_util.h:121:36: note: in instantiation of template type alias 'iterator_t' requested here
      requires contiguous_iterator<iterator_t<_Derived>>
                                   ^
/opt/compiler-explorer/gcc-12.2.0/lib/gcc/x86_64-linux-gnu/12.2.0/../../../../include/c++/12.2.0/bits/ranges_util.h:228:29: note: in instantiation of template class 'std::ranges::view_interface<std::ranges::subrange<__gnu_cxx::__normal_iterator<int *, std::vector<int>>, __gnu_cxx::__normal_iterator<int *, std::vector<int>>, std::ranges::subrange_kind::sized>>' requested here
    class subrange : public view_interface<subrange<_It, _Sent, _Kind>>
...
 ```

**Comment by royjacobson** [comment] 2022-12-25 21:06
Works on trunk, most likely a duplicate of #44178.

**Closed by royjacobson** 2022-12-25 21:06 UTC
Labels: libstdc++
