### ISSUE TITLE
clang-format not idempotent with long comment containing tabs

### ISSUE THREAD

**Issue by 044bd442-f905-4032-9274-abf2014e980e** [llvm/llvm-project#51808] opened 2021-11-10 10:29 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [52466](https://llvm.org/bz52466) |
| Version | 13.0 |
| OS | Linux |
| Attachments | [Example file for which the described issue occurs.](https://user-images.githubusercontent.com/95090400/143762706-79c337fb-f8b7-4144-94b2-662c32922ba1.gz) |
| CC | @mydeveloperday |

## Extended Description 

The output of `clang-format` changes multiple times on this example containing a long comment with tabs (this is extracted from a real-world example, reduced to the offending line):

> // 	//								for(auto const& value: sze) cout << value<<" ";

(the file is also added as attachment).

I am testing with version "13.0.0 (https://github.com/llvm/llvm-project d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)".

Expected behaviour
==================

Calling `clang-format` a second time on any file should not result in any additional changes, i.e. the output of

    $ clang-format file.cpp | clang-format --dry-run

should always be empty.

Actual behaviour
================

On the given example, 

    $ clang-format file.cpp | clang-format --dry-run

results in the following output:

> <stdin>:1:37: warning: code should be clang-formatted [-Wclang-format-violations]
> //      //                                                              for(auto const& value: sze)
>                                                                                               ^
> <stdin>:1:42: warning: code should be clang-formatted [-Wclang-format-violations]
> //      //                                                              for(auto const& value: sze)
>                                                                                                    ^
> <stdin>:2:1: warning: code should be clang-formatted [-Wclang-format-violations]
> // cout << value<<" ";
> ^

Actually, I have to call it four times until there are no changes anymore.

One run
-------

    $ clang-format file.cpp
    // 	//								for(auto const& value: sze)
    // cout << value<<" ";

Two runs
--------

    $ clang-format file.cpp | clang-format
    // 	//								for(auto const& value:
    // sze) cout << value<<" ";

Three runs
----------

    $ clang-format file.cpp | clang-format | clang-format
    // 	//								for(auto const&
    // value: sze) cout << value<<" ";

Four runs
---------

    $ clang-format file.cpp | clang-format | clang-format | clang-format
    // 	//								for(auto
    // const& value: sze) cout << value<<" ";

From here there are no more changes.

I noticed that when I replace the tabs with spaces, I don't have this issue.

**Comment by luator** [comment] 2021-12-13 11:06
Thanks for your effort!  Personally I would be fine with simply wiping all the tabs but I guess that wouldn't be a general solution for everyone.
I can understand that if this is more complicated to fix, it may not be worth the effort.  I'm afraid I won't have enough time to really look into this myself.

**Comment by mydeveloperday** [comment] 2021-12-13 11:10
It might just need someone to take a sit down and a long hard look. To be honest this isn't in my wheelhouse because I never use tabs, so I'm kind of unlikely to make this my own personal priority.

**Comment by garyo** [comment] 2022-07-12 20:52
> I never saw that written down as a requirement? I'm not saying its not desirable but there seems to be this belief that its a thing?
> 
> When the best practice is that we clang-format on save, isn't this only ever a problem that first time you clang-format something?
> 
> In your case the comments are reflowing.
> 
> Once reflowed don't they need to be reconsidered? This is one of the reasons why I think its not a "crime" that it might take 3 or 4 times to settle down, once settled it shouldn't do it any more.

The real problem here is that in the first run, clang-format is producing non-conforming code, i.e. code that will fail a clang-format check. That seems wrong to me. I would expect that clang-format should always produce correctly formatted code according to the chosen style. 

We are clang-formatting a large existing codebase, and not realizing this has caused some problems for us.

(And btw this means *every* run of clang-format, even running it on save, really needs to run multiple times, in case someone adds one of these "bad" comments.)

**Comment by rymiel** [comment] 2022-11-21 14:01
This is a duplicate of #56769. This issue is older, but the other issue is already awaiting review.

**Closed by rymiel** 2022-11-21 14:01 UTC
Labels: bug, clang-format, bugzilla, confirmed
