### ISSUE TITLE
clang-tidy gives incorrect result for `__has_builtin`

### ISSUE THREAD

**Issue by russellmcc** [llvm/llvm-project#59807] opened 2023-01-03 21:30 UTC
`clang-tidy` sometimes gives the wrong result for `__has_builtin`.

For example:

```cpp
#if !__has_builtin(__builtin_os_log_format)
#error "Needs built-in"
#endif

int main() {}
```

gives an error (https://godbolt.org/z/fWdz4zx6h), even though the built-in is actually there (https://godbolt.org/z/oE567Yeve)

**Comment by russellmcc** [comment] 2023-01-03 22:36
Apparently this only happens in `-std=c++20`

**Comment by PiotrZSL** [comment] 2023-06-27 20:26
Duplicate of #50087.
https://discourse.llvm.org/t/rfc-expand-modular-headers-ppcallbacks-problem-in-c-20/71628

**Closed** 2023-06-27 21:40 UTC
Labels: duplicate, clang-tidy, confirmed
