### ISSUE TITLE
gcc+lld+lto: entry symbol gets optimized away

### ISSUE THREAD

**Issue by medhefgo** [llvm/llvm-project#67152] opened 2023-09-22 14:55 UTC
```
$ gcc -xc <(echo "void _start(void) {}") -fuse-ld=lld -nostdlib -o bug -flto && readelf -s bug | grep start
ld.lld: warning: cannot find entry symbol _start; not setting start address
```

With clang or without lto:
```
$ clang -xc <(echo "void _start(void) {}") -fuse-ld=lld -nostdlib -o bug -flto && readelf -s bug | grep start
     3: 0000000000001340     6 FUNC    GLOBAL DEFAULT    8 _start

$ gcc -xc <(echo "void _start(void) {}") -fuse-ld=lld -nostdlib -o bug && readelf -s bug | grep start
     3: 000000000000136c     7 FUNC    GLOBAL DEFAULT    8 _start
```

**Comment by MaskRay** [comment] 2023-11-05 05:35
Duplicate of #41791
lld doesn't support GCC LTO.

**Closed by MaskRay** 2023-11-05 05:35 UTC
Labels: duplicate, lld, LTO
