### ISSUE TITLE
 Linking libLTO.so failed

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#59488] opened 2022-12-13 08:37 UTC
Hi!

We are bumping our LLVM build from 1ae33bf42680b156fe0f5cd6163bf24ef45d8cd3 to 35d9f873e3f21846de1b8f07271feedbbe8518ed, and get the following build error message:

```console
[3435/4368] Linking CXX shared library lib/libLTO.so.16git
FAILED: lib/libLTO.so.16git 
: && /tmp/llvm-project/build/./bin/clang++ -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG  -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=lld -Wl,--color-diagnostics   -Wl,--gc-sections  -Wl,--version-script,"/tmp/llvm-project/build/tools/clang/stage2-bins/tools/lto/LTO.exports" -shared -Wl,-soname,libLTO.so.16git -o lib/libLTO.so.16git tools/lto/CMakeFiles/LTO.dir/LTODisassembler.cpp.o tools/lto/CMakeFiles/LTO.dir/lto.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVM-16git.so && :
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMCreateDisasm' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMCreateDisasmCPU' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMDisasmDispose' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMDisasmInstruction' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMSetDisasmOptions' failed: symbol not defined
ld.lld: error: version script assignment of 'LLVM_16' to symbol 'LLVMCreateDisasmCPUFeatures' failed: symbol not defined
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

We are building inside a docker image (so the build folder is always clean), with the following configure and build command:

```shell
RUN cmake \
    -G Ninja \
    # First-stage options
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" \
    -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi" \
    -DLLVM_TARGETS_TO_BUILD="X86" \
    -DLLVM_USE_LINKER="gold" \
    -DCLANG_ENABLE_BOOTSTRAP=ON \
    # https://github.com/llvm/llvm-project/issues/55517
    -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
    # Second-stage options
    -DBOOTSTRAP_CMAKE_INSTALL_PREFIX=${OUTPUT_DIR}/usr \
    -DBOOTSTRAP_CMAKE_BUILD_TYPE=Release \
    -DBOOTSTRAP_LLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" \
    -DBOOTSTRAP_LLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi" \
    -DBOOTSTRAP_LLVM_TARGETS_TO_BUILD="X86;NVPTX" \
    -DBOOTSTRAP_LLVM_ENABLE_LLD=ON \
    -DBOOTSTRAP_LLVM_ENABLE_RTTI=ON \
    -DBOOTSTRAP_LLVM_BUILD_LLVM_DYLIB=ON \
    -DBOOTSTRAP_LLVM_LINK_LLVM_DYLIB=ON \
    # https://github.com/llvm/llvm-project/issues/55517
    -DBOOTSTRAP_COMPILER_RT_DEFAULT_TARGET_ONLY=ON \
    # Disable CMake developer warnings
    -Wno-dev \
    ../llvm
RUN ninja stage2
RUN ninja stage2-install
```

Is this known? How could we solve the problem? 

Thanks!

**Comment by jhuber6** [comment] 2022-12-14 11:48
Fixing this is an ongoing issue with the changes introduced in https://reviews.llvm.org/D135402. The issue above was intended to be fixed by https://reviews.llvm.org/D139932. I encountered that issue myself, usually I could get a complete build if I deleted the build directory and any previous installations.

**Comment by carlosgalvezp** [comment] 2022-12-14 12:07
I see, I guess the problem is that I'm doing a multi-stage build, and that's why it detects a non-clean build folder? I will check what the deb guys do.

**Closed** 2022-12-14 13:07 UTC
Labels: build-problem, LTO
