### ISSUE TITLE
[Clang] errors with "conflicting types for" function declarations which only differ by return type constness

### ISSUE THREAD

**Issue by nabijaczleweli** [llvm/llvm-project#78499] opened 2024-01-17 20:25 UTC
```
$ cat a.c
int qwe(void);
const int qwe(void);
$ cc -c a.c
a.c:2:11: error: conflicting types for 'qwe'
    2 | const int qwe(void);
      |           ^
a.c:1:5: note: previous declaration is here
    1 | int qwe(void);
      |     ^
1 error generated.
$ gcc -Wall -pedantic -c a.c
$ cc --version
Debian clang version 18.0.0 (++20231231112334+c7c912cff945-1~exp1~20231231112352.433)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
(and the same with gcc 13.2.0-7)

In [a Draft](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf), 6.7.6.3 Function declarators, Semantics, 4, I see
> If, in the declaration "**T D1**", **D1** has the form
> &nbsp; &nbsp; &nbsp; &nbsp; **D** `(` parameter-type-listopt `)` attribute-specifier-sequenceopt
> and the type specified for *ident* in the declaration "**T D**" is "*derived-declarator-type-list T*", then the type specified for *ident* is "*derived-declarator-type-list* function returning the unqualified, non-atomic version of *T*". The optional attribute specifier sequence appertains to the function type.

This appears to imply that the types for both declarations are processed thusly (pardon the C++-like syntax):
```cpp
remove_atomic<remove_cv<int>> qwe(void);
remove_atomic<remove_cv<const int>> qwe(void);
```
yielding
```c
int qwe(void);
int qwe(void);
```
which is identical.

([Original report](https://101010.pl/@sebastian@jittr.click/111770387762063846))

**Comment by shafik** [comment] 2024-01-18 02:28
CC @AaronBallman this feel vaguely familiar but I can't find a similar issue.

**Comment by AaronBallman** [comment] 2024-01-18 13:25
Duplicate of #39494

**Closed by AaronBallman** 2024-01-18 13:25 UTC
Labels: duplicate, c, clang:frontend
