### ISSUE TITLE
likely wrong code bug from arm64 backend with global isel enabled

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#55003] opened 2022-04-20 20:43 UTC
here's a function that's part of the LLVM unit test suite:
```
; ModuleID = 'file-020267.bc'
source_filename = "/home/regehr/llvm-project/llvm/test/Transforms/InstCombine/fsh.ll"

target triple = "arm64-apple-macosx12.0.0"

; Function Attrs: nofree nosync nounwind readnone speculatable willreturn
declare i32 @llvm.fshl.i32(i32, i32, i32) #0

define i32 @fshl_undef_shift_amount(i32 %x, i32 %y) {
  %r = call i32 @llvm.fshl.i32(i32 %x, i32 %y, i32 undef)
  ret i32 %r
}

attributes #0 = { nofree nosync nounwind readnone speculatable willreturn }
```

here's the output we get from LLVM 14 and also top of tree:
```
Johns-MacBook-Pro:~ regehr$ llc foo.ll -global-isel -march=arm64 -o -
	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 12, 0
	.globl	_fshl_undef_shift_amount        ; -- Begin function fshl_undef_shift_amount
	.p2align	2
_fshl_undef_shift_amount:               ; @fshl_undef_shift_amount
	.cfi_startproc
; %bb.0:
	mov	w8, #32
	udiv	w9, w8, w8
	msub	w9, w9, w8, w8
	sub	w8, w8, w9
	lsl	w9, w0, w9
	lsr	w8, w1, w8
	orr	w0, w9, w8
	ret
	.cfi_endproc
                                        ; -- End function
.subsections_via_symbols
Johns-MacBook-Pro:~ regehr$ 
```

this function, called with arguments (0, 4) returns 4, which is not one of the permitted outputs given how undef works. unless we're missing something, permissible outputs are 0, 1, 2.

here's the driver I'm using:
```
#include <stdio.h>

unsigned fshl_undef_shift_amount(unsigned, unsigned);

int main(void) {
  unsigned z = fshl_undef_shift_amount(0, 4);
  printf("%u\n", z);
  return 0;
}
```

and the output:
```
Johns-MacBook-Pro:~ regehr$ clang foo.s foo.c 
Johns-MacBook-Pro:~ regehr$ ./a.out 
4
Johns-MacBook-Pro:~ regehr$ 
```

this was found using a highly preliminary version of alive2 that does translation validation for the arm64 backend. 
cc @nunoplopes @nbushehri @ryan-berger

**Comment by nunoplopes** [comment] 2022-04-20 21:01
@EugeneZelenko concurrency clash, sorry :)

**Comment by EugeneZelenko** [comment] 2022-04-20 21:03
@nunoplopes: It's fine :-)

**Comment by fhahn** [comment] 2022-04-20 21:12
cc @aemerson @ornata

**Comment by davemgreen** [comment] 2022-04-21 08:15
> this was found using a highly preliminary version of alive2 that does translation validation for the arm64 backend.
Sounds very interesting. Do you have a link or a paper yet?

**Comment by regehr** [comment] 2022-04-21 15:07
> Sounds very interesting. Do you have a link or a paper yet?

nothing yet, still very much a work in progress. we hope to give a talk at the next LLVM Dev meeting and of course would be happy to discuss in person there or elsewhere

**Comment by nicolas17** [comment] 2022-05-04 00:45
fwiw 7bddf0058195dec111a54d4514b58a9f103b8ea4 generates the same asm so this is not a regression.

**Comment by dzhidzhoev** [comment] 2022-07-21 22:05
Working on it

**Comment by dzhidzhoev** [comment] 2022-08-01 23:13
Seems to be fixed by https://reviews.llvm.org/D125041

**Comment by efriedma-quic** [comment] 2022-08-19 20:05
The patch landed months ago; it's already in llvm 15.

**Closed by efriedma-quic** 2022-08-19 20:05 UTC
Labels: backend:AArch64, miscompilation, globalisel, release:backport, release:cherry-pick-failed
