### ISSUE TITLE
BOLT error while instrumenting Clang Executable on AArch64

### ISSUE THREAD

**Issue by liamhouston** [llvm/llvm-project#63255] opened 2023-06-11 19:53 UTC
I ran `llvm-bolt <clang-17 executable> -instrument -o <output file>` and received the following output: 

```console
BOLT-INFO: shared object or position-independent executable detected
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: 4fcbe5fbeda15220bbbd8f4dbd6909a66a19b779
BOLT-INFO: first alloc address is 0x0
BOLT-INFO: creating new program header table at address 0x5e00000, offset 0x5e00000
BOLT-INFO: enabling relocation mode
BOLT-INFO: forcing -jump-tables=move for instrumentation
BOLT-INFO: disabling -align-macro-fusion on non-x86 platform
BOLT-WARNING: 1 collisions detected while hashing binary objects. Use -v=1 to see the list.
BOLT-INFO: number of removed linker-inserted veneers: 0
BOLT-INFO: 0 out of 136265 functions in the binary (0.0%) have non-empty execution profile
BOLT-INFO: UCE removed 0 blocks and 0 bytes of code.
BOLT-INFO: Starting stub-insertion pass
BOLT-INFO: Inserted 114 stubs in the hot area and 0 stubs in the cold area. Shared 0 times, iterated 2 times.
 #0 0x0000aaaaab77ec64 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./llvm-bolt+0xcdec64)
 #1 0x0000aaaaab77ce84 llvm::sys::RunSignalHandlers() (./llvm-bolt+0xcdce84)
 #2 0x0000aaaaab77f4dc SignalHandler(int) Signals.cpp:0:0
 #3 0x00004000000707a0 (linux-vdso.so.1+0x7a0)
 #4 0x0000aaaaabac2f7c llvm::bolt::InstrumentationRuntimeLibrary::emitBinary(llvm::bolt::BinaryContext&, llvm::MCStreamer&) (./llvm-bolt+0x1022f7c)
 #5 0x0000aaaaac296584 llvm::bolt::emitBinaryContext(llvm::MCStreamer&, llvm::bolt::BinaryContext&, llvm::StringRef) (./llvm-bolt+0x17f6584)
 #6 0x0000aaaaab7c9400 llvm::bolt::RewriteInstance::emitAndLink() (./llvm-bolt+0xd29400)
 #7 0x0000aaaaab7c2884 llvm::bolt::RewriteInstance::run() (./llvm-bolt+0xd22884)
 #8 0x0000aaaaab417324 main (./llvm-bolt+0x977324)
 #9 0x0000400000564384 __libc_start_main (/lib64/libc.so.6+0x24384)
#10 0x0000aaaaab4157b4 _start (./llvm-bolt+0x9757b4)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.
```

Running on LLVM version 17.0.0, targeting AArch64

**Comment by ElvinaYakubova** [comment] 2023-06-13 06:18
Hi! Instrumentation for AArch64 is not merged yet, but you can try to apply patches [1](https://reviews.llvm.org/D151899) [2](https://reviews.llvm.org/D151942) [3](https://reviews.llvm.org/D151901)

**Comment by liamhouston** [comment] 2023-06-13 17:13
Hi Elvina,

I have applied the patches and I'm encountering this error message on the build step for bolt_rt


![3_patches](https://github.com/llvm/llvm-project/assets/105176614/be0d2520-d266-4c75-be5b-9c6080ab5340)

**Comment by liamhouston** [comment] 2023-06-14 03:08
With the batches and the if block commented out, the build ran successfully. Then I ran bolt with llvm-bolt [clang-17 executable] -instrument -o [output file] and it produced the following output:
BOLT-INFO: shared object or position-independent executable detected                                                                                                                                             BOLT-INFO: Target architecture: aarch64                                                                                                                                                                          BOLT-INFO: BOLT version: 666a56f1f1683535967d1a3b7587bf85044ea005                                                                                                                                                BOLT-INFO: first alloc address is 0x0                                                                                                                                                                            BOLT-INFO: creating new program header table at address 0x5e00000, offset 0x5e00000                                                                                                                              BOLT-INFO: enabling relocation mode                                                                                                                                                                              BOLT-INFO: forcing -jump-tables=move for instrumentation                                                                                                                                                         BOLT-INFO: disabling -align-macro-fusion on non-x86 platform                                                                                                                                                     BOLT-WARNING: 1 collisions detected while hashing binary objects. Use -v=1 to see the list.                                                                                                                      BOLT-INFO: number of removed linker-inserted veneers: 0                                                                                                                                                          BOLT-INFO: 0 out of 136265 functions in the binary (0.0%) have non-empty execution profile                                                                                                                        #0 0x0000aaaaab780170 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (./llvm-bolt+0xce0170)                                                                                                                 #1 0x0000aaaaab77e390 llvm::sys::RunSignalHandlers() (./llvm-bolt+0xcde390)                                                                                                                                      #2 0x0000aaaaab780a04 SignalHandler(int) Signals.cpp:0:0                                                                                                                                                         #3 0x00004000000707a0 (linux-vdso.so.1+0x7a0)                                                                                                                                                                    #4 0x00004000005bc1ec __libc_malloc (/lib64/libc.so.6+0x7c1ec)                                                                                                                                                   #5 0x00004000003e14d4 operator new(unsigned long) (/lib64/libstdc++.so.6+0x914d4)                                                                                                                                #6 0x0000aaaaab831318 llvm::bolt::getEscapedName[abi:cxx11](llvm::StringRef const&) (./llvm-bolt+0xd91318)                                                                                                       #7 0x0000aaaaabb43054 llvm::bolt::Instrumentation::getFunctionNameIndex(llvm::bolt::BinaryFunction const&) (./llvm-bolt+0x10a3054)                                                                               #8 0x0000aaaaabb431d0 llvm::bolt::Instrumentation::createCallDescription(llvm::bolt::FunctionDescription&, llvm::bolt::BinaryFunction const&, unsigned int, unsigned int, llvm::bolt::BinaryFunction const&, unsigned int, bool) (./llvm-bolt+0x10a31d0)                                                                                                                                                                          #9 0x0000aaaaabb43d00 llvm::bolt::Instrumentation::instrumentOneTarget(std::vector<std::pair<llvm::bolt::BinaryBasicBlock*, llvm::bolt::BinaryBasicBlock*>, std::allocator<std::pair<llvm::bolt::BinaryBasicBlock*, llvm::bolt::BinaryBasicBlock*>>>&, std::vector<std::vector<llvm::MCInst, std::allocator<llvm::MCInst>>, std::allocator<std::vector<llvm::MCInst, std::allocator<llvm::MCInst>>>>&, __gnu_cxx::__normal_iterator<llvm::MCInst*, std::vector<llvm::MCInst, std::allocator<llvm::MCInst>>>&, llvm::bolt::BinaryFunction&, llvm::bolt::BinaryBasicBlock&, unsigned int, llvm::bolt::BinaryFunction&, llvm::bolt::BinaryBasicBlock*, unsigned int, bool, bool, llvm::bolt::FunctionDescription*, unsigned int, unsigned int) (./llvm-bolt+0x10a3d00)                                                                                                #10 0x0000aaaaabb44cf8 llvm::bolt::Instrumentation::instrumentFunction(llvm::bolt::BinaryFunction&, unsigned short) (./llvm-bolt+0x10a4cf8)                                                                      #11 0x0000aaaaac2f223c llvm::bolt::ParallelUtilities::runOnEachFunctionWithUniqueAllocId(llvm::bolt::BinaryContext&, llvm::bolt::ParallelUtilities::SchedulingPolicy, std::function<void (llvm::bolt::BinaryFunction&, unsigned short)>, std::function<bool (llvm::bolt::BinaryFunction const&)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, bool, unsigned int)::$_0::operator()(std::_Rb_tree_iterator<std::pair<unsigned long const, llvm::bolt::BinaryFunction>>, std::_Rb_tree_iterator<std::pair<unsigned long const, llvm::bolt::BinaryFunction>>, unsigned short) const ParallelUtilities.cpp:0:0     #12 0x0000aaaaac2f1c80 llvm::bolt::ParallelUtilities::runOnEachFunctionWithUniqueAllocId(llvm::bolt::BinaryContext&, llvm::bolt::ParallelUtilities::SchedulingPolicy, std::function<void (llvm::bolt::BinaryFunction&, unsigned short)>, std::function<bool (llvm::bolt::BinaryFunction const&)>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, bool, unsigned int) (./llvm-bolt+0x1851c80)     #13 0x0000aaaaabb46858 llvm::bolt::Instrumentation::runOnFunctions(llvm::bolt::BinaryContext&) (./llvm-bolt+0x10a6858)                                                                                           #14 0x0000aaaaab7b29e8 llvm::bolt::BinaryFunctionPassManager::runPasses() (./llvm-bolt+0xd129e8)                                                                                                                 #15 0x0000aaaaab7b4c88 llvm::bolt::BinaryFunctionPassManager::runAllPasses(llvm::bolt::BinaryContext&) (./llvm-bolt+0xd14c88)                                                                                    #16 0x0000aaaaab7c3d58 llvm::bolt::RewriteInstance::run() (./llvm-bolt+0xd23d58)                                                                                                                                 #17 0x0000aaaaab4174dc main (./llvm-bolt+0x9774dc)                                                                                                                                                               #18 0x0000400000564384 __libc_start_main (/lib64/libc.so.6+0x24384)                                                                                                                                              #19 0x0000aaaaab41596c _start (./llvm-bolt+0x97596c)                                                                                                                                                             PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.                                                                                                      Stack dump:                                                                                                                                                                                                      0.      Program arguments: ./llvm-bolt ../../stage3-train/bin/clang-17 -instrument -o instrumented-clang17                                                                                                       Segmentation fault (core dumped)

**Comment by ElvinaYakubova** [comment] 2023-06-16 07:20
@liamhouston Hello! Could you please provide instructions on how to reproduce your error? I see your directory name is "stage3-train", are you using "Optimizing Clang" tutorial?

**Comment by liamhouston** [comment] 2023-06-16 16:49
@ElvinaYakubova yes I'm following the Optimizing Clang tutorial.

Here is the configure for the stage3-train clang-17 that I run the bolt instrument command on:
cmake ../llvm-project/llvm  -DLLVM_TARGETS_TO_BUILD=AArch64 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt" -DLLVM_USE_LINKER=lld -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-ftime-trace" -DCMAKE_CXX_FLAGS="-ftime-trace" -G Ninja

I applied the three patches and commented out the if block and then configuring the BOLT build.

Here is the configure for the BOLT
cmake ../llvm-project/llvm -DLLVM_TARGETS_TO_BUILD=AArch64 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;bolt;lld;compiler-rt" -DLLVM_USE_LINKER=lld -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja

Then I tried to use that bolt instrument on the stage3-train clang-17 executable

**Comment by ElvinaYakubova** [comment] 2023-06-19 20:26
@liamhouston do you use clang from stage2-prof-gen here DCMAKE_C_COMPILER=clang? I'm trying to reproduce the error, but the error occurred earlier, on buildCFG step.

**Comment by liamhouston** [comment] 2023-06-19 20:35
@ElvinaYakubova I use the clang from stage2-prof-gen to build the stage3-train clang. To build BOLT I use the baseline stage1 clang.

**Comment by liamhouston** [comment] 2023-06-21 15:43
@ElvinaYakubova Here's a script that recreates the error on my machine.
It should work as is, just adjust the variables LLVM to point to the upper level of a clone of LLVM, and the same for LLVM_PATCH except with the 3 patches and the commenting on the CMakeLists.txt. And adjust CORES depending on your machine.

#!/usr/bin/env bash

DIR=$PWD
# adjust these variables accordingly ###################
LLVM=~/llvm-project
LLVM_PATCH=~/llvm-project-patched
CORES=36
########################################################

module load llvm/16.0.0
# build our baseline clang
mkdir -p baseline
cd baseline
cmake $LLVM/llvm -DLLVM_TARGETS_TO_BUILD=AArch64 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt" -DLLVM_USE_LINKER=lld -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-ftime-trace" -DCMAKE_CXX_FLAGS="-ftime-trace" -G Ninja && ninja -j $CORES

if [ $? -ne 0]; then
  exit
fi

cd ..
mkdir -p stage1
cd stage1
# build the clang whose binary will be instrument
export LDFLAGS="-Wl,-q"
export PATH=$DIR/baseline/bin:$PATH
cmake $LLVM/llvm -DLLVM_TARGETS_TO_BUILD=AArch64 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lld;compiler-rt" -DLLVM_USE_LINKER=lld -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-ftime-trace" -DCMAKE_CXX_FLAGS="-ftime-trace" -G Ninja && ninja -j $CORES

if [ $? -ne 0 ]; then
  exit
fi

cd ..
mkdir -p bolt
cd bolt
# build bolt from the patched llvm
export PATH=$DIR/stage1/bin:$PATH
cmake $LLVM_PATCH/llvm -DLLVM_TARGETS_TO_BUILD=AArch64 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="bolt;clang;lld;compiler-rt" -DLLVM_USE_LINKER=lld -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-ftime-trace" -DCMAKE_CXX_FLAGS="-ftime-trace" -G Ninja && ninja -j $CORES

if [ $? -ne 0 ]; then
  exit
fi

cd ..
./bolt/bin/llvm-bolt -instrument stage1/bin/clang-17 -o stage1/bin/clang-17-instrumented

**Comment by ElvinaYakubova** [comment] 2023-06-21 15:55
@liamhouston Thank you! I'll try to use it, because still can't get the same error as you

**Comment by aaupov** [comment] 2023-06-22 00:57
As a suggestion: please try building with clang/cmake/caches/BOLT-PGO.cmake cache file, it simplifies the application of BOLT over (bootstrapped) PGO build. It uses a different profiling mechanism for PGO and BOLT (perf-training) but other than that, it follows the same steps.

An example build configuration is given here: https://github.com/aaupov/llvm-devmtg-2022/blob/main/driver.sh, `BOLT_LTO_PGO_ARGS` cmake args set up Clang bootstrapped build with InstrumentationPGO and ThinLTO, and BOLT on top of that.

**Closed** 2023-07-05 15:24 UTC
Labels: BOLT

**Comment by ElvinaYakubova** [comment] 2023-07-07 12:21
> I removed the flag DCMAKE_[C|CXX]_FLAGS="-ftime-trace" in the configuration for the clang that BOLT was trying to instrument (the stage3-train clang). This allowed BOLT to instrument properly.
That's good to hear. From my side, the error is still a different one, and yours is not reproducible, no matter if I remove "-ftime-trace" flag or not.
Did you manage to collect the profile? Does everything work after that?

**Comment by liamhouston** [comment] 2023-07-07 15:22
@ElvinaYakubova 
Hmmm that's very strange. But on my side I'm able to collect the profile with the instrumented compiler and use BOLT.
