### ISSUE TITLE
lli command line issue on arm64   ,cl::ConsumeAfter option is active! 

### ISSUE THREAD

**Issue by phoenixlabcn** [llvm/llvm-project#54361] opened 2022-03-13 06:08 UTC
LLVM (http://llvm.org/):
  LLVM version 14.0.0
  Optimized build.
  Default target: arm64-apple-darwin21.1.0
  Host CPU: cyclone

I compiled llvm release 14 into arm64，and made it into a  framework. 
clang and llvm-link can be used normally.

When I use ' lli XXXXX.bc  ' command always returns

<input bitcode> option: error - this positional option will never be matched, because it does not Require a value, and a cl::ConsumeAfter option is active!
<input file> option: error - this positional option will never be matched, because it does not Require a value, and a cl::ConsumeAfter option is active! 

How can I use it normally

**Comment by EugeneZelenko** [comment] 2022-03-13 06:16
Duplicate of #54362.

**Closed by EugeneZelenko** 2022-03-13 06:16 UTC
Labels: duplicate, backend:AArch64, llvm-tools
