### ISSUE TITLE
clang crashes when performing initialization on invalid code. 

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#75781] opened 2023-12-18 10:41 UTC
clang crashes on the the following invalid code:

```
template <class T, typename U>
struct A {  T a; U b;};

template<typename K>
struct A<int, int> { int a; K b;};

void s() {
  A<int, int> a{1, 2};
}
```

https://godbolt.org/z/vEh15cEzz

**Comment by shafik** [comment] 2023-12-18 18:40
This looks like a regression from clang-16: https://godbolt.org/z/5szPKWdnc

The change that brought in the assert was: 632dd6a4ca003

CC @yuanfang-chen

**Comment by shafik** [comment] 2023-12-18 18:42
Duplicate of: https://github.com/llvm/llvm-project/issues/67173

**Closed by shafik** 2023-12-18 18:42 UTC
Labels: clang:frontend, crash-on-invalid, confirmed
