### ISSUE TITLE
Bug report: clang-tidy: segmentation fault

### ISSUE THREAD

**Issue by juliusHuelsmann** [llvm/llvm-project#59674] opened 2022-12-23 12:39 UTC
I encountered a segmentation fault while running clang-tidy. The output prompted me to issue a bug report here. The underlying issue might already be fixed, because I retried it with clang-tidy 16.0.0 and no exception occurred there.

```console
> clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 15.0.6
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: alderlake
```

```console
$ /snap/clion/219/bin/cmake/linux/bin/cmake -E __run_co_compile --launcher=/usr/bin/ccache --tidy="/home/x/llvm/bin/clang-tidy;-extra-arg=-Wno-unknown-warning-option;-warnings-as-errors=*;-extra-arg=-std=c++20;--extra-arg-before=--driver-mode=g++" --cppcheck="/usr/bin/cppcheck;--template=gcc;--enable=style,performance,warning,portability;--inline-suppr;--suppress=cppcheckError;--suppress=internalAstError;--suppress=unmatchedSuppression;--suppress=passedByValue;--suppress=syntaxError;--inconclusive;--error-exitcode=2;--std=c++20" --source=/mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/src/Conversion.cpp -- /home/x/llvm/bin/clang++ -DBOOST_ALL_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DLIBJPEG_STATIC -DLZMA_API_STATIC -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/mnt/data/online/repos/dataspree/CPPTest/cpp/cmake-build-debug/configured_files/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/inference/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/cmake-build-debug/include -isystem /home/x/.conan/data/opencv/4.3.0/conan/stable/package/94d4187c0312e30f52a28cf6069676a7407a4cc3/include -isystem /home/x/.conan/data/opencv/4.3.0/conan/stable/package/94d4187c0312e30f52a28cf6069676a7407a4cc3/include/opencv4 -isystem /home/x/.conan/data/zlib/1.2.11/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/libjpeg/9d/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/libtiff/4.0.9/_/_/package/b7c94c803eedeb9bc626a06e797a57eb4f5c862d/include -isystem /home/x/.conan/data/xz_utils/5.2.5/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/jbig/20160605/_/_/package/cdc8bea8fb234d1e09962f1bf137733982bc42a5/include -isystem /home/x/.conan/data/libwebp/1.0.3/_/_/package/8edaed5f47b8187c7ffb8b02c5170d0fe25d95a4/include -isystem /home/x/.conan/data/libpng/1.6.37/_/_/package/c0916a7ff3d2994eec82f074f6736103ea491fce/include -isystem /home/x/.conan/data/openjpeg/2.3.1/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/openjpeg/2.3.1/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include/openjpeg-2.3 -isystem /home/x/.conan/data/openexr/2.3.0/_/_/package/fdaa2c68b4ec7da41ee60ca712e28e19a7fc1350/include/OpenEXR -isystem /home/x/.conan/data/openexr/2.3.0/_/_/package/fdaa2c68b4ec7da41ee60ca712e28e19a7fc1350/include -isystem /home/x/.conan/data/protobuf/3.5.2/bincrafters/stable/package/e84b6d643e7f97d33bf72700134618fbae8bbbf6/include -isystem /home/x/.conan/data/eigen/3.3.7/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/eigen3 -isystem /home/x/.conan/data/msgpack/3.3.0/_/_/package/ab348e18d5306e3da0e16a7c27e14920a0ff12e8/include -isystem /home/x/.conan/data/nlohmann_json/3.11.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -isystem /home/x/.conan/data/fmt/9.1.0/_/_/package/cd50048341de63231494c4addec91ebdcf784cb8/include -isystem /home/x/.conan/data/spdlog/1.10.0/_/_/package/4ba317fc75d66f33328cdfd7416ce40cb08d4f12/include -g -fcolor-diagnostics -fcolor-diagnostics -fsanitize=address,undefined -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Werror -std=c++20 -MD -MT examples/tcp/CMakeFiles/TcpTest.dir/src/Conversion.cpp.o -MF examples/tcp/CMakeFiles/TcpTest.dir/src/Conversion.cpp.o.d -o examples/tcp/CMakeFiles/TcpTest.dir/src/Conversion.cpp.o -c /mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/src/Conversion.cpp
Error running '/home/x/llvm/bin/clang-tidy': PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/x/llvm/bin/clang-tidy -extra-arg=-Wno-unknown-warning-option -warnings-as-errors=* -extra-arg=-std=c++20 --extra-arg-before=--driver-mode=g++ /mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/src/Conversion.cpp -- /home/x/llvm/bin/clang++ -DBOOST_ALL_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DLIBJPEG_STATIC -DLZMA_API_STATIC -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/mnt/data/online/repos/dataspree/CPPTest/cpp/cmake-build-debug/configured_files/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/inference/include -I/mnt/data/online/repos/dataspree/CPPTest/cpp/cmake-build-debug/include -isystem /home/x/.conan/data/opencv/4.3.0/conan/stable/package/94d4187c0312e30f52a28cf6069676a7407a4cc3/include -isystem /home/x/.conan/data/opencv/4.3.0/conan/stable/package/94d4187c0312e30f52a28cf6069676a7407a4cc3/include/opencv4 -isystem /home/x/.conan/data/zlib/1.2.11/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/libjpeg/9d/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/libtiff/4.0.9/_/_/package/b7c94c803eedeb9bc626a06e797a57eb4f5c862d/include -isystem /home/x/.conan/data/xz_utils/5.2.5/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/jbig/20160605/_/_/package/cdc8bea8fb234d1e09962f1bf137733982bc42a5/include -isystem /home/x/.conan/data/libwebp/1.0.3/_/_/package/8edaed5f47b8187c7ffb8b02c5170d0fe25d95a4/include -isystem /home/x/.conan/data/libpng/1.6.37/_/_/package/c0916a7ff3d2994eec82f074f6736103ea491fce/include -isystem /home/x/.conan/data/openjpeg/2.3.1/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include -isystem /home/x/.conan/data/openjpeg/2.3.1/_/_/package/06b9cd1c4dccbb163a99056eda646b0e168548fc/include/openjpeg-2.3 -isystem /home/x/.conan/data/openexr/2.3.0/_/_/package/fdaa2c68b4ec7da41ee60ca712e28e19a7fc1350/include/OpenEXR -isystem /home/x/.conan/data/openexr/2.3.0/_/_/package/fdaa2c68b4ec7da41ee60ca712e28e19a7fc1350/include -isystem /home/x/.conan/data/protobuf/3.5.2/bincrafters/stable/package/e84b6d643e7f97d33bf72700134618fbae8bbbf6/include -isystem /home/x/.conan/data/eigen/3.3.7/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/eigen3 -isystem /home/x/.conan/data/msgpack/3.3.0/_/_/package/ab348e18d5306e3da0e16a7c27e14920a0ff12e8/include -isystem /home/x/.conan/data/nlohmann_json/3.11.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -isystem /home/x/.conan/data/fmt/9.1.0/_/_/package/cd50048341de63231494c4addec91ebdcf784cb8/include -isystem /home/x/.conan/data/spdlog/1.10.0/_/_/package/4ba317fc75d66f33328cdfd7416ce40cb08d4f12/include -g -fcolor-diagnostics -fcolor-diagnostics -fsanitize=address,undefined -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Werror -std=c++20 -MD -MT examples/tcp/CMakeFiles/TcpTest.dir/src/Conversion.cpp.o -MF examples/tcp/CMakeFiles/TcpTest.dir/src/Conversion.cpp.o.d -o examples/tcp/CMakeFiles/TcpTest.dir/src/Conversion.cpp.o -c /mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/src/Conversion.cpp
1.	<eof> parser at end of file
2.	ASTMatcher: Processing 'bugprone-argument-comment' against:
	CallExpr : </mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/src/Conversion.cpp:367:7, col:50>
--- Bound Nodes Begin ---
    expr - { CallExpr : </mnt/data/online/repos/dataspree/CPPTest/cpp/examples/tcp/src/Conversion.cpp:367:7, col:50> }
--- Bound Nodes End ---
 #0 0x000055d5ae7d0363 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/x/llvm/bin/clang-tidy+0x2750363)
 #1 0x000055d5ae7ce23e llvm::sys::RunSignalHandlers() (/home/x/llvm/bin/clang-tidy+0x274e23e)
 #2 0x000055d5ae7d09df SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f08ba042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000055d5b116bfc0 clang::Lexer::LexStringLiteral(clang::Token&, char const*, clang::tok::TokenKind) (/home/x/llvm/bin/clang-tidy+0x50ebfc0)
 #5 0x000055d5b1173849 clang::Lexer::LexTokenInternal(clang::Token&, bool) (/home/x/llvm/bin/clang-tidy+0x50f3849)
 #6 0x000055d5af039f1c clang::tidy::bugprone::ArgumentCommentCheck::checkCallArgs(clang::ASTContext*, clang::FunctionDecl const*, clang::SourceLocation, llvm::ArrayRef<clang::Expr const*>) (/home/x/llvm/bin/clang-tidy+0x2fb9f1c)
 #7 0x000055d5aed28af0 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::MatchVisitor::visitMatch(clang::ast_matchers::BoundNodes const&) ASTMatchFinder.cpp:0:0
 #8 0x000055d5aed5587c clang::ast_matchers::internal::BoundNodesTreeBuilder::visitMatches(clang::ast_matchers::internal::BoundNodesTreeBuilder::Visitor*) (/home/x/llvm/bin/clang-tidy+0x2cd587c)
 #9 0x000055d5aed2855e clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::DynTypedNode const&) ASTMatchFinder.cpp:0:0
#10 0x000055d5aed3a3c5 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseCompoundStmt(clang::CompoundStmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*>>>>*) ASTMatchFinder.cpp:0:0
#11 0x000055d5aed37d88 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*>>>>*) ASTMatchFinder.cpp:0:0
#12 0x000055d5aed37c5f clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*>>>>*) ASTMatchFinder.cpp:0:0
#13 0x000055d5aed552d3 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionHelper(clang::FunctionDecl*) ASTMatchFinder.cpp:0:0
#14 0x000055d5aed309b2 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseFunctionDecl(clang::FunctionDecl*) ASTMatchFinder.cpp:0:0
#15 0x000055d5aed2b63e clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#16 0x000055d5aed3302b clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseTranslationUnitDecl(clang::TranslationUnitDecl*) ASTMatchFinder.cpp:0:0
#17 0x000055d5aed2b8fc clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) ASTMatchFinder.cpp:0:0
#18 0x000055d5aecfe74a clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) (/home/x/llvm/bin/clang-tidy+0x2c7e74a)
#19 0x000055d5b0006ebc clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/x/llvm/bin/clang-tidy+0x3f86ebc)
#20 0x000055d5b01d97b1 clang::ParseAST(clang::Sema&, bool, bool) (/home/x/llvm/bin/clang-tidy+0x41597b1)
#21 0x000055d5aff8bad9 clang::FrontendAction::Execute() (/home/x/llvm/bin/clang-tidy+0x3f0bad9)
#22 0x000055d5afefa406 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/x/llvm/bin/clang-tidy+0x3e7a406)
#23 0x000055d5ae84df3b clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (/home/x/llvm/bin/clang-tidy+0x27cdf3b)
#24 0x000055d5ae88cf12 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef)::ActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) ClangTidy.cpp:0:0
#25 0x000055d5ae84dcc1 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) (/home/x/llvm/bin/clang-tidy+0x27cdcc1)
#26 0x000055d5ae84ccb0 clang::tooling::ToolInvocation::run() (/home/x/llvm/bin/clang-tidy+0x27cccb0)
#27 0x000055d5ae84f4fb clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (/home/x/llvm/bin/clang-tidy+0x27cf4fb)
#28 0x000055d5ae8882f2 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef) (/home/x/llvm/bin/clang-tidy+0x28082f2)
#29 0x000055d5ae7a07e4 clang::tidy::clangTidyMain(int, char const**) (/home/x/llvm/bin/clang-tidy+0x27207e4)
#30 0x00007f08ba029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#31 0x00007f08ba029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#32 0x000055d5ae79b69a _start (/home/x/llvm/bin/clang-tidy+0x271b69a)
Segmentation fault
ninja: build stopped: subcommand failed.
```
I hope this helps!

**Comment by carlosgalvezp** [comment] 2023-04-07 21:29
Closing since the problem is no longer reproducible on clang-tidy 16

**Closed by carlosgalvezp** 2023-04-07 21:29 UTC
Labels: clang-tidy, crash
