### ISSUE TITLE
Assertion failed: (isSCEVable(Ty) && "Type is not SCEVable!"), function getTypeSizeInBits, file llvm/lib/Analysis/ScalarEvolution.cpp, line 3976.

### ISSUE THREAD

**Issue by DimitryAndric** [llvm/llvm-project#52697] opened 2021-12-14 18:07 UTC
Run with `llc -O1` or higher, having assertions enabled:

```
; ModuleID = 'bugpoint-reduced-simplified.bc'
source_filename = "read_termcap-min.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-unknown"

define dso_local void @e() local_unnamed_addr {
entry:
  %c = alloca [0 x i8], align 1
  %0 = getelementptr inbounds [0 x i8], [0 x i8]* %c, i64 0, i64 0
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %1 = phi i8* [ %incdec.ptr, %while.cond ], [ %0, %entry ]
  %incdec.ptr = getelementptr inbounds i8, i8* %1, i64 1
  br i1 undef, label %while.cond, label %while.cond2

while.cond2:                                      ; preds = %while.cond2, %while.cond
  %2 = phi i8* [ %incdec.ptr3, %while.cond2 ], [ %incdec.ptr, %while.cond ]
  %incdec.ptr3 = getelementptr inbounds i8, i8* %2, i64 1
  br i1 undef, label %while.cond2, label %while.cond.1

while.cond.1:                                     ; preds = %while.cond.1, %while.cond2
  %3 = phi i8* [ %incdec.ptr.1, %while.cond.1 ], [ %incdec.ptr3, %while.cond2 ]
  %incdec.ptr.1 = getelementptr inbounds i8, i8* %3, i64 1
  br i1 undef, label %while.cond.1, label %while.cond2.1

while.cond2.1:                                    ; preds = %while.cond2.1, %while.cond.1
  %4 = phi i8* [ %incdec.ptr3.1, %while.cond2.1 ], [ %incdec.ptr.1, %while.cond.1 ]
  %incdec.ptr3.1 = getelementptr inbounds i8, i8* %4, i64 1
  br i1 undef, label %while.cond2.1, label %while.cond.2

while.cond.2:                                     ; preds = %while.cond.2, %while.cond2.1
  %5 = phi i8* [ %incdec.ptr.2, %while.cond.2 ], [ %incdec.ptr3.1, %while.cond2.1 ]
  %incdec.ptr.2 = getelementptr inbounds i8, i8* %5, i64 1
  br i1 undef, label %while.cond.2, label %while.cond2.2

while.cond2.2:                                    ; preds = %while.cond2.2, %while.cond.2
  %6 = phi i8* [ %incdec.ptr3.2, %while.cond2.2 ], [ %incdec.ptr.2, %while.cond.2 ]
  %incdec.ptr3.2 = getelementptr inbounds i8, i8* %6, i64 1
  br i1 undef, label %while.cond2.2, label %while.cond.3

while.cond.3:                                     ; preds = %while.cond.3, %while.cond2.2
  %7 = phi i8* [ %incdec.ptr.3, %while.cond.3 ], [ %incdec.ptr3.2, %while.cond2.2 ]
  %incdec.ptr.3 = getelementptr inbounds i8, i8* %7, i64 1
  br i1 undef, label %while.cond.3, label %while.cond2.3

while.cond2.3:                                    ; preds = %while.cond2.3, %while.cond.3
  %8 = phi i8* [ %incdec.ptr3.3, %while.cond2.3 ], [ %incdec.ptr.3, %while.cond.3 ]
  %incdec.ptr3.3 = getelementptr inbounds i8, i8* %8, i64 1
  br i1 undef, label %while.cond2.3, label %while.cond.4

while.cond.4:                                     ; preds = %while.cond.4, %while.cond2.3
  %9 = phi i8* [ %incdec.ptr.4, %while.cond.4 ], [ %incdec.ptr3.3, %while.cond2.3 ]
  %incdec.ptr.4 = getelementptr inbounds i8, i8* %9, i64 1
  br i1 undef, label %while.cond.4, label %while.cond2.4

while.cond2.4:                                    ; preds = %while.cond2.4, %while.cond.4
  %10 = phi i8* [ %incdec.ptr3.4, %while.cond2.4 ], [ %incdec.ptr.4, %while.cond.4 ]
  %incdec.ptr3.4 = getelementptr inbounds i8, i8* %10, i64 1
  br i1 undef, label %while.cond2.4, label %while.cond.5

while.cond.5:                                     ; preds = %while.cond.5, %while.cond2.4
  %11 = phi i8* [ %incdec.ptr.5, %while.cond.5 ], [ %incdec.ptr3.4, %while.cond2.4 ]
  %incdec.ptr.5 = getelementptr inbounds i8, i8* %11, i64 1
  br i1 undef, label %while.cond.5, label %while.cond2.5

while.cond2.5:                                    ; preds = %while.cond2.5, %while.cond.5
  %12 = phi i8* [ %incdec.ptr3.5, %while.cond2.5 ], [ %incdec.ptr.5, %while.cond.5 ]
  %incdec.ptr3.5 = getelementptr inbounds i8, i8* %12, i64 1
  br i1 undef, label %while.cond2.5, label %while.cond.6

while.cond.6:                                     ; preds = %while.cond.6, %while.cond2.5
  %13 = phi i8* [ %incdec.ptr.6, %while.cond.6 ], [ %incdec.ptr3.5, %while.cond2.5 ]
  %incdec.ptr.6 = getelementptr inbounds i8, i8* %13, i64 1
  br i1 undef, label %while.cond.6, label %while.cond2.6

while.cond2.6:                                    ; preds = %while.cond2.6, %while.cond.6
  %14 = phi i8* [ %incdec.ptr3.6, %while.cond2.6 ], [ %incdec.ptr.6, %while.cond.6 ]
  %incdec.ptr3.6 = getelementptr inbounds i8, i8* %14, i64 1
  br i1 undef, label %while.cond2.6, label %while.cond.7

while.cond.7:                                     ; preds = %while.cond.7, %while.cond2.6
  %15 = phi i8* [ %incdec.ptr.7, %while.cond.7 ], [ %incdec.ptr3.6, %while.cond2.6 ]
  %incdec.ptr.7 = getelementptr inbounds i8, i8* %15, i64 1
  br i1 undef, label %while.cond.7, label %while.cond2.7

while.cond2.7:                                    ; preds = %while.cond2.7, %while.cond.7
  %16 = phi i8* [ %incdec.ptr3.7, %while.cond2.7 ], [ %incdec.ptr.7, %while.cond.7 ]
  %incdec.ptr3.7 = getelementptr inbounds i8, i8* %16, i64 1
  br i1 undef, label %while.cond2.7, label %while.cond.8

while.cond.8:                                     ; preds = %while.cond.8, %while.cond2.7
  %17 = phi i8* [ %incdec.ptr.8, %while.cond.8 ], [ %incdec.ptr3.7, %while.cond2.7 ]
  %incdec.ptr.8 = getelementptr inbounds i8, i8* %17, i64 1
  br i1 undef, label %while.cond.8, label %while.cond2.8

while.cond2.8:                                    ; preds = %while.cond2.8, %while.cond.8
  %18 = phi i8* [ %incdec.ptr3.8, %while.cond2.8 ], [ %incdec.ptr.8, %while.cond.8 ]
  %incdec.ptr3.8 = getelementptr inbounds i8, i8* %18, i64 1
  br i1 undef, label %while.cond2.8, label %while.cond.9

while.cond.9:                                     ; preds = %while.cond.9, %while.cond2.8
  %19 = phi i8* [ %incdec.ptr.9, %while.cond.9 ], [ %incdec.ptr3.8, %while.cond2.8 ]
  %incdec.ptr.9 = getelementptr inbounds i8, i8* %19, i64 1
  br i1 undef, label %while.cond.9, label %while.cond2.9

while.cond2.9:                                    ; preds = %while.cond2.9, %while.cond.9
  %20 = phi i8* [ %incdec.ptr3.9, %while.cond2.9 ], [ %incdec.ptr.9, %while.cond.9 ]
  %incdec.ptr3.9 = getelementptr inbounds i8, i8* %20, i64 1
  br i1 undef, label %while.cond2.9, label %while.cond.10

while.cond.10:                                    ; preds = %while.cond.10, %while.cond2.9
  %21 = phi i8* [ %incdec.ptr.10, %while.cond.10 ], [ %incdec.ptr3.9, %while.cond2.9 ]
  %incdec.ptr.10 = getelementptr inbounds i8, i8* %21, i64 1
  br i1 undef, label %while.cond.10, label %while.cond2.10

while.cond2.10:                                   ; preds = %while.cond2.10, %while.cond.10
  %22 = phi i8* [ %incdec.ptr3.10, %while.cond2.10 ], [ %incdec.ptr.10, %while.cond.10 ]
  %incdec.ptr3.10 = getelementptr inbounds i8, i8* %22, i64 1
  br i1 undef, label %while.cond2.10, label %while.cond.11

while.cond.11:                                    ; preds = %while.cond.11, %while.cond2.10
  %23 = phi i8* [ %incdec.ptr.11, %while.cond.11 ], [ %incdec.ptr3.10, %while.cond2.10 ]
  %incdec.ptr.11 = getelementptr inbounds i8, i8* %23, i64 1
  br i1 undef, label %while.cond.11, label %while.cond2.11

while.cond2.11:                                   ; preds = %while.cond2.11, %while.cond.11
  %24 = phi i8* [ %incdec.ptr3.11, %while.cond2.11 ], [ %incdec.ptr.11, %while.cond.11 ]
  %incdec.ptr3.11 = getelementptr inbounds i8, i8* %24, i64 1
  br i1 undef, label %while.cond2.11, label %while.cond.12

while.cond.12:                                    ; preds = %while.cond.12, %while.cond2.11
  %25 = phi i8* [ %incdec.ptr.12, %while.cond.12 ], [ %incdec.ptr3.11, %while.cond2.11 ]
  %incdec.ptr.12 = getelementptr inbounds i8, i8* %25, i64 1
  br i1 undef, label %while.cond.12, label %while.cond2.12

while.cond2.12:                                   ; preds = %while.cond2.12, %while.cond.12
  %26 = phi i8* [ %incdec.ptr3.12, %while.cond2.12 ], [ %incdec.ptr.12, %while.cond.12 ]
  %incdec.ptr3.12 = getelementptr inbounds i8, i8* %26, i64 1
  br i1 undef, label %while.cond2.12, label %while.cond.13

while.cond.13:                                    ; preds = %while.cond.13, %while.cond2.12
  %27 = phi i8* [ %incdec.ptr.13, %while.cond.13 ], [ %incdec.ptr3.12, %while.cond2.12 ]
  %incdec.ptr.13 = getelementptr inbounds i8, i8* %27, i64 1
  br i1 undef, label %while.cond.13, label %while.cond2.13

while.cond2.13:                                   ; preds = %while.cond2.13, %while.cond.13
  %28 = phi i8* [ %incdec.ptr3.13, %while.cond2.13 ], [ %incdec.ptr.13, %while.cond.13 ]
  %incdec.ptr3.13 = getelementptr inbounds i8, i8* %28, i64 1
  br i1 undef, label %while.cond2.13, label %while.cond.14

while.cond.14:                                    ; preds = %while.cond.14, %while.cond2.13
  %29 = phi i8* [ %incdec.ptr.14, %while.cond.14 ], [ %incdec.ptr3.13, %while.cond2.13 ]
  %incdec.ptr.14 = getelementptr inbounds i8, i8* %29, i64 1
  br i1 undef, label %while.cond.14, label %while.cond2.14

while.cond2.14:                                   ; preds = %while.cond2.14, %while.cond.14
  %30 = phi i8* [ %incdec.ptr3.14, %while.cond2.14 ], [ %incdec.ptr.14, %while.cond.14 ]
  %incdec.ptr3.14 = getelementptr inbounds i8, i8* %30, i64 1
  br i1 undef, label %while.cond2.14, label %while.cond.15

while.cond.15:                                    ; preds = %while.cond.15, %while.cond2.14
  %31 = phi i8* [ %incdec.ptr.15, %while.cond.15 ], [ %incdec.ptr3.14, %while.cond2.14 ]
  %incdec.ptr.15 = getelementptr inbounds i8, i8* %31, i64 1
  br i1 undef, label %while.cond.15, label %while.cond2.15

while.cond2.15:                                   ; preds = %while.cond2.15, %while.cond.15
  %32 = phi i8* [ %incdec.ptr3.15, %while.cond2.15 ], [ %incdec.ptr.15, %while.cond.15 ]
  %incdec.ptr3.15 = getelementptr inbounds i8, i8* %32, i64 1
  br i1 undef, label %while.cond2.15, label %while.cond.16

while.cond.16:                                    ; preds = %while.cond.16, %while.cond2.15
  %33 = phi i8* [ %incdec.ptr.16, %while.cond.16 ], [ %incdec.ptr3.15, %while.cond2.15 ]
  %incdec.ptr.16 = getelementptr inbounds i8, i8* %33, i64 1
  %34 = load i8, i8* %incdec.ptr.16, align 1
  br label %while.cond.16
}
```

**Comment by preames** [comment] 2021-12-14 20:47
Just noting that the IR above triggers with opt -loop-reduce as well.  i.e. this is definitely an issue reachable through LSR.

**Comment by caojoshua** [comment] 2023-01-15 05:40
Looks like its passing since LLVM 14, and failing in 13. https://godbolt.org/z/sPGv1WPd5. 

As noted in https://reviews.llvm.org/D109789, the issue was produced with LLVM 13.

**Comment by fhahn** [comment] 2023-01-15 11:40
Thanks for checking @caojoshua, it looks like this has been fixed in current `main`. I think it is time to close this, @DimitryAndric please double-check on your end and update the reproducer if the issue can still be reproduced.

**Closed by fhahn** 2023-01-15 11:40 UTC
Labels: new issue

**Comment by DimitryAndric** [comment] 2023-01-15 13:30
The assertion has disappeared as of 903c3d2863b9d0ae760a2f45e0e934f1d12cd1d4 ("[SCEVExpander] Always use i8 GEP for reused value offset") by @nikic, but I'm unsure whether it is actually supposed to fix it, or merely papers over it...
