### ISSUE TITLE
[clang-format] git-clang-format not skipping files mentioned ".clang-format-ignore"

### ISSUE THREAD

**Issue by rajkumar38** [llvm/llvm-project#112170] opened 2024-10-14 08:39 UTC
Use case is to have some files that are part of git and have fixed formatting and for such files we have entry in ".clang-format-ignore".
NOTE: clang-format-ignore works with explicit clang-format command.

version: Ubuntu clang-format version 18.1.8

**Comment by owenca** [comment] 2024-10-15 04:11
Duplicate of #102459.

**Closed by owenca** 2024-10-15 04:11 UTC
Labels: duplicate, clang-format
