### ISSUE TITLE
[AMDGPU][MC] image_atomic instructions do not support tfe

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#48190] opened 2021-01-22 14:49 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [48846](https://llvm.org/bz48846) |
| Version | trunk |
| OS | All |

## Extended Description 
The following image atomic instructions are legal and may be assembled by sp3 w/o any issues:

    image_atomic_add v[5:6], v252, s[8:15] dmask:0x1 tfe
    image_atomic_add v[5:7], v252, s[8:15] dmask:0x3 tfe
    image_atomic_cmpswap v[5:7], v252, s[8:15] dmask:0x3 tfe
    image_atomic_cmpswap v[5:9], v252, s[8:15] dmask:0xf tfe

However only the first one may be assembled by llvm assembler and only for GFX7-GFX9. For GFX10 all of these fail to assemble.

**Comment by jwanggit86** [comment] 2024-05-08 22:29
GFX10 introduced a non-optional operand "dim" for the image_atomic instructions. The above fail to parse because the "dim" operand is missing. Therefore, this is expected behavior.

**Comment by arsenm** [comment] 2024-05-09 09:11
> GFX10 introduced a non-optional operand "dim" for the image_atomic instructions. The above fail to parse because the "dim" operand is missing. Therefore, this is expected behavior.

So should this be closed as invalid?

**Comment by dpreobra** [comment] 2024-05-09 10:58
Unfortunately adding a “dim” operand does not change anything. The code below worked for sp3 but not for llvm:

`image_atomic_add v[5:6], v252, s[8:15] dmask:0x1 dim:SQ_RSRC_IMG_1D tfe`

**Comment by jwanggit86** [comment] 2024-05-15 17:40
I've tested the above 5 instructions. Here are the results.
```
image_atomic_add v[5:6], v252, s[8:15] dmask:0x1 tfe
GFX900: ok;  GFX1010: fail; matches wrong instruction due to missing 'dim'
sp3: both GFX9 and GFX10 ok

image_atomic_add v[5:7], v252, s[8:15] dmask:0x3 tfe
GFX900: fail at v[5:7];  GFX1010: fail at v[5:7]
sp3: both GFX9 and GFX10 ok

image_atomic_cmpswap v[5:7], v252, s[8:15] dmask:0x3 tfe
GFX900: fail at v[5:7];  GFX1010: fail at v[5:7]
sp3: both GFX9 and GFX10 ok

image_atomic_cmpswap v[5:9], v252, s[8:15] dmask:0xf tfe
GFX900: fail at v[5:9]; GFX1010: fail at v[5:9]
sp3: both GFX9 and GFX10 are ok

image_atomic_add v[5:6], v252, s[8:15] dmask:0x1 dim:SQ_RSRC_IMG_1D tfe
GFX1010: ok
```

**Comment by jwanggit86** [comment] 2024-05-16 23:18
A brief analysis of the problem:

In MIMGInstructions.td, (1) for non-cmpswap instructions, the dst reg RCs can only be VReg_32 or VReg_64. When dmask=0x3, and tfe is specified, it would require a VReg_96. Therefore, the parsing fails. (2) for cmpswap, the dst reg RCs can only be VReg_64 or VReg_128. When tfe is specified, either VReg_96 is required (when dmask=0x3) or VReg_160 is required (when dmask=0xf).

**Comment by jwanggit86** [comment] 2024-05-16 23:20
A PR has been created: [92469](https://github.com/llvm/llvm-project/pull/92469)

**Closed** 2024-06-04 18:41 UTC
Labels: backend:AMDGPU, bugzilla
