### ISSUE TITLE
InstSimplify unconditionally executed trapping constant expression in phi fold

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#49839] opened 2021-05-26 19:17 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [50495](https://llvm.org/bz50495) |
| Version | trunk |
| OS | All |
| CC | @rotateright |

## Extended Description 
[585] % clangtk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5dd86aadf0b014913bd35bb7435808eb081bc049)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
[586] %
[586] % clangtk -O2 small.c; ./.aout
bash: ./.aout: No such file or directory
[587] %
[587] %
[587] % clangtk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5dd86aadf0b014913bd35bb7435808eb081bc049)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
clang-13: warning: argument unused during compilation: '-I /usr/local/include/csmith' [-Wunused-command-line-argument]
[588] %
[588] % clangtk -O2 small.c; ./a.out
[589] %
[589] % clangtk -O3 small.c
[590] % ./a.out
Floating point exception
[591] %
[591] % cat small.c

```c
int a, b, e[2], f;
static char c, d, *g = &c, **h = &g;
char i(char j, char k) { return k ? j % k : 0; }
int main() {
  int *l = &e[1];
  for (; d < 1; d++) {
    int *m = &a, *o = &e[1];
    **h = l == m;
    char ***n[2] = {&h, &h};
    for (; b < 4; ++b)
      if (f != 1)
        *o = i(1, *g);
  }
  return 0;
}
```

**Comment by fhahn** [comment] 2022-03-22 11:40
The culprit seems to be `instsimplify`: https://godbolt.org/z/9xW8d3a1e

For the input, it sinks the `srem` to the a constant expression in the phi node in the successor block, which will then be unconditionally executed after lowering in the backend. The transformation is invalid according to Alive2
```
@e = external global [2 x i32]
@a = external global i32

define <2 x i8> @main(i1 %c) {
entry:
  br i1 %c, label %then, label %exit

then:
  %srem = srem i8 1, zext (i1 icmp eq (i32* getelementptr inbounds ([2 x i32], [2 x i32]* @e, i64 0, i64 1), i32* @a) to i8)
  %ins = insertelement <2 x i8> zeroinitializer, i8 %srem, i64 0
  br label %exit

exit:
  %p = phi <2 x i8> [ zeroinitializer, %entry ], [ %ins, %then ]
  ret <2 x i8> %p
}
```

**Comment by fhahn** [comment] 2022-03-22 12:39
I *think* `instsimplify` shouldn't move the code, but I'm tagging a couple of people for additional opinions about movement of constant expressions that may trap. @nikic @nunoplopes @preames @rotateright @LebedevRI

**Comment by nikic** [comment] 2022-03-22 13:11
Hm, I'm not so sure here. Intuitively I would say this transform is correct, because phi values are materialized on the incoming edge, not in the phi block. LangRef says:

> For the purposes of the SSA form, the use of each incoming value is deemed to occur on the edge from the corresponding predecessor block to the current block (but after any definition of an ‘invoke’ instruction’s return value on the same edge).

I would say it's a backend bug if the backend materializes a trapping constant expression in the phi block. It should happen on the edge (possibly a split critical edge).

But then alive2 says the transform is not valid, so possibly my understanding of the semantics is not correct.

**Comment by nikic** [comment] 2022-03-22 13:19
Thinking about this a bit more, I think this transform *must* be valid, otherwise doing RAUW with a constant folding result would be illegal, which would be very bad. I think the alive2 modelling isn't correct in this instance, because it places the constexpr evaluation in the wrong block.

**Comment by LebedevRI** [comment] 2022-03-22 13:50
I agree that as per langref the backend is at fault here.
Filed https://github.com/AliveToolkit/alive2/issues/781

**Comment by nunoplopes** [comment] 2022-03-22 15:38
What if a phi BB's predecessor has multiple successors?
There's no execution on an edge, only on BBs. Do we assume the execution happens in the predecessor on in an imaginary BB in-between?
e.g.:
```
br %cond, then, else

then:
phi [ div... ]
```

is this the same as:
```
%x = div ...
br %cond, then, else

then:
phi [ %x ]
```

or:
```
br %cond, then_0, else

then_0:
%x = div ...
br then

then:
phi [ %x ]
```

**Comment by nikic** [comment] 2022-03-22 15:59
@nunoplopes The latter. If the edge is critical, it needs to be split.

**Comment by nunoplopes** [comment] 2022-03-22 16:54
> @nunoplopes The latter. If the edge is critical, it needs to be split.

Thank you, makes sense! Let me try to implement that in Alive2..

**Comment by nikic** [comment] 2022-04-12 15:21
I looked a bit closer into the original reproducer, and the problem here is in InstSimplify after all, just in a different place:
 ```
@g = extern_weak global i32

define i64 @test(i1 %c) {
entry:
  br i1 %c, label %if, label %join

if:
  br label %join

join:
  %phi = phi i64 [ poison, %if ], [ srem (i64 1, i64 ptrtoint (i32* @g to i64)) , %entry ]
  ret i64 %phi
}

; RUN: opt -S -instsimplify < %s

@g = extern_weak global i32

define i64 @test(i1 %c) {
entry:
  br i1 %c, label %if, label %join

if:                                               ; preds = %entry
  br label %join

join:                                             ; preds = %if, %entry
  ret i64 srem (i64 1, i64 ptrtoint (i32* @g to i64))
}
```

The phi with poison fold ends up executing the constant expression unconditionally, rather than only on one branch.

**Comment by zhendongsu** [comment] 2022-06-12 19:52
It looks like the original C test still fails:
```
[526] % clangtk -v
clang version 15.0.0 (https://github.com/llvm/llvm-project.git d941d597837d9e1405086f008c9bd6a71e7263c9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version 11.0
[527] % 
[527] % clangtk -O3 49839.c
[528] % ./a.out
Floating point exception
[529] % 
[529] % cat 49839.c 
int a, b, e[2], f;
static char c, d, *g = &c, **h = &g;
char i(char j, char k) { return k ? j % k : 0; }
int main() {
  int *l = &e[1];
  for (; d < 1; d++) {
    int *m = &a, *o = &e[1];
    **h = l == m;
    char ***n[2] = {&h, &h};
    for (; b < 4; ++b)
      if (f != 1)
        *o = i(1, *g);
  }
  return 0;
}
```

Compiler Explorer: https://godbolt.org/z/f5G5r16x5

@nikic
@fhahn

**Comment by nunoplopes** [comment] 2022-06-12 20:22
According to alivecc, this is a bug in InstSimplify.
It seems that we have a constant expression with an `srem` in a phi node, which gets hoisted and ends up triggering UB.
Something like:
```llvm
%pred.srem.continue_%pred.srem.continue20:
  %__constexpr_34 = gep inbounds ptr @e, 8 x i64 0, 4 x i64 1
  %__constexpr_33 = icmp eq ptr %__constexpr_34, @a
  %__constexpr_32 = zext i1 %__constexpr_33 to i8 ; 0
  %__constexpr_31 = srem i8 1, %__constexpr_32  ; UB
  %__copy_1 = <4 x i8> { %__constexpr_31, poison, poison, poison }
  br label %pred.srem.continue20
```

We may need c-smith + alivecc to minimize this thing (@regehr).

**Comment by nunoplopes** [comment] 2022-06-12 20:37
The code looks good, I dunno where the bug might be: https://github.com/llvm/llvm-project/blob/b8c2781ff60126b8c7c11ed0dab90d0640a17d4f/llvm/lib/Analysis/InstructionSimplify.cpp#L4847-L4851

**Comment by nunoplopes** [comment] 2022-06-13 09:11
Reduced test case:
```llvm
@e = external global [2 x i32]
@a = external global i32

define i8 @main() {
pred.srem.continue8:
  br i1 false, label %pred.srem.if9, label %pred.srem.continue10

pred.srem.if9:
  %sr = srem i8 1, zext (i1 icmp eq (ptr getelementptr inbounds ([2 x i32], ptr @e, i64 0, i64 1), ptr @a) to i8)
  %v = insertelement <4 x i8> zeroinitializer, i8 %sr, i64 3
  br label %pred.srem.continue10

pred.srem.continue10:
  %phi = phi <4 x i8> [ poison, %pred.srem.continue8 ], [ %v, %pred.srem.if9 ]
  %r = extractelement <4 x i8> %phi, i64 3
  br label %middle.block

middle.block:
  ret i8 %r
}
```

InstSimplify changes:
```diff
@@ -6,15 +6,11 @@
   br i1 false, label %pred.srem.if9, label %pred.srem.continue10

 pred.srem.if9:
-  %sr = srem i8 1, zext (i1 icmp eq (ptr getelementptr inbounds ([2 x i32], ptr @e, i64 0, i64 1), ptr @a) to i8)
-  %v = insertelement <4 x i8> zeroinitializer, i8 %sr, i64 3
   br label %pred.srem.continue10

 pred.srem.continue10:
-  %phi = phi <4 x i8> [ poison, %pred.srem.continue8 ], [ %v, %pred.srem.if9 ]
-  %r = extractelement <4 x i8> %phi, i64 3
   br label %middle.block

 middle.block:
-  ret i8 %r
+  ret i8 srem (i8 1, i8 zext (i1 icmp eq (ptr getelementptr inbounds ([2 x i32], ptr @e, i64 0, i64 1), ptr @a) to i8))
 }
```

**Comment by nikic** [comment] 2022-06-13 09:17
This is because I only checked for `ConstantExpr` in https://github.com/llvm/llvm-project/blob/8ab925a2fdcf857edf16d9cb104c9007965e025c/llvm/lib/Analysis/InstructionSimplify.cpp#L4849, but this should be done for all `Constant`. In this case it's a trapping constant expression inside an aggregate constant.

**Comment by nikic** [comment] 2022-06-13 10:38
Okay, this was a bit trickier than expected, because the `canTrap()` API itself also didn't account for constant aggregates. The second InstSimplify issue is fixed with https://github.com/llvm/llvm-project/commit/7e64a29e58382b2616096d64a39c38075e51ebc3.

...however, testing the original C reproducer just now, it still fails, so there must be another issue somewhere.

**Comment by zhendongsu** [comment] 2022-06-13 11:07
Perhaps https://github.com/llvm/llvm-project/issues/55999 is also related although it doesn't reproduce with 13.* and 14.*?

**Comment by nunoplopes** [comment] 2022-06-13 11:14
@zhendongsu it's hard to tell without looking at the IR. You can use `clang -S -emit-llvm` + llvm-reduce to reduce at LLVM IR level. Alive2 can then tell you which optimization is wrong.
Anyway, just saying that it would be really nice if you guys switched your infrastructure to report bugs in LLVM IR, not C, as the minimal repro in LLVM IR is often much smaller than the C equivalent.

**Comment by nunoplopes** [comment] 2022-06-13 11:29
It's SimplifyCFG now:
```llvm
@e = external global [2 x i32]
@a = external global i32

define i32 @main(i1 %0) {
vector.body:
  br i1 %0, label %pred.srem.if, label %pred.srem.continue

pred.srem.if:
  br label %pred.srem.continue

pred.srem.continue:
  %1 = phi <4 x i8> [ zeroinitializer, %vector.body ], [ <i8 srem (i8 1, i8 zext (i1 icmp eq (ptr getelementptr inbounds ([2 x i32], ptr @e, i64 0, i64 1), ptr @a) to i8)), i8 poison, i8 poison, i8 poison>, %pred.srem.if ]
  ret i32 0
}
```

gets transformed to:
```llvm
define i32 @main(i1 %0) {
vector.body:
  %spec.select = select i1 %0, <4 x i8> <i8 srem (i8 1, i8 zext (i1 icmp eq (ptr getelementptr inbounds ([2 x i32], ptr @e, i64 0, i64 1), ptr @a) to i8)), i8 poison, i8 poison, i8 poison>, <4 x i8> zeroinitializer
  ret i32 0
}
```

**Comment by nikic** [comment] 2022-06-13 12:29
Yeah, we have quite a few places with the same basic issue, they're checking canTrap() on ConstantExpr rather than Constant.

**Comment by nikic** [comment] 2022-06-13 12:58
Fixed some SimplifyCFG issues in https://github.com/llvm/llvm-project/commit/571c7131444d6e4e92f002e4f136d26087f36810, but the C reproducer is still broken.

I still see an incorrect usage in SelectionDAGIsel, will check if fixing that helps.

**Comment by nikic** [comment] 2022-06-14 15:15
I've put up an RFC to address the root cause: https://discourse.llvm.org/t/rfc-remove-most-constant-expressions/63179

**Comment by nunoplopes** [comment] 2022-07-06 09:18
@nikic fixed this already.

**Closed by nunoplopes** 2022-07-06 09:18 UTC
Labels: bugzilla, miscompilation, ipo, confirmed
