### ISSUE TITLE
[GVNHoist] Common code hoisting of calls

### ISSUE THREAD

**Issue by 470e7f89-017b-4dca-8bb4-aa88c7fd5a01** [llvm/llvm-project#51883] opened 2021-11-18 04:35 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [52541](https://llvm.org/bz52541) |
| Version | trunk |
| OS | Windows NT |
| CC | @efriedma-quic,@rotateright |

## Extended Description 
The common call to foo() in this below code is hoisted above the if-else.
```
void A(int x) {
    if(x < 0) { // arbitrary condition...
        foo();
        bar();
    } else {
        foo();
        baz();
    }
}
```

This transformation is missed in the following code:

```
void B(int x) {
    if(x < 0) { // arbitrary condition...
        foo();
        bar();
    } else if(x % 2 == 0) { // arbitrary condition...
        foo();
        baz();
    } else {
        foo();
        boz();
    }
}
```

Which is only transformed to

```
void B(int x) {
    if(x < 0) { // arbitrary condition...
        foo();
        bar();
    } else {
        foo();
        if(x % 2 == 0) { // arbitrary condition...
            baz();
        } else {
            boz();
        }
    }
}
```

https://godbolt.org/z/qjjMYWb8o

This is also missed on switches.

This isn't just missed on function calls, it is missed with arithmetic as well:

```
void B(int x, int y) {
    if(x < 0) { // arbitrary condition...
        foo(x / y);
    } else if(x % 2 == 0) { // arbitrary condition...
        bar(x / y);
    } else {
        baz(x / y);
    }
}
```

Transforms to:

```
void B(int x, int y) {
    if(x < 0) { // arbitrary condition...
        int v = x / y;
        foo(v);
    } else {
        int v = x / y;
        if(x % 2 == 0) { // arbitrary condition...
            bar(v);
        } else {
            baz(v);
        }
    }
}
```

https://godbolt.org/z/vTYj75cx6

It seems there is room for improvement and generalization in this transformation.

**Comment by hiraditya** [comment] 2022-03-30 14:35
Enabling gvn-hoist would hoist the instruction.
```
void foo(int), bar(int), baz(int), boz(int), biz(int), buz(int);
void B(int x, int y) {
    if (x < 0) { // arbitrary condition...
        foo(x + y);
    } else if (x % 2 == 0) { // arbitrary condition...
        bar(x + y);
    } else {
        baz(x + y);
    }
}

```

with 

`clang -O3 -emit-llvm -g0 -mllvm -enable-gvn-hoist`

```
define dso_local void @_Z1Bii(i32 noundef %0, i32 noundef %1) local_unnamed_addr #0 {
  %3 = icmp slt i32 %0, 0
  br i1 %3, label %4, label %6

4:                                                ; preds = %2
  %5 = add nsw i32 %1, %0
  tail call void @_Z3fooi(i32 noundef %5)
  br label %12

6:                                                ; preds = %2
  %7 = and i32 %0, 1
  %8 = icmp eq i32 %7, 0
  %9 = add nsw i32 %1, %0
  br i1 %8, label %10, label %11

10:                                               ; preds = %6
  tail call void @_Z3bari(i32 noundef %9)
  br label %12

11:                                               ; preds = %6
  tail call void @_Z3bazi(i32 noundef %9)
  br label %12

12:                                               ; preds = %10, %11, %4
  ret void
}
```

**Comment by hiraditya** [comment] 2024-05-28 21:54
closing this as gvn-hoist works as intended. Feel free to re-open if anything else remains to be done for this ticket.

**Closed by hiraditya** 2024-05-28 21:54 UTC
Labels: bugzilla, llvm:optimizations
