### ISSUE TITLE
`clang-format` and `clang-format --dry-run -Werror` disagree regarding inline namespace

### ISSUE THREAD

**Issue by uyha** [llvm/llvm-project#82246] opened 2024-02-19 13:21 UTC
with the following snippet (`sample.cpp`)
```cpp
namespace name::inline name {
struct {
} a;
}
```

running `clang-format -i sample.cpp` will produce
```cpp
namespace name::inline name {
struct {
} a;
} // namespace name::inline name
```
However, running `clang-format sample.cpp | clang-format --dry-run -Werror` will produce an error saying
![image](https://github.com/llvm/llvm-project/assets/8091245/8fda7007-5397-434c-9e18-b76a668b0386)

**Comment by rymiel** [comment] 2024-02-19 21:46
This was fixed by f2c97ffe4688ba85274146b4c9fc4bcffa92ecbc. Duplicate of #67407. The fix is present in clang-format 18.

**Closed by rymiel** 2024-02-19 21:46 UTC
Labels: clang-format
