### ISSUE TITLE
clang-14 C parser does not accept integer constant 1E6L

### ISSUE THREAD

**Issue by ErichLoew** [llvm/llvm-project#52924] opened 2021-12-30 10:57 UTC
Compiler: clang version 14.0.0 (https://github.com/llvm/llvm-project.git 946eb7a037d5f83ea9cdc99bac0f939ddd344e09)
          Target: x86_64-unknown-linux-gnu
          Thread model: posix
Kernel:   5.15.11 vanilla
Module:   source/drivers/power/reset/ltc2952-poweroff.c
Method:   ltc2952_poweroff_default(struct ltc2952_poweroff *data)
Observations:
  --> Compiles fine with "gcc (GCC) 11.2.0" without changes of source code
  --> clang 14.0.0 fails on original source code --> source code mitigation changes are required.
Mitigation for clang 14.0.0:
  --> Change "1E6L" to "1000000L"

**Comment by nathanchance** [comment] 2021-12-31 21:52
We have been tracking this: https://github.com/ClangBuiltLinux/linux/issues/1497

[The patch](https://lore.kernel.org/r/20211105152049.2522250-1-nathan@kernel.org/) has been [tentatively accepted](https://git.kernel.org/sre/linux-power-supply/c/644106cdb89844be2496b21175b7c0c2e0fab381) but it has not been merged into Linus's tree. I will ping the maintainer on Monday so that we can try to get this resolved before 5.16 releases.

Not really a bug in clang so I think this can be closed out.

**Comment by ErichLoew** [comment] 2022-01-01 19:32
I agree as well, not a clang bug, interesting the Latest GNU eats it, even with -Wall. So we have maybe found a gcc bug?

Best,
Erich

**Comment by nathanchance** [comment] 2022-01-02 04:56
Yes, I noted that in the issue I linked above. It seems like GCC sees that the floating point literal is passed to an integer parameter and just implicitly converts it without a warning, which is definitely surprising: https://godbolt.org/z/rfjb5b4rM

Not really sure that qualifies as a bug but could be a feature request to them.

**Comment by erichkeane** [comment] 2022-01-09 16:15
I'm not terribly surprised.  GCC does a lot of its platform-based diagnostics in their backend-code-generation (IIRC), so situations like this that either the constant folder or optimizer removes don't get diagnosed.  This can mean that the optimization-settings can change the legality of the program.

**Comment by ErichLoew** [comment] 2022-01-09 21:14
Hi Erich,

you are fully right.
I‘ll perform next Kernel build run with -O1.

And I looked now closer, clang is strict and hence complains on implicit casting from 1E6L to int, prefixing with (int) or saying 1000000u is fine for clang and GCC. 

Linux code is sometimes at level of work-outs from Hieronymus Bosch or H.R. Giger…

Best
Erich

**Comment by Endilll** [comment] 2023-08-30 18:44
As mentioned above, this is not a bug on Clang side, and linked issue suggests that this was accepted to kernel.

**Closed by Endilll** 2023-08-30 18:44 UTC
Labels: invalid, clang:diagnostics
