### ISSUE TITLE
clang-format  v19.1.5 crash

### ISSUE THREAD

**Issue by haiboxia007** [llvm/llvm-project#120050] opened 2024-12-16 08:03 UTC
clang-format format "json.hpp" crash
---------------------------------------

Error Informations from clang-format output

Formatting [1/1] .\json.hpp
LLVM ERROR: out of memory
Allocation failed
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\DevTools\\bin\\clang-format --style=file -i --verbose .\\json.hpp
Exception Code: 0xC000001D
LLVM ERROR: out of memory
Allocation failed
Formatting [1/1] .\json_fwd.hpp

json.hpp from JSON for Modern C++, nlohmann-json https://github.com/nlohmann/json, single header, size: 919975 bytes

**Comment by owenca** [comment] 2024-12-16 16:17
Duplicate of #48863

**Closed by owenca** 2024-12-16 16:17 UTC
Labels: duplicate, clang-format, crash
