### ISSUE TITLE
`auto(x)` fails to be recognized as decay copy in some contexts (cannot compile libstdc++ 13.1.1 ranges)

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#62531] opened 2023-05-03 19:50 UTC
Given the following presumably valid C++20 code:

```cpp
int f() {
	int x;
	return (auto(x));
}
```

clang rejects with

```console
<source>:3:15: error: type-id cannot have a name
        return (auto(x));
                     ^
<source>:3:18: error: expected expression
        return (auto(x));
                        ^
2 errors generated.
Compiler returned: 1
```

See it live: https://godbolt.org/z/7qGf7qjf1

The effect of this is that including `<ranges>` from libstdc++ 13.1.1 fails to compile.

A slightly more reduced version:

```cpp
int f() {
	int x;
	return auto(x);
}
```

Causes clang to fail with

```console
<source>:3:9: error: 'auto' not allowed here
        return auto(x);
               ^~~~
1 error generated.
Compiler returned: 1
```

See it live: https://godbolt.org/z/59dYojYs7

**Comment by shafik** [comment] 2023-05-03 20:43
Duplicate of https://github.com/llvm/llvm-project/issues/62494 

@cor3ntin is working on this

**Closed** 2023-05-03 20:43 UTC
Labels: clang:frontend
