### ISSUE TITLE
clangd: Included header `<concepts>` incorrectly identified as unused

### ISSUE THREAD

**Issue by wangtz0607** [llvm/llvm-project#75707] opened 2023-12-16 17:52 UTC
## Example

```cpp
#include <concepts>

static_assert(std::same_as<int, int>);
```

## Actual Behavior

![](https://github.com/llvm/llvm-project/assets/25856391/717c6de5-b8fd-41cc-a26f-20073990004c)

Changing `std::same_as` to other concepts defined in `<concepts>` such as `std::derived_from` and `std::convertible_to` yields the same behavior.

## Expected Behavior

`<concepts>` should not be identified as "not used directly" due to the presence of `std::same_as`.

## Environment

**`clangd --version`**:

```
clangd version 17.0.6
Features: linux
Platform: x86_64-unknown-linux-gnu
```

**Compiler flags specified in `compile_commands.json`**: `-std=c++20`.

**Comment by HighCommander4** [comment] 2024-01-31 17:11
This was fixed for clangd 18.

**Comment by HighCommander4** [comment] 2024-01-31 17:14
It was fixed by https://github.com/llvm/llvm-project/issues/60702.

**Comment by HighCommander4** [comment] 2024-01-31 17:14
Duplicate of https://github.com/llvm/llvm-project/issues/60702

**Closed by HighCommander4** 2024-01-31 17:14 UTC
Labels: clang-include-cleaner
