### ISSUE TITLE
Failed to build LLVM 13 with gcc-9 (CentOS 7 devtoolset-9)

### ISSUE THREAD

**Issue by xkszltl** [llvm/llvm-project#52820] opened 2021-12-21 13:45 UTC
This is specific to 13, 11/12 seems fine.

```
FAILED: projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/cxa_default_handlers.cpp.o 
CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/local/bin/ccache /opt/rh/devtoolset-9/root/usr/bin/g++ -D_DEBUG -D_GNU_SOURCE -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_EXTERN_TEMPLATE -D_LIBCXXABI_BUILDING_LIBRARY -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACR
OS -D__STDC_LIMIT_MACROS -I/media/Scratch/tmp.6RltGbLyX1/llvm/build/projects/libcxxabi/src -I/media/Scratch/tmp.6RltGbLyX1/llvm/libcxxabi/src -I/media/Scratch/tmp.6RltGbLyX1/llvm/build/include -I/media/Scratch/tmp.6RltGbLyX1/llvm/llvm/include -I/media/Sc
ratch/tmp.6RltGbLyX1/llvm/libcxxabi/include -I/media/Scratch/tmp.6RltGbLyX1/llvm/libcxxabi/../libcxx -I/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include -I/media/Scratch/tmp.6RltGbLyX1/llvm/build/projects/pstl/generated_headers -fdebug-prefix-map='/media/S
cratch/tmp.6RltGbLyX1'='/usr/local/src' -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fa
llthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-section
s  -O3 -DNDEBUG -fPIC -nostdinc++ -Werror=return-type -W -Wall -Wchar-subscripts -Wconversion -Wmissing-braces -Wunused-function -Wshadow -Wsign-compare -Wsign-conversion -Wstrict-aliasing=2 -Wstrict-overflow=4 -Wunused-parameter -Wunused-variable -Wwrit
e-strings -Wundef -Wno-suggest-override -Wno-error -pedantic -fstrict-aliasing -funwind-tables -D_DEBUG -UNDEBUG -UNDEBUG -I/media/Scratch/tmp.6RltGbLyX1/llvm/build/include/c++/v1 -std=c++2a -MD -MT projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/cxa
_default_handlers.cpp.o -MF projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/cxa_default_handlers.cpp.o.d -o projects/libcxxabi/src/CMakeFiles/cxxabi_shared.dir/cxa_default_handlers.cpp.o -c /media/Scratch/tmp.6RltGbLyX1/llvm/libcxxabi/src/cxa_default
_handlers.cpp
In file included from /media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h:16,
                 from /media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/__pstl_memory:13,
                 from /media/Scratch/tmp.6RltGbLyX1/llvm/build/include/c++/v1/memory:966,
                 from /media/Scratch/tmp.6RltGbLyX1/llvm/libcxxabi/src/include/atomic_support.h:17,
                 from /media/Scratch/tmp.6RltGbLyX1/llvm/libcxxabi/src/cxa_default_handlers.cpp:18:
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/utils.h:24:15: error: ‘result_of’ in namespace ‘std’ does not name a template type
   24 | typename std::result_of<_Fp()>::type
      |               ^~~~~~~~~
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/utils.h:24:24: error: expected unqualified-id before ‘<’ token
   24 | typename std::result_of<_Fp()>::type
      |                        ^
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/utils.h:66:15: error: ‘result_of’ in namespace ‘std’ does not name a template type
   66 | typename std::result_of<_F1()>::type
      |               ^~~~~~~~~
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/utils.h:66:24: error: expected unqualified-id before ‘<’ token
   66 | typename std::result_of<_F1()>::type
      |                        ^
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/utils.h:73:15: error: ‘result_of’ in namespace ‘std’ does not name a template type
   73 | typename std::result_of<_F2()>::type
      |               ^~~~~~~~~
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/utils.h:73:24: error: expected unqualified-id before ‘<’ token
   73 | typename std::result_of<_F2()>::type
      |                        ^
In file included from /media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/__pstl_memory:13,
                 from /media/Scratch/tmp.6RltGbLyX1/llvm/build/include/c++/v1/memory:966,
                 from /media/Scratch/tmp.6RltGbLyX1/llvm/libcxxabi/src/include/atomic_support.h:17,
                 from /media/Scratch/tmp.6RltGbLyX1/llvm/libcxxabi/src/cxa_default_handlers.cpp:18:
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h: In function ‘__pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator> std::uninitialized_copy(_ExecutionPolicy&&, _InputIterator, _InputIterator
, _ForwardIterator)’:
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h:42:32: error: ‘__invoke_if_else’ is not a member of ‘__pstl::__internal’; did you mean ‘__invoke_if_not’?
   42 |     return __pstl::__internal::__invoke_if_else(
      |                                ^~~~~~~~~~~~~~~~
      |                                __invoke_if_not
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h: In function ‘__pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator> std::uninitialized_copy_n(_ExecutionPolicy&&, _InputIterator, _Size, _Forw
ardIterator)’:
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h:76:32: error: ‘__invoke_if_else’ is not a member of ‘__pstl::__internal’; did you mean ‘__invoke_if_not’?
   76 |     return __pstl::__internal::__invoke_if_else(
      |                                ^~~~~~~~~~~~~~~~
      |                                __invoke_if_not
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h: In function ‘__pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator> std::uninitialized_move(_ExecutionPolicy&&, _InputIterator, _InputIterator
, _ForwardIterator)’:
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h:111:32: error: ‘__invoke_if_else’ is not a member of ‘__pstl::__internal’; did you mean ‘__invoke_if_not’?
  111 |     return __pstl::__internal::__invoke_if_else(
      |                                ^~~~~~~~~~~~~~~~
      |                                __invoke_if_not
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h: In function ‘__pstl::__internal::__enable_if_execution_policy<_ExecutionPolicy, _ForwardIterator> std::uninitialized_move_n(_ExecutionPolicy&&, _InputIterator, _Size, _Forw
ardIterator)’:
/media/Scratch/tmp.6RltGbLyX1/llvm/pstl/include/pstl/internal/glue_memory_impl.h:145:32: error: ‘__invoke_if_else’ is not a member of ‘__pstl::__internal’; did you mean ‘__invoke_if_not’?
  145 |     return __pstl::__internal::__invoke_if_else(
      |                                ^~~~~~~~~~~~~~~~
      |                                __invoke_if_not
```

`result_of` is defined in `<type_traits>`, which is not included by utils.

Here's our build arg: https://github.com/xkszltl/Roaster/blob/81cdf622eaf4d5b7307b2ce532a5a8c3aebb0e09/pkgs/llvm.sh#L28-L86

**Comment by philnik777** [comment] 2023-01-15 06:38
This is a duplicate of #58155. (I guess the other one is a duplicate of this, but the other one describes the actual problem better)

**Closed by philnik777** 2023-01-15 06:38 UTC
Labels: libc++, build-problem

**Comment by xkszltl** [comment] 2023-01-15 10:00
Sure as long as it's well tracked.
