### ISSUE TITLE
Wrong header picked for forward-declared symbol in the presence IWYU-private pragma.

### ISSUE THREAD

**Issue by VitaNuo** [llvm/llvm-project#64248] opened 2023-07-31 08:53 UTC
unrelated_name.h
`struct Foo {};`

internal_header.h
```
// IWYU pragma: private, include "public.h"
struct Foo;
```

all.h
```
#include "internal_header.h"
#include "unrelated_name.h"
```

user.cc
```
#include "all.h"
Foo *f; // triggers an include for "public.h" and not "unrelated_header.h"
```

Note that renaming `unrelated_header.h` to `foo.h` would not have the problem, since `foo.h` and the symbol `Foo` have similar names.

**Comment by kadircet** [comment] 2023-09-06 07:38
duplicate of https://github.com/llvm/llvm-project/issues/62172

**Closed by kadircet** 2023-09-06 07:38 UTC
Labels: clang-include-cleaner
