### ISSUE TITLE
[FR] clang-format option for line breaks after [[attributes]] in function scope

### ISSUE THREAD

**Issue by FalcoGer** [llvm/llvm-project#71563] opened 2023-11-07 17:34 UTC
Currently there is no clang-format option for attributes like `[[maybe_unused]]` or `[[likely]]`. Right now clang-format will always force them onto the same line as the item.

```c++
int main()
{
    [[maybe_unused]]
    int y = 5;

    [[likely]]
    if (5 == 5) {}
    else {}
}
```

will always end up as, with no option to change the behavior

```c++
int main()
{
    [[maybe_unused]] int y = 5;

    [[likely]] if (5 == 5) {}
    else {}
//  ~~~~
//  ^ Different indentation for 'if' and corresponding 'else' (clang-tidy readability-misleading-indentation)
}
```

This is especially bothersome for the `if` because it leads to clang-tidy to report the misleading indentation.

It would be nice if there were an option for line breaks after such attributes.

**Comment by owenca** [comment] 2023-11-09 07:59
The part on attributes before `if` is a duplicate of #64474.

**Closed** 2023-11-10 07:01 UTC
Labels: enhancement, clang-format
