### ISSUE TITLE
Clang frontend crash in CodeGen::CodeGenModule

### ISSUE THREAD

**Issue by ZitongZhouEric** [llvm/llvm-project#94334] opened 2024-06-04 10:43 UTC
To reproduce: https://godbolt.org/z/f5onrb1co
```
static void temp ( ) { } 
int main ( ) { temp ( temp ) ; return 0 ; } 
```
This invalid program crashes the frontend, starting from clang-15 all the way to clang-19 (19 being tested locally)

Stack trace
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-15.0.0/bin/clang -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-12.2.0 -fcolor-diagnostics -fno-crash-diagnostics -emit-llvm -Xclang -disable-llvm-passes <source>
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
 #0 0x0000593956c10de4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000593956c0ec0c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x392ec0c)
 #2 0x0000593956b4ca28 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007a4bfa042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00005939570c19fd replaceUsesOfNonProtoConstant(llvm::Constant*, llvm::Function*) CodeGenModule.cpp:0:0
 #5 0x0000593957113d4d clang::CodeGen::CodeGenModule::GetOrCreateLLVMFunction(llvm::StringRef, llvm::Type*, clang::GlobalDecl, bool, bool, bool, llvm::AttributeList, clang::CodeGen::ForDefinition_t) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x3e33d4d)
 #6 0x0000593957115fbf clang::CodeGen::CodeGenModule::GetAddrOfFunction(clang::GlobalDecl, llvm::Type*, bool, bool, clang::CodeGen::ForDefinition_t) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x3e35fbf)
 #7 0x0000593957116695 clang::CodeGen::CodeGenModule::GetAddrOfGlobal(clang::GlobalDecl, clang::CodeGen::ForDefinition_t) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x3e36695)
 #8 0x000059395711b491 clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x3e3b491)
 #9 0x000059395711d8a9 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x3e3d8a9)
#10 0x0000593957e2f7ca (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#11 0x0000593957e2e23d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x4b4e23d)
#12 0x0000593958ffa1c9 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x5d1a1c9)
#13 0x0000593957e2db25 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x4b4db25)
#14 0x0000593957736031 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x4456031)
#15 0x00005939576bdd33 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x43ddd33)
#16 0x000059395781493b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x453493b)
#17 0x000059395451c5c4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x123c5c4)
#18 0x0000593954515b3b ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#19 0x00005939575277c9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#20 0x0000593956b4cb27 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x386cb27)
#21 0x0000593957527dbc clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#22 0x00005939574f1e2e clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x4211e2e)
#23 0x00005939574f284d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x421284d)
#24 0x00005939574fd69c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x421d69c)
#25 0x000059395451a329 clang_main(int, char**) (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x123a329)
#26 0x00007a4bfa029d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#27 0x00007a4bfa029e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#28 0x000059395451574e _start (/opt/compiler-explorer/clang-15.0.0/bin/clang+0x123574e)
clang-15: error: clang frontend command failed with exit code 135 (use -v to see invocation)
Compiler returned: 135
```

**Comment by EugeneZelenko** [comment] 2024-06-04 13:58
Could you please provide `main` version information that crashes on your side? `main` on GodBolt is OK.

**Comment by dtcxzyw** [comment] 2024-06-04 14:54
I cannot reproduce this issue with 2635d0419e4800c34c7cfea120a12fec8d4878fe.

**Comment by shafik** [comment] 2024-06-04 17:30
Yeah, this looks fixed on trunk.

**Comment by ZitongZhouEric** [comment] 2024-06-04 19:27
> Could you please provide `main` version information that crashes on your side? `main` on GodBolt is OK.

It appears that it's because I'm not using the latest clang-19.  Looks fixed.
```
root@50e8b228d24b:/tmp/crashes# "/tmp/clang-build/build/bin/clang-19" -Xclang -disable-llvm-passes crash_test_june4_3.c 
crash_test_june4_3.c:2:28: warning: too many arguments in call to 'temp'
    2 | int main ( ) { temp ( temp ) ; return 0 ; } 
      |                ~~~~        ^
crash_test_june4_3.c:2:21: warning: passing arguments to 'temp' without a prototype is deprecated in all versions of C and is not supported in C23 [-Wdeprecated-non-prototype]
    2 | int main ( ) { temp ( temp ) ; return 0 ; } 
      |                     ^
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /tmp/clang-build/build/bin/clang-19 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -dumpdir a- -disable-free -clear-ast-before-backend -main-file-name crash_test_june4_3.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/tmp/crashes -fcoverage-compilation-dir=/tmp/crashes -resource-dir /tmp/clang-build/build/lib/clang/19 -internal-isystem /tmp/clang-build/build/lib/clang/19/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -ferror-limit 19 -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fcolor-diagnostics -disable-llvm-passes -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/crash_test_june4_3-6500fa.o -x c crash_test_june4_3.c
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  clang-19        0x0000555570b78309 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 122
1  clang-19        0x0000555570b789ff
2  clang-19        0x0000555570b743fa llvm::sys::RunSignalHandlers() + 254
3  clang-19        0x0000555570b7784b
4  libpthread.so.0 0x00007ffff7fba730
5  clang-19        0x0000555569f08130
6  clang-19        0x0000555569fbd81b
7  clang-19        0x000055556b848b5d
8  clang-19        0x000055556b847513
9  clang-19        0x000055556b8458c5
10 clang-19        0x000055556e8d5680
11 clang-19        0x000055556e8d5276
12 clang-19        0x000055556e8d4f36
13 clang-19        0x000055556e8d4aa5
14 clang-19        0x0000555571730858
15 clang-19        0x0000555571731477
16 clang-19        0x0000555571727ea0 clang::CodeGen::CodeGenModule::GetOrCreateLLVMFunction(llvm::StringRef, llvm::Type*, clang::GlobalDecl, bool, bool, bool, llvm::AttributeList, clang::CodeGen::ForDefinition_t) + 4308
17 clang-19        0x00005555717289b6 clang::CodeGen::CodeGenModule::GetAddrOfFunction(clang::GlobalDecl, llvm::Type*, bool, bool, clang::CodeGen::ForDefinition_t) + 910
18 clang-19        0x000055557172bcd2 clang::CodeGen::CodeGenModule::GetAddrOfGlobal(clang::GlobalDecl, clang::CodeGen::ForDefinition_t) + 854
19 clang-19        0x000055557171a417 clang::CodeGen::CodeGenModule::EmitDeferred() + 1013
20 clang-19        0x00005555717030b0 clang::CodeGen::CodeGenModule::Release() + 318
21 clang-19        0x000055557240cd24
22 clang-19        0x00005555723e8a82 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 386
23 clang-19        0x00005555781c51c9 clang::ParseAST(clang::Sema&, bool, bool) + 1917
24 clang-19        0x0000555572909cde clang::ASTFrontendAction::ExecuteAction() + 746
25 clang-19        0x00005555723f10d7 clang::CodeGenAction::ExecuteAction() + 141
26 clang-19        0x0000555572908d45 clang::FrontendAction::Execute() + 287
27 clang-19        0x0000555572779f20 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 2014
28 clang-19        0x0000555572c4b8e9 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 1901
29 clang-19        0x0000555569ead8e7 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 3611
30 clang-19        0x0000555569e926a7
31 clang-19        0x0000555569e92ffe clang_main(int, char**, llvm::ToolContext const&) + 1454
32 clang-19        0x0000555569ef0cea main + 148
33 libc.so.6       0x00007ffff7ada09b __libc_start_main + 235
34 clang-19        0x0000555569e912ba _start + 42
clang-19: error: unable to execute command: Segmentation fault (core dumped)
clang-19: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 58b49cef1d772a922a433fd4a42e41db3f18d34b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /tmp/clang-build/build/bin
Build config: +unoptimized, +assertions
clang-19: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-19: note: diagnostic msg: /tmp/crash_test_june4_3-611026.c
clang-19: note: diagnostic msg: /tmp/crash_test_june4_3-611026.sh
clang-19: note: diagnostic msg: 

********************
```

**Closed** 2024-06-06 14:06 UTC
Labels: clang:codegen, crash-on-invalid
