### ISSUE TITLE
Bad codegen after commit 957eed0b1af2cb88edafe1ff2643a38165c67a40

### ISSUE THREAD

**Issue by dyung** [llvm/llvm-project#58777] opened 2022-11-03 07:20 UTC
We have an internal test which recently started failing when compiled with optimizations. I was able to bisect the failure to commit 957eed0b1af2cb88edafe1ff2643a38165c67a40. Here is the reduced test case:
```c++
extern "C" void printf(...);
typedef double __attribute__((ext_vector_type(2))) a;
a b{-0.0617794755735, -0.867816130255}, c = 302.232471398, d = -524.574969857,
                                        e = -385.69192343;
int main() {
  for (unsigned f = 0; f < 134; ++f)
    d += e;
  a g = d.xx, h(c - g);
  a i = __builtin_shufflevector(h, h, 2, 2);
  volatile a j(b - i);
  printf("%lf %lf\n", j, j[1]);
}
```
When compiled with optimizations and `-mavx`, the test should produce the output `-52509.586960 -52510.392997`. After 957eed0b1af2cb88edafe1ff2643a38165c67a40 though it now produces `0.000000 0.000000`.
```
$ ~/src/upstream/093200fd00ff5d3a615410ce66d666467629a10b-linux/bin/clang++ -mavx -O2 test.cpp -o test.good.out
$ ~/src/upstream/957eed0b1af2cb88edafe1ff2643a38165c67a40-linux/bin/clang++ -mavx -O2 test.cpp -o test.bad.out
$ ./test.good.out 
-52509.586960 -52510.392997
$ ./test.bad.out 
0.000000 0.000000
```

**Comment by peterwaller-arm** [comment] 2022-11-03 08:02
Hi @dyung, thanks for the report and reproducer. Matt's away today so I've applied a revert in e1790c8c290d773cd5b1fc79f80b7a23dceb7589.

Closing for now since with the revert the issue is fixed.

**Closed by peterwaller-arm** 2022-11-03 08:02 UTC
Labels: new issue

**Comment by MDevereau** [comment] 2022-11-07 14:01
https://reviews.llvm.org/D135876 Has been updated and I've verified the test now outputs `-52509.586960 -52510.392997`. Thanks.
