### ISSUE TITLE
[flang] Incorrect execution result of MVBITS intrinsic subroutine

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#62597] opened 2023-05-08 06:31 UTC
```
Version of flang-new : 17.0.0(5a50ba03e9adb1614189530f8a5ef06d90dfd670)
```

The execution result of `MVBITS` intrinsic subroutine is incorrect.
The first argument of the `MVBITS` intrinsic subroutine is an array.

The following are the test program, results of Flang-new, GFortran and ifort compilation and execution.

`snggf586_2.f90`:
```f90
program main
  integer i(2),j(2)
  i=(/1,1/);j=(/2,1/)
  write(6,*) "i = ", i, " j = ", j, " i(j) = ", i(j)
  call mvbits(i(j),0,2,i,1)
  write(6,*) "i = ", i
  if (any(i/=3))write(6,*) "NG"
end program main
```

```console
$ flang-new -flang-experimental-exec snggf586_2.f90; ./a.out
 i =  1 1  j =  2 1  i(j) =  1 1
 i =  3 7
 NG
$
```

```console
$ gfortran snggf586_2.f90; ./a.out
 i =            1           1  j =            2           1  i(j) =            1           1
 i =            3           3
$
```

```console
$ ifort snggf586_2.f90; ./a.out
 i =            1           1  j =            2           1  i(j) =            1
           1
 i =            3           3
$
```

**Comment by kiranchandramohan** [comment] 2023-05-08 21:41
This is a duplicate of #60302.

**Closed** 2023-05-08 21:41 UTC
Labels: flang
