### ISSUE TITLE
ceff23c6e39118fbbfb053e70d786fad40987c5b breaks LLD tests on builders containing "dylib" in their name

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#75910] opened 2023-12-19 08:58 UTC
For example:

```
command line:1:22: error: RESPONSE-NOT: excluded string found in input
-implicit-check-not='dylib'
                     ^
<stdin>:3:36: note: found here
-syslibroot b/1/llvm-x86_64-debian-dylib/llvm-project/lld/test/MachO/Inputs/MacOSX.sdk
                                   ^~~~~
Input file: <stdin>
Check file: /b/1/llvm-x86_64-debian-dylib/llvm-project/lld/test/MachO/flat-namespace-dysyms.s
-dump-input=help explains the following input dump.
Input was:
<<<<<<
          1: -arch x86_64 
          2: -platform_version macos 11.0 11.0 
          3: -syslibroot b/1/llvm-x86_64-debian-dylib/llvm-project/lld/test/MachO/Inputs/MacOSX.sdk 
not:imp1                                        !~~~~                                                error: no match expected
          4: -lSystem 
          5: -fatal_warnings 
          6: -flat_namespace 
          7: -lSystem 
          8: b/1/llvm-x86_64-debian-dylib/build/tools/lld/test/MachO/Output/flat-namespace-dysyms.s.tmp/main.o 
          9: b/1/llvm-x86_64-debian-dylib/build/tools/lld/test/MachO/Output/flat-namespace-dysyms.s.tmp/baz.dylib 
         10: -o out 
         11: -t 
>>>>>>
```

I see that ceff23c6e39118fbbfb053e70d786fad40987c5b is actually quite old, so something else must've changed, I guess?

**Comment by firewave** [comment] 2023-12-19 16:37
Looks like a duplicate of #75850.

**Comment by smeenai** [comment] 2023-12-19 19:43
I pushed c77c3663dbea as a short-term fix.

**Closed** 2023-12-19 19:42 UTC
Labels: lld:MachO
