### ISSUE TITLE
[MLIR] Dependent dialects of passes in dynamic pass pipelines are not loaded

### ISSUE THREAD

**Issue by rrbutani** [llvm/llvm-project#54859] opened 2022-04-12 05:14 UTC
## what

Since f9dc2b7079350d0fed3bb3775f496b90483c9e42, passes are encouraged to register the dialects they depend on with `getDependentDialects`. Dialects that are registered this way are then loaded by [`PassManager::run`](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/lib/Pass/Pass.cpp#L663-L668) (which ultimately [calls `OpToOpPassAdaptor::runPipeline`](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/lib/Pass/Pass.cpp#L393-L395) to actually run the passes in the pipeline).

This works well for ordinary pass pipelines but doesn't seem to work for _dynamic_ pass pipelines that are added using [`Pass::runPipeline`](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/include/mlir/Pass/Pass.h#L191-L196). Pipelines that are run this way are executed via the registered [`pipelineExecutor`](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/include/mlir/Pass/Pass.h#L195) ([this lambda](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/lib/Pass/Pass.cpp#L376-L395)) which then calls [`OpToOpPassAdaptor::runPipeline`](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/lib/Pass/Pass.cpp#L393) without loading dependent dialects. This leads to errors when dynamic pass pipeline passes try to use their dependent dialects.

Is this intended behavior? If not, it _seems_ like adding [these lines](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/lib/Pass/Pass.cpp#L663-L668) to [`dynamicPipelineCallback`](https://github.com/llvm/llvm-project/blob/64d3e163d8e35d2d67e060c1bd5a1f1e8d7cfa8f/mlir/lib/Pass/Pass.cpp#L388) would yield the expected behavior.

## example

Here's a small program that reproduces the error:
```c++
#include "mlir/Dialect/AMX/AMXDialect.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/PassManager.h"

namespace m = mlir;

struct PassWithDependentDialects
    : public m::PassWrapper<PassWithDependentDialects,
                               m::OperationPass<m::func::FuncOp>> {
  void getDependentDialects(m::DialectRegistry &registry) const override {
    llvm::errs() << "! PassWithDependentDialects deps\n";
    registry.insert<m::amx::AMXDialect>();
  }

  void runOnOperation(void) override {
    m::OpBuilder b(getOperation());
    b.create<m::amx::TileZeroOp>(
        /* loc: */ getOperation()->getLoc(),
        /* ret: */ m::VectorType::get({1, 1}, b.getF32Type())
    );
  }
};

struct ExamplePass
    : public m::PassWrapper<ExamplePass,
                               m::OperationPass<m::ModuleOp>> {

  static std::unique_ptr<m::OperationPass<m::ModuleOp>> create() {
    return std::make_unique<ExamplePass>();
  }

  void getDependentDialects(m::DialectRegistry &_registry) const override {
    llvm::errs() << "! ExamplePass deps\n";
  }

  void runOnOperation(void) override {
    m::ModuleOp f = getOperation();
    m::OpPassManager pipeline(m::ModuleOp::getOperationName());

    pipeline.nest<m::func::FuncOp>().addPass(std::make_unique<PassWithDependentDialects>());

    if (m::failed(runPipeline(pipeline, f.getOperation()))) {
      return signalPassFailure();
    }
  }
};

int main(int argc, char **argv) {
  m::MLIRContext context;
  context.getOrLoadDialect<m::func::FuncDialect>();

  auto input = R"(
    module {
      func.func @test(%x: i64) -> i64 {
        return %x : i64
      }
    }
  )";
  m::OwningOpRef<m::ModuleOp> module = m::parseSourceString<m::ModuleOp>(input, &context);

  m::PassManager pm(&context);
  pm.addPass(ExamplePass::create());

  if (m::failed(pm.run(module.get()))) {
    module->emitError();
    return 1;
  }

  module->dump();
}
```

`PassWithDependentDialects` is a (nonsensical) pass that makes use of an unregistered dialect; despite registering it in its `getDependentDialects` method, it encounters a runtime error when trying to create an op in the `AMX` dialect.

### example, as a Bazel workspace

[Here](https://github.com/llvm/llvm-project/files/8469736/dynamic-pipeline-example.zip) is a nix flake/Bazel workspace with the above (`nix develop` + `bazel run //:example`).

**Comment by River707** [comment] 2022-04-12 05:21
This is intended behavior. The parent pass, i.e. the one executing the dynamic pipeline, is expected to add the dependent passes for the dynamic pipeline. Dialects can't be loaded during multithreading, so we can't lazily load when the dynamic pipeline is first executing.

**Comment by joker-eph** [comment] 2022-04-12 05:24
Closing as intended behavior, feel free to re-open if you feel there is a suitable follow-up.

**Closed by joker-eph** 2022-04-12 05:24 UTC
Labels: mlir:core

**Comment by rrbutani** [comment] 2022-04-12 05:47
@River707 Thanks for the extremely fast response!

That's my bad; it totally didn't occur to me that loading dialects during pass execution is problematic.

Would a debug assertion ensuring that all dependent dialects of a dynamic pipeline have _already_ been loaded be appropriate?

**Comment by River707** [comment] 2022-04-12 05:50
Yeah, that sounds like a great addition. Anything that helps with catching things early is a great help. Would you be interested in preparing a patch?

**Comment by rrbutani** [comment] 2022-04-12 05:54
@River707 definitely; I'll try to put something together tomorrow.
