### ISSUE TITLE
[clang-format] Horrible formatting for lambdas inside member initializations and Ctor try/catch blocks

### ISSUE THREAD

**Issue by EmrecanKaracayir** [llvm/llvm-project#95679] opened 2024-06-15 19:03 UTC
Configuration:
```yaml
# BasedOnStyle: // Unused
AccessModifierOffset: -2
AlignAfterOpenBracket: BlockIndent
AlignArrayOfStructures: Left
AlignConsecutiveAssignments:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: true
  AlignCompound: true
  PadOperators: true
AlignConsecutiveBitFields:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: true
  AlignCompound: true
  PadOperators: true
AlignConsecutiveDeclarations:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: true
  AlignCompound: true
  PadOperators: true
AlignConsecutiveMacros:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: true
  AlignCompound: true
  PadOperators: true
AlignConsecutiveShortCaseStatements:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: true
  AlignCaseColons: true
# AlignConsecutiveTableGenCondOperatorColons: // v19
# AlignConsecutiveTableGenDefinitionColons:   // v19
AlignEscapedNewlines: Right
AlignOperands: AlignAfterOperator
AlignTrailingComments:
  Kind: Always
  OverEmptyLines: 1
AllowAllArgumentsOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowBreakBeforeNoexceptSpecifier: OnlyWithParen
AllowShortBlocksOnASingleLine: Empty
AllowShortCaseLabelsOnASingleLine: false
AllowShortCompoundRequirementOnASingleLine: true
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakBeforeMultilineStrings: false
# AttributeMacros: // Unused
BinPackArguments: false
BinPackParameters: false
BitFieldColonSpacing: Both
BraceWrapping:
  AfterCaseLabel: true
  AfterClass: true
  AfterControlStatement: Always
  AfterEnum: true
  AfterExternBlock: true
  AfterFunction: true
  AfterNamespace: true
  AfterObjCDeclaration: true
  AfterStruct: true
  AfterUnion: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: false
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
# BreakInitializerIndentWidth: // Unused (If unset ContinuationIndentWidth is used)
BreakAdjacentStringLiterals: true
BreakAfterAttributes: Always
# BreakAfterJavaFieldAnnotations: // Unused (Not C++)
# BreakAfterReturnType // v19
BreakArrays: true
BreakBeforeBinaryOperators: All
BreakBeforeBraces: Custom
BreakBeforeConceptDeclarations: Always
BreakBeforeInlineASMColon: OnlyMultiline
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeComma
BreakInheritanceList: BeforeComma
BreakStringLiterals: true
# BreakTemplateDeclarations // v19
ColumnLimit: 80
# CommentPragmas: // Unused
CompactNamespaces: false
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat: false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: LogicalBlock
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
# ForEachMacros: // Unused
# IfMacros:      // Unused
IncludeBlocks: Regroup
IncludeCategories:
  - Regex: ^\".*pch\..*\"$ # Precompiled headers
    Priority: -1
    SortPriority: 0
    CaseSensitive: false
  - Regex: ^\".*\..*\"$ # Project headers
    Priority: 1
    SortPriority: 0
    CaseSensitive: false
  - Regex: ^<.*\..*>$ # Included headers
    Priority: 2
    SortPriority: 0
    CaseSensitive: false
  - Regex: ^<.*>$ # Standard library headers
    Priority: 3
    SortPriority: 0
    CaseSensitive: false
IncludeIsMainRegex: $ # Main header
IncludeIsMainSourceRegex: $ # Main source
IndentAccessModifiers: false
IndentCaseBlocks: false
IndentCaseLabels: false
IndentExternBlock: AfterExternBlock
IndentGotoLabels: true
IndentPPDirectives: BeforeHash
IndentRequiresClause: true
IndentWidth: 2
IndentWrappedFunctionNames: false
InsertBraces: true
InsertNewlineAtEOF: true
InsertTrailingCommas: Wrapped
IntegerLiteralSeparator:
  Binary: 4
  BinaryMinDigits: 0
  Decimal: 3
  DecimalMinDigits: 0
  Hex: 2
  HexMinDigits: 0
# JavaImportGroups: // Unused (Not C++)
# JavaScriptQuotes: // Unused (Not C++)
# JavaScriptWrapImports: // Unused (Not C++)
KeepEmptyLinesAtEOF: false
KeepEmptyLinesAtTheStartOfBlocks: false
LambdaBodyIndentation: Signature
Language: Cpp
LineEnding: LF
# MacroBlockBegin: // Unused
# MacroBlockEnd: // Unused
# Macros: // Unused
# MainIncludeChar // v19
MaxEmptyLinesToKeep: 1
NamespaceIndentation: All
# NamespaceMacros: // Unused
# ObjCBinPackProtocolList: // Unused (Not C++)
# ObjCBlockIndentWidth: // Unused (Not C++)
# ObjCBreakBeforeNestedBlockParam: // Unused (Not C++)
# ObjCPropertyAttributeOrder: // Unused (Not C++)
# ObjCSpaceAfterProperty: // Unused (Not C++)
# ObjCSpaceBeforeProtocolList: // Unused (Not C++)
PPIndentWidth: -1 # Use IndentWidth
PackConstructorInitializers: Never
PenaltyBreakAssignment: 125
PenaltyBreakBeforeFirstCallParameter: 5
PenaltyBreakComment: 250
PenaltyBreakFirstLessLess: 125
PenaltyBreakOpenParenthesis: 0
PenaltyBreakScopeResolution: 1000
PenaltyBreakString: 250
PenaltyBreakTemplateDeclaration: 25
PenaltyExcessCharacter: 1000000
PenaltyIndentedWhitespace: 5
PenaltyReturnTypeOnItsOwnLine: 200
PointerAlignment: Left
QualifierAlignment: Left
# QualifierOrder: // Unused
# RawStringFormats: // Unused
ReferenceAlignment: Pointer
ReflowComments: true
RemoveBracesLLVM: false
RemoveParentheses: ReturnStatement
RemoveSemicolon: true
RequiresClausePosition: WithPreceding
RequiresExpressionIndentation: OuterScope
SeparateDefinitionBlocks: Always
ShortNamespaceLines: 0
SkipMacroDefinitionBody: false
SortIncludes: CaseSensitive
# SortJavaStaticImport: // Unused (Not C++)
SortUsingDeclarations: LexicographicNumeric
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: true
SpaceAroundPointerQualifiers: Default
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
# SpaceBeforeJsonColon: // Unused (Not C++)
SpaceBeforeParens: ControlStatements
SpaceBeforeParensOptions:
  AfterControlStatements: true
  AfterForeachMacros: true
  AfterFunctionDefinitionName: false
  AfterFunctionDeclarationName: false
  AfterIfMacros: true
  AfterOverloadedOperator: false
  AfterRequiresInClause: false
  AfterRequiresInExpression: false
  BeforeNonEmptyParentheses: false
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: Never
SpacesInContainerLiterals: true
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 1
SpacesInParens: Never
SpacesInParensOptions:
  InCStyleCasts: false
  InConditionalStatements: false
  InEmptyParentheses: false
  Other: false
SpacesInSquareBrackets: false
Standard: c++20
# StatementAttributeLikeMacros: // Unused
# StatementMacros: // Unused
TabWidth: 2
# TableGenBreakInsideDAGArg: // v19
# TableGenBreakingDAGArgOperators: // v19
# TypeNames: // Unused
# TypeNameMacros: // Unused
UseTab: Never
# VerilogBreakBetweenInstancePorts: // Unused (Not C++)
```

Result:
```cpp
  Texture::Texture(
    std::int32_t width,
    std::int32_t height,
    const Color& color,
    bool         transparency
  )
  try : m_bitmap{
    []()->Render::Target{return Render::Target{Render::Target::Action::ACQUIRE}
    ;
} // namespace Engine::Graphics
(), width, height
}
, m_transparency{transparency}
{
  // Create off-screen render target
  const Render::Target offscreenRenderTarget{
    Render::Target::Action::CREATE, screenRenderTarget.getHandle()
  };

  // Select the bitmap into the off-screen render target
  offscreenRenderTarget.selectObject(m_bitmap.getHandle());

  // Create the brush
  const Brush brush{color};

  // Fill the bitmap with the brush
  const Math::Rectangle<std::int32_t> rectangle{0, 0, width, height};
  brush.fillRectangle(offscreenRenderTarget, rectangle);
}

catch (...) { throw; }
```

Expected:
```cpp
  Texture::Texture(
    std::int32_t width,
    std::int32_t height,
    const Color& color,
    bool         transparency
  )
  try
    : m_bitmap{
        []() -> Render::Target
        {
          return Render::Target{Render::Target::Action::ACQUIRE};
        }(),
        width,
        height
      }
    , m_transparency{transparency}
  {
    // Create off-screen render target
    const Render::Target offscreenRenderTarget{
      Render::Target::Action::CREATE, screenRenderTarget.getHandle()
    };

    // Select the bitmap into the off-screen render target
    offscreenRenderTarget.selectObject(m_bitmap.getHandle());

    // Create the brush
    const Brush brush{color};

    // Fill the bitmap with the brush
    const Math::Rectangle<std::int32_t> rectangle{0, 0, width, height};
    brush.fillRectangle(offscreenRenderTarget, rectangle);
  }
  catch (...)
  {
    throw;
  }
```

Result:
```cpp
  Bitmap::Bitmap(
    const DeviceContext& deviceContext, std::int32_t width, std::int32_t height
  )
  try : m_width{width}, m_height{height},
    m_bitmap{
      CreateCompatibleBitmap(deviceContext.getHandle(), m_width, m_height)}
  {
    // Check if bitmap is valid
    if (m_bitmap == nullptr)
    {
      throw std::runtime_error{"Failed to create bitmap!"};
    }
  }
  catch (...)
  {
    throw;
  }
```

Expected:
```cpp
  Bitmap::Bitmap(
    const DeviceContext& deviceContext, std::int32_t width, std::int32_t height
  )
  try
    : m_width{width}
    , m_height{height}
    , m_bitmap{
        CreateCompatibleBitmap(deviceContext.getHandle(), m_width, m_height)
      }
  {
    // Check if bitmap is valid
    if (m_bitmap == nullptr)
    {
      throw std::runtime_error{"Failed to create bitmap!"};
    }
  }
  catch (...)
  {
    throw;
  }
```

**Comment by mydeveloperday** [comment] 2024-06-17 13:56
I'm unclear from the examples what you consider 'Horrible', is it the lambda or the positioning of the try?  can you break this down into a minimal example and minimal .clang-format that shows your concern so we are clear what part you don't like?

```c++
class Foo {
  Foo() try :
    throw std::runtime_error("Error") { std::cout << "Foo(int)\n"; }
  catch (std::exception const &e) {
    std::cout << e.what() << '\n';
  }
};
```
with

```yaml
BasedOnStyle: LLVM
Language: Cpp
```

**Comment by mydeveloperday** [comment] 2024-06-17 14:05
for a simple example

```c++
class Foo {
  Foo() try : bar{[]()->Bar{throw std::runtime_error("Error")}
    ;
  (), w, h
}, abc(2) {
  std::cout << "Foo(int)\n";
}
catch (std::exception const &e) {
  std::cout << e.what() << '\n';
}
}
;
```
I think its not really annotating the lambda correctly.

```
AnnotatedTokens(L=0, P=0, T=5, C=0):
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=0 Name=class L=5 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6be8108 Text='class'
 M=0 C=1 T=Unknown S=1 F=0 B=0 BK=0 P=5020 Name=identifier L=9 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6beece0 Text='Foo'
 M=0 C=0 T=ClassLBrace S=1 F=0 B=0 BK=1 P=23 Name=l_brace L=11 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='{'
----
AnnotatedTokens(L=1, P=0, T=5, C=0):
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=0 Name=identifier L=3 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6beece0 Text='Foo'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=23 Name=l_paren L=4 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='('
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=140 Name=r_paren L=5 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=')'
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=23 Name=try L=9 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6be8548 Text='try'
 M=0 C=1 T=CtorInitializerColon S=1 F=0 B=0 BK=0 P=23 Name=colon L=11 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=':'
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=22 Name=identifier L=15 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6beed10 Text='bar'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=23 Name=l_brace L=16 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='{'
 M=0 C=1 T=DesignatedInitializerLSquare S=0 F=0 B=0 BK=0 P=59 Name=l_square L=17 PPK=2 FakeLParens=0/ FakeRParens=0 II=0x0 Text='['
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=79 Name=r_square L=18 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=']'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=43 Name=l_paren L=19 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='('
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=79 Name=r_paren L=20 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=')'
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=190 Name=arrow L=22 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='->'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=43 Name=identifier L=25 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6beed40 Text='Bar'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=43 Name=l_brace L=26 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='{'
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=79 Name=throw L=31 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6be84e8 Text='throw'
 M=0 C=0 T=Unknown S=1 F=0 B=0 BK=0 P=63 Name=identifier L=35 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6bf9540 Text='std'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=63 Name=coloncolon L=37 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='::'
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=560 Name=identifier L=50 PPK=2 FakeLParens= FakeRParens=0 II=0x1f6e6bf9578 Text='runtime_error'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=63 Name=l_paren L=51 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='('
 M=0 C=1 T=Unknown S=0 F=0 B=0 BK=0 P=99 Name=string_literal L=58 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='"Error"'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=83 Name=r_paren L=59 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text=')'
 M=0 C=0 T=Unknown S=0 F=0 B=0 BK=0 P=61 Name=r_brace L=60 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='}'
```

I would expect 

 M=0 C=1 T=DesignatedInitializerLSquare S=0 F=0 B=0 BK=0 P=59 Name=l_square L=17 PPK=2 FakeLParens=0/ FakeRParens=0 II=0x0 Text='['

to be LambdaLSquare and the arrow to be 

M=0 C=1 T=TrailingReturnArrow S=1 F=0 B=0 BK=0 P=130 Name=arrow L=7 PPK=2 FakeLParens= FakeRParens=0 II=0x0 Text='->'

**Comment by EmrecanKaracayir** [comment] 2024-06-17 18:19
There are two issues here:
1. Constructor initializer setting (BeforeComma in this example) isn't respected when inside constructor try block.
2. When using brace/uniform initialization for constructor initializer, having a lambda inside braces, formatting gets messed up.

**Comment by rymiel** [comment] 2024-06-17 19:58
I think this is a duplicate of #58987

**Comment by EmrecanKaracayir** [comment] 2024-06-17 21:25
> I think this is a duplicate of #58987

Yes, 2. issue is exactly the same but 1 is different.

**Closed** 2024-06-19 01:56 UTC
Labels: clang-format
