### ISSUE TITLE
[clang-20] non-type template argument is not a constant expression

### ISSUE THREAD

**Issue by kalman5** [llvm/llvm-project#104850] opened 2024-08-19 20:31 UTC
The following snippet compiles just fine with clang-19 (boost 1.78)

```
#include <boost/date_time/posix_time/posix_time_config.hpp>
#include <boost/numeric/conversion/cast.hpp>

int main() {
  typedef boost::posix_time::time_duration::hour_type hour_type; 

  auto c = boost::numeric_cast<hour_type>(0);
}
```

$ clang++-19 main2.cpp -Wno-enum-constexpr-conversion -Wno-unknown-warning-option
$ echo $?
0

however with clang-20 gives the following error:

```
$ clang++-20 main2.cpp -Wno-enum-constexpr-conversion -Wno-unknown-warning-option
In file included from main2.cpp:2:
In file included from /usr/local/include/boost/numeric/conversion/cast.hpp:33:
In file included from /usr/local/include/boost/numeric/conversion/converter.hpp:13:
In file included from /usr/local/include/boost/numeric/conversion/conversion_traits.hpp:13:
In file included from /usr/local/include/boost/numeric/conversion/detail/conversion_traits.hpp:18:
In file included from /usr/local/include/boost/numeric/conversion/detail/int_float_mixture.hpp:19:
In file included from /usr/local/include/boost/mpl/integral_c.hpp:32:
/usr/local/include/boost/mpl/aux_/integral_wrapper.hpp:72:31: error: non-type template argument is not a constant expression
   72 |     typedef AUX_WRAPPER_INST( BOOST_MPL_AUX_STATIC_CAST(AUX_WRAPPER_VALUE_TYPE, (value - 1)) ) prior;
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
   24 | #   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
      |                                               ^
/usr/local/include/boost/mpl/integral_c.hpp:31:54: note: expanded from macro 'AUX_WRAPPER_INST'
   31 | #define AUX_WRAPPER_INST(value) AUX_WRAPPER_NAME< T, value >
      |                                                      ^~~~~
/usr/local/include/boost/numeric/conversion/detail/meta.hpp:30:46: note: in instantiation of template class 'mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>' requested here
   30 |        enum { x = ( BOOST_MPL_AUX_VALUE_WKND(T1)::value == BOOST_MPL_AUX_VALUE_WKND(T2)::value ) };
      |                                              ^
/usr/local/include/boost/mpl/if.hpp:63:68: note: in instantiation of template class 'boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>>' requested here
   63 |           BOOST_MPL_AUX_STATIC_CAST(bool, BOOST_MPL_AUX_VALUE_WKND(T1)::value)
      |                                                                    ^
/usr/local/include/boost/mpl/eval_if.hpp:37:22: note: in instantiation of template class 'boost::mpl::if_<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>>, boost::mpl::identity<boost::numeric::convdetail::get_subranged_BuiltIn2BuiltIn<long, int>>, boost::mpl::eval_if<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_udt>>, boost::mpl::identity<boost::mpl::identity<boost::numeric::convdetail::subranged_BuiltIn2Udt<long, int>>>, boost::mpl::if_<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::udt_to_builtin>>, boost::mpl::identity<boost::numeric::convdetail::subranged_Udt2BuiltIn<long, int>>, boost::mpl::identity<boost::numeric::convdetail::subranged_Udt2Udt<long, int>>>>>' requested here
   37 |     typedef typename if_<C,F1,F2>::type f_;
      |                      ^
/usr/local/include/boost/numeric/conversion/detail/meta.hpp:81:12: note: in instantiation of template class 'boost::mpl::eval_if<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>>, boost::mpl::identity<boost::numeric::convdetail::get_subranged_BuiltIn2BuiltIn<long, int>>, boost::mpl::eval_if<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_udt>>, boost::mpl::identity<boost::mpl::identity<boost::numeric::convdetail::subranged_BuiltIn2Udt<long, int>>>, boost::mpl::if_<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::udt_to_builtin>>, boost::mpl::identity<boost::numeric::convdetail::subranged_Udt2BuiltIn<long, int>>, boost::mpl::identity<boost::numeric::convdetail::subranged_Udt2Udt<long, int>>>>>' requested here
   81 |       mpl::eval_if<is_case0,Case0TypeQ,choose_1_2_3Q>::type
      |            ^
/usr/local/include/boost/numeric/conversion/detail/udt_builtin_mixture.hpp:41:7: note: in instantiation of template class 'boost::numeric::convdetail::ct_switch4<mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_builtin>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::builtin_to_udt>, mpl_::integral_c<boost::numeric::udt_builtin_mixture_enum, boost::numeric::udt_to_builtin>, boost::numeric::convdetail::get_subranged_BuiltIn2BuiltIn<long, int>, boost::mpl::identity<boost::numeric::convdetail::subranged_BuiltIn2Udt<long, int>>, boost::mpl::identity<boost::numeric::convdetail::subranged_Udt2BuiltIn<long, int>>, boost::mpl::identity<boost::numeric::convdetail::subranged_Udt2Udt<long, int>>>' requested here
   41 |       ct_switch4<UdtMixture
      |       ^
/usr/local/include/boost/numeric/conversion/detail/is_subranged.hpp:205:9: note: (skipping 3 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
  205 |         for_udt_builtin_mixture<udt_builtin_mixture, BuiltIn2BuiltInQ, BuiltIn2UdtQ, Udt2BuiltInQ, Udt2UdtQ>::type
      |         ^
/usr/local/include/boost/numeric/conversion/conversion_traits.hpp:22:7: note: in instantiation of template class 'boost::numeric::convdetail::non_trivial_traits_impl<long, int>' requested here
   22 |     : convdetail::get_conversion_traits<T,S>::type 
      |       ^
/usr/local/include/boost/numeric/conversion/detail/converter.hpp:584:22: note: in instantiation of template class 'boost::numeric::conversion_traits<long, int>' requested here
  584 |     typedef typename Traits::trivial trivial ;
      |                      ^
/usr/local/include/boost/numeric/conversion/converter.hpp:29:32: note: in instantiation of template class 'boost::numeric::convdetail::get_converter_impl<boost::numeric::conversion_traits<long, int>, boost::numeric::def_overflow_handler, boost::numeric::Trunc<int>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>, boost::numeric::UseInternalRangeChecker>' requested here
   29 | struct converter : convdetail::get_converter_impl<Traits,
      |                                ^
/usr/local/include/boost/numeric/conversion/cast.hpp:53:16: note: in instantiation of template class 'boost::numeric::converter<long, int, boost::numeric::conversion_traits<long, int>, boost::numeric::def_overflow_handler, boost::numeric::Trunc<int>>' requested here
   53 |         return converter::convert(arg);
      |                ^
main2.cpp:7:19: note: in instantiation of function template specialization 'boost::numeric_cast<long, int>' requested here
    7 |   auto c = boost::numeric_cast<hour_type>(0);
      |                   ^
/usr/local/include/boost/mpl/aux_/integral_wrapper.hpp:72:31: note: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'udt_builtin_mixture_enum'
   72 |     typedef AUX_WRAPPER_INST( BOOST_MPL_AUX_STATIC_CAST(AUX_WRAPPER_VALUE_TYPE, (value - 1)) ) prior;
      |                               ^
/usr/local/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
   24 | #   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
      |                                               ^
In file included from main2.cpp:2:
In file included from /usr/local/include/boost/numeric/conversion/cast.hpp:33:
In file included from /usr/local/include/boost/numeric/conversion/converter.hpp:13:
In file included from /usr/local/include/boost/numeric/conversion/conversion_traits.hpp:13:
In file included from /usr/local/include/boost/numeric/conversion/detail/conversion_traits.hpp:18:
In file included from /usr/local/include/boost/numeric/conversion/detail/int_float_mixture.hpp:19:
In file included from /usr/local/include/boost/mpl/integral_c.hpp:32:
/usr/local/include/boost/mpl/aux_/integral_wrapper.hpp:72:31: error: non-type template argument is not a constant expression
   72 |     typedef AUX_WRAPPER_INST( BOOST_MPL_AUX_STATIC_CAST(AUX_WRAPPER_VALUE_TYPE, (value - 1)) ) prior;
      |             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
   24 | #   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
      |                                               ^
/usr/local/include/boost/mpl/integral_c.hpp:31:54: note: expanded from macro 'AUX_WRAPPER_INST'
   31 | #define AUX_WRAPPER_INST(value) AUX_WRAPPER_NAME< T, value >
      |                                                      ^~~~~
/usr/local/include/boost/numeric/conversion/detail/meta.hpp:30:46: note: in instantiation of template class 'mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>' requested here
   30 |        enum { x = ( BOOST_MPL_AUX_VALUE_WKND(T1)::value == BOOST_MPL_AUX_VALUE_WKND(T2)::value ) };
      |                                              ^
/usr/local/include/boost/mpl/if.hpp:63:68: note: in instantiation of template class 'boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>>' requested here
   63 |           BOOST_MPL_AUX_STATIC_CAST(bool, BOOST_MPL_AUX_VALUE_WKND(T1)::value)
      |                                                                    ^
/usr/local/include/boost/mpl/eval_if.hpp:37:22: note: in instantiation of template class 'boost::mpl::if_<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>>, boost::mpl::identity<boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>>, boost::mpl::eval_if<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_float>>, boost::mpl::identity<boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>>, boost::mpl::if_<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::float_to_integral>>, boost::mpl::identity<boost::numeric::convdetail::rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>, boost::numeric::Trunc<int>>>, boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>>>>' requested here
   37 |     typedef typename if_<C,F1,F2>::type f_;
      |                      ^
/usr/local/include/boost/numeric/conversion/detail/meta.hpp:81:12: note: in instantiation of template class 'boost::mpl::eval_if<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>>, boost::mpl::identity<boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>>, boost::mpl::eval_if<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_float>>, boost::mpl::identity<boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>>, boost::mpl::if_<boost::numeric::convdetail::equal_to<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::float_to_integral>>, boost::mpl::identity<boost::numeric::convdetail::rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>, boost::numeric::Trunc<int>>>, boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>>>>' requested here
   81 |       mpl::eval_if<is_case0,Case0TypeQ,choose_1_2_3Q>::type
      |            ^
/usr/local/include/boost/numeric/conversion/detail/int_float_mixture.hpp:59:7: note: in instantiation of template class 'boost::numeric::convdetail::ct_switch4<mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_integral>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::integral_to_float>, mpl_::integral_c<boost::numeric::int_float_mixture_enum, boost::numeric::float_to_integral>, boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>, boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>, boost::mpl::identity<boost::numeric::convdetail::rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>, boost::numeric::Trunc<int>>>, boost::mpl::identity<boost::numeric::convdetail::non_rounding_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::convdetail::dummy_range_checker<boost::numeric::conversion_traits<long, int>>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>>>>' requested here
   59 |       ct_switch4<IntFloatMixture
      |       ^
/usr/local/include/boost/numeric/conversion/detail/converter.hpp:550:7: note: (skipping 1 context in backtrace; use -ftemplate-backtrace-limit=0 to see all)
  550 |       for_int_float_mixture<int_float_mixture, NonRoundingQ, NonRoundingQ, RoundingQ, NonRoundingQ>::type
      |       ^
/usr/local/include/boost/mpl/eval_if.hpp:38:22: note: in instantiation of template class 'boost::numeric::convdetail::get_non_trivial_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::def_overflow_handler, boost::numeric::Trunc<int>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>, boost::numeric::UseInternalRangeChecker>' requested here
   38 |     typedef typename f_::type type;
      |                      ^
/usr/local/include/boost/numeric/conversion/detail/converter.hpp:586:27: note: in instantiation of template class 'boost::mpl::eval_if<mpl_::bool_<false>, boost::mpl::identity<boost::numeric::convdetail::trivial_converter_impl<boost::numeric::conversion_traits<long, int>>>, boost::numeric::convdetail::get_non_trivial_converter<boost::numeric::conversion_traits<long, int>, boost::numeric::def_overflow_handler, boost::numeric::Trunc<int>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>, boost::numeric::UseInternalRangeChecker>>' requested here
  586 |     typedef typename mpl::eval_if<trivial,TrivialQ,NonTrivialQ>::type type ;
      |                           ^
/usr/local/include/boost/numeric/conversion/converter.hpp:29:32: note: in instantiation of template class 'boost::numeric::convdetail::get_converter_impl<boost::numeric::conversion_traits<long, int>, boost::numeric::def_overflow_handler, boost::numeric::Trunc<int>, boost::numeric::raw_converter<boost::numeric::conversion_traits<long, int>>, boost::numeric::UseInternalRangeChecker>' requested here
   29 | struct converter : convdetail::get_converter_impl<Traits,
      |                                ^
/usr/local/include/boost/numeric/conversion/cast.hpp:53:16: note: in instantiation of template class 'boost::numeric::converter<long, int, boost::numeric::conversion_traits<long, int>, boost::numeric::def_overflow_handler, boost::numeric::Trunc<int>>' requested here
   53 |         return converter::convert(arg);
      |                ^
main2.cpp:7:19: note: in instantiation of function template specialization 'boost::numeric_cast<long, int>' requested here
    7 |   auto c = boost::numeric_cast<hour_type>(0);
      |                   ^
/usr/local/include/boost/mpl/aux_/integral_wrapper.hpp:72:31: note: integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'int_float_mixture_enum'
   72 |     typedef AUX_WRAPPER_INST( BOOST_MPL_AUX_STATIC_CAST(AUX_WRAPPER_VALUE_TYPE, (value - 1)) ) prior;
      |                               ^
/usr/local/include/boost/mpl/aux_/static_cast.hpp:24:47: note: expanded from macro 'BOOST_MPL_AUX_STATIC_CAST'
   24 | #   define BOOST_MPL_AUX_STATIC_CAST(T, expr) static_cast<T>(expr)
      |                                               ^
2 errors generated.
```

**Comment by AaronBallman** [comment] 2024-08-20 11:33
Correct, MPL has a bug we no longer allow workarounds for:
https://github.com/llvm/llvm-project/blob/21de04918e0b4b6835d331b726861740525d06d9/clang/docs/ReleaseNotes.rst?plain=1#L52

However, the bug in MPL has been fixed as of [Boost 1.86](https://github.com/boostorg/mpl/releases/tag/boost-1.86.0) so you should be able to upgrade your boost version to get the code to compile again.

Closing the issue as not a bug, however, please reopen if there's more information we should be aware of regarding the issue. Thanks!

**Closed by AaronBallman** 2024-08-20 11:33 UTC
Labels: invalid, clang:frontend
