### ISSUE TITLE
clangd: iwyu export and NOLINT do not supress warning if an include is after a function declaration in a C header

### ISSUE THREAD

**Issue by apache-hb** [llvm/llvm-project#76722] opened 2024-01-02 14:47 UTC
```h
// header1.h
#pragma once

#include <stdbool.h>

int cpp_input(void *extra, char *out, int size);
#include "header2.h" // IWYU pragma: export
```
```h
// header2.h
#pragma once

#define YY_INPUT(buffer, result, size) result = flex_input(yyextra, buffer, size);

extern int i;
```

produces `Included header header2.h is not used directly (fix available)`. moving the include before the first declaration fixes this.

**Comment by hokein** [comment] 2024-01-03 10:48
This is a duplicate of https://github.com/clangd/clangd/issues/1571

**Closed by hokein** 2024-01-03 10:48 UTC
Labels: duplicate, clangd, clang-include-cleaner
