### ISSUE TITLE
Incorrect paste of placeholder with '##'.

### ISSUE THREAD

**Issue by mrolle45** [llvm/llvm-project#116720] opened 2024-11-19 01:22 UTC
If a macro definition contains `x ## ##` and `x` is a parameter and the macro is called with an empty argument, then clang ignores the `x ##` when expanding the macro, leaving just `##`.  It then tries to paste `##` after the preceding token!
To avoid confusion, let **paste** be a ## token in an odd numbered position in a sequence of ## tokens, and let **hashhash** be a ## token in an even numbered position in a sequence of ## tokens.
In most cases, clang treats **hashhash** as an ordinary token, not as a paste operator.
But if `x` is a parameter for an empty argument, `foo x ## bar foo x ## ## bar foo x ## ## ## bar ` is expanded to `foo bar foo ## bar foo ## ## bar`.  clang interprets this as `foo bar foo `**paste**` bar foo `**hashhash**` bar`.  The result output is `foo bar foobar foo ## bar`.

**Comment by chrchr-github** [comment] 2024-11-19 13:45
https://github.com/llvm/llvm-project/issues/112122 seems related.

**Comment by zygoloid** [comment] 2024-11-19 22:32
Closing as duplicate of #1112122.

@mrolle45 Please can you keep any further discussion on issue #112122? Splitting the discussion across multiple issues makes it harder to follow.

**Closed by zygoloid** 2024-11-19 22:32 UTC
Labels: clang:frontend

**Comment by mrolle45** [comment] 2024-11-20 19:19
OK.  I'll add comment to #112122.  Note that the example I have here is a different problem from the one in #112122, as it involves placeholders.
