### ISSUE TITLE
HIP frontend crash with C++20

### ISSUE THREAD

**Issue by fweig** [llvm/llvm-project#62017] opened 2023-04-08 13:08 UTC
# Steps to reproduce

Unpack [this reproducer](https://github.com/llvm/llvm-project/files/11183327/hipcub_allocator.zip), then run:
```shell
clang++ -std=c++20 -x hip-cpp-output hipcub_allocator.ii
```

# Stacktrace

Running the previous command results in a crash with the following stacktrace:
```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /opt/rocm-5.4.3/llvm/bin/clang-15 -cc1 -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name hipcub_allocator.ii -mrelocation-model pic -pic-level 1 -fhalf-no-semantic-interposition -mframe-pointer=all -fdenormal-fp-math-f32=preserve-sign,preserve-sign -fno-rounding-math -mconstructor-aliases -aux-target-cpu x86-64 -fcuda-is-device -mllvm -amdgpu-internalize-symbols -fcuda-allow-variadic-functions -fvisibility hidden -fapply-global-visibility-to-externs -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/hip.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/ocml.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/ockl.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/oclc_daz_opt_on.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/oclc_unsafe_math_off.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/oclc_finite_only_off.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/oclc_correctly_rounded_sqrt_on.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/oclc_wavefrontsize64_on.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/oclc_isa_version_803.bc -mlink-builtin-bitcode /opt/rocm-5.4.3/amdgcn/bitcode/oclc_abi_version_400.bc -target-cpu gfx803 -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -resource-dir /opt/rocm-5.4.3/llvm/lib/clang/15.0.0 -std=c++20 -fdeprecated-macro -fno-autolink -fdebug-compilation-dir=/home/weiglhofer/dev/hip/amd-clang-segfault-reproducer/build -ferror-limit 19 -fhip-new-launch-api -fgnuc-version=4.2.1 -fno-implicit-modules -no-opaque-pointers -fcxx-exceptions -fexceptions -fcolor-diagnostics -fcuda-allow-variadic-functions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/hipcub_allocator-a96804/hipcub_allocator-gfx803.o -x hip-cpp-output /tmp/hipcub_allocator-ed506e/hipcub_allocator-gfx803.cui
1.      <eof> parser at end of file
2.      /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_tree.h:983:7: instantiating function definition 'std::_Rb_tree<int, std::pair<const int, hipcub::CachingDeviceAllocator::TotalBytes>, std::_Select1st<std::pair<const int, hipcub::CachingDeviceAllocator::TotalBytes>>, std::less<int>>::~_Rb_tree'
3.      /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_tree.h:905:7: instantiating function definition 'std::_Rb_tree<int, std::pair<const int, hipcub::CachingDeviceAllocator::TotalBytes>, std::_Select1st<std::pair<const int, hipcub::CachingDeviceAllocator::TotalBytes>>, std::less<int>>::_M_erase'
4.      /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_tree.h:216:12: instantiating class definition 'std::_Rb_tree_node<std::pair<const int, hipcub::CachingDeviceAllocator::TotalBytes>>'
5.      /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/ext/aligned_buffer.h:47:12: instantiating class definition '__gnu_cxx::__aligned_membuf<std::pair<const int, hipcub::CachingDeviceAllocator::TotalBytes>>'
6.      /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/ext/aligned_buffer.h:54:14: instantiating class definition '__gnu_cxx::__aligned_membuf<std::pair<const int, hipcub::CachingDeviceAllocator::TotalBytes>>::_Tp2'
 #0 0x000055ad6f6dc395 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055ad6f6d9ae4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f34cd903520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x000055ad72118ebd clang::CXXMethodDecl::isCopyAssignmentOperator() const (/opt/rocm-5.4.3/llvm/bin/clang-15+0x50daebd)
 #4 0x000055ad7154fc7f clang::Sema::checkTypeSupport(clang::QualType, clang::SourceLocation, clang::ValueDecl*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4511c7f)
 #5 0x000055ad71878b46 clang::Sema::DiagnoseUseOfDecl(clang::NamedDecl*, llvm::ArrayRef<clang::SourceLocation>, clang::ObjCInterfaceDecl const*, bool, bool, clang::ObjCInterfaceDecl*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x483ab46)
 #6 0x000055ad7189d50c clang::Sema::BuildDeclarationNameExpr(clang::CXXScopeSpec const&, clang::DeclarationNameInfo const&, clang::NamedDecl*, clang::NamedDecl*, clang::TemplateArgumentListInfo const*, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x485f50c)
 #7 0x000055ad71d705aa clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDeclRefExpr(clang::DeclRefExpr*) SemaTemplateInstantiate.cpp:0:0
 #8 0x000055ad71d49d11 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExpr(clang::Expr*) SemaTemplateInstantiate.cpp:0:0
 #9 0x000055ad71d5314d clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) SemaTemplateInstantiate.cpp:0:0
#10 0x000055ad71d7955a clang::Sema::SubstExpr(clang::Expr*, clang::MultiLevelTemplateArgumentList const&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d3b55a)
#11 0x000055ad71677938 bool calculateConstraintSatisfaction<calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::TemplateArgument>, clang::SourceLocation, clang::MultiLevelTemplateArgumentList&, clang::Expr const*, clang::ConstraintSatisfaction&)::'lambda'(clang::Expr const*)&>(clang::Sema&, clang::Expr const*, clang::ConstraintSatisfaction&, calculateConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::TemplateArgument>, clang::SourceLocation, clang::MultiLevelTemplateArgumentList&, clang::Expr const*, clang::ConstraintSatisfaction&)::'lambda'(clang::Expr const*)&) SemaConcept.cpp:0:0
#12 0x000055ad71679437 CheckConstraintSatisfaction(clang::Sema&, clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::ArrayRef<clang::TemplateArgument>, clang::SourceRange, clang::ConstraintSatisfaction&) SemaConcept.cpp:0:0
#13 0x000055ad71679690 clang::Sema::CheckConstraintSatisfaction(clang::NamedDecl const*, llvm::ArrayRef<clang::Expr const*>, llvm::ArrayRef<clang::TemplateArgument>, clang::SourceRange, clang::ConstraintSatisfaction&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x463b690)
#14 0x000055ad71679f33 clang::Sema::CheckFunctionConstraints(clang::FunctionDecl const*, clang::ConstraintSatisfaction&, clang::SourceLocation) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x463bf33)
#15 0x000055ad71b94549 clang::Sema::AddMethodCandidate(clang::CXXMethodDecl*, clang::DeclAccessPair, clang::CXXRecordDecl*, clang::QualType, clang::Expr::Classification, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, llvm::MutableArrayRef<clang::ImplicitConversionSequence>, clang::OverloadCandidateParamOrder) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4b56549)
#16 0x000055ad71a634f1 clang::Sema::LookupSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, bool, bool, bool, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4a254f1)
#17 0x000055ad716940a3 clang::Sema::inferCUDATargetForImplicitSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, clang::CXXMethodDecl*, bool, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x46560a3)
#18 0x000055ad717cdf99 clang::Sema::DeclareImplicitCopyAssignment(clang::CXXRecordDecl*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x478ff99)
#19 0x000055ad717ce4e4 clang::Sema::AddImplicitlyDeclaredMembersToClass(clang::CXXRecordDecl*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x47904e4)
#20 0x000055ad716e3ff0 clang::Sema::ActOnFields(clang::Scope*, clang::SourceLocation, clang::Decl*, llvm::ArrayRef<clang::Decl*>, clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesView const&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x46a5ff0)
#21 0x000055ad71d65e41 clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d27e41)
#22 0x000055ad71ded381 void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::'lambda0'()>(long) SemaType.cpp:0:0
#23 0x000055ad7153d5d5 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x44ff5d5)
#24 0x000055ad71df2cbe clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4db4cbe)
#25 0x000055ad71df2e69 clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4db4e69)
#26 0x000055ad71582b5f clang::Sema::RequireCompleteDeclContext(clang::CXXScopeSpec&, clang::DeclContext*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4544b5f)
#27 0x000055ad7189e20c clang::Sema::BuildQualifiedDeclarationNameExpr(clang::CXXScopeSpec&, clang::DeclarationNameInfo const&, bool, clang::Scope const*, clang::TypeSourceInfo**) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x486020c)
#28 0x000055ad71d702fa clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformDependentScopeDeclRefExpr(clang::DependentScopeDeclRefExpr*, bool, clang::TypeSourceInfo**) SemaTemplateInstantiate.cpp:0:0
#29 0x000055ad71d77e31 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformUnaryExprOrTypeTraitExpr(clang::UnaryExprOrTypeTraitExpr*) SemaTemplateInstantiate.cpp:0:0
#30 0x000055ad71d7955a clang::Sema::SubstExpr(clang::Expr*, clang::MultiLevelTemplateArgumentList const&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d3b55a)
#31 0x000055ad71d804ce instantiateDependentAlignedAttr(clang::Sema&, clang::MultiLevelTemplateArgumentList const&, clang::AlignedAttr const*, clang::Decl*, bool) SemaTemplateInstantiateDecl.cpp:0:0
#32 0x000055ad71dc58a4 clang::Sema::InstantiateAttrs(clang::MultiLevelTemplateArgumentList const&, clang::Decl const*, clang::Decl*, llvm::SmallVector<clang::Sema::LateInstantiatedAttribute, 16u>*, clang::LocalInstantiationScope*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d878a4)
#33 0x000055ad71dc94c7 clang::TemplateDeclInstantiator::VisitFieldDecl(clang::FieldDecl*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d8b4c7)
#34 0x000055ad71d65d66 clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d27d66)
#35 0x000055ad71d7fdbe clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d41dbe)
#36 0x000055ad71ded2f3 void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::'lambda'()>(long) SemaType.cpp:0:0
#37 0x000055ad7153d5d5 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x44ff5d5)
#38 0x000055ad71df2dcf clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4db4dcf)
#39 0x000055ad71df2e69 clang::Sema::RequireCompleteType(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4db4e69)
#40 0x000055ad716e331f clang::Sema::CheckFieldDecl(clang::DeclarationName, clang::QualType, clang::TypeSourceInfo*, clang::RecordDecl*, clang::SourceLocation, bool, clang::Expr*, clang::InClassInitStyle, clang::SourceLocation, clang::AccessSpecifier, clang::NamedDecl*, clang::Declarator*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x46a531f)
#41 0x000055ad71dc949c clang::TemplateDeclInstantiator::VisitFieldDecl(clang::FieldDecl*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d8b49c)
#42 0x000055ad71d65d66 clang::Sema::InstantiateClass(clang::SourceLocation, clang::CXXRecordDecl*, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d27d66)
#43 0x000055ad71d7fdbe clang::Sema::InstantiateClassTemplateSpecialization(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d41dbe)
#44 0x000055ad71ded2f3 void llvm::function_ref<void ()>::callback_fn<clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*)::'lambda'()>(long) SemaType.cpp:0:0
#45 0x000055ad7153d5d5 clang::Sema::runWithSufficientStackSpace(clang::SourceLocation, llvm::function_ref<void ()>) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x44ff5d5)
#46 0x000055ad71df2dcf clang::Sema::RequireCompleteTypeImpl(clang::SourceLocation, clang::QualType, clang::Sema::CompleteTypeKind, clang::Sema::TypeDiagnoser*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4db4dcf)
#47 0x000055ad71776530 clang::Sema::IsDerivedFrom(clang::SourceLocation, clang::QualType, clang::QualType) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4738530)
#48 0x000055ad71b71136 clang::Sema::IsPointerConversion(clang::Expr*, clang::QualType, clang::QualType, bool, clang::QualType&, bool&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4b33136)
#49 0x000055ad71b8cc6d IsStandardConversion(clang::Sema&, clang::Expr*, clang::QualType, bool, clang::StandardConversionSequence&, bool, bool) SemaOverload.cpp:0:0
#50 0x000055ad71b9aa75 TryImplicitConversion(clang::Sema&, clang::Expr*, clang::QualType, bool, clang::Sema::AllowedExplicit, bool, bool, bool, bool) SemaOverload.cpp:0:0
#51 0x000055ad71b942cb TryCopyInitialization(clang::Sema&, clang::Expr*, clang::QualType, bool, bool, bool, bool) SemaOverload.cpp:0:0
#52 0x000055ad71b9480a clang::Sema::AddMethodCandidate(clang::CXXMethodDecl*, clang::DeclAccessPair, clang::CXXRecordDecl*, clang::QualType, clang::Expr::Classification, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool, bool, llvm::MutableArrayRef<clang::ImplicitConversionSequence>, clang::OverloadCandidateParamOrder) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4b5680a)
#53 0x000055ad71b98d55 clang::Sema::AddOverloadedCallCandidates(clang::UnresolvedLookupExpr*, llvm::ArrayRef<clang::Expr*>, clang::OverloadCandidateSet&, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4b5ad55)
#54 0x000055ad71b99078 clang::Sema::buildOverloadedCallSet(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::OverloadCandidateSet*, clang::ActionResult<clang::Expr*, true>*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4b5b078)
#55 0x000055ad71ba5c3c clang::Sema::BuildOverloadedCallExpr(clang::Scope*, clang::Expr*, clang::UnresolvedLookupExpr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4b67c3c)
#56 0x000055ad718cbd83 clang::Sema::BuildCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*, bool, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x488dd83)
#57 0x000055ad718d161b clang::Sema::ActOnCallExpr(clang::Scope*, clang::Expr*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, clang::Expr*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x489361b)
#58 0x000055ad71d53240 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) SemaTemplateInstantiate.cpp:0:0
#59 0x000055ad71d4b7ef clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformExprs(clang::Expr* const*, unsigned int, bool, llvm::SmallVectorImpl<clang::Expr*>&, bool*) SemaTemplateInstantiate.cpp:0:0
#60 0x000055ad71d531ce clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) SemaTemplateInstantiate.cpp:0:0
#61 0x000055ad71d79811 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*, clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::StmtDiscardKind) SemaTemplateInstantiate.cpp:0:0
#62 0x000055ad71d7b10b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#63 0x000055ad71d7969e clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformWhileStmt(clang::WhileStmt*) SemaTemplateInstantiate.cpp:0:0
#64 0x000055ad71d7b10b clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#65 0x000055ad71d7fc90 clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d41c90)
#66 0x000055ad71dc2760 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d84760)
#67 0x000055ad71dc080f clang::Sema::PerformPendingInstantiations(bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d8280f)
#68 0x000055ad71dc2106 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d84106)
#69 0x000055ad71dc080f clang::Sema::PerformPendingInstantiations(bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x4d8280f)
#70 0x000055ad7155b6c6 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.0) Sema.cpp:0:0
#71 0x000055ad7155be5d clang::Sema::ActOnEndOfTranslationUnit() (/opt/rocm-5.4.3/llvm/bin/clang-15+0x451de5d)
#72 0x000055ad7141a4e5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x43dc4e5)
#73 0x000055ad7140b36a clang::ParseAST(clang::Sema&, bool, bool) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x43cd36a)
#74 0x000055ad701c3939 clang::FrontendAction::Execute() (/opt/rocm-5.4.3/llvm/bin/clang-15+0x3185939)
#75 0x000055ad70150d81 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x3112d81)
#76 0x000055ad7027ecd0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0x3240cd0)
#77 0x000055ad6de50085 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/rocm-5.4.3/llvm/bin/clang-15+0xe12085)
#78 0x000055ad6de4951c ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#79 0x000055ad6de4bd30 clang_main(int, char**) (/opt/rocm-5.4.3/llvm/bin/clang-15+0xe0dd30)
#80 0x00007f34cd8ead90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#81 0x00007f34cd8eae40 call_init ./csu/../csu/libc-start.c:128:20
#82 0x00007f34cd8eae40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#83 0x000055ad6de489d5 _start (/opt/rocm-5.4.3/llvm/bin/clang-15+0xe0a9d5)
clang-15: error: unable to execute command: Segmentation fault (core dumped)
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.3 23045 a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.4.3/llvm/bin
clang-15: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
```

# Tested compiler

AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.3 23045 a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed)

# Additional notes

Reproducer was created by running:
```shell
echo "#include <hipcub/backend/rocprim/util_allocator.hpp>" | /opt/rocm-5.4.3/llvm/bin/clang++ -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -isystem /opt/rocm-5.4.3/hip/include -isystem /opt/rocm-5.4.3/llvm/lib/clang/15.0.0/include/.. -isystem /opt/rocm-5.4.3/include -std=gnu++20 -x hip -E - > hipcub_allocator.ii
```

**Comment by dmcdougall** [comment] 2023-04-12 22:02
@fweig Thanks.  I'll take a look at it.

**Comment by dmcdougall** [comment] 2023-04-12 23:23
I took the reproducer and minimised it.  Here's a smaller reproducer:

```cxx
template <  typename _T2 > struct pair {
  _T2 second;
  template < typename , typename > static bool _S_assignable(;
  void operator=(pair ) requires(
      _S_assignable<  _T1 , _T2 >()}template < typename _Tp > struct __aligned_membuf {
  struct _Tp2 {
    _Tp _M_t}alignas(__alignof__(_Tp2:_M_t)) char _M_storage;
  namespace  
    struct _Rb_tree_node_base ;template < typename _Val >
    struct _Rb_tree_node  {
      __aligned_membuf< _Val > _M_storage}class TotalBytes
    template < typename > struct _Rb_tree {
      typedef _Rb_tree_node< pair<  stdTotalBytes > > *_Link_type;
      static _Link_type _S_right(;
      static  int  _S_right(std_Rb_tree_node_base *) ;
    void _M_erase(_Link_type );
      _Rb_tree()  {
              _M_erase(0);
            }
      };
    template < typename _Alloc >
    void _Rb_tree< _Alloc >::_M_erase(_Link_type __x) {
      while (0) {
        _M_erase(_S_right(__x));
      }
    }struct  {
      _Rb_tree<int> _M_t} cached_bytes;
    struct TotalBytes {
      TotalBytes();
    };
```

**Comment by dmcdougall** [comment] 2023-04-13 14:50
Hang on, that code is total nonsense.  Apologies.

**Comment by dmcdougall** [comment] 2023-04-17 23:48
Ok here's an example that fails to compile with the same error message and also isn't ill-formed:

```c++
#include <map>
struct CachingDeviceAllocator {
  struct TotalBytes {
    TotalBytes();
  };
  typedef std::map<int, TotalBytes> GpuCachedBytes;
  GpuCachedBytes cached_bytes;
  CachingDeviceAllocator() {}
};
```
This fails to compile with the same error message as in the original bug report.  And it succeeds to compile with `-std=c++17`.  Here are my working and failing compile lines, respectively, for completeness:

```bash
# Working
$ /opt/rocm-5.4.3/llvm/bin/clang++ -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -isystem /opt/rocm-5.4.3/hip/include -isystem /opt/rocm-5.4.3/llvm/lib/clang/15.0.0/include/.. -isystem /opt/rocm-5.4.3/include -std=c++17 -x hip -c file.cxx

# Failing (with same backtrace)
$ /opt/rocm-5.4.3/llvm/bin/clang++ -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -isystem /opt/rocm-5.4.3/hip/include -isystem /opt/rocm-5.4.3/llvm/lib/clang/15.0.0/include/.. -isystem /opt/rocm-5.4.3/include -std=c++20 -x hip -c file.cxx
```

Fortunately, this error seems to disappear with LLVM 16: https://gcc.godbolt.org/z/6KK1nKcnW
And is present in LLVM 15: https://gcc.godbolt.org/z/hbGv5Gd88

@fweig So, I think the conclusion is that this bug is actually already fixed.  It looks like there may be cases where LLVM 15 doesn't provide enough C++20 support: https://clang.llvm.org/cxx_status.html#cxx20

From the ROCm side, I expect this problem will be resolved in a future ROCm release when it moves to LLVM 16.  From the clang/llvm side, I suspect it's probably fine to close this ticket but @fweig should confirm.

**Comment by fweig** [comment] 2023-04-18 09:58
@dmcdougall, thank you for investigating! Seeing that the issue was already fixed upstream, I'm totally fine with closing this ticket.

**Closed** 2023-04-18 16:43 UTC
Labels: clang:frontend, crash
