### ISSUE TITLE
WRONG CODE: bad integer conversion at -O1/-Og

### ISSUE THREAD

**Issue by JonPsson** [llvm/llvm-project#50861] opened 2021-08-18 09:11 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51519](https://llvm.org/bz51519) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@JonPsson,@uweigand |

## Extended Description 
This program involves a conversion from signed to unsigned and then back again, which should be well-defined. I understand that llvm should follow gccs bahaviour found here: https://gcc.gnu.org/onlinedocs/gcc/Integers-implementation.html#Integers-implementation.

It seems to print '1' typically, except at -O1 (and -Og) for some reason:

gcc -march=z13 -O0 wrong0.i -o a.out -w; ./a.out
1
clang -march=arch13 -O2 wrong0.i -o a.out -w; ./a.out
1
clang -march=arch13 -O1 wrong0.i -o a.out -w; ./a.out
0

This was run on SystemZ, but it should probably run the same on other architectures...

long a, e;
long *b = &a;
int c, d;
int main() {
  int f = -1452951746;
  long *g = &e;
h:
i:
  if (((0 != 8) != (*g = (f >= (-(unsigned)f)))) || b)
    ;
  else {
    int j;
    for (; 7;) {
      char k;
      d = 0;
      for (; d; d--)
    for (; c;)
          f = 0;
      for (; 0;)
    goto h;
      if (c)
    goto i;
      b = 0;
    }
  }
  printf("%d\n", ((int) e));
}

**Comment by fhahn** [comment] 2022-04-11 15:31
It looks like this has been fixed recently. It fails with 14.0 but passes with  current `main`: https://godbolt.org/z/vfj7z3s79

Looking closer at the difference between 14.0 and main, SimplifyCFG used to simplify the last `store 1` to `store undef`. That's not happening on `main` any longer. @JonPsson I am closing the issue but please re-open it with additional info if it still reproduces on your end.

**Closed by fhahn** 2022-04-11 15:31 UTC
Labels: bugzilla, miscompilation
