### ISSUE TITLE
clang14/mips crashes compiling qtlocations package on linux

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#54005] opened 2022-02-23 02:15 UTC
Attached testcase crashes the compiler when using `-O2` or `-Ofast`, it works ok with `-O1`, `-Os`

```
fatal error: error in backend: Cannot select: 0x559a37f85fe0: f64 = fabs nnan ninf nsz arcp contract afn reassoc 0x559a384adf98, git/src/3rdparty/clipper/clipper.cpp:3974:7
  0x559a384adf98: f64,ch = CopyFromReg 0x559a369e5068, Register:f64 %323, git/src/3rdparty/clipper/clipper.cpp:3974:7
    0x559a37f85ea8: f64 = Register %323
In function: _ZN12QtClipperLib13ClipperOffset8DoOffsetEd

```
[clipper-c6fc58.tar.gz](https://github.com/llvm/llvm-project/files/8121410/clipper-c6fc58.tar.gz)

**Comment by EugeneZelenko** [comment] 2022-02-23 02:19
Could you please provide full message? Is it compiler or linker crash?

**Comment by atanasyan** [comment] 2022-02-24 07:58
Duplicate of #53722.

**Closed by atanasyan** 2022-02-24 07:58 UTC
Labels: new issue
