### ISSUE TITLE
[clang] Question about devirtualization

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#116070] opened 2024-11-13 15:57 UTC
Here is the test case
```cpp
struct A {
    virtual int f() {
        return 1;
    }

    int call_f() {
        return f();
    }
};

struct C final: public A {
    int f() override {
        return 3;
    }
};

int test1(C& c) {
    return c.f();
}

int test2(C& c) {
    return c.call_f();
}
```
Both Clang and GCC devirtualize `f` call in `test1` but not in `test2` - why is that so? `C` is final, what is the scenario when call to `C::call_f` does not lead to `C::f`?
https://godbolt.org/z/6Kv38jeYo

**Comment by efriedma-quic** [comment] 2024-11-13 21:52
At least in clang, it's a layering issue; the clang frontend is aware that we have a "C" object, so if it sees a call, it can devirtualize.  But that fact isn't recorded into LLVM IR, so we can't devirtualize after inlining.

I think this is a duplicate of #61950.

**Closed by efriedma-quic** 2024-11-13 21:52 UTC
Labels: question, llvm:optimizations
