### ISSUE TITLE
Why clang does not support split-stack while having vararg but gcc does

### ISSUE THREAD

**Issue by zzkcode** [llvm/llvm-project#63768] opened 2023-07-10 03:29 UTC
### Background
We are building an application that uses `-fsplit-stack`, but it seems Clang does not support split-stack while having vararg but GCC does do. And there are already some issues(https://github.com/llvm/llvm-project/issues/40064, https://github.com/llvm/llvm-project/issues/19571) related to this, but since our application link so many other libs, it is almost impossible to use `attribute((no_split_stack))` in all places as a workaround.

### Questions
So here are my questions:
- Just curious: Clang does not support split-stack while having varargs, is that because the variadic arguments on the old stack are not copied or make references to, but GCC does?
- Will Clang consider supporting split-stack while having varargs in the near future or is it just technically impossible under Clang?

Our application switched from GCC to Clang years ago, and already using some flags and features that only Clang supports. So it may be hard to switch back. Any comments/suggestions will be appreciated. Thanks!

### Example Codes
```c
#include <stdio.h>
#include <stdarg.h>

void greet(int count, ...)
//void greet(int count, ...) __attribute__((no_split_stack))
{
    va_list args;
    va_start(args, count);

    for (int i = 0; i < count; i++) {
        char* name = va_arg(args, char*);
        printf("Hello, %s!\n", name);
    }

    va_end(args);
}

void call_loop(int i) {
    char a[10 * 1024];

    if (i > 0) {
    	call_loop(i-1);
    }
}

int main()
{
    greet(3, "Alice", "Bob", "Charlie");
    call_loop(1024);
    return 0;
}
```

clang output:
```bash
$ clang -fsplit-stack -g -O0 vararg_split_stack.c
fatal error: error in backend: Segmented stacks do not support vararg functions.
clang-16: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 16.0.0 (Red Hat 16.0.0-2.module_el8+405+25122a8c)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-16: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-16: note: diagnostic msg: /tmp/vararg_split_stack-422cf6.c
clang-16: note: diagnostic msg: /tmp/vararg_split_stack-422cf6.sh
clang-16: note: diagnostic msg:
```

gcc output:
```bash
$ gcc -fsplit-stack -g -O0 vararg_split_stack.c
$ ./a.out
Hello, Alice!
Hello, Bob!
Hello, Charlie!
```

clang/gcc version:
```bash
$ uname -a
Linux 3c5d5bb9b420 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ clang -v
clang version 16.0.0 (Red Hat 16.0.0-2.module_el8+405+25122a8c)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12
Selected GCC installation: /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
```

**Comment by AaronBallman** [comment] 2023-07-10 17:58
CC @echristo @pcc -- before I go on a code archeology expedition, do you have more information by any chance?

**Comment by asl** [comment] 2023-07-11 05:21
@AaronBallman I think situation is explained more or less in https://github.com/llvm/llvm-project/issues/40064#issuecomment-981009164 and around

**Comment by zzkcode** [comment] 2023-07-11 06:26
@asl Thanks, I had read this issue before, however, what I'm curious about now is **the difference between Clang and GCC**. I assume they will finally call into libgcc for `morestack`, but it seems GCC does support `-fsplit-stack` even if there are varargs, while Clang does not. And I'm wondering if will it be supported in further Clang.

**Comment by AaronBallman** [comment] 2023-08-09 13:33
> @AaronBallman I think situation is explained more or less in [#40064 (comment)](https://github.com/llvm/llvm-project/issues/40064#issuecomment-981009164) and around

Ah, thank you!

> And I'm wondering if will it be supported in further Clang.

I'm not aware of a reason why we wouldn't want to fix this issue, but there's no timeline for a fix. I think this is a bug, and we can probably close this issue as a duplicate of #19571.

**Closed** 2023-08-20 01:41 UTC
Labels: duplicate, question
