### ISSUE TITLE
clang-format crashes or deadlocks the system with certain files

### ISSUE THREAD

**Issue by laoshaw** [llvm/llvm-project#59087] opened 2022-11-19 23:53 UTC
[minilzo.c.txt](https://github.com/llvm/llvm-project/files/10048147/minilzo.c.txt)
[lzodefs.h.txt](https://github.com/llvm/llvm-project/files/10048148/lzodefs.h.txt)

Run `clang-format -i minilzo.c`, or `clang-format -i lzodefs.h` attached here (with default `.clang-format`), will takes 10+ minutes and either make the system totally unresponsive (Ubuntu 20.04) or leads to a power recycle by pressing the power button for 6 seconds (as the system appears to totally dead) or it will segfault after 10+ minutes. Tested both clang-format 12 and 15.

**Comment by rymiel** [comment] 2022-11-20 01:05
Duplicate of #53888

**Closed by rymiel** 2022-11-20 01:05 UTC
Labels: clang-format
