### ISSUE TITLE
Clang hang at -O1 on x86_64-linux_gnu (a recent regression in InstCombinePass)

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#63905] opened 2023-07-17 10:12 UTC
This looks like a recent regression.
Clang would hang at -O1 on the following test case. `opt-bisect-limit` suggests that the issue might be in `InstCombinePass`.

Compiler explorer: https://godbolt.org/z/YxeGxrWod

```console
% cat a.c
int g_3, g_637;
int foo(unsigned x, unsigned n) { return x << n | x >> (32 - n); }
int func_1() {
  int l_26;
  g_3 = 5;
  for (;; g_3 -= 1) {
    int l_4;
    for (; l_26; l_26 -= 1) {
      long l_2068;
      g_637 = 0;
      for (; g_637 <= 6;)
        for (;;) {
          int ij;
          if ((char)(foo(g_3, 2) + g_3))
            break;
          return 0;
        }
    }
  }
}
int main() {}
%
% clang-tk -O1 a.c
Killed
% clang-tk -v
clang version 17.0.0 (https://github.com/llvm/llvm-project.git 46333f71f8e0d6444a9b2c9e063aedb83ebb9735)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /zdata/shaoli/compilers/ccbuilder-compilers
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
%
```

**Comment by Karan741187** [comment] 2023-07-17 12:02
Hey, I'm new to open source and interested in this project. I've done programming in c and c++.
What are the prerequisites for contributing on this project

**Comment by nikic** [comment] 2023-07-17 12:27
Based on the code, it's probably a duplicate of https://github.com/llvm/llvm-project/issues/63699.

**Comment by dtcxzyw** [comment] 2023-10-22 17:42
I cannot reproduce this crash with the trunk version of LLVM.

**Comment by antoniofrighetto** [comment] 2023-12-23 17:16
Closing this as not reproducible on clang trunk (acacec3bbf4586ef9bc6c4f31707d3515d5215a1) (https://godbolt.org/z/T47f5Gnzq) w/ assertions enabled, feel free to reopen should you encounter a related issue.

**Closed by antoniofrighetto** 2023-12-23 17:16 UTC
Labels: llvm:instcombine, llvm:hang
