### ISSUE TITLE
clang-format 15 crash with stack dump and return code 139

### ISSUE THREAD

**Issue by M-Bab** [llvm/llvm-project#62604] opened 2023-05-08 10:19 UTC
We managed to make Clang-Format crash :tada: 

Here is the stack dump:

```console
Stack dump:
0.      Program arguments: clang-format crc8.c
 #0 0x00007f04b637baaa (/usr/lib/libLLVM-15.so+0xd7baaa)
 #1 0x00007f04b637913f llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-15.so+0xd7913f)
 #2 0x00007f04b637928d (/usr/lib/libLLVM-15.so+0xd7928d)
 #3 0x00007f04b5051f50 (/usr/lib/libc.so.6+0x38f50)
 #4 0x00007f04bf512710 clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions&&) (/usr/lib/libclang-cpp.so.15+0x2512710)
 #5 0x00007f04bf513695 clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) (/usr/lib/libclang-cpp.so.15+0x2513695)
 #6 0x00007f04bf549d15 clang::format::WhitespaceManager::generateReplacements() (/usr/lib/libclang-cpp.so.15+0x2549d15)
 #7 0x00007f04bf4e843c (/usr/lib/libclang-cpp.so.15+0x24e843c)
 #8 0x00007f04bf53fb67 clang::format::TokenAnalyzer::process() (/usr/lib/libclang-cpp.so.15+0x253fb67)
 #9 0x00007f04bf708638 (/usr/lib/libclang-cpp.so.15+0x2708638)
#10 0x00007f04bf48fcdb (/usr/lib/libclang-cpp.so.15+0x248fcdb)
#11 0x00007f04bf4ef42c clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/usr/lib/libclang-cpp.so.15+0x24ef42c)
#12 0x00007f04bf4f2ae0 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/usr/lib/libclang-cpp.so.15+0x24f2ae0)
#13 0x000055f591f85d89 (/usr/bin/clang-format+0xed89)
#14 0x000055f591f7de25 (/usr/bin/clang-format+0x6e25)
#15 0x00007f04b503c790 (/usr/lib/libc.so.6+0x23790)
#16 0x00007f04b503c84a __libc_start_main (/usr/lib/libc.so.6+0x2384a)
#17 0x000055f591f7e6e5 (/usr/bin/clang-format+0x76e5)
Segmentation fault (core dumped)
```

Good thing: I can provide a very minimalistic piece of code that compiles but leads to a crash of Clang-Format:

[crc8.zip](https://github.com/llvm/llvm-project/files/11420203/crc8.zip)

It crashes by this piece of code:

```c
static const CRC8_CTX asCrc8NamedCtxs[CRC8_NAME_LAST_ENTRY] =
{
  /*! Context for CRC8-MAXIM, @ref CRC8_NAME_MAXIM */
  {
    .pau8LUT            = au8Crc8Table_MAXIM,  //The table 'au8Crc8Table_MAXIM' is reflected.
    .u8InitialValue     = 0x00U,
    .u8FinalXorValue    = 0x00U,
    .bReflectedInput    = false, //Not reflected because whole table is reflected.
    .bReflectedOutput   = false  //Not reflected because whole table is reflected.
  }
};
```

**Comment by VoltrexKeyva** [comment] 2023-05-08 10:39
We only support the latest LLVM release which is v16 as of writing this, Clang-Format 16 does not crash on this.

**Comment by rymiel** [comment] 2023-05-08 11:09
Duplicate of https://github.com/llvm/llvm-project/issues/55493

**Closed by rymiel** 2023-05-08 11:09 UTC
Labels: clang-format
