### ISSUE TITLE
`offsetof()` doesn't support `::` in member names

### ISSUE THREAD

**Issue by HolyBlackCat** [llvm/llvm-project#63443] opened 2023-06-21 23:08 UTC
I'm not sure what the standard has to say about it, but GCC and MSVC accept it, and it can be a useful feature.

E.g. GCC and MSVC accept following code:
```cpp
#include <cstddef>
#include <iostream>

struct Empty {};

#define FOO [[no_unique_address]] Empty e;

struct A
{
    FOO int x;
};

struct B
{
    FOO int y;
};

struct C : A, B
{
    FOO int z;
};

template <typename D, typename B>
constexpr std::size_t base_offset = offsetof(D, B::e);

int main()
{
    std::cout << base_offset<C, A> << '\n'; // 0
    std::cout << base_offset<C, B> << '\n'; // 4
    std::cout << base_offset<C, C> << '\n'; // 8
}
```

While Clang trunk says:
```console
<source>:24:50: error: expected ')'
   24 | constexpr std::size_t base_offset = offsetof(D, B::e);
      |                                                  ^
```

**Comment by shafik** [comment] 2023-06-22 22:06
C11 says [7.19p3](https://port70.net/~nsz/c/c11/n1570.html#7.19p3)

> offsetof(type, member-designator)
>
> which expands to an integer constant expression that has type size_t, the value of which is the offset in bytes, to the structure member (designated by member-designator), from the beginning of its structure (designated by type). The type and member designator shall be such that given
>
> static type t;
>
> then the expression &(t.member-designator) evaluates to an address constant. (If the specified member is a bit-field, the behavior is undefined.)

and `&(c.B::e)` looks valid to me. So I think we should accept this.

CC @AaronBallman @zygoloid for second opinions

**Comment by zygoloid** [comment] 2023-06-22 22:51
The C++ rule is:

> The macro `offsetof(`*type*`, `*member-designator*`)` has the same semantics as the corresponding macro in the C standard library header <stddef.h> [...]

... which I take to mean, that in particular it accepts the same forms of *member-designator*s as the C `offsetof` macro accepts. Unfortunately, there is no agreement on what a *member-designator* might be (see the open C issue https://www.open-std.org/jtc1/sc22/wg14/www/docs/summary.htm#dr_496)... but C's Annex J.2 seems pretty unambiguous to me:

> The behavior is undefined in the following circumstances:
> - [...]
> - The *member-designator* parameter of an `offsetof` macro is an invalid right operand of the `.` operator for the *type* parameter, or designates a bit-field (7.19)

The right operand of the `.` operator in C is simply an *identifier*`, which to me implies that supporting anything other than an *identifier* as a *member-designator* in C is an extension, and the same would presumably apply in C++.

I think supporting a qualified name here would be an extension. But I think it's a reasonable extension and one that the macro implementation of `offsetof` permits, and we already support other such extensions (chained designators and array designators), so I'd lean towards accepting this too -- especially given that other implementations do so.

**Comment by zygoloid** [comment] 2023-06-22 22:52
(And for what it's worth, I'd support a change to the C++ standard to explicitly say that the C++ `offsetof` macro supports qualified field names. Though I'd prefer that we add standard library functions to convert between offsets and pointers-to-data-members.)

**Comment by AaronBallman** [comment] 2023-06-23 11:26
> I think supporting a qualified name here would be an extension. But I think it's a reasonable extension and one that the macro implementation of `offsetof` permits, and we already support other such extensions (chained designators and array designators), so I'd lean towards accepting this too -- especially given that other implementations do so.

I think it is a reasonable extension as well, but it's worth noting the code already relies on an extension because `C` is not standard-layout (http://eel.is/c++draft/class.prop#3.5, https://eel.is/c++draft/support#types.layout-1.sentence-2). Also something I think we should support when the result is a constant.

**Comment by cor3ntin** [comment] 2023-09-08 09:32
Closing as duplicate of https://github.com/llvm/llvm-project/issues/64154, a lot more discussion on the other issue

**Closed by cor3ntin** 2023-09-08 09:32 UTC
Labels: duplicate, clang:frontend
