### ISSUE TITLE
请问为什么每次下载都会失败？点【继续】按钮会提示“需要获得授权”？

### ISSUE THREAD

**Issue by youngvery** [llvm/llvm-project#55975] opened 2022-06-10 09:49 UTC
![image](https://user-images.githubusercontent.com/13428561/173039520-f84a2023-b5a7-411c-b388-cde5831ef1ad.png)
请问为什么每次下载都会失败？点【继续】按钮会提示“需要获得授权”？

**Comment by movie-travel-code** [comment] 2022-06-10 10:17
**This is not an LLVM problem,** but a chrome problem. Chrome will check the executable binary for security.

**Comment by fhahn** [comment] 2022-06-10 10:47
Unfortunately it is not clear what the issue is here. I'm going to close this for now. If there's an issue on the LLVM side here please feel free to re-open the issue with additional details.

**Closed by fhahn** 2022-06-10 10:47 UTC
Labels: invalid, new issue
