### ISSUE TITLE
mlir started to fail with `multiple definition`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#60379] opened 2023-01-30 09:16 UTC
On Linux ARM64:
```console
/usr/bin/ld.gold: error: tools/mlir/lib/Target/LLVMIR/CMakeFiles/obj.MLIRTargetLLVMIRImport.dir/AttrKindDetail.cpp.o: multiple definition of 'mlir::LLVM::detail::getAttrKindToNameMapping()'
/usr/bin/ld.gold: tools/mlir/lib/Target/LLVMIR/CMakeFiles/obj.MLIRTargetLLVMIRExport.dir/AttrKindDetail.cpp.o: previous definition here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by joker-eph** [comment] 2023-01-31 01:46
I think this is caused by  https://reviews.llvm.org/D142635 ; but was reverted in bd0c809209fe43dc79d3521bf609698cdec5864c

Closing, feel free to re-open if it isn't!

**Closed by joker-eph** 2023-01-31 01:46 UTC
Labels: build-problem, mlir
