### ISSUE TITLE
[libc++/clang] std::ranges::views::take does not work with | operator

### ISSUE THREAD

**Issue by mattreecebentley** [llvm/llvm-project#55673] opened 2022-05-24 10:16 UTC
The following code in C++20:

```cpp
#include <vector>
#include <ranges>


int main()
{
	std::vector<int> i_vec({1, 2, 3});
	auto rng = i_vec | std::ranges::views::take(2);
	return 0;
}

```

Produces the following error in Clang 14.00:

```console
<source>:8:19: error: invalid operands to binary expression ('std::vector<int>' and '_Partial<std::ranges::views::_Take, decay_t<int>>' (aka '_Partial<std::ranges::views::_Take, int>'))
        auto rng = i_vec | std::ranges::views::take(2);
```

Godbolt: https://godbolt.org/z/c35r4Pa1h

The code as far as I can tell, is valid and works in GCC11 and MSVC 2022.
Unsure whether this is a libc++ or clang bug.

**Comment by mattreecebentley** [comment] 2022-05-24 23:34
That would make sense.

**Comment by royjacobson** [comment] 2022-09-23 12:40
Works after https://reviews.llvm.org/D126907, so this was a duplicate of #44178 indeed.

**Closed by royjacobson** 2022-09-23 12:40 UTC
Labels: c++20
