### ISSUE TITLE
Debian packages install broken cmake find modules without libclang-dev

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#63408] opened 2023-06-20 14:38 UTC
It's possible to install the clang package, such that `find_package(Clang)` does not work. `find_package(clang)` finds the installed CMake module from the main clang package, but then errors when the libraries split into libclang-dev aren't present:

```console
CMake Error at /usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake:820 (message):
  The imported target "clangBasic" references the file

     "/usr/lib/llvm-17/lib/libclangBasic.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/cmake/clang-17/ClangConfig.cmake:20 (include)
  CMakeLists.txt:39 (find_package)
```

```console
$ dpkg -S /usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake
clang-17: /usr/lib/llvm-17/lib/cmake/clang/ClangTargets.cmake

$ dpkg -S  /usr/lib/llvm-17/lib/libclangBasic.a
libclang-17-dev: /usr/lib/llvm-17/lib/libclangBasic.a
```

This is using the prebuilt packages from apt.llvm.org

**Comment by asl** [comment] 2023-06-21 01:07
Tagging @sylvestre

**Comment by arsenm** [comment] 2023-08-14 00:16
Possible duplicate #45628

**Comment by jobor** [comment] 2024-09-06 11:28
Yes, this issue here is a duplicate of #45628.

**Closed** 2024-09-06 14:05 UTC
Labels: packaging, platform:linux
