### ISSUE TITLE
-Wunneeded-internal-declaration doesn't consider concept restraints

### ISSUE THREAD

**Issue by bjadamson** [llvm/llvm-project#97077] opened 2024-06-28 16:01 UTC
The following program demonstrates that a concept constraint requires the implementation of operator== for a type when emitting a -unneeded-internal-declaration warning with the following program.

Commenting out the line the compiler states is unnecessary causes a compiler error, and keeping it persists the warning.

```C++
#include <cassert>
#include <concepts>
#include <type_traits>

namespace
{
template <typename T>
concept EqualityComparable = requires(T a, T b)
{
  { a == b } -> std::convertible_to<bool>;
};

template <EqualityComparable T, EqualityComparable U>
auto constexpr
MY_subtract(T const lhs, U const rhs) noexcept
{
  auto const result = lhs.value - rhs.value;
  return result;
}

struct CustomType final
{
  int value;
};

// The line in question:
bool operator==(CustomType const& a, CustomType const& b) noexcept { return a.value == b.value; }
} // namespace

int main(int, char**)
{
  CustomType a{10}, b{3};
  auto result = MY_subtract(a, b);
  assert(7 == result);
}
```

Removing the line from the program (as suggested by the warning) yields the following compiler warning:

```bash
error: no matching function for call to 'MY_subtract'
   33 |   auto result = MY_subtract(a, b);
      |                 ^~~~~~~~~~~
test/core_value.cxx:11:1: note: candidate template ignored: constraints not satisfied [with T = CustomType, U = CustomType]
   11 | MY_subtract(T const lhs, U const rhs) noexcept
      | ^
test/core_value.cxx:9:11: note: because '(anonymous namespace)::CustomType' does not satisfy 'EqualityComparable'
    9 | template <EqualityComparable T, EqualityComparable U>
      |           ^
test/core_value.cxx:6:7: note: because 'a == b' would be invalid: invalid operands to binary expression ('(anonymous namespace)::CustomType' and '(anonymous namespace)::CustomType')
    6 |   { a == b } -> std::convertible_to<bool>;
```

However keeping the line in the program yields the following error:

```bash
[1/2] Building CXX object test/CMakeFiles/core-tests.dir/core_value.cxx.o
test/core_value.cxx:25:6: warning: function 'operator==' is not needed and will not be emitted [-Wunneeded-internal-declaration]
   25 | bool operator==(CustomType const& a, CustomType const& b) noexcept { return a.value == b.value; }
```

```bash
clang --version
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 0f61ba679fa1942397c8d2661f3339c305cc101b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by shafik** [comment] 2024-07-02 23:57
We need `-Wall`: https://godbolt.org/z/Gs7a9ds6r

Looks like a duplicate of: https://github.com/llvm/llvm-project/issues/42943

**Closed by shafik** 2024-07-02 23:57 UTC
Labels: c++20, concepts, clang:diagnostics
