### ISSUE TITLE
clang-format doesn't align compound assignment

### ISSUE THREAD

**Issue by songziming** [llvm/llvm-project#59895] opened 2023-01-09 13:27 UTC
Content of `.clang-format`:

``` yaml
AlignConsecutiveAssignments:
    Enabled: true
    AlignCompound: true
```

C file to be formatted:

```c
int my_func(int y) {
  y           = y + 15;
  y       += 7;
  y   &= ~7;
  return y;
}
```

Format result:

```c
int my_func(int y) {
  y = y + 15;
  y += 7;
  y &= ~7;
  return y;
}
```

But if the file content is:

```c
var          = 5;
var     += 321;
var &= 7;
```

Format result is correct:

```c
var  = 5;
var += 321;
var &= 7;
```

**Comment by rymiel** [comment] 2023-01-09 14:52
Duplicate of https://github.com/llvm/llvm-project/issues/58029

**Closed by rymiel** 2023-01-09 14:52 UTC
Labels: clang-format
