### ISSUE TITLE
clang fails to build for Linux sparc

### ISSUE THREAD

**Issue by victor-ve** [llvm/llvm-project#54779] opened 2022-04-06 13:34 UTC
$ uname -a
Linux sparc64 5.16.0-6-sparc64 #1 Debian 5.16.18-1 (2022-03-29) sparc64 GNU/Linux

$ clang -v
Debian clang version 13.0.1-1
Target: sparc64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/sparc64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/sparc64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/sparc64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/sparc64-linux-gnu/11
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

$ cat ttest.c
#include <stdio.h>
int main(void){
  printf("sizeof(long) = %d\n",sizeof(long));
  return 0;
}

$ clang -no-pie -O0 -m32 -o ttest ttest.c
$ ttest
sizeof(long) = 4

$ clang -no-pie -O3 -m32 -o ttest ttest.c
In file included from ttest.c:1:
In file included from /usr/include/stdio.h:871:
/usr/include/bits/stdio-ldbl.h:26:20: error: cannot apply asm label to function after its first use
__LDBL_REDIR_DECL (vfprintf)
~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/usr/include/sys/cdefs.h:509:26: note: expanded from macro '__LDBL_REDIR_DECL'
  extern __typeof (name) name __asm (__ASMNAME ("__nldbl_" #name));
                         ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by brad0** [comment] 2022-04-09 02:06
This seems to be a duplicate of bug 47994, which possibly is resolved with Clang 14.0.0. Please provide feedback in the other ticket.

**Closed by brad0** 2022-04-09 02:06 UTC
Labels: clang, backend:Sparc
