### ISSUE TITLE
Arm test suite failures since enable-split-backedge-in-load-pre option enabled for GVN

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#55899] opened 2022-06-06 16:13 UTC
Since https://reviews.llvm.org/D126382 landed our test suite bot has been failing to compile 2 tests.

https://lab.llvm.org/buildbot/#/builders/113/builds/5123

I reduced one of the reproducers down to this C:
```c
void a(short *b) {
          long c[9];
          int d;
          short *e = b;
          short f = *e;
#define g(d) c[d] += f * e[d];
  d = 9;
          for (;
        d--;
        c[d] = 0)     ;
          g(3) f = *++e;
          g(3) e = 8;
          g(3) a(c);
        }
```
Compiled with:
```shell
"/home/david.spickett/build-llvm-aarch64/bin/clang-15" "-cc1" "-triple" "thumbv7-unknown-linux-gnueabihf" "-emit-obj" "--mrelax-relocations" "-disable-free" "-clear-ast-before-backend" "-main-file-name" "lpc.c" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=none" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-target-cpu" "cortex-a15" "-target-feature" "-crc" "-target-feature" "-dotprod" "-target-feature" "+dsp" "-target-feature" "-mve" "-target-feature" "-mve.fp" "-target-feature" "-ras" "-target-feature" "-bf16" "-target-feature" "-sb" "-target-feature" "-i8mm" "-target-feature" "-lob" "-target-feature" "-cdecp0" "-target-feature" "-cdecp1" "-target-feature" "-cdecp2" "-target-feature" "-cdecp3" "-target-feature" "-cdecp4" "-target-feature" "-cdecp5" "-target-feature" "-cdecp6" "-target-feature" "-cdecp7" "-target-feature" "-pacbti" "-target-feature" "+hwdiv-arm" "-target-feature" "+hwdiv" "-target-feature" "+vfp2" "-target-feature" "+vfp2sp" "-target-feature" "+vfp3" "-target-feature" "+vfp3d16" "-target-feature" "+vfp3d16sp" "-target-feature" "+vfp3sp" "-target-feature" "+fp16" "-target-feature" "+vfp4" "-target-feature" "+vfp4d16" "-target-feature" "+vfp4d16sp" "-target-feature" "+vfp4sp" "-target-feature" "-fp-armv8" "-target-feature" "-fp-armv8d16" "-target-feature" "-fp-armv8d16sp" "-target-feature" "-fp-armv8sp" "-target-feature" "-fullfp16" "-target-feature" "+fp64" "-target-feature" "+d32" "-target-feature" "+neon" "-target-feature" "-fp16fml" "-target-feature" "-crypto" "-target-feature" "-sha2" "-target-feature" "-aes" "-target-abi" "aapcs-linux" "-mfloat-abi" "hard" "-fallow-half-arguments-and-returns" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debugger-tuning=gdb" "-fcoverage-compilation-dir=/home/david.spickett/sandbox/build/MultiSource/Benchmarks/MiBench/telecomm-gsm" "-D" "NDEBUG" "-D" "STUPID_COMPILER" "-D" "NeedFunctionPrototypes=1" "-D" "SASR" "-O3" "-Werror=date-time" "-w" "-faddrsig" "-x" "c" "test.c"
```

Though it happened on that bot it reproduces elsewhere with a clang built from current main (`facbfb121a5c0a78b3cc4ecc41b15dcef8d9c6a5`) as there's no need to run the code.

**Comment by fhahn** [comment] 2022-06-07 10:33
So it looks like `-arm-parallel-dsp` produces invalid IR: https://llvm.godbolt.org/z/cGKbnzfvq


```
Only PHI nodes may reference their own value!
  %16 = call i32 @llvm.arm.smlad(i32 %8, i32 %1, i32 %16)
in function test
LLVM ERROR: Broken function found, compilation aborted!
```


cc @sparker-arm @sjoerdmeijer

**Comment by sparker-arm** [comment] 2022-06-07 10:38
Thanks for the ping @fhahn and thanks for the reproducer @nikic. I will take a look.

**Comment by sparker-arm** [comment] 2022-06-09 09:12
[Fix committed.](https://github.com/llvm/llvm-project/commit/447c411fef6ed97a404087cc8289aeeb02a8ae5c)

**Closed** 2022-06-13 21:36 UTC
Labels: backend:ARM, miscompilation, llvm:crash
