### ISSUE TITLE
InstCombine hangs in Negator

### ISSUE THREAD

**Issue by vzakhari** [llvm/llvm-project#56601] opened 2022-07-18 23:32 UTC
[main.ll.gz](https://github.com/llvm/llvm-project/files/9136231/main.ll.gz)

Hangs with trunk and 14.0.0: `opt --instcombine main.ll`
`-debug-only=instcombine` shows the following instructions are being produced on and on:
```
    New =   <badref> = add <4 x i64> %shuffle2226.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg.neg., <i64 add (i64 ptrtoint (ptr @_QFEg2y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg1y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg3y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg4y to i64), i64 -1200)>
```

Passes with `-instcombine-negator-enabled=false`.

**Comment by vzakhari** [comment] 2022-07-19 00:11
Reduced IR:
```
@_QFEg1y = external hidden global [150 x [150 x double]]
@_QFEg2y = external hidden global [150 x [150 x double]]

define <4 x i64> @_QQmain(i64 %i2603, i64 %i2606) local_unnamed_addr {
  %i2608 = mul nsw i64 %i2606, 1200
  %i2609 = mul nsw i64 %i2603, 1200
  %i2610 = insertelement <4 x i64> poison, i64 %i2608, i32 0
  %shuffle2225 = shufflevector <4 x i64> %i2610, <4 x i64> poison, <4 x i32> zeroinitializer
  %i2611 = add <4 x i64> %shuffle2225, <i64 add (i64 ptrtoint (ptr @_QFEg1y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg2y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg2y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg1y to i64), i64 -1200)>
  %i2612 = insertelement <4 x i64> poison, i64 %i2609, i32 0
  %shuffle2226 = shufflevector <4 x i64> %i2612, <4 x i64> poison, <4 x i32> zeroinitializer
  %i2613 = add <4 x i64> %shuffle2226, <i64 add (i64 ptrtoint (ptr @_QFEg1y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg2y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg2y to i64), i64 -1200), i64 add (i64 ptrtoint (ptr @_QFEg1y to i64), i64 -1200)>
  %i2614 = sub <4 x i64> %i2611, %i2613
  ret <4 x i64> %i2614
}
```

Hangs the same way with: opt --instcombine rep.ll -instcombine-negator-enabled=true
Passes with: opt --instcombine rep.ll -instcombine-negator-enabled=false

**Comment by rotateright** [comment] 2022-07-21 11:23
The root cause is that we don't match a constant vector that contains constant expressions as a constant expression itself. That problem is more general than Negator or even InstCombine and should be fixed in PatternMatch.h.

It does raise a question: should LLVM allow a constant vector to include constant expressions (cc @nikic )? 
I'm curious how this is created - was the test here reduced from real code?

**Comment by rotateright** [comment] 2022-07-21 11:29
> I'm curious how this is created - was the test here reduced from real code?

Sorry - I see now that the zipped source IR derived from fortran source was included in the first comment, and a vector containing constant expressions is in the IR.

**Comment by vzakhari** [comment] 2022-07-21 16:13
Right, this was produced by Flang.

**Comment by rotateright** [comment] 2022-07-21 16:50
Proposal to fix the PatternMatch:
https://reviews.llvm.org/D130286

**Comment by vzakhari** [comment] 2022-07-21 19:08
Thank you for the prompt resolution!

**Comment by rotateright** [comment] 2022-07-21 21:02
Should be fixed with:
78c09f0f24b6af6d17

**Closed by rotateright** 2022-07-21 21:02 UTC
Labels: llvm:instcombine, llvm:hang
