### ISSUE TITLE
Completion for designated initializers of anonymous structures inside designed initializer

### ISSUE THREAD

**Issue by e3bde77a-984f-4943-b980-b97f576c6543** [llvm/llvm-project#50295] opened 2021-07-01 02:45 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [50951](https://llvm.org/bz50951) |
| Version | unspecified |
| OS | All |

## Extended Description 
Completion of nested initializers now works as of clangd version 13.0.0.

Unfortunately, it does not seem to support anonymous structures and unions.

struct test {
	struct {
		int x;
		struct {
			int y;
		} nested;
	} nested;

	struct {
		int z,w;
	}; // anonymous struct
};

int main()
{
	struct test t = {
		.nested = { .x = 3, .nested = { .y = 6 }, }, // full completion
		. // no completion for anonymous struct members z,w 
	};

 	return 0;
}

**Comment by HighCommander4** [comment] 2023-08-19 04:31
Duplicate of https://github.com/clangd/clangd/issues/836.

**Closed by HighCommander4** 2023-08-19 04:31 UTC
Labels: duplicate, clangd, bugzilla
