### ISSUE TITLE
Value initialization with implied zero-initialization does not occur for derived class

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#69890] opened 2023-10-22 21:19 UTC
This program
```
struct A {
    constexpr A() {}
    int x;
};

struct B : A {
    int y;
};

static_assert( B().x == 0 );
```
shall be accepted because
1. `()` performs value-initialization on `B`: http://eel.is/c++draft/dcl.dcl#dcl.init.general-16.4

2. Since `B`'s ctor is not user-provided, that resolves to zero-initialization followed by default-initialization: http://eel.is/c++draft/dcl.dcl#dcl.init.general-9.1.2

3. Zero-initialization of `B` propagates to `A`, then propagates to `x` and zeroes it, regardless of `A` having a user-provided constructor or not: http://eel.is/c++draft/dcl.dcl#dcl.init.general-6.2

4. Lastly default-initialization of `B` calls `B`'s constructor and in turn calls `A`'s constructor.

Unfortunatly, only MSVC implemented zero-initialization in this scenario by now. Online demo: https://godbolt.org/z/YMv94rabv

GCC has a similar defect, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=108993

Related discussion: https://stackoverflow.com/a/77273671/7325599

**Comment by shafik** [comment] 2023-10-23 20:17
Confirmed.

When we get here when the `Entity` is `B` we do execute this code as would be expected:

https://github.com/llvm/llvm-project/blob/159614a52f0bcb96513b1d18ed475e69250b5240/clang/lib/Sema/SemaInit.cpp#L6221-L6226

and in the call to `TryValueInitialization` we do call `Sequence.AddZeroInitializationStep(Entity.getType());`

This is being called from here:



https://github.com/llvm/llvm-project/blob/2f15082b15f12461246e9e1fe1ea0cb106c27a34/clang/lib/Sema/SemaExprCXX.cpp#L1597-L1599


Although for the base class when we get to `InitializationSequence::InitializeFrom(...)` the value of `Kind` is `IK_Default`

Which is being called from the next line:

https://github.com/llvm/llvm-project/blob/2f15082b15f12461246e9e1fe1ea0cb106c27a34/clang/lib/Sema/SemaExprCXX.cpp#L1600

When it hits here: 

https://github.com/llvm/llvm-project/blob/159614a52f0bcb96513b1d18ed475e69250b5240/clang/lib/Sema/SemaInit.cpp#L7078-L7084

`ConstructorInitRequiresZeroInit` is `true`.

So as far as I can tell at least the right things seem to be happening. I don't see where it is going wrong yet though.

CC @zygoloid

**Comment by zygoloid** [comment] 2023-10-23 21:51
The initialization is being built correctly: the `CXXTemporaryObjectExpr` is marked as `zeroing`, as it should be. So we will zero the `B` class before we start constructing it. But then, when constructing the `A` base class, per [[class.base.init]/9.3](https://eel.is/c++draft/class.base.init#9.3), we default-initialize the `x` member because the constructor doesn't supply a *mem-initializer* for it:

https://github.com/llvm/llvm-project/blob/853fb0a8ac053a31fef3405d1d4dd545ad9a6167/clang/lib/AST/ExprConstant.cpp#L6400

For this default-initialization, [no initialization is performed](https://eel.is/c++draft/dcl.init#general-7.3). Per the rules for [indeterminate values](https://eel.is/c++draft/basic.indet#1), that's not supposed to give the field an indeterminate value, because some initialization was previously performed. But that's not being properly handled here -- we're overwriting with the default-initialized value for the type (an indeterminate value) even if there's already some other value present.

I think we should only be overwriting the field with `getDefaultInitValue` there if its value was previously `isAbsent()`, and not if some other initialization has already been performed.

**Comment by zygoloid** [comment] 2023-10-23 21:58
It looks like it'd be correct to change `getDefaultInitValue` so that it leaves initialized `APValue`s alone (that is, if the value is `!isAbsent()`). If so, it'd be good to rename it to something like `handleDefaultInit` given that it's not just building a value.

**Closed** 2023-10-25 17:18 UTC
Labels: clang:frontend, rejects-valid, confirmed
