### ISSUE TITLE
Inefficient code generated in simple boolean expression

### ISSUE THREAD

**Issue by jamescooper-blis** [llvm/llvm-project#54313] opened 2022-03-09 21:26 UTC
In the code below, the function `check4` should return `true`.
It does not do this when using `&&`, but it does when using `&`.

```
static bool take4v1(bool a, bool b, bool c, bool d) {
    return (a && b) || (a && c) || (a && d);
}

static bool take4v2(bool a, bool b, bool c, bool d) {
    return a && (b || c || d); // Optimises better if & is used instead.
}

bool check4(bool a, bool b, bool c, bool d) {
    return take4v1(a, b, c, d) == take4v2(a, b, c, d);
}
```

LLVM IR generated in the problematic case (-std=c++17 -O3):
```
define dso_local noundef zeroext i1 @_Z6check4bbbb(i1 noundef zeroext %0, i1 noundef zeroext %1, i1 noundef zeroext %2, i1 noundef zeroext %3) local_unnamed_addr #0 !dbg !18 {
  call void @llvm.dbg.value(metadata i1 %0, metadata !22, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %1, metadata !23, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %2, metadata !24, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %3, metadata !25, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %0, metadata !27, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  call void @llvm.dbg.value(metadata i1 %1, metadata !30, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  call void @llvm.dbg.value(metadata i1 %2, metadata !31, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  call void @llvm.dbg.value(metadata i1 %3, metadata !32, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  %5 = or i1 %2, %3
  %6 = or i1 %5, %1, !dbg !35
  %7 = and i1 %6, %0, !dbg !35
  call void @llvm.dbg.value(metadata i1 %0, metadata !36, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !42
  call void @llvm.dbg.value(metadata i1 %1, metadata !39, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !42
  call void @llvm.dbg.value(metadata i1 %2, metadata !40, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !42
  call void @llvm.dbg.value(metadata i1 %3, metadata !41, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !42
  %8 = xor i1 %0, true, !dbg !44
  %9 = or i1 %8, %1, !dbg !44
  %10 = select i1 %9, i1 %0, i1 %5, !dbg !44
  %11 = xor i1 %10, %7, !dbg !45
  %12 = xor i1 %11, true, !dbg !45
  ret i1 %12, !dbg !46
}
 ```
 
 LLVM IR in the correct case (same flags):
 ```
define dso_local noundef zeroext i1 @_Z6check4bbbb(i1 noundef zeroext %0, i1 noundef zeroext %1, i1 noundef zeroext %2, i1 noundef zeroext %3) local_unnamed_addr #0 !dbg !18 {
  call void @llvm.dbg.value(metadata i1 %0, metadata !22, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %1, metadata !23, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %2, metadata !24, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %3, metadata !25, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !26
  call void @llvm.dbg.value(metadata i1 %0, metadata !27, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  call void @llvm.dbg.value(metadata i1 %1, metadata !30, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  call void @llvm.dbg.value(metadata i1 %2, metadata !31, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  call void @llvm.dbg.value(metadata i1 %3, metadata !32, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !33
  call void @llvm.dbg.value(metadata i1 %0, metadata !35, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !41
  call void @llvm.dbg.value(metadata i1 %1, metadata !38, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !41
  call void @llvm.dbg.value(metadata i1 %2, metadata !39, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !41
  call void @llvm.dbg.value(metadata i1 %3, metadata !40, metadata !DIExpression(DW_OP_LLVM_convert, 1, DW_ATE_unsigned, DW_OP_LLVM_convert, 8, DW_ATE_unsigned, DW_OP_stack_value)), !dbg !41
  ret i1 true, !dbg !43
}
 ```
 
 gcc gets it right.
 
 Assembly code for the problematic case:
 ```
 check4(bool, bool, bool, bool):                          # @check4(bool, bool, bool, bool)
        or      edx, ecx
        mov     eax, edx
        or      eax, esi
        and     eax, edi
        test    esi, esi
        cmovne  edx, edi
        and     edx, edi
        xor     eax, edx
        xor     al, 1
        ret
 ```
 All instructions apart from the final three seem superfluous.

**Comment by yurai007** [comment] 2022-03-31 14:09
Decreasing number of 'take' parameters also helps in better code generation:  https://godbolt.org/z/c756nhPP4
It's caused by different folding decisions made in SimplifyCFGPass, for take3 it's only about one folding: https://godbolt.org/z/474h494jj. Since take4 has more branches transformation is performed twice: https://godbolt.org/z/nqjfqbh71 and those resulting blocks are not merged anywhere in further pipeline.

**Comment by yurai007** [comment] 2022-04-01 09:27
Right, apparently first part of my investigation was based on IR from old trunk before submitting fix :(

**Comment by rotateright** [comment] 2022-04-01 14:11
> Right, apparently first part of my investigation was based on IR from old trunk before submitting fix :(

No problem. Please open a new report for the SimplifyCFG issue if we can improve it. We also have #54543 for the reassociate pass. Since the example here is optimized now, I'll close this report.

**Closed by rotateright** 2022-04-01 14:11 UTC
Labels: llvm:optimizations
