### ISSUE TITLE
Assertion in lexer for Unicode bidirectional text support

### ISSUE THREAD

**Issue by r0ller** [llvm/llvm-project#64161] opened 2023-07-27 15:21 UTC
When llvm and clang are built with debug build type, the front end crashes on trying to compile this one liner with clang:

int A\N{LEFT-TO-RIGHT OVERRIDE};

I attached the stack dump (crash.txt) but for whatever reasons the preprocessed sources don't get generated.

I debugged the issue as well and checked the source file LiteralSupport.cpp as the function expandUCNs() where the assertion fails resides there. There's a function called ProcessNamedUCNEscape() which seems to be handling such named escapes like the one that triggers the crash. That function calls after some checks nameToCodepointStrict() whereas before the failing assert nameToCodepointLooseMatching() is called but it returns nullopt. That gave me the idea to call nameToCodepointStrict() before nameToCodepointLooseMatching() is called and only call the latter if the former doesn't return anything. The order may be the other way around as well but judging by their names calling the stricter seemed logical. Actually, that seems to solve the problem at least the codepoint returned (202D) matches what is listed in the [UCN list](https://www.unicode.org/Public/15.0.0/ucd/NamesList.txt).

Does this solution seem to make sense? Shall I go on and submit a patch?
[crash.txt](https://github.com/llvm/llvm-project/files/12185078/crash.txt)

**Comment by shafik** [comment] 2023-07-27 17:58
Confirmed: https://godbolt.org/z/be46nz3qo

code: 

```cpp
int A\N{LEFT-TO-RIGHT OVERRIDE};
```

Assertion:

```console
clang++: /root/llvm-project/clang/lib/Lex/LiteralSupport.cpp:391:
void clang::expandUCNs(llvm::SmallVectorImpl<char>&, llvm::StringRef):
Assertion `Res' failed.
```

Backtrace:

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:1:5: current parser token 'A\N{LEFT-TO-RIGHT OVERRIDE}'
 #0 0x000000000368a738 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x368a738)
 #1 0x00000000036885bc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x36885bc)
 #2 0x00000000035d6068 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007fa1e4687420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007fa1e414a00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007fa1e4129859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007fa1e4129729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007fa1e413afd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x000000000782f85b clang::expandUCNs(llvm::SmallVectorImpl<char>&, llvm::StringRef) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x782f85b)
 #9 0x00000000078aae51 clang::Preprocessor::LookUpIdentifierInfo(clang::Token&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x78aae51)
#10 0x00000000078279cc clang::Lexer::LexIdentifierContinue(clang::Token&, char const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x78279cc)
#11 0x000000000782a19b clang::Lexer::LexTokenInternal(clang::Token&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x782a19b)
#12 0x000000000782c45f clang::Lexer::Lex(clang::Token&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x782c45f)
#13 0x00000000078b0e6f clang::Preprocessor::Lex(clang::Token&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x78b0e6f)
#14 0x0000000005d87912 clang::Parser::ConsumeToken() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5d87912)
#15 0x0000000005dbf5c9 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5dbf5c9)
#16 0x0000000005d89df4 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5d89df4)
#17 0x0000000005d8a6ff clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#18 0x0000000005d90d71 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5d90d71)
#19 0x0000000005d91672 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5d91672)
#20 0x0000000005d91ac0 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5d91ac0)
#21 0x0000000005d85952 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5d85952)
#22 0x00000000048d6f48 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48d6f48)
#23 0x000000000413fe59 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x413fe59)
#24 0x00000000040c598e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40c598e)
#25 0x000000000421ffe6 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x421ffe6)
#26 0x0000000000bc7532 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbc7532)
#27 0x0000000000bbfd1a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#28 0x0000000003f268b9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#29 0x00000000035d6514 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x35d6514)
#30 0x0000000003f26eaf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#31 0x0000000003eeeba5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3eeeba5)
#32 0x0000000003eef60d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3eef60d)
#33 0x0000000003ef713d clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ef713d)
#34 0x0000000000bc57e7 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbc57e7)
#35 0x0000000000abfea1 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xabfea1)
#36 0x00007fa1e412b083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#37 0x0000000000bbf7fe _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbbf7fe)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

**Comment by shafik** [comment] 2023-07-27 17:58
CC @cor3ntin

**Comment by cor3ntin** [comment] 2023-07-28 09:35
@shafik  https://reviews.llvm.org/D156518

@r0ller The call to `nameToCodepointLooseMatching` was correct before we want to be able to recover from an incorrect name when expanding UCNs , but the implementation of `nameToCodepointLooseMatching` failed to properly match `-` in Unicode names (the strict matching succeeded because it is a simpler comparison that did not suffer this bug)

**Comment by r0ller** [comment] 2023-07-28 12:04
@shafik I'm not sure if I got you right. Does it mean that calling nameToCodepointStrict() there is entirely wrong or that it should be called only if nameToCodepointLooseMatching() fails?

**Comment by cor3ntin** [comment] 2023-07-28 12:09
> @cor3ntin I'm not sure if I got you right. Does it mean that calling nameToCodepointStrict() there is entirely wrong or that it should be called only if nameToCodepointLooseMatching() fails?

Calling `nameToCodepointStrict` would be wrong. the fix https://reviews.llvm.org/D156518 - modifies the implementation of `nameToCodepointLooseMatching`

**Comment by cor3ntin** [comment] 2023-07-28 12:16
It will get closed automatically when the fix is merged :) - Probably later today.
Thanks for reporting this issue by the way!

**Closed** 2023-07-28 13:09 UTC
Labels: clang:frontend, confirmed, crash
