### ISSUE TITLE
Why clang-format doesn't work?

### ISSUE THREAD

**Issue by lalala-233** [llvm/llvm-project#60686] opened 2023-02-12 09:18 UTC
Linux-6.1.11.arch1-1

```console
$ clang --version                        
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ clang-format --version  
clang-format version 15.0.7
```

When I use the opinion `AfterOverloadedOperator: true`, Clang-Format doesn't work completely.

Before I use it:

```cpp
class printer
{
  public:
    template <class T>
    printer& operator<(T o);

    template <class T>
    printer& operator<<(T o);
}
```

But after I use it:

```cpp
class printer
{
  public:
    template <class T>
    printer& operator<(T o);

    template <class T>
    printer& operator<< (T o);
}
```

Why does it do that?

**Comment by rymiel** [comment] 2023-02-12 09:34
Duplicate of https://github.com/llvm/llvm-project/issues/58821. Fixed in clang-format 16 (upcoming release)

**Closed by rymiel** 2023-02-12 09:34 UTC
Labels: duplicate, clang-format
