### ISSUE TITLE
opt crashes with Assertion `!isa<SCEVCouldNotCompute>(BackedgeTakenCount) && "Invalid loop count"' failed.

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#51669] opened 2021-10-27 08:01 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [52327](https://llvm.org/bz52327) |
| Version | trunk |
| OS | Linux |
| Attachments | [bbi-62009.ll reproducer](https://user-images.githubusercontent.com/55733087/143762666-c8fe7f17-94e8-49c2-a90e-44f7356d5bc2.gz) |
| CC | @preames |

## Extended Description 

llvm commit: e42f5d4b488e
Reproduce with:
 `opt -passes="loop(indvars,require<access-info>),loop-vectorize" -o /dev/null bbi-62009.ll`

Result:
```
opt: ../lib/Transforms/Vectorize/LoopVectorize.cpp:3125: llvm::Value *llvm::InnerLoopVectorizer::getOrCreateTripCount(llvm::Loop *): Assertion `!isa<SCEVCouldNotCompute>(BackedgeTakenCount) && "Invalid loop count"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ../../master-github/llvm/build-all/bin/opt -passes=loop(indvars,require<access-info>),loop-vectorize -o /dev/null bbi-62009.ll
 #&#8203;0 0x0000000002b7d9f3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (../../master-github/llvm/build-all/bin/opt+0x2b7d9f3)
 #&#8203;1 0x0000000002b7b66e llvm::sys::RunSignalHandlers() (../../master-github/llvm/build-all/bin/opt+0x2b7b66e)
 #&#8203;2 0x0000000002b7dd76 SignalHandler(int) Signals.cpp:0:0
 #&#8203;3 0x00007fc514b80630 __restore_rt sigaction.c:0:0
 #&#8203;4 0x00007fc5122b3387 raise (/lib64/libc.so.6+0x36387)
 #&#8203;5 0x00007fc5122b4a78 abort (/lib64/libc.so.6+0x37a78)
 #&#8203;6 0x00007fc5122ac1a6 __assert_fail_base (/lib64/libc.so.6+0x2f1a6)
 #&#8203;7 0x00007fc5122ac252 (/lib64/libc.so.6+0x2f252)
 #&#8203;8 0x0000000002d16d9e llvm::InnerLoopVectorizer::getOrCreateTripCount(llvm::Loop*) (../../master-github/llvm/build-all/bin/opt+0x2d16d9e)
 #&#8203;9 0x0000000002d19f16 llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton() (../../master-github/llvm/build-all/bin/opt+0x2d19f16)
#&#8203;10 0x0000000002d3efdd llvm::LoopVectorizationPlanner::executePlan(llvm::InnerLoopVectorizer&, llvm::DominatorTree*) (../../master-github/llvm/build-all/bin/opt+0x2d3efdd)
#&#8203;11 0x0000000002d510ae llvm::LoopVectorizePass::processLoop(llvm::Loop*) (../../master-github/llvm/build-all/bin/opt+0x2d510ae)
#&#8203;12 0x0000000002d52f92 llvm::LoopVectorizePass::runImpl(llvm::Function&, llvm::ScalarEvolution&, llvm::LoopInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BlockFrequencyInfo&, llvm::TargetLibraryInfo*, llvm::DemandedBits&, llvm::AAResults&, llvm::AssumptionCache&, std::function<llvm::LoopAccessInfo const& (llvm::Loop&)>&, llvm::OptimizationRemarkEmitter&, llvm::ProfileSummaryInfo*) (../../master-github/llvm/build-all/bin/opt+0x2d52f92)
#&#8203;13 0x0000000002d53a79 llvm::LoopVectorizePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (../../master-github/llvm/build-all/bin/opt+0x2d53a79)
#&#8203;14 0x0000000002e6f81d llvm::detail::PassModel<llvm::Function, llvm::LoopVectorizePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
#&#8203;15 0x000000000231ebd5 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (../../master-github/llvm/build-all/bin/opt+0x231ebd5)
#&#8203;16 0x0000000000adb57d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) crtstuff.c:0:0
#&#8203;17 0x0000000002322f6a llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../master-github/llvm/build-all/bin/opt+0x2322f6a)
#&#8203;18 0x000000000079107d llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) crtstuff.c:0:0
#&#8203;19 0x000000000231dd18 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (../../master-github/llvm/build-all/bin/opt+0x231dd18)
#&#8203;20 0x0000000000788ea2 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (../../master-github/llvm/build-all/bin/opt+0x788ea2)
#&#8203;21 0x000000000079bb8d main (../../master-github/llvm/build-all/bin/opt+0x79bb8d)
#&#8203;22 0x00007fc51229f555 __libc_start_main (/lib64/libc.so.6+0x22555)
#&#8203;23 0x00000000007842fc _start (../../master-github/llvm/build-all/bin/opt+0x7842fc)
Abort
```

This starts happening with commit 16370e02a71
    [IndVars] Provide eliminateIVComparison with context
    
    We can prove more predicates when we have a context when eliminating ICmp.
    As first (and very obvious) approximation we can use the ICmp instruction itself,
    though in the future we are going to use a common dominator of all its users.
    Need some refactoring before that.
    
    Observed ~0.5% negative compile time impact.
    
    Differential Revision: https://reviews.llvm.org/D98697
    Reviewed By: lebedev.ri

**Comment by fhahn** [comment] 2022-03-20 11:04
@mikaelholmen unfortunately I am unable to reproduce the issue, as the `opt` invocation seems invalid:


```
> opt -passes="loop(indvars,require),loop-vectorize" 
/opt/compiler-explorer/clang-assertions-trunk/bin/opt: unknown loop pass 'require'
Compiler returned: 1
```

When removing `, require` , there's no crash: https://llvm.godbolt.org/z/bov9xo9jr and it looks like LV now doesn't try to vectorize the loop, due to being unable to compute the exit count.

I am closing the issue for now, but please re-open with additional info if it still reproduces on your end.

**Comment by mikaelholmen** [comment] 2022-03-21 07:09
@fhahn Ops. sorry, seems like I messed up the command line.
The correct one is
 opt -passes="loop(indvars,require<access-info>),loop-vectorize" -o /dev/null bbi-62009.ll

I've verified that it still crashes on current trunk, 1eada2adda8f.

**Comment by mikaelholmen** [comment] 2022-03-21 07:11
Um, ok, something funny going on. There should be < access-info > following "require", and if I try to "edit" the comment above the access-info stuff is there, but ti's not shown when jut looking at the comment.

**Comment by nikic** [comment] 2022-03-21 08:44
@mikaelholmen The angle brackets are interpreted as HTML. You need to put it between backticks to interpret as code (I've edited your comments).

**Comment by mikaelholmen** [comment] 2022-03-21 08:46
> @mikaelholmen The angle brackets are interpreted as HTML. You need to put it between backticks to interpret as code (I've edited your comments).

@nikic I see! Thank you!

**Comment by fhahn** [comment] 2022-05-16 10:07
The issue here is quite interesting. 

That's a slightly renamed version of the reproducer:

```
define void @f() {
entry:
  br label %loop.1.header

loop.1.header:                                         ; preds = %for.cond1, %entry
  %cmp = icmp eq i16 0, 1
  br i1 %cmp, label %for.body, label %exit

for.body:                                         ; preds = %for.cond
  br label %loop.2.header

loop.2.header:
  %d.0 = phi i16 [ 0, %for.body ], [ %inc, %loop.2.latch ]
  %tobool = icmp ne i16 %d.0, 0
  br i1 %tobool, label %loop.2.latch, label %loop.1.header

loop.2.latch:
  %idxprom = sext i16 %d.0 to i32
  %arrayidx = getelementptr inbounds i16, i16* undef, i32 %idxprom
  %inc = add nsw i16 %d.0, 1
  br label %loop.2.header

exit:
  ret void
}
```

Here's what's going on:

1. The original backedge taken count computed for `%loop.2.header` is 0, because when computing the count we determine that `%tobool == false` using inductive reasoning
1. IndVarSimplify simplifies `%tobool -> true` using the fact the `%cmp` is `false` (and false implies anything). This effectively turns the backedge taken count for `0` to `infinite`. But `simplifyAndExtend` does not invalidate SCEV for the loop. And technically that should be fine, as the loop is unreachable.
2. Now `LoopAccessAnalysis` runs on `%loop.2.header` and uses the BTC of 0. `LAA` is cached for the loop
3. IndVarSimplify runs on `loop.1.header` simplifies `%cmp` to `false` and invalidates SCEV for the loop nest, including `loop.1.header`. 
4. `LAA` is not invalidated and assumes the BTC of `loop.1.header` is 0.
5. When `LoopVectorize` tries to get the trip count of `loop.1.header` it gets re-computed and is `CouldNotCompute` -> crash. (LV relies on LAA to fail if the BTC is uncomputable).

So the issue here is that `LAA` is cached per-loop and depends on `SCEV`. And when information in `SCEV` changes, `LAA` doesn't get invalidated, because we use `SE->forgetTopMostLoop`, which invalidates SCEV for sub loop but `LAA` for sub-loops is not invalidated.

Not sure if there are other analyses that may be impacted by this. Given that `simplifyAndExtend` may cause the BTC go from computable -> uncomputable it might be worth invalidating SCEV  for the loop if it made changes.

**Comment by fhahn** [comment] 2022-09-26 11:16
Similar issue as #50940. Proposed fix: https://reviews.llvm.org/D134606

**Closed** 2022-10-01 14:44 UTC
Labels: bugzilla, loopoptim, vectorization, llvm:crash, SCEV
