### ISSUE TITLE
clang fails to compile `std::ranges::remove_if`

### ISSUE THREAD

**Issue by cppdev123** [llvm/llvm-project#57703] opened 2022-09-12 18:02 UTC
the following simple code fails to compile with clang (15, 14, 13, 12, ..) but compiles with gcc and msvc:

```cpp
#include <vector>
#include <algorithm>

void test_remove_if() noexcept
{
    std::vector<int> vec;
    std::ranges::remove_if(vec, [](int v) { return !v; });	
}
```

code on godbolt: https://godbolt.org/z/xd5Yd5rE8

**Comment by rymiel** [comment] 2022-09-12 18:07
This is probably a duplicate of https://github.com/llvm/llvm-project/issues/44178 libstdc++ ranges do not work with clang

**Comment by royjacobson** [comment] 2022-09-23 12:36
Works after https://reviews.llvm.org/D126907 landed, so confirmed as duplicate.

**Closed by royjacobson** 2022-09-23 12:36 UTC
Labels: clang:frontend
