### ISSUE TITLE
printf argument checking gets confused with 34 arguments

### ISSUE THREAD

**Issue by eliotmiranda** [llvm/llvm-project#99249] opened 2024-07-16 22:35 UTC
In a 34 argument printf of the register state of an ARMv8 processor the compiler mistakenly claims the 32'nd argument isn't used:
```
printf_warning_bug.c:45:43: warning: data argument not used by format string [-Wformat-extra-args]
                        vr(__x[28]), vr(__fp),    vr(__lr),    vr(__sp),
                                                               ^
printf_warning_bug.c:27:18: note: expanded from macro 'vr'
#   define vr(r) v(regs->r)
                 ^
printf_warning_bug.c:10:14: note: expanded from macro 'v'
#define v(v) ((void *)(v))
```

cc -v
```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

uname -a
Darwin Machado.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Apr 24 06:05:14 PDT 2024; root:xnu-8020.240.18.708.4~1/RELEASE_ARM64_T6000 arm64
```
============ printf_warning_bug.c ===============
```
#include <stdio.h>
#include <sys/ucontext.h>

/* Attempt to dump the registers to stdout.  Only do so if we know how. 
 * Answer the pc (or 0).
 */
static void *
printRegisterState(FILE *file,ucontext_t *uap)
{
#define v(v) ((void *)(v))
#if __x86_64__
	_STRUCT_X86_THREAD_STATE64 *regs = &uap->uc_mcontext->__ss;
	fprintf(file,
			"    rax %14p rbx %14p rcx %14p rdx %14p\n"
			"    rdi %14p rsi %14p rbp %14p rsp %14p\n"
			"    r8  %14p r9  %14p r10 %14p r11 %14p\n"
			"    r12 %14p r13 %14p r14 %14p r15 %14p\n"
			"    rip %14p\n",
			v(regs->__rax), v(regs->__rbx), v(regs->__rcx), v(regs->__rdx),
			v(regs->__rdi), v(regs->__rsi), v(regs->__rbp), v(regs->__rsp),
			v(regs->__r8 ), v(regs->__r9 ), v(regs->__r10), v(regs->__r11),
			v(regs->__r12), v(regs->__r13), v(regs->__r14), v(regs->__r15),
			v(regs->__rip));
	return v(regs->__rip);
# elif defined(__arm64__) || defined(__aarch64__)
	_STRUCT_ARM_THREAD_STATE64 *regs = &uap->uc_mcontext->__ss;
#   define vr(r) v(regs->r)
	fprintf(file,
			"     x0 %14p  x1 %14p  x2 %14p  x3 %14p\n"
			"     x4 %14p  x5 %14p  x6 %14p  x7 %14p\n"
			"     x8 %14p  x9 %14p x10 %14p x11 %14p\n"
			"    x12 %14p x13 %14p x14 %14p x15 %14p\n"
			"    x16 %14p x17 %14p x18 %14p x19 %14p\n"
			"    x20 %14p x21 %14p x22 %14p x23 %14p\n"
			"    x24 %14p x25 %14p x26 %14p x27 %14p\n"
			"    x28 %14p  fp %14p  lr %14p  sp %14p\n",
			"     pc %14p cpsr 0x%08x\n",
			vr( __x[0]), vr( __x[1]), vr( __x[2]), vr( __x[3]),
			vr( __x[4]), vr( __x[5]), vr( __x[6]), vr( __x[7]),
			vr( __x[8]), vr( __x[9]), vr(__x[10]), vr(__x[11]),
			vr(__x[12]), vr(__x[13]), vr(__x[14]), vr(__x[15]),
			vr(__x[16]), vr(__x[17]), vr(__x[18]), vr(__x[19]),
			vr(__x[20]), vr(__x[21]), vr(__x[22]), vr(__x[23]),
			vr(__x[24]), vr(__x[25]), vr(__x[26]), vr(__x[27]),
			vr(__x[28]), vr(__fp),    vr(__lr),    vr(__sp),
			vr(__pc), regs->__cpsr);
	return vr(__pc);
#else
	fprintf(file,"don't know how to derive register state from a ucontext_t on this platform\n");
	return v(0);
#endif
}
```

**Comment by EugeneZelenko** [comment] 2024-07-16 22:41
Could you please try LLVM (not Apple) 18 or  `main` branch? https://godbolt.org should be helpful.

**Comment by eliotmiranda** [comment] 2024-07-16 23:15
It's an FYI submission. I ignore the warning in routine use.  I don't want to substitute for Apple's standard compiler.  If the issue is fixed already then great.

**Comment by eliotmiranda** [comment] 2024-07-16 23:15
It's an FYI submission. I ignore the warning in routine use.  I don't want too substitute for Apple's standard compiler.  If the issue is fixed already then great.

**Comment by chrchr-github** [comment] 2024-07-17 12:55
Looks like it is fixed in `main`: https://godbolt.org/z/xfs9EKoWd

**Comment by chrchr-github** [comment] 2024-07-17 14:06
Its a true positive caused by the likely spurious comma in this line: `"    x28 %14p  fp %14p  lr %14p  sp %14p\n",`

**Comment by eliotmiranda** [comment] 2024-07-18 04:03
Thank you. Apologies for the noise.

**Closed** 2024-07-19 05:26 UTC
Labels: clang:diagnostics, false-positive
