### ISSUE TITLE
[clang-format] Segmentation fault libLLVM-13 due to AlignArrayOfStructures

### ISSUE THREAD

**Issue by n-r-w** [llvm/llvm-project#53748] opened 2022-02-11 10:09 UTC
cpp file and clang-format attached.
[source.zip](https://github.com/llvm/llvm-project/files/8047668/source.zip)

```
> Stack dump:
> 0.	Program arguments: clang-format ./srvtbldescr.cpp
>  #0 0x00007fc9360fcc93 (/usr/bin/../lib/libLLVM-13.so+0xba2c93)
>  #1 0x00007fc9360fa4a6 (/usr/bin/../lib/libLLVM-13.so+0xba04a6)
>  #2 0x00007fc9351b4da0 __restore_rt sigaction.c:0:0
>  #3 0x00007fc93ed7bf16 clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions&&) (/usr/bin/../lib/libclang-cpp.so.13+0x2ff3f16)
>  #4 0x00007fc93ed7cf23 clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) (/usr/bin/../lib/libclang-cpp.so.13+0x2ff4f23)
>  #5 0x00007fc93ed81d5d clang::format::WhitespaceManager::generateReplacements() (/usr/bin/../lib/libclang-cpp.so.13+0x2ff9d5d)
>  #6 0x00007fc93ed0be4f (/usr/bin/../lib/libclang-cpp.so.13+0x2f83e4f)
>  #7 0x00007fc93ed403e9 clang::format::TokenAnalyzer::process() (/usr/bin/../lib/libclang-cpp.so.13+0x2fb83e9)
>  #8 0x00007fc93ed0b3a6 (/usr/bin/../lib/libclang-cpp.so.13+0x2f833a6)
>  #9 0x00007fc93ed0b578 (/usr/bin/../lib/libclang-cpp.so.13+0x2f83578)
> #10 0x00007fc93ed0e94a clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/usr/bin/../lib/libclang-cpp.so.13+0x2f8694a)
> #11 0x00007fc93ed0f62d clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/usr/bin/../lib/libclang-cpp.so.13+0x2f8762d)
> #12 0x00005594d67f2362 (/usr/bin/clang-format+0xf362)
> #13 0x00005594d67ebf40 (/usr/bin/clang-format+0x8f40)
> #14 0x00007fc93519fb25 __libc_start_main (/usr/bin/../lib/libc.so.6+0x27b25)
> #15 0x00005594d67ec1de (/usr/bin/clang-format+0x91de)
> Segmentation fault (core dumped)
```

**Comment by mkurdej** [comment] 2022-02-11 10:52
That's due to (at least) `static SrvTblFldDesc flddescr_SotrENSI_ver1[]=` structure initialization.

Minimal repro:
```
AlignArrayOfStructures: Left
```

```
static SrvTblFldDesc flddescr_SotrENSI_ver1[]=
{
{SRVFLD_SotrENSI_birthDate,         FldType_DBDate, MarkType_Date,             0, NOSORTFLD, "birthDate", "������������"},
{SRVFLD_SotrENSI_phonelist,         FldType_String, MarkType_None,           512, NOSORTFLD, "phonelist", "������ ���������"},
{SRVFLD_SotrENSI_cfokey1,           FldType_Code,   MarkType_None,             0, NOSORTFLD, "cfokey1", "cfokey1", SRVTBL_CFOStruct, SRVFLD_CFOStruct_CFOcode},
};
```

Possible duplicate of #51767 and #51277.

**Comment by n-r-w** [comment] 2022-02-11 12:49
same issue for current git version 15.0.0

> Stack dump:
> 0.	Program arguments: /home/we/dev/tools/llvm/bin/bin/clang-format /home/we/dev/metastaff/trunk/KPServer1/dbinfo_kp/srvtbldescr.cpp
>  #0 0x00007fe8c5e97941 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
>  #1 0x00007fe8c5e9504e SignalHandler(int) Signals.cpp:0:0
>  #2 0x00007fe8cfe51870 __restore_rt sigaction.c:0:0
>  #3 0x00007fe8cf471fc6 clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions&&) (/home/we/dev/tools/llvm/bin/bin/../lib/libclang-cpp.so.15+0x2eb3fc6)
>  #4 0x00007fe8cf473033 clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) (/home/we/dev/tools/llvm/bin/bin/../lib/libclang-cpp.so.15+0x2eb5033)
>  #5 0x00007fe8cf477ebd clang::format::WhitespaceManager::generateReplacements() (/home/we/dev/tools/llvm/bin/bin/../lib/libclang-cpp.so.15+0x2eb9ebd)
>  #6 0x00007fe8cf3f2344 clang::format::(anonymous namespace)::Formatter::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) Format.cpp:0:0
>  #7 0x00007fe8cf431804 clang::format::TokenAnalyzer::process() (/home/we/dev/tools/llvm/bin/bin/../lib/libclang-cpp.so.15+0x2e73804)
>  #8 0x00007fe8cf3ecff8 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda5'(clang::format::Environment const&)::operator()(clang::format::Environment const&) const (.isra.0) Format.cpp:0:0
>  #9 0x00007fe8cf3ed058 std::_Function_handler<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&), clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda5'(clang::format::Environment const&)>::_M_invoke(std::_Any_data const&, clang::format::Environment const&) Format.cpp:0:0
> #10 0x00007fe8cf3f5e07 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/home/we/dev/tools/llvm/bin/bin/../lib/libclang-cpp.so.15+0x2e37e07)
> #11 0x00007fe8cf3f6edd clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/home/we/dev/tools/llvm/bin/bin/../lib/libclang-cpp.so.15+0x2e38edd)
> #12 0x000055c9692dba32 clang::format::format(llvm::StringRef) ClangFormat.cpp:0:0
> #13 0x000055c9692d3979 main (/home/we/dev/tools/llvm/bin/bin/clang-format+0x9979)
> #14 0x00007fe8c4bfbb25 __libc_start_main (/usr/lib/libc.so.6+0x27b25)
> #15 0x000055c9692d3e5e _start (/home/we/dev/tools/llvm/bin/bin/clang-format+0x9e5e)
> Segmentation fault (core dumped)

**Comment by mydeveloperday** [comment] 2022-02-19 11:21
I believe this algorithim is expecting square  structures  

i.e.

```
static foo[] = {
    {  "A", "B", "C" },
    {  "D", "E", "F" },
    {  "G", "H", "I" },
}
```

this example is 

```
static bar foo[] = {
    {  "A", "B", "C" },
    {  "D", "E", "F" },
    {  "G", "H", "I", "J", "K","L" },
};
```

Causes a crash

Assertion failed: idx < size(), file C:\cygwin64\buildareas\clang\llvm-project\llvm\include\llvm/ADT/SmallVector.h, line 277
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\cygwin64\\buildareas\\clang\\build_ninja\\bin\\clang-format.exe test10.cpp
0x00007FF64581D09C (0x0000007B00000016 0x0000000000000000 0x00007FF6456CADE9 0x0000000000000000), HandleAbort() + 0xC bytes(s), C:\cygwin64\buildareas\clang\llvm-project\llvm\lib\Support\Windows\Signals.inc, line 418
0x00007FFDBA04BC31 (0x00007FFD00000016 0x0000007B2DF887F0 0x0000000801000006 0xFFFFFF01000000FA), raise() + 0x441 bytes(s)
0x00007FFDBA04D889 (0x0000007B2DF887F0 0x0000000000000240 0x00007FFDBA14DA70 0x00007FF645DB8490), abort() + 0x39 bytes(s)
0x00007FFDBA0534B5 (0x00007FF645DB8490 0x00007FF645DB83D0 0x0000000000000115 0x0000007B2DF8A000), _get_wide_winmain_command_line() + 0x2515 bytes(s)
0x00007FFDBA053027 (0x00007FF645DB8490 0x00007FF645DB83D0 0x0000026F00000115 0x00007FF600000001), _get_wide_winmain_command_line() + 0x2087 bytes(s)
0x00007FFDBA051091 (0x00007FF645DB8490 0x00007FF645DB83D0 0x0000007B00000115 0x00007FF645868DAA), _get_wide_winmain_command_line() + 0xF1 bytes(s)
0x00007FFDBA053A1F (0x00007FF645DB8490 0x00007FF645DB83D0 0x0000002B00000115 0x0000026F00000000), _wassert() + 0x2F bytes(s)
0x00007FF645868DAA (0x0000007B2DF89168 0x00000000FDFDFDFD 0x0000007B0000002B 0x00007FF6459D6401), llvm::SmallVectorTemplateCommon<clang::format::WhitespaceManager::Change,void>::operator[]() + 0x3A bytes(s), C:\cygwin64\buildareas\clang\llvm-project\llvm\include\llvm\ADT\SmallVector.h, line 277 + 0x2B byte(s)
0x00007FF645844C40 (0x0000007B2DF89168 0x0000007B2DF88E28 0x0000007B2DF88E48 0x00007FF600000005), clang::format::WhitespaceManager::getNetWidth<clang::format::WhitespaceManager::CellDescription *>() + 0x60 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\WhitespaceManager.h, line 270 + 0x13 byte(s)
0x00007FF6459E7F5D (0x0000007B2DF89168 0x0000007B2DF88F28 0x0000007B2DF88EB8 0x0000007B00000005), clang::format::WhitespaceManager::getMaximumNetWidth<clang::format::WhitespaceManager::CellDescription *>() + 0x10D bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\WhitespaceManager.h, line 307 + 0x1F byte(s)
0x00007FF6459D56A2 (0x0000007B2DF89168 0x0000007B2DF88FD8 0x0000007B0000000D 0x00007FF60000002D), clang::format::WhitespaceManager::alignArrayInitializersLeftJustified() + 0x132 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\WhitespaceManager.cpp, line 1114 + 0x47 byte(s)
0x00007FF6459D4ED2 (0x0000007B2DF89168 0x000000000000000D 0x0000002E0000002D 0x0000002F0000002F), clang::format::WhitespaceManager::alignArrayInitializers() + 0xC2 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\WhitespaceManager.cpp, line 1030 + 0x32 byte(s)
0x00007FF6459D4DD0 (0x0000007B2DF89168 0x0000026F3E731730 0x0000007B2DF8A000 0xCCCCCCCCCCCCCCCC), clang::format::WhitespaceManager::alignArrayInitializers() + 0xE0 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\WhitespaceManager.cpp, line 1014
0x00007FF6459D2E4B (0x0000007B2DF89168 0x0000007B2DF8B208 0x0000007B2DF89100 0x0000007B00000000), clang::format::WhitespaceManager::generateReplacements() + 0xAB bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\WhitespaceManager.cpp, line 112
0x00007FF64594EEF5 (0x0000007B2DF8B5B0 0x0000007B2DF8B308 0x0000007B2DF8B2B8 0x0000007B2DF8B208), clang::format::`anonymous namespace'::Formatter::analyze() + 0x3C5 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\Format.cpp, line 1945 + 0xD byte(s)
0x00007FF645A00937 (0x0000007B2DF8B5B0 0x0000007B2DF8D668 0x0000007B2DF8C350 0x0000007B2DF8E3B8), clang::format::TokenAnalyzer::process() + 0x4F7 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\TokenAnalyzer.cpp, line 130
0x00007FF645957165 (0x0000007B2DF8D500 0x0000007B2DF8D668 0x0000026F3E73AD10 0xCCCCCCCCCCCCCCCC), <lambda_be157eee42e494a9ed92b4bd992e61c3>::operator()() + 0x65 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\Format.cpp, line 3161 + 0x3C byte(s)
0x00007FF645786F98 (0x0000007B2DF8D668 0x0000007B2DF8D500 0x0000026F3E73AD10 0x00007FF645996D84), std::invoke<<lambda_be157eee42e494a9ed92b4bd992e61c3> &,clang::format::Environment const &>() + 0x28 bytes(s), C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits, line 1595 + 0x14 byte(s)
0x00007FF64574D8E8 (0x0000007B2DF8D668 0x0000007B2DF8D500 0x0000026F3E73AD10 0x0000000000000000), std::_Invoker_ret<std::pair<clang::tooling::Replacements,unsigned int>,0>::_Call<<lambda_be157eee42e494a9ed92b4bd992e61c3> &,clang::format::Environment const &>() + 0x28 bytes(s), C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\functional, line 753 + 0x14 byte(s)
0x00007FF645958957 (0x0000007B2DF8D4F8 0x0000007B2DF8D668 0x0000026F3E73AD10 0xCCCCCCCC00000000), std::_Func_impl_no_alloc<<lambda_be157eee42e494a9ed92b4bd992e61c3>,std::pair<clang::tooling::Replacements,unsigned int>,clang::format::Environment const &>::_Do_call() + 0x37 bytes(s), C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\functional, line 920 + 0x23 byte(s)
0x00007FF6459946A5 (0x0000007B2DF8D4F8 0x0000007B2DF8D668 0x0000026F3E73AD10 0x0000007B2DF8DA00), std::_Func_class<std::pair<clang::tooling::Replacements,unsigned int>,clang::format::Environment const &>::operator()() + 0x65 bytes(s), C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\functional, line 968 + 0x2C byte(s)
0x00007FF64594D0EF (0x0000007B2DF8DAD0 0x0000007B2DF8DCF8 0x0000007B2DF8DAF0 0x0000007B2DF8DB00), clang::format::internal::reformat() + 0xACF bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\Format.cpp, line 3179
0x00007FF645949E79 (0x0000007B2DF8E3D8 0x0000007B2DF8DCF8 0x0000007B2DF8F830 0x0000007B2DF8F840), clang::format::reformat() + 0xB9 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\lib\Format\Format.cpp, line 3204 + 0x9C byte(s)
0x00007FF64570B206 (0x0000007B2DF8FD40 0x0000026F3E71CAB0 0x0000007B2DF8FD20 0x0000000000000000), clang::format::format() + 0x11C6 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\tools\clang-format\ClangFormat.cpp, line 481
0x00007FF64570C558 (0x0000000000000002 0x0000026F3E728AD0 0x0000000000000000 0x00007FF645BF6A9D), main() + 0x5F8 bytes(s), C:\cygwin64\buildareas\clang\llvm-project\clang\tools\clang-format\ClangFormat.cpp, line 614 + 0x56 byte(s)
0x00007FF645BF7599 (0x00007FF645DAE000 0x00007FF645DAE6D0 0x0000000000000000 0x0000000000000000), invoke_main() + 0x39 bytes(s), d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 79
0x00007FF645BF747E (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), __scrt_common_main_seh() + 0x12E bytes(s), d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 288 + 0x5 byte(s)
0x00007FF645BF733E (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), __scrt_common_main() + 0xE bytes(s), d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl, line 331
0x00007FF645BF762E (0x0000007B2D44E000 0x0000000000000000 0x0000000000000000 0x0000000000000000), mainCRTStartup() + 0xE bytes(s), d:\a01\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp, line 17
0x00007FFE054854E0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x10 bytes(s)
0x00007FFE069A485B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x2B bytes(s)


I think we get a crash because we walk over the end of the array

![image](https://user-images.githubusercontent.com/16046346/154798669-a5b943c3-904f-4d58-8531-a680376121b7.png)

The CellCount is 7, but this is only true for the last row, (which is why square structures work),

Actually I think the calculation of Start is likely wrong for all but the first row, (unless that has the maximum number of rows.

Ultimately I think we end up looking too far  and that is why we see

Assertion failed: idx < size(), file C:\cygwin64\buildareas\clang\llvm-project\llvm\include\llvm/ADT/SmallVector.h, line 277

I don't know this code that well, but I think it is assuming square strucutres and I'm not quite sure what we can do to overcome that...

**Comment by mydeveloperday** [comment] 2022-02-19 11:49
Looking deeper at what this is trying to do..

Its scanning all the cells to determine how long they are, i.e.
"A""B""C" = 9 characters

```
static bar foo[] = {
    {  "A", "B", "C" },
    {  "D", "E", "F" },
    {  "G", "H", "I" },
};
```

If I add 

`"AB""B""C" == 10`

`"DEF","E","F" == 11`

```
static bar foo[] = {
    {  "AB", "B", "C" },
    {  "DEF", "E", "F" },
    {  "G", "H", "I" },
};
```

Ok so what is wrong here is that in trying to determine the width of the row, we are using the larger number of "Cells" as the CellsPerRow

But doing that I beleive by just incrementing over all the rows with that value, so its not hard to see why we would crash

We can't have a single CellCount we have to determine the number of Cells per row.

**Comment by mydeveloperday** [comment] 2022-02-20 09:32
Even more pain is inflicted if the structure looks like

```
static bar foo[] = {
    {  "A", "B" },
    {  "D", "E", "F" },
    {  "G", "H", "I" },
};
```

in this case we don't see the whole top row of columns so we cannot work out the widths correctly, I fear we have to rewrite the algorithm to account for non square structures.  I took a quick looks and its not easy

In my view there are a couple of phases we could take

1) remove the crash  - anyone who face the crash would get likely incorrect formatting some of the time.
2) fix the algorithm completely - longer and more complex (@mkurdej , @HazardyKnusperkeks and thoughts?)

Should I take a go?

**Comment by mkurdej** [comment] 2022-02-20 10:54
I thought about doing the same (rewriting/fixing the algorithm) but had other things before.
I think that fixing the algorithm completely and not just this particular crash will be more efficient and save us lots of headaches.
Anyway, if you feel like giving it a try, I'll be happy to help you!

**Comment by HazardyKnusperkeks** [comment] 2022-02-20 10:55
Sounds reasonable. I would check if the original author is available for that. @feg208 do you want to look into this?

**Comment by mydeveloperday** [comment] 2022-03-06 17:20
Workaround fix https://reviews.llvm.org/D121069

**Comment by rymiel** [comment] 2023-05-08 10:45
Duplicate of #51277

**Closed by rymiel** 2023-05-08 10:45 UTC
Labels: bug, clang-format, crash
