### ISSUE TITLE
[clang] Please implement the resolution of cwg2369

### ISSUE THREAD

**Issue by ericniebler** [llvm/llvm-project#58988] opened 2022-11-14 17:10 UTC
https://cplusplus.github.io/CWG/issues/2369.html

The resolution of cwg2369 has been applied as a DR to the working draft and has been implemented in gcc since gcc 11.1.

*Example:*

```c++
   template <typename T>
   struct static_assert_integral {
     static_assert(std::is_integral_v<T>);
     using type = T;
   };

   struct fun {
     template <typename T>
       requires std::is_integral_v<T>
     typename static_assert_integral<T>::type
     operator()(T) {}
   };

   static_assert(!std::is_invocable_v<fun, float>); // error: static assertion failed:
                                                    // std::is_integral_v<T>
```

*Result*:
```
error: static assertion failed: std::is_integral_v<T>
```

*Expected:*
No error

*See:*
https://godbolt.org/z/YTxKjvsnG

**Comment by h-vetinari** [comment] 2022-11-28 05:19
Duplicate of #54440

**Closed** 2022-11-28 05:29 UTC
Labels: clang:frontend, concepts
