### ISSUE TITLE
crash when attempting to build llvm (main branch)

### ISSUE THREAD

**Issue by mfvalin** [llvm/llvm-project#85543] opened 2024-03-16 17:05 UTC
Distribution ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

attached :  system output + suggested diagnostic files

compiler used
clang version 18.1.2 (https://github.com/llvm/llvm-project.git ea6c457b8dd2d0e6a7f05b4a5bdd2686085e1ec0)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm-18/bin

[bug_report.txt](https://github.com/llvm/llvm-project/files/14624624/bug_report.txt)
[MachOObjectFile-02c7ff.cpp.txt](https://github.com/llvm/llvm-project/files/14624625/MachOObjectFile-02c7ff.cpp.txt)
[MachOObjectFile-02c7ff.sh.txt](https://github.com/llvm/llvm-project/files/14624626/MachOObjectFile-02c7ff.sh.txt)

**Comment by DimitryAndric** [comment] 2024-03-16 17:20
The MachOObjectFile-02c7ff.sh.txt file seems to indicate:

```
# Crash reproducer for clang version 19.0.0git (https://github.com/llvm/llvm-project.git 2d6988a45e29aec9242f96b3ab02a3c3699bc3ec)
```

so this is actually a crash occurring in a `/opt/llvm-19/bin/clang-19` binary? I am guessing you downloaded it from apt.llvm.org?

In any case, I cannot reproduce the crash here locally.

**Comment by fhahn** [comment] 2024-05-15 12:31
@mfvalin could you please confirm which compiler version is causing the crash? Does it still reproduce with latest main?

**Comment by fhahn** [comment] 2024-06-28 12:53
@DimitryAndric thanks for trying! I'll close this one for now, @mfvalin please let us know if this reproduces with current clang

**Closed by fhahn** 2024-06-28 12:53 UTC
Labels: vectorization, crash
