### ISSUE TITLE
clang crashes at -O1 on x86_64-linux-gnu in 'Simple Register Coalescing' pass: Assertion `isReg() && "This is not a register operand!"' failed

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#56123] opened 2022-06-19 21:09 UTC
It appears to be a regression from 12.*. 

```console
% clangtk -v
clang version 15.0.0 (https://github.com/llvm/llvm-project.git aa88161b378ecb49388eefc28abe2926a229bcfc)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
% 
% clangtk -O1 small.c
clang-15: /local/suz-local/software/clangbuild/llvm-project/llvm/include/llvm/CodeGen/MachineOperand.h:360: llvm::Register llvm::MachineOperand::getReg() const: Assertion `isReg() && "This is not a register operand!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /local/suz-local/software/local/clang-trunk/bin/clang-15 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name small.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/local/suz-local/software/emitesting/bugs/DUP/20220619-clangtk-m64-O3-g-mllvm-enable-constraint-elimination-mllvm-opaque-pointers-mllvm-enable-newgvn-build-183657/delta -resource-dir /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0 -I /usr/local/include/csmith -I /local/suz-local/software/local/include -internal-isystem /local/suz-local/software/local/clang-trunk/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O1 -fdebug-compilation-dir=/local/suz-local/software/emitesting/bugs/DUP/20220619-clangtk-m64-O3-g-mllvm-enable-constraint-elimination-mllvm-opaque-pointers-mllvm-enable-newgvn-build-183657/delta -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/small-6d9f9d.o -x c small.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'small.c'.
4.	Running pass 'Simple Register Coalescing' on function '@main'
 #0 0x00005600df296931 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005600df293fa4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fa3763ce980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #3 0x00007fa374ffbe87 raise /build/glibc-CVJwZb/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #4 0x00007fa374ffd7f1 abort /build/glibc-CVJwZb/glibc-2.27/stdlib/abort.c:81:0
 #5 0x00007fa374fed3fa __assert_fail_base /build/glibc-CVJwZb/glibc-2.27/assert/assert.c:89:0
 #6 0x00007fa374fed472 (/lib/x86_64-linux-gnu/libc.so.6+0x30472)
 #7 0x00005600de54999d isMoveInstr(llvm::TargetRegisterInfo const&, llvm::MachineInstr const*, llvm::Register&, llvm::Register&, unsigned int&, unsigned int&) (.constprop.0) RegisterCoalescer.cpp:0:0
 #8 0x00005600de55095f llvm::CoalescerPair::setRegisters(llvm::MachineInstr const*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x304895f)
 #9 0x00005600de55b800 (anonymous namespace)::RegisterCoalescer::joinCopy(llvm::MachineInstr*, bool&) (.constprop.0) RegisterCoalescer.cpp:0:0
#10 0x00005600de55e01f (anonymous namespace)::RegisterCoalescer::copyCoalesceWorkList(llvm::MutableArrayRef<llvm::MachineInstr*>) RegisterCoalescer.cpp:0:0
#11 0x00005600de560c8f (anonymous namespace)::RegisterCoalescer::runOnMachineFunction(llvm::MachineFunction&) RegisterCoalescer.cpp:0:0
#12 0x00005600de3acc58 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x2ea4c58)
#13 0x00005600de8fb1b3 llvm::FPPassManager::runOnFunction(llvm::Function&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x33f31b3)
#14 0x00005600de8fb3e1 llvm::FPPassManager::runOnModule(llvm::Module&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x33f33e1)
#15 0x00005600de8fbcd5 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x33f3cd5)
#16 0x00005600df6482af clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x41402af)
#17 0x00005600e04f2d22 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x4fead22)
#18 0x00005600e1113b89 clang::ParseAST(clang::Sema&, bool, bool) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x5c0bb89)
#19 0x00005600dfdb4231 clang::FrontendAction::Execute() (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x48ac231)
#20 0x00005600dfd3e816 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x4836816)
#21 0x00005600dfe778a8 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x496f8a8)
#22 0x00005600dc78906b cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x128106b)
#23 0x00005600dc782863 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#24 0x00005600dc7856c6 clang_main(int, char**) (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x127d6c6)
#25 0x00007fa374fdec87 __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:344:0
#26 0x00005600dc781dba _start (/local/suz-local/software/local/clang-trunk/bin/clang-15+0x1279dba)
clang-15: error: unable to execute command: Aborted
clang-15: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 15.0.0 (https://github.com/llvm/llvm-project.git aa88161b378ecb49388eefc28abe2926a229bcfc)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
clang-15: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/small-7079c7.c
clang-15: note: diagnostic msg: /tmp/small-7079c7.sh
clang-15: note: diagnostic msg: 

********************
% 
% cat small.c
int printf(const char *, ...);
int a, b, c, d, e, g;
volatile int f;
int main() {
  if (a) {
    int j = 1, i;
    for (; i; i++) {
      int k, l;
      k = c;
      l = j;
      if (g) {
      L1:
        j = j / ~0;
      }
      if (c) {
        if (d)
          printf("0");
        a = k / j;
        break;
      }
      j = l;
    }
    for (i = 0; i < 2; i++) {
      int n;
      f;
    }
    if (b)
      goto L3;
  L2:;
    int q = e, r;
    r = e = 0;
    if (!q && !r)
      goto L1;
    while (d++)
      ;
    goto L2;
  L3:
    while (1)
      ;
  }
  return 0;
}
```

Compiler Explorer: https://godbolt.org/z/bbqEn7ceb

**Comment by zhendongsu** [comment] 2022-06-19 21:11
It might be related to https://github.com/llvm/llvm-project/issues/53168.

**Comment by fhahn** [comment] 2023-11-03 15:08
Looks like this doesn't reproduce on current `main` any longer. Closing for now.

**Closed by fhahn** 2023-11-03 15:08 UTC
Labels: llvm:crash, llvm:optimizations
