### ISSUE TITLE
clang-format crashes on one of the files in a project I maintain

### ISSUE THREAD

**Issue by 669c3a3e-fba1-46d8-a39f-08bdb916c752** [llvm/llvm-project#50842] opened 2021-08-17 09:19 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51500](https://llvm.org/bz51500) |
| Version | trunk |
| OS | Linux |
| Attachments | [Backtrace](https://user-images.githubusercontent.com/93435524/143762427-f12b2d5f-bfe2-488d-85d2-6b0e888eeaf8.gz), [C source file](https://user-images.githubusercontent.com/93435524/143762428-92bff532-48fd-4311-b5a5-1b3aeb38107e.gz), [Configuration file](https://user-images.githubusercontent.com/93435524/143762429-93b6ee02-b6e1-4d87-93de-c0cd0431b656.gz) |

## Extended Description 

OS: Linux Mint 20
Platform: amd64
Version: 13.0.0-++20210816122611+dcdb12496c24-1~exp1~20210816103407.41 (from apt.llvm.org)

Hello.

When running the above clang-format version against the attached .c file with the attached .clang-format file, clang-format crashes with the attached backtrace.

Regards,
Aaron Jones

**Comment by mkurdej** [comment] 2021-12-13 13:46
Minimal reproduce on version 13.0.0:

file.c:
```
static const struct {
	const char* a;
	const char* b;
} bcrypt_test_vectors[] = {
	{
		.a = "a",
		.b = "b",
	},
};
```

.clang-format:
```
Language: Cpp
BasedOnStyle: LLVM

AlignArrayOfStructures:                     Right
```

However, the crash doesn't happen on current main branch (neither on original case nor minimal repro).

**Comment by mkurdej** [comment] 2021-12-13 13:49
Closing. Please reopen if I missed something and the issue isn't fixed.

**Closed by mkurdej** 2021-12-13 13:49 UTC
Labels: clang-format, bugzilla

**Comment by mydeveloperday** [comment] 2021-12-13 14:34
I believe this was added with the following commit a36227cb2b6a14fc30bfd303328d1d1abb632010
