### ISSUE TITLE
clang-format crashed while formatting a piece of simple code

### ISSUE THREAD

**Issue by MenthuZhou** [llvm/llvm-project#85898] opened 2024-03-20 06:27 UTC
### Llvm crashed while formatting a piece of simple code

Visual Studio 2022 Version 17.9.3

the simple piece of code:

~~~ C++
bool B::A::operator=(
~~~

create an empty CPP file and open it with VS, copy and parse,  the VS try to format this piece of code, and Llvm would crashed.

~~~
0.	Program arguments: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\Llvm\\bin\\clang-format.exe" -output-replacements-xml -style=file -fallback-style=Google -assume-filename=a.cpp -offset=0 -length=21 -cursor=21
Exception Code: 0xC0000005
0x0065B0C2, C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\bin\clang-format.exe(0x00000000005A0000) + 0xBB0C2 byte(s)
0x0164C618 <unknown module>
0x0164E5FC <unknown module>
~~~

**Comment by owenca** [comment] 2024-03-20 07:22
This is a duplicate of #82328.

**Closed** 2024-03-20 07:22 UTC
Labels: duplicate, clang-format, crash-on-invalid
