### ISSUE TITLE
MemorySanitizer-X86_64 :: mmap.cpp test fails on 6.1.1 Linux kernel

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#59717] opened 2022-12-27 11:27 UTC
The following test is failing for me on 6.1.1 kernel. After booting 6.0.14, it passes. Tested as of dfc20708bcdf7b4c4bea8595fc4ac8674634d5e6, on Gentoo Linux/amd64.

Kernel config for 6.0.14: [config-6.0.14.txt](https://github.com/llvm/llvm-project/files/10307840/config-6.0.14.txt)
Kernel config for 6.1.1: [config-6.1.1.txt](https://github.com/llvm/llvm-project/files/10307841/config-6.1.1.txt)

Let me know if there's anything else that could help.

```console
FAIL: MemorySanitizer-X86_64 :: mmap.cpp (2709 of 6366)
******************** TEST 'MemorySanitizer-X86_64 :: mmap.cpp' FAILED ********************
Script:
--
: 'RUN: at line 2';      /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/lib/llvm/16/bin/clang  --driver-mode=g++ -fsanitize=memory -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls  -m64  -gline-tables-only -O0 /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt/test/msan/mmap.cpp -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.tmp &&  /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.tmp
: 'RUN: at line 3';      /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/lib/llvm/16/bin/clang  --driver-mode=g++ -fsanitize=memory -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls  -m64  -gline-tables-only -O0 -fsanitize-memory-track-origins /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt/test/msan/mmap.cpp -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.tmp &&  /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.tmp
--
Exit Code: 134

Command Output (stdout):
--
0x7f6d27400000
0x7f5d27400000
0x7f4d27400000
0x7f3d27400000
0x7f2d27400000
0x7f1d27400000
0x7f0d27400000
0x7efd27400000
0x7eed27400000
0x7edd27400000
0x7ecd27400000
0x7ebd27400000
0x7ead27400000
0x7e9d27400000
0x7e8d27400000
0x7e7d27400000
0x7e6d27400000
0x7e5d27400000
0x7e4d27400000
0x7e3d27400000
0x7e2d27400000
0x7e1d27400000
0x7e0d27400000
0x7dfd27400000
0x7ded27400000
0x7ddd27400000
0x7dcd27400000
0x7dbd27400000
0x7dad27400000
0x7d9d27400000
0x7d8d27400000
0x7d7d27400000
0x7d6d27400000
0x7d5d27400000
0x7d4d27400000
0x7d3d27400000
0x7d2d27400000
0x7d1d27400000
0x7d0d27400000
0x7cfd27400000
0x7ced27400000
0x7cdd27400000
0x7ccd27400000
0x7cbd27400000
0x7cad27400000
0x7c9d27400000
0x7c8d27400000
0x7c7d27400000
0x7c6d27400000
0x7c5d27400000
0x7c4d27400000
0x7c3d27400000
0x7c2d27400000
0x7c1d27400000
0x7c0d27400000
0x7bfd27400000
0x7bed27400000
0x7bdd27400000
0x7bcd27400000
0x7bbd27400000
0x7bad27400000
0x7b9d27400000
0x7b8d27400000
0x7b7d27400000
0x7b6d27400000
0x7b5d27400000
0x7b4d27400000
0x7b3d27400000
0x7b2d27400000
0x7b1d27400000
0x7b0d27400000
0x7afd27400000
0x7aed27400000
0x7add27400000
0x7acd27400000
0x7abd27400000
0x7aad27400000
0x7a9d27400000
0x7a8d27400000
0x7a7d27400000
0x7a6d27400000
0x7a5d27400000
0x7a4d27400000
0x7a3d27400000
0x7a2d27400000
0x7a1d27400000
0x7a0d27400000
0x79fd27400000
0x79ed27400000
0x79dd27400000
0x79cd27400000
0x79bd27400000
0x79ad27400000
0x799d27400000
0x798d27400000
0x797d27400000
0x796d27400000
0x795d27400000
0x794d27400000
0x793d27400000
0x792d27400000
0x791d27400000
0x790d27400000
0x78fd27400000
0x78ed27400000
0x78dd27400000
0x78cd27400000
0x78bd27400000
0x78ad27400000
0x789d27400000
0x788d27400000
0x787d27400000
0x786d27400000
0x785d27400000
0x784d27400000
0x783d27400000
0x782d27400000
0x781d27400000
0x780d27400000
0x77fd27400000
0x77ed27400000
0x77dd27400000
0x77cd27400000
0x77bd27400000
0x77ad27400000
0x779d27400000
0x778d27400000
0x777d27400000
0x776d27400000
0x775d27400000
0x774d27400000
0x773d27400000
0x772d27400000
0x771d27400000
0x770d27400000
0x76fd27400000
0x76ed27400000
0x76dd27400000
0x76cd27400000
0x76bd27400000
0x76ad27400000
0x769d27400000
0x768d27400000
0x767d27400000
0x766d27400000
0x765d27400000
0x764d27400000
0x763d27400000
0x762d27400000
0x761d27400000
0x760d27400000
0x75fd27400000
0x75ed27400000
0x75dd27400000
0x75cd27400000
0x75bd27400000
0x75ad27400000
0x759d27400000
0x758d27400000
0x757d27400000
0x756d27400000
0x755d27400000
0x754d27400000
0x753d27400000
0x752d27400000
0x751d27400000
0x750d27400000
0x74fd27400000
0x74ed27400000
0x74dd27400000
0x74cd27400000
0x74bd27400000
0x74ad27400000
0x749d27400000
0x748d27400000
0x747d27400000
0x746d27400000
0x745d27400000
0x744d27400000
0x743d27400000
0x742d27400000
0x741d27400000
0x740d27400000
0x5ff000000000
0x5fe000000000
0x5fd000000000
0x5fc000000000
0x5fb000000000
0x5fa000000000
0x5f9000000000
0x5f8000000000
0x5f7000000000
0x5f6000000000
0x5f5000000000
0x5f4000000000
0x5f3000000000
0x5f2000000000
0x5f1000000000
0x5f0000000000
0x5ef000000000
0x5ee000000000
0x5ed000000000
0x5ec000000000
0x5eb000000000
0x5ea000000000
0x5e9000000000
0x5e8000000000
0x5e7000000000
0x5e6000000000
0x5e5000000000
0x5e4000000000
0x5e3000000000
0x5e2000000000
0x5e1000000000
0x5e0000000000
0x5df000000000
0x5de000000000
0x5dd000000000
0x5dc000000000
0x5db000000000
0x5da000000000
0x5d9000000000
0x5d8000000000
0x5d7000000000
0x5d6000000000
0x5d5000000000
0x5d4000000000
0x5d3000000000
0x5d2000000000
0x5d1000000000
0x5d0000000000
0x5cf000000000
0x5ce000000000
0x5cd000000000
0x5cc000000000
0x5cb000000000
0x5ca000000000
0x5c9000000000
0x5c8000000000
0x5c7000000000
0x5c6000000000
0x5c5000000000
0x5c4000000000
0x5c3000000000
0x5c2000000000
0x5c1000000000
0x5c0000000000
0x5bf000000000
0x5be000000000
0x5bd000000000
0x5bc000000000
0x5bb000000000
0x5ba000000000
0x5b9000000000
0x5b8000000000
0x5b7000000000
0x5b6000000000
0x5b5000000000
0x5b4000000000
0x5b3000000000
0x5b2000000000
0x5b1000000000
0x5b0000000000
0x5af000000000
0x5ae000000000
0x5ad000000000
0x5ac000000000
0x5ab000000000
0x5aa000000000
0x5a9000000000
0x5a8000000000
0x5a7000000000
0x5a6000000000
0
--
Command Output (stderr):
--
+ : 'RUN: at line 2'
+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/lib/llvm/16/bin/clang --driver-mode=g++ -fsanitize=memory -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -m64 -gline-tables-only -O0 /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt/test/msan/mmap.cpp -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.tmp
+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.tmp
mmap.cpp.tmp: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt/test/msan/mmap.cpp:67: int main(): Assertion `errno == ENOMEM' failed.
/var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.script: line 2: 159289 Aborted                 (core dumped) /var/tmp/portage/sys-libs/compiler-rt-sanitizers-16.0.0_pre20221226/work/compiler-rt_build/test/msan/X86_64/Output/mmap.cpp.tmp

--

********************
```

**Comment by mgorny** [comment] 2022-12-27 16:15
[Holger Hoffstätte](https://fosstodon.org/@asynchronaut) suggested that https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6f12be792fde994ed934168f93c2a0d2a0cf0bc5 may fix it.

**Comment by mgorny** [comment] 2023-01-01 07:46
> [Holger Hoffstätte](https://fosstodon.org/@asynchronaut) suggested that https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6f12be792fde994ed934168f93c2a0d2a0cf0bc5 may fix it.

Unless I've done something wrong, applying this patch on top of 6.1.2 did not help.

**Comment by hhoffstaette** [comment] 2023-01-01 13:34
My kernel has the mentioned patch. I built the test as standalone executable, added a printf for errno (to see what failed instead of the expected ENOMEM) and found something odd.

As regular user:
```
holger>clang++ -fsanitize=memory mmap.cpp
holger>./a.out                          
0x7f8de3300000
0x7f7de3300000
0x7f6de3300000
<snip>
0x5108e80a4000
0xf000000000
0xe000000000
0xd000000000
0xc000000000
0xb000000000
0xa000000000
0x9000000000
0x8000000000
0x7000000000
0x6000000000
0x5000000000
0x4000000000
0x3000000000
0x2000000000
0x1000000000
0xffffffffffffffff
errno=1
a.out: mmap.cpp:68: int main(): Assertion `errno == ENOMEM' failed.
zsh: IOT instruction  ./a.out
```
errno=1 is EPERM, so I tried as root and:
```
holger>sudo ./a.out                      
0x7fab68f00000
0x7f9b68f00000
0x7f8b68f00000
<snip>
0x510d6aa11000
0xf000000000
0xe000000000
0xd000000000
0xc000000000
0xb000000000
0xa000000000
0x9000000000
0x8000000000
0x7000000000
0x6000000000
0x5000000000
0x4000000000
0x3000000000
0x2000000000
0x1000000000
(nil)
0x7fbb6af22000
0x7fcb6af22000
0x7fdb6af22000
0x7feb6af22000
0xffffffffffffffff
errno=12
successful mappings: 446
```

**Comment by mgorny** [comment] 2023-01-01 13:58
So… I'm guessing that it relies on something that can no longer be done without superuser powers?

**Comment by hhoffstaette** [comment] 2023-01-01 14:23
> So… I'm guessing that it relies on something that can no longer be done without superuser powers?

Not necessarily. I don't understand what it is trying to verify in the first place, and it seems to be just written with a lot of assumptions. What is an endless loop that exits only at ENOMEM supposed to prove, when the final assertion checks that at least 6 mmaps could be made? It all seems very fragile.

**Comment by hhoffstaette** [comment] 2023-01-01 18:03
As far as I can see there are two different things going on here, and they are likely kernel regressions:

- mmap() suddenly returning a nullptr (the (nil))
- mmap() failing with `MAP_FAILED` but errno being `EPERM`, probably because mmap_min_addr has been reached. This should probably also set errno to `ENOMEM`, but does not - hence the assertion failure.

**Comment by mgorny** [comment] 2023-01-12 06:11
> This problem will be fixed by [this patch to 6.1](https://lore.kernel.org/stable/20230111200136.1851322-1-Liam.Howlett@oracle.com/). I've applied it and the test again succeeds with the expected ENOMEM instead of EPERM.

Thanks for looking into this! Hopefully the next 6.1.x release will be out and working before the next snapshot ;-).

**Comment by hhoffstaette** [comment] 2023-02-07 09:59
The fix for this is finally in [mainline aka upcoming 6.2](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7327e8111adb315423035fb5233533016dfd3f2e) and  was also just added to the stable-queue for 6.1.11.

**Comment by hhoffstaette** [comment] 2023-02-15 08:59
@mgorny can you retest with kernel >= 6.1.11?

**Comment by mgorny** [comment] 2023-02-15 09:25
Ah, sorry. I think it's fixed — I didn't see any test failures with neither 16.0.0rc2 or last weekend's 17.x snapshot.

**Comment by hhoffstaette** [comment] 2023-02-26 10:29
@mgorny @thesamesam Can one of you close this?

**Closed** 2023-02-26 14:47 UTC
Labels: regression, compiler-rt:msan, platform:linux
