### ISSUE TITLE
clang-15: error: clang frontend command failed with exit code 134

### ISSUE THREAD

**Issue by lanthora** [llvm/llvm-project#60707] opened 2023-02-13 13:49 UTC
```console
Stack dump:
0.	Program arguments: clang -g -O2 -I . -target bpf -c -D__x86_64__ sysprobe-ebpf/sysprobe.c -o target/sysprobe.o
1.	<eof> parser at end of file
2.	Optimizer
 #0 0x00007fa23d57c48a (/usr/lib/libLLVM-15.so+0xd7c48a)
 #1 0x00007fa23d579b1f llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-15.so+0xd79b1f)
 #2 0x00007fa23d45c5e9 (/usr/lib/libLLVM-15.so+0xc5c5e9)
 #3 0x00007fa23c251f50 (/usr/lib/libc.so.6+0x38f50)
 #4 0x00007fa23c2a08ec (/usr/lib/libc.so.6+0x878ec)
 #5 0x00007fa23c251ea8 raise (/usr/lib/libc.so.6+0x38ea8)
 #6 0x00007fa23c23b53d abort (/usr/lib/libc.so.6+0x2253d)
 #7 0x00007fa23c23c29e (/usr/lib/libc.so.6+0x2329e)
 #8 0x00007fa23c2aa657 (/usr/lib/libc.so.6+0x91657)
 #9 0x00007fa23c2ab144 (/usr/lib/libc.so.6+0x92144)
#10 0x00007fa23c2ac1f0 (/usr/lib/libc.so.6+0x931f0)
#11 0x00007fa23c2aee63 free (/usr/lib/libc.so.6+0x95e63)
#12 0x00007fa23d6ba042 llvm::Instruction::eraseFromParent() (/usr/lib/libLLVM-15.so+0xeba042)
#13 0x00007fa240313e9d (/usr/lib/libLLVM-15.so+0x3b13e9d)
#14 0x00007fa24031665a (/usr/lib/libLLVM-15.so+0x3b1665a)
#15 0x00007fa240316ae7 (/usr/lib/libLLVM-15.so+0x3b16ae7)
#16 0x00007fa240327786 (/usr/lib/libLLVM-15.so+0x3b27786)
#17 0x00007fa23fd34b85 (/usr/lib/libLLVM-15.so+0x3534b85)
#18 0x00007fa23d7412f0 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/libLLVM-15.so+0xf412f0)
#19 0x00007fa23fd25fe6 (/usr/lib/libLLVM-15.so+0x3525fe6)
#20 0x00007fa23d73a3e4 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/libLLVM-15.so+0xf3a3e4)
#21 0x00007fa2467ffd03 (/usr/lib/libclang-cpp.so.15+0x25ffd03)
#22 0x00007fa24575654c clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib/libclang-cpp.so.15+0x155654c)
#23 0x00007fa245a475a8 (/usr/lib/libclang-cpp.so.15+0x18475a8)
#24 0x00007fa244a491d0 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/libclang-cpp.so.15+0x8491d0)
#25 0x00007fa2460e7479 clang::FrontendAction::Execute() (/usr/lib/libclang-cpp.so.15+0x1ee7479)
#26 0x00007fa24608d14f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.15+0x1e8d14f)
#27 0x00007fa24615209a clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/libclang-cpp.so.15+0x1f5209a)
#28 0x000055608d6494d0 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-15+0x104d0)
#29 0x000055608d64f197 (/usr/bin/clang-15+0x16197)
#30 0x00007fa245dd5959 (/usr/lib/libclang-cpp.so.15+0x1bd5959)
#31 0x00007fa23d45c6b7 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/libLLVM-15.so+0xc5c6b7)
#32 0x00007fa245ddb48f (/usr/lib/libclang-cpp.so.15+0x1bdb48f)
#33 0x00007fa245d9ebbe clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/libclang-cpp.so.15+0x1b9ebbe)
#34 0x00007fa245d9ef7d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&, bool) const (/usr/lib/libclang-cpp.so.15+0x1b9ef7d)
#35 0x00007fa245df815c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib/libclang-cpp.so.15+0x1bf815c)
#36 0x000055608d6517f9 clang_main(int, char**) (/usr/bin/clang-15+0x187f9)
#37 0x00007fa23c23c790 (/usr/lib/libc.so.6+0x23790)
#38 0x00007fa23c23c84a __libc_start_main (/usr/lib/libc.so.6+0x2384a)
#39 0x000055608d645d25 _start (/usr/bin/clang-15+0xcd25)
clang-15: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 15.0.7
Target: bpf
Thread model: posix
InstalledDir: /usr/bin
clang-15: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/sysprobe-f95e8c.c
clang-15: note: diagnostic msg: /tmp/sysprobe-f95e8c.sh
clang-15: note: diagnostic msg: 

********************
```
[sysprobe-f95e8c.c.txt](https://github.com/llvm/llvm-project/files/10722793/sysprobe-f95e8c.c.txt)
[sysprobe-f95e8c.sh.txt](https://github.com/llvm/llvm-project/files/10722796/sysprobe-f95e8c.sh.txt)

**Comment by fhahn** [comment] 2023-02-13 14:08
Looks like this crashes in BPF specific code, and does not reproduce on `main`: https://clang.godbolt.org/z/ETofdqTMd

**Comment by lanthora** [comment] 2023-02-16 07:14
@fhahn Thanks,I will close this issue when the commit that fixes the bug is backported to clang 15

**Comment by fhahn** [comment] 2023-02-18 20:41
I don't think there will be another 15.x release now that 16.x branched

**Comment by fhahn** [comment] 2023-02-19 11:42
Let's close this for now, as there probably won't be another 15.x release. Please check if it is fixed on the 16.x branch. If it is not fixed, please let me know, then we can re-open the issue.

**Closed by fhahn** 2023-02-19 11:42 UTC
Labels: backend:BPF
