### ISSUE TITLE
[flang] extra warning in declaring proc with the same name as private proc in module

### ISSUE THREAD

**Issue by kkwli** [llvm/llvm-project#61170] opened 2023-03-03 19:33 UTC
There is a warning when declaring a procedure with the same name as a private procedure declared in a module. Is this behavior expected?

`f1` is a private procedure but it seems to be accessible via use association.

```f90
module m
  private
  abstract interface
    real(4) function p(x, y)
    real(4) :: x, y
    end function
  end interface

  procedure(p) :: f1
end module

program main
  use m
  integer(4) :: x, y, z
!  real(4) ::  f1
  z = f1(x, y)
end
```
Compile output:
```console
$ flang-new -fsyntax-only d1.f90
./d1.f90:9:19: warning: The global subprogram 'f1' is not compatible with its local procedure declaration (incompatible procedure attributes: ImplicitInterface)
    procedure(p) :: f1
                    ^^
./d1.f90:16:7: Declaration of 'f1'
    z = f1(x, y)
        ^^
./d1.f90:9:19: Declaration of 'f1'
    procedure(p) :: f1
                    ^^
```

The behavior seems to occur after 0d588347000bd8245b8a1824758c6ed005ae5bce.

**Comment by klausler** [comment] 2023-03-06 21:59
Private or not, this source file has two interfaces declared for the same external name and those interfaces are not compatible, hence the warning.

**Comment by kkwli** [comment] 2023-03-07 20:33
I am a little bit confused. The module has a `private` statement and `f1` is declared without the `public` attribute. So `f1` is not available to be accessed from the module by use association. In the main program, there exists only one `f1` with the implicit interface. The warning message alludes to conflicting declaration of `f1` but there is only one declaration (implicit) of `f1` in the main program.

If I add the declaration of `f1` (`integer` instead of `real(4)`) in `main`, it compiles without warning.
```f90
module m
  private
  abstract interface
    real(4) function p(x, y)
    real(4) :: x, y
    end function
  end interface
  procedure(p) :: f1
end module

program main
  use m
  integer(4) :: x, y, z
  integer(4) ::  f1         !!! declare f1
  z = f1(x, y)
end
```

**Comment by klausler** [comment] 2023-03-07 20:37
There are two places in this source file that declare an interface for the external name `f1`.

One interface has a result type of `real`, one interface has a result type of `integer'.

It will not be possible to define the external name `f1` in such a way that both of these interfaces can be correct.

One of them must be incorrect.

So the compiler emits a warning.

**Comment by kkwli** [comment] 2023-03-07 21:17
Sorry, I was not clear. There is no warning in this case (declare `f1` in the main).
> ```f90
> module m
>   private
>   abstract interface
>     real(4) function p(x, y)
>     real(4) :: x, y
>     end function
>   end interface
>   procedure(p) :: f1
> end module
> 
> program main
>   use m
>   integer(4) :: x, y, z
>   integer(4) ::  f1         !!! declare f1
>   z = f1(x, y)
> end
> ```

**Comment by klausler** [comment] 2023-05-17 15:45
I would not expect a warning from the modified program.

**Comment by klausler** [comment] 2023-06-05 17:15
Closing this issue; the compiler is working as intended.

**Closed by klausler** 2023-06-05 17:15 UTC
Labels: flang:frontend
