### ISSUE TITLE
Bufferization Over Aggressive Copy Removal

### ISSUE THREAD

**Issue by squablyScientist** [llvm/llvm-project#58293] opened 2022-10-11 15:46 UTC
Hello. While attempting to bufferize some mhlo code, I noticed a weird semantic change regarding how `iter_args` are lowered. It appears that if an `iter_arg` is not explicitly used after an `scf.for` loop, copy removal will be performed. However, this can lead to semantically different side effects than expected. For example, consider the following two IR snippets:

### IR A
```mlir
func.func @loop_example(%arg0: tensor<16xi32>) -> (tensor<16xi32>) attributes {tf.entry_function = {control_outputs = "", inputs = "args_0", outputs = "Identity"}}{
    %c0 = arith.constant 0 : index 
    %c1 = arith.constant 1 : index 
    %c16 = arith.constant 16 : index 
    %c1_i32 = arith.constant 1 : i32
    %0 = scf.for %arg1 = %c0 to %c16 step %c1 iter_args(%arg2 = %arg0) -> (tensor<16xi32>) {
        %1 = tensor.extract %arg2[%arg1] : tensor<16xi32>
        %2 = arith.addi %1, %c1_i32 : i32
        %3 = tensor.insert %2 into %arg2[%arg1] : tensor<16xi32>
        scf.yield %3 : tensor<16xi32>
        }
    return %arg0 : tensor<16xi32>
}
```

### IR B
```mlir
func.func @loop_example(%arg0: tensor<16xi32>) -> (tensor<16xi32>) attributes {tf.entry_function = {control_outputs = "", inputs = "args_0", outputs = "Identity"}}{
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c16 = arith.constant 16 : index
    %c1_i32 = arith.constant 1 : i32
    %0 = scf.for %arg1 = %c0 to %c16 step %c1 iter_args(%arg2 = %arg0) -> (tensor<16xi32>) {
        %1 = tensor.extract %arg2[%arg1] : tensor<16xi32>
        %2 = arith.addi %1, %c1_i32 : i32
        %3 = tensor.insert %2 into %arg2[%arg1] : tensor<16xi32>
        scf.yield %3 : tensor<16xi32>
    }
    return %0 : tensor<16xi32>
}
```

These two IRs are identical save for the fact that `IR A` uses `%arg0` post-loop, and `IR B` does not. They should return two different things; `IR A` throws out the loop modifications and `IR B` returns them. However, when lowering with the `mlir-opt` command: 
```sh
mlir-opt --one-shot-bufferize="bufferize-function-boundaries allow-return-allocs" --buffer-results-to-out-params --linalg-init-tensor-to-alloc-tensor --convert-tensor-to-linalg --finalizing-bufferize --buffer-deallocation -convert-bufferization-to-memref
```
something unexpected happens: 

### Bufferized IR A
```mlir
module {
  func.func @loop_example(%arg0: memref<16xi32, #map>, %arg1: memref<16xi32, #map>) attributes {tf.entry_function = {control_outputs = "", inputs = "args_0", outputs = "Identity"}} {
    %c1_i32 = arith.constant 1 : i32
    %c16 = arith.constant 16 : index
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %0 = memref.alloc() {alignment = 128 : i64} : memref<16xi32>
    memref.copy %arg0, %0 : memref<16xi32, #map> to memref<16xi32>
    scf.for %arg2 = %c0 to %c16 step %c1 {
      %1 = memref.load %0[%arg2] : memref<16xi32>
      %2 = arith.addi %1, %c1_i32 : i32
      memref.store %2, %0[%arg2] : memref<16xi32>
    }
    memref.dealloc %0 : memref<16xi32>
    memref.copy %arg0, %arg1 : memref<16xi32, #map> to memref<16xi32, #map>
    return
  }
}
```

### Bufferized IR B
```mlir
module {
  func.func @loop_example(%arg0: memref<16xi32, #map>, %arg1: memref<16xi32, #map>) attributes {tf.entry_function = {control_outputs = "", inputs = "args_0", outputs = "Identity"}} {
    %c1_i32 = arith.constant 1 : i32
    %c16 = arith.constant 16 : index
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    scf.for %arg2 = %c0 to %c16 step %c1 {
      %0 = memref.load %arg0[%arg2] : memref<16xi32, #map>
      %1 = arith.addi %0, %c1_i32 : i32
      memref.store %1, %arg0[%arg2] : memref<16xi32, #map>
    }
    memref.copy %arg0, %arg1 : memref<16xi32, #map> to memref<16xi32, #map>
    return
  }
}
```

Seen above, `IR B` becomes bufferized in a way that removes the copying from `%arg0` into the local `%0` allocation. This causes the loop to write directly to `%arg0`, modifying the input when the original IR did not. I believe this is a bufferization bug, as it is a pass that alters the semantics of a program. Is there a way to disable this, or is this truly a bug?

---

### LLVM SHA
`54d179116e7a79eb1fdf7819aad62b4d76bc0e15e8567871cae9b675f7dec5c1`

**Comment by matthias-springer** [comment] 2022-10-12 01:49
This is working as expected. One-Shot Bufferize bufferizes function boundaries as follows (taken from `OneShotModuleBufferize.cpp`):

```c++
// Module Bufferization implements the following calling convention.
//
// * In the absence of conflicts within a FuncOp, the FuncOp's bbArgs may always
//   be written to in-place.
// * If a tensor operand of a CallOp is read after the CallOp, the operand of
//   the CallOp must bufferize out-of-place.
```

In other words, it is OK to modify function args. If the original value is still needed, it is the caller's responsibility to make a copy.

If this is not desirable (e.g., because the function is getting called from an external program), you can explicitly mark the args as "not writable":

```mlir
// RUN: mlir-opt %s --one-shot-bufferize="bufferize-function-boundaries allow-return-allocs"

func.func @loop_exampleB(%arg0: tensor<16xi32> {bufferization.writable = false}) -> (tensor<16xi32>) {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %c16 = arith.constant 16 : index
    %c1_i32 = arith.constant 1 : i32
    %0 = scf.for %arg1 = %c0 to %c16 step %c1 iter_args(%arg2 = %arg0) -> (tensor<16xi32>) {
        %1 = tensor.extract %arg2[%arg1] : tensor<16xi32>
        %2 = arith.addi %1, %c1_i32 : i32
        %3 = tensor.insert %2 into %arg2[%arg1] : tensor<16xi32>
        scf.yield %3 : tensor<16xi32>
    }
    return %0 : tensor<16xi32>
}
```

Bufferizes to:

```mlir
  func.func @loop_exampleB(%arg0: memref<16xi32, strided<[?], offset: ?>>) -> memref<16xi32> {
    %c1_i32 = arith.constant 1 : i32
    %c16 = arith.constant 16 : index
    %c1 = arith.constant 1 : index
    %c0 = arith.constant 0 : index
    %alloc = memref.alloc() {alignment = 128 : i64} : memref<16xi32>
    memref.copy %arg0, %alloc : memref<16xi32, strided<[?], offset: ?>> to memref<16xi32>
    scf.for %arg1 = %c0 to %c16 step %c1 {
      %0 = memref.load %alloc[%arg1] : memref<16xi32>
      %1 = arith.addi %0, %c1_i32 : i32
      memref.store %1, %alloc[%arg1] : memref<16xi32>
    }
    return %alloc : memref<16xi32>
  }
```

We could also add a new bufferization flag if you want "read-only" arguments by default.

Btw, it may also be interesting to take a look at the result of the analysis (`mlir-opt %s --one-shot-bufferize="bufferize-function-boundaries allow-return-allocs test-analysis-only"`). You can see that `%arg0` is accessed differently in example A and example B:

```mlir
func.func @loop_exampleA(%arg0: tensor<16xi32> {bufferization.access = "read"}) -> tensor<16xi32> {
...
func.func @loop_exampleB(%arg0: tensor<16xi32> {bufferization.access = "read-write"}) -> tensor<16xi32> {
```

(This behavior is unrelated to `scf.for` and can be reproduced with any op that bufferizes to a memory write.)

**Comment by matthias-springer** [comment] 2022-10-24 14:24
WAI, closing this issue.

**Closed by matthias-springer** 2022-10-24 14:24 UTC
Labels: llvm:optimizations
