### ISSUE TITLE
Deduction of template template parameter from template function parameter fails without `-frelaxed-template-template-args`

### ISSUE THREAD

**Issue by vittorioromeo** [llvm/llvm-project#56373] opened 2022-07-04 13:50 UTC
Given

```cpp
template <template <typename> typename C, typename T> void f(C<T>) { }
template <typename, int = 0> struct S { };
int main() { f(S<int>{}); }
```

the trunk version of `clang++`, compiling with `-std=c++20`, reports:

```
<source>:3:14: error: no matching function for call to 'f'
int main() { f(S<int>{}); }
             ^
<source>:1:60: note: candidate template ignored: substitution failure: 
    template template argument has different template parameters than its corresponding template template parameter
template <template <typename> typename C, typename T> void f(C<T>) { }
                                                           ^
```

Passing `-frelaxed-template-template-args` prevents the compilation failure. Note that the trunk version of `g++` accepts the code with `-std=c++20` without the need of any additional flag.

[**live example on godbolt.org**](https://godbolt.org/z/zWMavoovP)

My understanding is that the code in this issue should be valid in C++17 -- shouldn't the `-frelaxed-template-template-args` be turned on by default when compiling in C++17 mode (or above)?

Thanks.

**Comment by mizvekov** [comment] 2022-07-04 16:23
The implementation currently in clang does not have any workarounds for the ambiguity issues caused by that change in the standard. Note that GCC made up their own rules to solve those issues, and in clang we intend to develop our own solution as well.

There is currently no one working on a change to the standard to solve those issues as far as I know.

Some time ago I created a patch which deprecated that flag and enabled it unconditionally, while also implementing a workaround, but @zygoloid suggested some changes in private which I didn't have time to follow up yet, and probably won't in the near future due to other commitments.

See https://reviews.llvm.org/D109496

**Comment by mizvekov** [comment] 2022-07-04 16:32
Duplicate of https://github.com/llvm/llvm-project/issues/48423

**Closed by mizvekov** 2022-07-04 16:32 UTC
Labels: c++20, clang:frontend

**Comment by SwuduSusuwu** [comment] 2024-10-28 05:04
This bug affects the _CodeQL_ runners on GitHub:
https://github.com/SwuduSusuwu/SubStack/actions/runs/11547225899/job/32136774360
