### ISSUE TITLE
Building Linux 6.9.9 Kernel Slung One

### ISSUE THREAD

**Issue by Grimish-ng** [llvm/llvm-project#98605] opened 2024-07-12 09:13 UTC
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ld.lld -m elf_x86_64 -mllvm -import-instr-limit=5 -z noexecstack -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive vmlinux.a --no-whole-archive --start-group --end-group
1.      Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
 #0 0x000071e34c5c4d90 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM.so.18.1+0x7c4d90)
 #1 0x000071e34c5c1d4d (/usr/lib/libLLVM.so.18.1+0x7c1d4d)
 #2 0x000071e34b850ae0 (/usr/lib/libc.so.6+0x3cae0)
 #3 0x000071e34b8a8e44 (/usr/lib/libc.so.6+0x94e44)
 #4 0x000071e34b850a30 raise (/usr/lib/libc.so.6+0x3ca30)
 #5 0x000071e34b8384c3 abort (/usr/lib/libc.so.6+0x244c3)
 #6 0x000071e34bad2d60 std::chrono::_V2::system_clock::now() /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/chrono.cc:52:5
 #7 0x000071e34d0ed7d0 llvm::ScheduleDAGSDNodes::AddSchedEdges() (/usr/lib/libLLVM.so.18.1+0x12ed7d0)
 #8 0x000071e34d0e5786 (/usr/lib/libLLVM.so.18.1+0x12e5786)
 #9 0x000071e34d1d95f2 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/libLLVM.so.18.1+0x13d95f2)
#10 0x000071e34d1dca09 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/libLLVM.so.18.1+0x13dca09)
#11 0x000071e34d1deb57 (/usr/lib/libLLVM.so.18.1+0x13deb57)
#12 0x000071e34d1e0591 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/libLLVM.so.18.1+0x13e0591)
#13 0x000071e3508984b8 (/usr/lib/libLLVM.so.18.1+0x4a984b8)
#14 0x000071e34cb2f72d (/usr/lib/libLLVM.so.18.1+0xd2f72d)
#15 0x000071e34c7830d3 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/libLLVM.so.18.1+0x9830d3)
#16 0x000071e34c7834a4 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x9834a4)
#17 0x000071e34c784f6f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x984f6f)
#18 0x000071e34e659abd (/usr/lib/libLLVM.so.18.1+0x2859abd)
#19 0x000071e34e65a1b1 llvm::lto::backend(llvm::lto::Config const&, std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/usr/lib/libLLVM.so.18.1+0x285a1b1)
#20 0x000071e34e64e9e9 llvm::lto::LTO::runRegularLTO(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>) (/usr/lib/libLLVM.so.18.1+0x284e9e9)
#21 0x000071e34e64eee1 llvm::lto::LTO::run(std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, std::function<llvm::Expected<std::function<llvm::Expected<std::unique_ptr<llvm::CachedFileStream, std::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>> (unsigned int, llvm::StringRef, llvm::Twine const&)>) (/usr/lib/libLLVM.so.18.1+0x284eee1)
#22 0x000071e35431bd69 lld::elf::BitcodeCompiler::compile() (/usr/lib/liblldELF.so.18.1+0x11bd69)
#23 0x000071e3542a23d6 lld::elf::LinkerDriver::link(llvm::opt::InputArgList&) (/usr/lib/liblldELF.so.18.1+0xa23d6)
#24 0x000071e354287760 lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (/usr/lib/liblldELF.so.18.1+0x87760)
#25 0x000071e354289218 lld::elf::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/usr/lib/liblldELF.so.18.1+0x89218)
#26 0x000071e3544e1acd lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/usr/lib/liblldCommon.so.18.1+0xbacd)
#27 0x000055cb5c9a8ab4 lld_main(int, char**, llvm::ToolContext const&) (/usr/bin/ld.lld+0x2ab4)
#28 0x000055cb5c9a82a5 main (/usr/bin/ld.lld+0x22a5)
#29 0x000071e34b839c88 (/usr/lib/libc.so.6+0x25c88)
#30 0x000071e34b839d4c __libc_start_main (/usr/lib/libc.so.6+0x25d4c)
#31 0x000055cb5c9a8305 _start (/usr/bin/ld.lld+0x2305)
make[2]: *** [scripts/Makefile.vmlinux_o:62: vmlinux.o] Error 134
make[1]: *** [/home/grimish/.build/linux-tkg/linux-src-git/Makefile:1143: vmlinux_o] Error 2
```

**Comment by dtcxzyw** [comment] 2024-07-12 09:28
Duplicate of #98301

**Closed** 2024-07-12 14:16 UTC
Labels: duplicate, backend:X86, incomplete, crash-on-valid, llvm:SelectionDAG
