### ISSUE TITLE
[C++20] [Modules] Non-exported definitions in C++ module interface partitions can conflict

### ISSUE THREAD

**Issue by rnikander** [llvm/llvm-project#61601] opened 2023-03-21 23:12 UTC
Is this a bug?

`Mod.cc`
```c++
export module TheMod;
export import :Part1;
export import :Part2;
```

`Part1.cc`
```c++
export module TheMod:Part1;
static int loog = 1;
```

`Part2.cc`
```c++
export module TheMod:Part2;
import :Part1;
static int loog = 2;
```

Error from Clang:

```console
Part2.cc:6:12: error: redefinition of 'loog'
static int loog = 2;
           ^
Part1.cc:4:12: note: previous definition is here
static int loog = 1;
```

Here is a simple build script to reproduce the error with the Clang I have currently (on macOS). I real life I run these experiments as part of a large CMake project, but this minimal script causes the same error:

`build.sh`
```sh
CXX="/Dev/llvm-project/build/bin/clang++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -std=c++2b"
set -e
$CXX -fprebuilt-module-path=. -x c++-module Part1.cc --precompile -o TheMod-Part1.pcm
$CXX -fprebuilt-module-path=. -x c++-module Part2.cc --precompile -o TheMod-Part2.pcm
```

**Comment by rnikander** [comment] 2023-03-21 23:19
Anonymous namespaces don't work either. They will get this to compile, as I wrote it above, but then if I'm *using* the symbol, that will fail with an error about an ambiguous reference.

**Comment by ChuanqiXu9** [comment] 2023-03-22 02:18
This should a bug/defect. I don't have a clear idea for how to fix this. Maybe you can only try to avoid renaming them temporarily.

**Comment by ChuanqiXu9** [comment] 2023-03-22 09:48
Sent https://reviews.llvm.org/D146614

**Comment by ChuanqiXu9** [comment] 2023-03-23 02:14
Thanks for the information. But maybe we can't fix this quickly since this may be related to https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1815r2.html. So we decide to take it carefully.

**Comment by rnikander** [comment] 2024-05-29 15:06
Does the C++ standard give enough information to implement this? In other words, are we waiting for an implementation, or for a clarification of the C++ specification?

**Comment by ChuanqiXu9** [comment] 2024-05-29 15:29
> Does the C++ standard give enough information to implement this? In other words, are we waiting for an implementation, or for a clarification of the C++ specification?
> 

yes, according to the standard, the reproducer should be accepted. 

And I forgot to update this, this should be implemented with (experimental) reduced bmi. Could you try to test that?

**Comment by rnikander** [comment] 2024-05-29 15:53
> And I forgot to update this, this should be implemented with (experimental) reduced bmi. Could you try to test that?

I will try this today or tomorrow and post back with an update. I've been using "two phase" builds, producing `.pcm` and then compiling those to `.o`. I should be able to change my build system without too much trouble, to produce the two `.pcm` files. I guess then I use the fat one for compiling to `.o` and the thin one for `-fmodule-file=name=file.pcm` flags.

**Comment by rnikander** [comment] 2024-05-29 19:24
@ChuanqiXu9 Do you think the reduced BMI is not compatible with the `std` module? I switched my build system to use the reduced BMI, and I got some new errors like: 

```
In module 'std' imported from ../../Views/ImageView.ixx:9:
/Users/rob/Dev/llvm-project/build_phase2_x86_macos/include/c++/v1/__algorithm/unwrap_range.h:65:12: error: no viable constructor or deduction guide for deduction of template arguments of 'pair'
   65 |     return pair{std::__unwrap_iter(std::move(__first)), std::__unwrap_iter(std::move(__last))};
      |            ^
/Users/rob/Dev/llvm-project/build_phase2_x86_macos/include/c++/v1/__algorithm/unwrap_range.h:76:45: note: in instantiation of member function 'std::__unwrap_range_impl<unsigned int *, unsigned int *>::__unwrap' requested here
   76 |   return __unwrap_range_impl<_Iter, _Sent>::__unwrap(std::move(__first), std::move(__last));
      |                                             ^
/Users/rob/Dev/llvm-project/build_phase2_x86_macos/include/c++/v1/__algorithm/copy_move_common.h:94:24: note: in instantiation of function template specialization 'std::__unwrap_range<unsigned int *, unsigned int *>' requested here
   94 |   auto __range  = std::__unwrap_range(__first, std::move(__last));
      |                        ^
/Users/rob/Dev/llvm-project/build_phase2_x86_macos/include/c++/v1/__algorithm/copy.h:109:15: note: in instantiation of function template specialization 'std::__copy_move_unwrap_iters<std::__copy_impl<std::_ClassicAlgPolicy>, unsigned int *, unsigned int *, unsigned int *, 0>' requested here
  109 |   return std::__copy_move_unwrap_iters<__copy_impl<_AlgPolicy> >(
      |               ^
/Users/rob/Dev/llvm-project/build_phase2_x86_macos/include/c++/v1/__algorithm/copy.h:116:15: note: in instantiation of function template specialization 'std::__copy<std::_ClassicAlgPolicy, unsigned int *, unsigned int *, unsigned int *>' requested here
  116 |   return std::__copy<_ClassicAlgPolicy>(__first, __last, __result).second;
      |               ^
../../Views/ImageView.ixx:193:14: note: in instantiation of function template specialization 'std::__nikander::copy<unsigned int *, unsigned int *>' requested here
  193 |         std::copy(idxs, idxs + 6, oidxs);
      |              ^
/Users/rob/Dev/llvm-project/build_phase2_x86_macos/include/c++/v1/__utility/pair.h:63:29: note: candidate function template not viable: requires 1 argument, but 2 were provided
   63 | struct _LIBCPP_TEMPLATE_VIS pair
      |                             ^~~~
```

Let me see if I can turn it off and go back to the full BMI, just for `std`.

**Comment by rnikander** [comment] 2024-05-29 19:45
I just changed my `-fmodule-file=std=std.pcm` arg to point to the full PCM instead of the reduced. I still get the error. Hmm. :| Let me know if it rings any bells. Otherwise I'm probably going back to just changing variable names to avoid the name conflicts.

**Comment by ChuanqiXu9** [comment] 2024-05-30 01:56
@rnikander it should be a bug. Please report them in seperate issues. This is somehow 'expected' since the reduced BMI is experimental so we may meet some bugs.

For the current issue, I think we can close it if reduced BMI can work for the reproducer.

BTW, glad to hear that there is a build system supporting 2 phase compilation. If your build system is publicly accessible, please register it in https://arewemodulesyet.org/tools/ to make the ecosystem better.

**Comment by rnikander** [comment] 2024-05-30 05:44
Yeah, reduced BMI works for the original reproducer, so I agree we can close this. I will file another report when I boil down this second problem.

My build system is not open source yet, but I'm thinking about it.

**Comment by ChuanqiXu9** [comment] 2024-05-30 05:50
> Yeah, reduced BMI works for the original reproducer, so I agree we can close this. I will file another report when I boil down this second problem.

Thanks. We think the reduced BMI will be the future direction. But it is somewhat fundamental change and we worry it breaks existing users so we marked it as experimental. However, we rarely receive bug reports about it.  The early testing feedbacks will be pretty helpful.

> 
> My build system is not open source yet, but I'm thinking about it.

Looking forward to it : )

**Closed by ChuanqiXu9** 2024-05-30 05:50 UTC
Labels: clang:modules
