### ISSUE TITLE
Clangs' frontend failed because file to compile had been changed during compilation

### ISSUE THREAD

**Issue by ii-sc** [llvm/llvm-project#89935] opened 2024-04-24 14:30 UTC
To whom it may concern: 

I was working on backend optimization and during a build process I made a change in file which was being compiled. 

```
clang++: error: unable to execute command: Segmentation fault (core dumped)
clang++: note: diagnostic msg: Error generating preprocessed source(s).
ninja: build stopped: subcommand failed.
```
Full stack trace and warnings that have been emitted only during this unsuccessful run are in the attached file.
[trace.txt](https://github.com/llvm/llvm-project/files/15095845/trace.txt)

**Comment by wangbyby** [comment] 2024-04-24 15:08
what's your input file and command?

**Comment by ii-sc** [comment] 2024-04-24 15:39
I was editing **llvm/lib/CodeGen/MachineCopyPropagation.cpp** file. I cannot send the exact state of the file because of the NDA, but I can assure you that there was only a C++ code. Moreover, the exact same file built successfully on the second run of the CMake. 

Command from CMake.
[Command-line.txt](https://github.com/llvm/llvm-project/files/15096594/Command-line.txt)

**Comment by shafik** [comment] 2024-04-25 01:01
Technically QoI issue but very low on the priority list, duplicate of: https://github.com/llvm/llvm-project/issues/64576

**Closed by shafik** 2024-04-25 01:01 UTC
Labels: clang:frontend, crash-on-invalid
