### ISSUE TITLE
[x86_64] va_arg will get wrong result in c++

### ISSUE THREAD

**Issue by CoTinker** [llvm/llvm-project#79790] opened 2024-01-29 07:05 UTC
demo.cpp
```
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

struct S271 { struct{}a; long long b; } ;
struct S271 s271;

void check271va (int z, ...) {
    struct S271 arg, *p;
    va_list ap;
    __builtin_va_start(ap, z);
    p = &s271;
    arg = __builtin_va_arg(ap, struct S271);
    if (p->b != arg.b) {
        printf("Fail!\n");
        printf("p->b:%lld , arg.b:%lld\n", p->b, arg.b);
    }
    __builtin_va_end(ap);
}

int main (void) {
    s271.b = 1;
    check271va (1, s271);
}
```
wrong output (clang) :
```
% clang++ demo.cpp
% ./a.out
Fail!
p->b:1 , arg.b:140726027523432
```
https://godbolt.org/z/7v6KEWGWT

**Comment by CoTinker** [comment] 2024-01-29 07:53
CC @hjl-tools @FreddyLeaf @phoebewang

**Comment by phoebewang** [comment] 2024-01-29 08:33
Is it a duplicate of https://github.com/llvm/llvm-project/issues/77036?

**Comment by CoTinker** [comment] 2024-01-30 01:37
No, they're not the same problem, they're just a little similar.#77036 is an independent empty structure.

**Comment by CoTinker** [comment] 2024-02-02 03:04
Does anyone have any idea on this issue?

**Comment by CoTinker** [comment] 2024-04-16 10:45
The actual structure layout is as follows:
```
(gdb) p &arg
$11 = (S271 *) 0x7fffffffe300
(gdb) x/2ug 0x7fffffffe300
0x7fffffffe300:  1       140726027523432
```

**Closed** 2024-08-13 03:35 UTC
Labels: backend:X86, miscompilation, ABI
