### ISSUE TITLE
[C++23] [Modules] module before include will have a "redefinition of concept" error

### ISSUE THREAD

**Issue by ncihnegn** [llvm/llvm-project#91111] opened 2024-05-05 07:27 UTC
Similar to #87609.

LLVM: 18.1.5
OS: macOS Sonoma 14.4.1
CPU: Apple M1

Demo: https://github.com/ncihnegn/cpp-modules-demo

```
[1/8] Scanning /Users/foobar/Temp/cpp-modules-demo/foo.cxx for CXX dependencies
[2/8] Scanning /Users/foobar/Temp/cpp-modules-demo/main.cxx for CXX dependencies
[3/8] Generating CXX dyndep file CMakeFiles/foo.dir/CXX.dd
[4/8] Generating CXX dyndep file CMakeFiles/hello.dir/CXX.dd
[5/8] Building CXX object CMakeFiles/foo.dir/foo.cxx.o
[6/8] Linking CXX static library libfoo.a
[7/8] Building CXX object CMakeFiles/hello.dir/main.cxx.o
FAILED: CMakeFiles/hello.dir/main.cxx.o 
/usr/local/Sither/Cellar/llvm/18.1.5/bin/clang++   -std=c++20 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -MD -MT CMakeFiles/hello.dir/main.cxx.o -MF CMakeFiles/hello.dir/main.cxx.o.d @CMakeFiles/hello.dir/main.cxx.o.modmap -o CMakeFiles/hello.dir/main.cxx.o -c /Users/foobar/Temp/cpp-modules-demo/main.cxx
In file included from /Users/foobar/Temp/cpp-modules-demo/main.cxx:3:
In file included from /Users/foobar/Temp/cpp-modules-demo/bar.h:4:
/usr/local/Sither/Cellar/llvm/18.1.5/bin/../include/c++/v1/optional:571:9: error: redefinition of concept '__is_derived_from_optional' with different template parameters or requirements
  571 | concept __is_derived_from_optional = requires(const _Tp& __t) { []<class _Up>(const optional<_Up>&) {}(__t); };
      |         ^
/Users/foobar/Temp/cpp-modules-demo/foo.cxx:3:10: note: '/usr/local/Sither/Cellar/llvm/18.1.5/bin/../include/c++/v1/optional' included multiple times, additional include site in header from module 'foo.<global>'
    3 | #include <optional>
      |          ^
/Users/foobar/Temp/cpp-modules-demo/foo.cxx:2:1: note: foo.<global> defined here
    2 | module;
      | ^
/Users/foobar/Temp/cpp-modules-demo/bar.h:4:10: note: '/usr/local/Sither/Cellar/llvm/18.1.5/bin/../include/c++/v1/optional' included multiple times, additional include site here
    4 | #include <optional>
      |          ^
In file included from /Users/foobar/Temp/cpp-modules-demo/main.cxx:3:
In file included from /Users/foobar/Temp/cpp-modules-demo/bar.h:4:
/usr/local/Sither/Cellar/llvm/18.1.5/bin/../include/c++/v1/optional:1240:13: error: use of undeclared identifier '__is_derived_from_optional'
 1240 |   requires(!__is_derived_from_optional<_Up>) && three_way_comparable_with<_Tp, _Up>
      |             ^
2 errors generated.
ninja: build stopped: subcommand failed.
```

**Comment by ChuanqiXu9** [comment] 2024-05-06 01:57
This looks similar with https://github.com/llvm/llvm-project/issues/87609. Have you tested on trunk?

**Comment by ChrisThrasher** [comment] 2024-05-06 02:17
I observed this same problem earlier today with the same OS and Clang version. I can confirm that Clang trunk fixes this problem!

**Comment by ChuanqiXu9** [comment] 2024-05-06 02:22
Thanks. Then I'd like to close the issue.

**Closed by ChuanqiXu9** 2024-05-06 02:22 UTC
Labels: clang:frontend, clang:modules

**Comment by neko-para** [comment] 2024-09-10 09:58
Sorry to bother, but I've met the same problem with clang 18.1.8 (which should already cover the trunk, according to the date of comment).

LLVM: 18.1.8 from MacPorts
OS: macOS Sonoma 14.5
CPU: Intel
CMake: 3.29.5

```c++
// info.cppm

module;

#include <future>
#include <map>

export module info;

export void func()
{
}

// main.cpp

import info;

#include <optional>
```

```shell
[build] /opt/local/bin/c++ -DNAPI_VERSION=8 -DNODE_ADDON_API_ENABLE_TYPE_CHECK_ON_AS -Dmaa_EXPORTS -I/Users/nekosu/Documents/Projects/MAA/maa-node/node_modules/node-api-headers/include -I/Users/nekosu/Documents/Projects/MAA/maa-node/node_modules/node-addon-api -isystem /Users/nekosu/Documents/Projects/MAA/maa-node/maa/include -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -g -std=gnu++20 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -fPIC -MD -MT CMakeFiles/maa.dir/src_new/main.cpp.o -MF CMakeFiles/maa.dir/src_new/main.cpp.o.d @CMakeFiles/maa.dir/src_new/main.cpp.o.modmap -o CMakeFiles/maa.dir/src_new/main.cpp.o -c /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp
[build] In file included from /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp:3:
[build] /opt/local/libexec/llvm-18/bin/../include/c++/v1/optional:571:9: error: redefinition of concept '__is_derived_from_optional' with different template parameters or requirements
[build]   571 | concept __is_derived_from_optional = requires(const _Tp& __t) { []<class _Up>(const optional<_Up>&) {}(__t); };
[build]       |         ^
[build] /opt/local/libexec/llvm-18/bin/../include/c++/v1/__ranges/movable_box.h:23:10: note: '/opt/local/libexec/llvm-18/bin/../include/c++/v1/optional' included multiple times, additional include site in header from module 'info.<global>'
[build]    23 | #include <optional>
[build]       |          ^
[build] /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/include/info.cppm:1:1: note: info.<global> defined here
[build]     1 | module;
[build]       | ^
[build] /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp:3:10: note: '/opt/local/libexec/llvm-18/bin/../include/c++/v1/optional' included multiple times, additional include site here
[build]     3 | #include <optional>
[build]       |          ^
[build] In file included from /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp:3:
[build] /opt/local/libexec/llvm-18/bin/../include/c++/v1/optional:1240:13: error: use of undeclared identifier '__is_derived_from_optional'
[build]  1240 |   requires(!__is_derived_from_optional<_Up>) && three_way_comparable_with<_Tp, _Up>
[build]       |             ^
[build] 2 errors generated.
[build] ninja: build stopped: subcommand failed.
```

```shell
nekosu@NEKOSULIAO-MC0 /Users/nekosu/Documents/Projects/MAA/maa-node % /opt/local/bin/c++ -v 
clang version 18.1.8
Target: x86_64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-18/bin
```

**Comment by ChuanqiXu9** [comment] 2024-09-11 01:48
> Sorry to bother, but I've met the same problem with clang 18.1.8 (which should already cover the trunk, according to the date of comment).
> 
> LLVM: 18.1.8 from MacPorts OS: macOS Sonoma 14.5 CPU: Intel CMake: 3.29.5
> 
> ```c++
> // info.cppm
> 
> module;
> 
> #include <future>
> #include <map>
> 
> export module info;
> 
> export void func()
> {
> }
> 
> // main.cpp
> 
> import info;
> 
> #include <optional>
> ```
> 
> ```shell
> [build] /opt/local/bin/c++ -DNAPI_VERSION=8 -DNODE_ADDON_API_ENABLE_TYPE_CHECK_ON_AS -Dmaa_EXPORTS -I/Users/nekosu/Documents/Projects/MAA/maa-node/node_modules/node-api-headers/include -I/Users/nekosu/Documents/Projects/MAA/maa-node/node_modules/node-addon-api -isystem /Users/nekosu/Documents/Projects/MAA/maa-node/maa/include -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -g -std=gnu++20 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -fPIC -MD -MT CMakeFiles/maa.dir/src_new/main.cpp.o -MF CMakeFiles/maa.dir/src_new/main.cpp.o.d @CMakeFiles/maa.dir/src_new/main.cpp.o.modmap -o CMakeFiles/maa.dir/src_new/main.cpp.o -c /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp
> [build] In file included from /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp:3:
> [build] /opt/local/libexec/llvm-18/bin/../include/c++/v1/optional:571:9: error: redefinition of concept '__is_derived_from_optional' with different template parameters or requirements
> [build]   571 | concept __is_derived_from_optional = requires(const _Tp& __t) { []<class _Up>(const optional<_Up>&) {}(__t); };
> [build]       |         ^
> [build] /opt/local/libexec/llvm-18/bin/../include/c++/v1/__ranges/movable_box.h:23:10: note: '/opt/local/libexec/llvm-18/bin/../include/c++/v1/optional' included multiple times, additional include site in header from module 'info.<global>'
> [build]    23 | #include <optional>
> [build]       |          ^
> [build] /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/include/info.cppm:1:1: note: info.<global> defined here
> [build]     1 | module;
> [build]       | ^
> [build] /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp:3:10: note: '/opt/local/libexec/llvm-18/bin/../include/c++/v1/optional' included multiple times, additional include site here
> [build]     3 | #include <optional>
> [build]       |          ^
> [build] In file included from /Users/nekosu/Documents/Projects/MAA/maa-node/src_new/main.cpp:3:
> [build] /opt/local/libexec/llvm-18/bin/../include/c++/v1/optional:1240:13: error: use of undeclared identifier '__is_derived_from_optional'
> [build]  1240 |   requires(!__is_derived_from_optional<_Up>) && three_way_comparable_with<_Tp, _Up>
> [build]       |             ^
> [build] 2 errors generated.
> [build] ninja: build stopped: subcommand failed.
> ```
> 
> ```shell
> nekosu@NEKOSULIAO-MC0 /Users/nekosu/Documents/Projects/MAA/maa-node % /opt/local/bin/c++ -v 
> clang version 18.1.8
> Target: x86_64-apple-darwin23.5.0
> Thread model: posix
> InstalledDir: /opt/local/libexec/llvm-18/bin
> ```

I took a quick check and it looks like the fix was not backported to 18.x. Would you like to test on trunk?

**Comment by neko-para** [comment] 2024-09-11 02:06
> I took a quick check and it looks like the fix was not backported to 18.x. Would you like to test on trunk?

I'll try it later, as building trunk does take quite a long time.
