### ISSUE TITLE
clang 16 -> 17 regression: "deduced return type cannot be used before it is defined"

### ISSUE THREAD

**Issue by helmesjo** [llvm/llvm-project#64029] opened 2023-07-22 10:54 UTC
See minimal reproducer [here (godbolt)](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIMwDMpK4AMngMmAByPgBGmMQgQQAOqAqETgwe3r7%2ByanpAmER0SxxCUF2mA4ZQgRMxARZPn6Btpj2jgK19QRFUbHxibZ1DU05rQojveH9pYMBAJS2qF7EyOwc5gHhyN5YANQmAW4AbvFpAkfYJhoAgls7e5iHx2gM60kEClc394GPXgORzcBAAnklMAB9AjEJiEb4Ba53B7vJ4vNxeRy0Qign7I5H/Kj7MBgLA0CLoCCQyHIJJJSHYmKQ/jEADu9XQDLwAGtMAtfsw2Aokkx1vtJuhfiYAOxWO77fYAekV%2BzcxEw%2BAIIH2CAIBCSChAysYADpaUl1VR4ox1mbUCxFazFebFZi6DjFSz2cROdjeb8FQRMCwkgYg8DdkwFAp9gAVUj7SPR/ZyPG3BUmACsVmzDAweAUoh9WYAIqXEwJJphVBb9kxMahzAA2Zv7L0crm8iCpswt3v7VQLfZ56sfAgBw6yicKt5VmvEfYxVCefYFyFMdD4Iw0ysEF4l/YgEASo9r2cESEnYFHk8gdUsVBnSGW63vKHj46xn6Io5y9MK1ciXPatawgG8CHQU8FAZE4xC8KEX3VN9L2BL9e2bK5%2BXlACZT/ACALwIDdxAhcIDXDct2AHcGEmLD/3whV1QIVYGEPY8IKPKNqMmCBB1/acAPaJQBPwpiWPFOpHGQGkow/NwexbRFeP5AI8Jw6Uy2whUhMwATcJEwCKxooN532MjoIo8IqPPOiGIAsTiFY8DIJAB8zjA9iXK489lJUtT8J0gzGMwZjHLY283MwZT%2BK0ydNP/GV4sSqVAlcQipTuIMQzDXTjjBCFBWeLiCATfLGFYZ5WUIBBoTTLw0iMfY/Xffd9iwXYyogW92x9TtcrcYqri6jiQHa2hYNoYEqoIGqP2wCAFkWmL7jucI9xYOEGAWqUp2w%2BqrP2MrWua2rXl3VdBGbBMqFoVAmDm5bkruDglloThM14PwOC0UhUE4NxrGscUVjWZ4th4UgtW%2Bl6lm5RIAhNAIkeRlGUabfROEkT7NF4P6OF4Q0NEhnGljgWAYEQFB7SSOh4nISg0BDWmEkjIwuCbDQiawE48HWAA1PBMFZAB5ArOAhmhaCDYhDQgGIcdIGJwnqUFxd4JXmGIUFhZibQqihiHGbYQRhYYWhVeh0gsBiLxgAG2haENbheCwDajHES38HVaozidn7qyqTENghtb2gVxlYS1jwsAVmE8BYNWlhuphgAUAWhdFxg1ZkQQRDEdgpBz%2BQlDUBXdC4fRDGMQHLH0PAYkNSAllQT4MidgBaCUjhLUxLGsMwfsfeJiDwLBG4WtoOgyFwGHcTxmj0UIZhKMo9BSNJOkyeecgr9eCgYPoV8GCvKmqLopjGPwT/afWaimQ%2BBgSE%2BL%2B3q/hh6B%2B5ifpYFBB9YJFeu9bGls8YDgABxNnbk2SQiYDCNXZiaDQiCzK4EICQQ4gQuALF4FDLQi1SAIEwBuQYE84aZiJm9DgWNSAJ3IaQL6g9OAExAETXBL1SBk0pisfUmJ6YQEZjTegxBIgVU4KoCBUCYGs2APsBBSD/aahIKPPQ/Bc6iHEIXVRxcVDqEtuXUgrJYRJEThjDgH16EKzxsLTESRMT7FQEScRkDoGwKrrIpsiDkEQA8EzIRGCAhYJwSTJYhDiEJAnpQ6htCiYMNxkw2wLDibQ3wXDJGiNUYZKRujShARgGMPxkkvBHCKacIgEgARzM%2BEVKESgOBVEYReAYNyK2mAeb80FiLMWzs%2BB0GlrLeWlsNYq2zkMrWOs9YOGzkbRgBBTbmwVtbW29tHbZ1dlXD2P0va319grAOyAg7Z1DpQn6EcVbRw2D9OOCdnZJwMKndOnSs7dK0XnDR0gtGKB0WXfwlcjAoBrjYRk49m6t0rJwTuEFu69ysJYAeuMzjEBHmPeAP8b5nz8BAVwl9F6z0/qvXe%2BRN7YoJRvDIeLj6T1vufHoxLKXou6A0clT936jFfnoSYH9l6PwAcsVY/8sGmPMbE36nBwHOKkXUsyDSmlDggKgogC5wbYMKTDUgqSEaZMyaYqJIA6HCrxsw1hJNinwDKSAbhtiSoUH4dTZmIi2BiIkS46RUriCNO5MqjUaCkUqNkK8gu7zZCfNLnon5himDGJuYKvJcSODWJ4XuBxYrJGuMahAaVHqzI%2BMEfEfxZhlVsPwaErA4TAFUN4NEixID4mExVSk%2BG6TNUo1Mbkqt%2BSgnJLLWYGNIqCmFqWAii4fhJBAA).

It works fine in Clang 16.0.0 (and older, tested back to 11.0), but fails in 17 (trunk).

**Comment by MitalAshok** [comment] 2023-07-22 21:58
This is broken by 0fd9c37d8cf20d1ee42263872ab2135265c3ac3d

It compiles with `-fno-builtin-std-forward_like`.

This is not a regression because your code has undefined behaviour (you modify the `std` namespace). To do these "polyfills" safely, you need to do something like this:

```c++
namespace my_namespace {
#ifdef __cpp_lib_forward_like
    using std::forward_like;
#else
    // your definition for forward_like
#endif
}
```

Though I do agree the given warning is confusing, and might be a sign that the implementation of the builtin wouldn't work with a conforming library implementation of `forward_like` (though [[forward]p8](https://wg21.link/forward#lib:forward_like) seems to say the return type is not `auto&&`)

**Comment by helmesjo** [comment] 2023-07-24 12:07
Thanks for the reply, and yes it's definitely UB but indeed the error message threw me off (I would expect it to complain about a redefinition). But then again, why isn't `__cpp_lib_forward_like` defined properly?

**Comment by CaseyCarter** [comment] 2023-09-07 21:33
Reopening for reconsideration because https://github.com/microsoft/STL/blob/f98b286a17e7c72e3fa10297868b877f9cdc0fa8/stl/inc/utility#L930-L949 is "the implementation" =)

We can workaround the issue, but we'd rather not muss our nicely clean implementation. Is there any chance you folks will address this regression?

**Comment by cor3ntin** [comment] 2023-09-07 22:00
@CaseyCarter Could you do something like libc++ ? https://github.com/llvm/llvm-project/blob/d5c6bd1ce9bb362904c79ff83196367b44ce51cb/libcxx/include/__utility/forward_like.h#L37 

The issue only affects implements who use type deduction in forward-like
And I think it would be a non-trivial fix.
As best we might be able to not replace the call if the declaration has a deduced type, but you would not get the perf benefits

@zygoloid did that work so maybe he would have a better idea!

**Comment by zygoloid** [comment] 2023-09-07 23:44
As part of treating `std::forward_like` as a builtin, we no longer instantiate its definition when it's used. This is an important optimization, at least for `std::forward` and `std::move` (and likely for `std::forward_like` once it starts being adopted more heavily). But that means that if the return type is deduced, then we don't have a body to deduce it against.

So, we could change Clang to accept this implementation of `forward_like`, by instantiating a definition anyway in the case where the return type is deduced. That'd accept the MSVC stdlib implementation, but would mean that you get slower compiles (and potentially larger object files and more debug information depending on whether we manage to avoid emitting anything about the instantiated template specialization or not). Or the MSVC implementation could add an explicit return type, and our optimization could continue to function. Or we could make this case even-more-builtin, and ignore the return type declared in the standard library entirely and work it out for ourselves (either only if it's deduced, or always).

**Comment by CaseyCarter** [comment] 2023-09-08 14:19
I was hoping for "even-more-builtin" as a best case, but I admit the marginal benefit over the current optimization would be small.  In any case, I've found a compromise that I think MSVC and Clang are equally happy with; let's close this issue again.

**Closed by CaseyCarter** 2023-09-08 14:19 UTC
Labels: clang:frontend, regression
