### ISSUE TITLE
C++20 coroutines: HALO regressed between clang 12 and 13

### ISSUE THREAD

**Issue by vogelsgesang** [llvm/llvm-project#56262] opened 2022-06-28 08:49 UTC
See https://godbolt.org/z/fjoK4aMKT for a self-contained example.

Clang 12 was still able to apply heap allocation elision on `-O2`.
Clang 13 is no longer able to apply heap allocation elision with `-O2` but instead requires `-O3`.
Also see https://stackoverflow.com/questions/71581531/halo-support-on-recent-compilers-for-c-coroutines/72770957

Not sure if this change was intentional, just wanted to bring it to your attention.

**Comment by vogelsgesang** [comment] 2022-06-28 08:50
@ChuanqiXu9 FYI, as I know you have a lot of knowledge on clang's coroutine implementation

**Comment by ChuanqiXu9** [comment] 2022-06-28 08:59
It is a regression change due to we enable new pass manager by default in 13: https://godbolt.org/z/c9csbhGjo
Thanks for reporting this. I'll take a look.

**Comment by ChuanqiXu9** [comment] 2022-06-29 07:43
This one should have been fixed in trunk: https://godbolt.org/z/q1aWx89hj

**Closed by ChuanqiXu9** 2022-06-29 07:43 UTC
Labels: llvm:optimizations

**Comment by vogelsgesang** [comment] 2022-06-29 09:06
Great! :) Thank you for looking into this!
