### ISSUE TITLE
clang may allocate exception thrown from a coroutine in place of another coroutine promise where both are allocated somewhere on the stack

### ISSUE THREAD

**Issue by cppdev123** [llvm/llvm-project#56455] opened 2022-07-09 19:08 UTC
I encountered this with clang-cl 14.0.6 on windows and it only happens under max speed optimizations (`/O2` for msvc) msvc never does this neither clang under other optimizations mode. I'm still trying to construct a minimal reproducible bug code but it is hard due to being an optimizer bug ! but I'll provide an explanatory code:

spawn function:
```cpp
        template<NonAwaitableFunctor<spawner&> Fn>
	auto scoped_spawn(any_executor& ex, Fn fn) -> task<std::invoke_result_t<Fn, spawner&>>
	{
		using fn_result = std::invoke_result_t<Fn, spawner&>;
		constexpr bool returns_void = std::is_same_v<fn_result, void>;
		using result_t = std::conditional_t<returns_void, std::monostate, fn_result>;

		spawner s{ ex };
		printf("coroutine fram ptr: %p\n", &s);
		std::optional<std::exception_ptr> ex_ptr;
		std::optional<result_t> result;
		
		try
		{
			if constexpr (returns_void)
			{
				printf("executing fn(s)\n");
				fn(s);
				printf("executed fn(s)\n");
			}
			else
			{
				result.emplace(fn(s));
			}
		}
		catch (const std::exception& ex) // ex instead of ... to see the the address
		{
			printf("caught an exception from fn(s): %p\n", std::addressof(ex));
			ex_ptr.emplace(std::current_exception());
			printf("stored an exception from fn(s)\n");
		}
		
		printf("waiting for spawner\n");
		co_await s.wait();
		printf("waited for spawner\n");
		if (ex_ptr)
			std::rethrow_exception(*ex_ptr);

		if constexpr (!returns_void)
			co_return std::move(*result);
	}
```

test:

```cpp
        task<> spawned_task(int inc, int& n)
	{
		n += inc;
		co_return;
	}

        task<> test_scoped_spawn(any_executor& ex)
        {
               int count = 0;
		auto throwing_fn = [&](spawner& s)
		{
			s.spawn(spawned_task(2, count)); // thrown exception is always 56 bytes after 
			s.spawn(spawned_task(3, count));
			s.spawn(spawned_task(5, count));
			throw std::exception{ "" };
		};
               TEST_THROW_EX(co_await scoped_spawn(ex, throwing_fn), std::exception, "scoped_spawn didn't propagate the exception");
		TEST_EQ(count, 10, "count", "10");
        }
```

sample output:

```console
main stack address: 000000C3E371F608 <= address of a variable in the first line in main test method
... skip some lines
coroutine fram ptr: 0000029164948D68
executing fn(s)
task(task&&: 000002916496AF88) coroutine(000000C3E371E448) promise(000000C3E371E458) <= allocated on the stack !!
task(task&&: 000002916496B7C8) coroutine(000000C3E371E3F8) promise(000000C3E371E408)
task(task&&: 000002916496B048) coroutine(000000C3E371E3A8) promise(000000C3E371E3B8)
caught an exception from fn(s): 000000C3E371E498 <= allocated on the stack near the first promise !!
stored an exception from fn(s)
waiting for spawner
await_ready : 3
await_suspend (0000029164948D90)
waiter address: 0000029164948D30
~await_suspend (0000029164948D90)
```

where does it crash ?
after coroutine is suspended in wait point the executor executes the three spawned coroutines I step in the debugger on calling `handle.resume()` of first task and the promise content in the debugger is invalid !! it seems to be overwritten by the exception data so when the coroutine resumes it causes random errors of access violation in very different addresses than code address !

I added a dummy reference to the promise in the destructor of the task with printf and it removes the issue also doing so in the task constructor used by the promise removes the issue and the exception is allocated in different memory !
 
I think the optimizer is thinking that the promise is not referenced anymore since the task isn't co_await ed but the handle is `resumed()` instead so it allocates the exception in place of it ??

**Comment by ChuanqiXu9** [comment] 2023-08-10 08:57
Would you like to provide a reproducer in godbolt?

**Comment by ChuanqiXu9** [comment] 2023-08-22 02:19
Oh, https://github.com/llvm/llvm-project/issues/56513 mentions it is a reproducer of the current issue. So this may be a duplicate of that. So I'll close this issue by duplication.

**Closed by ChuanqiXu9** 2023-08-22 02:19 UTC
Labels: duplicate, miscompilation, coroutines
