### ISSUE TITLE
[clang-format] Regression in indentation of a class within namespace and definition of a member function

### ISSUE THREAD

**Issue by tupos** [llvm/llvm-project#58464] opened 2022-10-19 08:27 UTC
Hello,

The following code snippet is incorrectly indented with the latest `llvmorg-15.0.2` git tag

```cpp
namespace A
{
    class Foo
    {
        void bar() const;
    };
}

void A::Foo::bar() const
{
    auto x = 5;
}
```
If I intend to reformat only the definition of the member function `bar` with the command
```shell
clang-format --style="Mozilla" --lines=8:12 test.cpp
```
the `auto x = 5;` will be indented with 8 spaces with `llvmorg-15.0.2` version. However with the version of 13.0.1 it is correctly indented with only 2 spaces.

With best regards,

**Comment by Sedeniono** [comment] 2023-05-10 18:36
I did a `git bisect` and found that it is a regression introduced in 14c30c70c4595d8f410c74a72357a5a31fdd5507 (#56352). Hence, this issue here is a duplicate of #59178. I posted more information [there](https://github.com/llvm/llvm-project/issues/59178#issuecomment-1542637781).

**Closed** 2023-05-24 02:40 UTC
Labels: clang-format
