### ISSUE TITLE
clang-format breaks comment integrity with SpacesInLineCommentPrefix

### ISSUE THREAD

**Issue by Sam0523** [llvm/llvm-project#52649] opened 2021-12-13 07:56 UTC
`.clang-format`:

```yaml
---
SpacesInLineCommentPrefix:
  Minimum:         1
  Maximum:         1
---
```
`input.cpp`:

```cpp
int main()
{
  //            loooooooooooooooooooooooooooooong commentcomments
  // normal comments

  {
    {
      //     std::string str = "Commented out";
      // std::string str2 = "Commented out too";
    }
  }

  return 0;
}
```

Format result with clang-format 13.0.0:

```cpp
int main() {
  // loooooooooooooooooooooooooooooong commentcomnormal comments

  {
    {
      // std::string str = "Commented out";
     std::string str2 = "Commented out too";
    }
  }

  return 0;
}
```

As you saw, the second lines of comments eats beyond prefix spaces.

result with git main build:

```
clang-format: <HOME>/llvm-project/clang/lib/Format/WhitespaceManager.cpp:123: void clang::format::WhitespaceManager::calculateLineBreakInformation(): Assertion `PreviousOriginalWhitespaceEndOffset <= OriginalWhitespaceStartOffset' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: <HOME>/llvm-project/build/bin/clang-format test.cpp
 #0 0x000055c5c76f1a7b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (.localalias) <HOME>/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:22
 #1 0x000055c5c76f1b32 PrintStackTraceSignalHandler(void*) <HOME>/llvm-project/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x000055c5c76efb27 llvm::sys::RunSignalHandlers() (.localalias) <HOME>/llvm-project/llvm/lib/Support/Signals.cpp:96:20
 #3 0x000055c5c76f14ce SignalHandler(int) <HOME>/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f612796a140 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14140)
 #5 0x00007f6127472ce1 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007f612745c537 abort ./stdlib/abort.c:81:7
 #7 0x00007f612745c40f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #8 0x00007f612745c40f _nl_load_domain ./intl/loadmsgcat.c:970:34
 #9 0x00007f612746b662 (/lib/x86_64-linux-gnu/libc.so.6+0x34662)
#10 0x000055c5c78004bd clang::format::WhitespaceManager::calculateLineBreakInformation() (.localalias) <HOME>/llvm-project/clang/lib/Format/WhitespaceManager.cpp:126:9
#11 0x000055c5c780031c clang::format::WhitespaceManager::generateReplacements() <HOME>/llvm-project/clang/lib/Format/WhitespaceManager.cpp:98:25
#12 0x000055c5c7771599 clang::format::(anonymous namespace)::Formatter::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) <HOME>/llvm-project/clang/lib/Format/Format.cpp:1860:59
#13 0x000055c5c77bb351 clang::format::TokenAnalyzer::process() <HOME>/llvm-project/clang/lib/Format/TokenAnalyzer.cpp:128:5
#14 0x000055c5c7776669 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda3'(clang::format::Environment const&)::operator()(clang::format::Environment const&) const <HOME>/llvm-project/clang/lib/Format/Format.cpp:3060:12
#15 0x000055c5c777f10a std::pair<clang::tooling::Replacements, unsigned int> std::__invoke_impl<std::pair<clang::tooling::Replacements, unsigned int>, clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda3'(clang::format::Environment const&)&, clang::format::Environment const&>(std::__invoke_other, clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda3'(clang::format::Environment const&)&, clang::format::Environment const&) /usr/include/c++/10/bits/invoke.h:60:70
#16 0x000055c5c777da01 _ZSt10__invoke_rISt4pairIN5clang7tooling12ReplacementsEjERZNS1_6format8internal8reformatERKNS5_11FormatStyleEN4llvm9StringRefENSA_8ArrayRefINS2_5RangeEEEjjjSB_PNS5_23FormattingAttemptStatusEEUlRKNS5_11EnvironmentEE3_JSJ_EENSt9enable_ifIXsrSt6__and_IJSt6__not_ISt7is_voidIT_EESt14is_convertibleINSt15__invoke_resultIT0_JDpT1_EE4typeESQ_EEE5valueESQ_E4typeEOSV_DpOSW_ /usr/include/c++/10/bits/invoke.h:143:5
#17 0x000055c5c777c9b0 std::_Function_handler<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&), clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::'lambda3'(clang::format::Environment const&)>::_M_invoke(std::_Any_data const&, clang::format::Environment const&) /usr/include/c++/10/bits/std_function.h:293:7
#18 0x000055c5c778f397 std::function<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&)>::operator()(clang::format::Environment const&) const /usr/include/c++/10/bits/std_function.h:623:5
#19 0x000055c5c7776fa4 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) (.localalias) <HOME>/llvm-project/clang/lib/Format/Format.cpp:3079:49
#20 0x000055c5c77772fd clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) (.localalias) <HOME>/llvm-project/clang/lib/Format/Format.cpp:3106:68
#21 0x000055c5c76120c1 clang::format::format(llvm::StringRef) <HOME>/llvm-project/clang/tools/clang-format/ClangFormat.cpp:480:76
#22 0x000055c5c7612f40 main <HOME>/llvm-project/clang/tools/clang-format/ClangFormat.cpp:614:11
#23 0x00007f612745dd0a __libc_start_main ./csu/../csu/libc-start.c:308:16
#24 0x000055c5c76100aa _start (<HOME>/llvm-project/build/bin/clang-format+0x3be0aa)
```

**Comment by mydeveloperday** [comment] 2021-12-13 10:47
This issue is still valid in the current main version (14), reproducible with just

```
void foo()
{
  //            loooooooooooooooooooooooooooooong commentcomments
  // normal comments
}
```

**Comment by mydeveloperday** [comment] 2021-12-13 10:47
Assertion failed: PreviousOriginalWhitespaceEndOffset <= OriginalWhitespaceStartOffset, file C:\cygwin64\buildareas\llvm3\llvm-project\clang\lib\Format\WhitespaceManager.cpp, line 124

**Comment by HazardyKnusperkeks** [comment] 2022-02-16 11:37
Should be fixed by https://reviews.llvm.org/D119680

**Comment by mkurdej** [comment] 2022-02-16 12:23
Indeed. It's fixed. I'll add a test case though and close it then.

**Comment by mkurdej** [comment] 2022-02-16 12:24
```
clang-format-main-20220212-7d5062c6.exe --style=file test.cpp
void foo() {
  // loooooooooooooooooooooooooooooong commentcommnormal comments
}

clang-format-main-20220214-e967d97a.exe --style=file test.cpp
void foo() {
  // loooooooooooooooooooooooooooooong commentcomments
  // normal comments
}
```

**Comment by mkurdej** [comment] 2022-02-16 12:31
Duplicate of #53799.

**Closed** 2022-02-16 12:55 UTC
Labels: bug, duplicate, clang-format
