### ISSUE TITLE
P1224: A Standard flat_set

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#99664] opened 2024-07-19 16:50 UTC
Specified by https://eel.is/c++draft/flat.set.

**Comment by ldionne** [comment] 2024-07-19 21:14
@huixie90 Has already started on this paper, so re-assigning to avoid work duplication. I would suggest looking at `inplace_vector` for another container that we don't implement yet.

**Comment by ldionne** [comment] 2024-10-02 17:17
Closing as a duplicate of the "official paper tracking issue" here: https://github.com/llvm/llvm-project/issues/105193

There's no difference other than the other issue was created via my scripts and added to the Conformance Table, and this one wasn't.

**Closed by ldionne** 2024-10-02 17:17 UTC
Labels: libc++, c++23
