### ISSUE TITLE
ICE in backend: Instruction Combining seems stuck in an infinite loop after 100 iterations

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [llvm/llvm-project#51139] opened 2021-09-08 18:56 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51797](https://llvm.org/bz51797) |
| Version | trunk |
| OS | Linux |
| CC | @dbabokin,@RKSimon,@regehr,@Vsevolod-Livinskij |

## Extended Description 
Reproducer:
```c
extern int var_23, var_24;
void test(unsigned char a, unsigned short b, unsigned char c,
          signed char d[][24][10][13]) {
    for (int e = 0; e < 2; e = 2) {
#pragma clang loop unroll(enable)
        for (short f = 0; f < 24; f += 4)
            for (char g = 0; g < 10; g += 2)
                for (int h = 0; h < 13; h += 2) {
                    var_23 = b ? 0 : d[0][4][g][h];
                    var_24 = d[e][4][g][h];
                }
        for (; c < a;)
            ;
    }
}
```
Error:
```
>$ clang++ -O3 -c func.cpp
fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 100 iterations.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.  Program arguments: clang++ -O3 -c func.cpp
1.  <eof> parser at end of file
2.  Optimizer
 #0 0x000055c560730bf4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055c56072e9f4 llvm::sys::CleanupOnSignal(unsigned long) (/testing/llvm/bin/bin/clang-14+0x243d9f4)
 #2 0x000055c560676463 llvm::CrashRecoveryContext::HandleExit(int) (/testing/llvm/bin/bin/clang-14+0x2385463)
 #3 0x000055c560726642 llvm::sys::Process::Exit(int, bool) (/testing/llvm/bin/bin/clang-14+0x2435642)
 #4 0x000055c55f21d0c7 LLVMErrorHandler(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) cc1_main.cpp:0:0
 #5 0x000055c56067e31c llvm::report_fatal_error(llvm::Twine const&, bool) (/testing/llvm/bin/bin/clang-14+0x238d31c)
 #6 0x000055c5601059ad combineInstructionsOverFunction(llvm::Function&, llvm::InstCombineWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::ProfileSummaryInfo*, unsigned int, llvm::LoopInfo*) InstructionCombining.cpp:0:0
 #7 0x000055c560106401 llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/testing/llvm/bin/bin/clang-14+0x1e15401)
 #8 0x000055c56192b136 llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/testing/llvm/bin/bin/clang-14+0x363a136)
 #9 0x000055c55ff397e6 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/testing/llvm/bin/bin/clang-14+0x1c487e6)
#10 0x000055c560a53b56 llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/testing/llvm/bin/bin/clang-14+0x2762b56)
#11 0x000055c563c6d47f llvm::CGSCCToFunctionPassAdaptor::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/testing/llvm/bin/bin/clang-14+0x597c47f)
#12 0x000055c561c93de6 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::CGSCCToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/testing/llvm/bin/bin/clang-14+0x39a2de6)
#13 0x000055c563c6519b llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/testing/llvm/bin/bin/clang-14+0x597419b)
#14 0x000055c5600613e6 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/testing/llvm/bin/bin/clang-14+0x1d703e6)
#15 0x000055c563c69024 llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/testing/llvm/bin/bin/clang-14+0x5978024)
#16 0x000055c560061396 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::DevirtSCCRepeatedPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) (/testing/llvm/bin/bin/clang-14+0x1d70396)
#17 0x000055c563c66cf3 llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/testing/llvm/bin/bin/clang-14+0x5975cf3)
#18 0x000055c560061436 llvm::detail::PassModel<llvm::Module, llvm::ModuleToPostOrderCGSCCPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/testing/llvm/bin/bin/clang-14+0x1d70436)
#19 0x000055c55ff35d1f llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/testing/llvm/bin/bin/clang-14+0x1c44d1f)
#20 0x000055c560064941 llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/testing/llvm/bin/bin/clang-14+0x1d73941)
#21 0x000055c56192b376 llvm::detail::PassModel<llvm::Module, llvm::ModuleInlinerWrapperPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/testing/llvm/bin/bin/clang-14+0x363a376)
#22 0x000055c55ff35d1f llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/testing/llvm/bin/bin/clang-14+0x1c44d1f)
#23 0x000055c560a64e76 (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) BackendUtil.cpp:0:0
#24 0x000055c560a6a135 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/testing/llvm/bin/bin/clang-14+0x2779135)
#25 0x000055c5618a8c6f clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/testing/llvm/bin/bin/clang-14+0x35b7c6f)
#26 0x000055c562a00a79 clang::ParseAST(clang::Sema&, bool, bool) (/testing/llvm/bin/bin/clang-14+0x470fa79)
#27 0x000055c5618a77a8 clang::CodeGenAction::ExecuteAction() (/testing/llvm/bin/bin/clang-14+0x35b67a8)
#28 0x000055c561166659 clang::FrontendAction::Execute() (/testing/llvm/bin/bin/clang-14+0x2e75659)
#29 0x000055c5610f7ade clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/testing/llvm/bin/bin/clang-14+0x2e06ade)
#30 0x000055c561246620 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/testing/llvm/bin/bin/clang-14+0x2f55620)
#31 0x000055c55f21e1b7 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/testing/llvm/bin/bin/clang-14+0xf2d1b7)
#32 0x000055c55f21a658 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#33 0x000055c560f81329 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#34 0x000055c56067632c llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/testing/llvm/bin/bin/clang-14+0x238532c)
#35 0x000055c560f81a3d clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.0) Job.cpp:0:0
#36 0x000055c560f53c8b clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/testing/llvm/bin/bin/clang-14+0x2c62c8b)
#37 0x000055c560f54799 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/testing/llvm/bin/bin/clang-14+0x2c63799)
#38 0x000055c560f5f899 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/testing/llvm/bin/bin/clang-14+0x2c6e899)
#39 0x000055c55f194a86 main (/testing/llvm/bin/bin/clang-14+0xea3a86)
#40 0x00007fbaf23810b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#41 0x000055c55f21a1ce _start (/testing/llvm/bin/bin/clang-14+0xf291ce)
clang-14: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 14.0.0 (https://github.com/llvm/llvm-project.git dfc46f02681447370a1ccbe340034e970bc7e572)
Target: x86_64-unknown-linux-gnu
Thread model: posix

LLVM version:
clang version 14.0.0 (https://github.com/llvm/llvm-project.git dfc46f02681447370a1ccbe340034e970bc7e572)
```

**Comment by JonPsson** [comment] 2021-12-15 16:29
Still here:

opt -mtriple=systemz-unknown -mcpu=z15 -O3 ./tc_crash1_aftercreduce.ll

LLVM ERROR: Instruction Combining seems stuck in an infinite loop after 100 iterations.


[tc_crash1_aftercreduce.zip](https://github.com/llvm/llvm-project/files/7721096/tc_crash1_aftercreduce.zip)

**Comment by RKSimon** [comment] 2021-12-15 17:02
CC'ing @rotateright

**Comment by fhahn** [comment] 2022-05-20 13:30
IR reproducer: https://godbolt.org/z/j5G8P9Pvx

With the default limit I wasn't able to reduce this further, at the moment it needs ~2k lines IR. Looks like this may be related to store merging.

**Comment by fhahn** [comment] 2022-05-20 13:38
This doesn't look like an infinite loop, just a lot of IR where in each iteration we perform a small simplification that unlocks further small simplifications. It passes with `-instcombine-infinite-loop-threshold=101`.

**Comment by rotateright** [comment] 2022-05-20 14:11
I didn't check if this one has stores, and I still don't know how to fix these, but here are possible duplicates:
- [ ] #46688
- [ ] #47132
- [ ] #48466
- [ ] #49014

**Comment by msebor** [comment] 2022-08-25 18:05
Based on the test case (both the original and the IR one in the [comment above](https://github.com/llvm/llvm-project/issues/51139#issuecomment-1132904801)) this does seem like the store merging problem behind the issues above.  Would it make sense to resolve these as duplicates to keep them from cluttering searches?

(Interestingly the original test case compiles successfully in C mode.)

**Comment by rotateright** [comment] 2022-08-26 13:57
I have no problem with closing bugs as duplicates. In bugzilla, we could use duplicates as a signal for frequency/importance of a bug, but I'm not sure how to do that with github issues.

**Comment by nikic** [comment] 2023-09-26 09:45
IR reproducer no longer reproduces. Fixed as part of the single-iteration InstCombine work.

**Closed by nikic** 2023-09-26 09:45 UTC
Labels: backend:SystemZ, bugzilla, llvm:crash, llvm:instcombine
