### ISSUE TITLE
Error thrown while compiling lib/Transforms/Scalar/FPG.cpp with clang++

### ISSUE THREAD

**Issue by BalaRishi-AMD** [llvm/llvm-project#57060] opened 2022-08-10 17:40 UTC
The below error is faced while building llvm (during compilation of llvm-project/llvm/lib/Transforms/Scalar/FPG.cpp) using llvm:
/home/amd/llvm-project/llvm/lib/Transforms/Scalar/FPG.cpp:1991:88: error: expected '{' after '\N' escape sequence

This issue was **introduced between 2022-06-21 and 2022-06-30.**

Reduced issue reproducer is given below:

_$ cat hello.cpp_
#include <iostream>
int main() {
    std::cout << "Hello \N \n";
    return 0;
}

_$ $compilerspath/DT2022_06_21/bin/clang++  hello.cpp  && ./a.out_
hello.cpp:3:25: warning: unknown escape sequence '\N' [-Wunknown-escape-sequence]
    std::cout << "Hello \N \n";
                        ^~
1 warning generated.
Hello N

## The above is older llvm build. The below is a recent one

_$ $compilerspath/DT2022_06_30/bin/clang++  hello.cpp  && ./a.out_
**hello.cpp:3:25: error: expected '{' after '\N' escape sequence**
    std::cout << "Hello \N \n";
                        ^~
1 error generated.

**Comment by efriedma-quic** [comment] 2022-08-10 21:12
Looks like https://reviews.llvm.org/D123064 .  I think this is expected?  CC @cor3ntin @tahonermann .

(llvm/lib/Transforms/Scalar/FPG.cpp does not exist in upstream LLVM.)

**Comment by cor3ntin** [comment] 2022-08-10 21:24
Yes, this is expected.
Clang (unfortunately?) replaces unknown escape sequences by the escaped character, which can lead to surprises when new escape sequences are introduced. in this case `\N{...}`

In this case, `\N` can be replaced by `N` with no change in behavior.
Which brings the question of whether `\N` in the original code was intended or perhaps the author meant `\n` - as escaping had no special meaning in - as far as we know - any compiler

**Comment by fhahn** [comment] 2022-08-11 09:37
IIUC this can be closed as per @cor3ntin comment as working as expected. If that's incorrect, please re-open with additional info.

**Closed by fhahn** 2022-08-11 09:37 UTC
Labels: clang:frontend

**Comment by BalaRishi-AMD** [comment] 2022-08-11 10:01
**Thank you all for clarifying behaviour.**
