### ISSUE TITLE
Missed optimization with inline assembly (chooses memory over register)

### ISSUE THREAD

**Issue by geometrian** [llvm/llvm-project#80528] opened 2024-02-03 05:38 UTC
Consider the following simple example:
```cpp
//Compile with "clang -O3 -masm=intel"

#include <stdint.h>

union A_sRGB { struct { uint8_t a, r,g,b; }; uint32_t packed; };
union sRGB_A { struct { uint8_t r,g,b, a; }; uint32_t packed; };

A_sRGB rgba_to_argb( sRGB_A srgba ) {
	// R, G, B, A   ->   A, R, G, B
	A_sRGB ret;
	asm(
		"rorx   %0,%1, 24\n"
		: "=r"(ret.packed)
		: "rm"(srgba.packed)
		:
	);
	return ret;
}
```
As written, this will produce:
```x86asm
rgba_to_argb(sRGB_A):                # @rgba_to_argb(sRGB_A)
        mov     dword ptr [rsp - 4], edi
        rorx    eax, dword ptr [rsp - 4], 24
        ret
```
I.e., there is a pointless save / load of `edi` on the stack.

It comes down to the constraint on the input, `"rm"(srgba.packed)`. This says that either a register or a memory location is allowed. It seems that if the "m" is present, clang will always choose it over the register—even when it has to get the value *out* of the register and into memory to do it. This is a weird pessimization.

FWIW, GCC does not make this mistake, and compiles to the right answer:
```x86asm
rgba_to_argb(sRGB_A):
        rorx   eax,edi, 24
        ret
```

**Comment by topperc** [comment] 2024-02-03 05:49
CC @nickdesaulniers

**Comment by nickdesaulniers** [comment] 2024-02-05 10:32
Thanks for the report; duplicate of #20571.

**Closed by nickdesaulniers** 2024-02-05 10:32 UTC
Labels: duplicate, llvm:optimizations, missed-optimization
