### ISSUE TITLE
Codegen regression for AArch64 Android Kernel

### ISSUE THREAD

**Issue by Gelbpunkt** [llvm/llvm-project#54628] opened 2022-03-29 22:17 UTC
## Preamble

Hi there,

first off I would like to mention that I have no clue what info might be useful to the LLVM developers to assist in fixing this issue, I tried my best to track it down for you as much as possible, but I know nothing about LLVM internals, kernel internals or Xiaomi's bootloader.

## The Problem

We have a modified Android kernel (repository: https://github.com/DavinciCodeOS/msm-4.14) for the Xiaomi Mi 9T. For building it, we use a LLVM-only toolchain (aka clang, lld, llvm-*).

For building it we initially used Google's "14.0.1" clang prebuilt (https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/tags/ndk-r25-beta2/clang-r437112b/clang_source_info.md), based on LLVM 79d58b4d3017d159bf09a77398c9a116128de193. **This one builds the kernel, and it boots fine.**

Switching to a newer toolchain, Google's "14.0.2" clang prebuilt (https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/tags/ndk-r25-beta2/clang-r445002/clang_source_info.md), based on LLVM 18308e171b5b1dd99627a4d88c7d6c5ff21b8c96, results in **kernel building, but not booting**.

Since the bootloader is proprietary and we have no insight in its logs, we don't know what was wrong. kmesg in recovery is also empty, indicating that a kernel was never booted, instead the bootloader straight up rejected the kernel, even though all we did was use a newer compiler.

## Tracking it down

I was certain that this is a bug in LLVM, and decided to manually bisect it down to a single commit by building specific revisions of LLVM (using ClangBuiltLinux' tc-build with a Dockerfile for reproducible builds: https://github.com/DavinciCodeOS/tc-build) and checking whether a kernel built by this revision of LLVM booted. Here's the results:

- 79d58b4d3017d159bf09a77398c9a116128de193 (Sep 3, 2021): GOOD
- 1f0bc617bdd11a4f3b0d820603b0089f81aca79b (Sep 30, 2021): GOOD
- a944f801cacdaa40b3869986844a6ffa08b87c19 (Oct 3, 2021): GOOD
- f38cbd785985be73be0d0129781d929e55abffb1 (Oct 4, 2021): GOOD
- c4dd0fe4b3709d4603df34f89b25cc03c1c5060d (Oct 4, 2021): GOOD
- 8b3d944a97cc944a24ed1296c801da5654896092 (Oct 4, 2021): GOOD
- 993555beb8ff33aa35773af01cb3821ae45e6e39 (Oct 4, 2021): GOOD
- 0f0e31cf511def3e92244e615b2646c1fd0df0cd (Oct 4, 2021): BAD (Only 3 commits in between, this is the only code change, other ones are doc & test)
- 6f80339b18da61be986e75b4824ff5b308412ead (Oct 4, 2021): BAD
- 7f28b4d5b7a5f3581dbdba0ee8936b519034ae65 (Oct 4, 2021): BAD
- c800119c46fb266b7fc75409fd9cbbb1a6d8f72a (Oct 5, 2021): BAD
- bbf4b3dbbe3bfaeecdff2a29ed49da172895d82c (Oct 9, 2021): BAD
- 239b4d62b6c07f27b1763a090f82c9f92ce06b8c (Oct 18, 2021): BAD
- 18308e171b5b1dd99627a4d88c7d6c5ff21b8c96 (Nov 30, 2021): BAD

I was able to narrow it down between two commits: a working one and a broken one, so the ones that might cause the breakage are these: https://github.com/llvm/llvm-project/compare/993555beb8ff33aa35773af01cb3821ae45e6e39...0f0e31cf511def3e92244e615b2646c1fd0df0cd. One of these two is a typo fix, the other one does not boot, indicating that  0f0e31cf511def3e92244e615b2646c1fd0df0cd is the commit that started the regression.

Latest clang 15 dev versions still have this issue.

## Figuring what is wrong

As I said, I don't know much C nor do I know the kernel or LLVM internally. From what I see, this commit changed `gnu_inline`, which only appears in the kernel tree once in a relevant place:

```
[adrian@lillia msm-4.14]$ grep -Rn "gnu_inline" .
./Documentation/trace/tracepoint-analysis.txt:307:         :      extern __inline void __attribute__((__gnu_inline__, __always_inline__, _
./include/linux/compiler-gcc.h:69: * Feature detection for gnu_inline (gnu89 extern inline semantics). Either
./include/linux/compiler-gcc.h:75:# define __gnu_inline    __attribute__((gnu_inline))
./include/linux/compiler-gcc.h:77:# define __gnu_inline
./include/linux/compiler-gcc.h:81: * Prefer gnu_inline, so that extern inline functions do not emit an
./include/linux/compiler-gcc.h:87:#define inline inline        __attribute__((unused)) notrace __gnu_inline
./include/linux/string.h:235:#define __FORTIFY_INLINE extern __always_inline __attribute__((gnu_inline))
```

The line in string.h has not been touched in a rather long time and still exists in 5.17+ upstream kernels, so from my perspective the issue should not be related to our changes, but I am unsure about that.

I wanted to try and compare the binary diff of the two compiler's build artifacts, but did not get anywhere with that.

I have all 13 toolchains that I used and compiled on my disk, so if those are needed for comparison, I can xz them and upload them somewhere.

**Comment by serge-sans-paille** [comment] 2022-03-30 08:13
Thanks @Gelbpunkt for the detailed error report. The change implied by commit https://github.com/llvm/llvm-project/commit/0f0e31cf511def3e92244e615b2646c1fd0df0cd basically means that we're now using the user-provided version of some builtins instead of the default builtin, which is needed for fortify source. So the error may as well be a compiler error or an error in the original source that was ignored before.

> I wanted to try and compare the binary diff of the two compiler's build artifacts, but did not get anywhere with that.

That's unfortunate. Taking a diff between the two binaries would help understanding what happens. 

If I understand correctly, you cannot share the source, so I cannot reproduce. Here is what I would do:

1. compile some CU with a working clang, and some with the failing version, bisecting until you end up with a single CI compiled with the failing version
2. take the diff of the .ll files generated by the working and failing compiler for that particular CU
3. share the result here.

Does that sound reasonable to you?

**Comment by Gelbpunkt** [comment] 2022-03-30 15:45
I didn't expect such a fast reply, thank you!

> If I understand correctly, you cannot share the source, so I cannot reproduce.

I am sorry for not making this clear: The source for the Kernel I am building can be found at https://github.com/DavinciCodeOS/msm-4.14. I am building with `LLVM=1` and `LLVM_IAS=1` to ensure that no binutils/gcc parts are used.

Sorry for being such a noob - I don't really know what you mean with "CU" and "CI" in this context, could you elaborate on that, please?

My attempt at a binary diff was mostly meaningless because `diff -r working-kernel-artifacts/ broken-kernel-artifacts/` showed too many modified files (I am guessing due to some compiler signature in almost all files, at least grepping for the commit hash of LLVM yields a result in almost every file, and since the hash changed I guess the files did too). I have a git-generated diff that  I attached as `kernel.txt`, which might help find initial traces.

I am guessing that a LLVM IR of the entire kernel tree would be much more useful, but I can't really figure how to compile the kernel with clang and additionally create `.ll` files - `-S -emit-llvm` seems to make it not build the binaries themselves.

I will try following along with https://github.com/ClangBuiltLinux/linux/issues/513 to get those built, but wanted to keep you updated even before I attempt that.

Cheers!

[kernel.txt](https://github.com/llvm/llvm-project/files/8381971/kernel.txt)

**Comment by nathanchance** [comment] 2022-03-30 17:06
@Gelbpunkt Could you try disabling `CONFIG_FORTIFY_SOURCE`? It is known to be broken for `clang` and it is only fixed in more recent kernels:

https://git.kernel.org/linus/a52f8a59aef46b59753e583bf4b28fccb069ce64

https://git.kernel.org/linus/281d0c962752fb40866dd8d4cade68656f34bd1f

**Comment by nathanchance** [comment] 2022-03-30 17:07
cc @nickdesaulniers

**Comment by xNombre** [comment] 2022-03-30 17:29
Hello @nathanchance thanks for your suggestion!

I can confirm that after disabling `CONFIG_FORTIFY_SOURCE` phone booted, both with clang 14.0.2 and 15 dev branch.

**Comment by xNombre** [comment] 2022-03-30 17:50
Thats a good idea. I see that CAF enables `CONFIG_FORTIFY_SOURCE` by default https://source.codeaurora.org/quic/la/kernel/msm-4.14/tree/arch/arm64/configs/vendor/sm8150-perf_defconfig?h=LA.UM.9.1.r1-11700-SMxxx0.0#n721.

As everyone is slowly moving towards updated clang more complaints regarding this issue will come up. Fixing it once and for all would be best option.

**Comment by Gelbpunkt** [comment] 2022-03-30 18:18
I managed to compile the LLVM IR for the kernel files using the method described above (https://github.com/ClangBuiltLinux/linux/issues/513), and generated a diff for the LLVM IR files generated by 993555beb8ff33aa35773af01cb3821ae45e6e39 (base) and 0f0e31cf511def3e92244e615b2646c1fd0df0cd (compared to).

It's 145MB, mainly because of minor changes like 
```diff
-  %5 = call i32 @crypto_register_aead(%struct.aead_alg* nonnull @ccm_aes_alg) #10
+  %5 = call i32 @crypto_register_aead(%struct.aead_alg* nonnull @ccm_aes_alg) #9
```
but I hope it will be of use nonetheless.

Due to the size, I can't upload it to GitHub, so I'll send a link to the file: https://ftp.travitia.xyz/adrian/llvm-ir.diff.

Regarding what @xNombre said above: Disabling `CONFIG_FORTIFY_SOURCE` does "fix" this, thanks a lot @nathanchance!

**Comment by serge-sans-paille** [comment] 2022-03-30 19:43
@nathanchance : so it looks like it's not a bug in clang `main` branch, but a mismatch between older linux version and clang support for inline builtins, correct?

**Comment by nathanchance** [comment] 2022-03-30 19:56
> @nathanchance : so it looks like it's not a bug in clang `main` branch, but a mismatch between older linux version and clang support for inline builtins, correct?

I believe so. @kees and @nickdesaulniers are free to correct me but as far as I am aware, we have seen no issues with `CONFIG_FORTIFY_SOURCE` on mainline with [the changes that Kees recent pushed there there](https://git.kernel.org/linus/4be240b18aa67b1144af546bea2d7cad1b75c19b) with several different LLVM versions, but that series is not available for older kernels, due to all the prerequisite changes that were needed for it to work. This is why it was disabled in older kernels versions as I mentioned but we were not able to disable it for just clang in a clean way for 4.9 and 4.14 kernel versions due to Kconfig machinery that is missing. As far as I am aware, there are no major entities aside from Android building with `clang` on those older kernel versions, hence the diff suggestion above.

We can likely close this issue here and move the discussion of how to proceed to [our issue tracker](https://github.com/ClangBuiltLinux/linux/issues), unless others disagree.

**Comment by kees** [comment] 2022-03-30 21:15
Hi, yeah, I can confirm what @nathanchance has said. It would be possible to backport the changes to earlier kernels, but I don't think it would be trivial work.

**Comment by nathanchance** [comment] 2022-03-30 21:31
I have opened https://github.com/ClangBuiltLinux/linux/issues/1621 for further discussion. If we decide something needs to be fixed in LLVM, we can reopen this with more information.

**Closed by nathanchance** 2022-03-30 21:31 UTC
Labels: backend:AArch64, clang:codegen
