### ISSUE TITLE
c++20 nullptr_t should be in global namespace if <stddef.h> is included

### ISSUE THREAD

**Issue by gnbond** [llvm/llvm-project#62903] opened 2023-05-24 03:55 UTC
According to [CPPReference](https://en.cppreference.com/w/cpp/types/nullptr_t), for versions up to C++20 nullptr_t should be in the global namespace if <stddef.h> is included.  I.e. the following code should compile:
```c++
#include <stddef.h>
void foo(nullptr_t) {}
``` 
According to Godbolt, this does compile for g++ from 10.1 onwards, but does not compile with clang 13-16. 

For C++2x nullptr_t should be in global namespace.

 It looks like stddef.h tries to implement this for the C++2x case, but there is a FIXME that is suspicious: https://github.com/llvm/llvm-project/blob/597dd1f91d9f3823e4184f1fe73d8125fa16c026/clang/lib/Headers/stddef.h#LL103C8-L103C8

**Comment by shafik** [comment] 2023-05-24 04:19
cppreference says:

> Defined in header <cstddef>

This is not the same as the C header `stddef.h`.

If we include the correct header and prefix it with `std::` then it does indeed work: https://godbolt.org/z/fEYMEEGPo

```cpp
#include <cstddef>
void foo(std::nullptr_t) {}
```

**Comment by gnbond** [comment] 2023-05-24 05:41
Does that mean CPPReference is wrong, and it should refer to <cstddef> instead of <stddef.h>?  

In any case, I'm not sure you are proving this case, as even with <cstddef> it fails for me.  It's only working on your godbolt session because you are also compiling with -stdlib=libc++.  If I remove that option and use raw clang on godbold it still fails.

I'm pretty sure I don't understand how the clang C++ libraries are supposed to work together, or why there is a version stddef.h (and many other library header files)  in both the clang/ and libc++/ directories.   My linux distro clang package includes the version from clang/.

**Comment by AaronBallman** [comment] 2023-05-24 12:49
Cpp Reference is correct: http://eel.is/c++draft/support.c.headers#other-1

> I'm pretty sure I don't understand how the clang C++ libraries are supposed to work together, or why there is a version stddef.h (and many other library header files) in both the clang/ and libc++/ directories. My linux distro clang package includes the version from clang/.

The compiler itself provides headers for cases that only the compiler can implement (such as basic datatypes used by the compiler), and stddef.h is one such header. Our headers typically `#include_next` to the host system headers so you get the host behavior, but still get the correct functionality in freestanding where there is no host to defer to.

So I think this is actually a bug and we should be providing `nullptr_t` (and probably others as well) through stddef.h, at least for freestanding compiles.

**Comment by AaronBallman** [comment] 2023-05-24 12:52
@ldionne -- should libc++ be providing stddef.h at all? https://github.com/llvm/llvm-project/blob/main/libcxx/include/stddef.h -- I would have assumed this is something Clang should be providing in https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/stddef.h and so libc++ doesn't need to be bothered with C headers at all, but this is much more in your wheelhouse than mine so I could be missing something.

**Comment by shafik** [comment] 2023-05-24 20:44
Apologies, I completely missed that in the notes cppreference says:

> nullptr_t is available in the global namespace when `<stddef.h>` is included

**Comment by AaronBallman** [comment] 2023-05-25 11:21
> Apologies, I completely missed that in the notes cppreference says:
> 
> > nullptr_t is available in the global namespace when `<stddef.h>` is included

No worries, I had to double-check myself because I thought cppreference was wrong. :-D

**Comment by frederick-vs-ja** [comment] 2023-05-26 00:48
See also [LWG3484](https://cplusplus.github.io/LWG/issue3484). Although I believe the current wording (requiring `<stddef.h>` to provide `::nullptr_t`) is fine and the issue should be closed as NAD.

**Comment by AaronBallman** [comment] 2023-08-11 14:00
One complicating factor is, C23 has `nullptr_t` defined in `stddef.h`: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3042.htm but C++23 is not rebased onto C23, so C++26 might want to expose `nullptr_t` from `stddef.h`.

**Comment by AaronBallman** [comment] 2023-08-14 15:22
This is a duplicate of #37564

**Closed by AaronBallman** 2023-08-14 15:22 UTC
Labels: duplicate, question, c++20, clang:headers
