### ISSUE TITLE
clangd uses up all the memory (~90GB) for miniaudio.h

### ISSUE THREAD

**Issue by lszl84** [llvm/llvm-project#70945] opened 2023-11-01 15:06 UTC
Reproduces on all clangd versions on Linux (tried clangd-14, 16, and current master 6477b41a0b56919c42f44c3499ed32720101b43b).

Steps:
1. Download miniaudio.h: https://github.com/mackron/miniaudio/blob/master/miniaudio.h
2. Open it in VSCode with the clangd extension enabled
3. Watch the memory gets eaten up
![Screenshot from 2023-11-01 15-48-30](https://github.com/llvm/llvm-project/assets/42072702/63614d21-cd41-49d7-8a87-066b8c501b85)
4. Thank the Linux Kernel for saving the day

```
Nov 01 16:01:09 debian kernel: Out of memory: Killed process 170232 (clangd.main) total-vm:99151264kB, anon-rss:29007340kB, file-rss:3840kB, shmem-rss:0kB, UID:1000 pgtables:189720kB oom_score_adj:200
Nov 01 16:01:09 debian systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
```

This also reproduces for NeoVim with neovim-lspconfig and clang.

**Comment by HighCommander4** [comment] 2023-11-01 20:49
Duplicate of https://github.com/llvm/llvm-project/issues/60151

**Closed** 2023-11-01 21:01 UTC
Labels: duplicate, clangd, hang

**Comment by lszl84** [comment] 2023-11-01 21:35
So 2+ years and `clangd` still can't handle single header libraries? This is a pretty common case in the C/C++ world.

**Comment by HighCommander4** [comment] 2023-11-01 22:16
> So 2+ years and `clangd` still can't handle single header libraries? This is a pretty common case in the C/C++ world.

My understanding is it's an issue with miniaudio.h in particular, see https://github.com/llvm/llvm-project/issues/48863 for some more discussion.

**Comment by HighCommander4** [comment] 2023-11-01 22:21
See also https://github.com/clangd/clangd/issues/719#issuecomment-1402273958:

> closing this one as there's not much we can do on the clangd side and this has been reported in https://github.com/llvm/llvm-project/issues/60151 and https://github.com/llvm/llvm-project/issues/48863 already

This needs to be fixed in libClangFormat by someone who understands that code.

**Comment by lszl84** [comment] 2023-11-02 09:14
Browsing through related issues, it looks like this is reproduced also for other libraries, not just miniaudio:

- minilzo.h: https://github.com/llvm/llvm-project/issues/53888
- someone's custom blis.h: https://github.com/llvm/llvm-project/issues/60151
- who knows what else.

Just saying that from the user's perspective it looks *really* bad that such a mature project as `clang(d)` cannot handle these cases (MS C++ plugin for VSCode can... I'd happily switch to that if I only knew how to use it with NeoVim...)
