### ISSUE TITLE
Clang generates invalid code and leaks resource when throwing an exception after return statement

### ISSUE THREAD

**Issue by CurTInq** [llvm/llvm-project#75940] opened 2023-12-19 15:11 UTC
To be fair, all the other major compilers (gcc and msvc) also generate incorrect code according to the C++ standard, however clang also produces memory leak (destructor for returned object was never called).
It seems like something similar being reported in #61900 but in context of coroutines, while it seems to be a more common case.

Minimal reproducible example (I literally took it from [the C++ standard](https://timsong-cpp.github.io/cppwp/n4659/except.ctor#2)): https://godbolt.org/z/Wvfz4jPW7

**Comment by shafik** [comment] 2023-12-19 15:57
Duplicate of: https://github.com/llvm/llvm-project/issues/12658

**Closed by shafik** 2023-12-19 15:57 UTC
Labels: clang:codegen
