### ISSUE TITLE
clang-format: Crash when using AlignArrayOfStructures: Right

### ISSUE THREAD

**Issue by KonstantinSeurer** [llvm/llvm-project#53579] opened 2022-02-04 10:38 UTC
The crash happened when trying to format [this file](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/compiler/nir/nir_convert_ycbcr.c)

Stack:
```
#0 0x00007f432a7ad9a6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM-13.so+0xb5f9a6)
 #1 0x00007f432a7ab734 llvm::sys::RunSignalHandlers() (/lib64/libLLVM-13.so+0xb5d734)
 #2 0x00007f432a7ab8b6 (/lib64/libLLVM-13.so+0xb5d8b6)
 #3 0x00007f4329867750 __restore_rt (/lib64/libc.so.6+0x42750)
 #4 0x00007f43327c0c06 clang::format::WhitespaceManager::alignArrayInitializersRightJustified(clang::format::WhitespaceManager::CellDescriptions&&) (/lib64/libclang-cpp.so.13+0x2b12c06)
 #5 0x00007f43327c1fcb clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) (/lib64/libclang-cpp.so.13+0x2b13fcb)
 #6 0x00007f43327c2084 clang::format::WhitespaceManager::alignArrayInitializers() (/lib64/libclang-cpp.so.13+0x2b14084)
 #7 0x00007f43327c4f64 clang::format::WhitespaceManager::generateReplacements() (/lib64/libclang-cpp.so.13+0x2b16f64)
 #8 0x00007f43327679f5 (/lib64/libclang-cpp.so.13+0x2ab99f5)
 #9 0x00007f433279017c clang::format::TokenAnalyzer::process() (/lib64/libclang-cpp.so.13+0x2ae217c)
#10 0x00007f4332766e3a (/lib64/libclang-cpp.so.13+0x2ab8e3a)
#11 0x00007f4332766f6c (/lib64/libclang-cpp.so.13+0x2ab8f6c)
#12 0x00007f433276d0d1 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/lib64/libclang-cpp.so.13+0x2abf0d1)
#13 0x00007f433276dd61 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) (/lib64/libclang-cpp.so.13+0x2abfd61)
#14 0x0000563a738becc3 (/usr/bin/clang-format+0xecc3)
#15 0x0000563a738b86a8 (/usr/bin/clang-format+0x86a8)
#16 0x00007f4329852560 __libc_start_call_main (/lib64/libc.so.6+0x2d560)
#17 0x00007f432985260c __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2d60c)
#18 0x0000563a738b8965 (/usr/bin/clang-format+0x8965)
```

**Comment by mkurdej** [comment] 2022-02-04 11:21
Possible duplicate of #53428.

Minimal repro with clang-format 13:
```
auto a = {
    {
     {{}, {}, {}, {}},
     {{}, {}},
     }
};
```

The crash doesn't occur with current main. Closing.

**Closed by mkurdej** 2022-02-04 11:21 UTC
Labels: bug, clang-format
