### ISSUE TITLE
CUDA code compile error: function template partial specialization is not allowed

### ISSUE THREAD

**Issue by zhiweij1** [llvm/llvm-project#68772] opened 2023-10-11 07:32 UTC
Smaller reproducer:
```
template<class T1, class T2>
struct A {
  template <class T3>
  void foo(T3 x);
};

template<typename T1, typename T2>
template<typename T3>
void A<T1, T2>::foo<T3>(T3 x) {

}
```
https://godbolt.org/z/xn7vre9db

The original code comes from https://github.com/NVIDIA/FasterTransformer/blob/afdf9a9eb86f15363c0249117d166d6b45dbb371/src/fastertransformer/kernels/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm_template.h#L426

It can be built with nvcc successfully.

**Comment by Endilll** [comment] 2023-10-11 08:38
I think out-of-line member function template definition looks the following way:
```cpp
template<typename T1, typename T2>
template<typename T3>
void A<T1, T2>::foo(T3 x) {}
```
So Clang is correct to reject this.

**Comment by zhiweij1** [comment] 2023-10-11 08:44
Hi @Endilll ,

Actually, the key point here is that the original code is compliable witn nvcc (and it is treated as CUDA language).
So, for clang, if I also treat it as CUDA code, I expect the code can be compiled.

**Comment by Endilll** [comment] 2023-10-11 08:51
I'm not sure we are bug-compatible with nvcc (or want to be) when it clashes with the C++ standard. That said, I think your code falls into conforming extension territory.
CC @AaronBallman

**Comment by AaronBallman** [comment] 2023-10-11 11:48
We don't currently aim for compatibility with NVCC within Clang, though given that we aim for compatibility with GCC and MSVC, I would suspect an RFC with a plan for NVCC compatibility would be well-received once we knew the shape of what the goal was (ABI compat sufficient, or do we need bug for bug compat, etc). CC @erichkeane on this point.

The official CUDA documentation lists [C++ language extensions](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#c-language-extensions), but makes no mention of this being a language extension. So I think this is very plausibly a bug in NVCC that their headers are relying on. Have you reported this to NVidia and gotten their stance on it?

**Comment by AaronBallman** [comment] 2023-10-11 15:13
> I would think this is a situation where filing a bug against the FasterTransform library to see if they would use a correct type of C++ would be the best course of action.

Agreed.

I'm going to close this as not a bug, but if we do decide we want NVCC CUDA compatibility at some point in the future or if @zhiweij1 comes back with more information on why this is needed regardless, we can reopen the issue at that point.

**Closed by AaronBallman** 2023-10-11 15:13 UTC
Labels: invalid, c++, cuda, clang:diagnostics

**Comment by erichkeane** [comment] 2023-10-11 15:28
> @AaronBallman @erichkeane This is probably an edg bug https://godbolt.org/z/81osqz3nd - it's not a partial specialization, it's just lets you repeat the parameter list _exactly_, probably a missing diag

That was my conclusion as well (though I phrased it less explicitly).

**Comment by zhiweij1** [comment] 2023-10-12 00:43
I have reported this issue in nvidia forum https://forums.developer.nvidia.com/t/nvcc-bug-incorrect-template-method-definition-syntax-can-pass-nvcc-compilation/269184 and FasterTransformer community https://github.com/NVIDIA/FasterTransformer/issues/765
