### ISSUE TITLE
when a constexpr returns rvalue and bound to a nonconstexpr variable, if there is inherit list expanded from folded expression, the parser will crash

### ISSUE THREAD

**Issue by leafwaltz** [llvm/llvm-project#59857] opened 2023-01-06 14:15 UTC
### **the code is here:**

```cpp
#include <string_view>
#include <utility>

template<size_t Index, typename T>
struct TupleElement {
    constexpr explicit TupleElement(T&& ele) : element_{ ele } {}
private:
    T element_;
};

template<typename T, typename... Ts>
struct TupleImpl;

template<size_t... Indices, typename... Ts>
struct TupleImpl<std::index_sequence<Indices...>, Ts...>
    : TupleElement<Indices, Ts>... { // **error occurred here, when remove this line, there will be no crash**
    constexpr explicit TupleImpl(Ts&&... ts) : TupleElement<Indices, Ts>{ std::forward<Ts>(ts) }... {}
};

template<typename... Ts>
struct Tuple : TupleImpl<std::make_index_sequence<sizeof...(Ts)>, Ts...> {
    using TupleImpl<std::make_index_sequence<sizeof...(Ts)>, Ts...>::TupleImpl;
};

template<typename... Ts>
struct SubModules {
    constexpr explicit SubModules(Ts&&... ts) : subModules{ std::forward<Ts>(ts)... } {}
    Tuple<Ts...> subModules;
};

template<typename ModuleType>
struct ModuleBase {
    constexpr explicit ModuleBase(std::string_view name) : moduleName{ name } {}
    static constexpr SubModules subModules{};
    std::string_view moduleName{};
};

struct ModuleA : ModuleBase<ModuleA> {
    using ModuleBase<ModuleA>::ModuleBase;
};

struct ModuleB : ModuleBase<ModuleB> {
    using ModuleBase<ModuleB>::ModuleBase;
};

struct ModuleC : ModuleBase<ModuleC> {
    using ModuleBase<ModuleC>::ModuleBase;

    static constexpr SubModules subModules{
        ModuleA{ "ModuleA0" },
        ModuleA{ "ModuleA1" },
        ModuleB{ "ModuleB0" }
    };
};

struct ModuleWrapper {
    static consteval auto init() {
        return ModuleC{ "ModuleC" }.subModules.subModules;
    }
};

int main() {
    auto x = ModuleWrapper::init(); // error
    //constexpr auto x = ModuleWrapper::init(); // work
    return 0;
}
```

### **error message:**

```console
$ /usr/bin/clang++   -g -std=gnu++20 -MD -MT CMakeFiles/testClang.dir/main.cpp.o -MF CMakeFiles/testClang.dir/main.cpp.o.d -o CMakeFiles/testClang.dir/main.cpp.o -c /home/ayo/CLionProjects/testClang/main.cpp
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++ -g -std=gnu++20 -MD -MT CMakeFiles/testClang.dir/main.cpp.o -MF CMakeFiles/testClang.dir/main.cpp.o.d -o CMakeFiles/testClang.dir/main.cpp.o -c /home/ayo/CLionProjects/testClang/main.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/home/ayo/CLionProjects/testClang/main.cpp'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@main'
 #0 0x00007f4d76df9fd2 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xf86fd2)
 #1 0x00007f4d76df8140 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xf85140)
 #2 0x00007f4d76df9694 llvm::sys::CleanupOnSignal(unsigned long) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xf86694)
 #3 0x00007f4d76d28f02 (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xeb5f02)
 #4 0x00007f4d76d29184 (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xeb6184)
 #5 0x00007f4d80cd5420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #6 0x00007f4d775291df llvm::SelectionDAGBuilder::visitGetElementPtr(llvm::User const&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x16b61df)
 #7 0x00007f4d77520c7b llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x16adc7b)
 #8 0x00007f4d775b34c6 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x17404c6)
 #9 0x00007f4d775b2f57 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x173ff57)
#10 0x00007f4d775b0dfb llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x173ddfb)
#11 0x00007f4d796c6fcf (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x3853fcf)
#12 0x00007f4d7715d9ab llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x12ea9ab)
#13 0x00007f4d76f31ba5 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x10beba5)
#14 0x00007f4d76f37753 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x10c4753)
#15 0x00007f4d76f321c5 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0x10bf1c5)
#16 0x00007f4d7ec26b72 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x1a08b72)
#17 0x00007f4d7ef8bc1f (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x1d6dc1f)
#18 0x00007f4d7dd4e6c2 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0xb306c2)
#19 0x00007f4d7f8d1715 clang::FrontendAction::Execute() (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x26b3715)
#20 0x00007f4d7f8529b4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x26349b4)
#21 0x00007f4d7f948614 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x272a614)
#22 0x0000560923324d8e cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang+++0x13d8e)
#23 0x00005609233225b0 (/usr/bin/clang+++0x115b0)
#24 0x00007f4d7f5366a2 (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x23186a2)
#25 0x00007f4d76d28df0 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xeb5df0)
#26 0x00007f4d7f535e03 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x2317e03)
#27 0x00007f4d7f502a62 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x22e4a62)
#28 0x00007f4d7f502cbe clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&, bool) const (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x22e4cbe)
#29 0x00007f4d7f51c89e clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib/llvm-16/bin/../lib/libclang-cpp.so.16+0x22fe89e)
#30 0x0000560923321e66 clang_main(int, char**) (/usr/bin/clang+++0x10e66)
#31 0x00007f4d7591f083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#32 0x000056092331f25e _start (/usr/bin/clang+++0xe25e)
clang: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Ubuntu clang version 16.0.0 (++20221129052932+d43a2f09de51-1~exp1~20221129173035.462)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/main-f7ed96.cpp
clang: note: diagnostic msg: /tmp/main-f7ed96.sh
clang: note: diagnostic msg: 

********************
ninja: build stopped: subcommand failed.
```

**Comment by shafik** [comment] 2023-01-08 22:15
Confirmed: https://godbolt.org/z/a8YPhhhrn

Assertion: 

```console
clang++: /root/llvm-project/llvm/include/llvm/IR/DataLayout.h:653: 
uint64_t llvm::StructLayout::getElementOffset(unsigned int) const:
Assertion `Idx < NumElements && "Invalid element idx!"' failed.
```

**Comment by shafik** [comment] 2023-01-08 22:39
It looks like the crash changed between clang-15: https://godbolt.org/z/cPKnqvsn4 and trunk: https://godbolt.org/z/n4GzEr5s4

**Comment by AaronBallman** [comment] 2023-02-22 16:09
I'm closing this issue as it no longer reproduces with Clang trunk. If you can still reproduce the problem, please reopen the issue with additional details.

**Closed by AaronBallman** 2023-02-22 16:09 UTC
Labels: llvm:codegen, confirmed, crash
