### ISSUE TITLE
_Static_assert not accepted in empty switch/case clause

### ISSUE THREAD

**Issue by joeyye-work** [llvm/llvm-project#69572] opened 2023-10-19 08:46 UTC
```c
#include <assert.h>
int main(int x, char **argv)
{
        switch (x) {
                case 1:
                    // x++;  // Uncommenting this will pass
                    _Static_assert(1, "error message");
                    break;
        };
        return x;
}
```
compiled with clang -c c.c -std=c11
error: expected expression
                    _Static_assert(1, "error message");

Impacted version: from llvm-14 to llvm-17

Strange thing is if I put some statements before the _Static_assert it will work.

GCC compiles it fine.

**Comment by AaronBallman** [comment] 2023-10-19 15:03
This isn't valid until C23 because `_Static_assert` is a declaration, not a statement; we partially implement WG14 N2508 but we don't fully implement it. This is a duplicate of #53692

**Closed by AaronBallman** 2023-10-19 15:03 UTC
Labels: c11, clang:frontend, rejects-valid
