### ISSUE TITLE
Failed conversion for `!fir.box<!fir.ptr<i32>>`

### ISSUE THREAD

**Issue by banach-space** [llvm/llvm-project#55210] opened 2022-05-01 14:00 UTC
### How to reproduce

```console
$ cat repro.mlir
module attributes {fir.defaultkind = "a1c4d8i4l4r4", fir.kindmap = "", llvm.target_triple = "aarch64-unknown-linux-gnu"}  {
  fir.global internal @_QFEx : !fir.box<!fir.ptr<i32>> {
    %0 = fir.zero_bits !fir.ptr<i32>
    %1 = fir.embox %0 : (!fir.ptr<i32>) -> !fir.box<!fir.ptr<i32>>
    fir.has_value %1 : !fir.box<!fir.ptr<i32>>
  }
}
$ fir-opt --fir-to-llvm-ir="target=x86_64-unknown-linux-gnu" repro.mlir
repro.mlir:2:3: error: 'llvm.mlir.global' op initializer region type '!llvm.ptr<struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>>' does not match global type '!llvm.struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>'
```

### Discussion
Reproduced with [ToT](https://github.com/llvm/llvm-project/commit/fb4113ef0c8b2c5e5e2817e9ca14fb57a6d252be). Works just fine on [fir-dev](https://github.com/flang-compiler/f18-llvm-project/tree/fir-dev).

IIUC, this is failing because:
* `!llvm.ptr<struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>>` 

is not re-mapped as:
* `!llvm.struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>`. 

It used to be re-mapped in MLIR's [remapValues](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Transforms/Utils/DialectConversion.cpp#L1255-L1307), but that hook was updated in https://reviews.llvm.org/D111620. 

### Credits
Extracted from this [comment](https://reviews.llvm.org/D124610#3484526) (posted by @peixin). Original reproducer:

```fortran
  integer, save, pointer :: x
   x = 1
end
``` 

### Next steps
Please assign this ticket to yourself if you intend to work on it! Otherwise, I'll try to prepare a fix myself.

**Comment by PeixinQiao** [comment] 2022-05-02 05:23
Thanks @banach-space . Please feel free to assign this to yourself.

**Comment by kiranchandramohan** [comment] 2022-05-02 08:05
Jean had a fix for a similar issue in fir-dev (https://github.com/flang-compiler/f18-llvm-project/pull/313). There is an entry for upstreaming this in the project board with a question whether this is still need (https://github.com/flang-compiler/f18-llvm-project/projects/4). I have not checked in detail but you might want to wait before proceeding.

**Comment by banach-space** [comment] 2022-05-06 09:58
> Thanks @banach-space . Please feel free to assign this to yourself.

@PeixinQiao I've not had a chance to take a look this week and I will be busy next week too :( Just letting you know in case this is a blocker for you!

Perhaps it's worth pinging @jeanPerier too :)

**Comment by PeixinQiao** [comment] 2022-05-07 08:08
@banach-space That's ok. It's not in hurry. It doesn't block any patch to proceed.

**Comment by rofirrim** [comment] 2022-05-25 21:10
I've seen this issue as well, IIUC the issue is caused by `convertBoxType` in `flang/lib/Optimizer/CodeGen/TypeConverter.h`. 

In the testcase above, when converting a type such as `!fir.box<!fir.ptr<i32>>` this type becomes `!llvm.ptr<struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>>`. 

One of such conversions is triggered in `mlir/lib/Transforms/Utils/DialectConversion.cpp`, in `remapValues`

```cpp
if (failed(currentTypeConverter->convertType(origType, legalTypes)))
```

However if this type as the result of an `embox` operation such as

```mlir
"fir.embox"(%1) {operand_segment_sizes = dense<[1, 0, 0, 0]> : vector<4xi32>} : 
   (!fir.ptr<i32>)
   -> !fir.box<!fir.ptr<i32>>
```
which in LLVM dialect seems to be mapped to this (or at least this is what `mapping.lookupOrDefault` computes)

```llvm
"llvm.insertvalue"(%19, %20) {position = [0 : i32]} :
  (!llvm.struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>, !llvm.ptr<i32>)
  -> !llvm.struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>
```

I understand the reason is that we're updating a `!fir.box` which is represented by a `!llvm.struct`.

This causes a mismatch because the `desiredType` (as computed ultimately by `convertType`) is a pointer to the struct descriptor (`!llvm.ptr<struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>>`) while the result type of the operation `llvm.insertvalue` does not have that pointer (`!llvm.struct<(ptr<i32>, i64, i32, i8, i8, i8, i8)>`). This leads to `remapValues` to eventually introduce a `builtin.unrealized_conversion_cast` which causes the issue.

Looks like `TypeConverter.h` has some kind of context in which `!fir.box` is lowered without a pointer using `convertBoxTypeAsStruct` (which computes the same as `convertBoxType` but removes the pointer) when used inside a record or a tuple.

I'm not versed enough in MLIR to be able fix this, but from a quick read of the code it looks like the generic code of MLIR expects the conversion to be "context insensitive". However, flang's conversion of a box type depends on whether it is part of a record/tuple or not. This causes a mismatch when we're operating with structs. (I'm a bit confused why a `!fir.box` should become an LLVM pointer given that we often wrap it in `!fir.ref<...>` but I'm sure I'm too missing context here!)

**Comment by kiranchandramohan** [comment] 2022-06-01 13:08
The cast should not be necessary. We probably have to strengthen the conversion pattern (or the legality check). I am having a look at this, @shraiysh please wait.

**Comment by kiranchandramohan** [comment] 2022-06-01 22:43
Adding `single` to the legality check and making the legality check more strict (adding operand types also to the check) seems to get this through. I will make a patch soon.

**Closed** 2022-06-09 10:13 UTC
Labels: flang:ir
