### ISSUE TITLE
AArch64 SVE VLS: ISel crashes with <8 x float> argument

### ISSUE THREAD

**Issue by kawashima-fj** [llvm/llvm-project#63025] opened 2023-05-31 07:12 UTC
`llc` crashes with the following IR.

```llvm
source_filename = "reproducer.c"
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

declare void @bar(<8 x float>) #0

define void @foo() #0 {
  call void @bar(<8 x float> undef)
  ret void
}

attributes #0 = { vscale_range(2,2) "target-features"="+sve" }
````

```console
$ /opt/llvm/16.0.4/bin/llc reproducer.ll 
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /opt/llvm/16.0.4/bin/llc reproducer.ll
1.      Running pass 'Function Pass Manager' on module 'reproducer.ll'.
2.      Running pass 'AArch64 Instruction Selection' on function '@foo'
 #0 0x0000ffffb7ea4e20 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0xd64e20)
 #1 0x0000ffffb7ea3110 llvm::sys::RunSignalHandlers() (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0xd63110)
 #2 0x0000ffffb7ea327c SignalHandler(int) Signals.cpp:0:0
 #3 0x0000ffffbe7b066c (linux-vdso.so.1+0x66c)
 #4 0x0000ffffb6cf2c1c raise (/lib64/libc.so.6+0x32c1c)
 #5 0x0000ffffb6ce07a8 abort (/lib64/libc.so.6+0x207a8)
 #6 0x0000ffffb9dd8db8 llvm::AArch64TargetLowering::LowerCall(llvm::TargetLowering::CallLoweringInfo&, llvm::SmallVectorImpl<llvm::SDValue>&) const (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x2c98db8)
 #7 0x0000ffffb86b7da0 llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x1577da0)
 #8 0x0000ffffb86c0f6c llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x1580f6c)
 #9 0x0000ffffb86da3b8 llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x159a3b8)
#10 0x0000ffffb86cb9f0 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x158b9f0)
#11 0x0000ffffb86edf04 llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x15adf04)
#12 0x0000ffffb87403cc llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x16003cc)
#13 0x0000ffffb87412ac llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0x16012ac)
#14 0x0000ffffb874346c llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.1092) SelectionDAGISel.cpp:0:0
#15 0x0000ffffb828d19c llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.80) MachineFunctionPass.cpp:0:0
#16 0x0000ffffb7fe5a1c llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0xea5a1c)
#17 0x0000ffffb7fe5b78 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0xea5b78)
#18 0x0000ffffb7fe6698 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/llvm/16.0.4/bin/../lib/libLLVM-16.so+0xea6698)
#19 0x00000000004134c0 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#20 0x000000000040bfd0 main (/opt/llvm/16.0.4/bin/llc+0x40bfd0)
#21 0x0000ffffb6ce0be4 __libc_start_main (/lib64/libc.so.6+0x20be4)
#22 0x000000000040c69c _start (/opt/llvm/16.0.4/bin/llc+0x40c69c)
```

# Environment

At least LLVM 16.0.4 and the latest `main` branch (commit aaa33b6a98de2be7cdc827b13e60c103206d6461) can reproduce this error.

# Quick Survey

## SVE VLS/VLA, NEON

This error only occurs with **SVE VLS** (a.k.a. fixed-length).

- SVE VLS (`attributes #0 = { vscale_range(2,2) "target-features"="+sve" }`: **crash**
- SVE VLA (`attributes #0 = { "target-features"="+sve" }`: no crash
- NEON (`attributes #0 = { "target-features"="+neon" }`: no crash

## Types

If the type size <= 128, this error doesn't occur.

- `<4 x float>`: no crash
- `<8 x float>`  **crash**
- `<16 x float>`  **crash**
- `<2 x double>`: no crash
- `<4 x double>`: **crash**
- `<8 x double>`: **crash**

## Assertion

With the debug build of the latest `main`,  an assertion at `llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:6859` fails.

```console
$ /opt/llvm/main/bin/llc reproducer.ll 
llc: llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:6859: void analyzeCallOperands(const llvm::AArch64TargetLowering&, const llvm::AArch64Subtarget*, const llvm::TargetLowering::CallLoweringInfo&, llvm::CCState&): Assertion `!Res && "Call operand has unhandled type"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llc reproducer.ll
1.      Running pass 'Function Pass Manager' on module 'reproducer.ll'.
2.      Running pass 'AArch64 Instruction Selection' on function '@foo'
 #0 0x00007f173cc297ea llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) llvm/lib/Support/Unix/Signals.inc:602:22
 #1 0x00007f173cc29baf PrintStackTraceSignalHandler(void*) llvm/lib/Support/Unix/Signals.inc:675:1
 #2 0x00007f173cc2728e llvm::sys::RunSignalHandlers() llvm/lib/Support/Signals.cpp:104:20
 #3 0x00007f173cc29102 SignalHandler(int) llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f173c43c520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f173c490a7c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #6 0x00007f173c490a7c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #7 0x00007f173c490a7c pthread_kill ./nptl/pthread_kill.c:89:10
 #8 0x00007f173c43c476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #9 0x00007f173c4227f3 abort ./stdlib/abort.c:81:7
#10 0x00007f173c42271b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#11 0x00007f173c433e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#12 0x00007f17431484cc analyzeCallOperands(llvm::AArch64TargetLowering const&, llvm::AArch64Subtarget const*, llvm::TargetLowering::CallLoweringInfo const&, llvm::CCState&) llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:6829:0
#13 0x00007f1743149b7c llvm::AArch64TargetLowering::LowerCall(llvm::TargetLowering::CallLoweringInfo&, llvm::SmallVectorImpl<llvm::SDValue>&) const llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:7134:0
#14 0x00007f17415a7753 llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:10244:24
#15 0x00007f174159a927 llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:7949:3
#16 0x00007f174159b3b0 llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*) llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:8079:27
#17 0x00007f174159dfa2 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:8630:16
#18 0x00007f174156a4be llvm::SelectionDAGBuilder::visit(unsigned int, llvm::User const&) llvm/include/llvm/IR/Instruction.def:209:1
#19 0x00007f1741569cc3 llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1178:22
#20 0x00007f174167e795 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, true>, bool&) llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:689:79
#21 0x00007f1741684352 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1705:33
#22 0x00007f174167d306 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:483:7
#23 0x00007f17430d0fbc (anonymous namespace)::AArch64DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp:58:0
#24 0x00007f1740a65b48 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) llvm/lib/CodeGen/MachineFunctionPass.cpp:91:33
#25 0x00007f173d59019a llvm::FPPassManager::runOnFunction(llvm::Function&) llvm/lib/IR/LegacyPassManager.cpp:1435:20
#26 0x00007f173d590470 llvm::FPPassManager::runOnModule(llvm::Module&) llvm/lib/IR/LegacyPassManager.cpp:1481:13
#27 0x00007f173d5908db (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) llvm/lib/IR/LegacyPassManager.cpp:1550:20
#28 0x00007f173d58b558 llvm::legacy::PassManagerImpl::run(llvm::Module&) llvm/lib/IR/LegacyPassManager.cpp:535:13
#29 0x00007f173d5911eb llvm::legacy::PassManager::run(llvm::Module&) llvm/lib/IR/LegacyPassManager.cpp:1678:1
#30 0x0000559342b3ecde compileModule(char**, llvm::LLVMContext&) llvm/tools/llc/llc.cpp:759:66
#31 0x0000559342b3c5ab main llvm/tools/llc/llc.cpp:420:35
#32 0x00007f173c423d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#33 0x00007f173c423e40 call_init ./csu/../csu/libc-start.c:128:20
#34 0x00007f173c423e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#35 0x0000559342b3b205 _start
```

## Debug

`analyzeCallOperands` function, which has the assertion, is:

```c++
static void analyzeCallOperands(const AArch64TargetLowering &TLI,
                                const AArch64Subtarget *Subtarget,
                                const TargetLowering::CallLoweringInfo &CLI,
                                CCState &CCInfo) {
  const SelectionDAG &DAG = CLI.DAG;
  CallingConv::ID CalleeCC = CLI.CallConv;
  bool IsVarArg = CLI.IsVarArg;
  const SmallVector<ISD::OutputArg, 32> &Outs = CLI.Outs;
  bool IsCalleeWin64 = Subtarget->isCallingConvWin64(CalleeCC);

  unsigned NumArgs = Outs.size();
  for (unsigned i = 0; i != NumArgs; ++i) {
    MVT ArgVT = Outs[i].VT;
    ISD::ArgFlagsTy ArgFlags = Outs[i].Flags;

    bool UseVarArgCC = false;
    if (IsVarArg) {
      // On Windows, the fixed arguments in a vararg call are passed in GPRs
      // too, so use the vararg CC to force them to integer registers.
      if (IsCalleeWin64) {
        UseVarArgCC = true;
      } else {
        UseVarArgCC = !Outs[i].IsFixed;
      }
    }

    if (!UseVarArgCC) {
      // Get type of the original argument.
      EVT ActualVT =
          TLI.getValueType(DAG.getDataLayout(), CLI.Args[Outs[i].OrigArgIndex].Ty,
                       /*AllowUnknown*/ true);
      MVT ActualMVT = ActualVT.isSimple() ? ActualVT.getSimpleVT() : ArgVT;
      // If ActualMVT is i1/i8/i16, we should set LocVT to i8/i8/i16.
      if (ActualMVT == MVT::i1 || ActualMVT == MVT::i8)
        ArgVT = MVT::i8;
      else if (ActualMVT == MVT::i16)
        ArgVT = MVT::i16;
    }

    CCAssignFn *AssignFn = TLI.CCAssignFnForCall(CalleeCC, UseVarArgCC);
    bool Res = AssignFn(i, ArgVT, ArgVT, CCValAssign::Full, ArgFlags, CCInfo);
    assert(!Res && "Call operand has unhandled type");
    (void)Res;
  }
}
```

When SVE 256-bit VLS, `ArgVT` is `{SimpleTy = llvm::MVT::v8f32}`. Which means the backend tries to use the 256-bit SVE register. The `AssignFn` function cannot handle this case and returns `false`.

When SVE VLA, `ArgVT` is `{SimpleTy = llvm::MVT::v4f32}`. The output assembly code seems to use two NEON registers.

I don't know whether trying to use a 256-bit SVE register is bad or the `AssignFn` function is bad.

# `<8 x float>`

This crash was observed when compiling a complex C++ code with `-march=armv8-a+sve -msve-vector-bits=256`. The code uses SVE ACLE. A reference (or a pointer) of something is used as an argument. The `ArgumentPromotionPass` seems to promote the reference to a `<8 x float>` value.

**Comment by v01dXYZ** [comment] 2023-06-07 20:20
You're example is not using `SVE` registers, thus it uses the Neon 128 bits.

The following example works:

```
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

declare aarch64_sve_vector_pcs void @bar(<vscale x 8 x float>) #0

define aarch64_sve_vector_pcs void @foo() #0 {
  call void @bar(<vscale x 8 x float> undef)
  ret void
}

attributes #0 =  { vscale_range(2,2) "target-features"="+sve" }
```

The question is why the code doesn't try to 2 neon registers as with the SVA case. Anyway it seems `llvm 15` does not exhibit this behaviour, only from `llvm 16` on.

**Comment by v01dXYZ** [comment] 2023-06-26 08:48
There is a quite strange behaviour: when testing with the Debian built `llc`, it passes, but it is not the case with compiler-explorer version.

**Comment by v01dXYZ** [comment] 2023-06-27 00:43
I think I found the reason of the regression between `15` and `16`, but also between the `compiler-explorer` and the debian version: access of an item of an empty vector without bound 

https://github.com/llvm/llvm-project/blob/5cbcaf1678709e4da8b32f075a5c9a3cab028965/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L7288C5-L7297

With the "working" version, `ArgLocs` is initialised with `0` but in the non-working version that's not the case and it will branch to the `unreachable` case.

`ArgLocs` is defined with:

https://github.com/llvm/llvm-project/blob/5cbcaf1678709e4da8b32f075a5c9a3cab028965/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L7134-L7135

**Comment by paulwalker-arm** [comment] 2023-08-08 16:17
There is no ABI for SVE VLS and thus by default the existing AArch64 ABI is used.  Just by the nature of how legalisation happens this means vectors bigger than 128-bit can sometimes be split across multiple registers.  However, this only works up to a point, which is why the SVE VLS unit tests typically use pass-by reference.

The advice for wanting to use larger than NEON vectors as function parameters remains the same as always.  Functions should take/return scalable vector types with fixed-length vector operands and return types "bitcasted" via the vector.insert/vector.extract intrinsics. This is the mechanism used to support the SVE ACLE's arm_sve_vector_bits feature.

Perhaps one day this will change but as it stands there are no plans to create a dedicated SVE VLS ABI.

**Comment by paulwalker-arm** [comment] 2023-09-01 14:14
Assuming this conversation has reach a natural conclusion I'm closing this issue as working as designed.

**Closed by paulwalker-arm** 2023-09-01 14:14 UTC
Labels: backend:AArch64, SVE

**Comment by paulwalker-arm** [comment] 2023-09-04 13:35
Yes that sounds like a bug we'll need to fix.  Have you a reproducer showing the bugs argument promotion?

**Comment by kawashima-fj** [comment] 2023-09-04 13:52
Yes, I have a reproducer. However, it is my colleague's code and may contain confidential material. I'll confirm it and put a small reproducer in a new issue.
