### ISSUE TITLE
[clang-format] change to string << string handling causes huge code changes

### ISSUE THREAD

**Issue by mydeveloperday** [llvm/llvm-project#88483] opened 2024-04-12 08:01 UTC
The change made for #44363 causes massive amount of change in the default behaviour, we shouldn't change the defaults like this without an option.

**Comment by djasper** [comment] 2024-04-12 08:36
FWIW, breaking between two consecutive string literals on either side of a
"<<" makes sense to me.

**Comment by mydeveloperday** [comment] 2024-04-12 09:42
A rare appearance from @djasper  ;-) means we have to fix this!!!

**Comment by owenca** [comment] 2024-04-14 06:24
> We should not change the default behaviour unless this the original cause was a bug (which it wasn't in this case it was intentional), this was a conscious decision made by @djasper (I assume) and whilst I know it might seem odd sometimes when we applied this to our large base the impact is huge and not necessarily for the better.
> 
> While I appreciate it goes wrong for some it doesn't mean its bad always:
> 
> ```c++
> osjson << "{\n"
>        <<"  \"name\": \"value\",\n"
>        <<"  \"key\": \"abc\", \n"
>        <<" }";
> ```
> 
> now becomes
> 
> ```
> osjson << "{\n" <<"  \"name\": \"value\",\n <<"  \"key\": \"abc\",\n  << "}";
> ```

See https://github.com/llvm/llvm-project/pull/69871#issuecomment-2053908754.

> I'm proposing here we make a new option (as an enum so we can add other behaviours in the future)
> 
> ```c++
> enum BreakChevronOperator
> {
>      Never
>      BetweenStrings
> }
> ```

See https://github.com/llvm/llvm-project/pull/69859#issuecomment-1776064714.

> But the default needs to be BetweenStrings.

The default behavior has been "breaking between two adjacent string literals only if the first one ends with a newline" since clang-format 17, and this should be the default value of whatever new option we add for breaking string literals.

> this original behvaiour wasn't a bug.

People who commented on #44363 and https://github.com/clangd/vscode-clangd/issues/545 thought otherwise. See also https://github.com/llvm/llvm-project/pull/69871#pullrequestreview-1691432534.

**Comment by mydeveloperday** [comment] 2024-04-15 10:22
I've read everything about this,I even proposed a similar change year ago, I just wish we hadn't changed the default... I have no problem with the change or the additional change to support "\n" but I just wish it had gone in as an option. It was never a bug, but was intended to behave like that. Now 1 or 2 people are making the decision to change it for everyone.

The question really comes down to if you have two strings next to each other

os << "ABC" << "DEF"

why not do it as os << "ABCDEF" if you want them on one line, and so hence if you have a "<<" between two literals then you want some form of a break between them. Hence the logical breaking (regardless of the newline or not)

os << "ABC"
     << "DEF"

At the end of the day, when 18 hits people source (likely most users are not on 18) we are going to generate alot of flux.. at that point I think we'll get people coming back saying clang-format keep changing the defaults.

**Comment by djasper** [comment] 2024-04-15 12:06
Regarding these two things individually:

Does the line wrapping make sense:
I have looked across Google's codebase and almost all insteads of having
<literal> << <literal> without a line break was caused by clang-format
merging lines that the user had previously split. As such, I agree that
this is very likely the desired behavior.

Rolling out / changing defaults:
If a separate option for this is introduced, I think we should keep the
current behavior as default to cause less churn. However, this specific
churn is IMO also acceptable, i.e. if we chose to not even make this an
additional option. The trade-off here is causing churn vs. ever increasing
the codebase and configuration complexity. I am not entirely certain that
creating a new option here is worth its weight. But that's just my 2c,
don't take that to mean too much (and I have not read up on the full
history on this particular behavior).

**Comment by owenca** [comment] 2024-04-16 06:19
> I've read everything about this,I even proposed a similar change year ago, I just wish we hadn't changed the default... I have no problem with the change or the additional change to support "\n" but I just wish it had gone in as an option. It was never a bug, but was intended to behave like that. Now 1 or 2 people are making the decision to change it for everyone.

This change was intended as a bug fix, not a change to the LLVM default. It has been baked on the main branch for 5+ months and gone into release 18. Had anyone wanted an option instead, either in the review of #69871 or in a request before 18 was branched, d68826dfbd98 would not have landed or would have been reverted before 18.1.1.

**Comment by owenca** [comment] 2024-04-16 06:39
>Rolling out / changing defaults: If a separate option for this is introduced, I think we should keep the current behavior as default to cause less churn. However, this specific churn is IMO also acceptable, i.e. if we chose to not even make this an additional option. The trade-off here is causing churn vs. ever increasing the codebase and configuration complexity. I am not entirely certain that creating a new option here is worth its weight. But that's just my 2c, don't take that to mean too much (and I have not read up on the full history on this particular behavior).

A third option would be to revert both d68826dfbd98 and 27f547968cce before 18.1.5 is released as I doubt that we can fix most of the existing issues related to breaking "<<" without a new option. @kadircet @HazardyKnusperkeks @rymiel would you please weigh in?

**Comment by kadircet** [comment] 2024-04-16 11:31
> The default behavior has been "breaking between two adjacent string literals only if the first one ends with a newline" since clang-format 18, and this should be the default value of whatever new option we add for breaking string literals.

FWIW, it was mostly to dampen some big shift in defaults caused by d68826dfbd987377ef6771d40c1d984f09ee3b9e, which completely turned off breaking between string literals. 27f547968cce89d4706ae2b27a0c15254d1670ee brought it down to cases that don't have an explicit `\n` in the literal.

I mostly went with this approach because there seemed to be some stance from maintainers around this new behavior being preferred, and some option based mechanism already being discussed in https://github.com/llvm/llvm-project/pull/69859. So I wanted to find a less-disruptive middle ground until things have finally settled.

So, maybe I misread the room back in the day, but if I felt like a revert on d68826dfbd987377ef6771d40c1d984f09ee3b9e  was an option, I'd definitely go with that rather than 27f547968cce89d4706ae2b27a0c15254d1670ee :D

Hence, I am definitely in favor of completely reverting both https://github.com/llvm/llvm-project/commit/d68826dfbd987377ef6771d40c1d984f09ee3b9e and https://github.com/llvm/llvm-project/commit/27f547968cce89d4706ae2b27a0c15254d1670ee.

As for my 2cents on defaults; I'd be leaning towards preserving the compatibility with existing formatting behaviour. Even if an option makes things easier to configure (and less of a churn for my employer), it's still disruptive for the ecosystem as people use different versions of clang-format, and in such cases a version skew between different developers just makes it much harder for everyone.

**Comment by owenca** [comment] 2024-04-17 04:20
> Hence, I am definitely in favor of completely reverting both [d68826d](https://github.com/llvm/llvm-project/commit/d68826dfbd987377ef6771d40c1d984f09ee3b9e) and [27f5479](https://github.com/llvm/llvm-project/commit/27f547968cce89d4706ae2b27a0c15254d1670ee).

+1. It seems that both @mydeveloperday and @djasper would be okay with this, so I've opened a pull request for it.

**Comment by externl** [comment] 2024-05-10 13:58
Is there a setting for this on `18.1.4`? 

Our CI is on `18.1.4` (The latest available in the apt packages. Any known ETA on 18.1.5's?) and the latest on Homebrew is `18.1.5`. This is causing lots of CI failures for us? Any suggestions would be appreciated.

**Comment by owenca** [comment] 2024-05-15 04:37
See #92214.

**Comment by externl** [comment] 2024-05-15 12:31
If I understand correctly, the `18.1.5` behavior is considered a regression?

**Comment by owenca** [comment] 2024-05-16 06:58
Actually, the behavior regressed in 18.1.1 through 18.1.4 and was restored to that of 17.0.6 and earlier in 18.1.5.

**Comment by owenca** [comment] 2024-07-05 06:30
This has been addressed by 8fe39e64c0ef0a1aefce3c1187c5822343caeedd.

**Closed by owenca** 2024-07-05 06:30 UTC
Labels: bug, clang-format, regression
