### ISSUE TITLE
[Flang] Implementation of C_LOC() is incorrect

### ISSUE THREAD

**Issue by psteinfeld** [llvm/llvm-project#58739] opened 2022-11-01 20:44 UTC
The code generated by the intrinsic `C_LOC()` is incorrect.  When calling `C_LOC()` on a variable, the function should return the address of the variable.  

Here's a program that calls the C library function `memcpy()` using the results of calls to `C_LOC()` that illustrates the problem.  This program compiles without error and emits "OK" when executed on gfortran and several other compilers.  When I compile and execute it on Flang, it gets a segmentation fault.

```f90
program test_memcpy
  use iso_c_binding
  interface
    function memcpy(dest, src, len) bind(c)
      import c_ptr
      type(c_ptr), value :: dest, src
      integer(kind=4), value :: len
      type(c_ptr) memcpy
    end
  end interface
  integer(kind=4), target :: src, dest
  type(c_ptr) tmp
  src = 343
  tmp = memcpy(c_loc(dest), c_loc(src), 4)
  if (src .eq. dest) then
    print *, "OK"
  else
    print *, "Bad"
  end if
end
```

Note that the implementation of `C_LOC()` was done in https://reviews.llvm.org/D129659.

Here's another program that contrasts the code that we generate for creating a pointer with `C_LOC()` and by using pointer assignment:

```f90
program contrast
  use iso_c_binding
  integer, target :: var
  integer, pointer :: faddr
  type(c_ptr) caddr

  var = 255
  faddr => var
  var = 127
  caddr = c_loc(var)
  var = 63
end
```

@PeixinQiao, please take note.

**Comment by PeixinQiao** [comment] 2022-11-02 01:01
Will fix this.

**Comment by psteinfeld** [comment] 2022-11-02 01:12
Thanks, @PeixinQiao.  You're the best!

**Comment by PeixinQiao** [comment] 2022-11-02 02:35
@psteinfeld This is not the problem of C_LOC. The problem is the interface of interoperability with C.
```
$ flang-new -fc1 -emit-llvm test.f90 -o test-f18.ll && cat test-f18.ll
...
  call void @memcpy(ptr %1, ptr %8, ptr %10, i32 4)
...
```
This code actually wants to call builtin `memcpy` in C. However, the interface of the `memcpy` is `void *memcpy(void *dest, const void * src, size_t n)`. As the above IR generated, `ptr %1` is the address of the variable `tmp`, `ptr %8` is the address of the `c_loc(dest)`, and so on.

The problem is that the record type is taken as abstract result (https://github.com/llvm/llvm-project/blob/a13122c612a653026b2ac220e220c50783c3aa82/flang/lib/Optimizer/Dialect/FIRType.cpp#L947-L952), and the function type is converted when the function result is an abstract result in AbstractResultOnFuncOpt pass.

This can be fixed by checking `type(c_loc)` for now. One patch will come soon. I had thought the function result of array, struct type is not commonly used in real applications. But the good thing, at least for good quality, is to test all the cases of varying data types for procedure argument and function result since this kind of problems always cause one segmentation fault which is hard to debug. I will try to continue to add and test the missed tests in https://gitee.com/src-openeuler/flang/blob/master/3-test-for-interoperability-with-c-fortran-call-c.patch and https://gitee.com/src-openeuler/flang/blob/master/5-test-for-interoperability-with-c-c-call-fortran.patch.

**Comment by PeixinQiao** [comment] 2022-11-02 10:21
https://reviews.llvm.org/D137236

**Comment by psteinfeld** [comment] 2022-11-02 20:05
Thanks, @PeixinQiao.  Note that change in both https://reviews.llvm.org/D137236 and https://reviews.llvm.org/D137237 are needed to fix this problem.

I have verified that those two patches fix it.  When they have been merged, we can close this issue.

**Comment by PeixinQiao** [comment] 2022-11-03 01:56
Thanks @psteinfeld for the verify.

Note only D137236 is needed to fix the problem in this issue. D137236 and D137237 are both needed to fix the problem in the issue #58756.

There is one problem in this issue, which is the function result rewrite. That is what D137236 wants to fix.
There are two problems in the issue #58756, which are the funtion result rewrite and the argument type.
Please note that the difference between the two test cases in two issues is the `bind(c)` function or `non-bind(c)` function.

**Closed** 2022-11-04 14:17 UTC
Labels: flang:ir

**Comment by psteinfeld** [comment] 2022-11-04 17:54
Thanks for fixing this @PeixinQiao.  The process that I usually follow is that the person who created the issue closes it after verifying that closes the issue after performing the final verification.

**Comment by EugeneZelenko** [comment] 2022-11-04 17:58
@psteinfeld: You could always reopen issue if something was not working on your side.

**Comment by PeixinQiao** [comment] 2022-11-05 03:32
@psteinfeld Sorry for the inconvenience for you. I usually add the keyword `Fix #(issue-num)` in the commit message, which will close the issue automatically. I guess you are tracking your opened issues for the problems to be solved and this is important for you review process. So, I think the better way is to not to add the keyword `Fix #(issue-num)` in the commit message, and to add the commit link to the issue as one comment after pushing the patch. I will do this for the convenience for your tracking process.

**Comment by psteinfeld** [comment] 2022-11-06 15:34
Thanks, @PeixinQiao.  I'm in favor of following a standardized process.  If your actions are what everyone else is doing, let's do that.
