### ISSUE TITLE
[lldb] Printing some pointers causes clang assertion while debugging LLVM tool

### ISSUE THREAD

**Issue by boomanaiden154** [llvm/llvm-project#62972] opened 2023-05-27 20:23 UTC
This is occurring on X86-64 Linux with LLVM commit f104d64616cafe5edb4a18a3d165070e335f5db0 (tip of tree at the time of writing) with an assertions (`LLVM_ENABLE_ASSERTIONS=ON`) build with `CMAKE_BUILD_TYPE` set to `RelWithDebInfo`.

When debugging one of the LLVM programs (`llvm-exegesis`) with lldb (everything compiled with assertions enabled), printing pointers (maybe some? maybe all?) causes an assertion in `clipTailPadding()`. The following is what I get on my machine/setup:
```bash
lldb llvm-exegesis -- -mode=latency --use-dummy-perf-counters -opcode-name=ADD64rr
```
Within `lldb`:
```
(lldb) b BenchmarkRunner.cpp:104
Breakpoint 1: where = llvm-exegesis`void llvm::function_ref<void ()>::callback_fn<llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(llvm::StringRef) const::'lambda'()>(long) + 10 [inlined] llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(llvm::StringRef) const::'lambda'()::operator()() const at BenchmarkRunner.cpp:104:9, address = 0x0000000004f60d4a
(lldb) run
rocess 1540 launched: '/llvm-project/build/bin/llvm-exegesis' (x86_64)
Process 1540 stopped
* thread #1, name = 'llvm-exegesis', stop reason = breakpoint 1.1
    frame #0: 0x0000561426db3d4a llvm-exegesis`void llvm::function_ref<void ()>::callback_fn<llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(llvm::StringRef) const::'lambda'()>(long) [inlined] llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(this=0x00007ffd2b121298) const::'lambda'()::operator()() const at BenchmarkRunner.cpp:104:9
   101        CrashRecoveryContext CRC;
   102        CrashRecoveryContext::Enable();
   103        const bool Crashed = !CRC.RunSafely([this, Counter, ScratchPtr]() {
-> 104          Counter->start();
   105          this->Function(ScratchPtr);
   106          Counter->stop();
   107        });
(lldb) p Counter
lldb: /llvm-project/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp:753: void (anonymous namespace)::CGRecordLowering::clipTailPadding(): Assertion `Prior->Kind == MemberInfo::Field && "Only storage fields have tail padding!"' failed.
LLDB diagnostics will be written to /tmp/diagnostics-22bb98
Please include the directory content when filing a bug report
Aborted (core dumped)
```

This also occurs if I try and print `ScratchPtr` which is of type `char *const`.  This behavior doesn't occur when I use a release build of `lldb` with assertions disabled (same invocation):
```
(lldb) b BenchmarkRunner.cpp:104
Breakpoint 1: where = llvm-exegesis`void llvm::function_ref<void ()>::callback_fn<llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(llvm::StringRef) const::'lambda'()>(long) + 10 [inlined] llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(llvm::StringRef) const::'lambda'()::operator()() const at BenchmarkRunner.cpp:104:9, address = 0x0000000004f60d4a
(lldb) run
Process 8962 launched: '/llvm-project/build/bin/llvm-exegesis' (x86_64)
Process 8962 stopped
* thread #1, name = 'llvm-exegesis', stop reason = breakpoint 1.1
    frame #0: 0x0000562848cded4a llvm-exegesis`void llvm::function_ref<void ()>::callback_fn<llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(llvm::StringRef) const::'lambda'()>(long) [inlined] llvm::exegesis::(anonymous namespace)::FunctionExecutorImpl::runWithCounter(this=0x00007ffc41e04308) const::'lambda'()::operator()() const at BenchmarkRunner.cpp:104:9
   101        CrashRecoveryContext CRC;
   102        CrashRecoveryContext::Enable();
   103        const bool Crashed = !CRC.RunSafely([this, Counter, ScratchPtr]() {
-> 104          Counter->start();
   105          this->Function(ScratchPtr);
   106          Counter->stop();
   107        });
(lldb) p Counter
(llvm::exegesis::pfm::Counter *) 0x000056284b453370
(lldb) p ScratchPtr
(char *const) 0x00007f273fa57400 ""
```

So it seems like the assertion might not be correct, but more investigation is necessary. I realize that this probably isn't a particularly helpful/actionable bug report since there's no MRE and I haven't been able to generalize anything yet. Hoping to get a MRE up soon (assuming I can get one) and better understand the behavior. Just wanted to get the documentation of this started so I have a place to put things.

**Comment by Michael137** [comment] 2023-05-27 22:22
Looks like this happens only when stopped inside a lambda? The expression evaluator has a special code path for this. I'll try to repro this but in the meantime a workaround is to use `frame var counter` instead of the expression evaluator to print variables

**Comment by Michael137** [comment] 2023-05-27 22:25
Probably unrelated since you're just printing raw pointers but this assertion frequently triggers when `[[no_unique_address]]` is involved. There's a discussion on following patch about this: https://reviews.llvm.org/D143347
Hopefully that work will be picked up again soon.

**Comment by Michael137** [comment] 2023-05-27 23:15
Could reproduce it locally on my ubuntu machine with a debug build of LLDB (at commit `44bb442fd5be3860e7819cb216621b5ea59970c3`). I attached the `expr` and `types` log: 
[lldb.log](https://github.com/llvm/llvm-project/files/11583195/lldb.log)

Also confirmed that using `frame var` works around the crash.

(question to self: why did `dwim-print` not use `frame var` here?).

**Comment by Michael137** [comment] 2023-05-28 08:42
Turns out it is related to `[[no_unique_address]]` handling. Applying https://reviews.llvm.org/D143347 fixed it for me locally.
Will see if we can revive the patch.

**Comment by boomanaiden154** [comment] 2023-05-29 06:25
I can confirm that patch fixes it for me as well. Thank you so much for the quick response, reproduction, and further information! I'll watch the patch and see what comes out of it (especially since it was attempted before and nothing ended up landing from that effort).

**Comment by Michael137** [comment] 2024-10-14 14:35
Should be fixed by https://github.com/llvm/llvm-project/pull/96422

**Closed by Michael137** 2024-10-14 14:35 UTC
Labels: lldb
