### ISSUE TITLE
Failed test `ORC-x86_64-darwin :: TestCases/Darwin/x86_64/trivial-cxa-atexit.S` on macOS with 13.0.1-rc2

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#53203] opened 2022-01-14 07:46 UTC
Hi,

While release testing I ran  into this issue:

```
FAIL: ORC-x86_64-darwin :: TestCases/Darwin/x86-64/trivial-cxa-atexit.S (78090 of 91780)
******************** TEST 'ORC-x86_64-darwin :: TestCases/Darwin/x86-64/trivial-cxa-atexit.S' FAILED ********************
Script:
--
: 'RUN: at line 3';      /Users/tobias/code/llvm-releases/13.0.1/rc2/Phase3/Release/llvmCore-13.0.1-rc2.obj/./bin/clang   -arch x86_64 -stdlib=libc++ -mmacosx-version-min=10.10 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk  -c -o /Users/tobias/code/llvm-releases/13.0.1/rc2/Phase3/Release/llvmCore-13.0.1-rc2.obj/projects/compiler-rt/test/orc/X86_64DarwinConfig/TestCases/Darwin/x86-64/Output/trivial-cxa-atexit.S.tmp /Users/tobias/code/llvm-releases/13.0.1/rc2/llvm-project/compiler-rt/test/orc/TestCases/Darwin/x86-64/trivial-cxa-atexit.S
: 'RUN: at line 4';   /Users/tobias/code/llvm-releases/13.0.1/rc2/Phase3/Release/llvmCore-13.0.1-rc2.obj/./bin/llvm-jitlink /Users/tobias/code/llvm-releases/13.0.1/rc2/Phase3/Release/llvmCore-13.0.1-rc2.obj/projects/compiler-rt/test/orc/X86_64DarwinConfig/TestCases/Darwin/x86-64/Output/trivial-cxa-atexit.S.tmp
--
Exit Code: 1

Command Output (stderr):
--
JIT session error: Symbols not found: [ _llvm_jitlink_setTestResultOverride ]
/Users/tobias/code/llvm-releases/13.0.1/rc2/Phase3/Release/llvmCore-13.0.1-rc2.obj/./bin/llvm-jitlink: Failed to materialize symbols: { (main, { _onExit, _main, __ZN6OnExitD1Ev }) }

```

Is this a blocker for 13.0.1?

**Comment by benlangmuir** [comment] 2022-01-14 18:49
@tru I was not able to reproduce this issue in the llvmorg-13.0.1-rc2 tag or in main. Could you share your cmake config?

> Is this a blocker for 13.0.1?

There are no changes to orc or the orc runtime between 13.0 and 13.0.1-rc2, so I suspect this is not a regression but a config change or something.

Incidentally, the version of the ORC runtime in 13.0.* has some debug `fprintf(stderr` that was later fixed on main 😭 

CC @lhames

**Comment by tru** [comment] 2022-01-18 10:23
I went back and looked and this is not a regression in the latest version. It's happening all the way back in 13.0.0-rc4 - it's the oldest version of logs I have around.

My CMakeCache.txt is here: https://gist.github.com/47022e217b08861fcaa1c8a8eaecb012

**Comment by benlangmuir** [comment] 2022-01-18 22:31
Reproduced in a release build of 13.0.1-rc2.  `llvm_jitlink_setTestResultOverride` is getting dead-stripped.  This issue only impacts our tests. Fix: https://reviews.llvm.org/D117609

**Closed** 2022-01-18 23:57 UTC
Labels: test-suite, orcjit, platform:macos
