### ISSUE TITLE
[clangd] Support for configuring the path to store PCH files.

### ISSUE THREAD

**Issue by memchr** [llvm/llvm-project#65029] opened 2023-08-28 01:36 UTC
### Feature Request

Configure the path for storing PCH files through command line flags or a configuration file.

### Motivation
At present, clangd stores `preamble-*.pch` files in `/tmp`, which is commonly mounted on many Linux distributions as [tmpfs](https://en.wikipedia.org/wiki/Tmpfs), a file system that stores data in volatile memory.

As has been reported several times, clangd sometimes fills the /tmp directory with relatively large preamble pch files and leaves them behind.

Since tmpfs uses volatile memory, OOM kills can potentially occur.

### Workarounds

As a workaround, it has been suggested to set a preferred path for **TMPDIR** when starting LSP clients or clangd. Nevertheless, this could lead to unintended results as **TMPDIR** is a canonical POSIX environmental variable that affects more than just clangd. 

Additionally, it could be inconvenient or impractical to set TMPDIR exclusively for clangd or LSP clients like vscode. With a command line flag, one can use `clangd.arguments` to determine the storage location for PCH files.

Thank you for your time and effort.

---

related: #51831

**Comment by HighCommander4** [comment] 2023-08-28 04:36
> Additionally, it could be inconvenient or impractical to set TMPDIR exclusively for clangd or LSP clients like vscode

For completeness, it's been suggested (in https://github.com/clangd/vscode-clangd/issues/198 and related issues) that vscode-clangd gain a new `clangd.env` setting to allow specifying environment variables for vscode to add to clangd's environment when invoking it.

If that were implemented, would you consider that a satisfactory solution to this issue?

**Comment by memchr** [comment] 2023-08-28 12:01
>For completeness, it's been suggested (in https://github.com/clangd/vscode-clangd/issues/198 and related issues) that vscode-clangd gain a new clangd.env setting to allow specifying environment variables for vscode to add to clangd's environment when invoking it

As a workaround, I am currently using a wrapper script that calls clangd with the TMPDIR variable set to the desired path.

`clangd.env` has its values and can be used as a more convenient approach, although I think it could still be regarded a workaround due to of the nature of the TMPDIR variable.

However, I do consider it to be a more **acceptable solution** than the workarounds currently available.

**Comment by HighCommander4** [comment] 2023-08-30 06:11
If we go with a server-side configuration option, an open question is whether to make it a command-line argument or a config file option.

We've been moving away from command-line configuration and towards config file, so I'd say the config file is the default choice for new options, but in this case we have the closely related `--pch-storage` option which is a command-line argument; we may want to keep them together.

**Comment by HighCommander4** [comment] 2024-05-11 07:34
Found an older issue thread about this: https://github.com/clangd/clangd/issues/255. I'll dupe this one over.

**Comment by HighCommander4** [comment] 2024-05-11 07:34
Duplicate of https://github.com/clangd/clangd/issues/255

**Closed by HighCommander4** 2024-05-11 07:34 UTC
Labels: enhancement, clangd
