### ISSUE TITLE
[OpenMP] complex reduction failure on AMD GPU

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#52706] opened 2021-12-15 00:26 UTC
reproducer code https://github.com/ye-luo/openmp-target/blob/master/tests/complex/complex_reduction.cpp
```
$ clang++ -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx906 -fopenmp-target-new-runtime -O3 complex_reduction.cpp -lm
$ ./a.out 
Testing float
hierarchical parallelism wrong reduction value check(0,0) correct value (4950,-4950)
Testing double
hierarchical parallelism wrong reduction value check(0,0) correct value (4950,-4950)
```
On a different machine with MI50, different OS. I got
```
[GPU Memory Error] Addr: 0x7f0613e00000 Reason: Page not present or supervisor privilege. 
Memory access fault by GPU node-2 (Agent handle: 0x1b883b0) on address 0x7f0613e00000. Reason: Page not present or supervisor privilege.
```

**Comment by jdoerfert** [comment] 2022-02-16 22:36
I'm assuming/hoping this is fixed on mainline now.

**Comment by ye-luo** [comment] 2022-02-18 05:59
Still got zero with 06f346cb7238fff88b2c7f94bf55fde50de5c1dd

**Comment by jdoerfert** [comment] 2022-03-23 21:49
This worked for me now. I think the manual unroll (https://reviews.llvm.org/rGa619072c6189a2eac82e30d5ebb5946cb1297281) hides the error. I further believe the AMD backend pass transforming allocas to vectors is the problem, or better the handling of pointer vectors by the backend. (Fyi @arsenm)

**Comment by arsenm** [comment] 2022-04-08 13:15
> This worked for me now. I think the manual unroll ([a619072](https://github.com/llvm/llvm-project/commit/a619072c6189a2eac82e30d5ebb5946cb1297281)) hides the error. I further believe the AMD backend pass transforming allocas to vectors is the problem, or better the handling of pointer vectors by the backend. (Fyi @arsenm)

I tried reverting this patch and I'm not seeing anything. Do you have the failing IR/ISA from when this was broken?

**Comment by arsenm** [comment] 2022-12-30 01:06
> > This worked for me now. I think the manual unroll ([a619072](https://github.com/llvm/llvm-project/commit/a619072c6189a2eac82e30d5ebb5946cb1297281)) hides the error. I further believe the AMD backend pass transforming allocas to vectors is the problem, or better the handling of pointer vectors by the backend. (Fyi @arsenm)
> 
> I tried reverting this patch and I'm not seeing anything. Do you have the failing IR/ISA from when this was broken?

Ping, do you have the before/after sample IR/ISA?

**Comment by ye-luo** [comment] 2022-12-30 02:36
This issue is obsolete. The most recent breakage was reported as https://github.com/llvm/llvm-project/issues/58774

**Comment by arsenm** [comment] 2022-12-30 13:46
> This issue is obsolete. The most recent breakage was reported as #58774

My understanding is the backend failure was worked around with a loop unroll, indicating there is still something broken here

**Comment by ye-luo** [comment] 2022-12-30 15:35
https://github.com/llvm/llvm-project/commit/06f346cb7238fff88b2c7f94bf55fde50de5c1dd was known to fail the reproducer.

**Comment by arsenm** [comment] 2022-12-31 14:11
Confirmed still broken with a619072c6189a2eac82e30d5ebb5946cb1297281 reverted and everything else current. It's a null dereference at this flat load
```
   0x00007ffef4557f30 <+1072>:	s_cbranch_execz 65523  # 0x7ffef4557f00 <__omp_offloading_fd00_194b419__Z14test_reductionISt7complexIfEEvv_l65+1024>
   0x00007ffef4557f34 <+1076>:	v_mov_b32_e32 v9, v22
   0x00007ffef4557f38 <+1080>:	s_mov_b32 s13, 0
   0x00007ffef4557f3c <+1084>:	s_nop 0
   0x00007ffef4557f40 <+1088>:	v_add_nc_u32_e32 v24, v21, v9
   0x00007ffef4557f44 <+1092>:	v_add_nc_u32_e32 v9, 1, v9
   0x00007ffef4557f48 <+1096>:	v_ashrrev_i32_e32 v25, 31, v24
   0x00007ffef4557f4c <+1100>:	v_lshlrev_b64 v[24:25], 3, v[24:25]
   0x00007ffef4557f54 <+1108>:	v_add_co_u32 v24, vcc_lo, v4, v24
   0x00007ffef4557f5c <+1116>:	v_add_co_ci_u32_e32 v25, vcc_lo, v5, v25, vcc_lo
   0x00007ffef4557f60 <+1120>:	v_cmp_ge_u32_e32 vcc_lo, v9, v23
   0x00007ffef4557f64 <+1124>:	flat_load_dwordx2 v[24:25], v[24:25]
   0x00007ffef4557f6c <+1132>:	s_or_b32 s13, vcc_lo, s13
   0x00007ffef4557f70 <+1136>:	s_waitcnt vmcnt(0) lgkmcnt(0)
=> 0x00007ffef4557f74 <+1140>:	v_add_f32_e32 v19, v24, v19
   0x00007ffef4557f78 <+1144>:	v_add_f32_e32 v20, v25, v20
   0x00007ffef4557f7c <+1148>:	s_andn2_b32 exec_lo, exec_lo, s13
   0x00007ffef4557f80 <+1152>:	s_cbranch_execnz 65519  # 0x7ffef4557f40 <__omp_offloading_fd00_194b419__Z14test_reductionISt7complexIfEEvv_l65+1088>
   0x00007ffef4557f84 <+1156>:	s_or_b32 exec_lo, exec_lo, s13
   0x00007ffef4557f88 <+1160>:	s_branch 65501  # 0x7ffef4557f00 <__omp_offloading_fd00_194b419__Z14test_reductionISt7complexIfEEvv_l65+1024>
   0x00007ffef4557f8c <+1164>:	s_inst_prefetch 0x2
   0x00007ffef4557f90 <+1168>:	s_or_b32 exec_lo, exec_lo, s3
   0x00007ffef4557f94 <+1172>:	s_or_b32 exec_lo, exec_lo, s2
   0x00007ffef4557f98 <+1176>:	v_mov_b32_e32 v4, s10
   0x00007ffef4557f9c <+1180>:	v_mov_b32_e32 v5, s11
   0x00007ffef4557fa0 <+1184>:	s_andn2_b32 vcc_lo, exec_lo, s1
```

Upsettingly this works if you compile with -g

**Comment by arsenm** [comment] 2022-12-31 14:17
> Upsettingly this works if you compile with -g
Even more upsetting is it goes back to broken with -save-temps -g

**Comment by jhuber6** [comment] 2023-01-03 16:17
> The state of the openmp driver is slowing me down. -save-temps is definitely broken, in that it doesn't produce .s files and sometimes changes the observed behavior. Also hiding the lld invocation I need to exactly reproduce the output inside clang-linker-wrapper is also annoying.

It's a bit of a complicated mess. There are some extra flags that get added when `-save-temps` is on, specifically `-disable-llvm-passes`, that change the IR. This seems to be intentional so I'm assuming we shouldn't change it. It's also difficult because we don't generate `.s` files for AMDGPU at any point in the entire pipeline. Since we use LLVM-IR as our object format and just go straight to an object file. The linker wrapper will spit out some temporary files in `-save-temps` mode. To try to get some `ASM` the following might work.

```
clang foo.c -fopenmp --offload-arch=gfx1030 -Wl,--save-temps -o exe
opt -O3 exe-device-amdgcn-amd-amdhsa-gfx1030.bc -o opt.bc
llc opt.bc -o opt.s
```
You should be able to use `-Wl,` to only make the linker wrapper save its temp files and leave the rest alone.

**Comment by jhuber6** [comment] 2023-01-03 16:19
We could make the linker wrapper emit assembly in `save-temps` mode and call `llc` manually to complete the linking. That might make this easier.

**Comment by arsenm** [comment] 2023-01-03 16:39
The produced bitcode files also are from an unclear point in the pass pipeline. The names don't help me figure out what point in the pipeline they're from. The one I would assume is the one I want is unoptimized bitcode. For comparison, HIP produces *.precodegen.bc which is what I'm interested in 80% of the time. That approximately does correspond to what input llc would see. The only reason I care about what the driver is doing is to figure out how to get this pre-codegen bitcode

**Comment by jhuber6** [comment] 2023-01-03 16:50
> This is nonsense, -save-temps should have identical behavior. This absolutely should change.
>
This seems to be where it was first introduced https://github.com/llvm/llvm-project/commit/23a55f1eeeb15ef6b8002e98e90cd025d53c97f2. It seemed very intentional and it's been there for quite some time so I figured that it's the desired behavior.

> You can codegen to asm and then assemble the output, or just codegen twice.
I think we'll want to just make the LTO pass spit out assembly instead. Then feed that assembly to the assembler machine. 

> llc and opt should never be invoked by a driver. The exact same clang or lld invocation, aside from the output format, needs to be used.
Is much liable to change if we already have an assembly file? I'll need to check if there are different passes that the LTO pass uses to generate the object file.

> The produced bitcode files also are from an unclear point in the pass pipeline. The names don't help me figure out what point in the pipeline they're from. The one I would assume is the one I want is unoptimized bitcode. For comparison, HIP produces *.precodegen.bc which is what I'm interested in 80% of the time. That approximately does correspond to what input llc would see. The only reason I care about what the driver is doing is to figure out how to get this pre-codegen bitcode
We could probably improve the names to be a little more descriptive. Right now something like `<exe>-device-<triple>-<cpu>.bc` is what post-link LTO will spit out, which is what gets fed to the backend. Maybe something more like `<exe>.<triple>.<arch>.postlink.bc`?

**Comment by arsenm** [comment] 2023-01-03 17:09
> > This is nonsense, -save-temps should have identical behavior. This absolutely should change.
> 
> This seems to be where it was first introduced [23a55f1](https://github.com/llvm/llvm-project/commit/23a55f1eeeb15ef6b8002e98e90cd025d53c97f2). It seemed very intentional and it's been there for quite some time so I figured that it's the desired behavior.
> 

The part that's important is being able to get an identical compilation from whatever it produces. It's reasonable to output the IR with -disable-llvm-passes as one of the temps, as long as a follow up clang invocation on that bitcode runs exactly the same pass pipeline as would have happened without it.

> > You can codegen to asm and then assemble the output, or just codegen twice.
> 
> I think we'll want to just make the LTO pass spit out assembly instead. Then feed that assembly to the assembler machine.
> 
Yes, same thing


> > llc and opt should never be invoked by a driver. The exact same clang or lld invocation, aside from the output format, needs to be used.

> 
> Is much liable to change if we already have an assembly file? I'll need to check if there are different passes that the LTO pass uses to generate the object file.
> 
If you already have assembly everything's done? I guess there's the final post-lld .so vs. .o. I rarely ever need to think about the difference. Regardless, opt and llc should still never be used and are for lit tests only. clang or lld should be driving whatever processes are happening


> > The produced bitcode files also are from an unclear point in the pass pipeline. The names don't help me figure out what point in the pipeline they're from. The one I would assume is the one I want is unoptimized bitcode. For comparison, HIP produces *.precodegen.bc which is what I'm interested in 80% of the time. That approximately does correspond to what input llc would see. The only reason I care about what the driver is doing is to figure out how to get this pre-codegen bitcode
> 
> We could probably improve the names to be a little more descriptive. Right now something like `<exe>-device-<triple>-<cpu>.bc` is what post-link LTO will spit out, which is what gets fed to the backend. Maybe something more like `<exe>.<triple>.<arch>.postlink.bc`?

Yes, I think this is the most important thing. Getting the bitcode immediately after clang, and right before codegen are the most interesting pieces usually.

**Comment by jdoerfert** [comment] 2023-01-04 23:37
Are these OpenMP LDS globals? Can you share/send the two IR files, I can take a look. Is LTO (implicitly or explicitly) on for one of the cases and that causes different results? I mean, once we internalize things during LTO we often get better results.

**Comment by arsenm** [comment] 2023-01-04 23:55
[issue52706-debug.zip](https://github.com/llvm/llvm-project/files/10348287/issue52706-debug.zip)

Includes reverting the argument loop change, and manually adding some noinlines. Only difference between the two was using -save-temps

Also -g seem to not add debug info to the device code

**Comment by jdoerfert** [comment] 2023-01-05 00:15
In both versions I see 15 times "Allocated @... = internal addrspace(3) ... at ..." and the initial globals are the same. Where did you see the linkage difference?

**Comment by arsenm** [comment] 2023-01-05 00:18
with_save_temps_lower_module.ll:
```
@_shared = internal addrspace(3) global [16 x i8] undef, align 16
@_shared.1 = internal addrspace(3) global [4 x i8] undef, align 16
@_shared.2 = internal addrspace(3) global [4 x i8] undef, align 16
@_shared.3 = internal addrspace(3) global [8 x i8] undef, align 16
@_shared.4 = internal addrspace(3) global [4 x i8] undef, align 16
@_shared.5 = internal addrspace(3) global [4 x i8] undef, align 16
@__omp_outlined__.6_wrapper.ID = private addrspace(1) constant i8 undef
```

no_save_temps_lower_module.ll:
```
@istart_shared = internal addrspace(3) global [4 x i8] undef, align 16
@iend_shared = internal addrspace(3) global [4 x i8] undef, align 16
@partial_sum_shared = internal addrspace(3) global [16 x i8] undef, align 16
@istart_shared.102 = internal addrspace(3) global [4 x i8] undef, align 16
@iend_shared.103 = internal addrspace(3) global [4 x i8] undef, align 16
@partial_sum_shared.104 = internal addrspace(3) global [8 x i8] undef, align 16
@__omp_outlined__.24_wrapper.ID = private addrspace(1) constant i8 undef

```

More relevant to the real issue here beyond save-temps being broken, I think deleting the code in __assert_assume is potentially more interesting

**Comment by jdoerfert** [comment] 2023-01-05 05:14
Those are the same globals, just w/o names, which doesn't matter since they are internal. so it's the "-g" thing.
What about deleting __assert_assume is potentially broken? Where in the log can I find that issue?

**Comment by arsenm** [comment] 2023-01-05 22:38
> Those are the same globals, just w/o names, which doesn't matter since they are internal. so it's the "-g" thing. What about deleting __assert_assume is potentially broken? Where in the log can I find that issue?

The IR is radically different between save temps and not, there's no -g involved (it seems to not do anything to the device code)

I need to post different temps for the with/without assume

**Comment by arsenm** [comment] 2023-01-05 23:12
If I disable all ASSERT()s in libomptarget, except for the ones in  __kmpc_kernel_end_parallel, it passes. With the assumes the final ISA is about ~3x bigger

**Comment by arsenm** [comment] 2023-01-05 23:56
[reduced_assume_.zip](https://github.com/llvm/llvm-project/files/10356369/reduced_assume_.zip)
Attached build with hacked up libomptarget, failing version has one additional pair of assumes in  __kmpc_kernel_end_parallel

**Comment by arsenm** [comment] 2023-01-06 00:13
```
  tail call void @llvm.amdgcn.s.barrier()
  %i56 = mul i32 %i53, 10
  tail call void @llvm.amdgcn.s.barrier()
  tail call void @llvm.amdgcn.s.barrier()
```
Seem to be missing a redundant barrier removal optimization

**Comment by jdoerfert** [comment] 2023-01-06 23:18
> ```
>   tail call void @llvm.amdgcn.s.barrier()
>   %i56 = mul i32 %i53, 10
>   tail call void @llvm.amdgcn.s.barrier()
>   tail call void @llvm.amdgcn.s.barrier()
> ```
> 
> Seem to be missing a redundant barrier removal optimization

Without context you cannot tell these are redundant. Unfortunately amdgcn has no explicit aligned barrier, that would make it easier to tell.

--- 

I'm looking at the reduced_assume.zip now

**Comment by jdoerfert** [comment] 2023-01-07 07:59
On my gfx90a I saw this problem after reverting the loop unroll patch. Applying [this](https://discourse.llvm.org/t/intrinsics-are-not-special-stop-pretending-i-mean-it/67545?u=jdoerfert) made it go away. I think we can put this issue to rest as soon as that proposal (or an alternative) gets in.

**Closed** 2023-01-10 19:39 UTC
Labels: openmp, backend:AMDGPU
