### ISSUE TITLE
[clang-format] always auto add a space after '@'

### ISSUE THREAD

**Issue by D-artagna** [llvm/llvm-project#78839] opened 2024-01-20 10:22 UTC
![2024-01-16_23-37](https://github.com/llvm/llvm-project/assets/146019002/14f8d526-9371-4543-b48f-0d31a3b9e32e)
![2024-01-16_23-38](https://github.com/llvm/llvm-project/assets/146019002/bee31ec9-3f93-49da-8ac0-07a4e840b97a)
I use "@Project_VERSION_MAJOR@" to express a value, but clang-format engine always add a space after the second '@', and compiler cannot identify "@Project_VERSION_MAJOR @".

**Comment by rymiel** [comment] 2024-01-20 13:02
Duplicate of https://github.com/llvm/llvm-project/issues/59851

**Closed by rymiel** 2024-01-20 13:02 UTC
Labels: clang-format
