### ISSUE TITLE
-Wformat too aggressive on variadic templates with __attribute__((format))

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#64704] opened 2023-08-15 12:08 UTC
@apple-fcloutier's 92edd74b37c7a96b1d47dc67cda7f92b65066025 made it possible to put `__attribute__((format))` on variadic templates.

In https://crbug.com/1472532 @pkasting raised an interesting point that because arguments to such templates don't undergo the same promotion that arguments to the regular printf/scanf varargs do, the warning becomes more aggressive https://godbolt.org/z/ajE5cYhKM:

```C++
template <typename... Args>
void __attribute__((format(printf, 1, 2))) variadic_template_printf(const char* format, Args&&... args) {
  // ...
}

void foo(float f) {
  variadic_template_printf("f: %f", f);
}
```

```
<source>:7:37: warning: format specifies type 'double' but the argument has type 'float' [-Wformat]
    7 |   variadic_template_printf("f: %f", f);
      |                                ~~   ^
      |                                %f
1 warning generated.
Compiler returned: 0
```

Providing a float value for a `%f` conversion with printf is allowed since it will get promoted to double, but that doesn't work with this template function. And there doesn't seem to be any good way of working around the warning!

Perhaps -Wformat needs to be relaxed somehow for this case?

**Comment by inclyc** [comment] 2023-08-16 09:18
Duplicate of https://github.com/llvm/llvm-project/issues/59824

**Closed by inclyc** 2023-08-16 09:18 UTC
Labels: clang:diagnostics
