### ISSUE TITLE
Enhancement for clang-tidy readability-redundant-string-cstr check #59255 (more clear code , good readability)

### ISSUE THREAD

**Issue by deeptirajora** [llvm/llvm-project#86490] opened 2024-03-25 11:22 UTC
The issue in the code was that it used the `c_str()` function unnecessarily when creating std::string_view and std::filesystem::path  objects. The  c_str()  function is typically used to obtain a C-style string from a  std::string, but in this context, it wasn't required. This could make the code less clear and may confuse readers, as it suggests that the code is dealing with C-style strings instead of C++ string data types.

i think it should be like this :

#include <string>
#include <filesystem>
int main()
{
std::string s("foo");
std::string t(s);
std::string_view u(s);
std::filesystem::path v(s);
(void)t;
(void)u;
(void)v;
return 0;
}

**Comment by EugeneZelenko** [comment] 2024-03-25 13:26
Duplicate of #25244.

**Closed** 2024-03-25 13:27 UTC
Labels: duplicate, clang-tidy
