### ISSUE TITLE
llvm-15.0.0-rc2 build fails on MacOS (Catalina) - build attempted via spack

### ISSUE THREAD

**Issue by balay** [llvm/llvm-project#57362] opened 2022-08-25 16:12 UTC
Note: `llvm@14.0.6` builds fine on the same box - (via spack)
```console
balay@ypro spack % ./bin/spack install llvm@15.0.0-rc2
<snip>
==> Installing llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua
==> No binary for llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua found: installing from source
==> Using cached archive: /Users/balay/spack/var/spack/cache/_source-cache/archive/4a/4a095a4988387ba5f25a11eb6f202c84ce0140389d663d6130345663577b9e00.tar.gz
==> No patches needed for llvm
==> llvm: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/cmake-3.23.3-2gclikxqwk6t4rb3pr5rflb2udoamjt5/bin/cmake' '-G' 'Ninja' '-DCMAKE_INSTALL_PREFIX:STRING=/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_FIND_FRAMEWORK:STRING=LAST' '-DCMAKE_FIND_APPBUNDLE:STRING=LAST' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua/lib;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua/lib64;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/hwloc-2.8.0-yniblvnantnctu3kikjpfzxkmagnnccl/lib;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/libxml2-2.9.13-tknjdyandygb5bfjgc2droicr6wfscx3/lib;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/libiconv-1.16-j53skaaulyd6jojdwyoruibxoedzrzow/lib;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/xz-5.2.5-4icklcdxlcrmnq6mvzuuecxbptyolsxt/lib;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/zlib-1.2.12-xg25rcxmky4rcnvppvjcthvnraggusqu/lib;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/ncurses-6.3-mht5dfiqkxwnjs2fbhxo6l4cslvduqtu/lib;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/libedit-3.1-20210216-us7v6k5ec44isuwf2fgwcy4wecyuo62f/lib' '-DCMAKE_PREFIX_PATH:STRING=/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/perl-data-dumper-2.173-e3g24kya5v26yuqi3l4jhvirx7pgblmm;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/ninja-1.11.0-6h3upkylwxkvqt7mgiv4tfcr7xmfttyf;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/python-3.9.13-y3nvmrk24dr5j4ewlw2db43u4rmdv3rz;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/libedit-3.1-20210216-us7v6k5ec44isuwf2fgwcy4wecyuo62f;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/hwloc-2.8.0-yniblvnantnctu3kikjpfzxkmagnnccl;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/libxml2-2.9.13-tknjdyandygb5bfjgc2droicr6wfscx3;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/xz-5.2.5-4icklcdxlcrmnq6mvzuuecxbptyolsxt;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/cmake-3.23.3-2gclikxqwk6t4rb3pr5rflb2udoamjt5;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/zlib-1.2.12-xg25rcxmky4rcnvppvjcthvnraggusqu;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/libiconv-1.16-j53skaaulyd6jojdwyoruibxoedzrzow;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/ncurses-6.3-mht5dfiqkxwnjs2fbhxo6l4cslvduqtu;/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/pkgconf-1.8.0-7xytetcdzmc7iyi4figp74ktzxzum5op' '-DLLVM_REQUIRES_RTTI:BOOL=ON' '-DLLVM_ENABLE_RTTI:BOOL=ON' '-DLLVM_ENABLE_EH:BOOL=ON' '-DLLVM_ENABLE_LIBXML2:BOOL=OFF' '-DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libomp' '-DPYTHON_EXECUTABLE:STRING=/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/python-3.9.13-y3nvmrk24dr5j4ewlw2db43u4rmdv3rz/bin/python3.9' '-DLIBOMP_USE_HWLOC:BOOL=ON' '-DLIBOMP_HWLOC_INSTALL_DIR:STRING=/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/hwloc-2.8.0-yniblvnantnctu3kikjpfzxkmagnnccl' '-DPython3_EXECUTABLE:STRING=/Users/balay/spack/opt/spack/darwin-catalina-skylake/apple-clang-12.0.0/python-3.9.13-y3nvmrk24dr5j4ewlw2db43u4rmdv3rz/bin/python3.9' '-DCUDA_TOOLKIT_ROOT_DIR:STRING=IGNORE' '-DCUDA_SDK_ROOT_DIR:STRING=IGNORE' '-DCUDA_NVCC_EXECUTABLE:STRING=IGNORE' '-DLIBOMPTARGET_DEP_CUDA_DRIVER_LIBRARIES:STRING=IGNORE' '-DLIBOMPTARGET_ENABLE_DEBUG:BOOL=OFF' '-DLLDB_ENABLE_LIBEDIT:BOOL=ON' '-DLLDB_ENABLE_CURSES:BOOL=ON' '-DLLVM_ENABLE_TERMINFO:BOOL=ON' '-DLLDB_ENABLE_LIBXML2:BOOL=OFF' '-DLLDB_ENABLE_PYTHON:BOOL=OFF' '-DLLVM_ENABLE_Z3_SOLVER:BOOL=OFF' '-DLINK_POLLY_INTO_TOOLS:BOOL=ON' '-DBUILD_SHARED_LIBS:BOOL=OFF' '-DLLVM_BUILD_LLVM_DYLIB:BOOL=ON' '-DLLVM_LINK_LLVM_DYLIB:BOOL=OFF' '-DLLVM_USE_SPLIT_DWARF:BOOL=OFF' '-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY:BOOL=ON' '-DLLVM_TARGETS_TO_BUILD:STRING=X86' '-DLIBOMP_TSAN_SUPPORT:BOOL=OFF' '-DLLDB_USE_SYSTEM_DEBUGSERVER:BOOL=ON' '-DLLVM_ENABLE_PROJECTS:STRING=lldb;clang;clang-tools-extra;lld;compiler-rt;libcxx;libcxxabi;libunwind;polly' '-DLLVM_ENABLE_RUNTIMES:STRING=openmp' '/private/var/folders/nt/_m1t_x7j76q6sl3xt91tqgs00000gn/T/balay/spack-stage/spack-stage-llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua/spack-src/llvm'

1 error found in build log:
     658    -- Checking DARWIN_watchsimulator_SYSROOT - ''
     659    -- Checking DARWIN_watchos_SYSROOT - ''
     660    -- Checking DARWIN_appletvsimulator_SYSROOT - ''
     661    -- Checking DARWIN_appletvos_SYSROOT - ''
     662    -- No arm64 support in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/SDKSettings.plist
     663    -- No arm64e support in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/SDKSettings.plist
  >> 664    CMake Error at /private/var/folders/nt/_m1t_x7j76q6sl3xt91tqgs00000gn/T/balay/spack-stage/spack-stage-llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua/spack-src/compiler-rt/cmake/Modules/CompilerRTD
            arwinUtils.cmake:73 (message):
     665      Failed to determine SDK version for "iphonesimulator" SDK
     666    Call Stack (most recent call first):
     667      /private/var/folders/nt/_m1t_x7j76q6sl3xt91tqgs00000gn/T/balay/spack-stage/spack-stage-llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua/spack-src/compiler-rt/cmake/builtin-config-ix.cmake:120 (fin
            d_darwin_sdk_version)
     668      /private/var/folders/nt/_m1t_x7j76q6sl3xt91tqgs00000gn/T/balay/spack-stage/spack-stage-llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua/spack-src/compiler-rt/lib/builtins/CMakeLists.txt:51 (includ
            e)
     669
     670

See build log for details:
  /var/folders/nt/_m1t_x7j76q6sl3xt91tqgs00000gn/T/balay/spack-stage/spack-stage-llvm-15.0.0-rc2-n2yfv6goqsw5z6hqjualkuziie5in4ua/spack-build-out.txt
```
[spack-build-out.txt](https://github.com/llvm/llvm-project/files/9426490/spack-build-out.txt)

**Comment by carlocab** [comment] 2022-08-25 17:39
You need an Xcode installation to build 15.0.0-rc2. The CLT alone does not suffice. I've been meaning to file an issue about this, but I haven't gotten around to it. But this is a regression against 14.0.6.

The errant commit seems to be https://github.com/llvm/llvm-project/commit/a680c212cb213bf73be7d3e2ee919fdc743cef0c.

A workaround is to pass
```
-DBUILTINS_CMAKE_ARGS=-DCOMPILER_RT_ENABLE_IOS=OFF
```
to your `cmake` invocation, if you don't want to use a full Xcode installation.

Related discussion at Homebrew/homebrew-core#106925.

**Comment by carlocab** [comment] 2022-08-25 17:49
Oh, actually this is a dupe of #57037.

**Closed** 2022-08-25 17:52 UTC
Labels: duplicate, build-problem, platform:macos
