### ISSUE TITLE
[Clang-CL] source_location is not available in clang-cl tool with /std:c++20

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#60347] opened 2023-01-28 01:02 UTC
A clang tool on Windows uses clang-cl, which uses the MSVC library, and the `<source_location>` header contains this:

```cpp
#pragma once
#ifndef _SOURCE_LOCATION_
#define _SOURCE_LOCATION_
#include <yvals_core.h>
#if _STL_COMPILER_PREPROCESSOR
#ifndef __cpp_consteval
_EMIT_STL_WARNING(STL4038, "The contents of <source_location> are available only with C++20 consteval support.");
#else // ^^^ !defined(__cpp_consteval) / defined(__cpp_consteval) vvv
```

If I pass `/D__cpp_consteval` then source_location is there. As consteval is supported in Clang with C++20, should clang-cl tooling automatically set this define?

This is possibly related to https://github.com/llvm/llvm-project/issues/59689 where `_CRT_USE_BUILTIN_OFFSETOF` is not defined in a clang-cl tool.

**Comment by alvinhochun** [comment] 2023-01-28 10:11
Related to #57094

**Comment by AaronBallman** [comment] 2023-02-22 15:35
Duplicate of #57094

**Closed by AaronBallman** 2023-02-22 15:35 UTC
Labels: duplicate, c++20, clang-cl, consteval
