### ISSUE TITLE
Error when structured binding an array type by {} initialization

### ISSUE THREAD

**Issue by 992678220** [llvm/llvm-project#53365] opened 2022-01-23 12:30 UTC
I've tried the below code in Compiler Explorer. Both msvc and gcc compile but clang cannot. (I've tried almost every clang's version)

```
void f() {
  int a[2]{1, 2};
  auto [x, y]{a};
}
```

https://godbolt.org/z/qWWe3M6MG

**Comment by frederick-vs-ja** [comment] 2022-04-18 14:42
Duplicate of #31813.

**Closed** 2022-04-18 14:50 UTC
Labels: duplicate, clang:frontend
