### ISSUE TITLE
Wrong code at -O1 on x86_64-linux_gnu

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#57497] opened 2022-09-01 12:21 UTC
```console
% clang-tk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project.git 92c4172756b33094aaa140879a861562b0114927)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /zdata/shaoli/compilers/ccbuilder-compilers
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
%
% clang-tk -O0 a.c && ./a.out
0
0
8
0
0
0
0
0
%
% clang-tk -O1 a.c && ./a.out
0
0
-1
0
0
0
0
0
%
% cat a.c
int printf(const char *, ...);
short b[8][1] = {{}, {}, 9};
int c, d, e, h, i;
int *f = &c;
int **g = &f;
int j(int k) {
  if (k < 8)
    k;
  else if (k < 9)
    ;
  else if (k < 9 + 3)
    k -= 4;
  return k;
}
int main() {
l:
  **g = --b[2][0];
  e = 4;
  for (; e < 1; --e)
    for (; h;)
      ;
  if (j(e))
    g = &e;
  else if (d)
    goto l;
  for (; i < 8; i++)
    printf("%d\n", b[i][0]);
}
% 
```
Compiler explorer : https://godbolt.org/z/TEP94acs4

**Comment by RKSimon** [comment] 2022-09-01 14:59
@shao-hua-li Is this a recent change?

**Comment by shao-hua-li** [comment] 2022-09-01 15:05
> @shao-hua-li Is this a recent change?

I believe so. At least clang-14/13/12/11/10/9 from CompilerExplorer do not have this issue.

**Comment by shao-hua-li** [comment] 2022-09-02 08:46
Here is a cleaned up testcase that triggered the same issue:
```console
% cat small.c
int printf(const char *, ...);
short a = 1;
int b, c, d, *e = &b;
int f(int g) {
 if (g < 8)
  g;
 else if (g >= 9 && g < 11)
  g--;
 return g;
}
int main() {
 L:
 *e = --a;
 for (d = 1; d < 1; d--)
  while (c)
   ;
 if (f(d))
  e = &d;
 else if (c)
  goto L;
 printf("%d\n", a);
 return 0;
}
%
% clang-tk -O0 -w small.c; ./a.out
0
% clang-tk -O1 -w small.c; ./a.out
-1
%
```

**Comment by nikic** [comment] 2022-09-02 10:52
```
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@a = dso_local local_unnamed_addr global i16 1, align 2
@c = dso_local local_unnamed_addr global i32 0, align 4
@b = dso_local global i32 0, align 4
@e = dso_local local_unnamed_addr global ptr @b, align 8
@d = dso_local global i32 0, align 4

define i32 @main() {
entry: 
  %0 = load ptr, ptr @e, align 8
  %a.promoted = load i16, ptr @a, align 2
  br label %L

L:                                                ; preds = %if.else, %entry
  %dec15 = phi i16 [ %dec, %if.else ], [ %a.promoted, %entry ]
  %dec = add i16 %dec15, -1
  %conv = sext i16 %dec to i32
  store i32 %conv, ptr %0, align 4
  store i32 1, ptr @d, align 4
  br i1 false, label %if.else, label %if.then

if.then:                                          ; preds = %L
  %dec.lcssa = phi i16 [ %dec, %L ] 
  %conv.lcssa = phi i32 [ %conv, %L ] 
  store i16 %dec.lcssa, ptr @a, align 2
  store ptr @d, ptr @e, align 8
  br label %if.end6

if.else:                                          ; preds = %L
  br i1 true, label %if.end6.loopexit, label %L

if.end6.loopexit:                                 ; preds = %if.else
  %conv.lcssa17 = phi i32 [ %conv, %if.else ]
  br label %if.end6

if.end6:                                          ; preds = %if.end6.loopexit, %if.then
  %conv18 = phi i32 [ %conv.lcssa17, %if.end6.loopexit ], [ %conv.lcssa, %if.then ]
  ret i32 %conv18
}
```
Miscompile under `-indvars`: https://alive2.llvm.org/ce/z/P2qKr6

**Comment by nikic** [comment] 2022-09-02 11:00
A bit cleaned up:
```
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i32 @main(ptr %ptr, i16 %iv.start) {
entry:
  br label %loop

loop:
  %iv = phi i16 [ %iv.next, %dead ], [ %iv.start, %entry ]
  %iv.next = add i16 %iv, -1
  %conv = sext i16 %iv.next to i32
  store i32 %conv, ptr %ptr, align 4
  br i1 false, label %dead, label %exit1

dead:
  br i1 true, label %exit2, label %loop

exit1:
  %conv.lcssa = phi i32 [ %conv, %loop ]
  br label %exit.join

exit2:
  %conv.lcssa17 = phi i32 [ %conv, %dead ]
  br label %exit.join

exit.join:
  %res = phi i32 [ %conv.lcssa17, %exit2 ], [ %conv.lcssa, %exit1 ]
  ret i32 %res
}
```
`opt -S -indvars < %s`
```
define i32 @main(ptr %ptr, i16 %iv.start) {
entry:
  br label %loop

loop:                                             ; preds = %dead, %entry
  store i32 -1, ptr %ptr, align 4
  br i1 false, label %dead, label %exit1

dead:                                             ; preds = %loop
  br i1 true, label %exit2, label %loop

exit1:                                            ; preds = %loop
  %conv.lcssa = phi i32 [ -1, %loop ]
  br label %exit.join

exit2:                                            ; preds = %dead
  %conv.lcssa17 = phi i32 [ -1, %dead ]
  br label %exit.join

exit.join:                                        ; preds = %exit2, %exit1
  %res = phi i32 [ %conv.lcssa17, %exit2 ], [ %conv.lcssa, %exit1 ]
  ret i32 %res
}
```

**Comment by nikic** [comment] 2022-09-02 12:15
Okay, this is a duplicate of https://github.com/llvm/llvm-project/issues/57187.

**Closed by nikic** 2022-09-02 12:15 UTC
Labels: miscompilation, llvm:optimizations
