### ISSUE TITLE
Clang should not warn "capture 'this' is not used" if it is used in another branch of if-constexpr.

### ISSUE THREAD

**Issue by zoecarver** [llvm/llvm-project#50807] opened 2021-08-12 23:52 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51465](https://llvm.org/bz51465) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@zygoloid |

## Extended Description 
The following will fail to compile, even though the member "p" is used in another branch of the if-constexpr: https://godbolt.org/z/hWbjbWYjq

**Comment by wheatman** [comment] 2023-11-04 18:25
duplicate of https://github.com/llvm/llvm-project/issues/34798

**Closed by wheatman** 2023-11-04 18:25 UTC
Labels: duplicate, c++20, bugzilla, clang:diagnostics
