### ISSUE TITLE
clang does not properly convert the object in a member access expression

### ISSUE THREAD

**Issue by zygoloid** [llvm/llvm-project#54406] opened 2022-03-16 22:30 UTC
Per [class.access.base]/6, this example is ill-formed:

```
struct A {
  int m;
} a;
struct B : A {};
int n = a.B::m;
```

... because the object expression `a` cannot be implicitly converted to `B` (because `B` is not a base class of `A`). Clang does not diagnose this and accepts the member access. This opens a hole in the protected member access rules:

```
struct C {
protected:
  int m;
};
struct D : private C {
  int get(C &c) { return c.D::m; }
};
```

This example is invalid for the same reason, but Clang accepts it. ([[class.protected]p1](https://eel.is/c++draft/class.protected#1), which normally would prevent `D` from accessing protected members on a `C` object that is not a `D` object, does not apply here because `m` as a member of the naming class `D` is private, not protected.)

**Comment by xgupta** [comment] 2023-01-14 12:33
Hello @zygoloid, does this function in` SemaExpr.cpp` needs correction with a new warning of `B is not a base class of A` in `DiagnosticSemaKinds.td`? Can you please provide some guidance on which clang API will be useful here?
https://github.com/llvm/llvm-project/blob/2140260d9154ea3b7dd905b72805004dd182b1a3/clang/lib/Sema/SemaExpr.cpp#L3000-L3004

**Comment by zwuis** [comment] 2024-08-12 10:44
Duplicate of #38632.

**Closed** 2024-08-12 14:07 UTC
Labels: bug, duplicate, c++, clang:frontend, accepts-invalid
