### ISSUE TITLE
error: symbol missing .functype when compiling .c to .s and then to wasm32 .o

### ISSUE THREAD

**Issue by TerrorJack** [llvm/llvm-project#54022] opened 2022-02-23 14:14 UTC
Not a duplicate of #53712 since this involves a defined function in the input code

Reduced repro:

```c
# 0 "" 3
typedef struct a {
  int c;
  struct a *d
} e;
struct {
  int b;
  e **aa[]
} f, *s;
g, h, i, j, k, l, m, n, o, p, t, a, u, v, w, x, y;
e q, r;
static z() {
  if (a * t) {
    n = k + j;
    p = 1 % ab(0, o);
    j = k = i;
    h = h << 1 | g++;
    q = *f.aa[l][m];
    for (;; q = r) {
      r = *q.d;
      if (n)
        q.d = 0;
    }
  }
  v = u = v % 4;
  s->aa[w][x] = y;
}
ac() {
  z();
  z();
}
```

Command line:

```sh
clang --target=wasm32-unknown-wasi -x c ghc_1.c -o ghc_1.s -S

clang --target=wasm32-unknown-wasi -x assembler -c ghc_1.s -o Hash.o.tmp
```

Error message:

```
ghc_1.s:23:2: error: symbol z missing .functype
        call    z
        ^
```

LLVM version: llvmorg-14.0.0-rc1, but with https://github.com/llvm/llvm-project/commit/2368f18eb305ae9d5a4f2110c048e5daf5007992 applied
Platform: x86_64-linux

**Comment by aardappel** [comment] 2022-02-28 18:49
So the asm emitted does have a `.functype	z () -> ()` but it appears later in the file than the `call`.

**Comment by aardappel** [comment] 2022-02-28 19:27
Debugging a little I can confirm that `WebAssemblyMCLowerPrePass` does NOT add the symbol for `z` to the table, yet the function `ac` that contains the `call` does get iterated.

The relevant IL looks like:

```
define hidden i32 @ac() local_unnamed_addr #0 {
entry:
  call fastcc void @z()
  call fastcc void @z()
  ret i32 undef
}

define internal fastcc void @z() unnamed_addr #0 {
```

My guess is that because of `static` / calling convention, the `MO.isSymbol()` in that pass never gets hit (it's either a different operand type or operand not present in the list), but I do not have time to further research right now..

**Comment by asb** [comment] 2022-03-16 14:26
Here's a smaller test case:
```
$ cat tc.c
static int static_func() {
  return -1;
}

int main() {
  if (static_func())
    return 0;
  return 1;
}
$ ./llvm-project/build/default/bin/clang --target=wasm32-wasi -O0 -save-temps tc.c
tc.s:27:2: error: symbol static_func missing .functype
        call    static_func
        ^
```

**Comment by sbc100** [comment] 2022-03-17 16:56
I think option 2 sounds good.  I suggest we just emit all `.functype`s at the top of the file and none inline.. then we don't need to worry about figuring out anything about ordering.

**Comment by asb** [comment] 2022-03-17 17:00
Yes, I'm thinking that's best. I started thinking through option 1) and asking myself if the extra complexity (and necessary tests for it) had any real value.

I can put together a patch for option 2 tomorrow.

**Comment by aardappel** [comment] 2022-03-17 17:17
Most test cases won't need updating since they're hand-written asm, there's only few roundtrip ones afaik.

**Comment by asb** [comment] 2022-03-18 17:07
This turned into a bit of a rabbit hole (but a good exercise for getting up to speed with wasm and the current state of the backend!). Just moving all the `.functype` to the top won't work, because functions are currently assumed to be bracketed by `.functype` and `end_function`. I haven't looked into options for that yet, as I've been fleshing out testing for the type checker before making further changes. See [here](https://reviews.llvm.org/D122020) for a WIP patch with test cases.

**Comment by sbc100** [comment] 2022-03-18 17:10
Hmm.. that seems like a bug.   I think we should allow .functype anywhere so maybe that needs fixing too.

**Comment by aardappel** [comment] 2022-03-18 17:21
The assembler uses `.functype` to know a new function starts, because we are placing each function in its own segment and thus we must distinguish function starts from any old label that does not start a function. Also we need to be type safe in a single pass. Wasm is a bit different from most targets here. 

Probably for now easiest would be to support duplicate `.functype` at the start of the file (optionally reduced to just those needed) and at the start of the function. Or start functions with another directive that is not .functype.

**Comment by sbc100** [comment] 2022-03-18 17:23
I think duplicating types is probably fine.   (Is this allowed on other targets?)

**Comment by sbc100** [comment] 2022-03-18 17:25
Yup, in ELF its perfectly OK to do:

```
  .type a,@object                       # @a                                        
  .type a,@object                       # @a                                     
  .type a,@object                       # @a                                     
  .type a,@object                       # @a    
```

I can even do (which is a little scary):

```
  .type main,@function                                                           
  .type main,@object  
```

**Comment by aardappel** [comment] 2022-03-18 18:14
I suppose you could consider attaching the logic for starting a function in the assembler to `.type main,@function` if its always there, and make it such that the corresponding `.functype` must have happened "anywhere before it"

**Comment by sbc100** [comment] 2022-03-18 18:16
As long we the old form is still acceptable (i.e. we don't need to rewrite all the tests and force them to include both `.type` *and* `.functype`, just one should be sufficient in the correct place).

**Comment by asb** [comment] 2022-03-21 14:10
I've submitted [D122134](https://reviews.llvm.org/D122134) which just emits duplicate .functype (it didn't seem worth adding logic to only emit duplicate .functype only when necessary, as I suspect we'll move to preferring a different marker for the start of a function).

**Comment by sbc100** [comment] 2022-03-21 15:40
Out of interest, is there some reason you are interesting in compiling to assembly rather than object files?

**Comment by TerrorJack** [comment] 2022-03-21 15:50
> Out of interest, is there some reason you are interesting in compiling to assembly rather than object files?

We're working on a GHC native codegen for wasm32 target. Compared to implementing binary linking convention, we think it's nicer to target assembly instead and have llvm assembler handle symbols & relocs for us. Rough edges here and there, but we can spot them and file bugs :)

**Comment by sbc100** [comment] 2022-03-21 16:13
> > I see... but in that case you are generating the .s your self right? So the asm generated by llvm is not an issue for you?
> 
> It's still a minor issue: when GHC compiles C, the pipeline emits assembly first, then object file. We bypass this for wasm32 currently due to bugs like these, but it would be nice to remove this hack, and after all, the GHC builds provide some interesting cases for testing round trip property for upstream as well.

What is the advantage to you of doing that?  (other than giving is good test coverage :)

**Comment by asb** [comment] 2022-03-22 09:27
This should have been fixed in https://github.com/llvm/llvm-project/commit/86cc731f4c50370b2ea715adcf1d07dd3db49207 - so marking this as closed.

**Closed by asb** 2022-03-22 09:27 UTC
Labels: backend:WebAssembly
