### ISSUE TITLE
Clang format crashed - Setting AlignArrayOfStructures on Left align and last struct comment

### ISSUE THREAD

**Issue by Komediruzecki** [llvm/llvm-project#57558] opened 2022-09-05 10:31 UTC
The clang format 13 option - `AlignArrayOfStructures` (`ArrayInitializerAlignmentStyle`) - crashes on left alignment of arrays.

e.g., code:

```cpp
struct CFG_INTERRUPT_STRUCT {
    uint16_t maxNumber;        //!< Maximum number of interrupts in period
    uint16_t floodPeriod;      //!< Interrupt flooding period
    uint16_t minDisablePeriod; //!< Minimum period for which the interrupt will be disabled after the flood
};

CFG_INTERRUPT_STRUCT cfg_test[1] = {
    {
     .floodPeriod      = 3u, // other comments do not crash the format, just last one
     .maxNumber        = 60u,
     .minDisablePeriod = 2500u, // the comment crashes clang-format !CRASH!
    }
};
```

Crashes the clang-format with the log trace below, when the last comment is added, other comments are not affected, without the comment it formats without crash.

Configuration

Version: v14.0.6

```yaml
---
BasedOnStyle: LLVM
# For option description see: https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormatStyleOptions.html
# General Settings (tabs, spaces, limits)
Language: Cpp
Standard: Auto
ReflowComments: false
DisableFormat: false
ColumnLimit: 120
UseTab: Never
UseCRLF: false # clang-format 11
TabWidth: 4
IndentWidth: 4
ContinuationIndentWidth: 8 # Two tabs
IndentCaseLabels: true
IndentWrappedFunctionNames: true
IndentPPDirectives: None
IndentGotoLabels: false    # clang-format 10
IndentCaseBlocks: false    # clang-format 11
IndentExternBlock: Indent  # clang-format 12
PPIndentWidth: -1          # clang-format 14 - no indent, default
#InsertTrailingCommas: Wrapped # clang-format 12 - only for Javascript
# Spaces
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: Never
SpaceInEmptyParentheses: false
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInSquareBrackets: false
SpaceAfterLogicalNot: false
SpaceAfterCStyleCast: true
SpacesInConditionalStatement: false # clang-format 11
SpaceBeforeSquareBrackets: false    # clang-format 11
SpaceInEmptyBlock: false            # clang-format 11
SpaceAroundPointerQualifiers: After # clang-format 12
SpaceBeforeCaseColon: false         # clang-format 12
SeparateDefinitionBlocks: Leave     # clang-format 14
SpacesInLineCommentPrefix:
  Minimum: 1
  Maximum: 1
# Penalties
# This decides in what order things should be done if a line is too long
PenaltyBreakAssignment: 100
PenaltyBreakBeforeFirstCallParameter: 10
PenaltyBreakComment: 10
PenaltyBreakFirstLessLess: 0
PenaltyBreakString: 10
PenaltyExcessCharacter: 60
PenaltyReturnTypeOnItsOwnLine: 400 # out of reach to avoid this
PenaltyBreakTemplateDeclaration: 0 # C++
PenaltyBreakOpenParenthesis: 10
# Alignments
AlignAfterOpenBracket: DontAlign
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: None
AlignConsecutiveBitFields: Consecutive
AlignConsecutiveMacros: AcrossComments
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments: true
PointerAlignment: Right
DerivePointerAlignment: false

AlignArrayOfStructures: Left # clang-format 13
QualifierAlignment: Custom   # clang-format 14
QualifierOrder:
  - 'restrict'
  - 'inline'
  - 'static'
  - 'const'
  - 'constexpr' # for cpp
  - 'type'
# Allowances
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Always
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: Never
AllowShortLoopsOnASingleLine: false
# clang-format 12
AllowShortEnumsOnASingleLine: false
# Breaks
# Deprecated - retained for backwards compatibility
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None # PenaltyReturnTypeOnItsOwnLine is taken into account
AlwaysBreakBeforeMultilineStrings: false
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Attach # Could be set to Custom and then configured per brace type (function, ifs, enums)
BreakBeforeTernaryOperators: false # todo: maybe set to true to get cleaner ternary
BreakStringLiterals: false
# clang-format 12
AttributeMacros:
  - 'ASIL_A_B_CODE'
  - 'ASIL_C_D_CODE'
  - 'ASIL_C_D_BSS'
BitFieldColonSpacing: Both
# Other
# Could be useful for not formatting comments matched with a regex
CommentPragmas: '@(ref|p|param|li|warning|ingroup|author|related|relates|date|relatesalso|deprecated|image|brief|attention|copydoc|addtogroup|todo|tparam|see|note|skip|skipline|until|line|dontinclude|include) '
MaxEmptyLinesToKeep: 2
Cpp11BracedListStyle: false
KeepEmptyLinesAtTheStartOfBlocks: true
# File include management
SortIncludes: CaseInsensitive
IncludeBlocks: Regroup
IncludeCategories:
  # Module includes
  - Regex: '^"(mdl).*'
    Priority: 4
    SortPriority: 4
  # Configuration includes
  - Regex: '^"(cfg_mdl).*'
    Priority: 3
    SortPriority: 3
  # Submodule includes
  - Regex: '^"(isotp|uds|utils|xcp|bsp|drv|mcu).*'
    Priority: 2
    SortPriority: 2
  # Everything else (not organized, stdlib, ewl_c, other libraries)
  - Regex: '<[[:alnum:].]+>'
    Priority: 1
    SortPriority: 1
#IncludeIsMainRegex: ""

# List of macros which would start a block (and then be indented properly)
# Add regexes as needed
#MacroBlockBegin: "Regexp"
#MacroBlockEnd: "Regexp"

# clang-format 14 - CPP
#EmptyLineAfterAccessModifier: Leave
#EmptyLineBeforeAccessModifier: LogicalBlock
IfMacros:
  - 'NULL_CHECK1'
  - 'NULL_CHECK2'
  - 'NULL_CHECK3'
  - 'NULL_CHECK4'
# clang-format 12
WhitespaceSensitiveMacros:
  - 'NULL_CHEKC1'
  - 'NULL_CHEKC2'
  - 'NULL_CHEKC3'
  - 'NULL_CHEKC4'
```

```console
Stack dump:
Stack dump:
0.	Program arguments: "C:\\Program Files\\LLVM\\bin\\clang-format.exe" -assume-filename=C:\\Users\\<user-name>\\sw_projects\\<project_name>\\<project>\\<project>\\app\\config\\modules\\production\\cfg_mdl_iat.c -style=file -fallback-style=Google -offset=0 -length=4368
 #0 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0xbe843 C:\Program Files\LLVM\bin\clang-format.exe 0xbe319
 #1 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0xbcd39 C:\Program Files\LLVM\bin\clang-format.exe 0xb9ef7
 #2 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x86397 C:\Program Files\LLVM\bin\clang-format.exe 0xa2519
 #3 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x94664 C:\Program Files\LLVM\bin\clang-format.exe 0x7dd6e
 #4 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x7ec69 C:\Program Files\LLVM\bin\clang-format.exe 0x545c
 #5 0x00007ff6c62ee843 C:\Program Files\LLVM\bin\clang-format.exe 0x385b C:\Program Files\LLVM\bin\clang-format.exe 0x1843d8
 #6 0x00007ff6c62ee843 (C:\Program Files\LLVM\bin\clang-format.exe+0xbe843)
 #7 0x00007ff6c62ee319 (C:\Program Files\LLVM\bin\clang-format.exe+0xbe319)
0x00007FF6C62EE843 (0x0000000000000000 0x0000003C00000000 0x0000000100000000 0x000000DC5C38AE20)
0x00007FF6C62EE319 (0x000000DC5C38B2D8 0x0000003C00000000 0x000000DC5C38CA00 0x000000DC00000000)
0x00007FF6C62ECD39 (0x0000000000000000 0x000000DC00000000 0x000000DC5C38AF18 0x00007FF96967F05B)
0x00007FF6C62E9EF7 (0x0000027544C3FF20 0x0000000000000000 0x0000000000000000 0x0000001000000000)
0x00007FF6C62B6397 (0x000000DC5C38BC80 0x00007FF6C62D292E 0x0000000000000000 0x0000000000000000)
0x00007FF6C62D2519 (0x0000000000000000 0x0000000000000009 0x0000027544C10320 0x0000027544C40ED0)
0x00007FF6C62C4664 (0x0000027544C3C170 0x0000000000000000 0x0000027544C3C7A0 0x0000000000000038)
0x00007FF6C62ADD6E (0x0000027544C237F0 0x00007FF96BE147B1 0x0000000000000000 0x0000027544C10000)
0x00007FF6C62AEC69 (0x0000027544C1D2E4 0x0072006700000000 0x0000027544C1D2B0 0x0000000000340032)
0x00007FF6C623545C (0x0000027544C17300 0x000000000000000E 0x0000000000000000 0x0000027544C15310)
0x00007FF6C623385B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF6C63B43D8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF96A577034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF96BE42651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```

**Comment by EugeneZelenko** [comment] 2022-09-05 14:00
Could you please try 15 or `main` branch?

**Comment by Komediruzecki** [comment] 2022-09-05 14:17
Sure, if you have prebuilt binaries for windows, otherwise I might need to dig into how to build it, is there an easy way to do it only for clang-format?

**Comment by jackhong12** [comment] 2022-09-05 15:23
I can reproduce this in `main` branch.

smaller producer
```yaml
AlignArrayOfStructures: Left
```

```cpp
TMP tmp[1] = {
  {
    .x = 1, //
    .y = 2,
    .z = 3, //
  }
};
```

```
clang-format: /home/sense/opensource/llvm-project/llvm/include/llvm/ADT/SmallVector.h:284: llvm::SmallVectorTemplateCommon::const_reference llvm::SmallVectorTemplateCommon<clang::format::WhitespaceManager::Change, void>::operator[](llvm::SmallVectorTemplateCommon::size_type) const [T = clang::format::WhitespaceManager::Change]: Assertion `idx < size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./bin/clang-format tmp.cpp
 #0 0x00000000005180da llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/sense/opensource/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:11
 #1 0x00000000005182ab PrintStackTraceSignalHandler(void*) /home/sense/opensource/llvm-project/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x000000000051681b llvm::sys::RunSignalHandlers() /home/sense/opensource/llvm-project/llvm/lib/Support/Signals.cpp:102:5
 #3 0x0000000000518a21 SignalHandler(int) /home/sense/opensource/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007fc7519df420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x00007fc75147200b raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007fc751451859 abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81:7
 #7 0x00007fc751451729 get_sysdep_segment_value /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:509:8
 #8 0x00007fc751451729 _nl_load_domain /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:970:34
 #9 0x00007fc751462fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
#10 0x000000000066554c llvm::SmallVectorTemplateCommon<clang::format::WhitespaceManager::Change, void>::operator[](unsigned long) const /home/sense/opensource/llvm-project/llvm/include/llvm/ADT/SmallVector.h:0:5
#11 0x0000000000665025 auto clang::format::WhitespaceManager::getNetWidth<clang::format::WhitespaceManager::CellDescription*>(clang::format::WhitespaceManager::CellDescription* const&, clang::format::WhitespaceManager::CellDescription* const&, unsigned int) const /home/sense/opensource/llvm-project/clang/lib/Format/WhitespaceManager.h:282:51
#12 0x000000000066523d unsigned int clang::format::WhitespaceManager::getMaximumNetWidth<clang::format::WhitespaceManager::CellDescription*>(clang::format::WhitespaceManager::CellDescription* const&, clang::format::WhitespaceManager::CellDescription* const&, unsigned int, unsigned int, unsigned int) const /home/sense/opensource/llvm-project/clang/lib/Format/WhitespaceManager.h:322:33
#13 0x000000000065c56c clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions&&) /home/sense/opensource/llvm-project/clang/lib/Format/WhitespaceManager.cpp:1182:10
#14 0x000000000065b308 clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) /home/sense/opensource/llvm-project/clang/lib/Format/WhitespaceManager.cpp:1091:5
#15 0x00000000006586dd clang::format::WhitespaceManager::alignArrayInitializers() /home/sense/opensource/llvm-project/clang/lib/Format/WhitespaceManager.cpp:1075:25
#16 0x0000000000656fc1 clang::format::WhitespaceManager::generateReplacements() /home/sense/opensource/llvm-project/clang/lib/Format/WhitespaceManager.cpp:111:3
#17 0x00000000005b899e clang::format::(anonymous namespace)::Formatter::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) /home/sense/opensource/llvm-project/clang/lib/Format/Format.cpp:2058:26
#18 0x0000000000600ba9 clang::format::TokenAnalyzer::process() /home/sense/opensource/llvm-project/clang/lib/Format/TokenAnalyzer.cpp:0:9
#19 0x00000000005bf7f2 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::$_10::operator()(clang::format::Environment const&) const /home/sense/opensource/llvm-project/clang/lib/Format/Format.cpp:3313:5
#20 0x00000000005bf66b std::_Function_handler<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&), clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::$_10>::_M_invoke(std::_Any_data const&, clang::format::Environment const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:285:9
#21 0x00000000005c1ff1 std::function<std::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&)>::operator()(clang::format::Environment const&) const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688:14
#22 0x00000000005aff66 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) /home/sense/opensource/llvm-project/clang/lib/Format/Format.cpp:3333:9
#23 0x00000000005b0c37 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) /home/sense/opensource/llvm-project/clang/lib/Format/Format.cpp:3357:10
#24 0x0000000000414dac clang::format::format(llvm::StringRef) /home/sense/opensource/llvm-project/clang/tools/clang-format/ClangFormat.cpp:498:23
#25 0x00000000004138ac main /home/sense/opensource/llvm-project/clang/tools/clang-format/ClangFormat.cpp:630:14
#26 0x00007fc751453083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#27 0x000000000041318e _start (./bin/clang-format+0x41318e)
[1]    4090645 abort (core dumped)  ./bin/clang-format tmp.cpp
```

**Comment by deePerl** [comment] 2022-09-07 19:28
Hi,
Here a shorter way to generate the crash

The shorter file to generate the crash
 
```
> type .\test.c

T A[] = {
  {0,0}
  #define M {},
};
```

**Comment by deePerl** [comment] 2022-09-07 19:48
Hi

Here an other way to generate the crash:
```
> type .\test.c
T A[] = {
  {0,0}
  #define M {},
};

> type .\.clang-format
AlignArrayOfStructures: Right
```
Running clan-format 15.0 on Windows 11
```
> clang-format.exe --version
clang-format version 15.0.0
```

Run and crash:
```
> clang-format.exe -style=File -assume-filename=.\test.c
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: D:\\LLVM\\bin\\clang-format.exe -style=File -assume-filename= .\\test.c
Exception Code: 0xC0000005
 #0 0x00007ff7455e2400 (D:\LLVM\bin\clang-format.exe+0xd2400)
 #1 0x00007ff7455e1398 (D:\LLVM\bin\clang-format.exe+0xd1398)
 #2 0x00007ff7455de596 (D:\LLVM\bin\clang-format.exe+0xce596)
 #3 0x00007ff745563fef (D:\LLVM\bin\clang-format.exe+0x53fef)
 #4 0x00007ff7455c59a9 (D:\LLVM\bin\clang-format.exe+0xb59a9)
 #5 0x00007ff745573544 (D:\LLVM\bin\clang-format.exe+0x63544)
 #6 0x00007ff74555b543 (D:\LLVM\bin\clang-format.exe+0x4b543)
 #7 0x00007ff74555c009 (D:\LLVM\bin\clang-format.exe+0x4c009)
 #8 0x00007ff7455155e8 (D:\LLVM\bin\clang-format.exe+0x55e8)
 #9 0x00007ff745513716 (D:\LLVM\bin\clang-format.exe+0x3716)
#10 0x00007ff7456a6aa0 (D:\LLVM\bin\clang-format.exe+0x196aa0)
#11 0x00007ff93fc154e0 (C:\WINDOWS\System32\KERNEL32.DLL+0x154e0)
#12 0x00007ff9406c485b (C:\WINDOWS\SYSTEM32\ntdll.dll+0x485b)
```

Replace  **'{},'** by '**{}**'  (remove the trailing comma) and it works:
```
> type .\test.c
T A[] = {
    {0,0}
    #define M {}
};

> clang-format.exe -style=File -assume-filename=.\test.c
T A[] = {
    {0, 0}
#define M      \
  {}
};
```

I hope this will help to fix this bug that has been there for too long.
It has been around since at least version 13.
https://github.com/llvm/llvm-project/issues/55269

Regards.

**Comment by Komediruzecki** [comment] 2022-09-13 16:52
Hi,

thanks for the additions, is there a way to proceed on this, is there a way to contribute to this fix or you already have someone on this?

I would also like to contribute to fix the structure and nested structures/arrays formatting altogether.

Any help appreciated.

**Comment by rymiel** [comment] 2022-10-25 18:31
Duplicate of #55493

**Closed by rymiel** 2022-10-25 18:31 UTC
Labels: clang-format
