### ISSUE TITLE
clang-format creates wrong indentation when lines argument spans multiple if-else branches

### ISSUE THREAD

**Issue by Venemo** [llvm/llvm-project#62799] opened 2023-05-18 14:51 UTC
`clang-format` will create an invalid indentation when you use the `-lines` argument and specify lines that span different if-else branches. This issue is especially noticable when using `git clang-format` because it is prone to specifying `-lines` arguments that trigger this problem.

### Steps to reproduce:

1. Clone this repo and checkout this branch: https://gitlab.freedesktop.org/Venemo/mesa/-/commits/clang_format_radv_gfx11_mesh_new_fast_launch 
2. Run the following command:
    `clang-format -i -lines=8676:8687 src/amd/vulkan/radv_cmd_buffer.c`
   Side note, the following also reproduces the problem:
   `git clang-format HEAD~`

### Expected outcome:

`clang-format` should produce the correct indentation as specified in the `.clang-format` file in that repo.

### Actual outcome:

An extra space is added, which is invalid.

### Potential workaround

The indentation of the same code is correct when running `clang-format` on the whole file (without `-lines`).

**Comment by Sedeniono** [comment] 2023-05-21 20:27
I just tried it and could reproduce the problem. This is a duplicate of #59178.

**Closed** 2023-05-21 21:40 UTC
Labels: duplicate, clang-format
