### ISSUE TITLE
Option for west const in const-correctness

### ISSUE THREAD

**Issue by vadi2** [llvm/llvm-project#62704] opened 2023-05-14 12:29 UTC
[const-correctness](https://clang.llvm.org/extra/clang-tidy/checks/misc/const-correctness.html) is a great check with an even better fixit, but it only supports east const. It would be great if west const was also supported, since [both are valid](https://hackingcpp.com/cpp/design/east_vs_west_const.html).

I agree that west const is less consistent - but the inconsistency only manifests itself in edge cases, and I don't plan on writing code that hits those edge cases in my codebase on a general basis.

**Comment by EugeneZelenko** [comment] 2023-05-14 14:10
Duplicate of #58221.

**Closed by EugeneZelenko** 2023-05-14 14:10 UTC
Labels: duplicate, clang-tidy
