### ISSUE TITLE
[packaging] clang-18 from apt.llvm.org on Ubuntu 23.10 mantic is missing LLVMgold.so and fails to link with LTO

### ISSUE THREAD

**Issue by illwieckz** [llvm/llvm-project#90810] opened 2024-05-02 01:27 UTC
When I build the [Daemon game engine](https://github.com/DaemonEngine/Daemon) with Clang 18 from https://apt.llvm.org On Ubuntu 23.10 mantis and enable LTO, the configuration fails at the pthread detection step. It works with Clang 18 if I disable LTO. It also works with Clang 17 and 19 if I enable or disable LTO.

&nbsp;|Clang 17|Clang 18|Clang 19
-|-|-|-
LTO ON|✅️ ok|❌️ ko|✅️ ok
LTO OFF|✅️ ok|✅️ ok|✅️ ok

The reported Clang is `18.1.3`.

As a side note, I noticed that with Intel ICX `2024.1` which is based on Clang `18.0.0` I can configure and build with LTO enabled.

## Environment

```
$ dpkg -l clang-18 | grep -E '^ii'
ii  clang-18       1:18.1.3~++20240322073236+ef6d1ec07c69-1~exp1~20240322193248.98 amd64        C, C++ and Objective-C compiler

$ dpkg -l llvm-18 | grep -E '^ii'
ii  llvm-18        1:18.1.3~++20240322073236+ef6d1ec07c69-1~exp1~20240322193248.98 amd64        Modular compiler and toolchain technologies

$ clang-18 -v 2>&1 | head -n1
Ubuntu clang version 18.1.3 (++20240322073236+ef6d1ec07c69-1~exp1~20240322193248.98)

$ lsb_release -irc
Distributor ID:	Ubuntu
Release:	23.10
Codename:	mantic
```

## How to reproduce

```sh
git clone -b 'unvanquished/0.54.1' --recurse-submodules 'https://github.com/DaemonEngine/Daemon.git'
cd Daemon
mkdir build
cd build
cmake .. -D'CMAKE_C_COMPILER'='clang-18' -D'CMAKE_CXX_COMPILER'='clang++-18' -D'USE_LTO'='ON'
```

## Some logs

Here is an excerpt of the log, including the error:

```
$ rm -f CMakeCache.txt
$ cmake .. -D'CMAKE_C_COMPILER'='clang-18' -D'CMAKE_CXX_COMPILER'='clang'++-18' -D'USE_LTO'='ON'
-- The C compiler identification is Clang 18.1.3
-- The CXX compiler identification is Clang 18.1.3
…
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
CMake Error at /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.27/Modules/FindThreads.cmake:226 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:580 (find_package)

  -- Configuring incomplete, errors occurred!
```

It works if I use Clang 18 with LTO disabled, or if I use Clang 17 or Clang 19 with LTO enabled or disabled:

```
$ rm -f CMakeCache.txt
$ cmake .. -D'CMAKE_C_COMPILER'='clang-18' -D'CMAKE_CXX_COMPILER'='clang'++-18' -D'USE_LTO'='OFF'
-- The C compiler identification is Clang 18.1.3
-- The CXX compiler identification is Clang 18.1.3
…
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
…
-- Configuring done (7.2s)
-- Generating done (0.1s)
-- Build files have been written to: Daemon/build
```

```
$ rm -f CMakeCache.txt
$ cmake .. -D'CMAKE_C_COMPILER'='clang-17' -D'CMAKE_CXX_COMPILER'='clang'++-17' -D'USE_LTO'='ON'
-- The C compiler identification is Clang 17.0.6
-- The CXX compiler identification is Clang 17.0.6
…
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
…
-- Configuring done (7.2s)
-- Generating done (0.1s)
-- Build files have been written to: Daemon/build
```

```
$ rm -f CMakeCache.txt
$ cmake .. -D'CMAKE_C_COMPILER'='clang-19' -D'CMAKE_CXX_COMPILER'='clang'++-19' -D'USE_LTO'='ON'
-- The C compiler identification is Clang 19.0.0
-- The CXX compiler identification is Clang 19.0.0
…
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
…
-- Configuring done (7.2s)
-- Generating done (0.1s)
-- Build files have been written to: Daemon/build
```

**Comment by illwieckz** [comment] 2024-05-02 01:33
Running `cmake`  with `--trace` prints:

```
/usr/share/cmake-3.27/Modules/FindThreads.cmake(141):  unset(_threads_src )
/usr/share/cmake-3.27/Modules/FindThreads.cmake(143):  if(THREADS_HAVE_PTHREAD_ARG )
/usr/share/cmake-3.27/Modules/FindThreads.cmake(146):  else()
/usr/share/cmake-3.27/Modules/FindThreads.cmake(147):  message(CHECK_FAIL no )
-- Check if compiler accepts -pthread - no
/usr/share/cmake-3.27/Modules/FindThreads.cmake(152):  if(THREADS_HAVE_PTHREAD_ARG )
/usr/share/cmake-3.27/Modules/FindThreads.cmake(182):  if(CMAKE_THREAD_LIBS_INIT OR CMAKE_HAVE_LIBC_PTHREAD )
/usr/share/cmake-3.27/Modules/FindThreads.cmake(187):  if(CMAKE_SYSTEM_NAME MATCHES Windows )
/usr/share/cmake-3.27/Modules/FindThreads.cmake(192):  if(CMAKE_USE_PTHREADS_INIT )
/usr/share/cmake-3.27/Modules/FindThreads.cmake(224):  set(CMAKE_REQUIRED_QUIET ${CMAKE_REQUIRED_QUIET_SAVE} )
/usr/share/cmake-3.27/Modules/FindThreads.cmake(225):  include(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake )
```

I tested this:

```
$ echo 'int main(){ return 0; }' > a.c
$ clang-18 -pthread -fno-lto a.c
$ clang-18 -pthread -flto a.c
/usr/bin/ld: /usr/lib/llvm-18/bin/../lib/LLVMgold.so: error loading plugin: /usr/lib/llvm-18/bin/../lib/LLVMgold.so: cannot open shared object file: No such file or directory
clang-18: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by illwieckz** [comment] 2024-05-02 01:36
The installation is likely incomplete and misses `/usr/lib/llvm-18/lib/LLVMgold.so`:

```
$ ls -1 /usr/bin/clang-1?
/usr/bin/clang-11
/usr/bin/clang-13
/usr/bin/clang-14
/usr/bin/clang-15
/usr/bin/clang-16
/usr/bin/clang-17
/usr/bin/clang-18
/usr/bin/clang-19
```

```
$ ls -1 /usr/lib/llvm-1?/lib/LLVMgold.so
/usr/lib/llvm-11/lib/LLVMgold.so
/usr/lib/llvm-13/lib/LLVMgold.so
/usr/lib/llvm-14/lib/LLVMgold.so
/usr/lib/llvm-15/lib/LLVMgold.so
/usr/lib/llvm-16/lib/LLVMgold.so
/usr/lib/llvm-17/lib/LLVMgold.so
/usr/lib/llvm-19/lib/LLVMgold.so
```

**Comment by EugeneZelenko** [comment] 2024-05-02 01:40
Duplicate of #87553?

**Comment by illwieckz** [comment] 2024-05-02 01:43
> Duplicate of #87553?

Indeed!

**Closed** 2024-05-02 02:58 UTC
Labels: duplicate, packaging, platform:linux

**Comment by illwieckz** [comment] 2024-05-10 20:18
Hi, unfortunately the issue is still not fixed.

The file in the `mantis` repository is still `clang-18_1%3a18.1.3~++20240322073236+ef6d1ec07c69-1~exp1~20240322193248.98_amd64.deb` today and still lacks the `LLVMgold.so` file.

**Comment by Bouncner** [comment] 2024-06-16 18:23
Having the same issues as @illwieckz on Ubuntu 24.04 with LTO and llvm 18. :(
