### ISSUE TITLE
[Clang Static Analyzer] Crash/Assertion violation on Windows for LLVM 16

### ISSUE THREAD

**Issue by hahn-absint** [llvm/llvm-project#62130] opened 2023-04-14 11:26 UTC
I am experiencing crashes (segmentation faults when built as release mode) aka assertion failure (when built as release + assertions) when using the Clang static analyzer on Windows.

I tried LLVM 16, and also the newest version of branch release/16.x; both fail:
```console
clang version 16.0.2
Target: x86_64-pc-windows-msvc
Thread model: posix
```

```console
Assertion failed: isa<To>(Val) && "cast<Ty>() argument of incompatible type!", file llvm\include\llvm/Support/Casting.h, line 567
Stack dump:
0.      Program arguments: clang -c --analyze C:\\Users\\user\\broken.c
1.      <eof> parser at end of file
Exception Code: 0x80000003
```
The stack trace is rather useless (just hex addresses) as it was not a debug build.

Code:
```c
int f4(int *p) {

  unsigned x = (unsigned) p;

  if (x)
    return 1;

  int *q = (int*) x;
  return *q;
}

```
and invoked via:
`clang -c --analyze <file.c>`

**Comment by steakhal** [comment] 2023-08-26 15:49
I could not reproduce this, but I'm using Linux.
Someone could give it a try on Windows?

**Comment by danix800** [comment] 2023-08-28 03:34
Tried on 16.0.2 and main, both debug/release with assertion, NOT reproducible.

**Comment by hahn-absint** [comment] 2023-08-28 05:30
We tried with Visual Studio 2022 Version 17.4.4 and Visual Studio 2022 Version 17.5.4, both failing (back in April).
When using clang-cl itself to build clang, the crash/assertion goes "away".

**Comment by steakhal** [comment] 2023-08-28 05:35
@hahn-absint Could you please check if it crashes on main?
If so, please write down the steps to reproduce it.

**Comment by danix800** [comment] 2023-08-28 05:50
It'd be better to provide the reproducible simplified testcase.

**Comment by danix800** [comment] 2023-08-28 05:53
It'd be better to provide more detailed info like your compiler or build env at the first place.

**Comment by hahn-absint** [comment] 2023-08-28 06:57
@danix800 I used a plain Windows 10 machine with the above mentioned Visual Studio version. I built using
`cmake.exe -DCMAKE_C_STANDARD=17 -DCMAKE_CXX_STANDARD=20 --no-warn-unused-cli -DCMAKE_PREFIX_PATH:PATH=C:\Users\<user>\Downloads\build_llvm\llvm-usr -DCMAKE_MODULE_PATH:PATH=C:\Users\<user>\Downloads\build_llvm\llvm-usr\share\cmake\modules -DCMAKE_INSTALL_PREFIX:PATH=C:\Users\<user>\Downloads\build_llvm\llvm-usr -G CodeBlocks - Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_EH=1 -DLLVM_ENABLE_RTTI=1 -DLLVM_ENABLE_TERMINFO=0 -DLLVM_ENABLE_ZLIB=1 -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld -DCOMPILER_RT_BUILD_SANITIZERS=0 -DLLVM_ENABLE_ZSTD=0 -DCMAKE_CXX_STANDARD=17 -DLLVM_ENABLE_ASSERTIONS=1 C:\Users\<user>\Downloads\build_llvm\llvm\llvm`

@steakhal Unfortunately, I do not have time right now to try out further builds. I am sorry.

**Comment by danix800** [comment] 2023-08-29 10:28
Confirmed on VS 17.7.2, but seems to be a VS bug. Stacktrace:
```
./Release/bin/clang.exe -c --analyzer-no-default-checks --analyze -Xclang -analyzer-checker=core.NullDereference test.c
Assertion failed: isa<To>(Val) && "cast<Ty>() argument of incompatible type!", file C:\Users\Administrator\source\repos\llvm-project\llvm\include\llvm/Support/Casting.h, line 566
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: C:\\Users\\Administrator\\source\\repos\\llvm-project\\build-main-vs2022\\Release\\bin\\clang.exe -c --analyzer-no-default-checks --analyze -Xclang -analyzer-checker=core.NullDereference test.c
1.      <eof> parser at end of file
Exception Code: 0x80000003
 #0 0x00007ff6899d61e5 HandleAbort (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0xfa61e5)
 #1 0x00007ffae843bab4 (C:\Windows\System32\ucrtbase.dll+0x7bab4)
 #2 0x00007ffae843ca81 (C:\Windows\System32\ucrtbase.dll+0x7ca81)
 #3 0x00007ffae843e451 (C:\Windows\System32\ucrtbase.dll+0x7e451)
 #4 0x00007ffae843e691 (C:\Windows\System32\ucrtbase.dll+0x7e691)
 #5 0x00007ff68b1f0ff9 llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const >::{ctor} C:\Users\Administrator\source\repos\llvm-project\llvm\include\llvm\ADT\IntrusiveRefCntPtr.h:176:0
 #6 0x00007ff68b1f0ff9 clang::ento::SimpleConstraintManager::assumeInternal(class llvm::IntrusiveRefCntPtr<class clang::ento::ProgramState const>, class clang::ento::DefinedSVal, bool) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\SimpleConstraintManager.cpp:42:0
 #7 0x00007ff68b1a591e clang::ento::ConstraintManager::assumeDualImpl<`clang::ento::ConstraintManager::assumeDual'::`2'::<lambda_1> > C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\ConstraintManager.cpp:65:0
 #8 0x00007ff68b1a5ffe clang::ento::ConstraintManager::assumeDual(class llvm::IntrusiveRefCntPtr<class clang::ento::ProgramState const>, class clang::ento::DefinedSVal) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\ConstraintManager.cpp:97:0
 #9 0x00007ff68b1a5f5b clang::ento::ConstraintManager::assume(class llvm::IntrusiveRefCntPtr<class clang::ento::ProgramState const>, class clang::ento::DefinedSVal, bool) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\ConstraintManager.cpp:112:0
#10 0x00007ff68b1c98be llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const >::operator bool C:\Users\Administrator\source\repos\llvm-project\llvm\include\llvm\ADT\IntrusiveRefCntPtr.h:201:0
#11 0x00007ff68b1c98be clang::ento::TrackConstraintBRVisitor::isUnderconstrained(class clang::ento::ExplodedNode const *) const C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporterVisitors.cpp:1807:0
#12 0x00007ff68b1c22ae clang::ento::TrackConstraintBRVisitor::VisitNode(class clang::ento::ExplodedNode const *, class clang::ento::BugReporterContext &, class clang::ento::PathSensitiveBugReport &) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporterVisitors.cpp:1819:0
#13 0x00007ff68b154a3b generateVisitorsDiagnostics C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporter.cpp:2809:0
#14 0x00007ff68b14f889 `anonymous namespace'::PathDiagnosticBuilder::findValidReport C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporter.cpp:2848:0
#15 0x00007ff68b1532b7 clang::ento::PathSensitiveBugReporter::generatePathDiagnostics(class llvm::ArrayRef<class clang::ento::PathDiagnosticConsumer *>, class llvm::ArrayRef<class clang::ento::PathSensitiveBugReport *> &) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporter.cpp:2882:0
#16 0x00007ff68b151ada clang::ento::PathSensitiveBugReporter::generateDiagnosticForConsumerMap(class clang::ento::BugReport *, class llvm::ArrayRef<class clang::ento::PathDiagnosticConsumer *>, class llvm::ArrayRef<class clang::ento::BugReport *>) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporter.cpp:3295:0
#17 0x00007ff68b14c7ee clang::ento::BugReporter::FlushReport(class clang::ento::BugReportEquivClass &) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporter.cpp:3077:0
#18 0x00007ff68b14d19b clang::ento::BugReporter::FlushReports(void) C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Core\BugReporter.cpp:2481:0
#19 0x00007ff68ae00807 std::unique_ptr<llvm::Timer,std::default_delete<llvm::Timer> >::operator bool C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\memory:3315:0
#20 0x00007ff68ae00807 `anonymous namespace'::AnalysisConsumer::RunPathSensitiveChecks C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Frontend\AnalysisConsumer.cpp:747:0
#21 0x00007ff68adff820 `anonymous namespace'::AnalysisConsumer::HandleCode C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Frontend\AnalysisConsumer.cpp:698:0
#22 0x00007ff68adffce1 llvm::detail::DenseSetImpl<clang::Decl const *,llvm::DenseMap<clang::Decl const *,llvm::detail::DenseSetEmpty,llvm::DenseMapInfo<clang::Decl const *,void>,llvm::detail::DenseSetPair<clang::Decl const *> >,llvm::DenseMapInfo<clang::Decl const *,void> >::begin C:\Users\Administrator\source\repos\llvm-project\llvm\include\llvm\ADT\DenseSet.h:173:0
#23 0x00007ff68adffce1 `anonymous namespace'::AnalysisConsumer::HandleDeclsCallGraph C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Frontend\AnalysisConsumer.cpp:490:0
#24 0x00007ff68ae25213 `anonymous namespace'::AnalysisConsumer::runAnalysisOnTranslationUnit C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Frontend\AnalysisConsumer.cpp:560:0
#25 0x00007ff68ae002a5 `anonymous namespace'::AnalysisConsumer::HandleTranslationUnit C:\Users\Administrator\source\repos\llvm-project\clang\lib\StaticAnalyzer\Frontend\AnalysisConsumer.cpp:615:0
#26 0x00007ff68b21dd37 clang::ParseAST(class clang::Sema &, bool, bool) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x27edd37)
#27 0x00007ff68a3dc724 clang::ASTFrontendAction::ExecuteAction(void) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x19ac724)
#28 0x00007ff68a3dc525 clang::FrontendAction::Execute(void) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x19ac525)
#29 0x00007ff68a39fc1d clang::CompilerInstance::ExecuteAction(class clang::FrontendAction &) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x196fc1d)
#30 0x00007ff68a4521d6 clang::ExecuteCompilerInvocation(class clang::CompilerInstance *) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x1a221d6)
#31 0x00007ff688aad00d cc1_main(class llvm::ArrayRef<char const *>, char const *, void *) C:\Users\Administrator\source\repos\llvm-project\clang\tools\driver\cc1_main.cpp:249:0
#32 0x00007ff688aa63ac ExecuteCC1Tool C:\Users\Administrator\source\repos\llvm-project\clang\tools\driver\driver.cpp:366:0
#33 0x00007ff68a2a3011 std::_Uninitialized_copy_n<class std::optional<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>> *, class std::allocator<class std::optional<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>>>(class std::optional<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>> *, unsigned __int64, class std::optional<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>> *, class std::allocator<class std::optional<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>> &) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x1873011)
#34 0x00007ff6899c3eea llvm::CrashRecoveryContext::RunSafely(class llvm::function_ref<(void)>) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0xf93eea)
#35 0x00007ff68a2a3725 clang::driver::CC1Command::Execute(class llvm::ArrayRef<class std::optional<class llvm::StringRef>>, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> *, bool *) const (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x1873725)
#36 0x00007ff68a2145de clang::driver::Compilation::ExecuteCommand(class clang::driver::Command const &, class clang::driver::Command const *&, bool) const (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x17e45de)
#37 0x00007ff68a2147c0 clang::driver::Compilation::ExecuteJobs(class clang::driver::JobList const &, class llvm::SmallVectorImpl<struct std::pair<int, class clang::driver::Command const *>> &, bool) const (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x17e47c0)
#38 0x00007ff68a1f8481 clang::driver::Driver::ExecuteCompilation(class clang::driver::Compilation &, class llvm::SmallVectorImpl<struct std::pair<int, class clang::driver::Command const *>> &) (C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin\clang.exe+0x17c8481)
#39 0x00007ff688aa91bf clang_main(int, char **, struct llvm::ToolContext const &) C:\Users\Administrator\source\repos\llvm-project\clang\tools\driver\driver.cpp:542:0
#40 0x00007ff688ab76f4 main C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\tools\clang\tools\driver\clang-driver.cpp:16:0
#41 0x00007ff68c4049a4 invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78:0
#42 0x00007ff68c4049a4 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288:0
#43 0x00007ffae8eb4ed0 (C:\Windows\System32\KERNEL32.DLL+0x14ed0)
#44 0x00007ffaea92e39b (C:\Windows\SYSTEM32\ntdll.dll+0x7e39b)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 17.0.0 (http://gitlab.feysh.local/llvm-mirror/llvm-project.git f0a8c5c5cbed8d2afb76da8f2406cd056f170206)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\Administrator\source\repos\llvm-project\build-main-vs2022\Release\bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: C:\Users\ADMINI~1\AppData\Local\Temp\test-b09b40.c
clang: note: diagnostic msg: C:\Users\ADMINI~1\AppData\Local\Temp\test-b09b40.sh
clang: note: diagnostic msg:
```

Crashed with an `UndefinedVal` which seems to be impossible:

https://github.com/llvm/llvm-project/blob/5f9b4bc293c26d93c9115c5fbe99ddc4e5fab6da/clang/lib/StaticAnalyzer/Core/ConstraintManager.cpp#L92-L114

`Cond` is passed in from line 112, it's still valid here, but inside `assumeDual` it's an `UndefinedVal` for unknown reason.

Disable exception handling with `-DLLVM_ENABLE_EH=0`, the crash goes away.

**Comment by steakhal** [comment] 2023-08-29 11:19
Interesting. I'm still puzzled about what to do with this issue.

According to the official [minimal requirements](https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library), Visual Studio 2019 16.7 is the minimum.
Is this crash present on that toolchain? If not, and the most recent VS is also happy with this, I'd just close this issue.

**Comment by danix800** [comment] 2023-08-29 11:40
Sorry I didn't make it clear enough: it's Visual Studio 2022 Community Version 17.7.2, NOT Visual Studio 2017!

**Comment by steakhal** [comment] 2023-08-29 11:52
I see. If it's a miscompilation, and we can workaround this by using some different construct, we can merge such patches.

**Comment by danix800** [comment] 2023-08-29 12:23
I'll give it a try.

**Comment by danix800** [comment] 2023-08-30 04:50
Fix proposed: https://reviews.llvm.org/D159163

**Closed** 2023-08-30 09:15 UTC
Labels: clang:static analyzer
