### ISSUE TITLE
[DebugInfo] "fragment is larger than or outside of variable" assert after -globalopt

### ISSUE THREAD

**Issue by mcinally** [llvm/llvm-project#60148] opened 2023-01-19 16:32 UTC
@OCHyams 

The following commit appears to have introduced a DebugInfo regression:

```
commit e1b3d7ab44e19d5a67f9d1a05ea503d23b4c0dd5
Author: OCHyams <orlando.hyams@sony.com>
Date:   Wed Oct 26 17:15:02 2022 +0100

    Account for memory locations in DIExpression::createFragmentExpression
    
    createFragmentExpression rejects expressions containing certain ops, like
    DW_OP_plus, that may cause the expression to compute a value that can't be
    split.
    
    Teach createFragmentExpression that the value loaded from an address computed
    using those ops is safe to split.
    
    Update a unittest to account for and test this change.
    
    Reviewed By: StephenTozer
    
    Differential Revision: https://reviews.llvm.org/D136243
```

Here is a small reproducer. The failure originates in `-globalopt`:

```console
$ cat test.ll
source_filename = "test.ll"
target datalayout = "e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

%struct.BSS1.0.1.2.3.4.5.6.8.9.17 = type <{ [16 x i8] }>

@.BSS1 = internal global %struct.BSS1.0.1.2.3.4.5.6.8.9.17 zeroinitializer, align 32, !dbg !0, !dbg !7
@.C317_MAIN_ = external dso_local constant i32
@.C310_MAIN_ = external dso_local constant i32
@.C308_MAIN_ = external dso_local constant [8 x i8]
@.C307_MAIN_ = external dso_local constant i32
@.C283_MAIN_ = external dso_local constant i32
@llvm.global_ctors = external global [3 x { i32, ptr, ptr }]

define dso_local void @MAIN_() #0 !dbg !2 {
L.entry:
  %0 = mul i32 1, 1000
  store i32 %0, ptr getelementptr inbounds (%struct.BSS1.0.1.2.3.4.5.6.8.9.17, ptr @.BSS1, i64 0, i32 0, i64 12), align 4
  %1 = load i32, ptr getelementptr inbounds (%struct.BSS1.0.1.2.3.4.5.6.8.9.17, ptr @.BSS1, i64 0, i32 0, i64 12), align 4
  unreachable
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.value(metadata, metadata, metadata) #1

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.declare(metadata, metadata, metadata) #1

attributes #0 = { "frame-pointer"="all" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.module.flags = !{!15, !16}
!llvm.dbg.cu = !{!4}

!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "bb1", scope: !2, file: !3, type: !9, isLocal: true, isDefinition: true)
!2 = distinct !DISubprogram(name: "test", scope: !4, file: !3, line: 1, type: !13, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagMainSubprogram, unit: !4)
!3 = !DIFile(filename: "scrubbed", directory: "/scrubbed")
!4 = distinct !DICompileUnit(language: DW_LANG_Fortran90, file: !3, producer: " scrubbed", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !5, retainedTypes: !5, globals: !6, imports: !5)
!5 = !{}
!6 = !{!0, !7}
!7 = !DIGlobalVariableExpression(var: !8, expr: !DIExpression(DW_OP_plus_uconst, 8))
!8 = distinct !DIGlobalVariable(name: "bb2", scope: !2, file: !3, type: !9, isLocal: true, isDefinition: true)
!9 = !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 64, align: 32, elements: !11)
!10 = !DIBasicType(name: "integer", size: 32, align: 32, encoding: DW_ATE_signed)
!11 = !{!12}
!12 = !DISubrange(lowerBound: 1, upperBound: 2)
!13 = !DISubroutineType(cc: DW_CC_program, types: !14)
!14 = !{null}
!15 = !{i32 2, !"Dwarf Version", i32 4}
!16 = !{i32 2, !"Debug Info Version", i32 3}

$ opt test.ll -passes='globalopt' -S
fragment is larger than or outside of variable
!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression(DW_OP_plus_uconst, 8, DW_OP_LLVM_fragment, 96, 32))
!1 = distinct !DIGlobalVariable(name: "bb2", scope: !2, file: !3, type: !9, isLocal: true, isDefinition: true)
LLVM ERROR: Broken module found, compilation aborted!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: opt test.ll -passes=globalopt -S
 #0 0x000055fa5181cf48 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/scrubbed/bin/opt+0x1b1af48)
 #1 0x000055fa5181aebe llvm::sys::RunSignalHandlers() (/scrubbed/bin/opt+0x1b18ebe)
 #2 0x000055fa5181d6dd SignalHandler(int) Signals.cpp:0:0
 #3 0x0000151df7576b20 __restore_rt sigaction.c:0:0
 #4 0x0000151df683137f raise (/lib64/libc.so.6+0x3737f)
 #5 0x0000151df681bdb5 abort (/lib64/libc.so.6+0x21db5)
 #6 0x000055fa517ad27c llvm::report_fatal_error(llvm::Twine const&, bool) (/scrubbed/bin/opt+0x1aab27c)
 #7 0x000055fa517ad0a6 (/scrubbed/bin/opt+0x1aab0a6)
 #8 0x000055fa5122342c (/scrubbed/bin/opt+0x152142c)
 #9 0x000055fa5032e92d llvm::detail::PassModel<llvm::Module, llvm::VerifierPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/scrubbed/bin/opt+0x62c92d)
#10 0x000055fa511fb7d7 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/scrubbed/bin/opt+0x14f97d7)
#11 0x000055fa503268d7 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool) (/scrubbed/bin/opt+0x6248d7)
#12 0x000055fa50334c13 main (/scrubbed/bin/opt+0x632c13)
#13 0x0000151df681d493 __libc_start_main (/lib64/libc.so.6+0x23493)
#14 0x000055fa5031ed5e _start (/scrubbed/bin/opt+0x61cd5e)
Aborted (core dumped)
```

I am certainly not a DebugInfo expert, but it appears that the offset and size calculations are incorrect for bb2 after `-globalopt` runs.

This issue affects hundreds of our in-house tests, so pulling/fixing the patch would be greatly appreciated.

**Comment by OCHyams** [comment] 2023-01-20 08:35
I'll take a look - thanks for the reproducer.

**Comment by OCHyams** [comment] 2023-01-20 09:13
Your global variable `!1` "bb1" has the type `!9 = !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 64, align: 32, elements: !11)` which says `size: 64` that looks at odds with the size of the struct in IR which is `16 x i8`. If I ask clang to give me a `16 x i8` global with C we get:

`echo "char global[16];" | clang++ -g -emit-llvm -S -o - -x c -`
```
; ModuleID = '-'
source_filename = "-"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@global = dso_local global [16 x i8] zeroinitializer, align 16, !dbg !0

!llvm.dbg.cu = !{!2}
!llvm.module.flags = !{!10, !11, !12, !13, !14, !15, !16}
!llvm.ident = !{!17}

!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "global", scope: !2, file: !5, line: 1, type: !6, isLocal: false, isDefinition: true)
!2 = distinct !DICompileUnit(language: DW_LANG_C11, file: !3, producer: "clang version 16.0.0", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, globals: !4, splitDebugInlining: false, nameTableKind: None)
!3 = !DIFile(filename: "-", directory: "/")
!4 = !{!0}
!5 = !DIFile(filename: "<stdin>", directory: "/")
!6 = !DICompositeType(tag: DW_TAG_array_type, baseType: !7, size: 128, elements: !8)
!7 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!8 = !{!9}
!9 = !DISubrange(count: 16)
!10 = !{i32 7, !"Dwarf Version", i32 5}
!11 = !{i32 2, !"Debug Info Version", i32 3}
!12 = !{i32 1, !"wchar_size", i32 4}
!13 = !{i32 8, !"PIC Level", i32 2}
!14 = !{i32 7, !"PIE Level", i32 2}
!15 = !{i32 7, !"uwtable", i32 2}
!16 = !{i32 7, !"frame-pointer", i32 2}
!17 = !{!"clang version 16.0.0"}
```
Here the size is `size: 128`.

Is the `DICompositeType !9` in your reproducer the correct size, and do you have source you can share?

**Comment by OCHyams** [comment] 2023-01-20 16:54
Ignore my previous comment - coming back to this I see that there are two variables associated with the global being transformed and their debug info look reasonable. It may be my patch that has caused the problem but my current thinking is that it may have just exposed a problem elsewhere (such as GlobalOpt's debug-info handling).

**Comment by OCHyams** [comment] 2023-01-20 17:12
To give more context to why I think my patch is just exposing other issues:

`transferSRADebugInfo` is called to update the debug info after globalopt splits the global `@.BSS1`. `transferSRADebugInfo` calls `createFragmentExpression`. Prior to my patch that always (unnecessarily) failed for your variable `!7 = !DIGlobalVariableExpression(var: !8, expr: !DIExpression(DW_OP_plus_uconst, 8))` due to the expression containing arithmetic operations - and the debug info was then dropped as a result. With my patch, `createFragmentExpression` succeeds and the expression `!DIExpression(DW_OP_plus_uconst, 8, DW_OP_LLVM_fragment, 96, 32)` is created and subsequently transferred to the split global.

That expression is definitely wrong - there should be no offset and I believe the fragment should be `DW_OP_LLVM_fragment, 32, 32` (offset = 32 for that variable, rather than offset = 96, which is actually the offset of the slice from the base memory location rather than start of the variable). I haven't worked out if that's `transferSRADebugInfo` or `createFragmentExpression`'s fault just yet.

I don't have time to look just now (it's the end of my work day) but I get the feeling `transferSRADebugInfo` also needs to learn to adjust the offset in expression (in this case make it zero / remove it).

**Comment by OCHyams** [comment] 2023-01-23 10:24
Hi @mcinally. I've found the root cause of this (TL;DR my patch exposes a latent bug elsewhere). I am not able to work on a fix right now - are you using trunk or a specific llvm release? For the latter, I think it could be reasonable for us to backport a revert of my patch to avoid triggering the bug.

### Root cause / collating my findings

In the reproducer, there's a 128-bit global value located at `@.BSS1` with two source variables associated with it. Variable `bb1` covers bits 0-63 of the global and `bb2` covers bits 64-127. Only bits 96-127 are used in the reproducer IR so `globalopt` splits `@.BSS1` into only that slice.

`transferSRADebugInfo` is responsible for updating the debug info and it produces an expression `DIExpression(DW_OP_plus_uconst, 8, DW_OP_LLVM_fragment, 96, 32)` for `bb2`. The bits at  offset=96 size=32 are indeed the slice of the global value that remain, however, that is incorrect debug info as the fragment needs to written in terms of `bb2`. It should be offset=32 size =32. Furthermore, there should be no offset applied to the new global value address (`DW_OP_plus_uconst, 8`) given that the sliced global value points directly to the remaining fragment of `bb2`.

A quick fix without reverting my patch would be to skip cases where the variable being worked on in `transferSRADebugInfo` is located at a non-zero offset from the global pointer. Or, as a proper fix, teach `transferSRADebugInfo` to do the right thing here.

The reason my patch mentioned in the description causes this to start happening is it changes `createFragmentExpression` (called by `transferSRADebugInfo`) to succeed in producing a fragment more often. Prior to the patch `createFragmentExpression` would fail and the debug info for the global would be dropped (hiding the issue).

**Comment by mcinally** [comment] 2023-01-23 15:58
Thanks, @OCHyams. I'll pass this along to our DebugInfo expert.

**Comment by mcinally** [comment] 2023-03-13 17:53
Sorry for the slow reply, @OCHyams. Our out-of-tree compiler is ok for the 16.0 release. 

Maybe we should unassign this issue from you so that someone interested can pick it up?

**Comment by OCHyams** [comment] 2023-03-14 11:39
> Maybe we should unassign this issue from you so that someone interested can pick it up?

SGTM, thank you.

Just a note - I haven't looked too closely or tested it but [D138992](https://reviews.llvm.org/D138992) (by @alokkrsharma) looks highly relevant and may fix this (currently it looks like the patch is stalled in review).

**Comment by alokkrsharma** [comment] 2023-03-14 11:44
[AMD Official Use Only - General]

I'll resume it now. Sorry for the inconvenience.

Regards,
Alok

**Comment by OCHyams** [comment] 2023-04-06 15:16
I have tested this now @alokkrsharma's patch (https://reviews.llvm.org/D138992) has landed and the issue appears to have been fixed. The verifier error no longer fires and the debug info for the sliced-up global now looks correct:

```
$ opt -passes=globalopt test.ll -S -o -
; ModuleID = 'test.ll'
source_filename = "test.ll"
target datalayout = "e-p:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

@.BSS1.0 = internal unnamed_addr global i32 0, align 32, !dbg !0

define dso_local void @MAIN_() local_unnamed_addr #0 !dbg !2 {
L.entry:
  %0 = mul i32 1, 1000
  store i32 %0, ptr @.BSS1.0, align 32
  %1 = load i32, ptr @.BSS1.0, align 32
  unreachable
}

attributes #0 = { "frame-pointer"="all" }

!llvm.module.flags = !{!16, !17}
!llvm.dbg.cu = !{!4}

!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression(DW_OP_LLVM_fragment, 32, 32))
!1 = distinct !DIGlobalVariable(name: "bb2", scope: !2, file: !3, type: !9, isLocal: true, isDefinition: true)
!2 = distinct !DISubprogram(name: "test", scope: !4, file: !3, line: 1, type: !14, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagMainSubprogram, unit: !4)
!3 = !DIFile(filename: "scrubbed", directory: "/scrubbed")
!4 = distinct !DICompileUnit(language: DW_LANG_Fortran90, file: !3, producer: " scrubbed", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !5, retainedTypes: !5, globals: !6, imports: !5)
!5 = !{}
!6 = !{!7, !13}
!7 = !DIGlobalVariableExpression(var: !8, expr: !DIExpression())
!8 = distinct !DIGlobalVariable(name: "bb1", scope: !2, file: !3, type: !9, isLocal: true, isDefinition: true)
!9 = !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 64, align: 32, elements: !11)
!10 = !DIBasicType(name: "integer", size: 32, align: 32, encoding: DW_ATE_signed)
!11 = !{!12}
!12 = !DISubrange(lowerBound: 1, upperBound: 2)
!13 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression(DW_OP_plus_uconst, 8))
!14 = !DISubroutineType(cc: DW_CC_program, types: !15)
!15 = !{null}
!16 = !{i32 2, !"Dwarf Version", i32 4}
!17 = !{i32 2, !"Debug Info Version", i32 3}
```

Closing as fixed.

**Closed by OCHyams** 2023-04-06 15:16 UTC
Labels: debuginfo
