### ISSUE TITLE
Bug when using std::vector in constexpr context

### ISSUE THREAD

**Issue by gergol** [llvm/llvm-project#57788] opened 2022-09-16 20:05 UTC
The following code compiles with gcc and MSVC, but not with clang 15 and latest trunk. It seems to miss the deallocations and reports an error. 

```cpp
#include <array>
#include <vector>

consteval void foo(auto func) {
    std::array<int, func().size()> f;
}

int main() {
    foo([](){ return std::vector<int>{1,2,3,4,5};});
}

```

[Compiler explorer](https://godbolt.org/z/PadTK7cEE)
[Question on SO](https://stackoverflow.com/questions/73748978/compiler-disagreement-on-using-stdvector-in-constexpr-context)

**Comment by shafik** [comment] 2022-09-16 20:15
Simplified reproducer:

```cpp
struct V {
    int* v = new int[10];
    constexpr ~V() { delete[] v; }
    constexpr int size() { return 10; }
};

template<auto>
struct A {};

int main() {
    constexpr auto x = V{}.size(); //1
    using T = A<V{}.size()>;       //2
}
```

Also this crashes on clang trunk see godbolt: https://godbolt.org/z/o1zsrs3qK

```cpp
Unhandled cleanup; missing full expression marker?
UNREACHABLE executed at /root/llvm-project/clang/lib/AST/ExprConstant.cpp:15177!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 <source>
1.	<source>:12:15: at annotation token
2.	<source>:10:12: parsing function body 'main'
3.	<source>:10:12: in compound statement ('{}')
 #0 0x00005573d0a823f4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005573d0a8019c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e8a19c)
 #2 0x00005573d09b6d18 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f75db208420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f75dacd500b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f75dacb4859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00005573d09c035e (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3dca35e)
 #7 0x00005573d404951c clang::Expr::EvaluateAsConstantExpr(clang::Expr::EvalResult&, clang::ASTContext const&, clang::Expr::ConstantExprKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x745351c)
 #8 0x00005573d386faa2 CheckConvertedConstantExpression(clang::Sema&, clang::Expr*, clang::QualType, clang::APValue&, clang::Sema::CCEKind, bool, clang::NamedDecl*) SemaOverload.cpp:0:0
 #9 0x00005573d3870032 clang::Sema::CheckConvertedConstantExpression(clang::Expr*, clang::QualType, clang::APValue&, clang::Sema::CCEKind, clang::NamedDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6c7a032)
#10 0x00005573d39208a6 clang::Sema::CheckTemplateArgument(clang::NonTypeTemplateParmDecl*, clang::QualType, clang::Expr*, clang::TemplateArgument&, clang::Sema::CheckTemplateArgumentKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d2a8a6)
#11 0x00005573d392953c clang::Sema::CheckTemplateArgument(clang::NamedDecl*, clang::TemplateArgumentLoc&, clang::NamedDecl*, clang::SourceLocation, clang::SourceLocation, unsigned int, llvm::SmallVectorImpl<clang::TemplateArgument>&, clang::Sema::CheckTemplateArgumentKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d3353c)
#12 0x00005573d392c519 clang::Sema::CheckTemplateArgumentList(clang::TemplateDecl*, clang::SourceLocation, clang::TemplateArgumentListInfo&, bool, llvm::SmallVectorImpl<clang::TemplateArgument>&, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d36519)
#13 0x00005573d393172b clang::Sema::CheckTemplateIdType(clang::TemplateName, clang::SourceLocation, clang::TemplateArgumentListInfo&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d3b72b)
#14 0x00005573d393422f clang::Sema::ActOnTemplateIdType(clang::Scope*, clang::CXXScopeSpec&, clang::SourceLocation, clang::OpaquePtr<clang::TemplateName>, clang::IdentifierInfo*, clang::SourceLocation, clang::SourceLocation, llvm::MutableArrayRef<clang::ParsedTemplateArgument>, clang::SourceLocation, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6d3e22f)
#15 0x00005573d312f9ae clang::Parser::AnnotateTemplateIdTokenAsType(clang::CXXScopeSpec&, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65399ae)
#16 0x00005573d30812b3 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x648b2b3)
#17 0x00005573d3083454 clang::Parser::ParseSpecifierQualifierList(clang::DeclSpec&, clang::AccessSpecifier, clang::Parser::DeclSpecContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x648d454)
#18 0x00005573d3072124 clang::Parser::ParseTypeName(clang::SourceRange*, clang::DeclaratorContext, clang::AccessSpecifier, clang::Decl**, clang::ParsedAttributes*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x647c124)
#19 0x00005573d309151d clang::Parser::ParseAliasDeclarationAfterDeclarator(clang::Parser::ParsedTemplateInfo const&, clang::SourceLocation, clang::Parser::UsingDeclarator&, clang::SourceLocation&, clang::AccessSpecifier, clang::ParsedAttributes&, clang::Decl**) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x649b51d)
#20 0x00005573d309aa23 clang::Parser::ParseUsingDeclaration(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::SourceLocation, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64a4a23)
#21 0x00005573d309b125 clang::Parser::ParseUsingDirectiveOrDeclaration(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::SourceLocation&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64a5125)
#22 0x00005573d308a878 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6494878)
#23 0x00005573d311c5b9 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x65265b9)
#24 0x00005573d311d225 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6527225)
#25 0x00005573d311e28a clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x652828a)
#26 0x00005573d311fb5a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6529b5a)
#27 0x00005573d3055b51 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x645fb51)
#28 0x00005573d308965f clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x649365f)
#29 0x00005573d304a6f9 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64546f9)
#30 0x00005573d304af50 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#31 0x00005573d3050701 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x645a701)
#32 0x00005573d305159a clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x645b59a)
#33 0x00005573d3045a0a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x644fa0a)
#34 0x00005573d1d97ac8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x51a1ac8)
#35 0x00005573d162dbc9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4a37bc9)
#36 0x00005573d15b627e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49c027e)
#37 0x00005573d17128e3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4b1c8e3)
#38 0x00005573cdff09d4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x13fa9d4)
#39 0x00005573cdfe9b08 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#40 0x00005573d14265f9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#41 0x00005573d09b74ba llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3dc14ba)
#42 0x00005573d1426e4f clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#43 0x00005573d13f1499 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47fb499)
#44 0x00005573d13f1f1d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x47fbf1d)
#45 0x00005573d13fb99c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x480599c)
#46 0x00005573cdfeedb3 clang_main(int, char**) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x13f8db3)
#47 0x00007f75dacb6083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#48 0x00005573cdfe96fe _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x13f36fe)
clang-16: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

**Comment by junaire** [comment] 2022-09-17 13:50
Even this:
```
struct V {
    constexpr ~V() {}
    constexpr int size() { return 1; }
};

template<int>
struct A {};

int main() {
   A<V{}.size()>;
}
```

**Comment by junaire** [comment] 2022-09-18 04:41
Looks like `V` have a non-trivial destructor so `EvalInfo::discardCleanups` returns false, then we hit the `llvm_unreachable`.

**Comment by cor3ntin** [comment] 2023-06-06 09:56
This was fixed in https://github.com/llvm/llvm-project/commit/9857caf9d14f70767035d821313045b56dbe3b10

**Closed by cor3ntin** 2023-06-06 09:56 UTC
Labels: clang:frontend, confirmed, crash
