### ISSUE TITLE
clang-format AlignConsecutiveAssignments failure

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#55265] opened 2022-05-04 13:32 UTC
Consider:

```console
$ cat /tmp/a.cc
#if A
bool thisisalongvariablename = true;
#else
bool thisisalongvariablename = false;
#endif

#if B
bool shortervarname = true;
#else
bool shortervarname = false;
#endif

$ build.release/bin/clang-format -style="{AlignConsecutiveAssignments: true}" /tmp/a.cc
#if A
bool thisisalongvariablename = true;
#else
bool thisisalongvariablename = false;
#endif

#if B
bool shortervarname = true;
#else
bool shortervarname          = false;
#endif
```

Note that the second initializer of shortervarname gets properly aligned, but not the first one.

I wasn't able to find a clang-format where this worked, so it doesn't seem to be a regression.

(Split out from https://github.com/llvm/llvm-project/issues/55161)

**Comment by owenca** [comment] 2022-05-05 21:16
We don't have an "AcrossPPDirectives" option, so IMO the correct formatting is:
```
bool thisisalongvariablename = true;
#else
bool thisisalongvariablename = false;
#endif

#if B
bool shortervarname = true;
#else
bool shortervarname = false;
#endif
```
That is, PPDirectives should break the consecutiveness.

**Comment by bdl126** [comment] 2023-05-01 19:54
I'm seeing something similar on my end. I've noticed that if the conditional PP is in an if statement, the else of the next conditional PP will not work :

`
if (x) {
#if SOMETHING
    var                     = assigment;
    long_var           = assigment;
    long_long_var = assigment;
#else
    var                     = assigment;
    long_var           = assigment;
    long_long_var = assigment;
#endif
}

#if SOMETHING
var                     = assigment;
long_var           = assigment;
long_long_var = assigment;
#else
var = assigment;
long_var = assigment;
long_long_var = assigment;
#endif

`

**Comment by owenca** [comment] 2023-05-07 01:56
Duplicate of #61498.

**Closed** 2023-05-07 02:11 UTC
Labels: bug, duplicate, clang-format
