### ISSUE TITLE
Wrong code at -O3 on x86_64-linux_gnu  since 1fc425380e9860a6beb53fa68d02e7fb14969963

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#64333] opened 2023-08-02 08:29 UTC
Clang at -O3 produces wrong code. 

Bisect to 1fc425380e9860a6beb53fa68d02e7fb14969963, which was committed by @nikic  

Compiler explorer: https://godbolt.org/z/EE8eKvKce

```console
% cat a.c
int printf(const char *, ...);
int a;
static long b = 2065201973, c;
char d, e;
short f;
short(g)(short h, short i) { return h + i; }
int j(int h) {
  if (h < 8)
    return 0;
  return (h < 48) & (1 << (h - 2));
}
void k(long *h) {}
int main() {
  long *l = &b;
  k(l);
  for (; c >= 0; --c) {
    for (; d <= 8; d = e = g(e, 4)) {
      f = 0;
      for (; (unsigned short)(j(b - 2065201972) + b - 2065201973) + f <= 4; f++)
        ;
    }
    for (; f + (int)b - 2065201978;)
      ;
  }
  printf("%X\n", a);
}
% clang -O0 a.c && ./a.out
0
% clang -O3 a.c && ./a.out
Killed - processing time exceeded
%
```

**Comment by nikic** [comment] 2023-08-07 08:45
From a quick look this is likely another duplicate of https://github.com/llvm/llvm-project/issues/63763.

**Closed** 2023-08-22 07:27 UTC
Labels: miscompilation, llvm:instcombine
