### ISSUE TITLE
Use of I32Attr from OpBase.td in AttrDef crashes in table gen.

### ISSUE THREAD

**Issue by nitish2112** [llvm/llvm-project#60774] opened 2023-02-15 16:56 UTC
```
include "mlir/IR/OpBase.td"

def Foo : AttrDef<Some_Dialect, "Doo"> {
  let summary = "...";

  let mnemonic = "foo";

  let parameters = (ins
    I32Attr:$bar
  );

  let assemblyFormat = "`<` struct(params) `>`";
}
```

when compiled using tablegen crashes.

**Comment by ftynse** [comment] 2023-02-15 16:58
@River707 looks like yours?

**Comment by Mogball** [comment] 2023-02-15 17:04
Dupe of https://github.com/llvm/llvm-project/issues/60671

**Closed by Mogball** 2023-02-15 17:04 UTC
Labels: duplicate, mlir:core
