### ISSUE TITLE
clang does not handle _Static_assert() in switch statement

### ISSUE THREAD

**Issue by shemminger** [llvm/llvm-project#78217] opened 2024-01-16 00:23 UTC
Any _Static_assert() in leg of switch statement generates error from expected: expression. This works with gcc.

Example:
$ cat switch-assert-bug.c 
```c
/* Simple program to show that clang cant do Static_assert in switch */
unsigned foo(unsigned x)
{
	unsigned m = 0;

	_Static_assert(1, "assert in function works");
	if (x == 1) {
		_Static_assert(1, "assert in if works");
		m |= 1;
	}
	switch (x) {
	case 2:
	case 3:
		_Static_assert(1, "assert in switch works");
		m |= 2;
		break;
	default:
		m |= 4;
	}
	return m;
}
```
$ clang -c switch-assert-bug.c
switch-assert-bug.c:14:3: error: expected expression
                _Static_assert(1, "assert in switch works");
                ^
1 error generated.

**Comment by shafik** [comment] 2024-01-16 04:13
This looks fixed in trunk: https://godbolt.org/z/5nr6Y4W5a

CC @AaronBallman

**Closed by shafik** 2024-01-16 04:13 UTC
Labels: c11, clang:frontend

**Comment by EugeneZelenko** [comment] 2024-01-16 15:29
Duplicate of #56040 to be more precise.
