### ISSUE TITLE
UNREACHABLE when having DW_OP_LLVM_arg inside DBG_VALUE (caused by debug info salvaging in loop-reduce?)

### ISSUE THREAD

**Issue by bjope** [llvm/llvm-project#55097] opened 2022-04-26 09:00 UTC
Given the attached reproducer  [lsr-debug.ll.gz](https://github.com/llvm/llvm-project/files/8561323/lsr-debug.ll.gz)

When running

```shell
llc -mtriple ppc lsr-debug.ll
```

the result is

```console
UNREACHABLE executed at ../lib/CodeGen/AsmPrinter/DwarfExpression.cpp:486!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: build-all/bin/llc lsr-debug.ll -mtriple ppc
1.      Running pass 'Function Pass Manager' on module 'lsr-debug.ll'.
2.      Running pass 'Linux PPC Assembly Printer' on function '@loopbody_9'
 #0 0x0000000002af4653 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build-all/bin/llc+0x2af4653)
 #1 0x0000000002af22ce llvm::sys::RunSignalHandlers() (build-all/bin/llc+0x2af22ce)
 #2 0x0000000002af49d6 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f2ce1060630 __restore_rt sigaction.c:0:0
 #4 0x00007f2cde7a7387 raise (/lib64/libc.so.6+0x36387)
 #5 0x00007f2cde7a8a78 abort (/lib64/libc.so.6+0x37a78)
 #6 0x0000000002a62c9f (build-all/bin/llc+0x2a62c9f)
 #7 0x0000000001d08139 (build-all/bin/llc+0x1d08139)
 #8 0x0000000001d08116 (build-all/bin/llc+0x1d08116)
 #9 0x0000000001d07613 llvm::DwarfExpression::addExpression(llvm::DIExpressionCursor&&, llvm::function_ref<bool (unsigned int, llvm::DIExpressionCursor&)>) (build-all/bin/llc+0x1d07613)
#10 0x0000000001d072b0 llvm::DwarfExpression::addExpression(llvm::DIExpressionCursor&&) (build-all/bin/llc+0x1d072b0)
#11 0x0000000001d5e92a llvm::DwarfCompileUnit::addComplexAddress(llvm::DbgVariable const&, llvm::DIE&, llvm::dwarf::Attribute, llvm::MachineLocation const&) (build-all/bin/llc+0x1d5e92a)
#12 0x0000000001d5bf9d llvm::DwarfCompileUnit::addVariableAddress(llvm::DbgVariable const&, llvm::DIE&, llvm::MachineLocation) (build-all/bin/llc+0x1d5bf9d)
#13 0x0000000001d5b581 llvm::DwarfCompileUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool) (build-all/bin/llc+0x1d5b581)
#14 0x0000000001d5a3ec llvm::DwarfCompileUnit::createAndAddScopeChildren(llvm::LexicalScope*, llvm::DIE&) (build-all/bin/llc+0x1d5a3ec)
#15 0x0000000001d5c111 llvm::DwarfCompileUnit::constructSubprogramScopeDIE(llvm::DISubprogram const*, llvm::LexicalScope*) (build-all/bin/llc+0x1d5c111)
#16 0x0000000001ceca29 llvm::DwarfDebug::endFunctionImpl(llvm::MachineFunction const*) (build-all/bin/llc+0x1ceca29)
#17 0x0000000001cd7ebe llvm::DebugHandlerBase::endFunction(llvm::MachineFunction const*) (build-all/bin/llc+0x1cd7ebe)
#18 0x0000000001cc19e7 llvm::AsmPrinter::emitFunctionBody() (build-all/bin/llc+0x1cc19e7)
```

This is what I see if adding `-debug -print-after-all`:

### `LoopStrengthReduce` (LSR)

loop-reduce is salvaging debug info (in two steps, I think the test case perhaps can be reduce to just include the first step):

```console
scev-salvage: Updating:   call void @llvm.dbg.value(metadata i16 undef, metadata !14, metadata !DIExpression()), !dbg !15
scev-salvage: to:   call void @llvm.dbg.value(metadata i16 %turns.011, metadata !14, metadata !DIExpression(DW_OP_consts, 8, DW_OP_div, DW_OP_consts, 4, DW_OP_mul, DW_OP_LLVM_arg, 0, DW_OP_plus, DW_OP_stack_value)), !dbg !15
...
scev-salvage: Updating:   call void @llvm.dbg.value(metadata i16 undef, metadata !14, metadata !DIExpression(DW_OP_consts, 8, DW_OP_div, DW_OP_consts, 4, DW_OP_mul, DW_OP_LLVM_arg, 0, DW_OP_plus, DW_OP_stack_value)), !dbg !15
scev-salvage: to:   call void @llvm.dbg.value(metadata i16 %m.010, metadata !14, metadata !DIExpression(DW_OP_consts, 8, DW_OP_mul, DW_OP_consts, 8, DW_OP_div, DW_OP_consts, 4, DW_OP_mul, DW_OP_LLVM_arg, 0, DW_OP_plus, DW_OP_stack_value)), !dbg !15
```

The `applyExprToDbgValue` method is actually taking a decision to use `setShortFinalExpression` based on only having a single `DW_OP_LLVM_arg` in the new `Expr` (not taking `OldExpr` into account, **is that a problem?**). Anyway, this decision is resulting in using `DW_OP_LLVM_arg` without also having a `DIArgList`. **Is that really allowed? Seems like a special case that just complicate the logic for the rest of the backend?**

### `ISel`

Given that we have 

```llvm
call void @llvm.dbg.value(metadata i16 %m.010, metadata !14, metadata !DIExpression(DW_OP_consts, 8, DW_OP_mul, DW_OP_consts, 8, DW_OP_div, DW_OP_consts, 4, DW_OP_mul, DW_OP_LLVM_arg, 0, DW_OP_plus, DW_OP_stack_value)), !dbg !18
```

in the input to `ISel` (no `DIArgList`)  it seems like we get

```llvm
call void @llvm.dbg.value(metadata i16 %m.010, metadata !14, metadata !DIExpression(DW_OP_consts, 8, DW_OP_mul, DW_OP_consts, 8, DW_OP_div, DW_OP_consts, 4, DW_OP_mul, DW_OP_LLVM_arg, 0, DW_OP_plus, DW_OP_stack_value)), !dbg !18
```

out from `ISel`. I.e. there is a `DBG_VALUE` with `DW_OP_LLVM_arg` in the `DIExpression` and not a `DBG_VALUE_LIST`.

**Is that supported? Or should MachineVerifier detect this as invalid?**

### `DwarfDebug` / `DwarfExpression`

The logic in `DwarfDebug::emitDebugLocValue` looks like this:

```cpp
  ...

  if (!Value.isVariadic()) {
    if (!EmitValueLocEntry(Value.getLocEntries()[0], ExprCursor))
      return;
    DwarfExpr.addExpression(std::move(ExprCursor));
    return;
  }

  // If any of the location entries are registers with the value 0, then the
  // location is undefined.
  if (any_of(Value.getLocEntries(), [](const DbgValueLocEntry &Entry) {
        return Entry.isLocation() && !Entry.getLoc().getReg();
      }))
    return;

  DwarfExpr.addExpression(
      std::move(ExprCursor),
      [EmitValueLocEntry, &Value](unsigned Idx,
                                  DIExpressionCursor &Cursor) -> bool {
        return EmitValueLocEntry(Value.getLocEntries()[Idx], Cursor);
      });
```

Afaict the `isVariadic` check is looking for `DBG_VALUE_LIST`. So unless having such we enter the early if statement and call `DwarfExpr.addExpression` without the `InsertArg` helper function that is needed to deal with `DW_OP_LLVM_arg`.

So depending on the correctness of `LoopStrengthReduce` (and ISel) I guess the `isVariadic` check might need to scan the `DIExpression` to look for `DW_OP_LLVM_arg` rather than just looking for `DBG_VALUE_LIST`. Or maybe it should provide an  `InsertArg` helper also in that first call to `DwarfExpr.addExpression`?

### Summary

Either `LSR`, `ISel` or `DwarfDebug` seem to be broken. Or maybe in some sense all of them unless MachineVerifier would stipulate some rules here and then the passes wouldn't need to check validity themselves.

**Comment by bjope** [comment] 2022-04-26 09:10
@Melamoto , do you know anything about this? I think you wrote the relevant code in DwarfDebug.

And chris.jackson@sony.com seem to have written the code in LSR. But I couldn't find any matching github user.

**Comment by OCHyams** [comment] 2022-04-26 09:19
(cc @chrisjbris - chris.jackson@sony.com's github username)

**Comment by Melamoto** [comment] 2022-04-26 10:26
> @Melamoto , do you know anything about this? I think you wrote the relevant code in DwarfDebug.
> 
> And [chris.jackson@sony.com](mailto:chris.jackson@sony.com) seem to have written the code in LSR. But I couldn't find any matching github user.

The answer would be that yes, there should not be a DBG_VALUE with a DW_OP_LLVM_arg in its expression - the latter is an index into a list of arguments, and DBG_VALUE does not use a list. I've left a comment on the Phabricator review, but to copy it here:

> I think I see the issue here, I brought up the same thing on the more recent LSR-salvage patch: This check is overly permissive. Specifically, the check `Values.size() == 1` only checks that there is only one value in the value list, not that there is only one DW_OP_LLVM_arg in the expression; i.e. if the DIExpression is `!(DW_OP_LLVM_arg 0, DW_OP_LLVM_arg 0, DW_OP_plus)`, it would still return true. Thus, when this function sees an expression like that, it assumes that it is safe to emit the short form and drops the first operator, producing `dbg.value(%value, !123, !DIExpression(DW_OP_LLVM_arg 0, DW_OP_plus)`.
> 
> Also, Chris's new patch stack will fix this when it lands, and I'm just about to approve it - will that be suitable, or is a temp fix needed? (For a very quick and dirty temp fix, adding `&& std::count_if(expr_op_iterator(Expr.begin()), expr_op_iterator(Expr.end()), [](auto ExprOp) { return ExprOp.getOp() == llvm::dwarf::DW_OP_LLVM_arg; }) == 1` would be the simplest fix.

**Comment by bjope** [comment] 2022-04-26 10:34
> > I think I see the issue here, I brought up the same thing on the more recent LSR-salvage patch: This check is overly permissive. Specifically, the check `Values.size() == 1` only checks that there is only one value in the value list, not that there is only one DW_OP_LLVM_arg in the expression; i.e. if the DIExpression is `!(DW_OP_LLVM_arg 0, DW_OP_LLVM_arg 0, DW_OP_plus)`, it would still return true. Thus, when this function sees an expression like that, it assumes that it is safe to emit the short form and drops the first operator, producing `dbg.value(%value, !123, !DIExpression(DW_OP_LLVM_arg 0, DW_OP_plus)`.

Yes, right. I just verified that we have two DW_OP_LLVM_arg with same index. And the setShortFinalExpression omit one of them (I misread omit as emit when I looked at the code the first time, probably since the IR dump after the pass included an DW_OP_LLVM_arg so I missed that it had omitted the second occurance).

> > Also, Chris's new patch stack will fix this when it lands, and I'm just about to approve it - will that be suitable, or is a temp fix needed? (For a very quick and dirty temp fix, adding `&& std::count_if(expr_op_iterator(Expr.begin()), expr_op_iterator(Expr.end()), [](auto ExprOp) { return ExprOp.getOp() == llvm::dwarf::DW_OP_LLVM_arg; }) == 1` would be the simplest fix.

Thanks! Maybe I'll use that workaround downstream until those other fixes has landed.
Would be nice if this github issue either is linked as a duplicate to any other issue related to those patches. Or maybe you can reference this issue in those patches?

**Comment by chrisjbris** [comment] 2022-04-26 12:06
Hello, sorry for taking so long to respond! It seems this bug has existed for some time but has only just reared its head. Thanks for reporting this and providing analysis @bjope. @Melamoto 's reponse is comprehensive, in fact he spotted the bug in the new patch series a couple of weeks ago! The patch series that will include the fix (as well as significantly increasing the salvages possible) has been accepted and is ready to land. However, I'm in meetings this afternoon, so I won't push until this evening or tomorrow so I can monitor the upstream CI.

This logic was included because the previous salvaging method in LSR did not output variadic-location dbg.value. SCEV-based salvaging does, and while it enabled a superset of the old salvages, I was reluctant to output dbg.values that were more verbose than those output by the previous method. Perhaps this was wrong the choice because it adds a chunk of logic that only shortens expressions that are already correct, and has led to this bug! 

I'll update this issue once I've landed the new patches and hopefully it will be resolved.

**Comment by chrisjbris** [comment] 2022-04-27 13:18
The patch hhat includes the fix has landed with commit [74273d57](https://github.com/llvm/llvm-project/commit/74273d575f9938d751a1c67862cffe553fe2de8b). The function UpdateDbgValueInst() in LoopStrengthReduce.cpp contains the relevant logic.

**Comment by fhahn** [comment] 2022-04-28 10:22
Thanks @chrisjbris! IIUC this has been fixed by 74273d57 and I am closing the issue. @bjope please re-open if the issue still reproduces on your end.

**Closed by fhahn** 2022-04-28 10:22 UTC
Labels: debuginfo, llvm:crash

**Comment by chrisjbris** [comment] 2022-04-28 10:56
Please hold fire, my patch had a memory management oversight that I'm fixing now. Its an easy fix so hopefully we can close this issue properly tomorrow.

**Comment by chrisjbris** [comment] 2022-04-28 13:28
I've relanded the amended patch, so this issue should be good to remain closed, barring any further bot findings.

**Comment by fhahn** [comment] 2022-04-28 13:48
Thanks!
