### ISSUE TITLE
[clang/lldb] Could not evaluate DW_OP_entry_value for argv and argc

### ISSUE THREAD

**Issue by iamanonymouscs** [llvm/llvm-project#55760] opened 2022-05-29 05:54 UTC
`$ cat small.c`

```c
#include <stdlib.h>
#include <string.h>

int b = 9;
int main(int argc, char **argv) {
  char *x = (char*)malloc(10);
  memset(x, 0, 10);
  int res = x[b];
  free(x);
  return res;
}
```

`$ clang -Ofast -g small.c; lldb a.out`

```
(lldb) target create "a.out"
Current executable set to '/root/DeVIL/a.out' (x86_64).
(lldb) b 10
Breakpoint 1: where = a.out`main + 35 at small.c:10:3, address = 0x00000000000006f3
(lldb) r
Process 23848 launched: '/root/DeVIL/a.out' (x86_64)
Process 23848 stopped
* thread #1, name = 'a.out', stop reason = breakpoint 1.1
    frame #0: 0x00005555555546f3 a.out`main(argc=<unavailable>, argv=<unavailable>) at small.c:10:3
   7      memset(x, 0, 10);
   8      int res = x[b];
   9      free(x);
-> 10     return res;
   11   }
(lldb) fr var
(int) argc = <Could not evaluate DW_OP_entry_value.>

(char **) argv = <Could not evaluate DW_OP_entry_value.>

(char *) x = <variable not available>

(int) res = 0
(lldb) 
```

As can be seen, `argc` and `argv ` are `<Could not evaluate DW_OP_entry_value.>`. 
When Line 10 is changed to `return 0;`, the result is correct. 

`$ clang --version`

```
Ubuntu clang version 15.0.0-++20220525063926+1f06398e96d4-1~exp1~20220525183937.510
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by dwblaikie** [comment] 2022-05-30 23:08
This sounds correct to me - any reason you believe it's not correct/where do you think this behavior should be changed?

The compiler optimized away the values, but said "hey, if you happen to be able to find the value of these parameters in the caller (if they had to be caller-saved, for instance) then you could still recover their values with that" - but presumably libc debug info doesn't have the location over the call (probably didn't save the value?) so there's no way to recover the value.

**Comment by yangyibiao** [comment] 2022-05-31 03:08
Thanks. In the stable version of clang/lldb, the behavior is different. Thus, I was wondering this might be a potential bug. 

As you said, debug info doesn't have the location over the call. May it be a clang issue? 

---
yibiao

**Comment by dwblaikie** [comment] 2022-05-31 04:31
> Thanks. In the stable version of clang/lldb, the behavior is different. Thus, I was wondering this might be a potential bug.
Could you run llvm-dwarfdump on the binary with the stable version of clang?
It /could/ be a bug, but might also be that the code got optimized further and there was no remaining copy of the location. (though this code seems simple enough that I'd be surprised if things got optimized significantly differently)
> As you said, debug info doesn't have the location over the call. May it be a clang issue?
Possibly - hard to tell as I don't happen to have the right compiler versions on-hand to reproduce/investigate.

**Comment by yangyibiao** [comment] 2022-05-31 04:53
Following the dwarfdump for the binary built with the stable version of clang.

$ clang-6.0 -Ofast -g small.c; llvm-dwarfdump a.out
```
a.out:  file format elf64-x86-64

.debug_info contents:
0x00000000: Compile Unit: length = 0x0000005a, format = DWARF32, version = 0x0004, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000005e)

0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("GNU C11 7.5.0 -mlong-double-80 -mtune=generic -march=x86-64 -g -g -g -O2 -O2 -O2 -fbuilding-libgcc -fno-stack-protector -fpic")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name        ("../../../src/libgcc/config/i386/crtfastmath.c")
              DW_AT_comp_dir    ("/build/gcc-7-EmPD0P/gcc-7-7.5.0/build/x86_64-linux-gnu/libgcc")
              DW_AT_ranges      (0x00000000
                 [0x0000000000400390, 0x00000000004003a3))
              DW_AT_low_pc      (0x0000000000000000)
              DW_AT_stmt_list   (0x00000000)

0x00000029:   DW_TAG_subprogram
                DW_AT_name      ("set_fast_math")
                DW_AT_decl_file ("/build/gcc-7-EmPD0P/gcc-7-7.5.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c")
                DW_AT_decl_line (83)
                DW_AT_prototyped        (true)
                DW_AT_low_pc    (0x0000000000400390)
                DW_AT_high_pc   (0x00000000004003a3)
                DW_AT_frame_base        (DW_OP_call_frame_cfa)
                DW_AT_GNU_all_call_sites        (true)
                DW_AT_sibling   (0x00000056)

0x00000046:     DW_TAG_variable
                  DW_AT_name    ("mxcsr")
                  DW_AT_decl_file       ("/build/gcc-7-EmPD0P/gcc-7-7.5.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c")
                  DW_AT_decl_line       (94)
                  DW_AT_type    (0x00000056 "unsigned int")
                  DW_AT_location        (0x00000000:
                     [0x0000000000400395, 0x000000000040039d): DW_OP_fbreg -12, DW_OP_deref_size 0x4, DW_OP_const2u 0x8040, DW_OP_or, DW_OP_stack_value
                     [0x000000000040039d, 0x00000000004003a3): DW_OP_fbreg -12)

0x00000055:     NULL

0x00000056:   DW_TAG_base_type
                DW_AT_byte_size (0x04)
                DW_AT_encoding  (DW_ATE_unsigned)
                DW_AT_name      ("unsigned int")

0x0000005d:   NULL
0x0000005e: Compile Unit: length = 0x0000009e, format = DWARF32, version = 0x0004, abbr_offset = 0x0046, addr_size = 0x08 (next unit at 0x00000100)

0x00000069: DW_TAG_compile_unit
              DW_AT_producer    ("clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name        ("small.c")
              DW_AT_stmt_list   (0x00000067)
              DW_AT_comp_dir    ("/root/DeVIL")
              DW_AT_GNU_pubnames        (true)
              DW_AT_low_pc      (0x00000000004004a0)
              DW_AT_high_pc     (0x00000000004004a3)

0x00000088:   DW_TAG_variable
                DW_AT_name      ("b")
                DW_AT_type      (0x0000009d "int")
                DW_AT_external  (true)
                DW_AT_decl_file ("/root/DeVIL/small.c")
                DW_AT_decl_line (4)
                DW_AT_location  (DW_OP_addr 0x601028)

0x0000009d:   DW_TAG_base_type
                DW_AT_name      ("int")
                DW_AT_encoding  (DW_ATE_signed)
                DW_AT_byte_size (0x04)

0x000000a4:   DW_TAG_pointer_type
                DW_AT_type      (0x000000a9 "char")

0x000000a9:   DW_TAG_base_type
                DW_AT_name      ("char")
                DW_AT_encoding  (DW_ATE_signed_char)
                DW_AT_byte_size (0x01)

0x000000b0:   DW_TAG_subprogram
                DW_AT_low_pc    (0x00000000004004a0)
                DW_AT_high_pc   (0x00000000004004a3)
                DW_AT_frame_base        (DW_OP_reg7 RSP)
                DW_AT_name      ("main")
                DW_AT_decl_file ("/root/DeVIL/small.c")
                DW_AT_decl_line (5)
                DW_AT_prototyped        (true)
                DW_AT_type      (0x0000009d "int")
                DW_AT_external  (true)

0x000000c9:     DW_TAG_formal_parameter
                  DW_AT_location        (DW_OP_reg5 RDI)
                  DW_AT_name    ("argc")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (5)
                  DW_AT_type    (0x0000009d "int")

0x000000d6:     DW_TAG_formal_parameter
                  DW_AT_location        (DW_OP_reg4 RSI)
                  DW_AT_name    ("argv")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (5)
                  DW_AT_type    (0x000000fa "char **")

0x000000e3:     DW_TAG_variable
                  DW_AT_name    ("x")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (6)
                  DW_AT_type    (0x000000a4 "char *")

0x000000ee:     DW_TAG_variable
                  DW_AT_name    ("res")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (8)
                  DW_AT_type    (0x0000009d "int")

0x000000f9:     NULL

0x000000fa:   DW_TAG_pointer_type
                DW_AT_type      (0x000000a4 "char *")

0x000000ff:   NULL
```

Following is the dwarfdump for the binary built with the trunk version of clang
$ clang -Ofast -g small.c; llvm-dwarfdump a.out
```
a.out:  file format elf64-x86-64

.debug_info contents:
0x00000000: Compile Unit: length = 0x0000005a, format = DWARF32, version = 0x0004, abbr_offset = 0x0000, addr_size = 0x08 (next unit at 0x0000005e)

0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("GNU C11 7.5.0 -mlong-double-80 -mtune=generic -march=x86-64 -g -g -g -O2 -O2 -O2 -fbuilding-libgcc -fno-stack-protector -fpic")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name        ("../../../src/libgcc/config/i386/crtfastmath.c")
              DW_AT_comp_dir    ("/build/gcc-7-EmPD0P/gcc-7-7.5.0/build/x86_64-linux-gnu/libgcc")
              DW_AT_ranges      (0x00000000
                 [0x0000000000000510, 0x0000000000000523))
              DW_AT_low_pc      (0x0000000000000000)
              DW_AT_stmt_list   (0x00000000)

0x00000029:   DW_TAG_subprogram
                DW_AT_name      ("set_fast_math")
                DW_AT_decl_file ("/build/gcc-7-EmPD0P/gcc-7-7.5.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c")
                DW_AT_decl_line (83)
                DW_AT_prototyped        (true)
                DW_AT_low_pc    (0x0000000000000510)
                DW_AT_high_pc   (0x0000000000000523)
                DW_AT_frame_base        (DW_OP_call_frame_cfa)
                DW_AT_GNU_all_call_sites        (true)
                DW_AT_sibling   (0x00000056)

0x00000046:     DW_TAG_variable
                  DW_AT_name    ("mxcsr")
                  DW_AT_decl_file       ("/build/gcc-7-EmPD0P/gcc-7-7.5.0/build/x86_64-linux-gnu/libgcc/../../../src/libgcc/config/i386/crtfastmath.c")
                  DW_AT_decl_line       (94)
                  DW_AT_type    (0x00000056 "unsigned int")
                  DW_AT_location        (0x00000000:
                     [0x0000000000000515, 0x000000000000051d): DW_OP_fbreg -12, DW_OP_deref_size 0x4, DW_OP_const2u 0x8040, DW_OP_or, DW_OP_stack_value
                     [0x000000000000051d, 0x0000000000000523): DW_OP_fbreg -12)

0x00000055:     NULL

0x00000056:   DW_TAG_base_type
                DW_AT_byte_size (0x04)
                DW_AT_encoding  (DW_ATE_unsigned)
                DW_AT_name      ("unsigned int")

0x0000005d:   NULL
0x0000005e: Compile Unit: length = 0x00000071, format = DWARF32, version = 0x0005, unit_type = DW_UT_compile, abbr_offset = 0x0046, addr_size = 0x08 (next unit at 0x000000d3)

0x0000006a: DW_TAG_compile_unit
              DW_AT_producer    ("Ubuntu clang version 15.0.0-++20220530091621+14cc4674bf5a-1~exp1~20220530091715.519")
              DW_AT_language    (DW_LANG_C99)
              DW_AT_name        ("small.c")
              DW_AT_str_offsets_base    (0x00000008)
              DW_AT_stmt_list   (0x00000067)
              DW_AT_comp_dir    ("/root/DeVIL")
              DW_AT_low_pc      (0x0000000000000640)
              DW_AT_high_pc     (0x0000000000000643)
              DW_AT_addr_base   (0x00000008)

0x00000081:   DW_TAG_variable
                DW_AT_name      ("b")
                DW_AT_type      (0x0000008c "int")
                DW_AT_external  (true)
                DW_AT_decl_file ("/root/DeVIL/small.c")
                DW_AT_decl_line (4)
                DW_AT_location  (DW_OP_addrx 0x0)

0x0000008c:   DW_TAG_base_type
                DW_AT_name      ("int")
                DW_AT_encoding  (DW_ATE_signed)
                DW_AT_byte_size (0x04)

0x00000090:   DW_TAG_pointer_type
                DW_AT_type      (0x00000095 "char")

0x00000095:   DW_TAG_base_type
                DW_AT_name      ("char")
                DW_AT_encoding  (DW_ATE_signed_char)
                DW_AT_byte_size (0x01)

0x00000099:   DW_TAG_subprogram
                DW_AT_low_pc    (0x0000000000000640)
                DW_AT_high_pc   (0x0000000000000643)
                DW_AT_frame_base        (DW_OP_reg7 RSP)
                DW_AT_call_all_calls    (true)
                DW_AT_name      ("main")
                DW_AT_decl_file ("/root/DeVIL/small.c")
                DW_AT_decl_line (5)
                DW_AT_prototyped        (true)
                DW_AT_type      (0x0000008c "int")
                DW_AT_external  (true)

0x000000a8:     DW_TAG_formal_parameter
                  DW_AT_location        (DW_OP_reg5 RDI)
                  DW_AT_name    ("argc")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (5)
                  DW_AT_type    (0x0000008c "int")

0x000000b2:     DW_TAG_formal_parameter
                  DW_AT_location        (DW_OP_reg4 RSI)
                  DW_AT_name    ("argv")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (5)
                  DW_AT_type    (0x000000cd "char **")

0x000000bc:     DW_TAG_variable
                  DW_AT_name    ("x")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (6)
                  DW_AT_type    (0x00000090 "char *")

0x000000c4:     DW_TAG_variable
                  DW_AT_name    ("res")
                  DW_AT_decl_file       ("/root/DeVIL/small.c")
                  DW_AT_decl_line       (8)
                  DW_AT_type    (0x0000008c "int")

0x000000cc:     NULL

0x000000cd:   DW_TAG_pointer_type
                DW_AT_type      (0x00000090 "char *")

0x000000d2:   NULL
```

**Comment by dwblaikie** [comment] 2022-05-31 16:44
Hmm - the old/"good" DWARF looks likely wrong to me - wouldn't RSI and RDI be clobbered by the function calls (malloc/free/memset), let alone for using the return register to store the resulting return value? 

Is the value of the argc/argv values correct when debugging the old/"good" dwarf? What's the assembly look like (how does it use RSI/RDI)?

**Comment by yangyibiao** [comment] 2022-06-01 01:00
$ clang-6.0 -Ofast -g small.c; lldb-6.0 a.out
```
(lldb) target create "a.out"
Current executable set to 'a.out' (x86_64).
(lldb) b 10
Breakpoint 1: where = a.out`main at small.c:10, address = 0x00000000004004a0
(lldb) r
Process 26128 launched: '/root/DeVIL/a.out' (x86_64)
Process 26128 stopped
* thread #1, name = 'a.out', stop reason = breakpoint 1.1
    frame #0: 0x00000000004004a0 a.out`main(argc=1, argv=0x00007fffffffe548) at small.c:10
   7   	  memset(x, 0, 10);
   8   	  int res = x[b];
   9   	  free(x);
-> 10  	  return 0;
   11  	}
(lldb) fr var
(int) argc = 1
(char **) argv = 0x00007fffffffe548
(char *) x = <no location, value may have been optimized out>

(int) res = <no location, value may have been optimized out>

(lldb) print *argv
(char *) $0 = 0x00007fffffffe789 "/root/DeVIL/a.out"
(lldb)
```

The value of `argc` equal to `1` and the value of `*argv` is also correct. 

The following is the assembly code of this old/"good" binary:

$ objdump -d a.out
```
a.out:     file format elf64-x86-64


Disassembly of section .init:

0000000000400370 <_init>:
  400370:	48 83 ec 08          	sub    $0x8,%rsp
  400374:	48 8b 05 7d 0c 20 00 	mov    0x200c7d(%rip),%rax        # 600ff8 <__gmon_start__>
  40037b:	48 85 c0             	test   %rax,%rax
  40037e:	74 02                	je     400382 <_init+0x12>
  400380:	ff d0                	call   *%rax
  400382:	48 83 c4 08          	add    $0x8,%rsp
  400386:	c3                   	ret

Disassembly of section .text:

0000000000400390 <set_fast_math>:
  400390:	0f ae 5c 24 fc       	stmxcsr -0x4(%rsp)
  400395:	81 4c 24 fc 40 80 00 	orl    $0x8040,-0x4(%rsp)
  40039c:	00
  40039d:	0f ae 54 24 fc       	ldmxcsr -0x4(%rsp)
  4003a2:	c3                   	ret
  4003a3:	66 2e 0f 1f 84 00 00 	cs nopw 0x0(%rax,%rax,1)
  4003aa:	00 00 00
  4003ad:	0f 1f 00             	nopl   (%rax)

00000000004003b0 <_start>:
  4003b0:	31 ed                	xor    %ebp,%ebp
  4003b2:	49 89 d1             	mov    %rdx,%r9
  4003b5:	5e                   	pop    %rsi
  4003b6:	48 89 e2             	mov    %rsp,%rdx
  4003b9:	48 83 e4 f0          	and    $0xfffffffffffffff0,%rsp
  4003bd:	50                   	push   %rax
  4003be:	54                   	push   %rsp
  4003bf:	49 c7 c0 20 05 40 00 	mov    $0x400520,%r8
  4003c6:	48 c7 c1 b0 04 40 00 	mov    $0x4004b0,%rcx
  4003cd:	48 c7 c7 a0 04 40 00 	mov    $0x4004a0,%rdi
  4003d4:	ff 15 16 0c 20 00    	call   *0x200c16(%rip)        # 600ff0 <__libc_start_main@GLIBC_2.2.5>
  4003da:	f4                   	hlt
  4003db:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

00000000004003e0 <_dl_relocate_static_pie>:
  4003e0:	f3 c3                	repz ret
  4003e2:	66 2e 0f 1f 84 00 00 	cs nopw 0x0(%rax,%rax,1)
  4003e9:	00 00 00
  4003ec:	0f 1f 40 00          	nopl   0x0(%rax)

00000000004003f0 <deregister_tm_clones>:
  4003f0:	55                   	push   %rbp
  4003f1:	b8 30 10 60 00       	mov    $0x601030,%eax
  4003f6:	48 3d 30 10 60 00    	cmp    $0x601030,%rax
  4003fc:	48 89 e5             	mov    %rsp,%rbp
  4003ff:	74 17                	je     400418 <deregister_tm_clones+0x28>
  400401:	b8 00 00 00 00       	mov    $0x0,%eax
  400406:	48 85 c0             	test   %rax,%rax
  400409:	74 0d                	je     400418 <deregister_tm_clones+0x28>
  40040b:	5d                   	pop    %rbp
  40040c:	bf 30 10 60 00       	mov    $0x601030,%edi
  400411:	ff e0                	jmp    *%rax
  400413:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)
  400418:	5d                   	pop    %rbp
  400419:	c3                   	ret
  40041a:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)

0000000000400420 <register_tm_clones>:
  400420:	be 30 10 60 00       	mov    $0x601030,%esi
  400425:	55                   	push   %rbp
  400426:	48 81 ee 30 10 60 00 	sub    $0x601030,%rsi
  40042d:	48 89 e5             	mov    %rsp,%rbp
  400430:	48 c1 fe 03          	sar    $0x3,%rsi
  400434:	48 89 f0             	mov    %rsi,%rax
  400437:	48 c1 e8 3f          	shr    $0x3f,%rax
  40043b:	48 01 c6             	add    %rax,%rsi
  40043e:	48 d1 fe             	sar    %rsi
  400441:	74 15                	je     400458 <register_tm_clones+0x38>
  400443:	b8 00 00 00 00       	mov    $0x0,%eax
  400448:	48 85 c0             	test   %rax,%rax
  40044b:	74 0b                	je     400458 <register_tm_clones+0x38>
  40044d:	5d                   	pop    %rbp
  40044e:	bf 30 10 60 00       	mov    $0x601030,%edi
  400453:	ff e0                	jmp    *%rax
  400455:	0f 1f 00             	nopl   (%rax)
  400458:	5d                   	pop    %rbp
  400459:	c3                   	ret
  40045a:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)

0000000000400460 <__do_global_dtors_aux>:
  400460:	80 3d c5 0b 20 00 00 	cmpb   $0x0,0x200bc5(%rip)        # 60102c <completed.7698>
  400467:	75 17                	jne    400480 <__do_global_dtors_aux+0x20>
  400469:	55                   	push   %rbp
  40046a:	48 89 e5             	mov    %rsp,%rbp
  40046d:	e8 7e ff ff ff       	call   4003f0 <deregister_tm_clones>
  400472:	c6 05 b3 0b 20 00 01 	movb   $0x1,0x200bb3(%rip)        # 60102c <completed.7698>
  400479:	5d                   	pop    %rbp
  40047a:	c3                   	ret
  40047b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)
  400480:	f3 c3                	repz ret
  400482:	0f 1f 40 00          	nopl   0x0(%rax)
  400486:	66 2e 0f 1f 84 00 00 	cs nopw 0x0(%rax,%rax,1)
  40048d:	00 00 00

0000000000400490 <frame_dummy>:
  400490:	55                   	push   %rbp
  400491:	48 89 e5             	mov    %rsp,%rbp
  400494:	5d                   	pop    %rbp
  400495:	eb 89                	jmp    400420 <register_tm_clones>
  400497:	66 0f 1f 84 00 00 00 	nopw   0x0(%rax,%rax,1)
  40049e:	00 00

00000000004004a0 <main>:
  4004a0:	31 c0                	xor    %eax,%eax
  4004a2:	c3                   	ret
  4004a3:	66 2e 0f 1f 84 00 00 	cs nopw 0x0(%rax,%rax,1)
  4004aa:	00 00 00
  4004ad:	0f 1f 00             	nopl   (%rax)

00000000004004b0 <__libc_csu_init>:
  4004b0:	41 57                	push   %r15
  4004b2:	41 56                	push   %r14
  4004b4:	49 89 d7             	mov    %rdx,%r15
  4004b7:	41 55                	push   %r13
  4004b9:	41 54                	push   %r12
  4004bb:	4c 8d 25 86 09 20 00 	lea    0x200986(%rip),%r12        # 600e48 <__frame_dummy_init_array_entry>
  4004c2:	55                   	push   %rbp
  4004c3:	48 8d 2d 8e 09 20 00 	lea    0x20098e(%rip),%rbp        # 600e58 <__do_global_dtors_aux_fini_array_entry>
  4004ca:	53                   	push   %rbx
  4004cb:	41 89 fd             	mov    %edi,%r13d
  4004ce:	49 89 f6             	mov    %rsi,%r14
  4004d1:	4c 29 e5             	sub    %r12,%rbp
  4004d4:	48 83 ec 08          	sub    $0x8,%rsp
  4004d8:	48 c1 fd 03          	sar    $0x3,%rbp
  4004dc:	e8 8f fe ff ff       	call   400370 <_init>
  4004e1:	48 85 ed             	test   %rbp,%rbp
  4004e4:	74 20                	je     400506 <__libc_csu_init+0x56>
  4004e6:	31 db                	xor    %ebx,%ebx
  4004e8:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
  4004ef:	00
  4004f0:	4c 89 fa             	mov    %r15,%rdx
  4004f3:	4c 89 f6             	mov    %r14,%rsi
  4004f6:	44 89 ef             	mov    %r13d,%edi
  4004f9:	41 ff 14 dc          	call   *(%r12,%rbx,8)
  4004fd:	48 83 c3 01          	add    $0x1,%rbx
  400501:	48 39 dd             	cmp    %rbx,%rbp
  400504:	75 ea                	jne    4004f0 <__libc_csu_init+0x40>
  400506:	48 83 c4 08          	add    $0x8,%rsp
  40050a:	5b                   	pop    %rbx
  40050b:	5d                   	pop    %rbp
  40050c:	41 5c                	pop    %r12
  40050e:	41 5d                	pop    %r13
  400510:	41 5e                	pop    %r14
  400512:	41 5f                	pop    %r15
  400514:	c3                   	ret
  400515:	90                   	nop
  400516:	66 2e 0f 1f 84 00 00 	cs nopw 0x0(%rax,%rax,1)
  40051d:	00 00 00

0000000000400520 <__libc_csu_fini>:
  400520:	f3 c3                	repz ret

Disassembly of section .fini:

0000000000400524 <_fini>:
  400524:	48 83 ec 08          	sub    $0x8,%rsp
  400528:	48 83 c4 08          	add    $0x8,%rsp
  40052c:	c3                   	ret
```

**Comment by dwblaikie** [comment] 2022-06-04 00:57
Ah, @jmorse looks like this might be an instrref issue?
The code is optimized away entirely in both cases - so argc/argv don't actually get clobbered - but maybe they did/were being clobbered party-way through optimizations? Not sure if this is especially recoverable, but would be nice if we could.

**Comment by jmorse** [comment] 2022-06-08 13:40
Important point for reproduction, I think in the first post you meant to have `return res;` rather than `return 0;`? I can't reproduce without `return res;`. The DWARF for the subprogram in that case:

```
0x0000003f:   DW_TAG_subprogram                                                                                                                                                                                                                                                 
                DW_AT_low_pc    (0x0000000000000000)                                                                                                                                                                                                                            
                DW_AT_high_pc   (0x0000000000000027)                                                                                                                                                                                                                            
                DW_AT_frame_base        (DW_OP_reg7 RSP)                                                                                                                                                                                                                        
                DW_AT_call_all_calls    (true)                                                                                                                                                                                                                                  
                DW_AT_name      ("main")                                                                                                                                                                                                                                        
                DW_AT_decl_file ("/tmp/bees.c")                                                                                                                                                                                                                                 
                DW_AT_decl_line (5)                                                                                                                                                                                                                                             
                DW_AT_prototyped        (true)                                                                                                                                                                                                                                  
                DW_AT_type      (0x00000032 "int")                                                                                                                                                                                                                              
                DW_AT_external  (true)                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                
0x0000004e:     DW_TAG_formal_parameter                                                                                                                                                                                                                                         
                  DW_AT_location        (indexed (0x0) loclist = 0x0000001c:                                                                                                                                                                                                    
                     [0x0000000000000000, 0x0000000000000006): DW_OP_reg5 RDI                                                                                                                                                                                                   
                     [0x0000000000000006, 0x0000000000000027): DW_OP_entry_value(DW_OP_reg5 RDI), DW_OP_stack_value)                                                                                                                                                            
                  DW_AT_name    ("argc")                                                                                                                                                                                                                                        
                  DW_AT_decl_file       ("/tmp/bees.c")                                                                                                                                                                                                                         
                  DW_AT_decl_line       (5)                                                                                                                                                                                                                                     
                  DW_AT_type    (0x00000032 "int")                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                
0x00000057:     DW_TAG_formal_parameter
                  DW_AT_location        (indexed (0x1) loclist = 0x0000002a:
                     [0x0000000000000000, 0x000000000000000b): DW_OP_reg4 RSI
                     [0x000000000000000b, 0x0000000000000027): DW_OP_entry_value(DW_OP_reg4 RSI), DW_OP_stack_value)
                  DW_AT_name    ("argv")
                  DW_AT_decl_file       ("/tmp/bees.c")
                  DW_AT_decl_line       (5)
                  DW_AT_type    (0x00000073 "char**")

0x00000060:     DW_TAG_variable
                  DW_AT_location        (indexed (0x2) loclist = 0x00000038:
                     [0x0000000000000010, 0x0000000000000023): DW_OP_reg0 RAX)
                  DW_AT_name    ("x")
                  DW_AT_decl_file       ("/tmp/bees.c")
                  DW_AT_decl_line       (6)
                  DW_AT_type    (0x00000036 "char*")

0x00000069:     DW_TAG_variable
                  DW_AT_location        (indexed (0x3) loclist = 0x0000003e:
                     [0x000000000000001b, 0x0000000000000026): DW_OP_reg3 RBX
                     [0x0000000000000026, 0x0000000000000027): DW_OP_reg0 RAX)
                  DW_AT_name    ("res")
                  DW_AT_decl_file       ("/tmp/bees.c")
                  DW_AT_decl_line       (8)
                  DW_AT_type    (0x00000032 "int")

0x00000072:     NULL
```
And assembly:
```
0000000000000000 <main>:
   0:   53                      push   %rbx
   1:   bf 01 00 00 00          mov    $0x1,%edi
   6:   be 0a 00 00 00          mov    $0xa,%esi
   b:   e8 00 00 00 00          callq  10 <main+0x10>
                        c: R_X86_64_PLT32       calloc-0x4
  10:   48 63 0d 00 00 00 00    movslq 0x0(%rip),%rcx        # 17 <main+0x17>
                        13: R_X86_64_PC32       b-0x4
  17:   0f be 1c 08             movsbl (%rax,%rcx,1),%ebx
  1b:   48 89 c7                mov    %rax,%rdi
  1e:   e8 00 00 00 00          callq  23 <main+0x23>
                        13: R_X86_64_PC32       b-0x4
  23:   89 d8                   mov    %ebx,%eax
  25:   5b                      pop    %rbx
  26:   c3                      retq   
```

With that in mind: the location lists look correct to me, argc and argv are in the argument registers until they're clobbered when calling calloc. For the rest of the function they're described as being available as an entry value in the relevant registers, which is AFAIUI correct.

I would imagine that the reason why lldb can't evaluate DW_OP_entry_value is because there isn't any DWARF call-site-information at the call site that would explain where the arguments can be found -- it would have to come from somewhere in the platforms crt0.o / startup object files.

IMHO this is all expected, although unfortunate.

**Comment by yangyibiao** [comment] 2022-06-08 13:53
@jmorse I am sorry. I post the wrong code. The reported problem only occurs when it comes to `return res;`. When the code changed to `return 0;`, lldb behaves corretly.

**Comment by yangyibiao** [comment] 2022-06-09 01:18
@dwblaikie I really apologize to let you know that I used the wrong code to post those dwarfdump info and the assembly code in above posts. Have update those information with the issue triggering code. Thanks for @jmorse pointing out this problem.

**Comment by dwblaikie** [comment] 2022-06-09 06:04
it's all good - I figured out and had reproduced your original failure - I forgot to call it out when referring this to @jmorse / or pointing it out to be corrected. But I did understand/had looked at the behavior you'd described and did observe the issue - hopefully @jmorse has more ideas on how to address it now that the explanation has been clarified.

**Comment by jmorse** [comment] 2022-06-20 15:09
Circling back to this -- my current understanding of the issue is that the output of the compiler is correct (location lists in main describe the entry value of $rdi and $rsi), however the next stack frame is below `main` and doesn't have any debug-info, meaning lldb can't find any call-site information.

From this comment ( https://github.com/llvm/llvm-project/issues/55760#issuecomment-1142933164 ) , am I right in thinking that you're expecting "<variable not available>" to be the "correct" output from displaying the variables, but with recent compilers the output is the "<Could not evaluate DW_OP_entry_value.>" error message?

In that sense, it's a change in the compiler that's causing this to happen, because between LLVM 6.0 and now, we've started to emit entry values to describe variable locations. However, I believe the "could not evaluate..." output is the expected behaviour of lldb when asked to print a variable where the location is an unavailable entry value.

CC @JDevlieghere to confirm the displayed error is correct.

**Comment by dwblaikie** [comment] 2022-06-22 07:51
Yeah, with the updated/edits to the previous comments that sounds right to me - looks like (@yangyibiao could you confirm this?) the behavior's equivalent, but we went from "<variable not available>" to "<Could not evaluate DW_OP_entry_value.>". - yeah, maybe the latter could be more precise about why it couldn't be evaluated, but it's equivalent functionality (& in other cases the runtime could potentially be improved to include DWARF for the caller-of-main, or this DWARF, if produced in some other place where the caller has info, it helps, etc)

**Comment by yangyibiao** [comment] 2022-06-22 16:17
@dwblaikie After reading @jmorse 's detail explanation. I agree that thest two bbehavior are equivalent and the latest one would be more precise.

**Comment by OCHyams** [comment] 2023-08-15 08:23
Closing this as it looks like it works as intended.

**Closed by OCHyams** 2023-08-15 08:23 UTC
Labels: lldb
