### ISSUE TITLE
[clang] class template argument deduction from braced initializer in non-type template parameter doesn't work

### ISSUE THREAD

**Issue by ericniebler** [llvm/llvm-project#63479] opened 2023-06-23 18:55 UTC
```c++
template <unsigned long N>
struct Array {
  int value[N];
};

template <unsigned long N>
Array(const int (&)[N]) -> Array<N>;

template <Array A>
struct S {
};

int main() {
  S<{{1,2,3,4}}> t;
  (void) t;
}
```

Result:
```
<source>:14:5: error: expected expression
   14 |   S<{{1,2,3,4}}> t;
      |     ^
```

Expected:
success

GCC and MSVC accept this code: https://godbolt.org/z/se6cd9eEx

**Comment by shafik** [comment] 2023-06-23 21:51
This is a duplicate of: https://github.com/llvm/llvm-project/issues/58434

**Closed by shafik** 2023-06-23 21:51 UTC
Labels: clang:frontend
