### ISSUE TITLE
Clang crashes on incorrect code with -std=c++17

### ISSUE THREAD

**Issue by Fznamznon** [llvm/llvm-project#57341] opened 2022-08-24 14:11 UTC
Reproducer:
```cpp
// test.cpp content
namespace a {
template <b> class c {
  d() {
    a::c.
```

Command to compile:
```shell
clang -cc1 -std=c++17 test.cpp
```
Without assertions it seems to be crashing due to an infinite recursion in `clang::Parser::isCXXDeclarationSpecifier`. With assertions I see the following Stack dump:
```console
clang: ../llvm/clang/lib/Parse/ParseTentative.cpp:1569: clang::Parser::TPResult clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*): Assertion `Tok.isNot(tok::annot_cxxscope) || NextToken().isNot(tok::identifier)' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: ../llvm/debug/bin/clang -cc1 -std=c++17 small.cpp
1.      small.cpp:4:5: at annotation token
2.      small.cpp:1:1: parsing namespace 'a'
3.      small.cpp:2:14: parsing struct/union/class body 'a::c'
4.      small.cpp:3:7: parsing function body 'a::c::d'
5.      small.cpp:3:7: in compound statement ('{}')
 #0 0x00000000042d0413 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) ../llvm/llvm/lib/Support/Unix/Signals.inc:569:22
 #1 0x00000000042d04ca PrintStackTraceSignalHandler(void*) ../llvm/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x00000000042ce46a llvm::sys::RunSignalHandlers() ../llvm/llvm/lib/Support/Signals.cpp:103:20
 #3 0x00000000042cfe47 SignalHandler(int) ../llvm/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f3f35c7db20 __restore_rt sigaction.c:0:0
 #5 0x00007f3f3475e37f raise (/lib64/libc.so.6+0x3737f)
 #6 0x00007f3f34748db5 abort (/lib64/libc.so.6+0x21db5)
 #7 0x00007f3f34748c89 _nl_load_domain.cold.0 loadmsgcat.c:0:0
 #8 0x00007f3f34756a76 .annobin___GI___assert_fail.end assert.c:0:0
 #9 0x0000000007a674a8 clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) ../llvm/clang/lib/Parse/ParseTentative.cpp:1570:
43
#10 0x0000000007a66c4a clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) ../llvm/clang/lib/Parse/ParseTentative.cpp:1322:
37
#11 0x0000000007a64c22 clang::Parser::isCXXSimpleDeclaration(bool) ../llvm/clang/lib/Parse/ParseTentative.cpp:114:43
#12 0x0000000007a64bf5 clang::Parser::isCXXDeclarationStatement() ../llvm/clang/lib/Parse/ParseTentative.cpp:64:62
#13 0x0000000007a574f6 clang::Parser::isDeclarationStatement() ../llvm/clang/include/clang/Parse/Parser.h:2418:40
#14 0x0000000007a4c9d1 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocat
ion*, clang::ParsedAttributes&, clang::ParsedAttributes&) ../llvm/clang/lib/Parse/ParseStmt.cpp:236:78
#15 0x0000000007a4c24d clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /iusers/m
podchis/source/syclos/llvm/clang/lib/Parse/ParseStmt.cpp:115:60
#16 0x0000000007a5051a clang::Parser::ParseCompoundStatementBody(bool) ../llvm/clang/lib/Parse/ParseStmt.cpp:1157:56
#17 0x0000000007a553dd clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) ../llvm/clang/lib/Parse/ParseStmt.cpp
:2428:48
#18 0x000000000797e624 clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) ../llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp:598:19
#19 0x000000000797d191 clang::Parser::LexedMethod::ParseLexedMethodDefs() ../llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp:275:1
#20 0x000000000797e0bf clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) ../llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp:527:3
#21 0x00000000079baedf clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributes&, unsigned int, clang::Decl*) /iuser
s/mpodchis/source/syclos/llvm/clang/lib/Parse/ParseDeclCXX.cpp:3541:21
#22 0x00000000079b4e68 clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::A
ccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) ../llvm/clang/lib/Parse/ParseDeclCXX.cpp:2018:34
#23 0x0000000007994ccc clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpec
Context, clang::Parser::LateParsedAttrList*) ../llvm/clang/lib/Parse/ParseDecl.cpp:4145:26
#24 0x0000000007a5d4ce clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&,
 clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) ../llvm/clang/lib/Parse/ParseTemplate.cpp:229:13
#25 0x0000000007a5d0a9 clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpec
ifier) ../llvm/clang/lib/Parse/ParseTemplate.cpp:170:45
#26 0x0000000007a5cbe3 clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) ../llvm/clang/lib/Parse/ParseTemplate.cpp:47:50
#27 0x000000000798bd7a clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLo
cation*) ../llvm/clang/lib/Parse/ParseDecl.cpp:1778:45
#28 0x000000000796c61b clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) ../llvm/clang/lib/Parse/Parser
.cpp:947:49
#29 0x00000000079ae1ae clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::Pars
edAttributes&, clang::BalancedDelimiterTracker&) ../llvm/clang/lib/Parse/ParseDeclCXX.cpp:256:41
#30 0x00000000079adfbd clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) ../llvm/clang/lib/
Parse/ParseDeclCXX.cpp:239:22
#31 0x000000000798bf46 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLo
cation*) ../llvm/clang/lib/Parse/ParseDecl.cpp:1793:43
#32 0x000000000796c61b clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) ../llvm/clang/lib/Parse/Parser
.cpp:947:49
#33 0x000000000796ba6b clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) ../llvm/clang/l
ib/Parse/Parser.cpp:737:42
#34 0x000000000796b1f9 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) ../llvm/cl
ang/lib/Parse/Parser.cpp:591:43
#35 0x00000000079669d3 clang::ParseAST(clang::Sema&, bool, bool) ../llvm/clang/lib/Parse/ParseAST.cpp:161:47
#36 0x00000000052a6c73 clang::ASTFrontendAction::ExecuteAction() ../llvm/clang/lib/Frontend/FrontendAction.cpp:1144:11
#37 0x00000000052a659f clang::FrontendAction::Execute() ../llvm/clang/lib/Frontend/FrontendAction.cpp:1041:38
#38 0x00000000051e3538 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ../llvm/clang/lib/Frontend/CompilerInstance.cpp:1038:42
#39 0x000000000543b624 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) ../llvm/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:2
66:38
#40 0x000000000279352d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) ../llvm/clang/tools/driver/cc1_main.cpp:250:40
#41 0x0000000002786b2f ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) ../llvm/clang/tools/driver/driver.cpp:317:20
#42 0x00000000027871af clang_main(int, char**) ../llvm/clang/tools/driver/driver.cpp:388:26
#43 0x00000000027aef7c main ../llvm/debug/tools/clang/tools/driver/clang-driver.cpp:11:63
#44 0x00007f3f3474a493 __libc_start_main (/lib64/libc.so.6+0x23493)
#45 0x000000000278549e _start (../llvm/debug/bin/clang+0x278549e)
Aborted (core dumped)
```

Godbolt link for convenience: https://godbolt.org/z/x3e1TGzx9

I was using clang built from sources.

**Comment by PatriotRossii** [comment] 2022-09-04 09:24
Same as #57495

**Comment by shafik** [comment] 2023-06-05 16:51
Duplicate of: https://github.com/llvm/llvm-project/issues/57495

**Closed** 2023-06-05 16:57 UTC
Labels: duplicate, c++17, clang:frontend, crash-on-invalid
