### ISSUE TITLE
clang-tidy crash when using std::bit_cast with C++20

### ISSUE THREAD

**Issue by diegohavenstein** [llvm/llvm-project#60657] opened 2023-02-10 09:35 UTC
We've noticed that the clang-tidy tool (version 15.0.7) on Linux, we run into a crash. In our code, we have a member function using a `std::bit_cast` to interpret bits of a pointer as `uint64_t`. Using a `reinterpret_cast` is our current workaround, since that does not crash clang-tidy

The callstack looks as follows

```
(anonymous namespace)::SimpleSValBuilder::evalBinOpLN(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::Loc, clang::ento::NonLoc, clang::QualType) (.llvm.15951751361112993616) (@(anonymous namespace)::SimpleSValBuilder::evalBinOpLN(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::Loc, clang::ento::NonLoc, clang::QualType) (.llvm.15951751361112993616):397)
clang::ento::SValBuilder::evalBinOp(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::SVal, clang::ento::SVal, clang::QualType) (@clang::ento::SValBuilder::evalBinOp(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::SVal, clang::ento::SVal, clang::QualType):130)
clang::ento::ExprEngine::VisitBinaryOperator(clang::BinaryOperator const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (@clang::ento::ExprEngine::VisitBinaryOperator(clang::BinaryOperator const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&):1572)
clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) (@clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&):1588)
clang::ento::ExprEngine::ProcessStmt(clang::Stmt const*, clang::ento::ExplodedNode*) (@clang::ento::ExprEngine::ProcessStmt(clang::Stmt const*, clang::ento::ExplodedNode*):144)
clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) (@clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*):49)
clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&) (@clang::ento::CoreEngine::dispatchWorkItem(clang::ento::ExplodedNode*, clang::ProgramPoint, clang::ento::WorkListUnit const&):123)
clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) (@clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>):305)
(anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*, void>>*) (@(anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*, void>>*):528)
(anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) (@(anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&):402)
clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (@clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&):16)
clang::ParseAST(clang::Sema&, bool, bool) (@clang::ParseAST(clang::Sema&, bool, bool):236)
clang::FrontendAction::Execute() (@clang::FrontendAction::Execute():32)
clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (@clang::CompilerInstance::ExecuteAction(clang::FrontendAction&):202)
clang::tooling::FrontendActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (@clang::tooling::FrontendActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*):109)
clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef)::ActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (@clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef)::ActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*):29)
clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::__1::shared_ptr<clang::CompilerInvocation>, std::__1::shared_ptr<clang::PCHContainerOperations>) (@clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::__1::shared_ptr<clang::CompilerInvocation>, std::__1::shared_ptr<clang::PCHContainerOperations>):88)
clang::tooling::ToolInvocation::run() (@clang::tooling::ToolInvocation::run():274)
clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (@clang::tooling::ClangTool::run(clang::tooling::ToolAction*):783)
clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef) (@clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef):287)
clang::tidy::clangTidyMain(int, char const**) (@clang::tidy::clangTidyMain(int, char const**):2690)
__libc_start_main (@__libc_start_main:61)
_start (@_start:14)
```

A min repro looks as follows:
Save this file to `repro.cpp`
```cpp
#include <bit>
#include <cstdint>
struct Repro {
	enum Tag {};
	void* ptr;
	Tag getTag() { return Tag(std::bit_cast<uint64_t>(ptr) >> 61); }
};
```

Content of `.clang-tidy` is e.g.
```yml
Checks: "performance-for-range-copy"
```

Then run:
```shell
clang-tidy --config-file=.clang-tidy --extra-arg=--std=c++20 repro.cpp
```

crashes with the following output

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./clang-tidy --config-file=.clang-tidy --extra-arg=--std=c++20 repro.cpp
1.      <eof> parser at end of file
2.      While analyzing stack: 
        #0 Calling Repro::getTag()
3.      repro.cpp:6:28: Error evaluating statement
4.      repro.cpp:6:28: Error evaluating statement
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
Segmentation fault
```

**Comment by steakhal** [comment] 2023-02-13 07:59
I could not reproduce on `main`. I think I likely fixed this sort of crash by aa12a48c8223aafafa45fb1e6e9ea49dc18a62d2.
Please reopen the issue if the crash is still present on llvm `main`.
The "fix" commit will be part of clang-tidy-16 in the upcoming months.

**Closed by steakhal** 2023-02-13 07:59 UTC
Labels: clang:static analyzer, crash
