### ISSUE TITLE
[Flang] FRACTION of +/- Inf, REAL and DOUBLE PRECISION, returns NaN instead of +/- Inf

### ISSUE THREAD

**Issue by chandankds** [llvm/llvm-project#76326] opened 2023-12-24 09:24 UTC
The intrinsic FRACTION should return Inf, not NaN, for Inf argument.

The Intel compiler returns Inf, GNU returns NaN.

```
Program test_fraction_inf
  Real :: x
  Real(Kind(1.d0)) :: y
  x = Huge(x) ;  y = Huge(y)
  Call s(x,y)
Contains
  Subroutine s(x,y)
    Real :: x
    Real(Kind(1.d0)) :: y
    x = x + x; y = y + y
    Print *, x,y  ! expected Inf
    Print *, Fraction(x), Fraction(y) ! expected Inf
    x = -x ; y = -y
    Print *, Fraction(x), Fraction(y) ! expected Inf
  End Subroutine s
End Program Test_fraction_inf
```

**Comment by kargl** [comment] 2023-12-25 03:51
It might be prudent to check the Fortran standard.  _16.9.90 FRACTION (X) ... If X is an IEEE infinity, the result is an IEEE NaN._

**Comment by klausler** [comment] 2023-12-25 20:52
Working as intended; closing bug.

**Closed by klausler** 2023-12-25 20:52 UTC
Labels: invalid, flang
