### ISSUE TITLE
Use of ambiguous member alias not rejected if they are equivalent

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#52613] opened 2021-12-11 13:46 UTC
See https://godbolt.org/z/qW1Mo4bTf.

**Comment by shafik** [comment] 2023-08-17 20:38
Please include the code (if it is of reasonable size), it allows reviewers to quickly get an idea of the bug w/o following any additional links.

code:

```cpp
template<auto V> struct C {
  using type = decltype(V);
};
struct X : C<0>, C<1> {
};
template<class T> concept able =
  requires {
    typename X::type;
  };
static_assert(able<X>);
```

**Comment by shafik** [comment] 2023-08-17 20:39
Duplicate of: https://github.com/llvm/llvm-project/issues/55692

**Closed by shafik** 2023-08-17 20:39 UTC
Labels: clang:frontend, concepts
