### ISSUE TITLE
[libc++] libc++ on apple does not re-export new/delete and exception symbols from the system libc++abi

### ISSUE THREAD

**Issue by a-n-n-a-l-e-e** [llvm/llvm-project#78860] opened 2024-01-20 21:07 UTC
libc++ on apple will re-export many of the symbols in libc++abi but re-exporting new/delete and exceptions was removed in 2020 with the change [[libc++] Simplify how we re-export symbols from libc++abi](https://github.com/llvm/llvm-project/commit/4f13b999297140486b2faa1b5d8d7c768fb40dfb#diff-20b3eeb706b19c7998c7dd44ac45c72752750df57dd43da9e46f2ff0782bbd75).

from the commit message I am not clear how one would continue to re-export the new/delete symbols in libc++ now that the duplicate code is eliminated.

Is it possible to re-add the re-export logic back into libc++ so that it re-exports all needed symbols from libc++abi ?

thanks! 

https://github.com/NixOS/nixpkgs/issues/166205

**Comment by a-n-n-a-l-e-e** [comment] 2024-01-21 16:05
I think this might only be an issue when trying to build libcxx and libcxxabi separately.

**Comment by ldionne** [comment] 2024-01-22 15:02
How are you building libc++ and libc++abi? We definitely still support re-exporting libc++abi symbols from libc++, that is how we build and ship the library on Apple platforms. Are you using the standalone build (which isn't supported anymore)?

**Comment by a-n-n-a-l-e-e** [comment] 2024-01-22 15:29
nixpkgs is currently building the components separately. on darwin, libcxx is built by:

copy libcxx source out of the monorepo into an empty directory $out
```bash
mkdir -p "$out"
cp -r ${monorepoSrc}/cmake "$out"
cp -r ${monorepoSrc}/libcxx "$out"
mkdir -p "$out/libcxxabi"
cp -r ${monorepoSrc}/libcxxabi/include "$out/libcxxabi"
mkdir -p "$out/llvm"
cp -r ${monorepoSrc}/llvm/cmake "$out/llvm"
cp -r ${monorepoSrc}/llvm/utils "$out/llvm"
cp -r ${monorepoSrc}/third-party "$out"
cp -r ${monorepoSrc}/runtimes "$out"
cd $out/runtimes
```

then invoke cmake with the following flags
```
-DLLVM_ENABLE_RUNTIMES=libcxx
-DLIBCXX_CXX_ABI=system-libcxxabi
-DLIBCXX_CXX_ABI_INCLUDE_PATHS=${cxxabi.dev}/include/c++/v1
```

I got the re-exporting working for us by [patching](https://github.com/NixOS/nixpkgs/pull/282624/files#diff-02031fd950d961b8ca1024076a0d1e1e5b82ffb942515ff216a3fdd7794d99f5) the libcxxabi and libcxx CMakefiles.txt to copy and consume the symbol files. I was going to submit it as a PR but if this is unsupported then I will not.

thanks!

**Comment by ldionne** [comment] 2024-01-22 16:47
I just looked into this some more, and the problem is that I think it doesn't make sense to re-export libc++abi symbols when we are using the `system-libcxxabi` ABI choice. In other words, I think https://github.com/llvm/llvm-project/pull/77218 didn't make sense after re-considering this, but I didn't catch that initially. Indeed, in general it's not possible to know exactly what symbols should be re-exported from the library since we don't know the exact version of the system libc++abi. There could also be ABI extensions and stuff that we just can't know.

Is there a reason why you're trying to build libc++ and libc++abi separately? Why don't you use this invocation instead?

```bash
-DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi"
```

**Comment by a-n-n-a-l-e-e** [comment] 2024-01-22 19:04
I appreciate you looking into this, thank you. building these together makes sense to me if only to reduce the maintenance burden. however, i am trying to track down why we are building these components separately and connecting with the right people might take a few days.

**Comment by ldionne** [comment] 2024-01-22 19:58
No worries. I'll close this as NTBF for the time being, please update this once you have more context and I'll be happy to help. I just want to keep the issues list tidy if we think this is unlikely to lead to changes on the libc++ side.

I'll also mention https://github.com/llvm/llvm-project/issues/79008 which I stumbled upon when looking into this issue. They're different but related.

**Closed by ldionne** 2024-01-22 19:58 UTC
Labels: libc++, libc++abi

**Comment by trcrsired** [comment] 2025-02-13 20:20
does system-libcxxabi support C++ exceptions?

**Comment by ldionne** [comment] 2025-02-13 20:43
I don't understand your question, please be (more) specific.
