### ISSUE TITLE
Emitted binary changes when -g is enabled at -O1

### ISSUE THREAD

**Issue by theo-lw** [llvm/llvm-project#57962] opened 2022-09-25 04:50 UTC
See `attributes_transformed_program0_preprocessed.c` below:

```console
$ cat attributes_transformed_program0_preprocessed.c
char a[];
int b;
__attribute__((zero_call_used_regs("used"))) char c(int d) {
  *a = ({
    int e = d;
    b;
  });
}
void main() {}
$ clang-trunk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project.git afb0b21f24adecfa0b302c79366980453b15ba7b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
$ clang-trunk -w -O1 attributes_transformed_program0_preprocessed.c -o a.out ; objdump --disassemble --section=.text a.out > no_dbg.txt
$ clang-trunk -w -O1 attributes_transformed_program0_preprocessed.c -o a.out -g ; objdump --disassemble --section=.text a.out > dbg.txt
$ diff no_dbg.txt dbg.txt
81,82c81,82
<     113d:	c3                   	retq
<     113e:	66 90                	xchg   %ax,%ax
---
>     113d:	31 ff                	xor    %edi,%edi
>     113f:	c3                   	retq
```

**Comment by xgupta** [comment] 2022-11-20 05:06
https://godbolt.org/z/ndz36Kn3P says prologepilog pass insert an xor instruction in -g case.

**Comment by xgupta** [comment] 2022-11-20 15:00
emitting xor or zero out the calle used register started from https://reviews.llvm.org/D110869. Seems gcc is not running this [ -fzero-call-used-regs ] pass at higher optimization level [ https://godbolt.org/z/j1qTr7r3Y] so shall we disable it ?

**Comment by pogo59** [comment] 2022-11-21 16:39
Zeroing used registers is a security measure, we should not be skipping it.

Looking at the godbolt link, clang is zeroing edi but gcc is not. The parameter to c() is passed in edi, probably this is why clang decided to zero it. Arguably, it doesn't need to be, because edi is not "used" inside of c(); the value on exit is the same value the caller put into it, i.e. there is no information leakage, so zeroing is unnecessary.  That might be why gcc does not bother to zero it.

The OP said this changed with/without -g; but in the godbolt link, if I remove -g, the codegen does not change, 'xor edi,edi' is still present.  So I'm not sure we've found what's really going on here.

**Comment by xgupta** [comment] 2022-11-22 01:14
> Zeroing used registers is a security measure, we should not be skipping it.
> 
But whether it is good choice to zeroing them also at higher optimization level? isn't it hurt performance?

> Looking at the godbolt link, clang is zeroing edi but gcc is not.
>
Sorry, gcc is also zeroing edi, but only at -O0.

>The parameter to c() is passed in edi, probably this is why clang decided to zero it. Arguably, it doesn't need to be, because edi is not "used" inside of c(); the value on exit is the same value the caller put into it, i.e. there is no information leakage, so zeroing is unnecessary. 
> 
Okay, thank you for explanation.

> The OP said this changed with/without -g; but in the godbolt link, if I remove -g, the codegen does not change, 'xor edi,edi' is still present. 
>
Actually godbolt by default pass -g, so even if we remove -g, it is still present there. We have to pass -g0 to disable that option or debuginfo.

> So I'm not sure we've found what's really going on here.
Agree, we still have to check how -g helps in running zero-call-used-regs pass at higher optimization level.

CC @nickdesaulniers and @isanbard on question whether zero-call-used-regs should run at higher level optimization level.

**Comment by nickdesaulniers** [comment] 2023-01-10 17:18
This was fixed by @nikic in https://github.com/llvm/llvm-project/commit/b4309800e9dc53a84222a6b57c8615d4a3084988.

clang-16.

**Comment by xgupta** [comment] 2023-01-21 11:40
> This was fixed by @nikic in [b430980](https://github.com/llvm/llvm-project/commit/b4309800e9dc53a84222a6b57c8615d4a3084988).
> 
> clang-16.

I reproduced the issue on trunk last time after the patch by @nikic, and currently, godbolt link is also showing a difference -https://godbolt.org/z/ndz36Kn3P.

**Comment by nickdesaulniers** [comment] 2023-01-23 21:07
So https://reviews.llvm.org/D138757 is still necessary @xgupta ?

**Comment by xgupta** [comment] 2023-01-23 21:08
Yes I think.

**Closed** 2023-01-25 05:33 UTC
Labels: debuginfo, llvm:optimizations
