### ISSUE TITLE
Dead Code Elimination Regression when using __builtin_unreachable (trunk vs 16)

### ISSUE THREAD

**Issue by thetheodor** [llvm/llvm-project#63576] opened 2023-06-28 10:13 UTC
https://godbolt.org/z/z3d5s1EdY

Given the following code:

```cpp
void foo(void);
static struct {
    int b;
} f;
static int c, d = 3;
static int *g = &c;
static void h();
static unsigned i(int, int *, int *);
static int j() {
    h();
    d = 0;
    return 1;
}
static void h() { i(8, &d, g); }
static unsigned i(int k, int *, int *l) {
    short a;
    c = 0;
    for (;; ++c) {
        int b;
        if (k) {
            int e = a >= 0;
            if (e) return 0;
            a = 0;
            for (; a >= 0; a--) k = 0;
            if (*l) continue;
            __builtin_unreachable();
        } else
            foo();
        return f.b;
    }
}
int main() { d || j(); }
```
Clang trunk `-O3` does not eliminate the call to `foo`:

```asm
main:                                   # @main
# %bb.0:
	cmpb	$1, d(%rip)
	jne	.LBB0_2
# %bb.1:
	pushq	%rax
	callq	foo@PLT
	movb	$1, d(%rip)
	addq	$8, %rsp
.LBB0_2:
	xorl	%eax, %eax
	retq
.Lfunc_end0:
```

Clang 16.0.6 `-O3` eliminates the call to `foo`:

```asm
main:                                   # @main
# %bb.0:
	xorl	%eax, %eax
	retq
.Lfunc_end0:
```

Bisects to 15d5c59280c9943b23a372ca5fdd8a88ce930514 (@vfdff)

**Comment by vfdff** [comment] 2023-09-02 09:04
a little simple case showed above issue, https://godbolt.org/z/WovaW6PdK
```
void foo(void);

static int c;

static int fooi(int k, int *l) {      // the variable &c is alias to the l
    short a;
    c = 0;                             // a) c == 0 when it first iteration of the for loop
    for (;; ++c) {
        int b;
        if (k) {
            a = 0;
            for (; a >= 0; a--) k = 0;
            if (*l) continue;
            __builtin_unreachable();   // b) this imply the *l !=0 
        } else
          foo();
         return 2;  
    }

    return 0;
}

int main() {
    fooi(8, &c);
    return 0;
}
```
I think it is UB when we add the **__builtin_unreachable()**, so this should not be fixed.
as you can see that, the following 2 hints are conflicted
* a) c == 0 when it first iteration of the for loop
* b) this imply the *l !=0

**Comment by vfdff** [comment] 2023-09-02 11:03
hi @fhahn, @thetheodor,  what do you think ?

**Comment by fhahn** [comment] 2023-09-04 12:03
Thanks @vfdff, I agree it looks like there is UB in the source. It also accesses an uninitialized variable (`a`) here:

```
    short a;
    c = 0;
    for (;; ++c) {
        int b;
        if (k) {
            int e = a >= 0;
            if (e) return 0;
            a = 0;
```.

@thetheodor I am going to close this now, but please feel free to re-open it if that was a mistake.

Do you think it would be possible to catch those kinds of UB during reproducer generation?

**Closed by fhahn** 2023-09-04 12:03 UTC
Labels: regression, llvm:optimizations

**Comment by thetheodor** [comment] 2023-09-04 12:19
@fhahn initializing `short a = -123` doesn't change the result much (it's actually never read in the original test case because `i()` is dead):
https://godbolt.org/z/PxcY57dGb

Also I don't think the original case contains UB: the location with `__builtin_unreachable()` is actually unreachable (the function that contains it is never called).

In contrast, in the modified case the `__builtin_unreachable()`  is actually reachable, which is obviously UB.
