### ISSUE TITLE
Clang instantiates overload despite failing constraint

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#61819] opened 2023-03-29 22:25 UTC
This GCC test should be well-formed, but is currently incorrect.
```cpp
// RUN: %clang_cc1 -std=c++20 -fsyntax-only -verify %s

template <class T> struct Z {
  typedef typename T::x xx;
};
template <class T> concept C = requires { typename T::A; };
template <C T> typename Z<T>::xx f(void *, T); // #1
template <class T> void f(int, T); // #2
struct A {} a;
struct ZZ {
  template <class T, class = typename Z<T>::xx> operator T *();
  operator int();
};
int main() {
  ZZ zz;
  f(1, a); // OK, deduction fails for #1 because there is no conversion from int to void*
  f(zz, 42); // OK, deduction fails for #1 because C<int> is not satisfied
}
```
Diagnostic issued:
```console
<source>:5:20: error: type 'void' cannot be used prior to '::' because it has no members
  typedef typename T::x xx;
                   ^
<source>:12:39: note: in instantiation of template class 'Z<void>' requested here
  template <class T, class = typename Z<T>::xx> operator T *();
                                      ^
<source>:12:49: note: in instantiation of default argument for 'operator type-parameter-0-0 *<void>' required here
  template <class T, class = typename Z<T>::xx> operator T *();
                                                ^~~~~~~~~~~~~~
<source>:18:5: note: while substituting deduced template arguments into function template 'operator type-parameter-0-0 *' [with T = void, $1 = (no value)]
  f(zz, 42); // OK, deduction fails for #1 because C<int> is not satisfied
    ^
<source>:18:3: note: while substituting deduced template arguments into function template 'f' [with T = int]
  f(zz, 42); // OK, deduction fails for #1 because C<int> is not satisfied
  ^
```
Note that `struct A` and `T::A` are completely unrelated.

**Comment by shafik** [comment] 2023-03-30 03:43
I think this looks correct wdyt @erichkeane

**Comment by cor3ntin** [comment] 2024-08-22 15:47
duplicate of #54440

**Closed by cor3ntin** 2024-08-22 15:47 UTC
Labels: c++20, clang:frontend, rejects-valid, concepts
