### ISSUE TITLE
Something happend when i want to get a Debugloc

### ISSUE THREAD

**Issue by aicreatbyme** [llvm/llvm-project#54015] opened 2022-02-23 10:20 UTC
code here:
  struct Hello : public FunctionPass
  {
    static char ID;
    Hello() : FunctionPass(ID) {}
    bool runOnFunction(Function &F) override
    {
      for (BasicBlock &BB : F)
      {
        // Print out the name of the basic block if it has one, and then the
        // number of instructions that it contains
        const DebugLoc &dd = BB.getInstList().begin()->getDebugLoc();
        auto i = dd.getLine();
        return false;
      }
    }
  };
}
environment:
clang 12
LLVM 12
release,by the way.
crash information:

0.      Program arguments: opt -load /home/kali/Desktop/toy/build/Hello/libtest.so -enable-new-pm=0 -hello main.ll -time-passes -o /dev/null
1.      Running pass 'Function Pass Manager' on module 'main.ll'.
2.      Running pass 'Hello World Pass' on function '@main'
 #0 0x000055e8f63ea1de llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/opt+0x18ec1de)
 #1 0x000055e8f63e7fc4 llvm::sys::RunSignalHandlers() (/usr/local/bin/opt+0x18e9fc4)
 #2 0x000055e8f63e8125 SignalHandler(int) (/usr/local/bin/opt+0x18ea125)
 #3 0x00007f91f1251200 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13200)
 #4 0x000055e8f5b4cf79 llvm::DebugLoc::getLine() const (/usr/local/bin/opt+0x104ef79)
 #5 0x00007f91f126ea0c (anonymous namespace)::Hello::runOnFunction(llvm::Function&) (/home/kali/Desktop/toy/build/Hello/libtest.so+0x4a0c)
 #6 0x000055e8f5bc12c5 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/local/bin/opt+0x10c32c5)
 #7 0x000055e8f5bc292c llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/local/bin/opt+0x10c492c)
 #8 0x000055e8f5bc0d48 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/local/bin/opt+0x10c2d48)
 #9 0x000055e8f4f7c12b main (/usr/local/bin/opt+0x47e12b)
#10 0x00007f91f0cde7ed __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x277ed)
#11 0x000055e8f4fedf3a _start (/usr/local/bin/opt+0x4eff3a)

**Comment by fhahn** [comment] 2022-02-23 10:28
I think the issue is that you are unconditionally accessing `DebugLoc`, which may be empty. You need to check if the debug location is valid: https://llvm.org/doxygen/classllvm_1_1DebugLoc.html#ad3d3e352271b660741f403e60c732b71

> auto i = dd.getLine();

Closing as this is not an LLVM bug.

**Closed by fhahn** 2022-02-23 10:28 UTC
Labels: invalid
