### ISSUE TITLE
assert.h: duplicate text 'be able to'

### ISSUE THREAD

**Issue by rillig** [llvm/llvm-project#61999] opened 2023-04-07 11:45 UTC

**Comment by EugeneZelenko** [comment] 2023-04-07 14:09
@rillig: Please elaborate. What is file path?

**Comment by rillig** [comment] 2023-04-07 16:52
There's only a single file named `assert.h` in the whole tree.

**Comment by michaelrj-google** [comment] 2023-04-07 19:01
Fixed with https://reviews.llvm.org/rGd92b58525951

**Closed by michaelrj-google** 2023-04-07 19:01 UTC
Labels: libc

**Comment by rillig** [comment] 2023-04-07 22:32
Thanks, could you perhaps replace "to capable" with "to be capable"?
I guess the changes to the `assert` macro were accidental, at least they are not mentioned in the commit message.

**Comment by michaelrj-google** [comment] 2023-04-10 17:04
Done. 
The assert macro changes were caused by clang-format.
