### ISSUE TITLE
Out of Line Definition Error for Constrained Method of Template Class

### ISSUE THREAD

**Issue by dev-lunarosa** [llvm/llvm-project#62003] opened 2023-04-07 14:29 UTC
For the following C++20 code, I am getting an out of line definition error from trunk, which I successfully pulled and compiled just a few hours ago. Clang 16 accepts this code; GCC does as well.

```cpp
template <typename A>
    concept valid = true; // Any concept will do
    
template <typename T>
    class Foo {
        template <valid U>
            void bar (U baz);
    };
    
template <typename T>
template <valid U>
    void Foo<T>::bar (U baz) {
    }
```

Error snippet:

```console
error: out-of-line definition of 'bar' does not match any declaration in 'Foo<T>'
    void Foo<T>::bar (U baz) {
                 ^~~
```

This seems like valid code, so I suspect there is a bug.

Note that either removing the template for class `Foo` and/or removing the constraint from the template method `bar` prevents the error.

**Comment by shafik** [comment] 2023-04-08 18:25
This looks like a possible clang-16 regression but needs some more digging into

CC @AaronBallman @erichkeane

**Comment by shafik** [comment] 2023-04-09 02:21
After thinking about it some more I realized this is: https://github.com/llvm/llvm-project/issues/61414

**Comment by alexander-shaposhnikov** [comment] 2023-04-09 04:40
This  will be fixed by https://reviews.llvm.org/D146178

**Comment by alexander-shaposhnikov** [comment] 2023-05-18 20:16
https://godbolt.org/z/Kzs69Parh

**Closed** 2023-05-18 20:16 UTC
Labels: clang:frontend, concepts
