### ISSUE TITLE
clang-19 unconditionally sets `__cpp_deleted_function`

### ISSUE THREAD

**Issue by mpusz** [llvm/llvm-project#110224] opened 2024-09-27 09:25 UTC
`__cpp_deleted_function` should be set only for C++26 and higher. It is set even for C++20 now (https://godbolt.org/z/T7Ph3E4fz), which makes the following code:

```cpp
  [[nodiscard]] friend consteval Unit auto operator*(Unit auto, Magnitude auto)
#if __cpp_deleted_function
    = delete("To scale a unit use `mag * unit` syntax");
#else
    = delete;
#endif
```

result in the following error on C++20 build:

```text
unit.h:154:14: error: '= delete' with a message is a C++2c extension [-Werror,-Wc++26-extensions]
   154 |     = delete("To scale a unit use `mag * unit` syntax");
       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by frederick-vs-ja** [comment] 2024-09-27 11:04
Duplicate of #109311, or even of #77262.

**Closed** 2024-09-27 12:40 UTC
Labels: duplicate, clang:driver
