### ISSUE TITLE
[MIPSEL][MIPS64EL] llvm-toolchain 15: builtins-bins build failed

### ISSUE THREAD

**Issue by kasperk81** [llvm/llvm-project#57397] opened 2022-08-27 03:38 UTC
builtins-bins' mipsel and mips64el builds failed with rc1, rc2 and rc3: https://buildd.debian.org/status/logs.php?pkg=llvm-toolchain-15&arch=mipsel and https://buildd.debian.org/status/logs.php?pkg=llvm-toolchain-15&arch=mips64el. It was building fine with llvm 14.

except from mipsel logs: https://buildd.debian.org/status/fetch.php?pkg=llvm-toolchain-15&arch=mipsel&ver=1%3A15.0.0%7E%2Brc3-1%7Eexp1&stamp=1661462547&raw=0

```console
[121/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/enable_execute_stack.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/enable_execute_stack.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/enable_execute_stack.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/enable_execute_stack.c'
[122/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/gcc_personality_v0.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/gcc_personality_v0.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/gcc_personality_v0.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/gcc_personality_v0.c'
[123/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/clear_cache.c'
FAILED: CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o 
"/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/clear_cache.c'
/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/clear_cache.c:97:3: error: call to undeclared function 'syscall'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  syscall(__NR_cacheflush, start, (end_int - start_int), BCACHE);
  ^
1 error generated.
[124/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/emutls.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/emutls.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/emutls.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/emutls.c'
[125/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips64r2 -mabi=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mips64el.dir/comparetf2.c.o -MF CMakeFiles/clang_rt.builtins-mips64el.dir/comparetf2.c.o.d -o CMakeFiles/clang_rt.builtins-mips64el.dir/comparetf2.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/comparetf2.c'
[126/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips64r2 -mabi=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mips64el.dir/addtf3.c.o -MF CMakeFiles/clang_rt.builtins-mips64el.dir/addtf3.c.o.d -o CMakeFiles/clang_rt.builtins-mips64el.dir/addtf3.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/addtf3.c'
[127/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips64r2 -mabi=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mips64el.dir/divtc3.c.o -MF CMakeFiles/clang_rt.builtins-mips64el.dir/divtc3.c.o.d -o CMakeFiles/clang_rt.builtins-mips64el.dir/divtc3.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/divtc3.c'
[128/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mipsel-unknown-linux-gnu -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips64r2 -mabi=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mips64el.dir/divtf3.c.o -MF CMakeFiles/clang_rt.builtins-mips64el.dir/divtf3.c.o.d -o CMakeFiles/clang_rt.builtins-mips64el.dir/divtf3.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/divtf3.c'
ninja: build stopped: subcommand failed.
FAILED: runtimes/builtins-stamps/builtins-build /<<PKGBUILDDIR>>/build-llvm/runtimes/builtins-stamps/builtins-build 
cd "/<<PKGBUILDDIR>>/build-llvm/runtimes/builtins-bins" && /usr/bin/cmake --build .
ninja: build stopped: subcommand failed.
make[1]: *** [debian/rules:648: debian-full-build] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:438: binary-arch] Error 2
dpkg-buildpackage: error: debian/rules binary-arch subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2022-08-25T21:22:14Z
```

excerpt from mips64el logs: https://buildd.debian.org/status/fetch.php?pkg=llvm-toolchain-15&arch=mips64el&ver=1%3A15.0.0%7E%2Brc3-1%7Eexp1&stamp=1661462048&raw=0
```console
[121/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/eprintf.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/eprintf.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/eprintf.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/eprintf.c'
[122/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/clear_cache.c'
FAILED: CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o 
"/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/clear_cache.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/clear_cache.c'
/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/clear_cache.c:97:3: error: call to undeclared function 'syscall'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  syscall(__NR_cacheflush, start, (end_int - start_int), BCACHE);
  ^
1 error generated.
[123/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/emutls.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/emutls.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/emutls.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/emutls.c'
[124/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mipsel.dir/gcc_personality_v0.c.o -MF CMakeFiles/clang_rt.builtins-mipsel.dir/gcc_personality_v0.c.o.d -o CMakeFiles/clang_rt.builtins-mipsel.dir/gcc_personality_v0.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/gcc_personality_v0.c'
[125/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips64r2 -mabi=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mips64el.dir/comparetf2.c.o -MF CMakeFiles/clang_rt.builtins-mips64el.dir/comparetf2.c.o.d -o CMakeFiles/clang_rt.builtins-mips64el.dir/comparetf2.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/comparetf2.c'
[126/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips64r2 -mabi=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mips64el.dir/addtf3.c.o -MF CMakeFiles/clang_rt.builtins-mips64el.dir/addtf3.c.o.d -o CMakeFiles/clang_rt.builtins-mips64el.dir/addtf3.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/addtf3.c'
[127/276] "/<<PKGBUILDDIR>>/build-llvm/./bin/clang" --target=mips64el-linux-gnuabi64 -DVISIBILITY_HIDDEN  -fstack-protector-strong -Wformat -Werror=format-security -O3 -DNDEBUG -mips64r2 -mabi=64 -std=c11 -fPIC -fno-builtin -fvisibility=hidden -fomit-frame-pointer -MD -MT CMakeFiles/clang_rt.builtins-mips64el.dir/divtc3.c.o -MF CMakeFiles/clang_rt.builtins-mips64el.dir/divtc3.c.o.d -o CMakeFiles/clang_rt.builtins-mips64el.dir/divtc3.c.o -c '/<<PKGBUILDDIR>>/compiler-rt/lib/builtins/divtc3.c'
ninja: build stopped: subcommand failed.
FAILED: runtimes/builtins-stamps/builtins-build /<<PKGBUILDDIR>>/build-llvm/runtimes/builtins-stamps/builtins-build 
cd "/<<PKGBUILDDIR>>/build-llvm/runtimes/builtins-bins" && /usr/bin/cmake --build .
ninja: build stopped: subcommand failed.
make[1]: *** [debian/rules:648: debian-full-build] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:438: binary-arch] Error 2
dpkg-buildpackage: error: debian/rules binary-arch subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2022-08-25T21:13:52Z
```

**Comment by tru** [comment] 2022-08-31 12:21
I checked this code and I can't see any changes to the relevant changes to this any time recently.. the correct include seems to be here: https://github.com/llvm/llvm-project/blob/release/15.x/compiler-rt/lib/builtins/clear_cache.c#L45

which is guarded the same way as the use of `syscall()`: https://github.com/llvm/llvm-project/blob/release/15.x/compiler-rt/lib/builtins/clear_cache.c#L94

So I am not sure what more I can do unless I have a good way to reproduce the problem locally, which seems unlikely I have time to do before the -final release.

If anyone want to investigate this that would be great, otherwise it will slip until after 15.0.0 release.

**Comment by tru** [comment] 2022-09-15 07:14
Any updates on this issue?

**Comment by tru** [comment] 2022-09-19 06:48
Moving this to 15.0.2 since I haven't had any updates and 15.0.1 is out tomorrow.

**Comment by kasperk81** [comment] 2022-09-19 07:35
It is up to @sylvestre if he wants to upstream the syscall patch: https://github.com/llvm/llvm-project-release-prs/pull/143#issuecomment-1237491737


Btw, after applying the syscall patch, the latest build failed with:

https://buildd.debian.org/status/fetch.php?pkg=llvm-toolchain-15&arch=mips64el&ver=1%3A15.0.0-2&stamp=1663011175&raw=0

```
[925/2368] /<<PKGBUILDDIR>>/build-llvm/./bin/clang++ --target=mips64el-linux-gnuabi64 -DHAVE_RPC_XDR_H=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/<<PKGBUILDDIR>>/compiler-rt/lib/sanitizer_common/.. -I/<<PKGBUILDDIR>>/build-llvm/include -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -ffile-prefix-map=/<<PKGBUILDDIR>>/= -no-canonical-prefixes -Wall -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -nostdinc++ -Wno-format -fno-rtti -Wglobal-constructors -MD -MT compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mipsel.dir/sanitizer_platform_limits_linux.cpp.o -MF compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mipsel.dir/sanitizer_platform_limits_linux.cpp.o.d -o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mipsel.dir/sanitizer_platform_limits_linux.cpp.o -c /<<PKGBUILDDIR>>/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_linux.cpp
FAILED: compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mipsel.dir/sanitizer_platform_limits_linux.cpp.o 
/<<PKGBUILDDIR>>/build-llvm/./bin/clang++ --target=mips64el-linux-gnuabi64 -DHAVE_RPC_XDR_H=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/<<PKGBUILDDIR>>/compiler-rt/lib/sanitizer_common/.. -I/<<PKGBUILDDIR>>/build-llvm/include -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/<<PKGBUILDDIR>>/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -ffile-prefix-map=/<<PKGBUILDDIR>>/= -no-canonical-prefixes -Wall -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG -mips32r2 -mabi=32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -nostdinc++ -Wno-format -fno-rtti -Wglobal-constructors -MD -MT compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mipsel.dir/sanitizer_platform_limits_linux.cpp.o -MF compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mipsel.dir/sanitizer_platform_limits_linux.cpp.o.d -o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.mipsel.dir/sanitizer_platform_limits_linux.cpp.o -c /<<PKGBUILDDIR>>/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_linux.cpp
/<<PKGBUILDDIR>>/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_linux.cpp:67:1: error: static assertion failed due to requirement 'struct_kernel_stat_sz == sizeof(stat)': 
COMPILER_CHECK(struct_kernel_stat_sz == sizeof(struct stat));
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tru** [comment] 2022-10-07 06:51
Since there haven't been much movement here for a while I am going to remove this from the 15.x milestone. If you still think it should be fixed in 15.x please let me know and I'll add it back.

**Comment by wzssyqa** [comment] 2023-08-28 01:22
This problem has been resoloved by:
0f99bc2d685c572c3b38fd0e1ca56be12d7e2f6a
674a17e9bbe82e8c53952fd94dcd862b17cb2d2f

**Closed** 2023-08-28 06:26 UTC
Labels: backend:MIPS, build-problem
