### ISSUE TITLE
[clang-format] Crash formatting header file - Windows - 17.0.1

### ISSUE THREAD

**Issue by bprb** [llvm/llvm-project#67616] opened 2023-09-27 22:49 UTC
I'm using prebuilt binary `LLVM-17.0.1-win64.exe` and see a crash when trying to format a C++ header file. It asks me to log an issue so here you go :)

```
> clang-format -i vk_device.h

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: clang-format -i vk_device.h
Exception Code: 0xC0000005
 #0 0x00007ff6273d5929 C:\Program Files\LLVM\bin\clang-format.exe 0xe5929 C:\Program Files\LLVM\bin\clang-format.exe 0xe5373
 #1 0x00007ff6273d5929 C:\Program Files\LLVM\bin\clang-format.exe 0xe3c20 C:\Program Files\LLVM\bin\clang-format.exe 0xe0d26
 #2 0x00007ff6273d5929 C:\Program Files\LLVM\bin\clang-format.exe 0x5bd3d C:\Program Files\LLVM\bin\clang-format.exe 0xc54d1
 #3 0x00007ff6273d5929 C:\Program Files\LLVM\bin\clang-format.exe 0x6eed7 C:\Program Files\LLVM\bin\clang-format.exe 0x51462
 #4 0x00007ff6273d5929 C:\Program Files\LLVM\bin\clang-format.exe 0x53e89 C:\Program Files\LLVM\bin\clang-format.exe 0x572d
 #5 0x00007ff6273d5929 C:\Program Files\LLVM\bin\clang-format.exe 0x39b6 C:\Program Files\LLVM\bin\clang-format.exe 0x1b0d40
 #6 0x00007ff6273d5929 (C:\Program Files\LLVM\bin\clang-format.exe+0xe5929)
 #7 0x00007ff6273d5373 (C:\Program Files\LLVM\bin\clang-format.exe+0xe5373)
0x00007FF6273D5929, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0xE5929 byte(s)
0x00007FF6273D5373, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0xE5373 byte(s)
0x00007FF6273D3C20, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0xE3C20 byte(s)
0x00007FF6273D0D26, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0xE0D26 byte(s)
0x00007FF62734BD3D, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0x5BD3D byte(s)
0x00007FF6273B54D1, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0xC54D1 byte(s)
0x00007FF62735EED7, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0x6EED7 byte(s)
0x00007FF627341462, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0x51462 byte(s)
0x00007FF627343E89, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0x53E89 byte(s)
0x00007FF6272F572D, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0x572D byte(s)
0x00007FF6272F39B6, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0x39B6 byte(s)
0x00007FF6274A0D40, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF6272F0000) + 0x1B0D40 byte(s)
0x00007FF920167034, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FF920150000) + 0x17034 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FF920F826A1, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FF920F30000) + 0x526A1 byte(s), RtlUserThreadStart() + 0x21 byte(s)

> clang-format --version

clang-format version 17.0.1

> ver

Microsoft Windows [Version 10.0.19045.2130]
```

I cannot share the file unfortunately but the crash seems to go away if I delete this code block:

```cpp
		VkDeviceQueueCreateInfo dqci[2] = {
			{
				VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,	// sType;
				nullptr,									// pNext;
				VkDeviceQueueCreateFlags(0),				// flags;
				preferred_graphics_queue_family_index,		// queueFamilyIndex;
				merge_queues ? 2u : 1u,						// queueCount;
				priorities,									// pQueuePriorities;
			},
			{
				VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,	// sType;
				nullptr,									// pNext;
				VkDeviceQueueCreateFlags(0),				// flags;
				preferred_compute_queue_family_index,		// queueFamilyIndex;
				1u,											// queueCount;
				priorities,									// pQueuePriorities;
			},
		};
```

I don't see any diagnostics in this file warning me about dubious C++ (using an LSP through Vim), so I'm not sure what's unusual about this snippet.  Thanks!

----

The format settings are `-style=Microsoft -dump-config` with these changes.  Sorry, the diff is backwards :\  The full file is below.

```diff
diff --git a/.clang-format b/.clang-format
index 2e06575..1d24348 100644
--- a/.clang-format
+++ b/.clang-format
@@ -3,37 +3,37 @@ Language:        Cpp
 # BasedOnStyle:  Microsoft
 AccessModifierOffset: -2
 AlignAfterOpenBracket: Align
-AlignArrayOfStructures: Left
+AlignArrayOfStructures: None
 AlignConsecutiveAssignments:
-  Enabled:         true
+  Enabled:         false
   AcrossEmptyLines: false
   AcrossComments:  false
-  AlignCompound:   true
+  AlignCompound:   false
   PadOperators:    true
 AlignConsecutiveBitFields:
-  Enabled:         true
+  Enabled:         false
   AcrossEmptyLines: false
   AcrossComments:  false
   AlignCompound:   false
   PadOperators:    false
 AlignConsecutiveDeclarations:
-  Enabled:         true
+  Enabled:         false
   AcrossEmptyLines: false
   AcrossComments:  false
-  AlignCompound:   true
-  PadOperators:    true
+  AlignCompound:   false
+  PadOperators:    false
 AlignConsecutiveMacros:
-  Enabled:         true
+  Enabled:         false
   AcrossEmptyLines: false
   AcrossComments:  false
-  AlignCompound:   true
-  PadOperators:    true
+  AlignCompound:   false
+  PadOperators:    false
 AlignConsecutiveShortCaseStatements:
-  Enabled:         true
-  AcrossEmptyLines: true
-  AcrossComments:  true
+  Enabled:         false
+  AcrossEmptyLines: false
+  AcrossComments:  false
   AlignCaseColons: false
-AlignEscapedNewlines: Left
+AlignEscapedNewlines: Right
 AlignOperands:   Align
 AlignTrailingComments:
   Kind:            Always
@@ -41,26 +41,26 @@ AlignTrailingComments:
 AllowAllArgumentsOnNextLine: true
 AllowAllParametersOfDeclarationOnNextLine: true
 AllowShortBlocksOnASingleLine: Never
-AllowShortCaseLabelsOnASingleLine: true
-AllowShortEnumsOnASingleLine: true
-AllowShortFunctionsOnASingleLine: All
+AllowShortCaseLabelsOnASingleLine: false
+AllowShortEnumsOnASingleLine: false
+AllowShortFunctionsOnASingleLine: None
 AllowShortIfStatementsOnASingleLine: Never
 AllowShortLambdasOnASingleLine: All
-AllowShortLoopsOnASingleLine: true
+AllowShortLoopsOnASingleLine: false
 AlwaysBreakAfterDefinitionReturnType: None
 AlwaysBreakAfterReturnType: None
 AlwaysBreakBeforeMultilineStrings: false
 AlwaysBreakTemplateDeclarations: MultiLine
 AttributeMacros:
   - __capability
-BinPackArguments: false
-BinPackParameters: false
+BinPackArguments: true
+BinPackParameters: true
 BitFieldColonSpacing: Both
 BraceWrapping:
   AfterCaseLabel:  false
   AfterClass:      true
   AfterControlStatement: Always
-  AfterEnum:       false
+  AfterEnum:       true
   AfterExternBlock: true
   AfterFunction:   true
   AfterNamespace:  true
@@ -68,13 +68,13 @@ BraceWrapping:
   AfterStruct:     true
   AfterUnion:      false
   BeforeCatch:     true
-  BeforeElse:      false
+  BeforeElse:      true
   BeforeLambdaBody: false
   BeforeWhile:     false
   IndentBraces:    false
-  SplitEmptyFunction: false
-  SplitEmptyRecord: false
-  SplitEmptyNamespace: false
+  SplitEmptyFunction: true
+  SplitEmptyRecord: true
+  SplitEmptyNamespace: true
 BreakAfterAttributes: Never
 BreakAfterJavaFieldAnnotations: false
 BreakArrays:     true
@@ -122,10 +122,10 @@ IncludeIsMainRegex: '(Test)?$'
 IncludeIsMainSourceRegex: ''
 IndentAccessModifiers: false
 IndentCaseBlocks: false
-IndentCaseLabels: true
+IndentCaseLabels: false
 IndentExternBlock: AfterExternBlock
 IndentGotoLabels: true
-IndentPPDirectives: AfterHash
+IndentPPDirectives: None
 IndentRequiresClause: true
 IndentWidth:     4
 IndentWrappedFunctionNames: false
@@ -133,11 +133,11 @@ InsertBraces:    false
 InsertNewlineAtEOF: false
 InsertTrailingCommas: None
 IntegerLiteralSeparator:
-  Binary:          4
+  Binary:          0
   BinaryMinDigits: 0
-  Decimal:         6
+  Decimal:         0
   DecimalMinDigits: 0
-  Hex:             4
+  Hex:             0
   HexMinDigits:    0
 JavaScriptQuotes: Leave
 JavaScriptWrapImports: true
@@ -165,11 +165,11 @@ PenaltyBreakTemplateDeclaration: 10
 PenaltyExcessCharacter: 1000000
 PenaltyIndentedWhitespace: 0
 PenaltyReturnTypeOnItsOwnLine: 1000
-PointerAlignment: Left
+PointerAlignment: Right
 PPIndentWidth:   -1
 QualifierAlignment: Leave
 ReferenceAlignment: Pointer
-ReflowComments:  false
+ReflowComments:  true
 RemoveBracesLLVM: false
 RemoveParentheses: Leave
 RemoveSemicolon: false
@@ -182,11 +182,11 @@ SortJavaStaticImport: Before
 SortUsingDeclarations: LexicographicNumeric
 SpaceAfterCStyleCast: false
 SpaceAfterLogicalNot: false
-SpaceAfterTemplateKeyword: false
+SpaceAfterTemplateKeyword: true
 SpaceAroundPointerQualifiers: Default
 SpaceBeforeAssignmentOperators: true
 SpaceBeforeCaseColon: false
-SpaceBeforeCpp11BracedList: true
+SpaceBeforeCpp11BracedList: false
 SpaceBeforeCtorInitializerColon: true
 SpaceBeforeInheritanceColon: true
 SpaceBeforeJsonColon: false
@@ -210,7 +210,7 @@ SpacesInContainerLiterals: true
 SpacesInLineCommentPrefix:
   Minimum:         1
   Maximum:         -1
-SpacesInParens:  Custom
+SpacesInParens:  Never
 SpacesInParensOptions:
   InCStyleCasts:   false
   InConditionalStatements: false
@@ -224,7 +224,7 @@ StatementMacros:
   - Q_UNUSED
   - QT_REQUIRE_VERSION
 TabWidth:        4
-UseTab:          AlignWithSpaces
+UseTab:          Never
 VerilogBreakBetweenInstancePorts: true
 WhitespaceSensitiveMacros:
   - BOOST_PP_STRINGIZE
```

Full `.clang-format`:

```
---
Language:        Cpp
# BasedOnStyle:  Microsoft
AccessModifierOffset: -2
AlignAfterOpenBracket: Align
AlignArrayOfStructures: Left
AlignConsecutiveAssignments:
  Enabled:         true
  AcrossEmptyLines: false
  AcrossComments:  false
  AlignCompound:   true
  PadOperators:    true
AlignConsecutiveBitFields:
  Enabled:         true
  AcrossEmptyLines: false
  AcrossComments:  false
  AlignCompound:   false
  PadOperators:    false
AlignConsecutiveDeclarations:
  Enabled:         true
  AcrossEmptyLines: false
  AcrossComments:  false
  AlignCompound:   true
  PadOperators:    true
AlignConsecutiveMacros:
  Enabled:         true
  AcrossEmptyLines: false
  AcrossComments:  false
  AlignCompound:   true
  PadOperators:    true
AlignConsecutiveShortCaseStatements:
  Enabled:         true
  AcrossEmptyLines: true
  AcrossComments:  true
  AlignCaseColons: false
AlignEscapedNewlines: Left
AlignOperands:   Align
AlignTrailingComments:
  Kind:            Always
  OverEmptyLines:  0
AllowAllArgumentsOnNextLine: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: true
AllowShortEnumsOnASingleLine: true
AllowShortFunctionsOnASingleLine: All
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: true
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: MultiLine
AttributeMacros:
  - __capability
BinPackArguments: false
BinPackParameters: false
BitFieldColonSpacing: Both
BraceWrapping:
  AfterCaseLabel:  false
  AfterClass:      true
  AfterControlStatement: Always
  AfterEnum:       false
  AfterExternBlock: true
  AfterFunction:   true
  AfterNamespace:  true
  AfterObjCDeclaration: true
  AfterStruct:     true
  AfterUnion:      false
  BeforeCatch:     true
  BeforeElse:      false
  BeforeLambdaBody: false
  BeforeWhile:     false
  IndentBraces:    false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
BreakAfterAttributes: Never
BreakAfterJavaFieldAnnotations: false
BreakArrays:     true
BreakBeforeBinaryOperators: None
BreakBeforeConceptDeclarations: Always
BreakBeforeBraces: Custom
BreakBeforeInlineASMColon: OnlyMultiline
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeColon
BreakInheritanceList: BeforeColon
BreakStringLiterals: true
ColumnLimit:     120
CommentPragmas:  '^ IWYU pragma:'
CompactNamespaces: false
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat:   false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: LogicalBlock
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
ForEachMacros:
  - foreach
  - Q_FOREACH
  - BOOST_FOREACH
IfMacros:
  - KJ_IF_MAYBE
IncludeBlocks:   Preserve
IncludeCategories:
  - Regex:           '^"(llvm|llvm-c|clang|clang-c)/'
    Priority:        2
    SortPriority:    0
    CaseSensitive:   false
  - Regex:           '^(<|"(gtest|gmock|isl|json)/)'
    Priority:        3
    SortPriority:    0
    CaseSensitive:   false
  - Regex:           '.*'
    Priority:        1
    SortPriority:    0
    CaseSensitive:   false
IncludeIsMainRegex: '(Test)?$'
IncludeIsMainSourceRegex: ''
IndentAccessModifiers: false
IndentCaseBlocks: false
IndentCaseLabels: true
IndentExternBlock: AfterExternBlock
IndentGotoLabels: true
IndentPPDirectives: AfterHash
IndentRequiresClause: true
IndentWidth:     4
IndentWrappedFunctionNames: false
InsertBraces:    false
InsertNewlineAtEOF: false
InsertTrailingCommas: None
IntegerLiteralSeparator:
  Binary:          4
  BinaryMinDigits: 0
  Decimal:         6
  DecimalMinDigits: 0
  Hex:             4
  HexMinDigits:    0
JavaScriptQuotes: Leave
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: true
KeepEmptyLinesAtEOF: false
LambdaBodyIndentation: Signature
LineEnding:      DeriveLF
MacroBlockBegin: ''
MacroBlockEnd:   ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: None
ObjCBinPackProtocolList: Auto
ObjCBlockIndentWidth: 2
ObjCBreakBeforeNestedBlockParam: true
ObjCSpaceAfterProperty: false
ObjCSpaceBeforeProtocolList: true
PackConstructorInitializers: BinPack
PenaltyBreakAssignment: 2
PenaltyBreakBeforeFirstCallParameter: 19
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakOpenParenthesis: 0
PenaltyBreakString: 1000
PenaltyBreakTemplateDeclaration: 10
PenaltyExcessCharacter: 1000000
PenaltyIndentedWhitespace: 0
PenaltyReturnTypeOnItsOwnLine: 1000
PointerAlignment: Left
PPIndentWidth:   -1
QualifierAlignment: Leave
ReferenceAlignment: Pointer
ReflowComments:  false
RemoveBracesLLVM: false
RemoveParentheses: Leave
RemoveSemicolon: false
RequiresClausePosition: OwnLine
RequiresExpressionIndentation: OuterScope
SeparateDefinitionBlocks: Leave
ShortNamespaceLines: 1
SortIncludes:    CaseSensitive
SortJavaStaticImport: Before
SortUsingDeclarations: LexicographicNumeric
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: false
SpaceAroundPointerQualifiers: Default
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeCpp11BracedList: true
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeJsonColon: false
SpaceBeforeParens: ControlStatements
SpaceBeforeParensOptions:
  AfterControlStatements: true
  AfterForeachMacros: true
  AfterFunctionDefinitionName: false
  AfterFunctionDeclarationName: false
  AfterIfMacros:   true
  AfterOverloadedOperator: false
  AfterRequiresInClause: false
  AfterRequiresInExpression: false
  BeforeNonEmptyParentheses: false
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: false
SpacesBeforeTrailingComments: 1
SpacesInAngles:  Never
SpacesInContainerLiterals: true
SpacesInLineCommentPrefix:
  Minimum:         1
  Maximum:         -1
SpacesInParens:  Custom
SpacesInParensOptions:
  InCStyleCasts:   false
  InConditionalStatements: false
  InEmptyParentheses: false
  Other:           false
SpacesInSquareBrackets: false
Standard:        Latest
StatementAttributeLikeMacros:
  - Q_EMIT
StatementMacros:
  - Q_UNUSED
  - QT_REQUIRE_VERSION
TabWidth:        4
UseTab:          AlignWithSpaces
VerilogBreakBetweenInstancePorts: true
WhitespaceSensitiveMacros:
  - BOOST_PP_STRINGIZE
  - CF_SWIFT_NAME
  - NS_SWIFT_NAME
  - PP_STRINGIZE
  - STRINGIZE
...

```

**Comment by owenca** [comment] 2023-11-29 23:31
It's likely that this was fixed in 17.0.6. I'm closing this issue because we can't really do anything without a reproducer.

**Closed by owenca** 2023-11-29 23:31 UTC
Labels: clang-format
