### ISSUE TITLE
build error 15.0.0rc1

### ISSUE THREAD

**Issue by blackcross86** [llvm/llvm-project#56923] opened 2022-08-04 13:18 UTC
```console
DEBUG util.py:623:  /usr/lib64/gcc/aarch64-rosa-linux-gnu/11.2.0/../../../../include/c++/11.2.0/math.h:39:12: error: no member named 'acos' in namespace 'std'
DEBUG util.py:623:  using std::acos;
DEBUG util.py:623:        ~~~~~^
DEBUG util.py:623:  /usr/lib64/gcc/aarch64-rosa-linux-gnu/11.2.0/../../../../include/c++/11.2.0/math.h:40:12: error: no member named 'asin' in namespace 'std'
DEBUG util.py:623:  using std::asin;
DEBUG util.py:623:        ~~~~~^
DEBUG util.py:623:  /usr/lib64/gcc/aarch64-rosa-linux-gnu/11.2.0/../../../../include/c++/11.2.0/math.h:41:12: error: no member named 'atan' in namespace 'std'
DEBUG util.py:623:  using std::atan;
DEBUG util.py:623:        ~~~~~^
DEBUG util.py:623:  /usr/lib64/gcc/aarch64-rosa-linux-gnu/11.2.0/../../../../include/c++/11.2.0/math.h:42:12: error: no member named 'atan2' in namespace 'std'
DEBUG util.py:623:  using std::atan2;
DEBUG util.py:623:        ~~~~~^
DEBUG util.py:623:  /usr/lib64/gcc/aarch64-rosa-linux-gnu/11.2.0/../../../../include/c++/11.2.0/math.h:43:12: error: no member named 'cos' in namespace 'std'; did you mean 'ios'?
DEBUG util.py:623:  using std::cos;
DEBUG util.py:623:        ~~~~~^
DEBUG util.py:623:  /builddir/build/BUILD/llvm-project-llvmorg-15.0.0-rc1/build/include/c++/v1/iosfwd:162:38: note: 'ios' declared here
DEBUG util.py:623:  typedef basic_ios<char>              ios;
```
the error occurs on aarch64 x86_64 architectures
full log in the archive
[build_log.zip](https://github.com/llvm/llvm-project/files/9259968/build_log.zip)

**Comment by philnik777** [comment] 2023-01-15 06:31
If this is still a problem, please provide a small reproducer. Closing this for now, since I suspect this is a configuration problem.

**Closed by philnik777** 2023-01-15 06:31 UTC
Labels: libc++, build-problem, new issue
