### ISSUE TITLE
libc++ std::visit does not optimize well

### ISSUE THREAD

**Issue by davidben** [llvm/llvm-project#73699] opened 2023-11-28 20:49 UTC
Trying to switch from `absl::variant` to `std::variant` in Chromium resulted in a small but non-trivial binary size regression. Poking around, I think the cause is libc++'s `std::visit`:

libc++'s `std::visit` seems to be implemented by building a function pointer table and jumping into it. I found this post which suggests this comes from a rather odd requirement where C++ promises an O(1) `std::visit`, relative to the number of choices in the variant. (Nevermind that this is a compile-time constant, and likely your program will fail to compile before you get too many alternatives to care!)
https://playfulprogramming.blogspot.com/2018/12/when-performance-guarantees-hurts.html

This doesn't optimize well and it seems Clang is unable to inline anything about it. `absl::variant` inlines fine.
https://godbolt.org/z/9Pehed59z
https://godbolt.org/z/qTKvMYoE7

Likewise, libstdc++ optimizes well:
https://godbolt.org/z/1dnYnb97c
https://godbolt.org/z/4jcaYcvoh

Interestingly, libstdc++ avoids having to worry about the `valueless_by_exception` state. They seem to try to specialize `std::variant` to avoid the case whenever possible:
https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libstdc%2B%2B-v3/include/std/variant;h=19b2158690a9b4d03081f697e6a945d7c2a4e56f;hb=cfb582f62791dfadc243d97d37f0b83ef77cf480#l380
https://godbolt.org/z/T77nGvM4o
https://godbolt.org/z/599qczYqs

Anyway, both Abseil and libstdc++ specialize variants with up to 33 and 11 alternatives, respectively with a switch/case, which is how they avoid the optimization issues that libc++ trips.
https://github.com/abseil/abseil-cpp/blob/8028a87c96df0fff5ab58daeec30c43ce6fb0d20/absl/types/internal/variant.h#L515
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78113

Seems we should either make libc++ implement a similar specialization, or make Clang better at optimizing away jump tables.

Abseil also has a variant benchmark, but I haven't tried it on libc++ yet.
https://github.com/abseil/abseil-cpp/blob/8028a87c96df0fff5ab58daeec30c43ce6fb0d20/absl/types/variant_benchmark.cc

**Comment by philnik777** [comment] 2023-11-28 23:24
This seems to be a duplicate of #62648. It would be great if you could post your analysis again there (which is really good BTW. Thanks!).

**Closed by philnik777** 2023-11-28 23:24 UTC
Labels: libc++
