### ISSUE TITLE
"No expected directives found" error message is confusing if `-verify=foo` was passed

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#58290] opened 2022-10-11 13:02 UTC
If one passes `-verify=foo`, the error message when no `foo-*` directives are found is:

```console
error: no expected directives found: consider use of 'expected-no-diagnostics'
```
however, what's meant here is not `expected-no-diagnostics` but of course `foo-no-diagnostics`. This is especially confusing if multiple compiler invocations with different `-verify=` values are present.

The error message should use the proper prefix.

**Comment by diohabara** [comment] 2022-10-14 19:38
Hi! Let me resolve this issue!

**Comment by diohabara** [comment] 2022-10-18 15:44
I'm still working on it!
I successfully reproduced the issue, and I'll fix it.

**Comment by diohabara** [comment] 2022-10-25 19:53
> It's fine that a "no-diagnostics" comment is required, _but_ if I pass `-verify=foo`, I must use "foo-no-diagnostics" and as such, it would be nice if error messages about the usage of such "expected" messages would use the proper prefix and tell me that I should be adding a "foo-no-diagnostics" comment, not an "expected-no-diagnostics" one.

Thanks, I see! Since the commit I mentioned said that `expected-no-diagnostics` was expected behavior, I was wondering if I were in the right direction.

**Comment by tbaederr** [comment] 2022-10-26 05:14
I don't think "expected-no-diagnostics" is to be taken literally; it's just the default when no `-verify=` is passed.

**Comment by Unique-Usman** [comment] 2023-04-10 18:36
Hello, has this issue been fixed and @diohabara are you still working on this, I will like to work on it.

**Comment by akshaykumars614** [comment] 2023-12-12 10:25
I am trying to understand this issue. Can you kindly provide me the steps to reproduce @diohabara. I am really new to this project.

**Comment by Sh0g0-1758** [comment] 2024-01-09 06:26
Hello, I think that this issue has not been resolved yet. @tbaederr , I would like to work on this issue, can you please assign it to me.

**Comment by Sh0g0-1758** [comment] 2024-01-10 04:29
I reproduced the error by reading the following documentation : [docs](https://clang.llvm.org/docs/InternalsManual.html#verifying-diagnostics). Will rectify it now.

**Comment by Sh0g0-1758** [comment] 2024-01-10 13:55
I have made the necessary changes in the DiagnosticFrontendKinds.td file as : 

`def err_verify_no_directives : Error<
    "no expected directives found: consider use of '%0'-no-diagnostics">;`

and in VerifyDiagnosticConsumer.cpp as : 

`  if (SrcManager) {
// Produce an error if no expected-* directives could be found in the
// source file(s) processed.
if (Status == HasNoDirectives) {
  Diags.Report(diag::err_verify_no_directives).AddString(TO DO : ADD DIAGNOSTIC NAME).setForceEmit();
  ++NumErrors;
  Status = HasNoDirectivesReported;
}`

can you please confirm whether or not I can get this by `SM.getDiagnostics()` ? 

@tbaederr

**Comment by tbaederr** [comment] 2024-01-11 08:52
You might wanna look at b4e0589b2cd98a93aad449486bb2a52ab8790781, which did something similar.

**Closed** 2024-02-07 14:10 UTC
Labels: good first issue, clang:driver
