### ISSUE TITLE
[clang++] Crash when calling coroutine handle.destroy() in await suspend()

### ISSUE THREAD

**Issue by FunMiles** [llvm/llvm-project#62335] opened 2023-04-24 21:00 UTC
I have an example of code that works with G++ 12, older Clang++ (v14.0.0 on macOS with experimental coroutines) and Clang++ in unoptimized compilation but crashes with `-O2` or `-O3` turned on. The crash happens when calling destroy on the handle of the suspended coroutine. The docs on cppreference.com states that when `await_resume` is called:

the coroutine is suspended (its coroutine state is populated with local variables and current suspension point). `awaiter.await_suspend(handle)` is called, where handle is the coroutine handle representing the current coroutine. Inside that function, the suspended coroutine state is observable via that handle, and it's this function's responsibility to schedule it to resume on some executor, or to be destroyed.

My code does just that. It destroys the calling subroutine and resumes another coroutine. Unfortunately, in macOS, Clang++ 14.0.2 (recent update) makes this code crash but only when `-O2` or `-O3` are used.

The below code is the minimum code I could build to demonstrate the problem. Note that almost any change will not be able to demonstrate the crash. For example, removing the loop in main (the part inside is called only once) will avoid the crash. The compiler does very aggressive optimization such that running the debugger does not allow to stop in several places that might be useful.

Is this, as I think, a bug in Clang++ or am I missing some detail of C++ legalese?

```.cpp
#include <iostream>
#if __has_include(<coroutine>)
#include <coroutine>
namespace crt = std;
#else
#include <experimental/coroutine>
namespace crt = std::experimental::coroutines_v1;
#endif

struct Timer {
    auto die_or_return(int t, bool destroy_handle=false)
    {
        struct awaiter {
            bool await_ready() const noexcept { return false; }

            void await_resume() const noexcept {}
            /* https://en.cppreference.com/w/cpp/language/coroutines states:
             * The coroutine is suspended (its coroutine state is populated with local variables and current suspension point).
             * awaiter.await_suspend(handle) is called, where handle is the coroutine handle representing the current coroutine.
             * Inside that function, the suspended coroutine state is observable via that handle,
             * and it's this function's responsibility to schedule it to resume on some executor,
             * or to be destroyed (returning false counts as scheduling)
             */
            crt::coroutine_handle<> await_suspend(crt::coroutine_handle<> h) noexcept
            {
                auto n = next;
                if (destroy_handle) {
                    h.destroy();
                }
                return n;
            }
            crt::coroutine_handle<> next;
            bool destroy_handle;
        };

        return awaiter{ender, destroy_handle};
    }

    crt::coroutine_handle<> ender = crt::noop_coroutine();
};

inline static bool active{true};

struct [[nodiscard]] autodestruct_task {
    struct promise_type {
        ~promise_type() { active = false; std::cout << "Dying" << std::endl; }
        autodestruct_task get_return_object() noexcept
        {
            return autodestruct_task{crt::coroutine_handle<promise_type>::from_promise(*this)};
        }

        crt::suspend_always initial_suspend() noexcept { return {}; }

        /// If the coroutine does not suspend at the end, its handle is automatically
        /// destroyed.
        crt::suspend_never final_suspend() noexcept {return {}; }

        void return_void() noexcept {}

        void unhandled_exception() noexcept { std::terminate(); }
    };

    crt::coroutine_handle<promise_type> handle;

    explicit autodestruct_task(crt::coroutine_handle<promise_type> h) noexcept : handle(h) {}

};

autodestruct_task test_death(Timer &timer) {
    co_await timer.die_or_return(0,true);
}

autodestruct_task end_task() {
    std::cout << "Ending" << std::endl;
    co_return;
}

int main() {
    Timer timer;
    timer.ender = end_task().handle;
    auto tsk_handle = test_death(timer).handle;
    while (active && !tsk_handle.done()) {
        std::cout << "Resume" << std::endl;
        tsk_handle();
    }
}
```

**Comment by shafik** [comment] 2023-04-24 21:30
CC @ChuanqiXu9

**Comment by FunMiles** [comment] 2023-04-25 17:20
@ChuanqiXu9 Godbolt has 14.0.0. On Mac OS it works with that. It's the later 14.0.2 that is causing issue. Do you have access to a MacOS machine?
One big change in Mac's clang++ between 14.0.0 and 14.0.2 is that the coroutine support library has moved from `std::experimental:: coroutines_v1` to `std`.
I can paste the assembly generated (969 lines). pastebin.com is undergoing some maintenance right now and I can wait until it's back on or paste into a message here. Would that help?

**Comment by ChuanqiXu9** [comment] 2023-04-26 02:00
@FunMiles I am going to close the issue since it doesn't appear in trunk. And there won't be new clang14 releases for sure. So it doesn't looks an **existing** issue from the perspective of developers. Please consider to try to update your compiler.

**Comment by FunMiles** [comment] 2023-04-26 05:03
@ChuanqiXu9 This is Apple's official Clang compiler based on LLVM14. We don't get a chance to upgrade the compiler until Apple decides we do. I don't mind if you are pushing this to Apple, but telling me it does not appear in trunk is utterly unsatisfying. It seems to me that with some setup/standard C++ library combination, the compiler does generate a code that crashes. I fear that the next Apple compiler (based on 15?) will still have the same issue. With all due respect and thanks for the work the LLVM team does, I think closing the issue like this is a disservice to a lot of clang++ (all the Mac OS users).

**Comment by ChuanqiXu9** [comment] 2023-04-26 05:34
@FunMiles  I don't mind to reopen the issue. I just think it is not helpful to keep this issue open. Since we (the LLVM developers) can do nothing about it. Maybe you can try to open an issue in Apple Clang's repo?

**Comment by FunMiles** [comment] 2023-04-26 05:38
I can open an issue there. I came to this repo after some search of coroutine issues lead me here. What's the location of Apple's clang repo?

**Comment by ChuanqiXu9** [comment] 2023-04-26 05:57
> I can open an issue there. I came to this repo after some search of coroutine issues lead me here. What's the location of Apple's clang repo?

https://github.com/apple/llvm-project

**Comment by ChuanqiXu9** [comment] 2023-08-10 08:51
Given it is not reproducible in trunk, I'll close this issue per our policy.

**Closed by ChuanqiXu9** 2023-08-10 08:51 UTC
Labels: coroutines
