### ISSUE TITLE
[clang-format] C++ `= 0` on virtual methods is susceptible to `BreakBeforeBinaryOperators`

### ISSUE THREAD

**Issue by Gregofi** [llvm/llvm-project#61181] opened 2023-03-04 08:45 UTC
Example:
```
class Foo {
public:
    virtual void Bar(int a, int b, int c, int d, int e, int g, int s, int w) const = 0;
};
```
becomes
```
class Foo {
public:
  virtual void Bar(int a, int b, int c, int d, int e, int g, int s, int w) const
      = 0;
};
```
with clang-format 15.0.7 and `BreakBeforeBinaryOperators: All`. On clang-format 14.0.0 with the same setting the output is following:
```
class Foo {
public:
  virtual void Bar(int a, int b, int c, int d, int e, int g, int s,
                   int w) const = 0;
};
```
which is what I would expect. Is this a bug with the newer version or is this intended? In the `BreakBeforeBinaryOperators` I couldn't find if this is intended behaviour. But nevertheless using the `NonAssignment` option is acceptable workaround.

**Comment by rymiel** [comment] 2023-03-04 11:21
Duplicate of #57569

**Closed by rymiel** 2023-03-04 11:21 UTC
Labels: new issue
