### ISSUE TITLE
Differing behavior of `std::type_index` hash and equality from libc++ and libstdc++

### ISSUE THREAD

**Issue by Skylion007** [llvm/llvm-project#61848] opened 2023-03-30 15:40 UTC
Full background can be found on the linked discussion https://github.com/pybind/pybind11/pull/4319#issuecomment-1480244859  Essentially the behavior of `std::type_index` is different between the two standard libraries. This behavior seems like a bug in LLVM's implementation and requires us to be careful whenever storing `std::type_index` in a hashmap when using libc++;

**Comment by frederick-vs-ja** [comment] 2023-04-03 03:41
Why is this considered a bug rather than a permissible implemenation divergence?

I think it's intended that libc++'s `type_info` can be ABI-compatible with other implemenations, but I'm not sure whether it's a goal for libc++'s `type_info::hash` to have the same results as others.

**Comment by frederick-vs-ja** [comment] 2023-04-03 10:48
Is this a duplicate of #59790? #34255 is possibly related.

**Comment by philnik777** [comment] 2023-04-07 23:10
Closing for now, since we can't fix it until Clang is fixed, and it's a duplicate (of a clang bug).

**Closed by philnik777** 2023-04-07 23:10 UTC
Labels: libc++
