### ISSUE TITLE
clang-tidy: modernize-use-using leaving fragments of the tidied code

### ISSUE THREAD

**Issue by ThomasHuetsch** [llvm/llvm-project#67531] opened 2023-09-27 08:46 UTC
clang-tidy check modernize-use-using (LLVM 17.0.1 and before) leaves some fragments of the tidied code which renders the code uncompilable (at best). A single function pointer typedef works fine but when multiple type aliases are defined the issue shows up.

Before
```
typedef void (*abcdefghijklmnopqrstuvw)(double);
typedef int (*ABCDEFGHIJKLMNO)(int);
typedef void (*x)();
```
After
```
using abcdefghijklmnopqrstuvw = void (*)(double);
typedef int (*ABCDE;
using ABCDEFGHIJKLMNO = int (*)(int);
typedef voi;
using x = void (*)();
```
Should be
```
using abcdefghijklmnopqrstuvw = void (*)(double);
using ABCDEFGHIJKLMNO = int (*)(int);
using x = void (*)();
```
Obviously, there is some relationship between the leftover fragments and the length of the type alias name
abcdefghijklmnopqrstuvw (23 characters)
typedef int (*ABCDE; (20 characters + LF == 23 - 2)
ABCDEFGHIJKLMNO (15 characters)
typedef voi; (12 characters + LF == 15 - 2)

**Comment by R2RT** [comment] 2023-10-15 22:11
Reproduces with17.0.2, does not reproduce on `main` (d5e91ca5633e630f97777d96103aba3fa1247080)

**Comment by R2RT** [comment] 2023-10-15 22:15
Seems to be already resolved by https://github.com/llvm/llvm-project/issues/65055

**Closed** 2023-11-09 17:11 UTC
Labels: duplicate, clang-tidy
