### ISSUE TITLE
flang openmp default(none) error for label

### ISSUE THREAD

**Issue by jdenny-ornl** [llvm/llvm-project#82029] opened 2024-02-16 19:07 UTC
Using LLVM main at f905877f2039, I see the following behavior:

```
$ cat tmp.F90
program hello
  !$omp parallel do default(none)
  label: do i=1,5
    print *, 'i=', i
  enddo label
end program hello

$ flang-new -fopenmp tmp.F90
error: Semantic errors in tmp.F90
./tmp.F90:3:3: error: The DEFAULT(NONE) clause requires that 'label' must be listed in a data-sharing attribute clause
    label: do i=1,5
    ^^^^^
./tmp.F90:5:9: error: The DEFAULT(NONE) clause requires that 'label' must be listed in a data-sharing attribute clause
    enddo label
          ^^^^^
```

My understanding is that labels are not relevant to `default(none)`.  Indeed gfortran (tested 12.2.0) compiles the above program successfully.

This use of labels appears many times in Fortran code in [UMT](https://github.com/LLNL/UMT) and prevents Flang from building it with OpenMP support.

**Comment by luporl** [comment] 2024-02-16 19:28
Possible duplicate of #80633.

**Comment by jdenny-ornl** [comment] 2024-02-16 19:39
> Possible duplicate of #80633.

Agreed.  Sorry, I didn't use the necessary keywords when searching existing issues.

**Closed** 2024-02-16 19:40 UTC
Labels: duplicate, flang:frontend, flang:openmp
