### ISSUE TITLE
Clang-15 ICE when compiled with -flto while building compiler-rt-sanitizers-15.0.0

### ISSUE THREAD

**Issue by immolo** [llvm/llvm-project#57740] opened 2022-09-14 15:52 UTC
I've found an interesting ICE which only occurs when LTO flags are turned on while building clang and llvm while compiling  compiler-rt-sanitizers. If I rebuild clang/llvm without the flto cflags then the bug does not appear.

Here is a small snippet but I've included the full build log to help.

```console
#0 0x00007fa7d69580b1 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0xd580b1)
 #1 0x00007fa7d69371f4 llvm::sys::RunSignalHandlers() (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0xd371f4)
 #2 0x00007fa7d688fbf8 (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0xc8fbf8)
 #3 0x00007fa7d5642f00 (/lib64/libc.so.6+0x3df00)
 #4 0x00007fa7d73e7d7d (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0x17e7d7d)
 #5 0x00007fa7d73e9e63 llvm::PromoteMemToReg(llvm::ArrayRef<llvm::AllocaInst*>, llvm::DominatorTree&, llvm::AssumptionCache*) (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0x17e9e63)
 #6 0x00007fa7d773517f llvm::SROAPass::runImpl(llvm::Function&, llvm::DominatorTree&, llvm::AssumptionCache&) (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0x1b3517f)
 #7 0x00007fa7d91209a3 (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0x35209a3)
 #8 0x00007fa7d6abb7eb llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0xebb7eb)
 #9 0x00007fa7d8a5cfe1 (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0x2e5cfe1)
#10 0x00007fa7d6abbbbe llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0xebbbbe)
#11 0x00007fa7d8a5cf81 (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0x2e5cf81)
#12 0x00007fa7d6abb42b llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0xebb42b)
#13 0x00007fa7debbecca (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x25becca)
#14 0x00007fa7ddc82315 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1682315)
#15 0x00007fa7ddf51974 (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1951974)
#16 0x00007fa7dcf82684 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x982684)
#17 0x00007fa7de5b8f19 clang::FrontendAction::Execute() (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1fb8f19)
#18 0x00007fa7de564647 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1f64647)
#19 0x00007fa7de623f20 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x2023f20)
#20 0x000056233403d2d9 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm/15/bin/x86_64-pc-linux-gnu-clang+++0x132d9)
#21 0x0000562334042af4 (/usr/lib/llvm/15/bin/x86_64-pc-linux-gnu-clang+++0x18af4)
#22 0x00007fa7de2b7855 (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1cb7855)
#23 0x00007fa7d6883f63 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/llvm/15/bin/../lib64/libLLVM-15.so+0xc83f63)
#24 0x00007fa7de2d0387 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1cd0387)
#25 0x00007fa7de2c819f clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1cc819f)
#26 0x00007fa7de2c84b9 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1cc84b9)
#27 0x00007fa7de2c985c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/lib/llvm/15/bin/../lib64/libclang-cpp.so.15+0x1cc985c)
#28 0x00005623340446b1 clang_main(int, char**) (/usr/lib/llvm/15/bin/x86_64-pc-linux-gnu-clang+++0x1a6b1)
#29 0x00007fa7d562e2ca (/lib64/libc.so.6+0x292ca)
#30 0x00007fa7d562e385 __libc_start_main (/lib64/libc.so.6+0x29385)
#31 0x000056233403a291 _start (/usr/lib/llvm/15/bin/x86_64-pc-linux-gnu-clang+++0x10291)
clang-15: error: clang frontend command failed with exit code 139 (use -v to see invocation)
```

CFLAGS used to build clang/llvm `-march=native -O2 -pipe -fgraphite-identity -floop-nest-optimize -flto=8 -fuse-linker-plugin -falign-functions=32`

This is the first time I've run into anything like this so please ask if any other files or tests will help you identify the cause and I'd be happy to oblige. 

[rt.log](https://github.com/llvm/llvm-project/files/9567885/rt.log)

**Comment by nikic** [comment] 2022-09-14 16:52
To clarify, you're saying that LTO is used to build LLVM/Clang, and then the resulting clang is used to build compiler-rt-sanitizers without LTO, right?

As far as I can tell `-fgraphite-identity -floop-nest-optimize` are not upstream clang flags, so what clang are you using here?

**Comment by nikic** [comment] 2022-09-14 16:54
Ah, these are GCC flags. So this is GCC miscompiling Clang or LLVM in a way that manifests in the compiler-rt build? In that case this probably needs to be reported on the GCC side, though not sure how actionable this is without a smaller reproducer.

**Comment by immolo** [comment] 2022-09-14 17:03
Sorry I forgot to add this was built from GCC.

I can push that bug their way and link back here if that helps?

**Comment by immolo** [comment] 2022-09-14 17:40
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106943

**Comment by xry111** [comment] 2023-05-13 03:13
It looks like a dup of #24952.

**Comment by thesamesam** [comment] 2023-05-13 23:25
Let's call this one fixed in 17 (thanks @xry111) but keep https://github.com/llvm/llvm-project/issues/24952 open for the UB.

**Closed by thesamesam** 2023-05-13 23:25 UTC
Labels: duplicate, llvm:optimizations, crash
