### ISSUE TITLE
[C++20] Clang doesn't support constructing aggregate type with () syntax.

### ISSUE THREAD

**Issue by danakj** [llvm/llvm-project#55799] opened 2022-05-31 17:45 UTC
This works in GCC and MSVC when compiling C++20:

```cpp
struct S {
    int i;
};

S f() {
    return S(2);
}
```

GCC: https://godbolt.org/z/Eh4vb55ro
MSVC: https://godbolt.org/z/hMhsMKPqb
Clang: https://godbolt.org/z/jjMTW65Yh

```
<source>:8:12: error: no matching conversion for functional-style cast from 'int' to 'S'
    return S(2);
           ^~~
<source>:3:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'int' to 'const S' for 1st argument
struct S {
       ^
<source>:3:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'int' to 'S' for 1st argument
struct S {
       ^
<source>:3:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
1 error generated.
```

**Comment by frederick-vs-ja** [comment] 2022-05-31 21:25
Duplicate of #54040.

**Closed** 2022-05-31 21:31 UTC
Labels: c++20, clang:frontend
