### ISSUE TITLE
Segmentation fault in clang++11.0.1

### ISSUE THREAD

**Issue by TylerSeanRau** [llvm/llvm-project#57112] opened 2022-08-12 05:25 UTC
Hello I've discovered a segmentation fault that occurs with clang++11.0.1

Command line that occurred, `clang-11 -emit-llvm -Xclang -disable-llvm-passes m.cpp -c`

Here's shell script the command output asked me to post:

```sh
# Crash reproducer for Debian clang version 11.0.1-2~deb10u1
# Driver args: "--driver-mode=g++" "m.cpp"
# Original command:  "/usr/lib/llvm-11/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "m.cpp" "-mrelocation-model" "static" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-resource-dir" "/usr/lib/llvm-11/lib/clang/11.0.1" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8" "-internal-isystem" "/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/backward" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/llvm-11/lib/clang/11.0.1/include" "-internal-externc-isystem" "/usr/include/x86_64-linux-gnu" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-fdeprecated-macro" "-fdebug-compilation-dir" "/home/tyler" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-o" "/tmp/m-e30949.o" "-x" "c++" "m.cpp"
 "/usr/lib/llvm-11/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "m.cpp" "-mrelocation-model" "static" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-fdeprecated-macro" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-x" "c++" "m-06476d.cpp"
```

Here's the reduced code that causes the issue
```cpp
# 1 "<built-in>"
# 1 "m.cpp"
typedef int a;
typedef int b;
template <typename, b...> struct c {
};
template <typename b, b d> using e = __make_integer_seq<c, b, d>;
template <a... f> using g = c<a, f...>;
template <a d> using h = e<a, d>;
constexpr int i = 1 << 15;
template <a j, typename k = h<j>> double l(double m) { n(m, k{}); }
template <a... o> double n(double m, g<o...>){((o, m) *...);}
double p(void) {
    l<i>(1);
}
```
If you change `constexpr int i = 1 << 15` to `constexpr int i = 1 << 13` then no segmentation fault occurs.

**Comment by tbaederr** [comment] 2022-08-12 05:50
Clang 11 is pretty old at this point. I can't reproduce the crash with clang 14, although the clang process takes roughly 20GB or memory while doing its work. That said, the crash your're seeing might just be clang running out of memory.

**Comment by TylerSeanRau** [comment] 2022-08-12 07:25
With clang built from f28c006a5895fc0e329fe15fead81e37457cb1d1 aka `lvmorrg-14.0.6` I get the following:
```
/home/tyler/m.cpp:10:56: warning: pack fold expression is a C++17 extension [-Wc++17-extensions]
template <a... o> double n(double m, g<o...>){((o, m) *...);}
                                                       ^
/home/tyler/m.cpp:10:49: warning: left operand of comma operator has no effect [-Wunused-value]
template <a... o> double n(double m, g<o...>){((o, m) *...);}
                                                ^
/home/tyler/m.cpp:13:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
/home/tyler/m.cpp:9:67: warning: non-void function does not return a value [-Wreturn-type]
template <a j, typename k = h<j>> double l(double m) { n(m, k{}); }
                                                                  ^
/home/tyler/m.cpp:12:5: note: in instantiation of function template specialization 'l<32768, c<int, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ...snipped..., 32764, 32765, 32766, 32767>' requested here
template <a j, typename k = h<j>> double l(double m) { n(m, k{}); }
                                                       ^
/home/tyler/m.cpp:12:5: note: in instantiation of function template specialization 'l<32768, c<int, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ...snipped..., 32764, 32765, 32766, 32767>>' requested here
    l<i>(1);
    ^
/home/tyler/m.cpp:10:56: note: use -fbracket-depth=N to increase maximum nesting level
template <a... o> double n(double m, g<o...>){((o, m) *...);}
                                                       ^
4 warnings and 1 error generated.
```
`...snippped...`s were inserted by me so I could make this comment.

**Comment by tbaederr** [comment] 2022-08-12 07:58
Yes, so no crash here.

**Comment by fhahn** [comment] 2022-08-14 16:25
> Yes, so no crash here.

It sounds like this has been fixed in current Clang. If I am mistaken, please re-open the issue.

**Closed by fhahn** 2022-08-14 16:25 UTC
Labels: clang, crash
