### ISSUE TITLE
[concepts] CTAD does not propagate constructor constraints to deduction guides

### ISSUE THREAD

**Issue by williamspatrick** [llvm/llvm-project#57646] opened 2022-09-09 11:07 UTC
Sample:
```c++
#include <iostream>
#include <string>

template <bool A = false, bool B = false>
struct foo
{
    constexpr foo() requires (!A && !B) = default;
    constexpr foo() requires (A || B) = delete;

    std::string value = "Hello World!";
};

int main()
{
    foo<> works{};
    std::cout << works.value << std::endl;

    foo fails{};

    return 0;
}
```
https://godbolt.org/z/coxs3PvbE

This fails with:
```console
<source>:18:9: error: ambiguous deduction for template arguments of 'foo'
    foo fails{};
        ^
<source>:7:15: note: candidate function [with A = false, B = false]
    constexpr foo() requires (!A && !B) = default;
              ^
<source>:8:15: note: candidate function [with A = false, B = false]
    constexpr foo() requires (A || B) = delete;
```

The same code passes with GCC 12.

**Comment by royjacobson** [comment] 2022-09-09 13:16
I tried to understand what the standard says here, and AFAICT the overload resolution in the CTAD here happens in terms of implicitly generated deduction guides which don't propagate the trailing requires from the constructors (see [over.match.class.deduct]). So I think this _is_ technically ambiguous.

Relevant GCC discussion from last year: https://www.mail-archive.com/gcc-patches@gcc.gnu.org/msg257689.html

Wish they'd filed a CWG issue for this.

**Comment by royjacobson** [comment] 2022-09-11 08:16
Great, this is also a duplicate of almost 3-years old #43829.

**Comment by royjacobson** [comment] 2022-09-11 19:22
This is now [CWG2528](https://cplusplus.github.io/CWG/issues/2628.html). I don't see a reason not to implement the suggested fix, since GCC/MSVC already do it.

**Comment by royjacobson** [comment] 2022-09-19 08:15
https://reviews.llvm.org/D134145

**Closed** 2022-09-19 21:07 UTC
Labels: clang:frontend, concepts
