### ISSUE TITLE
[clang] Structured bindings cannot be initialized from braced rvalue arrays

### ISSUE THREAD

**Issue by MagentaTreehouse** [llvm/llvm-project#98261] opened 2024-07-10 02:00 UTC
The following code fails to compile:
```cpp
struct Array {
    int data[2];
};

Array f() { return {}; }

int main() {
    auto [a, b]{f().data}; // xvalue init
    using T = int [2];
    auto [c, d]{T{}}; // prvalue init
}
```
See Compiler Explorer: https://godbolt.org/z/P3EPzWdTc

**Comment by shafik** [comment] 2024-07-10 04:58
Duplicate of: https://github.com/llvm/llvm-project/issues/31813

**Closed by shafik** 2024-07-10 04:58 UTC
Labels: clang:frontend
