### ISSUE TITLE
[ABI] Type with potentially-overlapping member (`[[no_unique_address]]`) still considered POD for the purpose of layout

### ISSUE THREAD

**Issue by MitalAshok** [llvm/llvm-project#90407] opened 2024-04-28 17:50 UTC
https://itanium-cxx-abi.github.io/cxx-abi/abi.html#POD

> However, a type is not considered to be a POD for the purpose of layout if it is:
>  - [...]
>  - a POD-struct with one or more potentially-overlapping non-static data members.

Clang does not seem to respect this. This is visible when tail-padding is not reused

https://github.com/llvm/llvm-project/blob/216787cffc4a864e0effb165c1c32b92328a0a06/clang/lib/AST/RecordLayoutBuilder.cpp#L2421

```c++
struct X {  // Not POD for the purpose of layout
    [[no_unique_address]] alignas(4) char a;  // potentially-overlapping
};

struct Y : X {
    char b;  // This should be in the tail-padding
};

static_assert(sizeof(Y) == 4);
```

Clang makes `sizeof(Y) == 8`, disagreeing with GCC

**Comment by Michael137** [comment] 2024-04-28 22:57
Dupe of https://github.com/llvm/llvm-project/issues/50766?

**Closed** 2024-04-29 07:38 UTC
Labels: clang:frontend
