### ISSUE TITLE
[MSVC] hardcode path in LLVMExports.cmake of clang+llvm-18.1.8-x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by ACWhaleN** [llvm/llvm-project#100372] opened 2024-07-24 13:21 UTC
When I coding under GCC(amd64, Windows11) by using the chooseMSVCCRT macro, `diaguids.lib` is implicitly imported. And because the `L476` of `LLVMExports.cmake` in the lib\cmake\llvm folder uses an absolute path, my program fails to build.

`lib\cmake\llvm\LLVMExports.cmake`: `L475`~`L477`
```
set_target_properties(LLVMDebugInfoPDB PROPERTIES
  INTERFACE_LINK_LIBRARIES "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/DIA SDK/lib/amd64/diaguids.lib;LLVMBinaryFormat;LLVMObject;LLVMSupport;LLVMDebugInfoCodeView;LLVMDebugInfoMSF"
)
```

biuld-logs:
```
[ 30%] Building CXX object test/CMakeFiles/qcc.dir/__/src/Parser/Type.cpp.obj
mingw32-make.exe[3]: *** No rule to make target 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/DIA SDK/lib/amd64/diaguids.lib', needed by 'test/qcc.exe'.  Stop.
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
```
(when I use ninja)
```
ninja: error: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/DIA SDK/lib/amd64/diaguids.lib', needed by 'test/qcc.exe', missing and no known rule to make it.
```
In fact, I have never used Microsoft Visual Studio 2019 Professional.

**The problem was solved when I switched to LLVM installed with pacman in msys2.**

**Comment by Sirraide** [comment] 2024-07-28 02:25
Thanks for the report; I’m going to close this one though since it’s a duplicate of #86250.

**Closed by Sirraide** 2024-07-28 02:25 UTC
Labels: clang
