### ISSUE TITLE
clang-tidy - cancel with Illegal instruction

### ISSUE THREAD

**Issue by shrek1402** [llvm/llvm-project#53285] opened 2022-01-19 06:51 UTC
```
0.      Program arguments: C:\\LLVM\\bin\\clang-tidy.exe -checks=* MI.EntryPoint.cpp -- -std=c++17
1.      <eof> parser at end of file
 #0 0x00007ff7ac183f56 (C:\LLVM\bin\clang-tidy.exe+0x1343f56)
 #1 0x00007ffb27321881 (C:\Windows\System32\ucrtbase.dll+0x71881)
 #2 0x00007ffb27322851 (C:\Windows\System32\ucrtbase.dll+0x72851)
 #3 0x00007ffb2732426e (C:\Windows\System32\ucrtbase.dll+0x7426e)
 #4 0x00007ffb27324165 (C:\Windows\System32\ucrtbase.dll+0x74165)
 #5 0x00007ffb273244f1 (C:\Windows\System32\ucrtbase.dll+0x744f1)
 #6 0x00007ff7ac5c8c84 (C:\LLVM\bin\clang-tidy.exe+0x1788c84)
 #7 0x00007ff7ac5c9939 (C:\LLVM\bin\clang-tidy.exe+0x1789939)
 #8 0x00007ff7ac5c9a52 (C:\LLVM\bin\clang-tidy.exe+0x1789a52)
 #9 0x00007ff7abcf8353 (C:\LLVM\bin\clang-tidy.exe+0xeb8353)
#10 0x00007ff7abcf15ea (C:\LLVM\bin\clang-tidy.exe+0xeb15ea)
#11 0x00007ff7abcf15ea (C:\LLVM\bin\clang-tidy.exe+0xeb15ea)
#12 0x00007ff7abcf21d8 (C:\LLVM\bin\clang-tidy.exe+0xeb21d8)
#13 0x00007ff7abc9ac21 (C:\LLVM\bin\clang-tidy.exe+0xe5ac21)
#14 0x00007ff7abc93742 (C:\LLVM\bin\clang-tidy.exe+0xe53742)
#15 0x00007ff7abd007f5 (C:\LLVM\bin\clang-tidy.exe+0xec07f5)
#16 0x00007ff7abc93d6f (C:\LLVM\bin\clang-tidy.exe+0xe53d6f)
#17 0x00007ff7abcf221a (C:\LLVM\bin\clang-tidy.exe+0xeb221a)
#18 0x00007ff7abc9ac21 (C:\LLVM\bin\clang-tidy.exe+0xe5ac21)
#19 0x00007ff7abc93742 (C:\LLVM\bin\clang-tidy.exe+0xe53742)
#20 0x00007ff7abd007f5 (C:\LLVM\bin\clang-tidy.exe+0xec07f5)
#21 0x00007ff7abc93d6f (C:\LLVM\bin\clang-tidy.exe+0xe53d6f)
#22 0x00007ff7ab1c17c5 (C:\LLVM\bin\clang-tidy.exe+0x3817c5)
#23 0x00007ff7ab1c285e (C:\LLVM\bin\clang-tidy.exe+0x38285e)
#24 0x00007ff7ab1c4209 (C:\LLVM\bin\clang-tidy.exe+0x384209)
#25 0x00007ff7ac59c683 (C:\LLVM\bin\clang-tidy.exe+0x175c683)
#26 0x00007ff7ac5b930b (C:\LLVM\bin\clang-tidy.exe+0x177930b)
#27 0x00007ff7ac59bb72 (C:\LLVM\bin\clang-tidy.exe+0x175bb72)
#28 0x00007ff7ac59cada (C:\LLVM\bin\clang-tidy.exe+0x175cada)
#29 0x00007ff7ac5a0d6b (C:\LLVM\bin\clang-tidy.exe+0x1760d6b)
#30 0x00007ff7ac59ce4e (C:\LLVM\bin\clang-tidy.exe+0x175ce4e)
#31 0x00007ff7ac59e68b (C:\LLVM\bin\clang-tidy.exe+0x175e68b)
#32 0x00007ff7ac59cc6e (C:\LLVM\bin\clang-tidy.exe+0x175cc6e)
#33 0x00007ff7ac5a3d6b (C:\LLVM\bin\clang-tidy.exe+0x1763d6b)
#34 0x00007ff7ac59d28c (C:\LLVM\bin\clang-tidy.exe+0x175d28c)
#35 0x00007ff7ac57e7bd (C:\LLVM\bin\clang-tidy.exe+0x173e7bd)
#36 0x00007ff7acc0242c (C:\LLVM\bin\clang-tidy.exe+0x1dc242c)
#37 0x00007ff7acdd0eb3 (C:\LLVM\bin\clang-tidy.exe+0x1f90eb3)
#38 0x00007ff7acc076c5 (C:\LLVM\bin\clang-tidy.exe+0x1dc76c5)
#39 0x00007ff7acbe8fb4 (C:\LLVM\bin\clang-tidy.exe+0x1da8fb4)
#40 0x00007ff7ac6669e0 (C:\LLVM\bin\clang-tidy.exe+0x18269e0)
#41 0x00007ff7ac689549 (C:\LLVM\bin\clang-tidy.exe+0x1849549)
#42 0x00007ff7ac666891 (C:\LLVM\bin\clang-tidy.exe+0x1826891)
#43 0x00007ff7ac665a77 (C:\LLVM\bin\clang-tidy.exe+0x1825a77)
#44 0x00007ff7ac66824f (C:\LLVM\bin\clang-tidy.exe+0x182824f)
#45 0x00007ff7ac685a6a (C:\LLVM\bin\clang-tidy.exe+0x1845a6a)
#46 0x00007ff7aae43404 (C:\LLVM\bin\clang-tidy.exe+0x3404)
#47 0x00007ff7ad1c7b00 (C:\LLVM\bin\clang-tidy.exe+0x2387b00)
#48 0x00007ffb28ac7034 (C:\Windows\System32\KERNEL32.DLL+0x17034)
#49 0x00007ffb293e2651 (C:\Windows\SYSTEM32\ntdll.dll+0x52651)
Illegal instruction
```

**Comment by asl** [comment] 2022-01-19 09:28
Will you please attach a reproducer?

**Comment by LegalizeAdulthood** [comment] 2022-01-28 23:34
This looks like it might be a duplicate of #53359

**Comment by PiotrZSL** [comment] 2023-08-06 21:57
This is most probably duplicate of #53874 that is already fixed.
But due to missing reproduction, debug symbols unable to go forward with this issue.
If problem reproduce, then please re-open this issue or create new one.

**Closed** 2023-08-06 21:57 UTC
Labels: clang-tidy, worksforme
