### ISSUE TITLE
Clang 15.0.2 libc++ segfault on __builtin_operator_new

### ISSUE THREAD

**Issue by victorstewart** [llvm/llvm-project#58611] opened 2022-10-25 22:08 UTC
let me know if there's any more information that would be helpful to gather

```gdb
Program received signal SIGSEGV, Segmentation fault.
0x00005555556a146e in operator new(unsigned long) ()
(gdb) backtrace
#0  0x00005555556a146e in operator new(unsigned long) ()
#1  0x000055555590495d in std::__1::__libcpp_operator_new[abi:v15002]<unsigned long>(unsigned long) (__args=93824997048064) at /usr/local/bin/../include/c++/v1/new:246
#2  std::__1::__libcpp_allocate[abi:v15002](unsigned long, unsigned long) (__size=93824997048064, __align=16) at /usr/local/bin/../include/c++/v1/new:272
#3  std::__1::allocator<unsigned __int128>::allocate[abi:v15002](unsigned long) (__n=1, this=<optimized out>) at /usr/local/bin/../include/c++/v1/__memory/allocator.h:112
#4  std::__1::__allocate_at_least[abi:v15002]<std::__1::allocator<unsigned __int128> >(std::__1::allocator<unsigned __int128>&, unsigned long) (__n=1, __alloc=...)
    at /usr/local/bin/../include/c++/v1/__memory/allocate_at_least.h:54
#5  std::__1::__split_buffer<unsigned __int128, std::__1::allocator<unsigned __int128>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<unsigned __int128>&) (__cap=1, __start=0, 
    this=<optimized out>, __a=...) at /usr/local/bin/../include/c++/v1/__split_buffer:316
#6  std::__1::vector<unsigned __int128, std::__1::allocator<unsigned __int128> >::__push_back_slow_path<unsigned __int128 const&>(unsigned __int128 const&) (this=<optimized out>, __x=<optimized out>)
    at /usr/local/bin/../include/c++/v1/vector:1535
#7  std::__1::vector<unsigned __int128, std::__1::allocator<unsigned __int128> >::push_back[abi:v15002](unsigned __int128 const&) (this=<optimized out>, __x=<optimized out>)
    at /usr/local/bin/../include/c++/v1/vector:1553
```

**Comment by mclow** [comment] 2022-10-25 22:15
A reproducer would be nice. 
I suspect that somewhere along the line, an out-of-bounds write corrupted the heap.

**Comment by philnik777** [comment] 2023-03-20 21:47
Do you have a reproducer? If not, let's close the issue, since we can't determine what the problem is without one.

**Closed** 2023-07-13 22:46 UTC
Labels: libc++, incomplete
