### ISSUE TITLE
Kernel 6.7.6 - linking vmlimuz.o failed - llvm 18.1.0-rc3

### ISSUE THREAD

**Issue by MrDuartePT** [llvm/llvm-project#82896] opened 2024-02-24 22:06 UTC
I having problem on the liking phase of kernel 6.7.6 - Im using the gentoo-source kernel (mainline kernel with gentoo patches) + [CachyOs Patches](https://github.com/CachyOS/kernel-patches/blob/master/6.7/all/0001-cachyos-base-all.patch)

Here is the backtrace log given by the kernel:
``` 
 LD      vmlinux.o
ld.lld: /var/tmp/portage/sys-devel/llvm-18.1.0_rc3/work/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:9845: SDValue llvm::SelectionDAG::getNode(unsigned int, const SDLoc &, SDVTList, ArrayRef<SDValue>, const SDNodeFlags): Assertion `Op.getOpcode() != ISD::DELETED_NODE && "Operand is DELETED_NODE!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ld.lld -m elf_x86_64 -mllvm -import-instr-limit=5 -z noexecstack -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive vmlinux.a --no-whole-archive --start-group --end-group
1.	Running pass 'Function Pass Manager' on module 'ld-temp.o'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
 #0 0x00007f0171a0a7f6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x480a7f6)
 #1 0x00007f0171a07c20 llvm::sys::RunSignalHandlers() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4807c20)
 #2 0x00007f0171a0b03e (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x480b03e)
 #3 0x00007f016cf60d30 (/usr/lib64/libc.so.6+0x3bd30)
 #4 0x00007f016cfb118c (/usr/lib64/libc.so.6+0x8c18c)
 #5 0x00007f016cf60c82 raise (/usr/lib64/libc.so.6+0x3bc82)
 #6 0x00007f016cf494ed abort (/usr/lib64/libc.so.6+0x244ed)
 #7 0x00007f016cf49415 (/usr/lib64/libc.so.6+0x24415)
 #8 0x00007f016cf595d2 (/usr/lib64/libc.so.6+0x345d2)
 #9 0x00007f01727dde7c llvm::SelectionDAG::getNode(unsigned int, llvm::SDLoc const&, llvm::SDVTList, llvm::ArrayRef<llvm::SDValue>, llvm::SDNodeFlags) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x55dde7c)
#10 0x00007f01728113c1 llvm::SelectionDAGISel::Select_INLINEASM(llvm::SDNode*) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x56113c1)
#11 0x00007f01762b3662 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x90b3662)
#12 0x00007f017280ad18 llvm::SelectionDAGISel::DoInstructionSelection() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x560ad18)
#13 0x00007f01728093ab llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x56093ab)
#14 0x00007f0172805abf llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x5605abf)
#15 0x00007f0172801ce6 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x5601ce6)
#16 0x00007f01762a580e (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x90a580e)
#17 0x00007f01720511d9 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4e511d9)
#18 0x00007f0171c15b2b llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4a15b2b)
#19 0x00007f0171c20652 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4a20652)
#20 0x00007f0171c1683f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x4a1683f)
#21 0x00007f0173e35963 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x6c35963)
#22 0x00007f0173e3467c llvm::lto::backend(llvm::lto::Config const&, std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, unsigned int, llvm::Module&, llvm::ModuleSummaryIndex&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x6c3467c)
#23 0x00007f0173e23193 llvm::lto::LTO::runRegularLTO(std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x6c23193)
#24 0x00007f0173e21fd1 llvm::lto::LTO::run(std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>, std::__1::function<llvm::Expected<std::__1::function<llvm::Expected<std::__1::unique_ptr<llvm::CachedFileStream, std::__1::default_delete<llvm::CachedFileStream>>> (unsigned int, llvm::Twine const&)>> (unsigned int, llvm::StringRef, llvm::Twine const&)>) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+libcxx+0x6c21fd1)
#25 0x00007f0177417b40 lld::elf::BitcodeCompiler::compile() (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x217b40)
#26 0x00007f017737410a lld::elf::LinkerDriver::link(llvm::opt::InputArgList&) (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x17410a)
#27 0x00007f017735e2dd lld::elf::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x15e2dd)
#28 0x00007f017735c870 lld::elf::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/usr/lib/llvm/18/bin/../lib64/liblldELF.so.18.1+libcxx+0x15c870)
#29 0x00007f0176fc53ee lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/usr/lib/llvm/18/bin/../lib64/liblldCommon.so.18.1+libcxx+0x133ee)
#30 0x000055734dd0b428 lld_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm/18/bin/ld.lld+0x4428)
#31 0x000055734dd0bd9e main (/usr/lib/llvm/18/bin/ld.lld+0x4d9e)
#32 0x00007f016cf4aeea (/usr/lib64/libc.so.6+0x25eea)
#33 0x00007f016cf4afa5 __libc_start_main (/usr/lib64/libc.so.6+0x25fa5)
#34 0x000055734dd0b1f1 _start (/usr/lib/llvm/18/bin/ld.lld+0x41f1)
make[2]: *** [scripts/Makefile.vmlinux_o:62: vmlinux.o] Error 134
make[1]: *** [/usr/src/linux-6.7.6-gentoo/Makefile:1293: vmlinux_o] Error 2
make: *** [Makefile:234: __sub-make] Error 2
Install Modules
  SYMLINK /lib/modules/6.7.6-gentoo-x86_64/build
  INSTALL /lib/modules/6.7.6-gentoo-x86_64/modules.order
make[2]: *** No rule to make target 'modules.builtin', needed by '/lib/modules/6.7.6-gentoo-x86_64/modules.builtin'.  Stop.
make[1]: *** [/usr/src/linux-6.7.6-gentoo/Makefile:1977: modules_install] Error 2
make: *** [Makefile:234: __sub-make] Error 2
```

Emerge info (include my compiler and glibc version + compiler flags): 
[emerge-info.txt](https://github.com/llvm/llvm-project/files/14394526/emerge-info.txt)
Note: It said that I have LLVM 17 still install but I only using LLVM 18 right now

**Comment by brad0** [comment] 2024-02-24 23:19
cc @MaskRay

**Comment by MrDuartePT** [comment] 2024-02-25 10:36
Forget to say this, but kernel 6.7.5 with the same patch + plus Burst-Oriented Response Enhancer patches didn’t crash.

**Comment by MaskRay** [comment] 2024-02-26 23:34
Can you link `vmlinux.o` using the environment vairable `LLD_REPRODUCE=rep.tar` and upload the reproduce tarball somewhere?

**Comment by MrDuartePT** [comment] 2024-02-26 23:41
I just use the manual build process for the kernel, just use the gentoo-source package because it applies the gentoo patches to it nothing more. If you what to here is the script I use to build the kernel: https://github.com/MrDuartePT/hyprland-dotfiles/blob/master/build-kernel

![image](https://github.com/llvm/llvm-project/assets/68701049/b6baeb7a-3a92-4c55-8842-03a4397576d3)

**Comment by MrDuartePT** [comment] 2024-02-26 23:57
Here is the rep.tar for kernel 6.7.5 (the error is the same that 6.7.6 when using LLVM-18)
Now I gonna compile 6.7.6 without any patches applied to see if fails.
https://we.tl/t-Qsm38GFxfc
Sorry for the wetranfer link but dosent fit on github size limit

**Comment by MrDuartePT** [comment] 2024-02-27 01:01
Ok compiled 6.7.6 with the CachyOS patches and it compile fine. Well probably is something with there patches and lld when liking the kernel.

**Comment by MrDuartePT** [comment] 2024-02-28 20:32
Well after talking with [developer of CachyOS kernel patches](https://github.com/CachyOS/kernel-patches/issues/48), we find out this to commit are problematic on LLVM-18:

https://github.com/CachyOS/linux/commit/2711ed12a829b6086add5be0bdb0be61bf23c892
https://github.com/CachyOS/linux/commit/6ec793e12dee914d26761bec11cbdb6df4a9ea1e

This two commit are part of this patch: https://github.com/CachyOS/kernel-patches/blob/master/6.7/0004-cachy.patch

**Comment by ptr1337** [comment] 2024-02-28 20:48
@MaskRay 
It appears to be a regression in lld/llvm , when following patch gets applied:
https://github.com/CachyOS/linux/commit/6ec793e12dee914d26761bec11cbdb6df4a9ea1e

This patch comes from:
https://github.com/graysky2/kernel_compiler_patch/blob/master/more-uarches-for-kernel-6.1.79-6.8-rc3.patch

In my case, I have tested it with MZEN4=y, which does apply -march=znver4 to the kernel compilation.
I need to test, if this also affects:
- ThinLTO
- Clang without LTO
- -march=x86-64(-v2,-v3-v4)

**Comment by ptr1337** [comment] 2024-02-28 21:17
Happens also with -march=znver4 and ThinLTO and no LTO enabled.
Here the log from no LTO + -march=znver4:

```
  CC [M]  drivers/virtio/virtio_dma_buf.o
/usr/include/c++/13.2.1/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = llvm::SUnit; _Alloc = std::allocator<llvm::SUnit>; reference = llvm::SUnit&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang -Wp,-MMD,net/ipv6/.ip6_input.o.d -nostdinc -I./arch/x86/include -I./arch/x86/include/generated -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ --target=x86_64-linux-gnu -fintegrated-as -Werror=unknown-warning-option -Werror=ignored-optimization-argument -Werror=option-ignored -Werror=unused-command-line-argument -fmacro-prefix-map=./= -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -mno-avx2 -mno-avx512f -fcf-protection=branch -fno-jump-tables -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mstack-alignment=8 -mskip-rax-setup -march=znver4 -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O3 -fstack-protector-strong -ftrivial-auto-var-init=zero -fno-stack-clash-protection -pg -mfentry -DCC_USING_NOP_MCOUNT -DCC_USING_FENTRY -falign-functions=16 -fstrict-flex-arrays=3 -fno-tree-vectorize -fno-strict-overflow -fno-stack-check -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wframe-larger-than=2048 -Wno-gnu -Wno-unused-but-set-variable -Wno-unused-const-variable -Wvla -Wno-pointer-sign -Wcast-function-type -Wimplicit-fallthrough -Werror=date-time -Werror=incompatible-pointer-types -Wenum-conversion -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-format-overflow -Wno-format-truncation -Wno-pointer-to-enum-cast -Wno-tautological-constant-out-of-range-compare -Wno-unaligned-access -Wno-cast-function-type-strict -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-initializer-overrides -Wno-sign-compare -g -gdwarf-5 -DKBUILD_MODFILE=\"net/ipv6/ipv6\" -DKBUILD_BASENAME=\"ip6_input\" -DKBUILD_MODNAME=\"ipv6\" -D__KBUILD_MODNAME=kmod_ipv6 -c -o net/ipv6/ip6_input.o net/ipv6/ip6_input.c
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'net/ipv6/ip6_input.c'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
 #0 0x00007db93c3a6ea3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM.so.18.1+0x7bfea3)
 #1 0x00007db93c3a3ebf llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM.so.18.1+0x7bcebf)
 #2 0x00007db93c292df9 (/usr/lib/libLLVM.so.18.1+0x6abdf9)
 #3 0x00007db93b76eb30 (/usr/lib/libc.so.6+0x41b30)
 #4 0x00007db93b7c9b5b pthread_kill (/usr/lib/libc.so.6+0x9cb5b)
 #5 0x00007db93b76ea88 raise (/usr/lib/libc.so.6+0x41a88)
 #6 0x00007db93b751478 abort (/usr/lib/libc.so.6+0x24478)
 #7 0x00007db93ba222d2 (/usr/lib/libstdc++.so.6+0xed2d2)
 #8 0x00007db93ce647e0 llvm::ScheduleDAGSDNodes::AddSchedEdges() (/usr/lib/libLLVM.so.18.1+0x127d7e0)
 #9 0x00007db93ce5c0de (/usr/lib/libLLVM.so.18.1+0x12750de)
#10 0x00007db93cf43ba5 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/libLLVM.so.18.1+0x135cba5)
#11 0x00007db93cf46cd5 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/libLLVM.so.18.1+0x135fcd5)
#12 0x00007db93cf48cc4 (/usr/lib/libLLVM.so.18.1+0x1361cc4)
#13 0x00007db9403d9f97 (/usr/lib/libLLVM.so.18.1+0x47f2f97)
#14 0x00007db93c8ece27 (/usr/lib/libLLVM.so.18.1+0xd05e27)
#15 0x00007db93c564c57 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/libLLVM.so.18.1+0x97dc57)
#16 0x00007db93c564da4 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x97dda4)
#17 0x00007db93c5656cc llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x97e6cc)
#18 0x00007db945019444 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/usr/lib/libclang-cpp.so.18.1+0x14b9444)
#19 0x00007db94538178f clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/lib/libclang-cpp.so.18.1+0x182178f)
#20 0x00007db9440d5cba clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/libclang-cpp.so.18.1+0x575cba)
#21 0x00007db945abfb79 clang::FrontendAction::Execute() (/usr/lib/libclang-cpp.so.18.1+0x1f5fb79)
#22 0x00007db945a64d2f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.18.1+0x1f04d2f)
#23 0x00007db945b1203e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/libclang-cpp.so.18.1+0x1fb203e)
#24 0x000056d9b3381f4f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-18+0xff4f)
#25 0x000056d9b3387a31 (/usr/bin/clang-18+0x15a31)
#26 0x00007db9457aa91d (/usr/lib/libclang-cpp.so.18.1+0x1c4a91d)
#27 0x00007db93c293257 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/libLLVM.so.18.1+0x6ac257)
#28 0x00007db9457afbe4 (/usr/lib/libclang-cpp.so.18.1+0x1c4fbe4)
#29 0x00007db94578aa81 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/libclang-cpp.so.18.1+0x1c2aa81)
#30 0x00007db94578ae3d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/lib/libclang-cpp.so.18.1+0x1c2ae3d)
#31 0x00007db945793394 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/lib/libclang-cpp.so.18.1+0x1c33394)
#32 0x000056d9b338a239 clang_main(int, char**, llvm::ToolContext const&) (/usr/bin/clang-18+0x18239)
#33 0x000056d9b337cecc main (/usr/bin/clang-18+0xaecc)
#34 0x00007db93b753010 (/usr/lib/libc.so.6+0x26010)
#35 0x00007db93b7530ca __libc_start_main (/usr/lib/libc.so.6+0x260ca)
#36 0x000056d9b337cf25 _start (/usr/bin/clang-18+0xaf25)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 18.1.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/sbin
  CC      kernel/module/strict_rwx.o
  CC [M]  drivers/regulator/88pm800-regulator.o
  CC      drivers/xen/xenbus/xenbus_dev_frontend.o
  CC      fs/verity/read_metadata.o
  CC      drivers/acpi/acpica/exdebug.o
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/ip6_input-d5bfe6.c
clang: note: diagnostic msg: /tmp/ip6_input-d5bfe6.sh
clang: note: diagnostic msg: 

********************
  CC [M]  drivers/regulator/88pm8607.o
make[4]: *** [scripts/Makefile.build:243: net/ipv6/ip6_input.o] Error 1
```

**Comment by ptr1337** [comment] 2024-02-28 21:32
-march=x86-64-v3 and no LTO - no issues

**Comment by ptr1337** [comment] 2024-02-28 21:42
The issue is also reproduceable by simply adding:
```
    export KCFLAGS=' -march=znver4 -mtune=znver4'
    export KCPPFLAGS=' -march=znver4 -mtune=znver4'
```

**Comment by MrDuartePT** [comment] 2024-02-29 16:16
> The issue is also reproduceable by simply adding:
> 
> ```
>     export KCFLAGS=' -march=znver4 -mtune=znver4'
>     export KCPPFLAGS=' -march=znver4 -mtune=znver4'
> ```

Yes I also notice using generic is fine. Only happen when using the processor flag at least only on ryzen for now. I don’t have latest Intel to test (the latest Intel I have is a MacBook Pro 2015). I can try but compile the kernel there would take a bit.

**Comment by ptr1337** [comment] 2024-02-29 16:17
> > The issue is also reproduceable by simply adding:
> > ```
> >     export KCFLAGS=' -march=znver4 -mtune=znver4'
> >     export KCPPFLAGS=' -march=znver4 -mtune=znver4'
> > ```
> 
> Yes I also notice using generic is fine. Only happen when using the processor flag at least only on ryzen for now. I don’t have latest Intel to test (the latest Intel I have is a MacBook Pro 2015). I can try but compile the kernel there would take a bit.

We have tested it with raptorlake and it doesnt seem to have this issue.

**Comment by MrDuartePT** [comment] 2024-02-29 16:19
Ok we can say it ryzen then.

**Comment by nathanchance** [comment] 2024-03-01 17:44
This is a duplicate of https://github.com/llvm/llvm-project/issues/72026.

**Closed** 2024-03-11 17:09 UTC
Labels: duplicate, backend:X86, crash, LTO, llvm:SelectionDAG
