### ISSUE TITLE
clang-tidy crash with Assertion `0 && "Invalid SLocOffset or bad function choice"' failed

### ISSUE THREAD

**Issue by jackua22** [llvm/llvm-project#89520] opened 2024-04-20 23:14 UTC
clang-tidy llvm-v18.1.4 crashes with similar stacks but different headers, see three attachments.
[ua_Compiler_sideFile_src_swfvDB.C.log](https://github.com/llvm/llvm-project/files/15050007/ua_Compiler_sideFile_src_swfvDB.C.log)
[ua_Debug_uart_src_uart_ckpt_sr.C.log](https://github.com/llvm/llvm-project/files/15050008/ua_Debug_uart_src_uart_ckpt_sr.C.log)
[ua_Jupiter_beDB_src_ffDB.C.log](https://github.com/llvm/llvm-project/files/15050009/ua_Jupiter_beDB_src_ffDB.C.log)

**Comment by EugeneZelenko** [comment] 2024-04-21 01:41
@jackua22: Could you please provide reproducer?

**Comment by jackua22** [comment] 2024-04-22 01:04
I reproduced the issue with one line
`#include <sparsehash/dense_hash_map>`
The header is from here:
https://github.com/sparsehash/sparsehash/releases/tag/sparsehash-2.0.4

To reproduce:
```
/grid/common/test/llvm-v18.1.4d1rh74_lnx86/bin/clang -c -std=c++17 -stdlib=libc++ -O3 -I/grid/cva/p4/eugene/z1/ua/3party/sparsehash/include tmp.cpp

/grid/common/test/llvm-v18.1.4d1rh74_lnx86/bin/clang-tidy '--checks=-*,modernize-loop-convert,modernize-make-shared,modernize-make-unique,readability-duplicate-include' -- -std=c++17 -stdlib=libc++ -I/grid/cva/p4/eugene/z1/ua/3party/sparsehash/include
```
The first command is to prove that the code is compilable, and the second reproduces the crash.
The crash is from readability-duplicate-include, but the first three checks change the depth of the crash stack (any of them), which requires some attention too.

**Comment by FruitClover** [comment] 2024-04-22 19:08
Could you try with https://github.com/llvm/llvm-project/pull/87433? Looks similar to https://github.com/llvm/llvm-project/issues/87303

**Comment by jackua22** [comment] 2024-04-22 19:25
I think we have a patch for #87433.

**Comment by FruitClover** [comment] 2024-04-22 20:18
> I think we have a patch for #87433.

Hm, I don't see any tags at https://github.com/llvm/llvm-project/commit/ed4e505c219fe6c7464ea5a056e90d8cd94c7332 commit, and https://github.com/llvm/llvm-project/blob/llvmorg-18.1.4/clang-tools-extra/clang-tidy/readability/DuplicateIncludeCheck.cpp in 18.1.4 has no such patch, so looks like it's not included in mentioned binaries

**Comment by PiotrZSL** [comment] 2024-04-22 21:46
This change were delivered only to main branch.

**Comment by jackua22** [comment] 2024-04-23 17:44
The main branch is for 18.2, 19.1 or 20.1?  And, is it truly the same as another?  I spent hours creating a minimal test case, as I was asked to do.  I suspect trying my case is faster than applying a patch and rebuilding LLVM in our house.

**Comment by PiotrZSL** [comment] 2024-04-23 17:52
main branch is for 19 and above

**Comment by jackua22** [comment] 2024-04-23 19:00
Our support rebuilt LLVM 18.1.4 with the patch.  No crash.

**Comment by FruitClover** [comment] 2024-04-26 00:17
I guess we could close this one.

**Closed by FruitClover** 2024-04-26 00:17 UTC
Labels: duplicate, clang-tidy, crash
