### ISSUE TITLE
Clang doesn't properly handle the template partial specialization based on the concept initialized by the lambda

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#55580] opened 2022-05-19 07:17 UTC
Although I seriously doubt this has been reported before.

```cpp
template<class>
concept C = [] { return true; } ();

template<class T>
struct S {};

template<class T>
  requires C<T>
struct S<T> { constexpr static bool value = true; };

static_assert(S<int>::value);
```
https://godbolt.org/z/oTGW71zTh

**Comment by royjacobson** [comment] 2022-05-21 17:25
This seems like a duplicate of #54380 (and not specific to template specialization), so I'm closing this.

**Closed by royjacobson** 2022-05-21 17:25 UTC
Labels: clang:frontend, concepts
