### ISSUE TITLE
C++17 leads to linker error with `ld` due to some strange debug info?

### ISSUE THREAD

**Issue by tru** [llvm/llvm-project#56994] opened 2022-08-08 06:04 UTC
As noted in the diff for the C++17 standards upgrade there has been some strange issues after we enabled C++17 with some configurations - this one reported by @dyung 

https://reviews.llvm.org/D130689#3705474

```console
[165/1101] Generating GwpAsan-x86_64-Test
FAILED: projects/compiler-rt/lib/gwp_asan/tests/GwpAsan-x86_64-Test 
cd /var/lib/buildbot/workers/suse-gary-m68k-cross/clang-m68k-linux-cross/stage1/projects/compiler-rt/lib/gwp_asan/tests && /var/lib/buildbot/workers/suse-gary-m68k-cross/clang-m68k-linux-cross/stage1/./bin/clang++ GwpAsanTestObjects.printf_sanitizer_common.cpp.x86_64.o GwpAsanTestObjects.alignment.cpp.x86_64.o GwpAsanTestObjects.backtrace.cpp.x86_64.o GwpAsanTestObjects.basic.cpp.x86_64.o GwpAsanTestObjects.compression.cpp.x86_64.o GwpAsanTestObjects.iterate.cpp.x86_64.o GwpAsanTestObjects.crash_handler_api.cpp.x86_64.o GwpAsanTestObjects.driver.cpp.x86_64.o GwpAsanTestObjects.mutex_test.cpp.x86_64.o GwpAsanTestObjects.slot_reuse.cpp.x86_64.o GwpAsanTestObjects.thread_contention.cpp.x86_64.o GwpAsanTestObjects.harness.cpp.x86_64.o GwpAsanTestObjects.enable_disable.cpp.x86_64.o GwpAsanTestObjects.late_init.cpp.x86_64.o GwpAsanTestObjects.options.cpp.x86_64.o GwpAsanTestObjects.gtest-all.cc.x86_64.o /var/lib/buildbot/workers/suse-gary-m68k-cross/clang-m68k-linux-cross/stage1/projects/compiler-rt/lib/gwp_asan/tests/libRTGwpAsanTest.x86_64.a -o /var/lib/buildbot/workers/suse-gary-m68k-cross/clang-m68k-linux-cross/stage1/projects/compiler-rt/lib/gwp_asan/tests/./GwpAsan-x86_64-Test -ldl -lstdc++ --driver-mode=g++ -pthread -m64
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
GwpAsanTestObjects.backtrace.cpp.x86_64.o: in function `Backtrace_ExceedsStorableLength_Test::TestBody()':
backtrace.cpp:(.text+0xca6): undefined reference to `gwp_asan::AllocationMetadata::kMaxTraceLengthToCollect'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

bot that's failing: https://lab.llvm.org/staging/#/builders/180/builds/7174

This seems like enabling c++17 makes clang emit some kind of DWARF info that's not handled correctly by `ld`?

This is a bit outside my expertise - so maybe we can get some help to fix this issue?

CC @MaskRay for linker stuff and @dwblaikie for DWARF knowledge.

**Comment by nikic** [comment] 2022-08-08 09:47
The DWARF error message sounds like typical too old binutils that does not support (clang's) DWARF 5.

The undefined reference might be somehow related to C++17 inline variables. It's a `static constexpr` (which is now implicitly inline) with a definition in common.cpp, and I have no idea what that even means anymore.

**Comment by MaskRay** [comment] 2022-08-08 18:02
In my `-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_{EXE,SHARED}_LINKER_FLAGS=-fuse-ld=bfd` build, `ninja check-gwp_asan` passes. I cannot reproduce the failure.

`DWARF error: invalid or unhandled FORM value: 0x23` has been worked around by the latest GNU ld (
https://sourceware.org/bugzilla/show_bug.cgi?id=29424 milestone: 2.39, may be back ported to the 2.38 branch). I don't know when the diagnostic triggers. There are some notes on https://reviews.llvm.org/D130566 that it appears to trigger on Sparc, but not other ports.

**Comment by dyung** [comment] 2022-08-08 18:42
I can reproduce the failure on my linux box running ubuntu 20.04.4 LTS x86_64 which has gcc 9.4.0 and ld 2.34. Our internal build bot is running an older version, Ubuntu 18.04.5 LTS x86_64 with gcc 7.5.0 and ld 2.30.

**Comment by tru** [comment] 2022-08-08 19:28
> I can reproduce the failure on my linux box running ubuntu 20.04.4 LTS x86_64 which has gcc 9.4.0 and ld 2.34. Our internal build bot is running an older version, Ubuntu 18.04.5 LTS x86_64 with gcc 7.5.0 and ld 2.30.

Can you post your cmake config line?

**Comment by dyung** [comment] 2022-08-08 19:33
> > I can reproduce the failure on my linux box running ubuntu 20.04.4 LTS x86_64 which has gcc 9.4.0 and ld 2.34. Our internal build bot is running an older version, Ubuntu 18.04.5 LTS x86_64 with gcc 7.5.0 and ld 2.30.
> 
> Can you post your cmake config line?

Sure, here is what I am using:
```
cmake -G Ninja -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DLLVM_USE_LINKER=gold -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_VERSION_SUFFIX= -DLLVM_BUILD_RUNTIME=ON "-DLLVM_LIT_ARGS=--verbose --no-progress-bar --xunit-xml-output=xunit.xml --max-tests=10" -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_TESTS=ON "-DLLVM_ENABLE_PROJECTS=clang;compiler-rt" /home/dyung/src/git/merge/llvm
```
(Our normal build doesn't usually use the -DCMAKE_CXX_STANDARD flag, but I've been using it to test stuff, but it shouldn't matter if you build a commit after your change.)

**Comment by dyung** [comment] 2022-08-08 19:35
I've tried an experiment where I force dwarf version 4 debug info by adding `-fdebug-default-version=4` to compiler-rt/lib/gwp_asan/tests/CMakeLists.txt, but the link still fails when compiled with C++17:
```
FAILED: projects/compiler-rt/lib/gwp_asan/tests/GwpAsan-x86_64-Test 
cd /home/dyung/src/git/merge/build_test/projects/compiler-rt/lib/gwp_asan/tests && /home/dyung/src/git/merge/build_test/./bin/clang++ GwpAsanTestObjects.printf_sanitizer_common.cpp.x86_64.o GwpAsanTestObjects.alignment.cpp.x86_64.o GwpAsanTestObjects.backtrace.cpp.x86_64.o GwpAsanTestObjects.basic.cpp.x86_64.o GwpAsanTestObjects.compression.cpp.x86_64.o GwpAsanTestObjects.iterate.cpp.x86_64.o GwpAsanTestObjects.crash_handler_api.cpp.x86_64.o GwpAsanTestObjects.driver.cpp.x86_64.o GwpAsanTestObjects.mutex_test.cpp.x86_64.o GwpAsanTestObjects.slot_reuse.cpp.x86_64.o GwpAsanTestObjects.thread_contention.cpp.x86_64.o GwpAsanTestObjects.harness.cpp.x86_64.o GwpAsanTestObjects.enable_disable.cpp.x86_64.o GwpAsanTestObjects.late_init.cpp.x86_64.o GwpAsanTestObjects.options.cpp.x86_64.o GwpAsanTestObjects.gtest-all.cc.x86_64.o /home/dyung/src/git/merge/build_test/projects/compiler-rt/lib/gwp_asan/tests/libRTGwpAsanTest.x86_64.a -o /home/dyung/src/git/merge/build_test/projects/compiler-rt/lib/gwp_asan/tests/./GwpAsan-x86_64-Test -ldl -lstdc++ --driver-mode=g++ -pthread -m64
/usr/bin/ld: GwpAsanTestObjects.backtrace.cpp.x86_64.o: in function `testing::AssertionResult testing::internal::CmpHelperEQ<unsigned long, unsigned long>(char const*, char const*, unsigned long const&, unsigned long const&)':
/home/dyung/src/git/merge/llvm/utils/unittest/googletest/include/gtest/gtest.h:1530: undefined reference to `gwp_asan::AllocationMetadata::kMaxTraceLengthToCollect'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MaskRay** [comment] 2022-08-08 20:10
I suspect some GCC versions don't produce a definition for `static constexpr size_t kMaxTraceLengthToCollect = 128;` (inline in C++17) when it is odr-used by `compiler-rt/lib/gwp_asan/tests/backtrace.cpp`. Can you check whether a cast works around the bug?

```patch
--- i/compiler-rt/lib/gwp_asan/tests/backtrace.cpp
+++ w/compiler-rt/lib/gwp_asan/tests/backtrace.cpp
@@ -92,7 +92,7 @@ TEST(Backtrace, ExceedsStorableLength) {
       });
   // Retrieve a frame from the collected backtrace, make sure it works E2E.
   uintptr_t TraceOutput;
-  EXPECT_EQ(gwp_asan::AllocationMetadata::kMaxTraceLengthToCollect,
+  EXPECT_EQ(static_cast<size_t>(gwp_asan::AllocationMetadata::kMaxTraceLengthToCollect),
             __gwp_asan_get_allocation_trace(&Meta, &TraceOutput, 1));
 }
 ```

**Comment by dyung** [comment] 2022-08-08 22:01
> For `` backtrace.cpp:(.text+0xca6): undefined reference to `gwp_asan::AllocationMetadata::kMaxTraceLengthToCollect' ``, I suspect some GCC versions don't produce a definition for `static constexpr size_t kMaxTraceLengthToCollect = 128;` (inline in C++17) when it is odr-used (e.g. by `compiler-rt/lib/gwp_asan/tests/backtrace.cpp`). Can you check whether a cast works around the bug?
> 
> ```diff
> --- i/compiler-rt/lib/gwp_asan/tests/backtrace.cpp
> +++ w/compiler-rt/lib/gwp_asan/tests/backtrace.cpp
> @@ -92,7 +92,7 @@ TEST(Backtrace, ExceedsStorableLength) {
>        });
>    // Retrieve a frame from the collected backtrace, make sure it works E2E.
>    uintptr_t TraceOutput;
> -  EXPECT_EQ(gwp_asan::AllocationMetadata::kMaxTraceLengthToCollect,
> +  EXPECT_EQ(static_cast<size_t>(gwp_asan::AllocationMetadata::kMaxTraceLengthToCollect),
>              __gwp_asan_get_allocation_trace(&Meta, &TraceOutput, 1));
>  }
> ```
> 
> For the DWARF issue, I guess you may have to configure llvm-project with `-DLLVM_ENABLE_LLD=on`, or downgrade to DWARF v4.

This change seems to work around the issue! If I just apply this change, I no longer get the LD error about invalid DWARF or an undefined reference. Could you submit this fix?

**Comment by MaskRay** [comment] 2022-08-08 23:25
An alternative fix (by updating `CMakeLists.txt`) is https://reviews.llvm.org/D131440 , which may be fore future-proof.

**Comment by dyung** [comment] 2022-08-08 23:55
> An alternative fix (by updating `CMakeLists.txt`) is https://reviews.llvm.org/D131440 , which may be more future-proof.

I'll try it.

**Comment by dyung** [comment] 2022-08-09 00:45
> > An alternative fix (by updating `CMakeLists.txt`) is https://reviews.llvm.org/D131440 , which may be more future-proof.
> 
> I'll try it.

It worked! I'll approve your patch.

**Comment by MaskRay** [comment] 2022-08-09 00:53
Hopefully fixed by 474145c0b2420cb316bb8a9dcc031d613679d496

It's really strange if `DWARF error: invalid or unhandled FORM value: 0x23` goes away with `-std=c++17`...

**Closed** 2022-08-09 00:53 UTC
Labels: compiler-rt:asan, build-problem

**Comment by dfaure-kdab** [comment] 2024-08-23 17:36
That error doesn't just go away with `-std=c++17`.

`/usr/bin/clang++-15 -fPIC -ftime-trace -stdlib=libc++ -std=c++17  -g  -Wl,--fatal-warnings -Wl,--no-undefined -lc -shared -Wl,-soname,libkdsingleapplication-qt6.so.1.1 -o bin/libkdsingleapplication-qt6.so.1.1.1 3rdparty/KDSingleApplication/src/CMakeFiles/kdsingleapplication.dir/kdsingleapplication_autogen/mocs_compilation.cpp.o 3rdparty/KDSingleApplication/src/CMakeFiles/kdsingleapplication.dir/kdsingleapplication.cpp.o 3rdparty/KDSingleApplication/src/CMakeFiles/kdsingleapplication.dir/kdsingleapplication_localsocket.cpp.o  -Wl,-rpath,/d/qt/6/inst/lib:::::::::::::::  /d/qt/6/inst/lib/libQt6Network.so.6.8.0  /d/qt/6/inst/lib/libQt6Core.so.6.8.0`
`/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23`

Adding `-fuse-ld=mold` (or gold) to that link line gets rid of the DWARF error.

I'm still getting undefined symbols to symbols like `QLockFile::tryLock(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >)`
I guess that's because I'm mixing libstdc++ and libc++.

Maybe this helps - my main point was that `-std=c++17` doesn't always get rid of that error.

**Comment by MaskRay** [comment] 2024-08-23 18:23
> That error doesn't just go away with `-std=c++17`.
> 
> `/usr/bin/clang++-15 -fPIC -ftime-trace -stdlib=libc++ -std=c++17 -g -Wl,--fatal-warnings -Wl,--no-undefined -lc -shared -Wl,-soname,libkdsingleapplication-qt6.so.1.1 -o bin/libkdsingleapplication-qt6.so.1.1.1 3rdparty/KDSingleApplication/src/CMakeFiles/kdsingleapplication.dir/kdsingleapplication_autogen/mocs_compilation.cpp.o 3rdparty/KDSingleApplication/src/CMakeFiles/kdsingleapplication.dir/kdsingleapplication.cpp.o 3rdparty/KDSingleApplication/src/CMakeFiles/kdsingleapplication.dir/kdsingleapplication_localsocket.cpp.o -Wl,-rpath,/d/qt/6/inst/lib::::::::::::::: /d/qt/6/inst/lib/libQt6Network.so.6.8.0 /d/qt/6/inst/lib/libQt6Core.so.6.8.0` `/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23`
> 
> Adding `-fuse-ld=mold` (or gold) to that link line gets rid of the DWARF error.
> 
> I'm still getting undefined symbols to symbols like `QLockFile::tryLock(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >)` I guess that's because I'm mixing libstdc++ and libc++.
> 
> Maybe this helps - my main point was that `-std=c++17` doesn't always get rid of that error.

`DWARF error: invalid or unhandled FORM value: 0x23`

It's better to report the issue on sourceware.org binutils. GNU ld tries to parse DWARF and it had many issues with DWARF v5 features. There is generally nothing LLVM can do.
