### ISSUE TITLE
Ubuntu package set as LLVM 11.1.0, but LLVM 11.1.0 not yet released.

### ISSUE THREAD

**Issue by banach-space** [llvm/llvm-project#48116] opened 2021-01-16 13:56 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [48772](https://llvm.org/bz48772) |
| Version | unspecified |
| OS | Linux |

## Extended Description 
Hi,

I've just noticed that LLVM 11 packages for Ubuntu Bionic have recently switched from `LLVM 11.0.0` to `LLVM 11.1.0`. As LLVM 11.1 has not been released yet (rc1 has just been tagged: https://lists.llvm.org/pipermail/llvm-dev/2021-January/147827.html), I assume that this is a bug.

It's quite problematic for me - I maintain a downstream project (*) that is based on LLVM 11.0.0 and currently I am not able to build it against the binary packages for Ubuntu Bionic.

HOW TO REPRODUCE:
```
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main"
sudo apt-get update
sudo apt-get install -y llvm-11 llvm-11-dev clang-11 llvm-11-tools
cat /usr/lib/llvm-11/lib/cmake/llvm/LLVMConfigVersion.cmake
set(PACKAGE_VERSION "11.1.0")

# (...) other output
```

WHEN IT STARTED FAILING:
My most recent successful CI job for this is from 5/1/2021. Today is 16/1/2021. So this change happened somewhere in that 11 day window.

EXPECTED BEHAVIOUR:
As LLVM 11.0.0 and LLVM 11.1.0 will be ABI incompatible (https://lists.llvm.org/pipermail/llvm-dev/2021-January/147599.html), I would expect there to be separate packages for both. 

Thank you for working on this!
-Andrzej

(*) https://github.com/banach-space/llvm-tutor

**Comment by sylvestre** [comment] 2021-12-14 21:53
dupe of
https://github.com/llvm/llvm-project/issues/48159

**Closed by sylvestre** 2021-12-14 21:53 UTC
Labels: packaging, bugzilla
