### ISSUE TITLE
Hitting assert when using `-funsafe-math-optimizations`

### ISSUE THREAD

**Issue by Saldivarcher** [llvm/llvm-project#58475] opened 2022-10-19 16:58 UTC
An assertion was hit when compiling the simple testcase below:
```console
$ cat xxt.c
extern double pow(double __x, double __y);

int XXT_stats(int n) {
  double test = pow(n, 1.5);
  return 0;
}

$ clang -funsafe-math-optimizations -O2 -c xxt.c -o xxt.o
Attribute after last parameter!
  %sqrt = tail call reassoc nsz arcp afn double @sqrt(double noundef %conv) #1
in function XXT_stats
fatal error: error in backend: Broken function found, compilation aborted!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -funsafe-math-optimizations -O2 -c xxt.c -o xxt.o
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'xxt.c'.
4.      Running pass 'Module Verifier' on function '@XXT_stats'
 #0 0x000000000840f1f3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:22
 #1 0x000000000840f2b6 PrintStackTraceSignalHandler(void*) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x000000000840d0eb llvm::sys::RunSignalHandlers() /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Signals.cpp:104:20
 #3 0x000000000840eb1f llvm::sys::CleanupOnSignal(unsigned long) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Unix/Signals.inc:361:31
 #4 0x000000000832eef1 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:77:5
 #5 0x000000000832f60b llvm::CrashRecoveryContext::HandleExit(int) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:450:3
 #6 0x0000000008408b2f llvm::sys::Process::Exit(int, bool) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Process.cpp:99:3
 #7 0x00000000067002d3 ensureStackAddressSpace() /home/users/saldivar/workspace/random/llvm-project/clang/tools/driver/cc1_main.cpp:132:39
 #8 0x0000000008336e87 llvm::report_fatal_error(llvm::Twine const&, bool) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/ErrorHandling.cpp:104:36
 #9 0x0000000008336d98 llvm::report_fatal_error(llvm::StringRef, bool) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/ErrorHandling.cpp:86:68
#10 0x0000000007a54477 (anonymous namespace)::VerifierLegacyPass::runOnFunction(llvm::Function&) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/IR/Verifier.cpp:6322:12
#11 0x0000000007978b2b llvm::FPPassManager::runOnFunction(llvm::Function&) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1430:20
#12 0x0000000007978d9b llvm::FPPassManager::runOnModule(llvm::Module&) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1476:13
#13 0x00000000079791c2 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1545:20
#14 0x00000000079745c4 llvm::legacy::PassManagerImpl::run(llvm::Module&) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:535:13
#15 0x00000000079799e5 llvm::legacy::PassManager::run(llvm::Module&) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1673:1
#16 0x0000000009238961 (anonymous namespace)::EmitAssemblyHelper::RunCodegenPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>&) /home/users/saldivar/workspace/random/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1055:3
#17 0x0000000009238b38 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) /home/users/saldivar/workspace/random/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1078:7
#18 0x0000000009239a6c clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) /home/users/saldivar/workspace/random/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1234:25
#19 0x000000000988df5a clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/users/saldivar/workspace/random/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:381:24
#20 0x000000000bb9d35d clang::ParseAST(clang::Sema&, bool, bool) /home/users/saldivar/workspace/random/llvm-project/clang/lib/Parse/ParseAST.cpp:203:14
#21 0x00000000096e6a23 clang::ASTFrontendAction::ExecuteAction() /home/users/saldivar/workspace/random/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1162:11
#22 0x000000000988a91f clang::CodeGenAction::ExecuteAction() /home/users/saldivar/workspace/random/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:1145:5
#23 0x00000000096e6379 clang::FrontendAction::Execute() /home/users/saldivar/workspace/random/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1059:38
#24 0x0000000009620da2 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/users/saldivar/workspace/random/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1043:42
#25 0x0000000009878cab clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/users/saldivar/workspace/random/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:266:38
#26 0x0000000006700b60 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/users/saldivar/workspace/random/llvm-project/clang/tools/driver/cc1_main.cpp:250:40
#27 0x00000000066f4121 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /home/users/saldivar/workspace/random/llvm-project/clang/tools/driver/driver.cpp:316:20
#28 0x00000000094e7a6d clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()::operator()() const /home/users/saldivar/workspace/random/llvm-project/clang/lib/Driver/Job.cpp:428:32
#29 0x00000000094e7fd2 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) /ptmp/saldivar/workspace/random/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:40
#30 0x0000000007038552 llvm::function_ref<void ()>::operator()() const /ptmp/saldivar/workspace/random/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:62
#31 0x000000000832f5a1 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:434:10
#32 0x00000000094e7c58 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const /home/users/saldivar/workspace/random/llvm-project/clang/lib/Driver/Job.cpp:428:7
#33 0x000000000948b13d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const /home/users/saldivar/workspace/random/llvm-project/clang/lib/Driver/Compilation.cpp:200:22
#34 0x000000000948b469 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const /home/users/saldivar/workspace/random/llvm-project/clang/lib/Driver/Compilation.cpp:254:62
#35 0x000000000949cdb6 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) /home/users/saldivar/workspace/random/llvm-project/clang/lib/Driver/Driver.cpp:1826:28
#36 0x00000000066f5588 clang_main(int, char**) /home/users/saldivar/workspace/random/llvm-project/clang/tools/driver/driver.cpp:513:39
#37 0x000000000671d4d1 main /ptmp/saldivar/workspace/random/llvm-project/build_debug/tools/clang/tools/driver/clang-driver.cpp:11:63
#38 0x00007faa3337234d __libc_start_main (/lib64/libc.so.6+0x2534d)
#39 0x00000000066f2a2a _start /home/abuild/rpmbuild/BUILD/glibc-2.31/csu/../sysdeps/x86_64/start.S:122:0
clang-16: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 16.0.0 (https://github.com/llvm/llvm-project.git dd38f899803465dd2765d1601b3989df3bd53863)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/users/saldivar/.local/bin
clang-16: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-16: note: diagnostic msg: /tmp/xxt-de7168.c
clang-16: note: diagnostic msg: /tmp/xxt-de7168.sh
clang-16: note: diagnostic msg: 

********************
```

I was able to track down where the optimization of `pow`->`sqrt` takes place, `Value *LibCallSimplifier::optimizePow(CallInst *Pow, IRBuilderBase &B)`, is the method in question. 

This is what the generation of the `sqrt` looks like in the method:
```c++
  Sqrt = getSqrtCall(Base, Pow->getCalledFunction()->getAttributes(),
                     Pow->doesNotAccessMemory(), M, B, TLI);
```

Here is the error and the check that's failing:
```console
Attribute after last parameter!
  %sqrt = tail call reassoc nsz arcp afn double @sqrt(double noundef %conv4) #1 
Function it's failing on:
```

```c++
bool Verifier::verifyAttributeCount(AttributeList Attrs, unsigned Params) {
  // There shouldn't be more attribute sets than there are parameters plus the
  // function and return value.
  return Attrs.getNumAttrSets() <= Params + 2;
}
```

It kinda seems like the attributes of `pow` shouldn't be given to the `sqrt`. I made some changes locally, and the changes I made seem ok testing wise. 

```diff
diff --git a/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp b/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
index 8f25e80a6c5a..c27ca32052dd 100644
--- a/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
+++ b/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
@@ -2099,6 +2099,7 @@ Value *LibCallSimplifier::optimizePow(CallInst *Pow, IRBuilderBase &B) {
   Module *M = Pow->getModule();
   bool AllowApprox = Pow->hasApproxFunc();
   bool Ignored;
+  AttributeList Attrs; // Attributes are only meaningful on the original call
 
   // Propagate the math semantics from the call to any created instructions.
   IRBuilderBase::FastMathFlagGuard Guard(B);
@@ -2160,8 +2161,7 @@ Value *LibCallSimplifier::optimizePow(CallInst *Pow, IRBuilderBase &B) {
         return nullptr;
       ExpoF = &ExpoI;
 
-      Sqrt = getSqrtCall(Base, Pow->getCalledFunction()->getAttributes(),
-                         Pow->doesNotAccessMemory(), M, B, TLI);
+      Sqrt = getSqrtCall(Base, Attrs, Pow->doesNotAccessMemory(), M, B, TLI);
       if (!Sqrt)
         return nullptr;
     }
```

If this seems ok, I can submit a patch to phabricator.

**Comment by fhahn** [comment] 2022-10-19 17:43
I think a good first step would be to extract an IR reproducer that just needs `opt` with a pass to crash.

**Comment by Saldivarcher** [comment] 2022-10-19 17:55
This is the IR reproducer I have:
```
$ cat xxt.ll 
; Function Attrs: nounwind uwtable
define dso_local i32 @XXT_stats(i32 noundef %n) local_unnamed_addr #0 {
entry:
  %conv = sitofp i32 %n to double
  %call = call reassoc nsz arcp afn double @pow(double noundef %conv, double noundef 1.500000e+00) #2
  ret i32 0
}

; Function Attrs: mustprogress nofree nounwind willreturn writeonly
declare double @pow(double noundef, double noundef) local_unnamed_addr #1

attributes #0 = { nounwind uwtable "approx-func-fp-math"="true" "denormal-fp-math"="preserve-sign,preserve-sign" "frame-pointer"="none" "min-legal-vector-width"="0" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" "unsafe-fp-math"="true" }
attributes #1 = { mustprogress nofree nounwind willreturn writeonly "approx-func-fp-math"="true" "denormal-fp-math"="preserve-sign,preserve-sign" "frame-pointer"="none" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" "unsafe-fp-math"="true" }
attributes #2 = { nounwind }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{!"clang version 16.0.0 (https://github.com/llvm/llvm-project.git dd38f899803465dd2765d1601b3989df3bd53863)"}

$ opt -instcombine xxt.ll -disable-output
Attribute after last parameter!
  %sqrt = call reassoc nsz arcp afn double @sqrt(double noundef %conv) #1
LLVM ERROR: Broken module found, compilation aborted!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: opt -instcombine xxt.ll -disable-output
 #0 0x00000000052d43d3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:22
 #1 0x00000000052d4496 PrintStackTraceSignalHandler(void*) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x00000000052d22cb llvm::sys::RunSignalHandlers() /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Signals.cpp:104:20
 #3 0x00000000052d3df1 SignalHandler(int) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f824e31f050 __restore_rt (/lib64/libpthread.so.0+0x14050)
 #5 0x00007f824cd9d18b raise (/lib64/libc.so.6+0x3a18b)
 #6 0x00007f824cd9e585 abort (/lib64/libc.so.6+0x3b585)
 #7 0x00000000051faa5a llvm::report_fatal_error(llvm::Twine const&, bool) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/ErrorHandling.cpp:125:9
 #8 0x00000000051fa878 llvm::report_fatal_error(llvm::StringRef, bool) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/Support/ErrorHandling.cpp:86:68
 #9 0x00000000048785a5 llvm::VerifierPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /ptmp/saldivar/workspace/random/llvm-project/llvm/lib/IR/Verifier.cpp:6711:33
#10 0x000000000330ff4e llvm::detail::PassModel<llvm::Module, llvm::VerifierPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /ptmp/saldivar/workspace/random/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:89:3
#11 0x00000000048083a0 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /ptmp/saldivar/workspace/random/llvm-project/llvm/include/llvm/IR/PassManager.h:521:32
#12 0x00000000032ee058 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool) /ptmp/saldivar/workspace/random/llvm-project/llvm/tools/opt/NewPMDriver.cpp:497:10
#13 0x0000000003319a9c main /ptmp/saldivar/workspace/random/llvm-project/llvm/tools/opt/opt.cpp:784:27
#14 0x00007f824cd8834d __libc_start_main (/lib64/libc.so.6+0x2534d)
#15 0x00000000032e77aa _start /home/abuild/rpmbuild/BUILD/glibc-2.31/csu/../sysdeps/x86_64/start.S:122:0
fish: Job 1, 'opt -instcombine xxt.ll -disabl…' terminated by signal SIGABRT (Abort)

$
```

**Comment by Saldivarcher** [comment] 2022-11-02 21:56
@fhahn any thoughts on this? :)

**Comment by rotateright** [comment] 2022-11-04 17:34
The patch seems good - can you post it to Phab along with the reduced IR test (can remove at least some of the attributes and still show a crash)?

**Comment by rotateright** [comment] 2022-11-04 17:42
Seems like the critical part is that the function declaration for `pow` has parameter attrs (those can't be transferred if we convert to `sqrt` because it only has 1 param), so this is enough to crash:

```ll
define void @PR58475(i32 %n) {
  %conv = sitofp i32 %n to double
  %call = call afn double @pow(double %conv, double 1.5)
  ret void
}

declare double @pow(double noundef, double noundef)

```

**Comment by Saldivarcher** [comment] 2022-11-04 17:50
@rotateright thanks for taking a look, let me create a patch on Phabricator. I'll add the reduced testcase you created as well.

**Comment by rotateright** [comment] 2022-11-07 17:27
Thanks for the analysis and patch!

**Closed by rotateright** 2022-11-07 17:27 UTC
Labels: llvm:optimizations, crash

**Comment by Saldivarcher** [comment] 2022-11-07 18:39
@rotateright no problem. I appreciate your help and feedback as well! Thank you :)
