### ISSUE TITLE
support for polymorphic types

### ISSUE THREAD

**Issue by mfvalin** [llvm/llvm-project#60316] opened 2023-01-26 16:16 UTC
compiler crashed with message
/dataCMC/my-llvm/flang/lib/Lower/CallInterface.cpp:854: not yet implemented: support for polymorphic types

is there a timeline estimate for said support (as well as C_LOC, LOC, ...  support) ?
simple demo code :
```
module demo
  use ISO_C_BINDING
  implicit none
  interface
    subroutine BeStreamInit(stream, buffer) bind(C, name='BeStreamInit')
      import :: C_PTR
      implicit none
      type(C_PTR), intent(IN), value :: stream, buffer
    end subroutine
  end interface
  type :: c_bitstream
    integer(C_INT64_T) :: accum
  end type
  type :: le_stream
    type(c_bitstream) :: s
  contains
    procedure, PASS :: create => stream_create_le
  end type
contains
subroutine stream_create_le(self, mem)
  implicit none
  class(le_stream), intent(INOUT) :: self
  integer(C_INT32_T), dimension(*), intent(IN), target :: mem
  type(C_PTR) :: t, m
  t = transfer( LOC(self%s) , t)
  m = C_LOC(mem)
  call BeStreamInit(t, m)
end subroutine
end 

```

**Comment by clementval** [comment] 2023-01-26 17:01
There is plenty of information given in the flang calls and on the RFC. Polymorphic entities development is on going on will likely be turned on by default in the next couple of weeks. 

Since this is not a bug I'll just close the issue.

**Closed by clementval** 2023-01-26 17:01 UTC
Labels: flang:ir

**Comment by jeffhammond** [comment] 2023-10-17 09:12
Any update here?  I built Flang from source this morning and the issue remains.

```
$ /opt/llvm/latest/bin/flang-new -c -fdefault-integer-8 -O3 ./object/mx_limits.F90 ./object/prec.F90 ./object/mod_grid_storage.F90
error: loc("/home/jehammond/GAMESS/gamess/object/mod_grid_storage.F90":3:2): /opt/llvm/git/flang/lib/Lower/CallInterface.cpp:904: not yet implemented: support for polymorphic types
LLVM ERROR: aborting
```

```
$ /opt/llvm/latest/bin/flang-new -v
flang-new version 18.0.0 (https://github.com/llvm/llvm-project.git bef3e8ea6d241a7e249410e85cff36cddfa98720)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/latest/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by clementval** [comment] 2023-10-17 15:46
You need an option to enable it `-flang-experimental-polymorphism`.
