### ISSUE TITLE
False positive unused-lambda-capture with if constexpr

### ISSUE THREAD

**Issue by chrchr-github** [llvm/llvm-project#63031] opened 2023-05-31 10:23 UTC
~~~c++
#include <type_traits>
#include <vector>
#include <algorithm>

template<typename T>
bool f(int j, std::vector<int>& v) {
  const bool b = j > 0;

  std::for_each(v.begin(), v.end(), [b](auto& i) {	
    if constexpr (std::is_same_v<T, int>) {
      i += i ? 5 : 7;
    }
    else if (b)
    {
      i += 1;
    }
  });
  return b;
}

void g(std::vector<int>& w) {
    f<int>(0, w);
}
~~~
~~~console
<source>:9:38: warning: lambda capture 'b' is not used [-Wunused-lambda-capture]
  std::for_each(v.begin(), v.end(), [b](auto& i) {      
                                     ^
<source>:22:5: note: in instantiation of function template specialization 'f<int>' requested here
    f<int>(0, w);
    ^
~~~
https://godbolt.org/z/4Ejczrv5n

The warning is correct on its face,  but not actionable.

**Comment by wheatman** [comment] 2023-11-04 18:26
duplicate of https://github.com/llvm/llvm-project/issues/34798

**Closed by wheatman** 2023-11-04 18:26 UTC
Labels: clang:diagnostics, false-positive
