### ISSUE TITLE
Wrong PHI simplification

### ISSUE THREAD

**Issue by bonjune** [llvm/llvm-project#98444] opened 2024-07-11 08:23 UTC
```ll
define i32 @fun0(i32 %val0, i32 %val1) {
entry:
  %val2 = icmp sle i32 %val1, 0
  br i1 %val2, label %end, label %rotbb

rotbb:                                            ; preds = %entry
  br label %end

end:                                              ; preds = %rotbb, %entry
  %val7 = phi i32 [ %val0, %entry ], [ undef, %rotbb ]
  ret i32 %val7
}
```

This function is miscompiled into

```ll
define i32 @fun0(i32 %val0, i32 %val1) {
entry:
  %val2 = icmp slt i32 %val1, 1
  br i1 %val2, label %end, label %rotbb

rotbb:
  br label %end

end:
  ret i32 %val0
}
```

Below is a part of LLVM DEBUG messages by `opt`.
```
IC: Visiting:   %val7 = phi i32 [ %val0, %entry ], [ undef, %rotbb ]
IC: Replacing   %val7 = phi i32 [ %val0, %entry ], [ undef, %rotbb ]
    with i32 %val0
IC: Mod =   %val7 = phi i32 [ %val0, %entry ], [ undef, %rotbb ]
    New =   %val7 = phi i32 [ %val0, %entry ], [ undef, %rotbb ]
IC: ERASE   %val7 = phi i32 [ %val0, %entry ], [ undef, %rotbb ]
```

Alive2 report: https://alive2.llvm.org/ce/z/txbbpc

```ll
Transformation doesn't verify!

ERROR: Target is more poisonous than source

Example:
i32 %val0 = poison
i32 %val1 = #x00000001 (1)

Source:
i1 %val2 = #x0 (0)
  >> Jump to %rotbb
  >> Jump to %end
i32 %val7 = #x00000000 (0)	[based on undef value]

Target:
i1 %val2 = #x0 (0)
  >> Jump to %rotbb
  >> Jump to %end
Source value: #x00000000 (0)
Target value: poison

Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

The simplifaction occurs by returning `CommonValue` by the source code below:

https://github.com/llvm/llvm-project/blob/d4e46f0e864e37085da0c5e56e4f6f278e2f7aee/llvm/lib/Analysis/InstructionSimplify.cpp#L5295-L5300

**Comment by nikic** [comment] 2024-07-15 09:30
Duplicate of https://github.com/llvm/llvm-project/issues/68683.

**Closed by nikic** 2024-07-15 09:30 UTC
Labels: miscompilation, llvm:optimizations
