### ISSUE TITLE
Can't take the address of a statement expression result

### ISSUE THREAD

**Issue by aalmkainzi** [llvm/llvm-project#75705] opened 2023-12-16 16:20 UTC
For example:

```C
int arr[5] = {1, 2, 3, 4, 5};

#define M() \
({ \
    arr[0]; \
})

int main()
{
    int *ptr = &M();
}
```

the above code doesn't compile with Clang, but compiles with GCC.

Tested with clang 17.0.1

**Comment by shafik** [comment] 2023-12-17 05:29
Duplicate of: https://github.com/llvm/llvm-project/issues/58361

**Closed by shafik** 2023-12-17 05:29 UTC
Labels: clang:frontend
