### ISSUE TITLE
CGPasses.h.inc: No such file or directory

### ISSUE THREAD

**Issue by hpcs-isaka** [llvm/llvm-project#54128] opened 2022-03-01 10:37 UTC
During the build process, I get interrupted with the error below.

```
[6150/7461] Building CXX object tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o
FAILED: tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o
/usr/bin/c++  -DFLANG_LITTLE_ENDIAN=1 -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/flang/lib/Frontend -I/app/setup/LLVM/13.0.1_20220301/llvm-project/flang/lib/Frontend -I/app/setup/LLVM/13.0.1_20220301/llvm-project/flang/include -Itools/flang/include -Iinclude -I/app/setup/LLVM/13.0.1_20220301/llvm-project/llvm/include -isystem /app/setup/LLVM/13.0.1_20220301/llvm-project/llvm/../mlir/include -isystem tools/mlir/include -isystem tools/clang/include -isystem /app/setup/LLVM/13.0.1_20220301/llvm-project/llvm/../clang/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-copy -fno-strict-aliasing -fno-semantic-interposition -O3 -DNDEBUG    -fno-exceptions -fno-rtti -std=c++17 -MD -MT tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o -MF tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o.d -o tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o -c /app/setup/LLVM/13.0.1_20220301/llvm-project/flang/lib/Frontend/FrontendActions.cpp
In file included from /app/setup/LLVM/13.0.1_20220301/llvm-project/flang/include/flang/Tools/CLOptions.inc:16,
                 from /app/setup/LLVM/13.0.1_20220301/llvm-project/flang/lib/Frontend/FrontendActions.cpp:404:
/app/setup/LLVM/13.0.1_20220301/llvm-project/flang/include/flang/Optimizer/CodeGen/CodeGen.h:51:10: fatal error: flang/Optimizer/CodeGen/CGPasses.h.inc: No such file or directory
   51 | #include "flang/Optimizer/CodeGen/CGPasses.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6165/7461] Building CXX object tools/mlir/test/lib/Dialect/Test/CMakeFiles/MLIRTestDialect.dir/TestDialect.cpp.o
In file included from /app/setup/LLVM/13.0.1_20220301/llvm-project/mlir/include/mlir/IR/OpImplementation.h:18,
                 from /app/setup/LLVM/13.0.1_20220301/llvm-project/mlir/include/mlir/IR/DialectImplementation.h:17,
                 from /app/setup/LLVM/13.0.1_20220301/llvm-project/mlir/test/lib/Dialect/Test/TestAttributes.h:23,
                 from /app/setup/LLVM/13.0.1_20220301/llvm-project/mlir/test/lib/Dialect/Test/TestDialect.h:17,
                 from /app/setup/LLVM/13.0.1_20220301/llvm-project/mlir/test/lib/Dialect/Test/TestDialect.cpp:9:
```

Where is the 'CGPasses.h.inc' file supplied from?

I would like help from anyone who knows the solution to this problem.

**Comment by banach-space** [comment] 2022-03-03 15:21
`CGPasses.h.inc` is generated during the build from [CGPasses.td](https://github.com/llvm/llvm-project/blob/main/flang/include/flang/Optimizer/CodeGen/CGPasses.td). This is most likely caused by a broken dependency. From your log, I can see that you are building LLVM 13. Could you try ToT or the LLVM 14 branch instead?

Thanks,
-Andrzej

**Comment by hpcs-isaka** [comment] 2022-03-07 10:27
I tried it with version 14.
Completed the build with no difficulty!
Thank you very much for your help!

**Comment by banach-space** [comment] 2022-03-07 10:32
Great, thanks for confirming! I'll close the issue then :)

**Closed by banach-space** 2022-03-07 10:32 UTC
Labels: build-problem, flang:build
