### ISSUE TITLE
segfault from `implicit instantiation of undefined template 'std::array<std::string, 3>'`

### ISSUE THREAD

**Issue by evanberkowitz** [llvm/llvm-project#54752] opened 2022-04-05 10:15 UTC
While attempting to compile [dict.cpp](https://github.com/evanberkowitz/llvm-segfault-dict/blob/main/dict.cpp) provided in [evanberkowitz/llvm-segfault-dict](https://github.com/evanberkowitz/llvm-segfault-dict) via `clang -std=c++20 dict.cpp` I get a failure via a segfault.

When following [the instructions to try to report a back-end bug](https://www.llvm.org/docs/HowToSubmitABug.html#backend-code-generator-bugs) I tried passing the `-emit-llvm -c -o foo.bc` argument and was greeted with

```
> clang -std=c++20 dict.cpp -emit-llvm -c -o foo.bc
dict.cpp:128:28: error: implicit instantiation of undefined template 'std::array<std::string, 3>'
    for(auto fName: config.fieldNames()){
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
dict.cpp:83:46: error: implicit instantiation of undefined template 'std::array<std::string, 3>'
    std::array<std::string,sizeof...(Types)> fieldNames(){
                                             ^
dict.cpp:128:28: note: in instantiation of member function 'Configuration<int, double, std::complex<double>>::fieldNames' requested here
    for(auto fName: config.fieldNames()){
                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
dict.cpp:84:50: error: implicit instantiation of undefined template 'std::array<std::string, 3>'
        std::array<std::string,sizeof...(Types)> names;
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/xs/n80hfp_j4zx4z6gfqjf05wwr0000gn/T/dict-45ef40.cpp
clang: note: diagnostic msg: /var/folders/xs/n80hfp_j4zx4z6gfqjf05wwr0000gn/T/dict-45ef40.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/evanberkowitz/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg:

********************
```

Because I cannot attach `.cpp`s to this issue, I have put the original `dict.cpp`, the diagnostic `dict-45ef40.{cpp,sh}` and the crash report into [evanberkowitz/llvm-segfault-dict](https://github.com/evanberkowitz/llvm-segfault-dict).

`dict.cpp` compiles with `g++-11 -std=c++20 dict.cpp` with
```
> g++-11 --version
g++-11 (Homebrew GCC 11.2.0_3) 11.2.0
```

**Comment by royjacobson** [comment] 2022-05-30 20:43
I couldn't reproduce your crash on Godbolt - which version of clang did you use exactly?
https://godbolt.org/z/6o95Kcvcr


(BTW, GCC12 needs the `<array>` include as well.)

**Comment by evanberkowitz** [comment] 2022-06-03 16:16
```bash
> clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by royjacobson** [comment] 2022-06-05 11:18
This seems to be specific to Apple Clang then. You might want to contact them directly.

**Comment by fhahn** [comment] 2022-06-06 13:14
Closing, as the segfault is fixed in upstream clang.

**Closed by fhahn** 2022-06-06 13:14 UTC
Labels: clang, c++20, crash
