### ISSUE TITLE
[ld.lld] missing RISCV_ATTRIBUTES segment

### ISSUE THREAD

**Issue by nekopsykose** [llvm/llvm-project#63084] opened 2023-06-03 08:55 UTC
Forwarded from https://sourceware.org/bugzilla/show_bug.cgi?id=30237:  

Creating an lld-linked file:  

```console
psykose-edge-riscv64:~$ cat main.c 
int main() {return 0;}

psykose-edge-riscv64:~$ clang main.c -fuse-ld=lld -o somebin
```

then stripping it with GNU Binutils:  

```console
psykose-edge-riscv64:~$ strip somebin
strip: stgnjAlO: not enough room for program headers, try linking with -N
strip: stgnjAlO[.interp]: bad value

psykose-edge-riscv64:~$ strip --version
GNU strip (GNU Binutils) 2.40
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

this is apparently a missing attribute segment in the output (given the Binutils maintainer response), but i don't know anything about this area

**Comment by MaskRay** [comment] 2023-06-03 14:34
Thanks for not mentioning "bug" in the issue. This is a missing feature, not a bug.

https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/71 (2021-06) added PT_RISCV_ATTRIBUTES, but no dynamic loader uses this yet.

> forwarded from https://sourceware.org/bugzilla/show_bug.cgi?id=30237 :

This looks like a GNU objcopy/strip bug. The tool should work regardless of whether the linker creates `PT_RISCV_ATTRIBUTES`. AArch32 doesn't have `PT_ARM_ATTRIBUTES` and I believe objcopy/strip can process such a trivial program. The RISC-V port should be fixed.

**Closed** 2023-06-06 20:06 UTC
Labels: backend:RISC-V, lld:ELF
