### ISSUE TITLE
clang-format adds new line between semicolon and body-less loop

### ISSUE THREAD

**Issue by Jorengarenar** [llvm/llvm-project#61708] opened 2023-03-26 11:53 UTC
I'm gonna borrow example from [this SO question](https://stackoverflow.com/q/74190943/10247460) (and [here's a similar one](https://stackoverflow.com/q/43198429/10247460)):

> I want to configure clang-format that it leaves single-line while-statement without adding a line break for the trailing semicolon.
> For example, clang-format should just leave a "one-liner" as it is:
> ```c
> while (checkWaitCondition() != true);
> ```
> But unfortunately it adds by default a line break (plus an indentation):
> ```c
> while (checkWaitCondition() != true)
>   ;
> ```

**Comment by gedare** [comment] 2023-06-12 20:54
Steps to reproduce:
```
$ echo "while(1);" | clang-format -style=LLVM
while (1)
  ;
```
I have this behavior on 16.0.0 and 17.0.0. I do not have an older version to test or bisect setup at the moment.

**Comment by rymiel** [comment] 2023-06-12 23:41
> I do not have an older version to test or bisect setup at the moment.

That's fine, this is clang-format's behavior since its inception (i think) and definitely intended. Question is, do we want this to be configurable

**Comment by owenca** [comment] 2023-08-06 00:16
> Steps to reproduce:
> 
> ```
> $ echo "while(1);" | clang-format -style=LLVM
> while (1)
>   ;
> ```

The default value of `AllowShortLoopsOnASingleLine` for LLVM is `false`. To demonstrate that the loop is not merged despite that `AllowShortLoopsOnASingleLine` is changed to `true`:
```
 $ echo "while(1);" | clang-format -style='{AllowShortLoopsOnASingleLine: true}'
while (1)
  ;
```

**Comment by owenca** [comment] 2023-08-06 00:16
https://reviews.llvm.org/D154550

**Comment by HazardyKnusperkeks** [comment] 2023-10-31 19:41
> > I do not have an older version to test or bisect setup at the moment.
> 
> That's fine, this is clang-format's behavior since its inception (i think) and definitely intended. Question is, do we want this to be configurable

I'd say this should not be formatted on a single line. I'd change `AllowShortLoopsOnASingleLine` to `Never`, `NonEmpty` (this is the old `true`) and `Always`, or something like that.

**Comment by owenca** [comment] 2023-10-31 21:39
See the discussion from [here](https://reviews.llvm.org/D154550#4526386) and onward.

**Closed** 2023-11-02 21:09 UTC
Labels: clang-format

**Comment by prj-** [comment] 2023-11-27 07:38
@owenca, @HazardyKnusperkeks, sorry to bump this old thread, but is there a way to revert to the "old" behavior, i.e., having the semi-colon on a single line? It seems https://reviews.llvm.org/D154550#4526386 never got merged, so I cannot use `NonNullStatement`.

**Comment by owenca** [comment] 2023-11-27 08:55
> is there a way to revert to the "old" behavior, i.e., having the semi-colon on a single line?

Yes, by setting `AllowShortLoopsOnASingleLine` to `false`.

**Comment by prj-** [comment] 2023-11-27 12:31
This, however, introduces a very large number of other white-space changes. Is something like `AllowEmptyLoopsOnASingleLine` planned at all?

**Comment by owenca** [comment] 2023-11-27 12:43
I don't think so, if you mean:
```
while (i > 0) --i;
while (0)
  ;
while (j > 0) { --j; }
while (1)
{}
```
