### ISSUE TITLE
Company's blog decided to conduct static analysis LLVM

### ISSUE THREAD

**Issue by GermanAizek** [llvm/llvm-project#117050] opened 2024-11-20 21:02 UTC
Hello everyone, I accidentally noticed that your project was published on a corporate blog. The company decided to do a static LLVM analysis and found 19 possible bugs, check if they are really problems.

English: https://pvs-studio.com/en/blog/posts/cpp/1188/

**Comment by topperc** [comment] 2024-11-20 21:11
Duplicate of #116944

**Closed** 2024-11-20 21:12 UTC
Labels: duplicate, code-quality
