### ISSUE TITLE
fatal error: error in backend: Unsupported library call operation! with "_ExtInt" Clang 13.0.0

### ISSUE THREAD

**Issue by Ayxan13** [llvm/llvm-project#52675] opened 2021-12-13 19:46 UTC
[See online with godbolt.org](https://godbolt.org/z/xsnaneGMo)

OS: Linux x86-64
Clang: 13.0.0
Language: C++

Code causing the problem:

```
#include <algorithm>
#include <iostream>

template <int size>
using Int = _ExtInt(size);

template <int size>
using UInt = unsigned _ExtInt(size);

template <int size>
auto& operator<<(std::ostream& os, Int<size> i) {
    char buffer[sizeof(i) * 3 + 2];

    bool isNeg = (i < 0);

    if (isNeg) i = -i;

    auto p = buffer;

    do {
        *p++ = (i % 10) + '0';
    } while (i /= 10);

    if (isNeg) *p++ = '-';

    std::reverse(buffer, p);

    *p++ = 0;

    os << buffer;

    return os;
}

int main() {
    using i512 = Int<512>;
    using u512 = UInt<512>;

    auto max = i512((~(u512(0))) >> 1);

    std::cout << max << '\n';
}
```

Compiler output:

```
fatal error: error in backend: Unsupported library call operation!
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-13.0.0/bin/clang++ -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-11.2.0 -fcolor-diagnostics -fno-crash-diagnostics -O3 <source>
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '<source>'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@main'
 #0 0x00005588042df7ff PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005588042dd6c0 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x34dd6c0)
 #2 0x000055880422ee12 llvm::CrashRecoveryContext::HandleExit(int) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x342ee12)
 #3 0x00005588042d628e llvm::sys::Process::Exit(int, bool) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x34d628e)
 #4 0x000055880208469e LLVMErrorHandler(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) cc1_main.cpp:0:0
 #5 0x0000558804236299 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3436299)
 #6 0x0000558804236458 (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3436458)
 #7 0x000055880516e588 llvm::TargetLowering::makeLibCall(llvm::SelectionDAG&, llvm::RTLIB::Libcall, llvm::EVT, llvm::ArrayRef<llvm::SDValue>, llvm::TargetLowering::MakeLibCallOptions, llvm::SDLoc const&, llvm::SDValue) const (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x436e588)
 #8 0x0000558805206a10 llvm::DAGTypeLegalizer::ExpandIntRes_SDIV(llvm::SDNode*, llvm::SDValue&, llvm::SDValue&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x4406a10)
 #9 0x000055880521a50b llvm::DAGTypeLegalizer::ExpandIntegerResult(llvm::SDNode*, unsigned int) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x441a50b)
#10 0x0000558805186075 llvm::DAGTypeLegalizer::run() (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x4386075)
#11 0x000055880518684e llvm::SelectionDAG::LegalizeTypes() (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x438684e)
#12 0x0000558805129990 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x4329990)
#13 0x000055880512d054 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x432d054)
#14 0x000055880512f2e2 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.887) SelectionDAGISel.cpp:0:0
#15 0x0000558802ff9e88 (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) X86ISelDAGToDAG.cpp:0:0
#16 0x0000558803672918 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x2872918)
#17 0x0000558803aa6eb9 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x2ca6eb9)
#18 0x0000558803aa7151 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x2ca7151)
#19 0x0000558803aa83c7 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x2ca83c7)
#20 0x00005588045d29f2 (anonymous namespace)::EmitAssemblyHelper::EmitAssemblyWithNewPassManager(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) BackendUtil.cpp:0:0
#21 0x00005588045d6ef5 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x37d6ef5)
#22 0x0000558805233e1d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x4433e1d)
#23 0x000055880608cd49 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x528cd49)
#24 0x0000558805233ec2 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x4433ec2)
#25 0x0000558804be1091 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3de1091)
#26 0x0000558804b7f352 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3d7f352)
#27 0x0000558804cad7d3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3ead7d3)
#28 0x000055880208601c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x128601c)
#29 0x00005588020821fd ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#30 0x0000558804a2aaa5 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#31 0x000055880422eca3 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x342eca3)
#32 0x0000558804a2cb5e clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3c2cb5e)
#33 0x0000558804a0258a clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3c0258a)
#34 0x0000558804a030df clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3c030df)
#35 0x0000558804a0c4d5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x3c0c4d5)
#36 0x0000558801f9b46e main (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x119b46e)
#37 0x00007f1314d970b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#38 0x0000558802081d7a _start (/opt/compiler-explorer/clang-13.0.0/bin/clang+++0x1281d7a)
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
ASM generation compiler returned: 70
fatal error: error in backend: Unsupported library call operation!
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Execution build compiler returned: 70
```

**Comment by duk-37** [comment] 2021-12-15 02:56
Seems like the issue here is that the runtime library [doesn't support division for integers of arbitrary bit-width](https://github.com/llvm/llvm-project/blob/5255ca9726e9734eae5115488517175f9c94c9de/llvm/lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp#L3920).

I don't know whether that's something planned for the near future. Doesn't exactly sound trivial.

**Comment by AaronBallman** [comment] 2022-01-18 19:20
This is a duplicate of https://github.com/llvm/llvm-project/issues/44994

**Closed by AaronBallman** 2022-01-18 19:20 UTC
Labels: duplicate, backend:X86, crash, llvm:SelectionDAG
