### ISSUE TITLE
Poor compilation errors for NTTPs  in clang

### ISSUE THREAD

**Issue by mpusz** [llvm/llvm-project#66744] opened 2023-09-19 07:48 UTC
Even though Clang was always known for great compiler error messages, it behaves poorly when NTTPs are used. Please see this Compiler Explorer link to compare the same error messages in GCC and CLANG: https://godbolt.org/z/bvfEa5jMr.

Typical issues are:
- printing `expr{{{}}}` instead of the actual type ( 'quantity<expr{{{}}}, double>')
- printing `{{{}}}` instead of just `{}` (`quantity<derived_unit<metre, per<second>>{{{}}}>`)

Longer example:

## GCC

```
error: conversion from 'quantity<mp_units::derived_unit<mp_units::si::metre, mp_units::si::second>(),[...]>' to non-scalar type 'quantity<mp_units::derived_unit<mp_units::si::metre, mp_units::per<mp_units::si::second> >(),[...]>' requested
    9 |   quantity<si::metre / si::second> v1 = q;
      |                      
```

## Clang

```
<source>:9:36: error: no viable conversion from 'quantity<{{{}}}, [...]>' to 'quantity<{{{}}}, [...]>'
    9 |   quantity<si::metre / si::second> v1 = q;
      |  
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/quantity.h:124:3: note: candidate constructor not viable: no known conversion from 'quantity<expr{{{}}}, std::remove_cvref_t<double>>' (aka 'quantity<expr{{{}}}, double>') to 'const quantity<derived_unit<metre, per<second>>{{{}}}> &' for 1st argument
  124 |   quantity(const quantity&) = default;
      |   ^        ~~~~~~~~~~~~~~~
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/quantity.h:125:3: note: candidate constructor not viable: no known conversion from 'quantity<expr{{{}}}, std::remove_cvref_t<double>>' (aka 'quantity<expr{{{}}}, double>') to 'quantity<derived_unit<metre, per<second>>{{{}}}> &&' for 1st argument
  125 |   quantity(quantity&&) = default;
      |   ^        ~~~~~~~~~~
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/quantity.h:128:66: note: candidate template ignored: constraints not satisfied [with Q = quantity<expr{{{}}}, std::remove_cvref_t<double>>]
  128 |   constexpr explicit(!std::convertible_to<typename Q::rep, Rep>) quantity(const Q& q) :
      |                                                                  ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/quantity.h:127:12: note: because 'detail::QuantityConvertibleTo<mp_units::quantity<expr{{{}}}>, quantity<derived_unit<metre, per<second> >{{{}}}> >' evaluated to false
  127 |   template<detail::QuantityConvertibleTo<quantity> Q>
      |            ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/quantity.h:52:39: note: because 'implicitly_convertible(quantity<expr{{{}}}>::quantity_spec, quantity<derived_unit<metre, per<second> >{{{}}}>::quantity_spec)' evaluated to false
   52 |   Quantity<QFrom> && Quantity<QTo> && implicitly_convertible(QFrom::quantity_spec, QTo::quantity_spec) &&
      |                                       ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/quantity.h:136:22: note: explicit constructor is not a candidate
  136 |   constexpr explicit quantity(const Q& q) :
      |                      ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/quantity.h:361:22: note: explicit constructor is not a candidate
  361 |   constexpr explicit quantity(Value&& v) : numerical_value_(std::forward<Value>(v))
      |                      ^
```

**Comment by erichkeane** [comment] 2023-09-20 16:32
Any chance you could produce a reduced example (that is, not #including the headers)?  I am not familiar with the library, so it isn't clear to me what is happening as a result.

**Comment by mpusz** [comment] 2023-09-20 16:46
Hi @erichkeane, I will try to do it, but I am really busy preparing three papers about the library for Kona and two workshops and two lectures for CppCon now.

I have the impression that any class NTTP passed to a class template as an argument will provide similar diagnostics.

You can find all the details about the types in the GCC log. Please note that those NTTP arguments are instances of tag types (e.g. have no members -> that is why GCC prints them as `mp_units::derived_unit<mp_units::si::metre, mp_units::si::second>()`).

**Comment by JohelEGP** [comment] 2023-09-20 16:49
> I have the impression that any class NTTP passed to a class template as an argument will provide similar diagnostics.

I tried taking the committed test for <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111471>,
and that's not the case: <https://compiler-explorer.com/z/78hc8Ksfc>.

**Comment by JohelEGP** [comment] 2023-09-21 13:40
Here's a reproducer: <https://compiler-explorer.com/z/n5dMYY7Ps>.
```C++
struct empty {};
struct metre : empty { };
struct second : empty { };
template<auto, auto> struct divided_units : empty { };
template<auto> struct quantity { };

int main() {
  quantity<divided_units<metre{}, second{}>{}> q{};
  [[maybe_unused]] quantity<metre{}> q2 = q;
}
```
```output
<source>:9:38: error: no viable conversion from 'quantity<{{}}>' to 'quantity<{{}}>'
    9 |   [[maybe_unused]] quantity<metre{}> q2 = q;
      |                                      ^    ~
<source>:5:23: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'quantity<divided_units<metre{}, second{}>{}>' to 'const quantity<metre{{}}> &' for 1st argument
    5 | template<auto> struct quantity { };
      |                       ^~~~~~~~
<source>:5:23: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'quantity<divided_units<metre{}, second{}>{}>' to 'quantity<metre{{}}> &&' for 1st argument
    5 | template<auto> struct quantity { };
      |                       ^~~~~~~~
1 error generated.
Compiler returned: 1
```

**Comment by erichkeane** [comment] 2023-09-21 13:51
Huh, curiously we do it fine with the notes, but not the error.  Best I can see we emit them the same, so I don't really know the difference.  I'm looking into it a bit.

**Comment by erichkeane** [comment] 2023-09-21 14:26
So the difference is: We use the `%diff` work for the error, and just plain `QualType` printing for the notes.  I haven't really figured out what the `%diff` is supposed to do, but I DO have it down to `ASTDiagnostic.cpp`'s `FormatASTNodeDiagnosticArgument`.  The 'Kind' for the error is the `ak_qualtype_pair` vs it normally being the `ak_qualtype`.

So I suspect there is SOMETHING that we're trying to do in the `FormatTemplateTypeDiff` is not really aware of the NTTPs or something.

**Closed** 2023-09-21 20:28 UTC
Labels: clang:diagnostics

**Comment by JohelEGP** [comment] 2023-09-25 16:04
Thank you.

This issue still remains:

> * printing `{{{}}}` instead of just `{}` (`quantity<derived_unit<metre, per<second>>{{{}}}>`)

From the example in the opening comment:
```output
<source>:9:36: error: no viable conversion from 'quantity<expr{{{}}}, [...]>' to 'quantity<mp_units::derived_unit<mp_units::si::metre, mp_units::per<mp_units::si::second>>{{{}}}, [...]>'
```

From my reduction above:
```output
<source>:9:38: error: no viable conversion from 'quantity<divided_units<metre{}, second{}>{{}}>' to 'quantity<metre{{}}>'
```

From the actual code base:
```output
note: in instantiation of function template specialization 'mp_units::operator/=<mp_units::quantity<mp_units::si::metre{{}}, int>, mp_units::quantity<struct one{{{{}}}}>>' requested here
```

@mpusz What do you think of the NTTP mismatch in the first error of the CE in the opening comment?
Clang:
```output
<source>:9:36: error: no viable conversion from 'quantity<expr{{{}}}, [...]>' to 'quantity<mp_units::derived_unit<mp_units::si::metre, mp_units::per<mp_units::si::second>>{{{}}}, [...]>'
```
GCC:
```output
<source>:9:41: error: conversion from 'quantity<mp_units::derived_unit<mp_units::si::metre, mp_units::si::second>(),[...]>' to non-scalar type 'quantity<mp_units::derived_unit<mp_units::si::metre, mp_units::per<mp_units::si::second> >(),[...]>' requested
```
I mean, specifically,
Clang's `expr{{{}}}` vs.
GCC's `mp_units::derived_unit<mp_units::si::metre, mp_units::si::second>()`.

**Comment by erichkeane** [comment] 2023-09-25 16:09
That `expr{{{}}}` vs `mp_units...` is obviously much worse.  I didn't see anything like that in my debugging, do you have a minimal reproducer for that one?

I did the patch debugging based on your repro above and got (https://compiler-explorer.com/z/3r3cPMnch).  We still print some extra curley braces, but that is because we aren't suppressing curleys in the initializer, there wasn't a good way of doing so as far as I could tell in the time I had.

**Comment by JohelEGP** [comment] 2023-09-25 16:34
This does the trick (<https://compiler-explorer.com/z/dWbzsWsdh>):
```C++
struct empty {};
struct metre : empty { };
struct second : empty { };
template<auto, auto> struct divided_units : empty { };
template<auto> struct quantity { };
template<auto L, auto R>
auto operator*(quantity<L>, quantity<R>) {
  using expr = divided_units<L, R>;
  return quantity<expr{}>{};
}

int main() {
  auto q = quantity<metre{}>{} * quantity<second{}>{};
  [[maybe_unused]] quantity<metre{}> q2 = q;
}
```
```output
struct empty {};
struct metre : empty { };
struct second : empty { };
template<auto, auto> struct divided_units : empty { };
template<auto> struct quantity { };
template<auto L, auto R>
auto operator*(quantity<L>, quantity<R>) {
  using expr = divided_units<L, R>;
  return quantity<expr{}>{};
}

int main() {
  auto q = quantity<metre{}>{} * quantity<second{}>{};
  [[maybe_unused]] quantity<metre{}> q2 = q;
}
```

**Comment by erichkeane** [comment] 2023-09-25 16:36
Ah, hrmph, the 'expr' comes from the 'using' there.  I thought we were printing something awful.  I'm unfortunately not sure how the logic there works to decide between aliases or not, though I think we typically use aliases (else we end up doing basic_string instead of string, etc).

**Comment by JohelEGP** [comment] 2023-09-25 16:42
I was made aware of that quirk before while working on improvements for the library.
I know this is a workaround (<https://compiler-explorer.com/z/61G31rrhv>):
```C++
#include <functional>
struct empty {};
struct metre : empty { };
struct second : empty { };
template<auto, auto> struct divided_units : empty { };
template<auto> struct quantity { };
template<auto L, auto R>
auto operator*(quantity<L>, quantity<R>) {
  using expr = divided_units<L, R>;
  return quantity<std::identity{}(expr{})>{};
}

int main() {
  auto q = quantity<metre{}>{} * quantity<second{}>{};
  [[maybe_unused]] quantity<metre{}> q2 = q;
}
```
```output
<source>:15:38: error: no viable conversion from 'quantity<divided_units<metre{{}}, second{{}}>{{}}>' to 'quantity<metre{{}}>'
   15 |   [[maybe_unused]] quantity<metre{}> q2 = q;
      |                                      ^    ~
<source>:6:23: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'quantity<std::identity{}(expr{})>' to 'const quantity<metre{{}}> &' for 1st argument
    6 | template<auto> struct quantity { };
      |                       ^~~~~~~~
<source>:6:23: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'quantity<std::identity{}(expr{})>' to 'quantity<metre{{}}> &&' for 1st argument
    6 | template<auto> struct quantity { };
      |                       ^~~~~~~~
1 error generated.
Compiler returned: 1
```
But the notes still use the literal expression.
In this case, `std::identity{}(expr{})`.

**Comment by mpusz** [comment] 2023-09-25 17:47
> I know this is a workaround

I applied this in the library today and was able to get rid of the confusing `expr` alias there. Thanks!

**Comment by mpusz** [comment] 2024-01-27 21:33
Hi @erichkeane , the errors are now MUCH better. Thanks!!!

However, some things still could be improved 😉. The following example https://godbolt.org/z/a79MG6MqE prints plenty of curly braces:

```text
<source>:53:15: error: no matching constructor for initialization of 'RectangularStorageTank'
   53 |   auto tank = RectangularStorageTank(horizontal_length(1'000 * mm),
      |               ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |                                      isq::height(200 * mm),
      |                                      ~~~~~~~~~~~~~~~~~~~~~~
   55 |                                      isq::width(500 * mm));
      |                                      ~~~~~~~~~~~~~~~~~~~~
<source>:43:13: note: candidate constructor not viable: no known conversion from 'quantity<mp_units::reference<mp_units::isq::height{{{{{}}}}}, mp_units::si::milli_<mp_units::si::metre{{}}>{{{{}}}}>{}, int>' to 'const quantity<reference<width{}, metre{}>{}, (default) double>' for 2nd argument
   43 |   constexpr RectangularStorageTank(const quantity<horizontal_length[m]>& length,
      |             ^
   44 |                                    const quantity<isq::width[m]>& width,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If those curlies could be collapsed into one pair only, the error message would be much more readable.

**Comment by mpusz** [comment] 2024-02-05 17:34
@erichkeane, here is another interesting error message (https://godbolt.org/z/PPnqacMdc):

```text
<source>:18:24: error: no matching function for call to 'time_to_goal'
   18 |   const quantity ttg = time_to_goal(half_marathon_distance, pace);
      |                        ^~~~~~~~~~~~
<source>:9:28: note: candidate template ignored: constraints not satisfied [with distance:auto = quantity<kilo_<metre{{}}>{}, double>, speed:auto = quantity<derived_unit<second, per<kilo_<metre{{}}>>>{}, double>]
    9 | QuantityOf<isq::time> auto time_to_goal(QuantityOf<isq::length> auto distance, QuantityOf<isq::speed> auto speed)
      |                            ^
<source>:9:80: note: because 'QuantityOf<mp_units::quantity<mp_units::derived_unit<mp_units::si::second, mp_units::per<mp_units::si::kilo_<mp_units::si::metre{{}}> > >{{{}}}>, isq::speed>' evaluated to false
    9 | QuantityOf<isq::time> auto time_to_goal(QuantityOf<isq::length> auto distance, QuantityOf<isq::speed> auto speed)
      |                                                                                ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/bits/quantity_concepts.h:61:37: note: because 'QuantitySpecOf<std::remove_const_t<decltype(quantity<derived_unit<second, per<kilo_<metre{{}}> > >{{{}}}, double>::quantity_spec)>, struct speed{{{}}}>' evaluated to false
   61 | concept QuantityOf = Quantity<Q> && QuantitySpecOf<std::remove_const_t<decltype(Q::quantity_spec)>, QS>;
      |                                     ^
/opt/compiler-explorer/libs/mp-units/trunk/src/core/include/mp-units/bits/quantity_spec_concepts.h:147:73: note: because 'implicitly_convertible(mp_units::kind_of_<mp_units::derived_quantity_spec<mp_units::isq::time, mp_units::per<mp_units::isq::length> >{{}, {{}}}>{}, struct speed{{{}}})' evaluated to false
  147 |   QuantitySpec<T> && QuantitySpec<std::remove_const_t<decltype(QS)>> && implicitly_convertible(T{}, QS) &&
      |                                                                         ^
1 error generated.
Compiler returned: 1
```

Notice how many curlies are in `implicitly_convertible(mp_units::kind_of_<mp_units::derived_quantity_spec<mp_units::isq::time, mp_units::per<mp_units::isq::length> >{{}, {{}}}>{}, struct speed{{{}}})`.
