### ISSUE TITLE
[clang-tidy] incorrect `misc-const-correctness` warning emitted for C++17 fold expression

### ISSUE THREAD

**Issue by romintomasetti** [llvm/llvm-project#70323] opened 2023-10-26 12:34 UTC
The following snippet can be used to "concatenate" a series of variadic parameters, thanks to a fold expression.

`clang-tidy` emits `misc-const-correctness` for the line declaring `oss`. I think it should not.

Command to run the example:
> clang-tidy --checks=misc-const-correctness --extra-arg=-std=c++20 test.cpp

```c++
#include <concepts>
#include <sstream>
#include <string>

//! Concatenate arguments in a @c std::string using a @c std::ostringstream.
template <typename... Args> requires (sizeof...(Args) > 0)
std::string concatenate(Args&&... args)
{
    std::ostringstream oss;
    (oss << ... << std::forward<Args>(args));
    return oss.str();
}
```

I'm using `Ubuntu LLVM version 17.0.4` version of `clang-tidy`.

**Comment by chrchr-github** [comment] 2023-10-26 13:46
Reduced:
~~~c++
#include <sstream>
#include <string>

template <typename T>
std::string f(T t)
{
    std::ostringstream oss;
    oss << t;
    return oss.str();
}
~~~
https://godbolt.org/z/376E3jh6o

**Comment by firewave** [comment] 2023-10-26 15:48
The reduced case is a duplicate of #57297.

**Closed** 2024-01-22 20:51 UTC
Labels: clang-tidy
