### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by showintime** [llvm/llvm-project#114375] opened 2024-10-31 08:28 UTC
``` c++

class A
{
protected:
	static void Func() {}
};

class B : public A
{
	friend class U;
};

class U
{
	void Abc()
	{
		// x64 msvc & x86-64 gcc compile success 
                // x86-64 clang: compile fail
		A::Func();
	}
};

```
![image](https://github.com/user-attachments/assets/8d38ea57-86b9-451f-9541-8140f53a148c)

**Comment by zyn0217** [comment] 2024-10-31 12:20
Duplicate of https://github.com/llvm/llvm-project/issues/34403

**Closed by zyn0217** 2024-10-31 12:20 UTC
Labels: clang:frontend, rejects-valid
