### ISSUE TITLE
[cmake][llvm version] using an hyphen for suffix breaks libc build

### ISSUE THREAD

**Issue by DunskiPhilippe** [llvm/llvm-project#108325] opened 2024-09-12 03:39 UTC
Hello,
It's a very good thing to define the LLVM version in a separate file (currently in <base project dir>/cmake/modules/LLVMVersion.cmake).

And it's a great idea to add a suffix like rcXXX when tagging release candidates, especially when they are four of them.

But this suffix is used in (libc/CMakeLists.txt) to define `default_namespace` as `__llvm_libc_${LLVM_VERSION_MAJOR}_${LLVM_VERSION_MINOR}_${LLVM_VERSION_PATCH}_${LLVM_VERSION_SUFFIX}`, which, will be used to define (still in libc/CMakeLists.txt) `LIBC_NAMESPACE` as the same value, then as preprocessor definition for LIBC_NAMESPACE and, finally used to define `LIBC_NAMESPACE_DECL` as being something like 
`#define  LIBC_NAMESPACE_DECL [[gnu::visibility("hidden")]] LIBC_NAMESPACE`
which will expend to
`[[gnu::visibility("hidden")]]_llvm_libc_19_1_0_-rc4`
to get the surrounding namespace for all all files in libc/src and its subdirectories

Problem is that single hyphen leads to multiple build error like
```
error: expected'{'
15 | namespace LIBC_NAMESPACE_DECL {
   |           ^
/home/philippe/Documents/projects/apogee/3rdParty/llvm-project/libc/src/__support/macros/config.h:39:59: note:expanded from macro 'LIBC_NAMESPACE_DECL'
39 | #define LIBC_NAMESPACE_DECL [[gnu::visibility("hidden")]] LIBC_NAMESPACE
   |                                                           ^
<command line>:1:43: note: expanded from macro 'LIBC_NAMESPACE'
1 | #define LIBC_NAMESPACE __llvm_libc_19_1_0_-rc4
  |                                           ^
```
I'm not sure if this hyphen is mandatory for some part of the complete build process, but I know it should not appear in this case because hyphens aren't allowed when defining an identifier in C++
So, I don't know what will be better:

Should you simply consider to define the suffix as rc4 in LLVMVersion.cmake file and maybe add it in some way where it is required?

Should you consider to keep it in LLVMVersion.cmake file and remove it locally to define the default_namespace variable in libc/CMakeLists ?

Maybe could you consider to remove the _${LLVM_VERSION_SUFFIX} part when declaring the default_namespace? But, if you do, what about people building both rc3 and rc4 versions?

Choice is yours, but I really thing that something has to be done ;)

**Comment by michaelrj-google** [comment] 2024-09-12 17:59
Duplicate of https://github.com/llvm/llvm-project/issues/101028

**Closed** 2024-09-12 18:01 UTC
Labels: duplicate, build-problem, libc
