### ISSUE TITLE
[ Windows] [C++20] [Modules] [ABI] Linker errors relating to vftable with C++20 modules

### ISSUE THREAD

**Issue by kamrann** [llvm/llvm-project#97447] opened 2024-07-02 17:25 UTC
The following simple repro will generate multiple definition linker errors on Windows (regardless of link.exe or lld-link.exe, so appears the issue is with clang emitting symbols for every TU importing the module in question).

```
// mod.mxx
export module mod;
export struct poly
{
  virtual ~poly() = default;
};
```
```
// a.cxx
import mod;
poly p1;
```
```
// b.cxx
import mod;
poly p2;

int main() { return 0; }
```

Tested with multiple build systems (CMake and build2), on
- trunk (c44e9ff691a10cd900b93d9ff4e0ada355ca82d7)

Edit: appears to be a regression, problem does not show up on 18.1.8 (3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff).

**Comment by ChuanqiXu9** [comment] 2024-07-03 01:33
Can you try the latest trunk?

**Comment by kamrann** [comment] 2024-07-03 12:02
Tried again today (1eec81a831dcf925c0c86c153e8dce019a5b5436), issue remains.

**Comment by ChuanqiXu9** [comment] 2024-07-05 02:19
It looks like at least it works fine on linux: https://godbolt.org/z/zErjTqazf

**Comment by ChuanqiXu9** [comment] 2024-07-05 02:46
I just realized that we changed the ABI spec for vtable in modules in **ItaniumCXX ABI**. But we didn't take care of it for Windows ABI..

I'll try to get connected with MSVC devs to make sure the behavior of vtables in modules in Windows ABI.

**Comment by kamrann** [comment] 2024-07-05 13:01
Yep, sorry should have been clearer - I'm building my project on both Windows and Linux, and this issue only showed up on Windows (and even there, only at some point after `18.1.8`).

> I'll try to get connected with MSVC devs to make sure the behavior of vtables in modules in Windows ABI.

Sounds good, thanks!

**Comment by Ivan171** [comment] 2024-07-06 21:47
> I just realized that we changed the ABI spec for vtable in modules in ItaniumCXX ABI. But we didn't take care of it for Windows ABI.

I tried to build one of my projects with an updated clang (af784a5c) and got errors related to vtable as well. My old build of clang (faf675ce) builds without any error.

It's probably related to this issue.

**Comment by ChuanqiXu9** [comment] 2024-07-10 03:26
I reverted that change for Itanium C++ ABI in https://github.com/llvm/llvm-project/pull/75912. So I think we can close this. Feel free to ask to reopen this if it is not actually fixed.

**Closed by ChuanqiXu9** 2024-07-10 03:26 UTC
Labels: clang:modules, platform:windows

**Comment by ChuanqiXu9** [comment] 2024-08-07 08:48
@kamrann @Ivan171  I don't know why I can't ping you in https://github.com/llvm/llvm-project/pull/102287. But I hope you can help to test that patch on windows to avoid the regression again.
