### ISSUE TITLE
void{} is not supported

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#63427] opened 2023-06-21 12:09 UTC
This program
```c++
template<typename T>
T bar() { return T{}; }

int main() {
    // error in Clang
    bar<void>();
}
```
must be accepted since C++20. See https://cplusplus.github.io/CWG/issues/2351.html

Unfortunately, Clang 16 prints the error:
```
error: illegal initializer type 'void'
```
Online demo: https://gcc.godbolt.org/z/zv9nzq36G

**Comment by shafik** [comment] 2023-06-21 17:53
Duplicate of: https://github.com/llvm/llvm-project/issues/51552

**Closed by shafik** 2023-06-21 17:53 UTC
Labels: c++20, clang:frontend
