### ISSUE TITLE
Analyzer warns about an uninitialized value on a structured binding captured in a lambda

### ISSUE THREAD

**Issue by KitsuneRal** [llvm/llvm-project#115137] opened 2024-11-06 08:57 UTC
In C++17, structured bindings could not be immediately captured in lambdas; in C++20 they can but Clang analyzer didn't seem to catch up with this. This small program:
```cplusplus
#include <tuple>
#include <iostream>

int main()
{
    std::tuple<std::size_t> t{ 1 };
    auto&& [a] = t;
    [a] {
        std::cout << a << std::endl;
    }();
}
```
triggers an uninitialised value warning inside the lambda, as can be seen at https://godbolt.org/z/sPsW4Pnr4.

**Comment by aaronpuchert** [comment] 2024-11-25 22:40
Looks very much like a duplicate of #91835.

**Closed by aaronpuchert** 2024-11-25 22:40 UTC
Labels: duplicate, clang:static analyzer
