### ISSUE TITLE
[Clang++][ABI] Different mangled name for clang++ and g++

### ISSUE THREAD

**Issue by dongjianqiang2** [llvm/llvm-project#88864] opened 2024-04-16 09:40 UTC
demo:

```c++
#include <type_traits>
template <class T>
std::enable_if_t <std::is_integral <T>::value, int>
foo() {
  return 0;
}

template int foo<int>();

```

G++ mangle it as :
`_Z3fooIiENSt9enable_ifIXsrSt11is_integralIT_E5valueEiE4typeEv`
Clang++ mangle it as:
`_Z3fooIiENSt9enable_ifIXsr3std11is_integralIT_EE5valueEiE4typeEv`

[godbolt](https://godbolt.org/z/Tc6YE3EzG)
I think this is a common ABI compatible issue between gcc and clang.

**Comment by shafik** [comment] 2024-04-16 17:46
Duplicate of: https://github.com/llvm/llvm-project/issues/62765

**Closed by shafik** 2024-04-16 17:46 UTC
Labels: clang:frontend
