### ISSUE TITLE
[OpenMP] Missing header `omp.h` in install directory when building `llvm@18.1.2` with `openmp` as runtime with `cmake@3.29.0` 

### ISSUE THREAD

**Issue by s-sajid-ali** [llvm/llvm-project#86744] opened 2024-03-26 22:38 UTC
### Summary
When installing `llvm@18.1.2` with `spack` using `cmake@3.29.0` and configuring `openmp` to be enabled as a runtime, the final install directory is missing `omp.h` even though the header is present in the build directory. However, this problem does not occur when building `llvm@18.1.2` with the same configuration using `cmake@3.27.9`. 

### Details
Here are the two builds of `llvm@18.1.2` differing only in the version of `cmake` used for the build. 
```
sasyed@MAC-140753 ~> spack find -lv llvm
-- darwin-sonoma-m1 / apple-clang@15.0.0 ------------------------
cgcsya3 llvm@18.1.2+clang~code_signing~cuda~flang~gold~ipo~libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3~zstd build_system=cmake build_type=Release compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime shlib_symbol_version=none targets=none version_suffix=none
bydpwmd llvm@18.1.2+clang~code_signing~cuda~flang~gold~ipo~libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3~zstd build_system=cmake build_type=Release compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime shlib_symbol_version=none targets=none version_suffix=none
==> 2 installed packages
sasyed@MAC-140753 ~> spack diff /cgc /byd
==> Warning: This interface is subject to change.

--- llvm@18.1.2/cgcsya36nknpeizproew2cdxtf4r6xcb
+++ llvm@18.1.2/bydpwmdkng7shunf3ltzj56a3bkjepy5
@@ hash @@
-  cmake slpmwq3esyyjikfqskqbea3nvobw7oei
+  cmake yyb45mfiot4obxxx7kashbrpvudmx3d4
-  llvm cgcsya36nknpeizproew2cdxtf4r6xcb
+  llvm bydpwmdkng7shunf3ltzj56a3bkjepy5
@@ package_hash @@
-  cmake gsj2wl26n5psfanwtf3a3owh6fcj5mnx6eyuygm6g7eo5wye6y4a====
+  cmake 4nfzzuirvovagbkvkxjvtkvwyokgaekv3iyo3emo7h2ai42uofmq====
@@ version @@
-  cmake 3.29.0
+  cmake 3.27.9
sasyed@MAC-140753 ~>
```

Here are the results of an attempt to locate `omp.h` within the two install destinations: 
```
sasyed@MAC-140753 ~> fd "omp.h" (spack location -i /cgc)
/Users/sasyed/Documents/packages/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/include/llvm/Frontend/OpenMP/OMP.h.inc
/Users/sasyed/Documents/packages/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/include/polly/CodeGen/LoopGeneratorsGOMP.h
sasyed@MAC-140753 ~> fd "omp.h" (spack location -i /byd)
/Users/sasyed/Documents/packages/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/llvm-18.1.2-bydpwmdkng7shunf3ltzj56a3bkjepy5/include/c++/v1/__algorithm/comp.h
/Users/sasyed/Documents/packages/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/llvm-18.1.2-bydpwmdkng7shunf3ltzj56a3bkjepy5/include/llvm/Frontend/OpenMP/OMP.h.inc
/Users/sasyed/Documents/packages/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/llvm-18.1.2-bydpwmdkng7shunf3ltzj56a3bkjepy5/include/polly/CodeGen/LoopGeneratorsGOMP.h
/Users/sasyed/Documents/packages/spack/opt/spack/darwin-sonoma-m1/apple-clang-15.0.0/llvm-18.1.2-bydpwmdkng7shunf3ltzj56a3bkjepy5/lib/clang/18/include/omp.h
sasyed@MAC-140753 ~> 
```
where it is clear that when using `cmake@3.29.0` the header `omp.h` is missing. 

It is however, present in the build directory as shown below:
```
sasyed@MAC-140753 /v/f/m/z/T/s/s/s/spack-build-cgcsya3> pwd
/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3
sasyed@MAC-140753 /v/f/m/z/T/s/s/s/spack-build-cgcsya3> fd "omp.h"
include/c++/v1/__algorithm/comp.h
include/llvm/Frontend/OpenMP/OMP.h.inc
runtimes/runtimes-bins/openmp/runtime/src/omp.h
sasyed@MAC-140753 /v/f/m/z/T/s/s/s/spack-build-cgcsya3> 
```

### Platform information & Supporting logs
Output of `spack debug report`:
```
sasyed@MAC-140753 ~> spack debug report
* **Spack:** 0.22.0.dev0 (69509a6d9a9c515dc4e00fbfe94c7e27a440b0ad)
* **Python:** 3.9.6
* **Platform:** darwin-sonoma-m1
* **Concretizer:** clingo
sasyed@MAC-140753 ~> 
```

Build log for `llvm@18.1.2 targets=none ^cmake@3.29.0`: [spack-build-out.txt](https://github.com/llvm/llvm-project/files/14765311/spack-build-out.txt)
Build log for `llvm@18.1.2 targets=none` (implicitly picking `cmake@3.27.9`): [spack-build-out.txt](https://github.com/llvm/llvm-project/files/14765315/spack-build-out.txt)

**Comment by shiltian** [comment] 2024-03-26 23:26
I can't reproduce it locally on either Linux or macOS (which appears to be used in the ticker).

Linux:
```
➜  cmake --version
cmake version 3.29.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
➜  ll /home/shiltian/Documents/build/llvm-runtimes/release/lib/clang/19/include/omp.h
-rw-r--r-- 1 shiltian shiltian 24K Mar 26 19:15 /home/shiltian/Documents/build/llvm-runtimes/release/lib/clang/19/include/omp.h
```

macOS:
```
➜  ll $BUILD_ROOT/llvm-runtimes/release/lib/clang/19/include/omp.h
-rw-r--r--  1 shiltian  staff    23K Mar 26 19:22 /Users/shiltian/Documents/build/llvm-runtimes/release/lib/clang/19/include/omp.h
➜  cmake --version
cmake version 3.29.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by vimproved** [comment] 2024-03-27 02:27
Looking through the build log, I think I've found the source of the issue:
During the build step, when it configures the runtimes, it passes `-DCMAKE_C_COMPILER=/priv
ate/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang -DCMAKE_CXX_COMPILER=/private/var/folders/mb/zd6pgmt
100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang++ -DCMAKE_ASM_COMPILER=/private/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/
T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang`. During the install step however, cmake detects that they have been changed and reruns configure with this message:
```
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= /private/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang
CMAKE_CXX_COMPILER= /private/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang++
CMAKE_ASM_COMPILER= /private/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang
CMAKE_C_COMPILER= /private/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang
CMAKE_CXX_COMPILER= /private/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang++
CMAKE_ASM_COMPILER= /private/var/folders/mb/zd6pgmt100q77s5fhn5xf4jw0000gq/T/sasyed/spack-stage/spack-stage-llvm-18.1.2-cgcsya36nknpeizproew2cdxtf4r6xcb/spack-build-cgcsya3/./bin/clang
```

which then causes there to be no install targets for runtimes:
```
[6/10] Performing build step for 'runtimes'
ninja: no work to do.
[7/10] No install step for 'runtimes'
[9/10] Completed 'runtimes'
[9/10] Install the project...
```

I'm hitting a similar case in Gentoo, where the `CMAKE_*_COMPILER` variables being passed to both cmake invocations are the exact same, but CMake is still detecting them as different and causing the build to break: https://0x0.st/XsWG.log. I'm going to conclude that this is most likely a CMake bug.

**Comment by vimproved** [comment] 2024-03-27 02:46
Digging deeper, it seems like CMake for whatever reason always thinks a variable has changed if it includes `./`. For a simple test, use any project utilizing CMake, then run `cmake -B build -DCMAKE_C_COMPILER="/usr/lib/llvm/18/./bin/clang"` with any path containing `./`. However, it seems like CMake is now automatically translating this to an absolute path in CMakeCache.txt: `CMAKE_C_COMPILER:STRING=/usr/lib/llvm/18/bin/clang`, but it's still checking `/usr/lib/llvm/18/./bin/clang` for whether it needs to be rerun, causing a reconfigure even when unneeded.

**Comment by s-sajid-ali** [comment] 2024-03-27 16:52
Thanks a lot for the analysis @vimproved! 

Should this be cross posted on the [`cmake repository`](https://gitlab.kitware.com/cmake/cmake/-/issues) as well?

**Comment by shiltian** [comment] 2024-03-27 17:07
@s-sajid-ali I'll close the issue here. If you think there is anything to be done on our side, feel free to open it in the future.

**Closed by shiltian** 2024-03-27 17:07 UTC
Labels: cmake, openmp

**Comment by fxcoudert** [comment] 2024-04-10 13:46
Issue on cmake tracker: https://gitlab.kitware.com/cmake/cmake/-/issues/25883

**Comment by s-sajid-ali** [comment] 2024-04-10 16:02
Thanks @fxcoudert !

**Comment by vimproved** [comment] 2024-04-12 14:03
> Issue on cmake tracker: https://gitlab.kitware.com/cmake/cmake/-/issues/25883

Haven't had time to send this upstream, thank you!
