### ISSUE TITLE
clangd crash

### ISSUE THREAD

**Issue by Du-Guang-rong** [llvm/llvm-project#117670] opened 2024-11-26 05:35 UTC
clangd version 19.1.1 (CentOS 19.1.1-5.el10)
Features: linux
Platform: x86_64-unknown-linux-gnu; target=x86_64-redhat-linux-gnu

PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
 #0 0x00007f24b8438f4a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.19.1+0x638f4a)
 #1 0x00007f24b84363f6 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.19.1+0x6363f6)
 #2 0x00007f24b843970b (/lib64/libLLVM.so.19.1+0x63970b)
 #3 0x00007f24bea69ac0 __restore_rt (/lib64/libc.so.6+0x40ac0)
 #4 0x00007f24b83c7ee1 llvm::StringMapImpl::LookupBucketFor(llvm::StringRef, unsigned int) (/lib64/libLLVM.so.19.1+0x5c7ee1)
 #5 0x0000561159bb11f6 (/usr/bin/clangd+0x5c21f6)
 #6 0x0000561159bafc84 (/usr/bin/clangd+0x5c0c84)
 #7 0x000056115a20a78f (/usr/bin/clangd+0xc1b78f)
 #8 0x0000561159939837 (/usr/bin/clangd+0x34a837)
 #9 0x00005611599d20f8 (/usr/bin/clangd+0x3e30f8)
#10 0x00005611599d1b6a (/usr/bin/clangd+0x3e2b6a)
#11 0x00005611599cd763 (/usr/bin/clangd+0x3de763)
#12 0x00005611599cb83f (/usr/bin/clangd+0x3dc83f)
#13 0x0000561159b45002 (/usr/bin/clangd+0x556002)
#14 0x00007f24beabd9e9 start_thread (/lib64/libc.so.6+0x949e9)
#15 0x00007f24beb2d4bc __GI___clone3 (/lib64/libc.so.6+0x1044bc)
Signalled during AST worker action: Build AST

**Comment by HighCommander4** [comment] 2024-11-26 05:40
Based on the `LookupBucketFor` in the backtrace, this is almost certainly https://github.com/llvm/llvm-project/issues/109367, a 19.1.0 regression which was fixed in 19.1.2.

**Comment by Du-Guang-rong** [comment] 2024-11-26 06:07
https://github.com/llvm/llvm-project/issues/117670#issuecomment-2499708305

I think you are right, I vi ~/.config/clangd/config.yaml file 
and change this line: 
  `boost-*,`
to 
  `#boost-*,`

then this problem is resolved. crash is NOT found again :)

**Comment by HighCommander4** [comment] 2024-11-26 06:14
Duplicate of https://github.com/llvm/llvm-project/issues/109367

**Closed by HighCommander4** 2024-11-26 06:14 UTC
Labels: clangd, incomplete, crash
