### ISSUE TITLE
address of label is "1" when label has been optimized away

### ISSUE THREAD

**Issue by kees** [llvm/llvm-project#54328] opened 2022-03-10 22:11 UTC
The value of a label address is changed to "1" when its basic block has been optimized away. This doesn't seem sensible, though I'm not sure what the "correct" behavior should be. I suspect the code at the label should not be elided? But that probably has a whole set of other problems.

Contrived example:
https://godbolt.org/z/G4hs55KrG

```
#include <stdio.h>

static __attribute__((noinline))
void set_return_addr(unsigned long *expected, unsigned long *addr)
{
    /* Use of volatile is to make sure final write isn't seen as a dead store. */
    unsigned long * volatile *ret_addr = (unsigned long **)__builtin_frame_address(0) + 1;

    printf("*ret_addr:%p expected:%p replacement:%p\n", *ret_addr, expected, addr);
    fflush(NULL);
    /*
     * If make sure we've found the right place on the stack before writing it.
     * Then make sure Clang isn't giving us something weird.
     */
    if (*ret_addr == expected && addr > (unsigned long *)1)
        *ret_addr = addr;
    else
        printf("Didn't find expected return address on stack\n");
}

volatile int tricky;
int main(void)
{
#ifdef FORCE
    if (tricky)
        goto redirected;
#endif
    
    set_return_addr(&&normal, &&redirected);

normal:
    printf("I should be skipped\n");
    return tricky;

redirected:
    printf("Redirected\n");
    return tricky;
}
```

GCC, -O2 will collapse the label to an earlier one:
```
*ret_addr:0x401069 expected:0x401060 replacement:0x401060
Didn't find expected return address on stack
I should be skipped
```

Clang, -O2:
```
*ret_addr:0x4005d6 expected:0x4005d6 replacement:0x1
Didn't find expected return address on stack
I should be skipped
```

If an explicit path is kept, the label sticks around, as expected.

Clang, -O2 -DFORCE
```
*ret_addr:0x4005e4 expected:0x4005e9 replacement:0x4005e9
Didn't find expected return address on stack
I should be skipped
```

While it does seem better to avoid aliasing a different label (as GCC does) with a literal "1", it seems it'd be better to error out the compile since the label doesn't exist any more.

@nickdesaulniers

**Comment by gwelymernans** [comment] 2022-03-10 23:24
Notice that both are getting it "wrong." GCC removes the code in the landing block. Even at `-O0` it fails.

From a quick look, it's the SimplifyCFG pass that removes the `redirected` block and the IPSCCP pass that's turning `addr` into a `1`.

**Comment by efriedma-quic** [comment] 2022-03-10 23:49
Addresses of labels are intended to be used with computed goto.  The handling here is based around that: if a block is dead, it can't be the target of a computed goto.  So we just set the address to an arbitrary non-zero constant; the use of "1" makes it clear what happened.

To make your example do what you want, you need a "call with computed goto" or something like that, but it doesn't exist.  You can emulate it with asm goto: something like `asm goto("lea 1f(%%rip), %%rdi; lea %0(%%rip), %%rsi; call set_return_addr; 1:"::::redirected);`.

**Comment by gwelymernans** [comment] 2022-03-10 23:59
Ah! That might explain why there's this at the bottom of `main`:

```
indirectgoto:                                     ; No predecessors!
  indirectbr i8* undef, [label %normal, label %redirected]
```

**Comment by nickdesaulniers** [comment] 2022-03-14 20:00
> Addresses of labels are intended to be used with computed goto. The handling here is based around that: if a block is dead, it can't be the target of a computed goto. So we just set the address to an arbitrary non-zero constant; the use of "1" makes it clear what happened.

I feel like that perhaps should be predicated on whether the label has its address taken.

Another surprising case:
```llvm
; main.ll
define i32 @foo () {
  ret i32 0
label42:
  ret i32 42
}

define i32 @main () {
entry:
  br label %labelx

labelx:
  %0 = tail call i32 bitcast (i8* blockaddress(@foo, %label42) to i32 ()*)()
  ret i32 %0
}
```
```sh
$ opt -O2 -S main.ll
```
```llvm
define i32 @foo() local_unnamed_addr #0 {
  ret i32 0
}

define i32 @main() local_unnamed_addr {
entry:
  %0 = tail call i32 inttoptr (i32 1 to i32 ()*)()
  ret i32 %0
}
```

I suspect some optimizations that check whether a `BasicBlock` is unreachable don't confirm whether it's had its address taken, and if that address escapes.  It might appear unreachable locally, but if its address escapes, it's not safe IMO to remove it.

Dealing with https://reviews.llvm.org/D120781, part of me things that `blockaddress`'s should only be able to refer to the function they're used in OR functions with external linkage.

**Comment by efriedma-quic** [comment] 2022-03-14 20:55
Restating https://llvm.org/docs/LangRef.html#addresses-of-basic-blocks, the value of a blockaddress formally has the following restrictions:

1. It's non-zero.
2. When you pass it to an indirectbr, and the indirectbr has the corresponding basic block as a successor, the indirectbr branches to that basic block.
3. When you pass it to a callbr, and the callbr has the corresponding basic block as a successor, a native branch instruction can branch to that basic block.  (We've discussed dropping this rule because it makes implementing return values messy, but it's there for now.)

For a blockaddress that points to a dead block, (2) and (3) are meaningless, so we're left with (1).

I'm not sure what new rule you're proposing.

**Comment by nickdesaulniers** [comment] 2022-03-14 21:31
> Restating https://llvm.org/docs/LangRef.html#addresses-of-basic-blocks
>> This value only has defined behavior when used as an operand to the ‘[indirectbr](https://llvm.org/docs/LangRef.html#i-indirectbr)’ or ‘[callbr](https://llvm.org/docs/LangRef.html#i-callbr)’instruction, or for comparisons against null. Pointer equality tests between labels addresses results in undefined behavior — though, again, comparison against null is ok, and no label is equal to the null pointer. This may be passed around as an opaque pointer sized value as long as the bits are not inspected. This allows ptrtoint and arithmetic to be performed on these values so long as the original value is reconstituted before the indirectbr or callbr instruction.

I guess https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html makes no statements about whether the comparisons of addresses of labels is well defined behavior. @pinskia confirmed this on IRC. So it's unspecified. @pinskia also pointed me to:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=28581
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=19969
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=44298

So, sorry @kees , closing as "what you're trying to do is unspecified behavior."

**Closed** 2022-03-14 22:29 UTC
Labels: llvm:optimizations

**Comment by kees** [comment] 2022-03-15 17:33
Totally reasonable. :) Thanks for looking at it!
