### ISSUE TITLE
P0429: A Standard flat_map

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#99665] opened 2024-07-19 16:52 UTC
See https://eel.is/c++draft/flat.map.

**Comment by ldionne** [comment] 2024-07-19 21:07
@huixie90 Is already working on a patch for this, we discussed it a few weeks ago. To avoid duplicate work.

**Comment by ldionne** [comment] 2024-10-02 17:16
Closing as a duplicate of the "official paper tracking issue" here: https://github.com/llvm/llvm-project/issues/105190

There's no difference other than the other issue was created via my scripts and added to the Conformance Table, and this one wasn't.

**Closed by ldionne** 2024-10-02 17:16 UTC
Labels: duplicate, libc++, c++23
