### ISSUE TITLE
clang-format crash with `QualifierAlignment: Left` and volatile keyword

### ISSUE THREAD

**Issue by Lorac** [llvm/llvm-project#58787] opened 2022-11-03 14:37 UTC
```
clang-format --version
Debian clang-format version 14.0.6-++20221029081924+f28c006a5895-1~exp1~20221029201936.206
```

Just have a file with this one-liner:
```
void Print() volatile const { }
```
Doesn't crash:
```
void Print() const { }
```

It looks like the `volatile` keyword makes clang-format crash

Stacktrace
```
 #0 0x00007f18e5432703 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (${SYSROOT_BIN}../lib/libLLVM-14.so+0x83a703)
 #1 0x00007f18e5430a00 llvm::sys::RunSignalHandlers() (${SYSROOT_BIN}../lib/libLLVM-14.so+0x838a00)
 #2 0x00007f18e5432b9a (${SYSROOT_BIN}../lib/libLLVM-14.so+0x83ab9a)
 #3 0x00007f18e472d9c0 (${SYSROOT_LIB}/libc.so.6+0x419c0)
 #4 0x00007f18eaf09611 clang::format::LeftRightQualifierAlignmentFixer::analyzeLeft(clang::SourceManager const&, clang::format::AdditionalKeywords const&, clang::tooling::Replacements&, clang::format::FormatToken const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, clang::tok::TokenKind) (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x27a9611)
 #5 0x00007f18eaf09d70 clang::format::LeftRightQualifierAlignmentFixer::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x27a9d70)
 #6 0x00007f18eaf124f1 clang::format::TokenAnalyzer::process() (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x27b24f1)
 #7 0x00007f18eaf0a1c7 (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x27aa1c7)
 #8 0x00007f18eaf07e27 clang::format::QualifierAlignmentFixer::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x27a7e27)
 #9 0x00007f18eaf124f1 clang::format::TokenAnalyzer::process() (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x27b24f1)
#10 0x00007f18eaefae39 (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x279ae39)
#11 0x00007f18eaee90a2 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x27890a2)
#12 0x00007f18eaee9e23 clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) (${SYSROOT_BIN}../lib/libclang-cpp.so.14+0x2789e23)
#13 0x0000563f24c13d2d (${SYSROOT_BIN}clang-format+0xbd2d)
#14 0x0000563f24c12296 (${SYSROOT_BIN}clang-format+0xa296)
#15 0x00007f18e471957b (${SYSROOT_LIB}/libc.so.6+0x2d57b)
#16 0x00007f18e4719630 __libc_start_main (${SYSROOT_LIB}/libc.so.6+0x2d630)
#17 0x0000563f24c0f465 (${SYSROOT_BIN}clang-format+0x7465)
```

[clang-format.txt](https://github.com/llvm/llvm-project/files/9930275/clang-format.txt)

**Comment by rymiel** [comment] 2022-11-03 15:01
Presumably a duplicate of https://github.com/llvm/llvm-project/issues/56696, fixed in clang-format 15

**Comment by Lorac** [comment] 2022-11-03 15:06
is it possible to backport it to clang-format-14?

**Comment by EugeneZelenko** [comment] 2022-11-03 15:10
Only 15 is supported. However, you could try to backport into your own branch.

**Comment by rymiel** [comment] 2022-11-03 17:47
Nothing to do here

**Closed by rymiel** 2022-11-03 17:47 UTC
Labels: clang-format
