### ISSUE TITLE
`-debug-info-kind=constructor -no-opaque-pointer` results in assertion

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#57179] opened 2022-08-16 18:11 UTC
```c
// RUN: %clang_cc1 -emit-obj -o /dev/null -debug-info-kind=constructor -no-opaque-pointers -x c %s

struct S {
  void *p;
};
struct S s[] = {
  { .p = (void *)0, },
};
extern struct S t __attribute__((__alias__("s")));
```

The `-no-opaque-pointer` results in an assertion due to an invalid cast here: https://github.com/apple/llvm-project/blob/stable/20220421/clang/lib/CodeGen/CodeGenModule.cpp#L5226-L5228

**Comment by compnerd** [comment] 2022-08-16 18:12
CC: @dwblaikie

**Comment by dwblaikie** [comment] 2022-08-16 20:36
Talked about this offline - @compnerd pointed out that it's probably missing bitcast skipping in  https://github.com/apple/llvm-project/blob/stable/20220421/clang/lib/CodeGen/CodeGenModule.cpp#L5228  and it looks like it's been broken since the alias debug info feature first landed earlier this year - even before opaque pointers were the default in clang. (ie: it's not like this was implemented after the opaque pointers fix and the issue was missed because of it - it was missed likely because the language features necessary to reproduce it aren't especially common to begin with)

**Closed** 2022-08-16 21:27 UTC
Labels: new issue
