### ISSUE TITLE
Constraint normalization of a parenthesized atomic constraint yields a different expression than an identical non-parenthesized atomic constraint

### ISSUE THREAD

**Issue by Matthewacon** [llvm/llvm-project#50748] opened 2021-08-08 01:13 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51406](https://llvm.org/bz51406) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Affected versions:
 - trunk
 - 12.0.1
 - 12.0.0
 - 11.0.1
 - 11.0.0
 - 10.0.1
 - 10.0.0
 - 9.0.1
 - 9.0.0

Driver cmdline:
Note: For versions not supporting -std=c++20, -std=c++2a was used.
 clang++ -std=c++20 -Werror -Wall -pedantic

Code:
```
 template<typename>
 concept B = true;

 template<typename T>
 requires (B<T>)
 struct A;

 template<typename T>
 requires B<T>
 struct A {};
```
https://godbolt.org/z/cT7b9za8o

Error:
```
 <source>:9:10: error: requires clause differs in template redeclaration
 requires B<T>
          ^
 <source>:5:10: note: previous template declaration is here
 requires (B<T>)
          ^
 1 error generated.
```

Notice that in the example the forward declaration of the template `A<T>` has a requires clause with a parenthesized atomic constraint, `(B<T>)`, whereas the definition of `A<T>` has the same requires clause, albeit non-parenthesized. After constraint normalization, both requires clauses should be equivalent, however, clang yields an error.

Notes:
 - GCC does not exhibit this issue.
 - MSVC has a similar issue that seems to be, incorrectly, fixed by converting the redeclaration of `A` into a partially specialized template.

**Comment by usx95** [comment] 2023-01-30 10:40
Duplicate of #60377.
(working as intended according to https://github.com/llvm/llvm-project/issues/60377#issuecomment-1408064741)

**Closed by usx95** 2023-01-30 10:40 UTC
Labels: c++, bugzilla, rejects-valid, concepts, confirmed

**Comment by fahadnayyar** [comment] 2023-01-30 14:46
@usx95 According to the first bullet in the Constraint normalization section at this cpp referencee page: https://en.cppreference.com/w/cpp/language/constraints ?
`The normal form of an expression (E) is the normal form of E;`

This doesn't look ill formed.
