### ISSUE TITLE
[C++20] [Modules] BMIs for implementation units cannot be loaded conditionally via `-fmodule-file=NAME=...`

### ISSUE THREAD

**Issue by aaronmondal** [llvm/llvm-project#57293] opened 2022-08-23 09:08 UTC
I am not sure whether this is a bug or working as intended. I suspect the former.

Consider a module with separate interface and implementation:
```bash
echo "export module mymodule;" > mymodule.cppm
echo "module mymodule;" > mymodule.cpp
```

This compiles fine when using the following commands (First produces `mymodule.cppm`, second produces `mymodule.o`.)
```bash
clang++ -std=c++20 mymodule.cppm --precompile
clang++ -std=c++20 -fmodule-file=mymodule.pcm mymodule.cpp -c
```
Clang will always load module files specified via `-fmodule-file` when omitting the name. So it makes sense that this works.

However, trying to load the precompiled module interface conditionally by declaring the modulename fails:
```bash
clang++ -fmodule-file=mymodule=mymodule.pcm -std=c++20 mymodule.cpp -c
# error: definition of module 'mymodule' is not available; use -fmodule-file= to specify path to precompiled module interface
```
It seems like module name resolution does not work in this case.

Shouldn't clang autodetect the correct module interface just from its name in the `-fmodule-file` flag?

**Comment by ChuanqiXu9** [comment] 2022-08-25 03:09
I prefer this is a defect instead of a bug and I am not sure if I understand your intention properly. What's the benefit of the second command line style?

**Comment by aaronmondal** [comment] 2022-08-26 07:35
@ChuanqiXu9 The docs for `-fmodule-file=[<name>=]<file>`:

>> Specify the mapping of module names to precompiled module files. If the name is omitted, then the module file is loaded whether actually required or not. If the name is specified, then the mapping is treated as another prebuilt module search mechanism (in addition to -fprebuilt-module-path) and the module is only loaded if required. Note that in this case the specified file also overrides this module’s paths that might be embedded in other precompiled module files.

So with the second style we get conditional loading, while with the first style we load everything conditionally. I'm not sure what the use case for path overriding is. Maybe this is useful for situations where we have different compilation environments for separate parts of the same module.

We are integrating modules into a ruleset for Bazel. To differentiate between Bazel target names, File names and module names we want to use the second style so that command lines do less work and are overall more readable/more easily greppable. The bug/feature request described above currently requires us to mix both styles just to handle the described case.

**Comment by ChuanqiXu9** [comment] 2022-08-26 07:44
@aaronmondal oh, my bad. This is another example that users get confused about the standard c++ modules and clang modules extension. Simply, the document you're visiting is for clang modules extension. And the document for standard c++ modules are preparing in https://reviews.llvm.org/D131388. (If you're interested, you could help to review the docs too.)

And since the implementation of standard c++ modules are based on clang modules, so there are many similar options. But they have some different semantics after all. And I didn't include all the options in clang modules in standard c++ modules (since I haven't verified them). 

Currently the implementation of standard c++ modules are still in the early ages, and the build system writers are the important users. So if you guys have any suggestion or using experience, feel free to contribute. 

Hope this helps.

**Comment by aaronmondal** [comment] 2022-08-27 12:10
@ChuanqiXu9 Thanks for the link :blush: Updated title according to the scheme proposed in the differential.

**Comment by aaronmondal** [comment] 2022-09-06 14:41
I believe this is a bug. According to https://eel.is/c++draft/module#unit-8,
> A [module-declaration](https://eel.is/c++draft/module#nt:module-declaration) that contains neither an export-keyword nor a [module-partition](https://eel.is/c++draft/module#nt:module-partition) implicitly imports the primary module interface unit of the module as if by a [module-import-declaration](https://eel.is/c++draft/module#nt:module-import-declaration)[.](https://eel.is/c++draft/module#unit-8.sentence-1)

At least from a user-point of view, Clang not recognizing `-fmodule-file=mymodule=mymodule_interface.pcm` for the module implementation unit leads to the notion that `module mymodule;` does not implicitly ``import mymodule;``.

**Comment by ChuanqiXu9** [comment] 2022-09-07 02:07
To be honest, I still think it is an improvement or at most a defect. The standard specification doesn't care about the command lines. As long as the compiler accept the standard codes in any way, the behavior shouldn't be wrong. But I totally agree it may be bad when we scale up.

**Comment by mathstuf** [comment] 2022-09-20 13:50
What kinds of control are there over the output filename for the module available without the `-fmodule-path=modname=path` spelling now? Is the output filename part of Clang's stable API? What about module names which are not valid paths on the hosting filesystem (e.g., `foo:bar` on Windows)? What are the transforms performed for such paths?

**Comment by ChuanqiXu9** [comment] 2022-09-20 15:02
> What kinds of control are there over the output filename for the module available without the -fmodule-path=modname=path spelling now? 

When generating BMI with `--precompile` option, the filename is controlled by `-o` option. After https://reviews.llvm.org/D134267 landed, the behavior is described in https://reviews.llvm.org/D134269.

> Is the output filename part of Clang's stable API? 

I am not sure if I misunderstood you. Since this is not related to API. I guess you're talking about if the compiler behavior is related to the filename of the BMI (or not)?

> What about module names which are not valid paths on the hosting filesystem (e.g., foo:bar on Windows)? What are the transforms performed for such paths?

For such cases, it will be transformed to `foo-bar`. This is documented. And I think all other names (for named modules) should be avialable generally.

**Comment by mathstuf** [comment] 2022-09-20 15:39
So the "split compilation" has control over the BMI path, but the combined one (part of your `MyP1689` branch) doesn't?

**Comment by ChuanqiXu9** [comment] 2022-09-21 02:03
> So the "split compilation" has control over the BMI path, but the combined one (part of your `MyP1689` branch) doesn't?

The combined one could control the path by the combination of `-fmodules-cache-path` and `-fmodule-name` options. See the documented change in https://reviews.llvm.org/D134269

**Comment by mathstuf** [comment] 2022-09-21 22:20
That doesn't seem to work…I'm not seeing the `.pcm` file written out for this source file:

```cpp
export module importable;

export int from_import()
{
  return 0;
}
```

This command line:

```
/home/boeckb/misc/root/clang-trtbd/bin/clang++ -g -std=gnu++20 -MD -MT CMakeFiles/simple.dir/importable.cxx.o -MF CMakeFiles/simple.dir/importable.cxx.o.d @CMakeFiles/simple.dir/importable.cxx.o.modmap -o CMakeFiles/simple.dir/importable.cxx.o -c /home/boeckb/code/depot/group-bld/cmake/src/Tests/RunCMake/CXXModules/examples/simple/importable.cxx
```

That response file contains:

```
-fmodules-cache-path=CMakeFiles/simple.dir
-fmodule-name=importable
```

**Comment by ChuanqiXu9** [comment] 2022-09-22 02:01
> That doesn't seem to work…I'm not seeing the `.pcm` file written out for this source file:
> 
> ```c++
> export module importable;
> 
> export int from_import()
> {
>   return 0;
> }
> ```
> 
> This command line:
> 
> ```
> /home/boeckb/misc/root/clang-trtbd/bin/clang++ -g -std=gnu++20 -MD -MT CMakeFiles/simple.dir/importable.cxx.o -MF CMakeFiles/simple.dir/importable.cxx.o.d @CMakeFiles/simple.dir/importable.cxx.o.modmap -o CMakeFiles/simple.dir/importable.cxx.o -c /home/boeckb/code/depot/group-bld/cmake/src/Tests/RunCMake/CXXModules/examples/simple/importable.cxx
> ```
> 
> That response file contains:
> 
> ```
> -fmodules-cache-path=CMakeFiles/simple.dir
> -fmodule-name=importable
> ```

Do you use the clang from https://github.com/ChuanqiXu9/llvm-project/tree/MyP1689? Currently the behavior is not adopted in the trunk. The patch is being reviewed at: https://reviews.llvm.org/D134267

Oh, wait, could you please change ` -std=gnu++20` to `-std=c++20`? I remember there is a defect.

**Closed** 2023-02-08 08:45 UTC
Labels: clang:driver, clang:modules

**Comment by Arthapz** [comment] 2023-02-10 15:27
Is this really fixed ?

```cpp
import <string>;

auto main() -> int {
    std::string{};
}
```
/usr/bin/clang -Qunused-arguments -m64 -std=c++2b -stdlib=libc++ -fexperimental-library -fmodules -fno-implicit-module-maps -fmodules-cache-path=build/stlmodules/cache/release -c -Wno-everything -o build/stlmodules/cache/release/string.pcm -x c++-system-header string -fmodule-name=string

/usr/bin/clang -c -Qunused-arguments -m64 -std=c++2b -stdlib=libc++ -fexperimental-library -fmodules -fno-implicit-module-maps -fmodule-file=string=build/stlmodules/cache/release/string.pcm -o build/.objs/Foo/linux/x86_64/release/src/main.cpp.o src/main.cpp

error: src/main.cpp:1:8: error: header file <string> (aka '/usr/bin/../include/c++/v1/string') cannot be imported because it is not known to be a header unit
import <string>;
       ^
src/main.cpp:4:5: error: use of undeclared identifier 'std'
    std::string{};
    ^
2 errors generated.
```

**Comment by ChuanqiXu9** [comment] 2023-02-11 04:58
@Arthapz yes, this is already fixed. The title of the issue says "implementation unit". And your reproducer is about header units. Note that we can't use `-fmodule-file=<module-name>=<path/to/BMI>` for header units since header units have no name technically.

**Comment by ChuanqiXu9** [comment] 2023-02-11 05:08
@Arthapz BTW, I noticed that you always use "-fmodules -fno-implicit-module-maps" in the reproducer of your command line. Is this intentional? I mean if you only want to use C++20 modules, this is unnecessary and maybe a risk for you since the mixed use of c++20 modules and clang modules are not well tested. But it is fine if you want to use them together intentionally.

**Comment by aaronmondal** [comment] 2023-02-16 15:42
It indeed works now. Thanks a lot, this makes it easier to implement it in build systems (e.g. https://github.com/eomii/rules_ll/commit/484e4e1aa5ffae2e7a3155f5e3df5da46ca68715) :heart:
