### ISSUE TITLE
Error when using iostream as module 

### ISSUE THREAD

**Issue by miyoku157** [llvm/llvm-project#71682] opened 2023-11-08 14:28 UTC
Hi, 
I'm trying to switch from using headers to using modules and i tried just to switch an `#include <iostream` to `import <iostream>;`
To do so, i'm building my program on c++23 with cmake 3.28.0-rc4, the ninja generator 1.11.1 and clang 16.0.6.
I added the compile option: -fmodules to look for modules and i got this error stack:

```
[main] Building folder: cppgame 
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /Development/cppgame/build --config Debug --target all --
[build] [2/6  16% :: 0.451] Scanning /Development/cppgame/src/Hvulk.cpp for CXX dependencies
[build] FAILED: CMakeFiles/sdvulk.dir/src/Hvulk.cpp.o.ddi 
[build] "/usr/bin/clang-scan-deps" -format=p1689 -- /usr/bin/clang++  -I/Development/cppgame/build/_deps/sdl-build/include -I/Development/cppgame/build/_deps/sdl-src/include -I/Development/cppgame/build/_deps/sdl-src/include/SDL3 -g -std=gnu++2b -fmodules -idirafter/Development/cppgame/build/_deps/sdl-src/src/video/khronos -x c++ /Development/cppgame/src/Hvulk.cpp -c -o CMakeFiles/sdvulk.dir/src/Hvulk.cpp.o -MT CMakeFiles/sdvulk.dir/src/Hvulk.cpp.o.ddi -MD -MF CMakeFiles/sdvulk.dir/src/Hvulk.cpp.o.ddi.d > CMakeFiles/sdvulk.dir/src/Hvulk.cpp.o.ddi
[build] LLVM ERROR: unexpected call to lookupModuleOutput
[build] PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
[build]  #0 0x00007fd5dda1f503 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM-16.so+0xe1f503)
[build]  #1 0x00007fd5dda1c7bf llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-16.so+0xe1c7bf)
[build]  #2 0x00007fd5dda1c90d (/usr/lib/libLLVM-16.so+0xe1c90d)
[build]  #3 0x00007fd5dc65c710 (/usr/lib/libc.so.6+0x3e710)
[build]  #4 0x00007fd5dc6ac83c (/usr/lib/libc.so.6+0x8e83c)
[build]  #5 0x00007fd5dc65c668 gsignal (/usr/lib/libc.so.6+0x3e668)
[build]  #6 0x00007fd5dc6444b8 abort (/usr/lib/libc.so.6+0x264b8)
[build]  #7 0x00007fd5dd74d25f (/usr/lib/libLLVM-16.so+0xb4d25f)
[build]  #8 0x00007fd5dd91f19e (/usr/lib/libLLVM-16.so+0xd1f19e)
[build]  #9 0x00007fd5e7223bec (/usr/lib/libclang-cpp.so.16+0x2223bec)
[build] #10 0x00007fd5e725b9eb clang::tooling::dependencies::ModuleDepCollector::addOutputPaths(clang::CompilerInvocation&, clang::tooling::dependencies::ModuleDeps&) (/usr/lib/libclang-cpp.so.16+0x225b9eb)
[build] #11 0x00007fd5e72605f5 clang::tooling::dependencies::ModuleDepCollectorPP::handleTopLevelModule(clang::Module const*) (/usr/lib/libclang-cpp.so.16+0x22605f5)
[build] #12 0x00007fd5e7260a57 clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile() (/usr/lib/libclang-cpp.so.16+0x2260a57)
[build] #13 0x00007fd5e711e82e clang::FrontendAction::EndSourceFile() (/usr/lib/libclang-cpp.so.16+0x211e82e)
[build] #14 0x00007fd5e70c0d85 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.16+0x20c0d85)
[build] #15 0x00007fd5e725e50f (/usr/lib/libclang-cpp.so.16+0x225e50f)
[build] #16 0x00007fd5e7292d09 clang::tooling::ToolInvocation::run() (/usr/lib/libclang-cpp.so.16+0x2292d09)
[build] #17 0x00007fd5e72597d5 clang::tooling::dependencies::DependencyScanningWorker::computeDependencies(llvm::StringRef, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, clang::tooling::dependencies::DependencyConsumer&, clang::DiagnosticConsumer&, std::optional<llvm::StringRef>) (/usr/lib/libclang-cpp.so.16+0x22597d5)
[build] #18 0x00007fd5e7259d7c clang::tooling::dependencies::DependencyScanningWorker::computeDependencies(llvm::StringRef, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, clang::tooling::dependencies::DependencyConsumer&, std::optional<llvm::StringRef>) (/usr/lib/libclang-cpp.so.16+0x2259d7c)
[build] #19 0x00007fd5e725abb3 clang::tooling::dependencies::DependencyScanningTool::getP1689ModuleDependencyFile(clang::tooling::CompileCommand const&, llvm::StringRef, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) (/usr/lib/libclang-cpp.so.16+0x225abb3)
[build] #20 0x0000561ccd1c115c (/usr/bin/clang-scan-deps+0x1115c)
[build] #21 0x0000561ccd1c54b2 (/usr/bin/clang-scan-deps+0x154b2)
[build] #22 0x00007fd5dd9a59f4 llvm::ThreadPool::processTasks(llvm::ThreadPoolTaskGroup*) (/usr/lib/libLLVM-16.so+0xda59f4)
[build] #23 0x00007fd5dd9a63ea (/usr/lib/libLLVM-16.so+0xda63ea)
[build] #24 0x00007fd5dc6aa9eb (/usr/lib/libc.so.6+0x8c9eb)
[build] #25 0x00007fd5dc72e7cc (/usr/lib/libc.so.6+0x1107cc)
[build] [2/6  33% :: 0.478] Scanning /Development/cppgame/src/main.cpp for CXX dependencies
[build] FAILED: CMakeFiles/sdvulk.dir/src/main.cpp.o.ddi 
[build] "/usr/bin/clang-scan-deps" -format=p1689 -- /usr/bin/clang++  -I/Development/cppgame/build/_deps/sdl-build/include -I/Development/cppgame/build/_deps/sdl-src/include -I/Development/cppgame/build/_deps/sdl-src/include/SDL3 -g -std=gnu++2b -fmodules -idirafter/Development/cppgame/build/_deps/sdl-src/src/video/khronos -x c++ /Development/cppgame/src/main.cpp -c -o CMakeFiles/sdvulk.dir/src/main.cpp.o -MT CMakeFiles/sdvulk.dir/src/main.cpp.o.ddi -MD -MF CMakeFiles/sdvulk.dir/src/main.cpp.o.ddi.d > CMakeFiles/sdvulk.dir/src/main.cpp.o.ddi
[build] LLVM ERROR: unexpected call to lookupModuleOutput
[build] PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
[build]  #0 0x00007f9c5a61f503 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM-16.so+0xe1f503)
[build]  #1 0x00007f9c5a61c7bf llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-16.so+0xe1c7bf)
[build]  #2 0x00007f9c5a61c90d (/usr/lib/libLLVM-16.so+0xe1c90d)
[build]  #3 0x00007f9c5925c710 (/usr/lib/libc.so.6+0x3e710)
[build]  #4 0x00007f9c592ac83c (/usr/lib/libc.so.6+0x8e83c)
[build]  #5 0x00007f9c5925c668 gsignal (/usr/lib/libc.so.6+0x3e668)
[build]  #6 0x00007f9c592444b8 abort (/usr/lib/libc.so.6+0x264b8)
[build]  #7 0x00007f9c5a34d25f (/usr/lib/libLLVM-16.so+0xb4d25f)
[build]  #8 0x00007f9c5a51f19e (/usr/lib/libLLVM-16.so+0xd1f19e)
[build]  #9 0x00007f9c63e23bec (/usr/lib/libclang-cpp.so.16+0x2223bec)
[build] #10 0x00007f9c63e5b9eb clang::tooling::dependencies::ModuleDepCollector::addOutputPaths(clang::CompilerInvocation&, clang::tooling::dependencies::ModuleDeps&) (/usr/lib/libclang-cpp.so.16+0x225b9eb)
[build] #11 0x00007f9c63e605f5 clang::tooling::dependencies::ModuleDepCollectorPP::handleTopLevelModule(clang::Module const*) (/usr/lib/libclang-cpp.so.16+0x22605f5)
[build] #12 0x00007f9c63e60a57 clang::tooling::dependencies::ModuleDepCollectorPP::EndOfMainFile() (/usr/lib/libclang-cpp.so.16+0x2260a57)
[build] #13 0x00007f9c63d1e82e clang::FrontendAction::EndSourceFile() (/usr/lib/libclang-cpp.so.16+0x211e82e)
[build] #14 0x00007f9c63cc0d85 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.16+0x20c0d85)
[build] #15 0x00007f9c63e5e50f (/usr/lib/libclang-cpp.so.16+0x225e50f)
[build] #16 0x00007f9c63e92d09 clang::tooling::ToolInvocation::run() (/usr/lib/libclang-cpp.so.16+0x2292d09)
[build] #17 0x00007f9c63e597d5 clang::tooling::dependencies::DependencyScanningWorker::computeDependencies(llvm::StringRef, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, clang::tooling::dependencies::DependencyConsumer&, clang::DiagnosticConsumer&, std::optional<llvm::StringRef>) (/usr/lib/libclang-cpp.so.16+0x22597d5)
[build] #18 0x00007f9c63e59d7c clang::tooling::dependencies::DependencyScanningWorker::computeDependencies(llvm::StringRef, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&, clang::tooling::dependencies::DependencyConsumer&, std::optional<llvm::StringRef>) (/usr/lib/libclang-cpp.so.16+0x2259d7c)
[build] #19 0x00007f9c63e5abb3 clang::tooling::dependencies::DependencyScanningTool::getP1689ModuleDependencyFile(clang::tooling::CompileCommand const&, llvm::StringRef, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) (/usr/lib/libclang-cpp.so.16+0x225abb3)
[build] #20 0x0000560280e3615c (/usr/bin/clang-scan-deps+0x1115c)
[build] #21 0x0000560280e3a4b2 (/usr/bin/clang-scan-deps+0x154b2)
[build] #22 0x00007f9c5a5a59f4 llvm::ThreadPool::processTasks(llvm::ThreadPoolTaskGroup*) (/usr/lib/libLLVM-16.so+0xda59f4)
[build] #23 0x00007f9c5a5a63ea (/usr/lib/libLLVM-16.so+0xda63ea)
[build] #24 0x00007f9c592aa9eb (/usr/lib/libc.so.6+0x8c9eb)
[build] #25 0x00007f9c5932e7cc (/usr/lib/libc.so.6+0x1107cc)
[build] ninja: build stopped: subcommand failed.
[proc] The command: /usr/local/bin/cmake --build /Development/cppgame/build --config Debug --target all -- exited with code: 1
[driver] Build completed: 00:00:00.513
[build] Build finished with exit code 1

```
Am i doing something wrong here?

**Comment by EugeneZelenko** [comment] 2023-11-08 15:01
Could you please try 17 or `main` branch? https://godbolt.org should be helpful.

**Comment by miyoku157** [comment] 2023-11-09 09:21
Hi, I've tried LLVM 17.0.4 with these options inside cmake : `add_compile_options(-fmodules -std=c++2b)`; I don't have the stack error anymore which must mean my error is already solved. 
Nevertheless, i still have an error trying to use <iostream> as a module:
```
error: header file <iostream> (aka '/usr/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/iostream') cannot be imported because it is not known to be a header unit
[build]     8 | import <iostream>;
```

**Comment by ChuanqiXu9** [comment] 2023-11-09 09:30
This may be a duplicate of https://github.com/llvm/llvm-project/issues/65903

**Closed by ChuanqiXu9** 2023-11-09 09:30 UTC
Labels: clang:modules, crash
