### ISSUE TITLE
Segmentation fault in clang

### ISSUE THREAD

**Issue by rkaminsk** [llvm/llvm-project#81407] opened 2024-02-11 10:34 UTC
There is a segmentation fault when trying to compile the following program:
```c++
namespace N {

// Note 1: changing to R const &x , and
template <int N, class R, class A>
auto get_attribute(R const x) -> A = delete;

struct X {
    int x = 0;
};

// Note 2: changing to decltype(x.x) fixes the problem and works in both clang and gcc
template <>
auto get_attribute<0>(X const &x) -> decltype(auto) { return x.x; }

}
```

From the crash reporter:
```
# Crash reproducer for Ubuntu clang version 17.0.6 (++20231209124227+6009708b4367-1~exp1~20231209124336.77)
"/usr/lib/llvm-17/bin/clang" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "aggregate.cc" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-debug-info-kind=constructor" "-dwarf-version=5" "-debugger-tuning=gdb" "-sys-header-deps" "-std=c++20" "-fdeprecated-macro" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "bug.cpp"
```

I extracted the relevant parts of the produced debug files. Let me know if you need more info.

PS: clang should probably report an error, instead.

**Comment by DimitryAndric** [comment] 2024-02-11 12:57
Looks like your clang binary was built without assertions, because if assertions are enabled, you get:

```text
Assertion failed: (!DT.isNull() && "Undeduced types shouldn't reach here."), function UnwrapTypeForDebugInfo, file /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CGDebugInfo.cpp, line 3482.
PLEASE submit a bug report to https://bugs.freebsd.org/submit/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name aggregate.cc -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -sys-header-deps -std=c++20 -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ pr81407.cpp
1.      <eof> parser at end of file
2.      pr81407.cpp:1:11: LLVM IR generation of declaration 'N'
3.      pr81407.cpp:13:6: Generating code for declaration 'N::get_attribute'
 #0 0x0000000005a79d41 PrintStackTrace /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0x0000000005a77d35 RunSignalHandlers /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #2 0x0000000005a7a342 SignalHandler /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
 #3 0x000000082b6f1540 handle_signal /share/dim/src/freebsd/llvm-18-update/lib/libthr/thread/thr_sig.c:0:3
 #4 0x000000082b6f0afb thr_sighandler /share/dim/src/freebsd/llvm-18-update/lib/libthr/thread/thr_sig.c:245:1
 #5 0x000000082826d2d3 ([vdso]+0x2d3)
 #6 0x000000082f64453a thr_kill /usr/obj/share/dim/src/freebsd/llvm-18-update/amd64.amd64/lib/libsys/thr_kill.S:4:0
 #7 0x000000082e3d2a74 _raise /share/dim/src/freebsd/llvm-18-update/lib/libc/gen/raise.c:0:10
 #8 0x000000082e485ed9 abort /share/dim/src/freebsd/llvm-18-update/lib/libc/stdlib/abort.c:67:17
 #9 0x000000082e3b6421 (/lib/libc.so.7+0x9c421)
#10 0x0000000002d38bfb UnwrapTypeForDebugInfo /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CGDebugInfo.cpp:0:7
#11 0x0000000002d28400 getOrCreateType /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CGDebugInfo.cpp:3538:6
#12 0x0000000002d314bb CollectTemplateParams /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CGDebugInfo.cpp:2130:11
#13 0x0000000002d3a11e collectFunctionDeclProps /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CGDebugInfo.cpp:3877:18
#14 0x0000000002d3cc54 starts_with /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/include/llvm/ADT/StringRef.h:258:14
#15 0x0000000002d3cc54 emitFunctionStart /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CGDebugInfo.cpp:4261:12
#16 0x0000000002da24d2 ShouldInstrumentFunction /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:534:8
#17 0x0000000002da24d2 StartFunction /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:1053:7
#18 0x0000000002da5544 GenerateCode /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:1436:3
#19 0x00000000027b82f3 EmitGlobalFunctionDefinition /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:5834:3
#20 0x00000000027b05a1 EmitGlobalDefinition /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:0:12
#21 0x00000000027b4e13 EmitGlobal /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:3810:5
#22 0x00000000027af077 EmitTopLevelDecl /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:6728:5
#23 0x00000000027bed3b asInt /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:41:5
#24 0x00000000027bed3b operator long /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:45:48
#25 0x00000000027bed3b getPointer /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/include/llvm/ADT/PointerIntPair.h:94:58
#26 0x00000000027bed3b getNextDeclInContext /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/include/clang/AST/DeclBase.h:450:62
#27 0x00000000027bed3b operator++ /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/include/clang/AST/DeclBase.h:2298:26
#28 0x00000000027bed3b EmitDeclContext /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenModule.cpp:6696:16
#29 0x000000000315700c HandleTopLevelDecl /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/ModuleBuilder.cpp:189:73
#30 0x000000000314d546 HandleTopLevelDecl /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:208:7
#31 0x0000000003adf3e9 ParseAST /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/Parse/ParseAST.cpp:167:11
#32 0x000000000341337f Execute /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1073:10
#33 0x000000000334409d getPtr /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/include/llvm/Support/Error.h:276:42
#34 0x000000000334409d operator bool /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/llvm/include/llvm/Support/Error.h:239:16
#35 0x000000000334409d ExecuteAction /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1057:23
#36 0x00000000034ddd8c ExecuteCompilerInvocation /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:272:25
#37 0x0000000002729516 cc1_main /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/tools/driver/cc1_main.cpp:294:15
#38 0x00000000027387ab ExecuteCC1Tool /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/tools/driver/driver.cpp:365:12
#39 0x0000000002737897 clang_main /share/dim/src/freebsd/llvm-18-update/contrib/llvm-project/clang/tools/driver/driver.cpp:405:12
#40 0x0000000002734fad main /share/dim/src/freebsd/llvm-18-update/usr.bin/clang/clang/clang-driver.cpp:17:10
#41 0x000000082e3a7b0a __libc_start1 /share/dim/src/freebsd/llvm-18-update/lib/libc/csu/libc_start1.c:157:2
Abort trap
```

This looks pretty much like a duplicate of #56652 (and #59296).

**Closed by DimitryAndric** 2024-02-11 12:57 UTC
Labels: duplicate, clang:codegen, crash-on-invalid, debuginfo
