### ISSUE TITLE
[clang-format]Compile switch follows code indentation?

### ISSUE THREAD

**Issue by zeerd** [llvm/llvm-project#92488] opened 2024-05-17 02:24 UTC
I'd like the code to be things like below for more readable :

```c
void foo(void)
{
    #ifdef LINUX
        linux_foo();
    #elif QNX
        qnx_foo();
    #elif ANDROID
        android_foo();
    #else
        #error "Not implemented"
    #endif
}
```

But now, it's like(this looks very messy) :

```c
void foo(void)
{
#ifdef LINUX
    linux_foo();
#elif QNX
    qnx_foo();
#elif ANDROID
    android_foo();
#else
#error "Not implemented"
#endif
}
```

I did not find any option to make this . Am I missing something or it real not supported?

**Comment by rymiel** [comment] 2024-06-25 13:10
It is not yet supported, duplicate of #47997

**Closed by rymiel** 2024-06-25 13:10 UTC
Labels: clang-format
