### ISSUE TITLE
lld silently creates an non-working executable if both .ctors and .init_array exist

### ISSUE THREAD

**Issue by rui314** [llvm/llvm-project#68071] opened 2023-10-03 07:11 UTC
If input object files contain both `.ctors` and `.init_array`, the result would contain both `.ctors` and `.init_array`, and the result is very likely to crash because some initializer are not executed. We may want to emit a warning from lld if the output may not work due to this issue.

**Comment by christopherbate** [comment] 2023-11-08 05:44
Actually I see that the work was done, but just not merged.  https://reviews.llvm.org/D35509

Development was tracked here: https://github.com/llvm/llvm-project/issues/30572

At the end of the thread, the author states:

> CUDA 11 has finally switched from .ctors to .init_array! Yet in order to support older CUDAs for a while I've ported my patch to LLD 11 (and fixed the sorting order of sections — the previous patch has sorted .ctors.64534 as .init_array.64534 rather than as .init_array.1001). (I do not propose to merge this patch into LLD due to the lack of interested users.).

Which is ironic because I just inspected CUDA 12.2 and 12.3 linux binaries and they include `.ctor` sections in several static libs.

**Comment by MaskRay** [comment] 2023-12-09 21:28
Duplicate of #30572 and there is nothing changed. I understand the frustration but as of 2023 this appears a CUDA specific issue. You can run `objcopy --rename-section .ctors=.init_array --rename-section .dtors=.fini_array $file` (https://maskray.me/blog/2021-11-07-init-ctors-init-array) or use `OVERWRITE_SECTIONS` to place `.ctors` into `.init_array`.

**Closed by MaskRay** 2023-12-09 21:28 UTC
Labels: lld, miscompilation
