### ISSUE TITLE
clang14/mips crashes compiling fio on linux

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#54044] opened 2022-02-24 00:51 UTC
attached testcase is failing with clang14 but compiles fine with clang13

```
fatal error: error in backend: Cannot select: 0x55de74d46ac0: f32 = fabs nnan ninf nsz arcp contract afn reassoc 0x55de74cdecf0, t/btrace2fio.c:883:8 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
  0x55de74cdecf0: f32 = fsub nnan ninf nsz arcp contract afn reassoc 0x55de74cdf6b0, 0x55de74cdf098, t/btrace2fio.c:882:18 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
    0x55de74cdf6b0: f32 = fp_round 0x55de74cd3da0, TargetConstant:i32<0>, t/btrace2fio.c:880:12 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
      0x55de74cd3da0: f64 = fdiv nnan ninf nsz arcp contract afn reassoc 0x55de74f6f158, 0x55de74cdf100, t/btrace2fio.c:880:45 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
        0x55de74f6f158: f64 = fmul nnan ninf nsz arcp contract afn reassoc 0x55de74cdf510, 0x55de74cdf718, t/btrace2fio.c:880:36 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
          0x55de74cdf510: f64 = fp_extend 0x55de74cd36b8, t/btrace2fio.c:880:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
            0x55de74cd36b8: f32,ch,glue = CopyFromReg 0x55de74cd3858, Register:f32 $f0, 0x55de74cd3858:1, t/btrace2fio.c:880:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
              0x55de74cdf370: f32 = Register $f0
              0x55de74cd3858: ch,glue = callseq_end 0x55de74d46988, TargetConstant:i32<16>, TargetConstant:i32<0>, 0x55de74d46988:1, t/btrace2fio.c:880:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
                0x55de74f6f7d8: i32 = TargetConstant<16>
                0x55de74f6fdf0: i32 = TargetConstant<0>
                0x55de74d46988: ch,glue = MipsISD::JmpLink 0x55de74d46718, 0x55de74d46c60, Register:i32 $a0, Register:i32 $a1, Register:i32 $gp, RegisterMask:Untyped, 0x55de74d46648:1, t/btrace2fio.c:880:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
                  0x55de74d46c60: i32,ch = load<(load (s32) from call-entry &__floatundisf)> 0x55de74d46718, 0x55de74f6fb80, undef:i32, t/btrace2fio.c:880:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]


                  0x55de74f1d3d8: i32 = Register $a0
                  0x55de74d46e00: i32 = Register $a1
                  0x55de74f6fe58: i32 = Register $gp
                  0x55de74f1d780: Untyped = RegisterMask
                  0x55de74d46648: ch,glue = CopyToReg 0x55de74d46850, Register:i32 $gp, Register:i32 %245, 0x55de74d46850:1, t/btrace2fio.c:880:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]



          0x55de74cdf718: f64,ch = load<(load (s64) from constant-pool)> 0x55de74cf1f88, 0x55de74f6f430, undef:i32
            0x55de74f6f430: i32 = add 0x55de74cdee28, 0x55de74cdf648
              0x55de74cdee28: i32,ch = load<(load (s32) from got)> 0x55de74cf1f88, 0x55de74d46fa0, undef:i32
                0x55de74d46fa0: i32 = MipsISD::Wrapper Register:i32 %245, TargetConstantPool:i32<double 1.000000e+02> 0 [TF=1]
                  0x55de74cde948: i32 = Register %245
                  0x55de74cd3788: i32 = TargetConstantPool<double 1.000000e+02> 0 [TF=1]
                0x55de74cd3990: i32 = undef
              0x55de74cdf648: i32 = MipsISD::Lo TargetConstantPool:i32<double 1.000000e+02> 0 [TF=5]
                0x55de74cd4280: i32 = TargetConstantPool<double 1.000000e+02> 0 [TF=5]
            0x55de74cd3990: i32 = undef
        0x55de74cdf100: f64 = fp_extend 0x55de74f1d8b8, t/btrace2fio.c:880:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
          0x55de74f1d8b8: f32 = fp_round 0x55de74f6ff90, Constant:i32<0>, t/btrace2fio.c:880:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
            0x55de74f6ff90: f64 = fsub 0x55de74cdf030, 0x55de74f1d370, t/btrace2fio.c:880:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
              0x55de74cdf030: f64,ch = load<(load (s64) from %stack.9)> 0x55de74f6fbe8, FrameIndex:i32<9>, undef:i32, t/btrace2fio.c:880:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
                0x55de74cdeef8: i32 = FrameIndex<9>
                0x55de74cd3990: i32 = undef
              0x55de74f1d370: f64,ch = load<(load (s64) from constant-pool)> 0x55de74cf1f88, 0x55de74cd3928, undef:i32
                0x55de74cd3928: i32 = add 0x55de74f1dac0, 0x55de74f6f1c0
                  0x55de74f1dac0: i32,ch = load<(load (s32) from got)> 0x55de74cf1f88, 0x55de74d472e0, undef:i32


                  0x55de74f6f1c0: i32 = MipsISD::Lo TargetConstantPool:i32<double 0x4330000000000000> 0 [TF=5]

                0x55de74cd3990: i32 = undef
            0x55de74cdeb50: i32 = Constant<0>
      0x55de74f6fdf0: i32 = TargetConstant<0>
    0x55de74cdf098: f32 = fp_round 0x55de74d470d8, TargetConstant:i32<0>, t/btrace2fio.c:881:12 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
      0x55de74d470d8: f64 = fdiv nnan ninf nsz arcp contract afn reassoc 0x55de74d47140, 0x55de74d467e8, t/btrace2fio.c:881:45 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
        0x55de74d47140: f64 = fmul nnan ninf nsz arcp contract afn reassoc 0x55de74cde8e0, 0x55de74cdf718, t/btrace2fio.c:881:36 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
          0x55de74cde8e0: f64 = fp_extend 0x55de74f6fd88, t/btrace2fio.c:881:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
            0x55de74f6fd88: f32,ch,glue = CopyFromReg 0x55de74d46780, Register:f32 $f0, 0x55de74d46780:1, t/btrace2fio.c:881:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
              0x55de74cdf370: f32 = Register $f0
              0x55de74d46780: ch,glue = callseq_end 0x55de74d46510, TargetConstant:i32<16>, TargetConstant:i32<0>, 0x55de74d46510:1, t/btrace2fio.c:881:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
                0x55de74f6f7d8: i32 = TargetConstant<16>
                0x55de74f6fdf0: i32 = TargetConstant<0>
                0x55de74d46510: ch,glue = MipsISD::JmpLink 0x55de74cd3580, 0x55de74f6fd20, Register:i32 $a0, Register:i32 $a1, Register:i32 $gp, RegisterMask:Untyped, 0x55de74d47210:1, t/btrace2fio.c:881:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
                  0x55de74f6fd20: i32,ch = load<(load (s32) from call-entry &__floatundisf)> 0x55de74cd3580, 0x55de74f6fb80, undef:i32, t/btrace2fio.c:881:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]


                  0x55de74f1d3d8: i32 = Register $a0
                  0x55de74d46e00: i32 = Register $a1
                  0x55de74f6fe58: i32 = Register $gp
                  0x55de74f1d780: Untyped = RegisterMask
                  0x55de74d47210: ch,glue = CopyToReg 0x55de74cdf1d0, Register:i32 $gp, Register:i32 %245, 0x55de74cdf1d0:1, t/btrace2fio.c:881:13 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]



          0x55de74cdf718: f64,ch = load<(load (s64) from constant-pool)> 0x55de74cf1f88, 0x55de74f6f430, undef:i32
            0x55de74f6f430: i32 = add 0x55de74cdee28, 0x55de74cdf648
              0x55de74cdee28: i32,ch = load<(load (s32) from got)> 0x55de74cf1f88, 0x55de74d46fa0, undef:i32
                0x55de74d46fa0: i32 = MipsISD::Wrapper Register:i32 %245, TargetConstantPool:i32<double 1.000000e+02> 0 [TF=1]
                  0x55de74cde948: i32 = Register %245
                  0x55de74cd3788: i32 = TargetConstantPool<double 1.000000e+02> 0 [TF=1]
                0x55de74cd3990: i32 = undef
              0x55de74cdf648: i32 = MipsISD::Lo TargetConstantPool:i32<double 1.000000e+02> 0 [TF=5]
                0x55de74cd4280: i32 = TargetConstantPool<double 1.000000e+02> 0 [TF=5]
            0x55de74cd3990: i32 = undef
        0x55de74d467e8: f64 = fp_extend 0x55de74cdf5e0, t/btrace2fio.c:881:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
          0x55de74cdf5e0: f32 = fp_round 0x55de74cdec20, Constant:i32<0>, t/btrace2fio.c:881:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
            0x55de74cdec20: f64 = fsub 0x55de74f6fec0, 0x55de74f1d370, t/btrace2fio.c:881:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
              0x55de74f6fec0: f64,ch = load<(load (s64) from %stack.8)> 0x55de74cdee90, FrameIndex:i32<8>, undef:i32, t/btrace2fio.c:881:47 @[ t/btrace2fio.c:931:7 @[ t/btrace2fio.c:970:7 @[ t/btrace2fio.c:1001:4 @[ t/btrace2fio.c:1159:9 ] ] ] ]
                0x55de74d46b28: i32 = FrameIndex<8>
                0x55de74cd3990: i32 = undef
              0x55de74f1d370: f64,ch = load<(load (s64) from constant-pool)> 0x55de74cf1f88, 0x55de74cd3928, undef:i32
                0x55de74cd3928: i32 = add 0x55de74f1dac0, 0x55de74f6f1c0
                  0x55de74f1dac0: i32,ch = load<(load (s32) from got)> 0x55de74cf1f88, 0x55de74d472e0, undef:i32


                  0x55de74f6f1c0: i32 = MipsISD::Lo TargetConstantPool:i32<double 0x4330000000000000> 0 [TF=5]

                0x55de74cd3990: i32 = undef
            0x55de74cdeb50: i32 = Constant<0>
      0x55de74f6fdf0: i32 = TargetConstant<0>
In function: main

```

[btrace2fio-439d21.tar.gz](https://github.com/llvm/llvm-project/files/8128793/btrace2fio-439d21.tar.gz)

**Comment by nikic** [comment] 2022-02-24 07:57
Closing this as a duplicate of #53722, it's the same SDAG fabs f32 selection failure on mips.

**Closed by nikic** 2022-02-24 07:57 UTC
Labels: backend:MIPS
