### ISSUE TITLE
[clang] Constexpr function of a function parameter cannot be used in a constant expression

### ISSUE THREAD

**Issue by StefanPaulet** [llvm/llvm-project#118063] opened 2024-11-29 07:44 UTC
The following code compiles on gcc, but fails on msvc and clang:
``` C++
template <unsigned int N>
struct array {
    constexpr auto size() const -> unsigned int {
        return N;
    }
};

constexpr auto foo(array<5> const& arr) {
    return array<arr.size()>{}.size();
}

constexpr auto bar(array<5> arr) {
    return array<arr.size()>{}.size();
}

int main()
{
    array<5> arr {};
    static_assert(arr.size() == 5);
    static_assert(foo(arr) == 5);
    static_assert(bar(arr) == 5);
}
```
https://godbolt.org/z/q1xajW1Gq

However, if `size` is made static, msvc also compiles:
https://godbolt.org/z/Tfqe5E9z8

The problem seems to be with `arr` being passed by reference, as passing by value also get accepted.

**Comment by frederick-vs-ja** [comment] 2024-11-29 08:12
This is being fixed by #95474, which implements [P2280R4](https://wg21.link/p2280r4).

Closing as duplicate of #63139.

**Closed by frederick-vs-ja** 2024-11-29 08:12 UTC
Labels: duplicate, clang, constexpr
