### ISSUE TITLE
[clang-format] Regressions with clang-format version 18?

### ISSUE THREAD

**Issue by prj-** [llvm/llvm-project#67729] opened 2023-09-28 19:49 UTC
```
$ cat src.cxx
namespace sycl
{

// internal "impls" class for SyclDevice. Each instance represents a single sycl device
class PETSC_NODISCARD Device::DeviceInternal {
  const int            id_; // -1 for the host device; 0 and up for gpu devices
  bool                 devInitialized_;
  const ::sycl::device syclDevice_;

public:
  // default constructor
  DeviceInternal(int id) noexcept : id_(id), devInitialized_(false), syclDevice_(chooseSYCLDevice_(id)) { }
  int  id() const { return id_; }
  bool initialized() const { return devInitialized_; }
}
}

struct MatProductData_SeqAIJKokkos {
  KernelHandle kh;
  PetscBool    reusesym;
  MatProductData_SeqAIJKokkos() : reusesym(PETSC_FALSE) { }
};

class PetscMatrixSampler : public HMatrixSampler {
public:
  PetscMatrixSampler();
  PetscMatrixSampler(Mat);
  ~PetscMatrixSampler();
  void         SetSamplingMat(Mat);
  void         SetIndexMap(int, int *);
  void         SetGPUSampling(bool);
  void         SetStream(h2opusComputeStream_t);
  virtual void sample(H2Opus_Real *, H2Opus_Real *, int);
  Mat          GetSamplingMat() { return A; }
};

struct Shift {
  int _shift;

  Shift(int shift) : _shift(shift) { }
  __host__ __device__ inline int operator()(const int &c) { return c + _shift; }
};
$ clang-format -version
clang-format version 17.0.1
$ clang-format --style=file:clang-format.txt src.cxx > 17.cxx 
$ clang-format-18 -version
Debian clang-format version 18.0.0 (++20230927111316+98e016d99732-1~exp1~20230927111428.1598)
$ clang-format-18 --style=file:clang-format.txt src.cxx > 18.cxx 
```
```diff
$ diff -pauN 17.cxx 18.cxx
--- 17.cxx	2023-09-28 19:09:20
+++ 18.cxx	2023-09-28 19:09:08
@@ -9,7 +9,7 @@ class PETSC_NODISCARD Device::DeviceInternal { (public
 
 public:
   // default constructor
-  DeviceInternal(int id) noexcept : id_(id), devInitialized_(false), syclDevice_(chooseSYCLDevice_(id)) { }
+       DeviceInternal(int id) noexcept : id_(id), devInitialized_(false), syclDevice_(chooseSYCLDevice_(id)) { }
   int  id() const { return id_; }
   bool initialized() const { return devInitialized_; }
 }
@@ -18,14 +18,14 @@ struct MatProductData_SeqAIJKokkos {
 struct MatProductData_SeqAIJKokkos {
   KernelHandle kh;
   PetscBool    reusesym;
-  MatProductData_SeqAIJKokkos() : reusesym(PETSC_FALSE) { }
+               MatProductData_SeqAIJKokkos() : reusesym(PETSC_FALSE) { }
 };
 
 class PetscMatrixSampler : public HMatrixSampler {
 public:
-  PetscMatrixSampler();
-  PetscMatrixSampler(Mat);
-  ~PetscMatrixSampler();
+               PetscMatrixSampler();
+               PetscMatrixSampler(Mat);
+  ~            PetscMatrixSampler();
   void         SetSamplingMat(Mat);
   void         SetIndexMap(int, int *);
   void         SetGPUSampling(bool);
@@ -37,6 +37,6 @@ struct Shift {
 struct Shift {
   int _shift;
 
-  Shift(int shift) : _shift(shift) { }
+                                 Shift(int shift) : _shift(shift) { }
   __host__ __device__ inline int operator()(const int &c) { return c + _shift; }
 };
```
I'm not sure if those are regressions, or just funny-looking (but correct). One way to revert to the previous formatting is to add extra line breaks, but I'm not sure whether that is intended or not. [clang-format.txt](https://github.com/llvm/llvm-project/files/12753413/clang-format.txt)

**Comment by rymiel** [comment] 2023-09-28 20:16
All of the shown issues will be fixed by https://github.com/llvm/llvm-project/pull/67618. This issue isn't exactly a duplicate of https://github.com/llvm/llvm-project/issues/67604, but since that PR will fix both issues, I'm just going to close it right away

**Closed by rymiel** 2023-09-28 20:16 UTC
Labels: clang-format, regression
