### ISSUE TITLE
-Wconsumed ICE on switch default case with empty enum

### ISSUE THREAD

**Issue by Quuxplusone** [llvm/llvm-project#47810] opened 2020-12-10 03:23 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [48466](https://llvm.org/bz48466) |
| Version | trunk |
| OS | All |
| CC | @dwblaikie,@devincoughlin,@haoNoQ,@zygoloid |

## Extended Description 
Originally reported by Drew Gross.
Possibly somehow related to #&#8203;16212, #&#8203;33699. The enum being "empty" (an enum type with no enumerators) is important to this ICE somehow.

// https://godbolt.org/z/KxbGsv
enum E {};
void foo(E e) {
    switch (e) { default:; }
}

clang++ -Wconsumed test.cpp

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/clang++ -g -o ./output.s -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -Wconsumed <source>
1.	<eof> parser at end of file
2.	<source>:3:15: parsing function body 'foo'
 #&#8203;0 0x00005651c0f17e4c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2e0ae4c)
 #&#8203;1 0x00005651c0f15be4 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2e08be4)
 #&#8203;2 0x00005651c0f15e75 llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2e08e75)
 #&#8203;3 0x00005651c0e84338 CrashRecoverySignalHandler(int) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2d77338)
 #&#8203;4 0x00007fc53fc493c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #&#8203;5 0x00005651c34128b3 clang::consumed::ConsumedAnalyzer::run(clang::AnalysisDeclContext&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x53058b3)
 #&#8203;6 0x00005651c336466e clang::sema::AnalysisBasedWarnings::IssueWarnings(clang::sema::AnalysisBasedWarnings::Policy, clang::sema::FunctionScopeInfo*, clang::Decl const*, clang::QualType) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x525766e)
 #&#8203;7 0x00005651c2c54dfe clang::Sema::PopFunctionScopeInfo(clang::sema::AnalysisBasedWarnings::Policy const*, clang::Decl const*, clang::QualType) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4b47dfe)
 #&#8203;8 0x00005651c2dab042 clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4c9e042)
 #&#8203;9 0x00005651c2bf9d97 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4aecd97)
#&#8203;10 0x00005651c2b4e527 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4a41527)
#&#8203;11 0x00005651c2b6a6d5 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4a5d6d5)
#&#8203;12 0x00005651c2b49551 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4a3c551)
#&#8203;13 0x00005651c2b49c81 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.250) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4a3cc81)
#&#8203;14 0x00005651c2b4fc29 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4a42c29)
#&#8203;15 0x00005651c2b511b1 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4a441b1)
#&#8203;16 0x00005651c2b44319 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x4a37319)
#&#8203;17 0x00005651c1735be1 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3628be1)
#&#8203;18 0x00005651c16ebe3b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x35dee3b)
#&#8203;19 0x00005651c17fd463 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x36f0463)
#&#8203;20 0x00005651bf00629c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xef929c)
#&#8203;21 0x00005651bf00297d ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0xef597d)
#&#8203;22 0x00005651c15b6955 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x34a9955)
#&#8203;23 0x00005651c0e84413 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x2d77413)
#&#8203;24 0x00005651c15b7487 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.172) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x34aa487)
#&#8203;25 0x00005651c159019a clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x348319a)
#&#8203;26 0x00005651c1590cef clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/compiler-explorer/clang-trunk/bin/clang+++0x3483cef)
#&#8203;27 0x00005651c1599ba5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/compiler-explorer/clang-trunk/bin/clang+++0x348cba5)
#&#8203;28 0x00005651bef31cf6 main (/opt/compiler-explorer/clang-trunk/bin/clang+++0xe24cf6)
#&#8203;29 0x00007fc53f6fa0b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#&#8203;30 0x00005651bf0024fa _start (/opt/compiler-explorer/clang-trunk/bin/clang+++0xef54fa)

**Comment by IhorGarbuzKh** [comment] 2022-09-16 16:06
Seems fixed in clang 13.

https://godbolt.org/z/c3efYaerK

Maybe here:

https://github.com/llvm/llvm-project/commit/83225936af317e6bdd7103a8a039c51a29ce9f57

**Comment by tbaederr** [comment] 2023-03-29 10:07
Closing since this doesn't reproduce anymore.

**Closed by tbaederr** 2023-03-29 10:07 UTC
Labels: bugzilla, clang:diagnostics
