### ISSUE TITLE
[clang-format] AlignAfterOpenBracket: BlockIndent: weird close-bracket when ')' or qualifiers exceeds ColumnLimit

### ISSUE THREAD

**Issue by svs590** [llvm/llvm-project#55473] opened 2022-05-15 11:42 UTC
Hello!
I'm using clang-format 14 with option ```AlignAfterOpenBracket: BlockIndent``` and I found strange сlosing brackets behavior when close bracket or following qualifiers exceed ```ColumnLimit```. This case appears when ```return-type``` + ```function-name``` + ```arguments``` can place on one line, but ```) + qualifiers``` cannot.

Here is an example of .clang-format file:
```yaml
# BasedOnStyle:  LLVM
AlignAfterOpenBracket: BlockIndent
AllowAllArgumentsOnNextLine: true
AllowShortFunctionsOnASingleLine: Empty
BinPackArguments: false
BinPackParameters: false
BreakBeforeBraces: Custom
BraceWrapping: 
  AfterFunction: false
ColumnLimit: 82
ContinuationIndentWidth: 4
IndentWidth: 4
PenaltyReturnTypeOnItsOwnLine: 41
PointerAlignment: Right
SpaceAroundPointerQualifiers: Both
TabWidth : 4
UseTab : Never
...
```

Here is an **example** when ```AlignAfterOpenBracket: BlockIndent``` **works fine**:
```cpp
std::string some_function(const std::string &a, const std::string &b) noexcept {
    // Some code here...
}

std::string some_function(
    const std::string &a,
    const std::string &b,
    const std::string &c,
    const std::string &d
) noexcept {
    // Some code here...
}

void check_range(const std::size_t &idx) noexcept {
    // Some code here...
}
```
Everything is just as I expected.

But if I increase function name length or add some function attributes (e.g. MACRO), then I have weird behavior: only ```) + qualifiers``` places on the next line.
**Example:**
```cpp
void check_range_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(const std::size_t &idx
) {
    // Some code here...
}

void check_range_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(const std::size_t &idx
) noexcept {
    // Some code here...
}

CXX17_NODISCARD CXX20_CONSTEXPR void check_range(const std::size_t &idx
) noexcept {
    // Some code here...
}
```
**Expected:**
```cpp
void check_range_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(
    const std::size_t &idx
) {
    // Some code here...
}

void check_range_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(
    const std::size_t &idx
) noexcept {
    // Some code here...
}

CXX17_NODISCARD CXX20_CONSTEXPR void check_range(
    const std::size_t &idx
) noexcept {
    // Some code here...
}
```

**Comment by martinling** [comment] 2022-07-06 10:31
Also reported as #54808.

**Comment by KnoerleMan** [comment] 2023-01-24 11:24
The whole thing gets even worse when you have a function call without parameters and reach the column limit around the parentheses:

![image](https://user-images.githubusercontent.com/55956669/214269010-d06f511e-8878-479c-9795-fa77b79c5469.png)

In that case the formatting looks extremely strange.

Are there any other settings that prevent this?

**Comment by louwers** [comment] 2023-04-30 10:20
Look at this:

```
class Test {
  virtual void
  mergeOfflineRegions(const std::string &sideDatabasePath, std::function<void(expected<OfflineRegions, std::exception_ptr>)>);
};
```

It doesn't even take into account the ColumnLimit anymore!

**Comment by Zingam** [comment] 2023-11-18 12:32
A duplicate of: https://github.com/llvm/llvm-project/issues/55731

**Closed** 2023-11-18 15:54 UTC
Labels: duplicate, clang-format
