### ISSUE TITLE
Clang-Tidy raises modernize-use-nullptr  with spaceship operator

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [llvm/llvm-project#64159] opened 2023-07-27 12:54 UTC
Reopening https://github.com/llvm/llvm-project/issues/53961 as it seems to me the issue is not solved.

I have a simple `struct`

```

#include <compare>

struct X {
  double a = 0.0;
  double b = 0.0;
  double c = 0.0;

  X() = default;
  X(const X&) = default;
  explicit X(double x);

  X& operator=(const X& other) = default;
  // NOLINTNEXTLINE(modernize-use-nullptr)
  std::partial_ordering operator<=>(const X&) const = default;
};
```

if I run `clang-tidy` I get an error

```
Resource filename: /opt/homebrew/lib/python3.11/site-packages/clang_tidy/data/bin/clang-tidy 
/Users/***/***.h:23:77: error: use nullptr [modernize-use-nullptr,-warnings-as-errors]
  std::partial_ordering operator<=>(const X&) const = default;
                                                                            ^
                                                                             nullptr
```

Am I missing anything here?

**Comment by PiotrZSL** [comment] 2023-07-27 15:40
Looks like warning is generated in system header:
```
include/c++/14.0.0/compare:364:21: warning: use nullptr [modernize-use-nullptr]
  364 |   { return __cmp != 0; }
```
Do not use --system-header to silent it. 
Anyway, duplicate of #63478

**Closed** 2023-07-27 15:54 UTC
Labels: duplicate, clang-tidy, false-positive

**Comment by andrea-cassioli-maersk** [comment] 2023-07-28 06:13
hey @PiotrZSL I am not sure I understand your suggestion.

**Comment by PiotrZSL** [comment] 2023-07-28 07:08
I mean that those issues are raised in system header, and looks like --warnings-as-errors is causing it to be visible. This issue (check filters) can be already fixed in Clang 17. As for bug in check, that is pending.
