### ISSUE TITLE
[feature request] clang-format: insert symmetric braces

### ISSUE THREAD

**Issue by timblechmann** [llvm/llvm-project#82087] opened 2024-02-17 01:37 UTC
Qt's coding style recommends "symmetric" braces in `if` statements:

```
 // Wrong
 if (address.isEmpty())
     qDebug("empty!");
 else {
     qDebug("%s", qPrintable(address));
     it;
 }

 // Correct
 if (address.isEmpty()) {
     qDebug("empty!");
 } else {
     qDebug("%s", qPrintable(address));
     it;
 }
```

it would be great if `InsertBraces` could be used to enforce this style

https://wiki.qt.io/Qt_Coding_Style#Braces

**Comment by owenca** [comment] 2024-02-18 07:29
> ```
>  // Wrong
>  if (address.isEmpty())
>      qDebug("empty!");
>  else {
>      qDebug("%s", qPrintable(address));
>      it;
>  }
> 
>  // Correct
>  if (address.isEmpty()) {
>      qDebug("empty!");
>  } else {
>      qDebug("%s", qPrintable(address));
>      it;
>  }
> ```
> 
> it would be great if `InsertBraces` could be used to enforce this style

This has always been the case:
```
$ cat test.cpp
if (address.isEmpty())
  qDebug("empty!");
else {
  qDebug("%s", qPrintable(address));
  it;
}
$ clang-format -style='{InsertBraces: true}' test.cpp
if (address.isEmpty()) {
  qDebug("empty!");
} else {
  qDebug("%s", qPrintable(address));
  it;
}
```

**Comment by timblechmann** [comment] 2024-02-18 08:02
@owenca, `InsertBraces`, cannot be used for the qt coding style, as it will *always* insert braces. according to qt's coding style, single-line block should not use braces, though:
```
 // Wrong
 if (address.isEmpty()) {
     return false;
 }

 for (int i = 0; i < 10; ++i) {
     qDebug("%i", i);
 }

 // Correct
 if (address.isEmpty())
     return false;

 for (int i = 0; i < 10; ++i)
     qDebug("%i", i);
```

https://wiki.qt.io/Qt_Coding_Style#Braces

**Comment by owenca** [comment] 2024-02-18 08:44
Then the issue is not that `InsertBraces` doesn't insert symmetric braces. Instead, you don't want it to insert braces for single-line if/else bodies.

**Comment by timblechmann** [comment] 2024-02-18 12:38
from the qt coding style (https://wiki.qt.io/Qt_Coding_Style#Braces):

* Use curly braces only when the body of a conditional statement contains more than one line:
* Exception 1: Use braces also if the parent statement covers several lines / wraps:
* Exception 2: Brace symmetry: Use braces also in if-then-else blocks where either the if-code or the else-code covers several lines:

symmetry according to the qt style guide is about symmetry between `if` and `else` block. if either block is more than a single line, braces should be inserted in both blocks

**Comment by owenca** [comment] 2024-02-19 19:36
@timblechmann regardless what you think "symmetric" means there, this is a duplicate of #59864.

**Closed by owenca** 2024-02-19 19:36 UTC
Labels: duplicate, clang-format
