### ISSUE TITLE
Defining a method with a user-defined concept of class template outside its scope gives an error: "out-of-line definition of does not match any declaration in"

### ISSUE THREAD

**Issue by akukh** [llvm/llvm-project#56482] opened 2022-07-11 22:17 UTC
Well, trying to define a method with a user-defined concept of class template outside its scope gives an error:
```console
error: out-of-line definition of '...' does not match any declaration in '...'
```
GCC, in turn, compiles such code just fine.
https://godbolt.org/z/PTnh6Y4ab

**Comment by royjacobson** [comment] 2022-09-29 16:45
This is solved in the Clang 16 branch. Since this concepts refers to the injected class name it's probably the deferred concepts change.

https://godbolt.org/z/ffa94TTjE

**Comment by hiraditya** [comment] 2023-09-27 19:51
seems like clang 17 has regressed and this issue shows up again?

https://godbolt.org/z/56eYa4jnq

**Comment by shafik** [comment] 2023-09-27 21:21
Confirmed fixed in 16 and then regressed in 17: https://godbolt.org/z/4nhKzahxc

CC @erichkeane @cor3ntin

**Comment by erichkeane** [comment] 2023-09-27 21:35
Interestingly, it is fully specifying the template arguments to the requires clause that makes it not the same: https://godbolt.org/z/ExEj5xaWP

(Thats a minimized version, uncomment the <T> to get it to break).

**Comment by erichkeane** [comment] 2023-09-28 14:16
So this probably worked in Clang16 because we were doing a little bit of a 'dumb' and inaccurate comparison of constraints by just trying to make the levels 'even'.  We fixed this in 17, which is unfortunately exposing a bunch of errors in how we 'instantiate' incomplete constraints.  

I don't know what the exact issue is (and might not have a chance to take a look anytime soon), but it seems we're having trouble with setting up the template arguments for the out of line definition there.  For some reason, even dumping the post-instantiated version fails with `DeclTemplate.cpp:1646's llvm_unreachable of: "Unhandled templated declaration kind"`, so we're messing SOMETHING up in collecting types.

If anyone wnats to take a look, the best place to start is SemaConcept.cpp's `AreConstraintExpressionsEqual`.  In that function we try to do the partial instantiation (`SubstituteConstraintExpression` collects the template arguments then tries to instantiate them) and compare using the `FoldingSetNodeID` stuff.  I doubt the latter is the problem, but I suspect the 2nd call to `SubstituteConstraintExpr` (from the `New` side) is what is wrong.

**Closed** 2024-01-31 04:17 UTC
Labels: clang:frontend, concepts
