### ISSUE TITLE
[Clang] Parser crashes on invalid redefined `alias`

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#97173] opened 2024-06-29 18:23 UTC
The `cc1` parser currently crashes if you try to initialize / redefine an alias variable, see https://godbolt.org/z/Mo4z9h98P

Code:

```cpp
extern int x;

int __x_impl __asm__("x") = 1;
[[gnu::alias("x")]] extern int x = 1;
```

Assertion:

```console
clang++: /root/llvm-project/clang/lib/Sema/SemaDecl.cpp:7059:
void checkAttributesAfterMerging(clang::Sema&, clang::NamedDecl&):
Assertion `VD->isThisDeclarationADefinition() && !VD->isExternallyVisible() && "Broken AliasAttr handled late!"' failed.
```

Backtrace:

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:4:37: current parser token ';'
 #0 0x0000000003a34d38 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a34d38)
 #1 0x0000000003a32a1c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a32a1c)
 #2 0x0000000003978268 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000747cb1c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000747cb1c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x0000747cb1c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x0000747cb1c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x0000747cb1c2871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x0000747cb1c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000000000674d8b7 checkAttributesAfterMerging(clang::Sema&, clang::NamedDecl&) SemaDecl.cpp:0:0
#10 0x0000000006759d6e clang::Sema::FinalizeDeclaration(clang::Decl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6759d6e)
#11 0x00000000063e87f4 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63e87f4)
#12 0x00000000063f7cda clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63f7cda)
#13 0x00000000063b607e clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63b607e)
#14 0x00000000063b68de clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63b68de)
#15 0x00000000063bd007 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63bd007)
#16 0x00000000063bdeef clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63bdeef)
#17 0x00000000063b16ea clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63b16ea)
#18 0x000000000431ee18 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x431ee18)
#19 0x00000000045a5909 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45a5909)
#20 0x000000000452b95e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x452b95e)
#21 0x000000000468e47e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x468e47e)
#22 0x0000000000c6efa5 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc6efa5)
#23 0x0000000000c681ca ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#24 0x00000000043625a9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#25 0x0000000003978714 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3978714)
#26 0x0000000004362b9f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#27 0x00000000043285e5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43285e5)
#28 0x000000000432904d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x432904d)
#29 0x0000000004330a65 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4330a65)
#30 0x0000000000c6c375 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc6c375)
#31 0x0000000000b44ef4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb44ef4)
#32 0x0000747cb1c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#33 0x0000747cb1c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#34 0x0000000000c67c7e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc67c7e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

**Comment by DimitryAndric** [comment] 2024-06-29 18:38
This is actually an assertion:

```text
Assertion failed: (VD->isThisDeclarationADefinition() && !VD->isExternallyVisible() && "Broken AliasAttr handled late!"), function checkAttributesAfterMerging, file /home/dim/src/llvm/llvm-project/clang/lib/Sema/SemaDecl.cpp, line 7019.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang++ -c pr97173.cpp
1.      pr97173.cpp:4:37: current parser token ';'
 #0 0x00000000041ee068 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x41ee068)
 #1 0x00000000041ebe29 llvm::sys::RunSignalHandlers() (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x41ebe29)
 #2 0x0000000004162043 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x000000082a2c94af handle_signal /usr/src/lib/libthr/thread/thr_sig.c:0:3
 #4 0x000000082a2c8a6b thr_sighandler /usr/src/lib/libthr/thread/thr_sig.c:245:1
 #5 0x00000008293772d3 ([vdso]+0x2d3)
 #6 0x000000082f024a0a __sys_thr_kill /usr/obj/usr/src/lib/libc/thr_kill.S:4:0
 #7 0x000000082ef9e1e4 _raise /usr/src/lib/libc/gen/raise.c:0:10
 #8 0x000000082f04ebc9 abort /usr/src/lib/libc/stdlib/abort.c:71:17
 #9 0x000000082ef81551 (/lib/libc.so.7+0x93551)
#10 0x000000000605992f checkAttributesAfterMerging(clang::Sema&, clang::NamedDecl&) SemaDecl.cpp:0:0
#11 0x00000000060601f1 clang::Sema::FinalizeDeclaration(clang::Decl*) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x60601f1)
#12 0x0000000005db5dbb clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x5db5dbb)
#13 0x0000000005db2cec clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::Parser::ParsedTemplateInfo&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x5db2cec)
#14 0x0000000005d3fd4f clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x5d3fd4f)
#15 0x0000000005d3f5db clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x5d3f5db)
#16 0x0000000005d3e483 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x5d3e483)
#17 0x0000000005d3c277 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x5d3c277)
#18 0x0000000005d3748e clang::ParseAST(clang::Sema&, bool, bool) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x5d3748e)
#19 0x0000000004dc3703 clang::FrontendAction::Execute() (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4dc3703)
#20 0x0000000004d47aed clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4d47aed)
#21 0x0000000004e9c49e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4e9c49e)
#22 0x000000000261b50f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x261b50f)
#23 0x00000000026181a5 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#24 0x0000000004bb5f7e void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_0>(long) Job.cpp:0:0
#25 0x0000000004161d89 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4161d89)
#26 0x0000000004bb58e3 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4bb58e3)
#27 0x0000000004b77d16 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4b77d16)
#28 0x0000000004b77fd8 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&, bool) const (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4b77fd8)
#29 0x0000000004b94601 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x4b94601)
#30 0x000000000261786f clang_main(int, char**, llvm::ToolContext const&) (/home/dim/ins/llvmorg-19-init-14557-g213e308633e/bin/clang+++0x261786f)
```

without assertions enabled, it results in a compile error:

```text
pr97173.cpp:4:32: warning: 'extern' variable has an initializer [-Wextern-initializer]
[[gnu::alias("x")]] extern int x = 1;
                               ^
pr97173.cpp:4:3: error: definition 'x' cannot also be an alias
[[gnu::alias("x")]] extern int x = 1;
  ^
1 warning and 1 error generated.
```

but in any case, this is a duplicate of #50535.

**Closed by DimitryAndric** 2024-06-29 18:38 UTC
Labels: duplicate, clang, crash-on-invalid, confirmed

**Comment by jhuber6** [comment] 2024-06-29 18:43
Thanks for pointing out the existing issue. My understanding is that the user shouldn't be able to trigger assertions in "normal" use so it should likely print the same thing as the no assertions case.
