### ISSUE TITLE
Coroutine promise types don't support destroying operator delete

### ISSUE THREAD

**Issue by ca13e524-e041-4bc1-a984-924326006e5a** [llvm/llvm-project#47688] opened 2020-12-01 01:23 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [48344](https://llvm.org/bz48344) |
| Version | trunk |
| OS | All |
| CC | @zygoloid |

## Extended Description 
$ cat pdd.cpp

#if __has_include(<coroutine>)
#include <coroutine>
namespace stdcoro = std;
#else
#include <experimental/coroutine>
namespace stdcoro = std::experimental;
#endif

#include <cstdlib>
#include <new>

struct coroutine
{
    struct promise_type
    {
        coroutine get_return_object() noexcept
        {
            return {*this};
        }

        stdcoro::suspend_always initial_suspend() const noexcept
        {
            return {};
        }

        stdcoro::suspend_always final_suspend() const noexcept
        {
            return {};
        }

        void return_void() const noexcept {}

        void unhandled_exception() noexcept {}

        void* operator new(std::size_t n)
        {
            return std::malloc(n);
        }

        void operator delete(
            promise_type* p,std::destroying_delete_t,std::size_t)
        {
            std::free(p);
        }
    };

    stdcoro::coroutine_handle<promise_type> h_;

    coroutine(promise_type& p)
        : h_{decltype(h_)::from_promise(p)}
    {}

    ~coroutine()
    {
        h_.destroy();
    }
};

coroutine f()
{
    co_return;
}

$ clang++ -std=c++20 -fsyntax-only pdd.cpp

pdd.cpp:59:11: error: too few arguments to function call, expected 3, have 2
coroutine f()
          ^
pdd.cpp:40:14: note: 'operator delete' declared here
        void operator delete(
             ^
1 error generated.

Looking at the end of CoroutineStmtBuilder::makeNewAndDeleteExpr(), it seems like support for destroying operator delete on promise types is not implemented.

Neither gcc 10.2 nor MSVC 16.8.2 accept this code with similar error messages, but it looks like it's impossible to implement a coroutine with statefull Allocator support for promise that also has access to its allocator in its implementation without support for this combination. I also can't find anything that prohibits this in the C++ standard.

**Comment by ChuanqiXu9** [comment] 2022-11-14 05:26
This one should be solved in trunk.

**Comment by tzcnt** [comment] 2024-01-12 02:21
This does not appear to be solved in trunk. I updated the original reproducer and get the exact same error with Clang 17.0.1.

https://godbolt.org/z/z3G3f867a

Interestingly on Clang 15 I can get the compiler to attempt to invoke the 2-argument form of destroying_delete but it doesn't seem to be able to convert the arguments properly (see the error shown at https://godbolt.org/z/cEMMjvv3c and then try changing line 33 to void* p instead and see the conflicting error).

Was this functionality dropped at some point after Clang 15? It would be very valuable for my current work.

**Comment by ChuanqiXu9** [comment] 2024-01-12 02:33
> This does not appear to be working. I updated the original reproducer and get the exact same error with Clang 17.0.1.
> 
> https://godbolt.org/z/z3G3f867a
> 
> Interestingly on Clang 15 I can get the compiler to attempt to invoke the 2-argument form of destroying_delete but it doesn't seem to be able to convert the arguments properly (see the error shown at https://godbolt.org/z/cEMMjvv3c and then try changing line 33 to void* p instead and see the conflicting error).
> 
> Was this functionality dropped at some point after Clang 15? It would be very valuable for my current work.

According to [dcl.fct.def.coroutine#12](http://eel.is/c++draft/dcl.fct.def.coroutine#12), the deallocation function for coroutines are either 2 parameters (a pointer with a size) or 1 parameters (a pointer). There is nothing related with `destroying_delete_t ` from the wording.

Oh, possibly I should close this as invalid. Since it looks like it needs a new language design to make the reproducer to work.

**Closed** 2024-01-12 02:33 UTC
Labels: c++20, bugzilla, coroutines
