### ISSUE TITLE
LLVM 18.1.0 stable release contains rc in the version string

### ISSUE THREAD

**Issue by bstaletic** [llvm/llvm-project#84351] opened 2024-03-07 18:02 UTC
The 18.1.0 release, archive `llvm-project-18.1.0.src.tar.xz` has `LLVM_VERSION_SUFFIX` set to `rc` in the `llvm/CMakeLists.txt`.
That results in version strings showing `18.1.0rc`.

Also, if that tarball is extracted within unrelated git repo and then also compiled within that unrelated git repo, the version string will contain the name and HEAD hash of the unrelated repo.

More specifically, YouCompleteMe uses [this repo](https://github.com/ycm-core/llvm/) to repackage `clangd` and `libclang.so` for its purposes. This time the version string showed the following:

```
clangd version 18.1.0rc (https://github.com/ycm-core/llvm abd06744664af7852747fc7190a38b36473ac13b)
Features: linux
Platform: x86_64-unknown-linux-gnu
```

**Comment by EugeneZelenko** [comment] 2024-03-07 18:07
Duplicate of #84168.

**Closed by EugeneZelenko** 2024-03-07 18:07 UTC
Labels: duplicate, cmake
