### ISSUE TITLE
[clangd] Wrong compilation flags are chosen for some header files

### ISSUE THREAD

**Issue by Febbe** [llvm/llvm-project#59254] opened 2022-11-29 18:18 UTC
When having a huge project structure with multiple dependencies and also multiple targets,
header files, which do not have a main source file, might fail to be analyzed via clangd.

This happens, because clangd is choosing a source file, that is completely out of context / an independent other target.

For example, the compile_command.json contains sources of:

```
C:\cpm_cache\OpenMesh\*
C:\Users\myuser\Desktop\workspace\my\project\subproject1\include\subproject1\*
C:\Users\myuser\Desktop\workspace\my\project\subproject2\include\subproject2\*
C:\Users\myuser\Desktop\workspace\my\project\subproject1\src\*
C:\Users\myuser\Desktop\workspace\my\project\subproject2\src\*
C:\Users\myuser\Desktop\workspace\my\project\executable\*
```

It might be, that a header, which is located in `subproject1\include\subproject1\` is analyzed with compile flags from a source in `C:\cpm_cache\OpenMesh\*` But the header is never included in that file. And there is not even the include path appended, which refers to the header.

My proposal:
 - Do not pretend to analyze a header file with the compile options of another unrelated source file. 
   - This is the case, when no include in a source file in combination with the include paths refer to the header.
 - Add a warning to a header file, which fails due to too many errors, where the compile commands actually came from.
 - Don't emit any errors and warnings for unresolved symbols, when the analysis has been stopped due to too many errors.
   - They are nearly all false positives anyway.
 - Change the search direction to source files with a minimal relative path distance.

**Comment by HighCommander4** [comment] 2022-11-30 07:14
https://github.com/clangd/clangd/issues/123 is on file for improving the heuristics for choosing a source file whose compile commands to use based on actual inclusion relationships (i.e. a source file that includes the header file being opened) rather than based on the filename/path.

**Comment by HighCommander4** [comment] 2023-08-18 02:54
I think this is covered by https://github.com/clangd/clangd/issues/123 (use the compile command of a source file that actually includes the header) and https://github.com/clangd/clangd/issues/1505 (give a warning if no such source file can be found). I'll close this one as a duplicate of those.

**Closed by HighCommander4** 2023-08-18 02:54 UTC
Labels: clangd
