### ISSUE TITLE
NULL pointer dereference in FillInEmptyInitForField

### ISSUE THREAD

**Issue by 57b46ce3-16ab-44f3-926b-ae7b94ba1e62** [llvm/llvm-project#49882] opened 2021-05-30 20:36 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [50538](https://llvm.org/bz50538) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [Stack trace](https://user-images.githubusercontent.com/93435628/143762178-b25b2f82-48bb-4fcc-9a08-a8780f638733.gz) |
| CC | @enedil,@zygoloid |

## Extended Description 

Clang crashes when compiling. According to godbolt.org, this affects all versions since 6.0.0. Tested on Fedora 34, with clang 12 from repositories.

POC:

```cpp
template<typename Ti>
struct Wrap { Ti _; };
template<typename Ti, typename = decltype(Wrap<Ti> {0})>
using Void = void;
template<typename, typename = void>
struct variant;
template<typename Ti>
struct variant< Ti, Void<Ti> >;
struct S { int x; variant<S>& v; };
variant<S> v;
```

This code was hand-minimized from this one (using libstdc++):

```cpp
#include <variant>
struct S;
using V = std::variant<int, S>;
struct S { int x; V& v; };
V l = 0;
```

After a bit of investigation, I come to conclusion, that there is a null pointer dereference in FillInEmptyInitForField:

```cpp
          InitListExpr *ILE 
/* some code */
          << ILE->getSyntacticForm()->getSourceRange();
Here, ILE->getSyntacticForm() evaluates to nullptr. I don't know enough internals to know how to fix it.
``

I'm attaching the full stack trace I get. Top entries (excluding those from the signal handler) are inline here:

```console
 #&#8203;4 0x00007f7e9edb80d6 clang::Stmt::getSourceRange() const /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/AST/Stmt.cpp:325:3
 #&#8203;5 0x00007f7e9f436737 clang::Sema::SemaDiagnosticBuilder const& clang::Sema::SemaDiagnosticBuilder::operator<<<clang::SourceRange, void>(clang::SourceRange&&) const /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../include/clang/Sema/Sema.h:1683:7
 #&#8203;6 0x00007f7e9f436737 FillInEmptyInitForField /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/Sema/SemaInit.cpp:697:54
 #&#8203;7 0x00007f7e9f436d16 FillInEmptyInitializations /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/Sema/SemaInit.cpp:820:9
 #&#8203;8 0x00007f7e9f4364b6 FillInEmptyInitForField /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/Sema/SemaInit.cpp:729:31
 #&#8203;9 0x00007f7e9f436d16 FillInEmptyInitializations /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/Sema/SemaInit.cpp:820:9
#&#8203;10 0x00007f7e9f439c5d InitListChecker /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/Sema/SemaInit.cpp:965:5
#&#8203;11 0x00007f7e9f439f17 diagnoseListInit /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/Sema/SemaInit.cpp:8912:3
#&#8203;12 0x00007f7e9f43aad7 clang::InitializationSequence::Diagnose(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::ArrayRef<clang::Expr*>) /usr/src/debug/clang-12.0.0-0.3.rc1.fc34.x86_64/x86_64-redhat-linux-gnu/../lib/Sema/SemaInit.cpp:9361:5
```

**Comment by shafik** [comment] 2023-05-02 19:32
This no longer reproduces on trunk: https://godbolt.org/z/n4hjvEYMj

Duplicate of: https://github.com/llvm/llvm-project/issues/58028

**Closed by shafik** 2023-05-02 19:32 UTC
Labels: clang:frontend, bugzilla
