### ISSUE TITLE
Cosmetic bug - the fix that removes erroneous virtual keyword doesn't remove the space after it.

### ISSUE THREAD

**Issue by Aster89** [llvm/llvm-project#63614] opened 2023-06-30 08:30 UTC
Given this code
```cpp
struct A {
    template<typename T>
    virtual void baz(T);
};
```
I correctly get the following diagnostic:
> 'virtual' cannot be specified on member function templates (fix available) [virtual_member_function_template]                                                                                                                                        

However, upon applying it, the code becomes
```cpp
struct A {
    template<typename T>
     void baz(T);
};
```
instead of
```cpp
struct A {
    template<typename T>
    void baz(T);
};
```
i.e. the correction removed `virtual` but not the space that follows it.

---

I use Vim + YCM, here's the clang version it's using:
> -- Clang version: clang version 16.0.1 (https://github.com/ycm-core/llvm f6d8fd76462bf638dd3368ddb7f60a23f82e8bad)

**Comment by tbaederr** [comment] 2023-06-30 08:58
IIRC, either @AaronBallman or @cjdb suggested that perfect whitespace alignment is not clang's task.

**Comment by AaronBallman** [comment] 2023-06-30 12:01
Correct -- we leave formatting up to a formatting tool like clang-format, otherwise we'll run into fix-it situations that conflict with the user's selected formatting rules (or we need to run a potentially expensive clang-format pass over the fixed source, and that can possibly change the meaning of code depending on the options the user has selected).

Closing as not a bug.

**Closed by AaronBallman** 2023-06-30 12:01 UTC
Labels: invalid, clang:frontend, clang:diagnostics
