### ISSUE TITLE
External symbol linker errors with std::shared_ptr in lambda

### ISSUE THREAD

**Issue by kamrann** [llvm/llvm-project#120558] opened 2024-12-19 11:34 UTC
The linked reproduction has had a lot of code removed so is somewhat nonsensical, but produces linker errors with clang (19 & trunk) whilst compiling successfully with gcc and MSVC. Similar errors result across both Windows (with MS STL) and Linux (both libc++ and libstdc++), seemingly relating to symbols of virtual functions initially declared pure.

https://godbolt.org/z/oK1dhPMhh

**Comment by kamrann** [comment] 2024-12-19 11:35
Adding code to issue.

```
#include <utility>
#include <string>
#include <functional>
#include <optional>
#include <memory>

template < typename ReturnedAttrib >
struct RuleDefinition
{
    using Matcher = std::function< std::optional< ReturnedAttrib >() >;

    template < typename Action >
    static auto adapt_action(Action&& action)
    {
        return [action = std::forward< Action >(action)]() {
            auto mr = std::optional< std::string >{};
            // @NOTE: This lambda appears to be the difference.
            // Just using `action` without the wrapper does not repro.
            auto const wrapped = [&action](auto&& a) {
                return action(std::move(a));
                };
            return std::move(mr).transform(wrapped);
            //return std::move(mr).transform(action); // no error
            };
    }

    template < typename Action >
    explicit RuleDefinition(Action&& action) :
        matcher{ adapt_action(std::forward< Action >(action)) }
    {
    }

    Matcher matcher;
};

template < typename ASTImpl >
auto r()
{
    using Node = std::shared_ptr< ASTImpl >;

    return RuleDefinition< Node >{
        // Deduced return type affects the repro. Remove the explicit return type and it links...
        //[](auto&& attrib) { return std::make_shared< ASTImpl >(); } // no error
        [](auto&& attrib) -> Node { return std::make_shared< ASTImpl >(); }
    };
}

struct Literal
{
    std::string value;
};

auto const grammar = r< Literal >();

```

**Comment by EugeneZelenko** [comment] 2024-12-19 15:50
Same in `main`: https://godbolt.org/z/zx815WxPY

**Comment by shafik** [comment] 2024-12-24 01:36
This is a duplicate of: https://github.com/llvm/llvm-project/issues/57561

**Comment by shafik** [comment] 2024-12-24 01:37
CC @zygoloid who may have some ideas especially since this has shown up a few times now

**Closed by shafik** 2024-12-24 01:37 UTC
Labels: clang, crash, lambda
