### ISSUE TITLE
x86 Clang can't compile forwarded non-trivially copyable params

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#62418] opened 2023-04-27 21:05 UTC
```console
$ cat foo.cc
class A {
  A(const A&);
};
auto x = +[](A) {};

$ third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /c foo.cc -m32
foo.cc(4,15): error: cannot compile this forwarded non-trivially copyable
      parameter yet
auto x = +[](A) {};
              ^
1 error generated.
```

The compile error goes away with `-m64` instead of `-m32`. MSVC x86 can compile this code (https://godbolt.org/z/c4W5fxzW8).

The precise error here dates to https://reviews.llvm.org/rG25b56024aa369df85e9c0d986ace6a5bac164664, which talked about diagnosing "PR28299 while I work on a proper solution". I'm assuming that proper solution never happened.

**Comment by efriedma-quic** [comment] 2023-04-27 22:01
Duplicate of #28673?  (You can translate old PR numbers by visiting "llvm.org/PR28299"

**Comment by pkasting** [comment] 2023-04-28 15:36
Yeah, same issue.

Looks like https://reviews.llvm.org/D137872 would address this maybe?

**Closed** 2023-04-28 18:31 UTC
Labels: duplicate, clang:frontend
