### ISSUE TITLE
Can't build UnrealEngine for Windows

### ISSUE THREAD

**Issue by broly** [llvm/llvm-project#56757] opened 2022-07-27 17:08 UTC
Tried to build UnrealEngine from source ("ue5-main" - 5.0.3) from source using Clang compiler, but got a lof of failures like this

.cpp and .sh files: https://drive.google.com/file/d/1t1rEN4n0uTezPMEoiH-xjBYln0GEQyQI/view?usp=sharing

```
1>[51/1090] Compile Module.MovieSceneTracks.5_of_7.cpp
1>EXEC : LLVM error : out of memory
1>Allocation failed
1>PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
1>Stack dump:
1>0.	Program arguments: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\Llvm\\bin\\clang-cl.exe" @..\\Intermediate\\Build\\Win64\\UnrealEditor\\Development\\MovieSceneTracks\\Module.MovieSceneTracks.5_of_7.cpp.obj.response
1>1.	<eof> parser at end of file
1>2.	Code generation
1>#0 0x023fc798
1>#1 0x76c1edc2
1>clang-cl : error : clang frontend command failed due to signal (use -v to see invocation)
1>clang version 13.0.1
1>Target: x86_64-pc-windows-msvc
1>Thread model: posix
1>InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin
1>clang-cl: note: diagnostic msg:
1>********************
1>PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
1>Preprocessed source(s) and associated run script(s) are located at:
1>clang-cl: note: diagnostic msg: C:\Users\IORpc\AppData\Local\Temp\Module-8ee8ab.cpp
1>clang-cl: note: diagnostic msg: C:\Users\IORpc\AppData\Local\Temp\Module-8ee8ab.sh
1>clang-cl: note: diagnostic msg:
1>********************
```

**Comment by efriedma-quic** [comment] 2022-07-27 17:20
"LLVM error : out of memory" could mean you're running too many instances of the compiler at once, and therefore running out of memory even if the compiler is using a reasonable amount of memory.  I've seen instances where build systems could accidentally invoke the compiler hundreds of times at once.  Can you try disabling parallelism in the build system?  (Not sure what build system you're using; for make or ninja, it's "-j1"; most other systems have some equivalent.)

Also, how much memory does your system have?

You can also get out-of-memory errors if the compiler uses infinite memory for some reason, but that's less common.

**Comment by fhahn** [comment] 2022-08-15 08:09
@broly could you confirm that Clang runs out of memory when just compiling the file you shared? Unfortunately I think it requires a Windows system to reproduce.

I am closing this for now, as it looks like an issue with the system running out of memory due to many parallel jobs. If that's incorrect, we can re-open it once we have additional info.

**Closed by fhahn** 2022-08-15 08:09 UTC
Labels: new issue

**Comment by broly** [comment] 2022-09-02 09:34
> @broly could you confirm that Clang runs out of memory when just compiling the file you shared? Unfortunately I think it requires a Windows system to reproduce.
> 
> I am closing this for now, as it looks like an issue with the system running out of memory due to many parallel jobs. If that's incorrect, we can re-open it once we have additional info.

I have enough memory on my Windows machine (128GB) and compiler not uses so much memory. I've tried to launch clang compiler with 8 (not 24) parallel jobs and it gives same error.

**Comment by broly** [comment] 2022-09-02 09:36
@broly could you confirm that Clang runs out of memory when just compiling the file you shared? Unfortunately I think it requires a Windows system to reproduce.

I am closing this for now, as it looks like an issue with the system running out of memory due to many parallel jobs. If that's incorrect, we can re-open it once we have additional info.

@fhahn 
I have enough memory on my Windows machine (128GB) and compiler not uses so much memory. I've tried to launch clang compiler with 8 (not 24) parallel jobs and it gives same error.

**Comment by fhahn** [comment] 2022-09-02 09:46
@broly thanks for checking! Can you reproduce the issue by just building the preprocessed source file (C:\Users\IORpc\AppData\Local\Temp\Module-8ee8ab.cpp)?
