### ISSUE TITLE
Unable to install llvm 19 with apt

### ISSUE THREAD

**Issue by glebpom** [llvm/llvm-project#109276] opened 2024-09-19 12:09 UTC
I start getting the following error while trying to install llvm 19 on debian:
```
 llvm-19-dev : Depends: libllvm19 (>= 1:19.1.0) but 1:19.1.0~++20240919064958+64075837b553-1~exp1~20240919065122.43 is to be installed
```

```
root@5338595196ce:/# apt install libllvm19
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libllvm19 is already the newest version (1:19.1.0~++20240919064958+64075837b553-1~exp1~20240919065122.43).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
root@5338595196ce:/# apt-cache policy libllvm19
libllvm19:
  Installed: 1:19.1.0~++20240919064958+64075837b553-1~exp1~20240919065122.43
  Candidate: 1:19.1.0~++20240919064958+64075837b553-1~exp1~20240919065122.43
  Version table:
 *** 1:19.1.0~++20240919064958+64075837b553-1~exp1~20240919065122.43 500
        500 http://apt.llvm.org/bookworm llvm-toolchain-bookworm-19/main arm64 Packages
        100 /var/lib/dpkg/status
```

**Comment by vient** [comment] 2024-09-19 12:35
Duplicate of https://github.com/llvm/llvm-project/issues/108995

**Comment by glebpom** [comment] 2024-09-19 12:39
I'm not sure if it's really a duplicate. Five hours ago, building the proposed fix was started, and the versions here are different.

**Comment by vient** [comment] 2024-09-19 12:41
Yeah, I noticed after that that your versions are latest.
@sylvestre seems that 19 packages have another problem.

**Comment by mccolljr** [comment] 2024-09-19 14:46
I can confirm that I am also seeing this problem. It started some time in the last 12-18 hours, as I was able to do this successfully yesterday evening.

**Comment by sylvestre** [comment] 2024-09-19 15:07
regressed here:
https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/commit/42f059d5a11da9cf30494c5ba2728eb749cc4127

I think I have a fix for this one.

**Comment by jthomas-dd** [comment] 2024-09-19 22:26
Does anyone have a workaround for this of any kind yet?

**Comment by sylvestre** [comment] 2024-09-20 11:07
it should be fixed now on most of the archs.

**Comment by glebov-andrey** [comment] 2024-09-20 11:42
This appears to still be broken at least for Debian 10 (Buster)

**Comment by ChrisGreenaway** [comment] 2024-09-20 12:10
Works on Debian bookworm. but not Debian bullseye.

**Comment by firewave** [comment] 2024-09-20 17:09
Can confirm that it is working again with LLVM 19 on ubuntu 22.04.

**Comment by sylvestre** [comment] 2024-09-20 17:34
Thanks for the confirmations.

**Comment by ChrisGreenaway** [comment] 2024-09-20 18:17
Works on debian bullseye.

**Comment by glebov-andrey** [comment] 2024-09-23 07:43
Works on Debian 10 (Buster)

**Comment by Zingam** [comment] 2024-09-24 06:39
I am unable to install LLVM20 due to unmet dependencies. Is this issue related: https://github.com/llvm/llvm-project/issues/109575

**Comment by henrythebuilder** [comment] 2024-09-24 08:19
At the moment I am unable to install/update the packages from Debian Bookworm, the update forces the removal of Chromium, this is the log of the simulated upgrade:

```
apt-get -s install clang-19 lldb-19 lld-19 clangd-19 clang-tidy-19 clang-format-19 clang-tools-19 llvm-19-dev lld-19 lldb-19 llvm-19-tools libomp-19-dev libc++-19-dev libc++abi-19-dev libclang-common-19-dev libclang-19-dev libclang-cpp19-dev libunwind-19-dev libclang-rt-19-dev libpolly-19-dev clang-19-doc llvm-19-doc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  lib32gcc-s1 lib32stdc++6 libc++1-19 libc++abi1-19 libc6-i386 libclang-cpp19 libclang1-19 libgrpc++1.51 libgrpc29 liblldb-19 libllvm19 libobjc-12-dev libomp5-19 libpfm4 libprotoc32
  libunwind-19 llvm-19 llvm-19-linker-tools llvm-19-runtime python3-lldb-19
Suggested packages:
  wasi-libc clang libomp-19-doc
The following packages will be REMOVED:
  chromium chromium-common chromium-l10n libc++1-16 libc++abi1-16 libunwind-16
The following NEW packages will be installed:
  clang-19 clang-19-doc clang-format-19 clang-tidy-19 clang-tools-19 clangd-19 lib32gcc-s1 lib32stdc++6 libc++-19-dev libc++1-19 libc++abi-19-dev libc++abi1-19 libc6-i386 libclang-19-dev
  libclang-common-19-dev libclang-cpp19 libclang-cpp19-dev libclang-rt-19-dev libclang1-19 libgrpc++1.51 libgrpc29 liblldb-19 libllvm19 libobjc-12-dev libomp-19-dev libomp5-19 libpfm4
  libpolly-19-dev libprotoc32 libunwind-19 libunwind-19-dev lld-19 lldb-19 llvm-19 llvm-19-dev llvm-19-doc llvm-19-linker-tools llvm-19-runtime llvm-19-tools python3-lldb-19
0 upgraded, 40 newly installed, 6 to remove and 0 not upgraded.
Remv chromium-l10n [129.0.6668.58-1~deb12u1]
Remv chromium [129.0.6668.58-1~deb12u1]
Remv chromium-common [129.0.6668.58-1~deb12u1]
Remv libc++1-16 [1:16.0.6-15~deb12u1]
Remv libc++abi1-16 [1:16.0.6-15~deb12u1]
Remv libunwind-16 [1:16.0.6-15~deb12u1]
Inst libllvm19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libclang-cpp19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libobjc-12-dev (12.2.0-14 Debian:12.7/stable [amd64])
Inst libclang-common-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst llvm-19-linker-tools (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libclang1-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst clang-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst clang-19-doc (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [all])
Inst clang-format-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst clang-tools-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst clang-tidy-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libprotoc32 (3.21.12-3 Debian:12.7/stable [amd64])
Inst libgrpc29 (1.51.1-3+b1 Debian:12.7/stable [amd64])
Inst libgrpc++1.51 (1.51.1-3+b1 Debian:12.7/stable [amd64])
Inst clangd-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libc6-i386 (2.36-9+deb12u8 Debian:12.7/stable [amd64])
Inst lib32gcc-s1 (12.2.0-14 Debian:12.7/stable [amd64])
Inst lib32stdc++6 (12.2.0-14 Debian:12.7/stable [amd64])
Inst libunwind-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libc++abi1-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libc++1-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libc++abi-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libunwind-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libc++-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libclang-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libclang-cpp19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libclang-rt-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst liblldb-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libomp5-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libomp-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst libpfm4 (4.13.0-1 Debian:12.7/stable [amd64])
Inst libpolly-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst lld-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst python3-lldb-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst lldb-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst llvm-19-runtime (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst llvm-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst llvm-19-tools (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst llvm-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Inst llvm-19-doc (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [all])
Conf libllvm19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libclang-cpp19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libobjc-12-dev (12.2.0-14 Debian:12.7/stable [amd64])
Conf libclang-common-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf llvm-19-linker-tools (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libclang1-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf clang-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf clang-19-doc (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [all])
Conf clang-format-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf clang-tools-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf clang-tidy-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libprotoc32 (3.21.12-3 Debian:12.7/stable [amd64])
Conf libgrpc29 (1.51.1-3+b1 Debian:12.7/stable [amd64])
Conf libgrpc++1.51 (1.51.1-3+b1 Debian:12.7/stable [amd64])
Conf clangd-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libc6-i386 (2.36-9+deb12u8 Debian:12.7/stable [amd64])
Conf lib32gcc-s1 (12.2.0-14 Debian:12.7/stable [amd64])
Conf lib32stdc++6 (12.2.0-14 Debian:12.7/stable [amd64])
Conf libunwind-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libc++abi1-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libc++1-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libc++abi-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libunwind-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libc++-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libclang-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libclang-cpp19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libclang-rt-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf liblldb-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libomp5-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libomp-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf libpfm4 (4.13.0-1 Debian:12.7/stable [amd64])
Conf libpolly-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf lld-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf python3-lldb-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf lldb-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf llvm-19-runtime (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf llvm-19 (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf llvm-19-tools (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf llvm-19-dev (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [amd64])
Conf llvm-19-doc (1:19.1.0~++20240920062301+64075837b553-1~exp1~20240920062432.44 apt.llvm.org [all])

```

**Comment by sylvestre** [comment] 2024-09-24 08:22
@henrythebuilder this is a different issue, please open a new issue

**Closed** 2024-09-24 08:22 UTC
Labels: packaging, platform:linux

**Comment by henrythebuilder** [comment] 2024-09-24 08:25
> @henrythebuilder this is a different issue, please open a new issue

ok, sorry for the mistake!
