### ISSUE TITLE
Header guard followed by `pragma once` is not obeyed

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#73023] opened 2023-11-21 18:23 UTC
https://gcc.godbolt.org/z/6cnd9qMjP courtesy of @filcab 

If a header has `#pragma once` under some kind of `#if` condition, with `-std=c++20`, the pragma is ignored. Adding `-fno-modules` doesn't help.

**Comment by pogo59** [comment] 2023-11-21 19:50
Updated description; it doesn't have to be a traditional header guard, just have the pragma under a condition (that causes the pragma to be read).

**Comment by AaronBallman** [comment] 2023-11-27 22:35
This only reproduces for me with `-fmodules`: https://gcc.godbolt.org/z/5eeWWbo5a

**Comment by AaronBallman** [comment] 2023-11-27 22:48
The issue is here: https://github.com/llvm/llvm-project/blob/c0fe0719df457b0992606b0f2a235719a5bbfd54/clang/lib/Lex/HeaderSearch.cpp#L1462

`isPragmaOnce` is true, but `TryEnterImported()` returns true for modules because of: https://github.com/llvm/llvm-project/blob/c0fe0719df457b0992606b0f2a235719a5bbfd54/clang/lib/Lex/HeaderSearch.cpp#L62

CC @ChuanqiXu9

**Comment by ChuanqiXu9** [comment] 2023-12-21 03:37
Sent https://github.com/llvm/llvm-project/pull/76119.

Also I find the reason why @pogo59 said he can reproduce this without `-fmodules` while @AaronBallman  said he can only reproduce this with `-fmodules`. The cause is that the feature `Modules` will be enabled either `-fmodules` is specified or `-std=c++20` is specified.

The history is that, clang chose the variable `Modules` as the feature variable for clang modules initially. (this is fine) Then when clang wants to implement C++20 Modules, clang wants to reuse a lot of existing components from clang modules. (We got there and indeed the implementation of clang modules help C++20 modules a lot too ). So once C++20 Modules is enabled, the variable `Modules` will be true. Then things happen.

The root cause should be, we'd better to create a new feature variable `ClangModules` and let the clang module specific behaviors dependent on that variable. And the variable `Modules` should only be related to the functionalities that are really commonly used.

**Comment by ChuanqiXu9** [comment] 2024-01-25 02:01
Reopen this https://github.com/llvm/llvm-project/pull/76119#issuecomment-1909214557 got reverted

**Comment by EugeneZelenko** [comment] 2024-01-26 00:01
Not merged yet.

**Comment by wjristow** [comment] 2024-11-14 08:01
> Reopen this https://github.com/llvm/llvm-project/pull/76119#issuecomment-1909214557 got reverted
> ...
> Not merged yet.

Although the commit was reverted and not re-instated, the problem ultimately was fixed in some work focused on modules, in commit 0cd0aa029647c8d1dba5c3d62f92325576796fa2 (https://github.com/llvm/llvm-project/pull/83660).  So I'm re-closing.

**Closed by wjristow** 2024-11-14 08:01 UTC
Labels: c++20, clang:frontend, clang:modules, confirmed
