### ISSUE TITLE
[packaging] Clang 14 is broken in Ubuntu focal

### ISSUE THREAD

**Issue by fslobanov** [llvm/llvm-project#60160] opened 2023-01-20 08:14 UTC
Hi folks!

It seems that libclang-rt-14-dev package is broken, because it conflicts with libclang-common-14-dev

According to https://apt.llvm.org/focal/pool/main/l/llvm-toolchain-14/ , changes were made at 11th Jan 2023

```
#5 101.9 Package: libclang-rt-14-dev
#5 101.9 Version: 1:14.0.6~++20230111091307+f28c006a5895-1~exp1~20230111091339.183
#5 101.9 Priority: optional
#5 101.9 Section: libdevel
#5 101.9 Source: llvm-toolchain-14
#5 101.9 Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
#5 101.9 Installed-Size: 44.5 MB
#5 101.9 Depends: lib32gcc-s1 (>= 3.0), lib32stdc++6 (>= 4.1.1), libc6 (>= 2.17), libc6-i386 (>= 2.17), libgcc-s1 (>= 3.0), libstdc++6 (>= 4.1.1)
#5 101.9 Breaks: libclang-common-14-dev (<< 1:14.0.6-10~exp4)
```

clang-rt-14-dev contains essential libraries such as builtins and so on, so linker fails to build application without them. These libraries were located at  libclang-common-14-dev package:

`/usr/bin/ld: cannot find /usr/lib/llvm-14/lib/clang/14.0.6/lib/linux/libclang_rt.builtins-x86_64.a: No such file or directory`

**Dockerfile to reproduce**

```
FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive
ARG LLVM_VERSION=14

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends software-properties-common curl gpg-agent \
    && curl https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    && add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${LLVM_VERSION} main" \
    && apt-get update -qq \
    && apt show libclang-common-${LLVM_VERSION}-dev \
    && apt show libclang-rt-${LLVM_VERSION}-dev \
    && apt-get install -qqy --no-install-recommends \
            llvm-${LLVM_VERSION} \
            libc++-${LLVM_VERSION}-dev \
            libc++abi-${LLVM_VERSION}-dev \
            libunwind-${LLVM_VERSION}-dev \
            clang-${LLVM_VERSION} \
            libclang-rt-${LLVM_VERSION}-dev
```

**Comment by MMory** [comment] 2023-01-20 11:53
Duplicate of #59903 and likely more. I would appreciate if this gets resolved, as it breaks our CI. I understand that clang/llvm 14 is not the most recent version, but since llvm 15 introduces breaking changes, migration to it is not trivial, at least not for us.

**Closed** 2023-01-20 13:15 UTC
Labels: new issue
