### ISSUE TITLE
Clang incorrectly instantiates conditional-explicit even when constraints are not satisfied

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#60710] opened 2023-02-13 15:16 UTC
In code like the following, Clang will instantiate the content of the conditional-explicit even when the constraint is not satisfied:

```cpp
template <some-constraint T>
  explicit(some-expression-involving-T)
constructor(T const&) { }
```

As a result, if `some-expression-involving-T` is not well-formed, Clang will issue a hard error even if `some-constraint` is not satisfied, in which case one would have expected that the constructor is removed from the overload sets instead.

Full reproducer:

```cpp
// clang++ -xc++ - -std=c++2b -fsyntax-only
#include <type_traits>
#include <utility>

template <class ...T>
struct tuple { };

template <class T>            struct IsPairLikeImpl : std::false_type { };
template <class T1, class T2> struct IsPairLikeImpl<tuple<T1, T2>> : std::true_type { };
template <class T>            concept IsPairLike = IsPairLikeImpl<T>::value;

template <class ...T>
constexpr auto f(tuple<T...> const&) {
    static_assert(sizeof...(T) == 2);
}

template <class T1, class T2>
struct pair {
    template <IsPairLike P>
    explicit(std::is_void_v<decltype(f(std::declval<P>()))>)
    pair(P const&) { }
};

template <class T>
concept can_construct_pair_from = requires (T t) {
    pair<int, int>(t);
};

static_assert(!can_construct_pair_from<tuple<int>>);
static_assert( can_construct_pair_from<tuple<int, int>>);
static_assert(!can_construct_pair_from<tuple<int, int, int>>);

int main() { }
```

Godbolt link: https://godbolt.org/z/7PjGqdjes

GCC and MSVC accept this code, Clang doesn't. This was discovered while trying to implement `pair-like` constructors for libc++.

**Comment by JMazurkiewicz** [comment] 2023-02-13 19:16
This is possibly duplicate of https://github.com/llvm/llvm-project/issues/59827.

**Comment by LYP951018** [comment] 2023-12-26 16:25
It seems that this bug has been fixed by https://github.com/llvm/llvm-project/pull/70548 . The code works with clang trunk.

**Closed by LYP951018** 2023-12-26 16:25 UTC
Labels: clang:frontend, rejects-valid, concepts, c++23
