### ISSUE TITLE
Object is not destructed while stack-unwinding

### ISSUE THREAD

**Issue by DKay7** [llvm/llvm-project#67074] opened 2023-09-21 23:47 UTC
I was solving cpp-quiz and got [question](https://cppquiz.org/quiz/question/323?result=OK&answer=bcad&did_answer=Answer) with followed code:
 
```cpp
#include <iostream>
#include <stdexcept>

struct A {
    A(char c) : c_(c) {}
    ~A() { std::cout << c_; }
    char c_;
};

struct Y { ~Y() noexcept(false) { throw std::runtime_error(""); } };

A f() {
    try {
        A a('a');
        Y y;
        A b('b');
        return {'c'};
    } catch (...) {
    }
    return {'d'};
}

int main()
{
    f();
}
```

According to standard, program's output should be `bcad`. But clang-18 produces just `bad`. I performed some tests and found out that A-object with `'c'` value was never destructed. Order of construction and destruction that I get is:

```
a CONSTRUCTED
b CONSTRUCTED
c CONSTRUCTED
b DESTRUCTED
a DESTRUCTED
d CONSTRUCTED
d DESTRUCTED
```

**Comment by Endilll** [comment] 2023-09-25 16:17
Confirmed: https://godbolt.org/z/Eo9hzjPhe
I feel like that it's not the first filed bug about (lack of) destruction of temporaries during unwinding, but I can't find other issues.

**Comment by zygoloid** [comment] 2023-09-25 23:26
Duplicate of #12658

**Closed by zygoloid** 2023-09-25 23:26 UTC
Labels: clang, c++, confirmed
