### ISSUE TITLE
clang-format crash on a simple code

### ISSUE THREAD

**Issue by sergio-nsk** [llvm/llvm-project#62946] opened 2023-05-26 04:11 UTC
Clang-Format version 15.0.7 on Windows 10

I've tried the code from here, updated it a bit and simplified the config:

`.clang-format`
```yaml
BasedOnStyle: LLVM
AlignArrayOfStructures: Left
```
`1.cc`
```c++
const some_type_t someVar = {
    .something = {
                  SOME_ENUM,
                  sizeof(some_32_array) / sizeof(int32_t), // Size
        some_32_array, // Pointer to data
        44100,                                    // Some comment
    }
};
```
The comma after 44100 causes the crash:
```console
> clang-format.exe 1.cc
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: "C:\\Program Files\\LLVM\\bin\\clang-format.exe" 1.cc
Exception Code: 0xC0000005
 #0 0x00007ff7012b30ac C:\Program Files\LLVM\bin\clang-format.exe 0xd30ac C:\Program Files\LLVM\bin\clang-format.exe 0xd2b24
 #1 0x00007ff7012b30ac C:\Program Files\LLVM\bin\clang-format.exe 0xd1410 C:\Program Files\LLVM\bin\clang-format.exe 0xce5e6
 #2 0x00007ff7012b30ac C:\Program Files\LLVM\bin\clang-format.exe 0x53fdf C:\Program Files\LLVM\bin\clang-format.exe 0xb5a59
 #3 0x00007ff7012b30ac C:\Program Files\LLVM\bin\clang-format.exe 0x63534 C:\Program Files\LLVM\bin\clang-format.exe 0x4b533
 #4 0x00007ff7012b30ac C:\Program Files\LLVM\bin\clang-format.exe 0x4bff9 C:\Program Files\LLVM\bin\clang-format.exe 0x55e8
 #5 0x00007ff7012b30ac C:\Program Files\LLVM\bin\clang-format.exe 0x3716 C:\Program Files\LLVM\bin\clang-format.exe 0x196af0
 #6 0x00007ff7012b30ac (C:\Program Files\LLVM\bin\clang-format.exe+0xd30ac)
 #7 0x00007ff7012b2b24 (C:\Program Files\LLVM\bin\clang-format.exe+0xd2b24)
0x00007FF7012B30AC, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0xD30AC byte(s)
0x00007FF7012B2B24, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0xD2B24 byte(s)
0x00007FF7012B1410, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0xD1410 byte(s)
0x00007FF7012AE5E6, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0xCE5E6 byte(s)
0x00007FF701233FDF, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0x53FDF byte(s)
0x00007FF701295A59, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0xB5A59 byte(s)
0x00007FF701243534, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0x63534 byte(s)
0x00007FF70122B533, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0x4B533 byte(s)
0x00007FF70122BFF9, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0x4BFF9 byte(s)
0x00007FF7011E55E8, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0x55E8 byte(s)
0x00007FF7011E3716, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0x3716 byte(s)
0x00007FF701376AF0, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF7011E0000) + 0x196AF0 byte(s)
0x00007FFF53EE7614, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFF53ED0000) + 0x17614 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FFF55E226A1, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFF55DD0000) + 0x526A1 byte(s), RtlUserThreadStart() + 0x21 byte(s)
```

**Comment by EugeneZelenko** [comment] 2023-05-26 04:16
Could you please try 16 or `main` branch?

**Comment by sergio-nsk** [comment] 2023-05-26 04:44
The same crash with 16.0.3.
```
> clang-format.exe 1.cc
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: "C:\\Program Files\\LLVM\\bin\\clang-format.exe" 1.cc
Exception Code: 0xC0000005
 #0 0x00007ff63ef6765b C:\Program Files\LLVM\bin\clang-format.exe 0xd765b C:\Program Files\LLVM\bin\clang-format.exe 0xd70b3
 #1 0x00007ff63ef6765b C:\Program Files\LLVM\bin\clang-format.exe 0xd5a00 C:\Program Files\LLVM\bin\clang-format.exe 0xd29f6
 #2 0x00007ff63ef6765b C:\Program Files\LLVM\bin\clang-format.exe 0x595cd C:\Program Files\LLVM\bin\clang-format.exe 0xb85f1
 #3 0x00007ff63ef6765b C:\Program Files\LLVM\bin\clang-format.exe 0x6b157 C:\Program Files\LLVM\bin\clang-format.exe 0x4f5d1
 #4 0x00007ff63ef6765b C:\Program Files\LLVM\bin\clang-format.exe 0x51609 C:\Program Files\LLVM\bin\clang-format.exe 0x5720
 #5 0x00007ff63ef6765b C:\Program Files\LLVM\bin\clang-format.exe 0x39b6 C:\Program Files\LLVM\bin\clang-format.exe 0x1a6c90
 #6 0x00007ff63ef6765b (C:\Program Files\LLVM\bin\clang-format.exe+0xd765b)
 #7 0x00007ff63ef670b3 (C:\Program Files\LLVM\bin\clang-format.exe+0xd70b3)
0x00007FF63EF6765B, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0xD765B byte(s)
0x00007FF63EF670B3, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0xD70B3 byte(s)
0x00007FF63EF65A00, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0xD5A00 byte(s)
0x00007FF63EF629F6, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0xD29F6 byte(s)
0x00007FF63EEE95CD, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0x595CD byte(s)
0x00007FF63EF485F1, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0xB85F1 byte(s)
0x00007FF63EEFB157, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0x6B157 byte(s)
0x00007FF63EEDF5D1, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0x4F5D1 byte(s)
0x00007FF63EEE1609, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0x51609 byte(s)
0x00007FF63EE95720, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0x5720 byte(s)
0x00007FF63EE939B6, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0x39B6 byte(s)
0x00007FF63F036C90, C:\Program Files\LLVM\bin\clang-format.exe(0x00007FF63EE90000) + 0x1A6C90 byte(s)
0x00007FFF53EE7614, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFF53ED0000) + 0x17614 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FFF55E226A1, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFF55DD0000) + 0x526A1 byte(s), RtlUserThreadStart() + 0x21 byte(s)
```
Where can I get clang-format.exe.pdb file?

**Comment by HC-pel** [comment] 2023-06-23 08:15
I believe I encountered the same crash in 16.0.2.
`.clang-format`:
```
---
AlignArrayOfStructures: Left
...
```
Reduced example:
```
#include <array>

const std::array<int, 3> test = {{
    1,
    2,
    3, // comment
}};
```
Backtrace:
```
0.	Program arguments: clang-format -i test.cpp
 #0 0x000055a744631d91 PrintStackTraceSignalHandler(void*) (.llvm.2738176987145136237) Signals.cpp:0:0
 #1 0x000055a744632915 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fccc268f420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x000055a7446ecb2b unsigned int clang::format::WhitespaceManager::getMaximumNetWidth<clang::format::WhitespaceManager::CellDescription*>(clang::format::WhitespaceManager::CellDescription* const&, clang::format::WhitespaceManager::CellDescription* const&, unsigned int, unsigned int, unsigned int) const WhitespaceManager.cpp:0:0
 #4 0x000055a7446ec656 clang::format::WhitespaceManager::alignArrayInitializersLeftJustified(clang::format::WhitespaceManager::CellDescriptions&&) ([...]/bin/clang-format+0x244656)
 #5 0x000055a7446eaf88 clang::format::WhitespaceManager::alignArrayInitializers(unsigned int, unsigned int) ([...]/bin/clang-format+0x242f88)
 #6 0x000055a7446e7353 clang::format::WhitespaceManager::generateReplacements() ([...]/bin/clang-format+0x23f353)
 #7 0x000055a74465d934 clang::format::(anonymous namespace)::Formatter::analyze(clang::format::TokenAnnotator&, llvm::SmallVectorImpl<clang::format::AnnotatedLine*>&, clang::format::FormatTokenLexer&) Format.cpp:0:0
 #8 0x000055a7446b37c1 clang::format::TokenAnalyzer::process(bool) ([...]/bin/clang-format+0x20b7c1)
 #9 0x000055a744671020 std::__1::__function::__func<clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::$_9, std::__1::allocator<clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*)::$_9>, std::__1::pair<clang::tooling::Replacements, unsigned int> (clang::format::Environment const&)>::operator()(clang::format::Environment const&) Format.cpp:0:0
#10 0x000055a7446528c0 clang::format::internal::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, unsigned int, unsigned int, unsigned int, llvm::StringRef, clang::format::FormattingAttemptStatus*) ([...]/bin/clang-format+0x1aa8c0)
#11 0x000055a74465378d clang::format::reformat(clang::format::FormatStyle const&, llvm::StringRef, llvm::ArrayRef<clang::tooling::Range>, llvm::StringRef, clang::format::FormattingAttemptStatus*) ([...]/bin/clang-format+0x1ab78d)
#12 0x000055a7445dc4c9 clang::format::format(llvm::StringRef) ClangFormat.cpp:0:0
#13 0x000055a7445d993c main ([...]/bin/clang-format+0x13193c)
#14 0x00007fccc2150083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#15 0x000055a7445d881e _start ([...]/bin/clang-format+0x13081e)
```
Removing either the last comma, the comment, or any of the other two elements fixes the crash.

**Comment by rymiel** [comment] 2023-06-23 14:47
Duplicate of #55493

**Closed by rymiel** 2023-06-23 14:47 UTC
Labels: clang-format, crash
