### ISSUE TITLE
Indent-level regression for AlignConsecutiveAssignments in clang-format 13.0.0, works in clang-format 12.0.1

### ISSUE THREAD

**Issue by JohnC32** [llvm/llvm-project#52913] opened 2021-12-29 16:02 UTC
The following file.cpp is  indented using clang-format 12.0.1:

```c++
namespace data_manager {
class Value {
  public:
    Value(int a, int b, int c, int d, int e, const double* f);
};
}  // namespace data_manager

enum {
    foobar12345,
    foobar12345678901234,
    foobar123456789012345,
    foobar123456789012345678901,
    foobar123456789012345678901234567890
};

void foo() {
    const double              val_data_k[] = {280};
    const data_manager::Value val_k        = data_manager::Value(
        foobar12345, foobar123456789012345678901234567890, foobar123456789012345,
        foobar12345678901234, foobar123456789012345678901, val_data_k);
}
```

If I run clang-format 13.0.0 on this the indent-level for the arguments to the data_manager::Value constructor are incorrect. They should be indented by 4 spaces relative to the prior statement but are indented by 12 spaces. Generally, the indent level for arguments seems to randomly vary with clang-format 13 whereas with clang-format 12.0.1 it's consistently 4 spaces relative to the prior statement.

```c++
namespace data_manager {
class Value {
  public:
    Value(int a, int b, int c, int d, int e, const double* f);
};
}  // namespace data_manager

enum {
    foobar12345,
    foobar12345678901234,
    foobar123456789012345,
    foobar123456789012345678901,
    foobar123456789012345678901234567890
};

void foo() {
    const double              val_data_k[] = {280};
    const data_manager::Value val_k        = data_manager::Value(
               foobar12345, foobar123456789012345678901234567890, foobar123456789012345,
               foobar12345678901234, foobar123456789012345678901, val_data_k);
}
```

Here's the _clang-format used in the above:

```yaml
---
BasedOnStyle: Google
ColumnLimit: 100
IndentWidth: 4
AccessModifierOffset: -2
BinPackParameters: false
AllowAllParametersOfDeclarationOnNextLine: false
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: Consecutive
CompactNamespaces: true
...
```
If you comment out the AlignConsecutiveAssignments, then clang-format 12.0.1 and 13.0.0 are both correct.

As a workaround for clang-format 13.0.0, if you introduce a comment after the open parenthesis, the indent-level is correct:

```c++
    const data_manager::Value val_k        = data_manager::Value(  //
        foobar12345, foobar123456789012345678901234567890, foobar123456789012345,
        foobar12345678901234, foobar123456789012345678901, val_data_k);
```
However, it's not practical to update large number of files that have been adversely impacted by this.

**Comment by thatguystone** [comment] 2022-01-03 18:34
I'm having the same problem in a slightly different context. It seems the indent is based on the number of spaces between the variable name and the equals, minus 1.

.clang-format:
```
---
BasedOnStyle: WebKit

AlignConsecutiveAssignments: true
AlignConsecutiveDeclarations: true
IndentWidth: 4
TabWidth: 4
UseTab: ForContinuationAndIndentation
```

Actual: In `test1`, with 4 spaces between `Type` and `b`, `.c` and `.d` have an extra 3 spaces. In `test2`, with 6 spaces, there are 5 extra spaces (1 four-width tab, 1 space).

```c
void test1()
{
	TypePad a = { 0 };
	Type    b = {
		   .c = -1,
		   .d = -1,
	};
}

void test2()
{
	TypePaddd a = { 0 };
	Type      b = {
			 .c = -1,
			 .d = -1,
	};
}
```

Expected: A constant indent size of 4 (1 tab).
```c
void test1()
{
	TypePad a = { 0 };
	Type    b = {
		.c = -1,
		.d = -1,
	};
}

void test2()
{
	TypePaddd a = { 0 };
	Type      b = {
		.c = -1,
		.d = -1,
	};
}
```

**Comment by owenca** [comment] 2024-04-28 21:57
Both examples above work in 18.1.4.

**Comment by thatguystone** [comment] 2024-05-25 00:04
This still appears to be a problem in 18.1.6.

**Comment by jamesdolan** [comment] 2024-09-01 19:46
Also, I am able to easily reproduce @thatguystone's examples on https://clang-format-configurator.site

**Comment by owenca** [comment] 2024-10-01 05:14
The original example at the top works in 19.1.0. The rest of this issue is a duplicate of #59809.

**Closed by owenca** 2024-10-01 05:14 UTC
Labels: bug, clang-format, regression
