### ISSUE TITLE
Why does not clang issue a warning for type coercion?

### ISSUE THREAD

**Issue by tokenizer-decode** [llvm/llvm-project#72957] opened 2023-11-21 06:01 UTC
Here clang issues a warning:
`int i = 1.4f; //Warning implicit type coercion`

But indirectly:
```
float f = 1.4;
int i = f; // No warning?
```

Why?

**Comment by chrchr-github** [comment] 2023-11-21 09:20
The warning is
~~~
<source>:1:9: warning: implicit conversion from 'float' to 'int' changes value from 1.4 to 1 [-Wliteral-conversion]
    1 | int i = 1.4f;
      |     ~   ^~~~
~~~
probably because the compiler knows the rhs,
There are bugprone-narrowing-conversions warnings for both instances.
https://godbolt.org/z/jjWM7o59e

**Comment by shafik** [comment] 2023-11-28 21:43
It looks like gcc puts this under `-Wconversion`: https://godbolt.org/z/7j31Td8G7

I don't have a strong inclination on this one.

CC @AaronBallman wdyt?

**Comment by AaronBallman** [comment] 2023-11-29 18:43
> Why?

To reduce chattiness. In the first case, we know the object will definitely change value due to type conversion and that's worth warning about. In the second case, we don't know if the value will or won't change. This is consistent with how we handle the literal case as well (when we know the value won't change): https://godbolt.org/z/xx4Tv8a8T

It appears that GCC does not look at the value of the initializer (https://godbolt.org/z/jsWbesW8r); so we seem to make different default assumptions. They assume the `float` holds a non-integral value and we assume it does. I think either assumption is defensible, but Clang usually errs on the side of not issuing diagnostics so that we don't overwhelm users with low-quality output.

I think this can be closed as Not a Bug (we do issue a warning under `-Wconversion` which we do not enable by default). Do others agree?

**Comment by cor3ntin** [comment] 2024-07-27 15:08
Makes sense to me

**Closed by cor3ntin** 2024-07-27 15:08 UTC
Labels: clang:diagnostics
