### ISSUE TITLE
s390x: fails to build SemaType.cpp with `cannot capture a bit-field by reference`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#56909] opened 2022-08-03 23:31 UTC
Regression from today:
```console
"/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/build-llvm/./bin/clang++" -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/lib/Sema -I"/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/clang/lib/Sema" -I"/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/clang/include" -Itools/clang/include -Iinclude -I"/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/llvm/include" -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/build-llvm/tools/clang/stage2-bins=build-llvm/tools/clang/stage2-bins -ffile-prefix-map=/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/= -no-canonical-prefixes -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3 -DNDEBUG  -fno-exceptions -std=c++14 -MD -MT tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaType.cpp.o -MF tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaType.cpp.o.d -o tools/clang/lib/Sema/CMakeFiles/obj.clangSema.dir/SemaType.cpp.o -c '/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/clang/lib/Sema/SemaType.cpp'
/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/clang/lib/Sema/SemaType.cpp:5436:40: error: cannot capture a bit-field by reference
              [&](unsigned i) { return FTI.Params[i].Param->getLocation(); });
                                       ^
/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/clang/lib/Sema/SemaType.cpp:5058:42: note: 'FTI' declared here
      DeclaratorChunk::FunctionTypeInfo &FTI = DeclType.Fun;
                                         ^
/build/llvm-toolchain-snapshot-16~++20220803063826+371610793491/clang/include/clang/Sema/DeclSpec.h:1553:27: note: bit-field is declared here
    FunctionTypeInfo      Fun;
                          ^
1 error generated.
```

Regression between 646e2f480336 and 371610793491

**Comment by fhahn** [comment] 2022-08-04 19:32
Likely culprit is https://reviews.llvm.org/D122768

@cor3ntin could you please take a look?

**Comment by cor3ntin** [comment] 2022-08-04 19:44
@fhahn This is caused by `44f2baa3804a62ca793f0ff3e43aa71cea91a795` - but it was reverted later yesterday.
I did bootstrap builds of the relanded patch locally so this should be fixed now.

So I *think* it was just a temporary issue (sorry about that). But please let me know if you are still seeing issues in main after `127bf44385424891eb04cff8e52d3f157fc2cb7c` . Thanks

**Comment by fhahn** [comment] 2022-08-05 10:30
Sounds good, I am closing this now. @sylvestre it would be great if you could double-check the issue is fixed on your end and re-open the issue if it still persists.

**Closed by fhahn** 2022-08-05 10:30 UTC
Labels: clang:frontend, build-problem
