### ISSUE TITLE
wrong code at -O3 on x86_64-linux_gnu (compiled code hangs)

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#59129] opened 2022-11-22 15:29 UTC
Compiler Explorer: https://godbolt.org/z/Gxfnjf9oc

It appears to be a regression from 13.0.1. 

```console
% clangtk -v
clang version 16.0.0 (https://github.com/llvm/llvm-project.git c08d3b08f6d71e974537de226c68d4c94c396a46)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
% 
% clangtk -O2 small.c; ./a.out
% 
% clangtk -O3 small.c
% timeout -s 9 5 ./a.out
Killed
% 
% cat small.c
int *a, **b = &a, c = 1, d, e, f;
int main() {
  int h = -2, i = -1;
  unsigned long j = 18446744073709551615UL;
 L:
  *b = &f;
  if (j >= 18446744073709551615UL)
    c = 0;
  while ((unsigned long)f <= j && h >= i)
    *a = 1;
  e = 1 - c;
  j = f = ~(j - e);
  d = ~-i;
  h = 0;
  int l = ~(f + d);
  if (l)
    goto L;
  return 0;
}
```

**Comment by nikic** [comment] 2023-03-07 11:07
Caused by https://github.com/llvm/llvm-project/commit/99d2582164c4bc8f10c3e3c20dd3690243ad49ba, closing this as duplicate of https://github.com/llvm/llvm-project/issues/60944.

**Closed by nikic** 2023-03-07 11:07 UTC
Labels: duplicate, miscompilation, SCEV
