### ISSUE TITLE
Other differences with GCC involving consecutive ## tokens.  See #113236.

### ISSUE THREAD

**Issue by mrolle45** [llvm/llvm-project#113270] opened 2024-10-22 06:37 UTC
When defining NDEBUG in a Debug build of clang, I found some important differences with GCC.

Input 
``` c
#define FOO(a,b,c) ;b########c,b##########c,a########a,a##########a,\
  b##a##a##a##c,b##a##a##a##a##c,a##a##a##a##a,a##a##a##a##a##a
FOO(,y,z)
FOO(x,y,z)
```

clang -E produces
``` c
 ;y####z,y####z,##,##, yz,yz,,
;y####z,y####z,x####x,x####x, yxxxz,yxxxxz,xxxxx,xxxxxx
```
gcc -E produces
``` c
;yz,yz,,, yz,yz,,
;yz,yz,xx,xx, yxxxz,yxxxxz,xxxxx,xxxxxx
```

It is apparent (without reading the actual GCC source code) that when it sees `####`, this is treated exactly the same as `##a##` with `a` being an empty parameter.

On the other hand, clang treats the second `##` as an ordinary token.

### Suggestion
When a parameter is empty, it would be simpler (and less error-prone) to make an actual placeholder token and follow the rules in the C standard for pasting.  Likewise, consecutive `##` tokens should be separated by a placeholder.  The only special cases you need are for the actual pasting of two tokens and the removal of placeholders later.  A placeholder only remains after pasting in a case like `a##a` or `a##a##a`.

Similarly, use a placeholder for `__VA_OPT__( tokens... )` when `__VA_ARGS__` is empty.

**Comment by shafik** [comment] 2024-10-22 17:22
Related: https://github.com/llvm/llvm-project/issues/112122

**Comment by pinskia** [comment] 2024-10-23 05:24
Looks like MSVC (and EDG) agrees with GCC:
```
;yz,yz,,, yz,yz,,
;yz,yz,xx,xx, yxxxz,yxxxxz,xxxxx,xxxxxx
```

**Comment by zygoloid** [comment] 2024-10-28 19:58
> Related: #112122

Is this not simply a duplicate of #112122?

**Closed** 2024-11-19 22:25 UTC
Labels: clang:frontend, diverges-from:gcc
