### ISSUE TITLE
constraints ignored on overloaded global 'operator=='

### ISSUE THREAD

**Issue by eridys** [llvm/llvm-project#59146] opened 2022-11-23 06:56 UTC
While trying to implement a global `operator==` for a specific type 
combination, Clang seems to ignore the given constraints.

The reduced test-case (https://godbolt.org/z/hnY8MjavY)
(Edit: More reduced https://godbolt.org/z/YxYbjnEYh)
```c++
#include <cstdint>
#include <iostream>
	
template <typename T>
struct result {
    T value;
    bool failed;

    constexpr operator const T&() const noexcept { return value; }
};

template <typename T>
    requires(false)
inline constexpr bool operator==(T lhs, bool rhs) noexcept {
    return static_cast<bool>(lhs) == rhs;
}

result<std::size_t> fn() { return {1, true}; }

int main() {
    auto res = fn();
    if (res == 1U) // <-- ERROR
        std::cout << "is one\n";
    else
        std::cout << "is not one\n";
}
```

produces the compiler error

```console
source:14:23: error: overloaded 'operator==' must have at least one parameter of class or enumeration type
inline constexpr bool operator==(T lhs, bool rhs) noexcept {
```

despite the template constraint `requires(false)`.

(Applies to all versions with C++-20 support, including trunk, see Godbolt link above.)

**Comment by cor3ntin** [comment] 2024-07-11 18:48
I believe clang is correct here (albeit it might be a wording defect)
Per https://eel.is/c++draft/over.oper#general-7

> An operator function shall [...] be a non-member function that has at least one non-object parameter whose type is a class

Nothing about checking that after overload resolution. @shafik @zygoloid

**Comment by zygoloid** [comment] 2024-07-12 00:19
[[temp.over]](https://eel.is/c++draft/temp.over) says we form a list of candidate functions by first performing deduction and checking, and only then synthesize a function declaration through instantiation. [[temp.deduct]](https://eel.is/c++draft/temp.deduct#general-5.sentence-7) says we reject candidates for which the constraints are not satisfied as part of the deduction phase. So we should never be instantiating `operator==<int>` according to the rules in the standard, so I think the rule that says it's ill-formed does not apply here.

It looks like Clang gets this backwards, and [instantiates the declaration](https://github.com/llvm/llvm-project/blob/1988c27e5f4dbcf42c9a80f44bdee7ccd208a0ac/clang/lib/Sema/SemaTemplateDeduction.cpp#L3887) immediately *before* checking constraints, rather than afterwards.

This is broken in some less subtle ways, [for example](https://godbolt.org/z/1zq9PbrEs):
```c++
template<typename T> struct X { using type = T::error; };
template<typename T> concept False = false;
template<False T> void f(T t, typename X<T>::type);
void f(...) {}
void g() { f(0, 0); }
```
This should be valid: the constraint means we should never substitute `T = int` into `typename X<T>::type`. But Clang does perform that substitution and incorrectly rejects. (MSVC too.)

This is [CWG2369](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2369).

**Comment by zygoloid** [comment] 2024-07-12 00:20
The constraint checking should instead be performed immediately before we [check for conversions for non-dependent parameters](https://github.com/llvm/llvm-project/blob/1988c27e5f4dbcf42c9a80f44bdee7ccd208a0ac/clang/lib/Sema/SemaTemplateDeduction.cpp#L3851).

**Comment by cor3ntin** [comment] 2024-08-09 15:37
Duplicate of #54440

**Closed** 2024-08-09 15:51 UTC
Labels: duplicate, c++20, clang:frontend, concepts
