### ISSUE TITLE
pointer (to dynamic multi dim array) conversion is rejected

### ISSUE THREAD

**Issue by franck-behaghel** [llvm/llvm-project#90357] opened 2024-04-27 20:51 UTC
The below code is rejected by Clang++ :
`cat main.cpp`
```cpp
void  init(int n1,int n2,int * data )
{
   int (*array_2d) [n1][n2] =( int (*)[n1][n2] )  data;
   for (int i1=0;i1<n1;i1++)
   for (int i2=0;i2<n2;i2++)
      (*array_2d)[i1][i2]=0;
}
```

I get :
```console
main.cpp:3:10: error: cannot initialize a variable of type 'int (*)[n1][n2]' with an rvalue of type 'int (*)[n1][n2]'
   int (*array_2d) [n1][n2] =( int (*)[n1][n2] )  data
```

note this is accepted by GCC and Clang (as a C source) and by G++ (as C++ source)

**Comment by shafik** [comment] 2024-04-28 05:18
This is a duplicate of: https://github.com/llvm/llvm-project/issues/59431

CC @AaronBallman @erichkeane for some further discussion before closing.

**Comment by AaronBallman** [comment] 2024-05-16 18:12
I agree that this is a duplicate (and I agree that we really need to improve the diagnostic message there because wow that's confusing).

**Closed by AaronBallman** 2024-05-16 18:12 UTC
Labels: duplicate, clang:frontend
