### ISSUE TITLE
[clang] Option -frounding-math not working as expected on x86

### ISSUE THREAD

**Issue by sfc-gh-lvolker** [llvm/llvm-project#59305] opened 2022-12-02 18:08 UTC
I'm trying to change the rounding mode using `fesetround` and it looks like Clang is still changing the order of instructions in a way that causes wrong results for floating point operations. This happens even when setting [-frounding-math](https://clang.llvm.org/docs/UsersManual.html#cmdoption-f-no-rounding-math).

To reproduce, consider this code (from GCC's [Bug 34678](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=34678) which describes the same issue):

```cpp
#include <cstdio>
#include <cstdlib>
#include <cfenv>

#include <cassert>

/**
 * With GCC
 * g++82 -O3 -lm -frounding-math -o round round.cc && ./round
 *
 * With Clang
 * clang++ -O3 -frounding-math -o round round.cc && ./round
 */


int main()
{
   double op;
   double down;
   double up;
   double near;

   op = atof("0.2");

   fesetround(FE_DOWNWARD);
   down = 1.0 / op;

   fesetround(FE_UPWARD);
   up = 1.0 / op;

   fesetround(FE_TONEAREST);
   near = 1.0 / op;

   printf("1/%.16g: down = %.16g near = %.16g up = %.16g\n", op, down, near, up);

   assert(down <= 5.0);
   assert(down <= near);
   assert(near <= up);
   assert(5.0 <= up);

   return 0;
}
```

Compiling and running this produces
```console
$ clang++ -O3 -frounding-math -o round round.cc && ./round
1/0.2: down = 4.999999999999999 near = 4.999999999999999 up = 4.999999999999999
round: round.cc:39: int main(): Assertion `5.0 <= up' failed.
[1]    10797 abort (core dumped)  ./round
```

The `clang++` version was `15.0.3`.

**Comment by topperc** [comment] 2022-12-02 18:48
It appears all of the divisions are being CSEd into a single division operation. Possibly in SelectionDAG? It doesn't happen with -ffp-model=strict or -ftrapping-math

**Comment by phoebewang** [comment] 2022-12-03 06:34
I think we didn't model rounding mode precisely. [D139246](https://reviews.llvm.org/D139246) could help with this if we manually replace `call i32 @fesetround` by `call void @llvm.set.rounding`. However, we don't have a way to invoke it in the front end according to [D74729](https://reviews.llvm.org/D74729). cc @spavloff

**Comment by topperc** [comment] 2022-12-03 06:52
Should calls be clobbering mxcsr?

**Comment by phoebewang** [comment] 2022-12-03 12:27
I'd guess not. Unlike we using `mayRaiseFPException` flag and setting `NoFPExcept` according to whether we are in trapping mode, we always modeling the use of `MXCSR` or `FPCW` for rounding. It may bring performance regression if we alway clobbering mxcsr for calls.
IIUC, currently constraint FP is supposed to be at function level granularity. Inlined function will inherit the constraint property. But it is not clear for non-inline function. I remember I saw a proposal that callee may preserve FP environments. I don't know what's the current status.
I'd suggest we just ignore to model the case that fesetround in non-inlined function.

**Comment by topperc** [comment] 2022-12-03 15:48
I believe this is the equivalent patch for this issue on PowerPC. https://reviews.llvm.org/D111433

**Comment by phoebewang** [comment] 2022-12-07 16:57
Thanks @topperc for the link. A candidate patch: https://reviews.llvm.org/D139549

**Comment by weiguozhi** [comment] 2022-12-19 21:49
> I'd guess not. Unlike we using mayRaiseFPException flag and setting NoFPExcept according to whether we are in trapping mode, we always modeling the use of MXCSR or FPCW for rounding. It may bring performance regression if we alway clobbering mxcsr for calls.

MXCSR is not listed in any CSR set, so semantically it should be clobbered by any function call. Power back end has similar behavior, it intendedly work like this https://reviews.llvm.org/D132987#3819683. I don't know if it's intended on X86.

Unfortunately MRI (wrongly) doesn't track RegMask correctly, a physical register clobbered by RegMask is missed by MRI, so CSE thinks the two DIV instructions use same value even they are crossing function call, so they are CSEd.

The MRI part can be fixed by https://reviews.llvm.org/D130919.

**Comment by phoebewang** [comment] 2022-12-20 11:45
> To reproduce, consider this code (from GCC's [Bug 34678](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=34678) which describes the same issue):

I think it's too conservative to assume every function will clobber `MXCSR`. Especially to assume user care about it in non strict FP model. This is the reason why we introducing [Constrained Floating-Point Intrinsics](https://llvm.org/docs/LangRef.html#id2143)

cc @uweigand, @andykaylor

**Comment by weiguozhi** [comment] 2022-12-20 17:02
It's not assumption, it's the semantic of implemented X86 CSR. If you don't want it to be clobbered by function call, you should add it to CSR. But then you need to invent some mechanism to let LLVM know fesetround can change MXCSR.

**Comment by phoebewang** [comment] 2022-12-21 08:54
We introduced MSCSR just for strict FP: https://github.com/llvm/llvm-project/commit/8f48ba993ba32925f37a374f624663da37d96254. We have already set MXCSR as reserved register, why do we expect it has the same semantic as common registers?
As https://reviews.llvm.org/D132987#3819683 said, it is status quo that RC register is not preserved by compiler. We can improve by honoring the supposed attribute. But we cannot strictly clobber it by default. It will give user surprise performance degradation and also against the intention of strict FP, which assumes `that the rounding mode is round-to-nearest` by default.
You can take a look at https://reviews.llvm.org/D111433. I think the change in cse-despite-rounding-mode.ll is definitely not expected:
```
; Without strictfp, CSE should be free to eliminate the repeated multiply
; and conversion instructions.
```

**Comment by weiguozhi** [comment] 2022-12-21 16:57
It seems "CSR" in my post was confused with "MXCSR". Here "CSR" means callee saved registers, the lists defined at the bottom of X86CallingConv.td, such as CSR_64, CSR_Win64. If you want to preserve a physical register across a function call, you should add it to the corresponding lists.

**Comment by andykaylor** [comment] 2022-12-21 18:39
According to the LLVM Language Reference (https://llvm.org/docs/LangRef.html#floating-point-environment) "The default LLVM floating-point environment assumes that floating-point instructions do not have side effects." The x86-64 ABI says that the status bits of the MXCSR register are callee saved, but in practice LLVM just assumes that nothing is modifying them unless we're using strictfp. 

The tricky thing here is that the entire MXCSR register shouldn't be preserved. From an ABIT point-of-view, we want the callee to be able to update the control bits (though again, LLVM IR assumes they don't exist). Only the control bits need to be preserved. At some point we experimented with modeling the control and status bits separately. I don't know what happened with that.

I would take the position that if the user code is changing MXCSR then the user code is responsible for restoring it, but I'll admit that my view on that is biased by the C language standard, which has the same expectation. If other languages require different behavior, we should consider the performance tradeoffs of always preserving the MXCSR control bits versus requiring use of strictfp.

**Comment by phoebewang** [comment] 2022-12-22 03:35
I understood the mean of "CSR". As andy indicated, I just want to indicate it (specifically speaking the control bits in MXCSR) is neither caller save nor callee save according to C language standard.
We introduced it just for strict FP scenarios. We don't want to play it with "CSR". Neither side is expected.

**Comment by weiguozhi** [comment] 2022-12-22 04:12
Let me try to clarify your expected MXCSR behavior:
  1. MXCSR should not be clobbered by function call
  2. MXCSR should be clobbered by fesetround, and maybe some other limited functions
  3. Normal explicit def / use of MXCSR.
 Is my understanding correct?

But MXCSR is defined as a register, it should obey some basic principles of registers, such as it can be clobbered by a RegMask or CSR if it is not included, even if you don't like it. If you want to avoid the interaction with CSR, you should define MXCSR as something other than a register.

**Comment by phoebewang** [comment] 2022-12-22 05:52
Not exactly. What I expected are:
1. (Ideally) MXCSR should be clobbered by fesetround, and maybe some other limited functions
2. (As a workaround) MXCSR should be clobbered by function call in strict FP mode and not clobbered otherwise

I didn't find a RFC, but introduing a new register and modeling its def/ues is the basestone we support the rounding control in strict FP. I can find the first implementation from @uweigand: https://github.com/llvm/llvm-project/commit/8e42f6ddc80f56e36264b1ec0f2d88df8486331e. Other targets include PowerPC follow the same design.

If you believe it is wrong, we have to find a new method to support strict FP before forcing to clobber it.

**Comment by weiguozhi** [comment] 2022-12-22 07:14
Thanks for the clarification. 

Most targets define rounding mode (and other control bits) as a special register, I think it's a natural choice. But then it will be inevitably impacted by CSR. 

A possible solution is choosing correct CSR (with or without MXCSR) according to current FP mode and function attribute in getCallPreservedMask(). We need some new function attribute to represent the modification of MXCSR.

**Comment by weiguozhi** [comment] 2022-12-22 07:32
Or add MXCSR to current CSR so it is preserved by default, but add an implicit def of MXCSR to call instruction according to current FP mode and function attribute.

**Closed** 2023-01-27 02:07 UTC
Labels: backend:X86
