### ISSUE TITLE
[clang-tidy] False positive bugprone-implicit-widening-of-multiplication-result when multiplying literals

### ISSUE THREAD

**Issue by chrchr-github** [llvm/llvm-project#83433] opened 2024-02-29 15:07 UTC
~~~c++
long long f() {
    return 1 * 2 * 3LL;
}
~~~
~~~
<source>:2:12: warning: performing an implicit widening conversion to type 'long long' of a multiplication performed in type 'int' [bugprone-implicit-widening-of-multiplication-result]
    2 |     return 1 * 2 * 3LL;
      |            ^
<source>:2:12: note: make conversion explicit to silence this warning
    1 | long long f() {
    2 |     return 1 * 2 * 3LL;
      |            ^~~~~
      |            static_cast<long long>( )
<source>:2:12: note: perform multiplication in a wider type
    2 |     return 1 * 2 * 3LL;
      |            ^
      |            static_cast<long long>( )
~~~
Clearly there is no danger of overflow here. Also, the suggested fix of adding a `static_cast` on a literal is rather silly.
https://godbolt.org/z/vjhzEqMKc

**Comment by felix642** [comment] 2024-02-29 17:01
Looks like a duplicate of https://github.com/llvm/llvm-project/issues/58709

**Comment by chrchr-github** [comment] 2024-02-29 19:12
There's also the even older https://github.com/llvm/llvm-project/issues/52806

**Closed** 2024-02-29 19:13 UTC
Labels: clang-tidy, false-positive

**Comment by cwarner-8702** [comment] 2024-07-16 14:54
A PR was merged yesterday that should address this for signed integer types (unsigned integers are a little more complicated, so it may take a bit longer): https://github.com/llvm/llvm-project/commit/f964e8a3f9ef9789f9075694cb887d0b3986d304
