### ISSUE TITLE
wrong code at -O1 and above on x86_64-linux-gnu 

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#56103] opened 2022-06-18 07:40 UTC
```console
% clangtk -v
clang version 15.0.0 (https://github.com/llvm/llvm-project.git be6af89f85ebd04646b5704301470f02b70a0447)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
% 
% clangtk -O0 small.c; ./a.out
% 
% clangtk -O1 small.c
% ./a.out
Aborted
% cat small.c
int a;
long b;
unsigned c;
static long *d = &b;
short e;
static short *f = &e, **g = &f, ***h = &g;
void i() {
  short *j[1];
  j[a] = &e;
  **h = j[0];
}
int main() {
  *d = *f = 1;
  unsigned short k = ~e >> a;
  long l = ~(~((c - 1) ^ (k - b)) | a);
  if (b > l)
    __builtin_abort();
  return 0;
}
```

Compiler Explorer: https://godbolt.org/z/Mh5cn1n55

**Comment by DimitryAndric** [comment] 2022-06-18 11:19
This appears to have regressed with d84ca05ef7f897fdd51900ea07e3c5344632130a / https://reviews.llvm.org/D124118 ("Enhance peephole optimization") by @minglotus-6.

**Comment by phoebewang** [comment] 2022-06-18 14:50
I think https://github.com/llvm/llvm-project/commit/d84ca05ef7f897fdd51900ea07e3c5344632130a just exposed the problem. The root cause is `jg/jge/jl/jle` also use `SF`, so we should check `NoSignFlag` before the optimization.
Candidate patch: https://reviews.llvm.org/D128122

**Comment by minglotus-6** [comment] 2022-06-18 22:26
Many thanks for the root cause and fix!

Comparing assembly of 14.01 [1] and truck [2] (diff in [3]), https://reviews.llvm.org/D124118 exposes the problem since the patch tries to optimize when a `SUBREG_TO_REG` instruction is used, and the reproducible example incluldes a pattern of `ecx` to `rcx` usage.

From a cursory look, the approach in https://reviews.llvm.org/D128122 looks reasonable. Going to follow up in D128122.

[1] https://godbolt.org/z/b8hPExnno
[2] https://godbolt.org/z/fvz91d1Pd
[3] https://www.diffchecker.com/h9dRa4pb

**Comment by nikic** [comment] 2022-06-21 10:12
Fixed by https://github.com/llvm/llvm-project/commit/edcc68e86f784fa6e1514f230a3c89a275a66bb6.

**Closed by nikic** 2022-06-21 10:12 UTC
Labels: backend:X86, miscompilation, llvm:optimizations
