### ISSUE TITLE
Clang rejects referencing local variable of class type to initialize template parameter in body of function template

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#49927] opened 2021-06-04 22:07 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [50583](https://llvm.org/bz50583) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
The following well-formed translation unit

```
struct integral_constant {
	static constexpr auto value = 0;
};

template<int>
struct s {};

template<typename>
void function_template() {
	[] {
		constexpr auto x = integral_constant();
		s<x.value>();
	};
}

void f() {
	function_template<void>();
}
```

is rejected by clang with the error message

```
<source>:12:5: error: variable 'x' cannot be implicitly captured in a lambda with no capture-default specified
                s<x.value>();
                  ^
<source>:17:2: note: in instantiation of function template specialization 'function_template<void>' requested here
        function_template<void>();
        ^
<source>:11:18: note: 'x' declared here
                constexpr auto x = integral_constant();
                               ^
<source>:10:2: note: lambda expression begins here
        [] {
        ^
<source>:10:3: note: capture 'x' by value
        [] {
         ^
         x
<source>:10:3: note: capture 'x' by reference
        [] {
         ^
         &x
<source>:10:3: note: default capture by value
        [] {
         ^
         =
<source>:10:3: note: default capture by reference
        [] {
         ^
         &
1 error generated.
Compiler returned: 1
```

See it live: https://godbolt.org/z/a5Mjh8ojv

A very similar translation unit,

```
struct integral_constant {
};

template<auto>
struct s {};

template<typename>
void function_template() {
	[] {
		constexpr auto x = integral_constant();
		s<x>();
	};
}

void f() {
	function_template<void>();
}
```

is rejected for the same bogus reason.

**Comment by JohelEGP** [comment] 2023-02-27 16:38
The same happens when you invoke a lambda during constant evaluation, see #61029.

**Comment by ldalessa** [comment] 2024-08-30 22:39
Ran into this today with
```c++
void foo()
{
    constexpr int x[]{1};
    using A = decltype([]<int=x>{});
}
```

Would be great to see this fixed.

**Comment by zyn0217** [comment] 2024-09-03 04:45
The original issue seems to have been fixed since around Clang 15.

https://godbolt.org/z/rKzKGs54z

**Comment by ldalessa** [comment] 2024-09-03 04:51
> The original issue seems to have been fixed since around Clang 15.
> 
> https://godbolt.org/z/rKzKGs54z

Oh weird. My issue seems new in clang-17.

https://godbolt.org/z/5T358neaY

Would it make more sense to create a new issue for this (or are you familiar with one that's active?).

**Comment by zyn0217** [comment] 2024-09-03 04:55
Yeah, I think that merits a new issue.
(My intuition is that this might be a regression caused by https://reviews.llvm.org/D124351, but I'm not sure before running a debugger.)

**Comment by ldalessa** [comment] 2024-09-03 05:03
Submitted as https://github.com/llvm/llvm-project/issues/107048.

**Comment by zyn0217** [comment] 2024-09-04 01:31
I'm closing this one - the case doesn't reproduce anyway.

**Closed by zyn0217** 2024-09-04 01:31 UTC
Labels: c++, clang:frontend, bugzilla, lambda, constexpr
