### ISSUE TITLE
ICE: fatal error: error in backend: Cannot select: intrinsic %llvm.thread.pointer

### ISSUE THREAD

**Issue by chengniansun** [llvm/llvm-project#50168] opened 2021-06-23 23:06 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [50824](https://llvm.org/bz50824) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
$ clang-trunk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

$ cat mutant.c
get_tp() { return __builtin_thread_pointer(); }

$ clang-trunk  mutant.c
mutant.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
get_tp() { return __builtin_thread_pointer(); }
^
mutant.c:1:19: warning: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
get_tp() { return __builtin_thread_pointer(); }
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
fatal error: error in backend: Cannot select: intrinsic %llvm.thread.pointer
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5c8659801a4976ef2b327f4071d98086efd42a36)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cnsun/usr/bin
clang-13: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/mutant-0e66db.c
clang-13: note: diagnostic msg: /tmp/mutant-0e66db.sh
clang-13: note: diagnostic msg:

********************

**Comment by wheatman** [comment] 2023-06-27 16:48
reproduces on 13.0.0
seems to be fixed on 14.0.0

https://godbolt.org/z/EnPj4GjGv

**Closed** 2023-06-27 17:13 UTC
Labels: c, bugzilla, llvm:crash
