### ISSUE TITLE
FR: Warn on copy when corresponding move op exists and the source is never used again

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#94799] opened 2024-06-07 20:16 UTC
Code like the following is a common source of extra copies in Chromium:
```
  void f1(T t);
  void f2(T t) { f1(t); }
```

When `T` has a move constructor, the caller presumably would have liked to invoke it.

The generalization of this is: I'd like to find code that has a `T`, copies from it (when a corresponding move op exists and isn't equivalent), and never reads from the source object again before it goes out of scope.

The case where this would fall down is if the read happens in a way the compiler can't detect, e.g. through some kind of pointer aliasing. This is almost never the case in practice in Chromium at least, but I'm not sure what sorts of safeguards need to be present.

To me this is such a clear pessimization that, like -Wpessimizing-move, it deserves a (possibly off-by-default) warning. But if I'm wrong, I would take a clang-tidy pass too.

**Comment by firewave** [comment] 2024-06-08 00:47
Duplicate of #53489.

**Closed** 2024-06-10 16:35 UTC
Labels: clang-tidy, check-request
