### ISSUE TITLE
[clang][FE] assert in Sema

### ISSUE THREAD

**Issue by ayermolo** [llvm/llvm-project#64819] opened 2023-08-18 22:01 UTC
Hello

I am getting assert in FE with trunk clang.
Small repro:
clang++ main.cpp -c -o main.o
```
#include <cstdint>
typedef int32_t __m256si_u
    __attribute__((__vector_size__(32), __may_alias__, __aligned__(1)));
template <uint8_t width>
void foo(const int* rows) {
auto indices = *reinterpret_cast<const __m256si_u*>(rows) * width;
}
```

partial stack:
```
#11 0x0000564d2ea190c3 canConvertIntToOtherIntTy(clang::Sema&, clang::ActionResult<clang::Expr*, true>*, clang::QualType) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Sema/SemaExpr.cpp:0:29
#12 0x0000564d2ea190c3 tryGCCVectorConvertAndSplat(clang::Sema&, clang::ActionResult<clang::Expr*, true>*, clang::ActionResult<clang::Expr*, true>*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Sema/SemaExpr.cpp:10964:9
#13 0x0000564d2ea13d67 clang::Sema::CheckVectorOperands(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, bool, bool, bool, bool, bool) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Sema/SemaExpr.cpp:11175:11
#14 0x0000564d2ea19c0e clang::Sema::CheckMultiplyDivideOperands(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, bool, bool) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Sema/SemaExpr.cpp:11452:12
#15 0x0000564d2ea060d6 clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Sema/SemaExpr.cpp:0:16
#16 0x0000564d2e9f1968 clang::Sema::ActOnBinOp(clang::Scope*, clang::SourceLocation, clang::tok::TokenKind, clang::Expr*, clang::Expr*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Sema/SemaExpr.cpp:16021:1
#17 0x0000564d2e5055c1 clang::Parser::ParseRHSOfBinaryExpression(clang::ActionResult<clang::Expr*, true>, clang::prec::Level) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseExpr.cpp:632:21
#18 0x0000564d2e504317 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseExpr.cpp:0:10
#19 0x0000564d2e55639a clang::Parser::ParseInitializer() /home/ayermolo/local/upstream-llvm/llvm-project/clang/include/clang/Parse/Parser.h:0:0
#20 0x0000564d2e55639a clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseDecl.cpp:2614:25
#21 0x0000564d2e553793 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseDecl.cpp:2348:21
#22 0x0000564d2e5529b8 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseDecl.cpp:0:10
#23 0x0000564d2e55237f clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseDecl.cpp:0:0
#24 0x0000564d2e598637 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseStmt.cpp:0:16
#25 0x0000564d2e596812 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseStmt.cpp:117:20
#26 0x0000564d2e5a0821 clang::Parser::ParseCompoundStatementBody(bool) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseStmt.cpp:1205:11
#27 0x0000564d2e5a185f clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseStmt.cpp:2468:21
#28 0x0000564d2e4e4f56 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/Parser.cpp:0:0
#29 0x0000564d2e588ce7 clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseTemplate.cpp:0:0
#30 0x0000564d2e586f0d clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseTemplate.cpp:0:0
#31 0x0000564d2e586826 clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseTemplate.cpp:0:0
#32 0x0000564d2e552196 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseDecl.cpp:1971:10
#33 0x0000564d2e4e1f93 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/Parser.cpp:0:0
#34 0x0000564d2e4e04b6 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/Parser.cpp:742:10
#35 0x0000564d2e4daf1e clang::ParseAST(clang::Sema&, bool, bool) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Parse/ParseAST.cpp:162:5
#36 0x0000564d2cc25a3f clang::FrontendAction::Execute() /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1067:10
#37 0x0000564d2cb9aa1d llvm::Error::getPtr() const /home/ayermolo/local/upstream-llvm/llvm-project/llvm/include/llvm/Support/Error.h:270:42
#38 0x0000564d2cb9aa1d llvm::Error::operator bool() /home/ayermolo/local/upstream-llvm/llvm-project/llvm/include/llvm/Support/Error.h:233:16
#39 0x0000564d2cb9aa1d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1054:23
#40 0x0000564d2cd032f3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/ayermolo/local/upstream-llvm/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:272:25
```

**Comment by shafik** [comment] 2023-08-18 22:21
Confirmed: https://godbolt.org/z/6WY99nP5W

Assert:

```console
clang++: /root/llvm-project/clang/lib/AST/ExprConstant.cpp:15370:
bool clang::Expr::EvaluateAsInt(clang::Expr::EvalResult&, const clang::ASTContext&, clang::Expr::SideEffectsKind, bool) const:
Assertion `!isValueDependent() && "Expression evaluator can't be called on a dependent expression."' failed.
```

Backtrace:

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -c <source>
1.	<source>:6:66: current parser token ';'
2.	<source>:5:27: parsing function body 'foo'
3.	<source>:5:27: in compound statement ('{}')
 #0 0x000000000368b5b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x368b5b8)
 #1 0x000000000368927c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x368927c)
 #2 0x00000000035d4968 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f76be94b420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f76be40e00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f76be3ed859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f76be3ed729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f76be3fefd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000000006ee5157 (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6ee5157)
 #9 0x00000000062b437f tryGCCVectorConvertAndSplat(clang::Sema&, clang::ActionResult<clang::Expr*, true>*, clang::ActionResult<clang::Expr*, true>*) SemaExpr.cpp:0:0
#10 0x0000000006348476 clang::Sema::CheckVectorOperands(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6348476)
#11 0x000000000634edb6 clang::Sema::CheckMultiplyDivideOperands(clang::ActionResult<clang::Expr*, true>&, clang::ActionResult<clang::Expr*, true>&, clang::SourceLocation, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x634edb6)
#12 0x0000000006355b7a clang::Sema::CreateBuiltinBinOp(clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6355b7a)
#13 0x000000000635750c clang::Sema::BuildBinOp(clang::Scope*, clang::SourceLocation, clang::BinaryOperatorKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x635750c)
#14 0x0000000006357833 clang::Sema::ActOnBinOp(clang::Scope*, clang::SourceLocation, clang::tok::TokenKind, clang::Expr*, clang::Expr*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6357833)
#15 0x0000000005e1da21 clang::Parser::ParseRHSOfBinaryExpression(clang::ActionResult<clang::Expr*, true>, clang::prec::Level) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e1da21)
#16 0x0000000005ddc5dd clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5ddc5dd)
#17 0x0000000005dea210 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5dea210)
#18 0x0000000005df2555 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5df2555)
#19 0x0000000005df29f7 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5df29f7)
#20 0x0000000005e92f50 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e92f50)
#21 0x0000000005e93c47 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e93c47)
#22 0x0000000005e94ba9 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e94ba9)
#23 0x0000000005e9649a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5e9649a)
#24 0x0000000005dc3281 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5dc3281)
#25 0x0000000005eafd90 clang::Parser::ParseSingleDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo const&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5eafd90)
#26 0x0000000005eb5343 clang::Parser::ParseTemplateDeclarationOrSpecialization(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (.part.0) ParseTemplate.cpp:0:0
#27 0x0000000005eb55c3 clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5eb55c3)
#28 0x0000000005df2b9b clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5df2b9b)
#29 0x0000000005dbd924 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5dbd924)
#30 0x0000000005dbe7ed clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5dbe7ed)
#31 0x0000000005db2b7a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5db2b7a)
#32 0x00000000048ef5c8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x48ef5c8)
#33 0x0000000004155619 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4155619)
#34 0x00000000040d936e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40d936e)
#35 0x00000000042358c6 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42358c6)
#36 0x0000000000bcf237 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbcf237)
#37 0x0000000000bc78ea ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#38 0x0000000003f31c69 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#39 0x00000000035d4e14 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x35d4e14)
#40 0x0000000003f3225f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#41 0x0000000003efa665 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3efa665)
#42 0x0000000003efb0cd clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3efb0cd)
#43 0x0000000003f02f95 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f02f95)
#44 0x0000000000bcd4cc clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbcd4cc)
#45 0x0000000000ac60a1 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xac60a1)
#46 0x00007f76be3ef083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#47 0x0000000000bc73ce _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbc73ce)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

**Comment by shafik** [comment] 2023-08-18 22:27
Looks like a duplicate of: https://github.com/llvm/llvm-project/issues/49570

**Comment by cor3ntin** [comment] 2023-08-19 13:28
@shafik agreed, closing as duplicate

**Comment by cor3ntin** [comment] 2023-08-30 07:48
Oups, forgot to actually close

**Closed by cor3ntin** 2023-08-30 07:48 UTC
Labels: duplicate, clang:frontend, confirmed, crash
