### ISSUE TITLE
CE when there is no implicit conversion while considering one of multiple functions from a overload set

### ISSUE THREAD

**Issue by ddvamp** [llvm/llvm-project#113898] opened 2024-10-28 11:33 UTC
Consider an example:
```
#include <cassert>

struct S {
  int x = 0;

  operator int const && () { return static_cast<int &&>(x); }
};

bool foo(int &&) { return false; }
bool foo(int const &&) { return true; }

int main() {
  assert(foo(S{}));  // error: no viable conversion from 'S' to 'int'

  return 0;
}
```
There is no implicit conversion from `S` to `int &&`, which means that the `foo(int const &&)` function should win, because
```
int const &&i1 = S{};  // well-formed
int &&i2 = S{};  // ill-formed
```

It looks like either an error occurs when defining `ICS` for `int &&` for ranking purposes, or for some reason the compiler decided that there is such an `ICS` and it is better than `ICS` for `int const &&`

gcc accepts this code

Please correct me if I'm wrong

**Comment by shafik** [comment] 2024-10-28 18:18
Duplicate of: https://github.com/llvm/llvm-project/issues/61121

**Closed by shafik** 2024-10-28 18:18 UTC
Labels: clang:frontend, diverges-from:gcc
