### ISSUE TITLE
libc++ std::reverse_iterator does not appear to correctly inherit or invoke iterator-based constructor

### ISSUE THREAD

**Issue by mattreecebentley** [llvm/llvm-project#55603] opened 2022-05-20 01:38 UTC
Clang is reporting it is unable to resolve a call to std::reverse_iterator(plf::hive<int *>::iterator), where hive overloads the class declaration to specialize for the hive iterator/reverse_iterator. 
Again with the latest version of plf::hive and it's test suite [here](https://github.com/mattreecebentley/plf_hive),
output via godbolt [here](https://godbolt.org/z/ee4cbEK8h) (consteval functions changed to constexpr to avoid related other non-related errors).

I am unclear what the issue is exactly here, but it is either a libc++ interaction or a clang interaction, and it appears to be something to do with either (a) std::reverse_iterator not inheriting the iterator-based constructor from hive::reverse_iterator, or (b) not matching to std::reverse_iterator overload at the bottom of plf_hive.h, line 4514.

The staggered errors as it tries to resolve follow:
1. no matching conversion for functional-style cast from 'plf::hive<int *>::hive_iterator<false>' to 'reverse_iterator<plf::hive<int *>::hive_iterator<false>>'
2. candidate constructor (the implicit copy constructor) not viable: no known conversion from 'plf::hive<int *>::hive_iterator<false>' to 'const std::reverse_iterator<plf::hive<int *>::hive_iterator<false>>' for 1st argument
3. candidate constructor (the implicit move constructor) not viable: no known conversion from 'plf::hive<int *>::hive_iterator<false>' to 'std::reverse_iterator<plf::hive<int *>::hive_iterator<false>>' for 1st argument
4.  candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided

If it is an error on my part, again it would be good to know what it is, as GCC11 and MSVC 2022 work fine with this code.
Thanks again-

**Comment by philnik777** [comment] 2022-05-21 09:41
This doesn't look like a libc++ bug, since you also get errors when using libstdc++. Also could you maybe make a reproducer that's not 6k lines long? I don't want to debug your program - that's your job, I want to know what the bug is.

**Comment by mattreecebentley** [comment] 2022-05-23 03:12
Hi there-
I don't get errors when I use GCC + libstdc++.
Both GCC11 and MSVC work fine.

It is either a clang or a libc++ problem.

The actual code as part of the repo which is causing the problem in 
clang/libc++ is the one line which has been pointed out to you.

This isn't my job, it's C++ standards committee stuff, and I don't get 
paid for it. Or any reward, actually. Anyway a reduced case follows:

#include <iterator>
#include <concepts>


namespace plf
{

template <class T>
concept hive_iterator_concept = requires { typename T::hive_iterator_tag; };


template <class T>
class hive
{
	public:

	T number;

	template <bool is_const>
	class hive_iterator;
	template <bool is_const_r>
	class hive_reverse_iterator;

	typedef hive_iterator<false> iterator;
	typedef hive_iterator<true> const_iterator;
	typedef hive_reverse_iterator<false> reverse_iterator;
	typedef hive_reverse_iterator<true> const_reverse_iterator;

	template <bool is_const>
	class hive_iterator
	{
	public:
		typedef hive_reverse_iterator<is_const> reverse_type;
		struct hive_iterator_tag {};
		typedef std::bidirectional_iterator_tag	iterator_category;
		typedef std::bidirectional_iterator_tag	iterator_concept;

		T* num;

		hive_iterator(T &number):
		num(&number)
		{}
	};


	template <bool is_const_r>
	class hive_reverse_iterator
	{
		public:

		struct hive_iterator_tag {};
		typedef std::bidirectional_iterator_tag	iterator_category;
		typedef std::bidirectional_iterator_tag	iterator_concept;

		T* num;

		hive_reverse_iterator(hive_iterator<is_const_r> &source):
		num(source.num)
		{}

		T operator*()
		{
			return *num;
		}
	};


	iterator begin()
	{
		return iterator(number);
	}

};


}

namespace std
{
	template <plf::hive_iterator_concept it_type>
	class reverse_iterator<it_type> : public it_type::reverse_type {};
}


int main()
{
	plf::hive<int> inthive;
	plf::hive<int>::reverse_iterator r_iterator = 
std::make_reverse_iterator(inthive.begin());
	return *r_iterator;
}

**Comment by philnik777** [comment] 2022-05-23 08:46
I get paid just as much as you for working on libc++. As a workaround you can add `reverse_iterator(it_type& it) : it_type::reverse_type(it) {}` to your `std::reverse_iterator<it_type>` for now. That fixes the problem. I think the deeper problem is that can hasn't implemented some paper yet. https://godbolt.org/z/3jrdPGec9 GCC also gives you an error pre-C++20. I don't know which paper made the change, so I'm transferring this issue to `clang:frontend` for now. It might already be claimed to be implemented.

**Comment by jwakely** [comment] 2022-05-26 20:10
It's documented as not implemented at https://clang.llvm.org/cxx_status.html#cxx20

**Comment by jwakely** [comment] 2022-05-26 20:14
> it appears to be something to do with either (a) std::reverse_iterator not inheriting the iterator-based constructor from hive::reverse_iterator

That's not what's supposed to happen here. Inheriting from a base class does not inherit its constructors unless you explicitly say to do that, via a `using` declaration for the base constructors. So it's completely correct that the derived class doesn't inherit constructors.

It "works" in C++20 because your type with no user-declared constructors is an aggregate, so can only be initialized using aggregate initialization. Before C++20, that means you have to use braces. Since C++20, you can use parens instead. But it's still doing aggregate init, because there are no constructors (inherited or otherwise) that you can call.

**Comment by mattreecebentley** [comment] 2022-05-27 00:15
Yes good point, will do:
	template <plf::hive_iterator_concept it_type>
	class reverse_iterator<it_type> : public it_type::reverse_type
	{
	public:
		typedef typename it_type::reverse_type rit;
		using rit::rit;
	};

However, from what you've said this is still a clang feature that needs 
to be implemented for C++20. So this bug report should probably fold 
under 'unimplemented'.

**Comment by frederick-vs-ja** [comment] 2023-12-20 10:46
The old issue looks resolved ([link](https://godbolt.org/z/Kc8sMG8YE)), see #54041. Perhaps we should close this as duplicate. Although there's still unexpected ambiguity which is probably same as that in #75404.

BTW, the motivation of this issue doesn't seem valid to me:
- when `hive` goes into the standard library one day, we can and probably should just change the bodies of `advance` etc., without adding overloads;
- but `hive` isn't a part of the standard library until then, and it's undefined behavior to add function overloads to namespace `std`.

**Comment by mattreecebentley** [comment] 2023-12-20 20:42
> The old issue looks resolved ([link](https://godbolt.org/z/Kc8sMG8YE)), see #54041. Perhaps we should close this as duplicate. Although there's still unexpected ambiguity which is probably same as that in #75404 (compiles fine with [some `const` dropped](https://godbolt.org/z/fj91bo1MT), while `const` shouldn't have effect here).
> 
> BTW, the motivation of this issue doesn't seem valid to me:
> 
>     * when `hive` goes into the standard library one day, we (implementations) can and probably should just change the bodies of `advance` etc., without adding overloads;
> 
>     * but `hive` isn't a part of the standard library until then, and it's undefined behavior to add function overloads to namespace `std`.

There are other containers other than plf::hive, which may benefit from non-ADL advance/etc overloads. slot maps spring to mind, as they may (depending on implementation) also be multi-block and may or may not have contiguous elements.
People work with undefined behaviour all the time, that part isn't an issue.

**Comment by jwakely** [comment] 2023-12-21 08:27
> People work with undefined behaviour all the time, that part isn't an issue.

I agree that it would be useful to make `advance` a customisation point, but currently it isn't, so only the std::lib can customise it. Changing that should go through wg21, not here.

If people "work with undefined behaviour" then they get to keep both pieces when they break it. It's not a bug in libc++ (or other third party code) if something doesn't work when playing with knives (to mix metaphors).

**Comment by mattreecebentley** [comment] 2023-12-21 23:10
> > People work with undefined behaviour all the time, that part isn't an issue.
> 
> I agree that it would be useful to make `advance` a customisation point, but currently it isn't, so only the std::lib can customise it. Changing that should go through wg21, not here.
> 
> If people "work with undefined behaviour" then they get to keep both pieces when they break it. It's not a bug in libc++ (or other third party code) if something doesn't work when playing with knives (to mix metaphors).

Game dev usefully work with UB all the time, so the question is not whether the above is explicitly a bug, it's whether the change is useful. It is. As to whether the change should go through WG21, I'll defer to you, but as the above does not cause problems in GCC/MSVC, what Exactly is the useful argument against allowing it here?

**Comment by jwakely** [comment] 2023-12-22 00:52
Because it relies on undefined behaviour, which means it could stop working in any of those compilers at any time. That's just not a sensible basis for writing reliable software.

In a game dev environment you might use a single toolchain that doesn't get updated, so "whatever happens to compile and run is ok" might be true. That's not acceptable in general though.

**Comment by mattreecebentley** [comment] 2023-12-24 21:11
Well, depends what area of UB. Heavily parallel work relies on UB all the time as well, largely due to the lifetime pointer zap issue, and no issues there cross-compiler. Some areas of UB are more typical in terms of how they're dealt with.
At any rate for this particular issue, as you've previously mentioned it will be sorted if-and-when libc++ updates to support [P0960R3](https://wg21.linkp0960r3/), so it's less about this particular issue, and more about compliance.

And Merry Christmas! :)

**Comment by frederick-vs-ja** [comment] 2023-12-25 00:53
> libc++ updates to support [P0960R3](https://wg21.linkp0960r3/)

Well, I don't think libc++ needs to update. Your example should _happen to_ work with libc++, and it is currently happen to be rejected only due to a bug of Clang frontend (which also incorrectly rejects some well-defined programs).

And Merry Christmas! :)

**Comment by mattreecebentley** [comment] 2024-02-10 21:34
Okay.

**Comment by frederick-vs-ja** [comment] 2024-02-15 02:13
Seems fixed on trunk by #81449. [Godbolt link](https://godbolt.org/z/KKTfYYo5K).

**Closed** 2024-07-26 11:06 UTC
Labels: clang:frontend
