### ISSUE TITLE
Failed loop simplification by -O3 (trunk v.s. 11.0.1)

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#55524] opened 2022-05-17 08:37 UTC
For the following code, clang trunk -O3 failed to optimize the loop and generated a lot of redundant instructions. You can see that clang-11.0.1 generated a much simpler assembly code.

```c
int a=0;
volatile int b[1] = {1};
int main() {
  for (; a >= 0; a--)
    b[0];
  return 0;
}
```

```console
$ clang-trunk -O3 a.c -S -o a-trunk.s
$ clang-11 -O3 a.c -S -o a-11.s
$ wc a-trunk.s a-11.s
  73  187 1508 a-trunk.s
  48  117 1047 a-11.s
 121  304 2555 total
```

#### a-11.s

```asm
main: 
        movl    a(%rip), %eax
        testl   %eax, %eax
        js      .LBB0_4
        addl    $1, %eax
.LBB0_2:
        movl    b(%rip), %ecx
        addl    $-1, %eax
        testl   %eax, %eax
        jg      .LBB0_2
        movl    $-1, a(%rip)
.LBB0_4:
        xorl    %eax, %eax
        retq
```

#### a-trunk.s

```asm
main: 
        movl    a(%rip), %eax
        testl   %eax, %eax
        js      .LBB0_9
        leal    1(%rax), %edx
        movl    %eax, %ecx
        andl    $7, %edx
        je      .LBB0_5
        xorl    %esi, %esi
.LBB0_3: 
        movl    b(%rip), %ecx
        incl    %esi
        cmpl    %esi, %edx
        jne     .LBB0_3
        movl    %eax, %ecx
        subl    %esi, %ecx
.LBB0_5:
        cmpl    $7, %eax
        jb      .LBB0_8
        incl    %ecx
.LBB0_7:
        movl    b(%rip), %eax
        movl    b(%rip), %eax
        movl    b(%rip), %eax
        movl    b(%rip), %eax
        movl    b(%rip), %eax
        movl    b(%rip), %eax
        movl    b(%rip), %eax
        movl    b(%rip), %eax
        addl    $-8, %ecx
        jne     .LBB0_7
.LBB0_8:
        movl    $-1, a(%rip)
.LBB0_9:
        xorl    %eax, %eax
        retq
```

**Comment by nikic** [comment] 2022-05-17 08:57
This just looks like loop unrolling to me? https://clang.godbolt.org/z/zxsn1dr8x

Given the nonsensical input (using volatile), one can't even argue whether this is a profitable transform or not.

**Comment by shao-hua-li** [comment] 2022-05-17 10:48
Perhaps. But there are a lot of meaningless instructions if you take a look at the a-trunk.s.
Especially the .LBB0_7 block.

**Comment by nikic** [comment] 2022-05-17 11:37
The LBB0_7 block contains the unrolled loop. The instructions are meaningless because you used meaningless instructions (volatile load, which cannot be eliminated).

**Comment by fhahn** [comment] 2022-05-19 19:49
I don't think there's much we can improve. The issue is that we don't know the trip count of the loop, so unrolling seems reasonable.

Note that if `a` would be `static`, we would figure out that the loop only executes once. Without `static` we are missing guarantees to reason about the trip count.

I'm closing the issue, but please feel free to re-open the issue if you think there's anything we could do better.

**Closed by fhahn** 2022-05-19 19:49 UTC
Labels: llvm:optimizations
