### ISSUE TITLE
clang-tidy: misc-include-cleaner: Unused includes not removed from .h file

### ISSUE THREAD

**Issue by JanMatCodasip** [llvm/llvm-project#113927] opened 2024-10-28 15:29 UTC
In the attached example, unused includes `#include <stdio.h>` and `#include <inttypes.h>` are not removed from `number_generator.h`.

These are the steps to reproduce:

```
# Extract the attached archive
tar xvf test-includes.tar.gz
cd test-includes

# Build the example program (compilation database is also created in the process)
mkdir build && cd build
cmake ..
cmake --build .

run-clang-tidy-18.py -header-filter='-*' -checks='-*,misc-include-cleaner' -fix

# Observe that number_generator.h still contains `#include <stdio.h>` and `#include <inttypes.h>`, despite being unused.
```

(Note that the attached example as well as the steps to reproduce are identical to issue https://github.com/llvm/llvm-project/issues/113926.)

Thank you.

[test-includes.tar.gz](https://github.com/user-attachments/files/17544830/test-includes.tar.gz)

**Comment by 5chmidti** [comment] 2024-11-03 12:20
This is a duplicate of #67550. Please see https://github.com/llvm/llvm-project/issues/67550#issuecomment-1740776296 as the current answer and https://github.com/llvm/llvm-project/issues/67550#issuecomment-1740861311 as a possible workaround on this topic.

**Closed by 5chmidti** 2024-11-03 12:20 UTC
Labels: duplicate, clang-include-cleaner
