### ISSUE TITLE
openmp/libompd/test/CMakeLists.txt is failing with  `Could not find a package configuration file`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#58941] opened 2022-11-11 16:35 UTC
On Linux
316e2599029e was ok
61c2276cb231 is failing

```console
-- Looking for __atomic_load_1 in atomic - found
-- Found Python3: /usr/bin/python3.10 (found version "3.10.8") found components: Interpreter Development Development.Module Development.Embed 
CMake Error at /build/llvm-toolchain-snapshot-16~++20221111111130+61c2276cb231/openmp/libompd/test/CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/build/llvm-toolchain-snapshot-16~++20221111111130+61c2276cb231/build-llvm/tools/clang/stage2-bins/CMakeFiles/CMakeOutput.log".
See also "/build/llvm-toolchain-snapshot-16~++20221111111130+61c2276cb231/build-llvm/tools/clang/stage2-bins/CMakeFiles/CMakeError.log".
```

I guess 1099498e3f35b2ad4b021ba3888b590259124e74 is the regressor
cc @vigbalu

log:
https://llvm-jenkins.debian.net/view/Debian%20sid/job/llvm-toolchain-binaries/architecture=amd64,distribution=unstable,label=amd64/729/console

**Comment by ms178** [comment] 2022-11-11 19:05
As there were several OpenMP related committs today, I just want to chime in that I also see a build problem due to OpenMP when building the library `pixman`:

```
WARNING: OpenMP found but omp.h missing.
Run-time dependency OpenMP found: NO (tried system)
pixman/meson.build:398:2: ERROR: Dependency "openmp" not found, tried system
```

[meson-log.txt](https://github.com/llvm/llvm-project/files/9992776/meson-log.txt)

**Comment by jhuber6** [comment] 2022-11-11 19:11
> As there were several OpenMP related committs today, I just want to chime in that I also see a build problem due to OpenMP when building the library `pixman`:
> 
> ```
> WARNING: OpenMP found but omp.h missing.
> Run-time dependency OpenMP found: NO (tried system)
> pixman/meson.build:398:2: ERROR: Dependency "openmp" not found, tried system
> ```
> 
> [meson-log.txt](https://github.com/llvm/llvm-project/files/9992776/meson-log.txt)

I heard a similar report but was unable to reproduce it. Would it be possible for you to bisect it? I think it's a very recent change.

**Comment by ms178** [comment] 2022-11-11 21:24
> I heard a similar report but was unable to reproduce it. Would it be possible for you to bisect it? I think it's a very recent change.

I am sorry, I cannot be of help on this as I use this system in production and there were a couple of other bugs I am chasing. I'll keep an eye on llvm-git during the next couple of days and can report back.

**Comment by sylvestre** [comment] 2022-11-11 21:42
> WARNING: OpenMP found but omp.h missing.

seems like a different issue. please create a separate issue for your problem.

**Comment by ms178** [comment] 2022-11-11 23:36
Yeah, but chances are that the same change is responsible for this. As I encountered yet another OpenMP build issue, I'll open other tickets for this if the issue is not resolved by a revert or fix in a couple of days.

**Comment by shiltian** [comment] 2023-01-16 18:21
Looks like it's been fixed.

**Closed by shiltian** 2023-01-16 18:21 UTC
Labels: openmp, build-problem
