### ISSUE TITLE
Clang front-end crash when lambda-capturing result of invalid structured binding

### ISSUE THREAD

**Issue by fahadnayyar** [llvm/llvm-project#72198] opened 2023-11-14 02:56 UTC
clang front-end crashes when lambda-capturing result of invalid structured binding.

Steps To Reproduce:

```c++
// test.cpp
void crash() {
    const int &[a, b] = {0, 0};
    auto x = [b]() -> int {
        return b;
    };
}
```

```
$ clang++ -std=gnu++17 -c test.cpp
```

Results:
Diagnostic output correctly reflects that program is invalid but the front-end also crashes.
https://godbolt.org/z/EfTbh1zKP

**Comment by shafik** [comment] 2023-11-14 03:37
Confirmed: https://godbolt.org/z/PMKx73Gbz

Assertions build are usually more useful since they will usually crash earlier and give a better indication of the underlying issue.

Assertion:

```console
clang++: /root/llvm-project/clang/include/clang/AST/Type.h:752:
const clang::ExtQualsTypeCommonBase* clang::QualType::getCommonPtr() const:
Assertion `!isNull() && "Cannot retrieve a NULL type pointer"' failed.
```

Backtrace:

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:7:17: current parser token '('
2.	<source>:5:14: parsing function body 'crash'
3.	<source>:5:14: in compound statement ('{}')
4.	<source>:7:14: lambda expression parsing
 #0 0x000000000378b8f8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x378b8f8)
 #1 0x00000000037895dc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x37895dc)
 #2 0x00000000036d2148 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f337311d420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f3372be000b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f3372bbf859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f3372bbf729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f3372bd0fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000000003ab2fbf clang::QualType::getNonReferenceType() const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ab2fbf)
 #9 0x000000000645ff08 clang::Sema::tryCaptureVariable(clang::ValueDecl*, clang::SourceLocation, clang::Sema::TryCaptureKind, clang::SourceLocation, bool, clang::QualType&, clang::QualType&, unsigned int const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x645ff08)
#10 0x000000000646202f clang::Sema::tryCaptureVariable(clang::ValueDecl*, clang::SourceLocation, clang::Sema::TryCaptureKind, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x646202f)
#11 0x0000000006684997 clang::Sema::ActOnLambdaExpressionAfterIntroducer(clang::LambdaIntroducer&, clang::Scope*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6684997)
#12 0x0000000005f95ffc clang::Parser::ParseLambdaExpressionAfterIntroducer(clang::LambdaIntroducer&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f95ffc)
#13 0x0000000005f97a2b clang::Parser::ParseLambdaExpression() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f97a2b)
#14 0x0000000005f75bb5 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f75bb5)
#15 0x0000000005f775ba clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f775ba)
#16 0x0000000005f77759 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f77759)
#17 0x0000000005f37f8d clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f37f8d)
#18 0x0000000005f456a0 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f456a0)
#19 0x0000000005f4dac5 clang::Parser::ParseSimpleDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, bool, clang::Parser::ForRangeInit*, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f4dac5)
#20 0x0000000005f4df67 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f4df67)
#21 0x0000000005fee370 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5fee370)
#22 0x0000000005fef067 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5fef067)
#23 0x0000000005feff89 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5feff89)
#24 0x0000000005ff18aa clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5ff18aa)
#25 0x0000000005f1e931 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f1e931)
#26 0x0000000005f45da8 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f45da8)
#27 0x0000000005f12b2b clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f12b2b)
#28 0x0000000005f132b1 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f132b1)
#29 0x0000000005f1a586 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f1a586)
#30 0x0000000005f1b42d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f1b42d)
#31 0x0000000005f1b900 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f1b900)
#32 0x0000000005f0e412 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5f0e412)
#33 0x00000000040052a8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40052a8)
#34 0x000000000426abe9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x426abe9)
#35 0x00000000041eb12e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41eb12e)
#36 0x0000000004349eee clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4349eee)
#37 0x0000000000bf81d6 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbf81d6)
#38 0x0000000000befa9a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#39 0x00000000040465c9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#40 0x00000000036d25f4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x36d25f4)
#41 0x0000000004046bbf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#42 0x000000000400eb35 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x400eb35)
#43 0x000000000400f59d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x400f59d)
#44 0x00000000040174c5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x40174c5)
#45 0x0000000000bf567c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbf567c)
#46 0x0000000000aef401 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xaef401)
#47 0x00007f3372bc1083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#48 0x0000000000bef57e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbef57e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

**Comment by shafik** [comment] 2023-11-14 03:42
Reduced a bit: https://godbolt.org/z/7qa7Te48h

```cpp
void crash() {
    int [_, b] = {0, 0};
    [b]{};
}
```

**Comment by shafik** [comment] 2023-11-14 18:53
So we diagnose the issue w/ the structured bindings but we don't turn it into an invalid decl: 

https://github.com/llvm/llvm-project/blob/410f130bb99b88f1a8f21659d98053e6f3e5e8f6/clang/lib/Sema/SemaDeclCXX.cpp#L856-L869

If we attempt to turn it into an invalid decl is break a bunch of expected diagnostics.

So we end up in `Sema::tryCaptureVariable(...)` with a `DecompositionDecl` that contains a `RecoveryExpr`:

```console
DecompositionDecl 0x10c808200 <decompCrash.cpp:2:5, col:23> col:9 'int' cinit
|-RecoveryExpr 0x10c808308 <col:18, col:23> '<dependent type>' contains-errors lvalue
| `-InitListExpr 0x10c8082b8 <col:18, col:23> 'void'
|   |-IntegerLiteral 0x10c808278 <col:19> 'int' 0
|   `-IntegerLiteral 0x10c808298 <col:22> 'int' 0
|-BindingDecl 0x1330e4738 <col:10> col:10 _ 'NULL TYPE'
`-BindingDecl 0x1330e4780 <col:13> col:13 b 'NULL TYPE'
```

We could do a `isNull()` check there but it feels like this should be caught a lot earlier.

if I modify this code:

https://github.com/llvm/llvm-project/blob/410f130bb99b88f1a8f21659d98053e6f3e5e8f6/clang/lib/Sema/SemaLambda.cpp#L1194-L1195

and add this check it catches way earlier:

```cpp
       if (auto *DD = BD->getDecomposedDecl())
          if ( auto *VD = DD->getPotentiallyDecomposedVarDecl())
            if ( auto *Init = VD->getAnyInitializer())
              if (Init->containsErrors())
                continue;
```

It looks like we are catching a bunch of problematic cases in that function as well but not sure if this is the right way to handle the `RecoveryExpr` or not.

CC @AaronBallman @hokein @cor3ntin

**Comment by hokein** [comment] 2023-11-15 13:57
> If we attempt to turn it into an invalid decl is break a bunch of expected diagnostics.

I think this is the right way to fix the issue.

Does it break a lot of existing testcase? This will affect some diagnostic behaivor, but it should be in a limited scope -- some follow-up diagnostics will not be displayed anymore. Depending on the case, but I think it should be fine.


> DecompositionDecl 0x10c808200 <decompCrash.cpp:2:5, col:23> col:9 'int' cinit
|-RecoveryExpr 0x10c808308 <col:18, col:23> '<dependent type>' contains-errors lvalue
| `-InitListExpr 0x10c8082b8 <col:18, col:23> 'void'
|   |-IntegerLiteral 0x10c808278 <col:19> 'int' 0
|   `-IntegerLiteral 0x10c808298 <col:22> 'int' 0
|-BindingDecl 0x1330e4738 <col:10> col:10 _ 'NULL TYPE'
`-BindingDecl 0x1330e4780 <col:13> col:13 b 'NULL TYPE'

The AST looks ill-formed, the `BindingDecl` is valid but with a NULL type, it will break some clang invariants thus leads to crashes. For this case, we should mark the `DecompositionDecl` and its `BindingDecl`s invalid. 

We already do this for cases `int [_, b];`, `int [_, b] = 1;`, but not for `int [_, b] = {0, 0};`, this seems like an oversight.

> It looks like we are catching a bunch of problematic cases in that function as well but not sure if this is the right way to handle the RecoveryExpr or not.

`RecoveryExpr` is not the root cause, we still have crashes without building the RecoveryExpr. 

```
// ./bin/clang -cc1 -ast-dump -fno-recovery-ast /tmp/t.cpp
void crash() {
    int [_, b] = {0, 0}; 
    [b]{};
}
```

**Comment by hokein** [comment] 2023-11-15 19:42
> This looks similar to https://github.com/llvm/llvm-project/issues/67495

Thanks! Yeah, they are similar.  https://github.com/llvm/llvm-project/pull/72428 is my attempt to fix them, it doesn't cause any diagnostic regressions.

**Comment by shafik** [comment] 2023-11-15 19:55
> > This looks similar to #67495
> 
> Thanks! Yeah, they are similar. #72428 is my attempt to fix them, it doesn't cause any diagnostic regressions.

That looks like a much better fix, I should have looked for where we create the `RecoveryExpr` now that I think about it.

When I set it to an invalid decl in `Sema::ActOnDecompositionDeclarator(...)` it broke about five tests and the diagnostics looked mostly valid.

**Comment by ecnelises** [comment] 2023-11-16 02:40
Thanks! I'd like to close #72230

**Comment by hokein** [comment] 2024-01-17 13:10
Fixed by https://github.com/llvm/llvm-project/pull/72428.

**Closed by hokein** 2024-01-17 13:10 UTC
Labels: clang:frontend, confirmed, crash
