### ISSUE TITLE
 clang refuses to match dependent reference non-type template parameter in partial specialization

### ISSUE THREAD

**Issue by Rush10233** [llvm/llvm-project#102314] opened 2024-08-07 13:47 UTC
The following code used to be accepted but is now rejected after clang-16:

```c++
template<int, class T, T> struct S;
template<class T, T A> struct S<0, T, A> {};
int i;
S<0, int*, &i> r;  // OK
S<0, int&, i> s;
```
The diagnostic shows that `template<class T, T A> struct S<0, T, A> {};` is not chosen for the instantiation of `S<0, int&, i> s;`.

```c++
<source>:5:15: error: implicit instantiation of undefined template 'S<0, int &, i>'
    5 | S<0, int&, i> s;  
      |               ^
<source>:1:34: note: template is declared here
    1 | template<int, class T, T> struct S;
      |                                  ^
1 error generated.
```

I'm not sure but it seems that implicit conversions like `int & A=i` should be taken into consideration. Note that non-type dependent pointer argument can be successfully matched as shown in the fourth line of the test.

GCC and MSVC accept the code.

[https://godbolt.org/z/jcMP8938e](https://godbolt.org/z/jcMP8938e)

**Comment by cor3ntin** [comment] 2024-08-07 14:07
Duplicate of https://github.com/llvm/llvm-project/issues/73460

**Closed** 2024-08-07 14:07 UTC
Labels: duplicate, clang:frontend, diverges-from:gcc, diverges-from:msvc
