### ISSUE TITLE
Unexpected evaluation-point of std::souce_location::current()

### ISSUE THREAD

**Issue by aasimon** [llvm/llvm-project#56580] opened 2022-07-17 10:41 UTC
Consider three files: log.h, log.cc and main.cc

log.h:
```c++
#pragma once

#include <string>
#include <source_location>

void log(const std::string& message,
         const std::source_location location = std::source_location::current());
````

log.cc:
```c++
#include "log.h"

#include <iostream>

void log(const std::string& message,
         const std::source_location location)
{
  std::cout << message << " " << location.file_name() << ":" << location.line() << '\n';
}
```

and main.cc:
```c++
#include "log.h"

int main()
{
  log("hello");
}
```

Compiling with latest clang++-15 trunk:
```
$ clang++-15 --version
Debian clang version 15.0.0-++20220715100655+5e0443292bf0-1~exp1~20220715220804.622
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
$ clang++-15 -std=c++20 log.cc main.cc -o test
```

Running is expected to give the result "hello main.cc:5" (which is the case for g++-11) but in fact gives:
```
$ ./test
hello ./log.h:7
```

**Comment by tbaederr** [comment] 2022-07-17 10:56
Duplicate of https://github.com/llvm/llvm-project/issues/56379

**Closed by tbaederr** 2022-07-17 10:56 UTC
Labels: new issue
