### ISSUE TITLE
consteval crash in codegen

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#53795] opened 2022-02-12 19:56 UTC
```c++
struct array {
	char buffer[1];
};

struct fixed_string: array {
	constexpr fixed_string(): array{} { }
};

consteval auto get_fixed_string() noexcept {
	return fixed_string{};
}

void foo() {
    get_fixed_string();
}
```
clang -std=c++20 -O0 -emit-llvm
https://compiler-explorer.com/z/6W156T5db

```
void llvm::StoreInst::AssertOK(): Assertion `cast<PointerType>(getOperand(1)->getType()) -isOpaqueOrPointeeTypeMatches(getOperand(0)->getType()) && "Ptr must be a pointer to Val type!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /usr/local/bin/clang-13 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name constevalcrash.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/home/xbolva00/AirStatus -resource-dir /usr/local/lib/clang/15.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/backward -internal-isystem /usr/local/lib/clang/15.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/home/xbolva00/AirStatus -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/constevalcrash-da08db.o -x c++ constevalcrash.cpp
1.      <eof> parser at end of file
2.      constevalcrash.cpp:13:6: LLVM IR generation of declaration 'foo'
3.      constevalcrash.cpp:13:6: Generating code for declaration 'foo'
 #0 0x000055ead86562af PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055ead86538ee SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f6a38c928a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #3 0x00007f6a37943f47 raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #4 0x00007f6a379458b1 abort /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81:0
 #5 0x00007f6a3793542a __assert_fail_base /build/glibc-2ORdQG/glibc-2.27/assert/assert.c:89:0
 #6 0x00007f6a379354a2 (/lib/x86_64-linux-gnu/libc.so.6+0x304a2)
 #7 0x000055ead7cf69ec llvm::StoreInst::AssertOK() (/usr/local/bin/clang-13+0x30589ec)
 #8 0x000055ead7cf6be3 llvm::StoreInst::StoreInst(llvm::Value*, llvm::Value*, bool, llvm::Align, llvm::Instruction*) (/usr/local/bin/clang-13+0x3058be3)
 #9 0x000055ead8c7c49a clang::CodeGen::CodeGenFunction::EmitAggregateStore(llvm::Value*, clang::CodeGen::Address, bool) (/usr/local/bin/clang-13+0x3fde49a)
#10 0x000055ead8d0d2df (anonymous namespace)::AggExprEmitter::VisitConstantExpr(clang::ConstantExpr*) CGExprAgg.cpp:0:0
#11 0x000055ead8d0955b clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::AggExprEmitter, void>::Visit(clang::Stmt*) CGExprAgg.cpp:0:0
#12 0x000055ead8d0aa3a (anonymous namespace)::AggExprEmitter::Visit(clang::Expr*) CGExprAgg.cpp:0:0
```

**Comment by davidbolvansky** [comment] 2022-02-12 19:58
cc @zygoloid

**Comment by AaronBallman** [comment] 2022-02-22 13:47
I think this may be related to or a duplicate of #51764.

**Comment by xgupta** [comment] 2022-06-27 17:15
No crash on trunk, fine to close.

**Closed by xgupta** 2022-06-27 17:15 UTC
Labels: c++20, clang:codegen, confirmed, crash
