### ISSUE TITLE
Type mismatch for pointer to template template function

### ISSUE THREAD

**Issue by pavelkryukov** [llvm/llvm-project#48423] opened 2021-02-07 20:23 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [49079](https://llvm.org/bz49079) |
| Version | 11.0 |
| OS | All |
| CC | @dwblaikie,@GabrielRavier,@zygoloid |

## Extended Description 
If a function is a template template function (template<template<typename> class> void foo(int&)), and a template template parameter has a default value, it does not fit to function pointer type.

Example:

> template<typename, typename = int> class A { };
> 
> template<template<typename> class> void foo(int&);
> void bar(void(*)(int&));
> 
> int main()
> {
>     bar(foo<A>);
> }
Output:

> <source>:8:5: error: no matching function for call to 'bar'
>     bar(foo<A>);
>     ^~~
> <source>:4:6: note: candidate function not viable:
>   no overload of 'foo' matching 'void (*)(int &)' for 1st argument
> void bar(void(*)(int&));
Godbolt: https://godbolt.org/z/enhYs8

With GCC and MSVC, example compiles fine.

**Comment by mizvekov** [comment] 2024-04-27 20:07
Duplicate of https://github.com/llvm/llvm-project/issues/42224

**Closed by mizvekov** 2024-04-27 20:07 UTC
Labels: c++17, clang:frontend, bugzilla
