### ISSUE TITLE
Crash while running a concrete-ml function on Ubuntu in VirtualBox.

### ISSUE THREAD

**Issue by BartoszDorobek** [llvm/llvm-project#64856] opened 2023-08-21 10:33 UTC
crash when I try run model.compile(X_train) from concrete-ml library (pip install concrete-ml). Where model is after fitting model.fit() and X_train is tabular numerical data.

Error Logs:
```
#0 0x00007fa5bc7b4b91 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x13b4b91)
 #1 0x00007fa5bc7b25a4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fa655a42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x00007fa5c0b9b652 concrete_optimizer::dag::unparametrized::OperationDag::new::h9a051e100108e97d (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x579b652)
 #4 0x00007fa5c0b946aa cxx::unwind::prevent_unwind::hb298ae28e065ccf9 (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x57946aa)
 #5 0x00007fa5c0b909da concrete_optimizer::dag::empty() (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x57909da)
 #6 0x00007fa5bfe4c378 mlir::concretelang::optimizer::(anonymous namespace)::FunctionToDag::build() ConcreteOptimizer.cpp:0:0
 #7 0x00007fa5bfe4e718 mlir::concretelang::optimizer::DagPass::runOnOperation() (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x4a4e718)
 #8 0x00007fa5bc6ee452 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x12ee452)
 #9 0x00007fa5bc6eea29 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x12eea29)
#10 0x00007fa5bc6efa33 mlir::detail::OpToOpPassAdaptor::runOnOperationImpl(bool) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x12efa33)
#11 0x00007fa5bc6ee146 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x12ee146)
#12 0x00007fa5bc6eea29 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x12eea29)
#13 0x00007fa5bc6ef531 mlir::PassManager::run(mlir::Operation*) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x12ef531)
#14 0x00007fa5be40216b mlir::concretelang::pipeline::getFHEContextFromFHE[abi:cxx11](mlir::MLIRContext&, mlir::ModuleOp&, mlir::concretelang::optimizer::Config, std::function<bool (mlir::Pass*)>) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x300216b)
#15 0x00007fa5be3db1b0 mlir::concretelang::CompilerEngine::getConcreteOptimizerDescription(mlir::concretelang::CompilerEngine::CompilationResult&) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x2fdb1b0)
#16 0x00007fa5be3db8dd mlir::concretelang::CompilerEngine::determineFHEParameters(mlir::concretelang::CompilerEngine::CompilationResult&) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x2fdb8dd)
#17 0x00007fa5be3de9d6 mlir::concretelang::CompilerEngine::compile(llvm::SourceMgr&, mlir::concretelang::CompilerEngine::Target, std::optional<std::shared_ptr<mlir::concretelang::CompilerEngine::Library> >) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x2fde9d6)
#18 0x00007fa5be3e40ac mlir::concretelang::CompilerEngine::compile(llvm::SourceMgr&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool, bool, bool, bool) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x2fe40ac)
#19 0x00007fa5bc58684c mlir::concretelang::LibrarySupport::compile(llvm::SourceMgr&, mlir::concretelang::CompilationOptions) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x118684c)
#20 0x00007fa5bc58901a library_compile(LibrarySupport_Py, char const*, mlir::concretelang::CompilationOptions) (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/libConcretelangBindingsPythonCAPI.so+0x118901a)
#21 0x00007fa632adbadc (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/_concretelang.cpython-310-x86_64-linux-gnu.so+0x5cadc)
#22 0x00007fa632abbb4d (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/_concretelang.cpython-310-x86_64-linux-gnu.so+0x3cb4d)
#23 0x00007fa632aa2177 (/home/ubuntu/ai/lib/python3.10/site-packages/mlir/_mlir_libs/_concretelang.cpython-310-x86_64-linux-gnu.so+0x23177)
#24 0x000055dbdcf3ee0e (/usr/bin/python3.10+0x15fe0e)
#25 0x000055dbdcf355eb _PyObject_MakeTpCall (/usr/bin/python3.10+0x1565eb)
#26 0x000055dbdcf4d7bb (/usr/bin/python3.10+0x16e7bb)
#27 0x000055dbdcf2d8a2 _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x14e8a2)
#28 0x000055dbdcf3f70c _PyFunction_Vectorcall (/usr/bin/python3.10+0x16070c)
#29 0x000055dbdcf27f52 _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x148f52)
#30 0x000055dbdcf3f70c _PyFunction_Vectorcall (/usr/bin/python3.10+0x16070c)
#31 0x000055dbdcf2d8a2 _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x14e8a2)
#32 0x000055dbdcf3f70c _PyFunction_Vectorcall (/usr/bin/python3.10+0x16070c)
#33 0x000055dbdcf27f52 _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x148f52)
#34 0x000055dbdcf34784 _PyObject_FastCallDictTstate (/usr/bin/python3.10+0x155784)
#35 0x000055dbdcf49744 (/usr/bin/python3.10+0x16a744)
#36 0x000055dbdcf3558c _PyObject_MakeTpCall (/usr/bin/python3.10+0x15658c)
#37 0x000055dbdcf2dc66 _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x14ec66)
#38 0x000055dbdcf4d4e1 (/usr/bin/python3.10+0x16e4e1)
#39 0x000055dbdcf290d1 _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x14a0d1)
#40 0x000055dbdcf4d4e1 (/usr/bin/python3.10+0x16e4e1)
#41 0x000055dbdcf2d8a2 _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x14e8a2)
#42 0x000055dbdcf3f70c _PyFunction_Vectorcall (/usr/bin/python3.10+0x16070c)
#43 0x000055dbdcf27e0d _PyEval_EvalFrameDefault (/usr/bin/python3.10+0x148e0d)
#44 0x000055dbdd018e56 (/usr/bin/python3.10+0x239e56)
#45 0x000055dbdd018cf6 PyEval_EvalCode (/usr/bin/python3.10+0x239cf6)
#46 0x000055dbdd0437d8 (/usr/bin/python3.10+0x2647d8)
#47 0x000055dbdd03d0bb (/usr/bin/python3.10+0x25e0bb)
#48 0x000055dbdd043525 (/usr/bin/python3.10+0x264525)
#49 0x000055dbdd042a08 _PyRun_SimpleFileObject (/usr/bin/python3.10+0x263a08)
#50 0x000055dbdd042653 _PyRun_AnyFileObject (/usr/bin/python3.10+0x263653)
#51 0x000055dbdd03541e Py_RunMain (/usr/bin/python3.10+0x25641e)
#52 0x000055dbdd00bcad Py_BytesMain (/usr/bin/python3.10+0x22ccad)
#53 0x00007fa655a29d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#54 0x00007fa655a29e40 call_init ./csu/../csu/libc-start.c:128:20
#55 0x00007fa655a29e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#56 0x000055dbdd00bba5 _start (/usr/bin/python3.10+0x22cba5)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Illegal instruction (core dumped)
```

**Comment by rikhuijzer** [comment] 2023-10-12 13:45
Closing because the issue cannot be reproduced.

**Closed by rikhuijzer** 2023-10-12 13:45 UTC
Labels: mlir, crash
