### ISSUE TITLE
[15, trunk] Compilation error w/ concepts

### ISSUE THREAD

**Issue by psiha** [llvm/llvm-project#58952] opened 2022-11-12 09:45 UTC
Clang cannot handle out-of-line concept-restricted template member function definitions:
https://godbolt.org/z/xTh9eah8a

```C++
#include <utility>
#include <type_traits>
#include <tuple>

template < typename T, auto ... vals >
class Bar;


template < typename T, auto ... vals >
requires ( ... && std::is_integral_v< decltype( vals ) > )
class Bar< T, vals... >
{
public:
    int foo();
};



template < typename T, auto ... vals >
requires ( ... && std::is_integral_v< decltype( vals ) > )
int Bar< T, vals... >::foo()
{
    return 1;
}


int main()
{
    Bar< float, 1 > bla;
    return bla.foo();
}
```

**Comment by royjacobson** [comment] 2022-12-04 20:39
Duplicate of #49620

**Closed by royjacobson** 2022-12-04 20:39 UTC
Labels: c++20, clang:frontend, concepts
