### ISSUE TITLE
Error while compiling net/ipv6/ip6_input.o from linux-6.8.0 with clang version 18.1.0

### ISSUE THREAD

**Issue by cmyster** [llvm/llvm-project#84790] opened 2024-03-11 16:38 UTC
IPv6 input complains and exits:

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -Wp,-MMD,net/ipv6/.ip6_input.o.d -nostdinc -I./arch/x86/include -I./arch/x86/include/generated -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated
/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ --target=x86
_64-linux-gnu -fintegrated-as -Werror=unknown-warning-option -Werror=ignored-optimization-argument -Werror=option-ignored -Werror=unused-command-line-argument -fmacro-prefix-map=./= -Werror -std=g
nu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387
 -mstack-alignment=8 -mskip-rax-setup -march=k8 -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -mindirect-branch-cs-prefix -mfunction-re
turn=thunk-extern -fno-delete-null-pointer-checks -O2 -fstack-protector-strong -fno-stack-clash-protection -pg -mfentry -DCC_USING_NOP_MCOUNT -DCC_USING_FENTRY -falign-functions=16 -fstrict-flex-a
rrays=3 -fno-strict-overflow -fno-stack-check -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigr
aphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-gnu -Wno-unused-but-set-variable -Wno-unused-const-variable -Wvla -W
no-pointer-sign -Wcast-function-type -Wimplicit-fallthrough -Werror=date-time -Werror=incompatible-pointer-types -Wenum-conversion -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-form
at-overflow -Wno-format-truncation -Wno-pointer-to-enum-cast -Wno-tautological-constant-out-of-range-compare -Wno-unaligned-access -Wno-cast-function-type-strict -Wno-missing-field-initializers -W
no-type-limits -Wno-shift-negative-value -Wno-initializer-overrides -Wno-sign-compare -O3 -march=native -DKBUILD_MODFILE=\"net/ipv6/ipv6\" -DKBUILD_BASENAME=\"ip6_input\" -DKBUILD_MODNAME=\"ipv6\"
 -D__KBUILD_MODNAME=kmod_ipv6 -c -o net/ipv6/ip6_input.o net/ipv6/ip6_input.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'net/ipv6/ip6_input.c'.
4.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
 #0 0x00007f548d5ba536 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x39ba536)
 #1 0x00007f548d5b77e0 llvm::sys::RunSignalHandlers() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x39b77e0)
 #2 0x00007f548d4c5e60 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x38c5e60)
 #3 0x00007f5489673d30 (/usr/lib64/libc.so.6+0x3bd30)
 #4 0x00007f548dd60c0a llvm::SUnit::addPred(llvm::SDep const&, bool) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x4160c0a)
 #5 0x00007f548e092fac llvm::ScheduleDAGSDNodes::AddSchedEdges() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x4492fac)
 #6 0x00007f548e085bec (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x4485bec)
 #7 0x00007f548e170e3e llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x4570e3e)
 #8 0x00007f548e16f6a1 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x456f6a1)
 #9 0x00007f548e16c181 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x456c181)
#10 0x00007f5491318af2 (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x7718af2)
#11 0x00007f548daf9e09 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x3ef9e09)
#12 0x00007f548d775728 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x3b75728)
#13 0x00007f548d77fa43 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x3b7fa43)
#14 0x00007f548d77657e llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x3b7657e)
#15 0x00007f54948ce6f9 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&,
llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang
::BackendConsumer*) (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x2cce6f9)
#16 0x00007f5494d69cea clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x3169cea)
#17 0x00007f54932c95e6 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x16c95e6)
#18 0x00007f5495c81b17 clang::FrontendAction::Execute() (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x4081b17)
#19 0x00007f5495bb87c4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x3fb87c4)
#20 0x00007f5495d21863 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x4121863)
#21 0x000055e28d81424f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm/18/bin/clang-18+0x1524f)
#22 0x000055e28d811298 (/usr/lib/llvm/18/bin/clang-18+0x12298)
#23 0x00007f54957263e9 (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x3b263e9)
#24 0x00007f548d4c5b6c llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/llvm/18/bin/../lib64/libLLVM.so.18.1+0x38c5b6c)
#25 0x00007f5495725f42 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) co
nst (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x3b25f42)
#26 0x00007f54956da6ac clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/llvm/18/bin/../lib64/libclang-cpp.so.18.1+0x3
ada6ac)
#27 0x00007f54956dac0e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/lib/llvm/18/b
in/../lib64/libclang-cpp.so.18.1+0x3adac0e)
#28 0x00007f54957015df clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/lib/llvm/18/bin/../lib64/
libclang-cpp.so.18.1+0x3b015df)
#29 0x000055e28d8103d3 clang_main(int, char**, llvm::ToolContext const&) (/usr/lib/llvm/18/bin/clang-18+0x113d3)
#30 0x000055e28d822ac4 main (/usr/lib/llvm/18/bin/clang-18+0x23ac4)
#31 0x00007f548965deea (/usr/lib64/libc.so.6+0x25eea)
#32 0x00007f548965dfa5 __libc_start_main (/usr/lib64/libc.so.6+0x25fa5)
#33 0x000055e28d80d2d1 _start (/usr/lib/llvm/18/bin/clang-18+0xe2d1)
clang: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 18.1.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/18/bin
Configuration file: /etc/clang/x86_64-unknown-linux-gnu-clang.cfg
clang: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/ip6_input-8e215e.c
clang: note: diagnostic msg: /tmp/ip6_input-8e215e.sh
clang: note: diagnostic msg:

********************
make[4]: *** [scripts/Makefile.build:243: net/ipv6/ip6_input.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [scripts/Makefile.build:481: net/ipv6] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:481: net] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-6.8.0-gentoo/Makefile:1921: .] Error 2
make: *** [Makefile:240: __sub-make] Error 2
```

**Comment by cmyster** [comment] 2024-03-11 16:50
[ip6_input-8e215e.tar.gz](https://github.com/llvm/llvm-project/files/14561977/ip6_input-8e215e.tar.gz)

**Comment by thesamesam** [comment] 2024-03-11 16:53
cc @nickdesaulniers @nathanchance

**Comment by nickdesaulniers** [comment] 2024-03-11 16:57
cc @phoebewang

**Comment by nickdesaulniers** [comment] 2024-03-11 16:59
@cmyster do you mind moving this to https://github.com/ClangBuiltLinux/linux/issues ? Kernel specific issues should be reported there first, at least for initial triage.  Then we move issues upstream to llvm when we determine the issue is within llvm and not the kernel. (In this case an internal compiler error (ICE) is obviously an issue in llvm, but we could help reduce the input/test case to provide in the upstream report).

Thanks for the report!

**Comment by nathanchance** [comment] 2024-03-11 17:05
This seems like yet another duplicate of https://github.com/llvm/llvm-project/issues/72026 (which has both a reproducer and a bisect result)? It has also been reported at https://github.com/ClangBuiltLinux/linux/issues/1987 and https://github.com/llvm/llvm-project/issues/82896.

**Closed** 2024-03-11 17:10 UTC
Labels: duplicate, backend:X86, crash, needs-reduction
