### ISSUE TITLE
[Flang][OpenMP] Compilation failure in 627.cam4_s

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#63147] opened 2023-06-06 14:11 UTC
Pointer association for a private variable fails in an OpenMP region with the following error.

```console
physpkg.fppized.f90":713:7): expr was not lowered to MutableBoxValue
```

A minimal reproducer will be something like the following:
```f90
subroutine sb(pbuf)
 real(kind=8), target, dimension(:) :: pbuf
 real(kind=8), pointer, dimension(:) :: teout
 integer :: c
!$OMP PARALLEL DO PRIVATE (C, TEOUT)
   do c=1,100
      teout  => pbuf
   end do
!$OMP END PARALLEL DO
end subroutine
```

**Comment by erjin** [comment] 2023-08-21 18:38
Hi, I think this issue is fixed in the commit https://reviews.llvm.org/D148570. Now I can compile the cam4_s with OpenMp enabled.
However, I am running into a runtime error with threads >1. The result of gdb running the cam4_s :
```
ZM_CONV: IENTROPY. Details: call#,lchnk,icol= 1 421   1 lat: -86.21 lon:  90.00 P(mb)= ****** Tfg(K)=    NaN qt(g/kg) =   2.21 qsat(g/kg) =    NaN, s(J/kg) =    NaN
 *** ZM_CONV: IENTROPY: Failed and about to exit, info follows ****
 ENDRUN:**** ZM_CONV IENTROPY: Tmix did not converge ****
Fortran STOP
IEEE arithmetic exceptions signaled: DIVBYZEROZM_CONV: IENTROPY. Details: call#,lchnk,icol= 12149   1 lat: -63.47 lon:  90.00 P(mb)= ****** Tfg(K)=    NaN qt(g/kg) =   2.69 qsat(g/kg) =    NaN, s(J/kg) =    NaN
 INEXACT INVALID ENDRUN:**** ZM_CONV IENTROPY: Tmix did not converge ****

Fortran STOP
IEEE arithmetic exceptions signaled: DIVBYZERO INEXACT INVALID

```
I think there is a problem in the calculation step. 

Given that we may switch to using hlfir soon as mentioned in this post: https://discourse.llvm.org/t/rfc-enabling-the-hlfir-lowering-by-default/72778 . I am wondering if we should fix it in the FIR?

I also tried using HLFIR with the option `-flang-experimental-hlfir` to compile cam4 but I ran into multiple compilation failures for different files. One example:
```
install/bin/flang-new -flang-experimental-hlfir   -flto=full -c -o pkez.fppized.o -I. -Iinclude -Inetcdf/include -O3 -mcpu=native -ffast-math -fopenmp pkez.fppized.f90
error: loc(".../pkez.fppized.f90":105:15): operand #1 does not dominate this use
error: verification of lowering to FIR failed

```
Any feedback is appreciated. Thanks!

**Comment by kiranchandramohan** [comment] 2023-08-21 22:10
Thanks @erjin for looking into this issue. As you observed, this benchmark currently fails at runtime. I was not sure what is the exact issue that is causing the failure here. When I last tried this out, I was seeing an assertion failure from the runtime.

We are in the process of updating the OpenMP lowering to work with HLFIR.  As you can see from the ticket (https://github.com/llvm/llvm-project/issues/64752) one of the requirements for switching ON HLFIR lowering is to ensure that there are no regressions in benchmarks like spec2017 speed. I think it will take us a couple of weeks to update the OpenMP lowering to work with HLFIR. I would advise waiting till then before you try this path.

**Comment by kiranchandramohan** [comment] 2023-08-23 11:36
@erjin The following patch should fix the compilation issues with HLFIR and probably takes you to the same runtime issue that you see without HLFIR.
https://reviews.llvm.org/D158594

**Comment by kiranchandramohan** [comment] 2023-09-01 11:01
@erjin I have submitted this patch.
Have you made progress with the investigation?

**Comment by erjin** [comment] 2023-09-01 14:32
> @erjin I have submitted this patch. Have you made progress with the investigation?

Hi @kiranchandramohan , thanks for the patch! I will take a look soon.

**Comment by erjin** [comment] 2023-09-05 19:12
Hi @kiranchandramohan , now I am running into a different runtime error. Here are the outputs from ./cam4_s
```
radiation ozone error   2 1 0.
radiation ozone error   1 2 0.
...
Segmentation fault (core dumped)

```
`radiation ozone error` is the output msg from `radae.fppized.f90` 

Infinite call stack found using gdb 
```
#10767 0x0000aaaaaad5f930 in _QMrepro_sum_modPrepro_sum_int..omp_par () 
```
Probably the problem is the omp used in this function since I can run successfully with --thread =1.

Please let me know if you have any thoughts. thanks!

**Comment by kiranchandramohan** [comment] 2023-09-08 17:06
@erjin Maybe there are a few more fixes in OpenMP HLFIR lowering required. I see the same error on my side. I will have a look next week.

**Comment by kiranchandramohan** [comment] 2023-09-10 13:21
If we try to convert the example given at the bottom with `fir-opt --fir-to-llvm-ir <filename.mlir>`, we can see that a temporary `alloca` created for a box is not captured in the parallel region but hoisted all the way into the entry block. This is done by the function called in https://github.com/llvm/llvm-project/blob/f2e5000937235aa35a9ee4423045b265c2c79e85/flang/lib/Optimizer/CodeGen/CodeGen.cpp#L353. 

Converting the called function (`getFuncForAllocaInsert`) to something like the following (`getAllocaBlock`) seems to fix the issue.
```
+  static mlir::Block*
+  getAllocaBlock(mlir::Operation *op) {
+    if (auto iface = mlir::dyn_cast<mlir::omp::OutlineableOpenMPOpInterface>(op)) {
+      return iface.getAllocaBlock();
+    } else if (auto llvmFuncOp = mlir::dyn_cast<mlir::LLVM::LLVMFuncOp>(op)) {
+      return &llvmFuncOp.front();
+    } else {
+      return getAllocaBlock(op->getParentOp());
+    }
   }
 ```  

```
func.func @_QQmain() attributes {fir.bindc_name = "mn"} {
  %0 = fir.alloca !fir.box<!fir.ptr<i32>> {bindc_name = "iattr", uniq_name = "_QFEiattr"}
  %1 = fir.zero_bits !fir.ptr<i32>
  %2 = fir.embox %1 : (!fir.ptr<i32>) -> !fir.box<!fir.ptr<i32>>
  fir.store %2 to %0 : !fir.ref<!fir.box<!fir.ptr<i32>>>
  %3 = fir.address_of(@_QFEx) : !fir.ref<i32>
  %4 = fir.alloca i32 {bindc_name = "y", uniq_name = "_QFEy"}
  %5 = fir.embox %3 : (!fir.ref<i32>) -> !fir.box<!fir.ptr<i32>>
  fir.store %5 to %0 : !fir.ref<!fir.box<!fir.ptr<i32>>>
  omp.parallel   {
    %6 = fir.load %4 : !fir.ref<i32>
    %7 = fir.load %0 : !fir.ref<!fir.box<!fir.ptr<i32>>>
    %8 = fir.box_addr %7 : (!fir.box<!fir.ptr<i32>>) -> !fir.ptr<i32>
    fir.store %6 to %8 : !fir.ptr<i32>
    omp.terminator
  }
  return
}
fir.global internal @_QFEx target : i32 {
  %0 = fir.zero_bits i32
  fir.has_value %0 : i32
}
```

**Comment by kiranchandramohan** [comment] 2023-09-11 10:57
This also seems to help `wrf_s`. @erjin Would you like to create a patch? Or is it OK for me to go ahead with a patch?

**Comment by erjin** [comment] 2023-09-11 19:29
> This also seems to help `wrf_s`. @erjin Would you like to create a patch? Or is it OK for me to go ahead with a patch?

Created a patch based on your suggestions. Please check. Thanks! https://github.com/llvm/llvm-project/pull/65999

**Comment by erjin** [comment] 2023-09-13 04:12
Close with #65999

**Closed** 2023-09-13 04:12 UTC
Labels: bug, openmp, flang:ir
