### ISSUE TITLE
C++20's P0528R3/P1123R0 not implemented (atomic ignoring padding bits)

### ISSUE THREAD

**Issue by comex** [llvm/llvm-project#64829] opened 2023-08-19 19:25 UTC
C++20 includes [P0528R3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0528r3.html) and [P1123R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1123r0.html), which together require `std::atomic<T>::compare_exchange_strong` and `std::atomic_ref<T>::compare_exchange_strong` to ignore any padding bits that exist in `T`.

However, this is not implemented in Clang or libc++ as of b41e75c8a42256cca4305f534b88d1d13711e10e.  Also, neither paper is mentioned on the [cxx_status page](https://clang.llvm.org/cxx_status.html).

As a result of the missing implementation, the following prints 0 when it should print 1:
```cpp
#include <atomic>
#include <stdio.h>
int main() {
    struct HasPadding { char a; short b; };
    HasPadding expected{};
    std::atomic<HasPadding> atomic(expected);
    ((char *)&expected)[1] = 0x42; // update padding byte
    printf("%d\n", atomic.compare_exchange_strong(
        expected, expected));
}
```

See also:
- [this comment](https://github.com/rust-lang/unsafe-code-guidelines/issues/449#issuecomment-1677985851) which includes a comparison of different compilers;
- #46030 for an intrinsic that MSVC's C++ standard library implementation uses as part of its implementation;
- #64830 for an intrinsic that libstdc++ uses as part of its implementation

**Comment by RalfJung** [comment] 2023-08-19 20:18
Relatedly, it would be good to get clarification on the behavior of LLVM's `cmpxchg` when the value being compared is partially `undef` / uninitialized / poison (which is what happens with the above program). Naively, the answer would be "it's UB" (that's usually what happens when you `memcp` memory that contains `undef` / uninitialized / poison), but that would make it impossible to perform `cmpxchg` on data with padding which would be unfortunate.

**Comment by huixie90** [comment] 2023-11-22 12:51
On the libc++ side, we need clang equivalent of gcc `__builtin_clear_padding` to make it implementable. Also notice that  for `long double` in the x87_fp80 format, gcc `__builtin_clear_padding` also clears the last 58 bits as only first 80bits of the `long double` is the value representation

**Comment by gonzalobg** [comment] 2024-02-20 15:10
Is there an issue tracking `__builtin_clear_padding` ?

**Comment by pkasting** [comment] 2024-08-19 19:32
> Is there an issue tracking `__builtin_clear_padding` ?

Yes, https://github.com/llvm/llvm-project/issues/64830.

**Comment by ldionne** [comment] 2024-08-29 14:57
Closing as a duplicate of:

- libc++ https://github.com/llvm/llvm-project/issues/99984 and https://github.com/llvm/llvm-project/issues/99991
- Clang's https://github.com/llvm/llvm-project/issues/64830

**Closed by ldionne** 2024-08-29 14:57 UTC
Labels: libc++, clang:codegen
