### ISSUE TITLE
Weird bug with `clang -std=c2x`

### ISSUE THREAD

**Issue by vmurali** [llvm/llvm-project#107148] opened 2024-09-03 20:08 UTC
```console
$ clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

$ cat hello.i 
```cpp
void say_hello()
{
  xoo::bar();
}
```

```console
$ clang -c -std=c2x -x cpp-output hello.i
hello.i:3:6: error: expected ';' after expression
  xoo::bar();
     ^
     ;
hello.i:3:3: error: use of undeclared identifier 'xoo'
  xoo::bar();
  ^
^C ##### <----------------- HANGS WITH -std=c2x
```

```console
$ clang -c -x cpp-output hello.i
hello.i:3:7: error: expected expression
  xoo::bar();
      ^
1 error generated.  ##### <------------ DOES NOT HANG without -std=c2x
```

$ cat hello.i 
```cpp
void say_hello()
{
  foo::bar();
}
```

```console
$ clang -c -std=c2x -x cpp-output hello.i
hello.i:3:3: error: use of undeclared identifier 'foo'; did you mean 'for'?
  foo::bar();
  ^~~
  for
hello.i:3:3: error: expected expression
2 errors generated. ##### <-------------------------------------- DOES NOT HANG with foo::bar !!!!
```

**Comment by AaronBallman** [comment] 2024-09-03 20:43
I'm not able to reproduce on Compiler Explorer or locally; can you try this with trunk Clang (instead of Apple Clang)?

**Comment by vmurali** [comment] 2024-09-03 21:01
This is from compiler explorer https://godbolt.org/z/z7qE6qvK1. Looks like this happens only in versions 15.0.0 or older (both arm and x86 clang compilers).

**Comment by AaronBallman** [comment] 2024-09-03 21:11
Thank you! Closing this one as it works on trunk (we won't be putting out any more point releases for 15.x).

**Closed by AaronBallman** 2024-09-03 21:11 UTC
Labels: clang, hang
