### ISSUE TITLE
wrong code at -Os and above with -mllvm -enable-constraint-elimination

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#54235] opened 2022-03-06 22:39 UTC
```
[507] % clangtk -v
clang version 15.0.0 (https://github.com/llvm/llvm-project.git 17a68065c378da74805e4e1b9a5b78cc9f83e580)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
[508] % 
[508] % clangtk -Os small.c; ./a.out
[509] % 
[509] % clangtk -Os -mllvm -enable-constraint-elimination small.c
[510] % ./a.out
Segmentation fault
[511] % 
[511] % cat small.c
int printf (const char *, ...);
static int *a, **b = &a;
int c, d = 1, e;
int main() {
  int f, g;
  f = d;
  for (g = 0; g < 2; g++) {
    if (e) {
      printf("%d", e);
      if (f)
        c = **b;
    }
    if (!f)
      while (1)
        while (g)
          ;
  }
  return 0;
}
```

@fhahn

**Comment by fhahn** [comment] 2022-03-07 12:18
Thanks for the report! This looks like a duplicate of #54217 should be fixed as by c60cdb44f7ec.

**Closed by fhahn** 2022-03-07 12:18 UTC
Labels: duplicate, llvm:optimizations
