### ISSUE TITLE
LLVM 19.1.0 fails to compile

### ISSUE THREAD

**Issue by davide-q** [llvm/llvm-project#109218] opened 2024-09-18 23:23 UTC
With various errors like

```
 lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): undefined reference to symbol 'define_key@@@@NCURSES6_TINFO_5.0.19991023'
FAILED: lib/liblldb.so.19.1.0-rc1
IOHandlerCursesGUI.cpp:(.text._ZN6curses6Window12DrawTitleBoxEPKcS2_[_ZN6curses6Window12DrawTitleBoxEPKcS2_]+0x4a): undefined reference to `acs_map'
ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCursesGUI8ActivateEv.part.713+0x112c): undefined reference to `curs_set'
ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCursesGUI8ActivateEv.part.713+0x1138): undefined reference to `stdscr'
ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCursesGUI8ActivateEv.part.713+0x1145): undefined reference to `keypad'
ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCursesGUI8ActivateEv.part.713+0x1be9): undefined reference to `define_key'
ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCursesGUI8ActivateEv.part.713+0x1bfa): undefined reference to `define_key'
```

and more

I wonder if #25067 has been inadvertently re-introduced?

**Comment by nikic** [comment] 2024-09-19 10:37
Duplicate of https://github.com/llvm/llvm-project/issues/101368.

**Closed by nikic** 2024-09-19 10:37 UTC
Labels: lldb, build-problem
