### ISSUE TITLE
[clang-tidy] Add check for variable that can be moved but isn't

### ISSUE THREAD

**Issue by sweemer** [llvm/llvm-project#88617] opened 2024-04-13 12:01 UTC
I would like to request a clang-tidy check for variables that can be moved but are not. For example, in the following code `string` can be moved into `f1` to save an unnecessary copy but there is apparently no check for it at the moment. Can it be added?

```c++
#include <string>
#include <utility>
#include <vector>

void f1(std::string string) {
  std::vector<std::string> vector;
  vector.push_back(std::move(string));
}

void f2() {
  auto string = std::string();
  f1(string);
}
```

```console
$ clang-tidy --version
Ubuntu LLVM version 19.0.0
  Optimized build.

$ clang-tidy -checks=*,-llvmlibc-* move.cpp
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "move.cpp"
No compilation database found in /home/sweemer/test or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
39836 warnings generated.
Suppressed 39836 warnings (39836 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```

**Comment by firewave** [comment] 2024-04-14 23:06
Duplicate of #53489.

**Closed** 2024-04-15 02:26 UTC
Labels: duplicate, clang-tidy, check-request
