### ISSUE TITLE
clang-format: .clang-format-ignore: does not respect  src/**/*

### ISSUE THREAD

**Issue by xavgru12** [llvm/llvm-project#118607] opened 2024-12-04 09:20 UTC
Given the file file.cpp is inside src/dir/subdir/file.cpp

configuring the ignore in:
.clang-format-ignore
src/**/*
and running clang-format -i src/dir/subdir/file.cpp

will result to: 
formatted src/dir/subdir/file.cpp.

I expected it to ignore src/dir/subdir/file.cpp.

Found in 19.1.4. Seems to be the same issue in other versions.
Platform: Windows 11

**Comment by owenca** [comment] 2024-12-05 05:17
Duplicate of #114969

**Closed by owenca** 2024-12-05 05:17 UTC
Labels: duplicate, clang-format

**Comment by jbytheway** [comment] 2025-02-28 23:06
This is not a duplicate of the linked issue.  That issue simply added a directory and expected all files recursively within it to be ignored. 

This issue is using `**` to recurse, which [the docs](https://clang.llvm.org/docs/ClangFormat.html#clang-format-ignore) say should work, but does not.

**Comment by owenca** [comment] 2025-03-01 08:26
It _is_ a duplicate of the linked issue. Handling globstar was added after the 19 release cycle and will be available in version 20 and later.
