### ISSUE TITLE
one case gcc can compile, but clang will fail to compile

### ISSUE THREAD

**Issue by 4465464** [llvm/llvm-project#60435] opened 2023-02-01 02:31 UTC
```cpp
#include <stdio.h>
#include <type_traits>

template <typename T>
constexpr inline bool is_nested(){
    return std::is_same_v<T,int>;
}

template<template <typename> class hash_function>
int device_hasher(){
    return 0;
}

template <typename Key, std::enable_if_t<(not is_nested<Key>())>* = nullptr>
struct SparkMurmurHash3_32{
    using result_type = int;

    constexpr SparkMurmurHash3_32()=default;

    [[nodiscard]] result_type  inline operator()(Key const& key) const{
        return compute(key);
    }
};

int main(){
    device_hasher<SparkMurmurHash3_32>();
    return 0;
}
```

```console
<source>:27:5: error: no matching function for call to 'device_hasher'
    device_hasher<SparkMurmurHash3_32>();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:11:5: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'hash_function'
int device_hasher(){
```

**Comment by shafik** [comment] 2023-02-01 03:19
I am not sure who is correct here, note MSVC agrees with clang: https://godbolt.org/z/EoMs3qsWq

Maybe @royjacobson might have an idea on this one.

**Comment by royjacobson** [comment] 2023-02-01 18:55
Another case of `-frelaxed-template-template-args` being abandoned, unfortunately :(

https://github.com/llvm/llvm-project/issues/37392

**Comment by mizvekov** [comment] 2024-04-27 20:08
Duplicate of https://github.com/llvm/llvm-project/issues/42224

**Closed by mizvekov** 2024-04-27 20:08 UTC
Labels: clang:frontend
