### ISSUE TITLE
[clang-cl] Macro definition depends on include order (without diagnostics)

### ISSUE THREAD

**Issue by andreas-0815-qwertz** [llvm/llvm-project#64898] opened 2023-08-22 12:32 UTC
Using `clang-cl` the value of `_dummy` in the below program depends on the order of the two include directives:

```cpp
#include <immintrin.h>
#include <Windows.h>

static const int dummy_ = _MM_HINT_T0;
```

Using Clang 16 (via PowerShell) like

`& 'C:\Program Files\LLVM\bin\clang-cl.exe' /Od /Z7 /Wall /WX /winsdkdir ms\sdk /vctoolsdir ms\crt -fuse-ld=lld /E redef_issue.cc`

(with Windows SDK and UCRT headers installed under the `ms` subdirectory) will result in `_dummy` having the value 1; switching the includes will result in the value 3.

Background is that  `_MM_HINT_T0` (as well as `_MM_HINT_T2`) are differently defined in clang's own `xmmintrin.h` and Windows SDK's `winnt.h`.  As both files are found via paths specified with `-internal-isystem`, the macro redefinition is not diagnosed regardless of the include order.

**Comment by chloekek** [comment] 2024-01-14 16:24
Duplicate of https://github.com/llvm/llvm-project/issues/36748?

**Closed** 2024-01-16 03:53 UTC
Labels: duplicate, platform:windows, clang:diagnostics
