### ISSUE TITLE
The compiler flag "-w" does **not** silence all the warnings

### ISSUE THREAD

**Issue by carlosgalvezp** [llvm/llvm-project#116218] opened 2024-11-14 12:32 UTC
Hi,

I have posted an [identical bug to GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117577), but thought it'd be good to have it here as well.

Example:

```c
typedef void (*PFUNC)(int);

void func(double);

int main()
{
    PFUNC x = func;
}
```

Compiling with "gcc -w main.c", I still get:

```console
<source>:7:11: error: incompatible function pointer types initializing 'PFUNC' (aka 'void (*)(int)') with an expression of type 'void (double)' [-Wincompatible-function-pointer-types]
    7 |     PFUNC x = func;
      |           ^   ~~~~
1 error generated.
Compiler returned: 1
```

https://godbolt.org/z/aYe19Kzab

I can still suppress the warning explicitly via -Wno-incompatible-function-pointer-types, but I would expect "-w" to work here, since this is a warning (not an error) and -w "Inhibit all warning messages" as per the docs.

Why is that?

**Comment by AaronBallman** [comment] 2024-11-14 12:49
This is by design (and is a duplicate of #92630 where I was arguing that design is confusing) -- `-w` silences warnings, but this is a case with an error that can be downgraded to a warning.

**Closed by AaronBallman** 2024-11-14 12:49 UTC
Labels: duplicate, clang:frontend, clang:diagnostics
