### ISSUE TITLE
Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by dcb314** [llvm/llvm-project#85194] opened 2024-03-14 07:58 UTC
csmith $ source ./in-6bd2d7.sh 
Instruction does not dominate all uses!
  %20 = extractelement <2 x i8> %16, i64 1, !dbg !3021
  %19 = sext i8 %20 to i16, !dbg !3021
in function func_47
fatal error: error in backend: Broken function found, compilation aborted!
csmith $ 

Machine is an AMD Zen3.

[in-6bd2d7.sh.gz](https://github.com/llvm/llvm-project/files/14598790/in-6bd2d7.sh.gz)
[in-6bd2d7.c.gz](https://github.com/llvm/llvm-project/files/14598791/in-6bd2d7.c.gz)

**Comment by nikic** [comment] 2024-03-14 08:59
Can't reproduce this with current LLVM main (at 8f68022f8e6e54d1aeae4ed301f5a015963089b7).

**Comment by dcb314** [comment] 2024-03-14 09:01
Reduced C code seems to be:

int g_41, func_61_l_125;
long g_78, g_147;
unsigned char func_61___trans_tmp_14;
short func_61_l_195;
void func_61();
void func_1() { func_61(); }
void func_61() {
  for (; g_41;)
    ;
  for (; g_78; g_78 += 1)
    g_41 = 25;
  for (; g_41 > 23; --g_41) {
    func_61_l_125 = 3;
    for (; func_61_l_125 <= 8; func_61_l_125 += 1) {
      long *l_219 = &g_147;
      func_61___trans_tmp_14 = 5 * g_147;
      func_61_l_195 |= func_61___trans_tmp_14;
      --*l_219;
    }
  }
}

**Comment by dcb314** [comment] 2024-03-14 09:02
My latest version of clang is c0f2177dac02903bb1ae85af5d91760d0a1b6a02

**Comment by nikic** [comment] 2024-03-14 09:07
@dcb314 I can reproduce the issue at that commit. So it looks like it was already fixed in the meantime.

**Comment by nikic** [comment] 2024-03-15 13:37
Closing this as already fixed.

**Closed by nikic** 2024-03-15 13:37 UTC
Labels: crash-on-valid
