### ISSUE TITLE
Wrong code at -O2/3/s on x86_64 (14 regression since 5db2735)

### ISSUE THREAD

**Issue by shao-hua-li** [llvm/llvm-project#66484] opened 2023-09-15 09:52 UTC
clang at -O2/3/s produced the wrong code.

Bisected to 5db2735af91be3bfb2fcb06bf8e1ac5f7d1e4812, which was committed by @preames 

Compiler explorer: https://godbolt.org/z/h43cr3GT3

```console
% cat a.c
int printf(const char *, ...);
int c, d, i, k, f, n, r, l;
int *e = &k, *a;
char g = -44, b;
int *j = &f;
short o;
char *s = &g;
unsigned fn1(char t, char u) { return t + u; }
int v() {
  if (i & c)
    if (d)
      return 0;
  return 1;
}
int **m = &j;
void w();
void x() {
  int **p = &a;
  int q = 0;
  for (; n <= 3; n++) {
    for (; *e < 1;)
      ;
    for (; v() + g + *e - 196 + q; q++) {
      for (; *e < 3;)
        for (; *e;)
          w();
      for (; *e - 299 + b; b++)
        for (; 19 + *e + **m - 318; o++)
          *p = 0;
    }
  }
}
void w() { *s = r; }
int main() {
  k = -20;
  unsigned char h = k;
  l = h + 3;
  k = l;
  r = 34339 + l;
  *s ^= r;
  for (; f <= 55; f = fn1(f, 5))
    ;
  x();
  printf("%d\n", o);
}
%
% clang -O0 a.c && ./a.out
0
% clang -O2 a.c && ./a.out
59
%
```

**Comment by nikic** [comment] 2023-09-15 09:59
Can't reproduce this. I landed related fixes today, does this reproduce for you on current main?

**Comment by antoniofrighetto** [comment] 2023-09-15 13:03
@nikic, I could reproduce this correctly on latest 72d4d4e3b9f6b54582358ac5c1006e295b9ed58e.

**Comment by nikic** [comment] 2023-09-18 13:06
I just double checked, and still can't reproduce. It also doesn't reproduce on godbolt after doing a whitespace change to invalidate the cache: https://godbolt.org/z/cvWbnhfrh

**Comment by shao-hua-li** [comment] 2023-09-18 13:25
On the current trunk(fb4bdf361feecfd0863c1553ec14ef9928027a24), this issue is gone.
I can reproduce with 0a1aa6cda2758b0926a95f87d39ffefb1cb90200.
According to my local builds, the issue is fixed or at least hidden by some commit between 0a1aa6cda2758b0926a95f87d39ffefb1cb90200 and ceb68eea8c5cfd7893d55afaef93932762bbebaa

**Closed** 2023-09-18 13:27 UTC
Labels: llvm:GVN

**Comment by shao-hua-li** [comment] 2023-09-18 14:01
I locally built them and confirmed that 7c229f6e85478bb0626a5e598f47b7be94bb50b0 fixed the underlying issue.
