### ISSUE TITLE
[consteval] The mixed use of 'consteval' and 'constexpr' takes longer time to compile

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#62947] opened 2023-05-26 05:15 UTC
The reproducer:

```c++
// Fib.cpp
namespace Fibonacci
{
	constexpr unsigned long Recursive(unsigned long n)
	{
		if (n == 0)
			return 0;
		if (n == 1)
			return 1;
		return Recursive(n - 2) + Recursive(n - 1);
	}

	template<unsigned long N>
	struct Number{};

	struct DefaultStrategy
	{
		constexpr unsigned long operator()(unsigned long n, auto... other) const
		{
			return (n + ... + other);
		}
	};

	template<unsigned long N, typename Strategy = DefaultStrategy>
	constexpr unsigned long Cache = Compute(Number<N>{}, Strategy{});
}

namespace Fibonacci
{
	constexpr unsigned long Compute(Number<30ul>, auto strategy)
	{
		return strategy(Recursive(30ul));
	}

	template constexpr unsigned long Cache<30ul>;
}
```

Let's run:

```shell
time clang++ -std=c++20 -fconstexpr-steps=4294967295 -c  Fib.cpp
```

in my computer it shows:

```console
real	0m8.070s
user	0m7.968s
sys	0m0.011s
```

But if I change `Recursive` into `consteval`, the result will be:

```console
$ time clang++ -std=c++20 -fconstexpr-steps=4294967295 -c  Fib.cpp

real	0m16.145s
user	0m15.948s
sys	0m0.012s
```

it shows now it takes double times to compile the source.

**Comment by erichkeane** [comment] 2023-05-30 13:24
I don't have much familiarity with the consteval code, @AaronBallman and @Fznamznon  are the two who have been spending the most time doing that lately.

**Comment by kaimfrai** [comment] 2023-06-03 13:13
I don't know if this is helpful, but I ran the example with -ftime-trace and put the .json into [speedscope](https://www.speedscope.app/), and interestingly it's not that something is really slower but rather it's simply computed twice.

The constexpr case has 
```
EvaluateAsInitializer {"detail":"Fibonacci::Cache"}
> Frontend
> ExecuteCompiler
```

The consteval case has 
```
EvaluateAsConstantExpr {"detail":"<Fib.cpp:39:19, col:33>"}
> InstantiateFunction {"detail":"Fibonacci::Compute<Fibonacci::DefaultStrategy>"}
> Frontend
> ExecuteCompiler
```
**as well as**
```
 EvaluateAsConstantExpr {"detail":"<Fib.cpp:39:19, col:33>"}
> Frontend
> ExecuteCompiler
```

both taking roughly the same time as the single constexpr case. So really, only EvaluateAsConstantExpr is performed twice which doubles the compile time.

**Comment by cor3ntin** [comment] 2023-06-05 11:28
Seems similar to #61425

**Comment by AaronBallman** [comment] 2023-06-05 15:19
Agreed, this seems to be a duplicate of #61425.

**Closed by AaronBallman** 2023-06-05 15:19 UTC
Labels: duplicate, c++20, clang:frontend, consteval

**Comment by AaronBallman** [comment] 2023-06-05 15:36
Oh, thank you for observing that! I've reopened the issue.
