### ISSUE TITLE
[C++14] Enable sized deallocation by default

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#60061] opened 2023-01-16 07:43 UTC
Sized deallocation is a C++14 feature and it was disabled in clang due to potential ABI breaking (https://reviews.llvm.org/D8467). There was guys trying to enable it by default 2 years ago (https://reviews.llvm.org/D112921) but the work suspended later.

**Comment by Romain-Geissler-1A** [comment] 2024-03-02 11:25
Hi @wangpc-pp,

Do you have any status on enabling this by default which you last tried this summer (https://reviews.llvm.org/D112921) ?

**Comment by shafik** [comment] 2024-03-03 06:38
This feels like a duplicate of: https://github.com/llvm/llvm-project/issues/56505

We should try and keep one main bug and updates and queries should go to that.

**Comment by wangpc-pp** [comment] 2024-03-04 03:08
> Hi @wangpc-pp,
> 
> Do you have any status on enabling this by default which you last tried this summer (https://reviews.llvm.org/D112921) ?

There were some buildbot failures (Windows, AMDGPU) and I don't have such environments, so I suspended the progress.
I'm glad to have another try, but I need some help to fix these failures.

**Comment by vitalybuka** [comment] 2024-04-27 00:16
Reverted with #90299

**Closed** 2024-05-22 04:37 UTC
Labels: c++14, clang:driver
