### ISSUE TITLE
EarlyCSE incorrectly assumes that readonly functions return

### ISSUE THREAD

**Issue by nunoplopes** [llvm/llvm-project#51010] opened 2021-08-30 09:48 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51668](https://llvm.org/bz51668) |
| Version | trunk |
| OS | All |
| CC | @alinas,@fhahn,@LebedevRI,@RKSimon,@nikic,@rotateright |

## Extended Description 
Test: Transforms/EarlyCSE/globalsaa-memoryssa.ll

define void @&#8203;f3() {
  %call1 = call i16 @&#8203;f1() nowrite nofree
  call void @&#8203;f2()
  %call2 = call i16 @&#8203;f1() nowrite nofree
  ret void
}
=>
define void @&#8203;f3() {
  %call1 = call i16 @&#8203;f1() nowrite nofree
  call void @&#8203;f2()
  ret void
}

The second call to @&#8203;f1() is incorrectly removed. We don't know if it exits, for example. Function @&#8203;f2 may change the state read by @&#8203;f1 and thus the first call may return and the second exit.
The optimization should be restricted to functions with the 'willreturn' attribute.

**Comment by rickyz** [comment] 2021-12-11 09:49
Please correct me if I'm mistaken, but [this test case](https://github.com/llvm/llvm-project/blob/686dca86bf62e7955438985903a3c1a55a9cb7a8/llvm/test/Transforms/EarlyCSE/globalsaa-memoryssa.ll) looks reasonable to me. If I understand correctly, the 2nd call to f1 is only removed because globals alias analysis determines that f1 does not read any memory.

**Comment by fhahn** [comment] 2021-12-13 21:03
> Please correct me if I'm mistaken, but this test case looks reasonable to me. If I understand correctly, the 2nd call to f1 is only removed because globals alias analysis determines that f1 does not read any memory.

@nunoplopes could you share a full LLVM IR reproducer? `f1` in `Transforms/EarlyCSE/globalsaa-memoryssa.ll` does not read any memory (and `globals-aa` is likely determining that), so both the first and second calls should behave exactly the same way. If the first call does not return, the second call will never be executed.

If `f1` is changed to actually read memory, the call is not eliminated. Similarly if if `f1` is a declaration, it must be `readnone`  for the call to be removed.

```
@g =  external global i16

define i16 @f1() readonly {
  %l = load i16, i16* @g
  ret i16 %l
}

define void @f3() {
  %call1 = call i16 @f1() readonly 
  call void @f2()
  %call2 = call i16 @f1() readonly 
  ret void
}

declare void @f2()
```
https://llvm.godbolt.org/z/b3KfGo5T6

**Comment by fhahn** [comment] 2021-12-17 11:30
Closing as per previous comment. @nunoplopes please re-open with a full IR reproducer if I missed anything above.

**Closed by fhahn** 2021-12-17 11:30 UTC
Labels: bugzilla, miscompilation

**Comment by nunoplopes** [comment] 2021-12-22 12:14
Sorry for the delay.
Yes, I missed that the test was using -globals-aa. I've added that to the Alive2 skip list as we don't support global analyses ATM.
