### ISSUE TITLE
lld-link doesn't find libraries in winsysroot

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#59710] opened 2022-12-27 00:51 UTC
```console
$ touch foo.c
$ clang-cl -o foo.obj -c foo.c
$ lld-link -out:foo.dll -dll foo.obj -winsysroot:/path/to/winsysroot user32.lib
lld-link: error: could not open 'user32.lib': No such file or directory
```
Using defaultlib does work:
```console
$ lld-link -out:foo.dll -dll foo.obj -winsysroot:/path/to/winsysroot -defaultlib:user32.lib
```
The problem is that `addWinSysRootLibSearchPaths` is called too late.

**Comment by aeubanks** [comment] 2023-05-18 20:18
dupe of https://github.com/llvm/llvm-project/issues/54409

**Closed by aeubanks** 2023-05-18 20:18 UTC
Labels: lld:COFF
