### ISSUE TITLE
clang-format: Inserts unwanted newlines in template <typename...> typename class template

### ISSUE THREAD

**Issue by cvigue** [llvm/llvm-project#93793] opened 2024-05-30 09:35 UTC
Desired format:

```
template <template <typename...> typename Xxx,
          template <typename...> typename Yyy,
          typename... T>
class A
{
};

```

Actual format: 

```
template <template <typename...> typename Xxx,
          template <typename...>
          typename Yyy,
          typename... T>
class A
{
};
```

My .clang-format:

```
BasedOnStyle: Microsoft
ColumnLimit: 0
SortIncludes: Never
BreakBeforeBinaryOperators: All
BinPackArguments: False
BinPackParameters: False
LambdaBodyIndentation: OuterScope
IndentCaseBlocks: true
MaxEmptyLinesToKeep: 3
BraceWrapping:
  AfterNamespace: false
  AfterCaseLabel: true
  BeforeLambdaBody: true

```

Using clang-format 14

**Comment by rymiel** [comment] 2024-06-10 19:28
Duplicate of https://github.com/llvm/llvm-project/issues/48746

**Closed by rymiel** 2024-06-10 19:28 UTC
Labels: duplicate, clang-format
