### ISSUE TITLE
[clang-format] Formatting chained stream output (bitwise left shift) operators <<

### ISSUE THREAD

**Issue by Alexolut** [llvm/llvm-project#93034] opened 2024-05-22 13:56 UTC
In clang-format 18.1.0-18.1.4 the following code doesn't changed after formatting based on Google-style:

```
stream << "A" << "B" << "C" << "D";
```

In other words as long as we fit in line length, all is places in one line.

But in 18.1.5 and 18.1.6 every operand is placed on the different line despite the allowed length of line like this:

```
stream << "A"
       << "B"
       << "C"
       << "D";
```

Which behavior is considered correct? Is there a way to configure this behavior by some format option?

**Comment by owenca** [comment] 2024-05-24 01:22
> In clang-format 18.1.0-18.1.4 the following code doesn't changed after formatting based on Google-style:
> 
> ```
> stream << "A" << "B" << "C" << "D";
> ```
> 
> In other words as long as we fit in line length, all is places in one line.
> 
> But in 18.1.5 and 18.1.6 every operand is placed on the different line despite the allowed length of line like this:
> 
> ```
> stream << "A"
>        << "B"
>        << "C"
>        << "D";
> ```

Please see the release notes of [18.1.5](https://discourse.llvm.org/t/18-1-5-released/78740).

> Which behavior is considered correct? Is there a way to configure this behavior by some format option?

See #92214, which addresses the issues post 18.1.6.

**Comment by Alexolut** [comment] 2024-05-24 10:46
> See #92214, which addresses the issues post 18.1.6.

Am I understand you correctly, that for versions newer than 18.1.6 expected behavior will be "Leave as is" for both code excerpts that I mentioned at the top of the thread? 

```
stream << "A"
       << "B"
       << "C"
       << "D";
```

```
stream << "A" << "B" << "C" << "D";
```

Will something like this:

```
stream              << "A" <<            "B"
  << "C"
                      << "D";
```

be formatted in this way?

```
stream << "A" << "B"
       << "C"
       << "D";
```

**Comment by owenca** [comment] 2024-05-25 02:29
@Alexolut exactly!

**Comment by owenca** [comment] 2024-05-27 22:50
Duplicate of #44363.

**Closed** 2024-05-27 22:50 UTC
Labels: duplicate, clang-format
