### ISSUE TITLE
[Clang] Clang erroneously allows `if constexpr` in C23 mode

### ISSUE THREAD

**Issue by Sirraide** [llvm/llvm-project#112587] opened 2024-10-16 17:30 UTC
See https://godbolt.org/z/E8PEzzfP3. According to @AaronBallman, this isn’t intentional, so we should probably disallow this.

**Comment by AaronBallman** [comment] 2024-10-16 17:32
It would be really nice if we could get a fix for this in to Clang 19.x

**Comment by Fznamznon** [comment] 2024-10-17 05:34
I don't think this is a regression since clang 18 doesn't support c23 constexpr.

**Comment by shafik** [comment] 2024-10-17 05:39
> I don't think this is a regression since clang 18 doesn't support c23 constexpr.

I guess I look at it as `if constexpr` is now erroneously enabled in C whereas previously it was a hard error.

**Closed** 2024-10-17 11:42 UTC
Labels: c23, clang:frontend, accepts-invalid, confirmed, regression:19
