### ISSUE TITLE
LLDB wont print string object. 

### ISSUE THREAD

**Issue by Hermit97** [llvm/llvm-project#65666] opened 2023-09-07 19:48 UTC
I compiled my .cpp file with clang++ -g -o file filename.cpp. Ran lldb ./test and set a break point and ran through till I hit it and I printed a simple string object called "a" whose value is "test\n". The result was an  error:  

(lldb) print a 
(std::string) $1 = error: summary string parsing error

I am only encountering this error when trying to print a string object. It prints a int object correctly. 
I tried compiling with g++ -g -o file filename.cpp
Then I ran lldb as usual and printed the string object fine with no issue. This seems to an issue with clang++ itself since g++ is not producing any error. 

lldb version 16.0.6
clang version 16.0.6
I also tried with lldb and clang version 14 result was the same issue. 
OS: Linux mint 5.15.0-79-generic

**Comment by DavidSpickett** [comment] 2023-09-08 10:02
What's your g++ version? Could be a difference in debug info, which we can find by comparing the output from `llvm-dwardump` on both objects.

**Comment by DavidSpickett** [comment] 2023-09-08 10:46
Might be a duplicate of https://github.com/llvm/llvm-project/issues/22687.

**Comment by Hermit97** [comment] 2023-09-08 21:57
g++ version is 11.4.0

**Comment by dwblaikie** [comment] 2023-09-20 22:03
duplicate #22687

**Closed by dwblaikie** 2023-09-20 22:03 UTC
Labels: lldb
