### ISSUE TITLE
BOLT doesn't build with -DLLVM_LINK_LLVM_DYLIB on Debian bullseye

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#57551] opened 2022-09-04 11:58 UTC
```console
FAILED: bin/llvm-bolt-heatmap 
: && "/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/./bin/clang++" -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/tools/clang/stage2-bins=build-llvm/tools/clang/stage2-bins -ffile-prefix-map=/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/= -no-canonical-prefixes -O3 -DNDEBUG -Wl,-z,relro -Wl,--build-id -fuse-ld=gold    -Wl,--gc-sections tools/bolt/tools/heatmap/CMakeFiles/llvm-bolt-heatmap.dir/heatmap.cpp.o -o bin/llvm-bolt-heatmap  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMBOLTProfile.a  lib/libLLVMBOLTRewrite.a  lib/libLLVMBOLTUtils.a  lib/libLLVMBOLTProfile.a  lib/libLLVMBOLTRuntimeLibs.a  lib/libLLVMBOLTPasses.a  lib/libLLVMBOLTCore.a  lib/libLLVMBOLTUtils.a  lib/libLLVMBOLTTargetAArch64.a  lib/libLLVMBOLTTargetX86.a  lib/libLLVM-15.so.1 && :
lib/libLLVMBOLTTargetAArch64.a(AArch64MCPlusBuilder.cpp.o):AArch64MCPlusBuilder.cpp:function (anonymous namespace)::AArch64MCPlusBuilder::getTargetExprFor(llvm::MCInst&, llvm::MCExpr const*, llvm::MCContext&, unsigned long) const: error: undefined reference to 'llvm::AArch64MCExpr::create(llvm::MCExpr const*, llvm::AArch64MCExpr::VariantKind, llvm::MCContext&)'
lib/libLLVMBOLTTargetAArch64.a(AArch64MCPlusBuilder.cpp.o):AArch64MCPlusBuilder.cpp:function (anonymous namespace)::AArch64MCPlusBuilder::createLongJmp(std::vector<llvm::MCInst, std::allocator<llvm::MCInst> >&, llvm::MCSymbol const*, llvm::MCContext*, bool): error: undefined reference to 'llvm::AArch64MCExpr::create(llvm::MCExpr const*, llvm::AArch64MCExpr::VariantKind, llvm::MCContext&)'
[...]

```

On a debian linux amd64

**Comment by aaupov** [comment] 2022-09-04 18:29
Can you please provide the CMake invocation and compiler/linker versions?
Couldn't reproduce on Ubuntu 20.04 on tags/llvmorg-15.0.0-rc3.

**Comment by sylvestre** [comment] 2022-09-04 18:34
This is the debian packages:

```
 cmake -S llvm/ -B build-llvm \
-G Ninja \
-DCMAKE_INSTALL_PREFIX=/usr/lib/llvm-15 \
-DLLVM_VERSION_SUFFIX= \
-DCMAKE_SUPPRESS_REGENERATION=ON \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_C_FLAGS="-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
-DCMAKE_CXX_FLAGS="-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
-DCMAKE_SHARED_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id" \
-DCMAKE_MODULE_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id" \
-DCMAKE_EXE_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id" \
-DPACKAGE_VENDOR=Debian \
-DENABLE_LINKER_BUILD_ID=ON \
-DLLVM_TARGETS_TO_BUILD=Native \
-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;cross-project-tests;mlir;bolt;polly;lldb" \
-DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind;openmp" \
-DLLVM_ENABLE_PIC=ON \
-DLLVM_ENABLE_RTTI=ON \
-DLLVM_BUILD_DOCS=OFF \
-DLLVM_INCLUDE_GO_TESTS=OFF \
-DLLVM_USE_RELATIVE_PATHS_IN_FILES=ON \
-DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON \
-DLLVM_ENABLE_CURL=ON \
-DCLANG_PLUGIN_SUPPORT=OFF \
-DCLANG_BUILD_EXAMPLES=OFF \
-DCLANG_DEFAULT_LINKER=ld \
-DCLANG_DEFAULT_CXX_STDLIB=libstdc++ \
-DCLANG_DEFAULT_RTLIB=libgcc \
-DCOMPILER_RT_BUILD_XRAY=OFF \
-DCOMPILER_RT_INCLUDE_TESTS=OFF \
-DCOMPILER_RT_USE_LIBCXX=OFF \
-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON \
-DLIBUNWIND_USE_COMPILER_RT=ON \
-DLIBUNWIND_INSTALL_LIBRARY=OFF \
-DLIBCXXABI_ENABLE_EXCEPTIONS=ON \
-DLIBCXXABI_USE_COMPILER_RT=ON \
-DLIBCXXABI_INSTALL_LIBRARY=OFF \
-DLIBCXX_ENABLE_EXCEPTIONS=ON \
-DLIBCXX_USE_COMPILER_RT=ON \
-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
-DLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON \
-DLIBCXX_STATICALLY_LINK_ABI_IN_SHARED_LIBRARY=OFF \
-DLIBCXX_INSTALL_LIBRARY=OFF \
-DOPENMP_ENABLE_LIBOMP_PROFILING=OFF \
-DOPENMP_ENABLE_LIBOMPTARGET_PROFILING=OFF \
-DLIBOMP_ENABLE_RTTI=OFF \
-DLIBOMP_OMPT_SUPPORT=OFF \
 -DLLVM_USE_LINKER=gold -DLLVM_BINUTILS_INCDIR=/usr/include/ -DLIBCXXABI_USE_LLVM_UNWINDER=ON -DLIBOMP_LIBFLAGS="-lm" -DOPENMP_USE_LLVM_UNWINDER=ON -DMLIR_INSTALL_AGGREGATE_OBJECTS=OFF -DLLDB_ENABLE_LUA=OFF \
-DBUILTINS_CMAKE_ARGS="-DCMAKE_C_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_CXX_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_EXE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_MODULE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_BUILD_TYPE=Release;-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF" \
-DRUNTIMES_CMAKE_ARGS="-DCMAKE_C_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_CXX_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_EXE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_MODULE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_BUILD_TYPE=Release;-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF" \
-DCLANG_ENABLE_BOOTSTRAP=ON \
-DCLANG_BOOTSTRAP_TARGETS="check-all;check-llvm;check-clang;check-clang-tools;check-lld;check-libcxx;check-libcxxabi;check-mlir;check-sanitizer;llvm-config;test-suite" \
-DCLANG_BOOTSTRAP_PASSTHROUGH="CMAKE_INSTALL_PREFIX;CMAKE_SUPPRESS_REGENERATION;ENABLE_LINKER_BUILD_ID;LLVM_ENABLE_PIC;LLVM_ENABLE_RTTI;LLVM_INCLUDE_GO_TESTS;LLVM_USE_RELATIVE_PATHS_IN_FILES;CLANG_DEFAULT_LINKER;CLANG_DEFAULT_CXX_STDLIB;CLANG_DEFAULT_RTLIB;COMPILER_RT_USE_LIBCXX;COMPILER_RT_USE_BUILTINS_LIBRARY;COMPILER_RT_INCLUDE_TESTS;LIBUNWIND_USE_COMPILER_RT;LIBCXXABI_ENABLE_EXCEPTIONS;LIBCXXABI_USE_COMPILER_RT;LIBCXX_USE_COMPILER_RT;LIBCXX_ENABLE_EXCEPTIONS;LIBCXX_ENABLE_STATIC_ABI_LIBRARY;LIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY;LIBCXX_STATICALLY_LINK_ABI_IN_SHARED_LIBRARY;LIBOMP_ENABLE_RTTI;LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN" \
-DBOOTSTRAP_CMAKE_BUILD_TYPE=RelWithDebInfo \
-DBOOTSTRAP_CMAKE_C_FLAGS_RELWITHDEBINFO="-O2 -DNDEBUG -g1" \
-DBOOTSTRAP_CMAKE_CXX_FLAGS_RELWITHDEBINFO="-O2 -DNDEBUG -g1" \
-DBOOTSTRAP_CMAKE_C_FLAGS="-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
-DBOOTSTRAP_CMAKE_CXX_FLAGS="-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
-DBOOTSTRAP_CMAKE_SHARED_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id" \
-DBOOTSTRAP_CMAKE_MODULE_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id" \
-DBOOTSTRAP_CMAKE_EXE_LINKER_FLAGS="-Wl,-z,relro -Wl,--build-id" \
-DBOOTSTRAP_LLVM_ENABLE_FFI=ON \
-DBOOTSTRAP_LLVM_ENABLE_DUMP=ON \
-DBOOTSTRAP_LLVM_ENABLE_LIBPFM=ON \
-DBOOTSTRAP_LLVM_ENABLE_SPHINX=ON \
-DBOOTSTRAP_CLANG_DEFAULT_PIE_ON_LINUX=ON \
-DBOOTSTRAP_SPHINX_WARNINGS_AS_ERRORS=OFF \
-DBOOTSTRAP_LLVM_USE_RELATIVE_PATHS_IN_FILES=ON \
-DBOOTSTRAP_LLVM_INSTALL_UTILS=ON \
-DBOOTSTRAP_LLVM_VERSION_SUFFIX= \
-DBOOTSTRAP_LLVM_POLLY_LINK_INTO_TOOLS=ON \
-DBOOTSTRAP_LLVM_EXPERIMENTAL_TARGETS_TO_BUILD="M68k" \
-DBOOTSTRAP_LLVM_LINK_LLVM_DYLIB=ON \
    -DBOOTSTRAP_LLVM_ENABLE_CURL=ON \
-DBOOTSTRAP_CLANG_LINK_CLANG_DYLIB=ON \
-DBOOTSTRAP_LIBCLANG_LIBRARY_VERSION=1 \
-DBOOTSTRAP_LIBCXX_INSTALL_EXPERIMENTAL_LIBRARY=ON \
-DBOOTSTRAP_PYTHON_EXECUTABLE=/usr/bin/python3 \
 -DBOOTSTRAP_LLVM_ENABLE_Z3_SOLVER=ON  -DBOOTSTRAP_CLANG_SYSTEMZ_DEFAULT_ARCH=z196  -DBOOTSTRAP_CLANGD_ENABLE_REMOTE=ON  -DBOOTSTRAP_LLVM_USE_PERF=ON  -DBOOTSTRAP_LLVM_ENABLE_LIBPFM=ON  -DBOOTSTRAP_LLVM_USE_LINKER=gold  -DBOOTSTRAP_LLVM_BINUTILS_INCDIR=/usr/include/  -DBOOTSTRAP_LIBCXXABI_USE_LLVM_UNWINDER=ON  -DBOOTSTRAP_LIBOMP_LIBFLAGS="-lm"  -DBOOTSTRAP_OPENMP_USE_LLVM_UNWINDER=ON  -DBOOTSTRAP_MLIR_INSTALL_AGGREGATE_OBJECTS=OFF  -DBOOTSTRAP_LLDB_ENABLE_LUA=OFF \
-DBOOTSTRAP_BUILTINS_CMAKE_ARGS="-DCMAKE_C_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_CXX_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_EXE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_MODULE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id;-DCMAKE_BUILD_TYPE=RelWithDebInfo;-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O2 -DNDEBUG -g1;-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O2 -DNDEBUG -g1;-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF" \
-DBOOTSTRAP_RUNTIMES_CMAKE_ARGS="-DCMAKE_C_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_CXX_FLAGS=-fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2;-DCMAKE_EXE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id -L/extra-dev/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/lib;-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id -L/extra-dev/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/lib;-DCMAKE_MODULE_LINKER_FLAGS=-Wl,-z,relro -Wl,--build-id -L/extra-dev/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/lib;-DCMAKE_BUILD_TYPE=RelWithDebInfo;-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O2 -DNDEBUG -g1;-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O2 -DNDEBUG -g1;-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF"

```

**Comment by aaupov** [comment] 2022-09-04 22:47
I can't reproduce the issue using cmake command or by following https://apt.llvm.org/building-pkgs.php (+adding BOLT to the list of projects). 
I vaguely understand I need a branch llvm-toolchain-15-15.0.0~+rc3 at https://salsa.debian.org/pkg-llvm-team/llvm-toolchain to repro exactly. Can you please push the branch for me?

**Comment by aaupov** [comment] 2022-09-05 00:48
Alternatively, please try this out:
```diff
diff --git a/bolt/lib/Target/AArch64/CMakeLists.txt b/bolt/lib/Target/AArch64/CMakeLists.txt
index 96c70168196e..f9767179dcb3 100644
--- a/bolt/lib/Target/AArch64/CMakeLists.txt
+++ b/bolt/lib/Target/AArch64/CMakeLists.txt
@@ -2,7 +2,7 @@ set(LLVM_LINK_COMPONENTS
   BOLTCore
   MC
   Support
-  AArch64Desc
+  AArch64
   )

 add_llvm_library(LLVMBOLTTargetAArch64
```

Or revert 64421e191bb23d67a2cd2777dbae9bd171d79482 which I tested as thoroughly as I could but apparently failed to account for some build configurations.

**Comment by sylvestre** [comment] 2022-09-05 19:12
> Alternatively, please try this out:
> 
> ```diff
> diff --git a/bolt/lib/Target/AArch64/CMakeLists.txt b/bolt/lib/Target/AArch64/CMakeLists.txt
> index 96c70168196e..f9767179dcb3 100644
> --- a/bolt/lib/Target/AArch64/CMakeLists.txt
> +++ b/bolt/lib/Target/AArch64/CMakeLists.txt
> @@ -2,7 +2,7 @@ set(LLVM_LINK_COMPONENTS
>    BOLTCore
>    MC
>    Support
> -  AArch64Desc
> +  AArch64
>    )
> 
>  add_llvm_library(LLVMBOLTTargetAArch64
> ```
> 
> Or revert [64421e1](https://github.com/llvm/llvm-project/commit/64421e191bb23d67a2cd2777dbae9bd171d79482) which I tested as thoroughly as I could but apparently failed to account for some build configurations.

Both won't work.
Adding these libs by hand fixes the issue:
`lib/libLLVMBOLTTargetAArch64.a  lib/libLLVMBOLTTargetX86.a   lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Utils.a lib/libLLVMX86Desc.a lib/libLLVMX86Info.` but dunno where to add them
Still on bin/llvm-bolt-heatmap 

To reproduce:
```
dget -x https://apt.llvm.org/unstable/pool/main/l/llvm-toolchain-15/llvm-toolchain-15_15.0.0~%2b%2b20220905103056%2b4ba6a9c9f65b-1~exp1~20220905103153.50.dsc.asc
cd llvm-toolchain-15*
# edit debian/rules to built bolt
```


And apply
```
Index: llvm-toolchain-15-15.0.0~+rc3/bolt/tools/merge-fdata/CMakeLists.txt
===================================================================
--- llvm-toolchain-15-15.0.0~+rc3.orig/bolt/tools/merge-fdata/CMakeLists.txt
+++ llvm-toolchain-15-15.0.0~+rc3/bolt/tools/merge-fdata/CMakeLists.txt
@@ -9,6 +9,6 @@ add_bolt_tool(merge-fdata
 set_target_properties(merge-fdata PROPERTIES FOLDER "BOLT")
 
 # Emit relocations for BOLT meta test (bolt/test/runtime/meta-merge-fdata.test)
-if (BOLT_INCLUDE_TESTS AND UNIX AND NOT APPLE)
-  target_link_options(merge-fdata PRIVATE LINKER:--emit-relocs)
-endif()
+# if (BOLT_INCLUDE_TESTS AND UNIX AND NOT APPLE)
+#   target_link_options(merge-fdata PRIVATE LINKER:--emit-relocs)
+# endif()

```

**Comment by aaupov** [comment] 2022-09-13 19:36
> > Alternatively, please try this out:
> > ```diff
> > diff --git a/bolt/lib/Target/AArch64/CMakeLists.txt b/bolt/lib/Target/AArch64/CMakeLists.txt
> > index 96c70168196e..f9767179dcb3 100644
> > --- a/bolt/lib/Target/AArch64/CMakeLists.txt
> > +++ b/bolt/lib/Target/AArch64/CMakeLists.txt
> > @@ -2,7 +2,7 @@ set(LLVM_LINK_COMPONENTS
> >    BOLTCore
> >    MC
> >    Support
> > -  AArch64Desc
> > +  AArch64
> >    )
> > 
> >  add_llvm_library(LLVMBOLTTargetAArch64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or revert [64421e1](https://github.com/llvm/llvm-project/commit/64421e191bb23d67a2cd2777dbae9bd171d79482) which I tested as thoroughly as I could but apparently failed to account for some build configurations.
> 
> Both won't work. Adding these libs by hand fixes the issue: `lib/libLLVMBOLTTargetAArch64.a lib/libLLVMBOLTTargetX86.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Utils.a lib/libLLVMX86Desc.a lib/libLLVMX86Info.` but dunno where to add them Still on bin/llvm-bolt-heatmap
> 
> To reproduce:
> 
> ```
> dget -x https://apt.llvm.org/unstable/pool/main/l/llvm-toolchain-15/llvm-toolchain-15_15.0.0~%2b%2b20220905103056%2b4ba6a9c9f65b-1~exp1~20220905103153.50.dsc.asc
> cd llvm-toolchain-15*
> # edit debian/rules to built bolt
> ```
> 

Sorry, I'm not very familiar with dget. dget downloads the asc file with PGP but then nothing happens. Do I need to add some sources?

**Comment by sylvestre** [comment] 2022-09-13 20:01
sorry, remove the .asc :)

**Comment by aaupov** [comment] 2022-09-14 00:52
Reproduced locally.

**Comment by aaupov** [comment] 2022-09-14 02:40
The issue is that 

> ```
> FAILED: bin/llvm-bolt-heatmap 
> : && "/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/./bin/clang++" -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/build-llvm/tools/clang/stage2-bins=build-llvm/tools/clang/stage2-bins -ffile-prefix-map=/home/sylvestre/dev/debian/pkg-llvm/llvm-toolchain/branches/llvm-toolchain-15-15.0.0~+rc3/= -no-canonical-prefixes -O3 -DNDEBUG -Wl,-z,relro -Wl,--build-id -fuse-ld=gold    -Wl,--gc-sections tools/bolt/tools/heatmap/CMakeFiles/llvm-bolt-heatmap.dir/heatmap.cpp.o -o bin/llvm-bolt-heatmap  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMBOLTProfile.a  lib/libLLVMBOLTRewrite.a  lib/libLLVMBOLTUtils.a  lib/libLLVMBOLTProfile.a  lib/libLLVMBOLTRuntimeLibs.a  lib/libLLVMBOLTPasses.a  lib/libLLVMBOLTCore.a  lib/libLLVMBOLTUtils.a  lib/libLLVMBOLTTargetAArch64.a  lib/libLLVMBOLTTargetX86.a  lib/libLLVM-15.so.1 && :
> lib/libLLVMBOLTTargetAArch64.a(AArch64MCPlusBuilder.cpp.o):AArch64MCPlusBuilder.cpp:function (anonymous namespace)::AArch64MCPlusBuilder::getTargetExprFor(llvm::MCInst&, llvm::MCExpr const*, llvm::MCContext&, unsigned long) const: error: undefined reference to 'llvm::AArch64MCExpr::create(llvm::MCExpr const*, llvm::AArch64MCExpr::VariantKind, llvm::MCContext&)'
> lib/libLLVMBOLTTargetAArch64.a(AArch64MCPlusBuilder.cpp.o):AArch64MCPlusBuilder.cpp:function (anonymous namespace)::AArch64MCPlusBuilder::createLongJmp(std::vector<llvm::MCInst, std::allocator<llvm::MCInst> >&, llvm::MCSymbol const*, llvm::MCContext*, bool): error: undefined reference to 'llvm::AArch64MCExpr::create(llvm::MCExpr const*, llvm::AArch64MCExpr::VariantKind, llvm::MCContext&)'
> [...]
> ```
> 
> On a debian linux amd64

The issue is probably that LLVM libraries specified with LLVM_LINK_COMPONENTS are not passed to the linker in stage2 build.

excerpt from the failing compiler invocation:
> lib/libLLVMBOLTProfile.a  lib/libLLVMBOLTRewrite.a  lib/libLLVMBOLTUtils.a  lib/libLLVMBOLTProfile.a  lib/libLLVMBOLTRuntimeLibs.a  lib/libLLVMBOLTPasses.a  lib/libLLVMBOLTCore.a  lib/libLLVMBOLTUtils.a  lib/libLLVMBOLTTargetAArch64.a  lib/libLLVMBOLTTargetX86.a  lib/libLLVM-15.so.1

There should also be libLLVMX86 and libLLVMAArch64 libraries.

Since it's not an issue for a regular build, I would assume they're passed just fine. Still trying to understand how to fix this issue.

**Comment by aaupov** [comment] 2022-09-14 22:10
Quick note: the issue doesn't reproduce with a regular two-stage build (`-DCLANG_ENABLE_BOOTSTRAP=On`)

**Comment by aaupov** [comment] 2022-09-14 22:32
Looks like the culprit is -DLLVM_LINK_LLVM_DYLIB

Simple reproducer:
```
time cmake -B build-clang-dylib llvm-project/llvm -GNinja   -DLLVM_ENABLE_PROJECTS="bolt"  -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="AArch64;X86" -DLLVM_LINK_LLVM_DYLIB=ON && time cmake --build build-clang-dylib --target llvm-bolt
```

**Comment by aaupov** [comment] 2022-09-19 18:10
Hi @compnerd @Ericson2314 @ldionne @Flakebi,
Can you please help me with this issue? It requires deeper understanding of LLVM's CMake configuration than what I have. 

The problem here is that with the DLLVM_LINK_LLVM_DYLIB flag (see repro above):
1) libLLVM doesn't have the target-specific libraries/symbols (e.g. symbols from libLLVMX86Desc). 
2) If these target-specific components are not supposed to be linked into libLLVM, the corresponding libraries are not provided to the linker for libLLVMBOLTTarget, even though they are requested via LLVM_LINK_COMPONENTS: https://github.com/llvm/llvm-project/blob/bbef90ace4cd565ba193c052e10f23459dbe9aac/bolt/lib/Target/X86/CMakeLists.txt#L1-L8

**Comment by compnerd** [comment] 2022-09-19 18:36
I think that the problem is that it explicitly is setting `X86Desc` rather than computing the targets enabled and picking up the appropriate set of dependencies from that set.

**Comment by aaupov** [comment] 2022-09-19 18:54
> I think that the problem is that it explicitly is setting `X86Desc` rather than computing the targets enabled and picking up the appropriate set of dependencies from that set.

We do that in upper level folder CMakeLists - BOLT Targets (X86 and AArch64 currently) are only added if corresponding LLVM_TARGETS_TO_BUILD are set: https://github.com/llvm/llvm-project/blob/20822e2d4250a4648ba56230828bc6957d60eb26/bolt/lib/Target/CMakeLists.txt#L1-L4

Note that we've also tried using the full target (X86/AArch64) in LLVM_LINK_COMPONENTS rather than only the required part (*Desc), with no effect - see comment https://github.com/llvm/llvm-project/issues/57551#issuecomment-1237401023.

Please let me know I'm missing something here.

**Comment by nikic** [comment] 2022-09-19 19:11
The problem here is that bolt is using parts of LLVM that are not part of it's public (the entire Target layer). This line should be a big indication of something going very, very wrong: https://github.com/llvm/llvm-project/blob/c625c17b88b4831c99269546fc0ede1667528c6b/bolt/lib/Target/X86/CMakeLists.txt#L19 This is including private LLVM headers in bolt.

For this issue in particular, I believe the relevant part is this: https://github.com/llvm/llvm-project/blob/eec19987c04be4c94ffdd27817d4f77e1b7ee0a8/llvm/lib/Target/CMakeLists.txt#L22-L31

The target symbols are not exported from the shared object, because they are explicitly not intended to be part of the public LLVM API.

By the way, this also makes it challenging to get bolt shipped in distros, because it makes it impossible to build against a system LLVM.

**Comment by aaupov** [comment] 2022-09-19 19:20
@nikic thank you for clarification! I can see the problem here, but we explicitly want to rely on target definitions instead of reimplementing them in BOLT. We can pull some of them back (e.g. X86::isJCC etc), but some of them must be used from the target (e.g. AArch64MCExpr::create). 

What do you think is a proper course of action here? CC @maksfb @rafaelauler

**Comment by nikic** [comment] 2022-09-19 19:27
@aaupov I agree that sharing target definitions instead of reimplementing is a good idea -- we just need to find some way to publicly export the needed parts (both in terms of symbol visibility and headers). Unfortunately I'm not familiar with both Bolt and the MC layer, so I don't know how that would look like in more concrete terms.

I guess to fix the particular issue here it might be enough to put LLVM_LIBRARY_VISIBILITY on relevant classes.

**Comment by serge-sans-paille** [comment] 2022-09-20 13:03
First step in that direction (doesn't fix the core issue though) https://reviews.llvm.org/D134278

**Comment by serge-sans-paille** [comment] 2022-09-21 08:17
@sylvestre : I managed to build bolt for Fedora, but it requires (in addition to the above patch) to link with the archive version of each llvm components. The associated specfile can be found here: https://sergesanspaille.fedorapeople.org/llvm-bolt.spec

**Comment by serge-sans-paille** [comment] 2022-09-22 13:05
With https://reviews.llvm.org/D134434 the build should succeed (but still not using libLLVM.so)

**Comment by aaupov** [comment] 2022-09-22 18:43
> With https://reviews.llvm.org/D134434 the build should succeed (but still not using libLLVM.so)

That's awesome. Thank you for your help.

**Comment by sylvestre** [comment] 2022-09-22 18:53
Indeed, many thanks :)

**Comment by serge-sans-paille** [comment] 2022-09-23 07:07
Patch landed, but it's more of a workaround as BOLT still doesn't link with libLLVM.so *at all*. Feel free to close the issue or keep it opened to track the underlying public vs. private interface issue.

**Comment by aaupov** [comment] 2022-09-23 07:21
> Patch landed, but it's more of a workaround as BOLT still doesn't link with libLLVM.so _at all_. Feel free to close the issue or keep it opened to track the underlying public vs. private interface issue.

Thank you again. We've started talking about this issue within the team. It might take a while to resolve, but until then, we hope that llvm-bolt ~52M binary size is not a terribly huge concern for distributors.

**Comment by aaupov** [comment] 2023-09-22 05:54
Fixed.

**Closed by aaupov** 2023-09-22 05:54 UTC
Labels: build-problem, BOLT
