### ISSUE TITLE
Clang rejects valid friend access

### ISSUE THREAD

**Issue by Boris-Rasin** [llvm/llvm-project#83072] opened 2024-02-26 22:16 UTC
Rejected by Clang 17.0.1, works with gcc and msvc.

```cpp
struct A
{
    template <typename T>
    using type = typename T::type;
};

class B
{
    friend class A;
    using type = int;
};

A::type<B> a;
```
https://godbolt.org/z/r1E55hn43

**Comment by shafik** [comment] 2024-02-27 05:12
Duplicate of: https://github.com/llvm/llvm-project/issues/25708

**Closed by shafik** 2024-02-27 05:12 UTC
Labels: clang:frontend
