### ISSUE TITLE
Strange formatting of a requires containing an array

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#53864] opened 2022-02-15 17:54 UTC
I tested with clang-format after https://reviews.llvm.org/D113319 landed and found some issues in new code. This looks similar to #53820, but I'm not sure whether it's the same issue.
I used this config
```
BasedOnStyle: LLVM
  
---
Language: Cpp
Standard: c++20
```
Code (for libc++ so uses __ugly_names)
```
template <class _Context, class _Tp>
  requires is_array_v<_Tp> &&
           same_as<_Tp, typename _Context::char_type[extent_v<_Tp>
]> consteval auto
  __make_storage_type() {
  return __storage_type<basic_string_view<typename _Context::char_type>>{};
}
```
I would expect this part to be on one line `same_as<_Tp, typename _Context::char_type[extent_v<_Tp>]>`
Using parens solves the issue
```
template <class _Context, class _Tp>
  requires(is_array_v<_Tp> &&
           same_as<_Tp, typename _Context::char_type[extent_v<_Tp>]>)
consteval auto __make_storage_type() {
  return __storage_type<basic_string_view<typename _Context::char_type>>{};
}
```

**Comment by HazardyKnusperkeks** [comment] 2022-02-15 22:20
It has definitely the same reason as #53820, but if the same fix applies I have to check the coming days.

**Comment by HazardyKnusperkeks** [comment] 2022-02-16 14:17
> It has definitely the same reason as #53820, but if the same fix applies I have to check the coming days.

So this was a lie. The problem is the nested template, this one will take some time to figure out.
But using an array in the top level of a constraint expression will also have a problem.

**Comment by HazardyKnusperkeks** [comment] 2022-02-21 20:25
Just to give a heads up. This is gonna take long. For once because it is a big problem to solve (which will help to clean clang-format), but also because I have to do other stuff right now. I'm sure we make it to the release of LLVM 15.

**Comment by mordante** [comment] 2022-02-22 07:15
Thanks for the heads up. I'll use the parens, at style I like slightly better. (They were removed to format better with clang-format at that time. Now it formats better with parens.)

**Comment by JohelEGP** [comment] 2022-07-04 16:49
Is this fixed? According to https://github.com/llvm/llvm-project/issues/53819#issuecomment-1047207866, it's my same issue. I was able to remove the workarounds to get the same formatting I had before.

**Comment by HazardyKnusperkeks** [comment] 2022-07-04 19:30
This one might be fixed, but the conceptual error is still there. Just the most likely stuff works.
If everything on your code works fine, you can close this issue. I have my todo list somewhere else.

**Comment by rymiel** [comment] 2022-12-25 17:27
(I think this issue can be closed now)

**Closed** 2023-10-25 10:52 UTC
Labels: bug, clang-format, confirmed
