### ISSUE TITLE
clang emits invalid wasm code when compiling C

### ISSUE THREAD

**Issue by TerrorJack** [llvm/llvm-project#108770] opened 2024-09-15 16:22 UTC
Minimal repro:

```c
extern int a;
void* b();
void c(void *);
void f() {
  void *d = b();
e:
  switch (a)
  case 0: {
    b();
    c(d);
    c((void *)*(int *)(d + -sizeof(int)));
    d = d - sizeof(int);
    goto e;
  }
}
```

The above code, when compiled with `--target=wasm32 -O1` using latest `clang` on `main`, will produce the following **invalid** assembly code:

```asm
f:                                      # @f
        .functype       f () -> ()
        .local          i32
# %bb.0:
        call    b
        local.set       0
        block
        i32.const       0
        i32.load        a
        br_if           0                               # 0: down to label0
# %bb.1:
        local.get       0
        local.set       0
.LBB0_2:                                # =>This Inner Loop Header: Depth=1
        loop                                            # label1:
        call    b
        drop
        local.get       0
        local.tee       0
        call    c
        local.get       0
        i32.load        -4
        call    c
        local.get       0
        i32.const       -4
        i32.add
        local.set       0
        i32.const       0
        i32.load        a
        i32.eqz
        br_if           0                               # 0: up to label1
.LBB0_3:
        end_loop
        end_block                               # label0:
                                        # fallthrough-return
        end_function
```

Note the `i32.load -4` line. This is invalid per wasm spec, the memarg offset/align must all be non-negative u32 literals. And indeed this code will trigger a memory trap at runtime!

I bisected this bug on `master` and the first bad commit is https://github.com/llvm/llvm-project/commit/7eca38ce76d5d1915f4ab7e665964062c0b37697.  cc @hazzlim

**Comment by aheejin** [comment] 2024-09-15 18:47
Another bug was reported recently regarding this commit (https://github.com/llvm/llvm-project/pull/107257#issuecomment-2346895150), which has been fixed by https://github.com/llvm/llvm-project/commit/940f89255e4a3982d94dad57837e8e658092af78. Can you check if https://github.com/llvm/llvm-project/commit/940f89255e4a3982d94dad57837e8e658092af78 fixes your bug too?

**Comment by nikic** [comment] 2024-09-15 20:39
@aheejin That's an unrelated issue. I expect that https://github.com/llvm/llvm-project/blob/76b54df87a860c20ac68e4ed1d766b545d412c1e/llvm/lib/Target/WebAssembly/WebAssemblyISelDAGToDAG.cpp#L328-L332 needs an adjustment to also check for non-negative offset, instead of assuming that nuw implies that (which it never did, but previously it was harder to get one with a negative offset).

**Comment by aheejin** [comment] 2024-09-17 06:06
@nikic Thanks for the pointer!

I think this code (added in #107257) is adding `nuw` to the `getelementptr`:
https://github.com/llvm/llvm-project/blob/41f1b467a29d2ca4e35df37c3aa79a0a8c04bc4f/clang/lib/CodeGen/CGExprScalar.cpp#L5774-L5775

But the condition there says `!SignedIndices`. Why wouldn't a negative RHS value make that `SignedIndices` true?
I traced where that `SignedIndices` comes from
https://github.com/llvm/llvm-project/blob/41f1b467a29d2ca4e35df37c3aa79a0a8c04bc4f/clang/lib/CodeGen/CGExprScalar.cpp#L3966
where that `Type` is set in
https://github.com/llvm/llvm-project/blob/41f1b467a29d2ca4e35df37c3aa79a0a8c04bc4f/clang/lib/Sema/SemaExpr.cpp#L15393-L15409

So the type of the value apparently does not depend on the signs (`UO_PLUS` or `UO_MINUS`). I'm not very familiar with Clang internals. Do you know why the minus sign doesn't make the type signed?

**Comment by nikic** [comment] 2024-09-17 07:25
@aheejin Basically, because `-unsigned` is still `unsigned`, or `-size_t` is `size_t` in this particular case. (But `-unsigned short` is `int` due to promotion rules.)

**Comment by aheejin** [comment] 2024-09-17 07:54
But we actually have a test case that tests folding a negative offset.. and it looks you added it https://github.com/llvm/llvm-project/commit/0564d0665b302d1c7861e03d2995612f46613a0f

**Comment by nikic** [comment] 2024-09-17 08:02
Right. When I added that test wasm was just a convenient testing vector for the underlying SDAG representation, I didn't really consider whether there is anything wasm-specific to take into account here. Sorry about that.

Now that I re-read the bug report, it's possible that I misunderstood what the report is about. So let me try to clarify this: Is `load` with a "negative" number (alternative reading: a large unsigned number) *malformed* wasm, as in, will it result in some kind of validation or verifier error? If yes, then we should prevent that with an additional non-negativity check. Or is it just that it does not have the semantics of performing negative indexing? If so, then there is nothing to do here -- the memory trap reported by OP is the expected outcome, because the code has undefined behavior.

**Comment by nikic** [comment] 2024-09-17 08:05
Per https://webassembly.github.io/spec/core/syntax/instructions.html#memory-instructions it looks to me like the memarg offset is interpreted like u32, in which case current codegen would be correct. But maybe I'm reading the spec wrong.

**Comment by aheejin** [comment] 2024-09-17 08:19
I think you are right. Negative values are read as a very large positive numbers, and that itself is not a validation failure. But it will trap if the resulting range exceeds the memory's size. See Step 10 in https://webassembly.github.io/spec/core/exec/instructions.html#t-mathsf-xref-syntax-instructions-syntax-instr-memory-mathsf-load-xref-syntax-instructions-syntax-memarg-mathit-memarg-and-t-mathsf-xref-syntax-instructions-syntax-instr-memory-mathsf-load-n-mathsf-xref-syntax-instructions-syntax-sx-mathit-sx-xref-syntax-instructions-syntax-memarg-mathit-memarg

Will close this as working as intended. @TerrorJack Feel free to reopen if there are things not addressed.

**Comment by TerrorJack** [comment] 2024-09-17 13:22
Sorry, but would you re-open this issue since I don't have the rights to do so? @aheejin This is *not* working as intended, see the following assembly program:

```asm
.functype foo () -> (i32)
.globl foo
.export_name foo, foo
.section .text.f,"",@
foo:
  .functype foo () -> (i32)
  i32.const 8
  i32.load -4
  end_function
```

You can compile it with `clang --target=wasm32 test.s -o test.wasm -nostdlib -Wl,--no-entry` and run the exported `foo` function. Unfortunately, it produces a memory trap with both nodejs(v8) and bun(javascriptcore). There is *no* automatic wrapping of arithmetic plus of memory address and offset.

**Comment by nikic** [comment] 2024-09-17 13:29
@TerrorJack The memory trap *is* the intended behavior. Please run your code under UBSan, you should receive an error like "addition of unsigned offset to ABC overflowed to XYZ". (If you have a sample that does not produce an ubsan error, please do share it.)

If you want to perform negative indexing, you need to either write either`d - sizeof(int)` or something like `d + -(ssize_t)sizeof(int)`.

**Comment by dschuff** [comment] 2024-09-17 17:27
>   i32.load -4

Remember that while it is possible to *write* this in assembler, it doesn't really mean what it looks like it means. According to the spec (see the links @nikic and @aheejin posted above), the constant offset field is always interpreted as an unsigned value. Wasm simply doesn't have the capability to do negative constant offsets on loads. As @nikic says, if you have a negative offset, it can't be folded directly into the load instruction, you just need an add instruction to calculate the effective address.

**Comment by TerrorJack** [comment] 2024-09-17 17:35
> it can't be folded directly into the load instruction, you just need an add instruction to calculate the effective address.

You're absolutely right; my point is, `clang` *might* generate this kind of problematic assembly these days as shown in the example; even though UB might be involved, it still makes some sense for upstream to avoid generating negative offsets.

**Comment by nikic** [comment] 2024-09-17 18:30
> > it can't be folded directly into the load instruction, you just need an add instruction to calculate the effective address.
> 
> You're absolutely right; my point is, `clang` _might_ generate this kind of problematic assembly these days as shown in the example; even though UB might be involved, it still makes some sense for upstream to avoid generating negative offsets.

Could you explain in more detail why?

**Comment by aheejin** [comment] 2024-09-17 22:14
While I think this is an intended behavior, I'll reopen the issue while we are discussing this. (I thought @TerrorJack could reopen it as an author but apparently not)

**Comment by aheejin** [comment] 2024-09-19 18:11
Closing for now given that no discussion seems to be happening.

**Closed by aheejin** 2024-09-19 18:11 UTC
Labels: question, backend:WebAssembly
