### ISSUE TITLE
[RISCV][JIT] JIT session error: No HI20 PCREL relocation type be found for LO12 PCREL relocation type

### ISSUE THREAD

**Issue by andreas-schwab** [llvm/llvm-project#86515] opened 2024-03-25 15:32 UTC
$ xvfb-run -s '-screen 0 1600x1200x16 -ac +extension GLX +render -noreset' ctest -R QtDataVisualization_datavisualization_test -VV
UpdateCTestConfiguration  from :/home/abuild/rpmbuild/BUILD/pyside-setup-opensource-src-5.15.12/build/sources/pyside2/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/abuild/rpmbuild/BUILD/pyside-setup-opensource-src-5.15.12/build/sources/pyside2/DartConfiguration.tcl
Test project /home/abuild/rpmbuild/BUILD/pyside-setup-opensource-src-5.15.12/build/sources/pyside2
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 455
    Start 455: QtDataVisualization_datavisualization_test

455: Test command: /usr/bin/python3 "/home/abuild/rpmbuild/BUILD/pyside-setup-opensource-src-5.15.12/sources/pyside2/tests/QtDataVisualization/datavisualization_test.py"
455: Working Directory: /home/abuild/rpmbuild/BUILD/pyside-setup-opensource-src-5.15.12/build/sources/pyside2/tests/QtDataVisualization
455: Environment variables: 
455:  BUILD_DIR=/home/abuild/rpmbuild/BUILD/pyside-setup-opensource-src-5.15.12
455:  QT_DIR=/usr
455:  PYSIDE_DISABLE_INTERNAL_QT_CONF=1
455:  QT_NO_GLIB=1
455: Test timeout computed to be: 60
455: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abuild'
455: .JIT session error: No HI20 PCREL relocation type be found for LO12 PCREL relocation type
455: Failed to materialize symbols: { (fs173_variant1_5, { fs_variant_whole, fs_variant_partial }) }
1/1 Test #455: QtDataVisualization_datavisualization_test ...***Failed   15.56 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  15.88 sec

The following tests FAILED:
        455 - QtDataVisualization_datavisualization_test (Failed)
Errors while running CTest

**Comment by jrtc27** [comment] 2024-09-02 17:32
Perhaps this is fixed by https://github.com/llvm/llvm-project/commit/78f39dc70c1feaea5130b90ea3fb7b3ddd62446b?

**Comment by andreas-schwab** [comment] 2024-09-02 18:10
No, I have already cherry picked that commit since without it llvm18 is
unusable.

**Comment by jrtc27** [comment] 2024-09-02 23:27
Given the motivation for that commit, my guess would be that you're hitting another problem with edges not ordered by offset: relaxation iterates over edges in the order they were added, not the offset in the file. LLD is careful to sort (via llvm:stable_sort, to preserve the order for a given offset) the relocations before processing them for RISC-V.

I also note that the code that squashes R_RISCV_RELAX into the to-be-relaxed relocation assumes it refers to the previous one seen, which should be true in practice, but there are no assertions that the previous relocation has the same offset as it. I think it would be perfectly valid to interleave relocations in the input file so long as, when you filter for relocations for a given offset, that subset is in the right order.

IMO it would be best to leave R_RISCV_RELAX as-is when doing the initial scan through the ELF file, stable sort the edges and then do whatever squashing JITLink wants to do (though I might suggest *not* squashing, so as to keep the code closer to LLD...).

**Comment by jrtc27** [comment] 2024-09-03 00:05
Something like the following (only compile-tested) might resolve the issue if it is that:

```diff
diff --git a/llvm/include/llvm/ExecutionEngine/JITLink/riscv.h b/llvm/include/llvm/ExecutionEngine/JITLink/riscv.h
index a31f7d73b099..f10ebcac49fb 100644
--- a/llvm/include/llvm/ExecutionEngine/JITLink/riscv.h
+++ b/llvm/include/llvm/ExecutionEngine/JITLink/riscv.h
@@ -203,6 +203,8 @@ enum EdgeKind_riscv : Edge::Kind {
   ///   Fixup <- (Target - Fixup + Addend)
   R_RISCV_32_PCREL,
 
+  R_RISCV_RELAX,
+
   /// An auipc/jalr pair eligible for linker relaxation.
   ///
   /// Linker relaxation will replace this with R_RISCV_RVC_JUMP or R_RISCV_JAL
diff --git a/llvm/lib/ExecutionEngine/JITLink/ELF_riscv.cpp b/llvm/lib/ExecutionEngine/JITLink/ELF_riscv.cpp
index 0cf548ede938..d9b4edec7bc1 100644
--- a/llvm/lib/ExecutionEngine/JITLink/ELF_riscv.cpp
+++ b/llvm/lib/ExecutionEngine/JITLink/ELF_riscv.cpp
@@ -871,6 +871,17 @@ private:
                                                   &Self::addSingleRelocation))
         return Err;
 
+    for (auto &I : Base::GraphBlocks) {
+      auto &Block = *I.getSecond();
+      llvm::stable_sort(Block.edges(),
+                        [](const Edge &A, const Edge &B) {
+                          return A.getOffset() < B.getOffset();
+                        });
+
+      if (Error Err = squashRelaxRelocations(Block))
+        return Err;
+    }
+
     return Error::success();
   }
 
@@ -882,18 +893,6 @@ private:
     uint32_t Type = Rel.getType(false);
     int64_t Addend = Rel.r_addend;
 
-    if (Type == ELF::R_RISCV_RELAX) {
-      if (BlockToFix.edges_empty())
-        return make_error<StringError>(
-            "R_RISCV_RELAX without preceding relocation",
-            inconvertibleErrorCode());
-
-      auto &PrevEdge = *std::prev(BlockToFix.edges().end());
-      auto Kind = static_cast<EdgeKind_riscv>(PrevEdge.getKind());
-      PrevEdge.setKind(getRelaxableRelocationKind(Kind));
-      return Error::success();
-    }
-
     Expected<riscv::EdgeKind_riscv> Kind = getRelocationKind(Type);
     if (!Kind)
       return Kind.takeError();
@@ -925,6 +924,31 @@ private:
     return Error::success();
   }
 
+  Error squashRelaxRelocations(Block &BlockToFix) {
+    for (auto Edge = BlockToFix.edges().begin(); Edge != BlockToFix.edges().end();) {
+      if (Edge->getKind() == R_RISCV_RELAX) {
+        if (Edge == BlockToFix.edges().begin())
+          return make_error<StringError>(
+              "R_RISCV_RELAX without preceding relocation",
+              inconvertibleErrorCode());
+
+        auto &PrevEdge = *std::prev(Edge);
+        if (PrevEdge.getOffset() != Edge->getOffset())
+          return make_error<StringError>(
+              "R_RISCV_RELAX without preceding relocation",
+              inconvertibleErrorCode());
+
+        auto Kind = static_cast<EdgeKind_riscv>(PrevEdge.getKind());
+        PrevEdge.setKind(getRelaxableRelocationKind(Kind));
+        Edge = BlockToFix.removeEdge(Edge);
+      } else {
+        ++Edge;
+      }
+    }
+
+    return Error::success();
+  }
+
 public:
   ELFLinkGraphBuilder_riscv(StringRef FileName,
                             const object::ELFFile<ELFT> &Obj, Triple TT,
```

**Comment by andreas-schwab** [comment] 2024-09-04 19:57
WARNING:  error during JITing: Unsupported riscv relocation:51: R_RISCV_RELAX

**Comment by jrtc27** [comment] 2024-09-04 20:09
Uh right, getRelocationKind needs to know how to map it, and applyFixup should probably assert it was dealt with already. Patch updated.

**Comment by lhames** [comment] 2024-09-05 00:31
> +    case R_RISCV_RELAX:
> +      return make_error<JITLinkError>("Unsquashed R_RISCV_RELAX");

I think it's reasonable to assert that the linker has dealt with all `R_RISCV_RELAX` edges prior to `applyFixups`, but otherwise this looks good to me. :)

**Comment by andreas-schwab** [comment] 2024-09-08 08:18
WARNING:  error during JITing: In graph pg-jitted-objectbuffer, section .text: relocation target "CurrentMemoryContext" at address 0x555555e84b00 is out of range of R_RISCV_PCREL_HI20 fixup at 0x7f68669e61e4 (evalexpr_0_0, 0x7f68669e6000 + 0x1e4)

**Comment by jrtc27** [comment] 2024-09-08 16:36
That’s with using PIC to work around the lack of a large code model, per #106203?

**Comment by andreas-schwab** [comment] 2024-09-08 16:43
Yes.

**Comment by andreas-schwab** [comment] 2024-09-08 16:49
Looks like I have mixed up the two issues here.  My previous comments were
actually related to #106203.

**Comment by aurel32** [comment] 2024-09-08 21:12
@andreas-schwab Could you please describe the way to reproduce the problem and the version of mesa and llvm you are using?

At least in debian, backporting 3d67cf681a728e4cf0ab9947c0dd07539dda8b74 and 3d67cf681a728e4cf0ab9947c0dd07539dda8b74 seems to be enough to get the pyside2 5.15.14 the QtDataVisualization_datavisualization_test to pass. Most of the pyside2 testsuite passes, except a few tests related to javascript.

This is using mesa 24.2.2 and llvm 18.1.8 with the above patches.

**Closed** 2024-09-09 08:09 UTC
Labels: backend:RISC-V, orcjit
