### ISSUE TITLE
[clang-format] Regression in continuation indent if `AlignConsecutiveAssignments: Consecutive`

### ISSUE THREAD

**Issue by 8bf6271d-b3a8-49e2-8eef-b3a7232cec42** [llvm/llvm-project#50527] opened 2021-07-23 15:56 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51183](https://llvm.org/bz51183) |
| Version | trunk |
| OS | Windows NT |
| CC | @mydeveloperday |

## Extended Description 
There is regression after the fix 
[clang-format] Fix aligning with linebreaks
c5243c63cda3c740d6e9c7e501f6518c21688da3:

if

   AlignConsecutiveAssignments: Consecutive

Additional two spaces before `=` were added to indentation while formatting

```
void SomeFunc()
{
    using DcgmNs::Timelib::FromLegacyTimestamp;
    using DcgmNs::Timelib::ToLegacyTimestamp;
    using DcgmNs::Utils::GetMaxAge;
    using namespace std::chrono;
    // check the continuation indent: 6 instead of 4
    newWatcher.maxAgeUsec   = ToLegacyTimestamp(GetMaxAge(
          FromLegacyTimestamp<milliseconds>(monitorFrequencyUsec), seconds(std::uint64_t(maxSampleAge)), maxKeepSamples));
    newWatcher.isSubscribed = subscribeForUpdates ? 1 : 0;
}
```

Here is original problem with attachments
CPP-25899 CLion formatting does not match what clang-format produces
https://youtrack.jetbrains.com/issue/CPP-25899

**Comment by mkurdej** [comment] 2022-01-27 21:22
I cannot reproduce this issue.
I tested current main, older main from about 10th January, and release 13.
@mydeveloperday, I remember having seen this problem before, do you happen to know if there was an intended fix for it or it was fixed by chance?
I'm not closing yet as I'd like to understand the underlying problem and add a test case.

**Comment by mkurdej** [comment] 2022-01-28 17:04
Found! This was fixed in https://github.com/llvm/llvm-project/commit/75f6a795.

**Closed by mkurdej** 2022-01-28 17:04 UTC
Labels: clang-format, bugzilla
