### ISSUE TITLE
llvmbot still tells people to submit to Phab

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#73400] opened 2023-11-25 20:00 UTC
See the message attached to #73399 

> 6) Submit the patch to [Phabricator](https://reviews.llvm.org/).
>    6.1) Detailed instructions can be found [here](https://llvm.org/docs/Phabricator.html#requesting-a-review-via-the-web-interface)

**Comment by SimplyDanny** [comment] 2023-11-25 20:49
This has already been addressed in #65914 awaiting review. Perhaps you can jump in for cross checking.

**Comment by JOE1994** [comment] 2023-11-25 21:17
Closing as duplicate of #65890

**Closed by JOE1994** 2023-11-25 21:17 UTC
Labels: duplicate, infrastructure, github-prs
