### ISSUE TITLE
Why GCC can optimize call strcmp , but Clang does not ?

### ISSUE THREAD

**Issue by raidenluikang** [llvm/llvm-project#60976] opened 2023-02-24 16:27 UTC
See result of https://godbolt.org/z/114scaYs1
```cpp
#include <string.h>
#include <stdio.h>

 int parse(const char* ptr)
{
    if ( ::strcmp(ptr, "s"))
        return 42;

    if ( ::strcmp(ptr, "ms"))
        return 420;
    
    if  ( ::strcmp(ptr, "ns"))
        return 12;

    if ( ::strcmp(ptr, "us"))
        return 45;

    if ( ::strcmp(ptr, "m"))
        return 0;

    if  (::strcmp(ptr, "h"))
        return 5;

    return -1;
}

int main()
{
    int i = parse("s");

    return i;
}

```

GCC produced assembler code doesn't have call `strcmp`, but Clang call `strcmp` every time.

Why Clang can't optimize call `strcmp` with compile time string literal?

**Comment by firewave** [comment] 2023-02-24 19:17
Most likely a duplicate of #58003.

**Comment by nikic** [comment] 2023-02-24 21:06
Right, closing as a duplicate. As to "why", this fold requires changing the CFG, so it doesn't fit into the place that simplifies all the other libcalls, and so nobody has implemented this yet...

**Closed by nikic** 2023-02-24 21:06 UTC
Labels: llvm:optimizations
