### ISSUE TITLE
Clang++ doesn't always add complete information for a class

### ISSUE THREAD

**Issue by billionai** [llvm/llvm-project#58143] opened 2022-10-04 13:11 UTC
Consider the following code:

```c++
class A {
public:
    A() : member_(0) {};
    int member_;
};

class B : public A {};

int main(){
    B *test;
    return 0;
}
```

Because we only declare a pointer to B, clang++ only adds the following DWARF information for the type:

```
 <1><47>: Abbrev Number: 6 (DW_TAG_class_type)
    <48>   DW_AT_name        : (indexed string: 0x6): B
    <49>   DW_AT_declaration : 1
```

Despite having complete information about the type. Contrast with the result if we have declared `B test` instead:

```
<0><2b>: Abbrev Number: 2 (DW_TAG_class_type)
    <2c>   DW_AT_calling_convention: 5  (pass by value)
    <2d>   DW_AT_name        : (indexed string: 0x6): B
    <2e>   DW_AT_byte_size   : 4
    <2f>   DW_AT_decl_file   : 0
    <30>   DW_AT_decl_line   : 7
 <1><31>: Abbrev Number: 3 (DW_TAG_inheritance)
    <32>   DW_AT_type        : <0x42>
    <36>   DW_AT_data_member_location: 0
    <37>   DW_AT_accessibility: 1       (public)
 <1><38>: Abbrev Number: 4 (DW_TAG_subprogram)
    <39>   DW_AT_name        : (indexed string: 0x6): B
    <3a>   DW_AT_declaration : 1
    <3a>   DW_AT_artificial  : 1
    <3a>   DW_AT_external    : 1
    <3a>   DW_AT_accessibility: 1       (public)
 <2><3b>: Abbrev Number: 5 (DW_TAG_formal_parameter)
    <3c>   DW_AT_type        : <0x82>
    <40>   DW_AT_artificial  : 1
 <2><40>: Abbrev Number: 0
 <1><41>: Abbrev Number: 0
```

This is a problem because GDB is unable to properly print the type or values of `test`, along with making it impossible to call on functions that take an A parameter with a *B variable, since we can't figure out the relationship between the two classes.

**Comment by pogo59** [comment] 2022-10-04 13:28
By default clang emits a full description of B only in the compilation units where a B instance is actually constructed, as a tactic to reduce the size of debug-info.  The idea is that debuggers will be able to find the full description in that (other) unit, and make use of it.
There are some known situations where this doesn't work out, e.g. if the B instances are constructed in a factory that isn't compiled with debug info (perhaps in a library).  Is that your situation?

**Comment by pogo59** [comment] 2022-10-04 14:48
>  is there a way to add a CLI option that would ignore these debug-info reduction strategies? 

Sorry, should have thought to add that in my first reply.
It looks like you could try `-fno-eliminate-unused-debug-types` to get the effect you want.  We used to have a mode called "limited" but I'm not seeing a way to ask for that anymore.

**Comment by jmorse** [comment] 2022-10-04 14:52
I believe `-Xclang -fno-use-ctor-homing` will turn constructor homing off -- however it's not technically a "supported" flag. Relevant discussion: https://discourse.llvm.org/t/keeping-vtable-homing-for-debug-info-type-generation/63732

**Comment by dwblaikie** [comment] 2022-10-04 15:23
So type homing is done in Clang with 4 things:
* If a type is never required to be complete (sounds like this example) then a declaration is emitted (eg: if you never dereference a pointer)
* If a class template implicit specialization is the subject of an explicit instantiation declaration then a declaration is emitted and the definition is emitted wherever the explicit instantiation definition apears
* If a class is dynamic (has a vtable) then the definition is emitted if and only if the vtable is emitted (so vtable homing strategies like the key function optimization are leveraged for debug info homing)
* If a class has all non-trivial ctors then the type is emitted if and only if one of those ctors is emitted.

GCC does the case 3, but not case 1, 2, and 4.

You can disable all 4 in Clang with `-fstandalone-debug` (the name refers to the idea that if you're compiling just one source file with debug info and the rest of your program without debug info, you want this one file's debug info to be "standalone" and not depend on assumptions about what might be present in other compilations linked into the program).

Clang and GCC support `-fno-eliminate-unused-debug-types` which goes a step further - and includes even entirely unreferenced types, this was added for some Linux kernel use cases.

I've run the GDB test suite with `-fstandalone-debug` before & it's generally usable, though if you happen to have any weight in the GDB community, I think it'd be appropriate to fix the GDB test suite to not rely on these sort of optimizations/workarounds (clearly they work with GCC's default that includes vtable homing, which has the same general justification as Clang's homing strategies (that the whole program is built with debug info) so I don't see any reason the tests shouldn't be more resilient to such assumptions), but I had limited success trying to explain this to GDB folks and upstream patches to fix these assumptions in the test suite.

**Comment by dwblaikie** [comment] 2022-10-04 15:26
> This is a problem because GDB is unable to properly print the type or values of test, along with making it impossible to call on functions that take an A parameter with a *B variable, since we can't figure out the relationship between the two classes.

Though, as an aside - could you clarify more about what you mean by these two things (show the GDB log/behavior explicitly)? if `test` is uninitialized, it's certainly UB to dereference it - so I'm not sure what function calling could be done, or what printing of the object could be done (since there is no `B` object in the program). (and/or could you point to which GDB test hit this)

But, yeah, I've certainly seen GDB tests that did rely on non-homing of types in certain cases (usually for pointers that were never dereferenced).

**Comment by billionai** [comment] 2022-10-04 16:52
pogo59, jmorse, thanks for those options, however I was hoping for something more general so I could add to the flags whenever we used clang, so those unfortunately don't really fix my problem. 

dwblaikie, thanks for your explanation. I'll look over `-fstandalone-debug` and the general type homing concepts, and take it from there. I hope this fixes my future problems! :)

> Though, as an aside - could you clarify more about what you mean by these two things (show the GDB log/behavior explicitly)? if test is uninitialized, it's certainly UB to dereference it - so I'm not sure what function calling could be done, or what printing of the object could be done (since there is no B object in the program). (and/or could you point to which GDB test hit this)

Sure! The test in question is gdb.cp/converts.exp, attempting to print foo1_4(bp) and failing to find the correct overload. The function in question is simply `int foo1_4(A* a) { return 14;}` and the point of the test is confirming that GDB can deduce the correct function call through inheritance.

I am planning on proposing to GDB that we side-step this issue by allocating a B object, so this specific case is an easy fix.

**Comment by dwblaikie** [comment] 2022-10-04 19:50
> dwblaikie, thanks for your explanation. I'll look over `-fstandalone-debug` and the general type homing concepts, and take it from there. I hope this fixes my future problems! :)
> 
> > Though, as an aside - could you clarify more about what you mean by these two things (show the GDB log/behavior explicitly)? if test is uninitialized, it's certainly UB to dereference it - so I'm not sure what function calling could be done, or what printing of the object could be done (since there is no B object in the program). (and/or could you point to which GDB test hit this)
> 
> Sure! The test in question is gdb.cp/converts.exp, attempting to print foo1_4(bp) and failing to find the correct overload. The function in question is simply `int foo1_4(A* a) { return 14;}` and the point of the test is confirming that GDB can deduce the correct function call through inheritance.

Ah, makes sense.

> I am planning on proposing to GDB that we side-step this issue by allocating a B object, so this specific case is an easy fix.

Awesome - thanks!

**Comment by dwblaikie** [comment] 2022-10-04 19:50
(just for posterity, here's a link to the test in the gdb test suite: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/testsuite/gdb.cp/converts.cc;h=ecf806481fdffc6abb19180fa200a9b5b433494c;hb=HEAD )

**Comment by dwblaikie** [comment] 2022-10-10 17:34
Closing this as by design - but always happy to discuss the details further.

**Closed** 2022-10-10 17:34 UTC
Labels: debuginfo
