### ISSUE TITLE
free(): corrupted unsorted chunks when compiling RPCS3's cache_utils.cpp

### ISSUE THREAD

**Issue by NetSysFire** [llvm/llvm-project#60134] opened 2023-01-19 00:30 UTC
Reporting this because the output tells me to.

```console
[ 75%] Building CXX object 3rdparty/llvm_build/lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86InsertWait.cpp.o
[ 75%] Linking CXX static library ../../libLLVMX86CodeGen.a
[ 75%] Built target LLVMX86CodeGen
[ 75%] Building CXX object 3rdparty/llvm_build/lib/Target/X86/AsmParser/CMakeFiles/LLVMX86AsmParser.dir/X86AsmParser.cpp.o
[ 75%] Linking CXX static library ../../../libLLVMX86AsmParser.a
[ 75%] Built target LLVMX86AsmParser
[ 75%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o
free(): corrupted unsorted chunks
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++ -DDATADIR=\"/usr/share/rpcs3\" -DGLX_GLXEXT_PROTOTYPES -DGL_GLEXT_PROTOTYPES -DHAVE_FAUDIO -DHAVE_LIBEVDEV -DHAVE_VULKAN -DHAVE_X11 -DLLVM_AVAILABLE -DSOUNDTOUCH_ALLOW_SSE -DSOUNDTOUCH_FLOAT_SAMPLES -DST_NO_EXCEPTION_HANDLING -DUSE_MULTICH_ALWAYS -DVK_USE_PLATFORM_WAYLAND_KHR -DWC_NO_HARDEN -I/home/user/rpcs3-git/src/rpcs3/rpcs3 -I/home/user/rpcs3-git/src/rpcs3 -I/home/user/rpcs3-git/src/rpcs3/3rdparty/yaml-cpp/yaml-cpp/include -I/home/user/rpcs3-git/src/rpcs3/3rdparty/flatbuffers/include -I/home/user/rpcs3-git/src/rpcs3/3rdparty/FAudio/src -I/home/user/rpcs3-git/src/rpcs3/3rdparty/FAudio/include -I/usr/include/AL -I/home/user/rpcs3-git/src/rpcs3/3rdparty/cubeb/cubeb/include -I/home/user/rpcs3-git/src/build/exports -I/home/user/rpcs3-git/src/rpcs3/3rdparty/SoundTouch/soundtouch/include -I/home/user/rpcs3-git/src/rpcs3/3rdparty/stblib/include -I/home/user/rpcs3-git/src/rpcs3/llvm/include -I/home/user/rpcs3-git/src/build/3rdparty/llvm_build/include -I/home/user/rpcs3-git/src/rpcs3/3rdparty/asmjit/asmjit/src -I/home/user/rpcs3-git/src/rpcs3/3rdparty/GL -I/home/user/rpcs3-git/src/rpcs3/3rdparty/glslang/glslang/SPIRV/.. -I/home/user/rpcs3-git/src/build/include -I/home/user/rpcs3-git/src/rpcs3/3rdparty/SPIRV/SPIRV-Tools/include -I/home/user/rpcs3-git/src/rpcs3/3rdparty/SPIRV/SPIRV-Headers/include -I/home/user/rpcs3-git/src/rpcs3/3rdparty/libusb/libusb/libusb -I/home/user/rpcs3-git/src/rpcs3/3rdparty/wolfssl/wolfssl -I/home/user/rpcs3-git/src/build/3rdparty/wolfssl/wolfssl -I/home/user/rpcs3-git/src/rpcs3/3rdparty/xxHash/cmake_unofficial/.. -I/home/user/rpcs3-git/src/rpcs3/3rdparty/xxHash -isystem /usr/include/libevdev-1.0 -isystem /usr/include/SDL2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wl,--exclude-libs,ALL -O3 -DNDEBUG -pthread -Wall -fno-exceptions -fstack-protector -msse -msse2 -mcx16 -Werror=old-style-cast -Werror=sign-compare -Werror=reorder -Werror=return-type -Werror=overloaded-virtual -Werror=missing-noreturn -Wunused-parameter -Wignored-qualifiers -Wredundant-move -Wcast-qual -Wdeprecated-copy -Wtautological-compare -Wempty-body -Wredundant-decls -Wstrict-aliasing=1 -Werror=inconsistent-missing-override -fconstexpr-steps=16777216 -Wno-unused-lambda-capture -Wno-unused-private-field -Wno-delete-non-virtual-dtor -Wno-unused-command-line-argument -std=gnu++20 -MD -MT rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o -MF CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o.d -o CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o -c /home/user/rpcs3-git/src/rpcs3/rpcs3/Emu/cache_utils.cpp
1.	<eof> parser at end of file
 #0 0x00007fdcc397c48a (/usr/lib/libLLVM-15.so+0xd7c48a)
 #1 0x00007fdcc3979b1f llvm::sys::RunSignalHandlers() (/usr/lib/libLLVM-15.so+0xd79b1f)
 #2 0x00007fdcc385c5e9 (/usr/lib/libLLVM-15.so+0xc5c5e9)
 #3 0x00007fdccd7889e0 (/usr/lib/libc.so.6+0x389e0)
 #4 0x00007fdccd7d864c (/usr/lib/libc.so.6+0x8864c)
 #5 0x00007fdccd788938 raise (/usr/lib/libc.so.6+0x38938)
 #6 0x00007fdccd77253d abort (/usr/lib/libc.so.6+0x2253d)
 #7 0x00007fdccd7cc7ee (/usr/lib/libc.so.6+0x7c7ee)
 #8 0x00007fdccd7e23dc (/usr/lib/libc.so.6+0x923dc)
 #9 0x00007fdccd7e459c (/usr/lib/libc.so.6+0x9459c)
#10 0x00007fdccd7e6ba3 cfree (/usr/lib/libc.so.6+0x96ba3)
#11 0x00007fdccb79e0e0 clang::Sema::PopExpressionEvaluationContext() (/usr/lib/libclang-cpp.so.15+0x119e0e0)
#12 0x00007fdccae49175 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/libclang-cpp.so.15+0x849175)
#13 0x00007fdccc4e7479 clang::FrontendAction::Execute() (/usr/lib/libclang-cpp.so.15+0x1ee7479)
#14 0x00007fdccc48d14f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.15+0x1e8d14f)
#15 0x00007fdccc55209a clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/libclang-cpp.so.15+0x1f5209a)
#16 0x000055f0a5d664d0 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang+++0x104d0)
#17 0x000055f0a5d6c197 (/usr/bin/clang+++0x16197)
#18 0x00007fdccc1d5959 (/usr/lib/libclang-cpp.so.15+0x1bd5959)
#19 0x00007fdcc385c6b7 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/libLLVM-15.so+0xc5c6b7)
#20 0x00007fdccc1db48f (/usr/lib/libclang-cpp.so.15+0x1bdb48f)
#21 0x00007fdccc19ebbe clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/libclang-cpp.so.15+0x1b9ebbe)
#22 0x00007fdccc19ef7d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/lib/libclang-cpp.so.15+0x1b9ef7d)
#23 0x00007fdccc1f815c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/lib/libclang-cpp.so.15+0x1bf815c)
#24 0x000055f0a5d6e7f9 clang_main(int, char**) (/usr/bin/clang+++0x187f9)
#25 0x00007fdccd773290 (/usr/lib/libc.so.6+0x23290)
#26 0x00007fdccd77334a __libc_start_main (/usr/lib/libc.so.6+0x2334a)
#27 0x000055f0a5d62d25 _start (/usr/bin/clang+++0xcd25)
clang-15: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-15: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /tmp/cache_utils-c0a412.cpp
clang-15: note: diagnostic msg: /tmp/cache_utils-c0a412.sh
clang-15: note: diagnostic msg:

********************
make[2]: *** [rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/build.make:76: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:23368: rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

Files renamed (should not matter because they are plaintext anyways) because GitHub does not like `.cpp` or `.sh`.

[cache_utils-c0a412.sh.txt](https://github.com/llvm/llvm-project/files/10452277/cache_utils-c0a412.sh.txt)
[cache_utils-c0a412.cpp.txt](https://github.com/llvm/llvm-project/files/10452278/cache_utils-c0a412.cpp.txt)

Environment:

Arch Linux, freshly upgraded.
Compiles fine with GCC.
PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rpcs3-git plus `export CC=clang; export CXX=clang++`

Tried to search for "corrupted unsorted chunks" in the existing issues, but did not find anything, so I hope this is not a duplicate.

**Comment by royjacobson** [comment] 2023-01-30 19:58
Seems like a duplicate of #58207

**Closed by royjacobson** 2023-01-30 19:58 UTC
Labels: clang:frontend, crash
