### ISSUE TITLE
wrong code at -O1 and above on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#49842] opened 2021-05-26 20:42 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [50498](https://llvm.org/bz50498) |
| Version | trunk |
| OS | All |

## Extended Description 
[507] % clangtk -v
clang version 13.0.0 (https://github.com/llvm/llvm-project.git 5dd86aadf0b014913bd35bb7435808eb081bc049)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
[508] % 
[508] % clangtk -O0 small.c; ./a.out
[509] % 
[509] % clangtk -O1 small.c
[510] % ./a.out
Aborted
[511] % 
[511] % cat small.c
```
int a;
int main() {
  int b;
 L:
  b = a;
  if (a >= 0) {
    int c;
    if ((!a) <= 0)
      goto L;
    a = -1;
  }
  if (b != 0)
    __builtin_abort ();
  return 0;
}
```

**Comment by fhahn** [comment] 2022-03-16 20:06
I am unable to reproduce this on current main. I'll close the issue, but please re-open it again with additional info if it still reproduces on your side.

**Closed by fhahn** 2022-03-16 20:06 UTC
Labels: bugzilla
