### ISSUE TITLE
[Modules] Can't call imported template with local type

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#56715] opened 2022-07-25 22:58 UTC
Commands:
```bash
CXX=clang++
echo "export module m1;
export constexpr int f(auto) { return 0; }
" > m1.cpp
echo "export module m2;
import m1;
constexpr int zero() {
  struct x { };
  return f(x{});
}
static_assert(zero() == 0);
" > m2.cpp
$CXX   -stdlib=libc++ -pedantic -Wall -Wextra -Wconversion -Werror=missing-field-initializers -O3 -DNDEBUG -fmodules -fbuiltin-module-map -std=c++2b -MD -MT m1.cpp.o -MF m1.cpp.o.d -o m1.cpp.o -c m1.cpp
$CXX   -stdlib=libc++ -pedantic -Wall -Wextra -Wconversion -Werror=missing-field-initializers -O3 -DNDEBUG -fmodules -fbuiltin-module-map -std=c++2b -MD -MT m1.pcm -MF m1.pcm.d -o m1.pcm -c m1.cpp -Xclang -emit-module-interface
$CXX   -stdlib=libc++ -pedantic -Wall -Wextra -Wconversion -Werror=missing-field-initializers -O3 -DNDEBUG -fmodules -fbuiltin-module-map -fprebuilt-module-path=. -std=c++2b -MD -MT m2.cpp.o -MF m2.cpp.o.d -o m2.cpp.o -c m2.cpp
```

Output:
```console
m2.cpp:5:10: error: no matching function for call to 'f'
  return f(x{});
         ^
m2.cpp:7:15: error: static assertion expression is not an integral constant expression
static_assert(zero() == 0);
              ^~~~~~~~~~~
```

**Comment by JohelEGP** [comment] 2022-07-25 23:14
Notably, it also fails for closure types. This worked with the build of 2 weeks ago.

**Comment by ChuanqiXu9** [comment] 2022-08-18 08:06
@JohelEGP 
I can't reproduce this by:
```
clang++ -std=c++20 --precompile m1.cppm -o m1.pcm
clang++ -std=c++20 --precompile m2.cppm -fmodule-file=m1.pcm -o m2.pcm
```

I rename m1.cpp and m2.cpp to m1.cppm and m2.cppm and I removed ` -fmodules -fbuiltin-module-map` part. `module-map` is not C++20 standard feature.

**Comment by JohelEGP** [comment] 2022-08-18 15:27
So is https://clang.llvm.org/docs/Modules.html an extension? Where are C++ modules documented?

**Comment by ChuanqiXu9** [comment] 2022-08-18 15:41
> So is https://clang.llvm.org/docs/Modules.html an extension?

Yes.

> Where are C++ modules documented?

It is being reviewed at https://reviews.llvm.org/D131388.

**Comment by JohelEGP** [comment] 2022-08-18 15:47
I see. So [all my modules bugs](https://github.com/llvm/llvm-project/issues?q=is%3Aopen+is%3Aissue+author%3AJohelEGP+label%3Aclang%3Amodules) were actually for Clang modules. It's great that it works with C++ modules. I'll work out switching to C++ modules, then.

**Comment by ChuanqiXu9** [comment] 2022-08-18 16:02
> 

Yeah, I'm working on that too. https://github.com/alibaba/async_simple/tree/CXX20Modules This is switching result for a library which consists of thousands lines of code. It could be compiled by clang15 or later. Hope this helps.

(I'll close the issue if you agree this is not an issue)

**Comment by ChuanqiXu9** [comment] 2022-08-18 16:12
Oh, maybe I misunderstand you. If you are saying you'll switch bug reports to c++20 modules instead of switching a project?

**Comment by JohelEGP** [comment] 2022-08-18 16:20
> Oh, maybe I misunderstand you. If you are saying you'll switch bug reports to c++20 modules instead of switching a project?

For now, I'll update the Clang commands in my [CMake module for C++ modules](https://github.com/JohelEGP/jegp.cmake_modules/#jegpaddmodule) to produce C++ modules rather than Clang modules. Then I'll see how that works for my C++ projects.

> (I'll close the issue if you agree this is not an issue)

Well, it _is_ an issue for Clang modules. So I'm not sure if it should be closed. I'm equally unsure if it's mislabeled with `clang:modules`.

> Yeah, I'm working on that too. https://github.com/alibaba/async_simple/tree/CXX20Modules This is switching result for a library which consists of thousands lines of code. It could be compiled by clang15 or later. Hope this helps.

Thank you. Seems like it'll help, indeed.

**Comment by ChuanqiXu9** [comment] 2022-08-18 16:34
> > Oh, maybe I misunderstand you. If you are saying you'll switch bug reports to c++20 modules instead of switching a project?
> 
> For now, I'll update the Clang commands in my [CMake module for C++ modules](https://github.com/JohelEGP/jegp.cmake_modules/#jegpaddmodule) to produce C++ modules rather than Clang modules. Then I'll see how that works for my C++ projects.

Oh, CMake for C++20 Modules! This is what I am looking for. As you can find in the link, it is painful to write Makefile for a project.

> 
> > (I'll close the issue if you agree this is not an issue)
> 
> Well, it _is_ an issue for Clang modules. So I'm not sure if it should be closed. I'm equally unsure if it's mislabeled with `clang:modules`.

OK. From the implementation side, clang modules and C++20 Modules in clang share a big part of codes. So currently the issues share one `clang:modules` tag. And from the design side, we **hope** the c++20 modules and clang modules could co_exist well since there are already many existing users for clang modules. But we are not sure if it is achievable or implementable. And **currently** I think the developers of clang modules and the developers c++20 modules don't have the time/motivation to see the co_use of clang modules and c++20 modules.

As a result, I agree it may be an issue. But I suggest **personally** to create a new issue for it since the log history might be a little bit confusing for others to track : )

**Comment by JohelEGP** [comment] 2022-08-18 16:39
In that case, this issue can be closed since it actually works with C++ modules.

**Closed** 2022-08-19 02:05 UTC
Labels: clang:modules
