### ISSUE TITLE
clang-tidy misc-const-correctness has performance issues with std::format

### ISSUE THREAD

**Issue by cedric-ca** [llvm/llvm-project#63308] opened 2023-06-14 15:50 UTC
Hi,

We encounter performance issues with Clang-Tidy `misc-const-correctness` when we introduced `std::format`.
I tried LLVM 16.0.0, 16.0.3 and 16.0.6.

The file I tested has only one `std::format`:
```cpp
const double toto = 1.0;
std::string s = std::format("text I want = {}", toto);
vs 
std::string s = "text I want = " + std::to_string(toto);
```

[std_format_performance.txt](https://github.com/llvm/llvm-project/files/11747920/std_format_performance.txt)
[without_std_format_performance.txt](https://github.com/llvm/llvm-project/files/11747921/without_std_format_performance.txt)

Cédric

**Comment by PiotrZSL** [comment] 2023-06-14 18:47
Difference between those 2 runs is like 0.5s. When entire run takes 38s.
Check is slow, but that does not depend on std::format.

**Comment by PiotrZSL** [comment] 2023-06-14 19:21
Tested locally, there is no difference in performance between using std::format or not.
But there is difference when enabling C++20.
This makes this issue duplicate of #62337
Still this could could probably improve.

**Comment by cedric-ca** [comment] 2023-06-15 09:48
Thanks for your investigation.
Yes we use C++20 as std::format is available since C++20 not before.
I'm sorry because I send the bad result without std::format.
I made more investigation and discovered that including <format> adds 5s.
The difference between std::format and without is small.
You can close this issue as "works for me".
Try:
#include <iostream>
#include <string>
int main()
{
    const double d = 0.;
    const std::string s = "Hello World" + std::to_string(d);
    std::cout << s;
    return 1;
}
vs
#include <iostream>
#include <format>
#include <string>
int main()
{
    const double d = 0.;
    const std::string s = "Hello World" + std::to_string(d);
    std::cout << s;
    return 1;
}

**Closed** 2023-06-23 08:22 UTC
Labels: clang-tidy, performance, worksforme
