### ISSUE TITLE
Bad code gen for simple swap

### ISSUE THREAD

**Issue by philnik777** [llvm/llvm-project#59745] opened 2022-12-30 02:59 UTC
```c++
struct Pair {
  unsigned long long a;
  unsigned long long b;
};

void swap(Pair& lhs, Pair& rhs) {
  Pair tmp = lhs;
  lhs = rhs;
  rhs = tmp;
}
```
produces
```asm
swap(Pair&, Pair&):
        movdqu  xmm0, XMMWORD PTR [rdi]
        movdqu  xmm1, XMMWORD PTR [rsi]
        movups  XMMWORD PTR [rdi], xmm1
        movups  XMMWORD PTR [rsi], xmm0
        ret
```
with GCC and
```asm
swap(Pair&, Pair&):                       # @swap(Pair&, Pair&)
        movups  xmm0, xmmword ptr [rdi]
        movaps  xmmword ptr [rsp - 24], xmm0
        movups  xmm0, xmmword ptr [rsi]
        movups  xmmword ptr [rdi], xmm0
        movaps  xmm0, xmmword ptr [rsp - 24]
        movups  xmmword ptr [rsi], xmm0
        ret
```
with Clang ([Godbolt](https://godbolt.org/z/rKdG5hY9q)). I haven't benchmarked, but I can't imagine that storing the data on the stack and then loading it again is faster than using a second register.

For types with size <= 8 clang does the right thing AFAICT.

**Comment by LebedevRI** [comment] 2022-12-30 13:22
Duplicate of https://github.com/llvm/llvm-project/issues/59116

**Closed by LebedevRI** 2022-12-30 13:22 UTC
Labels: llvm:optimizations
