### ISSUE TITLE
[Clang Tidy]: Type(Value)  is treated as C style casting which is definitely wrong

### ISSUE THREAD

**Issue by CGQAQ** [llvm/llvm-project#63820] opened 2023-07-12 03:10 UTC
On line 339, `FullObjectSlot(&object_)` is treated as C-style casting.
On line 338, I changed the `Object(object_)` to `Object{object_}`, the warning disappeared

![image](https://github.com/llvm/llvm-project/assets/15936231/073285ac-0434-44f0-9f98-f088ba16bea8)

And I found the [rule](https://google.github.io/styleguide/cppguide.html#Casting:~:text=You%20may%20use%20cast%20formats%20like%20T(x)%20only%20when%20T%20is%20a%20class%20type), they explicitly allowed this

**Comment by chrchr-github** [comment] 2023-07-19 10:26
It's not obvious how to reproduce this: https://godbolt.org/z/9dv9f51rq

**Comment by PiotrZSL** [comment] 2023-11-08 07:31
Duplicate of #57959

**Closed by PiotrZSL** 2023-11-08 07:31 UTC
Labels: duplicate, clang-tidy
