### ISSUE TITLE
Templated constructor in derived class erroneously hides inherited base class constructor

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#62050] opened 2023-04-10 17:06 UTC
The following code compiles in GCC and MSVC, but not Clang:
```cpp
#include <type_traits>

template <typename T>
class Base {
 public:
  template <typename M, typename = std::enable_if_t<!std::is_same_v<M, int>>>
  Base(M&& m);
};

template <typename T>
class Derived : public Base<T> {
 public:
  using Base<T>::Base;

  /*template <typename M, typename = std::enable_if_t<!std::is_same_v<M, int>>>
  Derived(M&& m);*/

  template <typename U, typename = std::enable_if_t<std::is_same_v<U, int>>, typename = void>
  Derived(U&& value);
};

void foo() {
  Derived<int> d(0L);  // error: no matching constructor for initialization of 'Derived<int>'
}
```

(See https://godbolt.org/z/jMvT7rvM1)

If the commented-out constructor is uncommented, this works.

Possible dupe of https://github.com/llvm/llvm-project/issues/61988?

**Comment by shafik** [comment] 2023-04-11 01:01
I am not sure about this one CC @royjacobson @erichkeane

**Comment by zygoloid** [comment] 2023-04-11 18:24
This language rule changed relatively recently, I think in [P1787R6](http://wg21.link/p1787r6) -- previously the rule was that for *using-declaration* hiding purposes, we do not consider the template parameter list, and now [the rule is](https://eel.is/c++draft/namespace.udecl#11) that we use the [normal signature matching mechanism](https://eel.is/c++draft/basic.scope.scope#4). The change was made as a DR so should be applied retroactively.

This can probably be implemented by simply removing the `UseMemberUsingDeclRules` flag from `Sema::IsOverload`.

**Comment by zygoloid** [comment] 2023-04-17 02:33
This is a duplicate of #39581.

**Closed by zygoloid** 2023-04-17 02:33 UTC
Labels: clang:frontend
