### ISSUE TITLE
ICE in clang++

### ISSUE THREAD

**Issue by debeea86-b8ba-498d-b3f4-0f283c1a4546** [llvm/llvm-project#49045] opened 2021-03-23 16:05 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [49701](https://llvm.org/bz49701) |
| Version | trunk |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
clang++ -S clangerr6.C -w
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ -S clangerr6.C -w
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
 #&#8203;0 0x00001485b7984bf6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib64/libLLVM-12.so+0xc07bf6)
 #&#8203;1 0x00001485b7982ae4 llvm::sys::RunSignalHandlers() (/usr/lib64/libLLVM-12.so+0xc05ae4)
 #&#8203;2 0x00001485b78c2008 (/usr/lib64/libLLVM-12.so+0xb45008)
 #&#8203;3 0x00001485b69cc310 __restore_rt (/usr/lib64/libc.so.6+0x3d310)
 #&#8203;4 0x00001485bd2a9fe1 (/usr/lib64/libclang-cpp.so.12+0x976fe1)
 #&#8203;5 0x00001485be41558d (/usr/lib64/libclang-cpp.so.12+0x1ae258d)
 #&#8203;6 0x00001485be419e6d (/usr/lib64/libclang-cpp.so.12+0x1ae6e6d)
 #&#8203;7 0x00001485be41a12e (/usr/lib64/libclang-cpp.so.12+0x1ae712e)
 #&#8203;8 0x00001485be43270a clang::CodeGen::CodeGenModule::emitMultiVersionFunctions() (/usr/lib64/libclang-cpp.so.12+0x1aff70a)
 #&#8203;9 0x00001485be449144 clang::CodeGen::CodeGenModule::Release() (/usr/lib64/libclang-cpp.so.12+0x1b16144)
#&#8203;10 0x00001485be4ac16a (/usr/lib64/libclang-cpp.so.12+0x1b7916a)
#&#8203;11 0x00001485be40334c (/usr/lib64/libclang-cpp.so.12+0x1ad034c)
#&#8203;12 0x00001485bd341b49 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib64/libclang-cpp.so.12+0xa0eb49)
#&#8203;13 0x00001485bea869d9 clang::FrontendAction::Execute() (/usr/lib64/libclang-cpp.so.12+0x21539d9)
#&#8203;14 0x00001485bea2cd1b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib64/libclang-cpp.so.12+0x20f9d1b)
#&#8203;15 0x00001485beaf3e8b clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib64/libclang-cpp.so.12+0x21c0e8b)
#&#8203;16 0x00005627dbdbe7dc cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-12+0x167dc)
#&#8203;17 0x00005627dbdbb81a (/usr/bin/clang-12+0x1381a)
#&#8203;18 0x00001485be761ad9 (/usr/lib64/libclang-cpp.so.12+0x1e2ead9)
#&#8203;19 0x00001485b78c20d7 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib64/libLLVM-12.so+0xb450d7)
#&#8203;20 0x00001485be762816 (/usr/lib64/libclang-cpp.so.12+0x1e2f816)
#&#8203;21 0x00001485be73882b clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/lib64/libclang-cpp.so.12+0x1e0582b)
#&#8203;22 0x00001485be738fee clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/lib64/libclang-cpp.so.12+0x1e05fee)
#&#8203;23 0x00001485be742752 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib64/libclang-cpp.so.12+0x1e0f752)
#&#8203;24 0x00005627dbdb9417 main (/usr/bin/clang-12+0x11417)
#&#8203;25 0x00001485b69b6b75 __libc_start_main (/usr/lib64/libc.so.6+0x27b75)
#&#8203;26 0x00005627dbdbac2e _start (/usr/bin/clang-12+0x12c2e)
clang-12: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 12.0.0 (Fedora 12.0.0-0.1.rc1.fc34)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-12: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-12: note: diagnostic msg: /tmp/clangerr6-e032f3.cpp
clang-12: note: diagnostic msg: /tmp/clangerr6-e032f3.sh
clang-12: note: diagnostic msg: 

********************
[vitti cc]$cat /tmp/clangerr6-e032f3.cpp
# 1 "<built-in>"
# 1 "clangerr6.C"
int fum () __attribute__ ((target("default")));

int fum () __attribute__((target("arch=core2")));

int (*p)() = &fum;

[vitti cc]$cat /tmp/clangerr6-e032f3.sh
# Crash reproducer for clang version 12.0.0 (Fedora 12.0.0-0.1.rc1.fc34)
# Driver args: "--driver-mode=g++" "-S" "clangerr6.C" "-w"
# Original command:  "/usr/bin/clang-12" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-S" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "clangerr6.C" "-mrelocation-model" "static" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-resource-dir" "/usr/lib64/clang/12.0.0" "-internal-isystem" "/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++" "-internal-isystem" "/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/x86_64-redhat-linux" "-internal-isystem" "/usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/backward" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib64/clang/12.0.0/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-w" "-fdeprecated-macro" "-fdebug-compilation-dir" "/home/vitti/f95/cc" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-o" "clangerr6.s" "-x" "c++" "clangerr6.C"
 "/usr/bin/clang-12" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-S" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "clangerr6.C" "-mrelocation-model" "static" "-mframe-pointer=all" "-fmath-errno" "-fno-rounding-math" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-fno-split-dwarf-inlining" "-debugger-tuning=gdb" "-w" "-fdeprecated-macro" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-fcolor-diagnostics" "-faddrsig" "-x" "c++" "clangerr6-e032f3.cpp"

**Comment by wheatman** [comment] 2023-06-27 23:53
This reproduces on 12.0.0
Seems to be fixed on 14.0.0
https://godbolt.org/z/aWMKGcb6n

code to fix the formatting for reference

```
int fum () __attribute__ ((target("default")));

int fum () __attribute__((target("arch=core2")));

int (*p)() = &fum;

```

**Closed** 2023-06-27 23:55 UTC
Labels: c++, clang:codegen, bugzilla, crash
