### ISSUE TITLE
[MachineSched] Mistake to schedule memory load across memory store

### ISSUE THREAD

**Issue by phoebewang** [llvm/llvm-project#60744] opened 2023-02-14 14:48 UTC
It seems [D138899](https://reviews.llvm.org/D138899) exposed a machine scheduler issue. The memory of load and store is overlapped, but scheduler seems not aware of it.

The reproducer comes from [D138899](https://reviews.llvm.org/D138899)
```ll
source_filename = "../../chrome/browser/dom_distiller/dom_distiller_service_factory.cc"
target datalayout = "e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i686-unknown-linux-android24"

%0 = type { %1 }
%1 = type { %2 }
%2 = type { ptr }
%3 = type { %4 }
%4 = type { %5 }
%5 = type { ptr }
%6 = type { %7 }
%7 = type { %8 }
%8 = type { ptr }
%9 = type { %10 }
%10 = type { %11 }
%11 = type { ptr }

@g = external hidden unnamed_addr constant { [5 x ptr], [9 x ptr] }, align 4
@g2 = external hidden unnamed_addr constant { [5 x ptr] }, align 4

; Function Attrs: minsize nounwind null_pointer_is_valid optsize uwtable
define hidden void @f(ptr noundef align 4 dereferenceable_or_null(48) %0, ptr noundef byval(%0) align 4 %1, ptr noundef byval(%3) align 4 %2, ptr noundef byval(%6) align 4 %3, ptr noundef byval(%9) align 4 %4) unnamed_addr #0 align 2 {
  %6 = alloca %0, align 4
  %7 = alloca %3, align 4
  %8 = alloca %6, align 4
  %9 = alloca %9, align 4
  store ptr getelementptr inbounds ({ [5 x ptr] }, ptr @g2, i32 0, inrange i32 0, i32 2), ptr %0, align 4
  %10 = getelementptr inbounds i8, ptr %0, i32 4
  %11 = load ptr, ptr %1, align 4
  store ptr null, ptr %1, align 4
  store ptr %11, ptr %6, align 4
  %12 = load ptr, ptr %2, align 4
  store ptr null, ptr %2, align 4
  store ptr %12, ptr %7, align 4
  %13 = load ptr, ptr %3, align 4
  store ptr null, ptr %3, align 4
  store ptr %13, ptr %8, align 4
  %14 = load ptr, ptr %4, align 4
  store ptr null, ptr %4, align 4
  store ptr %14, ptr %9, align 4
  tail call void @h1(ptr noundef align 4 dereferenceable_or_null(44) %10, ptr noundef nonnull byval(%0) align 4 %6, ptr noundef nonnull byval(%3) align 4 %7, ptr noundef nonnull byval(%6) align 4 %8, ptr noundef nonnull byval(%9) align 4 %9) #2
  store ptr getelementptr inbounds ({ [5 x ptr], [9 x ptr] }, ptr @g, i32 0, inrange i32 0, i32 2), ptr %0, align 4
  store ptr getelementptr inbounds ({ [5 x ptr], [9 x ptr] }, ptr @g, i32 0, inrange i32 1, i32 2), ptr %10, align 4
  call void @h2(ptr noundef align 4 dereferenceable_or_null(4) %4) #2
  call void @h3(ptr noundef align 4 dereferenceable_or_null(4) %3) #2
  call void @h4(ptr noundef align 4 dereferenceable_or_null(4) %2) #2
  call void @h5(ptr noundef align 4 dereferenceable_or_null(4) %1) #2
  ret void
}

; Function Attrs: minsize null_pointer_is_valid optsize
declare void @h1(ptr noundef align 4 dereferenceable_or_null(44), ptr noundef byval(%0) align 4, ptr noundef byval(%3) align 4, ptr noundef byval(%6) align 4, ptr noundef byval(%9) align 4) unnamed_addr #1

; Function Attrs: minsize nounwind null_pointer_is_valid optsize uwtable
declare hidden void @h2(ptr noundef align 4 dereferenceable_or_null(4)) unnamed_addr #0 align 2

; Function Attrs: minsize nounwind null_pointer_is_valid optsize uwtable
declare hidden void @h3(ptr noundef align 4 dereferenceable_or_null(4)) unnamed_addr #0 align 2

; Function Attrs: minsize nounwind null_pointer_is_valid optsize uwtable
declare hidden void @h4(ptr noundef align 4 dereferenceable_or_null(4)) unnamed_addr #0 align 2

; Function Attrs: minsize nounwind null_pointer_is_valid optsize uwtable
declare hidden void @h5(ptr noundef align 4 dereferenceable_or_null(4)) unnamed_addr #0 align 2

attributes #0 = { minsize nounwind null_pointer_is_valid optsize uwtable "frame-pointer"="non-leaf" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="i686" "target-features"="+cx8,+mmx,+sse,+sse2,+sse3,+ssse3,+x87" "tune-cpu"="generic" }
attributes #1 = { minsize null_pointer_is_valid optsize "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="i686" "target-features"="+cx8,+mmx,+sse,+sse2,+sse3,+ssse3,+x87" "tune-cpu"="generic" }
attributes #2 = { minsize nounwind optsize }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2, !3, !4, !5, !6}

!0 = !{i32 1, !"NumRegisterParameters", i32 0}
!1 = !{i32 7, !"Dwarf Version", i32 4}
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 8, !"PIC Level", i32 2}
!5 = !{i32 7, !"uwtable", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 1}
```

With [D138899](https://reviews.llvm.org/D138899) applied, machine-scheduler will turn

```
176B      %12:gr32 = LEA32r %fixed-stack.0, 1, $noreg, 0, $noreg
192B      %6:gr32 = MOV32rm %12:gr32, 1, $noreg, 0, $noreg :: (dereferenceable load (s32) from %ir.4, align 16)
208B      MOVUPSmr %18:gr32, 1, $noreg, 0, $noreg, %3:vr128 :: (store (s128) into %ir.1, align 4)
224B      MOV32mr %stack.0, 1, $noreg, 0, $noreg, %2:gr32 :: (store (s32) into %ir.6)
```
into
```
264B      %12:gr32 = LEA32r %fixed-stack.0, 1, $noreg, 0, $noreg
272B      MOVUPSmr %18:gr32, 1, $noreg, 0, $noreg, %3:vr128 :: (store (s128) into %ir.1, align 4)
280B      %6:gr32 = MOV32rm %12:gr32, 1, $noreg, 0, $noreg :: (dereferenceable load (s32) from %ir.4, align 16)      // now the content is loaded after the filling 0 MOVUPSmr
320B      MOV32mr $esp, 1, $noreg, 16, $noreg, %6:gr32 :: (store (s32))
```
Which seems a wrong schedule given `%ir.4` and `%ir.1` is overlapped.

**Comment by aeubanks** [comment] 2023-02-20 05:20
Slightly reduced example
```
target triple = "i686-unknown-linux-android24"

define void @f(ptr %arg, ptr byval(ptr) %arg1, ptr byval(ptr) %arg2, ptr byval(ptr) %arg3, ptr byval(ptr) %arg4) #0 {
bb:
  %inst = alloca ptr, align 4
  %inst5 = alloca ptr, align 4
  %inst6 = alloca ptr, align 4
  %inst7 = alloca ptr, align 4
  %inst9 = load ptr, ptr %arg1, align 4
  store ptr null, ptr %arg1, align 4
  store ptr %inst9, ptr %inst, align 4
  %inst10 = load ptr, ptr %arg2, align 4
  store ptr null, ptr %arg2, align 4
  store ptr %inst10, ptr %inst5, align 4
  %inst11 = load ptr, ptr %arg3, align 4
  store ptr null, ptr %arg3, align 4
  store ptr %inst11, ptr %inst6, align 4
  %inst12 = load ptr, ptr %arg4, align 4
  store ptr null, ptr %arg4, align 4
  store ptr %inst12, ptr %inst7, align 4
  call void @g(ptr %arg, ptr byval(ptr) %inst, ptr byval(ptr) %inst5, ptr byval(ptr) %inst6, ptr byval(ptr) %inst7)
  call void @h(ptr %arg4)
  call void @h(ptr %arg3)
  call void @h(ptr %arg2)
  call void @h(ptr %arg1)
  ret void
}

declare void @g(ptr, ptr, ptr, ptr, ptr)

declare void @h(ptr)

attributes #0 = { optsize "frame-pointer"="non-leaf" "target-cpu"="i686" "target-features"="+sse,+sse2" "tune-cpu"="generic" }
```

I'm not really familiar with codegen, I believe the issue is that the `MOVUPSmr` is created to write `null` across four separate pointers on the stack, but [ScheduleDAGInstrs only sees the first pointer on the stack as something that could alias the `MOVUPSmr`](https://github.com/llvm/llvm-project/blob/a489e11439e36c7e0ec83b28a6fb1596a5c21faa/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp#L937).

Not sure  if ScheduleDAGInstrs should properly handle this case, or if `MOVUPSmr` on multiple separate stack entities shouldn't be generated by SelectionDAG, or something else.

**Comment by aeubanks** [comment] 2023-02-20 05:30
Adding some people who've touched ScheduleDAGInstrs recently for hopefully some insight

@jayfoad @frasercrmck @arsenm

**Comment by phoebewang** [comment] 2023-02-20 08:32
Thanks @aeubanks

**Comment by arsenm** [comment] 2023-02-20 13:54
Wouldn't %ir.1 and %ir.4 refer to the IR byval arguments? These have to point to distinct objects, so how can they overlap?

**Comment by chenzheng1030** [comment] 2023-02-21 01:35
%ir.1 is a merged store after DAGCombiner.
Before DAGCombiner:
```
      t16: ch = store<(store (s32) into %ir.1)> t15:1, Constant:i32<0>, FrameIndex:i32<-2>, undef:i32
      t20: ch = store<(store (s32) into %ir.2)> t19:1, Constant:i32<0>, FrameIndex:i32<-3>, undef:i32
      t24: ch = store<(store (s32) into %ir.3)> t23:1, Constant:i32<0>, FrameIndex:i32<-4>, undef:i32
      t28: ch = store<(store (s32) into %ir.4)> t27:1, Constant:i32<0>, FrameIndex:i32<-5>, undef:i32
```

After DAGCombiner:
```
        t132: ch = TokenFactor t15:1, t124:1, t114:1, t104:1
        t131: v4i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
      t133: ch = store<(store (s128) into %ir.1, align 4)> t132, t131, FrameIndex:i32<-2>, undef:i32
```

**Comment by bzEq** [comment] 2023-02-21 03:06
> t133: ch = store<(store (s128) into %ir.1, align 4)> t132, t131, FrameIndex:i32<-2>, undef:i32

The `%ir.1` object has size of 4 bytes, storing 16 bytes content into `%ir.1` may make AA think it's undefined.

**Comment by chenzheng1030** [comment] 2023-02-22 09:18
Without [D138899](https://reviews.llvm.org/D138899), machine scheduler also gets wrong dependency analysis result for below two instructions
```
%6:gr32 = MOV32rm %13:gr32, 1, $noreg, 0, $noreg :: (dereferenceable load (s32) from %ir.4, align 16)
MOVUPSmr %19:gr32, 1, $noreg, 0, $noreg, %3:vr128 :: (store (s128) into %ir.1, align 4)
```

```
SU(11):   %6:gr32 = MOV32rm %13:gr32, 1, $noreg, 0, $noreg :: (dereferenceable load (s32) from %ir.4, align 16)
  Predecessors:
    SU(10): Data Latency=1 Reg=%13
    SU(1): Ord  Latency=1 Memory
  Successors:
    SU(16): Data Latency=5 Reg=%6
  Pressure Diff      : GR16 -2
SU(12):   MOVUPSmr %19:gr32, 1, $noreg, 0, $noreg, %3:vr128 :: (store (s128) into %ir.1, align 4)
  Predecessors:
    SU(5): Data Latency=1 Reg=%3
    SU(4): Ord  Latency=0 Memory
    SU(3): Data Latency=1 Reg=%19
    SU(1): Ord  Latency=0 Memory
  Pressure Diff      : FR16 1    FR16X 1
```

SU(11) and SU(12) are not dependent, so it has the possibility that SU(12) is scheduled to the front of SU(11).

**Comment by chenzheng1030** [comment] 2023-02-22 09:28
This below change can fix the dependency analysis result:
```
diff --git a/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp b/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp
index 6dcb1fac9a8c..900ddcab6764 100644
--- a/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp
+++ b/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp
@@ -156,9 +156,18 @@ static bool getUnderlyingObjectsForInstr(const MachineInstr *MI,
         Objects.emplace_back(PSV, MayAlias);
       } else if (const Value *V = MMO->getValue()) {
         SmallVector<Value *, 4> Objs;
+        unsigned MemSize = MMO->getSizeInBits();
         if (!getUnderlyingObjectsForCodeGen(V, Objs))
           return false;

+        // If the underlying object memory size is not equal to the size of MMO,
+        // the MMO must be widen in previous optimization, so it is not accurate
+        // that only check the alias for the underlying object now.
+        if (any_of(Objs, [&](Value *V) {
+              return DL.getTypeStoreSizeInBits(V->getType()) != MemSize;
+            }))
+          return false;
+
         for (Value *V : Objs) {
           assert(isIdentifiedObject(V));
           Objects.emplace_back(V, true);
```

**Comment by arsenm** [comment] 2023-02-23 12:43
> This below change can fix the dependency analysis result:
> 
> ```
> diff --git a/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp b/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp
> index 6dcb1fac9a8c..900ddcab6764 100644
> --- a/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp
> +++ b/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp
> @@ -156,9 +156,18 @@ static bool getUnderlyingObjectsForInstr(const MachineInstr *MI,
>          Objects.emplace_back(PSV, MayAlias);
>        } else if (const Value *V = MMO->getValue()) {
>          SmallVector<Value *, 4> Objs;
> +        unsigned MemSize = MMO->getSizeInBits();
>          if (!getUnderlyingObjectsForCodeGen(V, Objs))
>            return false;
> 
> +        // If the underlying object memory size is not equal to the size of MMO,
> +        // the MMO must be widen in previous optimization, so it is not accurate
> +        // that only check the alias for the underlying object now.
> +        if (any_of(Objs, [&](Value *V) {
> +              return DL.getTypeStoreSizeInBits(V->getType()) != MemSize;
> +            }))
> +          return false;
> +

This isn't really the place for reviews, but this doesn't require exact match. Only access size less than the allocation size

**Comment by jayfoad** [comment] 2023-02-23 13:29
Just checking the size is not reliable anyway, because the access could be at a non-zero offset into the object.

**Comment by chenzheng1030** [comment] 2023-02-24 09:50
I created https://reviews.llvm.org/D144711

Fixing this in scheduling needs to call `bool llvm::getObjectSize()` to get the underlying object size. But that function needs to query `TargetLibraryInfoWrapperPass` analysis which is not required by scheduler for now.

Instead I choose to fix this in the place where the wrong underlying object is tied to the widen store, this sounds like more reasonable.

**Comment by jayfoad** [comment] 2023-02-24 10:32
> Instead I choose to fix this in the place where the wrong underlying object is tied to the widen store, this sounds like more reasonable.
Agreed!

**Closed** 2023-03-08 01:31 UTC
Labels: bug, llvm:optimizations
