### ISSUE TITLE
clang-format alignment malfunctions near preprocessor ifdef blocks

### ISSUE THREAD

**Issue by mbeall-cricut** [llvm/llvm-project#60721] opened 2023-02-13 22:55 UTC
## Clang-Format alignment near preprocessor `ifdef` blocks
When using `ifdef` blocks for hardware configurations, Clang-Format assignment and comment alignment seem to misbehave.

Using `clang-format` version 15.0.6

Issue arises when using the following `.clang-format` style file:
```yml
BasedOnStyle: LLVM
BreakBeforeBraces: Allman
ColumnLimit: 180
IndentWidth: 2
IndentPPDirectives: BeforeHash
TabWidth: 2
UseTab: Never
BreakBeforeBraces: Allman
InsertBraces: true
BreakBeforeBinaryOperators: None
KeepEmptyLinesAtTheStartOfBlocks: false
AlignConsecutiveAssignments: Consecutive
AlignConsecutiveDeclarations: Consecutive
AlignTrailingComments: true
AlignConsecutiveMacros: Consecutive
SpacesBeforeTrailingComments: 1
AllowShortFunctionsOnASingleLine: Empty
PointerAlignment: Left
SortIncludes: Never
```

The resulting formatting looks like this:
```cpp
void myFunction()
{
#ifdef CONFIG_OPTION_1
  const uint8_t My_Big_Long_Variable_Divisor = 0x2;
#else
  const uint8_t My_Big_Long_Variable_Divisor = 0x3;
#endif

  // Comment
  BITREGISTER.REGBITS1 = 1;                            // same line comment
  BITREGISTER.REGBITS2 = My_Big_Long_Variable_Divisor; // same line comment
#ifdef CONFIG_OPTION_2
  BITREGISTER.BITS3 = 0; // same line comment
#else
  BITREGISTER.BITS3                          = 1; // same line comment
#endif
}
```

## Expected behavior

I would expect adjacent assignments across preprocessor directives to be aligned as if they are actually adjacent. In the example above, I would expect this result:
```cpp
void myFunction()
{
#ifdef CONFIG_OPTION_1
  const uint8_t My_Big_Long_Variable_Divisor = 0x2;
#else
  const uint8_t My_Big_Long_Variable_Divisor = 0x3;
#endif

  // Comment
  BITREGISTER.REGBITS1 = 1;                            // same line comment
  BITREGISTER.REGBITS2 = My_Big_Long_Variable_Divisor; // same line comment
#ifdef CONFIG_OPTION_2
  BITREGISTER.BITS3    = 0;                            // same line comment
#else
  BITREGISTER.BITS3    = 1;                            // same line comment
#endif
}
```

**Comment by owenca** [comment] 2023-05-06 23:24
> I would expect adjacent assignments across preprocessor directives to be aligned as if they are actually adjacent. In the example above, I would expect this result:
> 
> ```c++
> void myFunction()
> {
> #ifdef CONFIG_OPTION_1
>   const uint8_t My_Big_Long_Variable_Divisor = 0x2;
> #else
>   const uint8_t My_Big_Long_Variable_Divisor = 0x3;
> #endif
> 
>   // Comment
>   BITREGISTER.REGBITS1 = 1;                            // same line comment
>   BITREGISTER.REGBITS2 = My_Big_Long_Variable_Divisor; // same line comment
> #ifdef CONFIG_OPTION_2
>   BITREGISTER.BITS3    = 0;                            // same line comment
> #else
>   BITREGISTER.BITS3    = 1;                            // same line comment
> #endif
> }
> ```

Consecutive alignments do not cross preprocessor directives, so the expected output should be:
```
void myFunction()
{
#ifdef CONFIG_OPTION_1
  const uint8_t My_Big_Long_Variable_Divisor = 0x2;
#else
  const uint8_t My_Big_Long_Variable_Divisor = 0x3;
#endif

  // Comment
  BITREGISTER.REGBITS1 = 1;                            // same line comment
  BITREGISTER.REGBITS2 = My_Big_Long_Variable_Divisor; // same line comment
#ifdef CONFIG_OPTION_2
  BITREGISTER.BITS3 = 0; // same line comment
#else
  BITREGISTER.BITS3 = 1; // same line comment
#endif
}
```

**Comment by owenca** [comment] 2023-05-06 23:28
Duplicate of #61498.

**Closed** 2023-05-07 02:21 UTC
Labels: duplicate, clang-format
