### ISSUE TITLE
[C++2b] `if consteval` doesn't work well in template instantiations

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#60504] opened 2023-02-03 07:09 UTC
For,

```c++
// a.cpp
template<typename T>
auto a() {
	if consteval {
		typename T::type x;
	}
}

void b() {
	a<int>();
}
```

compile it with

```shell
clang++ -std=c++2b a.cpp -fsyntax-only
```

We will see

```console
a.cpp:4:12: error: type 'int' cannot be used prior to '::' because it has no members
                typename T::type x;
                         ^
a.cpp:9:2: note: in instantiation of function template specialization 'a<int>' requested here
        a<int>();
        ^
1 error generated.
```

But this shouldn't be true.

**Comment by ChuanqiXu9** [comment] 2023-02-03 07:15
This exists in clang15: https://godbolt.org/z/aaPqM63s7

**Comment by cor3ntin** [comment] 2023-02-23 12:04
@ChuanqiXu9 `if consteval` branches that are not evaluated are not discarded (ie, it's not like constexpr if), I believe the behavior of clang is conforming, and matches that of GCC. https://godbolt.org/z/3qqEMYEjv

**Comment by cor3ntin** [comment] 2023-02-23 14:28
Given that this is the intended behavior (confirmed with @AaronBallman to be extra certain), I'm closing this issue.

**Closed by cor3ntin** 2023-02-23 14:28 UTC
Labels: invalid, c++2b, consteval
