### ISSUE TITLE
Semantic difference for option -fno-zero-initialized-in-bss between gcc and clang

### ISSUE THREAD

**Issue by dustanddreams** [llvm/llvm-project#74632] opened 2023-12-06 17:42 UTC
When the `-fzero-initialized-in-bss` option was introduced in gcc 3.x,
it would only affect global variables with an explicit initializer turning out
to be equivalent to the zero initialization (C11 6.7.9#10).

Its current implementation (at least in clang 16) makes the decision at a very
low level place in the llvm stack, and affects global variables with an
initializer turning out to be equivalent to zero initialization. However, at
this state, every global variable has been given an initializer, regardless of
the presence of an explicit initialization or not.

This has the consequence that the negative option,
`-fno-zero-initialized-in-bss`, causes all global variables which would be
initialized with zero to be put in the data section with an explicit zero
initializer, and nothing ends up in bss anymore.

Consider the following example:
```
int bss_variable;
int zero_variable = 0;
int nonzero_variable = 42;
```

when compiling this with `gcc -fno-zero-initialized-in-bss`:
- `bss_variable` end up in bss.
- `zero_variable` and `nonzero_variable` end up in data.

when compiling this with `clang -fno-zero-initialized-in-bss`:
- all three variables end up in data.

**Comment by shafik** [comment] 2023-12-06 18:23
CC @jfbastien @AaronBallman

**Comment by pinskia** [comment] 2023-12-07 18:55
I am not 100% sure if the behavior matters these days but the documentation for this option says:
```
This option turns off this behavior because some programs explicitly rely on variables going to the data section—e.g., so that the resulting executable can find the beginning of that section and/or make assumptions based on that.
```

This option was added when `-fcommon` was the default also so you end up with the variable `bss_variable` (listed above) in the common section. There was some code at the time which depedent on variables not in the common section not to be in the BSS so they would get initialized to zero at build time; especially so you do a load the compiled binary (non-elf) into memory and you check if you already zero'd the bss or not and you run the memset at runtime.
But with `-fno-common` being the default, these `bss_variable` variables are now going into the BSS rather than the common section. That is `-fno-zero-initialized-in-bss` in both the GCC and clang/LLVM cases are working to what is required; except clang puts more into the data section could mean larger binaries and image sizes. BUT most embeded code from that era has been fixed such that it does the right thing and not depend on the option any more.

**Comment by hubert-reinterpretcast** [comment] 2024-10-08 16:15
This is a duplicate of https://github.com/llvm/llvm-project/issues/30973.

**Closed** 2024-10-08 16:16 UTC
Labels: duplicate, clang:codegen
