### ISSUE TITLE
`std::allocate_shared` does not use `std::allocator_traits<Alloc>::destroy` on C++17 - cppreference says it should (?)

### ISSUE THREAD

**Issue by burnpanck** [llvm/llvm-project#65788] opened 2023-09-08 18:21 UTC
That said, [cppreference.com](https://en.cppreference.com/w/cpp/memory/shared_ptr/allocate_shared) does state that `::allocate` is only used from C++20 onwards. There is no corresponding info regarding `::destroy`. Possibly, this is a documentation error on cppreference instead. Unfortunately, I do not have access to the standard, so I cannot verify. libstdc++ does call `::destroy` in C++17 mode though.

**Comment by burnpanck** [comment] 2023-09-08 18:28
For reference, the corresponding source line is here: https://github.com/llvm/llvm-project/blob/71168f6889b2335c4b394cc617b4247f6ddaa2c7/libcxx/include/__memory/shared_ptr.h#L314

**Comment by shafik** [comment] 2023-09-08 20:16
Note latest draft of C++ standard available here in HTML form: https://eel.is/c++draft/

**Comment by burnpanck** [comment] 2023-09-09 07:10
To answer this question, we need to consult the C++17 standard (and potentially earlier standards too). cppreference.com links [the final C++17 working draft here](https://timsong-cpp.github.io/cppwp/n4659/), which contains [a description of `std::allocate_shared`](https://timsong-cpp.github.io/cppwp/n4659/util.smartptr.shared.create#lib:allocate_shared). At least in that draft however, there is no mention of the way the managed object will ultimately be destroyed. If that is what the final standard says, I guess it is up to the implementation then.

From a symmetry perspective, as C++17 specifies construction via `new ...` (bypassing `alloc.construct`), I guess bypassing `alloc.destroy` too makes sense. We can therefore probably close this as "not a bug" and instead try to clarify cppreference. What do you think?

**Comment by frederick-vs-ja** [comment] 2023-09-09 07:28
This is likely a duplicate of #54365.

cppreference considers the part of [P0674R1](https://wg21.link/P0674R1) resolving [LWG2070](https://cplusplus.github.io/LWG/issue2070) to be a DR against C++17/14/11. However, libc++ only applies the part to C++20 and later modes for an unknown reason. @ldionne.

**Comment by ldionne** [comment] 2023-09-11 18:44
@frederick-vs-ja Thanks a lot for the analysis. This is indeed a duplicate of #54365.

I'll close this as a duplicate and I'll follow up on #54365 instead to keep things in one place. I think it is reasonable to apply the resolution of [LWG2070](https://cplusplus.github.io/LWG/issue2070) as a DR in C++17 since this is what we normally do for LWG issues.

**Closed by ldionne** 2023-09-11 18:44 UTC
Labels: duplicate, libc++
