### ISSUE TITLE
`APFloat.h` compilation errors in C++23 mode

### ISSUE THREAD

**Issue by AnFunctionArray** [llvm/llvm-project#58206] opened 2022-10-06 20:33 UTC
From this question (I've created and maybe so it's an **llvm library BUG** not an clang fronted one):

[SO](https://stackoverflow.com/questions/73978544/unique-pointer-with-incomplete-type-c2b)

[APFloat.h DoubleAPFloat implementation](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/ADT/APFloat.h#L608)

**Simple example:**

```cpp
#include <memory>
#include <llvm/ADT/APFloat.h>
```

```console
$ clang++ -std=c++2b -I /usr/lib/llvm-14/include ../bugl.cpp 
In file included from ../bugl.cpp:1:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:76:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:130:18: error: invalid application of 'sizeof' to an incomplete type 'llvm::APFloat'
          static_assert(sizeof(_Tp)>0,
                        ^~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:669:4: note: in instantiation of function template specialization 'std::default_delete<llvm::APFloat[]>::operator()<llvm::APFloat>' requested here
          get_deleter()(__ptr);
          ^
/usr/lib/llvm-14/include/llvm/ADT/APFloat.h:601:7: note: in instantiation of member function 'std::unique_ptr<llvm::APFloat[]>::~unique_ptr' requested here
class DoubleAPFloat final : public APFloatBase {
      ^
/usr/lib/llvm-14/include/llvm/ADT/APFloat.h:625:13: note: in implicit destructor for 'llvm::detail::DoubleAPFloat' first required here
      this->~DoubleAPFloat();
            ^
/usr/lib/llvm-14/include/llvm/ADT/APFloat.h:38:7: note: forward declaration of 'llvm::APFloat'
class APFloat;
      ^
In file included from ../bugl.cpp:1:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:76:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:720:9: error: subscript of pointer to incomplete type 'llvm::APFloat'
        return get()[__i];
               ^~~~~
/usr/lib/llvm-14/include/llvm/ADT/APFloat.h:633:38: note: in instantiation of member function 'std::unique_ptr<llvm::APFloat[]>::operator[]' requested here
  APFloat &getFirst() { return Floats[0]; }
                                     ^
/usr/lib/llvm-14/include/llvm/ADT/APFloat.h:38:7: note: forward declaration of 'llvm::APFloat'
class APFloat;
      ^
2 errors generated.
```
**In case it's a language bug (and not library one):**

```cpp
#include <memory>
class dummy;

std::unique_ptr<dummy[]> test;

int main() {
    const dummy &refdum = test[0];   
}

class dummy {

};
```

Compiles with c++20 but not with c++2b:

```console
$ clang++ -std=c++2b ../bugl.cpp 
In file included from ../bugl.cpp:1:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:76:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:130:18: error: invalid application of 'sizeof' to an incomplete type 'dummy'
          static_assert(sizeof(_Tp)>0,
                        ^~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:669:4: note: in instantiation of function template specialization 'std::default_delete<dummy[]>::operator()<dummy>' requested here
          get_deleter()(__ptr);
          ^
../bugl.cpp:4:26: note: in instantiation of member function 'std::unique_ptr<dummy[]>::~unique_ptr' requested here
std::unique_ptr<dummy[]> test;
                         ^
../bugl.cpp:2:7: note: forward declaration of 'dummy'
class dummy;
      ^
In file included from ../bugl.cpp:1:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:76:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:720:9: error: subscript of pointer to incomplete type 'dummy'
        return get()[__i];
               ^~~~~
../bugl.cpp:7:31: note: in instantiation of member function 'std::unique_ptr<dummy[]>::operator[]' requested here
    const dummy &refdum = test[0];   
                              ^
../bugl.cpp:2:7: note: forward declaration of 'dummy'
class dummy;
      ^
2 errors generated.
```

**Comment by EugeneZelenko** [comment] 2022-10-06 20:35
Could you please try 15 or `main` branch?

**Comment by AnFunctionArray** [comment] 2022-10-06 20:36
> Could you please try 15 or `main` branch?

I might but I'll have to compile it.

**Comment by AnFunctionArray** [comment] 2022-10-06 20:37
However from the answer in SO I've left with the impression the llvm implementation is at fault and not the clang frontend.

**Comment by EugeneZelenko** [comment] 2022-10-06 20:37
@AnFunctionArray : 14 is not longer maintained.

**Comment by AnFunctionArray** [comment] 2022-10-06 20:42
> @AnFunctionArray : 14 is not longer maintained.

OK - I'll test on the last released binary tag - how about that [LLVM 15.0.2](https://github.com/llvm/llvm-project/releases/tag/llvmorg-15.0.2)

**Comment by EugeneZelenko** [comment] 2022-10-06 20:46
@AnFunctionArray: 15.0.2 is fine, but `main` is even better since it may have more fixes and enhancements.

**Comment by AnFunctionArray** [comment] 2022-10-06 20:47
OK I did test it on that and the error is the same:

```
In file included from ./bugl.cpp:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:76:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:130:18: error: invalid application of 'sizeof' to an incomplete type 'dummy'
          static_assert(sizeof(_Tp)>0,
                        ^~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:669:4: note: in instantiation of function template specialization 'std::default_delete<dummy[]>::operator()<dummy>' requested here
          get_deleter()(__ptr);
          ^
./bugl.cpp:4:26: note: in instantiation of member function 'std::unique_ptr<dummy[]>::~unique_ptr' requested here
std::unique_ptr<dummy[]> test;
                         ^
./bugl.cpp:2:7: note: forward declaration of 'dummy'
class dummy;
      ^
In file included from ./bugl.cpp:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/memory:76:
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:720:9: error: subscript of pointer to incomplete type 'dummy'
        return get()[__i];
               ^~~~~
./bugl.cpp:7:31: note: in instantiation of member function 'std::unique_ptr<dummy[]>::operator[]' requested here
    const dummy &refdum = test[0];   
                              ^
./bugl.cpp:2:7: note: forward declaration of 'dummy'
class dummy;
      ^
2 errors generated.

```

```
clang version 15.0.2 (https://github.com/llvm/llvm-project.git 4bd3f3759259548e159aeba5c76efb9a0864e6fa)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/username/Downloads/clang+llvm-15.0.2-x86_64-unknown-linux-gnu-rhel86/clang+llvm-15.0.2-x86_64-unknown-linux-gnu/bin
```

**Comment by AnFunctionArray** [comment] 2022-10-06 20:47
> @AnFunctionArray: 15.0.2 is fine, but `main` is even better since it may have more fixes and enhancements.

But the llvm code in question is the same (if it's in fact a lib bug).

**Comment by EmmaJaneBonestell** [comment] 2023-05-28 19:16
Assuming this is also a forward declaration error, you can probably fix this by running clang-include-fixer on the entire build project, but don't expect your patch to be acknowledged. The run-find-all-symbols.py script (that you need for clang-include-fixer to work) is broken, too. I have a fixed version of it here, if you want to bother: https://gist.github.com/EmmaJaneBonestell/2443eaad3424bcb2db4ff436d9594ff8
You'll need clang-tools-extra installed.

**Comment by cor3ntin** [comment] 2024-07-11 13:49
I think this is not a bug and we should close it @AaronBallman @shafik

**Comment by AaronBallman** [comment] 2024-07-11 14:15
https://eel.is/c++draft/unique.ptr.runtime#general-3

The diagnostics are valid diagnostics; the issue is that the definition of `DoubleAPFloat` is using a forward declaration where the standard library requires a complete type. I'll update the issue details to make this more clear.

**Comment by AaronBallman** [comment] 2024-07-11 14:18
The issue is not specific to C++23 (C++20 had the same requirements, for example), but it seems to cause issues only in C++23 mode, so that's why the label is what it is.

**Comment by chriselrod** [comment] 2024-07-11 15:46
Is this a duplicate of https://github.com/llvm/llvm-project/issues/59784 ?
#59784 was fixed as of LLVM 17. `APFloat.h` version 17 and newer compiles fine:
https://godbolt.org/z/5nYY4o8P6
(Note, check the library versions, not the version of the compiler used).

**Comment by AaronBallman** [comment] 2024-07-11 15:54
> Is #59784 a duplicate of this? #59784 was fixed as of LLVM 17. `APFloat.h` version 17 and newer compiles fine: https://godbolt.org/z/5nYY4o8P6 Note, check the library versions, not the version of the compiler used.

Oh, good catch! Yes, this is a duplicate then, so it can be closed.

**Closed** 2024-07-11 15:55 UTC
Labels: duplicate, confirmed, c++23, llvm:adt
