### ISSUE TITLE
llc can compile a faulty IR

### ISSUE THREAD

**Issue by pzzp** [llvm/llvm-project#99428] opened 2024-07-18 04:07 UTC
```
define void @f() local_unnamed_addr #0 {
  call void @g(i32 0)
  ret void
}

define void @g() local_unnamed_addr #4 {
  ret void
}
```
This IR can be compiled successfully, no error reporting.

llc version:
![image](https://github.com/user-attachments/assets/60823daf-bd2e-488d-ab55-e8fa5f9d1598)

**Comment by dtcxzyw** [comment] 2024-07-18 05:32
VerifierPass doesn't complain about this:
https://godbolt.org/z/j5zafxqPh

**Comment by efriedma-quic** [comment] 2024-07-18 06:52
Duplicate of #63484

**Closed by efriedma-quic** 2024-07-18 06:52 UTC
Labels: bug, llvm:ir
