### ISSUE TITLE
Accessing invalid member of template class in other namespace causes ICE

### ISSUE THREAD

**Issue by f4e2561e-09b4-4f3e-85b1-0abbf76a367b** [llvm/llvm-project#51275] opened 2021-09-22 04:04 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51933](https://llvm.org/bz51933) |
| Version | 9.0 |
| OS | All |
| CC | @zygoloid |

## Extended Description 
The following code triggers an ICE / segfault in older clangs, on the later ones it simply errors out with return code 254 (and no error message or other info):

```cpp
namespace abc {  // Yes, the namespace is necessary
template<typename T>
struct BusinessLogic {};
} // namespace abc

int main()
{
    abc::BusinessLogic.ArbitraryStringHere;
}
```
--
Error:

1.	<source>:8:10: current parser token 'BusinessLogic'
2.	<source>:7:1: parsing function body 'main'
3.	<source>:7:1: in compound statement ('{}')
  #&#8203;0 0x000055d6cedd6f7a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x27d6f7a)
  #&#8203;1 0x000055d6cedd4d44 llvm::sys::RunSignalHandlers() (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x27d4d44)
  #&#8203;2 0x000055d6cedd4e82 SignalHandler(int) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x27d4e82)
  #&#8203;3 0x00007f6777a853c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
  #&#8203;4 0x000055d6d0bebc9c clang::DeclContext::lookup(clang::DeclarationName) const (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x45ebc9c)
  #&#8203;5 0x000055d6d0760a05 LookupDirect(clang::Sema&, clang::LookupResult&, clang::DeclContext const*) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x4160a05)
  #&#8203;6 0x000055d6d0761490 clang::Sema::LookupQualifiedName(clang::LookupResult&, clang::DeclContext*, bool) (.part.1132) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x4161490)
  #&#8203;7 0x000055d6d0504581 clang::Sema::getTypeName(clang::IdentifierInfo const&, clang::SourceLocation, clang::Scope*, clang::CXXScopeSpec*, bool, bool, clang::OpaquePtr<clang::QualType>, bool, bool, bool, clang::IdentifierInfo**) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3f04581)
  #&#8203;8 0x000055d6d02f52cb clang::Parser::TryAnnotateTypeOrScopeTokenAfterScopeSpec(clang::CXXScopeSpec&, bool) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3cf52cb)
  #&#8203;9 0x000055d6d02f7e9f clang::Parser::TryAnnotateTypeOrScopeToken() (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3cf7e9f)
 #&#8203;10 0x000055d6d03a20a5 clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3da20a5)
 #&#8203;11 0x000055d6d03a27ef clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3da27ef)
...
#&#8203;253 0x000055d6d03a27ef clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3da27ef)
#&#8203;254 0x000055d6d03a27ef clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3da27ef)
#&#8203;255 0x000055d6d03a27ef clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (/opt/compiler-explorer/clang-9.0.1/bin/clang-9+0x3da27ef)
clang-9: error: unable to execute command: Segmentation fault (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
Compiler returned: 254

--

https://godbolt.org/z/rTfGWGdPz

**Comment by Endilll** [comment] 2023-06-05 09:53
Assertion build is crashing, Clang 16 exits with code 139, Clang 15 issues proper diagnostics: https://godbolt.org/z/3qd9KzKsK
I guess this counts as a regression.
Assertion:
```
clang++: /root/llvm-project/clang/lib/Parse/ParseTentative.cpp:1671: clang::Parser::TPResult clang::Parser::isCXXDeclarationSpecifier(clang::ImplicitTypenameContext, clang::Parser::TPResult, bool*): Assertion `Tok.isNot(tok::annot_cxxscope) || NextToken().isNot(tok::identifier)' failed.
```
Stack:
```
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:8:5: at annotation token
2.	<source>:7:1: parsing function body 'main'
3.	<source>:7:1: in compound statement ('{}')
 #0 0x0000562d3c9f4dbf llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c12dbf)
 #1 0x0000562d3c9f2b2c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3c10b2c)
 #2 0x0000562d3c93c1a8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007f2cf46dc420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f2cf41a900b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f2cf4188859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f2cf4188729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f2cf4199fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000562d3f247620 clang::Parser::isCXXDeclarationSpecifier(clang::ImplicitTypenameContext, clang::Parser::TPResult, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6465620)
 #9 0x0000562d3f24659e clang::Parser::isCXXDeclarationSpecifier(clang::ImplicitTypenameContext, clang::Parser::TPResult, bool*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x646459e)
#10 0x0000562d3f24c65d clang::Parser::isCXXDeclarationStatement(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x646a65d)
#11 0x0000562d3f22093a clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributes&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x643e93a)
#12 0x0000562d3f221d11 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x643fd11)
#13 0x0000562d3f222d09 clang::Parser::ParseCompoundStatementBody(bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6440d09)
#14 0x0000562d3f2246ba clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64426ba)
#15 0x0000562d3f14f421 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x636d421)
#16 0x0000562d3f1762f0 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63942f0)
#17 0x0000562d3f142cc1 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6360cc1)
#18 0x0000562d3f14357f clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#19 0x0000562d3f149f21 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6367f21)
#20 0x0000562d3f14a896 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6368896)
#21 0x0000562d3f13e65a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x635c65a)
#22 0x0000562d3dc427c8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4e607c8)
#23 0x0000562d3d499f09 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x46b7f09)
#24 0x0000562d3d41e3d6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x463c3d6)
#25 0x0000562d3d57c9e6 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x479a9e6)
#26 0x0000562d39eb046d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x10ce46d)
#27 0x0000562d39eac16a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#28 0x0000562d3d28639d void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#29 0x0000562d3c93c6b0 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b5a6b0)
#30 0x0000562d3d2869bf clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#31 0x0000562d3d24e0ec clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x446c0ec)
#32 0x0000562d3d24eb7d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x446cb7d)
#33 0x0000562d3d256c5d clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4474c5d)
#34 0x0000562d39eae6ca clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x10cc6ca)
#35 0x0000562d39db5235 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xfd3235)
#36 0x00007f2cf418a083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#37 0x0000562d39ea6f4e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x10c4f4e)
```

**Comment by shafik** [comment] 2023-06-05 16:53
duplicate of: https://github.com/llvm/llvm-project/issues/57495

**Closed by shafik** 2023-06-05 16:53 UTC
Labels: clang:frontend, bugzilla, regression, crash-on-invalid, confirmed
