### ISSUE TITLE
`is_invocable_r` does not work with non-movable return types

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#55664] opened 2022-05-23 22:51 UTC
The following valid translation unit

```cpp
#include <functional>
#include <type_traits>

struct non_movable {
	non_movable() = default;
	non_movable(non_movable &&) = delete;
};

auto function() {
	return non_movable();
};

static_assert(std::is_invocable_r_v<non_movable, decltype(function)>);
```

is rejected by clang with libc++ with the message

```console
<source>:13:1: error: static_assert failed due to requirement 'std::is_invocable_r_v<non_movable, non_movable ()>'
static_assert(std::is_invocable_r_v<non_movable, decltype(function)>);
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Compiler returned: 1
```

See it live: https://godbolt.org/z/GrPE4vKz9

Presumably, the implementation of `is_invocable_r` is using `std::is_convertible`. However, `is_convertible` uses `std::declval`, which for types other than void produces a reference, and rvalue references do not have guaranteed copy elision. The standard specifies the behavior of `is_invocable_r` in terms of a call to `INVOKE<R>`, where `R` is the return type (https://eel.is/c++draft/meta.rel#lib:is_invocable_r). However, https://eel.is/c++draft/func.require#lib:INVOKE defines `INVOKE<R>` as just doing an implicit conversion from the result of the function to the type `R`.

**Comment by frederick-vs-ja** [comment] 2022-05-24 01:33
This is a duplicate of #55346.

**Closed** 2022-05-24 09:23 UTC
Labels: duplicate, libc++
