### ISSUE TITLE
error in backend: Cannot select: 0x7f8f9e8b17d0: v8i64 = X86ISD::PCMPEQ

### ISSUE THREAD

**Issue by jozefizso** [llvm/llvm-project#59909] opened 2023-01-10 00:04 UTC
I'm build the [cado-nfs](https://gitlab.inria.fr/cado-nfs/cado-nfs) on macOS 12.6 (MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports))

It fails to compile **merge_compute_weights.c.o** file and ends with this error:

```
fatal error: error in backend: Cannot select: 0x7f8f9e8b17d0: v8i64 = X86ISD::PCMPEQ 0x7f8f9e8839a0, 0x7f8f9e884020
  0x7f8f9e8839a0: v8i64,ch = load<(load (s64) from %ir.466, align 1, !tbaa !14), zext from v8i8> 0x7f8f9da0bbf8, 0x7f8f9e8b0ad0, undef:i64
    0x7f8f9e8b0ad0: i64 = add 0x7f8f9e8b0d40, Constant:i64<-24>
      0x7f8f9e8b0d40: i64 = add 0x7f8f9e09aee0, 0x7f8f9e883ad8
        0x7f8f9e09aee0: i64,ch = CopyFromReg 0x7f8f9da0bbf8, Register:i64 %107
          0x7f8f9e09aa00: i64 = Register %107
        0x7f8f9e883ad8: i64,ch = CopyFromReg 0x7f8f9da0bbf8, Register:i64 %109
          0x7f8f9e8b1428: i64 = Register %109
      0x7f8f9e8843c8: i64 = Constant<-24>
    0x7f8f9e8b1490: i64 = undef
  0x7f8f9e884020: v8i64 = BUILD_VECTOR Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
In function: compute_weights_backend
```

The tail of the `make VERBOSE=1` command:

```
[ 38%] Built target purge
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f filter/CMakeFiles/merge.dir/build.make filter/CMakeFiles/merge.dir/depend
cd /Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local && /usr/local/Cellar/cmake/3.25.1/bin/cmake -E cmake_depends "Unix Makefiles" /Users/jozef/Developer/cado-nfs /Users/jozef/Developer/cado-nfs/filter /Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local /Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local/filter /Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local/filter/CMakeFiles/merge.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f filter/CMakeFiles/merge.dir/build.make filter/CMakeFiles/merge.dir/build
[ 38%] Building C object filter/CMakeFiles/merge.dir/merge_compute_weights.c.o
cd /Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local/filter && /Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local/ccwrap.pl -DWITH_PTHREADS -I/usr/local/include -I/Users/jozef/Developer/cado-nfs -I/Users/jozef/Developer/cado-nfs/utils -I/Users/jozef/Developer/cado-nfs/utils/embedded -I/Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local -I/Users/jozef/Developer/cado-nfs/gf2x -I/Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local/gf2x -std=c99 -W -Wall -O2  -mpopcnt -mavx -mavx2 -mavx512f -mavx512vl -mavx512dq -mpclmul -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.6 -MD -MT filter/CMakeFiles/merge.dir/merge_compute_weights.c.o -MF CMakeFiles/merge.dir/merge_compute_weights.c.o.d -o CMakeFiles/merge.dir/merge_compute_weights.c.o -c /Users/jozef/Developer/cado-nfs/filter/merge_compute_weights.c
fatal error: error in backend: Cannot select: 0x7f8f9e8b17d0: v8i64 = X86ISD::PCMPEQ 0x7f8f9e8839a0, 0x7f8f9e884020
  0x7f8f9e8839a0: v8i64,ch = load<(load (s64) from %ir.466, align 1, !tbaa !14), zext from v8i8> 0x7f8f9da0bbf8, 0x7f8f9e8b0ad0, undef:i64
    0x7f8f9e8b0ad0: i64 = add 0x7f8f9e8b0d40, Constant:i64<-24>
      0x7f8f9e8b0d40: i64 = add 0x7f8f9e09aee0, 0x7f8f9e883ad8
        0x7f8f9e09aee0: i64,ch = CopyFromReg 0x7f8f9da0bbf8, Register:i64 %107
          0x7f8f9e09aa00: i64 = Register %107
        0x7f8f9e883ad8: i64,ch = CopyFromReg 0x7f8f9da0bbf8, Register:i64 %109
          0x7f8f9e8b1428: i64 = Register %109
      0x7f8f9e8843c8: i64 = Constant<-24>
    0x7f8f9e8b1490: i64 = undef
  0x7f8f9e884020: v8i64 = BUILD_VECTOR Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>, Constant:i64<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
    0x7f8f9e884360: i64 = Constant<0>
In function: compute_weights_backend
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/gn/jw60dx0571s05vl_x297r0xw0000gn/T/merge_compute_weights-382400.c
clang: note: diagnostic msg: /var/folders/gn/jw60dx0571s05vl_x297r0xw0000gn/T/merge_compute_weights-382400.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/jozef/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
make[2]: *** [filter/CMakeFiles/merge.dir/merge_compute_weights.c.o] Error 70
make[1]: *** [filter/CMakeFiles/merge.dir/all] Error 2
make: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by phoebewang** [comment] 2023-01-10 06:17
@jozefizso Can you provide these two files?
```
/var/folders/gn/jw60dx0571s05vl_x297r0xw0000gn/T/merge_compute_weights-382400.c
/var/folders/gn/jw60dx0571s05vl_x297r0xw0000gn/T/merge_compute_weights-382400.sh
```
It's more easy to reproduce the crash that build the whole project.

**Comment by phoebewang** [comment] 2023-01-11 14:01
Thanks @jozefizso. I don't have macOS, the below command works for me on Linux system:
```
clang -cc1 -triple x86_64-apple-macosx12.6.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name merge_compute_weights.c -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-strict-return -fno-rounding-math -funwind-tables=2 -target-sdk-version=13.1 -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -target-feature +popcnt -target-feature +avx -target-feature +avx2 -target-feature +avx512f -target-feature +avx512vl -target-feature +avx512dq -target-feature +pclmul -tune-cpu generic -debugger-tuning=lldb -target-linker-version 820.1 -sys-header-deps -D WITH_PTHREADS -O2 -W -Wall -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -Wno-cast-function-type -Wno-bitwise-instead-of-logical -std=c99 -fdebug-compilation-dir=/Users/jozef/Developer/cado-nfs/build/Jozi-MBP.local/filter -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcommon -fcolor-diagnostics -vectorize-loops -vectorize-slp -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c merge_compute_weights-382400.c
```
I checked it failed with 14.0.3 and passed with LLVM trunk. So I think we can close it.

**Closed by phoebewang** 2023-01-11 14:01 UTC
Labels: backend:X86, crash

**Comment by emmanuelthome** [comment] 2023-03-30 19:24
This is a duplicate of #53842 

@jozefizso It turns out that I'm the main author of cado-nfs, and I wasn't aware of this failure until today. I'm afraid I'll have to turn off avx512f for clang-13.x and clang-14.x, since all releases in these series seem to be affected. clang-15.x and later are ok
