### ISSUE TITLE
[libc++] Use `[[no_unique_address]]` in place of `__compressed_pair` to reduce compile time and debug info size

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#93069] opened 2024-05-22 16:55 UTC
As covered in crbug.com/338094922 , `__compressed_pair` is a major contributor to debug info size. Many libc++ classes use them to store allocators, default deleters, and other things. I believe that `no_unique_address` was intended to be layout-compatible with the `__compressed_pair` technique, but I'm not sure it actually is.

Regardless, for unstable ABI users, it would be a major QoI improvement to avoid extra compressed pair template instantiations.

I thought this feature request had already been filed, but I couldn't find it.

Related work:
* https://reviews.llvm.org/D153991
* https://github.com/llvm/llvm-project/pull/65675
* https://github.com/llvm/llvm-project/issues/49358
* https://github.com/llvm/llvm-project/issues/61196

Can we do this yet?

cc @zmodem @cjdb @amykhuang @zygoloid

**Comment by philnik777** [comment] 2024-05-22 17:05
See #76756

**Comment by dwblaikie** [comment] 2024-05-28 19:48
@Michael137 My understanding was this work was waiting on lldb support for `[[no_unique_adress]]` - is that correct? How's that work coming along since our last discussion?

**Comment by Michael137** [comment] 2024-07-18 14:10
Quick update: all the LLDB blockers have been merged/approved by now. The main remaining change is to the formatters themselves: https://github.com/llvm/llvm-project/pull/96538 (which is ready to land; I'm happy to coordinate merging this once the libc++ changes are ready). Outside of this there are 2 other LLDB issues that would be uncovered by this (which we know the root cause of and should be able to fix within in the coming weeks. But they're not a blocker since they only affect an experimental feature of LLDB).

**Comment by rnk** [comment] 2024-07-18 16:28
The last comment on https://github.com/llvm/llvm-project/pull/76756 says that we have to wait for the LLVM 20 release cycle because the last released version of XCode clang is too old (LLVM 15? unclear). Based on our usual release timeline, the LLVM 19 release will branch in September, so we'd have to wait until then to land this on mainline.

Is there a path to expediting this, like making it opt-in, or only making it available under the unstable ABI? @zmodem gathered data from Chrome and internal Google binaries, and it looks really promising. I don't have the precise numbers handy, but it's in the realm of reducing overall debug info size by around 5%.

**Comment by philnik777** [comment] 2024-07-18 16:32
The branch will be next week. After updating the Apple runners we can land the patch. The release will be in September.

**Comment by rnk** [comment] 2024-07-18 18:04
Great, sorry about misunderstanding the branch timeline, that was my bad.

**Closed** 2024-09-16 09:08 UTC
Labels: libc++, quality-of-implementation
