### ISSUE TITLE
[LIBC++] [EASYFIX] __locale header contains a bug when using Newlib as C library

### ISSUE THREAD

**Issue by belmeopmenieuwesim** [llvm/llvm-project#58656] opened 2022-10-27 23:08 UTC
https://github.com/llvm/llvm-project/blob/c3e09036e84a71f21672ae5ed4540edd5444cf94/libcxx/include/__locale#L552

This line is currently bugged for Newlib. Since Newlib uses all the 8 bits of the type `char` you can not check for overlapping bits as is done on this line of code. Not sure why this static_assert even needs to be here, probably best to remove it as it was 10 months ago. Or set `__regex_word ` to `0` inside `#elif defined(_NEWLIB_VERSION)`.

This is how I currently fixed it:
```cpp
// #elif defined(_NEWLIB_VERSION)
// ...
static const mask __regex_word = 0; 
```

**Comment by philnik777** [comment] 2022-10-27 23:28
This is a duplicate of #54594.

**Closed by philnik777** 2022-10-27 23:28 UTC
Labels: libc++
