### ISSUE TITLE
[Clang] Deducing this does not work correctly with move-only types.

### ISSUE THREAD

**Issue by slavek-kucera** [llvm/llvm-project#100341] opened 2024-07-24 10:30 UTC
Move only types have to be explicitly cast to r-value for the move constructor to be used. https://godbolt.org/z/fabdhKKEj

```
#include <utility>

struct X {
    X() = default;
    X(X&&) = default;
    void operator()(this X);
};

void fail() {
    X()();
    [x = X{}](this auto) {}();
}
void pass() {
    std::move(X())();
    std::move([x = X{}](this auto) {})();
}
```
```
<source>:10:5: error: call to implicitly-deleted copy constructor of 'X'
   10 |     X()();
      |     ^~~
<source>:5:5: note: copy constructor is implicitly deleted because 'X' has a user-declared move constructor
    5 |     X(X&&) = default;
      |     ^
<source>:6:27: note: passing argument to parameter here
    6 |     void operator()(this X);
      |                           ^
<source>:11:5: error: call to implicitly-deleted copy constructor of '(lambda at <source>:11:5)'
   11 |     [x = X{}](this auto) {}();
      |     ^~~~~~~~~~~~~~~~~~~~~~~
<source>:11:6: note: copy constructor of '(lambda at <source>:11:5)' is implicitly deleted because field '' has a deleted copy constructor
   11 |     [x = X{}](this auto) {}();
      |      ^
<source>:5:5: note: copy constructor is implicitly deleted because 'X' has a user-declared move constructor
    5 |     X(X&&) = default;
      |     ^
<source>:11:24: note: passing argument to parameter here
   11 |     [x = X{}](this auto) {}();
      |                        ^
```

**Comment by cor3ntin** [comment] 2024-07-24 14:32
possible duplicate of #100314 @MitalAshok

**Comment by MitalAshok** [comment] 2024-07-24 16:49
I don't think this is a dupe, since even without [CWG2813](https://cplusplus.github.io/CWG/issues/2813.html) this should have been accepted.  
`X{}()` should have done a temporary materialization conversion and the object parameter should be constructed by moving from the temporary.  
It is seemingly coincidentally fixed by allowing the prvalue to bind directly, but there seems to be an existing issue with either the temporary materialization conversion or how those temporary are passed to object parameters. I'll do some investigating.

**Comment by MitalAshok** [comment] 2024-07-24 17:42
Problem was here:

https://github.com/llvm/llvm-project/blob/2e57e6366677390110f5382894c8afeba8da7419/clang/lib/Sema/SemaOverload.cpp#L6359

The temporary was treated as an lvalue if the explicit object parameter was by-value or an lvalue reference type, and is only an xvalue if it had an rvalue reference type (including `void f(this int&&)`, which is pretty strange). This materialization is removed entirely in #95112. A smaller fix that can easily be cherry picked for Clang 19 is to remove that one line (i.e., the temporary is always an xvalue)

**Closed** 2024-12-18 09:44 UTC
Labels: clang:frontend
