### ISSUE TITLE
x86 backend emits `bswap` when `-march=i386` is used

### ISSUE THREAD

**Issue by jckarter** [llvm/llvm-project#63531] opened 2023-06-26 20:25 UTC
If you compile `clang -S -o - ~/foo.c -O3 -target i386-pc-linux -march=i386`:

```
unsigned bswap(unsigned num) {
    union {
        unsigned n;
        char b[4];
    } bytes = {.n = num}, rev = {
      .b[0] = bytes.b[3],
      .b[1] = bytes.b[2],
      .b[2] = bytes.b[1], 
      .b[3] = bytes.b[0]
    };
    return rev.num;
}
```

then clang generates:

```
bswap:                                  # @bswap
	.cfi_startproc
# %bb.0:
	movl	4(%esp), %eax
	bswapl	%eax
	retl
.Lfunc_end0:
	.size	bswap, .Lfunc_end0-bswap
	.cfi_endproc
```

even though `bswapl` is only available with `-march=i486` or later.

**Comment by efriedma-quic** [comment] 2023-06-27 07:06
Duplicate of #58470

**Closed by efriedma-quic** 2023-06-27 07:06 UTC
Labels: backend:X86
