### ISSUE TITLE
clang-format: improper formatting of C generic macros

### ISSUE THREAD

**Issue by jaskij** [llvm/llvm-project#59631] opened 2022-12-21 07:01 UTC
Clang format seems to treat C generic macros as some other type of structure. This *definitely* does not look correct.

What I get, using clang-format 14.0.6:

```c
#pragma once

#include <stdbool.h>
#include <stdint.h>

static inline bool is_bit_set_u32(uint32_t value, uint8_t bit) { return (value >> bit) == 1; }

static inline bool is_bit_set_u16(uint16_t value, uint8_t bit) { return (value >> bit) == 1; }

static inline bool is_bit_set_u8(uint8_t value, uint8_t bit) { return (value >> bit) == 1; }

#define is_bit_set(VAL, BIT)                      \
    _Generic((VAL), uint32_t                      \
             : is_bit_set_u32(VAL, BIT), uint16_t \
             : is_bit_set_u16(VAL, BIT), uint8_t  \
             : is_bit_set_u8(VAL, BIT))

```
How it *could* look:

```c
#define is_bit_set(VAL, BIT) _Generic((VAL), \
                                uint32_t : is_bit_set_u32(VAL, BIT), \
                                uint16_t : is_bit_set_u16(VAL, BIT), \
                                uint8_t : is_bit_set_u8(VAL, BIT))
```

There are definitely some points for discussion here, such as indentation and whether `_Generic` should be on a separate line. I don't think most anyone would question putting each type on it's own line.

The important part here is that lines start with the type, not the colon.

My [`.clang-format`](https://gist.github.com/jaskij/e2646cb88477d47d42ab5862dd677a31/1a11c342b48a5b9621510344089f1683d59558e4)

**Comment by rymiel** [comment] 2022-12-21 08:28
Duplicate of https://github.com/llvm/llvm-project/issues/18080

**Closed by rymiel** 2022-12-21 08:28 UTC
Labels: new issue
