### ISSUE TITLE
[InstCombine] Missed optimization: fold chained selects with exclusive condition but one identical arm

### ISSUE THREAD

**Issue by XChy** [llvm/llvm-project#85833] opened 2024-03-19 17:45 UTC
Alive2 proof: https://alive2.llvm.org/ce/z/ZkjFRM

### Motivating example 

```llvm
define ptr @src(i32 %level, ptr %level.addr) local_unnamed_addr #0 {
entry:
  %c1 = icmp eq i32 %level, 0
  %c2 = icmp eq i32 %level, 1
  %s1 = select i1 %c1, ptr %level.addr, ptr null
  %s2 = select i1 %c2, ptr null, ptr %s1
  ret ptr %s2
}
```
can be folded to:
```llvm
define ptr @tgt(i32 %level, ptr %level.addr) local_unnamed_addr #0 {
entry:
  %cond = icmp eq i32 %level, 0
  %s1 = select i1 %cond, ptr %level.addr, ptr null
  ret ptr %s1
}
```

### Real-world motivation

This snippet of IR is derived from [openssl/crypto/shlib/cmp_util.c@OSSL_CMP_print_to_bio](https://github.com/openssl/openssl/blob/dc9bc6c8e1bd329ead703417a2235ab3e97557ec/crypto/cmp/cmp_util.c#L127) (after O3 pipeline).
The example above is a reduced version. If you're interested in the original suboptimal IR and optimal IR, see also: https://godbolt.org/z/qrh916jj8

**Let me know if you can confirm that it's an optimization opportunity, thanks.**

**Comment by marcauberer** [comment] 2024-03-20 20:59
I would like to work on this

**Comment by marcauberer** [comment] 2024-03-20 21:01
This can be further generalized to: https://alive2.llvm.org/ce/z/pnK3jW

**Comment by sftlbcn** [comment] 2024-03-21 05:45
duplicate of #82350?

**Comment by XChy** [comment] 2024-03-21 05:57
> duplicate of #82350?

Oh, it's a duplicate. Close it now.

**Closed** 2024-03-21 05:57 UTC
Labels: llvm:instcombine, missed-optimization
