### ISSUE TITLE
Unexpected std::source_location::file_name() result in combination with lambda and std::function

### ISSUE THREAD

**Issue by pkl97** [llvm/llvm-project#98748] opened 2024-07-13 14:52 UTC
This program returns 

> File name: include/c++/v1/__type_traits/invoke.h

as file name when compiled with clang 17.0.6. I would have expected it to return main.cpp because the p_function() call is part of the program.

```c++
#include <iostream>
#include <functional>
#include <source_location>

void f(const std::function<void ()>& p_function)
{
    p_function(); // std::source_location::file_name() resolves into include/c++/v1/__type_traits/invoke.h
}

int main()
{
    const auto& lambda = [](const std::source_location& p_sourceLocation = std::source_location::current())
    {
        std::cout << "File name: " << p_sourceLocation.file_name() << std::endl;
    };
    f(lambda);
    return 0;
}
```

**Comment by EugeneZelenko** [comment] 2024-07-13 15:20
Could you please try 18 or `main` branch? https://godbolt.org should be helpful.

**Comment by pkl97** [comment] 2024-07-13 15:40
Interesting, trying this with clang 18.1.8 and the trunk crashes the compiler.

I just used "-std=c++20 -stdlib=libc++" on godbolt.

**Comment by shafik** [comment] 2024-07-13 21:33
This looks like a regression of clang-18: https://godbolt.org/z/W3KPjcdWK

Unreachable:

```console
Dependent types cannot show up in debug information
UNREACHABLE executed at /root/llvm-project/clang/lib/CodeGen/CGDebugInfo.cpp:3749!
```

Backtrace:

```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++20 -stdlib=libc++ <source>
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	/opt/compiler-explorer/clang-assertions-trunk-20240713/bin/../include/c++/v1/__functional/function.h:946:30: Generating code for declaration 'std::function<void ()>::function'
 #0 0x0000000003a4a2b8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a4a2b8)
 #1 0x0000000003a47fac llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a47fac)
 #2 0x0000000003992338 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007341c0242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007341c02969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x00007341c0242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x00007341c02287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000000000399dc6a (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x399dc6a)
 #8 0x0000000003d36528 clang::CodeGen::CGDebugInfo::CreateTypeNode(clang::QualType, llvm::DIFile*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d36528)
 #9 0x0000000003d367e0 clang::CodeGen::CGDebugInfo::getOrCreateType(clang::QualType, llvm::DIFile*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d367e0)
#10 0x0000000003d3cdf1 clang::CodeGen::CGDebugInfo::CollectTemplateParams(std::optional<clang::CodeGen::CGDebugInfo::TemplateArgs>, llvm::DIFile*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d3cdf1)
#11 0x0000000003d4a073 clang::CodeGen::CGDebugInfo::collectFunctionDeclProps(clang::GlobalDecl, llvm::DIFile*, llvm::StringRef&, llvm::StringRef&, llvm::DIScope*&, llvm::MDTupleTypedArrayWrapper<llvm::DINode>&, llvm::DINode::DIFlags&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d4a073)
#12 0x0000000003d4ab17 clang::CodeGen::CGDebugInfo::emitFunctionStart(clang::GlobalDecl, clang::SourceLocation, clang::SourceLocation, clang::QualType, llvm::Function*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3d4ab17)
#13 0x0000000003e20f18 clang::CodeGen::CodeGenFunction::StartFunction(clang::GlobalDecl, clang::QualType, llvm::Function*, clang::CodeGen::CGFunctionInfo const&, clang::CodeGen::FunctionArgList const&, clang::SourceLocation, clang::SourceLocation) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e20f18)
#14 0x0000000003e26777 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e26777)
#15 0x0000000004113b54 clang::CodeGen::CodeGenModule::codegenCXXStructor(clang::GlobalDecl) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4113b54)
#16 0x0000000003efb2ef (anonymous namespace)::ItaniumCXXABI::emitCXXStructor(clang::GlobalDecl) ItaniumCXXABI.cpp:0:0
#17 0x0000000003e8145c clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e8145c)
#18 0x0000000003e8cfad clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e8cfad)
#19 0x0000000003e8cf00 clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e8cf00)
#20 0x0000000003e8f9a3 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e8f9a3)
#21 0x000000000433db1e (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#22 0x000000000433b765 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x433b765)
#23 0x00000000063f536c clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x63f536c)
#24 0x000000000433bef8 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x433bef8)
#25 0x00000000045c47f9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45c47f9)
#26 0x00000000045490ee clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x45490ee)
#27 0x00000000046ad15e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x46ad15e)
#28 0x0000000000c76cbf cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc76cbf)
#29 0x0000000000c6fe5a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#30 0x000000000437f5f9 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#31 0x00000000039927e4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39927e4)
#32 0x000000000437fbef clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#33 0x00000000043456b5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x43456b5)
#34 0x000000000434611d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x434611d)
#35 0x000000000434db25 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x434db25)
#36 0x0000000000c74005 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc74005)
#37 0x0000000000b4b724 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb4b724)
#38 0x00007341c0229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#39 0x00007341c0229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#40 0x0000000000c6f90e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc6f90e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

CC @cor3ntin @AaronBallman

**Comment by cor3ntin** [comment] 2024-07-14 15:13
This is a duplicate of https://github.com/llvm/llvm-project/issues/81155

**Closed by cor3ntin** 2024-07-14 15:13 UTC
Labels: clang:frontend, confirmed, crash
