### ISSUE TITLE
Install target missing LLVMConfig.cmake on Windows

### ISSUE THREAD

**Issue by rnichollx** [llvm/llvm-project#60570] opened 2023-02-06 21:49 UTC
```cmake
find_package(LLVM REQUIRED)
```

Does not work on Windows using the Windows installer for LLVM by default.

```console
CMake Error at CMakeLists.txt:4 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```

A file should be generated by the installer at a location such as `C:\Program Files\LLVM\cmake\LLVMConfig.cmake` to enable automatic detection of LLVM to work.

**Comment by tatlook** [comment] 2023-02-12 20:02
I had same problem with both LLVM-15.0.7-win32.exe and LLVM-15.0.7-win64.exe.

**Comment by ebrianne** [comment] 2023-08-09 12:40
Can something be followed up on this?

**Comment by zmodem** [comment] 2023-09-18 11:20
Duplicate of #53052

**Closed by zmodem** 2023-09-18 11:20 UTC
Labels: packaging, platform:windows
