### ISSUE TITLE
[clang-format] SpaceBeforeParens and opererator less

### ISSUE THREAD

**Issue by Jarod42** [llvm/llvm-project#61911] opened 2023-04-03 12:44 UTC
`operator<` is not handled correctly with `SpaceBeforeParens` (either Always or NonEmptyParenthesis):

Formatting:
```
struct S {
  bool operator<(const S &) const;
  bool operator<=(const S &) const;
  bool operator>(const S &) const;
  bool operator>=(const S &) const;
};
```

results in

```
struct S {
  bool operator<(const S &) const;
  bool operator<= (const S &) const;
  bool operator> (const S &) const;
  bool operator>= (const S &) const;
};
```
it should be

```
struct S {
  bool operator< (const S &) const;
  bool operator<= (const S &) const;
  bool operator> (const S &) const;
  bool operator>= (const S &) const;
};
```

**Comment by rymiel** [comment] 2023-04-03 12:53
This issue is already fixed by df6f4b85138f86be73d58ff3f511df5306cc4b4d (present in clang-format-16). Duplicate of #58821

**Closed by rymiel** 2023-04-03 12:53 UTC
Labels: new issue
