### ISSUE TITLE
16.0.0 C2X labels not correctly supported.

### ISSUE THREAD

**Issue by uecker** [llvm/llvm-project#61507] opened 2023-03-19 09:07 UTC
Release notes for Clang state that for C2X WG14 N2508 is implemented, but this does not seem to be the case. The following code is still rejected:

```c
void foo(void)
{
    bar:
        int i;
}
```

https://godbolt.org/z/8zfc96GMj

**Comment by AaronBallman** [comment] 2023-03-19 14:00
Thanks Martin!

```
statement:
  labeled-statement
  unlabeled-statement

unlabeled-statement:
  expression-statement
  attribute-specifier-sequence_opt primary-block
  attribute-specifier-sequence_opt jump-statement

primary-block:
  compound-statement
  selection-statement
  iteration-statement

secondary-block:
  statement

label:
  attribute-specifier-sequence_opt identifier :
  attribute-specifier-sequence_opt case constant-expression :
  attribute-specifier-sequence_opt default :

labeled-statement:
  label statement
```

Starting from the labeled-statement (`bar:`), the next token is `int`. That rules out the statement being another labeled-statement (identifier, `case`, or `default`). So it needs to be some kind of unlabled-statement. It's not an expression-statement. It's not a primary block (doesn't start with `{`. `if`/`switch`, or `do`/`while`/`for`), nor is it a jump-statement (`goto`, `continue`, `break`, or `return`).

So I think we're correct to reject this as grammatically invalid when parsing, aren't we?

Or was "A label shall be translated as if it were followed by a null statement" (6.8.2p2) supposed to apply so it's as-if every label was written: `label: ;`? If so, I think that might be a tad subtle because it's in a Semantics section (which generally talks about semantic behavior and not parsing behavior), but it would kind of solve the grammar issue (it's an expression-statement followed by a declaration at that point, but then Semantics sections can change parsing rules and that seems non-obvious).

CC @Izaron

**Comment by uecker** [comment] 2023-03-19 14:46
The relevant part of the grammar is 6.8.2.
```
  compound-statement { block-item-list opt }

  block-item-list:
    block-item
    block-item-list block-item

 block-item:
    declaration
    unlabeled-statement
    label
```

So inside a compound statement there are no labeled statements but labels, declarations, and unlabeled-statements can be mixed freely. The grammar is structured differently than in C++  but it should still be the same.

**Comment by AaronBallman** [comment] 2023-03-19 16:17
Thank you Martin, that was the key bit I think we missed.

**Comment by Izaron** [comment] 2023-03-19 21:14
@AaronBallman It came out harder than I thought. I sent some hack, it seems to work, but it has three TODOs to fix yet =(

https://reviews.llvm.org/D146393

**Comment by AaronBallman** [comment] 2023-10-19 15:04
Resolving this as a duplicate of #53692

**Closed by AaronBallman** 2023-10-19 15:04 UTC
Labels: c23, clang:frontend, rejects-valid
