### ISSUE TITLE
TestConcurrentVFork.py in lldb times out on the build kits

### ISSUE THREAD

**Issue by feg208** [llvm/llvm-project#104609] opened 2024-08-16 15:52 UTC
In the process of completing:

https://github.com/llvm/llvm-project/pull/104109 the referenced test timed out. This should be investigated and fixed. The log with the timeout is attached
[github-pull-requests_build_92234_linux-linux-x64.log](https://github.com/user-attachments/files/16638939/github-pull-requests_build_92234_linux-linux-x64.log)

**Comment by DavidSpickett** [comment] 2024-08-19 13:45
See also https://github.com/llvm/llvm-project/issues/85084, we have disabled it on Linaro's builders.

**Comment by DavidSpickett** [comment] 2024-09-25 09:09
I've just disabled the test everywhere, so I'm going to close this as a duplicate of https://github.com/llvm/llvm-project/issues/85084.

**Closed by DavidSpickett** 2024-09-25 09:09 UTC
Labels: lldb, test-suite
