### ISSUE TITLE
Crashed under O2 with "CoroInstr.h:186: void llvm::CoroIdInst::setCoroutineSelf(): Assertion `isa<ConstantPointerNull>(getArgOperand(CoroutineArg)) && "Coroutine argument is already assigned"' failed."

### ISSUE THREAD

**Issue by Hatsunespica** [llvm/llvm-project#56525] opened 2022-07-14 05:01 UTC
[llvm-project/llvm/test/Transforms/Coroutines/coro-frame-reuse-alloca-02.ll](https://github.com/llvm/llvm-project/blob/main/llvm/test/Transforms/Coroutines/coro-frame-reuse-alloca-02.ll)

This test already failed under O2, but it can pass `opt` verify. 

I reduced this case so it looks like this:
https://gcc.godbolt.org/z/nKjbn3doT

```llvm
%"struct.task::promise_type" = type { i8 }
%struct.awaitable = type { i8 }
declare i8* @malloc(i64)
define void @a() "coroutine.presplit"="1" {
entry:
  %__promise = alloca %"struct.task::promise_type", align 1
  %ref.tmp7 = alloca %struct.awaitable, align 1
  %ref.tmp18 = alloca %struct.awaitable, align 1
  %0 = alloca i8
  %1 = call token @llvm.coro.id(i32 16, i8* nonnull %0, i8* bitcast (void ()* @a to i8*), i8* null)
  br label %init.ready
init.ready:
  %2 = call noalias nonnull i8* @llvm.coro.begin(token %1, i8* null)
  call void @llvm.lifetime.start.p0i8(i64 1, i8* nonnull %0)
  br label %if.then
if.then:
  %save = call token @llvm.coro.save(i8* null)
  %suspend = call i8 @llvm.coro.suspend(token %save, i1 false)
  switch i8 %suspend, label %coro.ret [
    i8 0, label %await.ready
    i8 1, label %cleanup1
  ]
await.ready:
  br label %cleanup1
cleanup1:
  br label %cleanup
cleanup:
  call i8* @llvm.coro.free(token %1, i8* %2)
  br label %coro.ret
coro.ret:
  call i1 @llvm.coro.end(i8* null, i1 false)
  ret void
}

declare token @llvm.coro.id(i32, i8* readnone, i8* nocapture readonly, i8*)
declare i1 @llvm.coro.alloc(token) 
declare i64 @llvm.coro.size.i64() 
declare i8* @llvm.coro.begin(token, i8* writeonly) 
declare token @llvm.coro.save(i8*) 
declare i8* @llvm.coro.frame() 
declare i8 @llvm.coro.suspend(token, i1) 
declare i8* @llvm.coro.free(token, i8* nocapture readonly) 
declare i1 @llvm.coro.end(i8*, i1) 
declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) 
```

However, the error message shown at the website is slightly different from my local running. 
My local error message:
```console
opt: /home/spica/GitRepo/llvm-project/llvm/lib/Transforms/Coroutines/CoroInstr.h:186: void llvm::CoroIdInst::setCoroutineSelf(): Assertion `isa<ConstantPointerNull>(getArgOperand(CoroutineArg)) && "Coroutine argument is already assigned"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: opt /home/spica/tmp/coro-frame-reuse-alloca-02.ll -O2
 #0 0x00007f3230e500d4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00007f3230e4d114 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f32308570c0 (/lib/x86_64-linux-gnu/libc.so.6+0x430c0)
 #3 0x00007f323085703b raise /build/glibc-sMfBJT/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #4 0x00007f3230836859 abort /build/glibc-sMfBJT/glibc-2.31/stdlib/abort.c:81:7
 #5 0x00007f3230836729 get_sysdep_segment_value /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:509:8
 #6 0x00007f3230836729 _nl_load_domain /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:970:34
 #7 0x00007f3230848006 (/lib/x86_64-linux-gnu/libc.so.6+0x34006)
 #8 0x00007f322fdee4b2 (anonymous namespace)::Lowerer::lowerEarlyIntrinsics(llvm::Function&) CoroEarly.cpp:0:0
 #9 0x00007f322fdeeb15 llvm::CoroEarlyPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/local/bin/../lib/../lib/libLLVMCoroutines.so.15git+0x1eb15)
#10 0x00007f3233b5f7b6 llvm::detail::PassModel<llvm::Module, llvm::CoroEarlyPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/local/bin/../lib/libLLVMPasses.so.15git+0xa87b6)
#11 0x00007f32311c5f71 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/local/bin/../lib/libLLVMCore.so.15git+0x2d6f71)
#12 0x000056541d0ec345 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::StringRef>, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool) (/usr/local/bin/opt+0x34345)
#13 0x000056541d0dca7b main (/usr/local/bin/opt+0x24a7b)
#14 0x00007f32308380b3 __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:342:3
#15 0x000056541d0dd4fe _start (/usr/local/bin/opt+0x254fe)
Aborted (core dumped)
```
cc @regehr

**Comment by ChuanqiXu9** [comment] 2022-08-01 08:21
This may not be a bug. [coro-frame-reuse-alloca-02.ll](https://github.com/llvm/llvm-project/blob/main/llvm/test/Transforms/Coroutines/coro-frame-reuse-alloca-02.ll) is already transformed by CoroEarly and if we pass it to `opt -O2`, it would be transformed again by CoroEarly. This is not by design.

By design, the IR transformed by CoroEarly should be transformed by CoroSplit then. Maybe this could be a defect that we could treat it more friendly.

**Comment by Hatsunespica** [comment] 2022-08-02 07:12
Aha, got it. Thanks for your explanation!
Except `CoroEarly` pass, are there other passes I shouldn't run on tests under coroutines folder?

**Comment by Hatsunespica** [comment] 2022-08-02 07:13
Because I am trying to find bugs hidden in different optimization passes, I won't run `CoroEarly`  pass on these test files!

**Comment by ChuanqiXu9** [comment] 2022-08-02 07:31
> Except CoroEarly pass, are there other passes I shouldn't run on tests under coroutines folder?

I am not sure. According to my understanding, there is not yet. But I am not sure about it.

> Because I am trying to find bugs hidden in different optimization passes, I won't run CoroEarly pass on these test files!

It may not be a perfect solution but it is workable. The test files in `Coroutines`  contain other passes too. But it wouldn't affect the research result personally.

---

It looks OK to close the issue.

**Closed by ChuanqiXu9** 2022-08-02 07:31 UTC
Labels: llvm:crash, llvm:optimizations, coroutines
