### ISSUE TITLE
clang-16 Segmentation fault

### ISSUE THREAD

**Issue by ikitayama** [llvm/llvm-project#56978] opened 2022-08-07 01:16 UTC
```console
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /p/project/cjinb33/kitayama1/dev/clang/bin/clang-16 -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name event_delivery_manager.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fcoverage-compilation-dir=/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/nestkernel -resource-dir /p/project/cjinb33/kitayama1/dev/clang/lib/clang/16.0.0 -dependency-file CMakeFiles/nestkernel.dir/event_delivery_manager.cpp.o.d -MT nestkernel/CMakeFiles/nestkernel.dir/event_delivery_manager.cpp.o -sys-header-deps -D nestkernel_EXPORTS -I /p/software/jurecadc/stages/2022/software/libreadline/8.1-GCCcore-11.2.0/include -I /p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/thirdparty -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/libnestutil -I /p/scratch/cjinb33/kitayama1/build/nest-clang-offload/libnestutil -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/sli -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel/spatial -I/p/software/jurecadc/stages/2022/software/Z3/4.8.12-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/GMP/6.2.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/hwloc/2.5.0-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/libpciaccess/0.16-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/numactl/2.0.14/include -I/p/software/jurecadc/stages/2022/software/DB/18.1.40-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/libreadline/8.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/gettext/0.21-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include/libxml2 -I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/expat/2.4.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/ICU/70.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/extras/CUPTI/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/include -I/p/software/jurecadc/stages/2022/software/libarchive/3.5.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/XZ/5.2.5-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/cURL/7.78.0-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/OpenSSL/1.1/include -I/p/software/jurecadc/stages/2022/software/bzip2/1.0.8-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/ncurses/6.2-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/binutils/2.37-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/zlib/1.2.11-GCCcore-11.2.0/include -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/bin/../include/x86_64-unknown-linux-gnu/c++/v1 -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/bin/../include/c++/v1 -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/bin/../include/x86_64-unknown-linux-gnu/c++/v1 -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/bin/../include/c++/v1 -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/16.0.0/include -internal-isystem /usr/local/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/16.0.0/include -internal-isystem /usr/local/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /p/software/jurecadc/stages/2022/software/CUDA/11.5/include -O2 -Wno-unknown-cuda-version -Wall -std=c++17 -fdeprecated-macro -fdebug-compilation-dir=/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/nestkernel -ferror-limit 19 -fopenmp -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -disable-llvm-passes -fopenmp-targets=nvptx64-nvidia-cuda -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/event_delivery_manager-721ace.bc -x c++ /p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel/event_delivery_manager.cpp
1.	<eof> parser at end of file
2.	/p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel/event_delivery_manager.h:250:8: instantiating function definition 'nest::EventDeliveryManager::gather_spike_data_<nest::OffGridSpikeData>'
 #0 0x0000000002fc9771 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000000002fc7074 SignalHandler(int) Signals.cpp:0:0
 #2 0x000014b3ed925c20 __restore_rt sigaction.c:0:0
 #3 0x000000000098c844 getCanonicalDecl(clang::ValueDecl const*) (.cold) SemaOpenMP.cpp:0:0
 #4 0x00000000052452d8 (anonymous namespace)::DSAStackTy::hasDSA(clang::ValueDecl*, llvm::function_ref<bool (llvm::omp::Clause, bool, (anonymous namespace)::DefaultDataSharingAttributes)>, llvm::function_ref<bool (llvm::omp::Directive)>, bool) const SemaOpenMP.cpp:0:0
 #5 0x0000000005247a57 clang::Sema::isOpenMPRebuildMemberExpr(clang::ValueDecl*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x5247a57)
 #6 0x0000000005508cb6 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformMemberExpr(clang::MemberExpr*) SemaTemplateInstantiate.cpp:0:0
 #7 0x00000000054e64da clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCallExpr(clang::CallExpr*) SemaTemplateInstantiate.cpp:0:0
 #8 0x000000000550caf1 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformStmt(clang::Stmt*, clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::StmtDiscardKind) SemaTemplateInstantiate.cpp:0:0
 #9 0x000000000550e3db clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#10 0x000000000550f37f clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformIfStmt(clang::IfStmt*) SemaTemplateInstantiate.cpp:0:0
#11 0x000000000550e3db clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#12 0x000000000550f91a clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformOMPExecutableDirective(clang::OMPExecutableDirective*) SemaTemplateInstantiate.cpp:0:0
#13 0x0000000005511767 clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformOMPSingleDirective(clang::OMPSingleDirective*) SemaTemplateInstantiate.cpp:0:0
#14 0x000000000550e3db clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#15 0x000000000550c97e clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformWhileStmt(clang::WhileStmt*) SemaTemplateInstantiate.cpp:0:0
#16 0x000000000550e3db clang::TreeTransform<(anonymous namespace)::TemplateInstantiator>::TransformCompoundStmt(clang::CompoundStmt*, bool) SemaTemplateInstantiate.cpp:0:0
#17 0x000000000551251c clang::Sema::SubstStmt(clang::Stmt*, clang::MultiLevelTemplateArgumentList const&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x551251c)
#18 0x00000000055539c5 clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x55539c5)
#19 0x0000000005551adf clang::Sema::PerformPendingInstantiations(bool) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x5551adf)
#20 0x0000000004d24631 clang::Sema::ActOnEndOfTranslationUnitFragment(clang::Sema::TUFragmentKind) (.part.0) Sema.cpp:0:0
#21 0x0000000004d24d6d clang::Sema::ActOnEndOfTranslationUnit() (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x4d24d6d)
#22 0x0000000004be94dd clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x4be94dd)
#23 0x0000000004bdac1a clang::ParseAST(clang::Sema&, bool, bool) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x4bdac1a)
#24 0x0000000003a39149 clang::FrontendAction::Execute() (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3a39149)
#25 0x00000000039c7f3b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x39c7f3b)
#26 0x0000000003aeeaa0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3aeeaa0)
#27 0x0000000000a51a24 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0xa51a24)
#28 0x0000000000a4ae45 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#29 0x0000000000a4d546 clang_main(int, char**) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0xa4d546)
#30 0x000014b3ecbb7493 __libc_start_main (/usr/lib64/libc.so.6+0x23493)
#31 0x0000000000a4a93e _start (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0xa4a93e)
clang-16: error: unable to execute command: Segmentation fault
clang-16: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 16.0.0 (https://github.com/llvm/llvm-project 967f95fb074deadfb1109cec5f42d83db7eff00b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /p/project/cjinb33/kitayama1/dev/clang/bin
clang-16: note: diagnostic msg:
```

**Comment by ikitayama** [comment] 2022-08-07 01:32
[event_delivery_manager-276db1.sh.txt](https://github.com/llvm/llvm-project/files/9276000/event_delivery_manager-276db1.sh.txt)
[event_delivery_manager-6237cf.cpp.txt](https://github.com/llvm/llvm-project/files/9276001/event_delivery_manager-6237cf.cpp.txt)
[event_delivery_manager-4bb37b.cpp.txt](https://github.com/llvm/llvm-project/files/9276002/event_delivery_manager-4bb37b.cpp.txt)

**Comment by ikitayama** [comment] 2022-08-07 03:52
My code was wrong.

**Comment by EugeneZelenko** [comment] 2022-08-07 04:10
@ikitayama: Even you your code was invalid, Clang should not crash. I think it makes sense to reopen issue.

**Comment by ikitayama** [comment] 2022-08-07 04:10
Done.

**Comment by ikitayama** [comment] 2022-08-07 04:48
My application uses OpenMP library to offload some code to the device.

**Comment by ikitayama** [comment] 2022-08-07 06:48
How do I notify this to the openmp project group?

**Comment by DAC324** [comment] 2022-08-08 08:30
Here is another example file from the Chromium project which causes a similar crash although there are no obvious errors. Clang 15.0.0 compiles that same file without problems. 
[prefetched_signed_exchange_manager.cc.gz](https://github.com/llvm/llvm-project/files/9280205/prefetched_signed_exchange_manager.cc.gz)

**Comment by inclyc** [comment] 2022-08-10 01:11
Seems duplicate to https://github.com/llvm/llvm-project/issues/56884 and fixed in https://github.com/llvm/llvm-project/commit/a7bca18bc50cd2483fded0c77706980b2721ce6a, I cannot reproduce at the newest branch.

**Closed** 2022-08-10 01:20 UTC
Labels: duplicate, clang:frontend, crash-on-invalid

**Comment by inclyc** [comment] 2022-08-10 01:45
> How do I notify this to the openmp (offloading) project group?

Maybe unnecessary because this is a bug caused by clang (and now fixed)

**Comment by ikitayama** [comment] 2022-08-10 08:01
I confirm that I don't see the crash any more.

**Comment by inclyc** [comment] 2022-08-10 08:15
> I confirm that I don't see the crash any more.

Thanks, feel free to reopen this issue if you could see such crash in some practice.

**Comment by ikitayama** [comment] 2022-08-10 08:57
I take it back, I still see it with Clang:

```
$ clang -v
clang version 16.0.0 (https://github.com/llvm/llvm-project 3bba12a81e242359580fa322cf1a9a0a43b461e6)
```

**Comment by inclyc** [comment] 2022-08-10 09:16
> I take it back, I still see it with Clang:
> 
> ```
> $ clang -v
> clang version 16.0.0 (https://github.com/llvm/llvm-project 3bba12a81e242359580fa322cf1a9a0a43b461e6)
> ```


Could you give us more information about stack trace / compile commands / source file? So we can reproduce locally. I've tried to compile 

>[event_delivery_manager-6237cf.cpp.txt](https://github.com/llvm/llvm-project/files/9276001/event_delivery_manager-6237cf.cpp.txt)

and didn't see such issue.

**Comment by ikitayama** [comment] 2022-08-12 01:17
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /p/project/cjinb33/kitayama1/dev/clang/bin/clang-16 -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-unknown-linux-gnu -S -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name modelsmodule.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -ffp-contract=on -fno-rounding-math -fno-verbose-asm -no-integrated-as -mlink-builtin-bitcode /p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/libdevice/libdevice.10.bc -target-sdk-version=11.5 -mlink-builtin-bitcode /p/project/cjinb33/kitayama1/dev/clang/lib/libomptarget-nvptx-sm_35.bc -target-cpu sm_35 -target-feature +ptx75 -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=line-directives-only -dwarf-version=2 -debugger-tuning=gdb -fno-dwarf-directory-asm -resource-dir /p/project/cjinb33/kitayama1/dev/clang/lib/clang/16.0.0 -dependency-file CMakeFiles/models.dir/modelsmodule.cpp.o.d -MT models/CMakeFiles/models.dir/modelsmodule.cpp.o -sys-header-deps -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/16.0.0/include/openmp_wrappers -include __clang_openmp_device_functions.h -D models_EXPORTS -I /p/software/jurecadc/stages/2022/software/libreadline/8.1-GCCcore-11.2.0/include -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/thirdparty -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/libnestutil -I /p/scratch/cjinb33/kitayama1/build/nest-clang-offload/libnestutil -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/sli -I /p/scratch/cjinb33/kitayama1/projects/nest-simulator/nestkernel -I/p/software/jurecadc/stages/2022/software/DB/18.1.40-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/libreadline/8.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/gettext/0.21-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include/libxml2 -I/p/software/jurecadc/stages/2022/software/libxml2/2.9.10-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/expat/2.4.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/Boost/1.78.0-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/ICU/70.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/nvvm/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/extras/CUPTI/include -I/p/software/jurecadc/stages/2022/software/CUDA/11.5/include -I/p/software/jurecadc/stages/2022/software/libarchive/3.5.1-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/XZ/5.2.5-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/cURL/7.78.0-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/OpenSSL/1.1/include -I/p/software/jurecadc/stages/2022/software/bzip2/1.0.8-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/ncurses/6.2-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/binutils/2.37-GCCcore-11.2.0/include -I/p/software/jurecadc/stages/2022/software/zlib/1.2.11-GCCcore-11.2.0/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0 -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/x86_64-pc-linux-gnu -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/backward -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0 -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/x86_64-pc-linux-gnu -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/backward -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/16.0.0/include -internal-isystem /usr/local/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -internal-isystem /p/software/jurecadc/stages/2022/software/CUDA/11.5/include -internal-isystem /p/project/cjinb33/kitayama1/dev/clang/lib/clang/16.0.0/include -internal-isystem /usr/local/include -internal-isystem /p/software/jurecadc/stages/2022/software/GCCcore/11.2.0/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -O2 -Wno-unknown-cuda-version -Wall -std=c++17 -fdeprecated-macro -fdebug-compilation-dir=/p/scratch/cjinb33/kitayama1/build/nest-clang-offload/models -ferror-limit 19 -fvisibility protected -fopenmp -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -fopenmp-is-device -fopenmp-host-ir-file-path /tmp/modelsmodule-6e1002.bc -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/modelsmodule-937850.s -x c++ /p/scratch/cjinb33/kitayama1/projects/nest-simulator/models/modelsmodule.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/p/scratch/cjinb33/kitayama1/projects/nest-simulator/models/modelsmodule.cpp'.
4.	Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_ZNK4nest9ConnectorINS_11GapJunctionINS_24TargetIdentifierPtrRportEEEE19get_target_node_idsEimRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt6vectorImNSt3pmr21polymorphic_allocatorImEEE'
 #0 0x0000000002feeb71 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000000002fec494 SignalHandler(int) Signals.cpp:0:0
 #2 0x00001526a4979c20 __restore_rt sigaction.c:0:0
 #3 0x0000000000962dee llvm::NVPTXTargetLowering::LowerCall(llvm::TargetLowering::CallLoweringInfo&, llvm::SmallVectorImpl<llvm::SDValue>&) const (.cold) NVPTXISelLowering.cpp:0:0
 #4 0x0000000003f45a4a llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3f45a4a)
 #5 0x0000000003f4992f llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3f4992f)
 #6 0x0000000003f588ab llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3f588ab)
 #7 0x0000000003f83410 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3f83410)
 #8 0x0000000003f83a3f llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3f83a3f)
 #9 0x0000000003fef766 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3fef766)
#10 0x0000000003ff0c08 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3ff0c08)
#11 0x0000000003ff31a2 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.0) SelectionDAGISel.cpp:0:0
#12 0x00000000023563b4 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#13 0x00000000027e1360 llvm::FPPassManager::runOnFunction(llvm::Function&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x27e1360)
#14 0x00000000027e14cc llvm::FPPassManager::runOnModule(llvm::Module&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x27e14cc)
#15 0x00000000027e1e4f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x27e1e4f)
#16 0x000000000335c585 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x335c585)
#17 0x0000000004122ff1 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) crtstuff.c:0:0
#18 0x0000000004c41189 clang::ParseAST(clang::Sema&, bool, bool) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x4c41189)
#19 0x0000000003a9ff59 clang::FrontendAction::Execute() (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3a9ff59)
#20 0x0000000003a2ed3b clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3a2ed3b)
#21 0x0000000003b555a0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0x3b555a0)
#22 0x0000000000a70ea4 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0xa70ea4)
#23 0x0000000000a6a615 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#24 0x0000000000a6c9a6 clang_main(int, char**) (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0xa6c9a6)
#25 0x00001526a3c0b493 __libc_start_main (/usr/lib64/libc.so.6+0x23493)
#26 0x0000000000a69dbe _start (/p/project/cjinb33/kitayama1/dev/clang/bin/clang-16+0xa69dbe)
clang-16: error: unable to execute command: Segmentation fault
clang-16: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 16.0.0 (https://github.com/llvm/llvm-project 3bba12a81e242359580fa322cf1a9a0a43b461e6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /p/project/cjinb33/kitayama1/dev/clang/bin
clang-16: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-16: note: diagnostic msg: /tmp/modelsmodule-320c90.cpp
clang-16: note: diagnostic msg: /tmp/modelsmodule-20e30e.cpp
clang-16: note: diagnostic msg: /tmp/modelsmodule-320c90.sh
clang-16: note: diagnostic msg:

********************
```

**Comment by ikitayama** [comment] 2022-08-12 01:18
[modelsmodule-320c90.sh.gz](https://github.com/llvm/llvm-project/files/9313059/modelsmodule-320c90.sh.gz)
[modelsmodule-320c90.cpp.gz](https://github.com/llvm/llvm-project/files/9313062/modelsmodule-320c90.cpp.gz)
[modelsmodule-20e30e.cpp.gz](https://github.com/llvm/llvm-project/files/9313065/modelsmodule-20e30e.cpp.gz)

**Comment by EugeneZelenko** [comment] 2022-08-12 01:28
@ikitayama: Please file this as different issue because crash happened in backend.
