### ISSUE TITLE
Clang-format: QualifierAlignment moves const to wrong location

### ISSUE THREAD

**Issue by JVApen** [llvm/llvm-project#61189] opened 2023-03-05 10:14 UTC
````
void f()
{
      NS::C const *p = &v;
}
````
becomes
````
void f()
{
      NS const ::C *p = &v;
}
````
instead of
````
void f()
{
      const NS::C *p = &v;
}
````

[reproduction.zip](https://github.com/llvm/llvm-project/files/10891555/reproduction.zip)

**Comment by JVApen** [comment] 2023-03-05 10:16
Found on clang-format 16-rc2, after manual correction it stays stable.

**Comment by rymiel** [comment] 2023-03-05 11:12
Duplicate of https://github.com/llvm/llvm-project/issues/60898

**Closed** 2023-03-05 11:41 UTC
Labels: duplicate, clang-format
