### ISSUE TITLE
Incorrectly accepting `Class<TParam>()` constructor which was made an explicit error in C++20

### ISSUE THREAD

**Issue by whisperity** [llvm/llvm-project#55164] opened 2022-04-28 11:31 UTC
> See [GCC #105419](http://gcc.gnu.org/bugzilla/show_bug.cgi?id=105419).

It seems that C++20 made

```c++
template <class T>
struct C {
  C<T>(T) {}
};
```

invalid, but as of Clang 14.0.0, it is still accepted.

Godbolt: http://godbolt.org/z/59azWTKqM
Godbolt for falsely assumed regression in GCC: http://godbolt.org/z/rrbae9P5d

**Comment by cor3ntin** [comment] 2024-01-21 17:23
Duplicate of #58635

**Closed by cor3ntin** 2024-01-21 17:23 UTC
Labels: c++, c++20, clang:frontend, accepts-invalid
