### ISSUE TITLE
[17.0.6] FAIL: LLVM :: CodeGen/RISCV/xtheadmempair.ll on armv7-linux

### ISSUE THREAD

**Issue by misuzu** [llvm/llvm-project#91336] opened 2024-05-07 14:16 UTC
```
********************
FAIL: LLVM :: CodeGen/RISCV/xtheadmempair.ll (16847 of 49006)
******************** TEST 'LLVM :: CodeGen/RISCV/xtheadmempair.ll' FAILED ********************
Script:
--
: 'RUN: at line 2';   /build/llvm-src-17.0.6/llvm/build/bin/llc -mtriple=riscv32 -mattr=+xtheadmempair -verify-machineinstrs < /build/llvm-src-17.0.6/llvm/test/CodeGen/RISCV/xtheadmempair.ll    | /build/llvm-src-17.0.6/llvm/build/bin/FileCheck /build/llvm-src-17.0.6/llvm/test/CodeGen/RISCV/xtheadmempair.ll -check-prefix=RV32XTHEADMEMPAIR
: 'RUN: at line 4';   /build/llvm-src-17.0.6/llvm/build/bin/llc -mtriple=riscv64 -mattr=+xtheadmempair -verify-machineinstrs < /build/llvm-src-17.0.6/llvm/test/CodeGen/RISCV/xtheadmempair.ll    | /build/llvm-src-17.0.6/llvm/build/bin/FileCheck /build/llvm-src-17.0.6/llvm/test/CodeGen/RISCV/xtheadmempair.ll -check-prefix=RV64XTHEADMEMPAIR
--
Exit Code: 2

Command Output (stderr):
--
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /build/llvm-src-17.0.6/llvm/build/bin/llc -mtriple=riscv32 -mattr=+xtheadmempair -verify-machineinstrs
1.      Running pass 'Function Pass Manager' on module '<stdin>'.
2.      Running pass 'Expand large div/rem' on function '@lwd'
 #0 0xfffffffff0c1c7a0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/build/llvm-src-17.0.6/llvm/build/lib/libLLVM-17.so+0x9377a0)
 #1 0xfffffffff0c19f38 SignalHandler(int) Signals.cpp:0:0
 #2 0xffffffffeff40ca0 __default_sa_restorer (/nix/store/s9zfx4ayrgvida0i9sx7nc3ibikzyxlr-glibc-2.39-31/lib/libc.so.6+0x3aca0)
 #3 0xfffffffff446c528 llvm::RISCVTargetLowering::RISCVTargetLowering(llvm::TargetMachine const&, llvm::RISCVSubtarget const&) (/build/llvm-src-17.0.6/llvm/build/lib/libLLVM-17.so+0x4187528)
 #4 0xfffffffff44c1d28 llvm::RISCVSubtarget::RISCVSubtarget(llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::StringRef, llvm::StringRef, unsigned int, unsigned int, llvm::TargetMachine const&) (/build/llvm-src-17.0.6/llvm/build/lib/libLLVM-17.so+0x41dcd28)
 #5 0xfffffffff44c8038 llvm::RISCVTargetMachine::getSubtargetImpl(llvm::Function const&) const (/build/llvm-src-17.0.6/llvm/build/lib/libLLVM-17.so+0x41e3038)
 #6 0xfffffffff0f83c98 (anonymous namespace)::ExpandLargeDivRemLegacyPass::runOnFunction(llvm::Function&) ExpandLargeDivRem.cpp:0:0
 #7 0xfffffffff0db0d3c llvm::FPPassManager::runOnFunction(llvm::Function&) (/build/llvm-src-17.0.6/llvm/build/lib/libLLVM-17.so+0xacbd3c)
 #8 0xfffffffff0db1120 llvm::FPPassManager::runOnModule(llvm::Module&) (/build/llvm-src-17.0.6/llvm/build/lib/libLLVM-17.so+0xacc120)
 #9 0xfffffffff0db1ad8 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/build/llvm-src-17.0.6/llvm/build/lib/libLLVM-17.so+0xaccad8)
#10 0x000248f8 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#11 0x0001c0b0 main (/build/llvm-src-17.0.6/llvm/build/bin/llc+0x1c0b0)
#12 0xffffffffeff298cc __libc_start_call_main (/nix/store/s9zfx4ayrgvida0i9sx7nc3ibikzyxlr-glibc-2.39-31/lib/libc.so.6+0x238cc)
#13 0xffffffffeff299c0 __libc_start_main@GLIBC_2.4 (/nix/store/s9zfx4ayrgvida0i9sx7nc3ibikzyxlr-glibc-2.39-31/lib/libc.so.6+0x239c0)
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /build/llvm-src-17.0.6/llvm/build/bin/FileCheck /build/llvm-src-17.0.6/llvm/test/CodeGen/RISCV/xtheadmempair.ll -check-prefix=RV32XTHEADMEMPAIR

--
```

**Comment by EugeneZelenko** [comment] 2024-05-07 14:18
Could you please try 18 or `main` branch?

**Comment by dtcxzyw** [comment] 2024-05-07 14:22
Duplicate of https://github.com/llvm/llvm-project/issues/62195.

**Closed** 2024-05-07 14:27 UTC
Labels: duplicate, backend:RISC-V, crash
