### ISSUE TITLE
clang-format AlignConsecutiveAssignments with preprocessor directives not working correctly

### ISSUE THREAD

**Issue by andli197** [llvm/llvm-project#62399] opened 2023-04-27 08:37 UTC
It seems that Clang-Format is grouping many preprocessor directives when formatting code. Especially `#else` statements along with `AlignConsecutiveAssignments`.

`.clang-format`:
```yml
---
Language: Cpp
AlignConsecutiveAssignments: true
...
```
Code example:
```cpp
#include <string>

const std::string GetName() {
#if _WIN32
  constexpr static char kMyName[] = "Foo";
#else 
  constexpr static char kMyName[] = "NewName";
#endif 
  return kMyName;
}

int main() {
#if _WIN32
  static constexpr char kVar[] = "MyFancyWindowsVariable";
#else
  static constexpr char kVar[] = "MyOtherFancyVariable";
#endif
  return 0;
}
```

Applying the style to the code above will render an alignment of the value for `kVar[]` in the `#else` statement to be aligned with the variable assignment of `kMyName[]` from the `#else` statement in the function `GetName()`.
Renaming `kMyName[]` to a shorter name is causing the reformatting to follow this. And if the `GetName` method is completley removed no alignment is made, hence my suspicion that preprocessors `else` statements are mixed up.

After applying the style:
```cpp
#include <string>

const std::string GetName() {
#if _WIN32
  constexpr static char kMyName[] = "Foo";
#else 
  constexpr static char kMyName[] = "NewName";
#endif 
  return kMyName;
}

int main() {
#if _WIN32
  static constexpr char kVar[] = "MyFancyWindowsVariable";
#else
  static constexpr char kVar[]    = "MyOtherFancyVariable";
#endif
  return 0;
}
```

**Comment by andli197** [comment] 2023-04-27 08:38
I've tested this with llvm 9.0.0 and 14.0.6 and the issue is present in both.

**Comment by EugeneZelenko** [comment] 2023-04-27 14:20
Could you please try 16 or `main` branch?

**Comment by rymiel** [comment] 2023-04-27 20:02
Duplicate of #61498

**Closed by rymiel** 2023-04-27 20:02 UTC
Labels: clang-format
