### ISSUE TITLE
14.0.0 clang: cmake adds libcmake.so.13 symlink

### ISSUE THREAD

**Issue by kloczek** [llvm/llvm-project#55012] opened 2022-04-21 13:00 UTC
Looks like sometbing has not been updated and clang cmake uses and installs `libcmake.so.13` instead `libcmake.so.14`
From $DESTDIR after `install` target execution
```console
[tkloczko@devel-g2v clang-14.0.0-2.fc35.x86_64]$ ls -l /home/tkloczko/rpmbuild/BUILDROOT/clang-14.0.0-2.fc35.x86_64/usr/lib64
total 69764
drwxr-xr-x. 1 tkloczko tkloczko       16 Apr 21 12:44 clang
drwxr-xr-x. 1 tkloczko tkloczko       10 Apr 21 12:44 cmake
lrwxrwxrwx. 1 tkloczko tkloczko       20 Apr 21 12:44 libclang-cpp.so -> libclang-cpp.so.14.0
-rwxr-xr-x. 1 tkloczko tkloczko 46607768 Apr 21 12:49 libclang-cpp.so.14.0
lrwxrwxrwx. 1 tkloczko tkloczko       14 Apr 21 12:44 libclang.so -> libclang.so.13      <<<<== HERE
lrwxrwxrwx. 1 tkloczko tkloczko       18 Apr 21 12:44 libclang.so.13 -> libclang.so.14.0.0
-rwxr-xr-x. 1 tkloczko tkloczko 24817192 Apr 21 12:46 libclang.so.14.0.0
```
And from build tree
```console
[tkloczko@devel-g2v x86_64-redhat-linux-gnu]$ pwd; echo; grep -r libclang.so.13
/home/tkloczko/rpmbuild/BUILD/clang-14.0.0.src/x86_64-redhat-linux-gnu

tools/libclang/CMakeFiles/libclang.dir/link.txt:/usr/bin/g++ -fPIC -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -pedantic -Wno-long-long -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG  -Wl,--gc-sections -Wl,--version-script,/home/tkloczko/rpmbuild/BUILD/clang-14.0.0.src/tools/libclang/libclang.map -Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1 -Wl,-z,defs -Wl,-z,nodelete -shared -Wl,-soname,libclang.so.13 -o ../../lib64/libclang.so.14.0.0 CMakeFiles/libclang.dir/ARCMigrate.cpp.o CMakeFiles/libclang.dir/BuildSystem.cpp.o CMakeFiles/libclang.dir/CIndex.cpp.o CMakeFiles/libclang.dir/CIndexCXX.cpp.o CMakeFiles/libclang.dir/CIndexCodeCompletion.cpp.o CMakeFiles/libclang.dir/CIndexDiagnostic.cpp.o CMakeFiles/libclang.dir/CIndexHigh.cpp.o CMakeFiles/libclang.dir/CIndexInclusionStack.cpp.o CMakeFiles/libclang.dir/CIndexUSRs.cpp.o CMakeFiles/libclang.dir/CIndexer.cpp.o CMakeFiles/libclang.dir/CXComment.cpp.o CMakeFiles/libclang.dir/CXCursor.cpp.o CMakeFiles/libclang.dir/CXIndexDataConsumer.cpp.o CMakeFiles/libclang.dir/CXCompilationDatabase.cpp.o CMakeFiles/libclang.dir/CXLoadedDiagnostic.cpp.o CMakeFiles/libclang.dir/CXSourceLocation.cpp.o CMakeFiles/libclang.dir/CXStoredDiagnostic.cpp.o CMakeFiles/libclang.dir/CXString.cpp.o CMakeFiles/libclang.dir/CXType.cpp.o CMakeFiles/libclang.dir/Indexing.cpp.o CMakeFiles/libclang.dir/FatalErrorHandler.cpp.o CMakeFiles/libclang.dir/Rewrite.cpp.o  ../../lib64/libclangAST.a ../../lib64/libclangBasic.a ../../lib64/libclangDriver.a ../../lib64/libclangFrontend.a ../../lib64/libclangIndex.a ../../lib64/libclangLex.a ../../lib64/libclangRewrite.a ../../lib64/libclangSema.a ../../lib64/libclangSerialization.a ../../lib64/libclangTooling.a ../../lib64/libclangARCMigrate.a -ldl ../../lib64/libclangFormat.a ../../lib64/libclangToolingInclusions.a ../../lib64/libclangToolingCore.a ../../lib64/libclangFrontend.a ../../lib64/libclangDriver.a ../../lib64/libclangParse.a ../../lib64/libclangRewrite.a ../../lib64/libclangSerialization.a ../../lib64/libclangSema.a ../../lib64/libclangEdit.a ../../lib64/libclangAnalysis.a ../../lib64/libclangASTMatchers.a ../../lib64/libclangAST.a ../../lib64/libclangLex.a ../../lib64/libclangBasic.a /usr/lib64/libLLVM-14.so.0
tools/libclang/CMakeFiles/libclang.dir/cmake_clean.cmake:  "../../lib64/libclang.so.13"
tools/libclang/CMakeFiles/libclang.dir/build.make:      cd /home/tkloczko/rpmbuild/BUILD/clang-14.0.0.src/x86_64-redhat-linux-gnu/tools/libclang && $(CMAKE_COMMAND) -E cmake_symlink_library ../../lib64/libclang.so.14.0.0 ../../lib64/libclang.so.13 ../../lib64/libclang.so
tools/libclang/CMakeFiles/libclang.dir/build.make:lib64/libclang.so.13: lib64/libclang.so.14.0.0
tools/libclang/CMakeFiles/libclang.dir/build.make:      @$(CMAKE_COMMAND) -E touch_nocreate lib64/libclang.so.13
tools/libclang/CMakeFiles/libclang.dir/DependInfo.cmake:  "/home/tkloczko/rpmbuild/BUILD/clang-14.0.0.src/x86_64-redhat-linux-gnu/lib64/libclang.so.13" "/home/tkloczko/rpmbuild/BUILD/clang-14.0.0.src/x86_64-redhat-linux-gnu/lib64/libclang.so.14.0.0"
tools/libclang/cmake_install.cmake:      "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib64/libclang.so.13"
tools/libclang/cmake_install.cmake:    "/home/tkloczko/rpmbuild/BUILD/clang-14.0.0.src/x86_64-redhat-linux-gnu/lib64/libclang.so.13"
tools/libclang/cmake_install.cmake:      "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib64/libclang.so.13"
grep: bin/c-arcmt-test: binary file matches
grep: bin/c-index-test: binary file matches
cmake/modules/CMakeFiles/Export/lib64/cmake/clang/ClangTargets-relwithdebinfo.cmake:  IMPORTED_SONAME_RELWITHDEBINFO "libclang.so.13"
lib64/cmake/clang/ClangTargets.cmake:  IMPORTED_SONAME_RELWITHDEBINFO "libclang.so.13"
grep: lib64/libclang.so.14.0.0: binary file matches
install_manifest.txt:/usr/lib64/libclang.so.13
```

**Comment by nathanchance** [comment] 2022-04-21 18:33
Duplicate of #54004 and #54853?

**Closed** 2022-04-21 19:22 UTC
Labels: cmake
