### ISSUE TITLE
libc++ - building on Ubuntu focal with `--target=wasm32-unknown-wasi`  fails with `cannot add 'abi_tag' attribute in a redeclaration`

### ISSUE THREAD

**Issue by sylvestre** [llvm/llvm-project#59843] opened 2023-01-05 13:42 UTC
Building with:
```
"/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/build-llvm/tools/clang/stage2-bins/bin/clang++" --target=wasm32-unknown-wasi  -DLIBCXX_BUILDING_LIBCXXABI -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_NEW_DELETE_DEFINITIONS -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/libcxx/src" -Iinclude/c++/v1 -I"/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/libcxxabi/include" -O2 -DNDEBUG -g1 -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fno-stack-protector -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color   -std=c++2a -MD -MT libcxx/src/CMakeFiles/cxx_static.dir/chrono.cpp.o -MF libcxx/src/CMakeFiles/cxx_static.dir/chrono.cpp.o.d -o libcxx/src/CMakeFiles/cxx_static.dir/chrono.cpp.o -c '/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/libcxx/src/chrono.cpp'
[...]

In file included from /root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/libcxx/src/chrono.cpp:16:
In file included from include/c++/v1/chrono:773:
In file included from include/c++/v1/__chrono/formatter.h:21:
In file included from include/c++/v1/__chrono/ostream.h:26:
In file included from include/c++/v1/__format/format_functions.h:27:
In file included from include/c++/v1/__format/format_context.h:24:
In file included from include/c++/v1/locale:203:
In file included from include/c++/v1/__locale:44:
include/c++/v1/__support/musl/xlocale.h:27:8: error: cannot add 'abi_tag' attribute in a redeclaration
inline _LIBCPP_HIDE_FROM_ABI long long
       ^
include/c++/v1/__config:615:26: note: expanded from macro '_LIBCPP_HIDE_FROM_ABI'
          __attribute__((__abi_tag__(_LIBCPP_TOSTRING(_LIBCPP_VERSIONED_IDENTIFIER))))
                         ^
/usr/include/stdlib.h:284:22: note: previous declaration is here
extern long long int strtoll_l (const char *__restrict __nptr,
```

Ubuntu Focal ships with libc6 2.31-0ubuntu9.9.

The problem probably occurs on old Ubuntu.

Built with:
```

mkdir -p "build-wasm/compiler-rt-wasm32"
cmake -B "build-wasm/compiler-rt-wasm32" -S compiler-rt/lib/builtins/ \
        -G Ninja \
        -DCMAKE_C_COMPILER_LAUNCHER=/opt/sccache/sccache -DCMAKE_CXX_COMPILER_LAUNCHER=/opt/sccache/sccache \
        -DCMAKE_C_COMPILER_TARGET=wasm32-unknown-unknown \
        -DCMAKE_CXX_COMPILER_TARGET=wasm32-unknown-unknown \
        -DCMAKE_ASM_COMPILER_TARGET=wasm32-unknown-unknown \
        -DCMAKE_C_COMPILER=/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/build-llvm/tools/clang/stage2-bins/bin/clang \
        -DCMAKE_CXX_COMPILER=/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/build-llvm/tools/clang/stage2-bins/bin/clang++ \
        -DCMAKE_C_FLAGS="-O2 -DNDEBUG -g1 -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
        -DCMAKE_CXX_FLAGS="-O2 -DNDEBUG -g1 -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2" \
        -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--build-id -L/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/build-llvm/tools/clang/stage2-bins/lib" \
        -DCMAKE_MODULE_LINKER_FLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--build-id -L/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/build-llvm/tools/clang/stage2-bins/lib" \
        -DCMAKE_EXE_LINKER_FLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--build-id -L/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/build-llvm/tools/clang/stage2-bins/lib" \
        -DCMAKE_INSTALL_PREFIX=/usr/lib/llvm-16/lib/clang/16.0.0 \
        -DCMAKE_INSTALL_DATADIR=lib \
        -DCMAKE_INSTALL_INCLUDEDIR=include \
        -DLLVM_CMAKE_DIR=/root/llvm-toolchain-snapshot_16~++20230105104856+551ec87883c5/build-llvm/tools/clang/stage2-bins/bin/../ \
        -DCOMPILER_RT_STANDALONE_BUILD=ON \
        -DCOMPILER_RT_BAREMETAL_BUILD=ON \
        -DCOMPILER_RT_INCLUDE_TESTS=OFF \
        -DCOMPILER_RT_USE_LIBCXX=OFF \
        -DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON \
        -DCOMPILER_RT_DEFAULT_TARGET_TRIPLE=wasm32-unknown-unknown \
        -DCOMPILER_RT_OS_DIR=wasi

```

**Comment by philnik777** [comment] 2023-01-05 14:59
Duplicate of #59540.

**Closed by philnik777** 2023-01-05 14:59 UTC
Labels: libc++, backend:WebAssembly, build-problem

**Comment by sylvestre** [comment] 2023-01-05 15:07
Sorry, i missed it!
