### ISSUE TITLE
Loop Interchange bug due to loop guards not being interchanged

### ISSUE THREAD

**Issue by alexgatea** [llvm/llvm-project#58170] opened 2022-10-05 17:33 UTC
Right now loop guards are not interchanged which leads to incorrect control flow after the interchange.
For example, consider the following code before the interchange.
```c
if(n > 0)
  for(int i=0; i != n; i++)
    if(m > 0)
      for(int j=0; j != m; j++)
         A[j][i] += B[j][i] + 1;
```
IR: [before.ll](https://github.com/llvm/llvm-project/files/9717558/before.ll.txt)

After interchange:
```c
if(n > 0)
  for(int j=0; j != m; j++)
    for(int i=0; i != n; i++) {
      if(m > 0)
         A[j][i] += B[j][i] + 1;
      else break;
    }
```
IR: [after.ll](https://github.com/llvm/llvm-project/files/10439591/after.ll.txt)

Command:
```shell
opt -aa-pipeline='default' -da-disable-delinearization-checks -passes='require<opt-remark-emit>,loop(loop-interchange),verify<domtree>,verify<loops>,verify<memoryssa>' before.ll -S -o after.ll
```

If `m` is -1 at run-time then the original code only executes the outer `for-i` loop whereas the resulting code is an infinite loop (since `j != m` always evaluates to `false`).

Possible solutions under consideration:
- See if running simple loop unswitch and/or LICM prior to loop interchange fixes the issue.
- View non-user generated loop guards (checked via `isGuarded()` for example) as part of anatomy of a loop.

**Comment by alexgatea** [comment] 2022-11-01 13:29
Update:
I verified that running LICM + simple loop unswitch before loop interchange fixes the issue. In particular, the C code is transformed into
```
if(n > 0)
  if (m > 0) {
    for(int j=0; j != m; j++)
      for(int i=0; i != n; i++)
         A[j][i] += B[j][i] + 1;
  } else {
    for(int i=0; i != n; i++) {}
  }
```

**Comment by caojoshua** [comment] 2023-01-07 23:10
For some reason, when I [compare before.ll and after.ll in alive](https://alive2.llvm.org/ce/z/tQd-EY), its returning `<Compilation failed>`. 

The before and after are technically the same. There is no infinite loop if `m = -1`, because eventually `j` will overflow and be equal to -1. And the body inside the nested loops will never be executed, since execution will never get past `if (m > 0)`. That being said, this is still an undesirable Transformation, and it may be possible to construct an example that is truly breaking.

There are similar cases in the test suite. For example, `llvm/test/Transforms/LoopInterchange/lcssa-preheader.ll`. The transformation is correct, but makes the originally-inner induction variable overflow.

 LoopInterchange will only interchanges 'tightly nested' loops. In the sample C code, it does not look like a tightly-nested loop because there is a if statement inbetween nested loops. But in LLVM IR, the outer loop header branches, with condition `m > 0` to A) the inner loop preheader and B) the outer loop latch. LoopInterchange considers this tightly nested, but I think there needs to re-evaluation on how we define tightly nested.

**Comment by alexgatea** [comment] 2023-01-18 15:01
Unfortunately I'm not familiar with this alive tool, so I would appreciate it if you could briefly let me know what this compilation failure means. Because the input IR `before.ll` I posted above _does_ compile with opt (including in the link you provided, if I change from alive-tv to opt). I double-checked my after.ll and realized it wasn't quite correct, so I reposted it above; I'm not sure if this what caused the failure though.
Regarding your comments, I agree that we don't have an infinite loop because eventually j will overflow. But as you said, this is undesirable, which was my main concern in this issue. You can imagine a case where the loop condition is an expensive check (e.g. j != n && expensive_foo(j) ) and we don't want to execute the loop until the IV wraps around.
Yes, LoopInterchange only interchanges 'tightly nested' loops, and right now that allows for an if-statement between the for-loops. As you said, we might want to re-evaluate the definition of 'tightly nested'; it's not incorrect the way it's now, it's just possibly leads to not fully optimized code.

**Comment by sjoerdmeijer** [comment] 2024-11-08 13:59
I can't reproduce this. 

First of all, I don't think the loops live in this form for very long:

```
if(n > 0)
  for(int i=0; i != n; i++)
    if(m > 0)
      for(int j=0; j != m; j++)
         A[j][i] += B[j][i] + 1;
```

When SimplifyCFG comes around, things look more like this:

```
if n>0 && m>0 goto outer.loop
outerloop:
  :
innerloop:
:
if i != m goto innerloop
if j != n  goto outerloop
```

So the `n>0 && m>0` is like one precondition to enter the loop nest. Which is why I don't think loop-interchange mix this up.

Secondly, loop-interchange is not triggering:

```
Processing InnerLoopId = 1 and OuterLoopId = 0
Failed interchange InnerLoopId = 1 and OuterLoopId = 0 due to dependence
Not interchanging loops. Cannot prove legality.
```

See also: https://godbolt.org/z/vxPEKM4Yh

I am closing this ticket, but let me know if you think I have missed something, happy to look more into this.

**Closed by sjoerdmeijer** 2024-11-08 13:59 UTC
Labels: loopoptim
