### ISSUE TITLE
clang-cl: always_inline function '_mm_crc32_u64' requires target feature 'crc32'

### ISSUE THREAD

**Issue by Neumann-A** [llvm/llvm-project#56722] opened 2022-07-26 11:04 UTC
```
clang version 14.0.6
Target: x86_64-pc-windows-msvc
```

probably related: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265027

While compiling libpq with clang-cl instead of cl I see:
```console
         src/port/pg_crc32c_sse42.c(38,18): error : always_inline function '_mm_crc32_u64' requires target feature 'crc32', but would be inlined into function 'pg_comp_crc32c_sse42' that is compiled without support for 'crc32' [E:\vcpkg_folders\qt6-update\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj]
         src/port/pg_crc32c_sse42.c(45,9): error : always_inline function '_mm_crc32_u32' requires target feature 'crc32', but would be inlined into function 'pg_comp_crc32c_sse42' that is compiled without support for 'crc32' [E:\vcpkg_folders\qt6-update\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj]
         src/port/pg_crc32c_sse42.c(64,9): error : always_inline function '_mm_crc32_u8' requires target feature 'crc32', but would be inlined into function 'pg_comp_crc32c_sse42' that is compiled without support for 'crc32' [E:\vcpkg_folders\qt6-update\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj]

```
Running the build with cl works as expected (Simply switched the toolset from Clang-Cl back to vc143). So I assume there is something wrong how llvm selects the target architecture. (especially since it seems that I am not the only one and it started happening with llvm 14(?) )

**Comment by efriedma-quic** [comment] 2022-07-26 18:52
Needs a reduced testcase.

In general, LLVM requires that you enable the relevant feature (pass -mcrc32, or use a target attribute) to use target-specific intrinsics.  MSVC generally doesn't enforce that sort of thing, but clang and gcc on other targets do.  If your code woks on non-Windows targets, maybe you already have code to deal with this, and are accidentally disabling it on Windows?

**Comment by Neumann-A** [comment] 2022-07-26 19:05
> Needs a reduced testcase.

just use the intrinsic in a simple c file and try to compile it with the clang-cl in a normal x64 vcvars env ?

> (pass -mcrc32, or use a target attribute)

won't be recognized by clang on windows as far as I can tell from `--help|/?` its not listed. Also -march=penryn doesn't work since it won't recognize -march. 

> MSVC generally doesn't enforce that sort of thin

x64 MSVC implies SSE 5.2 as far as I am aware. Adding /arch:AVX to the compile flags solves the compile problem so i assume llvm is deactivating it for some unkown reasons. 

> If your code woks on non-Windows targets, maybe you already have code to deal with this, and are accidentally disabling it on Windows?

Its not my code its Postgres. I am just switching the compiler with the same flags between cl and clang-cl.

**Comment by efriedma-quic** [comment] 2022-07-26 19:18
clang-cl supports both -mcrc32 and -march=nehalem, even if it doesn't show up in --help.

x64 MSVC is SSE2 by default.  It just lets you use all SSE intrinsics without explicitly specifying what you're doing.

**Comment by Neumann-A** [comment] 2022-07-26 19:32
> clang-cl supports both -mcrc32 and -march=nehalem, even if it doesn't show up in --help.

where can i find that list? (It works now fine with -mcrc32)

> x64 MSVC is SSE2 by default. It just lets you use all SSE intrinsics without explicitly specifying what you're doing.

shouldn't clang-cl then behave the same since it is intended to be a drop in replacement for cl ?

**Comment by efriedma-quic** [comment] 2022-07-26 19:43
> where can i find that list? (It works now fine with -mcrc32)

https://clang.llvm.org/docs/ClangCommandLineReference.html is the general command-line reference; I don't think we have any document that explicitly notes which options are accepted by clang-cl.

There's certainly room for improvement here.

> shouldn't clang-cl then behave the same since it is intended to be a drop in replacement for cl ?

It might be worth considering, but it would be tricky to implement, given the way LLVM works.  Currently, an instruction is either supported or not supported, but we'd have to split that to specify "supported for intrinsics" vs. "supported for general use by the compiler".

**Comment by phoebewang** [comment] 2022-07-27 02:23
So it is only a problem of option gap between clang-cl and cl, right? I'll close it due to it's unrelated problem. Feel free to reopen if you still think it's a problem.

> x64 MSVC implies SSE 4.2 as far as I am aware. Adding /arch:AVX to the compile flags solves the compile problem so i assume llvm is deactivating it for some unkown reasons.

Actually, the [doc of MSVC](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-170) says it implies SSE2, though I confirmed it doesn't raise error for crc32 intrinsics.

> probably related: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265027

It is not related. The CRC32 intrinsics require SSE 4.2 feature and above. However, Penryn is a special generation part of which supports SSE 4.2 and part not, see https://en.wikipedia.org/wiki/SSE4
I'm surprised `-march=penryn` solved the problem, because it doesn't work on my side.

**Closed by phoebewang** 2022-07-27 02:23 UTC
Labels: backend:X86, clang:headers, clang-cl
