### ISSUE TITLE
[RISCV] lli - hello world segmentation fault

### ISSUE THREAD

**Issue by developandplay** [llvm/llvm-project#52901] opened 2021-12-28 15:15 UTC
I saw https://reviews.llvm.org/D105429 so I was curious to see how well JIT already works on RISCV.
Therefore I just ran `clang -O3 -emit-llvm hello.c -c -o hello.bc` like in the LLVM getting started guide.
The code of course just being the basic hello world provided by the guide:

```c
#include <stdio.h>

int main() {
  printf("hello world\n");
  return 0;
}

```

Now running `lli` works as expected on x86 but on RISCV I am running into a segmentation fault.

```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: lli-13 hello.bc
#0 0x0000003f8a52aa60 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/riscv64-linux-gnu/libLLVM-13.so.1+0xd0ea60)
Segmentation fault
```

This leads me to the question: Which pieces of llvm are still missing for full JIT support on RISCV?

**Comment by developandplay** [comment] 2022-01-04 18:01
@luxufan Stefan already added some details regarding this on the llvm mailing list: https://groups.google.com/g/llvm-dev/c/MoCSoRK4wJ8/m/ZXt1l0sMEAAJ

However since you are the one who was most recently working on the RISCV part of the JIT you'll probably have more insights.
I'm looking forward to your response.

**Comment by luxufan** [comment] 2022-01-10 12:31
Hi @developandplay . Currently,  Using lli to run at RISCV platform will run into segmentation fault.

But I have submitted some patches(https://reviews.llvm.org/D116475, https://reviews.llvm.org/D116794) to resolve this problem. By applying these patches, helloworld test program can get the correct output. 

I test that by follow commands:
`clang --target=riscv64-unknown-linux-gnu -S -emit-llvm -fPIC --sysroot=/path/to/sysroot --gcc-toolchain=/path/to/gcc-toolchain hello.c -o hello.ll`

`qemu-riscv64 -L /path/to/sysroot lli --jit-linker=jitlink -code-model=medium hello.ll`

It can get the correct output, but still have error reported which is caused by missing some relocation support.

**Comment by developandplay** [comment] 2022-01-18 13:46
Oh the `--jit-linker=jitlink -code-model=medium` were important to get the correct output with the current llvm-14 release build.

Original output:
```
lli --jit-linker=jitlink -code-model=medium hello-world.ll
hello, world!
lli: ../include/llvm/ExecutionEngine/JITLink/JITLink.h:467: static llvm::jitlink::Symbol &llvm::jitlink::Symbol::constructNamedDef(void *, llvm::jitlink::Block &, orc::ExecutorAddrDiff, llvm::StringRef, orc::ExecutorAddrDiff, llvm::jitlink::Linkage, llvm::jitlink::Scope, bool, bool): Assertion `!Name.empty() && "Name cannot be empty"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ../llvm-project/llvm/install/riscv64-unknown-linux-gnu-clang/bin/lli --jit-linker=jitlink -code-model=medium hello-world.ll
```

**Comment by developandplay** [comment] 2022-01-18 13:53
@luxufan Thanks for the patches!
I just tried applying https://reviews.llvm.org/D116794 however it seems like clang does not seem to like the `reinterpret_cast()` calls.

```
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:275:27: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const void *' is not allowed
                          reinterpret_cast<const void *>(FixupAddress)) +
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:283:27: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const void *' is not allowed
                          reinterpret_cast<const void *>(FixupAddress)) +
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:291:27: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const void *' is not allowed
                          reinterpret_cast<const void *>(FixupAddress)) +
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:298:25: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const uint8_t *' (aka 'const unsigned char *') is not allowed
                      *(reinterpret_cast<const uint8_t *>(FixupAddress)) +
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:305:27: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const void *' is not allowed
                          reinterpret_cast<const void *>(FixupAddress)) -
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:312:27: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const void *' is not allowed
                          reinterpret_cast<const void *>(FixupAddress)) -
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:319:27: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const void *' is not allowed
                          reinterpret_cast<const void *>(FixupAddress)) -
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/ExecutionEngine/JITLink/ELF_riscv.cpp:325:25: error: reinterpret_cast from 'orc::ExecutorAddr' to 'const uint8_t *' (aka 'const unsigned char *') is not allowed
      int64_t Value = *(reinterpret_cast<const uint8_t *>(FixupAddress)) -
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8 errors generated.
```

I'd assume it's related to lhames comment regarding the `ExecutorAddr` changes.
I will look into it some more when I find the time.

**Comment by developandplay** [comment] 2022-01-18 15:03
I managed to adjust the diff for `ExecturoAddr`. Now we don't get a segmentation fault but a helpful massage as to which relocation is missing. Great work @luxufan!
```
lli --jit-linker=jitlink -code-model=medium hello-world.ll
hello, world!
JIT session error: Unsupported riscv relocation:57
../llvm-project/llvm/install/riscv64-unknown-linux-gnu-clang/bin/lli: Failed to materialize symbols: { (main, { __lljit_run_atexits, __dso_handle }) }
```

**Comment by developandplay** [comment] 2022-01-18 16:49
With https://reviews.llvm.org/D116475 we got one more relocation working. :partying_face: 
I'll see if I can get some more relocations done myself!

```
lli --jit-linker=jitlink -code-model=medium hello-world.ll
hello, world!
JIT session error: Unsupported riscv relocation:53
../llvm-project/llvm/install/riscv64-unknown-linux-gnu-clang/bin/lli: Failed to materialize symbols: { (main, { __lljit_run_atexits, __dso_handle }) }
```

**Comment by lhames** [comment] 2023-03-14 22:28
@developandplay I believe that the necessary patches have landed in the mainline and that hello-world should now work with LLI. I'm going to close this as completed. If hello world is not working for you please feel free to re-open this bug, or you can file follow up bugs for any issues with more complex programs.

**Closed by lhames** 2023-03-14 22:28 UTC
Labels: backend:RISC-V, jitlink
