### ISSUE TITLE
Better codegen for truncated bswap

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#50910] opened 2021-08-20 22:14 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [51568](https://llvm.org/bz51568) |
| Version | trunk |
| OS | Linux |
| CC | @RKSimon,@rotateright |

## Extended Description 
```
unsigned int swap_ull(unsigned long long value)
{
    return ((value & 0x00000000000000ffull) << 56)
            | ((value & 0x000000000000ff00ull) << 40)
            | ((value & 0x0000000000ff0000ull) << 24)
            | ((value & 0x00000000ff000000ull) << 8)
            | ((value & 0x000000ff00000000ull) >> 8)
            | ((value & 0x0000ff0000000000ull) >> 24)
            | ((value & 0x00ff000000000000ull) >> 40)
            | ((value & 0xff00000000000000ull) >> 56);
}

unsigned int swap_ull_builtin(unsigned long long value)
{
    return __builtin_bswap64(value);
}
```

Trunk -O3:
```
swap_ull(unsigned long long):                           # @&#8203;swap_ull(unsigned long long)
        movabs  rax, 72057589742960640
        and     rax, rdi
        bswap   rax
        shr     rdi, 56
        or      eax, edi
        ret
swap_ull_builtin(unsigned long long):                  # @&#8203;swap_ull_builtin(unsigned long long)
        mov     rax, rdi
        bswap   rax
        ret
```

ICC -O3:
```
swap_ull(unsigned long long):
        bswap     rdi                                           #&#8203;10.51
        mov       eax, edi                                      #&#8203;10.51
        ret                                                     #&#8203;10.51
swap_ull_builtin(unsigned long long):
        bswap     rdi                                           #&#8203;15.12
        mov       eax, edi                                      #&#8203;15.12
        ret                                                     #&#8203;15.12
```

```
unsigned int swap_ull(unsigned long long value)
{
    return ((value & 0x00000000000000ffull) << 56)
            | ((value & 0x000000000000ff00ull) << 40)
            | ((value & 0x0000000000ff0000ull) << 24)
            | ((value & 0x00000000ff000000ull) << 8)
            | ((value & 0x000000ff00000000ull) >> 8)
            | ((value & 0x0000ff0000000000ull) >> 24)
            | ((value & 0x00ff000000000000ull) >> 40)
            | ((value & 0xff00000000000000ull) >> 56);
}

unsigned int swap_ull_builtin(unsigned long long value)
{
    return __builtin_bswap64(value);
}
```

```
define i32 @&#8203;src(i64 %0) {
%1:
  %2 = and i64 %0, 72057594037927935
  %3 = bswap i64 %2
  %4 = lshr i64 %0, 56
  %5 = or i64 %3, %4
  %6 = trunc i64 %5 to i32
  ret i32 %6
}
=>
define i32 @&#8203;tgt(i64 %0) {
%1:
  %2 = bswap i64 %0
  %3 = trunc i64 %2 to i32
  ret i32 %3
}
Transformation seems to be correct!
```
https://alive2.llvm.org/ce/z/loQjOQ

**Comment by RKSimon** [comment] 2021-12-31 13:18
llvm::recognizeBSwapOrBitReverseIdiom could handle this, but it might bail out due to the trunc() user of the or()

**Comment by rotateright** [comment] 2021-12-31 14:23
Do you know why we have the [trunc user check]( https://github.com/llvm/llvm-project/blob/e2f1c4c7066b34ad171d91879263cfa32bc6c55c/llvm/lib/Transforms/Utils/Local.cpp#L3151 )? If I just comment it out, this bug is fixed with no regression test failures.

**Comment by RKSimon** [comment] 2021-12-31 23:23
It looks like it first appeared in https://reviews.llvm.org/D20591

When I refactored recognizeBSwapOrBitReverseIdiom to better handle truncs in https://reviews.llvm.org/D88316 it looks like I kept it, but I'm not certain if it was necessary any more.

@rotateright Are you up for dealing with this?

**Comment by rotateright** [comment] 2022-01-01 20:07
Sure - it should just be a matter of removing that check and cleaning up the code. I'll look over the tests to see if there was a test that became moot with D88316.

**Comment by rotateright** [comment] 2022-01-05 17:04
I added a trunc test that I thought might work with:
3a2393795f205
...but it doesn't match either way, so I'll plan to remove the trunc check as the fast fix for this bug.

**Closed** 2022-01-05 18:04 UTC
Labels: bugzilla, llvm:codegen

**Comment by RKSimon** [comment] 2022-01-06 14:12
Thanks @rotateright

**Comment by davidbolvansky** [comment] 2022-01-06 14:41
Thanks for the fix
