### ISSUE TITLE
[BOLT] perf2bolt fails on aarch64 due to an unsupported CFI opcode

### ISSUE THREAD

**Issue by ARG-NK** [llvm/llvm-project#80992] opened 2024-02-07 14:10 UTC
I am using BOLT to optimize a binary compiled with GCC (used options -gdwarf64 and -gdwarf4 ): 
When perf2bolt is used I get the below error message: 

command: perf2bolt -p perf.data FILENAME.so -o perf.fdata --itrace=el64i10ns

![image](https://github.com/llvm/llvm-project/assets/158327801/d60a8c4b-38fe-42dc-b53b-77a7779fd228)

This is the opcode:
![image](https://github.com/llvm/llvm-project/assets/158327801/a48b68bb-a592-456e-93f1-1587cd5fd9c5)

does BOLT support binary with dwarf64 format ?

**Comment by yota9** [comment] 2024-02-10 18:23
Closing as duplicate of https://github.com/llvm/llvm-project/issues/74833

**Closed by yota9** 2024-02-10 18:23 UTC
Labels: duplicate, BOLT

**Comment by ARG-NK** [comment] 2024-02-15 14:21
Hi, 
as a workaround, setting GCC option "-mbranch-protection=none" to disable all branch protection seem to work in my case. 
No crash seen, as before.

**Comment by yota9** [comment] 2024-02-15 14:29
@ARG-NK Thanks! Let's hope one day someone would add support for this CFI :)
