### ISSUE TITLE
[RISC-V] `llvm.*maximum`/`llvm.*minimum` can't be lowered to soft floats

### ISSUE THREAD

**Issue by dcaballe** [llvm/llvm-project#70061] opened 2023-10-24 16:47 UTC
Hi there,

It looks like `llvm.maximum` and `llvm.vector.reduce.fmaximum` (and I assume the minimum counterparts as well) can't be lowered to soft floats.

Repro:

```
define float @test(<4 x float> %in, float %in2, float %in3) {
  %mr = tail call float @llvm.vector.reduce.fmaximum.v4f32(<4 x float> %in)
  %m = tail call float @llvm.maximum.f32(float %in2, float %in3)
  %res = fadd float %m, %mr
  ret float %res
}

declare float @llvm.vector.reduce.fmaximum.v4f32(<4 x float>)

declare float @llvm.maximum.f32(float, float)
```

```
llc -mattr=+m -mtriple=riscv32-pc-linux-elf -target-abi=ilp32 test.ll

SoftenFloatResult #0: t46: f32 = fmaximum t35, t34

LLVM ERROR: Do not know how to soften the result of this operator!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llc -mattr=+m -mtriple=riscv32-pc-linux-elf -target-abi=ilp32 test.ll
1.      Running pass 'Function Pass Manager' on module 'test.ll'.
2.      Running pass 'RISC-V DAG->DAG Pattern Instruction Selection' on function '@test'
```

**Comment by dtcxzyw** [comment] 2023-10-24 16:59
Duplicate of #64206.

**Closed** 2023-10-24 20:33 UTC
Labels: bug, backend:RISC-V
