### ISSUE TITLE
Compiling empty CUDA kernel with RDC enabled fails in PTXAS

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#54934] opened 2022-04-15 17:01 UTC
The following CUDA kernel is failing to compile when RDC-mode is enabled because of PTXAS.

```
template <typename T>                    
__global__ void EmptyKernel(void) { }    
                
void foo() {                        
  EmptyKernel<void><<<1, 1>>>();    
} 
```

This function will create the following LLVM-IR
```
target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

$_Z11EmptyKernelIvEvv = comdat any

@gpu.used.external = appending global [1 x ptr] [ptr @_Z11EmptyKernelIvEvv]
@llvm.compiler.used = appending global [1 x ptr] [ptr @gpu.used.external], section "llvm.metadata"

; Function Attrs: convergent mustprogress noinline norecurse nounwind optnone
define weak_odr dso_local void @_Z11EmptyKernelIvEvv() #0 comdat {
entry:
  ret void
}

attributes #0 = { convergent mustprogress noinline norecurse nounwind optnone "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sm_70" "target-features"="+ptx75,+sm_70" }

!llvm.module.flags = !{!0, !1, !2, !3}
!nvvm.annotations = !{!4}

!0 = !{i32 2, !"SDK Version", [2 x i32] [i32 11, i32 5]}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 4, !"nvvm-reflect-ftz", i32 0}
!3 = !{i32 7, !"frame-pointer", i32 2}
!4 = !{ptr @_Z11EmptyKernelIvEvv, !"kernel", i32 1}
```
Which makes the following PTX
```
//
// Generated by LLVM NVPTX Back-End
//

.version 6.0
.target sm_70
.address_size 64

	// .weak	_Z11EmptyKernelIvEvv            // -- Begin function _Z11EmptyKernelIvEvv
.weak .entry _Z11EmptyKernelIvEvv
()
;
.global .align 8 .u64 gpu.used.external[1] = {_Z11EmptyKernelIvEvv};
                                        // @_Z11EmptyKernelIvEvv
.weak .entry _Z11EmptyKernelIvEvv()
{


// %bb.0:                               // %entry
	ret;
                                        // -- End function
}
```
Which fails when compiled with PTXAS
```
$ ptxas "-m64" "-O3" "--gpu-name" "sm_70" "--output-file" "empty.cubin" "empty.s" "-c"
ptxas empty.s, line 13; fatal   : Parsing error near '.used': syntax error
ptxas fatal   : Ptx assembly aborted due to errors
```

This seems to have started with 0424b5115cffa but is probably not the root cause.

**Comment by yxsamliu** [comment] 2022-04-18 14:57
I can reproduce this issue. This is because ptxas does not allow global variables with `.` in name. I will fix it.

**Comment by yxsamliu** [comment] 2022-04-18 15:47
fixed by https://reviews.llvm.org/D123946

**Closed** 2022-04-19 03:10 UTC
Labels: cuda
