### ISSUE TITLE
clang CUDA. error: no matching constructor for initialization of std::shared_ptr

### ISSUE THREAD

**Issue by burlen** [llvm/llvm-project#63199] opened 2023-06-08 17:47 UTC
It seems that Clang CUDA wrappers overload `free` from the C stdlib in a way that causes some valid C++ code to fail when compiling for CUDA. The issue specifically is with overload resolution in the `std::shared_ptr` constructor when using `free` as the deleter.

Here is small reproducer:
```C++
#include <cstdlib>

// note: the noinline issue was fixed in clang may '23
#undef __noinline__
#include <memory>
#define __noinline__ __attribute__((noinline))

int main(int, char**)
{
    unsigned int *tmp = (unsigned int*)malloc(16*sizeof(unsigned int));

    // fails with -x cuda
    auto ptr = std::shared_ptr<unsigned int>(tmp, free);

    return 0;
}
```

To reproduce compile this with:
```shell
clang++ -std=c++17 -x cuda --cuda-gpu-arch=sm_75 test.cpp
```

The errors are:
```console
test.cpp:14:16: error: no matching constructor for initialization of 'std::shared_ptr<unsigned int>'
    auto ptr = std::shared_ptr<unsigned int>(tmp, free);
               ^                             ~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:535:7: note: candidate constructor not viable: no known conversion from 'unsigned int *' to 'const weak_ptr<unsigned int>' for 1st argument
      shared_ptr(const weak_ptr<_Tp>& __r, std::nothrow_t) noexcept
      ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:231:2: note: candidate template ignored: couldn't infer template argument '_Deleter'
        shared_ptr(_Yp* __p, _Deleter __d)
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:248:2: note: candidate template ignored: couldn't infer template argument '_Deleter'
        shared_ptr(nullptr_t __p, _Deleter __d)
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:311:2: note: candidate template ignored: could not match 'shared_ptr<_Yp>' against 'unsigned int *'
        shared_ptr(const shared_ptr<_Yp>& __r, element_type* __p) noexcept
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:463:2: note: candidate template ignored: could not match '_Sp_alloc_shared_tag<_Alloc>' against 'unsigned int *'
        shared_ptr(_Sp_alloc_shared_tag<_Alloc> __tag, _Args&&... __args)
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:204:7: note: candidate constructor not viable: requires 1 argument, but 2 were provided
      shared_ptr(const shared_ptr&) noexcept = default; ///< Copy constructor
      ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:214:2: note: candidate constructor template not viable: requires single argument '__p', but 2 arguments were provided
        shared_ptr(_Yp* __p) : __shared_ptr<_Tp>(__p) { }
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:351:2: note: candidate constructor template not viable: requires single argument '__r', but 2 arguments were provided
        shared_ptr(const shared_ptr<_Yp>& __r) noexcept
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:359:7: note: candidate constructor not viable: requires single argument '__r', but 2 arguments were provided
      shared_ptr(shared_ptr&& __r) noexcept
      ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:368:2: note: candidate constructor template not viable: requires single argument '__r', but 2 arguments were provided
        shared_ptr(shared_ptr<_Yp>&& __r) noexcept
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:380:11: note: candidate constructor template not viable: requires single argument '__r', but 2 arguments were provided
        explicit shared_ptr(const weak_ptr<_Yp>& __r)
                 ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:387:2: note: candidate constructor template not viable: requires single argument '__r', but 2 arguments were provided
        shared_ptr(auto_ptr<_Yp>&& __r);
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:395:2: note: candidate constructor template not viable: requires single argument '__r', but 2 arguments were provided
        shared_ptr(unique_ptr<_Yp, _Del>&& __r)
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:412:17: note: candidate constructor not viable: requires 1 argument, but 2 were provided
      constexpr shared_ptr(nullptr_t) noexcept : shared_ptr() { }
                ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:268:2: note: candidate constructor template not viable: requires 3 arguments, but 2 were provided
        shared_ptr(_Yp* __p, _Deleter __d, _Alloc __a)
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:287:2: note: candidate constructor template not viable: requires 3 arguments, but 2 were provided
        shared_ptr(nullptr_t __p, _Deleter __d, _Alloc __a)
        ^
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/shared_ptr.h:202:17: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
      constexpr shared_ptr() noexcept : __shared_ptr<_Tp>() { }
                ^
```
After a bit of digging I found that clang cuda wrappers overload free for use on the device. For instance:

``` C++
#include <cstdlib>

int main(int, char**)
{
    // this line give some additional info. it seems the CUDA
    // wrappers overload free and type of free cannot be deduced.
    using free_t = decltype(free);

    return 0;
}   
```

errors out with:
```console
test.cpp:18:29: error: reference to overloaded function could not be resolved; did you mean to call it?
    using free_t = decltype(free);
                            ^~~~
/home/bloring/work/llvm/llvm-17_5_25-install/lib/clang/17/include/__clang_cuda_runtime_wrapper.h:405:17: note: possible target for call
__device__ void free(void *) __attribute((nothrow));
                ^
/usr/include/stdlib.h:568:13: note: possible target for call
extern void free (void *__ptr) __THROW;
```
Showing the device overload. Adding an explicit cast on free can be used to help the compiler find the right overload, `auto ptr = std::shared_ptr<unsigned int>(tmp, (void (*)(void *) noexcept(true))free);`

Clang version 17.0.0 (https://github.com/llvm/llvm-project.git 5df593a354714e081ac441a74f89ad2a56334e28)

**Comment by Artem-B** [comment] 2023-06-08 18:22
What do you propose to have fixed in this case?

CUDA compilation in clang does have a notion of target-based function overloads, and we do have a lot of functions with GPU-side overloads. E.g. most of the math library functions.

The fact that `std::shared_ptr<unsigned int>(tmp, free);` works for you with C++ relies on an assumption that there are no overloads for `free`. I do not think anything anywhere guarantees that.

One way to work around the issue is to wrap `free` in another function. That would unambiguously resolve `free` to the host-side variant.
https://godbolt.org/z/e3eoe8rcx
```
#include <cstdlib>

// note: the noinline issue was fixed in clang may '23
#undef __noinline__
#include <memory>
#define __noinline__ __attribute__((noinline))

int main(int, char**)
{
    unsigned int *tmp = (unsigned int*)malloc(16*sizeof(unsigned int));

    // fails with -x cuda
    auto free_proxy = [](void*p){ free(p); };
    auto ptr = std::shared_ptr<unsigned int>(tmp, free_proxy);

    return 0;
}
```

**Comment by burlen** [comment] 2023-06-08 23:55
Fair enough. there's no rule against overloading `free`. 

I was surprised that this canonical example didn't compile. I was not sure if the device overload of free was intentionally visible.  I did not expect to see a device overload for free since my first intuition would be to use cudaMalloc/cudaFree for device allocations.

sounds like this is not a bug

**Closed** 2023-06-08 23:56 UTC
Labels: cuda

**Comment by Artem-B** [comment] 2023-06-09 01:05
Cuda does provide GPU-side malloc/free. I don't think they are widely used, but they do exist.

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html?highlight=malloc#dynamic-global-memory-allocation-and-operations
