### ISSUE TITLE
Immediate CI failure on PR submissions

### ISSUE THREAD

**Issue by winner245** [llvm/llvm-project#116467] opened 2024-11-16 04:06 UTC
I encountered immediate CI failure when submitting a new PR (#116449) to the LLVM repository. The error message is as follows:

```
Run actions/labeler@v4
The configuration file (path: .github/new-prs-labeler.yml) isn't found locally, fetching via the api
Error: HttpError: Resource not accessible by personal access token
Error: Resource not accessible by personal access token
```

**Comment by zwuis** [comment] 2024-11-16 04:32
This seems like a duplicate of #116322.

**Comment by boomanaiden154** [comment] 2024-11-16 06:20
This should be fixed now. It was a permissions issue according `#build-systems` on Discord.

**Closed by boomanaiden154** 2024-11-16 06:20 UTC
Labels: github-prs
