### ISSUE TITLE
std::pair constructor helper __pair_like_explicit_wknd not SFINAE correctly

### ISSUE THREAD

**Issue by huixie90** [llvm/llvm-project#65907] opened 2023-09-10 19:41 UTC
The following code, extracted from Boost.JSON, compiles under C++20
but fails with Clang trunk libc++ in C++2b mode:

```cpp
#include <type_traits>
#include <utility>

struct kvp {
  kvp() = default;
  explicit kvp(std::pair<int, int> const& p);
};

namespace std {

template <>
struct tuple_size<kvp> : std::integral_constant<std::size_t, 2> {};

template <>
struct tuple_element<0, kvp> {
  using type = int;
};

template <>
struct tuple_element<1, kvp> {
  using type = int;
};

} // namespace std

int main()
{
  kvp k1;
  static_assert(noexcept(kvp(std::move(k1))));
}
```
(https://godbolt.org/z/4cGdPxrxx)

The helper function `__pair_like_explicit_wknd` is only SFINAE-ed with `tuple_size<remove_cvref_t<_PairLike>>::value == 2`, but its function body assumes `std::get` being valid
https://github.com/llvm/llvm-project/blame/main/libcxx/include/__utility/pair.h#L280

**Comment by huixie90** [comment] 2023-09-10 20:14
could we just do

```cpp
template <class _PairLike>
    _LIBCPP_HIDE_FROM_ABI static constexpr bool __pair_like_explicit_wknd() {
        if constexpr (__pair_like<remove_cvref_t<_PairLike>>) {
            return !is_convertible_v<decltype(std::get<0>(std::declval<_PairLike>())), first_type> ||
                       !is_convertible_v<decltype(std::get<1>(std::declval<_PairLike>())), second_type>;
        }
        return false;
    }
```

**Comment by cor3ntin** [comment] 2023-09-11 08:40
I think that's a duplicate of https://github.com/llvm/llvm-project/issues/65620

**Comment by ldionne** [comment] 2023-09-15 16:45
Closing as a dupe of https://github.com/llvm/llvm-project/issues/65620

**Closed by ldionne** 2023-09-15 16:45 UTC
Labels: duplicate, libc++
