### ISSUE TITLE
[clang-format] BlockIndent defect

### ISSUE THREAD

**Issue by williamhCode** [llvm/llvm-project#63383] opened 2023-06-19 07:26 UTC
If `AlignAfterOpenBracket` is set to `BlockIndent`, and the line is exactly 1-2 characters over `ColumnLimit`, the closing parenthesis hangs in the next line, without the inner code block going to the next line.

For example, I have `ColumnLimit` set to 88, and this line is 90 characters long:
```cpp
...
    bindGroupLayouts.push_back(handle.device.CreateBindGroupLayout(&bindGroupLayoutDesc));
...
```
This gets formatted to:
```cpp
...
    bindGroupLayouts.push_back(handle.device.CreateBindGroupLayout(&bindGroupLayoutDesc)
    );
...
```
Instead, should be:
```cpp
...
    bindGroupLayouts.push_back(
      handle.device.CreateBindGroupLayout(&bindGroupLayoutDesc)
    );
...
```
Info:
clang-format version: 16.0.6
macOS 12.6

**Comment by exo-core** [comment] 2023-08-11 07:36
Experiencing the same issue.
I believe this has already been reported in #55473.

**Comment by Zingam** [comment] 2023-11-18 12:31
A duplicate of: https://github.com/llvm/llvm-project/issues/55731

**Closed** 2023-11-18 15:54 UTC
Labels: duplicate, clang-format
