### ISSUE TITLE
clang FunctionDecl AST-Matcher matches `operator<=>` as `operator==`

### ISSUE THREAD

**Issue by Febbe** [llvm/llvm-project#53522] opened 2022-02-01 12:18 UTC
clang-14:
The following code will be matched by `FunctionDecl ` to `operator<=>` and `operator==`

```
struct TestDefaultOperatorA {
  int a{};
  int b{};

  friend auto operator<=>(const TestDefaultOperatorA &, const TestDefaultOperatorA &) noexcept = default;
};
```

The debug code:

```
  std::ostringstream ss;
  ss << "==================================================\n";
  ss << "name:" << F->getNameAsString() << "\n";
  ss << "is overloaded operator: " << F->isOverloadedOperator() << "\n";
  ss << "is autotype:" << !!AT << "\n";
  ss << "is undeduced:" << F->getReturnType()->isUndeducedType() << "\n";
  ss << "is defaulted:" << F->isDefaulted() << "\n";
  ss << "deduced_type:" << F->getDeclaredReturnType().getAsString() << "\n";
  ss << F->getSourceRange().getBegin().printToString(PP->getSourceManager())
     << "\n";
  ss << "==================================================\n";
  llvm::outs() << ss.str();
```

returns something like:

```
==================================================
name:operator<=>
is overloaded operator: 1
is autotype:1
is undeduced:0
is defaulted:1
deduced_type:auto
D:\\Febbe\\workspace\\llvm-project\\build\\tools\\clang\\tools\\extra\\test\\clang-tidy\\checkers\\Output\\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp:92:3
==================================================
==================================================
name:operator<=>
is overloaded operator: 1
is autotype:1
is undeduced:0
is defaulted:1
deduced_type:auto
D:\\Febbe\\workspace\\llvm-project\\build\\tools\\clang\\tools\\extra\\test\\clang-tidy\\checkers\\Output\\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp:92:3
==================================================
==================================================
name:operator==
is overloaded operator: 1
is autotype:0
is undeduced:0
is defaulted:1
deduced_type:_Bool
D:\\Febbe\\workspace\\llvm-project\\build\\tools\\clang\\tools\\extra\\test\\clang-tidy\\checkers\\Output\\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp:92:3
==================================================
==================================================
name:operator==
is overloaded operator: 1
is autotype:0
is undeduced:0
is defaulted:1
deduced_type:_Bool
D:\\Febbe\\workspace\\llvm-project\\build\\tools\\clang\\tools\\extra\\test\\clang-tidy\\checkers\\Output\\modernize-use-trailing-return-type-cxx20.cpp.tmp.cpp:92:3
==================================================
```

**Comment by Febbe** [comment] 2022-02-01 12:22
fixes #53355

**Comment by zygoloid** [comment] 2022-02-01 17:45
The C++20 language rules say that a declaration of a defaulted `operator<=>` injects a declaration of a defaulted `operator==` too, so this is working as intended. The `operator==` should be marked as implicit, so the normal ways to prevent an AST matcher from matching implicit code should work here. (If not, that'd be a bug.)

**Closed by zygoloid** 2022-02-01 17:45 UTC
Labels: clang:tooling

**Comment by Febbe** [comment] 2022-02-02 00:49
@zygoloid ok it works, thank you for the help.
