### ISSUE TITLE
[InstSimplify] simplifyPHINode phi fold incorrect according to alive2

### ISSUE THREAD

**Issue by akshayrdeodhar** [llvm/llvm-project#115250] opened 2024-11-07 02:45 UTC
When a phi has `undef` as one of the incoming values, and an SSA value as the other, and the SSA value dominates the phi, replacing the phi with the SSA value is incorrect according to alive2. 

Is this an actual bug?

https://alive2.llvm.org/ce/z/7RNy3W

**Comment by akshayrdeodhar** [comment] 2024-11-07 02:45
CC: @manasij7479

**Comment by dtcxzyw** [comment] 2024-11-07 03:06
Duplicate of https://github.com/llvm/llvm-project/issues/68683.

**Closed** 2024-11-07 10:09 UTC
Labels: duplicate, miscompilation, llvm:instcombine
