### ISSUE TITLE
Failure to optimize code converted to memset call into tail call

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#47852] opened 2020-12-14 22:50 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [48508](https://llvm.org/bz48508) |
| Version | trunk |
| OS | Linux |
| CC | @efriedma-quic,@rotateright |

## Extended Description 
void f(char *d, size_t c)
{
    while (c-- > 0)
        *d++ = 0;
}

This code can be optimized to using `memset`. It can also be further optimize to optimize out the call to `memset` to a tail call. This transformation is done by GCC, but not by LLVM.

Comparison here : https://godbolt.org/z/sjP8P8

**Comment by thecppzoo** [comment] 2022-07-21 20:53
Respectfully, I disagree this issue is the same as the putative duplicate
[Extra stack save+restore](https://github.com/llvm/llvm-project/issues/56662).
@nikic could you please explain why you think the above ticket is the same issue as this?
Thanks for your help from Snap, Inc. Tell us if we can help.

**Comment by nikic** [comment] 2022-07-21 20:56
@thecppzoo The root cause is that a tail call is not inferred for memsets formed by LoopIdiomRecognize in both cases.

**Comment by thecppzoo** [comment] 2022-07-21 21:07
> @thecppzoo The root cause is that a tail call is not inferred for memsets formed by LoopIdiomRecognize in both cases.

@nikic I continue to disagree, will explain in the other ticket, thanks for replying

**Comment by rotateright** [comment] 2022-07-22 18:22
Proposal to add a late tail-call-elim to the pipeline:
https://reviews.llvm.org/D130374

**Comment by rotateright** [comment] 2022-07-26 12:37
Should be fixed with:
bfb9b8e075ee

**Closed by rotateright** 2022-07-26 12:37 UTC
Labels: bugzilla, llvm:optimizations
