### ISSUE TITLE
There is no way to get the linker script information during compilation/linkage process

### ISSUE THREAD

**Issue by P1119r1m** [llvm/llvm-project#54009] opened 2022-02-23 07:53 UTC
I found impossible to get linker script information during compilation via CLANG compiler with LLD linker.

For example, in GCC compiler it is possible to get the mentioned information via "-Wl,--verbose" option:
```
$ gcc -o main main.c -Wl,--verbose
...
SECTIONS
{
  PROVIDE (__executable_start = SEGMENT_START("text-segment", 0)); . = SEGMENT_START("text-segment", 0) + SIZEOF_HEADERS;
  .interp         : { *(.interp) }
  ...
  .init           :
  {
    KEEP (*(SORT_NONE(.init)))
  }
  ...
  .text           :
  {
    *(.text.unlikely .text.*_unlikely .text.unlikely.*)
    *(.text.exit .text.exit.*)
    *(.text.startup .text.startup.*)
    *(.text.hot .text.hot.*)
    *(SORT(.text.sorted.*))
    *(.text .stub .text.* .gnu.linkonce.t.*)
    /* .gnu.warning sections are handled specially by elf.em.  */
    *(.gnu.warning)
  }
  ...
}
```

At the same time CLANG compiler (with LLD linker) doesn't provide such an information:
```
$ clang -fuse-ld=lld -o main main.c -Wl,--verbose
ld.lld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o
...
ld.lld: /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a
ld.lld: /usr/lib/gcc/x86_64-linux-gnu/9/crtend.o
ld.lld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
```

**Comment by bd1976bris** [comment] 2022-02-23 10:33
LLD doesn't have a default linker script, by default the linker is driven by internal rules that aim to create GNU compatible output.
LLD does support linker scripts (which can be specified with the _"--script -= file , -T file"_ option); so, if you need a linker script, you should be able to dump the default GNU one and use that as a starting point for your linker script.

**Comment by P1119r1m** [comment] 2022-02-23 14:04
@bd1976bris 
Thank you for your reply.

It is a bit inconvenient to use GNU Binutils's LD linker.
Moreover, Binutils's LD linker can provide around 150 different linker scripts.
Such variety of different linker scripts is a result of different options used during compilation.

Isn't it possible for the Clang's LLD to generate its own linker script, which can be modified by the developer later?
I don't think that this is such a difficult task for LLD Clang.
As far as I know the CLANG/LLD was designed as a full replacement of the GCC compiler, not as a little brother :)

**Comment by MaskRay** [comment] 2022-03-09 01:00
Duplicate of #50651

**Closed by MaskRay** 2022-03-09 01:00 UTC
Labels: lld, lld:ELF
