### ISSUE TITLE
c++20/libstdc++: `char_traits.h:213:13: note: subexpression not valid in a constant expression`

### ISSUE THREAD

**Issue by timblechmann** [llvm/llvm-project#58754] opened 2022-11-02 08:22 UTC
using this constexpr boost static_string (requires static_string develop) does not compile with clang against libstdc++ (g++ compiles against libstdc++ also clang++ compiles against libc++).

```c++
#include <boost/static_string.hpp>
using str = boost::static_strings::static_string<38>;
constexpr str a{ "mystr" };
```

```
c.cpp:5:15: error: constexpr variable 'a' must be initialized by a constant expression
constexpr str a{ "mystr" };
              ^~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/char_traits.h:213:13: note: subexpression not valid in a constant expression
   if (__s1 == __s2)
            ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/char_traits.h:417:11: note: in call to 'move(&a.static_string_base::data_[0], &"mystr"[0], 5)'
   return __gnu_cxx::char_traits<char_type>::move(__s1, __s2, __n);
          ^
/home/tim/NIBuild/3rdparty/boost-v1.78.0-R8/boost/static_string/static_string.hpp:6000:3: note: in call to 'move(&a.static_string_base::data_[0], &"mystr"[0], 5)'
  traits_type::move(data(), s, size());
  ^
/home/tim/NIBuild/3rdparty/boost-v1.78.0-R8/boost/static_string/static_string.hpp:1413:12: note: in call to '&a->assign(&"mystr"[0], 5)'
    return assign(s, traits_type::length(s));
           ^
/home/tim/NIBuild/3rdparty/boost-v1.78.0-R8/boost/static_string/static_string.hpp:961:5: note: in call to '&a->assign(&"mystr"[0])'
    assign(s);
    ^
c.cpp:5:15: note: in call to 'basic_static_string(&"mystr"[0])'
constexpr str a{ "mystr" };
              ^
1 error generated.
```

the offending code in libstdc++ is this one:
```
	  if (__s1 == __s2) // unlikely, but saves a lot of work
	    return __s1;
```
https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/char_traits.h#L216-L217

**Comment by tbaederr** [comment] 2022-11-02 08:34
Also reproducible using:

```c++
constexpr const char *f (const char* a, const char *b) {
  if (a == b)
    return a;

  return b;
}


constexpr const char *k = f("a", "b");
```

**Comment by tbaederr** [comment] 2022-11-02 08:44
And we return failure (and print the diagnostic) because:

https://github.com/llvm/llvm-project/blob/be369ea31b98f23c7d8e7a83ea4a1b4cf76b544f/clang/lib/AST/ExprConstant.cpp#L12955-L12960

**Comment by AaronBallman** [comment] 2022-11-02 12:11
Heh, that's a fun one. http://eel.is/c++draft/lex.string#9 is what that code is referring to and I believe Clang is correct to reject it as  a core constant expression per http://eel.is/c++draft/expr.const#5.24 because the equality operator's results are unspecified.

**Comment by jwakely** [comment] 2022-11-02 12:31
This is a libstdc++ bug.

**Comment by jwakely** [comment] 2022-11-02 12:32
And a g++ bug, for letting me do it.

**Comment by AaronBallman** [comment] 2022-11-02 12:43
Thank you for confirming @jwakely -- I'm closing this as not a bug.

**Comment by shafik** [comment] 2022-11-03 03:51
Note this is even true in C and that writeable string literals was a thing: https://stackoverflow.com/a/26279717/1708801

**Comment by timblechmann** [comment] 2022-11-03 05:50
@jwakely, do i need to submit a gcc bug or are you already on it?

**Comment by timblechmann** [comment] 2022-11-03 05:50
thanks everyone for the quick feedback, btw!

**Comment by jwakely** [comment] 2022-11-03 14:19
Could you report a gcc bug please? I probably won't work on it until next month.

**Comment by timblechmann** [comment] 2022-11-04 09:42
linking the discussion in gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107521

> When string literals are involved, I think this is [PR86369](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86369) instead, and Jason said he thinks GCC is correct there, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86369#c8

> And e.g. https://godbolt.org/z/qfzTT5jna from that PR is I think clearly a clang bug, not a grey area, neither string literal is evaluated there multiple times.

**Comment by timblechmann** [comment] 2022-11-06 02:08
@AaronBallman & @tbaederr, could you possibly check the discussions in the gcc bug tracker? there seem to be some arguments that it's a bug in clang, not in libstdc++. in that case, it would be great if this issue could be reopened.

many thanks!

**Comment by tbaederr** [comment] 2022-11-07 05:50
Yep, we talked about reopening on IRC already.

**Comment by tbaederr** [comment] 2022-11-07 06:10
If this:

```c++
constexpr auto foo(const char *p) { return p; }
constexpr auto p1 = "test1";
constexpr auto p2 = "test2";

constexpr bool b1 = foo(p1) == foo(p1);
static_assert(b1);

constexpr bool b2 = foo(p1) == foo(p2);
static_assert(!b2);

constexpr auto name1() { return "name1"; }
constexpr auto name2() { return "name2"; }

constexpr auto b3 = name1() == name1();
static_assert(b3);
constexpr auto b4 = name1() == name2();
static_assert(!b4);
```

should work without errors, is this a special case for character literals or should this work for every kind of literal? I can't come up with a test case for this right now with something that's not a string literal. But maybe it's just too early.

**Comment by jwakely** [comment] 2022-11-07 12:10
> or should this work for every kind of literal?

Are there other kinds of literals that decay to a pointer to the literal, such that the address is significant (or even observable)?

`int&& rval = 1;` is not the same, that materializes a temporary from the literal, and binds the rvalue reference to the temporary. In such a case, the temporary is not the literal. For a string literal, the `const char*` that it decays to points to the actual string literal object with static storage duration, not some materialized temporary. I don't think there are other equivalent cases.

**Comment by jwakely** [comment] 2022-11-07 13:12
[expr.prim.literal] p1:

> A _string-literal_ is an lvalue designating a corresponding string literal object ([lex.string]), a _user-defined-literal_ has the same value category as the corresponding operator call expression described in [lex.ext], and any other _literal_ is a prvalue.

You can't observe the address of a prvalue. I don't think user-defined literals are relevant here, they're just normal functions and follow the same rules for their return value as the rest of the language. String literals are the special case that produce an lvalue.

**Closed** 2024-09-13 08:30 UTC
Labels: c++20, clang:frontend, libstdc++

**Comment by shafik** [comment] 2024-09-16 21:06
@jyknight I believe this would be [cwg2765](https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2765) which is still open [Discussion in Tokyo](https://wiki.edg.com/bin/view/Wg21tokyo2024/CoreWorkingGroup).

There are lot of different ways this could go. If you have interest in a specific outcome then perhaps a paper or making sure someone is in core next time this is discussed would help move it forward.

**Comment by zygoloid** [comment] 2024-09-16 21:16
The new behavior does not appear to be correct, and will lead to miscompiles in some circumstances. For example:

```c++
constexpr auto p1 = "test";
constexpr auto p2 = "test";
void g(), h();
void f() {
  const bool eq1 = p1 == p2;
  if (eq1) g();
  bool eq2 = p1 == p2;
  if (eq2) h();
}
```

... is required to call either both `g()` and `h()` or neither. After this change, clang trunk calls just `h()`, which is a miscompile.

It seems to me that treating the comparisons as non-constant is the least-bad thing we can do until CWG2765 is resolved, so I think we should revert the change.

**Comment by zygoloid** [comment] 2024-09-18 22:15
I read through the current CWG discussions, and have implemented what appears to be the current thinking in #109208. What do we think about going in a direction like that? Broadly:

- Each time we evaluate a `StringLiteral`, give it a version number.
- Allow comparisons between `StringLiteral`s with the same version.
- Also allow comparisons between `StringLiteral`s that cannot possibly overlap because they have different contents.
- Disallow all the remaining comparisons on the basis that the result is unspecified.
