### ISSUE TITLE
HLFIR error in flang-new

### ISSUE THREAD

**Issue by eschnett** [llvm/llvm-project#85420] opened 2024-03-15 16:00 UTC
I am building on macOS with a MacPorts-provided flang-new:
```
$ flang-new-mp-18 --version
flang-new version 18.1.1
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-18/bin
```

I see this error:
```
$ flang-new-mp-18 -c hello-world-fortran08.f90
error: loc("/tmp/f/hello-world-fortran08.f90":4:3): /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_llvm-18/flang-18/work/llvm-project-18.1.1.src/flang/lib/Lower/ConvertExprToHLFIR.cpp:309: not yet implemented: lowering symbol to HLFIR
LLVM ERROR: aborting
```

The same code works with LLVM version 17.

The source code is spread over several source files (several modules and one main program). I tried to reduce the number of modules but this made the error go away. I am thus submitting several files. I did reduce the test case to 71 lines overall. I am also including a script `build.sh` that builds the modules in a correct order.

(The instructions for reporting an LLVM bug don't quite work because they assume I'm using the C/C++ compiler clang, and flang-new doesn't accept the same command line options.)

[files.tar.gz](https://github.com/llvm/llvm-project/files/14617895/files.tar.gz)

**Comment by jeanPerier** [comment] 2024-03-21 14:28
Hi @eschnett, thanks for the bug report and reproducer, #86121 should fix the issue you saw.

**Comment by jeanPerier** [comment] 2024-10-09 14:42
Hi @eschnett, the fix is part of LLVM-20, I am closing the issue given your reproducer works for me, feel to re-open it you still see issues in the original program.

**Closed by jeanPerier** 2024-10-09 14:42 UTC
Labels: flang:fir-hlfir
