### ISSUE TITLE
[lldb]  Not able to get the right template argument type via python API.

### ISSUE THREAD

**Issue by dprogm** [llvm/llvm-project#58492] opened 2022-10-20 08:03 UTC
I am currently trying to write my own data formatter for some variadic template class. Here is a simple example:
```cpp
template<typename...T>
class MyVariadic
{
private:
  int which{1};
};

int main()
{
  MyVariadic<int, float> myVariadic;
  return 0;
}
```

The corresponding data formatter looks like this:

```python
class MyVariadicSyntheticChildrenProvider:

  def __init__(self, valobj, internal_dict):
    self.valobj = valobj

  def num_children(self):
    return 1

  def has_children(self):
    return True

  def get_child_index(self, name):
    return None

  def get_child_at_index(self, index):
    which = self.valobj.GetChildMemberWithName('which').signed

    numberOfArgs = self.valobj.GetType().GetNumberOfTemplateArguments()
    print("Number of Args: ", numberOfArgs)
    templateType = self.valobj.GetType().GetTemplateArgumentType(which)
    print("Template Type: ", templateType)

    return None

  def update(self):
    pass

def __lldb_init_module(debugger, dict):
  debugger.HandleCommand('type synthetic add -l type_formatters.MyVariadicSyntheticChildrenProvider -x "^MyVariadic<.+>$')
```

**My expectations are:**
- `GetNumberOfTemplateArguments()` returns 2, but it actually returns 1
- `GetTemplateArgumentType(which)` returns float, but it actually returns 'No Value'

I was also trying to get the type via `target.FindFirstType(typeAsString)` but without success. A similar issue can be found here https://github.com/llvm/llvm-project/issues/31647.

**Comment by Michael137** [comment] 2022-10-20 08:45
Which lldb version are you using?

iirc @JDevlieghere's parameter pack support in https://reviews.llvm.org/D51387 should handle this

**Comment by dprogm** [comment] 2022-10-20 09:32
I am currently using version 15.0.0 bundled with the VS Code extension CodeLLDB.

**Comment by Michael137** [comment] 2022-10-20 15:18
Seems to work on top-of-tree LLDB:

```
$ ./run.sh                                                                                                               
lldb version 16.0.0git (https://github.com/Michael137/llvm-project.git revision 2dacb2f2758f7f45a1e56fbe6603d98f678fe0b4)
  clang revision 2dacb2f2758f7f45a1e56fbe6603d98f678fe0b4                                                                
  llvm revision 2dacb2f2758f7f45a1e56fbe6603d98f678fe0b4                                                                 
(lldb) target create "a.out"                                                                                             
Current executable set to 'a.out' (arm64).                        
(lldb) br se -p return -X main                                                                                           
Breakpoint 1: where = a.out`main + 36 at main.cpp:11:3, address = 0x0000000100003f5c                                     
(lldb) r                                                                                                                 
Process 39824 stopped                                                                                                    
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1                                               
    frame #0: 0x0000000100003f5c a.out`main at main.cpp:11:3                                                             
   8    int main()                                                                                                       
   9    {                                                                                                                
   10     MyVariadic<int, float> myVariadic;                                                                             
-> 11     return 0;                                                                                                      
   12   }                                                                                                                
Process 39824 launched: 'a.out' (arm64)                           
(lldb) script                                                                                                            
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.                                              
>>> var = lldb.frame.FindVariable("myVariadic")                                                                          
>>> var.GetType(). GetNumberOfTemplateArguments()                                                                        
2                                                                                                                        
>>> var.GetType(). GetTemplateArgumentType(0)                                                                            
int                                                                                                                      
>>> var.GetType(). GetTemplateArgumentType(1)                                                                            
float                                                                                                                    
>>> which = var.GetChildMemberWithName('which').signed                                                                   
>>> var.GetType().GetTemplateArgumentType(which)                                                                         
float                                                                                                                    
```

It looks like the fix didn't quite make it into the llvm-15 release, by couple of weeks. Unfortunately the 15.x release milestone has been closed and it looks like only major issues are eligible for a backport.

**Comment by dprogm** [comment] 2022-10-21 09:30
Thank you for your investigation. I tried to build the latest lldb but ld crashes with signal 9. Can you tell me when this will land in an official release? 16?

**Comment by Michael137** [comment] 2022-10-21 09:35
@dprogm oh, looks like it was decided just now that 15.0.4 will be released after all (https://discourse.llvm.org/t/llvm-15-0-4-release-schedule-update/66099). We could try cherry-picking this then

**Comment by dprogm** [comment] 2022-10-21 12:11
I am now able to build the latest lldb (1809414fe19a80afb1fb929e2e6a0c80b0f854f1) and can indeed verify that I get the right number of template arguments and also the type seems to be correct. However if I slightly modify my example to the following
```cpp
int main()
{
  MyVariadic<int, float, MyVariadic<double,std::string>> myVariadic;
  return 0;
}
```
it returns for the type at index 2:
- `var.GetType().GetTemplateArgumentType(2).GetNumberOfTemplateArguments()` = 0
- `var.GetType().GetTemplateArgumentType(2)` = template<> class MyVariadic<>

My expectation is that it resolves the correct template instantiation or I am wrong in my assumption?

**Comment by Michael137** [comment] 2022-10-21 12:40
The AST LLDB constructs looks mighty suspicious
```
(lldb) p myVariadic
(MyVariadic<int, float, MyVariadic<> >) $0 = (which = 1)
(lldb) target dump typesystem
State of scratch Clang type system:
...
|-ClassTemplateDecl 0x15c09ca30 <<invalid sloc>> <invalid sloc> MyVariadic
| |-TemplateTypeParmDecl 0x15c09c880 <<invalid sloc>> <invalid sloc> class depth 0 index 0 ... T
| |-CXXRecordDecl 0x15c09c948 <<invalid sloc>> <invalid sloc> <undeserialized declarations> class MyVariadic
| `-ClassTemplateSpecialization 0x15c09d100 'MyVariadic'
|-ClassTemplateDecl 0x15c09cdb8 <<invalid sloc>> <invalid sloc> MyVariadic
| |-CXXRecordDecl 0x15c09ccd8 <<invalid sloc>> <invalid sloc> <undeserialized declarations> class MyVariadic
| `-ClassTemplateSpecialization 0x15c09cfa8 'MyVariadic'
|-ClassTemplateSpecializationDecl 0x15c09cfa8 <<invalid sloc>> <invalid sloc> <undeserialized declarations> class MyVariadic
`-ClassTemplateSpecializationDecl 0x15c09d100 <<invalid sloc>> <invalid sloc> <undeserialized declarations> class MyVariadic definition
  |-DefinitionData pass_in_registers standard_layout trivially_copyable trivial literal
  | |-DefaultConstructor exists trivial needs_implicit
  | |-CopyConstructor simple trivial has_const_param needs_implicit implicit_has_const_param
  | |-MoveConstructor exists simple trivial needs_implicit
  | |-CopyAssignment simple trivial has_const_param needs_implicit implicit_has_const_param
  | |-MoveAssignment exists simple trivial needs_implicit
  | `-Destructor simple irrelevant trivial needs_implicit
  |-TemplateArgument pack
  | |-TemplateArgument type 'int'
  | | `-BuiltinType 0x15c098f10 'int'
  | |-TemplateArgument type 'float'
  | | `-BuiltinType 0x15c099010 'float'
  | `-TemplateArgument type 'MyVariadic<>'
  |   `-RecordType 0x15c09d090 'MyVariadic<>'
  |     `-ClassTemplateSpecialization 0x15c09cfa8 'MyVariadic'
  `-FieldDecl 0x15c09d290 <<invalid sloc>> <invalid sloc> which 'int'
```

Seems more like an expression evaluator bug than an unhandled edge-case of the SBAPI change.

**Comment by Michael137** [comment] 2022-10-21 12:45
Compare that to the AST that clang constructs:
```
$ clang++ -std=c++2a -g -O0 -Xclang -ast-dump -fsyntax-only main.cpp
...
ClassTemplateDecl 0x154860f40 <main.cpp:1:1, line:6:1> line:2:7 MyVariadic
|-TemplateTypeParmDecl 0x154860df0 <line:1:10, col:21> col:21 typename depth 0 index 0 ... T
|-CXXRecordDecl 0x154860eb0 <line:2:1, line:6:1> line:2:7 class MyVariadic definition
| |-DefinitionData standard_layout trivially_copyable literal has_constexpr_non_copy_move_ctor can_const_default_init
| | |-DefaultConstructor exists non_trivial constexpr needs_implicit defaulted_is_constexpr
| | |-CopyConstructor simple trivial has_const_param needs_implicit implicit_has_const_param
| | |-MoveConstructor exists simple trivial needs_implicit
| | |-CopyAssignment simple trivial has_const_param needs_implicit implicit_has_const_param
| | |-MoveAssignment exists simple trivial needs_implicit
| | `-Destructor simple irrelevant trivial constexpr needs_implicit
| |-CXXRecordDecl 0x154861210 <col:1, col:7> col:7 implicit class MyVariadic
| |-AccessSpecDecl 0x1548612a0 <line:4:1, col:8> col:1 private
| `-FieldDecl 0x1548612e0 <line:5:3, col:14> col:7 which 'int'
|   `-InitListExpr 0x1548613f8 <col:12, col:14> 'int'
|     `-IntegerLiteral 0x154861380 <col:13> 'int' 1
|-ClassTemplateSpecializationDecl 0x154881c18 <line:1:1, line:6:1> line:2:7 class MyVariadic
| `-TemplateArgument pack
|   `-TemplateArgument type 'int'
|     `-BuiltinType 0x154829110 'int'
`-ClassTemplateSpecializationDecl 0x154881de8 <line:1:1, line:6:1> line:2:7 class MyVariadic definition
  |-DefinitionData pass_in_registers standard_layout trivially_copyable literal has_constexpr_non_copy_move_ctor can_const_default_init
  | |-DefaultConstructor exists non_trivial constexpr defaulted_is_constexpr
  | |-CopyConstructor simple trivial has_const_param implicit_has_const_param
  | |-MoveConstructor exists simple trivial
  | |-CopyAssignment simple trivial has_const_param needs_implicit implicit_has_const_param
  | |-MoveAssignment exists simple trivial needs_implicit
  | `-Destructor simple irrelevant trivial constexpr needs_implicit
  |-TemplateArgument pack
  | |-TemplateArgument type 'int'
  | | `-BuiltinType 0x154829110 'int'
  | |-TemplateArgument type 'float'
  | | `-BuiltinType 0x154829210 'float'
  | `-TemplateArgument type 'MyVariadic<int>'
  |   `-RecordType 0x154881d00 'MyVariadic<int>'
  |     `-ClassTemplateSpecialization 0x154881c18 'MyVariadic'
...
```

Note how the second `ClassTemplateSpecializationDecl MyVariadic` has a `TemplateArgument` child, which is not the case with LLDB's AST.

**Comment by Michael137** [comment] 2022-10-23 11:21
> I am now able to build the latest lldb ([1809414](https://github.com/llvm/llvm-project/commit/1809414fe19a80afb1fb929e2e6a0c80b0f854f1)) and can indeed verify that I get the right number of template arguments and also the type seems to be correct. However if I slightly modify my example to the following
> 
> ```c++
> int main()
> {
>   MyVariadic<int, float, MyVariadic<double,std::string>> myVariadic;
>   return 0;
> }
> ```
> 
> it returns for the type at index 2:
> 
> * `var.GetType().GetTemplateArgumentType(2).GetNumberOfTemplateArguments()` = 0
> * `var.GetType().GetTemplateArgumentType(2)` = template<> class MyVariadic<>
> 
> My expectation is that it resolves the correct template instantiation or I am wrong in my assumption? Note that in case of types that have a fixed number of template arguments such as `std::string` it resolves the correct type.

Ok took another look at your example. The problem is actually that there's not enough debug-info available to resolve the `MyVariadic` template argument since it was never instantiated in the program (outside a compile-time context). See this debug-info:
```
0x00001fd2:     DW_TAG_variable
                  DW_AT_location        (DW_OP_breg31 WSP+8)
                  DW_AT_name    ("myVariadic")
                  DW_AT_decl_file       ("/Users/michaelbuch/Apple-internal/Radar/variadic-sbapi/example.cpp")
                  DW_AT_decl_line       (13)
                  DW_AT_type    (0x0000000000001fe1 "MyVariadic<int, float, MyVariadic<double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >")

...

0x00001fe1:   DW_TAG_class_type
                DW_AT_calling_convention        (DW_CC_pass_by_value)
                DW_AT_name      ("MyVariadic<int, float, MyVariadic<double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >")
                DW_AT_byte_size (0x04)
                DW_AT_decl_file ("/Users/michaelbuch/Apple-internal/Radar/variadic-sbapi/example.cpp")
                DW_AT_decl_line (4)

0x00001fea:     DW_TAG_GNU_template_parameter_pack
                  DW_AT_name    ("T")

0x00001fef:       DW_TAG_template_type_parameter
                    DW_AT_type  (0x000000000000083b "int")

0x00001ff4:       DW_TAG_template_type_parameter
                    DW_AT_type  (0x0000000000000927 "float")

0x00001ff9:       DW_TAG_template_type_parameter
                    DW_AT_type  (0x0000000000002018 "MyVariadic<double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >")

...

0x00002018:   DW_TAG_class_type
                DW_AT_name      ("MyVariadic<double, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >")
                DW_AT_declaration       (true)
```

Observer how at `0x00002018` the debug-info for the `MyVariadic<double, std::string>` instantiation is just a forward declaration without any further information about its template argument types. So LLDB doesn't know what the arguments to this instantiation were.

If we instead modify the example to instantiate the template beforehand the SBAPI works as expected:
```
int main()                                                          
{                                                                   
  MyVariadic<double,std::string> instantiation;                     
  MyVariadic<int, float, MyVariadic<double,std::string>> myVariadic;
  return 0;                                                         
}                                                                   
```

```
(lldb) script                                                                                             
Python Interactive Interpreter. To exit, type 'quit()', 'exit()' or Ctrl-D.                                                                                                                                           
>>> var = lldb.frame.FindVariable("myVariadic")                                                                                                                                                                       
>>> var.GetType().GetTemplateArgumentType(2).GetNumberOfTemplateArguments()                                
2                                                                                                          
>>> var.GetType().GetTemplateArgumentType(2)                                                               
template<> class MyVariadic<<double, std::basic_string<char, std::char_traits<char>, std::allocator<char> >>> {                                                                                                       
    int which;                                       
}                                                                                                                                                                                                                    
```

**Comment by dprogm** [comment] 2022-10-24 15:00
Thank you for the analysis. So as far as I understood this is not a debugger issue but an incomplete use case from my side. In real world applications this should not appear because at some point in my program there must be at least one instantiation when I use the type in the context of a memory allocation (variable declaration)?

**Comment by dwblaikie** [comment] 2022-10-24 18:26
Code can instantiate a declaration of a template (eg: "t1<int> *v;" would only instantiate the declaration of "t1<int>") - when that happens, the DWARF generated by Clang (& GCC, I think) is just a declaration with a name "t1<int>" and no structural description of the template parameters. You can turn off this feature (turn on structural descriptions of template parameters even for declarations) with a private/implementation detail flag in clang, if that's of interest. `-Xclang -debug-forward-template-params` would do that.

**Closed** 2022-10-25 09:17 UTC
Labels: lldb, release:fixed-in-main
