### ISSUE TITLE
LLVM ERROR: cannot select f32 fcanonicalize on x86

### ISSUE THREAD

**Issue by CAD97** [llvm/llvm-project#60324] opened 2023-01-27 01:48 UTC
This is quite possibly just a misuse of the intrinsic, but the error said to report it, so here's the report. [[godbolt]](https://llvm.godbolt.org/z/jsa1We8ch)

Input LLVM IR:

```llvm
declare float
@llvm.canonicalize.f32(float %a)

define float
@tgt(float noundef) {
   %r = call float @llvm.canonicalize.f32(float %0)
   ret float %r
}
```

Error:

```text

LLVM ERROR: Cannot select: 0x55f4083e4500: f32 = fcanonicalize 0x55f4083e4490
  0x55f4083e4490: f32,ch = CopyFromReg 0x55f408363770, Register:f32 %0
    0x55f4083e4420: f32 = Register %0
In function: tgt
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
1.	Running pass 'Function Pass Manager' on module '<source>'.
2.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@tgt'
 #0 0x000055f403a9aa3f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3352a3f)
 #1 0x000055f403a984b4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f8c69eba420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f8c6998700b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f8c69966859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x000055f401068a4a llvm::UniqueStringSaver::save(llvm::StringRef) (.cold) StringSaver.cpp:0:0
 #6 0x000055f40387bf80 llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3133f80)
 #7 0x000055f4038812c2 llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) (/opt/compiler-explorer/clang-trunk/bin/llc+0x31392c2)
 #8 0x000055f402316382 (anonymous namespace)::X86DAGToDAGISel::Select(llvm::SDNode*) X86ISelDAGToDAG.cpp:0:0
 #9 0x000055f403879dc7 llvm::SelectionDAGISel::DoInstructionSelection() (/opt/compiler-explorer/clang-trunk/bin/llc+0x3131dc7)
#10 0x000055f403885a79 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/opt/compiler-explorer/clang-trunk/bin/llc+0x313da79)
#11 0x000055f4038887ff llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x31407ff)
#12 0x000055f40388aeef llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (.part.0) SelectionDAGISel.cpp:0:0
#13 0x000055f4023201b5 (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) X86ISelDAGToDAG.cpp:0:0
#14 0x000055f402d236a0 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#15 0x000055f403212520 llvm::FPPassManager::runOnFunction(llvm::Function&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2aca520)
#16 0x000055f403212699 llvm::FPPassManager::runOnModule(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2aca699)
#17 0x000055f403213280 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2acb280)
#18 0x000055f401139553 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#19 0x000055f40107505a main (/opt/compiler-explorer/clang-trunk/bin/llc+0x92d05a)
#20 0x00007f8c69968083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#21 0x000055f4011311ae _start (/opt/compiler-explorer/clang-trunk/bin/llc+0x9e91ae)
Compiler returned: 139
```

**Comment by RKSimon** [comment] 2023-01-27 10:54
Duplicate of #32650 (which never reached a resolution either)

**Closed** 2023-01-27 10:54 UTC
Labels: backend:X86, crash
