### ISSUE TITLE
RISCV LLVM auto vectorization

### ISSUE THREAD

**Issue by SkAditAziz** [llvm/llvm-project#53536] opened 2022-02-02 09:49 UTC
How to generate stripminned assembly vector code for riscv target?
for this loop, clang generates less efficient code with so much overlap checking! Is there any way to tell the compiler to use strip minning?

void test_add(int *A, int *B, int * __restrict__ C, int n)
{
    for (int i = 0; i < n; i++)
        C[i] = A[i] + B[i];
}

**Comment by fhahn** [comment] 2022-02-02 10:22
Could you please clarify what the issue is here by sharing the flags used and the generated assembly/IR.

It is not clear to me what kind of overlap-checking you are referring to. LLVM's loop vectorizer won't generate any pointer overlap checks:
https://clang.godbolt.org/z/TGE4ahc16

**Comment by SkAditAziz** [comment] 2022-02-02 10:28
we are using these flags:

-menable-experimental-extensions -march=rv64gcv0p10 -target riscv64 -O3 -mllvm --riscv-v-vector-bits-min=2048

I am attaching the generated assembly code.
[test_add.txt](https://github.com/llvm/llvm-project/files/7985566/test_add.txt)

**Comment by fhahn** [comment] 2022-02-02 10:40
I think this works as expected. 

LLVM adds 2 extra checks up-front, one to check that the trip count is >= 32 and another one if the trip count is >= 128. If both succeed, the main vector loop is executed (it uses VF=64, UF=2). If only the first one succeeds, the epilogue vector loop is executed, which uses VF=32.

The reason an epilogue vector loop is also generated is because of the large main vectorization factor due to the large vector width.

> for this loop, clang generates less efficient code with so much overlap checking! Is there any way to tell the compiler to use strip minning?

Could you clarify what code is much less efficient? As mentioned, we have 2 minimum iteration checks due to epilogue vectorization happening. But we need at least one of them even if we do not perform epilogue vectorization.

**Comment by fhahn** [comment] 2022-02-02 10:43
For reference, see the results on godbolt: https://clang.godbolt.org/z/hf918753j

**Comment by fhahn** [comment] 2022-02-02 12:10
I am closing this for now as working as expected. If you think there's an issue here, please provide more details & data about what makes the code much less efficient compared to an optimal version.

**Closed by fhahn** 2022-02-02 12:10 UTC
Labels: new issue
