### ISSUE TITLE
overload resolution fails with conversion operator to const&&

### ISSUE THREAD

**Issue by rollbear** [llvm/llvm-project#73692] opened 2023-11-28 19:34 UTC
This (admittedly weird) code gives a curious compilation error with all versions of clang. Tested from 4.0 to 17 and main branch.

```C++
struct S
{
    operator const int&&() const;
};

void f(int&&);
void f(const int&&);

int main()
{
    S s;
    f(s);
}
```

The error message is (from compiler explorer with clang trunk @ e1f911e40ce6ad4a7f393ea1b33e65b24940eb84):
```
<source>:12:7: error: no viable conversion from 'S' to 'int'
   12 |     f(s);
      |       ^
<source>:3:5: note: candidate function
    3 |     operator const int&&() const;
      |     ^
<source>:6:13: note: passing argument to parameter here
    6 | void f(int&&);
      |             ^
1 error generated.
Compiler returned: 1
```

For comparison, both gcc and MSVC both use call the correct overload using the conversion operator.

https://godbolt.org/z/orhEEhf3e

**Comment by shafik** [comment] 2023-11-29 01:03
Looks like a duplicate of: https://github.com/llvm/llvm-project/issues/61121

**Closed by shafik** 2023-11-29 01:03 UTC
Labels: clang:frontend
