### ISSUE TITLE
Wasm-ld crash

### ISSUE THREAD

**Issue by harutyuntagushyan8** [llvm/llvm-project#69335] opened 2023-10-17 14:15 UTC
I'm building project with emscripten(3.1.47) in which clang version is 18.0.0.
In linking state I got crash with this stacktrace`

Stack dump:
0.	Program arguments: /Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/wasm-ld @/var/folders/7g/wm08bcvs20lbf6y0lzp_zm840000gn/T/emscripten_e0r14oju.rsp.utf-8
 #0 0x000000010909cfc8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100145fc8)
 #1 0x000000010909a9d5 llvm::sys::RunSignalHandlers() (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x1001439d5)
 #2 0x000000010909dbd6 SignalHandler(int) (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100146bd6)
 #3 0x00007ff81327637d (/usr/lib/system/libsystem_platform.dylib+0x7ff80046637d)
 #4 0x00000001094a68dd bool llvm::DenseMapBase<llvm::DenseMap<lld::wasm::ImportKey<llvm::wasm::WasmSignature>, unsigned int, llvm::DenseMapInfo<lld::wasm::ImportKey<llvm::wasm::WasmSignature>, void>, llvm::detail::DenseMapPair<lld::wasm::ImportKey<llvm::wasm::WasmSignature>, unsigned int>>, lld::wasm::ImportKey<llvm::wasm::WasmSignature>, unsigned int, llvm::DenseMapInfo<lld::wasm::ImportKey<llvm::wasm::WasmSignature>, void>, llvm::detail::DenseMapPair<lld::wasm::ImportKey<llvm::wasm::WasmSignature>, unsigned int>>::LookupBucketFor<lld::wasm::ImportKey<llvm::wasm::WasmSignature>>(lld::wasm::ImportKey<llvm::wasm::WasmSignature> const&, llvm::detail::DenseMapPair<lld::wasm::ImportKey<llvm::wasm::WasmSignature>, unsigned int> const*&) const (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x10054f8dd)
 #5 0x00000001094ac861 lld::wasm::writeResult() (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100555861)
 #6 0x000000010946ed27 lld::wasm::(anonymous namespace)::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100517d27)
 #7 0x000000010946abad lld::wasm::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100513bad)
 #8 0x00000001090b0553 lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100159553)
 #9 0x0000000108fe7c62 lld_main(int, char**, llvm::ToolContext const&) (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100090c62)
#10 0x0000000108fe8361 main (/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/lld+0x100091361)
#11 0x00007ff812ec03a6
em++: error: '/Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/bin/wasm-ld @/var/folders/7g/wm08bcvs20lbf6y0lzp_zm840000gn/T/emscripten_e0r14oju.rsp.utf-8' failed (received SIGSEGV (-11))
ninja: build stopped: subcommand failed.

**Comment by harutyuntagushyan8** [comment] 2023-10-17 14:32
FAILED: javascript/pi.js
: && /Users/htagushyan/repos/pi-libs/javascript/emsdk/upstream/emscripten/em++ -O3 -DNDEBUG -flto -fuse-ld=lld -pthread "-sPTHREAD_POOL_SIZE=Math.max(_emscripten_num_logical_cores() + 12, 16)" -Wl,--gc-sections -Wl,--wrap=__cxa_throw -Wl,--fatal-warnings --bind -sMODULARIZE=1 "-sEXPORTED_RUNTIME_METHODS=['EGL']" -sEXPORT_NAME=createPIModule -sWASM=1 -sDEFAULT_TO_CXX=0 -sALLOW_MEMORY_GROWTH=1 -sMAX_WEBGL_VERSION=2 -sFULL_ES3=1 -sLLD_REPORT_UNDEFINED --no-entry -sEXIT_RUNTIME=1 -fwasm-exceptions -Wno-pthreads-mem-growth --emit-symbol-map -sENVIRONMENT=web,webview,worker --pre-js=/Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/pi/pre.js --post-js=/Users/htagushyan/repos/pi-libs/javascript/pi/post.js -sEXPORT_ES6=1 -Wl,--whole-archive /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/src/utils/libpilibs_javascript_src_utils.a /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/src/bindings/libpilibs_javascript_src_bindings.a /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/src/bindings/fx/libpilibs_javascript_src_bindings_fx.a -Wl,--no-whole-archive -flto javascript/CMakeFiles/pijs.dir/__/pilibs_dummy.cpp.o -o javascript/pi.js  libpilibs.a  pi/Accelerate/libpilibs_pi_accelerate.a  pi/accelerate_helper/libpilibs_pi_accelerate_helper.a  pi/accelerate_helper/phoenix/libpilibs_pi_accelerate_helper_phoenix.a  pi/basic_ops/gles/libpilibs_pi_basic_ops_gles.a  pi/basic_ops/cpu/libpilibs_pi_basic_ops_cpu.a  pi/basic_ops/gpu/libpilibs_pi_basic_ops_gpu.a  pi/convert_ops/cpu/libpilibs_pi_convert_ops_cpu.a  pi/convert_ops/gpu/libpilibs_pi_convert_ops_gpu.a  pi/core/libpilibs_pi_core.a  pi/core/tasks/libpilibs_pi_core_tasks.a  pi/core/kvc/libpilibs_pi_core_kvc.a  pi/effects/algorithms/libpilibs_pi_effects_algorithms.a  pi/effects_ops/gles/libpilibs_pi_effects_ops_gles.a  pi/effects_ops/cpu/libpilibs_pi_effects_ops_cpu.a  pi/effects_ops/gpu/libpilibs_pi_effects_ops_gpu.a  pi/effects_ops/shared/libpilibs_pi_effects_ops_shared.a  pi/filter_ops/gles/libpilibs_pi_filter_ops_gles.a  pi/filter_ops/cpu/libpilibs_pi_filter_ops_cpu.a  pi/filter_ops/gpu/libpilibs_pi_filter_ops_gpu.a  pi/kernel_gen/libpilibs_pi_kernel_gen.a  pi/fx/core/libpilibs_pi_fx_core.a  pi/fx/parameters/libpilibs_pi_fx_parameters.a  pi/fx/resources/libpilibs_pi_fx_resources.a  pi/geometry_ops/cpu/libpilibs_pi_geometry_ops_cpu.a  pi/graph/bases/libpilibs_pi_graph_bases.a  pi/graph/core/libpilibs_pi_graph_core.a  pi/graph/factory/libpilibs_pi_graph_factory.a  pi/graph/lua/libpilibs_pi_graph_lua.a  pi/graph/lua/bindings/libpilibs_pi_graph_lua_bindings.a  pi/graph/json/traits/libpilibs_pi_graph_json_traits.a  pi/graph/profiler/libpilibs_pi_graph_profiler.a  pi/graph/value_ops/libpilibs_pi_graph_value_ops.a  pi/imgcodecs/libpilibs_pi_imgcodecs.a  pi/imgproc/algorithm/libpilibs_pi_imgproc_algorithm.a  pi/imgproc/transform/libpilibs_pi_imgproc_transform.a  pi/imgproc_ops/gles/libpilibs_pi_imgproc_ops_gles.a  pi/imgproc_ops/cpu/libpilibs_pi_imgproc_ops_cpu.a  libai-cv-common_vectorizer.a  pi/imgproc_ops/gpu/libpilibs_pi_imgproc_ops_gpu.a  pi/interop/libpilibs_pi_interop.a  pi/interpolation_ops/cpu/libpilibs_pi_interpolation_ops_cpu.a  pi/io_ops/gles/libpilibs_pi_io_ops_gles.a  pi/io_ops/cpu/libpilibs_pi_io_ops_cpu.a  pi/layers_ops/gpu/libpilibs_pi_layers_ops_gpu.a  pi/math_ops/cpu/libpilibs_pi_math_ops_cpu.a  pi/math_ops/gpu/libpilibs_pi_math_ops_gpu.a  pi/pacipher/libpilibs_pi_pacipher.a  pi/phoenix/libpilibs_pi_phoenix.a  pi/phoenix/backend/opengl/libpilibs_pi_phoenix_backend_opengl.a  pi/phoenix/impl/libpilibs_pi_phoenix_impl.a  pi/phoenix_helpers/libpilibs_pi_phoenix_helpers.a  pi/platform/linux/libpilibs_pi_platform_linux.a  pi/platform/generic/libpilibs_pi_platform_generic.a  pi/rendering_ops/gles/libpilibs_pi_rendering_ops_gles.a  pi/rendering_ops/filter_gen/libpilibs_pi_rendering_ops_filter_gen.a  pi/rendering_ops/gpu/libpilibs_pi_rendering_ops_gpu.a  pi/script_ops/cpu/libpilibs_pi_script_ops_cpu.a  liblua.a  pi/statement_ops/cpu/libpilibs_pi_statement_ops_cpu.a  pi/tools/blemish_fix/libpilibs_pi_tools_blemish_fix.a  pi/tools/body_enhancement/libpilibs_pi_tools_body_enhancement.a  pi/tools/dnn/libpilibs_pi_tools_dnn.a  pi/tools/edge_brush/libpilibs_pi_tools_edge_brush.a  pi/tools/edge_point_detector/libpilibs_pi_tools_edge_point_detector.a  pi/tools/face_landmark_detection/libpilibs_pi_tools_face_landmark_detection.a  pi/tools/grabcut/libpilibs_pi_tools_grabcut.a  pi/tools/object_removal/libpilibs_pi_tools_object_removal.a  pi/tools/optimization/libpilibs_pi_tools_optimization.a  pi/tools/stretch/libpilibs_pi_tools_stretch.a  pi/tools/stretch/brushes/libpilibs_pi_tools_stretch_brushes.a  pi/tools/text_drawing/libpilibs_pi_tools_text_drawing.a  pi/tools/hair_recolor/libpilibs_pi_tools_hair_recolor.a  pi/tools/aicv/landmarks/libpilibs_pi_tools_aicv_landmarks.a  pi/tools/mnn/libpilibs_pi_tools_mnn.a  pi/tools_ops/gles/libpilibs_pi_tools_ops_gles.a  pi/tools_ops/cpu/libpilibs_pi_tools_ops_cpu.a  pi/tools_ops/cpu/hair_recolor/libpilibs_pi_tools_ops_cpu_hair_recolor.a  pi/tools_ops/cpu/blemish_fix_kernels/libpilibs_pi_tools_ops_cpu_blemish_fix_kernels.a  libaicv_inpainting.a  pi/tools_ops/cpu/eye_coloring/libpilibs_pi_tools_ops_cpu_eye_coloring.a  pi/tools_ops/cpu/face_edit/libpilibs_pi_tools_ops_cpu_face_edit.a  pi/tools_ops/cpu/sticker_border/libpilibs_pi_tools_ops_cpu_sticker_border.a  pi/tools_ops/cpu/libpilibs_pi_tools_ops_cpu_conflicting.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/mnn-wasm/libs//libMNN.a  pi/tools_ops/gpu/libpilibs_pi_tools_ops_gpu.a  pi/tools_ops/gpu/body_enhancement/libpilibs_pi_tools_ops_gpu_body_enhancement.a  pi/tools_ops/gpu/lighting/libpilibs_pi_tools_ops_gpu_lighting.a  pi/tools_ops/utils/libpilibs_pi_tools_ops_utils.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//opencv4/3rdparty/liblibjpeg-turbo.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//opencv4/3rdparty/liblibpng.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//opencv4/3rdparty/liblibwebp.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//opencv4/3rdparty/libzlib.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_calib3d.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_core.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_dnn.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_features2d.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_flann.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_highgui.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_imgcodecs.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_imgproc.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_ml.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_objdetect.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_photo.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_stitching.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_video.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/opencv_wasm/lib//libopencv_videoio.a  pi/audioproc_ops/cpu/libpilibs_pi_audioproc_ops_cpu.a  pi/audioproc/libpilibs_pi_audioproc.a  pi/unsupported/libpilibs_pi_unsupported.a  pi/debugger/libme_pi_rx_engine_debugger.a  containers/cpp/libme_containers.a  core/debug/cpp/libme_core_debug.a  core/dispatch/cpp/libme_core_dispatch.a  core/startup/cpp/libme_core_startup.a  cornerstone/cpp/libme_cornerstone.a  layers/cpp/libme_layers.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/skia-wasm/skia_wasm/libskia.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/skia-wasm/skia_wasm/libexpat.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/skia-wasm/skia_wasm/libfreetype2.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/skia-wasm/skia_wasm/libskshaper.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/skia-wasm/skia_wasm/libsvg.a  /Users/htagushyan/repos/pi-libs/dependencies/binary/skia-wasm/skia_wasm/NotoMono-Regular.ttf.cpp  core/memory/cpp/libme_memory.a  javascript/src/utils/libpilibs_javascript_src_utils.a  javascript/src/bindings/libpilibs_javascript_src_bindings.a  javascript/src/bindings/fx/libpilibs_javascript_src_bindings_fx.a  core/foundation/cpp/libme_core_foundation.a  dependencies/source/fmtlib/libfmt.a  dependencies/source/xxhash/cmake_unofficial/libxxhash.a && cd /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript && /Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/pi.js /Users/htagushyan/repos/pi-libs/build_output/pi.js && cd /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript && /Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/pi.wasm /Users/htagushyan/repos/pi-libs/build_output/pi.wasm && cd /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript && /Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/pi.js.symbols /Users/htagushyan/repos/pi-libs/build_output/pi.js.symbols && cd /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript && /Applications/CMake.app/Contents/bin/cmake -E copy_if_different /Users/htagushyan/repos/pi-libs/build_dir/wasm/javascript/pi.worker.js /Users/htagushyan/repos/pi-libs/build_output/pi.worker.js
clang++: warning: argument unused during compilation: '-fuse-ld=lld' [-Wunused-command-line-argument]
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

**Comment by harutyuntagushyan8** [comment] 2023-10-17 14:33
will try to generate rsp.utf file.

**Comment by sbc100** [comment] 2023-10-17 14:45
If there is any way you could reduce tat size of the repro, or share the full repro case (you can use `-Wl,--reproduce=<file.tar>` that would be very useful.

**Comment by harutyuntagushyan8** [comment] 2023-10-17 15:01
Ah to save full log into it. Thanks

**Comment by harutyuntagushyan8** [comment] 2023-10-17 15:18
https://github.com/emscripten-core/emscripten/issues/19774
This is exact my case.
Will follow discussions.

**Comment by harutyuntagushyan8** [comment] 2023-10-17 15:27
I'm getting same problem with 3.1.47
Seems the problem still exist.

**Comment by kleisauke** [comment] 2023-11-06 13:36
Looks like a duplicate of #62243, which is still reproducible on Emscripten 3.1.48.
<details>
  <summary>Details</summary>

```bash
$ mkdir foo && cd foo
$ cat <<EOT > CMakeLists.txt
cmake_minimum_required(VERSION 3.13)

set(CMAKE_EXECUTABLE_SUFFIX_CXX .html)
set(CMAKE_CXX_STANDARD 17)

add_executable(lto_bug dummy.cpp)

add_library(main
  main.cpp
)

add_library(lib1
  lib1.cpp
)

target_link_libraries(lto_bug
  PRIVATE
    main
    lib1
)
EOT
$ cat <<EOT > main.cpp
int DoIt()
{
    return 0; 
}
inline int Unused0 = DoIt();

int GetUnused();

int main(int, char **)
{
    return GetUnused();
}
EOT
$ cat <<EOT > lib1.cpp
int DoIt();
inline int Unused0 = DoIt();

int GetUnused()
{
    return Unused0;
}
EOT
$ cat <<EOT > dummy.cpp
// Dummy file for CMake's add_executable
EOT
$ emcmake cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-flto" .
$ make -j$(nproc) VERBOSE=1
...
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/kleisauke/emsdk/upstream/bin/wasm-ld -o lto_bug.wasm CMakeFiles/lto_bug.dir/dummy.cpp.o libmain.a liblib1.a -L/home/kleisauke/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpe995_adnlibemscripten_js_symbols.so --strip-debug -u__cxa_atexit --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --no-entry --table-base=1 --global-base=1024
 #0 0x00005580baf311f8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0xf4e1f8)
 #1 0x00005580baf2e82e llvm::sys::RunSignalHandlers() (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0xf4b82e)
 #2 0x00005580baf31e35 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f7803666bb0 __restore_rt (/lib64/libc.so.6+0x3dbb0)
 #4 0x00005580bb33682e lld::wasm::(anonymous namespace)::Writer::run() Writer.cpp:0:0
 #5 0x00005580bb32b5c8 lld::wasm::writeResult() (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0x13485c8)
 #6 0x00005580bb304eb3 lld::wasm::(anonymous namespace)::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) Driver.cpp:0:0
 #7 0x00005580bb300b0c lld::wasm::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0x131db0c)
 #8 0x00005580baf33ffe lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0xf50ffe)
 #9 0x00005580bae7c1c2 lld_main(int, char**, llvm::ToolContext const&) (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0xe991c2)
#10 0x00005580bae7c8bc main (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0xe998bc)
#11 0x00007f7803650b8a __libc_start_call_main (/lib64/libc.so.6+0x27b8a)
#12 0x00007f7803650c4b __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x27c4b)
#13 0x00005580badf20ea _start (/home/kleisauke/emsdk/upstream/bin/wasm-ld+0xe0f0ea)
em++: error: '/home/kleisauke/emsdk/upstream/bin/wasm-ld -o lto_bug.wasm CMakeFiles/lto_bug.dir/dummy.cpp.o libmain.a liblib1.a -L/home/kleisauke/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto -lGL -lal -lhtml5 -lstubs -lnoexit -lc -ldlmalloc -lcompiler_rt -lc++-noexcept -lc++abi-noexcept -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr /tmp/tmpe995_adnlibemscripten_js_symbols.so --strip-debug -u__cxa_atexit --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__main_argc_argv --export=stackSave --export=stackRestore --export=stackAlloc --export=__errno_location --export=__get_temp_ret --export=__set_temp_ret --export=__wasm_call_ctors --export-table -z stack-size=65536 --initial-memory=16777216 --max-memory=16777216 --no-entry --table-base=1 --global-base=1024' failed (received SIGSEGV (-11))
...
```
</details>

**Comment by aheejin** [comment] 2023-11-30 02:16
https://github.com/llvm/llvm-project/pull/73095 might have fixed the issue.

**Comment by sbc100** [comment] 2024-03-13 21:08
@harutyuntagushyan8 can you confirm if this is still an issue with the latest emsdk?

**Comment by harutyuntagushyan8** [comment] 2024-03-14 06:56
@sbc100 please close the task. It's not actual with new versions of emscripten.

**Closed** 2024-03-14 14:38 UTC
Labels: lld:wasm, crash
