### ISSUE TITLE
wasm-ld should split up relocation function when function body size exceeds limit

### ISSUE THREAD

**Issue by TerrorJack** [llvm/llvm-project#108599] opened 2024-09-13 16:17 UTC
This issue is a feature request for `wasm-ld` to support splitting up linker-generated relocation functions like `__wasm_apply_data_relocs` in case it's linking a huge output `.so` with many relocation entries, in which case the function body may become too large and exceed the function body [size limit](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/wasm/wasm-limits.h;l=50?q=kV8MaxWasmFunctionSize&sq=) enforced by major wasm engines.

**Comment by sbc100** [comment] 2024-09-17 14:10
I think this is a duplicate of https://github.com/llvm/llvm-project/issues/55608?

**Closed** 2024-09-17 14:46 UTC
Labels: duplicate, lld:wasm
