### ISSUE TITLE
Class explicit-instantiation-definition tries to instantiate member functions disabled with `requires`

### ISSUE THREAD

**Issue by HolyBlackCat** [llvm/llvm-project#52625] opened 2021-12-12 09:41 UTC
When explicitly instantiating a class, Clang tries to instantiate all member functions, even those that should be disabled with `requires`. Example:

```cpp
template <typename T>
struct A
{
    void foo() requires requires{ T::bar(); }
    {
        T::bar();
    }
};

template struct A<int>;
```

This should compile, but doesn't:
```
<source>:6:9: error: type 'int' cannot be used prior to '::' because it has no members
        T::bar();
        ^
<source>:10:17: note: in instantiation of member function 'A<int>::foo' requested here
template struct A<int>;
                ^
```

**Comment by royjacobson** [comment] 2022-04-15 08:26
Duplicate of #46029. Checking constraints for class/struct templates was fixed in https://reviews.llvm.org/D120255.

**Closed by royjacobson** 2022-04-15 08:26 UTC
Labels: new issue
