### ISSUE TITLE
[IROutliner] 'OutputStoreBBs.size() < 2 && "Different store sets not handled!"' when compiling CINT2017rate/502.gcc_r

### ISSUE THREAD

**Issue by ornata** [llvm/llvm-project#54902] opened 2022-04-13 21:08 UTC
This bugpoints down to the following issue:

https://godbolt.org/z/Yx6TK659b

CC: @AndrewLitteken

**Comment by AndrewLitteken** [comment] 2022-04-13 21:29
Resolved by this patch: https://reviews.llvm.org/D122207

**Comment by ornata** [comment] 2022-04-13 21:30
Oh! It's a dupe. Phew :)

**Comment by EugeneZelenko** [comment] 2022-04-13 21:35
Duplicate of #54431.

**Closed** 2023-01-24 12:33 UTC
Labels: duplicate, llvm:crash, llvm:optimizations
