### ISSUE TITLE
[flang] Compilation error of ALLOCATABLE dummy argument

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#60226] opened 2023-01-23 07:06 UTC
```
Version of flang-new : 16.0.0(77f2f34d696b77fe5bf05afbe7386966b6bcc8ba)
```

ALLOCATABLE dummy argument results in a compilation-time error.

The following are the test program, flang-new, gfortran and ifort compilation result.

`snggj331_.f90`:
```f90
program main
  call sub
  print *,'OK'
end program main

module m1
contains
  function func(i,p) result(a)
    character(len=1,kind=1),allocatable,dimension(:,:):: a
    character(len=*,kind=1),allocatable,optional,dimension(:,:)::p
    character(len=*,kind=1),optional,intent(in)::i
  end function func
  function   chk(i,p) result(r)
    logical r(2)
    character(len=*,kind=1),allocatable,optional,dimension(:,:)::p
    character(len=*,kind=1),optional,intent(in)::i
    r=.true.
  end function chk
end module m1

recursive subroutine sub
  use m1
  character(len=1,kind=1),allocatable,dimension(:,:):: pointer
  if (count(mask=chk(p=func(i='1',p=pointer),i='1'))/=2)write(6,*) "NG"
end subroutine sub
```

```console
$ flang-new -flang-experimental-exec snggj331_.f90
error: Semantic errors in snggj331_.f90
./snggj331_.f90:24:24: error: ALLOCATABLE dummy argument 'p=' must be associated with an ALLOCATABLE actual argument
    if (count(mask=chk(p=func(i='1',p=pointer),i='1'))/=2)write(6,*) "NG"
                         ^^^^^^^^^^^^^^^^^^^^^
$
```

```console
$ gfortran snggj331_.f90
$
```

```console
$ ifort snggj331_.f90
snggj331_.f90(8): warning #6178: The return value of this FUNCTION has not been defined.   [A]
  function i4_f(i,p) result(a)
----------------------------^
$
```

**Comment by luporl** [comment] 2023-02-08 19:17
The problem is that the semantic checker is currently unable to retrieve the ALLOCATABLE attribute of a function call expression.

The following simplified code shows this:

```fortran
module m1
contains
  function func(p) result(a)
    character(len=1,kind=1), allocatable, dimension(:,:) :: a
    character(len=1,kind=1), allocatable, dimension(:,:) :: p

    a = p
  end function func

  subroutine chk(p)
    character(len=1,kind=1), allocatable, dimension(:,:) :: p
  end subroutine
end module m1

subroutine sub
  use m1
  character(len=1,kind=1), allocatable, dimension(:,:) :: ptr

  call chk(func(ptr))
end subroutine sub
```

If the result of the `func(ptr)` is first assigned to a variable and that variable is passed to `chk()` then no errors occur.

**Comment by luporl** [comment] 2023-04-04 11:47
Simpler reproducer:
```f90
program main
  integer, allocatable :: p
  p = f(f(p))

contains
  function f(p) result(r)
    integer, allocatable :: p, r
    r = p
  end function
end program
```

**Comment by luporl** [comment] 2023-04-04 11:57
Inspecting the code and data, I realized it's possible to obtain the function's result attributes from a FunctionRef expression.
My plan then is to modify `evaluate::IsAllocatableDesignator` to do this for FunctionRefs.

If someone thinks this is not the right approach, please let me know.

**Comment by luporl** [comment] 2023-04-05 14:22
Proposed patch: https://reviews.llvm.org/D147614

**Comment by luporl** [comment] 2023-04-06 22:06
It was discovered that code that uses the result of a function call as an ALLOCATABLE argument is not conforming, such as `f(f(p))` in the example above, even when the function result has the ALLOCATABLE attribute.

The NAG Fortran compiler also doesn't allow this.

More details are provided at https://reviews.llvm.org/D147614.

**Comment by luporl** [comment] 2023-04-06 23:07
I think I rushed a little bit with regards to this issue.
Despite this feature being not standards conforming, the community seems interested in supporting this as an extension, given that it is supported by other compilers, such as gfortran and ifort.

**Comment by luporl** [comment] 2023-05-09 11:54
As discussed in https://reviews.llvm.org/D147614, gfortran likely supported this extension only by accident and it is now an error in gcc-14. Also, while ifort supported this, the new Intel Fortran compiler, ifx, doesn't support it anymore.
Therefore, the motivation to support this extension in flang is gone.

**Comment by luporl** [comment] 2023-05-09 11:57
Closing with the correct reason...

**Closed by luporl** 2023-05-09 11:57 UTC
Labels: invalid, flang:frontend
