### ISSUE TITLE
clang-format job on Buildkite is bogus

### ISSUE THREAD

**Issue by asl** [llvm/llvm-project#66468] opened 2023-09-15 07:52 UTC
Consider e.g. https://buildkite.com/llvm-project/clang-ci/builds/3190#018a97ac-63f5-4517-ae31-3f185df940ae
clang-format job failed, however, there is no way to figure out what is wrong: the output is simply missed from the log.

**Comment by metaflow** [comment] 2023-09-15 11:54
@ldionne could you please take a look?

**Comment by ldionne** [comment] 2023-09-15 13:39
Actually, I'll assign this to @tru since he's made a lot of progress on setting up clang-format for the whole monorepo. That will replace the Buildkite job we have for Clang.

**Comment by asl** [comment] 2023-09-15 21:23
Will you please disable the job now as it simply makes everything else fail?

**Comment by ldionne** [comment] 2023-09-15 21:27
a52560c8dd804104041e3cde4d9b9b89bf22f81e

The issue is that someone (you?) added trailing whitespace. The job output isn't great, but it does say:

```
grep -rnI '[[:blank:]] clang/lib clang/include clang/docs
clang/lib/CodeGen/CGCoroutine.cpp:836:
```

**Comment by asl** [comment] 2023-09-15 21:42
> grep -rnI '[[:blank:]] clang/lib clang/include clang/docs
> clang/lib/CodeGen/CGCoroutine.cpp:836:

And how one could deduce that this is something related to the failure? And not just some part of job script? Especially given that line 69 is absent from the log and one could clearly expect to see the error there (after ":" on the line above). Certainly, it is clear what is going on to whoever written this script, but for everyone else the output is very confusing. I spent quite some time trying to find the error message in various parts of the system including raw logs, etc.

**Closed** 2023-09-19 22:17 UTC
Labels: bug, infrastructure
