### ISSUE TITLE
Incorrect -Wenum-constexpr-conversion warning?

### ISSUE THREAD

**Issue by thesamesam** [llvm/llvm-project#62686] opened 2023-05-12 19:35 UTC
With this (derived from Kleopatra, see https://bugs.gentoo.org/903576):
```c++
enum foo { x = 0xffff };
constexpr auto bar = static_cast<foo>(x + 1); /* fails */
static_assert (sizeof (x) == 4);
```

trunk gives:
```console
<source>:2:26: error: integer value 65536 is outside the valid range of values [0, 65535] for this enumeration type [-Wenum-constexpr-conversion]
constexpr auto bar = static_cast<foo>(x + 1); /* fails */
                         ^
``` 

It's getting the type right but not the range of valid enum values?

Thanks to @ArsenArsen for reducing it.

cc @shafik

**Comment by shafik** [comment] 2023-05-12 21:06
The key wording here is from [dcl.enum p8](https://eel.is/c++draft/enum#dcl.enum-8) which says:

> ... Otherwise, the values of the enumeration are the values representable by a hypothetical integer type with minimal width M such that all enumerators can be represented. The width of the smallest bit-field large enough to hold all the values of the enumeration type is M. It is possible to define an enumeration that has values not defined by any of its enumerators. If the enumerator-list is empty, the values of the enumeration are as if the enumeration had a single enumerator with value 0.

So yes, the range is correct. 

The correct fix is usually to give the enum a fixed underlying type, which is the behavior most folks assume but are incorrect about e.g.

```cpp
enum foo : unsigned  { x = 0xffff }; // The range of values now encompasses all of unsigned  
```

One can also make it a *escoped enum* but that break some cases since the values no longer leak out.

Also see [UBSan example with catches this as well](https://godbolt.org/z/G6bqWjsEr):

```cpp
enum foo { x = 0xffff };

int main() {
    auto bar = static_cast<foo>(x + 1); 

    return bar;
}
```

output:

```console
/app/example.cpp:6:12: runtime error: load of value 65536, which is not a valid value for type 'foo'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.cpp:6:12 in 
```

There is a large set of test in [clang/test/SemaCXX/constant-expression-cxx11.cpp](https://github.com/llvm/llvm-project/blob/main/clang/test/SemaCXX/constant-expression-cxx11.cpp#L2440) which might help clarify the behavior better for you.

**Comment by thesamesam** [comment] 2023-05-12 21:38
Thank you for the explanation! Let me try digest it.

**Comment by AaronBallman** [comment] 2023-06-13 11:58
Closing as not a bug.

**Closed by AaronBallman** 2023-06-13 11:58 UTC
Labels: invalid, clang:diagnostics
