### ISSUE TITLE
Clang failed to use std::source_location::current() in default argument

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#55769] opened 2022-05-30 03:36 UTC
See https://godbolt.org/z/r68nn8snr

Clang failed to compile the following example while gcc and MSVC accept it both:
```C++
#include<source_location>
#include<iostream>

void test_source_location(std::source_location src = std::source_location::current()) {
    std::cout << "called at " << src.line() << "\n";
}

int main() {
    test_source_location();
}
```

The use here of `std::source_location::current()` is recommended. So it should be the problem of clang.

**Comment by ChuanqiXu9** [comment] 2022-05-30 03:38
BTW, clang would accept it too if we use `std::experimental::source_location::current()`.

**Comment by jyknight** [comment] 2022-05-30 14:53
This is a duplicate of https://github.com/llvm/llvm-project/issues/48230

**Closed by jyknight** 2022-05-30 14:53 UTC
Labels: c++20, libstdc++

**Comment by IGR2014** [comment] 2022-07-05 08:30
Not yet fixed: Clang reports wrong line number.
While GCC/MSVC reports lline number of function INVOCATION, Clang reports line number of function DECLARATION (see screenshot)
![image](https://user-images.githubusercontent.com/10415461/177285260-e3537cb6-88c8-4c2d-b284-c4c1add53f76.png)

**Comment by ChuanqiXu9** [comment] 2022-07-05 08:41
> Not yet fixed: Clang reports wrong line number.
> While GCC/MSVC reports lline number of function INVOCATION, Clang reports line number of function DECLARATION (see screenshot)
> ![image](https://user-images.githubusercontent.com/10415461/177285260-e3537cb6-88c8-4c2d-b284-c4c1add53f76.png)

Hi, this issue (and the other issue you mentioned) refers to the problem we couldn't use constexpr functions in the default argument. And your suggestion should be another related but not the same issue. I suggest to create a new issue for this.

(BTW, it would be better to sent the link to Godbolt instead of posting up a picture. My mail client warns for this.)

**Comment by IGR2014** [comment] 2022-07-05 08:49
Yes, sorry. Here's one: https://github.com/llvm/llvm-project/issues/56379
