### ISSUE TITLE
[clang-format] BUG: Inline lambda will move following params, to the nowhere

### ISSUE THREAD

**Issue by florianbecker** [llvm/llvm-project#58146] opened 2022-10-04 17:06 UTC
Input:
```cpp
/* stl header */
#include <functional>
#include <iostream>

/* modern.cpp.core */
#include <Timer.h>

constexpr int intervallSeconds = 1;
constexpr int secondsToMilliseconds = 1000;
constexpr int exitSeconds = 15;

int main() {

  int intervall = 1;
  auto intervallTimer = vx::Timer();

  intervallTimer.setInterval( [ &intervallTimer, &intervall ]() {
    std::cout << "Intervall: " << intervall << std::endl;
    intervall++;
    if ( intervall >= exitSeconds ) {

      intervallTimer.stop();
    }
  }, intervallSeconds * secondsToMilliseconds );

  while ( true ) {

    /* Leave the app run infinity */
    if ( !intervallTimer.isRunning() ) {

      break;
    }
  }

  return EXIT_SUCCESS;
}
```

Will end like that:
```cpp
/* stl header */
#include <functional>
#include <iostream>

/* modern.cpp.core */
#include <Timer.h>

constexpr int intervallSeconds = 1;
constexpr int secondsToMilliseconds = 1000;
constexpr int exitSeconds = 15;

int main() {

  int intervall = 1;
  auto intervallTimer = vx::Timer();

  intervallTimer.setInterval( [ &intervallTimer, &intervall ]() {
    std::cout << "Intervall: " << intervall << std::endl;
    intervall++;
    if ( intervall >= exitSeconds ) {

      intervallTimer.stop();
    }
  },
                              intervallSeconds * secondsToMilliseconds );

  while ( true ) {

    /* Leave the app run infinity */
    if ( !intervallTimer.isRunning() ) {

      break;
    }
  }

  return EXIT_SUCCESS;
}
```

Workaround:
Define a function and do not write the lambda inline. Will keep the formatting.
```cpp
/* stl header */
#include <functional>
#include <iostream>

/* modern.cpp.core */
#include <Timer.h>

constexpr int intervallSeconds = 1;
constexpr int secondsToMilliseconds = 1000;
constexpr int exitSeconds = 15;

int main() {

  int intervall = 1;
  auto intervallTimer = vx::Timer();

  using func = std::function<void( void )>;
  const func runOnInterval = [ &intervallTimer, &intervall ]() {
    std::cout << "Intervall: " << intervall << std::endl;
    intervall++;
    if ( intervall >= exitSeconds ) {

      intervallTimer.stop();
    }
  };

  intervallTimer.setInterval( runOnInterval, intervallSeconds * secondsToMilliseconds );

  while ( true ) {

    /* Leave the app run infinity */
    if ( !intervallTimer.isRunning() ) {

      break;
    }
  }

  return EXIT_SUCCESS;
}
```

Tested on clang-format-15 and clang-format-14

My configuration:
[clang-format.txt](https://github.com/llvm/llvm-project/files/9709136/clang-format.txt)

**Comment by rymiel** [comment] 2022-10-05 06:32
Duplicate of #51146

**Closed by rymiel** 2022-10-05 06:32 UTC
Labels: clang-format

**Comment by florianbecker** [comment] 2022-10-05 08:47
@rymiel Thank you for finding that duplicate.

#51146 is open for more than one year? Can I support here in any way?

**Comment by rymiel** [comment] 2022-10-05 09:33
Note that the other parameters are not moved to "nowhere", they are in fact aligned with the lambda introducer `[`. You will get better results if you add a line break after the function call and put the lambda on its own line. This is what clang-format would do by default but it can't since you've set the ColumnLimit to 0.

This is still a bug, though, since those parameters should really be aligned to the end of the lambda, not the start of it. No promises as to when it would be fixed, though this is an open source project.
