### ISSUE TITLE
clang++ crash when using -target x86-pc-windows-gnu

### ISSUE THREAD

**Issue by dda1f292-2d11-4a1f-bf4f-5b4b9d7a30b7** [llvm/llvm-project#49412] opened 2021-04-22 00:41 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [50068](https://llvm.org/bz50068) |
| Version | 11.0 |
| OS | Windows NT |
| Attachments | [Source that caused the crash](https://user-images.githubusercontent.com/92601459/143762051-f1be0c4a-ce21-4e75-9d31-816fb74cbbbd.gz) |
| CC | @zygoloid |

## Extended Description 

I run
>clang -target x86-pc-windows-gnu BasicCppTest.c

clang crashed throwing this message:
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang -target x86-pc-windows-gnu BasicCppTest.c
1.      Compilation construction
2.      Building compilation jobs
3.      Building compilation jobs
#&#8203;0 0x02296394 C:\Program Files (x86)\LLVM\bin\clang.exe 0x1d26394 C:\Program Files (x86)\LLVM\bin\clang.exe 0x1cd6465
#&#8203;1 0x02296394 C:\Program Files (x86)\LLVM\bin\clang.exe 0x1cd473b C:\Program Files (x86)\LLVM\bin\clang.exe 0x1ccc837
0x02296394 (0x06B91560 0x06BA2120 0x0698E500 0x0698E6A4)
0x02246465 (0x0698E788 0x06B91560 0x06BA2120 0x06BCE1A0)
0x0224473B (0x0698E870 0x06B91560 0x06BA2120 0x06BCE1A0)
0x0223C837 (0x00000033 0x06BA2138 0x00000001 0x00000003)

I was running directly from command line.
I attached BasicCppTest.c

The error also occurred when I replaced the comments to use C++ style print (iostream and cout<<).

My machine:
Windows 10, Intel i7, 16 GB RAM

Clang version (clang --version):
clang version 12.0.0
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\LLVM\bin

GCC version (gcc --version):
gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.

**Comment by k-mana** [comment] 2023-05-01 05:39
Still crashes on current `trunk`: https://godbolt.org/z/caPdaebT4

### backtrace
```
Unsupported target architecture.
UNREACHABLE executed at /root/llvm-project/clang/lib/Driver/ToolChains/MinGW.cpp:138!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -target x86-pc-windows-gnu <source> -L. -Wl,-rpath,. -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib64 -Wl,-rpath,/opt/compiler-explorer/gcc-snapshot/lib32
1.	Compilation construction
2.	Building compilation jobs
3.	Building compilation jobs
 #0 0x000055d5513f317f llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ad617f)
 #1 0x000055d5513f08a4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f34979c0420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007f349748d00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007f349746c859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x000055d551348f8e (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a2bf8e)
 #6 0x000055d551d6a397 clang::driver::tools::MinGW::Linker::ConstructJob(clang::driver::Compilation&, clang::driver::JobAction const&, clang::driver::InputInfo const&, llvm::SmallVector<clang::driver::InputInfo, 4u> const&, llvm::opt::ArgList const&, char const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x444d397)
 #7 0x000055d551c4db2c clang::driver::Driver::BuildJobsForActionNoCache(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::SmallVector<clang::driver::InputInfo, 4u>, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const, llvm::SmallVector<clang::driver::InputInfo, 4u>>>>&, clang::driver::Action::OffloadKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4330b2c)
 #8 0x000055d551c4f190 clang::driver::Driver::BuildJobsForAction(clang::driver::Compilation&, clang::driver::Action const*, clang::driver::ToolChain const*, llvm::StringRef, bool, bool, char const*, std::map<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::SmallVector<clang::driver::InputInfo, 4u>, std::less<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>, std::allocator<std::pair<std::pair<clang::driver::Action const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>> const, llvm::SmallVector<clang::driver::InputInfo, 4u>>>>&, clang::driver::Action::OffloadKind) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4332190)
 #9 0x000055d551c4f941 clang::driver::Driver::BuildJobs(clang::driver::Compilation&) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4332941)
#10 0x000055d551c60735 clang::driver::Driver::BuildCompilation(llvm::ArrayRef<char const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4343735)
#11 0x000055d54e9651ec clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x10481ec)
#12 0x000055d54e870465 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xf53465)
#13 0x00007f349746e083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#14 0x000055d54e95ec3e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x1041c3e)
Compiler returned: 139
```

**Comment by k-mana** [comment] 2023-05-01 05:39
duplicates #59545

but x86 is invalid?

**Comment by BertalanD** [comment] 2023-05-01 10:14
> but x86 is invalid?

Yes, 32-bit x86 is usually called `i386` or `i686` in target triples (but a few other names are also accepted for historical reasons):
https://github.com/llvm/llvm-project/blob/6875424135312aeb26ab8e0358ba7f9e6e80e741/llvm/lib/TargetParser/Triple.cpp#L466-L470

Closing this issue as the newer one has more discussion on it:

Duplicate of #59545

**Comment by BertalanD** [comment] 2023-05-01 10:14
Duplicate of #59545

**Closed by BertalanD** 2023-05-01 10:14 UTC
Labels: clang, bugzilla
