### ISSUE TITLE
wrong code at -O1, -O2, -O3 (but not -Os) on x86_64-linux-gnu

### ISSUE THREAD

**Issue by zhendongsu** [llvm/llvm-project#51721] opened 2021-11-02 06:10 UTC
|  |  |
| --- | --- |
| Bugzilla Link | [52379](https://llvm.org/bz52379) |
| Version | unspecified |
| OS | All |
| CC | @fhahn,@RKSimon,@rotateright |

## Extended Description 
This appears to be a recent regression.

[508] % clangtk -v
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 8cabd8f0d26c3cff03faec9b1cea974f08618d6d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/opfuzz/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
[509] % 
[509] % clangtk -O0 small.c; ./a.out
[510] % 
[510] % clangtk -O1 small.c
[511] % ./a.out
Segmentation fault
[512] % 
[512] % cat small.c
int printf(const char *, ...);
int a = 354757809, b[2], c, d = 147639773, e, n = 2000;
short f = -25324;
long g;
int main() {
  int h = a, k = ~d, m = 0;
  a = ~h;
  if (a > 3)
    goto L2;
  a = h;
  --d;
  e = d;
L1:
  d = ~(~48988294629 & ~d * (~48988294629 | ~e));
  a = (h | d) ^ ~(e | f) ^ (a - 48988294629);
  unsigned l;
  if (k)
    if (a > 1523073808)
      c++;
  if (a <= 1523073808)
    l = d;
  if (a >= 1523073808) {
    m = a;
    while (a > 1523073808)
      ;
  }
  a = m;
L2:
  a = l;
  if (m)
    g = ~a;
  if (g > 4073172680703UL) {
    printf("%d\n", b[n]);
    goto L1;
  }
  return 0;
}

**Comment by fhahn** [comment] 2022-03-16 19:57
I am unable to reproduce this on current `main`. I'll close the issue, but please re-open it again with additional info if it still reproduces on your side.

**Closed by fhahn** 2022-03-16 19:57 UTC
Labels: bugzilla
