### ISSUE TITLE
Overload resolution fails with deleted destructor

### ISSUE THREAD

**Issue by hpesoj** [llvm/llvm-project#54674] opened 2022-03-31 14:43 UTC
With Clang 15.0.0, this fails to compile:

```
template <bool B>
struct test {
    ~test() = delete;
    ~test() requires(B) {}
};

int main() {
    test<true>{};
}
```

```
prog.cc:8:15: error: attempt to use a deleted function
    test<true>{};
              ^
prog.cc:3:5: note: '~test' has been explicitly marked deleted here
    ~test() = delete;
```

This precludes real uses cases, such as this `std::optional`-like wrapper, where variant member with with a non-trivial destructor causes the defaulted destructor to be deleted:

```
#include <type_traits>

template <typename T>
struct opt
{
    union {
        char none;
        T some;
    };

    opt() : none() {}

    ~opt() = default;
    ~opt() requires(!std::is_trivially_destructible_v<T>) { some.~T(); }
};
```

Note that the latest GCC does not have the same problem.

**Comment by royjacobson** [comment] 2022-04-20 08:06
Duplicate of #45614

**Closed by royjacobson** 2022-04-20 08:06 UTC
Labels: clang:frontend
