### ISSUE TITLE
[Clang] Cannot use static constexpr member variable in constant expression

### ISSUE THREAD

**Issue by craffael** [llvm/llvm-project#62136] opened 2023-04-14 13:31 UTC
## Clang Version:
```console
clang version 17.0.0 (https://github.com/llvm/llvm-project.git 27f27d15f6c90b026eca23b8ee238fdbf772fd80)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/compiler-explorer/clang-trunk/bin
```

## Steps to reproduce
Try to compile the following simple program with `clang++-16 -std=c++20 source.cc` (see also [Godbolt](https://godbolt.org/z/1bsazYvK7):
```c++
struct Mesh {
  static constexpr int kDimMesh = 3;
};

void checkMesh(const Mesh& mesh) {
  constexpr auto kDimMesh = mesh.kDimMesh;
}

int main() {
  Mesh mesh;
  checkMesh(mesh);
}
```

Error Message:
```console
<source>:6:18: error: constexpr variable 'kDimMesh' must be initialized by a constant expression
  constexpr auto kDimMesh = mesh.kDimMesh;
                 ^          ~~~~~~~~~~~~~
<source>:6:29: note: function parameter 'mesh' with unknown value cannot be used in a constant expression
  constexpr auto kDimMesh = mesh.kDimMesh;
                            ^
<source>:5:28: note: declared here
void checkMesh(const Mesh& mesh) {
                           ^
1 error generated.
```

As far as I can tell, this is perfectly valid C++ and it compiles fine with GCC and MSVC.

**Comment by tbaederr** [comment] 2023-04-14 14:15
It also works in clang if you reference it using `Mesh::kDimMesh` instead.

**Comment by craffael** [comment] 2023-04-14 14:53
> It also works in clang if you reference it using `Mesh::kDimMesh` instead.

Yes that's true, but if you don't have the type of `mesh` readily available, you have to write `std::remove_cvref_t<decltype(mesh)>::kDimMesh` which is a lot longer than `mesh.kDimMesh` 😉 

The piece of code that I show above was actually extracted from heavily templated source code. Also for compatibility with gcc/msvc it would be nice if `mesh.kDimMesh` would work.

**Comment by shafik** [comment] 2023-04-15 03:26
This is a duplicate of: https://github.com/llvm/llvm-project/issues/60548

This [P2280R4](https://wg21.link/P2280R4) which I have not implemented yet.

**Closed** 2023-04-15 03:27 UTC
Labels: clang:frontend, consteval

**Comment by barracuda156** [comment] 2024-02-22 23:33
This is not fixed yet in any Clang release?

**Comment by tbaederr** [comment] 2024-02-23 05:19
No, but as you can see from https://github.com/llvm/llvm-project/issues/60548, it's being worked on.
