### ISSUE TITLE
[mlir] Comparing two double values directly using ==. It will not produce correct output due to precision problems.

### ISSUE THREAD

**Issue by ustchcs-bugfinder** [llvm/llvm-project#61609] opened 2023-03-22 06:09 UTC
https://github.com/llvm/llvm-project/blob/08d094a0e457360ad8b94b017d2dc277e697ca76/mlir/lib/Dialect/Arith/IR/ArithOps.cpp#L1294

In the case of floating-point numbers, the [relational operator (==)](https://www.geeksforgeeks.org/java-relational-operators-with-examples/) does not produce correct output, this is due to the internal precision errors in rounding up floating-point numbers. 

Reference: [here](https://www.geeksforgeeks.org/problem-in-comparing-floating-point-numbers-and-how-to-compare-them-correctly/)

Current code:
```cpp
/// Perform safe const propagation for truncf, i.e. only propagate if FP value
/// can be represented without precision loss or rounding.
OpFoldResult arith::TruncFOp::fold(FoldAdaptor adaptor) {
  auto constOperand = adaptor.getIn();
  if (!constOperand || !constOperand.isa<FloatAttr>())
    return {};

  // Convert to target type via 'double'.
  double sourceValue =
      constOperand.dyn_cast<FloatAttr>().getValue().convertToDouble();
  auto targetAttr = FloatAttr::get(getType(), sourceValue);

  // Propagate if constant's value does not change after truncation.
  if (sourceValue == targetAttr.getValue().convertToDouble())                 //----> compare two doubles using ==
    return targetAttr;

  return {};
}
```

**Comment by ustchcs-bugfinder** [comment] 2023-03-23 01:09
Floating point arithmetic suffers a lot  from the precision. Here is a lesson for Java (https://introcs.cs.princeton.edu/java/91float/). 

If you just want some counterexample, here is QA on site a stackexchange.

https://scicomp.stackexchange.com/questions/25516/testing-equality-of-two-floats-realistic-example

**Comment by joker-eph** [comment] 2023-03-23 13:58
All of your references still don't seem to apply in this case as far as I can tell. 

Closing as "not a bug" right now, pending a test case showing that there is an actual bug for this folder.

**Closed by joker-eph** 2023-03-23 13:58 UTC
Labels: wontfix, code-quality, mlir
