### ISSUE TITLE
clang-format puts `break` on the same line as `}`.

### ISSUE THREAD

**Issue by ilya-biryukov** [llvm/llvm-project#63034] opened 2023-05-31 11:20 UTC
Input:
```cpp
  switch (0) {
    case 1:
      {
      }
      break;
  }
```

Suggested formatting with `--style=Google`:
```cpp
  switch (0) {
    case 1:
      {
      }
      break;
  }
```

Actual:
```cpp
  switch (0) {
    case 1: {
    } break;
  }
```

**Comment by owenca** [comment] 2023-05-31 23:47
Duplicate of #40786. Caused by a5510af for #15279.

**Closed** 2023-06-01 00:08 UTC
Labels: duplicate, clang-format
