### ISSUE TITLE
[clang] clang frontend command failed with exit code 139

### ISSUE THREAD

**Issue by zhaoShiEnthalpy** [llvm/llvm-project#57142] opened 2022-08-14 14:23 UTC
I was building a project with CMake, Ninja, with clang-14, and the clang frond end crashed (139).
Here is the clang version information (clang -v):

```
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
And [clang_14_frontend_crashes_UTCplus8_22081422.log](https://github.com/llvm/llvm-project/files/9333513/clang_14_frontend_crashes_UTCplus8_22081422.log) is the full stacktrace produced by clang-14, preprocessed sources and run scripts are [clang_14_frontend_crashes_UTCplus8_22081422.zip](https://github.com/llvm/llvm-project/files/9333507/clang_14_frontend_crashes_UTCplus8_22081422.zip).
(Codes uploaded here includes a part of an unpublished project, they are only permitted to be used in this bug report.)

**Comment by EugeneZelenko** [comment] 2022-08-14 14:28
Could you please try `main` branch?

**Comment by zhaoShiEnthalpy** [comment] 2022-08-14 14:39
> Could you please try `main` branch?

Let me try. It performs well on clang-13 distributed by Ubuntu apt, and crashes on 14. I may try to compile a clang of the main branch, and I will reply after trying.

**Comment by zhaoShiEnthalpy** [comment] 2022-08-14 18:07
> > Could you please try `main` branch?
> 
> Let me try. It performs well on clang-13 distributed by Ubuntu apt, and crashes on 14. I may try to compile a clang of the main branch, and I will reply after trying.

Well, I tried main branch with the debug build, here is the output of clang -v:
```
clang version 16.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/zhaoshihan/Public/apps/clang-main-220814/bin/.
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
It seems that the error persists, even though in clang-main. 
[Here](https://github.com/llvm/llvm-project/files/9333841/clang_main_frontend_crashes_UTCplus8_22081501.log)  is the full stacktrace, and [here](https://github.com/llvm/llvm-project/files/9333842/clang_main_frontend_crashes_UTCplus8_22081501.zip) are the preprocessed sources and run scripts.
I hope this would help.
(Codes uploaded here includes a part of an unpublished project, they are only permitted to be used in this bug report.)

**Comment by zhaoShiEnthalpy** [comment] 2022-08-14 18:23
FYI, here is the output of my gcc-12 -v:
```
Using built-in specs.
COLLECT_GCC=gcc-12
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 12-20220319-1ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-12-OcsLtf/gcc-12-12-20220319/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-12-OcsLtf/gcc-12-12-20220319/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.0.1 20220319 (experimental) [master r12-7719-g8ca61ad148f] (Ubuntu 12-20220319-1ubuntu1)
```

**Comment by inclyc** [comment] 2022-08-14 19:01
Could reproduce locally

**Comment by inclyc** [comment] 2022-08-14 19:59
I've made a simplified version which is sufficient to reproduce this issue here.

```C++
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <vector>

namespace MACE::Utility::Concept {

namespace Internal {

template<template<typename...> class, typename>
struct IsTemplateOf : std::false_type {};

template<template<typename...> class ATemplate, typename... Args>
struct IsTemplateOf<ATemplate, ATemplate<Args...>> : std::true_type {};

} // namespace Internal

template<class T, template<typename...> class ATemplate>
concept InstantiatedFrom = Internal::IsTemplateOf<ATemplate, T>::value;

} // namespace MACE::Utility::Concept

namespace MACE::Core::Geometry {
    
using Utility::Concept::InstantiatedFrom;
class DescriptionIO final {
public:
    DescriptionIO() = delete;

    template<typename... ArgsOfImport>
    static void Import(const InstantiatedFrom<std::tuple> auto& yamlText);

};

} // namespace MACE::Core::Geometry
```

See https://godbolt.org/z/qeKKqaedo

**Comment by zhaoShiEnthalpy** [comment] 2022-08-14 20:18
Thank you. That's much clearer.

**Comment by inclyc** [comment] 2022-08-14 21:46
https://reviews.llvm.org/D131866

**Comment by mizvekov** [comment] 2022-08-14 22:39
Duplicate of #55567

**Closed** 2022-08-14 22:46 UTC
Labels: duplicate, clang:frontend, crash
