### ISSUE TITLE
[clang-tidy] New check: Prefer list initialization

### ISSUE THREAD

**Issue by SunBlack** [llvm/llvm-project#81001] opened 2024-02-07 15:25 UTC
We are currently still using round brackets instead of curly brackets to create instances in our project. The transition within the member initialization lists to list initialization already showed some type issues.

As showed e.g., [here](https://stackoverflow.com/a/18222927) I think there are good reasons to prefer list initialization. Sadly it is not possible to refactor a project just with regular expressions, as there are some exceptions.

So my suggestion is to:
- Add a check `modernize-use-list-initialization` (ways thinking also about `bugprone` category, but not sure which is better)
- Suggest list initialization on all objects, which doesn't implement a initialization list constructor (e.g., `std::vector` should not transformed to an initializer list).

**Comment by carlosgalvezp** [comment] 2024-02-07 16:55
I'm not sure this fits in modernize, uniform initialization is available since C++11. Maybe misc-use-uniform-initialization? Or misc-use-brace-initialization.

**Comment by battlmonstr** [comment] 2024-10-28 09:21
This is a duplicate of https://github.com/llvm/llvm-project/issues/61454

**Closed** 2024-10-28 14:26 UTC
Labels: duplicate, clang-tidy, check-request
