### ISSUE TITLE
[llvm-mca][X86] Crash with alderlake scheduler model

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#57548] opened 2022-09-04 09:03 UTC
https://llvm.godbolt.org/z/q6qfPbdaK

```asm
code_snippet:
        vpmovzxbq       %xmm1, %xmm1
        vpsllw  %xmm1, %ymm0, %ymm0
        vpcmpeqd        %xmm2, %xmm2, %xmm2
        vpsllw  %xmm1, %xmm2, %xmm1
        vpbroadcastb    %xmm1, %ymm1
        vpand   %ymm1, %ymm0, %ymm0
```
`llvm-mca -mcpu=alderlake`
```console
llvm-mca: /root/llvm-project/llvm/lib/MCA/HardwareUnits/ResourceManager.cpp:181: llvm::mca::ResourceRef llvm::mca::ResourceManager::selectPipe(uint64_t): Assertion `RS.isReady() && "No available units to select!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca -o /app/output.s -mcpu=alderlake <source>
 #0 0x0000556196518a94 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005561965166d4 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fa31a417420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #3 0x00007fa319eea00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #4 0x00007fa319ec9859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #5 0x00007fa319ec9729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #6 0x00007fa319edafd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #7 0x00005561963b6b37 llvm::mca::ResourceManager::selectPipe(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa81b37)
 #8 0x00005561963b843b llvm::mca::ResourceManager::issueInstruction(llvm::mca::InstrDesc const&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ResourceCycles>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa8343b)
 #9 0x00005561963b9e68 llvm::mca::Scheduler::issueInstructionImpl(llvm::mca::InstRef&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ResourceCycles>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa84e68)
#10 0x00005561963bbd0e llvm::mca::Scheduler::issueInstruction(llvm::mca::InstRef&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ResourceCycles>>&, llvm::SmallVectorImpl<llvm::mca::InstRef>&, llvm::SmallVectorImpl<llvm::mca::InstRef>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa86d0e)
#11 0x00005561963caa57 llvm::mca::ExecuteStage::issueInstruction(llvm::mca::InstRef&) (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa95a57)
#12 0x00005561963cac43 llvm::mca::ExecuteStage::issueReadyInstructions() (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa95c43)
#13 0x00005561963caf41 llvm::mca::ExecuteStage::cycleStart() (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa95f41)
#14 0x00005561963c6b1e llvm::mca::Pipeline::runCycle() (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa91b1e)
#15 0x00005561963c715a llvm::mca::Pipeline::run() (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0xa9215a)
#16 0x0000556195f88c9f runPipeline(llvm::mca::Pipeline&) llvm-mca.cpp:0:0
#17 0x0000556195f4f57b main (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0x61a57b)
#18 0x00007fa319ecb083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#19 0x0000556195f841de _start (/opt/compiler-explorer/clang-assertions-trunk/bin/llvm-mca+0x64f1de)
Compiler returned: 139
```
I found this when running the costs script from D103695 to check shift-by-uniform costs

Removing either of the `vpsllw` ops seems to fix this

**Comment by phoebewang** [comment] 2022-09-04 09:52
cc @HaohaiWen

**Comment by HaohaiWen** [comment] 2022-09-05 02:56
I'll take a look.
The case can be simplified as:
`
code_snippet:
        vpsllw  %xmm1, %ymm0, %ymm0
        vpsllw  %xmm1, %xmm2, %xmm1
        vpand   %ymm1, %ymm0, %ymm0

`

**Comment by adibiagio** [comment] 2022-09-06 15:10
> I'll take a look. The case can be simplified as: ` code_snippet: vpsllw %xmm1, %ymm0, %ymm0 vpsllw %xmm1, %xmm2, %xmm1 vpand %ymm1, %ymm0, %ymm0
> 
> `

Thanks for looking into this.

Please let me know if you need help with triaging this issue.

**Comment by adibiagio** [comment] 2022-09-06 18:05
I believe this issue has to do with the presence of partially overlapping resource groups, and the lack of extra checks for resource availability in the Scheduler.

Below is the descriptor for the "problematic" vpsllw (from the original code snippet):

```
                Opcode Name= VPSLLWrr
                SchedClassID=283
                Opcode=15119
                Resource Mask=0x00000000002003, Reserved=0, #Units=1, cy=1
                Resource Mask=0x00000000100022, Reserved=0, #Units=1, cy=1
```

It means that VPSLLWrr consumes 1cy of resource group `ADLPPort00_01`, and also 1cy of resource group `ADLPPort01_05`.

Note how the two groups partially overlap; their intersection contains resource unit `ADLPPort01`.

Resource bookkeeping is done by a so-called `ResourceManager` unit. The Scheduler stage uses that unit to select the next "Ready to issue" instruction.

In the problematic cycle, that vpsllw is seen as Ready because the RDYMASK of both groups is a non-zero mask (see debug prints below):

```
MASK=0x00000000000001, SZMASK=0x00000000000001, RDYMASK=0x00000000000000, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000000002, SZMASK=0x00000000000001, RDYMASK=0x00000000000001, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000000020, SZMASK=0x00000000000001, RDYMASK=0x00000000000000, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000002003, SZMASK=0x00000000000003, RDYMASK=0x00000000000002, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000100022, SZMASK=0x00000000000022, RDYMASK=0x00000000000002, BufferSize=-1, AvailableSlots=0, Reserved=0
```

However, the ResourceManager fails to realise is that their RDYMASK is the same, and it only contains ADLPPort01.

When selecting resource group 0x2003 (ADLPPort00_01), the only possibility for the ResourceManager is to consume `ADLPPort01`.

So we end up in the following situation:

```
MASK=0x00000000000001, SZMASK=0x00000000000001, RDYMASK=0x00000000000000, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000000002, SZMASK=0x00000000000001, RDYMASK=0x00000000000000, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000000020, SZMASK=0x00000000000001, RDYMASK=0x00000000000000, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000002003, SZMASK=0x00000000000003, RDYMASK=0x00000000000000, BufferSize=-1, AvailableSlots=0, Reserved=0
MASK=0x00000000100022, SZMASK=0x00000000000022, RDYMASK=0x00000000000000, BufferSize=-1, AvailableSlots=0, Reserved=0
```

This is bad because Resource 0x00000000100022 (ADLPPort01_05) now is fully used, and there is no way to further select resources from it. This is what leads to the assertion failure.

**Comment by adibiagio** [comment] 2022-09-06 21:33
I think that this issue could be fixed in method `ResourceManager::checkAvailability`.

Essentially, method `ResourceManager::checkAvailability` needs to perform extra (potentially expensive) checks for instructions that consume overlapping resource groups.

**Comment by adibiagio** [comment] 2022-09-07 01:31
I have a fix for this issue. It passes all the regression tests, and it fixes the reproducible from this ticket.
I plan to commit it tomorrow after a few more extensive tests.

**Comment by HaohaiWen** [comment] 2022-09-07 01:59
Thanks @adibiagio for quick triage and fix.
Seem like this is a llvm-mca bug and not due to ADL schedule model?

**Comment by adibiagio** [comment] 2022-09-07 02:05
> Thanks @adibiagio for quick triage and fix. Seem like this is a llvm-mca bug and not due to ADL schedule model?

That's correct. This issue is caused by a bug in llvm-mca.

**Closed** 2022-09-07 11:39 UTC
Labels: backend:X86, tools:llvm-mca, backend:X86 Scheduler Models
