### ISSUE TITLE
__PRETTY_FUNCTION__ no longer contains namespace qualifications for return type, affects frontend and libtooling

### ISSUE THREAD

**Issue by Hexlord** [llvm/llvm-project#59338] opened 2022-12-05 07:15 UTC
Version | trunk
-- | --
OS | All

Clang 15's `__PRETTY_FUNCTION__` emitted fully qualified return type name, but Clang 16 lacks namespace qualifications.

```c++
#include <iostream>

namespace SE {

struct my_struct {
    int field;
};

template<typename T>
my_struct func() {
    std::cout<< __PRETTY_FUNCTION__;
    return my_struct{};
}

}

int main()
{
    SE::func<int>();
    return 0;
}
```
trunk yields 
> my_struct SE::func() [T = int]

clang 15 yields
> SE::my_struct SE::func() [T = int]

When updating libtooling plugin, a similar issue occurred: `FunctionDecl`'s `getReturnType()`, `getType()`, and `parameters()` each `QualType` no longer prints in fully qualified form, and requires manual walking through `getPointeeType()` and retrieving qualified name from `TypedefType`, `RecordType`, this is probably connected.

Compiler Explorer: https://godbolt.org/z/bGKTvEjKe

**Comment by mizvekov** [comment] 2022-12-05 13:57
Duplicate of https://github.com/llvm/llvm-project/issues/58040

**Closed** 2022-12-05 13:59 UTC
Labels: duplicate, clang:frontend, clang:tooling

**Comment by Hexlord** [comment] 2022-12-05 14:14
`clang::TypeName::getFullyQualifiedName` solves all my problems with parsing `FunctionDecl`-s, thank you so much!
