### ISSUE TITLE
When using the text `module` as an identifier, clang++ incorrectly rejects it

### ISSUE THREAD

**Issue by androm3da** [llvm/llvm-project#103054] opened 2024-08-13 12:59 UTC
According to §5.10 Identifiers [lex.name], "Unless otherwise specified, any ambiguity as to whether a given identifier has a special meaning is resolved to interpret the token as a regular identifier."

Does this mean that clang is incorrect to emit an error in this case?

```
$ cat ~/tmp/module_ident.cpp 

using module = int;
module i;
int foo() {
    return i;
}
```

```
$ clang++ -c ~/tmp/module_ident.cpp -std=c++20
/usr2/bcain/tmp/module_ident.cpp:3:1: error: module declaration must occur at the start of the translation unit
    3 | module i;
      | ^
/usr2/bcain/tmp/module_ident.cpp:1:1: note: add 'module;' to the start of the file to introduce a global module fragment
    1 | 
      | ^
/usr2/bcain/tmp/module_ident.cpp:3:8: fatal error: module 'i' not found
    3 | module i;
      | ~~~~~~~^
2 errors generated.

```

**Comment by androm3da** [comment] 2024-08-13 14:29
gcc does permit this code, btw:

```
$ g++ -c ~/tmp/module_ident.cpp -std=c++23; echo $?
0

```

```
$ g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


```

**Comment by AaronBallman** [comment] 2024-08-13 16:25
I think Clang's behavior is correct because `module i;` matches the grammar production for a module declaration: https://eel.is/c++draft/module#unit

But there are shenanigans as to how `module` is handled as a keyword. CC @ChuanqiXu9

**Comment by ChuanqiXu9** [comment] 2024-08-14 03:02
It looks like true that the clang's behavior is incorrect. Here is my interpretation for the wording:

From http://eel.is/c++draft/lex.pptoken#4:

> The import-keyword is produced by preprocessing an import directive ([[cpp.import]](http://eel.is/c++draft/cpp.import)), the module-keyword is produced by preprocessing a module directive ([[cpp.module]](http://eel.is/c++draft/cpp.module)), and the export-keyword is produced by preprocessing either of the previous two directives[.](http://eel.is/c++draft/lex.pptoken#4.sentence-1)

So the modules' keyword are special keyword. They are not directly produced from tokens but from the preprocessor.

And from the preprocessor, in http://eel.is/c++draft/cpp.pre, we can see:

> [preprocessing-file:](http://eel.is/c++draft/cpp.pre#nt:preprocessing-file)
>        [group](http://eel.is/c++draft/cpp.pre#nt:group)opt
>        [module-file](http://eel.is/c++draft/cpp.pre#nt:module-file)
>
> [module-file:](http://eel.is/c++draft/cpp.pre#nt:module-file)
>       [pp-global-module-fragment](http://eel.is/c++draft/cpp.pre#nt:pp-global-module-fragment)opt
>
>       [pp-module](http://eel.is/c++draft/cpp.module#nt:pp-module) [group](http://eel.is/c++draft/cpp.pre#nt:group)opt ...
>

That said, the preprocessing module file must start with `module;` (start of `[pp-global-module-fragment]`) or `[pp-module]` (http://eel.is/c++draft/cpp.module#nt:pp-module), which should start with `export module [identifier]` or `module [identifier]`.). And then the module keywords are produced since then.

And in this example, the reproducer is not a `module-file` since it doesn't start with `module;`, `export module [identifier];` or `module [identifier];`. So the module-keywords wouldn't be produced.

My understanding for this design is, we don't want to the common words: `module`, `export` , `import` to be keywords unconditionally to break programs like this issue raised.

CC people who may be interested: @cor3ntin @yronglin

**Comment by AaronBallman** [comment] 2024-08-14 12:01
I read http://eel.is/c++draft/lex.pptoken#4 as taking us to http://eel.is/c++draft/cpp.module where the grammar production is `export_opt module pp-tokens_opt ; new-line`, so we match the grammar production. p1 doesn't apply because it's not an object-like macro. We meet the requirements in p2. p3 doesn't apply. Then we get to p4 which is what makes it a `module-keyword` that ends up passed to the parser. So I still think we're correct to reject that code -- if we were treating `module` as a keyword, we would have given an error on `using module = int;`, or in cases like: https://godbolt.org/z/T5e4s3W1d

**Comment by cor3ntin** [comment] 2024-08-14 13:41
Whether `module foo;` is a preprocessing directive is not affected by whether we are in a module or not.
The wording is `https://eel.is/c++draft/cpp.pre#1`

> A [preprocessing directive](https://eel.is/c++draft/cpp.pre#def:preprocessing_directive) [...] is [...] a module preprocessing token immediately followed on the same logical source line by an [identifier](https://eel.is/c++draft/lex.name#nt:identifier)

So clang is correct even though we do not fully implement P1857R3

**Comment by ChuanqiXu9** [comment] 2024-08-15 02:46
but if we're not in a module, why do we need to emit the diagnostics? And even if the `module foo;` is a preprocessing directive, I feel it doesn't imply that  the syntax of [cpp.module] may be consumed. The syntax of http://eel.is/c++draft/cpp.pre implies that [cpp.module] can only be in a module-file.

I'll try to ask the CWG

**Comment by ChuanqiXu9** [comment] 2024-08-16 02:04
> Where do you see wording that says that `module` is only a preprocessing token inside a module?

I think you can take a look at the CWG's discussing.

**Comment by cor3ntin** [comment] 2024-08-16 15:31
https://cplusplus.github.io/CWG/issues/2927.html CWG confirmed the intent of the current behavior

**Comment by AaronBallman** [comment] 2024-08-19 12:53
Closing as not a bug, but if CWG changes direction, we'll capture it when processing DRs.

**Closed by AaronBallman** 2024-08-19 12:53 UTC
Labels: invalid, c++20, clang:modules

**Comment by shafik** [comment] 2024-09-13 18:44
Note additionally all but gcc rejects this: https://godbolt.org/z/fbPvaenMb
