### ISSUE TITLE
[clang++] constexpr is not propagated in lambda in a template context under specific condition

### ISSUE THREAD

**Issue by stephen-hqxu** [llvm/llvm-project#94849] opened 2024-06-08 10:39 UTC
I initially discovered this issue on the official clang 18 build on Ubuntu. Then I did a quick test on [compiler explorer](https://godbolt.org/), and it seems to affect all clang versions (starting clang 5) that support C++17 constexpr lambda feature; perhaps platform does not really matter.

Consider the following code:
```cpp
template<typename = void>
void doStuff() {
	auto equalsOne = [](auto x) -> bool {
		return x == 1;
	};
	static_assert(equalsOne(1), "oops");
}

int main() {
	doStuff();
}
```
And compile with:
```sh
clang++ -std=c++17 ./example.cpp -o example
```
This code does not compile and will generate the following errors:
> static assertion expression is not an integral constant expression \
> static_assert(equalsOne(1), "oops");

There are a few observations:
- The code compiles on GCC and MSVC.
- Make `doStuff` non-template, i.e. removing `template<typename = void>`, compiles.
- Change the lambda call signature from `auto x` to `int x`, compiles. However, it still does not compile if it is in C++20 and replace `auto` with explicit lambda template parameter. This basically means it does not compile when lambda is a template, regardless of how it is templated.
- Change the trailing return type of lambda `-> bool` to `-> auto`, or equivalently removing the trailing return type, compiles.
- It does not compile even if decorating the lambda with `constexpr`, i.e. `[](auto x) constexpr -> bool`.

**Comment by zyn0217** [comment] 2024-06-15 12:25
Duplicate of #35052

**Closed by zyn0217** 2024-06-15 12:25 UTC
Labels: duplicate, clang:frontend, lambda, constexpr
