### ISSUE TITLE
clang/llvm 18.1.8 ( Arch Linux ) crash when compiling linux using march set to znver4

### ISSUE THREAD

**Issue by sinatosk** [llvm/llvm-project#98880] opened 2024-07-15 10:19 UTC
update 1: 36 minutes after initial post - I've redid the run again and since updated the error log and attached files

I've been compiling Linux using clang/llvm for sometime ( 1-2 years ).

Since Arch Linux updated llvm to 18.1.8 recently ( 7th July 2024 ), clang/llvm crashes when using "march=znver4" when compiling Linux 6.9 and 6.10

> net/ipv6/ip6_input.c

from the Linux source tree

The error I'm seeing is ( from Linux 6.10, it's the same for Linux 6.9 )

```
/usr/include/c++/14.1.1/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = llvm::SUnit; _Alloc = std::allocator<llvm::SUnit>; reference = llvm::SUnit&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /usr/bin/clang --target=x86_64-linux-gnu -fintegrated-as -Werror=unknown-warning-option -Werror=ignored-optimization-argument -Werror=option-ignored -Werror=unused-command-line-argument -fmacro-prefix-map=./= -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=branch -fno-jump-tables -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mstack-alignment=8 -mskip-rax-setup -march=znver4 -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fstack-protector-strong -ftrivial-auto-var-init=zero -fno-stack-clash-protection -fzero-call-used-regs=used-gpr -pg -mfentry -falign-functions=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-gnu -Wvla -Wno-pointer-sign -Wcast-function-type -Wimplicit-fallthrough -Werror=date-time -Werror=incompatible-pointer-types -Wenum-conversion -Wextra -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-format-overflow -Wno-format-overflow-non-kprintf -Wno-format-truncation-non-kprintf -Wno-override-init -Wno-pointer-to-enum-cast -Wno-tautological-constant-out-of-range-compare -Wno-unaligned-access -Wno-enum-compare-conditional -Wno-enum-enum-conversion -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-sign-compare -Wno-unused-parameter -g -gdwarf-5 -nostdinc -I./arch/x86/include -I./arch/x86/include/generated -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -DCC_USING_NOP_MCOUNT -DCC_USING_FENTRY -DKBUILD_MODFILE=\"net/ipv6/ipv6\" -DKBUILD_BASENAME=\"ip6_input\" -DKBUILD_MODNAME=\"ipv6\" -D__KBUILD_MODNAME=kmod_ipv6 -c -Wp,-MMD,net/ipv6/.ip6_input.o.d -fcolor-diagnostics -o net/ipv6/ip6_input.o net/ipv6/ip6_input.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'net/ipv6/ip6_input.c'.
4.      Running pass 'X86 DAG->DAG Instruction Selection' on function '@ip6_rcv_core'
 #0 0x00007fda05fc4d90 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM.so.18.1+0x7c4d90)
 #1 0x00007fda05fc226d llvm::sys::CleanupOnSignal(unsigned long) (/usr/lib/libLLVM.so.18.1+0x7c226d)
 #2 0x00007fda05ea88e9 (/usr/lib/libLLVM.so.18.1+0x6a88e9)
 #3 0x00007fda05250ae0 (/usr/lib/libc.so.6+0x3cae0)
 #4 0x00007fda052a8e44 (/usr/lib/libc.so.6+0x94e44)
 #5 0x00007fda05250a30 raise (/usr/lib/libc.so.6+0x3ca30)
 #6 0x00007fda052384c3 abort (/usr/lib/libc.so.6+0x244c3)
 #7 0x00007fda054d2d60 std::chrono::_V2::system_clock::now() /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/chrono.cc:52:5
 #8 0x00007fda06aed7d0 llvm::ScheduleDAGSDNodes::AddSchedEdges() (/usr/lib/libLLVM.so.18.1+0x12ed7d0)
 #9 0x00007fda06ae5786 (/usr/lib/libLLVM.so.18.1+0x12e5786)
#10 0x00007fda06bd95f2 llvm::SelectionDAGISel::CodeGenAndEmitDAG() (/usr/lib/libLLVM.so.18.1+0x13d95f2)
#11 0x00007fda06bdca09 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/usr/lib/libLLVM.so.18.1+0x13dca09)
#12 0x00007fda06bdeb57 (/usr/lib/libLLVM.so.18.1+0x13deb57)
#13 0x00007fda06be0591 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/usr/lib/libLLVM.so.18.1+0x13e0591)
#14 0x00007fda0a2984b8 (/usr/lib/libLLVM.so.18.1+0x4a984b8)
#15 0x00007fda0652f72d (/usr/lib/libLLVM.so.18.1+0xd2f72d)
#16 0x00007fda061830d3 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/libLLVM.so.18.1+0x9830d3)
#17 0x00007fda061834a4 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x9834a4)
#18 0x00007fda06184f6f llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/libLLVM.so.18.1+0x984f6f)
#19 0x00007fda0ef2f21f clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) (/usr/lib/libclang-cpp.so.18.1+0x152f21f)
#20 0x00007fda0f2add95 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/lib/libclang-cpp.so.18.1+0x18add95)
#21 0x00007fda0df89f23 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/libclang-cpp.so.18.1+0x589f23)
#22 0x00007fda0fa1a7c1 clang::FrontendAction::Execute() (/usr/lib/libclang-cpp.so.18.1+0x201a7c1)
#23 0x00007fda0f9bbad7 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/libclang-cpp.so.18.1+0x1fbbad7)
#24 0x00007fda0fa6e11d clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/libclang-cpp.so.18.1+0x206e11d)
#25 0x00005597b234f284 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang+0x13284)
#26 0x00005597b23535ba (/usr/bin/clang+0x175ba)
#27 0x00007fda0f6f7175 (/usr/lib/libclang-cpp.so.18.1+0x1cf7175)
#28 0x00007fda05ea8d3a llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/libLLVM.so.18.1+0x6a8d3a)
#29 0x00007fda0f6f9aa6 (/usr/lib/libclang-cpp.so.18.1+0x1cf9aa6)
#30 0x00007fda0f6b5529 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/usr/lib/libclang-cpp.so.18.1+0x1cb5529)
#31 0x00007fda0f6b591c clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/usr/lib/libclang-cpp.so.18.1+0x1cb591c)
#32 0x00007fda0f6d38c4 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/usr/lib/libclang-cpp.so.18.1+0x1cd38c4)
#33 0x00005597b2355ebd clang_main(int, char**, llvm::ToolContext const&) (/usr/bin/clang+0x19ebd)
#34 0x00005597b2346fb5 main (/usr/bin/clang+0xafb5)
#35 0x00007fda05239c88 (/usr/lib/libc.so.6+0x25c88)
#36 0x00007fda05239d4c __libc_start_main (/usr/lib/libc.so.6+0x25d4c)
#37 0x00005597b2347015 _start (/usr/bin/clang+0xb015)
clang: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 18.1.8
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/ip6_input-aa8fa7.c
clang: note: diagnostic msg: /tmp/ip6_input-aa8fa7.sh
clang: note: diagnostic msg: 

********************
make[4]: *** [scripts/Makefile.build:244: net/ipv6/ip6_input.o] Error 1
make[3]: *** [scripts/Makefile.build:485: net/ipv6] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:485: net] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/home/user/path/to/linux/src/Makefile:1934: .] Error 2
make: *** [Makefile:240: __sub-make] Error 2
```

I've [attached](https://github.com/user-attachments/files/16233381/ip6_input-aa8fa7.zip) the two files ( ip6_input-aa8fa7.c and ip6_input-aa8fa7.sh in a zip file ) mentioned in error log. I've searched and replaced some paths and hostname in the files like

> /path/to/private/key

> /home/user/path/to/linux/src

> hostname

I've compiled Linux 6.10 with march set to x86-64-v4 successfully

**Comment by dtcxzyw** [comment] 2024-07-15 12:27
Duplicate of #98301.

**Closed** 2024-07-15 13:58 UTC
Labels: duplicate, backend:X86, llvm:crash, llvm:SelectionDAG

**Comment by DimitryAndric** [comment] 2024-07-15 14:02
Is it really the same? #98301 is marked as incomplete, while this one has a reproducer, and the stack trace is different?

**Comment by RKSimon** [comment] 2024-07-15 14:17
Duplicate of #82431?

**Comment by Grimish-ng** [comment] 2024-07-15 14:52
I've experienced the same problem with znver4.

**Comment by LtdJorge** [comment] 2024-07-21 01:42
@RKSimon I see you went through some of the duplicate issues asking about trunk. Can confirm that on Gentoo, 18.1 crashes when compiling the kernel at vmlinux (znver2) for me, but latest 19.0 from git compiles the kernel and it boots OK.
