### ISSUE TITLE
Segmentation fault when running `clang-tidy`.

### ISSUE THREAD

**Issue by lilyatplyable** [llvm/llvm-project#96472] opened 2024-06-24 09:52 UTC
After upgrading to Fedora 40 and LLVM version 18.1.6

```
Error running 'clang-tidy': PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: clang-tidy --config-file=../.clang-tidy --extra-arg-before=--driver-mode=g++ /q/***.cxx -- /usr/bin/c++ -D _GLIBCXX_ASSERTIONS -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_LOG_DYN_LINK -DBOOST_LOG_NO_LIB -DBOOST_LOG_SETUP_DYN_LINK -DBOOST_LOG_SETUP_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_STACKTRACE_USE_ADDR2LINE -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_NO_LIB -DCGAL_USE_CORE=1 -DCGAL_USE_GMPXX=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/q/cmake-build-debug/tests_autogen/include -I/usr/include/python3.12 -I/usr/include/eigen3 -isystem /usr/local/include/opencascade -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -std=gnu++2b -DBOOST_LOG_DYN_LINK -lboost_log -g -fno-inline -frounding-math -fPIC -MD -MT CMakeFiles/tests.dir/***.cxx.o -MF CMakeFiles/tests.dir/***.cxx.o.d -o CMakeFiles/tests.dir/***.cxx.o -c /q/***.cxx
1.	<eof> parser at end of file
2.	ASTMatcher: Processing 'modernize-use-constraints' against:
	FunctionTemplateDecl boost::multiprecision::abs : </usr/include/boost/multiprecision/detail/default_ops.hpp:2313:1, line:2318:1>
--- Bound Nodes Begin ---
    function - { FunctionDecl boost::multiprecision::abs : </usr/include/boost/multiprecision/detail/default_ops.hpp:2314:1, line:2318:1> }
    functionTemplate - { FunctionTemplateDecl boost::multiprecision::abs : </usr/include/boost/multiprecision/detail/default_ops.hpp:2313:1, line:2318:1> }
    return - { DependentNameTypeLoc : </usr/include/boost/multiprecision/detail/default_ops.hpp:2314:33, col:162> }
--- Bound Nodes End ---
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM.so.18.1      0x00007fd2df3534fa llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 58
1  libLLVM.so.18.1      0x00007fd2df350ce4 llvm::sys::RunSignalHandlers() + 84
2  libLLVM.so.18.1      0x00007fd2df353c5b
3  libc.so.6            0x00007fd2de85c710
4  clang-tidy           0x0000000000948887
5  clang-tidy           0x00000000009476ea clang::tidy::modernize::UseConstraintsCheck::check(clang::ast_matchers::MatchFinder::MatchResult const&) + 154
6  clang-tidy           0x0000000000ca2b32
7  clang-tidy           0x0000000000cd7e6c clang::ast_matchers::internal::BoundNodesTreeBuilder::visitMatches(clang::ast_matchers::internal::BoundNodesTreeBuilder::Visitor*) + 172
8  clang-tidy           0x0000000000ca2381
9  clang-tidy           0x0000000000ca421b
10 clang-tidy           0x0000000000ca698b
11 clang-tidy           0x0000000000ca476d
12 clang-tidy           0x0000000000ca698b
13 clang-tidy           0x0000000000ca476d
14 clang-tidy           0x0000000000cd444b
15 clang-tidy           0x0000000000ca4b86
16 clang-tidy           0x0000000000ca423a
17 clang-tidy           0x0000000000c6f3ea clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) + 730
18 libclang-cpp.so.18.1 0x00007fd2e8600acc clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 44
19 libclang-cpp.so.18.1 0x00007fd2e6321436 clang::ParseAST(clang::Sema&, bool, bool) + 614
20 libclang-cpp.so.18.1 0x00007fd2e85c99f6 clang::FrontendAction::Execute() + 102
21 libclang-cpp.so.18.1 0x00007fd2e8541700 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 768
22 libclang-cpp.so.18.1 0x00007fd2e87de901 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) + 513
23 clang-tidy           0x00000000013ed1ce
24 libclang-cpp.so.18.1 0x00007fd2e87de5c4 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) + 372
25 libclang-cpp.so.18.1 0x00007fd2e87dd344 clang::tooling::ToolInvocation::run() + 1172
26 libclang-cpp.so.18.1 0x00007fd2e87e04f5 clang::tooling::ClangTool::run(clang::tooling::ToolAction*) + 5157
27 clang-tidy           0x00000000013e85d3 clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, bool, llvm::StringRef) + 1299
28 clang-tidy           0x00000000005ff0b8 clang::tidy::clangTidyMain(int, char const**) + 12344
29 libc.so.6            0x00007fd2de846088
30 libc.so.6            0x00007fd2de84614b __libc_start_main + 139
31 clang-tidy           0x00000000005fb2f5 _start + 37
Segmentation fault
```

**Comment by njames93** [comment] 2024-06-28 16:01
@PiotrZSL is this a duplicate of #91872

**Comment by PiotrZSL** [comment] 2024-06-28 18:06
> @PiotrZSL is this a duplicate of #91872

Yes, welcome back

**Closed** 2024-06-28 18:06 UTC
Labels: duplicate, clang-tidy, crash
