### ISSUE TITLE
crash in wasm-ld

### ISSUE THREAD

**Issue by dimitry-** [llvm/llvm-project#84731] opened 2024-03-11 08:57 UTC
I have encountered this crash while trying to build one of android-ndk-samples for wasm, please find a reproducer file attached.

```
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld -m wasm64 -L/projects/wasm/wasm_ndk/cmake/toolchain/../../libs -L/usr/local/google/home/dimitry/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/lib --emit-relocs --no-entry -lc --export=ANativeActivity_onCreate --strip-debug CMakeFiles/TeapotNativeActivity.dir/TeapotNativeActivity.cpp.o CMakeFiles/TeapotNativeActivity.dir/TeapotRenderer.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/gestureDetector.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/gl3stub.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/GLContext.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/interpolator.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/JNIHelper.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/perfMonitor.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/sensorManager.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/shader.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/tapCamera.cpp.o CMakeFiles/TeapotNativeActivity.dir/projects/ndk-samples/teapots/common/ndk_helper/vecmath.cpp.o CMakeFiles/TeapotNativeActivity.dir/usr/local/google/home/dimitry/Android/Sdk/ndk/25.1.8937393/sources/android/native_app_glue/android_native_app_glue.c.o -landroid -lGLESv2 -lEGL -llog -lc++ -lm -ldl -o TeapotNativeActivity
 #0 0x0000560136de11f8 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1ab01f8)
 #1 0x0000560136ddf05e (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1aae05e)
 #2 0x0000560136de1b35 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1ab0b35)
 #3 0x00007f984e10d510 (/lib/x86_64-linux-gnu/libc.so.6+0x3c510)
 #4 0x00005601370f32e4 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1dc22e4)
 #5 0x000056013710a599 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1dd9599)
 #6 0x000056013710061a (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1dcf61a)
 #7 0x00005601370fb580 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1dca580)
 #8 0x00005601370f3c50 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1dc2c50)
 #9 0x00005601370d6cb9 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1da5cb9)
#10 0x00005601370d3a1b (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1da2a1b)
#11 0x0000560136de3902 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1ab2902)
#12 0x0000560136d4f3b5 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1a1e3b5)
#13 0x0000560136d4f841 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1a1e841)
#14 0x00007f984e0f86ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#15 0x00007f984e0f8785 call_init ./csu/../csu/libc-start.c:128:20
#16 0x00007f984e0f8785 __libc_start_main ./csu/../csu/libc-start.c:347:5
#17 0x0000560136d4efa9 (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1a1dfa9)
clang++: error: unable to execute command: Segmentation fault
clang++: error: linker command failed due to signal (use -v to see invocation)
```

[emit-reloc-wasm-ld-crash.tar.gz](https://github.com/llvm/llvm-project/files/14555937/emit-reloc-wasm-ld-crash.tar.gz)

**Comment by dimitry-** [comment] 2024-03-11 08:58
wasm-ld works fine if --emit-reloc option is removed

**Comment by sbc100** [comment] 2024-03-19 23:43
I can't seem to reproduce this using my debug build of wasm-ld.  It did run into an assertion, but simply commenting it out resulting in no crash.

Are you able to try to reproduce with a `Release+Asserts` build of wasm-ld so we can see a better stack trace?

**Comment by dimitry-** [comment] 2024-03-21 08:39
Symbolized stack-trace

```
 #0 0x00005640e9784bf8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1b60bf8)
 #1 0x00005640e9782a5e llvm::sys::RunSignalHandlers() (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1b5ea5e)
 #2 0x00005640e9785555 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fc4b7a75510 (/lib/x86_64-linux-gnu/libc.so.6+0x3c510)
 #4 0x00005640e9b00c84 lld::wasm::DefinedData::getOutputSegmentIndex() const (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1edcc84)
 #5 0x00005640e9b1aed9 lld::wasm::LinkingSection::writeBody() (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1ef6ed9)
 #6 0x00005640e9b0dfda lld::wasm::SyntheticSection::finalizeContents() Writer.cpp:0:0
 #7 0x00005640e9b08f30 lld::wasm::(anonymous namespace)::Writer::run() Writer.cpp:0:0
 #8 0x00005640e9b01600 lld::wasm::writeResult() (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1edd600)
 #9 0x00005640e9ae0399 lld::wasm::(anonymous namespace)::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) Driver.cpp:0:0
#10 0x00005640e9add0fb lld::wasm::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1eb90fb)
#11 0x00005640e9787702 lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1b63702)
#12 0x00005640e96ee235 lld_main(int, char**, llvm::ToolContext const&) (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1aca235)
#13 0x00005640e96ee711 main (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1aca711)
#14 0x00007fc4b7a606ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#15 0x00007fc4b7a60785 call_init ./csu/../csu/libc-start.c:128:20
#16 0x00007fc4b7a60785 __libc_start_main ./csu/../csu/libc-start.c:347:5
#17 0x00005640e96ede29 _start (/projects/android-llvm-toolchain/out/install/linux-x86/clang-dev/bin/wasm-ld+0x1ac9e29)

```

**Comment by dimitry-** [comment] 2024-03-21 12:20
This is stacktrace with full debug info, I enabled asserts (for context the android-toolchain uses python to build it, I built it with --enable-asserts), but I did not see any asserts:

```
 #0 0x000055b5afb567bd llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) out/stage2/out/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x000055b5afb56cab PrintStackTraceSignalHandler(void*) out/stage2/out/llvm-project/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x000055b5afb54fc6 llvm::sys::RunSignalHandlers() out/stage2/out/llvm-project/llvm/lib/Support/Signals.cpp:105:5
 #3 0x000055b5afb57285 SignalHandler(int) out/stage2/out/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f7b2ce4a510 (/lib/x86_64-linux-gnu/libc.so.6+0x3c510)
 #5 0x000055b5b02d1eb3 lld::wasm::DefinedData::getOutputSegmentIndex() const out/stage2/out/llvm-project/lld/wasm/Symbols.cpp:335:19
 #6 0x000055b5b0307705 lld::wasm::LinkingSection::writeBody() out/stage2/out/llvm-project/lld/wasm/SyntheticSections.cpp:668:41
 #7 0x000055b5b02eb2aa lld::wasm::SyntheticSection::finalizeContents() out/stage2/out/llvm-project/lld/wasm/SyntheticSections.h:58:5
 #8 0x000055b5b02dd9cf lld::wasm::(anonymous namespace)::Writer::finalizeSections() out/stage2/out/llvm-project/lld/wasm/Writer.cpp:550:17
 #9 0x000055b5b02d5c6b lld::wasm::(anonymous namespace)::Writer::run() out/stage2/out/llvm-project/lld/wasm/Writer.cpp:1817:7
#10 0x000055b5b02d4f76 lld::wasm::writeResult() out/stage2/out/llvm-project/lld/wasm/Writer.cpp:1861:22
#11 0x000055b5b0282e22 lld::wasm::(anonymous namespace)::LinkerDriver::linkerMain(llvm::ArrayRef<char const*>) out/stage2/out/llvm-project/lld/wasm/Driver.cpp:1337:1
#12 0x000055b5b028160b lld::wasm::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) out/stage2/out/llvm-project/lld/wasm/Driver.cpp:100:3
#13 0x000055b5afb5d400 lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) out/stage2/out/llvm-project/lld/Common/DriverDispatcher.cpp:164:11
#14 0x000055b5afa3d770 lld_main(int, char**, llvm::ToolContext const&) out/stage2/out/llvm-project/lld/tools/lld/lld.cpp:91:9
#15 0x000055b5afa4094d main out/stage2/out/stage2/tools/lld/tools/lld/lld-driver.cpp:15:3
#16 0x00007f7b2ce356ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#17 0x00007f7b2ce35785 call_init ./csu/../csu/libc-start.c:128:20
#18 0x00007f7b2ce35785 __libc_start_main ./csu/../csu/libc-start.c:347:5
#19 0x000055b5afa3d529 _start (/projects/android-llvm-toolchain/out/stage2-install/bin/wasm-ld+0x39f3529)
```

line 335
```
333 uint64_t DefinedData::getOutputSegmentIndex() const {
334   LLVM_DEBUG(dbgs() << "getOutputSegmentIndex: " << getName() << "\n");
335   return segment->outputSeg->index;
336 } 
```

**Comment by sbc100** [comment] 2024-03-21 17:50
Thanks for extra info.

I don't really understand why I can't reproduce this myself.    Can you share the exact version of llvm you are build and I'll try that.

**Comment by matthias-blume** [comment] 2024-03-28 14:26
I just tried this again, and I am now able to link just fine.

Perhaps this was a transient problem with the particular build of llvm-toolchain?
I did update my llvm-toolchain since the problem occurred last time...

**Comment by sbc100** [comment] 2024-03-28 15:46
I suspect this will come back to bite us at some point.  Closing this for now but please re-open if/when it does

**Closed** 2024-03-28 15:52 UTC
Labels: lld:wasm, crash, needs-reduction
