### ISSUE TITLE
clang-format hangs when piping to it's own config

### ISSUE THREAD

**Issue by ljmf00** [llvm/llvm-project#54502] opened 2022-03-22 18:49 UTC
Doing the following:

```
clang-format --dump-config > .clang-format
```

Produces:

```
Error reading /some/path/.clang-format: Invalid argument
```

**Comment by mydeveloperday** [comment] 2022-03-23 10:08
You get this error if your .clang-format file is empty

Error reading /some./path/.clang-format:
 Invalid argument

If you run any command, say

```
cat test.txt > test.txt
```

Where test.txt has something in it, the result will be an empty test.txt because of the way I suspect the shell works

So I don't think this error is unreasonable and I'm not convinced we can do anything about it.

I'm going to close this as functioning as designed (as its a shell think not a clang-format thing).

**Closed by mydeveloperday** 2022-03-23 10:08 UTC
Labels: clang-format

**Comment by ljmf00** [comment] 2022-03-23 21:27
Ah right, it's a shell specific behaviour. I think it's sensible to convert this to a feature, although, to allow `-i` to dump the config in place.
