### ISSUE TITLE
clang-format. SeparateDefinitionBlocks inserts spaces after attribute like macro

### ISSUE THREAD

**Issue by yrHeTaTeJlb** [llvm/llvm-project#66759] opened 2023-09-19 10:28 UTC
Unreal Engine widely uses attribute-like macroses. And SeparateDefinitionBlocks fails to format them properly in some places. For example UPROPERTY and UENUM and UFUNCTION look fine
```
UENUM()
enum class EEnum 
{
    Foo,
    Bar,
};

struct FStruct
{
    UPROPERTY()
    int Baz = 0;
    
    UFUNCTION()
    int Quux();
}
```

but USTRUCT and UCLASS get space after them
```
USTRUCT()

struct FStruct 
{

};

UCLASS()

class FClass 
{

};
```

I tried adding these macro to StatementMacros and StatementAttributeLikeMacros lists, but it didn't help

**Comment by owenca** [comment] 2023-10-18 22:28
Works in 17.0.3 and trunk:
```
$ clang-format -version
clang-format version 17.0.3
$ cat test.cpp
USTRUCT()
struct FStruct 
{

};

UCLASS()

class FClass 
{

};
$ clang-format test.cpp
USTRUCT()
struct FStruct {};

UCLASS()

class FClass {};
```
clang-format removes empty lines subject to `MaxEmptyLinesToKeep`. See #69051.

**Comment by yrHeTaTeJlb** [comment] 2023-10-19 11:22
MaxEmptyLinesToKeep has nothing to do there. I neither  want my code to get squashed into single block, nor to align everything manually. The problem is taht `SeparateDefinitionBlocks: Always` treats property-like macro incorrectly. USTRUCT(), UCLASS(), UPROPERTY() and UENUM() are not definitions, and there should be no emty line afer them.
```
$ cat .clang-format
SeparateDefinitionBlocks: Always
BreakBeforeBraces: Allman

$ cat test.cpp
UENUM()
enum class EEnum
{
    Foo,
    Bar,
};
USTRUCT()
struct FStruct
{
    UPROPERTY()
    int baz = 0;
    UFUNCTION()
    int quux(){}
};
UCLASS()
class FClass
{
    void foo(){}
    void bar(){}
};

$ clang-format.exe --version
clang-format version 17.0.1 (git://code.qt.io/clang/llvm-project.git 1eee682c1df3ce22d1c53c36f9c44cb4bf3df615)

$ clang-format.exe test.cpp
UENUM()
enum class EEnum
{
  Foo,
  Bar,
};
USTRUCT()

struct FStruct
{
  UPROPERTY()
  int baz = 0;
  UFUNCTION()

  int quux() {}
};
UCLASS()

class FClass
{
  void foo() {}

  void bar() {}
};

$ cat expected.cpp
UENUM()
enum class EEnum
{
  Foo,
  Bar,
};

USTRUCT()
struct FStruct
{
  UPROPERTY()
  int baz = 0;

  UFUNCTION()
  int quux() {}
};

UCLASS()
class FClass
{
  void foo() {}

  void bar() {}
};
```

**Comment by owenca** [comment] 2023-10-19 12:08
Duplicate of #69591

**Closed by owenca** 2023-10-19 12:08 UTC
Labels: duplicate, clang-format
