### ISSUE TITLE
Right-clicking source.zip file causes issues on windows

### ISSUE THREAD

**Issue by kimiyoribaka** [llvm/llvm-project#107045] opened 2024-09-03 03:39 UTC
If you go into windows explorer and right-click the freshly downloaded source code file to unzip it, the explorer window becomes unresponsive. If I then try to close it, explorer resets (which causes all explorer windows to close and jumbles all tabs for all other windows in the toolbar).

This is occurring on version 18.1.8 while using windows 10.

**Comment by AaronBallman** [comment] 2024-09-03 20:53
This is an issue with Windows Explorer rather than with the source we're providing. I verified that the zip file is not corrupted (I was able to open it fine with WinRAR for example).

FWIW, Windows Explorer did eventually finish opening the zip file for me, but it took a *long* time.

Closing the issue as not a bug; I don't think there's anything we can do to improve this.

**Closed by AaronBallman** 2024-09-03 20:53 UTC
Labels: invalid, packaging, platform:windows
