### ISSUE TITLE
error: 'd<int>::d' from module 'd' is not present in definition of 'd<int>' in module 'd'

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#60036] opened 2023-01-14 22:46 UTC
This was probably the hardest to reduce bug I've found yet. I suspect it can be reduced more but I don't know how.

The following set of translation units should be accepted:

```cpp
export module a;

export template<typename>
struct a;

template<typename T>
struct a<T &> {
	using type = char;
};
```

```cpp
export module b;

import a;

typename a<char &>::type;
```

```cpp
export module c;

import a;

typename a<char &>::type;
```

```cpp
export module d;

export template<typename>
struct d {
	d() {}
	explicit d(int) requires(true) {}
	d(auto &&) {}
};
```

```cpp
export module e;

import d;

auto r = d<int>();
```

```cpp
export module f;

import a;
import b;
import c;
import d;

template<typename T>
struct array {
	friend void fr(array<T> const &) {
	}
};

array() -> array<typename a<char &>::type>;

struct wrap {
	d<int> m;
};

template<typename T>
int f1(T) {
	return 1;
}

void f2() {
	d<int> view;
	int x = f1(view);
	typename a<decltype([x]{}) &>::type;
	wrap w;
}
```

```cpp
export module g;

import e;
import f;
```

But instead clang gives this error while compiling `g.cpp`:

```console
In module 'e':
d.cpp:6:11: error: 'd<int>::d' from module 'd' is not present in definition of 'd<int>' in module 'd'
        explicit d(int) requires(true) {}
                 ^
d.cpp:5:2: note: declaration of 'd' does not match
        d() {}
        ^
d.cpp:6:11: note: declaration of 'd' does not match
        explicit d(int) requires(true) {}
                 ^
d.cpp:7:2: note: declaration of 'd' does not match
        d(auto &&) {}
        ^
d.cpp:4:8: note: declaration of 'd' does not match
struct d {
       ^
d.cpp:4:8: note: declaration of 'd' does not match
1 error generated.
```

**Comment by ChuanqiXu9** [comment] 2023-01-16 07:09
I failed to reproduce this on trunk. What is the compiler you're using? Or would you like to provide the full command line flags?

**Comment by ChuanqiXu9** [comment] 2023-02-03 06:21
I'll close this one since I can't reproduce it. Feel free to reopen it if the bug still exists.

**Closed by ChuanqiXu9** 2023-02-03 06:21 UTC
Labels: clang:modules
