### ISSUE TITLE
Clang bug with handling of pointers to VLAs

### ISSUE THREAD

**Issue by jeremy-rifkin** [llvm/llvm-project#55968] opened 2022-06-09 23:46 UTC
```cpp
void foo(int* ptr, int n) {
    int(*arr)[n] = (int(*)[n])ptr;
}
```
https://godbolt.org/z/zf8E1cbar

This code is accepted by gcc but not clang:

```cpp
<source>:2:10: error: cannot initialize a variable of type 'int (*)[n]' with an rvalue of type 'int (*)[n]'
    int(*arr)[n] = (int(*)[n])ptr;
         ^         ~~~~~~~~~~~~~~
```

The code compiles fine in C mode.

**Comment by efriedma-quic** [comment] 2022-06-09 23:56
Duplicate of #35229.

**Closed by efriedma-quic** 2022-06-09 23:56 UTC
Labels: new issue
